// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 4
//===- aie-upd-ext-intrinsic.cpp -------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//

// RUN: %clang -O2 %s --target=aie2p -nostdlibinc -S -emit-llvm -o - | FileCheck %s -check-prefixes=CHECK,CHECK-AIE2P
// RUN: %clang -O2 %s --target=aie2ps -nostdlibinc -S -emit-llvm -o - | FileCheck %s -check-prefixes=CHECK,CHECK-AIE2PS

  // Small vector datatypes
// CHECK-LABEL: define dso_local noundef i32 @_Z12test_set_w32ijjij(
// CHECK-SAME: i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]], i32 noundef [[ELEMS:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[ELEM_MASK:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB_I:%.*]] = add i32 [[ELEMS]], -1
// CHECK-NEXT:    [[AND_I:%.*]] = and i32 [[SUB_I]], [[IDX]]
// CHECK-NEXT:    [[AND1_I:%.*]] = and i32 [[ELEM_MASK]], [[VAL]]
// CHECK-NEXT:    [[MUL_I:%.*]] = mul nsw i32 [[AND_I]], [[STEP]]
// CHECK-NEXT:    [[SHL_I:%.*]] = shl i32 [[AND1_I]], [[MUL_I]]
// CHECK-NEXT:    ret i32 [[SHL_I]]
//
  unsigned int test_set_w32(int idx, unsigned int val, unsigned int elems, int step, unsigned int elem_mask)
  {
    return set_w32(idx, val, elems, step, elem_mask);
  }
// CHECK-LABEL: define dso_local noundef <2 x i32> @_Z12test_set_w64ijjij(
// CHECK-SAME: i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]], i32 noundef [[ELEMS:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[ELEM_MASK:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB_I:%.*]] = add i32 [[ELEMS]], -1
// CHECK-NEXT:    [[AND_I:%.*]] = and i32 [[SUB_I]], [[IDX]]
// CHECK-NEXT:    [[AND1_I:%.*]] = and i32 [[ELEM_MASK]], [[VAL]]
// CHECK-NEXT:    [[CONV_I:%.*]] = zext i32 [[AND1_I]] to i64
// CHECK-NEXT:    [[MUL_I:%.*]] = mul nsw i32 [[AND_I]], [[STEP]]
// CHECK-NEXT:    [[SH_PROM_I:%.*]] = zext nneg i32 [[MUL_I]] to i64
// CHECK-NEXT:    [[SHL_I:%.*]] = shl i64 [[CONV_I]], [[SH_PROM_I]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i64 [[SHL_I]] to <2 x i32>
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
  mask64 test_set_w64(int idx, unsigned int val, unsigned int elems, int step, unsigned int elem_mask)
  {
    return set_w64(idx, val, elems, step, elem_mask);
  }
// CHECK-LABEL: define dso_local noundef i32 @_Z12test_upd_w32jijjij(
// CHECK-SAME: i32 noundef [[A:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]], i32 noundef [[ELEMS:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[ELEM_MASK:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB_I:%.*]] = add i32 [[ELEMS]], -1
// CHECK-NEXT:    [[AND_I:%.*]] = and i32 [[SUB_I]], [[IDX]]
// CHECK-NEXT:    [[MUL_I:%.*]] = mul nsw i32 [[AND_I]], [[STEP]]
// CHECK-NEXT:    [[SHL_I:%.*]] = shl i32 [[ELEM_MASK]], [[MUL_I]]
// CHECK-NEXT:    [[NOT_I:%.*]] = xor i32 [[SHL_I]], -1
// CHECK-NEXT:    [[AND1_I:%.*]] = and i32 [[A]], [[NOT_I]]
// CHECK-NEXT:    [[AND2_I:%.*]] = and i32 [[ELEM_MASK]], [[VAL]]
// CHECK-NEXT:    [[SHL4_I:%.*]] = shl i32 [[AND2_I]], [[MUL_I]]
// CHECK-NEXT:    [[OR_I:%.*]] = or i32 [[AND1_I]], [[SHL4_I]]
// CHECK-NEXT:    ret i32 [[OR_I]]
//
  unsigned int test_upd_w32(unsigned int a, int idx, unsigned int val, unsigned int elems, int step, unsigned int elem_mask)
  {
    return upd_w32(a, idx, val, elems, step, elem_mask);
  }
// CHECK-LABEL: define dso_local noundef <2 x i32> @_Z12test_upd_w64Dv2_jijjij(
// CHECK-SAME: <2 x i32> noundef [[A_:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]], i32 noundef [[ELEMS:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[ELEM_MASK:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i32> [[A_]] to i64
// CHECK-NEXT:    [[SUB_I:%.*]] = add i32 [[ELEMS]], -1
// CHECK-NEXT:    [[AND_I:%.*]] = and i32 [[SUB_I]], [[IDX]]
// CHECK-NEXT:    [[CONV_I:%.*]] = zext i32 [[ELEM_MASK]] to i64
// CHECK-NEXT:    [[MUL_I:%.*]] = mul nsw i32 [[AND_I]], [[STEP]]
// CHECK-NEXT:    [[SH_PROM_I:%.*]] = zext i32 [[MUL_I]] to i64
// CHECK-NEXT:    [[SHL_I:%.*]] = shl i64 [[CONV_I]], [[SH_PROM_I]]
// CHECK-NEXT:    [[NOT_I:%.*]] = xor i64 [[SHL_I]], -1
// CHECK-NEXT:    [[AND1_I:%.*]] = and i64 [[NOT_I]], [[TMP0]]
// CHECK-NEXT:    [[AND2_I:%.*]] = and i32 [[ELEM_MASK]], [[VAL]]
// CHECK-NEXT:    [[CONV3_I:%.*]] = zext i32 [[AND2_I]] to i64
// CHECK-NEXT:    [[SHL6_I:%.*]] = shl i64 [[CONV3_I]], [[SH_PROM_I]]
// CHECK-NEXT:    [[OR_I:%.*]] = or i64 [[AND1_I]], [[SHL6_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64 [[OR_I]] to <2 x i32>
// CHECK-NEXT:    ret <2 x i32> [[TMP1]]
//
  mask64 test_upd_w64(mask64 a_, int idx, unsigned int val, unsigned int elems, int step, unsigned int elem_mask)
  {
    return upd_w64(a_, idx, val, elems, step, elem_mask);
  }

// CHECK-LABEL: define dso_local noundef i32 @_Z12test_ext_w32iijij(
// CHECK-SAME: i32 noundef [[A:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[ELEMS:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[ELEM_MASK:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB_I:%.*]] = add i32 [[ELEMS]], -1
// CHECK-NEXT:    [[AND_I:%.*]] = and i32 [[SUB_I]], [[IDX]]
// CHECK-NEXT:    [[ADD_NEG_I:%.*]] = xor i32 [[AND_I]], -1
// CHECK-NEXT:    [[MUL_NEG_I:%.*]] = mul i32 [[STEP]], [[ADD_NEG_I]]
// CHECK-NEXT:    [[SUB1_I:%.*]] = add i32 [[MUL_NEG_I]], 32
// CHECK-NEXT:    [[SHL_I:%.*]] = shl i32 [[A]], [[SUB1_I]]
// CHECK-NEXT:    [[SUB2_I:%.*]] = sub nsw i32 32, [[STEP]]
// CHECK-NEXT:    [[SHR_I:%.*]] = ashr i32 [[SHL_I]], [[SUB2_I]]
// CHECK-NEXT:    ret i32 [[SHR_I]]
//
  int test_ext_w32(int a, int idx, unsigned int elems, int step, unsigned int elem_mask)
  {
    return ext_w32(a, idx, elems, step, elem_mask);
  }
// CHECK-LABEL: define dso_local noundef i32 @_Z12test_ext_w64Dv2_jijij(
// CHECK-SAME: <2 x i32> noundef [[A_:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[ELEMS:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[ELEM_MASK:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i32> [[A_]] to i64
// CHECK-NEXT:    [[SUB_I:%.*]] = add i32 [[ELEMS]], -1
// CHECK-NEXT:    [[AND_I:%.*]] = and i32 [[SUB_I]], [[IDX]]
// CHECK-NEXT:    [[MUL_I:%.*]] = mul nsw i32 [[AND_I]], [[STEP]]
// CHECK-NEXT:    [[SH_PROM_I:%.*]] = zext nneg i32 [[MUL_I]] to i64
// CHECK-NEXT:    [[SHR_I:%.*]] = lshr i64 [[TMP0]], [[SH_PROM_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = trunc i64 [[SHR_I]] to i32
// CHECK-NEXT:    [[VECEXT_I:%.*]] = and i32 [[ELEM_MASK]], [[TMP1]]
// CHECK-NEXT:    ret i32 [[VECEXT_I]]
//
  int test_ext_w64(mask64 a_, int idx, unsigned int elems, int step, unsigned int elem_mask)
  {
    return ext_w64(a_, idx, elems, step, elem_mask);
  }
// CHECK-LABEL: define dso_local noundef i32 @_Z12test_ext_u32jijij(
// CHECK-SAME: i32 noundef [[A:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[ELEMS:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[ELEM_MASK:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB_I:%.*]] = add i32 [[ELEMS]], -1
// CHECK-NEXT:    [[AND_I:%.*]] = and i32 [[SUB_I]], [[IDX]]
// CHECK-NEXT:    [[MUL_I:%.*]] = mul nsw i32 [[AND_I]], [[STEP]]
// CHECK-NEXT:    [[SHR_I:%.*]] = lshr i32 [[A]], [[MUL_I]]
// CHECK-NEXT:    [[AND1_I:%.*]] = and i32 [[SHR_I]], [[ELEM_MASK]]
// CHECK-NEXT:    ret i32 [[AND1_I]]
//
  unsigned int test_ext_u32(unsigned int a, int idx, unsigned int elems, int step, unsigned int elem_mask)
  {
    return ext_u32(a, idx, elems, step, elem_mask);
  }
// CHECK-LABEL: define dso_local noundef <2 x i32> @_Z12test_ext_u64Dv2_jijij(
// CHECK-SAME: <2 x i32> noundef [[A_:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[ELEMS:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[ELEM_MASK:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i32> [[A_]] to i64
// CHECK-NEXT:    [[SUB_I:%.*]] = add i32 [[ELEMS]], -1
// CHECK-NEXT:    [[AND_I:%.*]] = and i32 [[SUB_I]], [[IDX]]
// CHECK-NEXT:    [[MUL_I:%.*]] = mul nsw i32 [[AND_I]], [[STEP]]
// CHECK-NEXT:    [[SH_PROM_I:%.*]] = zext nneg i32 [[MUL_I]] to i64
// CHECK-NEXT:    [[SHR_I:%.*]] = lshr i64 [[TMP0]], [[SH_PROM_I]]
// CHECK-NEXT:    [[CONV_I:%.*]] = zext i32 [[ELEM_MASK]] to i64
// CHECK-NEXT:    [[AND1_I:%.*]] = and i64 [[SHR_I]], [[CONV_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64 [[AND1_I]] to <2 x i32>
// CHECK-NEXT:    ret <2 x i32> [[TMP1]]
//
  mask64 test_ext_u64(mask64 a_, int idx, unsigned int elems, int step, unsigned int elem_mask)
  {
    return ext_u64(a_, idx, elems, step, elem_mask);
  }

// CHECK-LABEL: define dso_local noundef range(i32 0, 241) i32 @_Z13test_set_v2w4ij(
// CHECK-SAME: i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND1_I_I:%.*]] = and i32 [[VAL]], 15
// CHECK-NEXT:    [[AND_I_I:%.*]] = shl i32 [[IDX]], 2
// CHECK-NEXT:    [[MUL_I_I:%.*]] = and i32 [[AND_I_I]], 4
// CHECK-NEXT:    [[SHL_I_I:%.*]] = shl nuw nsw i32 [[AND1_I_I]], [[MUL_I_I]]
// CHECK-NEXT:    ret i32 [[SHL_I_I]]
//
  unsigned int test_set_v2w4(int idx, unsigned int val)
  {
    return set_v2w4(idx, val);
  }
// CHECK-LABEL: define dso_local noundef range(i32 0, 61441) i32 @_Z13test_set_v4w4ij(
// CHECK-SAME: i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND1_I_I:%.*]] = and i32 [[VAL]], 15
// CHECK-NEXT:    [[AND_I_I:%.*]] = shl i32 [[IDX]], 2
// CHECK-NEXT:    [[MUL_I_I:%.*]] = and i32 [[AND_I_I]], 12
// CHECK-NEXT:    [[SHL_I_I:%.*]] = shl nuw nsw i32 [[AND1_I_I]], [[MUL_I_I]]
// CHECK-NEXT:    ret i32 [[SHL_I_I]]
//
  unsigned int test_set_v4w4(int idx, unsigned int val)
  {
     return set_v4w4(idx, val);
  }
// CHECK-LABEL: define dso_local noundef range(i32 0, -268435455) i32 @_Z13test_set_v8w4ij(
// CHECK-SAME: i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND1_I_I:%.*]] = and i32 [[VAL]], 15
// CHECK-NEXT:    [[AND_I_I:%.*]] = shl i32 [[IDX]], 2
// CHECK-NEXT:    [[MUL_I_I:%.*]] = and i32 [[AND_I_I]], 28
// CHECK-NEXT:    [[SHL_I_I:%.*]] = shl nuw i32 [[AND1_I_I]], [[MUL_I_I]]
// CHECK-NEXT:    ret i32 [[SHL_I_I]]
//
  unsigned int test_set_v8w4(int idx, unsigned int val)
  {
     return set_v8w4(idx, val);
  }
// CHECK-LABEL: define dso_local noundef <2 x i32> @_Z14test_set_v16w4ij(
// CHECK-SAME: i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND1_I_I:%.*]] = and i32 [[VAL]], 15
// CHECK-NEXT:    [[CONV_I_I:%.*]] = zext nneg i32 [[AND1_I_I]] to i64
// CHECK-NEXT:    [[AND_I_I:%.*]] = shl i32 [[IDX]], 2
// CHECK-NEXT:    [[MUL_I_I:%.*]] = and i32 [[AND_I_I]], 60
// CHECK-NEXT:    [[SH_PROM_I_I:%.*]] = zext nneg i32 [[MUL_I_I]] to i64
// CHECK-NEXT:    [[SHL_I_I:%.*]] = shl nuw i64 [[CONV_I_I]], [[SH_PROM_I_I]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i64 [[SHL_I_I]] to <2 x i32>
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
  mask64  test_set_v16w4(int idx, unsigned int val)
  {
     return set_v16w4(idx, val);
  }
// CHECK-LABEL: define dso_local noundef range(i32 0, 65281) i32 @_Z13test_set_v2w8ij(
// CHECK-SAME: i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND1_I_I:%.*]] = and i32 [[VAL]], 255
// CHECK-NEXT:    [[AND_I_I:%.*]] = shl i32 [[IDX]], 3
// CHECK-NEXT:    [[MUL_I_I:%.*]] = and i32 [[AND_I_I]], 8
// CHECK-NEXT:    [[SHL_I_I:%.*]] = shl nuw nsw i32 [[AND1_I_I]], [[MUL_I_I]]
// CHECK-NEXT:    ret i32 [[SHL_I_I]]
//
  unsigned int test_set_v2w8(int idx, unsigned int val)
  {
     return set_v2w8(idx, val);
  }
// CHECK-LABEL: define dso_local noundef range(i32 0, -16777215) i32 @_Z13test_set_v4w8ij(
// CHECK-SAME: i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND1_I_I:%.*]] = and i32 [[VAL]], 255
// CHECK-NEXT:    [[AND_I_I:%.*]] = shl i32 [[IDX]], 3
// CHECK-NEXT:    [[MUL_I_I:%.*]] = and i32 [[AND_I_I]], 24
// CHECK-NEXT:    [[SHL_I_I:%.*]] = shl nuw i32 [[AND1_I_I]], [[MUL_I_I]]
// CHECK-NEXT:    ret i32 [[SHL_I_I]]
//
  unsigned int test_set_v4w8(int idx, unsigned int val)
  {
    return set_v4w8(idx, val);
  }
// CHECK-LABEL: define dso_local noundef <2 x i32> @_Z13test_set_v8w8ij(
// CHECK-SAME: i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND1_I_I:%.*]] = and i32 [[VAL]], 255
// CHECK-NEXT:    [[CONV_I_I:%.*]] = zext nneg i32 [[AND1_I_I]] to i64
// CHECK-NEXT:    [[AND_I_I:%.*]] = shl i32 [[IDX]], 3
// CHECK-NEXT:    [[MUL_I_I:%.*]] = and i32 [[AND_I_I]], 56
// CHECK-NEXT:    [[SH_PROM_I_I:%.*]] = zext nneg i32 [[MUL_I_I]] to i64
// CHECK-NEXT:    [[SHL_I_I:%.*]] = shl nuw i64 [[CONV_I_I]], [[SH_PROM_I_I]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i64 [[SHL_I_I]] to <2 x i32>
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
  mask64  test_set_v8w8(int idx, unsigned int val)
  {
    return set_v8w8(idx, val);
  }
// CHECK-LABEL: define dso_local noundef range(i32 0, -65535) i32 @_Z14test_set_v2w16ij(
// CHECK-SAME: i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND1_I_I:%.*]] = and i32 [[VAL]], 65535
// CHECK-NEXT:    [[AND_I_I:%.*]] = shl i32 [[IDX]], 4
// CHECK-NEXT:    [[MUL_I_I:%.*]] = and i32 [[AND_I_I]], 16
// CHECK-NEXT:    [[SHL_I_I:%.*]] = shl nuw i32 [[AND1_I_I]], [[MUL_I_I]]
// CHECK-NEXT:    ret i32 [[SHL_I_I]]
//
  unsigned int test_set_v2w16(int idx, unsigned int val)
  {
    return set_v2w16(idx, val);
  }
// CHECK-LABEL: define dso_local noundef <2 x i32> @_Z14test_set_v4w16ij(
// CHECK-SAME: i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND1_I_I:%.*]] = and i32 [[VAL]], 65535
// CHECK-NEXT:    [[CONV_I_I:%.*]] = zext nneg i32 [[AND1_I_I]] to i64
// CHECK-NEXT:    [[AND_I_I:%.*]] = shl i32 [[IDX]], 4
// CHECK-NEXT:    [[MUL_I_I:%.*]] = and i32 [[AND_I_I]], 48
// CHECK-NEXT:    [[SH_PROM_I_I:%.*]] = zext nneg i32 [[MUL_I_I]] to i64
// CHECK-NEXT:    [[SHL_I_I:%.*]] = shl nuw i64 [[CONV_I_I]], [[SH_PROM_I_I]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i64 [[SHL_I_I]] to <2 x i32>
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
  mask64  test_set_v4w16(int idx, unsigned int val)
  {
    return set_v4w16(idx, val);
  }
// CHECK-LABEL: define dso_local noundef <2 x i32> @_Z14test_set_v2w32ij(
// CHECK-SAME: i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CONV_I_I:%.*]] = zext i32 [[VAL]] to i64
// CHECK-NEXT:    [[AND_I_I:%.*]] = shl i32 [[IDX]], 5
// CHECK-NEXT:    [[MUL_I_I:%.*]] = and i32 [[AND_I_I]], 32
// CHECK-NEXT:    [[SH_PROM_I_I:%.*]] = zext nneg i32 [[MUL_I_I]] to i64
// CHECK-NEXT:    [[SHL_I_I:%.*]] = shl nuw i64 [[CONV_I_I]], [[SH_PROM_I_I]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i64 [[SHL_I_I]] to <2 x i32>
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
  mask64  test_set_v2w32(int idx, unsigned int val)
  {
    return set_v2w32(idx, val);
  }
// CHECK-LABEL: define dso_local noundef i32 @_Z13test_upd_v2w4jij(
// CHECK-SAME: i32 noundef [[A:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND_I_I:%.*]] = shl i32 [[IDX]], 2
// CHECK-NEXT:    [[MUL_I_I:%.*]] = and i32 [[AND_I_I]], 4
// CHECK-NEXT:    [[SHL_I_I:%.*]] = shl nuw nsw i32 15, [[MUL_I_I]]
// CHECK-NEXT:    [[NOT_I_I:%.*]] = xor i32 [[SHL_I_I]], -1
// CHECK-NEXT:    [[AND1_I_I:%.*]] = and i32 [[A]], [[NOT_I_I]]
// CHECK-NEXT:    [[AND2_I_I:%.*]] = and i32 [[VAL]], 15
// CHECK-NEXT:    [[SHL4_I_I:%.*]] = shl nuw nsw i32 [[AND2_I_I]], [[MUL_I_I]]
// CHECK-NEXT:    [[OR_I_I:%.*]] = or i32 [[AND1_I_I]], [[SHL4_I_I]]
// CHECK-NEXT:    ret i32 [[OR_I_I]]
//
  unsigned int test_upd_v2w4(unsigned int a, int idx, unsigned int val)
  {
    return upd_v2w4(a, idx, val);
  }
// CHECK-LABEL: define dso_local noundef i32 @_Z13test_upd_v4w4jij(
// CHECK-SAME: i32 noundef [[A:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND_I_I:%.*]] = shl i32 [[IDX]], 2
// CHECK-NEXT:    [[MUL_I_I:%.*]] = and i32 [[AND_I_I]], 12
// CHECK-NEXT:    [[SHL_I_I:%.*]] = shl nuw nsw i32 15, [[MUL_I_I]]
// CHECK-NEXT:    [[NOT_I_I:%.*]] = xor i32 [[SHL_I_I]], -1
// CHECK-NEXT:    [[AND1_I_I:%.*]] = and i32 [[A]], [[NOT_I_I]]
// CHECK-NEXT:    [[AND2_I_I:%.*]] = and i32 [[VAL]], 15
// CHECK-NEXT:    [[SHL4_I_I:%.*]] = shl nuw nsw i32 [[AND2_I_I]], [[MUL_I_I]]
// CHECK-NEXT:    [[OR_I_I:%.*]] = or i32 [[AND1_I_I]], [[SHL4_I_I]]
// CHECK-NEXT:    ret i32 [[OR_I_I]]
//
  unsigned int test_upd_v4w4(unsigned int a, int idx, unsigned int val)
  {
    return upd_v4w4(a, idx, val);
  }
// CHECK-LABEL: define dso_local noundef i32 @_Z13test_upd_v8w4jij(
// CHECK-SAME: i32 noundef [[A:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND_I_I:%.*]] = shl i32 [[IDX]], 2
// CHECK-NEXT:    [[MUL_I_I:%.*]] = and i32 [[AND_I_I]], 28
// CHECK-NEXT:    [[SHL_I_I:%.*]] = shl nuw i32 15, [[MUL_I_I]]
// CHECK-NEXT:    [[NOT_I_I:%.*]] = xor i32 [[SHL_I_I]], -1
// CHECK-NEXT:    [[AND1_I_I:%.*]] = and i32 [[A]], [[NOT_I_I]]
// CHECK-NEXT:    [[AND2_I_I:%.*]] = and i32 [[VAL]], 15
// CHECK-NEXT:    [[SHL4_I_I:%.*]] = shl nuw i32 [[AND2_I_I]], [[MUL_I_I]]
// CHECK-NEXT:    [[OR_I_I:%.*]] = or i32 [[AND1_I_I]], [[SHL4_I_I]]
// CHECK-NEXT:    ret i32 [[OR_I_I]]
//
  unsigned int test_upd_v8w4(unsigned int a, int idx, unsigned int val)
  {
    return upd_v8w4(a, idx, val);
  }
// CHECK-LABEL: define dso_local noundef <2 x i32> @_Z14test_upd_v16w4Dv2_jij(
// CHECK-SAME: <2 x i32> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i32> [[A]] to i64
// CHECK-NEXT:    [[AND_I_I:%.*]] = shl i32 [[IDX]], 2
// CHECK-NEXT:    [[MUL_I_I:%.*]] = and i32 [[AND_I_I]], 60
// CHECK-NEXT:    [[SH_PROM_I_I:%.*]] = zext nneg i32 [[MUL_I_I]] to i64
// CHECK-NEXT:    [[SHL_I_I:%.*]] = shl nuw i64 15, [[SH_PROM_I_I]]
// CHECK-NEXT:    [[NOT_I_I:%.*]] = xor i64 [[SHL_I_I]], -1
// CHECK-NEXT:    [[AND1_I_I:%.*]] = and i64 [[NOT_I_I]], [[TMP0]]
// CHECK-NEXT:    [[AND2_I_I:%.*]] = and i32 [[VAL]], 15
// CHECK-NEXT:    [[CONV3_I_I:%.*]] = zext nneg i32 [[AND2_I_I]] to i64
// CHECK-NEXT:    [[SHL6_I_I:%.*]] = shl nuw i64 [[CONV3_I_I]], [[SH_PROM_I_I]]
// CHECK-NEXT:    [[OR_I_I:%.*]] = or i64 [[AND1_I_I]], [[SHL6_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64 [[OR_I_I]] to <2 x i32>
// CHECK-NEXT:    ret <2 x i32> [[TMP1]]
//
  mask64 test_upd_v16w4(mask64       a, int idx, unsigned int val)
  {
    return upd_v16w4(a, idx, val);
  }
// CHECK-LABEL: define dso_local noundef i32 @_Z13test_upd_v2w8jij(
// CHECK-SAME: i32 noundef [[A:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND_I_I:%.*]] = shl i32 [[IDX]], 3
// CHECK-NEXT:    [[MUL_I_I:%.*]] = and i32 [[AND_I_I]], 8
// CHECK-NEXT:    [[SHL_I_I:%.*]] = shl nuw nsw i32 255, [[MUL_I_I]]
// CHECK-NEXT:    [[NOT_I_I:%.*]] = xor i32 [[SHL_I_I]], -1
// CHECK-NEXT:    [[AND1_I_I:%.*]] = and i32 [[A]], [[NOT_I_I]]
// CHECK-NEXT:    [[AND2_I_I:%.*]] = and i32 [[VAL]], 255
// CHECK-NEXT:    [[SHL4_I_I:%.*]] = shl nuw nsw i32 [[AND2_I_I]], [[MUL_I_I]]
// CHECK-NEXT:    [[OR_I_I:%.*]] = or i32 [[AND1_I_I]], [[SHL4_I_I]]
// CHECK-NEXT:    ret i32 [[OR_I_I]]
//
  unsigned int test_upd_v2w8(unsigned int a, int idx, unsigned int val)
  {
    return upd_v2w8(a, idx, val);
  }
// CHECK-LABEL: define dso_local noundef i32 @_Z13test_upd_v4w8jij(
// CHECK-SAME: i32 noundef [[A:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND_I_I:%.*]] = shl i32 [[IDX]], 3
// CHECK-NEXT:    [[MUL_I_I:%.*]] = and i32 [[AND_I_I]], 24
// CHECK-NEXT:    [[SHL_I_I:%.*]] = shl nuw i32 255, [[MUL_I_I]]
// CHECK-NEXT:    [[NOT_I_I:%.*]] = xor i32 [[SHL_I_I]], -1
// CHECK-NEXT:    [[AND1_I_I:%.*]] = and i32 [[A]], [[NOT_I_I]]
// CHECK-NEXT:    [[AND2_I_I:%.*]] = and i32 [[VAL]], 255
// CHECK-NEXT:    [[SHL4_I_I:%.*]] = shl nuw i32 [[AND2_I_I]], [[MUL_I_I]]
// CHECK-NEXT:    [[OR_I_I:%.*]] = or i32 [[AND1_I_I]], [[SHL4_I_I]]
// CHECK-NEXT:    ret i32 [[OR_I_I]]
//
  unsigned int test_upd_v4w8(unsigned int a, int idx, unsigned int val)
  {
    return upd_v4w8(a, idx, val);
  }
// CHECK-LABEL: define dso_local noundef <2 x i32> @_Z13test_upd_v8w8Dv2_jij(
// CHECK-SAME: <2 x i32> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i32> [[A]] to i64
// CHECK-NEXT:    [[AND_I_I:%.*]] = shl i32 [[IDX]], 3
// CHECK-NEXT:    [[MUL_I_I:%.*]] = and i32 [[AND_I_I]], 56
// CHECK-NEXT:    [[SH_PROM_I_I:%.*]] = zext nneg i32 [[MUL_I_I]] to i64
// CHECK-NEXT:    [[SHL_I_I:%.*]] = shl nuw i64 255, [[SH_PROM_I_I]]
// CHECK-NEXT:    [[NOT_I_I:%.*]] = xor i64 [[SHL_I_I]], -1
// CHECK-NEXT:    [[AND1_I_I:%.*]] = and i64 [[NOT_I_I]], [[TMP0]]
// CHECK-NEXT:    [[AND2_I_I:%.*]] = and i32 [[VAL]], 255
// CHECK-NEXT:    [[CONV3_I_I:%.*]] = zext nneg i32 [[AND2_I_I]] to i64
// CHECK-NEXT:    [[SHL6_I_I:%.*]] = shl nuw i64 [[CONV3_I_I]], [[SH_PROM_I_I]]
// CHECK-NEXT:    [[OR_I_I:%.*]] = or i64 [[AND1_I_I]], [[SHL6_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64 [[OR_I_I]] to <2 x i32>
// CHECK-NEXT:    ret <2 x i32> [[TMP1]]
//
  mask64 test_upd_v8w8(mask64       a, int idx, unsigned int val)
  {
    return upd_v8w8(a, idx, val);
  }
// CHECK-LABEL: define dso_local noundef i32 @_Z14test_upd_v2w16jij(
// CHECK-SAME: i32 noundef [[A:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND_I_I:%.*]] = shl i32 [[IDX]], 4
// CHECK-NEXT:    [[MUL_I_I:%.*]] = and i32 [[AND_I_I]], 16
// CHECK-NEXT:    [[SHL_I_I:%.*]] = shl nuw i32 65535, [[MUL_I_I]]
// CHECK-NEXT:    [[NOT_I_I:%.*]] = xor i32 [[SHL_I_I]], -1
// CHECK-NEXT:    [[AND1_I_I:%.*]] = and i32 [[A]], [[NOT_I_I]]
// CHECK-NEXT:    [[AND2_I_I:%.*]] = and i32 [[VAL]], 65535
// CHECK-NEXT:    [[SHL4_I_I:%.*]] = shl nuw i32 [[AND2_I_I]], [[MUL_I_I]]
// CHECK-NEXT:    [[OR_I_I:%.*]] = or i32 [[AND1_I_I]], [[SHL4_I_I]]
// CHECK-NEXT:    ret i32 [[OR_I_I]]
//
  unsigned int test_upd_v2w16(unsigned int a, int idx, unsigned int val)
  {
    return upd_v2w16(a, idx, val);
  }
// CHECK-LABEL: define dso_local noundef <2 x i32> @_Z14test_upd_v4w16Dv2_jij(
// CHECK-SAME: <2 x i32> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i32> [[A]] to i64
// CHECK-NEXT:    [[AND_I_I:%.*]] = shl i32 [[IDX]], 4
// CHECK-NEXT:    [[MUL_I_I:%.*]] = and i32 [[AND_I_I]], 48
// CHECK-NEXT:    [[SH_PROM_I_I:%.*]] = zext nneg i32 [[MUL_I_I]] to i64
// CHECK-NEXT:    [[SHL_I_I:%.*]] = shl nuw i64 65535, [[SH_PROM_I_I]]
// CHECK-NEXT:    [[NOT_I_I:%.*]] = xor i64 [[SHL_I_I]], -1
// CHECK-NEXT:    [[AND1_I_I:%.*]] = and i64 [[NOT_I_I]], [[TMP0]]
// CHECK-NEXT:    [[AND2_I_I:%.*]] = and i32 [[VAL]], 65535
// CHECK-NEXT:    [[CONV3_I_I:%.*]] = zext nneg i32 [[AND2_I_I]] to i64
// CHECK-NEXT:    [[SHL6_I_I:%.*]] = shl nuw i64 [[CONV3_I_I]], [[SH_PROM_I_I]]
// CHECK-NEXT:    [[OR_I_I:%.*]] = or i64 [[AND1_I_I]], [[SHL6_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64 [[OR_I_I]] to <2 x i32>
// CHECK-NEXT:    ret <2 x i32> [[TMP1]]
//
  mask64 test_upd_v4w16(mask64       a, int idx, unsigned int val)
  {
    return upd_v4w16(a, idx, val);
  }
// CHECK-LABEL: define dso_local noundef <2 x i32> @_Z14test_upd_v2w32Dv2_jij(
// CHECK-SAME: <2 x i32> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i32> [[A]] to i64
// CHECK-NEXT:    [[AND_I_I:%.*]] = shl i32 [[IDX]], 5
// CHECK-NEXT:    [[MUL_I_I:%.*]] = and i32 [[AND_I_I]], 32
// CHECK-NEXT:    [[SH_PROM_I_I:%.*]] = zext nneg i32 [[MUL_I_I]] to i64
// CHECK-NEXT:    [[SHL_I_I:%.*]] = shl nuw i64 4294967295, [[SH_PROM_I_I]]
// CHECK-NEXT:    [[NOT_I_I:%.*]] = xor i64 [[SHL_I_I]], -1
// CHECK-NEXT:    [[AND1_I_I:%.*]] = and i64 [[NOT_I_I]], [[TMP0]]
// CHECK-NEXT:    [[CONV3_I_I:%.*]] = zext i32 [[VAL]] to i64
// CHECK-NEXT:    [[SHL6_I_I:%.*]] = shl nuw i64 [[CONV3_I_I]], [[SH_PROM_I_I]]
// CHECK-NEXT:    [[OR_I_I:%.*]] = or i64 [[AND1_I_I]], [[SHL6_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64 [[OR_I_I]] to <2 x i32>
// CHECK-NEXT:    ret <2 x i32> [[TMP1]]
//
  mask64 test_upd_v2w32(mask64       a, int idx, unsigned int val)
  {
    return upd_v2w32(a, idx, val);
  }
// CHECK-LABEL: define dso_local noundef range(i32 -8, 8) i32 @_Z13test_ext_v2w4ji(
// CHECK-SAME: i32 noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[ADD_NEG_I_I:%.*]] = xor i32 [[AND_I_I]], -1
// CHECK-NEXT:    [[MUL_NEG_I_I:%.*]] = shl nsw i32 [[ADD_NEG_I_I]], 2
// CHECK-NEXT:    [[SUB1_I_I:%.*]] = add nsw i32 [[MUL_NEG_I_I]], 32
// CHECK-NEXT:    [[SHL_I_I:%.*]] = shl i32 [[A]], [[SUB1_I_I]]
// CHECK-NEXT:    [[SHR_I_I:%.*]] = ashr i32 [[SHL_I_I]], 28
// CHECK-NEXT:    ret i32 [[SHR_I_I]]
//
  int test_ext_v2w4(unsigned int a, int idx)
  {
    return ext_v2w4(a, idx);
  }
// CHECK-LABEL: define dso_local noundef range(i32 -8, 8) i32 @_Z13test_ext_v4w4ji(
// CHECK-SAME: i32 noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 3
// CHECK-NEXT:    [[ADD_NEG_I_I:%.*]] = xor i32 [[AND_I_I]], -1
// CHECK-NEXT:    [[MUL_NEG_I_I:%.*]] = shl nsw i32 [[ADD_NEG_I_I]], 2
// CHECK-NEXT:    [[SUB1_I_I:%.*]] = add nsw i32 [[MUL_NEG_I_I]], 32
// CHECK-NEXT:    [[SHL_I_I:%.*]] = shl i32 [[A]], [[SUB1_I_I]]
// CHECK-NEXT:    [[SHR_I_I:%.*]] = ashr i32 [[SHL_I_I]], 28
// CHECK-NEXT:    ret i32 [[SHR_I_I]]
//
  int test_ext_v4w4(unsigned int a, int idx)
  {
    return ext_v4w4(a, idx);
  }
// CHECK-LABEL: define dso_local noundef range(i32 -8, 8) i32 @_Z13test_ext_v8w4ji(
// CHECK-SAME: i32 noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 7
// CHECK-NEXT:    [[ADD_NEG_I_I:%.*]] = xor i32 [[AND_I_I]], -1
// CHECK-NEXT:    [[MUL_NEG_I_I:%.*]] = shl nsw i32 [[ADD_NEG_I_I]], 2
// CHECK-NEXT:    [[SUB1_I_I:%.*]] = add nsw i32 [[MUL_NEG_I_I]], 32
// CHECK-NEXT:    [[SHL_I_I:%.*]] = shl i32 [[A]], [[SUB1_I_I]]
// CHECK-NEXT:    [[SHR_I_I:%.*]] = ashr i32 [[SHL_I_I]], 28
// CHECK-NEXT:    ret i32 [[SHR_I_I]]
//
  int test_ext_v8w4(unsigned int a, int idx)
  {
    return ext_v8w4(a, idx);
  }
// CHECK-LABEL: define dso_local noundef range(i32 0, 16) i32 @_Z14test_ext_v16w4Dv2_ji(
// CHECK-SAME: <2 x i32> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i32> [[A]] to i64
// CHECK-NEXT:    [[AND_I_I:%.*]] = shl i32 [[IDX]], 2
// CHECK-NEXT:    [[MUL_I_I:%.*]] = and i32 [[AND_I_I]], 60
// CHECK-NEXT:    [[SH_PROM_I_I:%.*]] = zext nneg i32 [[MUL_I_I]] to i64
// CHECK-NEXT:    [[SHR_I_I:%.*]] = lshr i64 [[TMP0]], [[SH_PROM_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = trunc i64 [[SHR_I_I]] to i32
// CHECK-NEXT:    [[VECEXT_I_I:%.*]] = and i32 [[TMP1]], 15
// CHECK-NEXT:    ret i32 [[VECEXT_I_I]]
//
  int test_ext_v16w4(mask64       a, int idx)
  {
    return ext_v16w4(a, idx);
  }
// CHECK-LABEL: define dso_local noundef range(i32 -128, 128) i32 @_Z13test_ext_v2w8ji(
// CHECK-SAME: i32 noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[ADD_NEG_I_I:%.*]] = xor i32 [[AND_I_I]], -1
// CHECK-NEXT:    [[MUL_NEG_I_I:%.*]] = shl nsw i32 [[ADD_NEG_I_I]], 3
// CHECK-NEXT:    [[SUB1_I_I:%.*]] = add nsw i32 [[MUL_NEG_I_I]], 32
// CHECK-NEXT:    [[SHL_I_I:%.*]] = shl i32 [[A]], [[SUB1_I_I]]
// CHECK-NEXT:    [[SHR_I_I:%.*]] = ashr i32 [[SHL_I_I]], 24
// CHECK-NEXT:    ret i32 [[SHR_I_I]]
//
  int test_ext_v2w8(unsigned int a, int idx)
  {
    return ext_v2w8(a, idx);
  }
// CHECK-LABEL: define dso_local noundef range(i32 -128, 128) i32 @_Z13test_ext_v4w8ji(
// CHECK-SAME: i32 noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 3
// CHECK-NEXT:    [[ADD_NEG_I_I:%.*]] = xor i32 [[AND_I_I]], -1
// CHECK-NEXT:    [[MUL_NEG_I_I:%.*]] = shl nsw i32 [[ADD_NEG_I_I]], 3
// CHECK-NEXT:    [[SUB1_I_I:%.*]] = add nsw i32 [[MUL_NEG_I_I]], 32
// CHECK-NEXT:    [[SHL_I_I:%.*]] = shl i32 [[A]], [[SUB1_I_I]]
// CHECK-NEXT:    [[SHR_I_I:%.*]] = ashr i32 [[SHL_I_I]], 24
// CHECK-NEXT:    ret i32 [[SHR_I_I]]
//
  int test_ext_v4w8(unsigned int a, int idx)
  {
    return ext_v4w8(a, idx);
  }
// CHECK-LABEL: define dso_local noundef range(i32 0, 256) i32 @_Z13test_ext_v8w8Dv2_ji(
// CHECK-SAME: <2 x i32> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i32> [[A]] to i64
// CHECK-NEXT:    [[AND_I_I:%.*]] = shl i32 [[IDX]], 3
// CHECK-NEXT:    [[MUL_I_I:%.*]] = and i32 [[AND_I_I]], 56
// CHECK-NEXT:    [[SH_PROM_I_I:%.*]] = zext nneg i32 [[MUL_I_I]] to i64
// CHECK-NEXT:    [[SHR_I_I:%.*]] = lshr i64 [[TMP0]], [[SH_PROM_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = trunc i64 [[SHR_I_I]] to i32
// CHECK-NEXT:    [[VECEXT_I_I:%.*]] = and i32 [[TMP1]], 255
// CHECK-NEXT:    ret i32 [[VECEXT_I_I]]
//
  int test_ext_v8w8(mask64       a, int idx)
  {
    return ext_v8w8(a, idx);
  }

// CHECK-LABEL: define dso_local noundef range(i32 -32768, 32768) i32 @_Z14test_ext_v2w16ji(
// CHECK-SAME: i32 noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[ADD_NEG_I_I:%.*]] = xor i32 [[AND_I_I]], -1
// CHECK-NEXT:    [[MUL_NEG_I_I:%.*]] = shl nsw i32 [[ADD_NEG_I_I]], 4
// CHECK-NEXT:    [[SUB1_I_I:%.*]] = add nsw i32 [[MUL_NEG_I_I]], 32
// CHECK-NEXT:    [[SHL_I_I:%.*]] = shl i32 [[A]], [[SUB1_I_I]]
// CHECK-NEXT:    [[SHR_I_I:%.*]] = ashr i32 [[SHL_I_I]], 16
// CHECK-NEXT:    ret i32 [[SHR_I_I]]
//
  int test_ext_v2w16(unsigned int a, int idx)
  {
    return ext_v2w16(a, idx);
  }
// CHECK-LABEL: define dso_local noundef range(i32 0, 65536) i32 @_Z14test_ext_v4w16Dv2_ji(
// CHECK-SAME: <2 x i32> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i32> [[A]] to i64
// CHECK-NEXT:    [[AND_I_I:%.*]] = shl i32 [[IDX]], 4
// CHECK-NEXT:    [[MUL_I_I:%.*]] = and i32 [[AND_I_I]], 48
// CHECK-NEXT:    [[SH_PROM_I_I:%.*]] = zext nneg i32 [[MUL_I_I]] to i64
// CHECK-NEXT:    [[SHR_I_I:%.*]] = lshr i64 [[TMP0]], [[SH_PROM_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = trunc i64 [[SHR_I_I]] to i32
// CHECK-NEXT:    [[VECEXT_I_I:%.*]] = and i32 [[TMP1]], 65535
// CHECK-NEXT:    ret i32 [[VECEXT_I_I]]
//
  int test_ext_v4w16(mask64       a, int idx)
  {
    return ext_v4w16(a, idx);
  }
// CHECK-LABEL: define dso_local noundef i32 @_Z14test_ext_v2w32Dv2_ji(
// CHECK-SAME: <2 x i32> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i32> [[A]] to i64
// CHECK-NEXT:    [[AND_I_I:%.*]] = shl i32 [[IDX]], 5
// CHECK-NEXT:    [[MUL_I_I:%.*]] = and i32 [[AND_I_I]], 32
// CHECK-NEXT:    [[SH_PROM_I_I:%.*]] = zext nneg i32 [[MUL_I_I]] to i64
// CHECK-NEXT:    [[SHR_I_I:%.*]] = lshr i64 [[TMP0]], [[SH_PROM_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = trunc i64 [[SHR_I_I]] to i32
// CHECK-NEXT:    ret i32 [[TMP1]]
//
  int test_ext_v2w32(mask64       a, int idx)
  {
    return ext_v2w32(a, idx);
  }
// CHECK-LABEL: define dso_local noundef range(i32 0, 16) i32 @_Z13test_ext_v2u4ji(
// CHECK-SAME: i32 noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND_I_I:%.*]] = shl i32 [[IDX]], 2
// CHECK-NEXT:    [[MUL_I_I:%.*]] = and i32 [[AND_I_I]], 4
// CHECK-NEXT:    [[SHR_I_I:%.*]] = lshr i32 [[A]], [[MUL_I_I]]
// CHECK-NEXT:    [[AND1_I_I:%.*]] = and i32 [[SHR_I_I]], 15
// CHECK-NEXT:    ret i32 [[AND1_I_I]]
//
  unsigned int test_ext_v2u4(unsigned int a, int idx)
  {
    return ext_v2u4(a, idx);
  }
// CHECK-LABEL: define dso_local noundef range(i32 0, 16) i32 @_Z13test_ext_v4u4ji(
// CHECK-SAME: i32 noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND_I_I:%.*]] = shl i32 [[IDX]], 2
// CHECK-NEXT:    [[MUL_I_I:%.*]] = and i32 [[AND_I_I]], 12
// CHECK-NEXT:    [[SHR_I_I:%.*]] = lshr i32 [[A]], [[MUL_I_I]]
// CHECK-NEXT:    [[AND1_I_I:%.*]] = and i32 [[SHR_I_I]], 15
// CHECK-NEXT:    ret i32 [[AND1_I_I]]
//
  unsigned int test_ext_v4u4(unsigned int a, int idx)
  {
    return ext_v4u4(a, idx);
  }
// CHECK-LABEL: define dso_local noundef range(i32 0, 16) i32 @_Z13test_ext_v8u4ji(
// CHECK-SAME: i32 noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND_I_I:%.*]] = shl i32 [[IDX]], 2
// CHECK-NEXT:    [[MUL_I_I:%.*]] = and i32 [[AND_I_I]], 28
// CHECK-NEXT:    [[SHR_I_I:%.*]] = lshr i32 [[A]], [[MUL_I_I]]
// CHECK-NEXT:    [[AND1_I_I:%.*]] = and i32 [[SHR_I_I]], 15
// CHECK-NEXT:    ret i32 [[AND1_I_I]]
//
  unsigned int test_ext_v8u4(unsigned int a, int idx)
  {
    return ext_v8u4(a, idx);
  }
// CHECK-LABEL: define dso_local noundef range(i32 0, 16) i32 @_Z14test_ext_v16u4Dv2_ji(
// CHECK-SAME: <2 x i32> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i32> [[A]] to i64
// CHECK-NEXT:    [[AND_I_I:%.*]] = shl i32 [[IDX]], 2
// CHECK-NEXT:    [[MUL_I_I:%.*]] = and i32 [[AND_I_I]], 60
// CHECK-NEXT:    [[SH_PROM_I_I:%.*]] = zext nneg i32 [[MUL_I_I]] to i64
// CHECK-NEXT:    [[SHR_I_I:%.*]] = lshr i64 [[TMP0]], [[SH_PROM_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = trunc i64 [[SHR_I_I]] to i32
// CHECK-NEXT:    [[VECEXT_I:%.*]] = and i32 [[TMP1]], 15
// CHECK-NEXT:    ret i32 [[VECEXT_I]]
//
  unsigned int test_ext_v16u4(mask64       a, int idx)
  {
    return ext_v16u4(a, idx);
  }
// CHECK-LABEL: define dso_local noundef range(i32 0, 256) i32 @_Z13test_ext_v2u8ji(
// CHECK-SAME: i32 noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND_I_I:%.*]] = shl i32 [[IDX]], 3
// CHECK-NEXT:    [[MUL_I_I:%.*]] = and i32 [[AND_I_I]], 8
// CHECK-NEXT:    [[SHR_I_I:%.*]] = lshr i32 [[A]], [[MUL_I_I]]
// CHECK-NEXT:    [[AND1_I_I:%.*]] = and i32 [[SHR_I_I]], 255
// CHECK-NEXT:    ret i32 [[AND1_I_I]]
//
  unsigned int test_ext_v2u8(unsigned int a, int idx)
  {
    return ext_v2u8(a, idx);
  }
// CHECK-LABEL: define dso_local noundef range(i32 0, 256) i32 @_Z13test_ext_v4u8ji(
// CHECK-SAME: i32 noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND_I_I:%.*]] = shl i32 [[IDX]], 3
// CHECK-NEXT:    [[MUL_I_I:%.*]] = and i32 [[AND_I_I]], 24
// CHECK-NEXT:    [[SHR_I_I:%.*]] = lshr i32 [[A]], [[MUL_I_I]]
// CHECK-NEXT:    [[AND1_I_I:%.*]] = and i32 [[SHR_I_I]], 255
// CHECK-NEXT:    ret i32 [[AND1_I_I]]
//
  unsigned int test_ext_v4u8(unsigned int a, int idx)
  {
    return ext_v4u8(a, idx);
  }
// CHECK-LABEL: define dso_local noundef range(i32 0, 256) i32 @_Z13test_ext_v8u8Dv2_ji(
// CHECK-SAME: <2 x i32> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i32> [[A]] to i64
// CHECK-NEXT:    [[AND_I_I:%.*]] = shl i32 [[IDX]], 3
// CHECK-NEXT:    [[MUL_I_I:%.*]] = and i32 [[AND_I_I]], 56
// CHECK-NEXT:    [[SH_PROM_I_I:%.*]] = zext nneg i32 [[MUL_I_I]] to i64
// CHECK-NEXT:    [[SHR_I_I:%.*]] = lshr i64 [[TMP0]], [[SH_PROM_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = trunc i64 [[SHR_I_I]] to i32
// CHECK-NEXT:    [[VECEXT_I:%.*]] = and i32 [[TMP1]], 255
// CHECK-NEXT:    ret i32 [[VECEXT_I]]
//
  unsigned int test_ext_v8u8(mask64       a, int idx)
  {
    return ext_v8u8(a, idx);

  }
// CHECK-LABEL: define dso_local noundef range(i32 0, 65536) i32 @_Z14test_ext_v2u16ji(
// CHECK-SAME: i32 noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND_I_I:%.*]] = shl i32 [[IDX]], 4
// CHECK-NEXT:    [[MUL_I_I:%.*]] = and i32 [[AND_I_I]], 16
// CHECK-NEXT:    [[SHR_I_I:%.*]] = lshr i32 [[A]], [[MUL_I_I]]
// CHECK-NEXT:    [[AND1_I_I:%.*]] = and i32 [[SHR_I_I]], 65535
// CHECK-NEXT:    ret i32 [[AND1_I_I]]
//
  unsigned int test_ext_v2u16(unsigned int a, int idx)
  {
    return ext_v2u16(a, idx);
  }
// CHECK-LABEL: define dso_local noundef range(i32 0, 65536) i32 @_Z14test_ext_v4u16Dv2_ji(
// CHECK-SAME: <2 x i32> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i32> [[A]] to i64
// CHECK-NEXT:    [[AND_I_I:%.*]] = shl i32 [[IDX]], 4
// CHECK-NEXT:    [[MUL_I_I:%.*]] = and i32 [[AND_I_I]], 48
// CHECK-NEXT:    [[SH_PROM_I_I:%.*]] = zext nneg i32 [[MUL_I_I]] to i64
// CHECK-NEXT:    [[SHR_I_I:%.*]] = lshr i64 [[TMP0]], [[SH_PROM_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = trunc i64 [[SHR_I_I]] to i32
// CHECK-NEXT:    [[VECEXT_I:%.*]] = and i32 [[TMP1]], 65535
// CHECK-NEXT:    ret i32 [[VECEXT_I]]
//
  unsigned int test_ext_v4u16(mask64       a, int idx)
  {
    return ext_v4u16(a, idx);
  }
// CHECK-LABEL: define dso_local noundef i32 @_Z14test_ext_v2u32Dv2_ji(
// CHECK-SAME: <2 x i32> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i32> [[A]] to i64
// CHECK-NEXT:    [[AND_I_I:%.*]] = shl i32 [[IDX]], 5
// CHECK-NEXT:    [[MUL_I_I:%.*]] = and i32 [[AND_I_I]], 32
// CHECK-NEXT:    [[SH_PROM_I_I:%.*]] = zext nneg i32 [[MUL_I_I]] to i64
// CHECK-NEXT:    [[SHR_I_I:%.*]] = lshr i64 [[TMP0]], [[SH_PROM_I_I]]
// CHECK-NEXT:    [[VECEXT_I:%.*]] = trunc i64 [[SHR_I_I]] to i32
// CHECK-NEXT:    ret i32 [[VECEXT_I]]
//
  unsigned int test_ext_v2u32(mask64       a, int idx)
  {
    return ext_v2u32(a, idx);
  }

// CHECK-LABEL: define dso_local noundef signext range(i8 0, -15) i8 @_Z15test_set_v2int4ii(
// CHECK-SAME: i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[VAL]], 15
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 2
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 4
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw nsw i32 [[AND1_I_I_I]], [[MUL_I_I_I]]
// CHECK-NEXT:    [[CONV_I:%.*]] = trunc nuw i32 [[SHL_I_I_I]] to i8
// CHECK-NEXT:    ret i8 [[CONV_I]]
//
 v2int4 test_set_v2int4   (int idx, int val)
 {
    return set_v2int4(idx, val);
 }
// CHECK-LABEL: define dso_local noundef <2 x i8> @_Z15test_set_v4int4ii(
// CHECK-SAME: i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[VAL]], 15
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 2
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 12
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw nsw i32 [[AND1_I_I_I]], [[MUL_I_I_I]]
// CHECK-NEXT:    [[CONV_I:%.*]] = trunc nuw i32 [[SHL_I_I_I]] to i16
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i16 [[CONV_I]] to <2 x i8>
// CHECK-NEXT:    ret <2 x i8> [[TMP0]]
//
 v4int4 test_set_v4int4   (int idx, int val)
 {
    return set_v4int4(idx, val);
 }
// CHECK-LABEL: define dso_local noundef <4 x i8> @_Z15test_set_v8int4ii(
// CHECK-SAME: i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[VAL]], 15
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 2
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 28
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw i32 [[AND1_I_I_I]], [[MUL_I_I_I]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i32 [[SHL_I_I_I]] to <4 x i8>
// CHECK-NEXT:    ret <4 x i8> [[TMP0]]
//
 v8int4 test_set_v8int4   (int idx, int val)
 {
    return set_v8int4(idx, val);
 }
// CHECK-LABEL: define dso_local noundef <8 x i8> @_Z16test_set_v16int4ii(
// CHECK-SAME: i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[VAL]], 15
// CHECK-NEXT:    [[CONV_I_I_I:%.*]] = zext nneg i32 [[AND1_I_I_I]] to i64
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 2
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 60
// CHECK-NEXT:    [[SH_PROM_I_I_I:%.*]] = zext nneg i32 [[MUL_I_I_I]] to i64
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw i64 [[CONV_I_I_I]], [[SH_PROM_I_I_I]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i64 [[SHL_I_I_I]] to <8 x i8>
// CHECK-NEXT:    ret <8 x i8> [[TMP0]]
//
v16int4 test_set_v16int4  (int idx, int val)
 {
    return set_v16int4(idx, val);
 }
// CHECK-LABEL: define dso_local noundef <2 x i8> @_Z15test_set_v2int8ii(
// CHECK-SAME: i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[VAL]], 255
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 3
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 8
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw nsw i32 [[AND1_I_I_I]], [[MUL_I_I_I]]
// CHECK-NEXT:    [[CONV_I:%.*]] = trunc nuw i32 [[SHL_I_I_I]] to i16
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i16 [[CONV_I]] to <2 x i8>
// CHECK-NEXT:    ret <2 x i8> [[TMP0]]
//
v2int8 test_set_v2int8    (int idx, int val)
 {
    return set_v2int8(idx, val);
 }
// CHECK-LABEL: define dso_local noundef <4 x i8> @_Z15test_set_v4int8ii(
// CHECK-SAME: i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[VAL]], 255
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 3
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 24
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw i32 [[AND1_I_I_I]], [[MUL_I_I_I]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i32 [[SHL_I_I_I]] to <4 x i8>
// CHECK-NEXT:    ret <4 x i8> [[TMP0]]
//
v4int8 test_set_v4int8    (int idx, int val)
 {
    return set_v4int8(idx, val);
 }
// CHECK-LABEL: define dso_local noundef <8 x i8> @_Z15test_set_v8int8ii(
// CHECK-SAME: i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[VAL]], 255
// CHECK-NEXT:    [[CONV_I_I_I:%.*]] = zext nneg i32 [[AND1_I_I_I]] to i64
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 3
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 56
// CHECK-NEXT:    [[SH_PROM_I_I_I:%.*]] = zext nneg i32 [[MUL_I_I_I]] to i64
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw i64 [[CONV_I_I_I]], [[SH_PROM_I_I_I]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i64 [[SHL_I_I_I]] to <8 x i8>
// CHECK-NEXT:    ret <8 x i8> [[TMP0]]
//
v8int8 test_set_v8int8    (int idx, int val)
 {
    return set_v8int8(idx, val);
 }
// CHECK-LABEL: define dso_local noundef <2 x i16> @_Z16test_set_v2int16ii(
// CHECK-SAME: i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[VAL]], 65535
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 4
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 16
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw i32 [[AND1_I_I_I]], [[MUL_I_I_I]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i32 [[SHL_I_I_I]] to <2 x i16>
// CHECK-NEXT:    ret <2 x i16> [[TMP0]]
//
v2int16 test_set_v2int16  (int idx, int val)
 {
    return set_v2int16(idx, val);
 }
// CHECK-LABEL: define dso_local noundef <4 x i16> @_Z16test_set_v4int16ii(
// CHECK-SAME: i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[VAL]], 65535
// CHECK-NEXT:    [[CONV_I_I_I:%.*]] = zext nneg i32 [[AND1_I_I_I]] to i64
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 4
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 48
// CHECK-NEXT:    [[SH_PROM_I_I_I:%.*]] = zext nneg i32 [[MUL_I_I_I]] to i64
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw i64 [[CONV_I_I_I]], [[SH_PROM_I_I_I]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i64 [[SHL_I_I_I]] to <4 x i16>
// CHECK-NEXT:    ret <4 x i16> [[TMP0]]
//
v4int16 test_set_v4int16  (int idx, int val)
 {
    return set_v4int16(idx, val);
 }
// CHECK-LABEL: define dso_local noundef <2 x i32> @_Z16test_set_v2int32ii(
// CHECK-SAME: i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CONV_I_I_I:%.*]] = zext i32 [[VAL]] to i64
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 5
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 32
// CHECK-NEXT:    [[SH_PROM_I_I_I:%.*]] = zext nneg i32 [[MUL_I_I_I]] to i64
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw i64 [[CONV_I_I_I]], [[SH_PROM_I_I_I]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i64 [[SHL_I_I_I]] to <2 x i32>
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
v2int32 test_set_v2int32  (int idx, int val)
 {
    return set_v2int32(idx, val);
 }
// CHECK-LABEL: define dso_local noundef zeroext range(i8 0, -15) i8 @_Z16test_set_v2uint4ij(
// CHECK-SAME: i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[VAL]], 15
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 2
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 4
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw nsw i32 [[AND1_I_I_I]], [[MUL_I_I_I]]
// CHECK-NEXT:    [[CONV_I:%.*]] = trunc nuw i32 [[SHL_I_I_I]] to i8
// CHECK-NEXT:    ret i8 [[CONV_I]]
//
 v2uint4 test_set_v2uint4 (int idx, unsigned int val)
 {
    return set_v2uint4(idx, val);
 }
// CHECK-LABEL: define dso_local noundef <2 x i8> @_Z16test_set_v4uint4ij(
// CHECK-SAME: i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[VAL]], 15
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 2
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 12
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw nsw i32 [[AND1_I_I_I]], [[MUL_I_I_I]]
// CHECK-NEXT:    [[CONV_I:%.*]] = trunc nuw i32 [[SHL_I_I_I]] to i16
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i16 [[CONV_I]] to <2 x i8>
// CHECK-NEXT:    ret <2 x i8> [[TMP0]]
//
 v4uint4 test_set_v4uint4 (int idx, unsigned int val)
 {
    return set_v4uint4(idx, val);
 }
// CHECK-LABEL: define dso_local noundef <4 x i8> @_Z16test_set_v8uint4ij(
// CHECK-SAME: i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[VAL]], 15
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 2
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 28
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw i32 [[AND1_I_I_I]], [[MUL_I_I_I]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i32 [[SHL_I_I_I]] to <4 x i8>
// CHECK-NEXT:    ret <4 x i8> [[TMP0]]
//
 v8uint4 test_set_v8uint4 (int idx, unsigned int val)
 {
    return set_v8uint4(idx, val);
 }
// CHECK-LABEL: define dso_local noundef <8 x i8> @_Z17test_set_v16uint4ij(
// CHECK-SAME: i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[VAL]], 15
// CHECK-NEXT:    [[CONV_I_I_I:%.*]] = zext nneg i32 [[AND1_I_I_I]] to i64
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 2
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 60
// CHECK-NEXT:    [[SH_PROM_I_I_I:%.*]] = zext nneg i32 [[MUL_I_I_I]] to i64
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw i64 [[CONV_I_I_I]], [[SH_PROM_I_I_I]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i64 [[SHL_I_I_I]] to <8 x i8>
// CHECK-NEXT:    ret <8 x i8> [[TMP0]]
//
v16uint4 test_set_v16uint4(int idx, unsigned int val)
 {
    return set_v16uint4(idx, val);
 }
// CHECK-LABEL: define dso_local noundef <2 x i8> @_Z16test_set_v2uint8ij(
// CHECK-SAME: i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[VAL]], 255
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 3
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 8
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw nsw i32 [[AND1_I_I_I]], [[MUL_I_I_I]]
// CHECK-NEXT:    [[CONV_I:%.*]] = trunc nuw i32 [[SHL_I_I_I]] to i16
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i16 [[CONV_I]] to <2 x i8>
// CHECK-NEXT:    ret <2 x i8> [[TMP0]]
//
v2uint8 test_set_v2uint8  (int idx, unsigned int val)
 {
    return set_v2uint8(idx, val);
 }
// CHECK-LABEL: define dso_local noundef <4 x i8> @_Z16test_set_v4uint8ij(
// CHECK-SAME: i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[VAL]], 255
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 3
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 24
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw i32 [[AND1_I_I_I]], [[MUL_I_I_I]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i32 [[SHL_I_I_I]] to <4 x i8>
// CHECK-NEXT:    ret <4 x i8> [[TMP0]]
//
v4uint8 test_set_v4uint8  (int idx, unsigned int val)
 {
    return set_v4uint8(idx, val);
 }
// CHECK-LABEL: define dso_local noundef <8 x i8> @_Z16test_set_v8uint8ij(
// CHECK-SAME: i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[VAL]], 255
// CHECK-NEXT:    [[CONV_I_I_I:%.*]] = zext nneg i32 [[AND1_I_I_I]] to i64
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 3
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 56
// CHECK-NEXT:    [[SH_PROM_I_I_I:%.*]] = zext nneg i32 [[MUL_I_I_I]] to i64
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw i64 [[CONV_I_I_I]], [[SH_PROM_I_I_I]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i64 [[SHL_I_I_I]] to <8 x i8>
// CHECK-NEXT:    ret <8 x i8> [[TMP0]]
//
v8uint8 test_set_v8uint8  (int idx, unsigned int val)
 {
    return set_v8uint8(idx, val);
 }
// CHECK-LABEL: define dso_local noundef <2 x i16> @_Z17test_set_v2uint16ij(
// CHECK-SAME: i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[VAL]], 65535
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 4
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 16
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw i32 [[AND1_I_I_I]], [[MUL_I_I_I]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i32 [[SHL_I_I_I]] to <2 x i16>
// CHECK-NEXT:    ret <2 x i16> [[TMP0]]
//
v2uint16 test_set_v2uint16(int idx, unsigned int val)
 {
    return set_v2uint16(idx, val);
 }
// CHECK-LABEL: define dso_local noundef <4 x i16> @_Z17test_set_v4uint16ij(
// CHECK-SAME: i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[VAL]], 65535
// CHECK-NEXT:    [[CONV_I_I_I:%.*]] = zext nneg i32 [[AND1_I_I_I]] to i64
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 4
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 48
// CHECK-NEXT:    [[SH_PROM_I_I_I:%.*]] = zext nneg i32 [[MUL_I_I_I]] to i64
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw i64 [[CONV_I_I_I]], [[SH_PROM_I_I_I]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i64 [[SHL_I_I_I]] to <4 x i16>
// CHECK-NEXT:    ret <4 x i16> [[TMP0]]
//
v4uint16 test_set_v4uint16(int idx, unsigned int val)
 {
    return set_v4uint16(idx, val);
 }
// CHECK-LABEL: define dso_local noundef <2 x i32> @_Z17test_set_v2uint32ij(
// CHECK-SAME: i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CONV_I_I_I:%.*]] = zext i32 [[VAL]] to i64
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 5
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 32
// CHECK-NEXT:    [[SH_PROM_I_I_I:%.*]] = zext nneg i32 [[MUL_I_I_I]] to i64
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw i64 [[CONV_I_I_I]], [[SH_PROM_I_I_I]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i64 [[SHL_I_I_I]] to <2 x i32>
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
v2uint32 test_set_v2uint32(int idx, unsigned int val)
 {
    return set_v2uint32(idx, val);
 }
// CHECK-LABEL: define dso_local noundef signext i8 @_Z11test_insertDB8_ii(
// CHECK-SAME: i8 noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CONV_I:%.*]] = zext i8 [[V]] to i32
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 2
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 4
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw nsw i32 15, [[MUL_I_I_I]]
// CHECK-NEXT:    [[NOT_I_I_I:%.*]] = xor i32 [[SHL_I_I_I]], -1
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[NOT_I_I_I]], [[CONV_I]]
// CHECK-NEXT:    [[AND2_I_I_I:%.*]] = and i32 [[VAL]], 15
// CHECK-NEXT:    [[SHL4_I_I_I:%.*]] = shl nuw nsw i32 [[AND2_I_I_I]], [[MUL_I_I_I]]
// CHECK-NEXT:    [[OR_I_I_I:%.*]] = or i32 [[AND1_I_I_I]], [[SHL4_I_I_I]]
// CHECK-NEXT:    [[CONV1_I:%.*]] = trunc nuw i32 [[OR_I_I_I]] to i8
// CHECK-NEXT:    ret i8 [[CONV1_I]]
//
 v2int4 test_insert( v2int4 v, int idx, int val)
 {
    return insert(v, idx, val);
 }
// CHECK-LABEL: define dso_local noundef <2 x i8> @_Z11test_insertDv2_DB8_ii(
// CHECK-SAME: <2 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i8> [[V]] to i16
// CHECK-NEXT:    [[CONV_I:%.*]] = zext i16 [[TMP0]] to i32
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 2
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 12
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw nsw i32 15, [[MUL_I_I_I]]
// CHECK-NEXT:    [[NOT_I_I_I:%.*]] = xor i32 [[SHL_I_I_I]], -1
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[NOT_I_I_I]], [[CONV_I]]
// CHECK-NEXT:    [[AND2_I_I_I:%.*]] = and i32 [[VAL]], 15
// CHECK-NEXT:    [[SHL4_I_I_I:%.*]] = shl nuw nsw i32 [[AND2_I_I_I]], [[MUL_I_I_I]]
// CHECK-NEXT:    [[OR_I_I_I:%.*]] = or i32 [[AND1_I_I_I]], [[SHL4_I_I_I]]
// CHECK-NEXT:    [[CONV1_I:%.*]] = trunc nuw i32 [[OR_I_I_I]] to i16
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i16 [[CONV1_I]] to <2 x i8>
// CHECK-NEXT:    ret <2 x i8> [[TMP1]]
//
 v4int4 test_insert( v4int4 v, int idx, int val)
 {
    return insert(v, idx, val);
 }
// CHECK-LABEL: define dso_local noundef <4 x i8> @_Z11test_insertDv4_DB8_ii(
// CHECK-SAME: <4 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[V]] to i32
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 2
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 28
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw i32 15, [[MUL_I_I_I]]
// CHECK-NEXT:    [[NOT_I_I_I:%.*]] = xor i32 [[SHL_I_I_I]], -1
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[NOT_I_I_I]], [[TMP0]]
// CHECK-NEXT:    [[AND2_I_I_I:%.*]] = and i32 [[VAL]], 15
// CHECK-NEXT:    [[SHL4_I_I_I:%.*]] = shl nuw i32 [[AND2_I_I_I]], [[MUL_I_I_I]]
// CHECK-NEXT:    [[OR_I_I_I:%.*]] = or i32 [[AND1_I_I_I]], [[SHL4_I_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i32 [[OR_I_I_I]] to <4 x i8>
// CHECK-NEXT:    ret <4 x i8> [[TMP1]]
//
 v8int4 test_insert( v8int4 v, int idx, int val)
 {
    return insert(v, idx, val);
 }
// CHECK-LABEL: define dso_local noundef <8 x i8> @_Z11test_insertDv8_DB8_ii(
// CHECK-SAME: <8 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x i8> [[V]] to i64
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 2
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 60
// CHECK-NEXT:    [[SH_PROM_I_I_I:%.*]] = zext nneg i32 [[MUL_I_I_I]] to i64
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw i64 15, [[SH_PROM_I_I_I]]
// CHECK-NEXT:    [[NOT_I_I_I:%.*]] = xor i64 [[SHL_I_I_I]], -1
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i64 [[NOT_I_I_I]], [[TMP0]]
// CHECK-NEXT:    [[AND2_I_I_I:%.*]] = and i32 [[VAL]], 15
// CHECK-NEXT:    [[CONV3_I_I_I:%.*]] = zext nneg i32 [[AND2_I_I_I]] to i64
// CHECK-NEXT:    [[SHL6_I_I_I:%.*]] = shl nuw i64 [[CONV3_I_I_I]], [[SH_PROM_I_I_I]]
// CHECK-NEXT:    [[OR_I_I_I:%.*]] = or i64 [[AND1_I_I_I]], [[SHL6_I_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64 [[OR_I_I_I]] to <8 x i8>
// CHECK-NEXT:    ret <8 x i8> [[TMP1]]
//
v16int4 test_insert(v16int4 v, int idx, int val)
 {
    return insert(v, idx, val);
 }
// CHECK-LABEL: define dso_local noundef <2 x i8> @_Z11test_insertDv2_aii(
// CHECK-SAME: <2 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i8> [[V]] to i16
// CHECK-NEXT:    [[CONV_I:%.*]] = zext i16 [[TMP0]] to i32
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 3
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 8
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw nsw i32 255, [[MUL_I_I_I]]
// CHECK-NEXT:    [[NOT_I_I_I:%.*]] = xor i32 [[SHL_I_I_I]], -1
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[NOT_I_I_I]], [[CONV_I]]
// CHECK-NEXT:    [[AND2_I_I_I:%.*]] = and i32 [[VAL]], 255
// CHECK-NEXT:    [[SHL4_I_I_I:%.*]] = shl nuw nsw i32 [[AND2_I_I_I]], [[MUL_I_I_I]]
// CHECK-NEXT:    [[OR_I_I_I:%.*]] = or i32 [[AND1_I_I_I]], [[SHL4_I_I_I]]
// CHECK-NEXT:    [[CONV1_I:%.*]] = trunc nuw i32 [[OR_I_I_I]] to i16
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i16 [[CONV1_I]] to <2 x i8>
// CHECK-NEXT:    ret <2 x i8> [[TMP1]]
//
v2int8 test_insert(v2int8 v, int idx, int val)
 {
    return insert(v, idx, val);
 }

// CHECK-LABEL: define dso_local noundef <4 x i8> @_Z11test_insertDv4_aii(
// CHECK-SAME: <4 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[V]] to i32
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 3
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 24
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw i32 255, [[MUL_I_I_I]]
// CHECK-NEXT:    [[NOT_I_I_I:%.*]] = xor i32 [[SHL_I_I_I]], -1
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[NOT_I_I_I]], [[TMP0]]
// CHECK-NEXT:    [[AND2_I_I_I:%.*]] = and i32 [[VAL]], 255
// CHECK-NEXT:    [[SHL4_I_I_I:%.*]] = shl nuw i32 [[AND2_I_I_I]], [[MUL_I_I_I]]
// CHECK-NEXT:    [[OR_I_I_I:%.*]] = or i32 [[AND1_I_I_I]], [[SHL4_I_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i32 [[OR_I_I_I]] to <4 x i8>
// CHECK-NEXT:    ret <4 x i8> [[TMP1]]
//
v4int8 test_insert(v4int8 v, int idx, int val)
 {
    return insert(v, idx, val);
 }
// CHECK-LABEL: define dso_local noundef <8 x i8> @_Z11test_insertDv8_aii(
// CHECK-SAME: <8 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x i8> [[V]] to i64
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 3
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 56
// CHECK-NEXT:    [[SH_PROM_I_I_I:%.*]] = zext nneg i32 [[MUL_I_I_I]] to i64
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw i64 255, [[SH_PROM_I_I_I]]
// CHECK-NEXT:    [[NOT_I_I_I:%.*]] = xor i64 [[SHL_I_I_I]], -1
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i64 [[NOT_I_I_I]], [[TMP0]]
// CHECK-NEXT:    [[AND2_I_I_I:%.*]] = and i32 [[VAL]], 255
// CHECK-NEXT:    [[CONV3_I_I_I:%.*]] = zext nneg i32 [[AND2_I_I_I]] to i64
// CHECK-NEXT:    [[SHL6_I_I_I:%.*]] = shl nuw i64 [[CONV3_I_I_I]], [[SH_PROM_I_I_I]]
// CHECK-NEXT:    [[OR_I_I_I:%.*]] = or i64 [[AND1_I_I_I]], [[SHL6_I_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64 [[OR_I_I_I]] to <8 x i8>
// CHECK-NEXT:    ret <8 x i8> [[TMP1]]
//
v8int8 test_insert(v8int8 v, int idx, int val)
 {
    return insert(v, idx, val);
 }
// CHECK-LABEL: define dso_local noundef <2 x i16> @_Z11test_insertDv2_sii(
// CHECK-SAME: <2 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i16> [[V]] to i32
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 4
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 16
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw i32 65535, [[MUL_I_I_I]]
// CHECK-NEXT:    [[NOT_I_I_I:%.*]] = xor i32 [[SHL_I_I_I]], -1
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[NOT_I_I_I]], [[TMP0]]
// CHECK-NEXT:    [[AND2_I_I_I:%.*]] = and i32 [[VAL]], 65535
// CHECK-NEXT:    [[SHL4_I_I_I:%.*]] = shl nuw i32 [[AND2_I_I_I]], [[MUL_I_I_I]]
// CHECK-NEXT:    [[OR_I_I_I:%.*]] = or i32 [[AND1_I_I_I]], [[SHL4_I_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i32 [[OR_I_I_I]] to <2 x i16>
// CHECK-NEXT:    ret <2 x i16> [[TMP1]]
//
v2int16 test_insert(v2int16 v, int idx, int val)
 {
    return insert(v, idx, val);
 }
// CHECK-LABEL: define dso_local noundef <4 x i16> @_Z11test_insertDv4_sii(
// CHECK-SAME: <4 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x i16> [[V]] to i64
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 4
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 48
// CHECK-NEXT:    [[SH_PROM_I_I_I:%.*]] = zext nneg i32 [[MUL_I_I_I]] to i64
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw i64 65535, [[SH_PROM_I_I_I]]
// CHECK-NEXT:    [[NOT_I_I_I:%.*]] = xor i64 [[SHL_I_I_I]], -1
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i64 [[NOT_I_I_I]], [[TMP0]]
// CHECK-NEXT:    [[AND2_I_I_I:%.*]] = and i32 [[VAL]], 65535
// CHECK-NEXT:    [[CONV3_I_I_I:%.*]] = zext nneg i32 [[AND2_I_I_I]] to i64
// CHECK-NEXT:    [[SHL6_I_I_I:%.*]] = shl nuw i64 [[CONV3_I_I_I]], [[SH_PROM_I_I_I]]
// CHECK-NEXT:    [[OR_I_I_I:%.*]] = or i64 [[AND1_I_I_I]], [[SHL6_I_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64 [[OR_I_I_I]] to <4 x i16>
// CHECK-NEXT:    ret <4 x i16> [[TMP1]]
//
v4int16 test_insert(v4int16 v, int idx, int val)
 {
    return insert(v, idx, val);
 }
// CHECK-LABEL: define dso_local noundef <2 x i32> @_Z11test_insertDv2_iii(
// CHECK-SAME: <2 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i32> [[V]] to i64
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 5
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 32
// CHECK-NEXT:    [[SH_PROM_I_I_I:%.*]] = zext nneg i32 [[MUL_I_I_I]] to i64
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw i64 4294967295, [[SH_PROM_I_I_I]]
// CHECK-NEXT:    [[NOT_I_I_I:%.*]] = xor i64 [[SHL_I_I_I]], -1
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i64 [[NOT_I_I_I]], [[TMP0]]
// CHECK-NEXT:    [[CONV3_I_I_I:%.*]] = zext i32 [[VAL]] to i64
// CHECK-NEXT:    [[SHL6_I_I_I:%.*]] = shl nuw i64 [[CONV3_I_I_I]], [[SH_PROM_I_I_I]]
// CHECK-NEXT:    [[OR_I_I_I:%.*]] = or i64 [[AND1_I_I_I]], [[SHL6_I_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64 [[OR_I_I_I]] to <2 x i32>
// CHECK-NEXT:    ret <2 x i32> [[TMP1]]
//
v2int32 test_insert(v2int32 v, int idx, int val)   {
    return insert(v, idx, val);
 }
// CHECK-LABEL: define dso_local noundef zeroext i8 @_Z11test_insertDU8_ij(
// CHECK-SAME: i8 noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CONV_I:%.*]] = zext i8 [[V]] to i32
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 2
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 4
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw nsw i32 15, [[MUL_I_I_I]]
// CHECK-NEXT:    [[NOT_I_I_I:%.*]] = xor i32 [[SHL_I_I_I]], -1
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[NOT_I_I_I]], [[CONV_I]]
// CHECK-NEXT:    [[AND2_I_I_I:%.*]] = and i32 [[VAL]], 15
// CHECK-NEXT:    [[SHL4_I_I_I:%.*]] = shl nuw nsw i32 [[AND2_I_I_I]], [[MUL_I_I_I]]
// CHECK-NEXT:    [[OR_I_I_I:%.*]] = or i32 [[AND1_I_I_I]], [[SHL4_I_I_I]]
// CHECK-NEXT:    [[CONV1_I:%.*]] = trunc nuw i32 [[OR_I_I_I]] to i8
// CHECK-NEXT:    ret i8 [[CONV1_I]]
//
 v2uint4 test_insert( v2uint4 v, int idx, unsigned int val)
 {
    return insert(v, idx, val);
 }
// CHECK-LABEL: define dso_local noundef <2 x i8> @_Z11test_insertDv2_DU8_ij(
// CHECK-SAME: <2 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i8> [[V]] to i16
// CHECK-NEXT:    [[CONV_I:%.*]] = zext i16 [[TMP0]] to i32
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 2
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 12
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw nsw i32 15, [[MUL_I_I_I]]
// CHECK-NEXT:    [[NOT_I_I_I:%.*]] = xor i32 [[SHL_I_I_I]], -1
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[NOT_I_I_I]], [[CONV_I]]
// CHECK-NEXT:    [[AND2_I_I_I:%.*]] = and i32 [[VAL]], 15
// CHECK-NEXT:    [[SHL4_I_I_I:%.*]] = shl nuw nsw i32 [[AND2_I_I_I]], [[MUL_I_I_I]]
// CHECK-NEXT:    [[OR_I_I_I:%.*]] = or i32 [[AND1_I_I_I]], [[SHL4_I_I_I]]
// CHECK-NEXT:    [[CONV1_I:%.*]] = trunc nuw i32 [[OR_I_I_I]] to i16
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i16 [[CONV1_I]] to <2 x i8>
// CHECK-NEXT:    ret <2 x i8> [[TMP1]]
//
 v4uint4 test_insert( v4uint4 v, int idx, unsigned int val)
 {
    return insert(v, idx, val);
 }
// CHECK-LABEL: define dso_local noundef <4 x i8> @_Z11test_insertDv4_DU8_ij(
// CHECK-SAME: <4 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[V]] to i32
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 2
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 28
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw i32 15, [[MUL_I_I_I]]
// CHECK-NEXT:    [[NOT_I_I_I:%.*]] = xor i32 [[SHL_I_I_I]], -1
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[NOT_I_I_I]], [[TMP0]]
// CHECK-NEXT:    [[AND2_I_I_I:%.*]] = and i32 [[VAL]], 15
// CHECK-NEXT:    [[SHL4_I_I_I:%.*]] = shl nuw i32 [[AND2_I_I_I]], [[MUL_I_I_I]]
// CHECK-NEXT:    [[OR_I_I_I:%.*]] = or i32 [[AND1_I_I_I]], [[SHL4_I_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i32 [[OR_I_I_I]] to <4 x i8>
// CHECK-NEXT:    ret <4 x i8> [[TMP1]]
//
 v8uint4 test_insert( v8uint4 v, int idx, unsigned int val)
 {
    return insert(v, idx, val);
 }
// CHECK-LABEL: define dso_local noundef <8 x i8> @_Z11test_insertDv8_DU8_ij(
// CHECK-SAME: <8 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x i8> [[V]] to i64
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 2
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 60
// CHECK-NEXT:    [[SH_PROM_I_I_I:%.*]] = zext nneg i32 [[MUL_I_I_I]] to i64
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw i64 15, [[SH_PROM_I_I_I]]
// CHECK-NEXT:    [[NOT_I_I_I:%.*]] = xor i64 [[SHL_I_I_I]], -1
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i64 [[NOT_I_I_I]], [[TMP0]]
// CHECK-NEXT:    [[AND2_I_I_I:%.*]] = and i32 [[VAL]], 15
// CHECK-NEXT:    [[CONV3_I_I_I:%.*]] = zext nneg i32 [[AND2_I_I_I]] to i64
// CHECK-NEXT:    [[SHL6_I_I_I:%.*]] = shl nuw i64 [[CONV3_I_I_I]], [[SH_PROM_I_I_I]]
// CHECK-NEXT:    [[OR_I_I_I:%.*]] = or i64 [[AND1_I_I_I]], [[SHL6_I_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64 [[OR_I_I_I]] to <8 x i8>
// CHECK-NEXT:    ret <8 x i8> [[TMP1]]
//
v16uint4 test_insert(v16uint4 v, int idx, unsigned int val)
 {
    return insert(v, idx, val);
 }

// CHECK-LABEL: define dso_local noundef <2 x i8> @_Z11test_insertDv2_hij(
// CHECK-SAME: <2 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i8> [[V]] to i16
// CHECK-NEXT:    [[CONV_I:%.*]] = zext i16 [[TMP0]] to i32
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 3
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 8
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw nsw i32 255, [[MUL_I_I_I]]
// CHECK-NEXT:    [[NOT_I_I_I:%.*]] = xor i32 [[SHL_I_I_I]], -1
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[NOT_I_I_I]], [[CONV_I]]
// CHECK-NEXT:    [[AND2_I_I_I:%.*]] = and i32 [[VAL]], 255
// CHECK-NEXT:    [[SHL4_I_I_I:%.*]] = shl nuw nsw i32 [[AND2_I_I_I]], [[MUL_I_I_I]]
// CHECK-NEXT:    [[OR_I_I_I:%.*]] = or i32 [[AND1_I_I_I]], [[SHL4_I_I_I]]
// CHECK-NEXT:    [[CONV1_I:%.*]] = trunc nuw i32 [[OR_I_I_I]] to i16
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i16 [[CONV1_I]] to <2 x i8>
// CHECK-NEXT:    ret <2 x i8> [[TMP1]]
//
v2uint8 test_insert(v2uint8 v, int idx, unsigned int val)
 {
    return insert(v, idx, val);
 }
// CHECK-LABEL: define dso_local noundef <4 x i8> @_Z11test_insertDv4_hij(
// CHECK-SAME: <4 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[V]] to i32
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 3
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 24
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw i32 255, [[MUL_I_I_I]]
// CHECK-NEXT:    [[NOT_I_I_I:%.*]] = xor i32 [[SHL_I_I_I]], -1
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[NOT_I_I_I]], [[TMP0]]
// CHECK-NEXT:    [[AND2_I_I_I:%.*]] = and i32 [[VAL]], 255
// CHECK-NEXT:    [[SHL4_I_I_I:%.*]] = shl nuw i32 [[AND2_I_I_I]], [[MUL_I_I_I]]
// CHECK-NEXT:    [[OR_I_I_I:%.*]] = or i32 [[AND1_I_I_I]], [[SHL4_I_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i32 [[OR_I_I_I]] to <4 x i8>
// CHECK-NEXT:    ret <4 x i8> [[TMP1]]
//
v4uint8 test_insert(v4uint8 v, int idx, unsigned int val)
 {
    return insert(v, idx, val);
 }
// CHECK-LABEL: define dso_local noundef <8 x i8> @_Z11test_insertDv8_hij(
// CHECK-SAME: <8 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x i8> [[V]] to i64
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 3
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 56
// CHECK-NEXT:    [[SH_PROM_I_I_I:%.*]] = zext nneg i32 [[MUL_I_I_I]] to i64
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw i64 255, [[SH_PROM_I_I_I]]
// CHECK-NEXT:    [[NOT_I_I_I:%.*]] = xor i64 [[SHL_I_I_I]], -1
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i64 [[NOT_I_I_I]], [[TMP0]]
// CHECK-NEXT:    [[AND2_I_I_I:%.*]] = and i32 [[VAL]], 255
// CHECK-NEXT:    [[CONV3_I_I_I:%.*]] = zext nneg i32 [[AND2_I_I_I]] to i64
// CHECK-NEXT:    [[SHL6_I_I_I:%.*]] = shl nuw i64 [[CONV3_I_I_I]], [[SH_PROM_I_I_I]]
// CHECK-NEXT:    [[OR_I_I_I:%.*]] = or i64 [[AND1_I_I_I]], [[SHL6_I_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64 [[OR_I_I_I]] to <8 x i8>
// CHECK-NEXT:    ret <8 x i8> [[TMP1]]
//
v8uint8 test_insert(v8uint8 v, int idx, unsigned int val)
 {
    return insert(v, idx, val);
 }
// CHECK-LABEL: define dso_local noundef <2 x i16> @_Z11test_insertDv2_tij(
// CHECK-SAME: <2 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i16> [[V]] to i32
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 4
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 16
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw i32 65535, [[MUL_I_I_I]]
// CHECK-NEXT:    [[NOT_I_I_I:%.*]] = xor i32 [[SHL_I_I_I]], -1
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[NOT_I_I_I]], [[TMP0]]
// CHECK-NEXT:    [[AND2_I_I_I:%.*]] = and i32 [[VAL]], 65535
// CHECK-NEXT:    [[SHL4_I_I_I:%.*]] = shl nuw i32 [[AND2_I_I_I]], [[MUL_I_I_I]]
// CHECK-NEXT:    [[OR_I_I_I:%.*]] = or i32 [[AND1_I_I_I]], [[SHL4_I_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i32 [[OR_I_I_I]] to <2 x i16>
// CHECK-NEXT:    ret <2 x i16> [[TMP1]]
//
v2uint16 test_insert(v2uint16 v, int idx, unsigned int val)
 {
    return insert(v, idx, val);
 }
// CHECK-LABEL: define dso_local noundef <4 x i16> @_Z11test_insertDv4_tij(
// CHECK-SAME: <4 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x i16> [[V]] to i64
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 4
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 48
// CHECK-NEXT:    [[SH_PROM_I_I_I:%.*]] = zext nneg i32 [[MUL_I_I_I]] to i64
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw i64 65535, [[SH_PROM_I_I_I]]
// CHECK-NEXT:    [[NOT_I_I_I:%.*]] = xor i64 [[SHL_I_I_I]], -1
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i64 [[NOT_I_I_I]], [[TMP0]]
// CHECK-NEXT:    [[AND2_I_I_I:%.*]] = and i32 [[VAL]], 65535
// CHECK-NEXT:    [[CONV3_I_I_I:%.*]] = zext nneg i32 [[AND2_I_I_I]] to i64
// CHECK-NEXT:    [[SHL6_I_I_I:%.*]] = shl nuw i64 [[CONV3_I_I_I]], [[SH_PROM_I_I_I]]
// CHECK-NEXT:    [[OR_I_I_I:%.*]] = or i64 [[AND1_I_I_I]], [[SHL6_I_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64 [[OR_I_I_I]] to <4 x i16>
// CHECK-NEXT:    ret <4 x i16> [[TMP1]]
//
v4uint16 test_insert(v4uint16 v, int idx, unsigned int val)
 {
    return insert(v, idx, val);
 }
// CHECK-LABEL: define dso_local noundef <2 x i32> @_Z11test_insertDv2_jij(
// CHECK-SAME: <2 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i32> [[V]] to i64
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 5
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 32
// CHECK-NEXT:    [[SH_PROM_I_I_I:%.*]] = zext nneg i32 [[MUL_I_I_I]] to i64
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl nuw i64 4294967295, [[SH_PROM_I_I_I]]
// CHECK-NEXT:    [[NOT_I_I_I:%.*]] = xor i64 [[SHL_I_I_I]], -1
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i64 [[NOT_I_I_I]], [[TMP0]]
// CHECK-NEXT:    [[CONV3_I_I_I:%.*]] = zext i32 [[VAL]] to i64
// CHECK-NEXT:    [[SHL6_I_I_I:%.*]] = shl nuw i64 [[CONV3_I_I_I]], [[SH_PROM_I_I_I]]
// CHECK-NEXT:    [[OR_I_I_I:%.*]] = or i64 [[AND1_I_I_I]], [[SHL6_I_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64 [[OR_I_I_I]] to <2 x i32>
// CHECK-NEXT:    ret <2 x i32> [[TMP1]]
//
v2uint32 test_insert(v2uint32 v, int idx, unsigned int val)
 {
    return insert(v, idx, val);
 }

// CHECK-LABEL: define dso_local noundef range(i32 -8, 8) i32 @_Z17test_extract_elemDB8_i(
// CHECK-SAME: i8 noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CONV_I:%.*]] = sext i8 [[V]] to i32
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[ADD_NEG_I_I_I:%.*]] = xor i32 [[AND_I_I_I]], -1
// CHECK-NEXT:    [[MUL_NEG_I_I_I:%.*]] = shl nsw i32 [[ADD_NEG_I_I_I]], 2
// CHECK-NEXT:    [[SUB1_I_I_I:%.*]] = add nsw i32 [[MUL_NEG_I_I_I]], 32
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl i32 [[CONV_I]], [[SUB1_I_I_I]]
// CHECK-NEXT:    [[SHR_I_I_I:%.*]] = ashr i32 [[SHL_I_I_I]], 28
// CHECK-NEXT:    ret i32 [[SHR_I_I_I]]
//
int test_extract_elem( v2int4 v, int idx)
{
   return extract_elem(v, idx);
}
// CHECK-LABEL: define dso_local noundef range(i32 -8, 8) i32 @_Z17test_extract_elemDv2_DB8_i(
// CHECK-SAME: <2 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i8> [[V]] to i16
// CHECK-NEXT:    [[CONV_I:%.*]] = sext i16 [[TMP0]] to i32
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = and i32 [[IDX]], 3
// CHECK-NEXT:    [[ADD_NEG_I_I_I:%.*]] = xor i32 [[AND_I_I_I]], -1
// CHECK-NEXT:    [[MUL_NEG_I_I_I:%.*]] = shl nsw i32 [[ADD_NEG_I_I_I]], 2
// CHECK-NEXT:    [[SUB1_I_I_I:%.*]] = add nsw i32 [[MUL_NEG_I_I_I]], 32
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl i32 [[CONV_I]], [[SUB1_I_I_I]]
// CHECK-NEXT:    [[SHR_I_I_I:%.*]] = ashr i32 [[SHL_I_I_I]], 28
// CHECK-NEXT:    ret i32 [[SHR_I_I_I]]
//
int test_extract_elem( v4int4 v, int idx)
{
    return extract_elem(v, idx);
}
// CHECK-LABEL: define dso_local noundef range(i32 -8, 8) i32 @_Z17test_extract_elemDv4_DB8_i(
// CHECK-SAME: <4 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[V]] to i32
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = and i32 [[IDX]], 7
// CHECK-NEXT:    [[ADD_NEG_I_I_I:%.*]] = xor i32 [[AND_I_I_I]], -1
// CHECK-NEXT:    [[MUL_NEG_I_I_I:%.*]] = shl nsw i32 [[ADD_NEG_I_I_I]], 2
// CHECK-NEXT:    [[SUB1_I_I_I:%.*]] = add nsw i32 [[MUL_NEG_I_I_I]], 32
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl i32 [[TMP0]], [[SUB1_I_I_I]]
// CHECK-NEXT:    [[SHR_I_I_I:%.*]] = ashr i32 [[SHL_I_I_I]], 28
// CHECK-NEXT:    ret i32 [[SHR_I_I_I]]
//
int test_extract_elem( v8int4 v, int idx)
{
    return extract_elem(v, idx);
}
// CHECK-LABEL: define dso_local noundef range(i32 0, 16) i32 @_Z17test_extract_elemDv8_DB8_i(
// CHECK-SAME: <8 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x i8> [[V]] to i64
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 2
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 60
// CHECK-NEXT:    [[SH_PROM_I_I_I:%.*]] = zext nneg i32 [[MUL_I_I_I]] to i64
// CHECK-NEXT:    [[SHR_I_I_I:%.*]] = lshr i64 [[TMP0]], [[SH_PROM_I_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = trunc i64 [[SHR_I_I_I]] to i32
// CHECK-NEXT:    [[VECEXT_I_I_I:%.*]] = and i32 [[TMP1]], 15
// CHECK-NEXT:    ret i32 [[VECEXT_I_I_I]]
//
int test_extract_elem(v16int4 v, int idx)
{
    return extract_elem(v, idx);
}
// CHECK-LABEL: define dso_local noundef range(i32 -128, 128) i32 @_Z17test_extract_elemDv2_ai(
// CHECK-SAME: <2 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i8> [[V]] to i16
// CHECK-NEXT:    [[CONV_I:%.*]] = sext i16 [[TMP0]] to i32
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[ADD_NEG_I_I_I:%.*]] = xor i32 [[AND_I_I_I]], -1
// CHECK-NEXT:    [[MUL_NEG_I_I_I:%.*]] = shl nsw i32 [[ADD_NEG_I_I_I]], 3
// CHECK-NEXT:    [[SUB1_I_I_I:%.*]] = add nsw i32 [[MUL_NEG_I_I_I]], 32
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl i32 [[CONV_I]], [[SUB1_I_I_I]]
// CHECK-NEXT:    [[SHR_I_I_I:%.*]] = ashr i32 [[SHL_I_I_I]], 24
// CHECK-NEXT:    ret i32 [[SHR_I_I_I]]
//
int test_extract_elem(v2int8 v,  int idx)
{
    return extract_elem(v, idx);
}
// CHECK-LABEL: define dso_local noundef range(i32 -128, 128) i32 @_Z17test_extract_elemDv4_ai(
// CHECK-SAME: <4 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[V]] to i32
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = and i32 [[IDX]], 3
// CHECK-NEXT:    [[ADD_NEG_I_I_I:%.*]] = xor i32 [[AND_I_I_I]], -1
// CHECK-NEXT:    [[MUL_NEG_I_I_I:%.*]] = shl nsw i32 [[ADD_NEG_I_I_I]], 3
// CHECK-NEXT:    [[SUB1_I_I_I:%.*]] = add nsw i32 [[MUL_NEG_I_I_I]], 32
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl i32 [[TMP0]], [[SUB1_I_I_I]]
// CHECK-NEXT:    [[SHR_I_I_I:%.*]] = ashr i32 [[SHL_I_I_I]], 24
// CHECK-NEXT:    ret i32 [[SHR_I_I_I]]
//
int test_extract_elem(v4int8 v,  int idx)
{
    return extract_elem(v, idx);
}
// CHECK-LABEL: define dso_local noundef range(i32 0, 256) i32 @_Z17test_extract_elemDv8_ai(
// CHECK-SAME: <8 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x i8> [[V]] to i64
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 3
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 56
// CHECK-NEXT:    [[SH_PROM_I_I_I:%.*]] = zext nneg i32 [[MUL_I_I_I]] to i64
// CHECK-NEXT:    [[SHR_I_I_I:%.*]] = lshr i64 [[TMP0]], [[SH_PROM_I_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = trunc i64 [[SHR_I_I_I]] to i32
// CHECK-NEXT:    [[VECEXT_I_I_I:%.*]] = and i32 [[TMP1]], 255
// CHECK-NEXT:    ret i32 [[VECEXT_I_I_I]]
//
int test_extract_elem(v8int8 v,  int idx)
{
    return extract_elem(v, idx);
}
// CHECK-LABEL: define dso_local noundef range(i32 -32768, 32768) i32 @_Z17test_extract_elemDv2_si(
// CHECK-SAME: <2 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i16> [[V]] to i32
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[ADD_NEG_I_I_I:%.*]] = xor i32 [[AND_I_I_I]], -1
// CHECK-NEXT:    [[MUL_NEG_I_I_I:%.*]] = shl nsw i32 [[ADD_NEG_I_I_I]], 4
// CHECK-NEXT:    [[SUB1_I_I_I:%.*]] = add nsw i32 [[MUL_NEG_I_I_I]], 32
// CHECK-NEXT:    [[SHL_I_I_I:%.*]] = shl i32 [[TMP0]], [[SUB1_I_I_I]]
// CHECK-NEXT:    [[SHR_I_I_I:%.*]] = ashr i32 [[SHL_I_I_I]], 16
// CHECK-NEXT:    ret i32 [[SHR_I_I_I]]
//
int test_extract_elem(v2int16 v, int idx)
{
    return extract_elem(v, idx);
}
// CHECK-LABEL: define dso_local noundef range(i32 0, 65536) i32 @_Z17test_extract_elemDv4_si(
// CHECK-SAME: <4 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x i16> [[V]] to i64
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 4
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 48
// CHECK-NEXT:    [[SH_PROM_I_I_I:%.*]] = zext nneg i32 [[MUL_I_I_I]] to i64
// CHECK-NEXT:    [[SHR_I_I_I:%.*]] = lshr i64 [[TMP0]], [[SH_PROM_I_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = trunc i64 [[SHR_I_I_I]] to i32
// CHECK-NEXT:    [[VECEXT_I_I_I:%.*]] = and i32 [[TMP1]], 65535
// CHECK-NEXT:    ret i32 [[VECEXT_I_I_I]]
//
int test_extract_elem(v4int16 v, int idx)
{
    return extract_elem(v, idx);
}
// CHECK-LABEL: define dso_local noundef i32 @_Z17test_extract_elemDv2_ii(
// CHECK-SAME: <2 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i32> [[V]] to i64
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 5
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 32
// CHECK-NEXT:    [[SH_PROM_I_I_I:%.*]] = zext nneg i32 [[MUL_I_I_I]] to i64
// CHECK-NEXT:    [[SHR_I_I_I:%.*]] = lshr i64 [[TMP0]], [[SH_PROM_I_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = trunc i64 [[SHR_I_I_I]] to i32
// CHECK-NEXT:    ret i32 [[TMP1]]
//
int test_extract_elem(v2int32 v, int idx)
{
    return extract_elem(v, idx);
}
// CHECK-LABEL: define dso_local noundef range(i32 0, 16) i32 @_Z17test_extract_elemDU8_i(
// CHECK-SAME: i8 noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CONV_I:%.*]] = zext i8 [[V]] to i32
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 2
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 4
// CHECK-NEXT:    [[SHR_I_I_I:%.*]] = lshr i32 [[CONV_I]], [[MUL_I_I_I]]
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[SHR_I_I_I]], 15
// CHECK-NEXT:    ret i32 [[AND1_I_I_I]]
//
unsigned int test_extract_elem( v2uint4 v, int idx)
{
    return extract_elem(v, idx);
}
// CHECK-LABEL: define dso_local noundef range(i32 0, 16) i32 @_Z17test_extract_elemDv2_DU8_i(
// CHECK-SAME: <2 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i8> [[V]] to i16
// CHECK-NEXT:    [[CONV_I:%.*]] = zext i16 [[TMP0]] to i32
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 2
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 12
// CHECK-NEXT:    [[SHR_I_I_I:%.*]] = lshr i32 [[CONV_I]], [[MUL_I_I_I]]
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[SHR_I_I_I]], 15
// CHECK-NEXT:    ret i32 [[AND1_I_I_I]]
//
unsigned int test_extract_elem( v4uint4 v, int idx)
{
    return extract_elem(v, idx);
}
// CHECK-LABEL: define dso_local noundef range(i32 0, 16) i32 @_Z17test_extract_elemDv4_DU8_i(
// CHECK-SAME: <4 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[V]] to i32
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 2
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 28
// CHECK-NEXT:    [[SHR_I_I_I:%.*]] = lshr i32 [[TMP0]], [[MUL_I_I_I]]
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[SHR_I_I_I]], 15
// CHECK-NEXT:    ret i32 [[AND1_I_I_I]]
//
unsigned int test_extract_elem( v8uint4 v, int idx)
{
    return extract_elem(v, idx);
}
// CHECK-LABEL: define dso_local noundef range(i32 0, 16) i32 @_Z17test_extract_elemDv8_DU8_i(
// CHECK-SAME: <8 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x i8> [[V]] to i64
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 2
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 60
// CHECK-NEXT:    [[SH_PROM_I_I_I:%.*]] = zext nneg i32 [[MUL_I_I_I]] to i64
// CHECK-NEXT:    [[SHR_I_I_I:%.*]] = lshr i64 [[TMP0]], [[SH_PROM_I_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = trunc i64 [[SHR_I_I_I]] to i32
// CHECK-NEXT:    [[VECEXT_I_I:%.*]] = and i32 [[TMP1]], 15
// CHECK-NEXT:    ret i32 [[VECEXT_I_I]]
//
unsigned int test_extract_elem(v16uint4 v, int idx)
{
    return extract_elem(v, idx);
}
// CHECK-LABEL: define dso_local noundef range(i32 0, 256) i32 @_Z17test_extract_elemDv2_hi(
// CHECK-SAME: <2 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i8> [[V]] to i16
// CHECK-NEXT:    [[CONV_I:%.*]] = zext i16 [[TMP0]] to i32
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 3
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 8
// CHECK-NEXT:    [[SHR_I_I_I:%.*]] = lshr i32 [[CONV_I]], [[MUL_I_I_I]]
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[SHR_I_I_I]], 255
// CHECK-NEXT:    ret i32 [[AND1_I_I_I]]
//
unsigned int test_extract_elem(v2uint8  v, int idx)
{
    return extract_elem(v, idx);
}
// CHECK-LABEL: define dso_local noundef range(i32 0, 256) i32 @_Z17test_extract_elemDv4_hi(
// CHECK-SAME: <4 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[V]] to i32
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 3
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 24
// CHECK-NEXT:    [[SHR_I_I_I:%.*]] = lshr i32 [[TMP0]], [[MUL_I_I_I]]
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[SHR_I_I_I]], 255
// CHECK-NEXT:    ret i32 [[AND1_I_I_I]]
//
unsigned int test_extract_elem(v4uint8  v, int idx)
{
    return extract_elem(v, idx);
}
// CHECK-LABEL: define dso_local noundef range(i32 0, 256) i32 @_Z17test_extract_elemDv8_hi(
// CHECK-SAME: <8 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x i8> [[V]] to i64
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 3
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 56
// CHECK-NEXT:    [[SH_PROM_I_I_I:%.*]] = zext nneg i32 [[MUL_I_I_I]] to i64
// CHECK-NEXT:    [[SHR_I_I_I:%.*]] = lshr i64 [[TMP0]], [[SH_PROM_I_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = trunc i64 [[SHR_I_I_I]] to i32
// CHECK-NEXT:    [[VECEXT_I_I:%.*]] = and i32 [[TMP1]], 255
// CHECK-NEXT:    ret i32 [[VECEXT_I_I]]
//
unsigned int test_extract_elem(v8uint8  v, int idx)
{
    return extract_elem(v, idx);
}
// CHECK-LABEL: define dso_local noundef range(i32 0, 65536) i32 @_Z17test_extract_elemDv2_ti(
// CHECK-SAME: <2 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i16> [[V]] to i32
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 4
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 16
// CHECK-NEXT:    [[SHR_I_I_I:%.*]] = lshr i32 [[TMP0]], [[MUL_I_I_I]]
// CHECK-NEXT:    [[AND1_I_I_I:%.*]] = and i32 [[SHR_I_I_I]], 65535
// CHECK-NEXT:    ret i32 [[AND1_I_I_I]]
//
unsigned int test_extract_elem(v2uint16 v, int idx)
{
    return extract_elem(v, idx);
}
// CHECK-LABEL: define dso_local noundef range(i32 0, 65536) i32 @_Z17test_extract_elemDv4_ti(
// CHECK-SAME: <4 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x i16> [[V]] to i64
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 4
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 48
// CHECK-NEXT:    [[SH_PROM_I_I_I:%.*]] = zext nneg i32 [[MUL_I_I_I]] to i64
// CHECK-NEXT:    [[SHR_I_I_I:%.*]] = lshr i64 [[TMP0]], [[SH_PROM_I_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = trunc i64 [[SHR_I_I_I]] to i32
// CHECK-NEXT:    [[VECEXT_I_I:%.*]] = and i32 [[TMP1]], 65535
// CHECK-NEXT:    ret i32 [[VECEXT_I_I]]
//
unsigned int test_extract_elem(v4uint16 v, int idx)
{
    return extract_elem(v, idx);
}
// CHECK-LABEL: define dso_local noundef i32 @_Z17test_extract_elemDv2_ji(
// CHECK-SAME: <2 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i32> [[V]] to i64
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = shl i32 [[IDX]], 5
// CHECK-NEXT:    [[MUL_I_I_I:%.*]] = and i32 [[AND_I_I_I]], 32
// CHECK-NEXT:    [[SH_PROM_I_I_I:%.*]] = zext nneg i32 [[MUL_I_I_I]] to i64
// CHECK-NEXT:    [[SHR_I_I_I:%.*]] = lshr i64 [[TMP0]], [[SH_PROM_I_I_I]]
// CHECK-NEXT:    [[VECEXT_I_I:%.*]] = trunc i64 [[SHR_I_I_I]] to i32
// CHECK-NEXT:    ret i32 [[VECEXT_I_I]]
//
unsigned int test_extract_elem(v2uint32 v, int idx)
{
    return extract_elem(v, idx);
}



//!   @name Scalar updates and extracts
// CHECK-LABEL: define dso_local noundef i64 @_Z11test_insertyij(
// CHECK-SAME: i64 noundef [[A:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i64 [[A]] to <2 x i32>
// CHECK-NEXT:    [[VECINS_I:%.*]] = insertelement <2 x i32> [[TMP0]], i32 [[B]], i32 [[IDX]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[VECINS_I]] to i64
// CHECK-NEXT:    ret i64 [[TMP1]]
//
unsigned long long test_insert(unsigned long long a, int idx, unsigned int b)
{
    return insert(a, idx, b);
}
// CHECK-LABEL: define dso_local noundef i64 @_Z15test_set_uint64ij(
// CHECK-SAME: i32 noundef [[IDX:%.*]], i32 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[VECINS_I:%.*]] = insertelement <2 x i32> poison, i32 [[B]], i32 [[IDX]]
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i32> [[VECINS_I]] to i64
// CHECK-NEXT:    ret i64 [[TMP0]]
//
unsigned long long test_set_uint64(int idx, unsigned int b)
{
    return set_uint64(idx, b);
}
// CHECK-LABEL: define dso_local noundef i32 @_Z19test_extract_uint32yi(
// CHECK-SAME: i64 noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i64 [[A]] to <2 x i32>
// CHECK-NEXT:    [[VECEXT_I:%.*]] = extractelement <2 x i32> [[TMP0]], i32 [[IDX]]
// CHECK-NEXT:    ret i32 [[VECEXT_I]]
//
unsigned int test_extract_uint32(unsigned long long a, int idx)
{
    return extract_uint32(a, idx);
}
// CHECK-LABEL: define dso_local noundef i64 @_Z11test_concatjj(
// CHECK-SAME: i32 noundef [[A:%.*]], i32 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[VECINS_I_I:%.*]] = insertelement <2 x i32> poison, i32 0, i32 [[A]]
// CHECK-NEXT:    [[VECINS_I2_I:%.*]] = insertelement <2 x i32> [[VECINS_I_I]], i32 [[B]], i64 1
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i32> [[VECINS_I2_I]] to i64
// CHECK-NEXT:    ret i64 [[TMP0]]
//
unsigned long long test_concat(unsigned int a, unsigned int b)
{
    return concat(a,b);
}

// Constant-idx companions: verify each helper folds to a single op.
// CHECK-LABEL: define dso_local noundef i64 @_Z20test_insert_u64_idx0yj(
// CHECK-SAME: i64 noundef [[A:%.*]], i32 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i64 [[A]] to <2 x i32>
// CHECK-NEXT:    [[VECINS_I:%.*]] = insertelement <2 x i32> [[TMP0]], i32 [[B]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[VECINS_I]] to i64
// CHECK-NEXT:    ret i64 [[TMP1]]
//
unsigned long long test_insert_u64_idx0(unsigned long long a, unsigned int b) { return insert(a, 0, b); }
// CHECK-LABEL: define dso_local noundef i64 @_Z20test_insert_u64_idx1yj(
// CHECK-SAME: i64 noundef [[A:%.*]], i32 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i64 [[A]] to <2 x i32>
// CHECK-NEXT:    [[VECINS_I:%.*]] = insertelement <2 x i32> [[TMP0]], i32 [[B]], i64 1
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[VECINS_I]] to i64
// CHECK-NEXT:    ret i64 [[TMP1]]
//
unsigned long long test_insert_u64_idx1(unsigned long long a, unsigned int b) { return insert(a, 1, b); }
// CHECK-LABEL: define dso_local noundef i64 @_Z20test_set_uint64_idx0j(
// CHECK-SAME: i32 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[VECINS_I:%.*]] = insertelement <2 x i32> poison, i32 [[B]], i64 0
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i32> [[VECINS_I]] to i64
// CHECK-NEXT:    ret i64 [[TMP0]]
//
unsigned long long test_set_uint64_idx0(unsigned int b) { return set_uint64(0, b); }
// CHECK-LABEL: define dso_local noundef i64 @_Z20test_set_uint64_idx1j(
// CHECK-SAME: i32 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[VECINS_I:%.*]] = insertelement <2 x i32> poison, i32 [[B]], i64 1
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i32> [[VECINS_I]] to i64
// CHECK-NEXT:    ret i64 [[TMP0]]
//
unsigned long long test_set_uint64_idx1(unsigned int b) { return set_uint64(1, b); }
// CHECK-LABEL: define dso_local noundef i32 @_Z24test_extract_uint32_idx0y(
// CHECK-SAME: i64 noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[VECEXT_I:%.*]] = trunc i64 [[A]] to i32
// CHECK-NEXT:    ret i32 [[VECEXT_I]]
//
unsigned int test_extract_uint32_idx0(unsigned long long a) { return extract_uint32(a, 0); }
// CHECK-LABEL: define dso_local noundef i32 @_Z24test_extract_uint32_idx1y(
// CHECK-SAME: i64 noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i64 [[A]] to <2 x i32>
// CHECK-NEXT:    [[VECEXT_I:%.*]] = extractelement <2 x i32> [[TMP0]], i64 1
// CHECK-NEXT:    ret i32 [[VECEXT_I]]
//
unsigned int test_extract_uint32_idx1(unsigned long long a) { return extract_uint32(a, 1); }


// Conversions

// v128uint4

// CHECK-LABEL: define dso_local noundef <32 x i8> @_Z21test_extract_v64uint4Dv64_DU8_i(
// CHECK-SAME: <64 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i32> [[COND_I_I]] to <32 x i8>
// CHECK-NEXT:    ret <32 x i8> [[TMP1]]
//
v64uint4 test_extract_v64uint4 (v128uint4 a, int idx)
{
    return extract_v64uint4(a, idx);
}

// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_DU8_iDv32_S_(
// CHECK-SAME: <64 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <32 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A]] to <16 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i8> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[COND_I_I]] to <64 x i8>
// CHECK-NEXT:    ret <64 x i8> [[TMP2]]
//
v128uint4 test_insert (v128uint4 a, int idx, v64uint4 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z18test_set_v128uint4iDv32_DU8_(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <32 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[COND_I_I]] to <64 x i8>
// CHECK-NEXT:    ret <64 x i8> [[TMP1]]
//
v128uint4 test_set_v128uint4 (int idx, v64uint4 b)
{
    return set_v128uint4(idx, b);
}

// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z11test_concatDv32_DU8_S0_(
// CHECK-SAME: <32 x i8> noundef [[A0:%.*]], <32 x i8> noundef [[A1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8> [[A0]] to <8 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i8> [[A1]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> [[TMP1]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[SHUFFLE_I_I]] to <64 x i8>
// CHECK-NEXT:    ret <64 x i8> [[TMP2]]
//
v128uint4 test_concat (v64uint4 a0, v64uint4 a1)
{
  return concat( a0,  a1);
}

// v128int4

// CHECK-LABEL: define dso_local noundef <32 x i8> @_Z20test_extract_v64int4Dv64_DB8_i(
// CHECK-SAME: <64 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i32> [[COND_I_I]] to <32 x i8>
// CHECK-NEXT:    ret <32 x i8> [[TMP1]]
//
v64int4 test_extract_v64int4 (v128int4 a, int idx)
{
    return extract_v64int4(a, idx);
}

// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_DB8_iDv32_S_(
// CHECK-SAME: <64 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <32 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A]] to <16 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i8> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[COND_I_I]] to <64 x i8>
// CHECK-NEXT:    ret <64 x i8> [[TMP2]]
//
v128int4 test_insert (v128int4 a, int idx, v64int4 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z17test_set_v128int4iDv32_DB8_(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <32 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[COND_I_I]] to <64 x i8>
// CHECK-NEXT:    ret <64 x i8> [[TMP1]]
//
v128int4 test_set_v128int4 (int idx, v64int4 b)
{
    return set_v128int4(idx, b);
}

// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z11test_concatDv32_DB8_S0_(
// CHECK-SAME: <32 x i8> noundef [[A0:%.*]], <32 x i8> noundef [[A1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8> [[A0]] to <8 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i8> [[A1]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> [[TMP1]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[SHUFFLE_I_I]] to <64 x i8>
// CHECK-NEXT:    ret <64 x i8> [[TMP2]]
//
v128int4 test_concat (v64int4 a0, v64int4 a1)
{
  return concat( a0,  a1);
}

// v64uint8

// CHECK-LABEL: define dso_local noundef <32 x i8> @_Z21test_extract_v32uint8Dv64_hi(
// CHECK-SAME: <64 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i32> [[COND_I_I]] to <32 x i8>
// CHECK-NEXT:    ret <32 x i8> [[TMP1]]
//
v32uint8 test_extract_v32uint8 (v64uint8 a, int idx)
{
    return extract_v32uint8(a, idx);
}

// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_hiDv32_h(
// CHECK-SAME: <64 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <32 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A]] to <16 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i8> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[COND_I_I]] to <64 x i8>
// CHECK-NEXT:    ret <64 x i8> [[TMP2]]
//
v64uint8 test_insert (v64uint8 a, int idx, v32uint8 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z17test_set_v64uint8iDv32_h(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <32 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[COND_I_I]] to <64 x i8>
// CHECK-NEXT:    ret <64 x i8> [[TMP1]]
//
v64uint8 test_set_v64uint8 (int idx, v32uint8 b)
{
    return set_v64uint8(idx, b);
}

// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z11test_concatDv32_hS_(
// CHECK-SAME: <32 x i8> noundef [[A0:%.*]], <32 x i8> noundef [[A1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8> [[A0]] to <8 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i8> [[A1]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> [[TMP1]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[SHUFFLE_I_I]] to <64 x i8>
// CHECK-NEXT:    ret <64 x i8> [[TMP2]]
//
v64uint8 test_concat (v32uint8 a0, v32uint8 a1)
{
  return concat( a0,  a1);
}

// v64int8

// CHECK-LABEL: define dso_local noundef <32 x i8> @_Z20test_extract_v32int8Dv64_ai(
// CHECK-SAME: <64 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i32> [[COND_I_I]] to <32 x i8>
// CHECK-NEXT:    ret <32 x i8> [[TMP1]]
//
v32int8 test_extract_v32int8 (v64int8 a, int idx)
{
    return extract_v32int8(a, idx);
}

// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_aiDv32_a(
// CHECK-SAME: <64 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <32 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A]] to <16 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i8> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[COND_I_I]] to <64 x i8>
// CHECK-NEXT:    ret <64 x i8> [[TMP2]]
//
v64int8 test_insert (v64int8 a, int idx, v32int8 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z16test_set_v64int8iDv32_a(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <32 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[COND_I_I]] to <64 x i8>
// CHECK-NEXT:    ret <64 x i8> [[TMP1]]
//
v64int8 test_set_v64int8 (int idx, v32int8 b)
{
    return set_v64int8(idx, b);
}

// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z11test_concatDv32_aS_(
// CHECK-SAME: <32 x i8> noundef [[A0:%.*]], <32 x i8> noundef [[A1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8> [[A0]] to <8 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i8> [[A1]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> [[TMP1]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[SHUFFLE_I_I]] to <64 x i8>
// CHECK-NEXT:    ret <64 x i8> [[TMP2]]
//
v64int8 test_concat (v32int8 a0, v32int8 a1)
{
  return concat( a0,  a1);
}

// v32uint16

// CHECK-LABEL: define dso_local noundef <16 x i16> @_Z22test_extract_v16uint16Dv32_ti(
// CHECK-SAME: <32 x i16> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[A]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i32> [[COND_I_I]] to <16 x i16>
// CHECK-NEXT:    ret <16 x i16> [[TMP1]]
//
v16uint16 test_extract_v16uint16 (v32uint16 a, int idx)
{
    return extract_v16uint16(a, idx);
}

// CHECK-LABEL: define dso_local noundef <32 x i16> @_Z11test_insertDv32_tiDv16_t(
// CHECK-SAME: <32 x i16> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <16 x i16> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[A]] to <16 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i16> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[COND_I_I]] to <32 x i16>
// CHECK-NEXT:    ret <32 x i16> [[TMP2]]
//
v32uint16 test_insert (v32uint16 a, int idx, v16uint16 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local noundef <32 x i16> @_Z18test_set_v32uint16iDv16_t(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <16 x i16> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i16> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[COND_I_I]] to <32 x i16>
// CHECK-NEXT:    ret <32 x i16> [[TMP1]]
//
v32uint16 test_set_v32uint16 (int idx, v16uint16 b)
{
    return set_v32uint16(idx, b);
}

// CHECK-LABEL: define dso_local noundef <32 x i16> @_Z11test_concatDv16_tS_(
// CHECK-SAME: <16 x i16> noundef [[A0:%.*]], <16 x i16> noundef [[A1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i16> [[A0]] to <8 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i16> [[A1]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> [[TMP1]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[SHUFFLE_I_I]] to <32 x i16>
// CHECK-NEXT:    ret <32 x i16> [[TMP2]]
//
v32uint16 test_concat (v16uint16 a0, v16uint16 a1)
{
  return concat( a0,  a1);
}

// v32int16

// CHECK-LABEL: define dso_local noundef <16 x i16> @_Z21test_extract_v16int16Dv32_si(
// CHECK-SAME: <32 x i16> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[A]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i32> [[COND_I_I]] to <16 x i16>
// CHECK-NEXT:    ret <16 x i16> [[TMP1]]
//
v16int16 test_extract_v16int16 (v32int16 a, int idx)
{
    return extract_v16int16(a, idx);
}

// CHECK-LABEL: define dso_local noundef <32 x i16> @_Z11test_insertDv32_siDv16_s(
// CHECK-SAME: <32 x i16> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <16 x i16> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[A]] to <16 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i16> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[COND_I_I]] to <32 x i16>
// CHECK-NEXT:    ret <32 x i16> [[TMP2]]
//
v32int16 test_insert (v32int16 a, int idx, v16int16 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local noundef <32 x i16> @_Z17test_set_v32int16iDv16_s(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <16 x i16> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i16> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[COND_I_I]] to <32 x i16>
// CHECK-NEXT:    ret <32 x i16> [[TMP1]]
//
v32int16 test_set_v32int16 (int idx, v16int16 b)
{
    return set_v32int16(idx, b);
}

// CHECK-LABEL: define dso_local noundef <32 x i16> @_Z11test_concatDv16_sS_(
// CHECK-SAME: <16 x i16> noundef [[A0:%.*]], <16 x i16> noundef [[A1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i16> [[A0]] to <8 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i16> [[A1]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> [[TMP1]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[SHUFFLE_I_I]] to <32 x i16>
// CHECK-NEXT:    ret <32 x i16> [[TMP2]]
//
v32int16 test_concat (v16int16 a0, v16int16 a1)
{
  return concat( a0,  a1);
}

// v16uint32

// CHECK-LABEL: define dso_local noundef <8 x i32> @_Z21test_extract_v8uint32Dv16_ji(
// CHECK-SAME: <16 x i32> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[A]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[A]], <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    ret <8 x i32> [[COND_I_I]]
//
v8uint32 test_extract_v8uint32 (v16uint32 a, int idx)
{
    return extract_v8uint32(a, idx);
}

// CHECK-LABEL: define dso_local noundef <16 x i32> @_Z11test_insertDv16_jiDv8_j(
// CHECK-SAME: <16 x i32> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <8 x i32> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[A]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[A]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    ret <16 x i32> [[COND_I_I]]
//
v16uint32 test_insert (v16uint32 a, int idx, v8uint32 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local noundef <16 x i32> @_Z18test_set_v16uint32iDv8_j(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <8 x i32> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    ret <16 x i32> [[COND_I_I]]
//
v16uint32 test_set_v16uint32 (int idx, v8uint32 b)
{
    return set_v16uint32(idx, b);
}

// CHECK-LABEL: define dso_local noundef <16 x i32> @_Z11test_concatDv8_jS_(
// CHECK-SAME: <8 x i32> noundef [[A0:%.*]], <8 x i32> noundef [[A1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[A0]], <8 x i32> [[A1]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i32> [[SHUFFLE_I_I]]
//
v16uint32 test_concat (v8uint32 a0, v8uint32 a1)
{
  return concat( a0,  a1);
}

// v16int32

// CHECK-LABEL: define dso_local noundef <8 x i32> @_Z20test_extract_v8int32Dv16_ii(
// CHECK-SAME: <16 x i32> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[A]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[A]], <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    ret <8 x i32> [[COND_I_I]]
//
v8int32 test_extract_v8int32 (v16int32 a, int idx)
{
    return extract_v8int32(a, idx);
}

// CHECK-LABEL: define dso_local noundef <16 x i32> @_Z11test_insertDv16_iiDv8_i(
// CHECK-SAME: <16 x i32> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <8 x i32> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[A]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[A]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    ret <16 x i32> [[COND_I_I]]
//
v16int32 test_insert (v16int32 a, int idx, v8int32 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local noundef <16 x i32> @_Z17test_set_v16int32iDv8_i(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <8 x i32> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    ret <16 x i32> [[COND_I_I]]
//
v16int32 test_set_v16int32 (int idx, v8int32 b)
{
    return set_v16int32(idx, b);
}

// CHECK-LABEL: define dso_local noundef <16 x i32> @_Z11test_concatDv8_iS_(
// CHECK-SAME: <8 x i32> noundef [[A0:%.*]], <8 x i32> noundef [[A1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[A0]], <8 x i32> [[A1]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i32> [[SHUFFLE_I_I]]
//
v16int32 test_concat (v8int32 a0, v8int32 a1)
{
  return concat( a0,  a1);
}

// v32bfloat16

// CHECK-LABEL: define dso_local noundef <16 x bfloat> @_Z24test_extract_v16bfloat16Dv32_8bfloat16i(
// CHECK-SAME: <32 x bfloat> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x bfloat> [[A]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i32> [[COND_I_I]] to <16 x bfloat>
// CHECK-NEXT:    ret <16 x bfloat> [[TMP1]]
//
v16bfloat16 test_extract_v16bfloat16 (v32bfloat16 a, int idx)
{
    return extract_v16bfloat16(a, idx);
}

// CHECK-LABEL: define dso_local noundef <32 x bfloat> @_Z11test_insertDv32_8bfloat16iDv16_S_(
// CHECK-SAME: <32 x bfloat> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <16 x bfloat> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x bfloat> [[A]] to <16 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x bfloat> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[COND_I_I]] to <32 x bfloat>
// CHECK-NEXT:    ret <32 x bfloat> [[TMP2]]
//
v32bfloat16 test_insert (v32bfloat16 a, int idx, v16bfloat16 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local noundef <32 x bfloat> @_Z20test_set_v32bfloat16iDv16_8bfloat16(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <16 x bfloat> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x bfloat> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[COND_I_I]] to <32 x bfloat>
// CHECK-NEXT:    ret <32 x bfloat> [[TMP1]]
//
v32bfloat16 test_set_v32bfloat16 (int idx, v16bfloat16 b)
{
    return set_v32bfloat16(idx, b);
}

// CHECK-LABEL: define dso_local noundef <32 x bfloat> @_Z11test_concatDv16_8bfloat16S0_(
// CHECK-SAME: <16 x bfloat> noundef [[A0:%.*]], <16 x bfloat> noundef [[A1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x bfloat> [[A0]] to <8 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x bfloat> [[A1]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> [[TMP1]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[SHUFFLE_I_I]] to <32 x bfloat>
// CHECK-NEXT:    ret <32 x bfloat> [[TMP2]]
//
v32bfloat16 test_concat (v16bfloat16 a0, v16bfloat16 a1)
{
  return concat( a0,  a1);
}

// v16float

// CHECK-LABEL: define dso_local noundef <8 x float> @_Z20test_extract_v8floatDv16_fi(
// CHECK-SAME: <16 x float> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[A]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i32> [[COND_I_I]] to <8 x float>
// CHECK-NEXT:    ret <8 x float> [[TMP1]]
//
v8float test_extract_v8float (v16float a, int idx)
{
    return extract_v8float(a, idx);
}

// CHECK-LABEL: define dso_local noundef <16 x float> @_Z11test_insertDv16_fiDv8_f(
// CHECK-SAME: <16 x float> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <8 x float> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[A]] to <16 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x float> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[COND_I_I]] to <16 x float>
// CHECK-NEXT:    ret <16 x float> [[TMP2]]
//
v16float test_insert (v16float a, int idx, v8float b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local noundef <16 x float> @_Z17test_set_v16floatiDv8_f(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <8 x float> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x float> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[COND_I_I]] to <16 x float>
// CHECK-NEXT:    ret <16 x float> [[TMP1]]
//
v16float test_set_v16float (int idx, v8float b)
{
    return set_v16float(idx, b);
}

// CHECK-LABEL: define dso_local noundef <16 x float> @_Z11test_concatDv8_fS_(
// CHECK-SAME: <8 x float> noundef [[A0:%.*]], <8 x float> noundef [[A1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_UNCASTED_I:%.*]] = shufflevector <8 x float> [[A0]], <8 x float> [[A1]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x float> [[SHUFFLE_I_UNCASTED_I]]
//
v16float test_concat (v8float a0, v8float a1)
{
  return concat( a0,  a1);
}

// v256uint4

// CHECK-LABEL: define dso_local noundef <32 x i8> @_Z21test_extract_v64uint4Dv128_DU8_i(
// CHECK-SAME: <128 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A]] to <32 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[COND9_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE2_I_I]], <8 x i32> [[SHUFFLE3_I_I]]
// CHECK-NEXT:    [[AND10_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I:%.*]] = icmp eq i32 [[AND10_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I]], <8 x i32> [[COND_I_I]], <8 x i32> [[COND9_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i32> [[COND15_I_I]] to <32 x i8>
// CHECK-NEXT:    ret <32 x i8> [[TMP1]]
//
v64uint4 test_extract_v64uint4 (v256uint4 a, int idx)
{
    return extract_v64uint4(a, idx);
}

// CHECK-LABEL: define dso_local noundef <128 x i8> @_Z11test_insertDv128_DU8_iDv32_S_(
// CHECK-SAME: <128 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <32 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A]] to <32 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i8> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE2_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE7_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE3_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE5_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE1_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE4_I_I:%.*]] = shufflevector <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[TMP0]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE4_I_I]], <32 x i32> [[SHUFFLE5_I_I]]
// CHECK-NEXT:    [[COND13_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE6_I_I]], <32 x i32> [[SHUFFLE7_I_I]]
// CHECK-NEXT:    [[AND14_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL15_NOT_I_I:%.*]] = icmp eq i32 [[AND14_I_I]], 0
// CHECK-NEXT:    [[COND19_I_I:%.*]] = select i1 [[TOBOOL15_NOT_I_I]], <32 x i32> [[COND_I_I]], <32 x i32> [[COND13_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[COND19_I_I]] to <128 x i8>
// CHECK-NEXT:    ret <128 x i8> [[TMP2]]
//
v256uint4 test_insert (v256uint4 a, int idx, v64uint4 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local noundef <128 x i8> @_Z18test_set_v256uint4iDv32_DU8_(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <32 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[COND9_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE2_I_I]], <32 x i32> [[SHUFFLE3_I_I]]
// CHECK-NEXT:    [[AND10_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I:%.*]] = icmp eq i32 [[AND10_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I]], <32 x i32> [[COND_I_I]], <32 x i32> [[COND9_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i32> [[COND15_I_I]] to <128 x i8>
// CHECK-NEXT:    ret <128 x i8> [[TMP1]]
//
v256uint4 test_set_v256uint4 (int idx, v64uint4 b)
{
    return set_v256uint4(idx, b);
}

// CHECK-LABEL: define dso_local noundef <128 x i8> @_Z11test_concatDv32_DU8_S0_S0_S0_(
// CHECK-SAME: <32 x i8> noundef [[A0:%.*]], <32 x i8> noundef [[A1:%.*]], <32 x i8> noundef [[A2:%.*]], <32 x i8> noundef [[A3:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8> [[A0]] to <8 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i8> [[A1]] to <8 x i32>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i8> [[A2]] to <8 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <32 x i8> [[A3]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> [[TMP1]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP2]], <8 x i32> [[TMP3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I]] to <128 x i8>
// CHECK-NEXT:    ret <128 x i8> [[TMP4]]
//
v256uint4 test_concat (v64uint4 a0, v64uint4 a1, v64uint4 a2, v64uint4 a3)
{
  return concat( a0,  a1,  a2,  a3);
}

// v256uint4

// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z22test_extract_v128uint4Dv128_DU8_i(
// CHECK-SAME: <128 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A]] to <32 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[COND_I_I]] to <64 x i8>
// CHECK-NEXT:    ret <64 x i8> [[TMP1]]
//
v128uint4 test_extract_v128uint4 (v256uint4 a, int idx)
{
    return extract_v128uint4(a, idx);
}

// CHECK-LABEL: define dso_local noundef <128 x i8> @_Z11test_insertDv128_DU8_iDv64_S_(
// CHECK-SAME: <128 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <64 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A]] to <32 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <64 x i8> [[B]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[TMP0]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE1_I_I]], <32 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[COND_I_I]] to <128 x i8>
// CHECK-NEXT:    ret <128 x i8> [[TMP2]]
//
v256uint4 test_insert (v256uint4 a, int idx, v128uint4 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local noundef <128 x i8> @_Z18test_set_v256uint4iDv64_DU8_(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <64 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[B]] to <16 x i32>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i32> [[COND_I_I]] to <128 x i8>
// CHECK-NEXT:    ret <128 x i8> [[TMP1]]
//
v256uint4 test_set_v256uint4 (int idx, v128uint4 b)
{
    return set_v256uint4(idx, b);
}

// CHECK-LABEL: define dso_local noundef <128 x i8> @_Z11test_concatDv64_DU8_S0_(
// CHECK-SAME: <64 x i8> noundef [[A0:%.*]], <64 x i8> noundef [[A1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A0]] to <16 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <64 x i8> [[A1]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE_I_I]] to <128 x i8>
// CHECK-NEXT:    ret <128 x i8> [[TMP2]]
//
v256uint4 test_concat (v128uint4 a0, v128uint4 a1)
{
  return concat( a0,  a1);
}

// v256int4

// CHECK-LABEL: define dso_local noundef <32 x i8> @_Z20test_extract_v64int4Dv128_DB8_i(
// CHECK-SAME: <128 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A]] to <32 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[COND9_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE2_I_I]], <8 x i32> [[SHUFFLE3_I_I]]
// CHECK-NEXT:    [[AND10_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I:%.*]] = icmp eq i32 [[AND10_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I]], <8 x i32> [[COND_I_I]], <8 x i32> [[COND9_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i32> [[COND15_I_I]] to <32 x i8>
// CHECK-NEXT:    ret <32 x i8> [[TMP1]]
//
v64int4 test_extract_v64int4 (v256int4 a, int idx)
{
    return extract_v64int4(a, idx);
}

// CHECK-LABEL: define dso_local noundef <128 x i8> @_Z11test_insertDv128_DB8_iDv32_S_(
// CHECK-SAME: <128 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <32 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A]] to <32 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i8> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE2_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE7_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE3_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE5_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE1_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE4_I_I:%.*]] = shufflevector <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[TMP0]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE4_I_I]], <32 x i32> [[SHUFFLE5_I_I]]
// CHECK-NEXT:    [[COND13_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE6_I_I]], <32 x i32> [[SHUFFLE7_I_I]]
// CHECK-NEXT:    [[AND14_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL15_NOT_I_I:%.*]] = icmp eq i32 [[AND14_I_I]], 0
// CHECK-NEXT:    [[COND19_I_I:%.*]] = select i1 [[TOBOOL15_NOT_I_I]], <32 x i32> [[COND_I_I]], <32 x i32> [[COND13_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[COND19_I_I]] to <128 x i8>
// CHECK-NEXT:    ret <128 x i8> [[TMP2]]
//
v256int4 test_insert (v256int4 a, int idx, v64int4 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local noundef <128 x i8> @_Z17test_set_v256int4iDv32_DB8_(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <32 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[COND9_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE2_I_I]], <32 x i32> [[SHUFFLE3_I_I]]
// CHECK-NEXT:    [[AND10_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I:%.*]] = icmp eq i32 [[AND10_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I]], <32 x i32> [[COND_I_I]], <32 x i32> [[COND9_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i32> [[COND15_I_I]] to <128 x i8>
// CHECK-NEXT:    ret <128 x i8> [[TMP1]]
//
v256int4 test_set_v256int4 (int idx, v64int4 b)
{
    return set_v256int4(idx, b);
}

// CHECK-LABEL: define dso_local noundef <128 x i8> @_Z11test_concatDv32_DB8_S0_S0_S0_(
// CHECK-SAME: <32 x i8> noundef [[A0:%.*]], <32 x i8> noundef [[A1:%.*]], <32 x i8> noundef [[A2:%.*]], <32 x i8> noundef [[A3:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8> [[A0]] to <8 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i8> [[A1]] to <8 x i32>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i8> [[A2]] to <8 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <32 x i8> [[A3]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> [[TMP1]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP2]], <8 x i32> [[TMP3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I]] to <128 x i8>
// CHECK-NEXT:    ret <128 x i8> [[TMP4]]
//
v256int4 test_concat (v64int4 a0, v64int4 a1, v64int4 a2, v64int4 a3)
{
  return concat( a0,  a1,  a2,  a3);
}

// v256int4

// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z21test_extract_v128int4Dv128_DB8_i(
// CHECK-SAME: <128 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A]] to <32 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[COND_I_I]] to <64 x i8>
// CHECK-NEXT:    ret <64 x i8> [[TMP1]]
//
v128int4 test_extract_v128int4 (v256int4 a, int idx)
{
    return extract_v128int4(a, idx);
}

// CHECK-LABEL: define dso_local noundef <128 x i8> @_Z11test_insertDv128_DB8_iDv64_S_(
// CHECK-SAME: <128 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <64 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A]] to <32 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <64 x i8> [[B]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[TMP0]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE1_I_I]], <32 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[COND_I_I]] to <128 x i8>
// CHECK-NEXT:    ret <128 x i8> [[TMP2]]
//
v256int4 test_insert (v256int4 a, int idx, v128int4 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local noundef <128 x i8> @_Z17test_set_v256int4iDv64_DB8_(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <64 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[B]] to <16 x i32>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i32> [[COND_I_I]] to <128 x i8>
// CHECK-NEXT:    ret <128 x i8> [[TMP1]]
//
v256int4 test_set_v256int4 (int idx, v128int4 b)
{
    return set_v256int4(idx, b);
}

// CHECK-LABEL: define dso_local noundef <128 x i8> @_Z11test_concatDv64_DB8_S0_(
// CHECK-SAME: <64 x i8> noundef [[A0:%.*]], <64 x i8> noundef [[A1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A0]] to <16 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <64 x i8> [[A1]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE_I_I]] to <128 x i8>
// CHECK-NEXT:    ret <128 x i8> [[TMP2]]
//
v256int4 test_concat (v128int4 a0, v128int4 a1)
{
  return concat( a0,  a1);
}

// v128uint8

// CHECK-LABEL: define dso_local noundef <32 x i8> @_Z21test_extract_v32uint8Dv128_hi(
// CHECK-SAME: <128 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A]] to <32 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[COND9_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE2_I_I]], <8 x i32> [[SHUFFLE3_I_I]]
// CHECK-NEXT:    [[AND10_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I:%.*]] = icmp eq i32 [[AND10_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I]], <8 x i32> [[COND_I_I]], <8 x i32> [[COND9_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i32> [[COND15_I_I]] to <32 x i8>
// CHECK-NEXT:    ret <32 x i8> [[TMP1]]
//
v32uint8 test_extract_v32uint8 (v128uint8 a, int idx)
{
    return extract_v32uint8(a, idx);
}

// CHECK-LABEL: define dso_local noundef <128 x i8> @_Z11test_insertDv128_hiDv32_h(
// CHECK-SAME: <128 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <32 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A]] to <32 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i8> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE2_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE7_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE3_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE5_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE1_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE4_I_I:%.*]] = shufflevector <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[TMP0]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE4_I_I]], <32 x i32> [[SHUFFLE5_I_I]]
// CHECK-NEXT:    [[COND13_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE6_I_I]], <32 x i32> [[SHUFFLE7_I_I]]
// CHECK-NEXT:    [[AND14_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL15_NOT_I_I:%.*]] = icmp eq i32 [[AND14_I_I]], 0
// CHECK-NEXT:    [[COND19_I_I:%.*]] = select i1 [[TOBOOL15_NOT_I_I]], <32 x i32> [[COND_I_I]], <32 x i32> [[COND13_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[COND19_I_I]] to <128 x i8>
// CHECK-NEXT:    ret <128 x i8> [[TMP2]]
//
v128uint8 test_insert (v128uint8 a, int idx, v32uint8 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local noundef <128 x i8> @_Z18test_set_v128uint8iDv32_h(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <32 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[COND9_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE2_I_I]], <32 x i32> [[SHUFFLE3_I_I]]
// CHECK-NEXT:    [[AND10_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I:%.*]] = icmp eq i32 [[AND10_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I]], <32 x i32> [[COND_I_I]], <32 x i32> [[COND9_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i32> [[COND15_I_I]] to <128 x i8>
// CHECK-NEXT:    ret <128 x i8> [[TMP1]]
//
v128uint8 test_set_v128uint8 (int idx, v32uint8 b)
{
    return set_v128uint8(idx, b);
}

// CHECK-LABEL: define dso_local noundef <128 x i8> @_Z11test_concatDv32_hS_S_S_(
// CHECK-SAME: <32 x i8> noundef [[A0:%.*]], <32 x i8> noundef [[A1:%.*]], <32 x i8> noundef [[A2:%.*]], <32 x i8> noundef [[A3:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8> [[A0]] to <8 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i8> [[A1]] to <8 x i32>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i8> [[A2]] to <8 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <32 x i8> [[A3]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> [[TMP1]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP2]], <8 x i32> [[TMP3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I]] to <128 x i8>
// CHECK-NEXT:    ret <128 x i8> [[TMP4]]
//
v128uint8 test_concat (v32uint8 a0, v32uint8 a1, v32uint8 a2, v32uint8 a3)
{
  return concat( a0,  a1,  a2,  a3);
}

// v128uint8

// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z21test_extract_v64uint8Dv128_hi(
// CHECK-SAME: <128 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A]] to <32 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[COND_I_I]] to <64 x i8>
// CHECK-NEXT:    ret <64 x i8> [[TMP1]]
//
v64uint8 test_extract_v64uint8 (v128uint8 a, int idx)
{
    return extract_v64uint8(a, idx);
}

// CHECK-LABEL: define dso_local noundef <128 x i8> @_Z11test_insertDv128_hiDv64_h(
// CHECK-SAME: <128 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <64 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A]] to <32 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <64 x i8> [[B]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[TMP0]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE1_I_I]], <32 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[COND_I_I]] to <128 x i8>
// CHECK-NEXT:    ret <128 x i8> [[TMP2]]
//
v128uint8 test_insert (v128uint8 a, int idx, v64uint8 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local noundef <128 x i8> @_Z18test_set_v128uint8iDv64_h(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <64 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[B]] to <16 x i32>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i32> [[COND_I_I]] to <128 x i8>
// CHECK-NEXT:    ret <128 x i8> [[TMP1]]
//
v128uint8 test_set_v128uint8 (int idx, v64uint8 b)
{
    return set_v128uint8(idx, b);
}

// CHECK-LABEL: define dso_local noundef <128 x i8> @_Z11test_concatDv64_hS_(
// CHECK-SAME: <64 x i8> noundef [[A0:%.*]], <64 x i8> noundef [[A1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A0]] to <16 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <64 x i8> [[A1]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE_I_I]] to <128 x i8>
// CHECK-NEXT:    ret <128 x i8> [[TMP2]]
//
v128uint8 test_concat (v64uint8 a0, v64uint8 a1)
{
  return concat( a0,  a1);
}

// v128int8

// CHECK-LABEL: define dso_local noundef <32 x i8> @_Z20test_extract_v32int8Dv128_ai(
// CHECK-SAME: <128 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A]] to <32 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[COND9_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE2_I_I]], <8 x i32> [[SHUFFLE3_I_I]]
// CHECK-NEXT:    [[AND10_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I:%.*]] = icmp eq i32 [[AND10_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I]], <8 x i32> [[COND_I_I]], <8 x i32> [[COND9_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i32> [[COND15_I_I]] to <32 x i8>
// CHECK-NEXT:    ret <32 x i8> [[TMP1]]
//
v32int8 test_extract_v32int8 (v128int8 a, int idx)
{
    return extract_v32int8(a, idx);
}

// CHECK-LABEL: define dso_local noundef <128 x i8> @_Z11test_insertDv128_aiDv32_a(
// CHECK-SAME: <128 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <32 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A]] to <32 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i8> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE2_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE7_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE3_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE5_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE1_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE4_I_I:%.*]] = shufflevector <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[TMP0]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE4_I_I]], <32 x i32> [[SHUFFLE5_I_I]]
// CHECK-NEXT:    [[COND13_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE6_I_I]], <32 x i32> [[SHUFFLE7_I_I]]
// CHECK-NEXT:    [[AND14_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL15_NOT_I_I:%.*]] = icmp eq i32 [[AND14_I_I]], 0
// CHECK-NEXT:    [[COND19_I_I:%.*]] = select i1 [[TOBOOL15_NOT_I_I]], <32 x i32> [[COND_I_I]], <32 x i32> [[COND13_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[COND19_I_I]] to <128 x i8>
// CHECK-NEXT:    ret <128 x i8> [[TMP2]]
//
v128int8 test_insert (v128int8 a, int idx, v32int8 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local noundef <128 x i8> @_Z17test_set_v128int8iDv32_a(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <32 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[COND9_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE2_I_I]], <32 x i32> [[SHUFFLE3_I_I]]
// CHECK-NEXT:    [[AND10_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I:%.*]] = icmp eq i32 [[AND10_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I]], <32 x i32> [[COND_I_I]], <32 x i32> [[COND9_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i32> [[COND15_I_I]] to <128 x i8>
// CHECK-NEXT:    ret <128 x i8> [[TMP1]]
//
v128int8 test_set_v128int8 (int idx, v32int8 b)
{
    return set_v128int8(idx, b);
}

// CHECK-LABEL: define dso_local noundef <128 x i8> @_Z11test_concatDv32_aS_S_S_(
// CHECK-SAME: <32 x i8> noundef [[A0:%.*]], <32 x i8> noundef [[A1:%.*]], <32 x i8> noundef [[A2:%.*]], <32 x i8> noundef [[A3:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8> [[A0]] to <8 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i8> [[A1]] to <8 x i32>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i8> [[A2]] to <8 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <32 x i8> [[A3]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> [[TMP1]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP2]], <8 x i32> [[TMP3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I]] to <128 x i8>
// CHECK-NEXT:    ret <128 x i8> [[TMP4]]
//
v128int8 test_concat (v32int8 a0, v32int8 a1, v32int8 a2, v32int8 a3)
{
  return concat( a0,  a1,  a2,  a3);
}

// v128int8

// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z20test_extract_v64int8Dv128_ai(
// CHECK-SAME: <128 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A]] to <32 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[COND_I_I]] to <64 x i8>
// CHECK-NEXT:    ret <64 x i8> [[TMP1]]
//
v64int8 test_extract_v64int8 (v128int8 a, int idx)
{
    return extract_v64int8(a, idx);
}

// CHECK-LABEL: define dso_local noundef <128 x i8> @_Z11test_insertDv128_aiDv64_a(
// CHECK-SAME: <128 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <64 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <128 x i8> [[A]] to <32 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <64 x i8> [[B]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[TMP0]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE1_I_I]], <32 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[COND_I_I]] to <128 x i8>
// CHECK-NEXT:    ret <128 x i8> [[TMP2]]
//
v128int8 test_insert (v128int8 a, int idx, v64int8 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local noundef <128 x i8> @_Z17test_set_v128int8iDv64_a(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <64 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[B]] to <16 x i32>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i32> [[COND_I_I]] to <128 x i8>
// CHECK-NEXT:    ret <128 x i8> [[TMP1]]
//
v128int8 test_set_v128int8 (int idx, v64int8 b)
{
    return set_v128int8(idx, b);
}

// CHECK-LABEL: define dso_local noundef <128 x i8> @_Z11test_concatDv64_aS_(
// CHECK-SAME: <64 x i8> noundef [[A0:%.*]], <64 x i8> noundef [[A1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A0]] to <16 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <64 x i8> [[A1]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE_I_I]] to <128 x i8>
// CHECK-NEXT:    ret <128 x i8> [[TMP2]]
//
v128int8 test_concat (v64int8 a0, v64int8 a1)
{
  return concat( a0,  a1);
}

// v64uint16

// CHECK-LABEL: define dso_local noundef <16 x i16> @_Z22test_extract_v16uint16Dv64_ti(
// CHECK-SAME: <64 x i16> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i16> [[A]] to <32 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[COND9_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE2_I_I]], <8 x i32> [[SHUFFLE3_I_I]]
// CHECK-NEXT:    [[AND10_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I:%.*]] = icmp eq i32 [[AND10_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I]], <8 x i32> [[COND_I_I]], <8 x i32> [[COND9_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i32> [[COND15_I_I]] to <16 x i16>
// CHECK-NEXT:    ret <16 x i16> [[TMP1]]
//
v16uint16 test_extract_v16uint16 (v64uint16 a, int idx)
{
    return extract_v16uint16(a, idx);
}

// CHECK-LABEL: define dso_local noundef <64 x i16> @_Z11test_insertDv64_tiDv16_t(
// CHECK-SAME: <64 x i16> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <16 x i16> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i16> [[A]] to <32 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i16> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE2_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE7_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE3_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE5_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE1_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE4_I_I:%.*]] = shufflevector <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[TMP0]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE4_I_I]], <32 x i32> [[SHUFFLE5_I_I]]
// CHECK-NEXT:    [[COND13_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE6_I_I]], <32 x i32> [[SHUFFLE7_I_I]]
// CHECK-NEXT:    [[AND14_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL15_NOT_I_I:%.*]] = icmp eq i32 [[AND14_I_I]], 0
// CHECK-NEXT:    [[COND19_I_I:%.*]] = select i1 [[TOBOOL15_NOT_I_I]], <32 x i32> [[COND_I_I]], <32 x i32> [[COND13_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[COND19_I_I]] to <64 x i16>
// CHECK-NEXT:    ret <64 x i16> [[TMP2]]
//
v64uint16 test_insert (v64uint16 a, int idx, v16uint16 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local noundef <64 x i16> @_Z18test_set_v64uint16iDv16_t(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <16 x i16> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i16> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[COND9_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE2_I_I]], <32 x i32> [[SHUFFLE3_I_I]]
// CHECK-NEXT:    [[AND10_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I:%.*]] = icmp eq i32 [[AND10_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I]], <32 x i32> [[COND_I_I]], <32 x i32> [[COND9_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i32> [[COND15_I_I]] to <64 x i16>
// CHECK-NEXT:    ret <64 x i16> [[TMP1]]
//
v64uint16 test_set_v64uint16 (int idx, v16uint16 b)
{
    return set_v64uint16(idx, b);
}

// CHECK-LABEL: define dso_local noundef <64 x i16> @_Z11test_concatDv16_tS_S_S_(
// CHECK-SAME: <16 x i16> noundef [[A0:%.*]], <16 x i16> noundef [[A1:%.*]], <16 x i16> noundef [[A2:%.*]], <16 x i16> noundef [[A3:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i16> [[A0]] to <8 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i16> [[A1]] to <8 x i32>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i16> [[A2]] to <8 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <16 x i16> [[A3]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> [[TMP1]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP2]], <8 x i32> [[TMP3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I]] to <64 x i16>
// CHECK-NEXT:    ret <64 x i16> [[TMP4]]
//
v64uint16 test_concat (v16uint16 a0, v16uint16 a1, v16uint16 a2, v16uint16 a3)
{
  return concat( a0,  a1,  a2,  a3);
}

// v64uint16

// CHECK-LABEL: define dso_local noundef <32 x i16> @_Z22test_extract_v32uint16Dv64_ti(
// CHECK-SAME: <64 x i16> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i16> [[A]] to <32 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[COND_I_I]] to <32 x i16>
// CHECK-NEXT:    ret <32 x i16> [[TMP1]]
//
v32uint16 test_extract_v32uint16 (v64uint16 a, int idx)
{
    return extract_v32uint16(a, idx);
}

// CHECK-LABEL: define dso_local noundef <64 x i16> @_Z11test_insertDv64_tiDv32_t(
// CHECK-SAME: <64 x i16> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <32 x i16> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i16> [[A]] to <32 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i16> [[B]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[TMP0]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE1_I_I]], <32 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[COND_I_I]] to <64 x i16>
// CHECK-NEXT:    ret <64 x i16> [[TMP2]]
//
v64uint16 test_insert (v64uint16 a, int idx, v32uint16 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local noundef <64 x i16> @_Z18test_set_v64uint16iDv32_t(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <32 x i16> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[B]] to <16 x i32>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i32> [[COND_I_I]] to <64 x i16>
// CHECK-NEXT:    ret <64 x i16> [[TMP1]]
//
v64uint16 test_set_v64uint16 (int idx, v32uint16 b)
{
    return set_v64uint16(idx, b);
}

// CHECK-LABEL: define dso_local noundef <64 x i16> @_Z11test_concatDv32_tS_(
// CHECK-SAME: <32 x i16> noundef [[A0:%.*]], <32 x i16> noundef [[A1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[A0]] to <16 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i16> [[A1]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE_I_I]] to <64 x i16>
// CHECK-NEXT:    ret <64 x i16> [[TMP2]]
//
v64uint16 test_concat (v32uint16 a0, v32uint16 a1)
{
  return concat( a0,  a1);
}

// v64int16

// CHECK-LABEL: define dso_local noundef <16 x i16> @_Z21test_extract_v16int16Dv64_si(
// CHECK-SAME: <64 x i16> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i16> [[A]] to <32 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[COND9_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE2_I_I]], <8 x i32> [[SHUFFLE3_I_I]]
// CHECK-NEXT:    [[AND10_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I:%.*]] = icmp eq i32 [[AND10_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I]], <8 x i32> [[COND_I_I]], <8 x i32> [[COND9_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i32> [[COND15_I_I]] to <16 x i16>
// CHECK-NEXT:    ret <16 x i16> [[TMP1]]
//
v16int16 test_extract_v16int16 (v64int16 a, int idx)
{
    return extract_v16int16(a, idx);
}

// CHECK-LABEL: define dso_local noundef <64 x i16> @_Z11test_insertDv64_siDv16_s(
// CHECK-SAME: <64 x i16> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <16 x i16> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i16> [[A]] to <32 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i16> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE2_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE7_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE3_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE5_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE1_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE4_I_I:%.*]] = shufflevector <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[TMP0]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE4_I_I]], <32 x i32> [[SHUFFLE5_I_I]]
// CHECK-NEXT:    [[COND13_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE6_I_I]], <32 x i32> [[SHUFFLE7_I_I]]
// CHECK-NEXT:    [[AND14_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL15_NOT_I_I:%.*]] = icmp eq i32 [[AND14_I_I]], 0
// CHECK-NEXT:    [[COND19_I_I:%.*]] = select i1 [[TOBOOL15_NOT_I_I]], <32 x i32> [[COND_I_I]], <32 x i32> [[COND13_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[COND19_I_I]] to <64 x i16>
// CHECK-NEXT:    ret <64 x i16> [[TMP2]]
//
v64int16 test_insert (v64int16 a, int idx, v16int16 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local noundef <64 x i16> @_Z17test_set_v64int16iDv16_s(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <16 x i16> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i16> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[COND9_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE2_I_I]], <32 x i32> [[SHUFFLE3_I_I]]
// CHECK-NEXT:    [[AND10_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I:%.*]] = icmp eq i32 [[AND10_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I]], <32 x i32> [[COND_I_I]], <32 x i32> [[COND9_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i32> [[COND15_I_I]] to <64 x i16>
// CHECK-NEXT:    ret <64 x i16> [[TMP1]]
//
v64int16 test_set_v64int16 (int idx, v16int16 b)
{
    return set_v64int16(idx, b);
}

// CHECK-LABEL: define dso_local noundef <64 x i16> @_Z11test_concatDv16_sS_S_S_(
// CHECK-SAME: <16 x i16> noundef [[A0:%.*]], <16 x i16> noundef [[A1:%.*]], <16 x i16> noundef [[A2:%.*]], <16 x i16> noundef [[A3:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i16> [[A0]] to <8 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i16> [[A1]] to <8 x i32>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i16> [[A2]] to <8 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <16 x i16> [[A3]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> [[TMP1]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP2]], <8 x i32> [[TMP3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I]] to <64 x i16>
// CHECK-NEXT:    ret <64 x i16> [[TMP4]]
//
v64int16 test_concat (v16int16 a0, v16int16 a1, v16int16 a2, v16int16 a3)
{
  return concat( a0,  a1,  a2,  a3);
}

// v64int16

// CHECK-LABEL: define dso_local noundef <32 x i16> @_Z21test_extract_v32int16Dv64_si(
// CHECK-SAME: <64 x i16> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i16> [[A]] to <32 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[COND_I_I]] to <32 x i16>
// CHECK-NEXT:    ret <32 x i16> [[TMP1]]
//
v32int16 test_extract_v32int16 (v64int16 a, int idx)
{
    return extract_v32int16(a, idx);
}

// CHECK-LABEL: define dso_local noundef <64 x i16> @_Z11test_insertDv64_siDv32_s(
// CHECK-SAME: <64 x i16> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <32 x i16> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i16> [[A]] to <32 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i16> [[B]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[TMP0]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE1_I_I]], <32 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[COND_I_I]] to <64 x i16>
// CHECK-NEXT:    ret <64 x i16> [[TMP2]]
//
v64int16 test_insert (v64int16 a, int idx, v32int16 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local noundef <64 x i16> @_Z17test_set_v64int16iDv32_s(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <32 x i16> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[B]] to <16 x i32>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i32> [[COND_I_I]] to <64 x i16>
// CHECK-NEXT:    ret <64 x i16> [[TMP1]]
//
v64int16 test_set_v64int16 (int idx, v32int16 b)
{
    return set_v64int16(idx, b);
}

// CHECK-LABEL: define dso_local noundef <64 x i16> @_Z11test_concatDv32_sS_(
// CHECK-SAME: <32 x i16> noundef [[A0:%.*]], <32 x i16> noundef [[A1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[A0]] to <16 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i16> [[A1]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE_I_I]] to <64 x i16>
// CHECK-NEXT:    ret <64 x i16> [[TMP2]]
//
v64int16 test_concat (v32int16 a0, v32int16 a1)
{
  return concat( a0,  a1);
}

// v32uint32

// CHECK-LABEL: define dso_local noundef <8 x i32> @_Z21test_extract_v8uint32Dv32_ji(
// CHECK-SAME: <32 x i32> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[COND9_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE2_I_I]], <8 x i32> [[SHUFFLE3_I_I]]
// CHECK-NEXT:    [[AND10_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I:%.*]] = icmp eq i32 [[AND10_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I]], <8 x i32> [[COND_I_I]], <8 x i32> [[COND9_I_I]]
// CHECK-NEXT:    ret <8 x i32> [[COND15_I_I]]
//
v8uint32 test_extract_v8uint32 (v32uint32 a, int idx)
{
    return extract_v8uint32(a, idx);
}

// CHECK-LABEL: define dso_local noundef <32 x i32> @_Z11test_insertDv32_jiDv8_j(
// CHECK-SAME: <32 x i32> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <8 x i32> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> [[SHUFFLE2_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE7_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> [[SHUFFLE3_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE5_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> [[SHUFFLE1_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE4_I_I:%.*]] = shufflevector <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[A]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE4_I_I]], <32 x i32> [[SHUFFLE5_I_I]]
// CHECK-NEXT:    [[COND13_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE6_I_I]], <32 x i32> [[SHUFFLE7_I_I]]
// CHECK-NEXT:    [[AND14_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL15_NOT_I_I:%.*]] = icmp eq i32 [[AND14_I_I]], 0
// CHECK-NEXT:    [[COND19_I_I:%.*]] = select i1 [[TOBOOL15_NOT_I_I]], <32 x i32> [[COND_I_I]], <32 x i32> [[COND13_I_I]]
// CHECK-NEXT:    ret <32 x i32> [[COND19_I_I]]
//
v32uint32 test_insert (v32uint32 a, int idx, v8uint32 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local noundef <32 x i32> @_Z18test_set_v32uint32iDv8_j(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <8 x i32> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[COND9_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE2_I_I]], <32 x i32> [[SHUFFLE3_I_I]]
// CHECK-NEXT:    [[AND10_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I:%.*]] = icmp eq i32 [[AND10_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I]], <32 x i32> [[COND_I_I]], <32 x i32> [[COND9_I_I]]
// CHECK-NEXT:    ret <32 x i32> [[COND15_I_I]]
//
v32uint32 test_set_v32uint32 (int idx, v8uint32 b)
{
    return set_v32uint32(idx, b);
}

// CHECK-LABEL: define dso_local noundef <32 x i32> @_Z11test_concatDv8_jS_S_S_(
// CHECK-SAME: <8 x i32> noundef [[A0:%.*]], <8 x i32> noundef [[A1:%.*]], <8 x i32> noundef [[A2:%.*]], <8 x i32> noundef [[A3:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[A0]], <8 x i32> [[A1]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[A2]], <8 x i32> [[A3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    ret <32 x i32> [[SHUFFLE2_I_I]]
//
v32uint32 test_concat (v8uint32 a0, v8uint32 a1, v8uint32 a2, v8uint32 a3)
{
  return concat( a0,  a1,  a2,  a3);
}

// v32uint32

// CHECK-LABEL: define dso_local noundef <16 x i32> @_Z22test_extract_v16uint32Dv32_ji(
// CHECK-SAME: <32 x i32> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    ret <16 x i32> [[COND_I_I]]
//
v16uint32 test_extract_v16uint32 (v32uint32 a, int idx)
{
    return extract_v16uint32(a, idx);
}

// CHECK-LABEL: define dso_local noundef <32 x i32> @_Z11test_insertDv32_jiDv16_j(
// CHECK-SAME: <32 x i32> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <16 x i32> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[B]], <16 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[A]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE1_I_I]], <32 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    ret <32 x i32> [[COND_I_I]]
//
v32uint32 test_insert (v32uint32 a, int idx, v16uint32 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local noundef <32 x i32> @_Z18test_set_v32uint32iDv16_j(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <16 x i32> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[B]], <16 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[B]], <16 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    ret <32 x i32> [[COND_I_I]]
//
v32uint32 test_set_v32uint32 (int idx, v16uint32 b)
{
    return set_v32uint32(idx, b);
}

// CHECK-LABEL: define dso_local noundef <32 x i32> @_Z11test_concatDv16_jS_(
// CHECK-SAME: <16 x i32> noundef [[A0:%.*]], <16 x i32> noundef [[A1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[A0]], <16 x i32> [[A1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    ret <32 x i32> [[SHUFFLE_I_I]]
//
v32uint32 test_concat (v16uint32 a0, v16uint32 a1)
{
  return concat( a0,  a1);
}

// v32int32

// CHECK-LABEL: define dso_local noundef <8 x i32> @_Z20test_extract_v8int32Dv32_ii(
// CHECK-SAME: <32 x i32> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[COND9_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE2_I_I]], <8 x i32> [[SHUFFLE3_I_I]]
// CHECK-NEXT:    [[AND10_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I:%.*]] = icmp eq i32 [[AND10_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I]], <8 x i32> [[COND_I_I]], <8 x i32> [[COND9_I_I]]
// CHECK-NEXT:    ret <8 x i32> [[COND15_I_I]]
//
v8int32 test_extract_v8int32 (v32int32 a, int idx)
{
    return extract_v8int32(a, idx);
}

// CHECK-LABEL: define dso_local noundef <32 x i32> @_Z11test_insertDv32_iiDv8_i(
// CHECK-SAME: <32 x i32> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <8 x i32> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> [[SHUFFLE2_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE7_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> [[SHUFFLE3_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE5_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> [[SHUFFLE1_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE4_I_I:%.*]] = shufflevector <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[A]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE4_I_I]], <32 x i32> [[SHUFFLE5_I_I]]
// CHECK-NEXT:    [[COND13_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE6_I_I]], <32 x i32> [[SHUFFLE7_I_I]]
// CHECK-NEXT:    [[AND14_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL15_NOT_I_I:%.*]] = icmp eq i32 [[AND14_I_I]], 0
// CHECK-NEXT:    [[COND19_I_I:%.*]] = select i1 [[TOBOOL15_NOT_I_I]], <32 x i32> [[COND_I_I]], <32 x i32> [[COND13_I_I]]
// CHECK-NEXT:    ret <32 x i32> [[COND19_I_I]]
//
v32int32 test_insert (v32int32 a, int idx, v8int32 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local noundef <32 x i32> @_Z17test_set_v32int32iDv8_i(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <8 x i32> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[COND9_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE2_I_I]], <32 x i32> [[SHUFFLE3_I_I]]
// CHECK-NEXT:    [[AND10_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I:%.*]] = icmp eq i32 [[AND10_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I]], <32 x i32> [[COND_I_I]], <32 x i32> [[COND9_I_I]]
// CHECK-NEXT:    ret <32 x i32> [[COND15_I_I]]
//
v32int32 test_set_v32int32 (int idx, v8int32 b)
{
    return set_v32int32(idx, b);
}

// CHECK-LABEL: define dso_local noundef <32 x i32> @_Z11test_concatDv8_iS_S_S_(
// CHECK-SAME: <8 x i32> noundef [[A0:%.*]], <8 x i32> noundef [[A1:%.*]], <8 x i32> noundef [[A2:%.*]], <8 x i32> noundef [[A3:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[A0]], <8 x i32> [[A1]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[A2]], <8 x i32> [[A3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    ret <32 x i32> [[SHUFFLE2_I_I]]
//
v32int32 test_concat (v8int32 a0, v8int32 a1, v8int32 a2, v8int32 a3)
{
  return concat( a0,  a1,  a2,  a3);
}

// v32int32

// CHECK-LABEL: define dso_local noundef <16 x i32> @_Z21test_extract_v16int32Dv32_ii(
// CHECK-SAME: <32 x i32> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    ret <16 x i32> [[COND_I_I]]
//
v16int32 test_extract_v16int32 (v32int32 a, int idx)
{
    return extract_v16int32(a, idx);
}

// CHECK-LABEL: define dso_local noundef <32 x i32> @_Z11test_insertDv32_iiDv16_i(
// CHECK-SAME: <32 x i32> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <16 x i32> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[B]], <16 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[A]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE1_I_I]], <32 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    ret <32 x i32> [[COND_I_I]]
//
v32int32 test_insert (v32int32 a, int idx, v16int32 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local noundef <32 x i32> @_Z17test_set_v32int32iDv16_i(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <16 x i32> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[B]], <16 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[B]], <16 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    ret <32 x i32> [[COND_I_I]]
//
v32int32 test_set_v32int32 (int idx, v16int32 b)
{
    return set_v32int32(idx, b);
}

// CHECK-LABEL: define dso_local noundef <32 x i32> @_Z11test_concatDv16_iS_(
// CHECK-SAME: <16 x i32> noundef [[A0:%.*]], <16 x i32> noundef [[A1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[A0]], <16 x i32> [[A1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    ret <32 x i32> [[SHUFFLE_I_I]]
//
v32int32 test_concat (v16int32 a0, v16int32 a1)
{
  return concat( a0,  a1);
}

// v64bfloat16

// CHECK-LABEL: define dso_local noundef <16 x bfloat> @_Z24test_extract_v16bfloat16Dv64_8bfloat16i(
// CHECK-SAME: <64 x bfloat> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x bfloat> [[A]] to <32 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[COND9_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE2_I_I]], <8 x i32> [[SHUFFLE3_I_I]]
// CHECK-NEXT:    [[AND10_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I:%.*]] = icmp eq i32 [[AND10_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I]], <8 x i32> [[COND_I_I]], <8 x i32> [[COND9_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i32> [[COND15_I_I]] to <16 x bfloat>
// CHECK-NEXT:    ret <16 x bfloat> [[TMP1]]
//
v16bfloat16 test_extract_v16bfloat16 (v64bfloat16 a, int idx)
{
    return extract_v16bfloat16(a, idx);
}

// CHECK-LABEL: define dso_local noundef <64 x bfloat> @_Z11test_insertDv64_8bfloat16iDv16_S_(
// CHECK-SAME: <64 x bfloat> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <16 x bfloat> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x bfloat> [[A]] to <32 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x bfloat> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE2_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE7_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE3_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE5_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE1_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE4_I_I:%.*]] = shufflevector <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[TMP0]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE4_I_I]], <32 x i32> [[SHUFFLE5_I_I]]
// CHECK-NEXT:    [[COND13_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE6_I_I]], <32 x i32> [[SHUFFLE7_I_I]]
// CHECK-NEXT:    [[AND14_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL15_NOT_I_I:%.*]] = icmp eq i32 [[AND14_I_I]], 0
// CHECK-NEXT:    [[COND19_I_I:%.*]] = select i1 [[TOBOOL15_NOT_I_I]], <32 x i32> [[COND_I_I]], <32 x i32> [[COND13_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[COND19_I_I]] to <64 x bfloat>
// CHECK-NEXT:    ret <64 x bfloat> [[TMP2]]
//
v64bfloat16 test_insert (v64bfloat16 a, int idx, v16bfloat16 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local noundef <64 x bfloat> @_Z20test_set_v64bfloat16iDv16_8bfloat16(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <16 x bfloat> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x bfloat> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[COND9_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE2_I_I]], <32 x i32> [[SHUFFLE3_I_I]]
// CHECK-NEXT:    [[AND10_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I:%.*]] = icmp eq i32 [[AND10_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I]], <32 x i32> [[COND_I_I]], <32 x i32> [[COND9_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i32> [[COND15_I_I]] to <64 x bfloat>
// CHECK-NEXT:    ret <64 x bfloat> [[TMP1]]
//
v64bfloat16 test_set_v64bfloat16 (int idx, v16bfloat16 b)
{
    return set_v64bfloat16(idx, b);
}

// CHECK-LABEL: define dso_local noundef <64 x bfloat> @_Z11test_concatDv16_8bfloat16S0_S0_S0_(
// CHECK-SAME: <16 x bfloat> noundef [[A0:%.*]], <16 x bfloat> noundef [[A1:%.*]], <16 x bfloat> noundef [[A2:%.*]], <16 x bfloat> noundef [[A3:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x bfloat> [[A0]] to <8 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x bfloat> [[A1]] to <8 x i32>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x bfloat> [[A2]] to <8 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <16 x bfloat> [[A3]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> [[TMP1]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP2]], <8 x i32> [[TMP3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I]] to <64 x bfloat>
// CHECK-NEXT:    ret <64 x bfloat> [[TMP4]]
//
v64bfloat16 test_concat (v16bfloat16 a0, v16bfloat16 a1, v16bfloat16 a2, v16bfloat16 a3)
{
  return concat( a0,  a1,  a2,  a3);
}

// v64bfloat16

// CHECK-LABEL: define dso_local noundef <32 x bfloat> @_Z24test_extract_v32bfloat16Dv64_8bfloat16i(
// CHECK-SAME: <64 x bfloat> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x bfloat> [[A]] to <32 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[COND_I_I]] to <32 x bfloat>
// CHECK-NEXT:    ret <32 x bfloat> [[TMP1]]
//
v32bfloat16 test_extract_v32bfloat16 (v64bfloat16 a, int idx)
{
    return extract_v32bfloat16(a, idx);
}

// CHECK-LABEL: define dso_local noundef <64 x bfloat> @_Z11test_insertDv64_8bfloat16iDv32_S_(
// CHECK-SAME: <64 x bfloat> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <32 x bfloat> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x bfloat> [[A]] to <32 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x bfloat> [[B]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[TMP0]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE1_I_I]], <32 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[COND_I_I]] to <64 x bfloat>
// CHECK-NEXT:    ret <64 x bfloat> [[TMP2]]
//
v64bfloat16 test_insert (v64bfloat16 a, int idx, v32bfloat16 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local noundef <64 x bfloat> @_Z20test_set_v64bfloat16iDv32_8bfloat16(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <32 x bfloat> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x bfloat> [[B]] to <16 x i32>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i32> [[COND_I_I]] to <64 x bfloat>
// CHECK-NEXT:    ret <64 x bfloat> [[TMP1]]
//
v64bfloat16 test_set_v64bfloat16 (int idx, v32bfloat16 b)
{
    return set_v64bfloat16(idx, b);
}

// CHECK-LABEL: define dso_local noundef <64 x bfloat> @_Z11test_concatDv32_8bfloat16S0_(
// CHECK-SAME: <32 x bfloat> noundef [[A0:%.*]], <32 x bfloat> noundef [[A1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x bfloat> [[A0]] to <16 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x bfloat> [[A1]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE_I_I]] to <64 x bfloat>
// CHECK-NEXT:    ret <64 x bfloat> [[TMP2]]
//
v64bfloat16 test_concat (v32bfloat16 a0, v32bfloat16 a1)
{
  return concat( a0,  a1);
}

// v32accfloat

// CHECK-LABEL: define dso_local inreg noundef <16 x float> @_Z24test_extract_v16accfloatDv32_u10__accfloati(
// CHECK-SAME: <32 x float> inreg noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x float> [[A]] to <32 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[COND_I_I]] to <16 x float>
// CHECK-NEXT:    ret <16 x float> [[TMP1]]
//
v16accfloat test_extract_v16accfloat (v32accfloat a, int idx)
{
    return extract_v16accfloat(a, idx);
}

// CHECK-LABEL: define dso_local inreg noundef <32 x float> @_Z11test_insertDv32_u10__accfloatiDv16_u10__accfloat(
// CHECK-SAME: <32 x float> inreg noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <16 x float> inreg noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x float> [[A]] to <32 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[B]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[TMP0]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE1_I_I]], <32 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[COND_I_I]] to <32 x float>
// CHECK-NEXT:    ret <32 x float> [[TMP2]]
//
v32accfloat test_insert (v32accfloat a, int idx, v16accfloat b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local inreg noundef <32 x float> @_Z20test_set_v32accfloatiDv16_u10__accfloat(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <16 x float> inreg noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[B]] to <16 x i32>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i32> [[COND_I_I]] to <32 x float>
// CHECK-NEXT:    ret <32 x float> [[TMP1]]
//
v32accfloat test_set_v32accfloat (int idx, v16accfloat b)
{
    return set_v32accfloat(idx, b);
}

// CHECK-LABEL: define dso_local inreg noundef <32 x float> @_Z11test_concatDv16_u10__accfloatS_(
// CHECK-SAME: <16 x float> inreg noundef [[A0:%.*]], <16 x float> inreg noundef [[A1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_UNCASTED_I:%.*]] = shufflevector <16 x float> [[A0]], <16 x float> [[A1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    ret <32 x float> [[SHUFFLE_I_UNCASTED_I]]
//
v32accfloat test_concat (v16accfloat a0, v16accfloat a1)
{
  return concat( a0,  a1);
}

// v32float

// CHECK-LABEL: define dso_local noundef <8 x float> @_Z20test_extract_v8floatDv32_fi(
// CHECK-SAME: <32 x float> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x float> [[A]] to <32 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[COND9_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE2_I_I]], <8 x i32> [[SHUFFLE3_I_I]]
// CHECK-NEXT:    [[AND10_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I:%.*]] = icmp eq i32 [[AND10_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I]], <8 x i32> [[COND_I_I]], <8 x i32> [[COND9_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i32> [[COND15_I_I]] to <8 x float>
// CHECK-NEXT:    ret <8 x float> [[TMP1]]
//
v8float test_extract_v8float (v32float a, int idx)
{
    return extract_v8float(a, idx);
}

// CHECK-LABEL: define dso_local noundef <32 x float> @_Z11test_insertDv32_fiDv8_f(
// CHECK-SAME: <32 x float> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <8 x float> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x float> [[A]] to <32 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x float> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE2_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE7_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE3_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE5_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE1_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE4_I_I:%.*]] = shufflevector <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[TMP0]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE4_I_I]], <32 x i32> [[SHUFFLE5_I_I]]
// CHECK-NEXT:    [[COND13_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE6_I_I]], <32 x i32> [[SHUFFLE7_I_I]]
// CHECK-NEXT:    [[AND14_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL15_NOT_I_I:%.*]] = icmp eq i32 [[AND14_I_I]], 0
// CHECK-NEXT:    [[COND19_I_I:%.*]] = select i1 [[TOBOOL15_NOT_I_I]], <32 x i32> [[COND_I_I]], <32 x i32> [[COND13_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[COND19_I_I]] to <32 x float>
// CHECK-NEXT:    ret <32 x float> [[TMP2]]
//
v32float test_insert (v32float a, int idx, v8float b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local noundef <32 x float> @_Z17test_set_v32floatiDv8_f(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <8 x float> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x float> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[COND9_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE2_I_I]], <32 x i32> [[SHUFFLE3_I_I]]
// CHECK-NEXT:    [[AND10_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I:%.*]] = icmp eq i32 [[AND10_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I]], <32 x i32> [[COND_I_I]], <32 x i32> [[COND9_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i32> [[COND15_I_I]] to <32 x float>
// CHECK-NEXT:    ret <32 x float> [[TMP1]]
//
v32float test_set_v32float (int idx, v8float b)
{
    return set_v32float(idx, b);
}

// CHECK-LABEL: define dso_local noundef <32 x float> @_Z11test_concatDv8_fS_S_S_(
// CHECK-SAME: <8 x float> noundef [[A0:%.*]], <8 x float> noundef [[A1:%.*]], <8 x float> noundef [[A2:%.*]], <8 x float> noundef [[A3:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_UNCASTED_I:%.*]] = shufflevector <8 x float> [[A0]], <8 x float> [[A1]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE1_I_UNCASTED_I:%.*]] = shufflevector <8 x float> [[A2]], <8 x float> [[A3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_UNCASTED_I:%.*]] = shufflevector <16 x float> [[SHUFFLE_I_UNCASTED_I]], <16 x float> [[SHUFFLE1_I_UNCASTED_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    ret <32 x float> [[SHUFFLE2_I_UNCASTED_I]]
//
v32float test_concat (v8float a0, v8float a1, v8float a2, v8float a3)
{
  return concat( a0,  a1,  a2,  a3);
}

// v32float

// CHECK-LABEL: define dso_local noundef <16 x float> @_Z21test_extract_v16floatDv32_fi(
// CHECK-SAME: <32 x float> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x float> [[A]] to <32 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[COND_I_I]] to <16 x float>
// CHECK-NEXT:    ret <16 x float> [[TMP1]]
//
v16float test_extract_v16float (v32float a, int idx)
{
    return extract_v16float(a, idx);
}

// CHECK-LABEL: define dso_local noundef <32 x float> @_Z11test_insertDv32_fiDv16_f(
// CHECK-SAME: <32 x float> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <16 x float> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x float> [[A]] to <32 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[B]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[TMP0]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE1_I_I]], <32 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[COND_I_I]] to <32 x float>
// CHECK-NEXT:    ret <32 x float> [[TMP2]]
//
v32float test_insert (v32float a, int idx, v16float b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local noundef <32 x float> @_Z17test_set_v32floatiDv16_f(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <16 x float> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[B]] to <16 x i32>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i32> [[COND_I_I]] to <32 x float>
// CHECK-NEXT:    ret <32 x float> [[TMP1]]
//
v32float test_set_v32float (int idx, v16float b)
{
    return set_v32float(idx, b);
}

// CHECK-LABEL: define dso_local noundef <32 x float> @_Z11test_concatDv16_fS_(
// CHECK-SAME: <16 x float> noundef [[A0:%.*]], <16 x float> noundef [[A1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_UNCASTED_I:%.*]] = shufflevector <16 x float> [[A0]], <16 x float> [[A1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    ret <32 x float> [[SHUFFLE_I_UNCASTED_I]]
//
v32float test_concat (v16float a0, v16float a1)
{
  return concat( a0,  a1);
}

// v32acc32

// CHECK-LABEL: define dso_local inreg noundef <16 x i32> @_Z21test_extract_v16acc32Dv32_u7__acc32i(
// CHECK-SAME: <32 x i32> inreg noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    ret <16 x i32> [[COND_I_I]]
//
v16acc32 test_extract_v16acc32 (v32acc32 a, int idx)
{
    return extract_v16acc32(a, idx);
}

// CHECK-LABEL: define dso_local inreg noundef <32 x i32> @_Z11test_insertDv32_u7__acc32iDv16_u7__acc32(
// CHECK-SAME: <32 x i32> inreg noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <16 x i32> inreg noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[B]], <16 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[A]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE1_I_I]], <32 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    ret <32 x i32> [[COND_I_I]]
//
v32acc32 test_insert (v32acc32 a, int idx, v16acc32 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local inreg noundef <32 x i32> @_Z17test_set_v32acc32iDv16_u7__acc32(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <16 x i32> inreg noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[B]], <16 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[B]], <16 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    ret <32 x i32> [[COND_I_I]]
//
v32acc32 test_set_v32acc32 (int idx, v16acc32 b)
{
    return set_v32acc32(idx, b);
}

// CHECK-LABEL: define dso_local inreg noundef <32 x i32> @_Z11test_concatDv16_u7__acc32S_(
// CHECK-SAME: <16 x i32> inreg noundef [[A0:%.*]], <16 x i32> inreg noundef [[A1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[A0]], <16 x i32> [[A1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    ret <32 x i32> [[SHUFFLE_I_I]]
//
v32acc32 test_concat (v16acc32 a0, v16acc32 a1)
{
  return concat( a0,  a1);
}

// v16acc64

// CHECK-LABEL: define dso_local inreg noundef <8 x i64> @_Z20test_extract_v8acc64Dv16_u7__acc64i(
// CHECK-SAME: <16 x i64> inreg noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i64> [[A]] to <32 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[COND_I_I]] to <8 x i64>
// CHECK-NEXT:    ret <8 x i64> [[TMP1]]
//
v8acc64 test_extract_v8acc64 (v16acc64 a, int idx)
{
    return extract_v8acc64(a, idx);
}

// CHECK-LABEL: define dso_local inreg noundef <16 x i64> @_Z11test_insertDv16_u7__acc64iDv8_u7__acc64(
// CHECK-SAME: <16 x i64> inreg noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <8 x i64> inreg noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i64> [[A]] to <32 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i64> [[B]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[TMP0]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE1_I_I]], <32 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[COND_I_I]] to <16 x i64>
// CHECK-NEXT:    ret <16 x i64> [[TMP2]]
//
v16acc64 test_insert (v16acc64 a, int idx, v8acc64 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local inreg noundef <16 x i64> @_Z17test_set_v16acc64iDv8_u7__acc64(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <8 x i64> inreg noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x i64> [[B]] to <16 x i32>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i32> [[COND_I_I]] to <16 x i64>
// CHECK-NEXT:    ret <16 x i64> [[TMP1]]
//
v16acc64 test_set_v16acc64 (int idx, v8acc64 b)
{
    return set_v16acc64(idx, b);
}

// CHECK-LABEL: define dso_local inreg noundef <16 x i64> @_Z11test_concatDv8_u7__acc64S_(
// CHECK-SAME: <8 x i64> inreg noundef [[A0:%.*]], <8 x i64> inreg noundef [[A1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i64> [[A0]], <8 x i64> [[A1]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i64> [[TMP0]]
//
v16acc64 test_concat (v8acc64 a0, v8acc64 a1)
{
  return concat( a0,  a1);
}

// v64accfloat

// CHECK-LABEL: define dso_local inreg noundef <16 x float> @_Z24test_extract_v16accfloatDv64_u10__accfloati(
// CHECK-SAME: <64 x float> inreg noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x float> [[A]] to <32 x i64>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <32 x i64> [[TMP0]], <32 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i64> [[TMP0]], <32 x i64> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <32 x i64> [[TMP0]], <32 x i64> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <32 x i64> [[TMP0]], <32 x i64> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i64> [[SHUFFLE_I_I]], <8 x i64> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[COND9_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i64> [[SHUFFLE2_I_I]], <8 x i64> [[SHUFFLE3_I_I]]
// CHECK-NEXT:    [[AND10_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I:%.*]] = icmp eq i32 [[AND10_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I]], <8 x i64> [[COND_I_I]], <8 x i64> [[COND9_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i64> [[COND15_I_I]] to <16 x float>
// CHECK-NEXT:    ret <16 x float> [[TMP1]]
//
v16accfloat test_extract_v16accfloat (v64accfloat a, int idx)
{
    return extract_v16accfloat(a, idx);
}

// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z11test_insertDv64_u10__accfloatiDv16_u10__accfloat(
// CHECK-SAME: <64 x float> inreg noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <16 x float> inreg noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x float> [[A]] to <32 x i64>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[B]] to <8 x i64>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i64> [[TMP1]], <8 x i64> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <8 x i64> [[TMP1]], <8 x i64> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <32 x i64> [[TMP0]], <32 x i64> [[SHUFFLE2_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE7_I_I:%.*]] = shufflevector <32 x i64> [[TMP0]], <32 x i64> [[SHUFFLE3_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i64> [[TMP1]], <8 x i64> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE5_I_I:%.*]] = shufflevector <32 x i64> [[TMP0]], <32 x i64> [[SHUFFLE1_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i64> [[TMP1]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE4_I_I:%.*]] = shufflevector <32 x i64> [[SHUFFLE_I_I]], <32 x i64> [[TMP0]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i64> [[SHUFFLE4_I_I]], <32 x i64> [[SHUFFLE5_I_I]]
// CHECK-NEXT:    [[COND13_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i64> [[SHUFFLE6_I_I]], <32 x i64> [[SHUFFLE7_I_I]]
// CHECK-NEXT:    [[AND14_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL15_NOT_I_I:%.*]] = icmp eq i32 [[AND14_I_I]], 0
// CHECK-NEXT:    [[COND19_I_I:%.*]] = select i1 [[TOBOOL15_NOT_I_I]], <32 x i64> [[COND_I_I]], <32 x i64> [[COND13_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i64> [[COND19_I_I]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP2]]
//
v64accfloat test_insert (v64accfloat a, int idx, v16accfloat b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z20test_set_v64accfloatiDv16_u10__accfloat(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <16 x float> inreg noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[B]] to <8 x i64>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i64> [[TMP0]], <8 x i64> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <8 x i64> [[TMP0]], <8 x i64> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i64> [[TMP0]], <8 x i64> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i64> [[TMP0]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i64> [[SHUFFLE_I_I]], <32 x i64> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[COND9_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i64> [[SHUFFLE2_I_I]], <32 x i64> [[SHUFFLE3_I_I]]
// CHECK-NEXT:    [[AND10_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I:%.*]] = icmp eq i32 [[AND10_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I]], <32 x i64> [[COND_I_I]], <32 x i64> [[COND9_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i64> [[COND15_I_I]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP1]]
//
v64accfloat test_set_v64accfloat (int idx, v16accfloat b)
{
    return set_v64accfloat(idx, b);
}

// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z11test_concatDv16_u10__accfloatS_S_S_(
// CHECK-SAME: <16 x float> inreg noundef [[A0:%.*]], <16 x float> inreg noundef [[A1:%.*]], <16 x float> inreg noundef [[A2:%.*]], <16 x float> inreg noundef [[A3:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[A0]] to <8 x i64>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[A1]] to <8 x i64>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x float> [[A2]] to <8 x i64>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <16 x float> [[A3]] to <8 x i64>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i64> [[TMP0]], <8 x i64> [[TMP1]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i64> [[TMP2]], <8 x i64> [[TMP3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i64> [[SHUFFLE_I_I]], <16 x i64> [[SHUFFLE1_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <32 x i64> [[SHUFFLE2_I_I]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP4]]
//
v64accfloat test_concat (v16accfloat a0, v16accfloat a1, v16accfloat a2, v16accfloat a3)
{
  return concat( a0,  a1,  a2,  a3);
}

// v64accfloat

// CHECK-LABEL: define dso_local inreg noundef <32 x float> @_Z24test_extract_v32accfloatDv64_u10__accfloati(
// CHECK-SAME: <64 x float> inreg noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x float> [[A]] to <32 x i64>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i64> [[TMP0]], <32 x i64> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <32 x i64> [[TMP0]], <32 x i64> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i64> [[SHUFFLE_I_I]], <16 x i64> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i64> [[COND_I_I]] to <32 x float>
// CHECK-NEXT:    ret <32 x float> [[TMP1]]
//
v32accfloat test_extract_v32accfloat (v64accfloat a, int idx)
{
    return extract_v32accfloat(a, idx);
}

// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z11test_insertDv64_u10__accfloatiDv32_u10__accfloat(
// CHECK-SAME: <64 x float> inreg noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <32 x float> inreg noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x float> [[A]] to <32 x i64>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x float> [[B]] to <16 x i64>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i64> [[TMP1]], <16 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <32 x i64> [[TMP0]], <32 x i64> [[SHUFFLE_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i64> [[SHUFFLE_I_I]], <32 x i64> [[TMP0]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i64> [[SHUFFLE1_I_I]], <32 x i64> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i64> [[COND_I_I]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP2]]
//
v64accfloat test_insert (v64accfloat a, int idx, v32accfloat b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z20test_set_v64accfloatiDv32_u10__accfloat(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <32 x float> inreg noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x float> [[B]] to <16 x i64>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i64> [[TMP0]], <16 x i64> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i64> [[TMP0]], <16 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i64> [[SHUFFLE_I_I]], <32 x i64> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i64> [[COND_I_I]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP1]]
//
v64accfloat test_set_v64accfloat (int idx, v32accfloat b)
{
    return set_v64accfloat(idx, b);
}

// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z11test_concatDv32_u10__accfloatS_(
// CHECK-SAME: <32 x float> inreg noundef [[A0:%.*]], <32 x float> inreg noundef [[A1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x float> [[A0]] to <16 x i64>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x float> [[A1]] to <16 x i64>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i64> [[TMP0]], <16 x i64> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i64> [[SHUFFLE_I_I]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP2]]
//
v64accfloat test_concat (v32accfloat a0, v32accfloat a1)
{
  return concat( a0,  a1);
}

// v64acc32

// CHECK-LABEL: define dso_local inreg noundef <16 x i32> @_Z21test_extract_v16acc32Dv64_u7__acc32i(
// CHECK-SAME: <64 x i32> inreg noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i32> [[A]] to <32 x i64>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <32 x i64> [[TMP0]], <32 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i64> [[TMP0]], <32 x i64> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <32 x i64> [[TMP0]], <32 x i64> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <32 x i64> [[TMP0]], <32 x i64> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i64> [[SHUFFLE_I_I]], <8 x i64> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[COND9_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i64> [[SHUFFLE2_I_I]], <8 x i64> [[SHUFFLE3_I_I]]
// CHECK-NEXT:    [[AND10_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I:%.*]] = icmp eq i32 [[AND10_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I]], <8 x i64> [[COND_I_I]], <8 x i64> [[COND9_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i64> [[COND15_I_I]] to <16 x i32>
// CHECK-NEXT:    ret <16 x i32> [[TMP1]]
//
v16acc32 test_extract_v16acc32 (v64acc32 a, int idx)
{
    return extract_v16acc32(a, idx);
}

// CHECK-LABEL: define dso_local inreg noundef <64 x i32> @_Z11test_insertDv64_u7__acc32iDv16_u7__acc32(
// CHECK-SAME: <64 x i32> inreg noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <16 x i32> inreg noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i32> [[A]] to <32 x i64>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[B]] to <8 x i64>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i64> [[TMP1]], <8 x i64> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <8 x i64> [[TMP1]], <8 x i64> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <32 x i64> [[TMP0]], <32 x i64> [[SHUFFLE2_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE7_I_I:%.*]] = shufflevector <32 x i64> [[TMP0]], <32 x i64> [[SHUFFLE3_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i64> [[TMP1]], <8 x i64> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE5_I_I:%.*]] = shufflevector <32 x i64> [[TMP0]], <32 x i64> [[SHUFFLE1_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i64> [[TMP1]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE4_I_I:%.*]] = shufflevector <32 x i64> [[SHUFFLE_I_I]], <32 x i64> [[TMP0]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i64> [[SHUFFLE4_I_I]], <32 x i64> [[SHUFFLE5_I_I]]
// CHECK-NEXT:    [[COND13_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i64> [[SHUFFLE6_I_I]], <32 x i64> [[SHUFFLE7_I_I]]
// CHECK-NEXT:    [[AND14_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL15_NOT_I_I:%.*]] = icmp eq i32 [[AND14_I_I]], 0
// CHECK-NEXT:    [[COND19_I_I:%.*]] = select i1 [[TOBOOL15_NOT_I_I]], <32 x i64> [[COND_I_I]], <32 x i64> [[COND13_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i64> [[COND19_I_I]] to <64 x i32>
// CHECK-NEXT:    ret <64 x i32> [[TMP2]]
//
v64acc32 test_insert (v64acc32 a, int idx, v16acc32 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local inreg noundef <64 x i32> @_Z17test_set_v64acc32iDv16_u7__acc32(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <16 x i32> inreg noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i32> [[B]] to <8 x i64>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i64> [[TMP0]], <8 x i64> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <8 x i64> [[TMP0]], <8 x i64> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i64> [[TMP0]], <8 x i64> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i64> [[TMP0]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i64> [[SHUFFLE_I_I]], <32 x i64> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[COND9_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i64> [[SHUFFLE2_I_I]], <32 x i64> [[SHUFFLE3_I_I]]
// CHECK-NEXT:    [[AND10_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I:%.*]] = icmp eq i32 [[AND10_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I]], <32 x i64> [[COND_I_I]], <32 x i64> [[COND9_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i64> [[COND15_I_I]] to <64 x i32>
// CHECK-NEXT:    ret <64 x i32> [[TMP1]]
//
v64acc32 test_set_v64acc32 (int idx, v16acc32 b)
{
    return set_v64acc32(idx, b);
}

// CHECK-LABEL: define dso_local inreg noundef <64 x i32> @_Z11test_concatDv16_u7__acc32S_S_S_(
// CHECK-SAME: <16 x i32> inreg noundef [[A0:%.*]], <16 x i32> inreg noundef [[A1:%.*]], <16 x i32> inreg noundef [[A2:%.*]], <16 x i32> inreg noundef [[A3:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i32> [[A0]] to <8 x i64>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[A1]] to <8 x i64>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[A2]] to <8 x i64>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[A3]] to <8 x i64>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i64> [[TMP0]], <8 x i64> [[TMP1]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i64> [[TMP2]], <8 x i64> [[TMP3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i64> [[SHUFFLE_I_I]], <16 x i64> [[SHUFFLE1_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <32 x i64> [[SHUFFLE2_I_I]] to <64 x i32>
// CHECK-NEXT:    ret <64 x i32> [[TMP4]]
//
v64acc32 test_concat (v16acc32 a0, v16acc32 a1, v16acc32 a2, v16acc32 a3)
{
  return concat( a0,  a1,  a2,  a3);
}

// v64acc32

// CHECK-LABEL: define dso_local inreg noundef <32 x i32> @_Z21test_extract_v32acc32Dv64_u7__acc32i(
// CHECK-SAME: <64 x i32> inreg noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i32> [[A]] to <32 x i64>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i64> [[TMP0]], <32 x i64> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <32 x i64> [[TMP0]], <32 x i64> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i64> [[SHUFFLE_I_I]], <16 x i64> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i64> [[COND_I_I]] to <32 x i32>
// CHECK-NEXT:    ret <32 x i32> [[TMP1]]
//
v32acc32 test_extract_v32acc32 (v64acc32 a, int idx)
{
    return extract_v32acc32(a, idx);
}

// CHECK-LABEL: define dso_local inreg noundef <64 x i32> @_Z11test_insertDv64_u7__acc32iDv32_u7__acc32(
// CHECK-SAME: <64 x i32> inreg noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <32 x i32> inreg noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i32> [[A]] to <32 x i64>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i32> [[B]] to <16 x i64>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i64> [[TMP1]], <16 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <32 x i64> [[TMP0]], <32 x i64> [[SHUFFLE_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i64> [[SHUFFLE_I_I]], <32 x i64> [[TMP0]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i64> [[SHUFFLE1_I_I]], <32 x i64> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i64> [[COND_I_I]] to <64 x i32>
// CHECK-NEXT:    ret <64 x i32> [[TMP2]]
//
v64acc32 test_insert (v64acc32 a, int idx, v32acc32 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local inreg noundef <64 x i32> @_Z17test_set_v64acc32iDv32_u7__acc32(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <32 x i32> inreg noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i32> [[B]] to <16 x i64>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i64> [[TMP0]], <16 x i64> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i64> [[TMP0]], <16 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i64> [[SHUFFLE_I_I]], <32 x i64> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i64> [[COND_I_I]] to <64 x i32>
// CHECK-NEXT:    ret <64 x i32> [[TMP1]]
//
v64acc32 test_set_v64acc32 (int idx, v32acc32 b)
{
    return set_v64acc32(idx, b);
}

// CHECK-LABEL: define dso_local inreg noundef <64 x i32> @_Z11test_concatDv32_u7__acc32S_(
// CHECK-SAME: <32 x i32> inreg noundef [[A0:%.*]], <32 x i32> inreg noundef [[A1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i32> [[A0]] to <16 x i64>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i32> [[A1]] to <16 x i64>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i64> [[TMP0]], <16 x i64> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i64> [[SHUFFLE_I_I]] to <64 x i32>
// CHECK-NEXT:    ret <64 x i32> [[TMP2]]
//
v64acc32 test_concat (v32acc32 a0, v32acc32 a1)
{
  return concat( a0,  a1);
}

// v32acc64

// CHECK-LABEL: define dso_local inreg noundef <8 x i64> @_Z20test_extract_v8acc64Dv32_u7__acc64i(
// CHECK-SAME: <32 x i64> inreg noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <32 x i64> [[A]], <32 x i64> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i64> [[A]], <32 x i64> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <32 x i64> [[A]], <32 x i64> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <32 x i64> [[A]], <32 x i64> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i64> [[SHUFFLE_I_I]], <8 x i64> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[COND9_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i64> [[SHUFFLE2_I_I]], <8 x i64> [[SHUFFLE3_I_I]]
// CHECK-NEXT:    [[AND10_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I:%.*]] = icmp eq i32 [[AND10_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I]], <8 x i64> [[COND_I_I]], <8 x i64> [[COND9_I_I]]
// CHECK-NEXT:    ret <8 x i64> [[COND15_I_I]]
//
v8acc64 test_extract_v8acc64 (v32acc64 a, int idx)
{
    return extract_v8acc64(a, idx);
}

// CHECK-LABEL: define dso_local inreg noundef <32 x i64> @_Z11test_insertDv32_u7__acc64iDv8_u7__acc64(
// CHECK-SAME: <32 x i64> inreg noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <8 x i64> inreg noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i64> [[B]], <8 x i64> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <8 x i64> [[B]], <8 x i64> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <32 x i64> [[A]], <32 x i64> [[SHUFFLE2_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE7_I_I:%.*]] = shufflevector <32 x i64> [[A]], <32 x i64> [[SHUFFLE3_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i64> [[B]], <8 x i64> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE5_I_I:%.*]] = shufflevector <32 x i64> [[A]], <32 x i64> [[SHUFFLE1_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i64> [[B]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE4_I_I:%.*]] = shufflevector <32 x i64> [[SHUFFLE_I_I]], <32 x i64> [[A]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i64> [[SHUFFLE4_I_I]], <32 x i64> [[SHUFFLE5_I_I]]
// CHECK-NEXT:    [[COND13_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i64> [[SHUFFLE6_I_I]], <32 x i64> [[SHUFFLE7_I_I]]
// CHECK-NEXT:    [[AND14_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL15_NOT_I_I:%.*]] = icmp eq i32 [[AND14_I_I]], 0
// CHECK-NEXT:    [[COND19_I_I:%.*]] = select i1 [[TOBOOL15_NOT_I_I]], <32 x i64> [[COND_I_I]], <32 x i64> [[COND13_I_I]]
// CHECK-NEXT:    ret <32 x i64> [[COND19_I_I]]
//
v32acc64 test_insert (v32acc64 a, int idx, v8acc64 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local inreg noundef <32 x i64> @_Z17test_set_v32acc64iDv8_u7__acc64(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <8 x i64> inreg noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i64> [[B]], <8 x i64> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <8 x i64> [[B]], <8 x i64> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i64> [[B]], <8 x i64> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i64> [[B]], <8 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i64> [[SHUFFLE_I_I]], <32 x i64> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[COND9_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i64> [[SHUFFLE2_I_I]], <32 x i64> [[SHUFFLE3_I_I]]
// CHECK-NEXT:    [[AND10_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I:%.*]] = icmp eq i32 [[AND10_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I]], <32 x i64> [[COND_I_I]], <32 x i64> [[COND9_I_I]]
// CHECK-NEXT:    ret <32 x i64> [[COND15_I_I]]
//
v32acc64 test_set_v32acc64 (int idx, v8acc64 b)
{
    return set_v32acc64(idx, b);
}

// CHECK-LABEL: define dso_local inreg noundef <32 x i64> @_Z11test_concatDv8_u7__acc64S_S_S_(
// CHECK-SAME: <8 x i64> inreg noundef [[A0:%.*]], <8 x i64> inreg noundef [[A1:%.*]], <8 x i64> inreg noundef [[A2:%.*]], <8 x i64> inreg noundef [[A3:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i64> [[A0]], <8 x i64> [[A1]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i64> [[A2]], <8 x i64> [[A3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i64> [[SHUFFLE_I_I]], <16 x i64> [[SHUFFLE1_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    ret <32 x i64> [[SHUFFLE2_I_I]]
//
v32acc64 test_concat (v8acc64 a0, v8acc64 a1, v8acc64 a2, v8acc64 a3)
{
  return concat( a0,  a1,  a2,  a3);
}

// v32acc64

// CHECK-LABEL: define dso_local inreg noundef <16 x i64> @_Z21test_extract_v16acc64Dv32_u7__acc64i(
// CHECK-SAME: <32 x i64> inreg noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i64> [[A]], <32 x i64> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <32 x i64> [[A]], <32 x i64> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i64> [[SHUFFLE_I_I]], <16 x i64> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    ret <16 x i64> [[COND_I_I]]
//
v16acc64 test_extract_v16acc64 (v32acc64 a, int idx)
{
    return extract_v16acc64(a, idx);
}

// CHECK-LABEL: define dso_local inreg noundef <32 x i64> @_Z11test_insertDv32_u7__acc64iDv16_u7__acc64(
// CHECK-SAME: <32 x i64> inreg noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <16 x i64> inreg noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i64> [[B]], <16 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <32 x i64> [[A]], <32 x i64> [[SHUFFLE_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i64> [[SHUFFLE_I_I]], <32 x i64> [[A]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i64> [[SHUFFLE1_I_I]], <32 x i64> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    ret <32 x i64> [[COND_I_I]]
//
v32acc64 test_insert (v32acc64 a, int idx, v16acc64 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local inreg noundef <32 x i64> @_Z17test_set_v32acc64iDv16_u7__acc64(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <16 x i64> inreg noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i64> [[B]], <16 x i64> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i64> [[B]], <16 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i64> [[SHUFFLE_I_I]], <32 x i64> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    ret <32 x i64> [[COND_I_I]]
//
v32acc64 test_set_v32acc64 (int idx, v16acc64 b)
{
    return set_v32acc64(idx, b);
}

// CHECK-LABEL: define dso_local inreg noundef <32 x i64> @_Z11test_concatDv16_u7__acc64S_(
// CHECK-SAME: <16 x i64> inreg noundef [[A0:%.*]], <16 x i64> inreg noundef [[A1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i64> [[A0]], <16 x i64> [[A1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    ret <32 x i64> [[SHUFFLE_I_I]]
//
v32acc64 test_concat (v16acc64 a0, v16acc64 a1)
{
  return concat( a0,  a1);
}




// CHECK-AIE2P-LABEL: define dso_local noundef <16 x i8> @_Z21test_extract_v32uint4Dv64_DU8_i(
// CHECK-AIE2P-SAME: <64 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A]] to <16 x i32>
// CHECK-AIE2P-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2p.vextract.broadcast128.I512(<16 x i32> [[TMP0]], i32 [[IDX]])
// CHECK-AIE2P-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[SHUFFLE_I_I]] to <16 x i8>
// CHECK-AIE2P-NEXT:    ret <16 x i8> [[TMP2]]
//
// CHECK-AIE2PS-LABEL: define dso_local noundef <16 x i8> @_Z21test_extract_v32uint4Dv64_DU8_i(
// CHECK-AIE2PS-SAME: <64 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A]] to <16 x i32>
// CHECK-AIE2PS-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2ps.vextract.broadcast128.I512(<16 x i32> [[TMP0]], i32 [[IDX]])
// CHECK-AIE2PS-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[SHUFFLE_I_I]] to <16 x i8>
// CHECK-AIE2PS-NEXT:    ret <16 x i8> [[TMP2]]
//
v32uint4 test_extract_v32uint4 ( v128uint4 a, int idx )
{
    return extract_v32uint4 ( a, idx );
}


// CHECK-AIE2P-LABEL: define dso_local noundef <16 x i8> @_Z20test_extract_v32int4Dv64_DB8_i(
// CHECK-AIE2P-SAME: <64 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A]] to <16 x i32>
// CHECK-AIE2P-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2p.vextract.broadcast128.I512(<16 x i32> [[TMP0]], i32 [[IDX]])
// CHECK-AIE2P-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[SHUFFLE_I_I]] to <16 x i8>
// CHECK-AIE2P-NEXT:    ret <16 x i8> [[TMP2]]
//
// CHECK-AIE2PS-LABEL: define dso_local noundef <16 x i8> @_Z20test_extract_v32int4Dv64_DB8_i(
// CHECK-AIE2PS-SAME: <64 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A]] to <16 x i32>
// CHECK-AIE2PS-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2ps.vextract.broadcast128.I512(<16 x i32> [[TMP0]], i32 [[IDX]])
// CHECK-AIE2PS-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[SHUFFLE_I_I]] to <16 x i8>
// CHECK-AIE2PS-NEXT:    ret <16 x i8> [[TMP2]]
//
v32int4 test_extract_v32int4 ( v128int4 a, int idx )
{
    return extract_v32int4 ( a, idx );
}


// CHECK-AIE2P-LABEL: define dso_local noundef <16 x i8> @_Z21test_extract_v16uint8Dv64_hi(
// CHECK-AIE2P-SAME: <64 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A]] to <16 x i32>
// CHECK-AIE2P-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2p.vextract.broadcast128.I512(<16 x i32> [[TMP0]], i32 [[IDX]])
// CHECK-AIE2P-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[SHUFFLE_I_I]] to <16 x i8>
// CHECK-AIE2P-NEXT:    ret <16 x i8> [[TMP2]]
//
// CHECK-AIE2PS-LABEL: define dso_local noundef <16 x i8> @_Z21test_extract_v16uint8Dv64_hi(
// CHECK-AIE2PS-SAME: <64 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A]] to <16 x i32>
// CHECK-AIE2PS-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2ps.vextract.broadcast128.I512(<16 x i32> [[TMP0]], i32 [[IDX]])
// CHECK-AIE2PS-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[SHUFFLE_I_I]] to <16 x i8>
// CHECK-AIE2PS-NEXT:    ret <16 x i8> [[TMP2]]
//
v16uint8 test_extract_v16uint8 ( v64uint8 a, int idx )
{
    return extract_v16uint8 ( a, idx );
}


// CHECK-AIE2P-LABEL: define dso_local noundef <16 x i8> @_Z20test_extract_v16int8Dv64_ai(
// CHECK-AIE2P-SAME: <64 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A]] to <16 x i32>
// CHECK-AIE2P-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2p.vextract.broadcast128.I512(<16 x i32> [[TMP0]], i32 [[IDX]])
// CHECK-AIE2P-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[SHUFFLE_I_I]] to <16 x i8>
// CHECK-AIE2P-NEXT:    ret <16 x i8> [[TMP2]]
//
// CHECK-AIE2PS-LABEL: define dso_local noundef <16 x i8> @_Z20test_extract_v16int8Dv64_ai(
// CHECK-AIE2PS-SAME: <64 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[A]] to <16 x i32>
// CHECK-AIE2PS-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2ps.vextract.broadcast128.I512(<16 x i32> [[TMP0]], i32 [[IDX]])
// CHECK-AIE2PS-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[SHUFFLE_I_I]] to <16 x i8>
// CHECK-AIE2PS-NEXT:    ret <16 x i8> [[TMP2]]
//
v16int8 test_extract_v16int8 ( v64int8 a, int idx )
{
    return extract_v16int8 ( a, idx );
}


// CHECK-AIE2P-LABEL: define dso_local noundef <8 x i16> @_Z21test_extract_v8uint16Dv32_ti(
// CHECK-AIE2P-SAME: <32 x i16> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[A]] to <16 x i32>
// CHECK-AIE2P-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2p.vextract.broadcast128.I512(<16 x i32> [[TMP0]], i32 [[IDX]])
// CHECK-AIE2P-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[SHUFFLE_I_I]] to <8 x i16>
// CHECK-AIE2P-NEXT:    ret <8 x i16> [[TMP2]]
//
// CHECK-AIE2PS-LABEL: define dso_local noundef <8 x i16> @_Z21test_extract_v8uint16Dv32_ti(
// CHECK-AIE2PS-SAME: <32 x i16> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[A]] to <16 x i32>
// CHECK-AIE2PS-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2ps.vextract.broadcast128.I512(<16 x i32> [[TMP0]], i32 [[IDX]])
// CHECK-AIE2PS-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[SHUFFLE_I_I]] to <8 x i16>
// CHECK-AIE2PS-NEXT:    ret <8 x i16> [[TMP2]]
//
v8uint16 test_extract_v8uint16 ( v32uint16 a, int idx )
{
    return extract_v8uint16 ( a, idx );
}


// CHECK-AIE2P-LABEL: define dso_local noundef <8 x i16> @_Z20test_extract_v8int16Dv32_si(
// CHECK-AIE2P-SAME: <32 x i16> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[A]] to <16 x i32>
// CHECK-AIE2P-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2p.vextract.broadcast128.I512(<16 x i32> [[TMP0]], i32 [[IDX]])
// CHECK-AIE2P-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[SHUFFLE_I_I]] to <8 x i16>
// CHECK-AIE2P-NEXT:    ret <8 x i16> [[TMP2]]
//
// CHECK-AIE2PS-LABEL: define dso_local noundef <8 x i16> @_Z20test_extract_v8int16Dv32_si(
// CHECK-AIE2PS-SAME: <32 x i16> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[A]] to <16 x i32>
// CHECK-AIE2PS-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2ps.vextract.broadcast128.I512(<16 x i32> [[TMP0]], i32 [[IDX]])
// CHECK-AIE2PS-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[SHUFFLE_I_I]] to <8 x i16>
// CHECK-AIE2PS-NEXT:    ret <8 x i16> [[TMP2]]
//
v8int16 test_extract_v8int16 ( v32int16 a, int idx )
{
    return extract_v8int16 ( a, idx );
}


// CHECK-AIE2P-LABEL: define dso_local noundef <4 x i32> @_Z21test_extract_v4uint32Dv16_ji(
// CHECK-AIE2P-SAME: <16 x i32> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2p.vextract.broadcast128.I512(<16 x i32> [[A]], i32 [[IDX]])
// CHECK-AIE2P-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-AIE2P-NEXT:    ret <4 x i32> [[SHUFFLE_I_I]]
//
// CHECK-AIE2PS-LABEL: define dso_local noundef <4 x i32> @_Z21test_extract_v4uint32Dv16_ji(
// CHECK-AIE2PS-SAME: <16 x i32> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2ps.vextract.broadcast128.I512(<16 x i32> [[A]], i32 [[IDX]])
// CHECK-AIE2PS-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-AIE2PS-NEXT:    ret <4 x i32> [[SHUFFLE_I_I]]
//
v4uint32 test_extract_v4uint32 ( v16uint32 a, int idx )
{
    return extract_v4uint32 ( a, idx );
}


// CHECK-AIE2P-LABEL: define dso_local noundef <4 x i32> @_Z20test_extract_v4int32Dv16_ii(
// CHECK-AIE2P-SAME: <16 x i32> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2p.vextract.broadcast128.I512(<16 x i32> [[A]], i32 [[IDX]])
// CHECK-AIE2P-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-AIE2P-NEXT:    ret <4 x i32> [[SHUFFLE_I_I]]
//
// CHECK-AIE2PS-LABEL: define dso_local noundef <4 x i32> @_Z20test_extract_v4int32Dv16_ii(
// CHECK-AIE2PS-SAME: <16 x i32> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2ps.vextract.broadcast128.I512(<16 x i32> [[A]], i32 [[IDX]])
// CHECK-AIE2PS-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-AIE2PS-NEXT:    ret <4 x i32> [[SHUFFLE_I_I]]
//
v4int32 test_extract_v4int32 ( v16int32 a, int idx )
{
    return extract_v4int32 ( a, idx );
}


// CHECK-AIE2P-LABEL: define dso_local noundef <8 x bfloat> @_Z23test_extract_v8bfloat16Dv32_8bfloat16i(
// CHECK-AIE2P-SAME: <32 x bfloat> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x bfloat> [[A]] to <16 x i32>
// CHECK-AIE2P-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2p.vextract.broadcast128.I512(<16 x i32> [[TMP0]], i32 [[IDX]])
// CHECK-AIE2P-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[SHUFFLE_I_I]] to <8 x bfloat>
// CHECK-AIE2P-NEXT:    ret <8 x bfloat> [[TMP2]]
//
// CHECK-AIE2PS-LABEL: define dso_local noundef <8 x bfloat> @_Z23test_extract_v8bfloat16Dv32_8bfloat16i(
// CHECK-AIE2PS-SAME: <32 x bfloat> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <32 x bfloat> [[A]] to <16 x i32>
// CHECK-AIE2PS-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2ps.vextract.broadcast128.I512(<16 x i32> [[TMP0]], i32 [[IDX]])
// CHECK-AIE2PS-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[SHUFFLE_I_I]] to <8 x bfloat>
// CHECK-AIE2PS-NEXT:    ret <8 x bfloat> [[TMP2]]
//
v8bfloat16 test_extract_v8bfloat16 ( v32bfloat16 a, int idx )
{
    return extract_v8bfloat16 ( a, idx );
}


// CHECK-AIE2P-LABEL: define dso_local noundef <4 x float> @_Z20test_extract_v4floatDv16_fi(
// CHECK-AIE2P-SAME: <16 x float> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[A]] to <16 x i32>
// CHECK-AIE2P-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2p.vextract.broadcast128.I512(<16 x i32> [[TMP0]], i32 [[IDX]])
// CHECK-AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[TMP1]] to <16 x float>
// CHECK-AIE2P-NEXT:    [[TMP3:%.*]] = shufflevector <16 x float> [[TMP2]], <16 x float> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-AIE2P-NEXT:    ret <4 x float> [[TMP3]]
//
// CHECK-AIE2PS-LABEL: define dso_local noundef <4 x float> @_Z20test_extract_v4floatDv16_fi(
// CHECK-AIE2PS-SAME: <16 x float> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[A]] to <16 x i32>
// CHECK-AIE2PS-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2ps.vextract.broadcast128.I512(<16 x i32> [[TMP0]], i32 [[IDX]])
// CHECK-AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[TMP1]] to <16 x float>
// CHECK-AIE2PS-NEXT:    [[TMP3:%.*]] = shufflevector <16 x float> [[TMP2]], <16 x float> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-AIE2PS-NEXT:    ret <4 x float> [[TMP3]]
//
v4float test_extract_v4float ( v16float a, int idx )
{
    return extract_v4float ( a, idx );
}



// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z18test_set_v128uint4iDv16_DU8_(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <16 x i8> noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i8> [[A]] to <4 x i32>
// CHECK-NEXT:    [[REM_I_I:%.*]] = srem i32 [[IDX]], 4
// CHECK-NEXT:    switch i32 [[REM_I_I]], label [[IF_ELSE_I_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[IF_THEN_I_I:%.*]]
// CHECK-NEXT:      i32 1, label [[IF_THEN4_I_I:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN10_I_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then.i.i:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    br label [[_ZL13SET_V128UINT4IDV16_DU8__EXIT:%.*]]
// CHECK:       if.then4.i.i:
// CHECK-NEXT:    [[SHUFFLE5_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE5_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    br label [[_ZL13SET_V128UINT4IDV16_DU8__EXIT]]
// CHECK:       if.then10.i.i:
// CHECK-NEXT:    [[SHUFFLE11_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE12_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE11_I_I]], <8 x i32> undef, <16 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    br label [[_ZL13SET_V128UINT4IDV16_DU8__EXIT]]
// CHECK:       if.else.i.i:
// CHECK-NEXT:    [[SHUFFLE13_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE14_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE13_I_I]], <8 x i32> undef, <16 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    br label [[_ZL13SET_V128UINT4IDV16_DU8__EXIT]]
// CHECK:       _ZL13set_v128uint4iDv16_DU8_.exit:
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = phi <16 x i32> [ [[SHUFFLE1_I_I]], [[IF_THEN_I_I]] ], [ [[SHUFFLE6_I_I]], [[IF_THEN4_I_I]] ], [ [[SHUFFLE12_I_I]], [[IF_THEN10_I_I]] ], [ [[SHUFFLE14_I_I]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[RETVAL_0_I_I]] to <64 x i8>
// CHECK-NEXT:    ret <64 x i8> [[TMP1]]
//
v128uint4 test_set_v128uint4 ( int idx, v32uint4 a )
{
    return set_v128uint4 (idx, a);
}


// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z17test_set_v128int4iDv16_DB8_(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <16 x i8> noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i8> [[A]] to <4 x i32>
// CHECK-NEXT:    [[REM_I_I:%.*]] = srem i32 [[IDX]], 4
// CHECK-NEXT:    switch i32 [[REM_I_I]], label [[IF_ELSE_I_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[IF_THEN_I_I:%.*]]
// CHECK-NEXT:      i32 1, label [[IF_THEN4_I_I:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN10_I_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then.i.i:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    br label [[_ZL12SET_V128INT4IDV16_DB8__EXIT:%.*]]
// CHECK:       if.then4.i.i:
// CHECK-NEXT:    [[SHUFFLE5_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE5_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    br label [[_ZL12SET_V128INT4IDV16_DB8__EXIT]]
// CHECK:       if.then10.i.i:
// CHECK-NEXT:    [[SHUFFLE11_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE12_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE11_I_I]], <8 x i32> undef, <16 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    br label [[_ZL12SET_V128INT4IDV16_DB8__EXIT]]
// CHECK:       if.else.i.i:
// CHECK-NEXT:    [[SHUFFLE13_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE14_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE13_I_I]], <8 x i32> undef, <16 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    br label [[_ZL12SET_V128INT4IDV16_DB8__EXIT]]
// CHECK:       _ZL12set_v128int4iDv16_DB8_.exit:
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = phi <16 x i32> [ [[SHUFFLE1_I_I]], [[IF_THEN_I_I]] ], [ [[SHUFFLE6_I_I]], [[IF_THEN4_I_I]] ], [ [[SHUFFLE12_I_I]], [[IF_THEN10_I_I]] ], [ [[SHUFFLE14_I_I]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[RETVAL_0_I_I]] to <64 x i8>
// CHECK-NEXT:    ret <64 x i8> [[TMP1]]
//
v128int4 test_set_v128int4 ( int idx, v32int4 a )
{
    return set_v128int4 (idx, a);
}


// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z17test_set_v64uint8iDv16_h(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <16 x i8> noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i8> [[A]] to <4 x i32>
// CHECK-NEXT:    [[REM_I_I:%.*]] = srem i32 [[IDX]], 4
// CHECK-NEXT:    switch i32 [[REM_I_I]], label [[IF_ELSE_I_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[IF_THEN_I_I:%.*]]
// CHECK-NEXT:      i32 1, label [[IF_THEN4_I_I:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN10_I_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then.i.i:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    br label [[_ZL12SET_V64UINT8IDV16_H_EXIT:%.*]]
// CHECK:       if.then4.i.i:
// CHECK-NEXT:    [[SHUFFLE5_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE5_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    br label [[_ZL12SET_V64UINT8IDV16_H_EXIT]]
// CHECK:       if.then10.i.i:
// CHECK-NEXT:    [[SHUFFLE11_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE12_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE11_I_I]], <8 x i32> undef, <16 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    br label [[_ZL12SET_V64UINT8IDV16_H_EXIT]]
// CHECK:       if.else.i.i:
// CHECK-NEXT:    [[SHUFFLE13_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE14_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE13_I_I]], <8 x i32> undef, <16 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    br label [[_ZL12SET_V64UINT8IDV16_H_EXIT]]
// CHECK:       _ZL12set_v64uint8iDv16_h.exit:
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = phi <16 x i32> [ [[SHUFFLE1_I_I]], [[IF_THEN_I_I]] ], [ [[SHUFFLE6_I_I]], [[IF_THEN4_I_I]] ], [ [[SHUFFLE12_I_I]], [[IF_THEN10_I_I]] ], [ [[SHUFFLE14_I_I]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[RETVAL_0_I_I]] to <64 x i8>
// CHECK-NEXT:    ret <64 x i8> [[TMP1]]
//
v64uint8 test_set_v64uint8 ( int idx, v16uint8 a )
{
    return set_v64uint8 (idx, a);
}


// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z16test_set_v64int8iDv16_a(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <16 x i8> noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i8> [[A]] to <4 x i32>
// CHECK-NEXT:    [[REM_I_I:%.*]] = srem i32 [[IDX]], 4
// CHECK-NEXT:    switch i32 [[REM_I_I]], label [[IF_ELSE_I_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[IF_THEN_I_I:%.*]]
// CHECK-NEXT:      i32 1, label [[IF_THEN4_I_I:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN10_I_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then.i.i:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    br label [[_ZL11SET_V64INT8IDV16_A_EXIT:%.*]]
// CHECK:       if.then4.i.i:
// CHECK-NEXT:    [[SHUFFLE5_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE5_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    br label [[_ZL11SET_V64INT8IDV16_A_EXIT]]
// CHECK:       if.then10.i.i:
// CHECK-NEXT:    [[SHUFFLE11_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE12_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE11_I_I]], <8 x i32> undef, <16 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    br label [[_ZL11SET_V64INT8IDV16_A_EXIT]]
// CHECK:       if.else.i.i:
// CHECK-NEXT:    [[SHUFFLE13_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE14_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE13_I_I]], <8 x i32> undef, <16 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    br label [[_ZL11SET_V64INT8IDV16_A_EXIT]]
// CHECK:       _ZL11set_v64int8iDv16_a.exit:
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = phi <16 x i32> [ [[SHUFFLE1_I_I]], [[IF_THEN_I_I]] ], [ [[SHUFFLE6_I_I]], [[IF_THEN4_I_I]] ], [ [[SHUFFLE12_I_I]], [[IF_THEN10_I_I]] ], [ [[SHUFFLE14_I_I]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[RETVAL_0_I_I]] to <64 x i8>
// CHECK-NEXT:    ret <64 x i8> [[TMP1]]
//
v64int8 test_set_v64int8 ( int idx, v16int8 a )
{
    return set_v64int8 (idx, a);
}


// CHECK-LABEL: define dso_local noundef <32 x i16> @_Z18test_set_v32uint16iDv8_t(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <8 x i16> noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x i16> [[A]] to <4 x i32>
// CHECK-NEXT:    [[REM_I_I:%.*]] = srem i32 [[IDX]], 4
// CHECK-NEXT:    switch i32 [[REM_I_I]], label [[IF_ELSE_I_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[IF_THEN_I_I:%.*]]
// CHECK-NEXT:      i32 1, label [[IF_THEN4_I_I:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN10_I_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then.i.i:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    br label [[_ZL13SET_V32UINT16IDV8_T_EXIT:%.*]]
// CHECK:       if.then4.i.i:
// CHECK-NEXT:    [[SHUFFLE5_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE5_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    br label [[_ZL13SET_V32UINT16IDV8_T_EXIT]]
// CHECK:       if.then10.i.i:
// CHECK-NEXT:    [[SHUFFLE11_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE12_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE11_I_I]], <8 x i32> undef, <16 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    br label [[_ZL13SET_V32UINT16IDV8_T_EXIT]]
// CHECK:       if.else.i.i:
// CHECK-NEXT:    [[SHUFFLE13_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE14_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE13_I_I]], <8 x i32> undef, <16 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    br label [[_ZL13SET_V32UINT16IDV8_T_EXIT]]
// CHECK:       _ZL13set_v32uint16iDv8_t.exit:
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = phi <16 x i32> [ [[SHUFFLE1_I_I]], [[IF_THEN_I_I]] ], [ [[SHUFFLE6_I_I]], [[IF_THEN4_I_I]] ], [ [[SHUFFLE12_I_I]], [[IF_THEN10_I_I]] ], [ [[SHUFFLE14_I_I]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[RETVAL_0_I_I]] to <32 x i16>
// CHECK-NEXT:    ret <32 x i16> [[TMP1]]
//
v32uint16 test_set_v32uint16 ( int idx, v8uint16 a )
{
    return set_v32uint16 (idx, a);
}


// CHECK-LABEL: define dso_local noundef <32 x i16> @_Z17test_set_v32int16iDv8_s(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <8 x i16> noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x i16> [[A]] to <4 x i32>
// CHECK-NEXT:    [[REM_I_I:%.*]] = srem i32 [[IDX]], 4
// CHECK-NEXT:    switch i32 [[REM_I_I]], label [[IF_ELSE_I_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[IF_THEN_I_I:%.*]]
// CHECK-NEXT:      i32 1, label [[IF_THEN4_I_I:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN10_I_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then.i.i:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    br label [[_ZL12SET_V32INT16IDV8_S_EXIT:%.*]]
// CHECK:       if.then4.i.i:
// CHECK-NEXT:    [[SHUFFLE5_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE5_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    br label [[_ZL12SET_V32INT16IDV8_S_EXIT]]
// CHECK:       if.then10.i.i:
// CHECK-NEXT:    [[SHUFFLE11_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE12_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE11_I_I]], <8 x i32> undef, <16 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    br label [[_ZL12SET_V32INT16IDV8_S_EXIT]]
// CHECK:       if.else.i.i:
// CHECK-NEXT:    [[SHUFFLE13_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE14_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE13_I_I]], <8 x i32> undef, <16 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    br label [[_ZL12SET_V32INT16IDV8_S_EXIT]]
// CHECK:       _ZL12set_v32int16iDv8_s.exit:
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = phi <16 x i32> [ [[SHUFFLE1_I_I]], [[IF_THEN_I_I]] ], [ [[SHUFFLE6_I_I]], [[IF_THEN4_I_I]] ], [ [[SHUFFLE12_I_I]], [[IF_THEN10_I_I]] ], [ [[SHUFFLE14_I_I]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[RETVAL_0_I_I]] to <32 x i16>
// CHECK-NEXT:    ret <32 x i16> [[TMP1]]
//
v32int16 test_set_v32int16 ( int idx, v8int16 a )
{
    return set_v32int16 (idx, a);
}


// CHECK-LABEL: define dso_local noundef <16 x i32> @_Z18test_set_v16uint32iDv4_j(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <4 x i32> noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[REM_I_I:%.*]] = srem i32 [[IDX]], 4
// CHECK-NEXT:    switch i32 [[REM_I_I]], label [[IF_ELSE_I_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[IF_THEN_I_I:%.*]]
// CHECK-NEXT:      i32 1, label [[IF_THEN4_I_I:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN10_I_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then.i.i:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[A]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    br label [[_ZL13SET_V16UINT32IDV4_J_EXIT:%.*]]
// CHECK:       if.then4.i.i:
// CHECK-NEXT:    [[SHUFFLE5_I_I:%.*]] = shufflevector <4 x i32> [[A]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE5_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    br label [[_ZL13SET_V16UINT32IDV4_J_EXIT]]
// CHECK:       if.then10.i.i:
// CHECK-NEXT:    [[SHUFFLE11_I_I:%.*]] = shufflevector <4 x i32> [[A]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE12_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE11_I_I]], <8 x i32> undef, <16 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    br label [[_ZL13SET_V16UINT32IDV4_J_EXIT]]
// CHECK:       if.else.i.i:
// CHECK-NEXT:    [[SHUFFLE13_I_I:%.*]] = shufflevector <4 x i32> [[A]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE14_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE13_I_I]], <8 x i32> undef, <16 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    br label [[_ZL13SET_V16UINT32IDV4_J_EXIT]]
// CHECK:       _ZL13set_v16uint32iDv4_j.exit:
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = phi <16 x i32> [ [[SHUFFLE1_I_I]], [[IF_THEN_I_I]] ], [ [[SHUFFLE6_I_I]], [[IF_THEN4_I_I]] ], [ [[SHUFFLE12_I_I]], [[IF_THEN10_I_I]] ], [ [[SHUFFLE14_I_I]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    ret <16 x i32> [[RETVAL_0_I_I]]
//
v16uint32 test_set_v16uint32 ( int idx, v4uint32 a )
{
    return set_v16uint32 (idx, a);
}


// CHECK-LABEL: define dso_local noundef <16 x i32> @_Z17test_set_v16int32iDv4_i(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <4 x i32> noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[REM_I_I:%.*]] = srem i32 [[IDX]], 4
// CHECK-NEXT:    switch i32 [[REM_I_I]], label [[IF_ELSE_I_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[IF_THEN_I_I:%.*]]
// CHECK-NEXT:      i32 1, label [[IF_THEN4_I_I:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN10_I_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then.i.i:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[A]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    br label [[_ZL12SET_V16INT32IDV4_I_EXIT:%.*]]
// CHECK:       if.then4.i.i:
// CHECK-NEXT:    [[SHUFFLE5_I_I:%.*]] = shufflevector <4 x i32> [[A]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE5_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    br label [[_ZL12SET_V16INT32IDV4_I_EXIT]]
// CHECK:       if.then10.i.i:
// CHECK-NEXT:    [[SHUFFLE11_I_I:%.*]] = shufflevector <4 x i32> [[A]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE12_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE11_I_I]], <8 x i32> undef, <16 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    br label [[_ZL12SET_V16INT32IDV4_I_EXIT]]
// CHECK:       if.else.i.i:
// CHECK-NEXT:    [[SHUFFLE13_I_I:%.*]] = shufflevector <4 x i32> [[A]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE14_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE13_I_I]], <8 x i32> undef, <16 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    br label [[_ZL12SET_V16INT32IDV4_I_EXIT]]
// CHECK:       _ZL12set_v16int32iDv4_i.exit:
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = phi <16 x i32> [ [[SHUFFLE1_I_I]], [[IF_THEN_I_I]] ], [ [[SHUFFLE6_I_I]], [[IF_THEN4_I_I]] ], [ [[SHUFFLE12_I_I]], [[IF_THEN10_I_I]] ], [ [[SHUFFLE14_I_I]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    ret <16 x i32> [[RETVAL_0_I_I]]
//
v16int32 test_set_v16int32 ( int idx, v4int32 a )
{
    return set_v16int32 (idx, a);
}


// CHECK-LABEL: define dso_local noundef <32 x bfloat> @_Z20test_set_v32bfloat16iDv8_8bfloat16(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <8 x bfloat> noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x bfloat> [[A]] to <4 x i32>
// CHECK-NEXT:    [[REM_I_I:%.*]] = srem i32 [[IDX]], 4
// CHECK-NEXT:    switch i32 [[REM_I_I]], label [[IF_ELSE_I_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[IF_THEN_I_I:%.*]]
// CHECK-NEXT:      i32 1, label [[IF_THEN4_I_I:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN10_I_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then.i.i:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    br label [[_ZL15SET_V32BFLOAT16IDV8_8BFLOAT16_EXIT:%.*]]
// CHECK:       if.then4.i.i:
// CHECK-NEXT:    [[SHUFFLE5_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE5_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    br label [[_ZL15SET_V32BFLOAT16IDV8_8BFLOAT16_EXIT]]
// CHECK:       if.then10.i.i:
// CHECK-NEXT:    [[SHUFFLE11_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE12_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE11_I_I]], <8 x i32> undef, <16 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    br label [[_ZL15SET_V32BFLOAT16IDV8_8BFLOAT16_EXIT]]
// CHECK:       if.else.i.i:
// CHECK-NEXT:    [[SHUFFLE13_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE14_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE13_I_I]], <8 x i32> undef, <16 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    br label [[_ZL15SET_V32BFLOAT16IDV8_8BFLOAT16_EXIT]]
// CHECK:       _ZL15set_v32bfloat16iDv8_8bfloat16.exit:
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = phi <16 x i32> [ [[SHUFFLE1_I_I]], [[IF_THEN_I_I]] ], [ [[SHUFFLE6_I_I]], [[IF_THEN4_I_I]] ], [ [[SHUFFLE12_I_I]], [[IF_THEN10_I_I]] ], [ [[SHUFFLE14_I_I]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[RETVAL_0_I_I]] to <32 x bfloat>
// CHECK-NEXT:    ret <32 x bfloat> [[TMP1]]
//
v32bfloat16 test_set_v32bfloat16 ( int idx, v8bfloat16 a )
{
    return set_v32bfloat16 (idx, a);
}


// CHECK-LABEL: define dso_local noundef <16 x float> @_Z17test_set_v16floatiDv4_f(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <4 x float> noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x float> [[A]] to <4 x i32>
// CHECK-NEXT:    [[REM_I_I:%.*]] = srem i32 [[IDX]], 4
// CHECK-NEXT:    switch i32 [[REM_I_I]], label [[IF_ELSE_I_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[IF_THEN_I_I:%.*]]
// CHECK-NEXT:      i32 1, label [[IF_THEN4_I_I:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN10_I_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then.i.i:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    br label [[_ZL12SET_V16FLOATIDV4_F_EXIT:%.*]]
// CHECK:       if.then4.i.i:
// CHECK-NEXT:    [[SHUFFLE5_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE5_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    br label [[_ZL12SET_V16FLOATIDV4_F_EXIT]]
// CHECK:       if.then10.i.i:
// CHECK-NEXT:    [[SHUFFLE11_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE12_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE11_I_I]], <8 x i32> undef, <16 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    br label [[_ZL12SET_V16FLOATIDV4_F_EXIT]]
// CHECK:       if.else.i.i:
// CHECK-NEXT:    [[SHUFFLE13_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE14_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE13_I_I]], <8 x i32> undef, <16 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    br label [[_ZL12SET_V16FLOATIDV4_F_EXIT]]
// CHECK:       _ZL12set_v16floatiDv4_f.exit:
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = phi <16 x i32> [ [[SHUFFLE1_I_I]], [[IF_THEN_I_I]] ], [ [[SHUFFLE6_I_I]], [[IF_THEN4_I_I]] ], [ [[SHUFFLE12_I_I]], [[IF_THEN10_I_I]] ], [ [[SHUFFLE14_I_I]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[RETVAL_0_I_I]] to <16 x float>
// CHECK-NEXT:    ret <16 x float> [[TMP1]]
//
v16float test_set_v16float ( int idx, v4float a )
{
    return set_v16float (idx, a);
}


// CHECK-LABEL: define dso_local noundef <16 x i8> @_Z21test_extract_v32uint4Dv32_DU8_i(
// CHECK-SAME: <32 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8> [[A]] to <8 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP1]], 0
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <4 x i32> [[SHUFFLE_I_I]], <4 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[RETVAL_0_I_I]] to <16 x i8>
// CHECK-NEXT:    ret <16 x i8> [[TMP2]]
//
v32uint4 test_extract_v32uint4 ( v64uint4 a, int idx )
{
    return extract_v32uint4 (a, idx);
}

// CHECK-LABEL: define dso_local noundef <16 x i8> @_Z20test_extract_v32int4Dv32_DB8_i(
// CHECK-SAME: <32 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8> [[A]] to <8 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP1]], 0
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <4 x i32> [[SHUFFLE_I_I]], <4 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[RETVAL_0_I_I]] to <16 x i8>
// CHECK-NEXT:    ret <16 x i8> [[TMP2]]
//
v32int4 test_extract_v32int4 ( v64int4 a, int idx )
{
    return extract_v32int4 (a, idx);
}

// CHECK-LABEL: define dso_local noundef <16 x i8> @_Z21test_extract_v16uint8Dv32_hi(
// CHECK-SAME: <32 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8> [[A]] to <8 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP1]], 0
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <4 x i32> [[SHUFFLE_I_I]], <4 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[RETVAL_0_I_I]] to <16 x i8>
// CHECK-NEXT:    ret <16 x i8> [[TMP2]]
//
v16uint8 test_extract_v16uint8 ( v32uint8 a, int idx )
{
    return extract_v16uint8 (a, idx);
}

// CHECK-LABEL: define dso_local noundef <16 x i8> @_Z20test_extract_v16int8Dv32_ai(
// CHECK-SAME: <32 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8> [[A]] to <8 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP1]], 0
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <4 x i32> [[SHUFFLE_I_I]], <4 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[RETVAL_0_I_I]] to <16 x i8>
// CHECK-NEXT:    ret <16 x i8> [[TMP2]]
//
v16int8 test_extract_v16int8 ( v32int8 a, int idx )
{
    return extract_v16int8 (a, idx);
}

// CHECK-LABEL: define dso_local noundef <8 x i16> @_Z21test_extract_v8uint16Dv16_ti(
// CHECK-SAME: <16 x i16> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i16> [[A]] to <8 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP1]], 0
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <4 x i32> [[SHUFFLE_I_I]], <4 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[RETVAL_0_I_I]] to <8 x i16>
// CHECK-NEXT:    ret <8 x i16> [[TMP2]]
//
v8uint16 test_extract_v8uint16 ( v16uint16 a, int idx )
{
    return extract_v8uint16 (a, idx);
}

// CHECK-LABEL: define dso_local noundef <8 x i16> @_Z20test_extract_v8int16Dv16_si(
// CHECK-SAME: <16 x i16> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i16> [[A]] to <8 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP1]], 0
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <4 x i32> [[SHUFFLE_I_I]], <4 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[RETVAL_0_I_I]] to <8 x i16>
// CHECK-NEXT:    ret <8 x i16> [[TMP2]]
//
v8int16 test_extract_v8int16 ( v16int16 a, int idx )
{
    return extract_v8int16 (a, idx);
}

// CHECK-LABEL: define dso_local noundef <4 x i32> @_Z21test_extract_v4uint32Dv8_ji(
// CHECK-SAME: <8 x i32> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP0]], 0
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <4 x i32> [[SHUFFLE_I_I]], <4 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    ret <4 x i32> [[RETVAL_0_I_I]]
//
v4uint32 test_extract_v4uint32 ( v8uint32 a, int idx )
{
    return extract_v4uint32 (a, idx);
}

// CHECK-LABEL: define dso_local noundef <4 x i32> @_Z20test_extract_v4int32Dv8_ii(
// CHECK-SAME: <8 x i32> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP0]], 0
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <4 x i32> [[SHUFFLE_I_I]], <4 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    ret <4 x i32> [[RETVAL_0_I_I]]
//
v4int32 test_extract_v4int32 ( v8int32 a, int idx )
{
    return extract_v4int32 (a, idx);
}

// CHECK-LABEL: define dso_local noundef <8 x bfloat> @_Z23test_extract_v8bfloat16Dv16_8bfloat16i(
// CHECK-SAME: <16 x bfloat> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x bfloat> [[A]] to <8 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP1]], 0
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <4 x i32> [[SHUFFLE_I_I]], <4 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[RETVAL_0_I_I]] to <8 x bfloat>
// CHECK-NEXT:    ret <8 x bfloat> [[TMP2]]
//
v8bfloat16 test_extract_v8bfloat16 ( v16bfloat16 a, int idx )
{
    return extract_v8bfloat16 (a, idx);
}

// CHECK-LABEL: define dso_local noundef <4 x float> @_Z20test_extract_v4floatDv8_fi(
// CHECK-SAME: <8 x float> noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x float> [[A]] to <8 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP1]], 0
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <4 x i32> [[SHUFFLE_I_I]], <4 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[RETVAL_0_I_I]] to <4 x float>
// CHECK-NEXT:    ret <4 x float> [[TMP2]]
//
v4float test_extract_v4float ( v8float a, int idx )
{
    return extract_v4float (a, idx);
}


// CHECK-LABEL: define dso_local noundef <32 x i8> @_Z17test_set_v64uint4iDv16_DU8_(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <16 x i8> noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i8> [[A]] to <4 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP1]], 0
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i32> [[RETVAL_0_I_I]] to <32 x i8>
// CHECK-NEXT:    ret <32 x i8> [[TMP2]]
//
v64uint4 test_set_v64uint4 (int idx, v32uint4 a )
{
    return set_v64uint4(idx, a);
}
// CHECK-LABEL: define dso_local noundef <32 x i8> @_Z16test_set_v64int4iDv16_DB8_(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <16 x i8> noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i8> [[A]] to <4 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP1]], 0
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i32> [[RETVAL_0_I_I]] to <32 x i8>
// CHECK-NEXT:    ret <32 x i8> [[TMP2]]
//
v64int4 test_set_v64int4 (int idx, v32int4 a )
{
    return set_v64int4(idx, a);
}
// CHECK-LABEL: define dso_local noundef <32 x i8> @_Z17test_set_v32uint8iDv16_h(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <16 x i8> noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i8> [[A]] to <4 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP1]], 0
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i32> [[RETVAL_0_I_I]] to <32 x i8>
// CHECK-NEXT:    ret <32 x i8> [[TMP2]]
//
v32uint8 test_set_v32uint8 (int idx, v16uint8 a )
{
    return set_v32uint8(idx, a);
}
// CHECK-LABEL: define dso_local noundef <32 x i8> @_Z16test_set_v32int8iDv16_a(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <16 x i8> noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i8> [[A]] to <4 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP1]], 0
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i32> [[RETVAL_0_I_I]] to <32 x i8>
// CHECK-NEXT:    ret <32 x i8> [[TMP2]]
//
v32int8 test_set_v32int8 (int idx, v16int8 a )
{
    return set_v32int8(idx, a);
}
// CHECK-LABEL: define dso_local noundef <16 x i16> @_Z18test_set_v16uint16iDv8_t(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <8 x i16> noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x i16> [[A]] to <4 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP1]], 0
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i32> [[RETVAL_0_I_I]] to <16 x i16>
// CHECK-NEXT:    ret <16 x i16> [[TMP2]]
//
v16uint16 test_set_v16uint16 (int idx, v8uint16 a )
{
    return set_v16uint16(idx, a);
}
// CHECK-LABEL: define dso_local noundef <16 x i16> @_Z17test_set_v16int16iDv8_s(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <8 x i16> noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x i16> [[A]] to <4 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP1]], 0
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i32> [[RETVAL_0_I_I]] to <16 x i16>
// CHECK-NEXT:    ret <16 x i16> [[TMP2]]
//
v16int16 test_set_v16int16 (int idx, v8int16 a )
{
    return set_v16int16(idx, a);
}
// CHECK-LABEL: define dso_local noundef <8 x i32> @_Z17test_set_v8uint32iDv4_j(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <4 x i32> noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP0]], 0
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[A]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <4 x i32> [[A]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    ret <8 x i32> [[RETVAL_0_I_I]]
//
v8uint32 test_set_v8uint32 (int idx, v4uint32 a )
{
    return set_v8uint32(idx, a);
}
// CHECK-LABEL: define dso_local noundef <8 x i32> @_Z16test_set_v8int32iDv4_i(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <4 x i32> noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP0]], 0
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[A]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <4 x i32> [[A]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    ret <8 x i32> [[RETVAL_0_I_I]]
//
v8int32 test_set_v8int32 (int idx, v4int32 a )
{
    return set_v8int32(idx, a);
}
// CHECK-LABEL: define dso_local noundef <16 x bfloat> @_Z20test_set_v16bfloat16iDv8_8bfloat16(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <8 x bfloat> noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x bfloat> [[A]] to <4 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP1]], 0
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i32> [[RETVAL_0_I_I]] to <16 x bfloat>
// CHECK-NEXT:    ret <16 x bfloat> [[TMP2]]
//
v16bfloat16 test_set_v16bfloat16 (int idx, v8bfloat16 a )
{
    return set_v16bfloat16(idx, a);
}
// CHECK-LABEL: define dso_local noundef <8 x float> @_Z16test_set_v8floatiDv4_f(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <4 x float> noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x float> [[A]] to <4 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP1]], 0
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i32> [[RETVAL_0_I_I]] to <8 x float>
// CHECK-NEXT:    ret <8 x float> [[TMP2]]
//
v8float test_set_v8float (int idx, v4float a )
{
    return set_v8float(idx, a);
}


// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_DU8_iDv16_S_(
// CHECK-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <16 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i8> [[B]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[REM_I_I:%.*]] = srem i32 [[IDX]], 4
// CHECK-NEXT:    switch i32 [[REM_I_I]], label [[IF_ELSE_I_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[IF_THEN_I_I:%.*]]
// CHECK-NEXT:      i32 1, label [[IF_THEN5_I_I:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN10_I_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then.i.i:
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERTDV64_DU8_IDV16_S__EXIT:%.*]]
// CHECK:       if.then5.i.i:
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 0, i32 1, i32 2, i32 3, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERTDV64_DU8_IDV16_S__EXIT]]
// CHECK:       if.then10.i.i:
// CHECK-NEXT:    [[SHUFFLE11_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 0, i32 1, i32 2, i32 3, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERTDV64_DU8_IDV16_S__EXIT]]
// CHECK:       if.else.i.i:
// CHECK-NEXT:    [[SHUFFLE12_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    br label [[_ZL6INSERTDV64_DU8_IDV16_S__EXIT]]
// CHECK:       _ZL6insertDv64_DU8_iDv16_S_.exit:
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = phi <16 x i32> [ [[SHUFFLE2_I_I]], [[IF_THEN_I_I]] ], [ [[SHUFFLE6_I_I]], [[IF_THEN5_I_I]] ], [ [[SHUFFLE11_I_I]], [[IF_THEN10_I_I]] ], [ [[SHUFFLE12_I_I]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[RETVAL_0_I_I]] to <64 x i8>
// CHECK-NEXT:    ret <64 x i8> [[TMP2]]
//
v128uint4 test_insert (v128uint4 v, int idx, v32uint4 b )
{
    return insert(v, idx, b);
}
// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_DB8_iDv16_S_(
// CHECK-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <16 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i8> [[B]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[REM_I_I:%.*]] = srem i32 [[IDX]], 4
// CHECK-NEXT:    switch i32 [[REM_I_I]], label [[IF_ELSE_I_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[IF_THEN_I_I:%.*]]
// CHECK-NEXT:      i32 1, label [[IF_THEN5_I_I:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN10_I_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then.i.i:
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERTDV64_DB8_IDV16_S__EXIT:%.*]]
// CHECK:       if.then5.i.i:
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 0, i32 1, i32 2, i32 3, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERTDV64_DB8_IDV16_S__EXIT]]
// CHECK:       if.then10.i.i:
// CHECK-NEXT:    [[SHUFFLE11_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 0, i32 1, i32 2, i32 3, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERTDV64_DB8_IDV16_S__EXIT]]
// CHECK:       if.else.i.i:
// CHECK-NEXT:    [[SHUFFLE12_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    br label [[_ZL6INSERTDV64_DB8_IDV16_S__EXIT]]
// CHECK:       _ZL6insertDv64_DB8_iDv16_S_.exit:
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = phi <16 x i32> [ [[SHUFFLE2_I_I]], [[IF_THEN_I_I]] ], [ [[SHUFFLE6_I_I]], [[IF_THEN5_I_I]] ], [ [[SHUFFLE11_I_I]], [[IF_THEN10_I_I]] ], [ [[SHUFFLE12_I_I]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[RETVAL_0_I_I]] to <64 x i8>
// CHECK-NEXT:    ret <64 x i8> [[TMP2]]
//
v128int4 test_insert (v128int4 v, int idx, v32int4 b )
{
    return insert(v, idx, b);
}
// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_hiDv16_h(
// CHECK-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <16 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i8> [[B]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[REM_I_I:%.*]] = srem i32 [[IDX]], 4
// CHECK-NEXT:    switch i32 [[REM_I_I]], label [[IF_ELSE_I_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[IF_THEN_I_I:%.*]]
// CHECK-NEXT:      i32 1, label [[IF_THEN5_I_I:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN10_I_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then.i.i:
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERTDV64_HIDV16_H_EXIT:%.*]]
// CHECK:       if.then5.i.i:
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 0, i32 1, i32 2, i32 3, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERTDV64_HIDV16_H_EXIT]]
// CHECK:       if.then10.i.i:
// CHECK-NEXT:    [[SHUFFLE11_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 0, i32 1, i32 2, i32 3, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERTDV64_HIDV16_H_EXIT]]
// CHECK:       if.else.i.i:
// CHECK-NEXT:    [[SHUFFLE12_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    br label [[_ZL6INSERTDV64_HIDV16_H_EXIT]]
// CHECK:       _ZL6insertDv64_hiDv16_h.exit:
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = phi <16 x i32> [ [[SHUFFLE2_I_I]], [[IF_THEN_I_I]] ], [ [[SHUFFLE6_I_I]], [[IF_THEN5_I_I]] ], [ [[SHUFFLE11_I_I]], [[IF_THEN10_I_I]] ], [ [[SHUFFLE12_I_I]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[RETVAL_0_I_I]] to <64 x i8>
// CHECK-NEXT:    ret <64 x i8> [[TMP2]]
//
v64uint8 test_insert (v64uint8 v, int idx, v16uint8 b )
{
    return insert(v, idx, b);
}
// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_aiDv16_a(
// CHECK-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <16 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i8> [[B]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[REM_I_I:%.*]] = srem i32 [[IDX]], 4
// CHECK-NEXT:    switch i32 [[REM_I_I]], label [[IF_ELSE_I_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[IF_THEN_I_I:%.*]]
// CHECK-NEXT:      i32 1, label [[IF_THEN5_I_I:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN10_I_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then.i.i:
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERTDV64_AIDV16_A_EXIT:%.*]]
// CHECK:       if.then5.i.i:
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 0, i32 1, i32 2, i32 3, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERTDV64_AIDV16_A_EXIT]]
// CHECK:       if.then10.i.i:
// CHECK-NEXT:    [[SHUFFLE11_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 0, i32 1, i32 2, i32 3, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERTDV64_AIDV16_A_EXIT]]
// CHECK:       if.else.i.i:
// CHECK-NEXT:    [[SHUFFLE12_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    br label [[_ZL6INSERTDV64_AIDV16_A_EXIT]]
// CHECK:       _ZL6insertDv64_aiDv16_a.exit:
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = phi <16 x i32> [ [[SHUFFLE2_I_I]], [[IF_THEN_I_I]] ], [ [[SHUFFLE6_I_I]], [[IF_THEN5_I_I]] ], [ [[SHUFFLE11_I_I]], [[IF_THEN10_I_I]] ], [ [[SHUFFLE12_I_I]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[RETVAL_0_I_I]] to <64 x i8>
// CHECK-NEXT:    ret <64 x i8> [[TMP2]]
//
v64int8 test_insert (v64int8 v, int idx, v16int8 b )
{
    return insert(v, idx, b);
}
// CHECK-LABEL: define dso_local noundef <32 x i16> @_Z11test_insertDv32_tiDv8_t(
// CHECK-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <8 x i16> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[V]] to <16 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i16> [[B]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[REM_I_I:%.*]] = srem i32 [[IDX]], 4
// CHECK-NEXT:    switch i32 [[REM_I_I]], label [[IF_ELSE_I_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[IF_THEN_I_I:%.*]]
// CHECK-NEXT:      i32 1, label [[IF_THEN5_I_I:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN10_I_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then.i.i:
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERTDV32_TIDV8_T_EXIT:%.*]]
// CHECK:       if.then5.i.i:
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 0, i32 1, i32 2, i32 3, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERTDV32_TIDV8_T_EXIT]]
// CHECK:       if.then10.i.i:
// CHECK-NEXT:    [[SHUFFLE11_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 0, i32 1, i32 2, i32 3, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERTDV32_TIDV8_T_EXIT]]
// CHECK:       if.else.i.i:
// CHECK-NEXT:    [[SHUFFLE12_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    br label [[_ZL6INSERTDV32_TIDV8_T_EXIT]]
// CHECK:       _ZL6insertDv32_tiDv8_t.exit:
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = phi <16 x i32> [ [[SHUFFLE2_I_I]], [[IF_THEN_I_I]] ], [ [[SHUFFLE6_I_I]], [[IF_THEN5_I_I]] ], [ [[SHUFFLE11_I_I]], [[IF_THEN10_I_I]] ], [ [[SHUFFLE12_I_I]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[RETVAL_0_I_I]] to <32 x i16>
// CHECK-NEXT:    ret <32 x i16> [[TMP2]]
//
v32uint16 test_insert (v32uint16 v, int idx, v8uint16 b )
{
    return insert(v, idx, b);
}
// CHECK-LABEL: define dso_local noundef <32 x i16> @_Z11test_insertDv32_siDv8_s(
// CHECK-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <8 x i16> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[V]] to <16 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i16> [[B]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[REM_I_I:%.*]] = srem i32 [[IDX]], 4
// CHECK-NEXT:    switch i32 [[REM_I_I]], label [[IF_ELSE_I_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[IF_THEN_I_I:%.*]]
// CHECK-NEXT:      i32 1, label [[IF_THEN5_I_I:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN10_I_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then.i.i:
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERTDV32_SIDV8_S_EXIT:%.*]]
// CHECK:       if.then5.i.i:
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 0, i32 1, i32 2, i32 3, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERTDV32_SIDV8_S_EXIT]]
// CHECK:       if.then10.i.i:
// CHECK-NEXT:    [[SHUFFLE11_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 0, i32 1, i32 2, i32 3, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERTDV32_SIDV8_S_EXIT]]
// CHECK:       if.else.i.i:
// CHECK-NEXT:    [[SHUFFLE12_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    br label [[_ZL6INSERTDV32_SIDV8_S_EXIT]]
// CHECK:       _ZL6insertDv32_siDv8_s.exit:
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = phi <16 x i32> [ [[SHUFFLE2_I_I]], [[IF_THEN_I_I]] ], [ [[SHUFFLE6_I_I]], [[IF_THEN5_I_I]] ], [ [[SHUFFLE11_I_I]], [[IF_THEN10_I_I]] ], [ [[SHUFFLE12_I_I]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[RETVAL_0_I_I]] to <32 x i16>
// CHECK-NEXT:    ret <32 x i16> [[TMP2]]
//
v32int16 test_insert (v32int16 v, int idx, v8int16 b )
{
    return insert(v, idx, b);
}
// CHECK-LABEL: define dso_local noundef <16 x i32> @_Z11test_insertDv16_jiDv4_j(
// CHECK-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <4 x i32> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[B]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[REM_I_I:%.*]] = srem i32 [[IDX]], 4
// CHECK-NEXT:    switch i32 [[REM_I_I]], label [[IF_ELSE_I_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[IF_THEN_I_I:%.*]]
// CHECK-NEXT:      i32 1, label [[IF_THEN5_I_I:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN10_I_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then.i.i:
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[V]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERTDV16_JIDV4_J_EXIT:%.*]]
// CHECK:       if.then5.i.i:
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[V]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 0, i32 1, i32 2, i32 3, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERTDV16_JIDV4_J_EXIT]]
// CHECK:       if.then10.i.i:
// CHECK-NEXT:    [[SHUFFLE11_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[V]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 0, i32 1, i32 2, i32 3, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERTDV16_JIDV4_J_EXIT]]
// CHECK:       if.else.i.i:
// CHECK-NEXT:    [[SHUFFLE12_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[V]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    br label [[_ZL6INSERTDV16_JIDV4_J_EXIT]]
// CHECK:       _ZL6insertDv16_jiDv4_j.exit:
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = phi <16 x i32> [ [[SHUFFLE2_I_I]], [[IF_THEN_I_I]] ], [ [[SHUFFLE6_I_I]], [[IF_THEN5_I_I]] ], [ [[SHUFFLE11_I_I]], [[IF_THEN10_I_I]] ], [ [[SHUFFLE12_I_I]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    ret <16 x i32> [[RETVAL_0_I_I]]
//
v16uint32 test_insert (v16uint32 v, int idx, v4uint32 b )
{
    return insert(v, idx, b);
}
// CHECK-LABEL: define dso_local noundef <16 x i32> @_Z11test_insertDv16_iiDv4_i(
// CHECK-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <4 x i32> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[B]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[REM_I_I:%.*]] = srem i32 [[IDX]], 4
// CHECK-NEXT:    switch i32 [[REM_I_I]], label [[IF_ELSE_I_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[IF_THEN_I_I:%.*]]
// CHECK-NEXT:      i32 1, label [[IF_THEN5_I_I:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN10_I_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then.i.i:
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[V]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERTDV16_IIDV4_I_EXIT:%.*]]
// CHECK:       if.then5.i.i:
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[V]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 0, i32 1, i32 2, i32 3, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERTDV16_IIDV4_I_EXIT]]
// CHECK:       if.then10.i.i:
// CHECK-NEXT:    [[SHUFFLE11_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[V]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 0, i32 1, i32 2, i32 3, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERTDV16_IIDV4_I_EXIT]]
// CHECK:       if.else.i.i:
// CHECK-NEXT:    [[SHUFFLE12_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[V]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    br label [[_ZL6INSERTDV16_IIDV4_I_EXIT]]
// CHECK:       _ZL6insertDv16_iiDv4_i.exit:
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = phi <16 x i32> [ [[SHUFFLE2_I_I]], [[IF_THEN_I_I]] ], [ [[SHUFFLE6_I_I]], [[IF_THEN5_I_I]] ], [ [[SHUFFLE11_I_I]], [[IF_THEN10_I_I]] ], [ [[SHUFFLE12_I_I]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    ret <16 x i32> [[RETVAL_0_I_I]]
//
v16int32 test_insert (v16int32 v, int idx, v4int32 b )
{
    return insert(v, idx, b);
}
// CHECK-LABEL: define dso_local noundef <32 x bfloat> @_Z11test_insertDv32_8bfloat16iDv8_S_(
// CHECK-SAME: <32 x bfloat> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <8 x bfloat> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x bfloat> [[V]] to <16 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x bfloat> [[B]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[REM_I_I:%.*]] = srem i32 [[IDX]], 4
// CHECK-NEXT:    switch i32 [[REM_I_I]], label [[IF_ELSE_I_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[IF_THEN_I_I:%.*]]
// CHECK-NEXT:      i32 1, label [[IF_THEN5_I_I:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN10_I_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then.i.i:
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERTDV32_8BFLOAT16IDV8_S__EXIT:%.*]]
// CHECK:       if.then5.i.i:
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 0, i32 1, i32 2, i32 3, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERTDV32_8BFLOAT16IDV8_S__EXIT]]
// CHECK:       if.then10.i.i:
// CHECK-NEXT:    [[SHUFFLE11_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 0, i32 1, i32 2, i32 3, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERTDV32_8BFLOAT16IDV8_S__EXIT]]
// CHECK:       if.else.i.i:
// CHECK-NEXT:    [[SHUFFLE12_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    br label [[_ZL6INSERTDV32_8BFLOAT16IDV8_S__EXIT]]
// CHECK:       _ZL6insertDv32_8bfloat16iDv8_S_.exit:
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = phi <16 x i32> [ [[SHUFFLE2_I_I]], [[IF_THEN_I_I]] ], [ [[SHUFFLE6_I_I]], [[IF_THEN5_I_I]] ], [ [[SHUFFLE11_I_I]], [[IF_THEN10_I_I]] ], [ [[SHUFFLE12_I_I]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[RETVAL_0_I_I]] to <32 x bfloat>
// CHECK-NEXT:    ret <32 x bfloat> [[TMP2]]
//
v32bfloat16 test_insert (v32bfloat16 v, int idx, v8bfloat16 b )
{
    return insert(v, idx, b);
}
// CHECK-LABEL: define dso_local noundef <16 x float> @_Z11test_insertDv16_fiDv4_f(
// CHECK-SAME: <16 x float> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <4 x float> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[V]] to <16 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <4 x float> [[B]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[REM_I_I:%.*]] = srem i32 [[IDX]], 4
// CHECK-NEXT:    switch i32 [[REM_I_I]], label [[IF_ELSE_I_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[IF_THEN_I_I:%.*]]
// CHECK-NEXT:      i32 1, label [[IF_THEN5_I_I:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN10_I_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then.i.i:
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERTDV16_FIDV4_F_EXIT:%.*]]
// CHECK:       if.then5.i.i:
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 0, i32 1, i32 2, i32 3, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERTDV16_FIDV4_F_EXIT]]
// CHECK:       if.then10.i.i:
// CHECK-NEXT:    [[SHUFFLE11_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 0, i32 1, i32 2, i32 3, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERTDV16_FIDV4_F_EXIT]]
// CHECK:       if.else.i.i:
// CHECK-NEXT:    [[SHUFFLE12_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    br label [[_ZL6INSERTDV16_FIDV4_F_EXIT]]
// CHECK:       _ZL6insertDv16_fiDv4_f.exit:
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = phi <16 x i32> [ [[SHUFFLE2_I_I]], [[IF_THEN_I_I]] ], [ [[SHUFFLE6_I_I]], [[IF_THEN5_I_I]] ], [ [[SHUFFLE11_I_I]], [[IF_THEN10_I_I]] ], [ [[SHUFFLE12_I_I]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[RETVAL_0_I_I]] to <16 x float>
// CHECK-NEXT:    ret <16 x float> [[TMP2]]
//
v16float test_insert (v16float v, int idx, v4float b )
{
    return insert(v, idx, b);
}

// CHECK-LABEL: define dso_local noundef <32 x i8> @_Z11test_insertDv32_DU8_iDv16_S_(
// CHECK-SAME: <32 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <16 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8> [[A]] to <8 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i8> [[B]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP2]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[TMP0]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <8 x i32> [[SHUFFLE1_I_I]], <8 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <8 x i32> [[RETVAL_0_I_I]] to <32 x i8>
// CHECK-NEXT:    ret <32 x i8> [[TMP3]]
//
v64uint4 test_insert (v64uint4 a, int idx, v32uint4 b )
{
    return insert(a, idx, b);
}
// CHECK-LABEL: define dso_local noundef <32 x i8> @_Z11test_insertDv32_DB8_iDv16_S_(
// CHECK-SAME: <32 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <16 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8> [[A]] to <8 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i8> [[B]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP2]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[TMP0]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <8 x i32> [[SHUFFLE1_I_I]], <8 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <8 x i32> [[RETVAL_0_I_I]] to <32 x i8>
// CHECK-NEXT:    ret <32 x i8> [[TMP3]]
//
v64int4 test_insert (v64int4 a, int idx, v32int4 b )
{
    return insert(a, idx, b);
}
// CHECK-LABEL: define dso_local noundef <32 x i8> @_Z11test_insertDv32_hiDv16_h(
// CHECK-SAME: <32 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <16 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8> [[A]] to <8 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i8> [[B]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP2]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[TMP0]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <8 x i32> [[SHUFFLE1_I_I]], <8 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <8 x i32> [[RETVAL_0_I_I]] to <32 x i8>
// CHECK-NEXT:    ret <32 x i8> [[TMP3]]
//
v32uint8 test_insert (v32uint8 a, int idx, v16uint8 b )
{
    return insert(a, idx, b);
}
// CHECK-LABEL: define dso_local noundef <32 x i8> @_Z11test_insertDv32_aiDv16_a(
// CHECK-SAME: <32 x i8> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <16 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8> [[A]] to <8 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i8> [[B]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP2]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[TMP0]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <8 x i32> [[SHUFFLE1_I_I]], <8 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <8 x i32> [[RETVAL_0_I_I]] to <32 x i8>
// CHECK-NEXT:    ret <32 x i8> [[TMP3]]
//
v32int8 test_insert (v32int8 a, int idx, v16int8 b )
{
    return insert(a, idx, b);
}
// CHECK-LABEL: define dso_local noundef <16 x i16> @_Z11test_insertDv16_tiDv8_t(
// CHECK-SAME: <16 x i16> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <8 x i16> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i16> [[A]] to <8 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i16> [[B]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP2]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[TMP0]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <8 x i32> [[SHUFFLE1_I_I]], <8 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <8 x i32> [[RETVAL_0_I_I]] to <16 x i16>
// CHECK-NEXT:    ret <16 x i16> [[TMP3]]
//
v16uint16 test_insert (v16uint16 a, int idx, v8uint16 b )
{
    return insert(a, idx, b);
}
// CHECK-LABEL: define dso_local noundef <16 x i16> @_Z11test_insertDv16_siDv8_s(
// CHECK-SAME: <16 x i16> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <8 x i16> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i16> [[A]] to <8 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i16> [[B]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP2]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[TMP0]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <8 x i32> [[SHUFFLE1_I_I]], <8 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <8 x i32> [[RETVAL_0_I_I]] to <16 x i16>
// CHECK-NEXT:    ret <16 x i16> [[TMP3]]
//
v16int16 test_insert (v16int16 a, int idx, v8int16 b )
{
    return insert(a, idx, b);
}
// CHECK-LABEL: define dso_local noundef <8 x i32> @_Z11test_insertDv8_jiDv4_j(
// CHECK-SAME: <8 x i32> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <4 x i32> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[B]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP0:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP0]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[A]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <8 x i32> [[SHUFFLE1_I_I]], <8 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    ret <8 x i32> [[RETVAL_0_I_I]]
//
v8uint32 test_insert (v8uint32 a, int idx, v4uint32 b )
{
    return insert(a, idx, b);
}
// CHECK-LABEL: define dso_local noundef <8 x i32> @_Z11test_insertDv8_iiDv4_i(
// CHECK-SAME: <8 x i32> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <4 x i32> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[B]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP0:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP0]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[A]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <8 x i32> [[SHUFFLE1_I_I]], <8 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    ret <8 x i32> [[RETVAL_0_I_I]]
//
v8int32 test_insert (v8int32 a, int idx, v4int32 b )
{
    return insert(a, idx, b);
}
// CHECK-LABEL: define dso_local noundef <16 x bfloat> @_Z11test_insertDv16_8bfloat16iDv8_S_(
// CHECK-SAME: <16 x bfloat> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <8 x bfloat> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x bfloat> [[A]] to <8 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x bfloat> [[B]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP2]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[TMP0]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <8 x i32> [[SHUFFLE1_I_I]], <8 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <8 x i32> [[RETVAL_0_I_I]] to <16 x bfloat>
// CHECK-NEXT:    ret <16 x bfloat> [[TMP3]]
//
v16bfloat16 test_insert (v16bfloat16 a, int idx, v8bfloat16 b )
{
    return insert(a, idx, b);
}
// CHECK-LABEL: define dso_local noundef <8 x float> @_Z11test_insertDv8_fiDv4_f(
// CHECK-SAME: <8 x float> noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <4 x float> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x float> [[A]] to <8 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <4 x float> [[B]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP2]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[TMP0]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <8 x i32> [[SHUFFLE1_I_I]], <8 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <8 x i32> [[RETVAL_0_I_I]] to <8 x float>
// CHECK-NEXT:    ret <8 x float> [[TMP3]]
//
v8float test_insert (v8float a, int idx, v4float b )
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z11test_concatDv16_DU8_S0_S0_S0_(
// CHECK-SAME: <16 x i8> noundef [[V0:%.*]], <16 x i8> noundef [[V1:%.*]], <16 x i8> noundef [[V2:%.*]], <16 x i8> noundef [[V3:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i8> [[V0]] to <4 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i8> [[V1]] to <4 x i32>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[V2]] to <4 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <16 x i8> [[V3]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> [[TMP1]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <4 x i32> [[TMP2]], <4 x i32> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <16 x i32> [[SHUFFLE2_I_I]] to <64 x i8>
// CHECK-NEXT:    ret <64 x i8> [[TMP4]]
//
v128uint4 test_concat (v32uint4 v0, v32uint4 v1, v32uint4 v2, v32uint4 v3 )
{
    return concat (v0, v1, v2, v3 );
}
// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z11test_concatDv16_DB8_S0_S0_S0_(
// CHECK-SAME: <16 x i8> noundef [[V0:%.*]], <16 x i8> noundef [[V1:%.*]], <16 x i8> noundef [[V2:%.*]], <16 x i8> noundef [[V3:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i8> [[V0]] to <4 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i8> [[V1]] to <4 x i32>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[V2]] to <4 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <16 x i8> [[V3]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> [[TMP1]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <4 x i32> [[TMP2]], <4 x i32> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <16 x i32> [[SHUFFLE2_I_I]] to <64 x i8>
// CHECK-NEXT:    ret <64 x i8> [[TMP4]]
//
v128int4 test_concat (v32int4 v0, v32int4 v1, v32int4 v2, v32int4 v3 )
{
    return concat (v0, v1, v2, v3 );
}
// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z11test_concatDv16_hS_S_S_(
// CHECK-SAME: <16 x i8> noundef [[V0:%.*]], <16 x i8> noundef [[V1:%.*]], <16 x i8> noundef [[V2:%.*]], <16 x i8> noundef [[V3:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i8> [[V0]] to <4 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i8> [[V1]] to <4 x i32>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[V2]] to <4 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <16 x i8> [[V3]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> [[TMP1]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <4 x i32> [[TMP2]], <4 x i32> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <16 x i32> [[SHUFFLE2_I_I]] to <64 x i8>
// CHECK-NEXT:    ret <64 x i8> [[TMP4]]
//
v64uint8 test_concat (v16uint8 v0, v16uint8 v1, v16uint8 v2, v16uint8 v3 )
{
    return concat (v0, v1, v2, v3 );
}
// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z11test_concatDv16_aS_S_S_(
// CHECK-SAME: <16 x i8> noundef [[V0:%.*]], <16 x i8> noundef [[V1:%.*]], <16 x i8> noundef [[V2:%.*]], <16 x i8> noundef [[V3:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i8> [[V0]] to <4 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i8> [[V1]] to <4 x i32>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[V2]] to <4 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <16 x i8> [[V3]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> [[TMP1]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <4 x i32> [[TMP2]], <4 x i32> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <16 x i32> [[SHUFFLE2_I_I]] to <64 x i8>
// CHECK-NEXT:    ret <64 x i8> [[TMP4]]
//
v64int8 test_concat (v16int8 v0, v16int8 v1, v16int8 v2, v16int8 v3 )
{
    return concat (v0, v1, v2, v3 );
}
// CHECK-LABEL: define dso_local noundef <32 x i16> @_Z11test_concatDv8_tS_S_S_(
// CHECK-SAME: <8 x i16> noundef [[V0:%.*]], <8 x i16> noundef [[V1:%.*]], <8 x i16> noundef [[V2:%.*]], <8 x i16> noundef [[V3:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x i16> [[V0]] to <4 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i16> [[V1]] to <4 x i32>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i16> [[V2]] to <4 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <8 x i16> [[V3]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> [[TMP1]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <4 x i32> [[TMP2]], <4 x i32> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <16 x i32> [[SHUFFLE2_I_I]] to <32 x i16>
// CHECK-NEXT:    ret <32 x i16> [[TMP4]]
//
v32uint16 test_concat (v8uint16 v0, v8uint16 v1, v8uint16 v2, v8uint16 v3 )
{
    return concat (v0, v1, v2, v3 );
}
// CHECK-LABEL: define dso_local noundef <32 x i16> @_Z11test_concatDv8_sS_S_S_(
// CHECK-SAME: <8 x i16> noundef [[V0:%.*]], <8 x i16> noundef [[V1:%.*]], <8 x i16> noundef [[V2:%.*]], <8 x i16> noundef [[V3:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x i16> [[V0]] to <4 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i16> [[V1]] to <4 x i32>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i16> [[V2]] to <4 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <8 x i16> [[V3]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> [[TMP1]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <4 x i32> [[TMP2]], <4 x i32> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <16 x i32> [[SHUFFLE2_I_I]] to <32 x i16>
// CHECK-NEXT:    ret <32 x i16> [[TMP4]]
//
v32int16 test_concat (v8int16 v0, v8int16 v1, v8int16 v2, v8int16 v3 )
{
    return concat (v0, v1, v2, v3 );
}
// CHECK-LABEL: define dso_local noundef <16 x i32> @_Z11test_concatDv4_jS_S_S_(
// CHECK-SAME: <4 x i32> noundef [[V0:%.*]], <4 x i32> noundef [[V1:%.*]], <4 x i32> noundef [[V2:%.*]], <4 x i32> noundef [[V3:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[V0]], <4 x i32> [[V1]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <4 x i32> [[V2]], <4 x i32> [[V3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i32> [[SHUFFLE2_I_I]]
//
v16uint32 test_concat (v4uint32 v0, v4uint32 v1, v4uint32 v2, v4uint32 v3 )
{
    return concat (v0, v1, v2, v3 );
}
// CHECK-LABEL: define dso_local noundef <16 x i32> @_Z11test_concatDv4_iS_S_S_(
// CHECK-SAME: <4 x i32> noundef [[V0:%.*]], <4 x i32> noundef [[V1:%.*]], <4 x i32> noundef [[V2:%.*]], <4 x i32> noundef [[V3:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[V0]], <4 x i32> [[V1]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <4 x i32> [[V2]], <4 x i32> [[V3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i32> [[SHUFFLE2_I_I]]
//
v16int32 test_concat (v4int32 v0, v4int32 v1, v4int32 v2, v4int32 v3 )
{
    return concat (v0, v1, v2, v3 );
}
// CHECK-LABEL: define dso_local noundef <32 x bfloat> @_Z11test_concatDv8_8bfloat16S0_S0_S0_(
// CHECK-SAME: <8 x bfloat> noundef [[V0:%.*]], <8 x bfloat> noundef [[V1:%.*]], <8 x bfloat> noundef [[V2:%.*]], <8 x bfloat> noundef [[V3:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x bfloat> [[V0]] to <4 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x bfloat> [[V1]] to <4 x i32>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x bfloat> [[V2]] to <4 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <8 x bfloat> [[V3]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> [[TMP1]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <4 x i32> [[TMP2]], <4 x i32> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <16 x i32> [[SHUFFLE2_I_I]] to <32 x bfloat>
// CHECK-NEXT:    ret <32 x bfloat> [[TMP4]]
//
v32bfloat16 test_concat (v8bfloat16 v0, v8bfloat16 v1, v8bfloat16 v2, v8bfloat16 v3 )
{
    return concat (v0, v1, v2, v3 );
}
// CHECK-LABEL: define dso_local noundef <16 x float> @_Z11test_concatDv4_fS_S_S_(
// CHECK-SAME: <4 x float> noundef [[V0:%.*]], <4 x float> noundef [[V1:%.*]], <4 x float> noundef [[V2:%.*]], <4 x float> noundef [[V3:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_UNCASTED_I:%.*]] = shufflevector <4 x float> [[V0]], <4 x float> [[V1]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_UNCASTED_I:%.*]] = shufflevector <4 x float> [[V2]], <4 x float> [[V3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE2_I_UNCASTED_I:%.*]] = shufflevector <8 x float> [[SHUFFLE_I_UNCASTED_I]], <8 x float> [[SHUFFLE1_I_UNCASTED_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x float> [[SHUFFLE2_I_UNCASTED_I]]
//
v16float test_concat (v4float v0, v4float v1, v4float v2, v4float v3 )
{
    return concat (v0, v1, v2, v3 );
}

// CHECK-LABEL: define dso_local noundef <32 x i8> @_Z11test_concatDv16_DU8_S0_(
// CHECK-SAME: <16 x i8> noundef [[V0:%.*]], <16 x i8> noundef [[V1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i8> [[V0]] to <4 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i8> [[V1]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> [[TMP1]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i32> [[SHUFFLE_I_I]] to <32 x i8>
// CHECK-NEXT:    ret <32 x i8> [[TMP2]]
//
v64uint4 test_concat (v32uint4 v0, v32uint4 v1 )
{
    return concat(v0, v1);
}
// CHECK-LABEL: define dso_local noundef <32 x i8> @_Z11test_concatDv16_DB8_S0_(
// CHECK-SAME: <16 x i8> noundef [[V0:%.*]], <16 x i8> noundef [[V1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i8> [[V0]] to <4 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i8> [[V1]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> [[TMP1]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i32> [[SHUFFLE_I_I]] to <32 x i8>
// CHECK-NEXT:    ret <32 x i8> [[TMP2]]
//
v64int4 test_concat (v32int4 v0, v32int4 v1 )
{
    return concat(v0, v1);
}
// CHECK-LABEL: define dso_local noundef <32 x i8> @_Z11test_concatDv16_hS_(
// CHECK-SAME: <16 x i8> noundef [[V0:%.*]], <16 x i8> noundef [[V1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i8> [[V0]] to <4 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i8> [[V1]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> [[TMP1]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i32> [[SHUFFLE_I_I]] to <32 x i8>
// CHECK-NEXT:    ret <32 x i8> [[TMP2]]
//
v32uint8 test_concat (v16uint8 v0, v16uint8 v1 )
{
    return concat(v0, v1);
}
// CHECK-LABEL: define dso_local noundef <32 x i8> @_Z11test_concatDv16_aS_(
// CHECK-SAME: <16 x i8> noundef [[V0:%.*]], <16 x i8> noundef [[V1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i8> [[V0]] to <4 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i8> [[V1]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> [[TMP1]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i32> [[SHUFFLE_I_I]] to <32 x i8>
// CHECK-NEXT:    ret <32 x i8> [[TMP2]]
//
v32int8 test_concat (v16int8 v0, v16int8 v1 )
{
    return concat(v0, v1);
}
// CHECK-LABEL: define dso_local noundef <16 x i16> @_Z11test_concatDv8_tS_(
// CHECK-SAME: <8 x i16> noundef [[V0:%.*]], <8 x i16> noundef [[V1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x i16> [[V0]] to <4 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i16> [[V1]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> [[TMP1]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i32> [[SHUFFLE_I_I]] to <16 x i16>
// CHECK-NEXT:    ret <16 x i16> [[TMP2]]
//
v16uint16 test_concat (v8uint16 v0, v8uint16 v1 )
{
    return concat(v0, v1);
}
// CHECK-LABEL: define dso_local noundef <16 x i16> @_Z11test_concatDv8_sS_(
// CHECK-SAME: <8 x i16> noundef [[V0:%.*]], <8 x i16> noundef [[V1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x i16> [[V0]] to <4 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i16> [[V1]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> [[TMP1]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i32> [[SHUFFLE_I_I]] to <16 x i16>
// CHECK-NEXT:    ret <16 x i16> [[TMP2]]
//
v16int16 test_concat (v8int16 v0, v8int16 v1 )
{
    return concat(v0, v1);
}
// CHECK-LABEL: define dso_local noundef <8 x i32> @_Z11test_concatDv4_jS_(
// CHECK-SAME: <4 x i32> noundef [[V0:%.*]], <4 x i32> noundef [[V1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[V0]], <4 x i32> [[V1]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i32> [[SHUFFLE_I_I]]
//
v8uint32 test_concat (v4uint32 v0, v4uint32 v1 )
{
    return concat(v0, v1);
}
// CHECK-LABEL: define dso_local noundef <8 x i32> @_Z11test_concatDv4_iS_(
// CHECK-SAME: <4 x i32> noundef [[V0:%.*]], <4 x i32> noundef [[V1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[V0]], <4 x i32> [[V1]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i32> [[SHUFFLE_I_I]]
//
v8int32 test_concat (v4int32 v0, v4int32 v1 )
{
    return concat(v0, v1);
}
// CHECK-LABEL: define dso_local noundef <16 x bfloat> @_Z11test_concatDv8_8bfloat16S0_(
// CHECK-SAME: <8 x bfloat> noundef [[V0:%.*]], <8 x bfloat> noundef [[V1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x bfloat> [[V0]] to <4 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x bfloat> [[V1]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> [[TMP1]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i32> [[SHUFFLE_I_I]] to <16 x bfloat>
// CHECK-NEXT:    ret <16 x bfloat> [[TMP2]]
//
v16bfloat16 test_concat (v8bfloat16 v0, v8bfloat16 v1 )
{
    return concat(v0, v1);
}
// CHECK-LABEL: define dso_local noundef <8 x float> @_Z11test_concatDv4_fS_(
// CHECK-SAME: <4 x float> noundef [[V0:%.*]], <4 x float> noundef [[V1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_UNCASTED_I:%.*]] = shufflevector <4 x float> [[V0]], <4 x float> [[V1]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x float> [[SHUFFLE_I_UNCASTED_I]]
//
v8float test_concat (v4float v0, v4float v1 )
{
    return concat(v0, v1);
}



// Conversions
// v8accfloat
// CHECK-LABEL: define dso_local inreg noundef <8 x float> @_Z23test_extract_v8accfloatDv16_u10__accfloati(
// CHECK-SAME: <16 x float> inreg noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[A]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I_I:%.*]] = icmp eq i32 [[AND_I_I_I]], 0
// CHECK-NEXT:    [[COND_I_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I_I]], <8 x i32> [[SHUFFLE_I_I_I]], <8 x i32> [[SHUFFLE1_I_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i32> [[COND_I_I_I]] to <8 x float>
// CHECK-NEXT:    ret <8 x float> [[TMP1]]
//
v8accfloat test_extract_v8accfloat (v16accfloat a, int idx)
{
    return extract_v8accfloat (a, idx);
}

// CHECK-LABEL: define dso_local inreg noundef <16 x float> @_Z11test_insertDv16_u10__accfloatiDv8_u10__accfloat(
// CHECK-SAME: <16 x float> inreg noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <8 x float> inreg noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x float> [[A]] to <16 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x float> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[SHUFFLE_I_I_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I_I:%.*]] = icmp eq i32 [[AND_I_I_I]], 0
// CHECK-NEXT:    [[COND_I_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I_I]], <16 x i32> [[SHUFFLE1_I_I_I]], <16 x i32> [[SHUFFLE2_I_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[COND_I_I_I]] to <16 x float>
// CHECK-NEXT:    ret <16 x float> [[TMP2]]
//
v16accfloat test_insert (v16accfloat a, int idx, v8accfloat b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local inreg noundef <16 x float> @_Z20test_set_v16accfloatiDv8_u10__accfloat(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <8 x float> inreg noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x float> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I_I:%.*]] = icmp eq i32 [[AND_I_I_I]], 0
// CHECK-NEXT:    [[COND_I_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I_I]], <16 x i32> [[SHUFFLE_I_I_I]], <16 x i32> [[SHUFFLE1_I_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[COND_I_I_I]] to <16 x float>
// CHECK-NEXT:    ret <16 x float> [[TMP1]]
//
v16accfloat test_set_v16accfloat (int idx, v8accfloat b)
{
    return set_v16accfloat (idx, b);
}

// CHECK-LABEL: define dso_local inreg noundef <16 x float> @_Z11test_concatDv8_u10__accfloatS_(
// CHECK-SAME: <8 x float> inreg noundef [[A:%.*]], <8 x float> inreg noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I_UNCASTED_I:%.*]] = shufflevector <8 x float> [[A]], <8 x float> [[B]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x float> [[SHUFFLE_I_I_UNCASTED_I]]
//
v16accfloat test_concat (v8accfloat a, v8accfloat b)
{
    return concat(a, b);
}
// v8acc32
// CHECK-LABEL: define dso_local inreg noundef <8 x i32> @_Z20test_extract_v8acc32Dv16_u7__acc32i(
// CHECK-SAME: <16 x i32> inreg noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <16 x i32> [[A]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <16 x i32> [[A]], <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I_I:%.*]] = icmp eq i32 [[AND_I_I_I]], 0
// CHECK-NEXT:    [[COND_I_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I_I]], <8 x i32> [[SHUFFLE_I_I_I]], <8 x i32> [[SHUFFLE1_I_I_I]]
// CHECK-NEXT:    ret <8 x i32> [[COND_I_I_I]]
//
v8acc32 test_extract_v8acc32 (v16acc32 a, int idx)
{
    return extract_v8acc32 (a, idx);
}

// CHECK-LABEL: define dso_local inreg noundef <16 x i32> @_Z11test_insertDv16_u7__acc32iDv8_u7__acc32(
// CHECK-SAME: <16 x i32> inreg noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <8 x i32> inreg noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I_I]], <16 x i32> [[A]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[A]], <16 x i32> [[SHUFFLE_I_I_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I_I:%.*]] = icmp eq i32 [[AND_I_I_I]], 0
// CHECK-NEXT:    [[COND_I_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I_I]], <16 x i32> [[SHUFFLE1_I_I_I]], <16 x i32> [[SHUFFLE2_I_I_I]]
// CHECK-NEXT:    ret <16 x i32> [[COND_I_I_I]]
//
v16acc32 test_insert (v16acc32 a, int idx, v8acc32 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local inreg noundef <16 x i32> @_Z17test_set_v16acc32iDv8_u7__acc32(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <8 x i32> inreg noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I_I:%.*]] = icmp eq i32 [[AND_I_I_I]], 0
// CHECK-NEXT:    [[COND_I_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I_I]], <16 x i32> [[SHUFFLE_I_I_I]], <16 x i32> [[SHUFFLE1_I_I_I]]
// CHECK-NEXT:    ret <16 x i32> [[COND_I_I_I]]
//
v16acc32 test_set_v16acc32 (int idx, v8acc32 b)
{
    return set_v16acc32 (idx, b);
}

// CHECK-LABEL: define dso_local inreg noundef <16 x i32> @_Z11test_concatDv8_u7__acc32S_(
// CHECK-SAME: <8 x i32> inreg noundef [[A:%.*]], <8 x i32> inreg noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> [[B]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i32> [[SHUFFLE_I_I_I]]
//
v16acc32 test_concat (v8acc32 a, v8acc32 b)
{
    return concat(a, b);
}
// v4acc64
// CHECK-LABEL: define dso_local inreg noundef <4 x i64> @_Z20test_extract_v4acc64Dv8_u7__acc64i(
// CHECK-SAME: <8 x i64> inreg noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x i64> [[A]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I_I:%.*]] = icmp eq i32 [[AND_I_I_I]], 0
// CHECK-NEXT:    [[COND_I_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I_I]], <8 x i32> [[SHUFFLE_I_I_I]], <8 x i32> [[SHUFFLE1_I_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i32> [[COND_I_I_I]] to <4 x i64>
// CHECK-NEXT:    ret <4 x i64> [[TMP1]]
//
v4acc64 test_extract_v4acc64 (v8acc64 a, int idx)
{
    return extract_v4acc64 (a, idx);
}

// CHECK-LABEL: define dso_local inreg noundef <8 x i64> @_Z11test_insertDv8_u7__acc64iDv4_u7__acc64(
// CHECK-SAME: <8 x i64> inreg noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <4 x i64> inreg noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x i64> [[A]] to <16 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <4 x i64> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[SHUFFLE_I_I_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I_I:%.*]] = icmp eq i32 [[AND_I_I_I]], 0
// CHECK-NEXT:    [[COND_I_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I_I]], <16 x i32> [[SHUFFLE1_I_I_I]], <16 x i32> [[SHUFFLE2_I_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[COND_I_I_I]] to <8 x i64>
// CHECK-NEXT:    ret <8 x i64> [[TMP2]]
//
v8acc64 test_insert (v8acc64 a, int idx, v4acc64 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local inreg noundef <8 x i64> @_Z16test_set_v8acc64iDv4_u7__acc64(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <4 x i64> inreg noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x i64> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I_I:%.*]] = icmp eq i32 [[AND_I_I_I]], 0
// CHECK-NEXT:    [[COND_I_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I_I]], <16 x i32> [[SHUFFLE_I_I_I]], <16 x i32> [[SHUFFLE1_I_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[COND_I_I_I]] to <8 x i64>
// CHECK-NEXT:    ret <8 x i64> [[TMP1]]
//
v8acc64 test_set_v8acc64 (int idx, v4acc64 b)
{
    return set_v8acc64 (idx, b);
}

// CHECK-LABEL: define dso_local inreg noundef <8 x i64> @_Z11test_concatDv4_u7__acc64S_(
// CHECK-SAME: <4 x i64> inreg noundef [[A:%.*]], <4 x i64> inreg noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <4 x i64> [[A]], <4 x i64> [[B]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i64> [[TMP0]]
//
v8acc64 test_concat (v4acc64 a, v4acc64 b)
{
    return concat(a, b);
}
// v8accfloat
// CHECK-LABEL: define dso_local inreg noundef <8 x float> @_Z23test_extract_v8accfloatDv32_u10__accfloati(
// CHECK-SAME: <32 x float> inreg noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x float> [[A]] to <32 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[SHUFFLE3_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I_I:%.*]] = icmp eq i32 [[AND_I_I_I]], 0
// CHECK-NEXT:    [[COND_I_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I_I]], <8 x i32> [[SHUFFLE_I_I_I]], <8 x i32> [[SHUFFLE1_I_I_I]]
// CHECK-NEXT:    [[COND9_I_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I_I]], <8 x i32> [[SHUFFLE2_I_I_I]], <8 x i32> [[SHUFFLE3_I_I_I]]
// CHECK-NEXT:    [[AND10_I_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I_I:%.*]] = icmp eq i32 [[AND10_I_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I_I]], <8 x i32> [[COND_I_I_I]], <8 x i32> [[COND9_I_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i32> [[COND15_I_I_I]] to <8 x float>
// CHECK-NEXT:    ret <8 x float> [[TMP1]]
//
v8accfloat test_extract_v8accfloat (v32accfloat a, int idx)
{
    return extract_v8accfloat (a, idx);
}

// CHECK-LABEL: define dso_local inreg noundef <32 x float> @_Z11test_insertDv32_u10__accfloatiDv8_u10__accfloat(
// CHECK-SAME: <32 x float> inreg noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <8 x float> inreg noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x float> [[A]] to <32 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x float> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE6_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE2_I_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE7_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE3_I_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I_I:%.*]] = icmp eq i32 [[AND_I_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE5_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE1_I_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE4_I_I_I:%.*]] = shufflevector <32 x i32> [[SHUFFLE_I_I_I]], <32 x i32> [[TMP0]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I_I]], <32 x i32> [[SHUFFLE4_I_I_I]], <32 x i32> [[SHUFFLE5_I_I_I]]
// CHECK-NEXT:    [[COND13_I_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I_I]], <32 x i32> [[SHUFFLE6_I_I_I]], <32 x i32> [[SHUFFLE7_I_I_I]]
// CHECK-NEXT:    [[AND14_I_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL15_NOT_I_I_I:%.*]] = icmp eq i32 [[AND14_I_I_I]], 0
// CHECK-NEXT:    [[COND19_I_I_I:%.*]] = select i1 [[TOBOOL15_NOT_I_I_I]], <32 x i32> [[COND_I_I_I]], <32 x i32> [[COND13_I_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[COND19_I_I_I]] to <32 x float>
// CHECK-NEXT:    ret <32 x float> [[TMP2]]
//
v32accfloat test_insert (v32accfloat a, int idx, v8accfloat b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local inreg noundef <32 x float> @_Z20test_set_v32accfloatiDv8_u10__accfloat(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <8 x float> inreg noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x float> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I_I:%.*]] = icmp eq i32 [[AND_I_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I_I]], <32 x i32> [[SHUFFLE_I_I_I]], <32 x i32> [[SHUFFLE1_I_I_I]]
// CHECK-NEXT:    [[COND9_I_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I_I]], <32 x i32> [[SHUFFLE2_I_I_I]], <32 x i32> [[SHUFFLE3_I_I_I]]
// CHECK-NEXT:    [[AND10_I_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I_I:%.*]] = icmp eq i32 [[AND10_I_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I_I]], <32 x i32> [[COND_I_I_I]], <32 x i32> [[COND9_I_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i32> [[COND15_I_I_I]] to <32 x float>
// CHECK-NEXT:    ret <32 x float> [[TMP1]]
//
v32accfloat test_set_v32accfloat (int idx, v8accfloat b)
{
    return set_v32accfloat (idx, b);
}

// CHECK-LABEL: define dso_local inreg noundef <32 x float> @_Z11test_concatDv8_u10__accfloatS_S_S_(
// CHECK-SAME: <8 x float> inreg noundef [[A:%.*]], <8 x float> inreg noundef [[B:%.*]], <8 x float> inreg noundef [[C:%.*]], <8 x float> inreg noundef [[D:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I_UNCASTED_I:%.*]] = shufflevector <8 x float> [[A]], <8 x float> [[B]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE1_I_I_UNCASTED_I:%.*]] = shufflevector <8 x float> [[C]], <8 x float> [[D]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I_UNCASTED_I:%.*]] = shufflevector <16 x float> [[SHUFFLE_I_I_UNCASTED_I]], <16 x float> [[SHUFFLE1_I_I_UNCASTED_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    ret <32 x float> [[SHUFFLE2_I_I_UNCASTED_I]]
//
v32accfloat test_concat (v8accfloat a, v8accfloat b, v8accfloat c, v8accfloat d)
{
    return concat(a, b, c, d);
}
// v8acc32
// CHECK-LABEL: define dso_local inreg noundef <8 x i32> @_Z20test_extract_v8acc32Dv32_u7__acc32i(
// CHECK-SAME: <32 x i32> inreg noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[SHUFFLE3_I_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I_I:%.*]] = icmp eq i32 [[AND_I_I_I]], 0
// CHECK-NEXT:    [[COND_I_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I_I]], <8 x i32> [[SHUFFLE_I_I_I]], <8 x i32> [[SHUFFLE1_I_I_I]]
// CHECK-NEXT:    [[COND9_I_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I_I]], <8 x i32> [[SHUFFLE2_I_I_I]], <8 x i32> [[SHUFFLE3_I_I_I]]
// CHECK-NEXT:    [[AND10_I_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I_I:%.*]] = icmp eq i32 [[AND10_I_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I_I]], <8 x i32> [[COND_I_I_I]], <8 x i32> [[COND9_I_I_I]]
// CHECK-NEXT:    ret <8 x i32> [[COND15_I_I_I]]
//
v8acc32 test_extract_v8acc32 (v32acc32 a, int idx)
{
    return extract_v8acc32 (a, idx);
}

// CHECK-LABEL: define dso_local inreg noundef <32 x i32> @_Z11test_insertDv32_u7__acc32iDv8_u7__acc32(
// CHECK-SAME: <32 x i32> inreg noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <8 x i32> inreg noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I_I:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE6_I_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> [[SHUFFLE2_I_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE7_I_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> [[SHUFFLE3_I_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I_I:%.*]] = icmp eq i32 [[AND_I_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE5_I_I_I:%.*]] = shufflevector <32 x i32> [[A]], <32 x i32> [[SHUFFLE1_I_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE4_I_I_I:%.*]] = shufflevector <32 x i32> [[SHUFFLE_I_I_I]], <32 x i32> [[A]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I_I]], <32 x i32> [[SHUFFLE4_I_I_I]], <32 x i32> [[SHUFFLE5_I_I_I]]
// CHECK-NEXT:    [[COND13_I_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I_I]], <32 x i32> [[SHUFFLE6_I_I_I]], <32 x i32> [[SHUFFLE7_I_I_I]]
// CHECK-NEXT:    [[AND14_I_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL15_NOT_I_I_I:%.*]] = icmp eq i32 [[AND14_I_I_I]], 0
// CHECK-NEXT:    [[COND19_I_I_I:%.*]] = select i1 [[TOBOOL15_NOT_I_I_I]], <32 x i32> [[COND_I_I_I]], <32 x i32> [[COND13_I_I_I]]
// CHECK-NEXT:    ret <32 x i32> [[COND19_I_I_I]]
//
v32acc32 test_insert (v32acc32 a, int idx, v8acc32 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local inreg noundef <32 x i32> @_Z17test_set_v32acc32iDv8_u7__acc32(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <8 x i32> inreg noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I_I:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I_I:%.*]] = icmp eq i32 [[AND_I_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I_I]], <32 x i32> [[SHUFFLE_I_I_I]], <32 x i32> [[SHUFFLE1_I_I_I]]
// CHECK-NEXT:    [[COND9_I_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I_I]], <32 x i32> [[SHUFFLE2_I_I_I]], <32 x i32> [[SHUFFLE3_I_I_I]]
// CHECK-NEXT:    [[AND10_I_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I_I:%.*]] = icmp eq i32 [[AND10_I_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I_I]], <32 x i32> [[COND_I_I_I]], <32 x i32> [[COND9_I_I_I]]
// CHECK-NEXT:    ret <32 x i32> [[COND15_I_I_I]]
//
v32acc32 test_set_v32acc32 (int idx, v8acc32 b)
{
    return set_v32acc32 (idx, b);
}

// CHECK-LABEL: define dso_local inreg noundef <32 x i32> @_Z11test_concatDv8_u7__acc32S_S_S_(
// CHECK-SAME: <8 x i32> inreg noundef [[A:%.*]], <8 x i32> inreg noundef [[B:%.*]], <8 x i32> inreg noundef [[C:%.*]], <8 x i32> inreg noundef [[D:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> [[B]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <8 x i32> [[C]], <8 x i32> [[D]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I_I]], <16 x i32> [[SHUFFLE1_I_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    ret <32 x i32> [[SHUFFLE2_I_I_I]]
//
v32acc32 test_concat (v8acc32 a, v8acc32 b, v8acc32 c, v8acc32 d)
{
    return concat(a, b, c, d);
}
// v4acc64
// CHECK-LABEL: define dso_local inreg noundef <4 x i64> @_Z20test_extract_v4acc64Dv16_u7__acc64i(
// CHECK-SAME: <16 x i64> inreg noundef [[A:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i64> [[A]] to <32 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[SHUFFLE3_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I_I:%.*]] = icmp eq i32 [[AND_I_I_I]], 0
// CHECK-NEXT:    [[COND_I_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I_I]], <8 x i32> [[SHUFFLE_I_I_I]], <8 x i32> [[SHUFFLE1_I_I_I]]
// CHECK-NEXT:    [[COND9_I_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I_I]], <8 x i32> [[SHUFFLE2_I_I_I]], <8 x i32> [[SHUFFLE3_I_I_I]]
// CHECK-NEXT:    [[AND10_I_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I_I:%.*]] = icmp eq i32 [[AND10_I_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I_I]], <8 x i32> [[COND_I_I_I]], <8 x i32> [[COND9_I_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i32> [[COND15_I_I_I]] to <4 x i64>
// CHECK-NEXT:    ret <4 x i64> [[TMP1]]
//
v4acc64 test_extract_v4acc64 (v16acc64 a, int idx)
{
    return extract_v4acc64 (a, idx);
}

// CHECK-LABEL: define dso_local inreg noundef <16 x i64> @_Z11test_insertDv16_u7__acc64iDv4_u7__acc64(
// CHECK-SAME: <16 x i64> inreg noundef [[A:%.*]], i32 noundef [[IDX:%.*]], <4 x i64> inreg noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i64> [[A]] to <32 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <4 x i64> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE6_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE2_I_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE7_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE3_I_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I_I:%.*]] = icmp eq i32 [[AND_I_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE5_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE1_I_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE4_I_I_I:%.*]] = shufflevector <32 x i32> [[SHUFFLE_I_I_I]], <32 x i32> [[TMP0]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I_I]], <32 x i32> [[SHUFFLE4_I_I_I]], <32 x i32> [[SHUFFLE5_I_I_I]]
// CHECK-NEXT:    [[COND13_I_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I_I]], <32 x i32> [[SHUFFLE6_I_I_I]], <32 x i32> [[SHUFFLE7_I_I_I]]
// CHECK-NEXT:    [[AND14_I_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL15_NOT_I_I_I:%.*]] = icmp eq i32 [[AND14_I_I_I]], 0
// CHECK-NEXT:    [[COND19_I_I_I:%.*]] = select i1 [[TOBOOL15_NOT_I_I_I]], <32 x i32> [[COND_I_I_I]], <32 x i32> [[COND13_I_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[COND19_I_I_I]] to <16 x i64>
// CHECK-NEXT:    ret <16 x i64> [[TMP2]]
//
v16acc64 test_insert (v16acc64 a, int idx, v4acc64 b)
{
    return insert(a, idx, b);
}

// CHECK-LABEL: define dso_local inreg noundef <16 x i64> @_Z17test_set_v16acc64iDv4_u7__acc64(
// CHECK-SAME: i32 noundef [[IDX:%.*]], <4 x i64> inreg noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x i64> [[B]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[AND_I_I_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I_I:%.*]] = icmp eq i32 [[AND_I_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I_I]], <32 x i32> [[SHUFFLE_I_I_I]], <32 x i32> [[SHUFFLE1_I_I_I]]
// CHECK-NEXT:    [[COND9_I_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I_I]], <32 x i32> [[SHUFFLE2_I_I_I]], <32 x i32> [[SHUFFLE3_I_I_I]]
// CHECK-NEXT:    [[AND10_I_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I_I:%.*]] = icmp eq i32 [[AND10_I_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I_I]], <32 x i32> [[COND_I_I_I]], <32 x i32> [[COND9_I_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i32> [[COND15_I_I_I]] to <16 x i64>
// CHECK-NEXT:    ret <16 x i64> [[TMP1]]
//
v16acc64 test_set_v16acc64 (int idx, v4acc64 b)
{
    return set_v16acc64 (idx, b);
}

// CHECK-LABEL: define dso_local inreg noundef <16 x i64> @_Z11test_concatDv4_u7__acc64S_S_S_(
// CHECK-SAME: <4 x i64> inreg noundef [[A:%.*]], <4 x i64> inreg noundef [[B:%.*]], <4 x i64> inreg noundef [[C:%.*]], <4 x i64> inreg noundef [[D:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <4 x i64> [[A]], <4 x i64> [[B]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <4 x i64> [[C]], <4 x i64> [[D]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i64> [[TMP0]], <8 x i64> [[TMP1]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i64> [[TMP2]]
//
v16acc64 test_concat (v4acc64 a, v4acc64 b, v4acc64 c, v4acc64 d)
{
    return concat(a, b, c, d);
}
