// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
//===- aie-ups-intrinsics.cpp ---------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//
// RUN: %clang -O2 %s --target=aie2p -nostdlibinc -S -emit-llvm -o - | FileCheck %s -check-prefix=AIE2P
// RUN: %clang -O2 %s --target=aie2ps -nostdlibinc -S -emit-llvm -o - | FileCheck %s -check-prefix=AIE2PS

// AIE2P-LABEL: @_Z9test_lupsDv8_ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i64> @llvm.aie2p.acc64.v8.I256.ups(<8 x i32> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2P-NEXT:    ret <8 x i64> [[TMP0]]
//
// AIE2PS-LABEL: @_Z9test_lupsDv8_ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i64> @llvm.aie2ps.acc64.v8.I256.ups(<8 x i32> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2PS-NEXT:    ret <8 x i64> [[TMP0]]
//
v8acc64 test_lups(v8int32 a, int shft) {
   return lups(a,shft,__SIGN_SIGNED);
}

//
// AIE2P-LABEL: @_Z9test_lupsDv8_ji(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i64> @llvm.aie2p.acc64.v8.I256.ups(<8 x i32> [[A:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2P-NEXT:    ret <8 x i64> [[TMP0]]
//
// AIE2PS-LABEL: @_Z9test_lupsDv8_ji(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i64> @llvm.aie2ps.acc64.v8.I256.ups(<8 x i32> [[A:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2PS-NEXT:    ret <8 x i64> [[TMP0]]
//
v8acc64 test_lups(v8uint32 a, int shft) {
   return lups(a,shft,__SIGN_UNSIGNED);
}

// AIE2P-LABEL: @_Z9test_lupsDv8_iii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i64> @llvm.aie2p.acc64.v8.I256.ups(<8 x i32> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <8 x i64> [[TMP0]]
//
// AIE2PS-LABEL: @_Z9test_lupsDv8_iii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i64> @llvm.aie2ps.acc64.v8.I256.ups(<8 x i32> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <8 x i64> [[TMP0]]
//
v8acc64 test_lups(v8int32 a, int shft, int sign) {
   return lups(a,shft,sign);
}

// AIE2P-LABEL: @_Z9test_supsDv16_si(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.acc32.v16.I256.ups(<16 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2P-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z9test_supsDv16_si(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.acc32.v16.I256.ups(<16 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2PS-NEXT:    ret <16 x i32> [[TMP0]]
//
v16acc32 test_sups(v16int16 a, int shft) {
   return sups(a,shft,__SIGN_SIGNED);
}

// AIE2P-LABEL: @_Z9test_supsDv16_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.acc32.v16.I256.ups(<16 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2P-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z9test_supsDv16_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.acc32.v16.I256.ups(<16 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2PS-NEXT:    ret <16 x i32> [[TMP0]]
//
v16acc32 test_sups(v16uint16 a, int shft) {
   return sups(a,shft,__SIGN_UNSIGNED);
}

// AIE2P-LABEL: @_Z9test_supsDv32_ai(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2p.acc32.v32.I256.ups(<32 x i8> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2P-NEXT:    ret <32 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z9test_supsDv32_ai(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I256.ups(<32 x i8> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2PS-NEXT:    ret <32 x i32> [[TMP0]]
//
v32acc32 test_sups(v32int8 a, int shft) {
   return sups(a,shft,__SIGN_SIGNED);
}

//
// AIE2P-LABEL: @_Z9test_supsDv32_hi(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2p.acc32.v32.I256.ups(<32 x i8> [[A:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2P-NEXT:    ret <32 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z9test_supsDv32_hi(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I256.ups(<32 x i8> [[A:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2PS-NEXT:    ret <32 x i32> [[TMP0]]
//
v32acc32 test_sups(v32uint8 a, int shft) {
   return sups(a,shft,__SIGN_UNSIGNED);
}

// AIE2P-LABEL: @_Z9test_supsDv32_aii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2p.acc32.v32.I256.ups(<32 x i8> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <32 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z9test_supsDv32_aii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I256.ups(<32 x i8> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <32 x i32> [[TMP0]]
//
v32acc32 test_sups(v32int8 a, int shft, int sign) {
   return sups(a,shft,sign);
}

// AIE2P-LABEL: @_Z9test_supsDv32_hii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2p.acc32.v32.I256.ups(<32 x i8> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <32 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z9test_supsDv32_hii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I256.ups(<32 x i8> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <32 x i32> [[TMP0]]
//
v32acc32 test_sups(v32uint8 a, int shft, int sign) {
   return sups(a,shft,sign);
}

// AIE2P-LABEL: @_Z9test_lupsDv16_si(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i64> @llvm.aie2p.acc64.v16.I256.ups(<16 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2P-NEXT:    ret <16 x i64> [[TMP0]]
//
// AIE2PS-LABEL: @_Z9test_lupsDv16_si(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i64> @llvm.aie2ps.acc64.v16.I256.ups(<16 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2PS-NEXT:    ret <16 x i64> [[TMP0]]
//
v16acc64 test_lups(v16int16 a, int shft) {
   return lups(a,shft,__SIGN_SIGNED);
}

// AIE2P-LABEL: @_Z9test_lupsDv16_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i64> @llvm.aie2p.acc64.v16.I256.ups(<16 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2P-NEXT:    ret <16 x i64> [[TMP0]]
//
// AIE2PS-LABEL: @_Z9test_lupsDv16_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i64> @llvm.aie2ps.acc64.v16.I256.ups(<16 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2PS-NEXT:    ret <16 x i64> [[TMP0]]
//
v16acc64 test_lups(v16uint16 a, int shft) {
   return lups(a,shft,__SIGN_UNSIGNED);
}

//
// AIE2P-LABEL: @_Z9test_lupsDv16_sii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i64> @llvm.aie2p.acc64.v16.I256.ups(<16 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <16 x i64> [[TMP0]]
//
// AIE2PS-LABEL: @_Z9test_lupsDv16_sii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i64> @llvm.aie2ps.acc64.v16.I256.ups(<16 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <16 x i64> [[TMP0]]
//
v16acc64 test_lups(v16int16 a, int shft, int sign) {
   return lups(a,shft,sign);
}

// AIE2P-LABEL: @_Z9test_lupsDv16_tii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i64> @llvm.aie2p.acc64.v16.I256.ups(<16 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <16 x i64> [[TMP0]]
//
// AIE2PS-LABEL: @_Z9test_lupsDv16_tii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i64> @llvm.aie2ps.acc64.v16.I256.ups(<16 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <16 x i64> [[TMP0]]
//
v16acc64 test_lups(v16uint16 a, int shft, int sign) {
   return lups(a,shft,sign);
}

// AIE2P-LABEL: @_Z9test_lupsDv16_ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i64> @llvm.aie2p.acc64.v16.I512.ups(<16 x i32> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2P-NEXT:    ret <16 x i64> [[TMP0]]
//
// AIE2PS-LABEL: @_Z9test_lupsDv16_ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i64> @llvm.aie2ps.acc64.v16.I512.ups(<16 x i32> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2PS-NEXT:    ret <16 x i64> [[TMP0]]
//
v16acc64 test_lups(v16int32 a, int shft){
 return lups(a,shft,__SIGN_SIGNED);
}

// AIE2P-LABEL: @_Z9test_lupsDv16_ji(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i64> @llvm.aie2p.acc64.v16.I512.ups(<16 x i32> [[A:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2P-NEXT:    ret <16 x i64> [[TMP0]]
//
// AIE2PS-LABEL: @_Z9test_lupsDv16_ji(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i64> @llvm.aie2ps.acc64.v16.I512.ups(<16 x i32> [[A:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2PS-NEXT:    ret <16 x i64> [[TMP0]]
//
v16acc64 test_lups(v16uint32 a, int shft) {
 return lups(a,shft,__SIGN_UNSIGNED);
}

// AIE2P-LABEL: @_Z9test_lupsDv16_iii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i64> @llvm.aie2p.acc64.v16.I512.ups(<16 x i32> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <16 x i64> [[TMP0]]
//
// AIE2PS-LABEL: @_Z9test_lupsDv16_iii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i64> @llvm.aie2ps.acc64.v16.I512.ups(<16 x i32> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <16 x i64> [[TMP0]]
//
v16acc64 test_lups(v16int32 a, int shft, int sign) {
   return lups(a,shft,sign);
}

// AIE2P-LABEL: @_Z9test_lupsDv16_jii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i64> @llvm.aie2p.acc64.v16.I512.ups(<16 x i32> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <16 x i64> [[TMP0]]
//
// AIE2PS-LABEL: @_Z9test_lupsDv16_jii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i64> @llvm.aie2ps.acc64.v16.I512.ups(<16 x i32> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <16 x i64> [[TMP0]]
//
v16acc64 test_lups(v16uint32 a, int shft, int sign) {
   return lups(a,shft,sign);
}

// AIE2P-LABEL: @_Z9test_supsDv32_si(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2p.acc32.v32.I512.ups(<32 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2P-NEXT:    ret <32 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z9test_supsDv32_si(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2PS-NEXT:    ret <32 x i32> [[TMP0]]
//
v32acc32 test_sups(v32int16 a, int shft) {
 return sups(a,shft,__SIGN_SIGNED);
}

// AIE2P-LABEL: @_Z9test_supsDv32_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2p.acc32.v32.I512.ups(<32 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2P-NEXT:    ret <32 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z9test_supsDv32_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2PS-NEXT:    ret <32 x i32> [[TMP0]]
//
v32acc32 test_sups(v32uint16 a, int shft) {
 return sups(a,shft,__SIGN_UNSIGNED);
}

// AIE2P-LABEL: @_Z9test_supsDv32_sii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2p.acc32.v32.I512.ups(<32 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <32 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z9test_supsDv32_sii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <32 x i32> [[TMP0]]
//
v32acc32 test_sups(v32int16 a, int shft, int sign) {
   return sups(a,shft,sign);
}

// AIE2P-LABEL: @_Z9test_supsDv32_tii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2p.acc32.v32.I512.ups(<32 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <32 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z9test_supsDv32_tii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <32 x i32> [[TMP0]]
//
v32acc32 test_sups(v32uint16 a, int shft, int sign) {
   return sups(a,shft,sign);
}

// AIE2P-LABEL: @_Z19test_ups_to_v8acc64Dv8_iii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i64> @llvm.aie2p.acc64.v8.I256.ups(<8 x i32> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <8 x i64> [[TMP0]]
//
// AIE2PS-LABEL: @_Z19test_ups_to_v8acc64Dv8_iii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i64> @llvm.aie2ps.acc64.v8.I256.ups(<8 x i32> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <8 x i64> [[TMP0]]
//
v8acc64 test_ups_to_v8acc64(v8int32 a, int shft, int sign) {
   return ups_to_v8acc64(a,shft,sign);
}

// AIE2P-LABEL: @_Z19test_ups_to_v8acc64Dv8_ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i64> @llvm.aie2p.acc64.v8.I256.ups(<8 x i32> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2P-NEXT:    ret <8 x i64> [[TMP0]]
//
// AIE2PS-LABEL: @_Z19test_ups_to_v8acc64Dv8_ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i64> @llvm.aie2ps.acc64.v8.I256.ups(<8 x i32> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2PS-NEXT:    ret <8 x i64> [[TMP0]]
//
v8acc64 test_ups_to_v8acc64(v8int32 a, int shft) {
   return ups_to_v8acc64(a,shft);
}

// AIE2P-LABEL: @_Z19test_ups_to_v8acc64Dv8_jii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i64> @llvm.aie2p.acc64.v8.I256.ups(<8 x i32> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <8 x i64> [[TMP0]]
//
// AIE2PS-LABEL: @_Z19test_ups_to_v8acc64Dv8_jii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i64> @llvm.aie2ps.acc64.v8.I256.ups(<8 x i32> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <8 x i64> [[TMP0]]
//
v8acc64 test_ups_to_v8acc64(v8uint32 a, int shft, int sign) {
   return ups_to_v8acc64(a,shft,sign);
}

// AIE2P-LABEL: @_Z19test_ups_to_v8acc64Dv8_ji(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i64> @llvm.aie2p.acc64.v8.I256.ups(<8 x i32> [[A:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2P-NEXT:    ret <8 x i64> [[TMP0]]
//
// AIE2PS-LABEL: @_Z19test_ups_to_v8acc64Dv8_ji(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i64> @llvm.aie2ps.acc64.v8.I256.ups(<8 x i32> [[A:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2PS-NEXT:    ret <8 x i64> [[TMP0]]
//
v8acc64 test_ups_to_v8acc64(v8uint32 a, int shft) {
   return ups_to_v8acc64(a,shft);
}

// AIE2P-LABEL: @_Z20test_ups_to_v16acc32Dv16_sii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.acc32.v16.I256.ups(<16 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z20test_ups_to_v16acc32Dv16_sii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.acc32.v16.I256.ups(<16 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <16 x i32> [[TMP0]]
//
v16acc32 test_ups_to_v16acc32(v16int16 a, int shft, int sign) {
   return ups_to_v16acc32(a,shft,sign);
}

// AIE2P-LABEL: @_Z20test_ups_to_v16acc32Dv16_si(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.acc32.v16.I256.ups(<16 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2P-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z20test_ups_to_v16acc32Dv16_si(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.acc32.v16.I256.ups(<16 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2PS-NEXT:    ret <16 x i32> [[TMP0]]
//
v16acc32 test_ups_to_v16acc32(v16int16 a, int shft) {
   return ups_to_v16acc32(a,shft);
}

// AIE2P-LABEL: @_Z20test_ups_to_v16acc32Dv16_tii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.acc32.v16.I256.ups(<16 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z20test_ups_to_v16acc32Dv16_tii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.acc32.v16.I256.ups(<16 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <16 x i32> [[TMP0]]
//
v16acc32 test_ups_to_v16acc32(v16uint16 a, int shft, int sign) {
   return ups_to_v16acc32(a,shft,sign);
}

// AIE2P-LABEL: @_Z20test_ups_to_v16acc32Dv16_ti(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.acc32.v16.I256.ups(<16 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2P-NEXT:    ret <16 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z20test_ups_to_v16acc32Dv16_ti(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.acc32.v16.I256.ups(<16 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2PS-NEXT:    ret <16 x i32> [[TMP0]]
//
v16acc32 test_ups_to_v16acc32(v16uint16 a, int shft) {
   return ups_to_v16acc32(a,shft);
}

// AIE2P-LABEL: @_Z20test_ups_to_v16acc64Dv16_iii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i64> @llvm.aie2p.acc64.v16.I512.ups(<16 x i32> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <16 x i64> [[TMP0]]
//
// AIE2PS-LABEL: @_Z20test_ups_to_v16acc64Dv16_iii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i64> @llvm.aie2ps.acc64.v16.I512.ups(<16 x i32> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <16 x i64> [[TMP0]]
//
v16acc64 test_ups_to_v16acc64(v16int32 a, int shft, int sign) {
   return ups_to_v16acc64(a,shft,sign);
}

// AIE2P-LABEL: @_Z20test_ups_to_v16acc64Dv16_ii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i64> @llvm.aie2p.acc64.v16.I512.ups(<16 x i32> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2P-NEXT:    ret <16 x i64> [[TMP0]]
//
// AIE2PS-LABEL: @_Z20test_ups_to_v16acc64Dv16_ii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i64> @llvm.aie2ps.acc64.v16.I512.ups(<16 x i32> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2PS-NEXT:    ret <16 x i64> [[TMP0]]
//
v16acc64 test_ups_to_v16acc64(v16int32 a, int shft) {
    return ups_to_v16acc64(a,shft);
}

// AIE2P-LABEL: @_Z20test_ups_to_v16acc64Dv16_ji(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i64> @llvm.aie2p.acc64.v16.I512.ups(<16 x i32> [[A:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2P-NEXT:    ret <16 x i64> [[TMP0]]
//
// AIE2PS-LABEL: @_Z20test_ups_to_v16acc64Dv16_ji(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i64> @llvm.aie2ps.acc64.v16.I512.ups(<16 x i32> [[A:%.*]], i32 [[SHFT:%.*]], i32 0)
// AIE2PS-NEXT:    ret <16 x i64> [[TMP0]]
//
v16acc64 test_ups_to_v16acc64(v16uint32 a, int shft) {
    return ups_to_v16acc64(a,shft);
}

// AIE2P-LABEL: @_Z20test_ups_to_v16acc64Dv16_jii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i64> @llvm.aie2p.acc64.v16.I512.ups(<16 x i32> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <16 x i64> [[TMP0]]
//
// AIE2PS-LABEL: @_Z20test_ups_to_v16acc64Dv16_jii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i64> @llvm.aie2ps.acc64.v16.I512.ups(<16 x i32> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <16 x i64> [[TMP0]]
//
v16acc64 test_ups_to_v16acc64(v16uint32 a, int shft, int sign){
   return  ups_to_v16acc64(a,shft,sign);
}

// AIE2P-LABEL: @_Z20test_ups_to_v32acc32Dv32_sii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2p.acc32.v32.I512.ups(<32 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <32 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z20test_ups_to_v32acc32Dv32_sii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <32 x i32> [[TMP0]]
//
v32acc32 test_ups_to_v32acc32(v32int16 a, int shft, int sign) {
   return ups_to_v32acc32(a,shft,sign);
}

// AIE2P-LABEL: @_Z20test_ups_to_v32acc32Dv32_si(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2p.acc32.v32.I512.ups(<32 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2P-NEXT:    ret <32 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z20test_ups_to_v32acc32Dv32_si(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2PS-NEXT:    ret <32 x i32> [[TMP0]]
//
v32acc32 test_ups_to_v32acc32(v32int16 a, int shft) {
   return ups_to_v32acc32(a,shft);
}

// CHECK-LABEL: @_Z28test_v64acc32_sups_with_signDv64_aii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i32> @llvm.aie2ps.acc32.v64.I512.ups(<64 x i8> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <64 x i32> [[TMP0]]
// AIE2P-LABEL: @_Z28test_v64acc32_sups_with_signDv64_aii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i32> @llvm.aie2p.acc32.v64.I512.ups(<64 x i8> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <64 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z28test_v64acc32_sups_with_signDv64_aii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i32> @llvm.aie2ps.acc32.v64.I512.ups(<64 x i8> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <64 x i32> [[TMP0]]
//
v64acc32 test_v64acc32_sups_with_sign(v64int8 a, int shft, int sign) {
   return sups(a,shft,sign);
}

// CHECK-LABEL: @_Z33test_v64acc32_sups_with_sign_confDv64_aiii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[CONV1_I:%.*]] = and i32 [[SAT:%.*]], 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 [[CONV1_I]])
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef <64 x i32> @llvm.aie2ps.acc32.v64.I512.ups(<64 x i8> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    [[CONV3_I:%.*]] = and i32 [[TMP0]], 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 [[CONV3_I]])
// CHECK-NEXT:    ret <64 x i32> [[TMP1]]
// AIE2P-LABEL: @_Z33test_v64acc32_sups_with_sign_confDv64_aiii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef <64 x i32> @llvm.aie2p.acc32.v64.I512.ups(<64 x i8> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// AIE2P-NEXT:    ret <64 x i32> [[TMP1]]
//
// AIE2PS-LABEL: @_Z33test_v64acc32_sups_with_sign_confDv64_aiii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[CONV2_I:%.*]] = and i32 [[SAT:%.*]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV2_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef <64 x i32> @llvm.aie2ps.acc32.v64.I512.ups(<64 x i8> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    [[CONV5_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV5_I]])
// AIE2PS-NEXT:    ret <64 x i32> [[TMP1]]
//
v64acc32 test_v64acc32_sups_with_sign_conf(v64int8 a, int shft, int sign, int sat) {
   return sups_conf(a,shft,sign,sat);
}

// CHECK-LABEL: @_Z28test_v64acc32_sups_with_signDv64_ai(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i32> @llvm.aie2ps.acc32.v64.I512.ups(<64 x i8> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    ret <64 x i32> [[TMP0]]
// AIE2P-LABEL: @_Z28test_v64acc32_sups_with_signDv64_ai(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i32> @llvm.aie2p.acc32.v64.I512.ups(<64 x i8> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2P-NEXT:    ret <64 x i32> [[TMP0]]
//
// AIE2PS-LABEL: @_Z28test_v64acc32_sups_with_signDv64_ai(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i32> @llvm.aie2ps.acc32.v64.I512.ups(<64 x i8> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2PS-NEXT:    ret <64 x i32> [[TMP0]]
//
v64acc32 test_v64acc32_sups_with_sign(v64int8 a, int shft) {
  return sups(a, shft);
}

// CHECK-LABEL: @_Z33test_v64acc32_sups_with_sign_confDv64_aii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[CONV1_I:%.*]] = and i32 [[SAT:%.*]], 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 [[CONV1_I]])
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef <64 x i32> @llvm.aie2ps.acc32.v64.I512.ups(<64 x i8> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    [[CONV3_I:%.*]] = and i32 [[TMP0]], 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 [[CONV3_I]])
// CHECK-NEXT:    ret <64 x i32> [[TMP1]]
// AIE2P-LABEL: @_Z33test_v64acc32_sups_with_sign_confDv64_aii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef <64 x i32> @llvm.aie2p.acc32.v64.I512.ups(<64 x i8> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// AIE2P-NEXT:    ret <64 x i32> [[TMP1]]
//
// AIE2PS-LABEL: @_Z33test_v64acc32_sups_with_sign_confDv64_aii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[CONV2_I:%.*]] = and i32 [[SAT:%.*]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV2_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef <64 x i32> @llvm.aie2ps.acc32.v64.I512.ups(<64 x i8> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2PS-NEXT:    [[CONV5_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV5_I]])
// AIE2PS-NEXT:    ret <64 x i32> [[TMP1]]
//
v64acc32 test_v64acc32_sups_with_sign_conf(v64int8 a, int shft, int sat) {
  return sups_conf(a, shft, sat);
}

// CHECK-LABEL: @_Z19test_lups_with_signDv32_sii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i64> @llvm.aie2ps.acc64.v32.I512.ups(<32 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <32 x i64> [[TMP0]]
// AIE2P-LABEL: @_Z19test_lups_with_signDv32_sii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i64> @llvm.aie2p.acc64.v32.I512.ups(<32 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    ret <32 x i64> [[TMP0]]
//
// AIE2PS-LABEL: @_Z19test_lups_with_signDv32_sii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i64> @llvm.aie2ps.acc64.v32.I512.ups(<32 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    ret <32 x i64> [[TMP0]]
//
v32acc64 test_lups_with_sign(v32int16 a, int shft, int sign) {
   return lups(a,shft,sign);
}

// CHECK-LABEL: @_Z24test_lups_with_sign_confDv32_siii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[CONV1_I:%.*]] = and i32 [[SAT:%.*]], 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 [[CONV1_I]])
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef <32 x i64> @llvm.aie2ps.acc64.v32.I512.ups(<32 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    [[CONV3_I:%.*]] = and i32 [[TMP0]], 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 [[CONV3_I]])
// CHECK-NEXT:    ret <32 x i64> [[TMP1]]
// AIE2P-LABEL: @_Z24test_lups_with_sign_confDv32_siii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef <32 x i64> @llvm.aie2p.acc64.v32.I512.ups(<32 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2P-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// AIE2P-NEXT:    ret <32 x i64> [[TMP1]]
//
// AIE2PS-LABEL: @_Z24test_lups_with_sign_confDv32_siii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[CONV2_I:%.*]] = and i32 [[SAT:%.*]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV2_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef <32 x i64> @llvm.aie2ps.acc64.v32.I512.ups(<32 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// AIE2PS-NEXT:    [[CONV5_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV5_I]])
// AIE2PS-NEXT:    ret <32 x i64> [[TMP1]]
//
v32acc64 test_lups_with_sign_conf(v32int16 a, int shft, int sign, int sat) {
   return lups_conf(a,shft,sign, sat);
}
// CHECK-LABEL: @_Z17test_lups_no_signDv32_si(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i64> @llvm.aie2ps.acc64.v32.I512.ups(<32 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    ret <32 x i64> [[TMP0]]
// AIE2P-LABEL: @_Z17test_lups_no_signDv32_si(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i64> @llvm.aie2p.acc64.v32.I512.ups(<32 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2P-NEXT:    ret <32 x i64> [[TMP0]]
//
// AIE2PS-LABEL: @_Z17test_lups_no_signDv32_si(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i64> @llvm.aie2ps.acc64.v32.I512.ups(<32 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// AIE2PS-NEXT:    ret <32 x i64> [[TMP0]]
//
v32acc64 test_lups_no_sign(v32int16 a, int shft) {
  return lups(a, shft);
}

// CHECK-LABEL: @_Z22test_lups_no_sign_confDv32_sii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i64> @llvm.aie2ps.acc64.v32.I512.ups(<32 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SAT:%.*]])
// CHECK-NEXT:    ret <32 x i64> [[TMP0]]
// AIE2P-LABEL: @_Z22test_lups_no_sign_confDv32_sii(
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i64> @llvm.aie2p.acc64.v32.I512.ups(<32 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SAT:%.*]])
// AIE2P-NEXT:    ret <32 x i64> [[TMP0]]
//
// AIE2PS-LABEL: @_Z22test_lups_no_sign_confDv32_sii(
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i64> @llvm.aie2ps.acc64.v32.I512.ups(<32 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SAT:%.*]])
// AIE2PS-NEXT:    ret <32 x i64> [[TMP0]]
//
v32acc64 test_lups_no_sign_conf(v32int16 a, int shft, int sat) {
  return lups(a, shft, sat);
}


