// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
//===- test-float16-math-overloads.cpp --------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//

// Verify that std::sqrt resolves without ambiguity when called with _Float16 arguments, and lower to the expected float builtins.

// RUN: %clang -O2 --target=aie2ps -nostdlibinc -S -emit-llvm %s -o - | FileCheck --check-prefix=AIE2PS %s

// AIE2PS-LABEL: define dso_local noundef float @_Z13test_sqrt_f167float16(
// AIE2PS-SAME: half noundef [[X:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// AIE2PS-NEXT:  [[ENTRY:.*:]]
// AIE2PS-NEXT:    [[CONV_I:%.*]] = fpext half [[X]] to float
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef float @llvm.aie2ps.sqrtf(float [[CONV_I]])
// AIE2PS-NEXT:    ret float [[TMP0]]
//
float test_sqrt_f16(_Float16 x) {
  return std::sqrt(x);
}

// Also test with the float16 typedef, which is how users typically call these.

// AIE2PS-LABEL: define dso_local noundef float @_Z19test_sqrt_float16_t7float16(
// AIE2PS-SAME: half noundef [[X:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2PS-NEXT:  [[ENTRY:.*:]]
// AIE2PS-NEXT:    [[CONV_I:%.*]] = fpext half [[X]] to float
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef float @llvm.aie2ps.sqrtf(float [[CONV_I]])
// AIE2PS-NEXT:    ret float [[TMP0]]
//
float test_sqrt_float16_t(float16 x) {
  return std::sqrt(x);
}
