// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
//===- test-build-vector-from-byte-loads.cpp ---------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//
// Test that packing 4 byte loads into a 32-bit word via v4int8 produces
// insertelement chains (build_vector) in the LLVM IR.
//
// RUN: %clang -O2 %s --target=aie2ps -nostdlibinc -S -emit-llvm -o - | FileCheck %s

// --- v4int8 vector + bitcast approach, 3D pointer loads ---

// CHECK-LABEL: define dso_local void @_Z18pack_bytes_v4i8_3dPciiRiiiS0_iPi(
// CHECK-SAME: ptr [[PTR:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nocapture nonnull align 4 dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]], i32 noundef [[SIZE2:%.*]], ptr nocapture nonnull align 4 dereferenceable(4) [[COUNT2:%.*]], i32 noundef [[INC2:%.*]], ptr nocapture writeonly initializes((0, 4)) [[DST:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[PTR]], align 1, !tbaa [[TBAA2:![0-9]+]]
// CHECK-NEXT:    [[TMP1:%.*]] = trunc i32 [[OFF]] to i20
// CHECK-NEXT:    [[TMP2:%.*]] = trunc i32 [[INC1]] to i20
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[INC2]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA5:![0-9]+]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[SIZE2]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[COUNT2]], align 4, !tbaa [[TBAA5]]
// CHECK-NEXT:    [[TMP9:%.*]] = trunc i32 [[TMP8]] to i20
// CHECK-NEXT:    [[TMP10:%.*]] = tail call { ptr, i20, i20 } @llvm.aie2ps.add.3d(ptr nonnull [[PTR]], i20 [[TMP1]], i20 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP9]])
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, i20, i20 } [[TMP10]], 1
// CHECK-NEXT:    [[TMP12:%.*]] = zext i20 [[TMP11]] to i32
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, i20, i20 } [[TMP10]], 2
// CHECK-NEXT:    [[TMP14:%.*]] = zext i20 [[TMP13]] to i32
// CHECK-NEXT:    store i32 [[TMP12]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP14]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, i20, i20 } [[TMP10]], 0
// CHECK-NEXT:    [[TMP16:%.*]] = load i8, ptr [[TMP15]], align 1, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP17:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA5]]
// CHECK-NEXT:    [[TMP18:%.*]] = trunc i32 [[TMP17]] to i20
// CHECK-NEXT:    [[TMP19:%.*]] = tail call { ptr, i20, i20 } @llvm.aie2ps.add.3d(ptr nonnull [[TMP15]], i20 [[TMP1]], i20 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP18]], i20 [[TMP7]], i20 [[TMP13]])
// CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { ptr, i20, i20 } [[TMP19]], 1
// CHECK-NEXT:    [[TMP21:%.*]] = zext i20 [[TMP20]] to i32
// CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { ptr, i20, i20 } [[TMP19]], 2
// CHECK-NEXT:    [[TMP23:%.*]] = zext i20 [[TMP22]] to i32
// CHECK-NEXT:    store i32 [[TMP21]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP23]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    [[TMP24:%.*]] = extractvalue { ptr, i20, i20 } [[TMP19]], 0
// CHECK-NEXT:    [[TMP25:%.*]] = load i8, ptr [[TMP24]], align 1, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP26:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA5]]
// CHECK-NEXT:    [[TMP27:%.*]] = trunc i32 [[TMP26]] to i20
// CHECK-NEXT:    [[TMP28:%.*]] = tail call { ptr, i20, i20 } @llvm.aie2ps.add.3d(ptr nonnull [[TMP24]], i20 [[TMP1]], i20 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP27]], i20 [[TMP7]], i20 [[TMP22]])
// CHECK-NEXT:    [[TMP29:%.*]] = extractvalue { ptr, i20, i20 } [[TMP28]], 1
// CHECK-NEXT:    [[TMP30:%.*]] = zext i20 [[TMP29]] to i32
// CHECK-NEXT:    [[TMP31:%.*]] = extractvalue { ptr, i20, i20 } [[TMP28]], 2
// CHECK-NEXT:    [[TMP32:%.*]] = zext i20 [[TMP31]] to i32
// CHECK-NEXT:    store i32 [[TMP30]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP32]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    [[TMP33:%.*]] = extractvalue { ptr, i20, i20 } [[TMP28]], 0
// CHECK-NEXT:    [[TMP34:%.*]] = load i8, ptr [[TMP33]], align 1, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[VECINIT:%.*]] = insertelement <4 x i8> poison, i8 [[TMP0]], i64 0
// CHECK-NEXT:    [[VECINIT3:%.*]] = insertelement <4 x i8> [[VECINIT]], i8 [[TMP16]], i64 1
// CHECK-NEXT:    [[VECINIT4:%.*]] = insertelement <4 x i8> [[VECINIT3]], i8 [[TMP25]], i64 2
// CHECK-NEXT:    [[VECINIT5:%.*]] = insertelement <4 x i8> [[VECINIT4]], i8 [[TMP34]], i64 3
// CHECK-NEXT:    store <4 x i8> [[VECINIT5]], ptr [[DST]], align 4, !tbaa [[TBAA5]]
// CHECK-NEXT:    ret void
//
void pack_bytes_v4i8_3d(char *ptr, int off, int size1, int &count1,
                         int inc1, int size2, int &count2, int inc2,
                         int *dst) {
    char a = *ptr;
    ptr = add_3d_byte(ptr, off, size1, count1, inc1, size2, count2, inc2);
    char b = *ptr;
    ptr = add_3d_byte(ptr, off, size1, count1, inc1, size2, count2, inc2);
    char c = *ptr;
    ptr = add_3d_byte(ptr, off, size1, count1, inc1, size2, count2, inc2);
    char d = *ptr;
    v4int8 v = {a, b, c, d};
    *dst = __builtin_bit_cast(int, v);
}

// --- v4int8 vector + bitcast approach, separate pointers (plain C++) ---

// CHECK-LABEL: define dso_local void @_Z20pack_bytes_v4i8_ptrsPcS_S_S_Pi(
// CHECK-SAME: ptr nocapture readonly [[P0:%.*]], ptr nocapture readonly [[P1:%.*]], ptr nocapture readonly [[P2:%.*]], ptr nocapture readonly [[P3:%.*]], ptr nocapture writeonly initializes((0, 4)) [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[P0]], align 1, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[VECINIT:%.*]] = insertelement <4 x i8> poison, i8 [[TMP0]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = load i8, ptr [[P1]], align 1, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[VECINIT1:%.*]] = insertelement <4 x i8> [[VECINIT]], i8 [[TMP1]], i64 1
// CHECK-NEXT:    [[TMP2:%.*]] = load i8, ptr [[P2]], align 1, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[VECINIT2:%.*]] = insertelement <4 x i8> [[VECINIT1]], i8 [[TMP2]], i64 2
// CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[P3]], align 1, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[VECINIT3:%.*]] = insertelement <4 x i8> [[VECINIT2]], i8 [[TMP3]], i64 3
// CHECK-NEXT:    store <4 x i8> [[VECINIT3]], ptr [[DST]], align 4, !tbaa [[TBAA5]]
// CHECK-NEXT:    ret void
//
void pack_bytes_v4i8_ptrs(char *p0, char *p1, char *p2, char *p3, int *dst) {
    v4int8 v = {*p0, *p1, *p2, *p3};
    *dst = __builtin_bit_cast(int, v);
}
//.
// CHECK: [[TBAA2]] = !{[[META3:![0-9]+]], [[META3]], i64 0}
// CHECK: [[META3]] = !{!"omnipotent char", [[META4:![0-9]+]], i64 0}
// CHECK: [[META4]] = !{!"Simple C++ TBAA"}
// CHECK: [[TBAA5]] = !{[[META6:![0-9]+]], [[META6]], i64 0}
// CHECK: [[META6]] = !{!"int", [[META3]], i64 0}
//.
