// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 4
//===- aie2p-nlf.cpp -------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//

// RUN: %clang -O2 --target=aie2p -nostdlibinc -S -emit-llvm %s -o - | FileCheck %s -check-prefix=CHECK-AIE2P
// RUN: %clang -O2 --target=aie2ps -nostdlibinc -S -emit-llvm %s -o - | FileCheck %s -check-prefix=CHECK-AIE2PS

// CHECK-LABEL: define dso_local noundef float @_Z11test__sqrtff(
// CHECK-SAME: float noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef float @llvm.aie2p.sqrtf(float [[A]])
// CHECK-NEXT:    ret float [[TMP0]]
// CHECK-AIE2P-LABEL: define dso_local noundef float @_Z11test__sqrtff(
// CHECK-AIE2P-SAME: float noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef float @llvm.aie2p.sqrtf(float [[A]])
// CHECK-AIE2P-NEXT:    ret float [[TMP0]]
//
// CHECK-AIE2PS-LABEL: define dso_local noundef float @_Z11test__sqrtff(
// CHECK-AIE2PS-SAME: float noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef float @llvm.aie2ps.sqrtf(float [[A]])
// CHECK-AIE2PS-NEXT:    ret float [[TMP0]]
//
float test__sqrtf(float a) {
  return _sqrtf(a);
}
// CHECK-LABEL: define dso_local noundef float @_Z8test_invf(
// CHECK-SAME: float noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef float @llvm.aie2p.inv(float [[A]])
// CHECK-NEXT:    ret float [[TMP0]]
// CHECK-AIE2P-LABEL: define dso_local noundef float @_Z8test_invf(
// CHECK-AIE2P-SAME: float noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef float @llvm.aie2p.inv(float [[A]])
// CHECK-AIE2P-NEXT:    ret float [[TMP0]]
//
// CHECK-AIE2PS-LABEL: define dso_local noundef float @_Z8test_invf(
// CHECK-AIE2PS-SAME: float noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef float @llvm.aie2ps.inv(float [[A]])
// CHECK-AIE2PS-NEXT:    ret float [[TMP0]]
//
float test_inv(float a) {
  return inv(a);
}
// CHECK-LABEL: define dso_local noundef float @_Z12test_invsqrtf(
// CHECK-SAME: float noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef float @llvm.aie2p.invsqrt(float [[A]])
// CHECK-NEXT:    ret float [[TMP0]]
// CHECK-AIE2P-LABEL: define dso_local noundef float @_Z12test_invsqrtf(
// CHECK-AIE2P-SAME: float noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef float @llvm.aie2p.invsqrt(float [[A]])
// CHECK-AIE2P-NEXT:    ret float [[TMP0]]
//
// CHECK-AIE2PS-LABEL: define dso_local noundef float @_Z12test_invsqrtf(
// CHECK-AIE2PS-SAME: float noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef float @llvm.aie2ps.invsqrt(float [[A]])
// CHECK-AIE2PS-NEXT:    ret float [[TMP0]]
//
float test_invsqrt(float a) {
  return invsqrt(a);
}
