// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 4
//===- test-vector-acc32.cc ------------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//



// RUN: %clang -O2 %s --target=aie2p -nostdlibinc -S -emit-llvm -o - | FileCheck %s -check-prefix=CHECK-AIE2P
// RUN: %clang -O2 %s --target=aie2ps -nostdlibinc -S -emit-llvm -o - | FileCheck %s -check-prefix=CHECK-AIE2PS
// CHECK-LABEL: define dso_local inreg noundef <8 x i32> @_Z12test_v8acc32Dv8_u7__acc32(
// CHECK-SAME: <8 x i32> inreg noundef returned [[A:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <8 x i32> [[A]]
// CHECK-AIE2P-LABEL: define dso_local inreg noundef <8 x i32> @_Z12test_v8acc32Dv8_u7__acc32(
// CHECK-AIE2P-SAME: <8 x i32> inreg noundef returned [[A:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    ret <8 x i32> [[A]]
//
// CHECK-AIE2PS-LABEL: define dso_local inreg noundef <8 x i32> @_Z12test_v8acc32Dv8_u7__acc32(
// CHECK-AIE2PS-SAME: <8 x i32> inreg noundef returned [[A:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    ret <8 x i32> [[A]]
//
v8acc32 test_v8acc32(v8acc32 a) {
 return a;
}
// CHECK-LABEL: define dso_local inreg noundef <16 x i32> @_Z13test_v16acc32Dv16_u7__acc32(
// CHECK-SAME: <16 x i32> inreg noundef returned [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <16 x i32> [[A]]
// CHECK-AIE2P-LABEL: define dso_local inreg noundef <16 x i32> @_Z13test_v16acc32Dv16_u7__acc32(
// CHECK-AIE2P-SAME: <16 x i32> inreg noundef returned [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    ret <16 x i32> [[A]]
//
// CHECK-AIE2PS-LABEL: define dso_local inreg noundef <16 x i32> @_Z13test_v16acc32Dv16_u7__acc32(
// CHECK-AIE2PS-SAME: <16 x i32> inreg noundef returned [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    ret <16 x i32> [[A]]
//
v16acc32 test_v16acc32(v16acc32 a) {
 return a;
}
// CHECK-LABEL: define dso_local inreg noundef <32 x i32> @_Z13test_v32acc32Dv32_u7__acc32(
// CHECK-SAME: <32 x i32> inreg noundef returned [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <32 x i32> [[A]]
// CHECK-AIE2P-LABEL: define dso_local inreg noundef <32 x i32> @_Z13test_v32acc32Dv32_u7__acc32(
// CHECK-AIE2P-SAME: <32 x i32> inreg noundef returned [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    ret <32 x i32> [[A]]
//
// CHECK-AIE2PS-LABEL: define dso_local inreg noundef <32 x i32> @_Z13test_v32acc32Dv32_u7__acc32(
// CHECK-AIE2PS-SAME: <32 x i32> inreg noundef returned [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    ret <32 x i32> [[A]]
//
v32acc32 test_v32acc32(v32acc32 a) {
 return a;
}
// CHECK-LABEL: define dso_local inreg noundef <64 x i32> @_Z13test_v64acc32Dv64_u7__acc32(
// CHECK-SAME: <64 x i32> inreg noundef returned [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <64 x i32> [[A]]
// CHECK-AIE2P-LABEL: define dso_local inreg noundef <64 x i32> @_Z13test_v64acc32Dv64_u7__acc32(
// CHECK-AIE2P-SAME: <64 x i32> inreg noundef returned [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    ret <64 x i32> [[A]]
//
// CHECK-AIE2PS-LABEL: define dso_local inreg noundef <64 x i32> @_Z13test_v64acc32Dv64_u7__acc32(
// CHECK-AIE2PS-SAME: <64 x i32> inreg noundef returned [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    ret <64 x i32> [[A]]
//
v64acc32 test_v64acc32(v64acc32 a) {
 return a;
}
