// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 4
//===- aie2p-cnvf2f.cpp -------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//

// RUN: %clang -O2 --target=aie2p -nostdlibinc -S -emit-llvm %s -o - | FileCheck %s -check-prefix=CHECK-AIE2P
// RUN: %clang -O2 --target=aie2ps -nostdlibinc -S -emit-llvm %s -o - | FileCheck %s -check-prefix=CHECK-AIE2PS

// CHECK-LABEL: define dso_local noundef float @_Z14test_fix2floati(
// CHECK-SAME: i32 noundef [[N:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef float @llvm.aie2p.fx2flt(i32 [[N]], i32 0)
// CHECK-NEXT:    ret float [[TMP0]]
// CHECK-AIE2P-LABEL: define dso_local noundef float @_Z14test_fix2floati(
// CHECK-AIE2P-SAME: i32 noundef [[N:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef float @llvm.aie2p.fx2flt(i32 [[N]], i32 0)
// CHECK-AIE2P-NEXT:    ret float [[TMP0]]
//
// CHECK-AIE2PS-LABEL: define dso_local noundef float @_Z14test_fix2floati(
// CHECK-AIE2PS-SAME: i32 noundef [[N:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef float @llvm.aie2ps.fx2flt(i32 [[N]], i32 0)
// CHECK-AIE2PS-NEXT:    ret float [[TMP0]]
//
float test_fix2float(int n) {
  return fix2float(n);
}
// CHECK-LABEL: define dso_local noundef float @_Z14test_fix2floatii(
// CHECK-SAME: i32 noundef [[N:%.*]], i32 noundef [[SFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef float @llvm.aie2p.fx2flt(i32 [[N]], i32 [[SFT]])
// CHECK-NEXT:    ret float [[TMP0]]
// CHECK-AIE2P-LABEL: define dso_local noundef float @_Z14test_fix2floatii(
// CHECK-AIE2P-SAME: i32 noundef [[N:%.*]], i32 noundef [[SFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef float @llvm.aie2p.fx2flt(i32 [[N]], i32 [[SFT]])
// CHECK-AIE2P-NEXT:    ret float [[TMP0]]
//
// CHECK-AIE2PS-LABEL: define dso_local noundef float @_Z14test_fix2floatii(
// CHECK-AIE2PS-SAME: i32 noundef [[N:%.*]], i32 noundef [[SFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef float @llvm.aie2ps.fx2flt(i32 [[N]], i32 [[SFT]])
// CHECK-AIE2PS-NEXT:    ret float [[TMP0]]
//
float test_fix2float(int n, int sft) {
  return fix2float(n, sft);
}
// CHECK-LABEL: define dso_local noundef i32 @_Z14test_float2fixf(
// CHECK-SAME: float noundef [[N:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.flt2fx(float [[N]], i32 0)
// CHECK-NEXT:    ret i32 [[TMP0]]
// CHECK-AIE2P-LABEL: define dso_local noundef i32 @_Z14test_float2fixf(
// CHECK-AIE2P-SAME: float noundef [[N:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.flt2fx(float [[N]], i32 0)
// CHECK-AIE2P-NEXT:    ret i32 [[TMP0]]
//
// CHECK-AIE2PS-LABEL: define dso_local noundef i32 @_Z14test_float2fixf(
// CHECK-AIE2PS-SAME: float noundef [[N:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.flt2fx(float [[N]], i32 0)
// CHECK-AIE2PS-NEXT:    ret i32 [[TMP0]]
//
int test_float2fix(float n) {
  return float2fix(n);
}
// CHECK-LABEL: define dso_local noundef i32 @_Z14test_float2fixfi(
// CHECK-SAME: float noundef [[N:%.*]], i32 noundef [[SFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.flt2fx(float [[N]], i32 [[SFT]])
// CHECK-NEXT:    ret i32 [[TMP0]]
// CHECK-AIE2P-LABEL: define dso_local noundef i32 @_Z14test_float2fixfi(
// CHECK-AIE2P-SAME: float noundef [[N:%.*]], i32 noundef [[SFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2P-NEXT:  entry:
// CHECK-AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.flt2fx(float [[N]], i32 [[SFT]])
// CHECK-AIE2P-NEXT:    ret i32 [[TMP0]]
//
// CHECK-AIE2PS-LABEL: define dso_local noundef i32 @_Z14test_float2fixfi(
// CHECK-AIE2PS-SAME: float noundef [[N:%.*]], i32 noundef [[SFT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.flt2fx(float [[N]], i32 [[SFT]])
// CHECK-AIE2PS-NEXT:    ret i32 [[TMP0]]
//
int test_float2fix(float n, int sft) {
  return float2fix(n, sft);
}
