# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -verify-machineinstrs --march=aie2p -run-pass=prologepilog %s -o - | FileCheck %s
# RUN: llc -verify-machineinstrs --march=aie2ps -run-pass=prologepilog %s -o - | FileCheck -check-prefix=AIE2PS %s

# l4 is composed of r8-r9, which are callee-saved. None of those regs
# are used as CC registers, so r16-r17 should be saved-restored by PEI.
---
name:            save_L
body:             |
  bb.0:
    liveins: $l1
    ; CHECK-LABEL: name: save_L
    ; CHECK: liveins: $l1, $r8, $r9
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $r0 = PseudoMove killed $r8
    ; CHECK-NEXT: $r1 = PseudoMove killed $r9
    ; CHECK-NEXT: $l4 = COPY $l1
    ; CHECK-NEXT: $r9 = PseudoMove killed $r1
    ; CHECK-NEXT: $r8 = PseudoMove killed $r0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $l4
    ;
    ; AIE2PS-LABEL: name: save_L
    ; AIE2PS: liveins: $l1, $l4
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; AIE2PS-NEXT: ST_dml_sts_scalar_spill killed $l4, -64, implicit $sp :: (store (s64) into %stack.0, align 4)
    ; AIE2PS-NEXT: $l4 = COPY $l1
    ; AIE2PS-NEXT: $l4 = LDA_dml_lda_scalar_L_spill -64, implicit $sp :: (load (s64) from %stack.0, align 4)
    ; AIE2PS-NEXT: frame-destroy PADDXM_pstm_sp_imm -64, implicit-def $sp, implicit $sp
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit $l4
    $l4 = COPY $l1
    PseudoRET implicit $lr, implicit $l4
...

# Same as above, but l0 is used by the calling convention. It's therefore
# not callee-saved.
---
name:            no_save_L
calleeSavedRegisters: [ '$lr', '$r20', '$r21', '$r22', '$r23', '$p6', '$p7' ]
body:             |
  bb.0:
    liveins: $l1
    ; CHECK-LABEL: name: no_save_L
    ; CHECK: liveins: $l1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $l4 = COPY $l1
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $l4
    ;
    ; AIE2PS-LABEL: name: no_save_L
    ; AIE2PS: liveins: $l1
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: $l4 = COPY $l1
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit $l4
    $l4 = COPY $l1
    PseudoRET implicit $lr, implicit $l4
...

# Similar to no_save_L, but write to $l4's subregs instead.
---
name:            no_save_L_subregs
calleeSavedRegisters: [ '$lr', '$r18', '$r19', '$r20', '$r21', '$r22', '$r23', '$p6', '$p7' ]
body:             |
  bb.0:
    liveins: $l0
    ; CHECK-LABEL: name: no_save_L_subregs
    ; CHECK: liveins: $l0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $r8 = COPY $r0
    ; CHECK-NEXT: $r9 = COPY $r1
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    ;
    ; AIE2PS-LABEL: name: no_save_L_subregs
    ; AIE2PS: liveins: $l0
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: $r8 = COPY $r0
    ; AIE2PS-NEXT: $r9 = COPY $r1
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    $r8 = COPY $r0
    $r9 = COPY $r1
    PseudoRET implicit $lr, implicit $r0, implicit $r1
...

# Here, only $l4.sub_hi (r9) is callee-saved, not $l4.sub_lo (r8).
# Given that $l4 is re-defined, r9 should be saved.
---
name:            save_partial_L
calleeSavedRegisters: [ '$lr', '$r9', '$r18', '$r19', '$r20', '$r21', '$r22', '$r23', '$p6', '$p7' ]
body:             |
  bb.0:
    liveins: $l1

    ; CHECK-LABEL: name: save_partial_L
    ; CHECK: liveins: $l1, $r9
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $r0 = PseudoMove killed $r9
    ; CHECK-NEXT: $l4 = COPY $l1
    ; CHECK-NEXT: $r9 = PseudoMove killed $r0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $l4
    ;
    ; AIE2PS-LABEL: name: save_partial_L
    ; AIE2PS: liveins: $l1, $r9
    ; AIE2PS-NEXT: {{  $}}
    ; AIE2PS-NEXT: $r0 = PseudoMove killed $r9
    ; AIE2PS-NEXT: $l4 = COPY $l1
    ; AIE2PS-NEXT: $r9 = PseudoMove killed $r0
    ; AIE2PS-NEXT: PseudoRET implicit $lr, implicit $l4
    $l4 = COPY $l1
    PseudoRET implicit $lr, implicit $l4
...
