; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2024-2026 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc --march=aie2 --stop-after=prologepilog < %s | FileCheck %s --check-prefix=COMMON --check-prefix=AIE2
; RUN: llc --march=aie2p --stop-after=prologepilog < %s | FileCheck %s --check-prefix=COMMON --check-prefix=AIE2P
; RUN: llc --march=aie2ps --stop-after=prologepilog < %s | FileCheck %s --check-prefix=COMMON --check-prefix=AIE2PS

declare i32 @external_function(i32)

define i32 @test_call_external(i32 %a) nounwind {
  ; AIE2-LABEL: name: test_call_external
  ; AIE2: bb.0 (%ir-block.0):
  ; AIE2-NEXT:   liveins: $r1
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT:   frame-setup PADD_sp_imm_pseudo 32, implicit-def $sp, implicit $sp
  ; AIE2-NEXT:   ST_dms_spill killed $lr, -32, implicit $sp :: (store (s32) into %stack.0)
  ; AIE2-NEXT:   PseudoJL @external_function, csr_aie2, implicit-def $lr, implicit $r1, implicit-def $r0
  ; AIE2-NEXT:   $lr = LDA_dms_spill -32, implicit $sp :: (load (s32) from %stack.0)
  ; AIE2-NEXT:   frame-destroy PADD_sp_imm_pseudo -32, implicit-def $sp, implicit $sp
  ; AIE2-NEXT:   PseudoRET implicit $lr, implicit $r0
  ;
  ; AIE2P-LABEL: name: test_call_external
  ; AIE2P: bb.0 (%ir-block.0):
  ; AIE2P-NEXT:   liveins: $r1
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT:   frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
  ; AIE2P-NEXT:   ST_dms_sts_spill killed $lr, -64, implicit $sp :: (store (s32) into %stack.0)
  ; AIE2P-NEXT:   PseudoJL @external_function, csr_aie2p, implicit-def $lr, implicit $r1, implicit-def $r0
  ; AIE2P-NEXT:   $lr = LDA_dms_lda_spill -64, implicit $sp :: (load (s32) from %stack.0)
  ; AIE2P-NEXT:   frame-destroy PADDXM_pstm_sp_imm -64, implicit-def $sp, implicit $sp
  ; AIE2P-NEXT:   PseudoRET implicit $lr, implicit $r0
  ;
  ; AIE2PS-LABEL: name: test_call_external
  ; AIE2PS: bb.0 (%ir-block.0):
  ; AIE2PS-NEXT:   liveins: $r1
  ; AIE2PS-NEXT: {{  $}}
  ; AIE2PS-NEXT:   frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
  ; AIE2PS-NEXT:   ST_dms_sts_scalar_spill killed $lr, -64, implicit $sp :: (store (s32) into %stack.0)
  ; AIE2PS-NEXT:   PseudoJL @external_function, csr_aie2ps, implicit-def $lr, implicit $r1, implicit-def $r0
  ; AIE2PS-NEXT:   $lr = LDA_dms_lda_scalar_spill -64, implicit $sp :: (load (s32) from %stack.0)
  ; AIE2PS-NEXT:   frame-destroy PADDXM_pstm_sp_imm -64, implicit-def $sp, implicit $sp
  ; AIE2PS-NEXT:   PseudoRET implicit $lr, implicit $r0
  %1 = call i32 @external_function(i32 %a)
  ret i32 %1
}

declare dso_local i32 @dso_local_function(i32)

define i32 @test_call_dso_local(i32 %a) nounwind {
  ; AIE2-LABEL: name: test_call_dso_local
  ; AIE2: bb.0 (%ir-block.0):
  ; AIE2-NEXT:   liveins: $r1
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT:   frame-setup PADD_sp_imm_pseudo 32, implicit-def $sp, implicit $sp
  ; AIE2-NEXT:   ST_dms_spill killed $lr, -32, implicit $sp :: (store (s32) into %stack.0)
  ; AIE2-NEXT:   PseudoJL @dso_local_function, csr_aie2, implicit-def $lr, implicit $r1, implicit-def $r0
  ; AIE2-NEXT:   $lr = LDA_dms_spill -32, implicit $sp :: (load (s32) from %stack.0)
  ; AIE2-NEXT:   frame-destroy PADD_sp_imm_pseudo -32, implicit-def $sp, implicit $sp
  ; AIE2-NEXT:   PseudoRET implicit $lr, implicit $r0
  ;
  ; AIE2P-LABEL: name: test_call_dso_local
  ; AIE2P: bb.0 (%ir-block.0):
  ; AIE2P-NEXT:   liveins: $r1
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT:   frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
  ; AIE2P-NEXT:   ST_dms_sts_spill killed $lr, -64, implicit $sp :: (store (s32) into %stack.0)
  ; AIE2P-NEXT:   PseudoJL @dso_local_function, csr_aie2p, implicit-def $lr, implicit $r1, implicit-def $r0
  ; AIE2P-NEXT:   $lr = LDA_dms_lda_spill -64, implicit $sp :: (load (s32) from %stack.0)
  ; AIE2P-NEXT:   frame-destroy PADDXM_pstm_sp_imm -64, implicit-def $sp, implicit $sp
  ; AIE2P-NEXT:   PseudoRET implicit $lr, implicit $r0
  ;
  ; AIE2PS-LABEL: name: test_call_dso_local
  ; AIE2PS: bb.0 (%ir-block.0):
  ; AIE2PS-NEXT:   liveins: $r1
  ; AIE2PS-NEXT: {{  $}}
  ; AIE2PS-NEXT:   frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
  ; AIE2PS-NEXT:   ST_dms_sts_scalar_spill killed $lr, -64, implicit $sp :: (store (s32) into %stack.0)
  ; AIE2PS-NEXT:   PseudoJL @dso_local_function, csr_aie2ps, implicit-def $lr, implicit $r1, implicit-def $r0
  ; AIE2PS-NEXT:   $lr = LDA_dms_lda_scalar_spill -64, implicit $sp :: (load (s32) from %stack.0)
  ; AIE2PS-NEXT:   frame-destroy PADDXM_pstm_sp_imm -64, implicit-def $sp, implicit $sp
  ; AIE2PS-NEXT:   PseudoRET implicit $lr, implicit $r0
  %1 = call i32 @dso_local_function(i32 %a)
  ret i32 %1
}

define i32 @defined_function(i32 %a) nounwind {
  ; COMMON-LABEL: name: defined_function
  ; COMMON: bb.0 (%ir-block.0):
  ; COMMON-NEXT:   liveins: $r1
  ; COMMON-NEXT: {{  $}}
  ; COMMON-NEXT:   renamable $r0 = ADD_add_r_ri killed renamable $r1, 1, implicit-def dead $srcarry
  ; COMMON-NEXT:   PseudoRET implicit $lr, implicit $r0
  %1 = add i32 %a, 1
  ret i32 %1
}

define i32 @test_call_defined(i32 %a) nounwind {
  ; AIE2-LABEL: name: test_call_defined
  ; AIE2: bb.0 (%ir-block.0):
  ; AIE2-NEXT:   liveins: $r1
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT:   frame-setup PADD_sp_imm_pseudo 32, implicit-def $sp, implicit $sp
  ; AIE2-NEXT:   ST_dms_spill killed $lr, -32, implicit $sp :: (store (s32) into %stack.0)
  ; AIE2-NEXT:   PseudoJL @defined_function, csr_aie2, implicit-def $lr, implicit $r1, implicit-def $r0
  ; AIE2-NEXT:   $lr = LDA_dms_spill -32, implicit $sp :: (load (s32) from %stack.0)
  ; AIE2-NEXT:   frame-destroy PADD_sp_imm_pseudo -32, implicit-def $sp, implicit $sp
  ; AIE2-NEXT:   PseudoRET implicit $lr, implicit $r0
  ;
  ; AIE2P-LABEL: name: test_call_defined
  ; AIE2P: bb.0 (%ir-block.0):
  ; AIE2P-NEXT:   liveins: $r1
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT:   frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
  ; AIE2P-NEXT:   ST_dms_sts_spill killed $lr, -64, implicit $sp :: (store (s32) into %stack.0)
  ; AIE2P-NEXT:   PseudoJL @defined_function, csr_aie2p, implicit-def $lr, implicit $r1, implicit-def $r0
  ; AIE2P-NEXT:   $lr = LDA_dms_lda_spill -64, implicit $sp :: (load (s32) from %stack.0)
  ; AIE2P-NEXT:   frame-destroy PADDXM_pstm_sp_imm -64, implicit-def $sp, implicit $sp
  ; AIE2P-NEXT:   PseudoRET implicit $lr, implicit $r0
  ;
  ; AIE2PS-LABEL: name: test_call_defined
  ; AIE2PS: bb.0 (%ir-block.0):
  ; AIE2PS-NEXT:   liveins: $r1
  ; AIE2PS-NEXT: {{  $}}
  ; AIE2PS-NEXT:   frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
  ; AIE2PS-NEXT:   ST_dms_sts_scalar_spill killed $lr, -64, implicit $sp :: (store (s32) into %stack.0)
  ; AIE2PS-NEXT:   PseudoJL @defined_function, csr_aie2ps, implicit-def $lr, implicit $r1, implicit-def $r0
  ; AIE2PS-NEXT:   $lr = LDA_dms_lda_scalar_spill -64, implicit $sp :: (load (s32) from %stack.0)
  ; AIE2PS-NEXT:   frame-destroy PADDXM_pstm_sp_imm -64, implicit-def $sp, implicit $sp
  ; AIE2PS-NEXT:   PseudoRET implicit $lr, implicit $r0
  %1 = call i32 @defined_function(i32 %a)
  ret i32 %1
}

; Ensure that calls to fastcc functions aren't rejected. Such calls may be
; introduced when compiling with optimisation.
define fastcc i32 @fastcc_function(i32 %a, i32 %b) nounwind {
  ; AIE2-LABEL: name: fastcc_function
  ; AIE2: bb.0 (%ir-block.0):
  ; AIE2-NEXT:   liveins: $r1, $r2
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT:   renamable $r0 = ADD killed renamable $r1, killed renamable $r2, implicit-def dead $srcarry
  ; AIE2-NEXT:   PseudoRET implicit $lr, implicit $r0
  ;
  ; AIE2P-LABEL: name: fastcc_function
  ; AIE2P: bb.0 (%ir-block.0):
  ; AIE2P-NEXT:   liveins: $r1, $r2
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT:   renamable $r0 = ADD_alu_r_rr killed renamable $r1, killed renamable $r2, implicit-def dead $srcarry
  ; AIE2P-NEXT:   PseudoRET implicit $lr, implicit $r0
  ;
  ; AIE2PS-LABEL: name: fastcc_function
  ; AIE2PS: bb.0 (%ir-block.0):
  ; AIE2PS-NEXT:   liveins: $r1, $r2
  ; AIE2PS-NEXT: {{  $}}
  ; AIE2PS-NEXT:   renamable $r0 = ADD_alu_r_rr killed renamable $r1, killed renamable $r2, implicit-def dead $srcarry
  ; AIE2PS-NEXT:   PseudoRET implicit $lr, implicit $r0
 %1 = add i32 %a, %b
 ret i32 %1
}

define i32 @test_call_fastcc(i32 %a, i32 %b) nounwind {
  ; AIE2-LABEL: name: test_call_fastcc
  ; AIE2: bb.0 (%ir-block.0):
  ; AIE2-NEXT:   liveins: $r1, $r2, $r16
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT:   frame-setup PADD_sp_imm_pseudo 32, implicit-def $sp, implicit $sp
  ; AIE2-NEXT:   ST_dms_spill killed $lr, -32, implicit $sp :: (store (s32) into %stack.0)
  ; AIE2-NEXT:   ST_dms_spill killed $r16, -28, implicit $sp :: (store (s32) into %stack.1)
  ; AIE2-NEXT:   renamable $r16 = COPY $r1
  ; AIE2-NEXT:   PseudoJL @fastcc_function, csr_aie2, implicit-def $lr, implicit $r1, implicit $r2, implicit-def dead $r0
  ; AIE2-NEXT:   $r0 = COPY killed renamable $r16
  ; AIE2-NEXT:   $r16 = LDA_dms_spill -28, implicit $sp :: (load (s32) from %stack.1)
  ; AIE2-NEXT:   $lr = LDA_dms_spill -32, implicit $sp :: (load (s32) from %stack.0)
  ; AIE2-NEXT:   frame-destroy PADD_sp_imm_pseudo -32, implicit-def $sp, implicit $sp
  ; AIE2-NEXT:   PseudoRET implicit $lr, implicit killed $r0
  ;
  ; AIE2P-LABEL: name: test_call_fastcc
  ; AIE2P: bb.0 (%ir-block.0):
  ; AIE2P-NEXT:   liveins: $r1, $r2, $r8
  ; AIE2P-NEXT: {{  $}}
  ; AIE2P-NEXT:   frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
  ; AIE2P-NEXT:   ST_dms_sts_spill killed $lr, -64, implicit $sp :: (store (s32) into %stack.0)
  ; AIE2P-NEXT:   ST_dms_sts_spill killed $r8, -60, implicit $sp :: (store (s32) into %stack.1)
  ; AIE2P-NEXT:   renamable $r8 = COPY $r1
  ; AIE2P-NEXT:   PseudoJL @fastcc_function, csr_aie2p, implicit-def $lr, implicit $r1, implicit $r2, implicit-def dead $r0
  ; AIE2P-NEXT:   $r0 = COPY killed renamable $r8
  ; AIE2P-NEXT:   $r8 = LDA_dms_lda_spill -60, implicit $sp :: (load (s32) from %stack.1)
  ; AIE2P-NEXT:   $lr = LDA_dms_lda_spill -64, implicit $sp :: (load (s32) from %stack.0)
  ; AIE2P-NEXT:   frame-destroy PADDXM_pstm_sp_imm -64, implicit-def $sp, implicit $sp
  ; AIE2P-NEXT:   PseudoRET implicit $lr, implicit killed $r0
  ;
  ; AIE2PS-LABEL: name: test_call_fastcc
  ; AIE2PS: bb.0 (%ir-block.0):
  ; AIE2PS-NEXT:   liveins: $r1, $r2, $r9
  ; AIE2PS-NEXT: {{  $}}
  ; AIE2PS-NEXT:   frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
  ; AIE2PS-NEXT:   ST_dms_sts_scalar_spill killed $lr, -64, implicit $sp :: (store (s32) into %stack.0)
  ; AIE2PS-NEXT:   ST_dms_sts_scalar_spill killed $r9, -60, implicit $sp :: (store (s32) into %stack.1)
  ; AIE2PS-NEXT:   renamable $r9 = COPY $r1
  ; AIE2PS-NEXT:   PseudoJL @fastcc_function, csr_aie2ps, implicit-def $lr, implicit $r1, implicit $r2, implicit-def dead $r0
  ; AIE2PS-NEXT:   $r0 = COPY killed renamable $r9
  ; AIE2PS-NEXT:   $r9 = LDA_dms_lda_scalar_spill -60, implicit $sp :: (load (s32) from %stack.1)
  ; AIE2PS-NEXT:   $lr = LDA_dms_lda_scalar_spill -64, implicit $sp :: (load (s32) from %stack.0)
  ; AIE2PS-NEXT:   frame-destroy PADDXM_pstm_sp_imm -64, implicit-def $sp, implicit $sp
  ; AIE2PS-NEXT:   PseudoRET implicit $lr, implicit killed $r0
  %1 = call fastcc i32 @fastcc_function(i32 %a, i32 %b)
  ret i32 %a
}
