; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie2 -verify-machineinstrs -o - < %s | FileCheck --check-prefix=COMMON --check-prefix=AIE2 %s
; RUN: llc -mtriple=aie2p -verify-machineinstrs -o - < %s | FileCheck --check-prefix=COMMON --check-prefix=AIE2P %s

; NOTE: both versions for the second operand of the builtin are covered by CLZ

define i32 @f(i32 %x) {
; CHECK-LABEL: f:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    clz r0, r1 // Delay Slot 1
; COMMON-LABEL: f:
; COMMON:       // %bb.0: // %entry
; COMMON-NEXT:    ret lr
; COMMON-NEXT:    nop // Delay Slot 5
; COMMON-NEXT:    nop // Delay Slot 4
; COMMON-NEXT:    nop // Delay Slot 3
; COMMON-NEXT:    clz r0, r1 // Delay Slot 2
; COMMON-NEXT:    nop // Delay Slot 1
entry:
  %0 = call i32 @llvm.ctlz.i32(i32 %x, i1 false)
  ret i32 %0
}

declare i32 @llvm.ctlz.i32(i32, i1 immarg)
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; AIE2: {{.*}}
; AIE2P: {{.*}}
