; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2024-2026 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie2 --issue-limit=1 -verify-machineinstrs -o - < %s \
; RUN:   | FileCheck %s --check-prefixes=AIE2
; RUN: llc -mtriple=aie2p --issue-limit=1 -verify-machineinstrs -o - < %s \
; RUN:   | FileCheck %s --check-prefixes=AIE2P
; RUN: llc -mtriple=aie2ps --issue-limit=1 -verify-machineinstrs -o - < %s \
; RUN:   | FileCheck %s --check-prefixes=AIE2PS

define void @test_simple_dyn_alloca(i32 noundef %n) {
; AIE2-LABEL: test_simple_dyn_alloca:
; AIE2:       // %bb.0: // %entry
; AIE2-NEXT:    paddb [sp], #32; nopa ; nops ; nopxm ; nopv
; AIE2-NEXT:    mova r1, #2; nopx
; AIE2-NEXT:    st p7, [sp, #-28] // 4-byte Folded Spill
; AIE2-NEXT:    mov p7, sp
; AIE2-NEXT:    mov p1, sp
; AIE2-NEXT:    lshl r0, r0, r1
; AIE2-NEXT:    mova r1, #-32
; AIE2-NEXT:    st lr, [sp, #-32] // 4-byte Folded Spill
; AIE2-NEXT:    padda [p7], #-32
; AIE2-NEXT:    add r0, r0, #31
; AIE2-NEXT:    jl #extern_call
; AIE2-NEXT:    mov p0, p1 // Delay Slot 5
; AIE2-NEXT:    and r0, r0, r1 // Delay Slot 4
; AIE2-NEXT:    mov m0, r0 // Delay Slot 3
; AIE2-NEXT:    paddb [p1], m0 // Delay Slot 2
; AIE2-NEXT:    mov sp, p1 // Delay Slot 1
; AIE2-NEXT:    nopa ; nopb ; nopx ; mov sp, p7; nops
; AIE2-NEXT:    lda lr, [sp, #-32] // 4-byte Folded Reload
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    lda p7, [sp, #-28] // 4-byte Folded Reload
; AIE2-NEXT:    ret lr
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    nop // Delay Slot 2
; AIE2-NEXT:    paddb [sp], #-32 // Delay Slot 1
;
; AIE2P-LABEL: test_simple_dyn_alloca:
; AIE2P:       // %bb.0: // %entry
; AIE2P-NEXT:    mova r1, #2; nopb ; nops ; nopxm ; nopv
; AIE2P-NEXT:    paddxm [sp], #64
; AIE2P-NEXT:    lshl r0, r0, r1
; AIE2P-NEXT:    st p7, [sp, #-60] // 4-byte Folded Spill
; AIE2P-NEXT:    mov p7, sp
; AIE2P-NEXT:    mov p1, sp
; AIE2P-NEXT:    mova r1, #-64
; AIE2P-NEXT:    st lr, [sp, #-64] // 4-byte Folded Spill
; AIE2P-NEXT:    add r0, r0, #63
; AIE2P-NEXT:    mov p0, p1
; AIE2P-NEXT:    jl #extern_call
; AIE2P-NEXT:    padda [p7], #-64 // Delay Slot 5
; AIE2P-NEXT:    and r0, r0, r1 // Delay Slot 4
; AIE2P-NEXT:    mov m0, r0 // Delay Slot 3
; AIE2P-NEXT:    padda [p1], m0 // Delay Slot 2
; AIE2P-NEXT:    mov sp, p1 // Delay Slot 1
; AIE2P-NEXT:    nopa ; nopb ; nopx ; mov sp, p7
; AIE2P-NEXT:    lda lr, [sp, #-64] // 4-byte Folded Reload
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    lda p7, [sp, #-60] // 4-byte Folded Reload
; AIE2P-NEXT:    ret lr
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    paddxm [sp], #-64 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
;
; AIE2PS-LABEL: test_simple_dyn_alloca:
; AIE2PS:       // %bb.0: // %entry
; AIE2PS-NEXT:    paddxm [sp], #64; nopb ; nops ; nopxm ; nopv
; AIE2PS-NEXT:    mova r2, #2; nopx
; AIE2PS-NEXT:    lshl r0, r0, r2
; AIE2PS-NEXT:    st p7, [sp, #-60] // 4-byte Folded Spill
; AIE2PS-NEXT:    mov p7, sp
; AIE2PS-NEXT:    mov p1, sp
; AIE2PS-NEXT:    mova r2, #-64
; AIE2PS-NEXT:    st lr, [sp, #-64] // 4-byte Folded Spill
; AIE2PS-NEXT:    padda [p7], #-64
; AIE2PS-NEXT:    add r0, r0, #63
; AIE2PS-NEXT:    jl #extern_call
; AIE2PS-NEXT:    mov p0, p1 // Delay Slot 5
; AIE2PS-NEXT:    and r0, r0, r2 // Delay Slot 4
; AIE2PS-NEXT:    mov m0, r0 // Delay Slot 3
; AIE2PS-NEXT:    padda [p1], m0 // Delay Slot 2
; AIE2PS-NEXT:    mov sp, p1 // Delay Slot 1
; AIE2PS-NEXT:    nopa ; nopb ; nopx ; mov sp, p7; nops
; AIE2PS-NEXT:    lda lr, [sp, #-64] // 4-byte Folded Reload
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    lda p7, [sp, #-60] // 4-byte Folded Reload
; AIE2PS-NEXT:    ret lr
; AIE2PS-NEXT:    nop // Delay Slot 5
; AIE2PS-NEXT:    nop // Delay Slot 4
; AIE2PS-NEXT:    nop // Delay Slot 3
; AIE2PS-NEXT:    nop // Delay Slot 2
; AIE2PS-NEXT:    paddxm [sp], #-64 // Delay Slot 1
entry:
  %0 = trunc i32 %n to i20
  %vla = alloca i32, i20 %0, align 4
  call void @extern_call(ptr nonnull %vla)
  ret void
}

define void @test_loop_dyn_alloca(i32 noundef %n) {
; AIE2-LABEL: test_loop_dyn_alloca:
; AIE2:       // %bb.0: // %entry
; AIE2-NEXT:    nopa ; paddb [sp], #64; nopxm
; AIE2-NEXT:    st p7, [sp, #-32] // 4-byte Folded Spill
; AIE2-NEXT:    mov p7, sp
; AIE2-NEXT:    st r16, [sp, #-60] // 4-byte Folded Spill
; AIE2-NEXT:    mova r16, #1
; AIE2-NEXT:    st r17, [sp, #-56] // 4-byte Folded Spill
; AIE2-NEXT:    mova r17, #0
; AIE2-NEXT:    st r18, [sp, #-52] // 4-byte Folded Spill
; AIE2-NEXT:    mova r18, #10
; AIE2-NEXT:    st r19, [sp, #-48] // 4-byte Folded Spill
; AIE2-NEXT:    mova r19, #2
; AIE2-NEXT:    st r20, [sp, #-44] // 4-byte Folded Spill
; AIE2-NEXT:    mova r20, #-32
; AIE2-NEXT:    st r21, [sp, #-40] // 4-byte Folded Spill
; AIE2-NEXT:    mova r21, #0
; AIE2-NEXT:    st lr, [sp, #-64] // 4-byte Folded Spill
; AIE2-NEXT:    st p6, [sp, #-36] // 4-byte Folded Spill
; AIE2-NEXT:    padda [p7], #-64
; AIE2-NEXT:  .LBB1_1: // %for.body
; AIE2-NEXT:    // =>This Inner Loop Header: Depth=1
; AIE2-NEXT:    nopa ; nopx ; mov p6, sp
; AIE2-NEXT:    mov p1, sp
; AIE2-NEXT:    lshl r0, r17, r19
; AIE2-NEXT:    add r0, r0, #31
; AIE2-NEXT:    jl #extern_call
; AIE2-NEXT:    mov p0, p1 // Delay Slot 5
; AIE2-NEXT:    and r0, r0, r20 // Delay Slot 4
; AIE2-NEXT:    mov m0, r0 // Delay Slot 3
; AIE2-NEXT:    paddb [p1], m0 // Delay Slot 2
; AIE2-NEXT:    mov sp, p1 // Delay Slot 1
; AIE2-NEXT:    nopa ; add r17, r17, #1
; AIE2-NEXT:    ltu r0, r17, r16
; AIE2-NEXT:    add r21, r21, r0
; AIE2-NEXT:    xor r0, r17, r18
; AIE2-NEXT:    or r0, r0, r21
; AIE2-NEXT:    jnz r0, #.LBB1_1
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    nop // Delay Slot 2
; AIE2-NEXT:    mov sp, p6 // Delay Slot 1
; AIE2-NEXT:  // %bb.2: // %for.cond.cleanup
; AIE2-NEXT:    mov sp, p7
; AIE2-NEXT:    lda p7, [sp, #-32] // 4-byte Folded Reload
; AIE2-NEXT:    lda p6, [sp, #-36] // 4-byte Folded Reload
; AIE2-NEXT:    lda lr, [sp, #-64] // 4-byte Folded Reload
; AIE2-NEXT:    lda r21, [sp, #-40] // 4-byte Folded Reload
; AIE2-NEXT:    lda r20, [sp, #-44] // 4-byte Folded Reload
; AIE2-NEXT:    lda r19, [sp, #-48] // 4-byte Folded Reload
; AIE2-NEXT:    lda r18, [sp, #-52] // 4-byte Folded Reload
; AIE2-NEXT:    lda r17, [sp, #-56] // 4-byte Folded Reload
; AIE2-NEXT:    lda r16, [sp, #-60] // 4-byte Folded Reload
; AIE2-NEXT:    ret lr
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    nop // Delay Slot 2
; AIE2-NEXT:    paddb [sp], #-64 // Delay Slot 1
;
; AIE2P-LABEL: test_loop_dyn_alloca:
; AIE2P:       // %bb.0: // %entry
; AIE2P-NEXT:    nopa ; nopb ; paddxm [sp], #64
; AIE2P-NEXT:    st p7, [sp, #-32] // 4-byte Folded Spill
; AIE2P-NEXT:    mov p7, sp
; AIE2P-NEXT:    st r8, [sp, #-60] // 4-byte Folded Spill
; AIE2P-NEXT:    mova r8, #1
; AIE2P-NEXT:    st r9, [sp, #-56] // 4-byte Folded Spill
; AIE2P-NEXT:    mova r9, #0
; AIE2P-NEXT:    st r10, [sp, #-52] // 4-byte Folded Spill
; AIE2P-NEXT:    mova r10, #10
; AIE2P-NEXT:    st r11, [sp, #-48] // 4-byte Folded Spill
; AIE2P-NEXT:    mova r11, #2
; AIE2P-NEXT:    st r12, [sp, #-44] // 4-byte Folded Spill
; AIE2P-NEXT:    mova r12, #-64
; AIE2P-NEXT:    st r13, [sp, #-40] // 4-byte Folded Spill
; AIE2P-NEXT:    mova r13, #0
; AIE2P-NEXT:    st lr, [sp, #-64] // 4-byte Folded Spill
; AIE2P-NEXT:    st p6, [sp, #-36] // 4-byte Folded Spill
; AIE2P-NEXT:    padda [p7], #-64
; AIE2P-NEXT:  .LBB1_1: // %for.body
; AIE2P-NEXT:    // =>This Inner Loop Header: Depth=1
; AIE2P-NEXT:    nopa ; lshl r0, r9, r11; nopm
; AIE2P-NEXT:    mov p6, sp
; AIE2P-NEXT:    mov p1, sp
; AIE2P-NEXT:    add r0, r0, #63
; AIE2P-NEXT:    jl #extern_call
; AIE2P-NEXT:    mov p0, p1 // Delay Slot 5
; AIE2P-NEXT:    and r0, r0, r12 // Delay Slot 4
; AIE2P-NEXT:    mov m0, r0 // Delay Slot 3
; AIE2P-NEXT:    padda [p1], m0 // Delay Slot 2
; AIE2P-NEXT:    mov sp, p1 // Delay Slot 1
; AIE2P-NEXT:    add r9, r9, #1
; AIE2P-NEXT:    ltu r0, r9, r8
; AIE2P-NEXT:    add r13, r13, r0
; AIE2P-NEXT:    xor r0, r9, r10
; AIE2P-NEXT:    or r0, r0, r13
; AIE2P-NEXT:    jnz r0, #.LBB1_1
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    nop // Delay Slot 2
; AIE2P-NEXT:    mov sp, p6 // Delay Slot 1
; AIE2P-NEXT:  // %bb.2: // %for.cond.cleanup
; AIE2P-NEXT:    mov sp, p7
; AIE2P-NEXT:    lda p7, [sp, #-32] // 4-byte Folded Reload
; AIE2P-NEXT:    lda p6, [sp, #-36] // 4-byte Folded Reload
; AIE2P-NEXT:    lda lr, [sp, #-64] // 4-byte Folded Reload
; AIE2P-NEXT:    lda r13, [sp, #-40] // 4-byte Folded Reload
; AIE2P-NEXT:    lda r12, [sp, #-44] // 4-byte Folded Reload
; AIE2P-NEXT:    lda r11, [sp, #-48] // 4-byte Folded Reload
; AIE2P-NEXT:    lda r10, [sp, #-52] // 4-byte Folded Reload
; AIE2P-NEXT:    lda r9, [sp, #-56] // 4-byte Folded Reload
; AIE2P-NEXT:    lda r8, [sp, #-60] // 4-byte Folded Reload
; AIE2P-NEXT:    ret lr
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    paddxm [sp], #-64 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
;
; AIE2PS-LABEL: test_loop_dyn_alloca:
; AIE2PS:       // %bb.0: // %entry
; AIE2PS-NEXT:    paddxm [sp], #64
; AIE2PS-NEXT:    st p7, [sp, #-28] // 4-byte Folded Spill
; AIE2PS-NEXT:    mov p7, sp
; AIE2PS-NEXT:    st r9:r8, [sp, #-56] // 8-byte Folded Spill
; AIE2PS-NEXT:    mova r8, #0
; AIE2PS-NEXT:    st r11:r10, [sp, #-48] // 8-byte Folded Spill
; AIE2PS-NEXT:    mova r10, #2
; AIE2PS-NEXT:    st r12, [sp, #-40] // 4-byte Folded Spill
; AIE2PS-NEXT:    mova r12, #-64
; AIE2PS-NEXT:    st r14, [sp, #-36] // 4-byte Folded Spill
; AIE2PS-NEXT:    mova r14, #1
; AIE2PS-NEXT:    mova r9, #10
; AIE2PS-NEXT:    mova r11, #0
; AIE2PS-NEXT:    st lr, [sp, #-64] // 4-byte Folded Spill
; AIE2PS-NEXT:    st p6, [sp, #-32] // 4-byte Folded Spill
; AIE2PS-NEXT:    padda [p7], #-64
; AIE2PS-NEXT:  .LBB1_1: // %for.body
; AIE2PS-NEXT:    // =>This Inner Loop Header: Depth=1
; AIE2PS-NEXT:    nopa ; lshl r0, r8, r10; nopm
; AIE2PS-NEXT:    mov p6, sp
; AIE2PS-NEXT:    mov p1, sp
; AIE2PS-NEXT:    add r0, r0, #63
; AIE2PS-NEXT:    jl #extern_call
; AIE2PS-NEXT:    mov p0, p1 // Delay Slot 5
; AIE2PS-NEXT:    and r0, r0, r12 // Delay Slot 4
; AIE2PS-NEXT:    mov m0, r0 // Delay Slot 3
; AIE2PS-NEXT:    padda [p1], m0 // Delay Slot 2
; AIE2PS-NEXT:    mov sp, p1 // Delay Slot 1
; AIE2PS-NEXT:    nopa ; nopb ; add r8, r8, #1; nopm ; nops
; AIE2PS-NEXT:    ltu r0, r8, r14
; AIE2PS-NEXT:    add r11, r11, r0
; AIE2PS-NEXT:    xor r0, r8, r9
; AIE2PS-NEXT:    or r0, r0, r11
; AIE2PS-NEXT:    jnz r0, #.LBB1_1
; AIE2PS-NEXT:    nop // Delay Slot 5
; AIE2PS-NEXT:    nop // Delay Slot 4
; AIE2PS-NEXT:    nop // Delay Slot 3
; AIE2PS-NEXT:    nop // Delay Slot 2
; AIE2PS-NEXT:    mov sp, p6 // Delay Slot 1
; AIE2PS-NEXT:  // %bb.2: // %for.cond.cleanup
; AIE2PS-NEXT:    mov sp, p7
; AIE2PS-NEXT:    lda lr, [sp, #-64] // 4-byte Folded Reload
; AIE2PS-NEXT:    lda p7, [sp, #-28] // 4-byte Folded Reload
; AIE2PS-NEXT:    lda p6, [sp, #-32] // 4-byte Folded Reload
; AIE2PS-NEXT:    lda r14, [sp, #-36] // 4-byte Folded Reload
; AIE2PS-NEXT:    lda r12, [sp, #-40] // 4-byte Folded Reload
; AIE2PS-NEXT:    lda r11:r10, [sp, #-48] // 8-byte Folded Reload
; AIE2PS-NEXT:    lda r9:r8, [sp, #-56] // 8-byte Folded Reload
; AIE2PS-NEXT:    ret lr
; AIE2PS-NEXT:    nop // Delay Slot 5
; AIE2PS-NEXT:    nop // Delay Slot 4
; AIE2PS-NEXT:    nop // Delay Slot 3
; AIE2PS-NEXT:    nop // Delay Slot 2
; AIE2PS-NEXT:    paddxm [sp], #-64 // Delay Slot 1
entry:
  br label %for.body

for.cond.cleanup:
  ret void

for.body:
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %0 = call ptr @llvm.stacksave()
  %vla = alloca i32, i64 %indvars.iv, align 4
  call void @extern_call(ptr noundef nonnull %vla)
  call void @llvm.stackrestore(ptr %0)
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 10
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

define  void @test_huge_stack(i32 noundef %n) #0 {
; AIE2-LABEL: test_huge_stack:
; AIE2:       // %bb.0: // %entry
; AIE2-NEXT:    nopa ; paddb [sp], #40032; nopxm ; nops
; AIE2-NEXT:    movxm m0, #-40032
; AIE2-NEXT:    mova r1, #0
; AIE2-NEXT:    mova r2, #2
; AIE2-NEXT:    mova r3, #-32
; AIE2-NEXT:    st p7, [sp, #-4] // 4-byte Folded Spill
; AIE2-NEXT:    mov p7, sp
; AIE2-NEXT:    mov p1, sp
; AIE2-NEXT:    st lr, [sp, #-16] // 4-byte Folded Spill
; AIE2-NEXT:    st r16, [sp, #-12] // 4-byte Folded Spill
; AIE2-NEXT:    st p6, [sp, #-8] // 4-byte Folded Spill
; AIE2-NEXT:    padda [p7], m0
; AIE2-NEXT:    mov p0, p7
; AIE2-NEXT:    mov p3, p7
; AIE2-NEXT:    mov p2, p7
; AIE2-NEXT:    mov p6, p7
; AIE2-NEXT:    paddb [p3], #-24
; AIE2-NEXT:    paddb [p0], #-20
; AIE2-NEXT:    st r0, [p0, #0]
; AIE2-NEXT:    lda r0, [p0, #0]
; AIE2-NEXT:    paddb [p2], #-32
; AIE2-NEXT:    mov r16, p3
; AIE2-NEXT:    st r1, [p2, #4]
; AIE2-NEXT:    mov p0, sp
; AIE2-NEXT:    st p0, [p3, #0]
; AIE2-NEXT:    mov p0, p1
; AIE2-NEXT:    lshl r2, r0, r2
; AIE2-NEXT:    st r0, [p2, #0]
; AIE2-NEXT:    add r2, r2, #31
; AIE2-NEXT:    and r2, r2, r3
; AIE2-NEXT:    jl #extern_call
; AIE2-NEXT:    mov m0, r2 // Delay Slot 5
; AIE2-NEXT:    paddb [p1], m0 // Delay Slot 4
; AIE2-NEXT:    movxm m0, #-40032 // Delay Slot 3
; AIE2-NEXT:    paddb [p6], m0 // Delay Slot 2
; AIE2-NEXT:    mov sp, p1 // Delay Slot 1
; AIE2-NEXT:    nopb ; nopa ; nops ; jl #extern_call; nopv
; AIE2-NEXT:    nopa ; nopx // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    nop // Delay Slot 2
; AIE2-NEXT:    mov p0, p6 // Delay Slot 1
; AIE2-NEXT:    nopb ; nopa ; nops ; nopx ; mov p0, r16; nopv
; AIE2-NEXT:    lda p0, [p0, #0]; nopx
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    mov sp, p0
; AIE2-NEXT:    mov sp, p7
; AIE2-NEXT:    lda lr, [sp, #-16] // 4-byte Folded Reload
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    lda p7, [sp, #-4] // 4-byte Folded Reload
; AIE2-NEXT:    lda p6, [sp, #-8] // 4-byte Folded Reload
; AIE2-NEXT:    lda r16, [sp, #-12] // 4-byte Folded Reload
; AIE2-NEXT:    ret lr
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    nop // Delay Slot 2
; AIE2-NEXT:    paddb [sp], #-40032 // Delay Slot 1
;
; AIE2P-LABEL: test_huge_stack:
; AIE2P:       // %bb.0: // %entry
; AIE2P-NEXT:    nopa ; nopb ; nops ; movxm m0, #-40064; nopv
; AIE2P-NEXT:    mova r1, #0; nopx
; AIE2P-NEXT:    mova r2, #2
; AIE2P-NEXT:    mova r3, #-64
; AIE2P-NEXT:    paddxm [sp], #40064
; AIE2P-NEXT:    st p7, [sp, #-20] // 4-byte Folded Spill
; AIE2P-NEXT:    mov p7, sp
; AIE2P-NEXT:    mov p1, sp
; AIE2P-NEXT:    st lr, [sp, #-32] // 4-byte Folded Spill
; AIE2P-NEXT:    st r8, [sp, #-28] // 4-byte Folded Spill
; AIE2P-NEXT:    st p6, [sp, #-24] // 4-byte Folded Spill
; AIE2P-NEXT:    padda [p7], m0
; AIE2P-NEXT:    mova m0, #-36
; AIE2P-NEXT:    mov p0, p7
; AIE2P-NEXT:    mov p3, p7
; AIE2P-NEXT:    mov p2, p7
; AIE2P-NEXT:    mov p6, p7
; AIE2P-NEXT:    padda [p0], m0
; AIE2P-NEXT:    mova m0, #-40
; AIE2P-NEXT:    padda [p3], m0
; AIE2P-NEXT:    mova m0, #-48
; AIE2P-NEXT:    st r0, [p0, #0]
; AIE2P-NEXT:    lda r0, [p0, #0]
; AIE2P-NEXT:    mov p0, sp
; AIE2P-NEXT:    mov r8, p3
; AIE2P-NEXT:    padda [p2], m0
; AIE2P-NEXT:    st p0, [p3, #0]
; AIE2P-NEXT:    mov p0, p1
; AIE2P-NEXT:    st r1, [p2, #4]
; AIE2P-NEXT:    lshl r2, r0, r2
; AIE2P-NEXT:    st r0, [p2, #0]
; AIE2P-NEXT:    add r2, r2, #63
; AIE2P-NEXT:    and r2, r2, r3
; AIE2P-NEXT:    jl #extern_call
; AIE2P-NEXT:    mov m0, r2 // Delay Slot 5
; AIE2P-NEXT:    padda [p1], m0 // Delay Slot 4
; AIE2P-NEXT:    movxm m0, #-40048 // Delay Slot 3
; AIE2P-NEXT:    padda [p6], m0 // Delay Slot 2
; AIE2P-NEXT:    mov sp, p1 // Delay Slot 1
; AIE2P-NEXT:    nopa ; nopb ; nops ; jl #extern_call; nopv
; AIE2P-NEXT:    nopa ; nopx // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    nop // Delay Slot 2
; AIE2P-NEXT:    mov p0, p6 // Delay Slot 1
; AIE2P-NEXT:    nopa ; nopb ; nops ; nopx ; mov p0, r8; nopv
; AIE2P-NEXT:    lda p0, [p0, #0]
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    mov sp, p0
; AIE2P-NEXT:    mov sp, p7
; AIE2P-NEXT:    lda lr, [sp, #-32] // 4-byte Folded Reload
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    lda p7, [sp, #-20] // 4-byte Folded Reload
; AIE2P-NEXT:    lda p6, [sp, #-24] // 4-byte Folded Reload
; AIE2P-NEXT:    lda r8, [sp, #-28] // 4-byte Folded Reload
; AIE2P-NEXT:    ret lr
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    paddxm [sp], #-40064 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
;
; AIE2PS-LABEL: test_huge_stack:
; AIE2PS:       // %bb.0: // %entry
; AIE2PS-NEXT:    paddxm [sp], #40064; nopxm
; AIE2PS-NEXT:    movxm m0, #-40064
; AIE2PS-NEXT:    mova r1, #0
; AIE2PS-NEXT:    mova r2, #2
; AIE2PS-NEXT:    mova r4, #-64
; AIE2PS-NEXT:    mov p0, sp
; AIE2PS-NEXT:    mov p1, sp
; AIE2PS-NEXT:    st lr, [sp, #-32] // 4-byte Folded Spill
; AIE2PS-NEXT:    st p7, [sp, #-24] // 4-byte Folded Spill
; AIE2PS-NEXT:    mov p7, sp
; AIE2PS-NEXT:    padda [p7], m0
; AIE2PS-NEXT:    mova m0, #-36
; AIE2PS-NEXT:    mov p2, p7
; AIE2PS-NEXT:    padda [p2], m0
; AIE2PS-NEXT:    st r0, [p2, #0]
; AIE2PS-NEXT:    lda r0, [p2, #0]
; AIE2PS-NEXT:    st p6, [sp, #-28] // 4-byte Folded Spill
; AIE2PS-NEXT:    mov p6, p7
; AIE2PS-NEXT:    mova m0, #-40
; AIE2PS-NEXT:    padda [p6], m0
; AIE2PS-NEXT:    st p0, [p6, #0]
; AIE2PS-NEXT:    mov p0, p1
; AIE2PS-NEXT:    lshl r2, r0, r2
; AIE2PS-NEXT:    add r2, r2, #63
; AIE2PS-NEXT:    and r2, r2, r4
; AIE2PS-NEXT:    mov m0, r2
; AIE2PS-NEXT:    padda [p1], m0
; AIE2PS-NEXT:    mova m0, #-48
; AIE2PS-NEXT:    jl #extern_call
; AIE2PS-NEXT:    mov sp, p1 // Delay Slot 5
; AIE2PS-NEXT:    mov p1, p7 // Delay Slot 4
; AIE2PS-NEXT:    padda [p1], m0 // Delay Slot 3
; AIE2PS-NEXT:    st r1:r0, [p1, #0] // Delay Slot 2
; AIE2PS-NEXT:    nop // Delay Slot 1
; AIE2PS-NEXT:    nopa ; nopb ; jl #extern_call; nops
; AIE2PS-NEXT:    nop // Delay Slot 5
; AIE2PS-NEXT:    nop // Delay Slot 4
; AIE2PS-NEXT:    mov p0, p7 // Delay Slot 3
; AIE2PS-NEXT:    movxm m0, #-40048 // Delay Slot 2
; AIE2PS-NEXT:    padda [p0], m0 // Delay Slot 1
; AIE2PS-NEXT:    lda p0, [p6, #0]; nopb ; nopx
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    mov sp, p0
; AIE2PS-NEXT:    mov sp, p7
; AIE2PS-NEXT:    lda lr, [sp, #-32] // 4-byte Folded Reload
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    lda p7, [sp, #-24] // 4-byte Folded Reload
; AIE2PS-NEXT:    lda p6, [sp, #-28] // 4-byte Folded Reload
; AIE2PS-NEXT:    ret lr
; AIE2PS-NEXT:    nop // Delay Slot 5
; AIE2PS-NEXT:    nop // Delay Slot 4
; AIE2PS-NEXT:    nop // Delay Slot 3
; AIE2PS-NEXT:    nop // Delay Slot 2
; AIE2PS-NEXT:    paddxm [sp], #-40064 // Delay Slot 1
entry:
  %n.addr = alloca i32, align 4
  %t = alloca [10000 x i32], align 16
  %saved_stack = alloca ptr, align 8
  %__vla_expr0 = alloca i64, align 8
  store i32 %n, ptr %n.addr, align 4
  %0 = load i32, ptr %n.addr, align 4
  %1 = zext i32 %0 to i64
  %2 = call ptr @llvm.stacksave()
  store ptr %2, ptr %saved_stack, align 8
  %vla = alloca i32, i64 %1, align 16
  store i64 %1, ptr %__vla_expr0, align 8
  call void @extern_call(ptr noundef %vla)
  %arraydecay = getelementptr inbounds [10000 x i32], ptr %t, i64 0, i64 0
  call void @extern_call(ptr noundef %arraydecay)
  %3 = load ptr, ptr %saved_stack, align 8
  call void @llvm.stackrestore(ptr %3)
  ret void
}

declare void @extern_call(ptr)
declare ptr @llvm.stacksave() #0
declare void @llvm.stackrestore(ptr) #0

attributes #0 = { mustprogress nocallback nofree nosync nounwind willreturn }
