; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -O2 -mtriple=aie2 --issue-limit=1 %s -o - | FileCheck %s --check-prefix=AIE2
; RUN: llc -O2 -mtriple=aie2p --issue-limit=1 %s -o - | FileCheck %s --check-prefix=AIE2P

; 64-bit vectors
define <2 x i32> @insert_v2i32(<2 x i32> %v, i32 %e) nounwind {
; AIE2-LABEL: insert_v2i32:
; AIE2:       // %bb.0:
; AIE2-NEXT:    nopb ; nopa ; nops ; ret lr ; nopm ; nopv
; AIE2-NEXT:    nopx // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    mov r16, r18 // Delay Slot 3
; AIE2-NEXT:    mov r17, r0 // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: insert_v2i32:
; AIE2P:       // %bb.0:
; AIE2P-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; AIE2P-NEXT:    nopx // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    mov r0, r2 // Delay Slot 3
; AIE2P-NEXT:    mov r1, r4 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
  %1 = insertelement <2 x i32> %v, i32 %e, i32 1
  ret <2 x i32> %1
}

define <2 x i32> @insert_v2i32_dyn(<2 x i32> %v, i32 %e, i32 %idx) nounwind {
; AIE2-LABEL: insert_v2i32_dyn:
; AIE2:       // %bb.0:
; AIE2-NEXT:    nopb ; nopa ; nops ; ret lr ; nopm ; nopv
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    mov r27, r1 // Delay Slot 4
; AIE2-NEXT:    sel.nez r16, r18, r0, r27 // Delay Slot 3
; AIE2-NEXT:    sel.nez r17, r0, r19, r27 // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: insert_v2i32_dyn:
; AIE2P:       // %bb.0:
; AIE2P-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    mov r27, r5 // Delay Slot 4
; AIE2P-NEXT:    sel.nez r0, r2, r4, r27 // Delay Slot 3
; AIE2P-NEXT:    sel.nez r1, r4, r3, r27 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
  %1 = insertelement <2 x i32> %v, i32 %e, i32 %idx
  ret <2 x i32> %1
}

; 256-bit vectors
define <32 x i8> @insert_v32i8(<32 x i8> %v, i8 %e) nounwind {
; AIE2-LABEL: insert_v32i8:
; AIE2:       // %bb.0:
; AIE2-NEXT:    nopb ; nopa ; nops ; ret lr ; nopm ; nopv
; AIE2-NEXT:    nopx // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    mova r29, #1 // Delay Slot 3
; AIE2-NEXT:    vinsert.8 x0, x2, r29, r0 // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: insert_v32i8:
; AIE2P:       // %bb.0:
; AIE2P-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; AIE2P-NEXT:    nopx // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    mova r29, #1 // Delay Slot 3
; AIE2P-NEXT:    vinsert.8 x0, x2, r29, r0 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
  %1 = insertelement <32 x i8> %v, i8 %e, i32 1
  ret <32 x i8> %1
}

define <32 x i8> @insert_v32i8_dyn(<32 x i8> %v, i8 %e, i32 %idx) nounwind {
; AIE2-LABEL: insert_v32i8_dyn:
; AIE2:       // %bb.0:
; AIE2-NEXT:    nopb ; nopa ; nops ; ret lr ; nopm ; nopv
; AIE2-NEXT:    nopx // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    mov r29, r1 // Delay Slot 3
; AIE2-NEXT:    vinsert.8 x0, x2, r29, r0 // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: insert_v32i8_dyn:
; AIE2P:       // %bb.0:
; AIE2P-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; AIE2P-NEXT:    nopx // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    mov r29, r1 // Delay Slot 3
; AIE2P-NEXT:    vinsert.8 x0, x2, r29, r0 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
  %1 = insertelement <32 x i8> %v, i8 %e, i32 %idx
  ret <32 x i8> %1
}

define <16 x i16> @insert_v16i16(<16 x i16> %v, i16 %e) nounwind {
; AIE2-LABEL: insert_v16i16:
; AIE2:       // %bb.0:
; AIE2-NEXT:    nopb ; nopa ; nops ; ret lr ; nopm ; nopv
; AIE2-NEXT:    nopx // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    mova r29, #11 // Delay Slot 3
; AIE2-NEXT:    vinsert.16 x0, x2, r29, r0 // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: insert_v16i16:
; AIE2P:       // %bb.0:
; AIE2P-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; AIE2P-NEXT:    nopx // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    mova r29, #11 // Delay Slot 3
; AIE2P-NEXT:    vinsert.16 x0, x2, r29, r0 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
  %1 = insertelement <16 x i16> %v, i16 %e, i32 11
  ret <16 x i16> %1
}

define <16 x i16> @insert_v16i16_dyn(<16 x i16> %v, i16 %e, i32 %idx) nounwind {
; AIE2-LABEL: insert_v16i16_dyn:
; AIE2:       // %bb.0:
; AIE2-NEXT:    nopb ; nopa ; nops ; ret lr ; nopm ; nopv
; AIE2-NEXT:    nopx // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    mov r29, r1 // Delay Slot 3
; AIE2-NEXT:    vinsert.16 x0, x2, r29, r0 // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: insert_v16i16_dyn:
; AIE2P:       // %bb.0:
; AIE2P-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; AIE2P-NEXT:    nopx // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    mov r29, r1 // Delay Slot 3
; AIE2P-NEXT:    vinsert.16 x0, x2, r29, r0 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
  %1 = insertelement <16 x i16> %v, i16 %e, i32 %idx
  ret <16 x i16> %1
}

define <8 x i32> @insert_v8i32(<8 x i32> %v, i32 %e) nounwind {
; AIE2-LABEL: insert_v8i32:
; AIE2:       // %bb.0:
; AIE2-NEXT:    nopb ; nopa ; nops ; ret lr ; nopm ; nopv
; AIE2-NEXT:    nopx // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    mova r29, #7 // Delay Slot 3
; AIE2-NEXT:    vinsert.32 x0, x2, r29, r0 // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: insert_v8i32:
; AIE2P:       // %bb.0:
; AIE2P-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; AIE2P-NEXT:    nopx // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    mova r29, #7 // Delay Slot 3
; AIE2P-NEXT:    vinsert.32 x0, x2, r29, r0 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
  %1 = insertelement <8 x i32> %v, i32 %e, i32 7
  ret <8 x i32> %1
}

define <8 x i32> @insert_v8i32_dyn(<8 x i32> %v, i32 %e, i32 %idx) nounwind {
; AIE2-LABEL: insert_v8i32_dyn:
; AIE2:       // %bb.0:
; AIE2-NEXT:    nopb ; nopa ; nops ; ret lr ; nopm ; nopv
; AIE2-NEXT:    nopx // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    mov r29, r1 // Delay Slot 3
; AIE2-NEXT:    vinsert.32 x0, x2, r29, r0 // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: insert_v8i32_dyn:
; AIE2P:       // %bb.0:
; AIE2P-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; AIE2P-NEXT:    nopx // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    mov r29, r1 // Delay Slot 3
; AIE2P-NEXT:    vinsert.32 x0, x2, r29, r0 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
  %1 = insertelement <8 x i32> %v, i32 %e, i32 %idx
  ret <8 x i32> %1
}

; 512-bit vectors
define <64 x i8> @insert_v64i8(<64 x i8> %v, i8 %e) nounwind {
; AIE2-LABEL: insert_v64i8:
; AIE2:       // %bb.0:
; AIE2-NEXT:    nopb ; nopa ; nops ; ret lr ; nopm ; nopv
; AIE2-NEXT:    nopx // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    mova r29, #1 // Delay Slot 3
; AIE2-NEXT:    vinsert.8 x0, x2, r29, r0 // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: insert_v64i8:
; AIE2P:       // %bb.0:
; AIE2P-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; AIE2P-NEXT:    nopx // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    mova r29, #1 // Delay Slot 3
; AIE2P-NEXT:    vinsert.8 x0, x2, r29, r0 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
  %1 = insertelement <64 x i8> %v, i8 %e, i32 1
  ret <64 x i8> %1
}

define <64 x i8> @insert_v64i8_dyn(<64 x i8> %v, i8 %e, i32 %idx) nounwind {
; AIE2-LABEL: insert_v64i8_dyn:
; AIE2:       // %bb.0:
; AIE2-NEXT:    nopb ; nopa ; nops ; ret lr ; nopm ; nopv
; AIE2-NEXT:    nopx // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    mov r29, r1 // Delay Slot 3
; AIE2-NEXT:    vinsert.8 x0, x2, r29, r0 // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: insert_v64i8_dyn:
; AIE2P:       // %bb.0:
; AIE2P-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; AIE2P-NEXT:    nopx // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    mov r29, r1 // Delay Slot 3
; AIE2P-NEXT:    vinsert.8 x0, x2, r29, r0 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
  %1 = insertelement <64 x i8> %v, i8 %e, i32 %idx
  ret <64 x i8> %1
}

define <32 x i16> @insert_v32i16(<32 x i16> %v, i16 %e) nounwind {
; AIE2-LABEL: insert_v32i16:
; AIE2:       // %bb.0:
; AIE2-NEXT:    nopb ; nopa ; nops ; ret lr ; nopm ; nopv
; AIE2-NEXT:    nopx // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    mova r29, #11 // Delay Slot 3
; AIE2-NEXT:    vinsert.16 x0, x2, r29, r0 // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: insert_v32i16:
; AIE2P:       // %bb.0:
; AIE2P-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; AIE2P-NEXT:    nopx // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    mova r29, #11 // Delay Slot 3
; AIE2P-NEXT:    vinsert.16 x0, x2, r29, r0 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
  %1 = insertelement <32 x i16> %v, i16 %e, i32 11
  ret <32 x i16> %1
}

define <32 x i16> @insert_v32i16_dyn(<32 x i16> %v, i16 %e, i32 %idx) nounwind {
; AIE2-LABEL: insert_v32i16_dyn:
; AIE2:       // %bb.0:
; AIE2-NEXT:    nopb ; nopa ; nops ; ret lr ; nopm ; nopv
; AIE2-NEXT:    nopx // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    mov r29, r1 // Delay Slot 3
; AIE2-NEXT:    vinsert.16 x0, x2, r29, r0 // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: insert_v32i16_dyn:
; AIE2P:       // %bb.0:
; AIE2P-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; AIE2P-NEXT:    nopx // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    mov r29, r1 // Delay Slot 3
; AIE2P-NEXT:    vinsert.16 x0, x2, r29, r0 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
  %1 = insertelement <32 x i16> %v, i16 %e, i32 %idx
  ret <32 x i16> %1
}

define <16 x i32> @insert_v16i32(<16 x i32> %v, i32 %e) nounwind {
; AIE2-LABEL: insert_v16i32:
; AIE2:       // %bb.0:
; AIE2-NEXT:    nopb ; nopa ; nops ; ret lr ; nopm ; nopv
; AIE2-NEXT:    nopx // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    mova r29, #7 // Delay Slot 3
; AIE2-NEXT:    vinsert.32 x0, x2, r29, r0 // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: insert_v16i32:
; AIE2P:       // %bb.0:
; AIE2P-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; AIE2P-NEXT:    nopx // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    mova r29, #7 // Delay Slot 3
; AIE2P-NEXT:    vinsert.32 x0, x2, r29, r0 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
  %1 = insertelement <16 x i32> %v, i32 %e, i32 7
  ret <16 x i32> %1
}

define <16 x i32> @insert_v16i32_dyn(<16 x i32> %v, i32 %e, i32 %idx) nounwind {
; AIE2-LABEL: insert_v16i32_dyn:
; AIE2:       // %bb.0:
; AIE2-NEXT:    nopb ; nopa ; nops ; ret lr ; nopm ; nopv
; AIE2-NEXT:    nopx // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    mov r29, r1 // Delay Slot 3
; AIE2-NEXT:    vinsert.32 x0, x2, r29, r0 // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: insert_v16i32_dyn:
; AIE2P:       // %bb.0:
; AIE2P-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; AIE2P-NEXT:    nopx // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    mov r29, r1 // Delay Slot 3
; AIE2P-NEXT:    vinsert.32 x0, x2, r29, r0 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
  %1 = insertelement <16 x i32> %v, i32 %e, i32 %idx
  ret <16 x i32> %1
}

; 1024-bit vectors
define <128 x i8> @insert_v128i8(<128 x i8> %v, i8 %e) nounwind {
; AIE2-LABEL: insert_v128i8:
; AIE2:       // %bb.0:
; AIE2-NEXT:    nopa ; nopb ; ret lr ; nopm ; nops
; AIE2-NEXT:    mova r29, #1 // Delay Slot 5
; AIE2-NEXT:    vmov x4, x6 // Delay Slot 4
; AIE2-NEXT:    vmov x5, x7 // Delay Slot 3
; AIE2-NEXT:    vinsert.8 x4, x4, r29, r0 // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: insert_v128i8:
; AIE2P:       // %bb.0:
; AIE2P-NEXT:    nopa ; nopb ; ret lr; nopm ; nops
; AIE2P-NEXT:    mova r29, #1 // Delay Slot 5
; AIE2P-NEXT:    vmov x4, x6 // Delay Slot 4
; AIE2P-NEXT:    vmov x5, x7 // Delay Slot 3
; AIE2P-NEXT:    vinsert.8 x4, x4, r29, r0 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
  %1 = insertelement <128 x i8> %v, i8 %e, i32 1
  ret <128 x i8> %1
}

define <128 x i8> @insert_v128i8_dyn(<128 x i8> %v, i8 %e, i32 %idx) nounwind {
; AIE2-LABEL: insert_v128i8_dyn:
; AIE2:       // %bb.0:
; AIE2-NEXT:    nopa ; paddb [sp], #128; nopxm
; AIE2-NEXT:    mova r2, #127
; AIE2-NEXT:    mov p0, sp
; AIE2-NEXT:    and r1, r1, r2
; AIE2-NEXT:    paddb [p0], #-128
; AIE2-NEXT:    mov dj0, r1
; AIE2-NEXT:    vst wh7, [p0, #96]
; AIE2-NEXT:    vst wl7, [p0, #64]
; AIE2-NEXT:    vst wh6, [p0, #32]
; AIE2-NEXT:    vst wl6, [p0, #0]
; AIE2-NEXT:    st.s8 r0, [p0, dj0]
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    vldb wh5, [p0, #96]
; AIE2-NEXT:    vldb wl5, [p0, #64]
; AIE2-NEXT:    vldb wh4, [p0, #32]
; AIE2-NEXT:    vldb wl4, [p0, #0]
; AIE2-NEXT:    ret lr
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    paddb [sp], #-128 // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: insert_v128i8_dyn:
; AIE2P:       // %bb.0:
; AIE2P-NEXT:    mova r2, #127; nopb ; nopx
; AIE2P-NEXT:    paddxm [sp], #128
; AIE2P-NEXT:    mov p0, sp
; AIE2P-NEXT:    and r1, r1, r2
; AIE2P-NEXT:    mov dj0, r1
; AIE2P-NEXT:    padda [p0], #-128
; AIE2P-NEXT:    vst x7, [p0, #64]
; AIE2P-NEXT:    vst x6, [p0, #0]
; AIE2P-NEXT:    st.s8 r0, [p0, dj0]
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    vldb x5, [p0, #64]
; AIE2P-NEXT:    vldb x4, [p0, #0]
; AIE2P-NEXT:    ret lr
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    paddxm [sp], #-128 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
  %1 = insertelement <128 x i8> %v, i8 %e, i32 %idx
  ret <128 x i8> %1
}

define <64 x i16> @insert_v64i16(<64 x i16> %v, i16 %e) nounwind {
; AIE2-LABEL: insert_v64i16:
; AIE2:       // %bb.0:
; AIE2-NEXT:    nopa ; nopb ; ret lr ; nopm ; nops
; AIE2-NEXT:    mova r29, #11 // Delay Slot 5
; AIE2-NEXT:    vmov x4, x6 // Delay Slot 4
; AIE2-NEXT:    vmov x5, x7 // Delay Slot 3
; AIE2-NEXT:    vinsert.16 x4, x4, r29, r0 // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: insert_v64i16:
; AIE2P:       // %bb.0:
; AIE2P-NEXT:    nopa ; nopb ; ret lr; nopm ; nops
; AIE2P-NEXT:    mova r29, #11 // Delay Slot 5
; AIE2P-NEXT:    vmov x4, x6 // Delay Slot 4
; AIE2P-NEXT:    vmov x5, x7 // Delay Slot 3
; AIE2P-NEXT:    vinsert.16 x4, x4, r29, r0 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
  %1 = insertelement <64 x i16> %v, i16 %e, i32 11
  ret <64 x i16> %1
}

define <64 x i16> @insert_v64i16_dyn(<64 x i16> %v, i16 %e, i32 %idx) nounwind {
; AIE2-LABEL: insert_v64i16_dyn:
; AIE2:       // %bb.0:
; AIE2-NEXT:    paddb [sp], #128
; AIE2-NEXT:    mova r2, #63
; AIE2-NEXT:    mov p0, sp
; AIE2-NEXT:    and r1, r1, r2
; AIE2-NEXT:    mova r2, #1
; AIE2-NEXT:    paddb [p0], #-128
; AIE2-NEXT:    lshl r1, r1, r2
; AIE2-NEXT:    mov dj0, r1
; AIE2-NEXT:    vst wh7, [p0, #96]
; AIE2-NEXT:    vst wl7, [p0, #64]
; AIE2-NEXT:    vst wh6, [p0, #32]
; AIE2-NEXT:    vst wl6, [p0, #0]
; AIE2-NEXT:    st.s16 r0, [p0, dj0]
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    vldb wh5, [p0, #96]
; AIE2-NEXT:    vldb wl5, [p0, #64]
; AIE2-NEXT:    vldb wh4, [p0, #32]
; AIE2-NEXT:    vldb wl4, [p0, #0]
; AIE2-NEXT:    ret lr
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    paddb [sp], #-128 // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: insert_v64i16_dyn:
; AIE2P:       // %bb.0:
; AIE2P-NEXT:    mova r2, #63; nopb ; nops ; nopxm ; nopv
; AIE2P-NEXT:    paddxm [sp], #128
; AIE2P-NEXT:    mov p0, sp
; AIE2P-NEXT:    and r1, r1, r2
; AIE2P-NEXT:    mova r2, #1
; AIE2P-NEXT:    lshl r1, r1, r2
; AIE2P-NEXT:    padda [p0], #-128
; AIE2P-NEXT:    mov dj0, r1
; AIE2P-NEXT:    vst x7, [p0, #64]
; AIE2P-NEXT:    vst x6, [p0, #0]
; AIE2P-NEXT:    st.s16 r0, [p0, dj0]
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    vldb x5, [p0, #64]
; AIE2P-NEXT:    vldb x4, [p0, #0]
; AIE2P-NEXT:    ret lr
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    paddxm [sp], #-128 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
  %1 = insertelement <64 x i16> %v, i16 %e, i32 %idx
  ret <64 x i16> %1
}

define <32 x i32> @insert_v32i32(<32 x i32> %v, i32 %e) nounwind {
; AIE2-LABEL: insert_v32i32:
; AIE2:       // %bb.0:
; AIE2-NEXT:    nopa ; nopb ; ret lr ; nopm ; nops
; AIE2-NEXT:    mova r29, #7 // Delay Slot 5
; AIE2-NEXT:    vmov x4, x6 // Delay Slot 4
; AIE2-NEXT:    vmov x5, x7 // Delay Slot 3
; AIE2-NEXT:    vinsert.32 x4, x4, r29, r0 // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: insert_v32i32:
; AIE2P:       // %bb.0:
; AIE2P-NEXT:    nopa ; nopb ; ret lr; nopm ; nops
; AIE2P-NEXT:    mova r29, #7 // Delay Slot 5
; AIE2P-NEXT:    vmov x4, x6 // Delay Slot 4
; AIE2P-NEXT:    vmov x5, x7 // Delay Slot 3
; AIE2P-NEXT:    vinsert.32 x4, x4, r29, r0 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
  %1 = insertelement <32 x i32> %v, i32 %e, i32 7
  ret <32 x i32> %1
}

define <32 x i32> @insert_v32i32_dyn(<32 x i32> %v, i32 %e, i32 %idx) nounwind {
; AIE2-LABEL: insert_v32i32_dyn:
; AIE2:       // %bb.0:
; AIE2-NEXT:    paddb [sp], #128; nopa ; nops ; nopxm ; nopv
; AIE2-NEXT:    mova r2, #31
; AIE2-NEXT:    mov p0, sp
; AIE2-NEXT:    and r1, r1, r2
; AIE2-NEXT:    mova r2, #2
; AIE2-NEXT:    paddb [p0], #-128
; AIE2-NEXT:    lshl r1, r1, r2
; AIE2-NEXT:    mov dj0, r1
; AIE2-NEXT:    vst wh7, [p0, #96]
; AIE2-NEXT:    vst wl7, [p0, #64]
; AIE2-NEXT:    vst wh6, [p0, #32]
; AIE2-NEXT:    vst wl6, [p0, #0]
; AIE2-NEXT:    st r0, [p0, dj0]
; AIE2-NEXT:    vldb wh5, [p0, #96]
; AIE2-NEXT:    vldb wl5, [p0, #64]
; AIE2-NEXT:    vldb wh4, [p0, #32]
; AIE2-NEXT:    vldb wl4, [p0, #0]
; AIE2-NEXT:    ret lr
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    paddb [sp], #-128 // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: insert_v32i32_dyn:
; AIE2P:       // %bb.0:
; AIE2P-NEXT:    mova r2, #31; nopb ; nopxm
; AIE2P-NEXT:    paddxm [sp], #128
; AIE2P-NEXT:    mov p0, sp
; AIE2P-NEXT:    and r1, r1, r2
; AIE2P-NEXT:    mova r2, #2
; AIE2P-NEXT:    lshl r1, r1, r2
; AIE2P-NEXT:    padda [p0], #-128
; AIE2P-NEXT:    mov dj0, r1
; AIE2P-NEXT:    vst x7, [p0, #64]
; AIE2P-NEXT:    vst x6, [p0, #0]
; AIE2P-NEXT:    st r0, [p0, dj0]
; AIE2P-NEXT:    vldb x5, [p0, #64]
; AIE2P-NEXT:    vldb x4, [p0, #0]
; AIE2P-NEXT:    ret lr
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    paddxm [sp], #-128 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
  %1 = insertelement <32 x i32> %v, i32 %e, i32 %idx
  ret <32 x i32> %1
}
