; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie2 -O0 < %s | FileCheck %s --check-prefix=AIE2-O0
; RUN: llc -mtriple=aie2 -O2 < %s | FileCheck %s --check-prefix=AIE2-O2
; RUN: llc -mtriple=aie2p -O0 < %s | FileCheck %s --check-prefix=AIE2P-O0
; RUN: llc -mtriple=aie2p -O2 < %s | FileCheck %s --check-prefix=AIE2P-O2
; RUN: llc -mtriple=aie2ps -O0 < %s | FileCheck %s --check-prefix=AIE2P-O0
; RUN: llc -mtriple=aie2ps -O2 < %s | FileCheck %s --check-prefix=AIE2P-O2

; Verify that architecturally-required delay are properly inserted at O0 and O2

define i32 @load_ptr(i8 *%a) {
; AIE2-O0-LABEL: load_ptr:
; AIE2-O0:       // %bb.0:
; AIE2-O0-NEXT:    mova m0, #1
; AIE2-O0-NEXT:    paddb [p0], m0
; AIE2-O0-NEXT:    lda.s8 r0, [p0, #0]
; AIE2-O0-NEXT:    nop
; AIE2-O0-NEXT:    nop
; AIE2-O0-NEXT:    ret lr
; AIE2-O0-NEXT:    nop // Delay Slot 5
; AIE2-O0-NEXT:    nop // Delay Slot 4
; AIE2-O0-NEXT:    nop // Delay Slot 3
; AIE2-O0-NEXT:    extend.s8 r0, r0 // Delay Slot 2
; AIE2-O0-NEXT:    nop // Delay Slot 1
;
; AIE2-O2-LABEL: load_ptr:
; AIE2-O2:       // %bb.0:
; AIE2-O2-NEXT:    nopb ; lda.s8 r0, [p0, #1]; nops ; nopxm ; nopv
; AIE2-O2-NEXT:    nopa ; ret lr
; AIE2-O2-NEXT:    nop // Delay Slot 5
; AIE2-O2-NEXT:    nop // Delay Slot 4
; AIE2-O2-NEXT:    nop // Delay Slot 3
; AIE2-O2-NEXT:    nop // Delay Slot 2
; AIE2-O2-NEXT:    nop // Delay Slot 1
;
; AIE2P-O0-LABEL: load_ptr:
; AIE2P-O0:       // %bb.0:
; AIE2P-O0-NEXT:    mova m0, #1
; AIE2P-O0-NEXT:    padda [p0], m0
; AIE2P-O0-NEXT:    lda.s8 r0, [p0, #0]
; AIE2P-O0-NEXT:    nop
; AIE2P-O0-NEXT:    nop
; AIE2P-O0-NEXT:    ret lr
; AIE2P-O0-NEXT:    nop // Delay Slot 5
; AIE2P-O0-NEXT:    nop // Delay Slot 4
; AIE2P-O0-NEXT:    nop // Delay Slot 3
; AIE2P-O0-NEXT:    extend.s8 r0, r0 // Delay Slot 2
; AIE2P-O0-NEXT:    nop // Delay Slot 1
;
; AIE2P-O2-LABEL: load_ptr:
; AIE2P-O2:       // %bb.0:
; AIE2P-O2-NEXT:    lda.s8 r0, [p0, #1]; nopb ; nops ; nopxm ; nopv
; AIE2P-O2-NEXT:    nopa ; ret lr
; AIE2P-O2-NEXT:    nop // Delay Slot 5
; AIE2P-O2-NEXT:    nop // Delay Slot 4
; AIE2P-O2-NEXT:    nop // Delay Slot 3
; AIE2P-O2-NEXT:    nop // Delay Slot 2
; AIE2P-O2-NEXT:    nop // Delay Slot 1
  %1 = getelementptr i8, i8* %a, i32 1
  %2 = load i8, i8* %1
  %3 = sext i8 %2 to i32
  ret i32 %3
}

define i32 @load_ptr_optnone(i8 *%a) noinline optnone {
; AIE2-O0-LABEL: load_ptr_optnone:
; AIE2-O0:       // %bb.0:
; AIE2-O0-NEXT:    mova m0, #1
; AIE2-O0-NEXT:    paddb [p0], m0
; AIE2-O0-NEXT:    lda.s8 r0, [p0, #0]
; AIE2-O0-NEXT:    nop
; AIE2-O0-NEXT:    nop
; AIE2-O0-NEXT:    ret lr
; AIE2-O0-NEXT:    nop // Delay Slot 5
; AIE2-O0-NEXT:    nop // Delay Slot 4
; AIE2-O0-NEXT:    nop // Delay Slot 3
; AIE2-O0-NEXT:    extend.s8 r0, r0 // Delay Slot 2
; AIE2-O0-NEXT:    nop // Delay Slot 1
;
; AIE2-O2-LABEL: load_ptr_optnone:
; AIE2-O2:       // %bb.0:
; AIE2-O2-NEXT:    nopb ; lda.s8 r0, [p0, #1]; nops ; nopxm ; nopv
; AIE2-O2-NEXT:    nopa ; ret lr
; AIE2-O2-NEXT:    nop // Delay Slot 5
; AIE2-O2-NEXT:    nop // Delay Slot 4
; AIE2-O2-NEXT:    nop // Delay Slot 3
; AIE2-O2-NEXT:    nop // Delay Slot 2
; AIE2-O2-NEXT:    nop // Delay Slot 1
;
; AIE2P-O0-LABEL: load_ptr_optnone:
; AIE2P-O0:       // %bb.0:
; AIE2P-O0-NEXT:    mova m0, #1
; AIE2P-O0-NEXT:    padda [p0], m0
; AIE2P-O0-NEXT:    lda.s8 r0, [p0, #0]
; AIE2P-O0-NEXT:    nop
; AIE2P-O0-NEXT:    nop
; AIE2P-O0-NEXT:    ret lr
; AIE2P-O0-NEXT:    nop // Delay Slot 5
; AIE2P-O0-NEXT:    nop // Delay Slot 4
; AIE2P-O0-NEXT:    nop // Delay Slot 3
; AIE2P-O0-NEXT:    extend.s8 r0, r0 // Delay Slot 2
; AIE2P-O0-NEXT:    nop // Delay Slot 1
;
; AIE2P-O2-LABEL: load_ptr_optnone:
; AIE2P-O2:       // %bb.0:
; AIE2P-O2-NEXT:    lda.s8 r0, [p0, #1]; nopb ; nops ; nopxm ; nopv
; AIE2P-O2-NEXT:    nopa ; ret lr
; AIE2P-O2-NEXT:    nop // Delay Slot 5
; AIE2P-O2-NEXT:    nop // Delay Slot 4
; AIE2P-O2-NEXT:    nop // Delay Slot 3
; AIE2P-O2-NEXT:    nop // Delay Slot 2
; AIE2P-O2-NEXT:    nop // Delay Slot 1
  %1 = getelementptr i8, i8* %a, i32 1
  %2 = load i8, i8* %1
  %3 = sext i8 %2 to i32
  ret i32 %3
}
