; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2023-2026 Advanced Micro Devices, Inc. or its affiliates

; RUN: llc -mtriple=aie2 --issue-limit=1 -verify-machineinstrs -o - < %s \
; RUN:   | FileCheck --check-prefix=AIE2 %s

; RUN: llc -mtriple=aie2p --issue-limit=1 -verify-machineinstrs -o - < %s \
; RUN:   | FileCheck --check-prefix=AIE2P %s

define  i32 @test(i8 signext %i) noinline nounwind optnone {
; AIE2-LABEL: test:
; AIE2:       // %bb.0: // %entry
; AIE2-NEXT:    paddb [sp], #32; nopx
; AIE2-NEXT:    st p6, [sp, #-28] // 4-byte Folded Spill
; AIE2-NEXT:    mov p6, sp
; AIE2-NEXT:    paddb [p6], #-24
; AIE2-NEXT:    st.s8 r1, [p6, #0]
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    lda.s8 r0, [p6, #0]
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    mova r2, #15
; AIE2-NEXT:    movxm r1, #1048575
; AIE2-NEXT:    add r0, r0, #-1
; AIE2-NEXT:    and r1, r0, r1
; AIE2-NEXT:    ltu r1, r2, r1
; AIE2-NEXT:    jnz r1, #.LBB0_6
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    nop // Delay Slot 2
; AIE2-NEXT:    st lr, [sp, #-32] // 4-byte Folded Spill Delay Slot 1
; AIE2-NEXT:  // %bb.1: // %entry
; AIE2-NEXT:    movxm p0, #.LJTI0_0
; AIE2-NEXT:    movxm r1, #1048575
; AIE2-NEXT:    and r0, r0, r1
; AIE2-NEXT:    mova r1, #2
; AIE2-NEXT:    lshl r0, r0, r1
; AIE2-NEXT:    mov dj0, r0
; AIE2-NEXT:    lda p0, [p0, dj0]
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    j p0
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    nop // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
; AIE2-NEXT:  .LBB0_2: // %sw.bb
; AIE2-NEXT:    jl #case1
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    nop // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
; AIE2-NEXT:    j #.LBB0_7
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    nop // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
; AIE2-NEXT:  .LBB0_3: // %sw.bb1
; AIE2-NEXT:    jl #case2
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    nop // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
; AIE2-NEXT:    j #.LBB0_7
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    nop // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
; AIE2-NEXT:  .LBB0_4: // %sw.bb3
; AIE2-NEXT:    jl #case3
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    nop // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
; AIE2-NEXT:    j #.LBB0_7
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    nop // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
; AIE2-NEXT:  .LBB0_5: // %sw.bb5
; AIE2-NEXT:    jl #case4
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    nop // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
; AIE2-NEXT:    j #.LBB0_7
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    nop // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
; AIE2-NEXT:  .LBB0_6: // %sw.default
; AIE2-NEXT:    jl #caseb
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    nop // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
; AIE2-NEXT:  .LBB0_7: // %sw.epilog
; AIE2-NEXT:    nopb ; lda lr, [sp, #-32]; nops ; nopxm ; nopv // 4-byte Folded Reload
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    lda.s8 r0, [p6, #0]
; AIE2-NEXT:    lda p6, [sp, #-28] // 4-byte Folded Reload
; AIE2-NEXT:    ret lr
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    nop // Delay Slot 2
; AIE2-NEXT:    paddb [sp], #-32 // Delay Slot 1
;
; AIE2P-LABEL: test:
; AIE2P:       // %bb.0: // %entry
; AIE2P-NEXT:    mova m0, #-56; nopb ; nops ; nopxm ; nopv
; AIE2P-NEXT:    paddxm [sp], #64
; AIE2P-NEXT:    st p6, [sp, #-60] // 4-byte Folded Spill
; AIE2P-NEXT:    mov p6, sp
; AIE2P-NEXT:    padda [p6], m0
; AIE2P-NEXT:    st.s8 r1, [p6, #0]
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    lda.s8 r0, [p6, #0]
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    mova r2, #15
; AIE2P-NEXT:    movxm r1, #1048575
; AIE2P-NEXT:    add r0, r0, #-1
; AIE2P-NEXT:    and r1, r0, r1
; AIE2P-NEXT:    ltu r1, r2, r1
; AIE2P-NEXT:    jnz r1, #.LBB0_6
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    nop // Delay Slot 2
; AIE2P-NEXT:    st lr, [sp, #-64] // 4-byte Folded Spill Delay Slot 1
; AIE2P-NEXT:  // %bb.1: // %entry
; AIE2P-NEXT:    movxm p0, ##.LJTI0_0
; AIE2P-NEXT:    movxm r1, #1048575
; AIE2P-NEXT:    and r0, r0, r1
; AIE2P-NEXT:    mova r1, #2
; AIE2P-NEXT:    lshl r0, r0, r1
; AIE2P-NEXT:    mov dj0, r0
; AIE2P-NEXT:    lda p0, [p0, dj0]
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    j p0
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    nop // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
; AIE2P-NEXT:  .LBB0_2: // %sw.bb
; AIE2P-NEXT:    jl #case1
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    nop // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
; AIE2P-NEXT:    j #.LBB0_7
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    nop // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
; AIE2P-NEXT:  .LBB0_3: // %sw.bb1
; AIE2P-NEXT:    jl #case2
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    nop // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
; AIE2P-NEXT:    j #.LBB0_7
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    nop // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
; AIE2P-NEXT:  .LBB0_4: // %sw.bb3
; AIE2P-NEXT:    jl #case3
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    nop // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
; AIE2P-NEXT:    j #.LBB0_7
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    nop // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
; AIE2P-NEXT:  .LBB0_5: // %sw.bb5
; AIE2P-NEXT:    jl #case4
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    nop // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
; AIE2P-NEXT:    j #.LBB0_7
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    nop // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
; AIE2P-NEXT:  .LBB0_6: // %sw.default
; AIE2P-NEXT:    jl #caseb
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    nop // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
; AIE2P-NEXT:  .LBB0_7: // %sw.epilog
; AIE2P-NEXT:    lda lr, [sp, #-64]; nopb ; nopxm ; nops // 4-byte Folded Reload
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    lda.s8 r0, [p6, #0]
; AIE2P-NEXT:    lda p6, [sp, #-60] // 4-byte Folded Reload
; AIE2P-NEXT:    ret lr
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    paddxm [sp], #-64 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
entry:
  %i.addr = alloca i8, align 1
  store i8 %i, ptr %i.addr, align 1
  %0 = load i8, ptr %i.addr, align 1
  %conv = sext i8 %0 to i32
  switch i32 %conv, label %sw.default [
    i32 1, label %sw.bb
    i32 3, label %sw.bb1
    i32 5, label %sw.bb3
    i32 16, label %sw.bb5
  ]

sw.bb:
  %call = call i32 @case1()
  br label %sw.epilog

sw.bb1:
  %call2 = call i32 @case2()
  br label %sw.epilog

sw.bb3:
  %call4 = call i32 @case3()
  br label %sw.epilog

sw.bb5:
  %call6 = call i32 @case4()
  br label %sw.epilog

sw.default:
  %call7 = call i32 @caseb()
  br label %sw.epilog

sw.epilog:
  %1 = load i8, ptr %i.addr, align 1
  %conv8 = sext i8 %1 to i32
  ret i32 %conv8
}

declare i32 @case1(...)
declare i32 @case2(...)
declare i32 @case3(...)
declare i32 @case4(...)
declare i32 @caseb(...)
