; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2023-2025 Advanced Micro Devices, Inc. or its affiliates

; RUN: llc -O2 -mtriple=aie2 --issue-limit=1 %s -o - | FileCheck --check-prefix=AIE2 %s
; RUN: llc -O2 -mtriple=aie2p --issue-limit=1 %s -o - | FileCheck --check-prefix=AIE2P %s

define <32 x i8> @test_select_32xi8(i1 noundef zeroext %sel, <32 x i8> noundef %a, <32 x i8> noundef %b) {
; AIE2-LABEL: test_select_32xi8:
; AIE2:       // %bb.0: // %entry
; AIE2-NEXT:    nopa ; nopb ; ret lr ; nopm ; nops
; AIE2-NEXT:    mov r1, r16 // Delay Slot 5
; AIE2-NEXT:    add r16, r0, #-1 // Delay Slot 4
; AIE2-NEXT:    vsel.32 x0, x2, x4, r16 // Delay Slot 3
; AIE2-NEXT:    mov r16, r1 // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: test_select_32xi8:
; AIE2P:       // %bb.0: // %entry
; AIE2P-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; AIE2P-NEXT:    nopx // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    add r16, r0, #-1 // Delay Slot 3
; AIE2P-NEXT:    vsel.32 x0, x2, x4, r16 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
entry:
  %cond = select i1 %sel, <32 x i8> %a, <32 x i8> %b
  ret <32 x i8> %cond
}

define <16 x i16> @test_select_16xi16(i1 noundef zeroext %sel, <16 x i16> noundef %a, <16 x i16> noundef %b) {
; AIE2-LABEL: test_select_16xi16:
; AIE2:       // %bb.0: // %entry
; AIE2-NEXT:    nopa ; nopb ; ret lr ; nopm ; nops
; AIE2-NEXT:    mov r1, r16 // Delay Slot 5
; AIE2-NEXT:    add r16, r0, #-1 // Delay Slot 4
; AIE2-NEXT:    vsel.32 x0, x2, x4, r16 // Delay Slot 3
; AIE2-NEXT:    mov r16, r1 // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: test_select_16xi16:
; AIE2P:       // %bb.0: // %entry
; AIE2P-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; AIE2P-NEXT:    nopx // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    add r16, r0, #-1 // Delay Slot 3
; AIE2P-NEXT:    vsel.32 x0, x2, x4, r16 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
entry:
  %cond = select i1 %sel, <16 x i16> %a, <16 x i16> %b
  ret <16 x i16> %cond
}

define <8 x i32> @test_select_8xi32(i1 noundef zeroext %sel, <8 x i32> noundef %a, <8 x i32> noundef %b) {
; AIE2-LABEL: test_select_8xi32:
; AIE2:       // %bb.0: // %entry
; AIE2-NEXT:    nopa ; nopb ; ret lr ; nopm ; nops
; AIE2-NEXT:    mov r1, r16 // Delay Slot 5
; AIE2-NEXT:    add r16, r0, #-1 // Delay Slot 4
; AIE2-NEXT:    vsel.32 x0, x2, x4, r16 // Delay Slot 3
; AIE2-NEXT:    mov r16, r1 // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: test_select_8xi32:
; AIE2P:       // %bb.0: // %entry
; AIE2P-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; AIE2P-NEXT:    nopx // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    add r16, r0, #-1 // Delay Slot 3
; AIE2P-NEXT:    vsel.32 x0, x2, x4, r16 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
entry:
  %cond = select i1 %sel, <8 x i32> %a, <8 x i32> %b
  ret <8 x i32> %cond
}

define <64 x i8> @test_select_64xi8(i1 noundef zeroext %sel, <64 x i8> noundef %a, <64 x i8> noundef %b) {
; AIE2-LABEL: test_select_64xi8:
; AIE2:       // %bb.0: // %entry
; AIE2-NEXT:    nopa ; nopb ; ret lr ; nopm ; nops
; AIE2-NEXT:    mov r1, r16 // Delay Slot 5
; AIE2-NEXT:    add r16, r0, #-1 // Delay Slot 4
; AIE2-NEXT:    vsel.32 x0, x2, x4, r16 // Delay Slot 3
; AIE2-NEXT:    mov r16, r1 // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: test_select_64xi8:
; AIE2P:       // %bb.0: // %entry
; AIE2P-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; AIE2P-NEXT:    nopx // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    add r16, r0, #-1 // Delay Slot 3
; AIE2P-NEXT:    vsel.32 x0, x2, x4, r16 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
entry:
  %cond = select i1 %sel, <64 x i8> %a, <64 x i8> %b
  ret <64 x i8> %cond
}

define <32 x i16> @test_select_32xi16(i1 noundef zeroext %sel, <32 x i16> noundef %a, <32 x i16> noundef %b) {
; AIE2-LABEL: test_select_32xi16:
; AIE2:       // %bb.0: // %entry
; AIE2-NEXT:    nopa ; nopb ; ret lr ; nopm ; nops
; AIE2-NEXT:    mov r1, r16 // Delay Slot 5
; AIE2-NEXT:    add r16, r0, #-1 // Delay Slot 4
; AIE2-NEXT:    vsel.32 x0, x2, x4, r16 // Delay Slot 3
; AIE2-NEXT:    mov r16, r1 // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: test_select_32xi16:
; AIE2P:       // %bb.0: // %entry
; AIE2P-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; AIE2P-NEXT:    nopx // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    add r16, r0, #-1 // Delay Slot 3
; AIE2P-NEXT:    vsel.32 x0, x2, x4, r16 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
entry:
  %cond = select i1 %sel, <32 x i16> %a, <32 x i16> %b
  ret <32 x i16> %cond
}

define <16 x i32> @test_select_16xi32(i1 noundef zeroext %sel, <16 x i32> noundef %a, <16 x i32> noundef %b) {
; AIE2-LABEL: test_select_16xi32:
; AIE2:       // %bb.0: // %entry
; AIE2-NEXT:    nopa ; nopb ; ret lr ; nopm ; nops
; AIE2-NEXT:    mov r1, r16 // Delay Slot 5
; AIE2-NEXT:    add r16, r0, #-1 // Delay Slot 4
; AIE2-NEXT:    vsel.32 x0, x2, x4, r16 // Delay Slot 3
; AIE2-NEXT:    mov r16, r1 // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: test_select_16xi32:
; AIE2P:       // %bb.0: // %entry
; AIE2P-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; AIE2P-NEXT:    nopx // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    add r16, r0, #-1 // Delay Slot 3
; AIE2P-NEXT:    vsel.32 x0, x2, x4, r16 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
entry:
  %cond = select i1 %sel, <16 x i32> %a, <16 x i32> %b
  ret <16 x i32> %cond
}

define <128 x i8> @test_select_128xi8(i1 noundef zeroext %sel, <128 x i8> noundef %a, <128 x i8> noundef %b) {
; AIE2-LABEL: test_select_128xi8:
; AIE2:       // %bb.0: // %entry
; AIE2-NEXT:    nopa ; nopx ; mov r1, r16
; AIE2-NEXT:    ret lr
; AIE2-NEXT:    add r16, r0, #-1 // Delay Slot 5
; AIE2-NEXT:    vsel.32 x4, x6, x8, r16 // Delay Slot 4
; AIE2-NEXT:    vsel.32 x5, x7, x9, r16 // Delay Slot 3
; AIE2-NEXT:    mov r16, r1 // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: test_select_128xi8:
; AIE2P:       // %bb.0: // %entry
; AIE2P-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    add r16, r0, #-1 // Delay Slot 4
; AIE2P-NEXT:    vsel.32 x4, x6, x8, r16 // Delay Slot 3
; AIE2P-NEXT:    vsel.32 x5, x7, x9, r16 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
entry:
  %cond = select i1 %sel, <128 x i8> %a, <128 x i8> %b
  ret <128 x i8> %cond
}

define <64 x i16> @test_select_64xi16(i1 noundef zeroext %sel, <64 x i16> noundef %a, <64 x i16> noundef %b) {
; AIE2-LABEL: test_select_64xi16:
; AIE2:       // %bb.0: // %entry
; AIE2-NEXT:    nopa ; nopx ; mov r1, r16
; AIE2-NEXT:    ret lr
; AIE2-NEXT:    add r16, r0, #-1 // Delay Slot 5
; AIE2-NEXT:    vsel.32 x4, x6, x8, r16 // Delay Slot 4
; AIE2-NEXT:    vsel.32 x5, x7, x9, r16 // Delay Slot 3
; AIE2-NEXT:    mov r16, r1 // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: test_select_64xi16:
; AIE2P:       // %bb.0: // %entry
; AIE2P-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    add r16, r0, #-1 // Delay Slot 4
; AIE2P-NEXT:    vsel.32 x4, x6, x8, r16 // Delay Slot 3
; AIE2P-NEXT:    vsel.32 x5, x7, x9, r16 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
entry:
  %cond = select i1 %sel, <64 x i16> %a, <64 x i16> %b
  ret <64 x i16> %cond
}

define <32 x i32> @test_select_32xi32(i1 noundef zeroext %sel, <32 x i32> noundef %a, <32 x i32> noundef %b) {
; AIE2-LABEL: test_select_32xi32:
; AIE2:       // %bb.0: // %entry
; AIE2-NEXT:    nopa ; nopx ; mov r1, r16
; AIE2-NEXT:    ret lr
; AIE2-NEXT:    add r16, r0, #-1 // Delay Slot 5
; AIE2-NEXT:    vsel.32 x4, x6, x8, r16 // Delay Slot 4
; AIE2-NEXT:    vsel.32 x5, x7, x9, r16 // Delay Slot 3
; AIE2-NEXT:    mov r16, r1 // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: test_select_32xi32:
; AIE2P:       // %bb.0: // %entry
; AIE2P-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    add r16, r0, #-1 // Delay Slot 4
; AIE2P-NEXT:    vsel.32 x4, x6, x8, r16 // Delay Slot 3
; AIE2P-NEXT:    vsel.32 x5, x7, x9, r16 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
entry:
  %cond = select i1 %sel, <32 x i32> %a, <32 x i32> %b
  ret <32 x i32> %cond
}
