# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -verify-machineinstrs -run-pass=postmisched %s -o - | FileCheck %s

---
name:            test_reg
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $r3, $r4

    ; CHECK-LABEL: name: test_reg
    ; CHECK: liveins: $p0, $r3, $r4
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $r1 = LDA_dms_lda_idx_imm $p0, 0
    ; CHECK-NEXT: $r2 = LDA_dms_lda_idx_imm killed $p0, 0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r13 = ADD killed $r1, killed $r2, implicit-def $srcarry
    ; CHECK-NEXT: $r12 = ADC killed $r3, killed $r4, implicit-def $srcarry, implicit $srcarry
    $r1 = LDA_dms_lda_idx_imm $p0, 0
    $r2 = LDA_dms_lda_idx_imm $p0, 0
    $r13 = ADD $r1, $r2, implicit-def $srcarry
    $r12 = ADC $r3, $r4, implicit-def $srcarry, implicit $srcarry
...

---
name:            test_reg2
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r3, $r4

    ; CHECK-LABEL: name: test_reg2
    ; CHECK: liveins: $r3, $r4
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $srcarry = MOVXM_lng_cg 0
    ; CHECK-NEXT: $r12 = SBC killed $r3, killed $r4, implicit-def $srcarry, implicit $srcarry
    $srcarry  = MOVXM_lng_cg 0
    $r12 = SBC $r3, $r4, implicit-def $srcarry, implicit $srcarry
...
