# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 %topdown-single -verify-machineinstrs \
# RUN:   -run-pass=postmisched %s -o - | FileCheck %s

---
name:            test_reg
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $cm3, $s1

    ; CHECK-LABEL: name: test_reg
    ; CHECK: liveins: $cm3, $s1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $r0 = MOV_mv_scl $srsrs_of
    ; CHECK-NEXT: $wl5 = VSRS_D8_S32_mv_w_srs killed $cm3, killed $s1, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r0 = MOV_mv_scl $srsrs_of
    $r0  = MOV_mv_scl $srsrs_of
    $wl5 = VSRS_D8_S32_mv_w_srs  $cm3, $s1, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    $r0  = MOV_mv_scl $srsrs_of
...

---
name:            II_VSRSM
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $cm3, $s1

    ; CHECK-LABEL: name: II_VSRSM
    ; CHECK: liveins: $cm3, $s1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $r0 = MOV_mv_scl $srsrs_of
    ; CHECK-NEXT: $wl5 = VSRSM_D16_S32 killed $bml3, killed $s1, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r0 = MOV_mv_scl $srsrs_of
    $r0  = MOV_mv_scl $srsrs_of
    $wl5 = VSRSM_D16_S32  $bml3, $s1, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    $r0  = MOV_mv_scl $srsrs_of
...

---
name:            vst_srs
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $cm0, $s0

    ; CHECK-LABEL: name: vst_srs
    ; CHECK: liveins: $p0, $cm0, $s0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $r0 = MOV_mv_scl $srsrs_of
    ; CHECK-NEXT: VST_SRS_D8_S32_ag_idx_imm killed $p0, 0, killed $cm0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r0 = MOV_mv_scl $srsrs_of
    $r0  = MOV_mv_scl $srsrs_of
    VST_SRS_D8_S32_ag_idx_imm $p0, 0, $cm0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    $r0  = MOV_mv_scl $srsrs_of
...

---
name:            vst_srs_postinc
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $cm0, $s0

    ; CHECK-LABEL: name: vst_srs_postinc
    ; CHECK: liveins: $p0, $cm0, $s0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $r0 = MOV_mv_scl $srsrs_of
    ; CHECK-NEXT: $p0 = VST_SRS_D16_S64_ag_pstm_nrm_imm killed $p0, 0, killed $cm0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r0 = MOV_mv_scl $srsrs_of
    $r0  = MOV_mv_scl $srsrs_of
    $p0 = VST_SRS_D16_S64_ag_pstm_nrm_imm $p0, 0, $cm0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    $r0  = MOV_mv_scl $srsrs_of
...

---
name:            vst_srs_2d
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $cm0, $s0, $d0

    ; CHECK-LABEL: name: vst_srs_2d
    ; CHECK: liveins: $p0, $cm0, $s0, $d0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $r0 = MOV_mv_scl $srsrs_of
    ; CHECK-NEXT: $p0, $dc0 = VST_2D_SRS_D16_S64 killed $p0, killed $d0, killed $cm0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r0 = MOV_mv_scl $srsrs_of
    $r0  = MOV_mv_scl $srsrs_of
    $p0, $dc0 = VST_2D_SRS_D16_S64 $p0, $d0, $cm0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    $r0  = MOV_mv_scl $srsrs_of
...

---
name:            vst_3d_srs
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $cm0, $s0, $d0
    ; CHECK-LABEL: name: vst_3d_srs
    ; CHECK: liveins: $p0, $cm0, $s0, $d0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $r0 = MOV_mv_scl $srsrs_of
    ; CHECK-NEXT: $p0, $dc0, $dc4 = VST_3D_SRS_D16_S64 killed $p0, killed $d0_3d, killed $cm0, killed $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r0 = MOV_mv_scl $srsrs_of
    $r0  = MOV_mv_scl $srsrs_of
    $p0, $dc0, $dc4 = VST_3D_SRS_D16_S64 $p0, $d0_3d, $cm0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
    $r0  = MOV_mv_scl $srsrs_of
...
