# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 %topdown-single -verify-machineinstrs \
# RUN:   -run-pass=postmisched %s -o - | FileCheck %s

# This test checks the output latency of the status register srUPS.
# VLDA_UPS writes it in E8, therefore we need 7 delay slots before the MOVXM.

---
name:            test_reg_indexed
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $s0

    ; CHECK-LABEL: name: test_reg_indexed
    ; CHECK: liveins: $p0, $s0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $r0 = MOV_mv_scl $srups_of
    ; CHECK-NEXT: $bmh0 = VLDA_UPS_S32_D16_ag_idx_imm killed $s0, killed $p0, 0, implicit-def $srups_of, implicit $crsat, implicit $crupssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r0 = MOV_mv_scl $srups_of
    $r0  = MOV_mv_scl $srups_of
    $bmh0 = VLDA_UPS_S32_D16_ag_idx_imm $s0, $p0, 0, implicit-def $srups_of, implicit $crsat, implicit $crupssign
    $r0  = MOV_mv_scl $srups_of
...

---
name:            test_reg_postinc
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $s0

    ; CHECK-LABEL: name: test_reg_postinc
    ; CHECK: liveins: $p0, $s0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $r0 = MOV_mv_scl $srups_of
    ; CHECK-NEXT: $bmh0, $p0 = VLDA_UPS_S32_D16_ag_pstm_nrm_imm killed $s0, killed $p0, 0, implicit-def $srups_of, implicit $crsat, implicit $crupssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r0 = MOV_mv_scl $srups_of
    $r0  = MOV_mv_scl $srups_of
    $bmh0, $p0 = VLDA_UPS_S32_D16_ag_pstm_nrm_imm $s0, $p0, 0, implicit-def $srups_of, implicit $crsat, implicit $crupssign
    $r0  = MOV_mv_scl $srups_of
...

---
name:            test_reg_2d
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $s0, $d0

    ; CHECK-LABEL: name: test_reg_2d
    ; CHECK: liveins: $p0, $s0, $d0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $r0 = MOV_mv_scl $srups_of
    ; CHECK-NEXT: $bmh0, $p0, $dc0 = VLDA_2D_UPS_S32_D16 killed $s0, killed $p0, killed $d0, implicit-def $srups_of, implicit $crsat, implicit $crupssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r0 = MOV_mv_scl $srups_of
    $r0  = MOV_mv_scl $srups_of
    $bmh0, $p0, $dc0 = VLDA_2D_UPS_S32_D16 $s0, $p0, $d0, implicit-def $srups_of, implicit $crsat, implicit $crupssign
    $r0  = MOV_mv_scl $srups_of
...

---
name:            test_reg_3d
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $s0, $d0
    ; CHECK-LABEL: name: test_reg_3d
    ; CHECK: liveins: $p0, $s0, $d0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $r0 = MOV_mv_scl $srups_of
    ; CHECK-NEXT: $bmh0, $p0, $dc0, $dc4 = VLDA_3D_UPS_S32_D16 killed $s0, killed $p0, killed $d0_3d, implicit-def $srups_of, implicit $crsat, implicit $crupssign
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $r0 = MOV_mv_scl $srups_of
    $r0  = MOV_mv_scl $srups_of
    $bmh0, $p0, $dc0, $dc4 = VLDA_3D_UPS_S32_D16 $s0, $p0, $d0_3d, implicit-def $srups_of, implicit $crsat, implicit $crupssign
    $r0  = MOV_mv_scl $srups_of
...
