# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=register-coalescer %s -verify-machineinstrs -o - \
# RUN:    | FileCheck %s

---
name: WidenCopy_no_coalesce
tracksRegLiveness: true

body:             |
  ; CHECK-LABEL: name: WidenCopy_no_coalesce
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 7
  ; CHECK-NEXT:   [[VBCST_16_:%[0-9]+]]:vec512 = VBCST_16 [[MOV_RLC_imm11_pseudo]]
  ; CHECK-NEXT:   [[VCONV_fp32_bf16_mv_ups_xbf:%[0-9]+]]:ecml = VCONV_fp32_bf16_mv_ups_xbf [[VBCST_16_]]
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   undef [[COPY:%[0-9]+]].sub_1024_acc_lo:acc2048 = COPY [[VCONV_fp32_bf16_mv_ups_xbf]]
  ; CHECK-NEXT:   dead [[VADD_vmac_cm2_add_reg:%[0-9]+]]:acc2048 = VADD_vmac_cm2_add_reg [[COPY]], [[COPY]], [[MOV_RLC_imm11_pseudo1]]
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.0.entry:
    successors: %bb.1

    %69:er = MOV_RLC_imm11_pseudo 7
    %24:vec512 = VBCST_16 %69
    %77:ecml = VCONV_fp32_bf16_mv_ups_xbf %24
    %18:er = MOV_RLC_imm11_pseudo 0

  bb.1:
    successors: %bb.1

    undef %62.sub_1024_acc_lo:acc2048 = COPY %77
    %42:acc2048 = VADD_vmac_cm2_add_reg %62, %62, %18
    PseudoRET implicit $lr
...

---
name: WidenCopy_same_MBB_coalesce
tracksRegLiveness: true

body:             |
  bb.0.entry:
    successors:

    ; CHECK-LABEL: name: WidenCopy_same_MBB_coalesce
    ; CHECK: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 7
    ; CHECK-NEXT: [[VBCST_16_:%[0-9]+]]:vec512 = VBCST_16 [[MOV_RLC_imm11_pseudo]]
    ; CHECK-NEXT: undef [[VCONV_fp32_bf16_mv_ups_xbf:%[0-9]+]].sub_1024_acc_lo:acc2048 = VCONV_fp32_bf16_mv_ups_xbf [[VBCST_16_]]
    ; CHECK-NEXT: dead [[VCONV_fp32_bf16_mv_ups_xbf1:%[0-9]+]]:ecml = VCONV_fp32_bf16_mv_ups_xbf [[VBCST_16_]]
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: dead [[VADD_vmac_cm2_add_reg:%[0-9]+]]:acc2048 = VADD_vmac_cm2_add_reg [[VCONV_fp32_bf16_mv_ups_xbf]], [[VCONV_fp32_bf16_mv_ups_xbf]], [[MOV_RLC_imm11_pseudo1]]
    ; CHECK-NEXT: PseudoRET implicit $lr
    %69:er = MOV_RLC_imm11_pseudo 7
    %24:vec512 = VBCST_16 %69
    %77:ecml = VCONV_fp32_bf16_mv_ups_xbf %24
    %78:ecml = VCONV_fp32_bf16_mv_ups_xbf %24
    %18:er = MOV_RLC_imm11_pseudo 0
    undef %62.sub_1024_acc_lo:acc2048 = COPY %77
    %42:acc2048 = VADD_vmac_cm2_add_reg %62, %62, %18
    PseudoRET implicit $lr
...

---
name: WidenCopy_inside_singleMBBLoop
tracksRegLiveness: true

body:             |
  ; CHECK-LABEL: name: WidenCopy_inside_singleMBBLoop
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 7
  ; CHECK-NEXT:   [[VBCST_16_:%[0-9]+]]:vec512 = VBCST_16 [[MOV_RLC_imm11_pseudo]]
  ; CHECK-NEXT:   [[VCONV_fp32_bf16_mv_ups_xbf:%[0-9]+]]:ecml = VCONV_fp32_bf16_mv_ups_xbf [[VBCST_16_]]
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   undef [[COPY:%[0-9]+]].sub_1024_acc_lo:acc2048 = COPY [[VCONV_fp32_bf16_mv_ups_xbf]]
  ; CHECK-NEXT:   dead [[VADD_vmac_cm2_add_reg:%[0-9]+]]:acc2048 = VADD_vmac_cm2_add_reg [[COPY]], [[COPY]], [[MOV_RLC_imm11_pseudo1]]
  ; CHECK-NEXT:   PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.1, implicit $ls, implicit $le
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.0.entry:
    successors: %bb.1

    %69:er = MOV_RLC_imm11_pseudo 7
    %24:vec512 = VBCST_16 %69
    %77:ecml = VCONV_fp32_bf16_mv_ups_xbf %24
    %18:er = MOV_RLC_imm11_pseudo 0

  bb.1:
    successors: %bb.1, %bb.2

    undef %62.sub_1024_acc_lo:acc2048 = COPY %77
    %42:acc2048 = VADD_vmac_cm2_add_reg %62, %62, %18
    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.1, implicit $ls, implicit $le
    PseudoJ_jump_imm %bb.2

  bb.2:
    PseudoRET implicit $lr
...
