# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
#
# RUN: llc -mtriple=aie2p --start-before=regbankselect --stop-after=regbankselect -o - -verify-machineinstrs  %s | FileCheck %s

# G_CONCAT_VECTORS should determine the RegisterBank for the source operands.
# <32 x s32> requires an Accumulator register. Assign AccReg.
# <16 x s16> fits in a Vector Register. Assign Vreg.
---
name:            GConcatAccResult
alignment:       16
legalized:       true
regBankSelected: false
body:             |
  bb.1:
    liveins: $p0, $p1
    ; CHECK-LABEL: name: GConcatAccResult
    ; CHECK: liveins: $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ptrregbank(p0) = COPY $p0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:accregbank(<16 x s32>) = G_LOAD [[COPY]](p0) :: (load (<16 x s32>))
    ; CHECK-NEXT: [[C:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 64
    ; CHECK-NEXT: [[AIE_OFFSET_LOAD:%[0-9]+]]:accregbank(<16 x s32>) = G_AIE_OFFSET_LOAD [[COPY]](p0), [[C]](s20) :: (load (<16 x s32>))
    ; CHECK-NEXT: %ACC:accregbank(<32 x s32>) = G_CONCAT_VECTORS [[LOAD]](<16 x s32>), [[AIE_OFFSET_LOAD]](<16 x s32>)
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ptrregbank(p0) = COPY $p1
    ; CHECK-NEXT: [[LOAD1:%[0-9]+]]:vregbank(<16 x s16>) = G_LOAD [[COPY]](p0) :: (load (<16 x s16>))
    ; CHECK-NEXT: [[C1:%[0-9]+]]:modregbank(s20) = G_CONSTANT i20 32
    ; CHECK-NEXT: [[AIE_OFFSET_LOAD1:%[0-9]+]]:vregbank(<16 x s16>) = G_AIE_OFFSET_LOAD [[COPY]](p0), [[C1]](s20) :: (load (<16 x s16>))
    ; CHECK-NEXT: %VREG:vregbank(<32 x s16>) = G_CONCAT_VECTORS [[LOAD1]](<16 x s16>), [[AIE_OFFSET_LOAD1]](<16 x s16>)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 42
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC1024.bf.mac.conf), %VREG(<32 x s16>), %VREG(<32 x s16>), %ACC(<32 x s32>), [[C2]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[INT]](<32 x s32>)
    %0:_(p0) = COPY $p0
    %1:_(<16 x s32>) = G_LOAD %0(p0) :: (load (<16 x s32>))
    %2:_(s20) = G_CONSTANT i20 64
    %3:_(<16 x s32>) = G_AIE_OFFSET_LOAD %0(p0), %2(s20) :: (load (<16 x s32>))
    %ACC:_(<32 x s32>) = G_CONCAT_VECTORS %1(<16 x s32>), %3(<16 x s32>)
    %5:_(p0) = COPY $p1
    %6:_(<16 x s16>) = G_LOAD %0(p0) :: (load (<16 x s16>))
    %7:_(s20) = G_CONSTANT i20 32
    %8:_(<16 x s16>) = G_AIE_OFFSET_LOAD %0(p0), %7(s20) :: (load (<16 x s16>))
    %VREG:_(<32 x s16>) = G_CONCAT_VECTORS %6(<16 x s16>), %8(<16 x s16>)
    %10:_(s32) = G_CONSTANT i32 42
    %44:_(<32 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.I512.I512.ACC1024.bf.mac.conf), %VREG(<32 x s16>), %VREG(<32 x s16>), %ACC(<32 x s32>), %10(s32)
    PseudoRET implicit $lr, implicit %44

...
