# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5

#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple=aie2p -verify-machineinstrs --start-before=register-coalescer --stop-after=register-coalescer %s -o - | FileCheck %s

# KeepExe should remain EXE reg, otherwise it is assigned to
# spill_vec512_to_composite and  will change machine scheduling.
---
name:            reg-coalescer-regression
alignment:       16
legalized:       true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: reg-coalescer-regression
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   dead [[DEF:%[0-9]+]]:er = IMPLICIT_DEF
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   PseudoRET implicit $lr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x40000000), %bb.4(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   PseudoJZ undef [[DEF]], %bb.4
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.4(0x04000000), %bb.3(0x7c000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   PseudoJZ undef [[DEF]], %bb.4
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  bb.0:
    successors: %bb.2(0x80000000)

    %67:er = IMPLICIT_DEF
    %KeepEXE:exe = IMPLICIT_DEF
    PseudoJ_jump_imm %bb.2

  bb.1:
    PseudoRET implicit $lr

  bb.2:
    successors: %bb.3(0x40000000), %bb.4(0x40000000)

    %49:exe = COPY killed %KeepEXE
    PseudoJZ killed undef %67, %bb.4
    PseudoJ_jump_imm %bb.3

  bb.3:
    successors: %bb.4(0x04000000), %bb.3(0x7c000000)

    undef %36.sub_512_lo:vec1024 = COPY killed %49
    %49:exe = IMPLICIT_DEF
    PseudoJZ killed undef %67, %bb.4
    PseudoJ_jump_imm %bb.3

  bb.4:
    successors: %bb.1(0x80000000)

    PseudoJ_jump_imm %bb.1

...
