# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple=aie2p -run-pass=aie-spill-slot-opt -o - %s | FileCheck %s

# StackSlotColoring can coalesce registers with disjoint live ranges from
# different register files onto a single frame index. Here a DS descriptor spill
# (which decomposes into 32-bit scalar lanes) and a DM accumulator spill (which
# decomposes into 512-bit BM lanes) share %stack.0, so the scalar lane and the BM
# lane both map to byte offset 0 but with different sizes (4 vs 64 bytes).
#
# Decomposing such a slot is not safe/profitable: the per-offset replacement slot
# would have to grow to the largest (512-bit) lane, replacing one small coalesced
# object with several much larger ones (increasing stack usage), and the size
# mismatch can select an illegal spill opcode for the accumulator register. The
# pass detects the conflicting same-offset lanes and bails out, leaving the
# original composite DS/DM spills and reloads untouched.

---
name:            ds_dm_shared_slot
alignment:       16
tracksRegLiveness: true
stack:
  - { id: 0, type: spill-slot, size: 256, alignment: 128 }
body:             |
  ; CHECK-LABEL: name: ds_dm_shared_slot
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $d0_3d
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   ST_DS_SPILL $d0_3d, %stack.0, implicit $sp :: (store (s256) into %stack.0, align 4)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT:   liveins: $dm0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $d0_3d = LDA_DS_SPILL %stack.0, implicit $sp :: (load (s256) from %stack.0, align 4)
  ; CHECK-NEXT:   VST_DM_SPILL $dm0, %stack.0, implicit $sp :: (store (s2048) into %stack.0, align 128)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   liveins: $d0_3d
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $dm1 = VLDA_DM_SPILL %stack.0, implicit $sp :: (load (s2048) from %stack.0, align 128)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $d0_3d, implicit $dm1
  bb.0:
    successors: %bb.1
    liveins: $d0_3d

    ST_DS_SPILL $d0_3d, %stack.0, implicit $sp :: (store (s256) into %stack.0, align 4)

  bb.1:
    successors: %bb.2
    liveins: $dm0

    renamable $d0_3d = LDA_DS_SPILL %stack.0, implicit $sp :: (load (s256) from %stack.0, align 4)
    VST_DM_SPILL $dm0, %stack.0, implicit $sp :: (store (s2048) into %stack.0, align 128)

  bb.2:
    liveins: $d0_3d

    renamable $dm1 = VLDA_DM_SPILL %stack.0, implicit $sp :: (load (s2048) from %stack.0, align 128)
    PseudoRET implicit $lr, implicit $d0_3d, implicit $dm1
...
