# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple=aie2p -verify-machineinstrs --start-before=greedy --stop-after=virtregrewriter %s -o - | FileCheck %s

# Example where spilling is reduced by the combined Vec/Acc Registerclass.

---
name:            spill-vec-acc
alignment:       16
legalized:       true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: spill-vec-acc
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $r16 = MOV_RLC_imm11_pseudo 0
  ; CHECK-NEXT:   renamable $x5 = VBCST_32 renamable $r16
  ; CHECK-NEXT:   renamable $r0 = MOVXM -19312
  ; CHECK-NEXT:   renamable $x0 = VBCST_16 killed renamable $r0
  ; CHECK-NEXT:   renamable $bmll2 = COPY killed renamable $x0
  ; CHECK-NEXT:   renamable $r0 = MOVXM -19360
  ; CHECK-NEXT:   renamable $x2 = VBCST_16 killed renamable $r0
  ; CHECK-NEXT:   renamable $r0 = MOVXM -19424
  ; CHECK-NEXT:   renamable $x4 = VBCST_16 killed renamable $r0
  ; CHECK-NEXT:   renamable $r0 = MOVXM 32704
  ; CHECK-NEXT:   renamable $x6 = VBCST_16 killed renamable $r0
  ; CHECK-NEXT:   renamable $r0 = MOVXM 16256
  ; CHECK-NEXT:   renamable $x8 = VBCST_16 killed renamable $r0
  ; CHECK-NEXT:   renamable $r0 = MOVXM 46208
  ; CHECK-NEXT:   renamable $x10 = VBCST_16 killed renamable $r0
  ; CHECK-NEXT:   renamable $r0 = MOVXM 46144
  ; CHECK-NEXT:   renamable $x1 = VBCST_16 killed renamable $r0
  ; CHECK-NEXT:   renamable $r0 = MOVXM 46080
  ; CHECK-NEXT:   renamable $x3 = VBCST_16 killed renamable $r0
  ; CHECK-NEXT:   renamable $r0 = MOVXM 45952
  ; CHECK-NEXT:   renamable $bmll0 = COPY killed renamable $x5
  ; CHECK-NEXT:   renamable $x5 = VBCST_16 killed renamable $r0
  ; CHECK-NEXT:   renamable $r0 = MOV_RLC_imm11_pseudo 1
  ; CHECK-NEXT:   renamable $x7 = VBCST_16 renamable $r16
  ; CHECK-NEXT:   renamable $bmlh0 = COPY renamable $bmll0
  ; CHECK-NEXT:   renamable $x9 = VBCST_16 killed renamable $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $bmll2, $cml0:0x000000000000000C, $r16, $x1, $x2, $x3, $x4, $x5, $x6, $x7, $x8, $x9, $x10
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $x11 = VCONV_bf16_fp32_mv_x_srs_bf renamable $cml0, implicit-def dead $srf2fflags, implicit $crf2fmask, implicit $crrnd
  ; CHECK-NEXT:   renamable $x0 = COPY renamable $bmll2
  ; CHECK-NEXT:   renamable $r17 = VGE_bf16 renamable $x11, killed renamable $x0
  ; CHECK-NEXT:   renamable $x0 = VSEL_16 renamable $x7, renamable $x10, killed renamable $r17
  ; CHECK-NEXT:   renamable $r17 = VGE_bf16 renamable $x11, renamable $x2
  ; CHECK-NEXT:   renamable $r18 = VGE_bf16 renamable $x11, renamable $x4
  ; CHECK-NEXT:   renamable $r19 = VGE_bf16 renamable $x11, renamable $x6
  ; CHECK-NEXT:   renamable $r20 = VGE_bf16 killed renamable $x11, renamable $x8
  ; CHECK-NEXT:   renamable $x0 = VSEL_16 killed renamable $x0, renamable $x1, killed renamable $r17
  ; CHECK-NEXT:   renamable $x0 = VSEL_16 killed renamable $x0, renamable $x3, killed renamable $r18
  ; CHECK-NEXT:   renamable $x0 = VSEL_16 killed renamable $x0, renamable $x5, killed renamable $r19
  ; CHECK-NEXT:   renamable $x0 = VSEL_16 killed renamable $x0, renamable $x7, killed renamable $r20
  ; CHECK-NEXT:   renamable $x0 = VSEL_16 killed renamable $x0, renamable $x9, renamable $r16
  ; CHECK-NEXT:   dead renamable $dm1 = VMUL_f_vmul_bf_vmul_bf_core_X_X renamable $x7, killed renamable $x0, renamable $r16, implicit-def dead $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  bb.0:
    successors: %bb.1(0x80000000)

    %36:ers16 = MOV_RLC_imm11_pseudo 0
    %40:vec512 = VBCST_32 %36
    %58:er = MOVXM -19312
    %4:vec512 = VBCST_16 %58
    %57:er = MOVXM -19360
    %7:vec512 = VBCST_16 %57
    %56:er = MOVXM -19424
    %10:vec512 = VBCST_16 %56
    %55:er = MOVXM 32704
    %13:vec512 = VBCST_16 %55
    %54:er = MOVXM 16256
    %16:vec512 = VBCST_16 %54
    %47:er = MOVXM 46208
    %21:vec512 = VBCST_16 %47
    %48:er = MOVXM 46144
    %24:vec512 = VBCST_16 %48
    %49:er = MOVXM 46080
    %27:vec512 = VBCST_16 %49
    %50:er = MOVXM 45952
    undef %1.sub_512_acc_lo:acc1024 = COPY %40
    %30:vec512 = VBCST_16 %50
    %51:er = MOV_RLC_imm11_pseudo 1
    %19:vec512 = VBCST_16 %36
    %1.sub_512_acc_hi:acc1024 = COPY %1.sub_512_acc_lo
    %34:vec512 = VBCST_16 %51

  bb.1:
    successors: %bb.1(0x80000000)

    %0:vec512 = VCONV_bf16_fp32_mv_x_srs_bf %1, implicit-def dead $srf2fflags, implicit $crf2fmask, implicit $crrnd
    %3:ers16 = VGE_bf16 %0, %4
    %18:vec512 = VSEL_16 %19, %21, %3
    %6:ers16 = VGE_bf16 %0, %7
    %9:ers16 = VGE_bf16 %0, %10
    %12:ers16 = VGE_bf16 %0, %13
    %15:ers16 = VGE_bf16 %0, %16
    %23:vec512 = VSEL_16 %18, %24, %6
    %26:vec512 = VSEL_16 %23, %27, %9
    %29:vec512 = VSEL_16 %26, %30, %12
    %32:vec512 = VSEL_16 %29, %19, %15
    %33:vec512 = VSEL_16 %32, %34, %36
    dead %61:edm = VMUL_f_vmul_bf_vmul_bf_core_X_X %19, %33, %36, implicit-def dead $srfpflags, implicit $crfpmask
    PseudoJ_jump_imm %bb.1

...
