# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
#
#
# This file tests AIE Spill Slot Optimization (aie-spill-slot-opt).
#
# The pass uses a two-phase approach:
#   Phase 1 (Analysis): Collect spill/reload info, compute liveness, and
#                       determine per-subreg decomposition details.
#   Phase 2 (Rewrite):  Emit decomposed instructions with lazily-created
#                       replacement slots, ensuring slots are only allocated
#                       when actually used.
#
# =============================================================================
# Pass Behavior Summary
# =============================================================================
#
# - Analyzes liveness at spill/reload points
# - Decomposes large register spills (DM→CM→BM) to only store/reload live parts
# - Same offset → share replacement slot (StackSlotColoring ensures safety)
# - Undef subregs at spill time don't need storage (skipped during reload)
#
# =============================================================================

# RUN: llc -mtriple=aie2p --verify-machineinstrs \
# RUN:     -run-pass=aie-spill-slot-opt -o - %s | FileCheck %s

# RUN: llc -mtriple=aie2p --verify-machineinstrs \
# RUN:     -run-pass=aie-spill-slot-opt,prologepilog -o - %s | FileCheck %s --check-prefix=STACK

# =============================================================================
# Section 1: Liveness-based Decomposition Tests
# =============================================================================

---
# Test 1: Only CML live - should decompose DM spill to CM spill, then minimize
name:            decomp_only_cml_live
alignment:       16
tracksRegLiveness: true
stack:
  - { id: 0, type: spill-slot, size: 256, alignment: 64 }
body:             |
  ; CHECK-LABEL: name: decomp_only_cml_live
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $cml0 = IMPLICIT_DEF
  ; CHECK-NEXT:   VST_dmx_sts_bm_spill renamable $bmll0, %stack.1, implicit $sp :: (store (s512) into %stack.1)
  ; CHECK-NEXT:   VST_dmx_sts_bm_spill renamable $bmlh0, %stack.2, implicit $sp :: (store (s512) into %stack.2)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   liveins: $cml0:0x000000000000000C
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $bmll0 = VLDA_dmx_lda_bm_spill %stack.1, implicit $sp :: (load (s512) from %stack.1)
  ; CHECK-NEXT:   renamable $bmlh0 = VLDA_dmx_lda_bm_spill %stack.2, implicit $sp :: (load (s512) from %stack.2)
  ; CHECK-NEXT:   $r0 = COPY killed renamable $cml0
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
  ;
  ; STACK-LABEL: name: decomp_only_cml_live
  ; STACK: bb.0.entry:
  ; STACK-NEXT:   successors: %bb.1(0x80000000)
  ; STACK-NEXT: {{  $}}
  ; STACK-NEXT:   frame-setup PADDXM_pstm_sp_imm 128, implicit-def $sp, implicit $sp
  ; STACK-NEXT:   $cml0 = IMPLICIT_DEF
  ; STACK-NEXT:   VST_dmx_sts_bm_spill renamable $bmll0, -128, implicit $sp :: (store (s512) into %stack.1)
  ; STACK-NEXT:   VST_dmx_sts_bm_spill renamable $bmlh0, -64, implicit $sp :: (store (s512) into %stack.2)
  ; STACK-NEXT: {{  $}}
  ; STACK-NEXT: bb.1:
  ; STACK-NEXT:   liveins: $cml0:0x000000000000000C
  ; STACK-NEXT: {{  $}}
  ; STACK-NEXT:   renamable $bmll0 = VLDA_dmx_lda_bm_spill -128, implicit $sp :: (load (s512) from %stack.1)
  ; STACK-NEXT:   renamable $bmlh0 = VLDA_dmx_lda_bm_spill -64, implicit $sp :: (load (s512) from %stack.2)
  ; STACK-NEXT:   $r0 = COPY killed renamable $cml0
  ; STACK-NEXT:   frame-destroy PADDXM_pstm_sp_imm -128, implicit-def $sp, implicit $sp
  ; STACK-NEXT:   PseudoRET implicit $lr, implicit $r0
  bb.0.entry:
    successors: %bb.1

    $cml0 = IMPLICIT_DEF
    VST_DM_SPILL renamable $dm0, %stack.0, implicit $sp :: (store (s2048) into %stack.0, align 64)

  bb.1:
    liveins: $cml0:0x000000000000000C

    renamable $dm0 = VLDA_DM_SPILL %stack.0, implicit $sp :: (load (s2048) from %stack.0, align 64)
    $r0 = COPY killed renamable $cml0
    PseudoRET implicit $lr, implicit $r0
...

---
# Test 2: Only CMH live - should decompose DM spill to CM spill for CMH
name:            decomp_only_cmh_live
alignment:       16
tracksRegLiveness: true
stack:
  - { id: 0, type: spill-slot, size: 256, alignment: 64 }
body:             |
  ; CHECK-LABEL: name: decomp_only_cmh_live
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $cmh0 = IMPLICIT_DEF
  ; CHECK-NEXT:   VST_dmx_sts_bm_spill renamable $bmhl0, %stack.1, implicit $sp :: (store (s512) into %stack.1)
  ; CHECK-NEXT:   VST_dmx_sts_bm_spill renamable $bmhh0, %stack.2, implicit $sp :: (store (s512) into %stack.2)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   liveins: $cmh0:0x0000000018000000
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $bmhl0 = VLDA_dmx_lda_bm_spill %stack.1, implicit $sp :: (load (s512) from %stack.1)
  ; CHECK-NEXT:   renamable $bmhh0 = VLDA_dmx_lda_bm_spill %stack.2, implicit $sp :: (load (s512) from %stack.2)
  ; CHECK-NEXT:   $r0 = COPY killed renamable $cmh0
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
  ;
  ; STACK-LABEL: name: decomp_only_cmh_live
  ; STACK: bb.0.entry:
  ; STACK-NEXT:   successors: %bb.1(0x80000000)
  ; STACK-NEXT: {{  $}}
  ; STACK-NEXT:   frame-setup PADDXM_pstm_sp_imm 128, implicit-def $sp, implicit $sp
  ; STACK-NEXT:   $cmh0 = IMPLICIT_DEF
  ; STACK-NEXT:   VST_dmx_sts_bm_spill renamable $bmhl0, -128, implicit $sp :: (store (s512) into %stack.1)
  ; STACK-NEXT:   VST_dmx_sts_bm_spill renamable $bmhh0, -64, implicit $sp :: (store (s512) into %stack.2)
  ; STACK-NEXT: {{  $}}
  ; STACK-NEXT: bb.1:
  ; STACK-NEXT:   liveins: $cmh0:0x0000000018000000
  ; STACK-NEXT: {{  $}}
  ; STACK-NEXT:   renamable $bmhl0 = VLDA_dmx_lda_bm_spill -128, implicit $sp :: (load (s512) from %stack.1)
  ; STACK-NEXT:   renamable $bmhh0 = VLDA_dmx_lda_bm_spill -64, implicit $sp :: (load (s512) from %stack.2)
  ; STACK-NEXT:   $r0 = COPY killed renamable $cmh0
  ; STACK-NEXT:   frame-destroy PADDXM_pstm_sp_imm -128, implicit-def $sp, implicit $sp
  ; STACK-NEXT:   PseudoRET implicit $lr, implicit $r0
  bb.0.entry:
    successors: %bb.1

    $cmh0 = IMPLICIT_DEF
    VST_DM_SPILL renamable $dm0, %stack.0, implicit $sp :: (store (s2048) into %stack.0, align 64)

  bb.1:
    liveins: $cmh0:0x0000000018000000

    renamable $dm0 = VLDA_DM_SPILL %stack.0, implicit $sp :: (load (s2048) from %stack.0, align 64)
    $r0 = COPY killed renamable $cmh0
    PseudoRET implicit $lr, implicit $r0
...

---
# Test 3: Both subregs live - decomposes to 4 BM spills, 4 separate slots
name:            decomp_both_subregs_live
alignment:       16
tracksRegLiveness: true
stack:
  - { id: 0, type: spill-slot, size: 256, alignment: 64 }
body:             |
  ; CHECK-LABEL: name: decomp_both_subregs_live
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $dm0 = IMPLICIT_DEF
  ; CHECK-NEXT:   VST_dmx_sts_bm_spill renamable $bmll0, %stack.1, implicit $sp :: (store (s512) into %stack.1)
  ; CHECK-NEXT:   VST_dmx_sts_bm_spill renamable $bmlh0, %stack.2, implicit $sp :: (store (s512) into %stack.2)
  ; CHECK-NEXT:   VST_dmx_sts_bm_spill renamable $bmhl0, %stack.3, implicit $sp :: (store (s512) into %stack.3)
  ; CHECK-NEXT:   VST_dmx_sts_bm_spill renamable $bmhh0, %stack.4, implicit $sp :: (store (s512) into %stack.4)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   liveins: $dm0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $bmll0 = VLDA_dmx_lda_bm_spill %stack.1, implicit $sp :: (load (s512) from %stack.1)
  ; CHECK-NEXT:   renamable $bmlh0 = VLDA_dmx_lda_bm_spill %stack.2, implicit $sp :: (load (s512) from %stack.2)
  ; CHECK-NEXT:   renamable $bmhl0 = VLDA_dmx_lda_bm_spill %stack.3, implicit $sp :: (load (s512) from %stack.3)
  ; CHECK-NEXT:   renamable $bmhh0 = VLDA_dmx_lda_bm_spill %stack.4, implicit $sp :: (load (s512) from %stack.4)
  ; CHECK-NEXT:   $r0 = COPY killed renamable $cml0
  ; CHECK-NEXT:   $r1 = COPY killed renamable $cmh0
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0, implicit $r1
  ;
  ; STACK-LABEL: name: decomp_both_subregs_live
  ; STACK: bb.0.entry:
  ; STACK-NEXT:   successors: %bb.1(0x80000000)
  ; STACK-NEXT: {{  $}}
  ; STACK-NEXT:   frame-setup PADDXM_pstm_sp_imm 256, implicit-def $sp, implicit $sp
  ; STACK-NEXT:   $dm0 = IMPLICIT_DEF
  ; STACK-NEXT:   VST_dmx_sts_bm_spill renamable $bmll0, -256, implicit $sp :: (store (s512) into %stack.1)
  ; STACK-NEXT:   VST_dmx_sts_bm_spill renamable $bmlh0, -192, implicit $sp :: (store (s512) into %stack.2)
  ; STACK-NEXT:   VST_dmx_sts_bm_spill renamable $bmhl0, -128, implicit $sp :: (store (s512) into %stack.3)
  ; STACK-NEXT:   VST_dmx_sts_bm_spill renamable $bmhh0, -64, implicit $sp :: (store (s512) into %stack.4)
  ; STACK-NEXT: {{  $}}
  ; STACK-NEXT: bb.1:
  ; STACK-NEXT:   liveins: $dm0
  ; STACK-NEXT: {{  $}}
  ; STACK-NEXT:   renamable $bmll0 = VLDA_dmx_lda_bm_spill -256, implicit $sp :: (load (s512) from %stack.1)
  ; STACK-NEXT:   renamable $bmlh0 = VLDA_dmx_lda_bm_spill -192, implicit $sp :: (load (s512) from %stack.2)
  ; STACK-NEXT:   renamable $bmhl0 = VLDA_dmx_lda_bm_spill -128, implicit $sp :: (load (s512) from %stack.3)
  ; STACK-NEXT:   renamable $bmhh0 = VLDA_dmx_lda_bm_spill -64, implicit $sp :: (load (s512) from %stack.4)
  ; STACK-NEXT:   $r0 = COPY killed renamable $cml0
  ; STACK-NEXT:   $r1 = COPY killed renamable $cmh0
  ; STACK-NEXT:   frame-destroy PADDXM_pstm_sp_imm -256, implicit-def $sp, implicit $sp
  ; STACK-NEXT:   PseudoRET implicit $lr, implicit $r0, implicit $r1
  bb.0.entry:
    successors: %bb.1

    $dm0 = IMPLICIT_DEF
    VST_DM_SPILL renamable $dm0, %stack.0, implicit $sp :: (store (s2048) into %stack.0, align 64)

  bb.1:
    liveins: $dm0

    renamable $dm0 = VLDA_DM_SPILL %stack.0, implicit $sp :: (load (s2048) from %stack.0, align 64)
    $r0 = COPY killed renamable $cml0
    $r1 = COPY killed renamable $cmh0
    PseudoRET implicit $lr, implicit $r0, implicit $r1
...

---
# Test 4: Only BMLL live - recursive decomposition DM -> CML -> BMLL
name:            decomp_only_bmll_live
alignment:       16
tracksRegLiveness: true
stack:
  - { id: 0, type: spill-slot, size: 256, alignment: 64 }
body:             |
  ; CHECK-LABEL: name: decomp_only_bmll_live
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $bmll0 = IMPLICIT_DEF
  ; CHECK-NEXT:   VST_dmx_sts_bm_spill renamable $bmll0, %stack.1, implicit $sp :: (store (s512) into %stack.1)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   liveins: $bmll0:0x0000000000000004
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $bmll0 = VLDA_dmx_lda_bm_spill %stack.1, implicit $sp :: (load (s512) from %stack.1)
  ; CHECK-NEXT:   $r0 = COPY killed renamable $bmll0
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
  ;
  ; STACK-LABEL: name: decomp_only_bmll_live
  ; STACK: bb.0.entry:
  ; STACK-NEXT:   successors: %bb.1(0x80000000)
  ; STACK-NEXT: {{  $}}
  ; STACK-NEXT:   frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
  ; STACK-NEXT:   $bmll0 = IMPLICIT_DEF
  ; STACK-NEXT:   VST_dmx_sts_bm_spill renamable $bmll0, -64, implicit $sp :: (store (s512) into %stack.1)
  ; STACK-NEXT: {{  $}}
  ; STACK-NEXT: bb.1:
  ; STACK-NEXT:   liveins: $bmll0:0x0000000000000004
  ; STACK-NEXT: {{  $}}
  ; STACK-NEXT:   renamable $bmll0 = VLDA_dmx_lda_bm_spill -64, implicit $sp :: (load (s512) from %stack.1)
  ; STACK-NEXT:   $r0 = COPY killed renamable $bmll0
  ; STACK-NEXT:   frame-destroy PADDXM_pstm_sp_imm -64, implicit-def $sp, implicit $sp
  ; STACK-NEXT:   PseudoRET implicit $lr, implicit $r0
  bb.0.entry:
    successors: %bb.1

    $bmll0 = IMPLICIT_DEF
    VST_DM_SPILL renamable $dm0, %stack.0, implicit $sp :: (store (s2048) into %stack.0, align 64)

  bb.1:
    liveins: $bmll0:0x0000000000000004

    renamable $dm0 = VLDA_DM_SPILL %stack.0, implicit $sp :: (load (s2048) from %stack.0, align 64)
    $r0 = COPY killed renamable $bmll0
    PseudoRET implicit $lr, implicit $r0
...

---
# Test 5: BMLL and CMH live - partial decomposition
name:            decomp_bmll_cmh_live
alignment:       16
tracksRegLiveness: true
stack:
  - { id: 0, type: spill-slot, size: 256, alignment: 64 }
body:             |
  ; CHECK-LABEL: name: decomp_bmll_cmh_live
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $bmll0 = IMPLICIT_DEF
  ; CHECK-NEXT:   $cmh0 = IMPLICIT_DEF
  ; CHECK-NEXT:   VST_dmx_sts_bm_spill renamable $bmll0, %stack.1, implicit $sp :: (store (s512) into %stack.1)
  ; CHECK-NEXT:   VST_dmx_sts_bm_spill renamable $bmhl0, %stack.2, implicit $sp :: (store (s512) into %stack.2)
  ; CHECK-NEXT:   VST_dmx_sts_bm_spill renamable $bmhh0, %stack.3, implicit $sp :: (store (s512) into %stack.3)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   liveins: $bmll0:0x0000000000000004
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $bmll0 = VLDA_dmx_lda_bm_spill %stack.1, implicit $sp :: (load (s512) from %stack.1)
  ; CHECK-NEXT:   $r0 = COPY killed renamable $bmll0
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0
  ;
  ; STACK-LABEL: name: decomp_bmll_cmh_live
  ; STACK: bb.0.entry:
  ; STACK-NEXT:   successors: %bb.1(0x80000000)
  ; STACK-NEXT: {{  $}}
  ; STACK-NEXT:   frame-setup PADDXM_pstm_sp_imm 192, implicit-def $sp, implicit $sp
  ; STACK-NEXT:   $bmll0 = IMPLICIT_DEF
  ; STACK-NEXT:   $cmh0 = IMPLICIT_DEF
  ; STACK-NEXT:   VST_dmx_sts_bm_spill renamable $bmll0, -192, implicit $sp :: (store (s512) into %stack.1)
  ; STACK-NEXT:   VST_dmx_sts_bm_spill renamable $bmhl0, -128, implicit $sp :: (store (s512) into %stack.2)
  ; STACK-NEXT:   VST_dmx_sts_bm_spill renamable $bmhh0, -64, implicit $sp :: (store (s512) into %stack.3)
  ; STACK-NEXT: {{  $}}
  ; STACK-NEXT: bb.1:
  ; STACK-NEXT:   liveins: $bmll0:0x0000000000000004
  ; STACK-NEXT: {{  $}}
  ; STACK-NEXT:   renamable $bmll0 = VLDA_dmx_lda_bm_spill -192, implicit $sp :: (load (s512) from %stack.1)
  ; STACK-NEXT:   $r0 = COPY killed renamable $bmll0
  ; STACK-NEXT:   frame-destroy PADDXM_pstm_sp_imm -192, implicit-def $sp, implicit $sp
  ; STACK-NEXT:   PseudoRET implicit $lr, implicit $r0
  bb.0.entry:
    successors: %bb.1

    $bmll0 = IMPLICIT_DEF
    $cmh0 = IMPLICIT_DEF
    VST_DM_SPILL renamable $dm0, %stack.0, implicit $sp :: (store (s2048) into %stack.0, align 64)

  bb.1:
    liveins: $bmll0:0x0000000000000004

    renamable $dm0 = VLDA_DM_SPILL %stack.0, implicit $sp :: (load (s2048) from %stack.0, align 64)
    $r0 = COPY killed renamable $bmll0
    PseudoRET implicit $lr, implicit $r0
...

---
# Test 6: Multiple spills same slot with different live subregs
name:            decomp_multiple_spills_same_slot
alignment:       16
tracksRegLiveness: true
stack:
  - { id: 0, type: spill-slot, size: 256, alignment: 64 }
body:             |
  ; CHECK-LABEL: name: decomp_multiple_spills_same_slot
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $cml0 = IMPLICIT_DEF
  ; CHECK-NEXT:   VST_dmx_sts_bm_spill renamable $bmll0, %stack.1, implicit $sp :: (store (s512) into %stack.1)
  ; CHECK-NEXT:   VST_dmx_sts_bm_spill renamable $bmlh0, %stack.2, implicit $sp :: (store (s512) into %stack.2)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT:   liveins: $cml0:0x000000000000000C
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $bmll0 = VLDA_dmx_lda_bm_spill %stack.1, implicit $sp :: (load (s512) from %stack.1)
  ; CHECK-NEXT:   renamable $bmlh0 = VLDA_dmx_lda_bm_spill %stack.2, implicit $sp :: (load (s512) from %stack.2)
  ; CHECK-NEXT:   renamable $r0 = COPY killed renamable $cml0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $cmh0 = IMPLICIT_DEF
  ; CHECK-NEXT:   VST_dmx_sts_bm_spill renamable $bmhl0, %stack.3, implicit $sp :: (store (s512) into %stack.3)
  ; CHECK-NEXT:   VST_dmx_sts_bm_spill renamable $bmhh0, %stack.4, implicit $sp :: (store (s512) into %stack.4)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   liveins: $r0, $cmh0:0x0000000018000000
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $bmhl0 = VLDA_dmx_lda_bm_spill %stack.3, implicit $sp :: (load (s512) from %stack.3)
  ; CHECK-NEXT:   renamable $bmhh0 = VLDA_dmx_lda_bm_spill %stack.4, implicit $sp :: (load (s512) from %stack.4)
  ; CHECK-NEXT:   $r1 = COPY killed renamable $cmh0
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r0, implicit $r1
  ;
  ; STACK-LABEL: name: decomp_multiple_spills_same_slot
  ; STACK: bb.0.entry:
  ; STACK-NEXT:   successors: %bb.1(0x80000000)
  ; STACK-NEXT: {{  $}}
  ; STACK-NEXT:   frame-setup PADDXM_pstm_sp_imm 256, implicit-def $sp, implicit $sp
  ; STACK-NEXT:   $cml0 = IMPLICIT_DEF
  ; STACK-NEXT:   VST_dmx_sts_bm_spill renamable $bmll0, -256, implicit $sp :: (store (s512) into %stack.1)
  ; STACK-NEXT:   VST_dmx_sts_bm_spill renamable $bmlh0, -192, implicit $sp :: (store (s512) into %stack.2)
  ; STACK-NEXT: {{  $}}
  ; STACK-NEXT: bb.1:
  ; STACK-NEXT:   successors: %bb.2(0x80000000)
  ; STACK-NEXT:   liveins: $cml0:0x000000000000000C
  ; STACK-NEXT: {{  $}}
  ; STACK-NEXT:   renamable $bmll0 = VLDA_dmx_lda_bm_spill -256, implicit $sp :: (load (s512) from %stack.1)
  ; STACK-NEXT:   renamable $bmlh0 = VLDA_dmx_lda_bm_spill -192, implicit $sp :: (load (s512) from %stack.2)
  ; STACK-NEXT:   renamable $r0 = COPY killed renamable $cml0
  ; STACK-NEXT: {{  $}}
  ; STACK-NEXT: bb.2:
  ; STACK-NEXT:   successors: %bb.3(0x80000000)
  ; STACK-NEXT:   liveins: $r0
  ; STACK-NEXT: {{  $}}
  ; STACK-NEXT:   $cmh0 = IMPLICIT_DEF
  ; STACK-NEXT:   VST_dmx_sts_bm_spill renamable $bmhl0, -128, implicit $sp :: (store (s512) into %stack.3)
  ; STACK-NEXT:   VST_dmx_sts_bm_spill renamable $bmhh0, -64, implicit $sp :: (store (s512) into %stack.4)
  ; STACK-NEXT: {{  $}}
  ; STACK-NEXT: bb.3:
  ; STACK-NEXT:   liveins: $r0, $cmh0:0x0000000018000000
  ; STACK-NEXT: {{  $}}
  ; STACK-NEXT:   renamable $bmhl0 = VLDA_dmx_lda_bm_spill -128, implicit $sp :: (load (s512) from %stack.3)
  ; STACK-NEXT:   renamable $bmhh0 = VLDA_dmx_lda_bm_spill -64, implicit $sp :: (load (s512) from %stack.4)
  ; STACK-NEXT:   $r1 = COPY killed renamable $cmh0
  ; STACK-NEXT:   frame-destroy PADDXM_pstm_sp_imm -256, implicit-def $sp, implicit $sp
  ; STACK-NEXT:   PseudoRET implicit $lr, implicit $r0, implicit $r1
  bb.0.entry:
    successors: %bb.1

    $cml0 = IMPLICIT_DEF
    VST_DM_SPILL renamable $dm0, %stack.0, implicit $sp :: (store (s2048) into %stack.0, align 64)

  bb.1:
    successors: %bb.2
    liveins: $cml0:0x000000000000000C

    renamable $dm0 = VLDA_DM_SPILL %stack.0, implicit $sp :: (load (s2048) from %stack.0, align 64)
    renamable $r0 = COPY killed renamable $cml0

  bb.2:
    successors: %bb.3
    liveins: $r0

    $cmh0 = IMPLICIT_DEF
    VST_DM_SPILL renamable $dm0, %stack.0, implicit $sp :: (store (s2048) into %stack.0, align 64)

  bb.3:
    liveins: $r0, $cmh0:0x0000000018000000

    renamable $dm0 = VLDA_DM_SPILL %stack.0, implicit $sp :: (load (s2048) from %stack.0, align 64)
    $r1 = COPY killed renamable $cmh0
    PseudoRET implicit $lr, implicit $r0, implicit $r1
...

---
# Test 7: Reload without prior store - should not decompose
name:            decomp_reload_without_store
alignment:       16
tracksRegLiveness: true
stack:
  - { id: 0, type: spill-slot, size: 256, alignment: 64 }
body:             |
  bb.0.entry:
    liveins: $dm0:0x000000000000000C

    ; CHECK-LABEL: name: decomp_reload_without_store
    ; CHECK: liveins: $dm0:0x000000000000000C
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $dm0 = VLDA_DM_SPILL %stack.0, implicit $sp :: (load (s2048) from %stack.0, align 64)
    ; CHECK-NEXT: $r0 = COPY killed renamable $cml0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    ;
    ; STACK-LABEL: name: decomp_reload_without_store
    ; STACK: liveins: $dm0:0x000000000000000C
    ; STACK-NEXT: {{  $}}
    ; STACK-NEXT: frame-setup PADDXM_pstm_sp_imm 256, implicit-def $sp, implicit $sp
    ; STACK-NEXT: $bmll0 = VLDA_dmx_lda_bm_spill -256, implicit $sp :: (load (s512) from %stack.0)
    ; STACK-NEXT: $bmlh0 = VLDA_dmx_lda_bm_spill -192, implicit $sp :: (load (s512) from %stack.0 + 64)
    ; STACK-NEXT: $r0 = COPY killed renamable $cml0
    ; STACK-NEXT: frame-destroy PADDXM_pstm_sp_imm -256, implicit-def $sp, implicit $sp
    ; STACK-NEXT: PseudoRET implicit $lr, implicit $r0
    renamable $dm0 = VLDA_DM_SPILL %stack.0, implicit $sp :: (load (s2048) from %stack.0, align 64)
    $r0 = COPY killed renamable $cml0
    PseudoRET implicit $lr, implicit $r0
...

# =============================================================================
# Section 2: Stack Slot Minimization Tests
# =============================================================================

---
# Test 8: Simple vector spills should preserve stack size
name:            min_vector_spill_preserve_size
alignment:       16
tracksRegLiveness: true
stack:
  - { id: 0, type: spill-slot, size: 64, alignment: 64 }
body:             |
  bb.0:
    liveins: $x8

    ; CHECK-LABEL: name: min_vector_spill_preserve_size
    ; CHECK: liveins: $x8
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: VST_512_COMPOSED_REG_SPILL renamable $x8, %stack.0, implicit $sp :: (store (s512) into %stack.0)
    ; CHECK-NEXT: renamable $x8 = VLDA_512_COMPOSED_REG_SPILL %stack.0, implicit $sp :: (load (s512) from %stack.0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x8
    ;
    ; STACK-LABEL: name: min_vector_spill_preserve_size
    ; STACK: liveins: $x8
    ; STACK-NEXT: {{  $}}
    ; STACK-NEXT: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; STACK-NEXT: VST_512_COMPOSED_REG_SPILL renamable $x8, -64, implicit $sp :: (store (s512) into %stack.0)
    ; STACK-NEXT: renamable $x8 = VLDA_512_COMPOSED_REG_SPILL -64, implicit $sp :: (load (s512) from %stack.0)
    ; STACK-NEXT: frame-destroy PADDXM_pstm_sp_imm -64, implicit-def $sp, implicit $sp
    ; STACK-NEXT: PseudoRET implicit $lr, implicit $x8
    VST_512_COMPOSED_REG_SPILL renamable $x8, %stack.0, implicit $sp :: (store (s512) into %stack.0)
    renamable $x8 = VLDA_512_COMPOSED_REG_SPILL %stack.0, implicit $sp :: (load (s512) from %stack.0)

    PseudoRET implicit $lr, implicit $x8

...

---
# Test 9: Same offset (0), different registers -> share slot
name: min_same_offset_zero_share_slot
alignment: 16
legalized: true
tracksRegLiveness: true
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 16, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true }
body: |
  bb.0.entry:
    liveins: $l0, $d0

    ; CHECK-LABEL: name: min_same_offset_zero_share_slot
    ; CHECK: liveins: $l0, $d0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: ST_R_SPILL killed $r0, %stack.1, implicit $sp :: (store (s32) into %stack.1)
    ; CHECK-NEXT: ST_R_SPILL killed $r1, %stack.2, implicit $sp :: (store (s32) into %stack.2)
    ; CHECK-NEXT: $r0 = LDA_R_SPILL %stack.1, implicit $sp :: (load (s32) from %stack.1)
    ; CHECK-NEXT: $r1 = LDA_R_SPILL %stack.2, implicit $sp :: (load (s32) from %stack.2)
    ; CHECK-NEXT: ST_R_SPILL killed $m0, %stack.1, implicit $sp :: (store (s32) into %stack.1)
    ; CHECK-NEXT: ST_R_SPILL killed $dn0, %stack.3, implicit $sp :: (store (s32) into %stack.3)
    ; CHECK-NEXT: ST_R_SPILL killed $dj0, %stack.4, implicit $sp :: (store (s32) into %stack.4)
    ; CHECK-NEXT: ST_R_SPILL killed $dc0, %stack.5, implicit $sp :: (store (s32) into %stack.5)
    ; CHECK-NEXT: $m0 = LDA_R_SPILL %stack.1, implicit $sp :: (load (s32) from %stack.1)
    ; CHECK-NEXT: $dn0 = LDA_R_SPILL %stack.3, implicit $sp :: (load (s32) from %stack.3)
    ; CHECK-NEXT: $dj0 = LDA_R_SPILL %stack.4, implicit $sp :: (load (s32) from %stack.4)
    ; CHECK-NEXT: $dc0 = LDA_R_SPILL %stack.5, implicit $sp :: (load (s32) from %stack.5)
    ; CHECK-NEXT: RET implicit $lr, implicit $l0, implicit $d0
    ;
    ; STACK-LABEL: name: min_same_offset_zero_share_slot
    ; STACK: liveins: $l0, $d0
    ; STACK-NEXT: {{  $}}
    ; STACK-NEXT: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; STACK-NEXT: ST_dms_sts_spill killed $r0, -64, implicit $sp :: (store (s32) into %stack.1)
    ; STACK-NEXT: ST_dms_sts_spill killed $r1, -60, implicit $sp :: (store (s32) into %stack.2)
    ; STACK-NEXT: $r0 = LDA_dms_lda_spill -64, implicit $sp :: (load (s32) from %stack.1)
    ; STACK-NEXT: $r1 = LDA_dms_lda_spill -60, implicit $sp :: (load (s32) from %stack.2)
    ; STACK-NEXT: ST_dms_sts_spill killed $m0, -64, implicit $sp :: (store (s32) into %stack.1)
    ; STACK-NEXT: ST_dms_sts_spill killed $dn0, -56, implicit $sp :: (store (s32) into %stack.3)
    ; STACK-NEXT: ST_dms_sts_spill killed $dj0, -52, implicit $sp :: (store (s32) into %stack.4)
    ; STACK-NEXT: ST_dms_sts_spill killed $dc0, -48, implicit $sp :: (store (s32) into %stack.5)
    ; STACK-NEXT: $m0 = LDA_dms_lda_spill -64, implicit $sp :: (load (s32) from %stack.1)
    ; STACK-NEXT: $dn0 = LDA_dms_lda_spill -56, implicit $sp :: (load (s32) from %stack.3)
    ; STACK-NEXT: $dj0 = LDA_dms_lda_spill -52, implicit $sp :: (load (s32) from %stack.4)
    ; STACK-NEXT: $dc0 = LDA_dms_lda_spill -48, implicit $sp :: (load (s32) from %stack.5)
    ; STACK-NEXT: RET implicit $lr, implicit $l0, implicit $d0
    VST_L_SPILL killed $l0, %stack.0, implicit $sp :: (store (s64) into %stack.0, align 4)
    $l0 = VLDA_L_SPILL %stack.0, implicit $sp :: (load (s64) from %stack.0, align 4)


    ST_D_SPILL killed $d0, %stack.0, implicit $sp :: (store (s128) into %stack.0, align 4)
    $d0 = LDA_D_SPILL %stack.0, implicit $sp :: (load (s128) from %stack.0, align 4)

    RET implicit $lr, implicit $l0, implicit $d0
...

---
# Test 10: Work on fully materialized pseudo instructions.
name: full_materialized_pseudo_instrs
alignment: 16
legalized: true
tracksRegLiveness: true
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64,
      stack-id: default, callee-saved-register: '', callee-saved-restored: false }
body: |
  bb.0.entry:
    liveins: $x2

    ; CHECK-LABEL: name: full_materialized_pseudo_instrs
    ; CHECK: liveins: $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: VST_dmx_sts_x_spill $x2, %stack.0, implicit $sp :: (store (s512) into %stack.0)
    ; CHECK-NEXT: renamable $x0 = VLDA_dmx_lda_x_spill %stack.0, implicit $sp :: (load (s512) from %stack.0)
    ; CHECK-NEXT: RET implicit $lr, implicit $x0
    ;
    ; STACK-LABEL: name: full_materialized_pseudo_instrs
    ; STACK: liveins: $x2
    ; STACK-NEXT: {{  $}}
    ; STACK-NEXT: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; STACK-NEXT: VST_dmx_sts_x_spill $x2, -64, implicit $sp :: (store (s512) into %stack.0)
    ; STACK-NEXT: renamable $x0 = VLDA_dmx_lda_x_spill -64, implicit $sp :: (load (s512) from %stack.0)
    ; STACK-NEXT: RET implicit $lr, implicit $x0
    VST_dmx_sts_x_spill $x2, %stack.0, implicit $sp :: (store (s512) into %stack.0)
    renamable $x0 = VLDA_dmx_lda_x_spill %stack.0, implicit $sp :: (load (s512) from %stack.0)

    RET implicit $lr, implicit $x0
...


