# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
#

# RUN: llc -mtriple=aie2p --start-before=greedy --stop-after=virtregrewriter -o - -verify-machineinstrs  %s | FileCheck %s

# Spill before Copies within the same BB.

---
name:            spill-before-copies
tracksRegLiveness: true
frameInfo:
  adjustsStack:    true
body:             |
  ; CHECK-LABEL: name: spill-before-copies
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $r0 = MOV_RLC_imm11_pseudo 0
  ; CHECK-NEXT:   renamable $m0 = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   renamable $x0 = VBCST_16 killed renamable $r0
  ; CHECK-NEXT:   renamable $dj0 = MOV_PD_imm11_pseudo 64
  ; CHECK-NEXT:   renamable $dn0 = COPY renamable $m0
  ; CHECK-NEXT:   VST_512_COMPOSED_REG_SPILL renamable $x0, %stack.2, implicit $sp :: (store (s512) into %stack.2)
  ; CHECK-NEXT:   renamable $dc0 = COPY renamable $m0
  ; CHECK-NEXT:   renamable $dc1 = COPY renamable $m0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $d0:0x0000000000200E00, $d1:0x0000000000000200, $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   VST_512_COMPOSED_REG_SPILL killed renamable $x0, %stack.3, implicit $sp :: (store (s512) into %stack.3)
  ; CHECK-NEXT:   ST_D_SPILL renamable $d1, %stack.1, implicit $sp :: (store (s32) into %stack.1)
  ; CHECK-NEXT:   renamable $p0 = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   $r1 = MOV_RLC_imm11_pseudo 1
  ; CHECK-NEXT:   $r2 = MOV_RLC_imm11_pseudo 0
  ; CHECK-NEXT:   dead $p0, $dc0 = PADD_2D_pseudo_split killed $p0, $m0, $dn0, $dj0, $dc0
  ; CHECK-NEXT:   ST_D_SPILL killed renamable $d0, %stack.0, implicit $sp :: (store (s128) into %stack.0, align 4)
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoJL &__umodsi3, csr_aie2p, implicit-def $lr, implicit killed $r1, implicit killed $r2, implicit-def $r0
  ; CHECK-NEXT:   renamable $dc1 = LDA_R_SPILL %stack.1, implicit $sp :: (load (s32) from %stack.1)
  ; CHECK-NEXT:   renamable $d0 = LDA_D_SPILL %stack.0, implicit $sp :: (load (s128) from %stack.0, align 4)
  ; CHECK-NEXT:   renamable $r0 = EQZ killed renamable $r0
  ; CHECK-NEXT:   renamable $x0 = VLDA_dmx_lda_x_spill %stack.2, implicit $sp :: (load (s512) from %stack.2)
  ; CHECK-NEXT:   renamable $x0 = VINSERT_16_mIdxImm0 killed renamable $x0, killed renamable $r0
  ; CHECK-NEXT:   renamable $p0 = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   renamable $x2 = VLDA_dmx_lda_x_spill %stack.3, implicit $sp :: (load (s512) from %stack.3)
  ; CHECK-NEXT:   renamable $x2 = VBOR killed renamable $x0, killed renamable $x2
  ; CHECK-NEXT:   VST_dmx_sts_x_spill killed renamable $x2, %stack.3, implicit $sp :: (store (s512) into %stack.3)
  ; CHECK-NEXT:   renamable $x0 = VLDA_dmx_lda_x_spill %stack.3, implicit $sp :: (load (s512) from %stack.3)
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   renamable $m1 = COPY renamable $m0
  ; CHECK-NEXT:   renamable $dn1 = COPY renamable $dn0
  ; CHECK-NEXT:   renamable $dj1 = COPY renamable $dj0
  ; CHECK-NEXT:   dead $p0, $dc1 = PADD_2D_pseudo_split killed $p0, $m1, $dn1, $dj1, $dc1
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  bb.0:
    successors: %bb.1(0x80000000)

    %13:er = MOV_RLC_imm11_pseudo 0
    undef %36.sub_mod:ed = MOV_PD_imm11_pseudo 0
    %11:vec512 = VBCST_16 %13
    %36.sub_dim_stride:ed = MOV_PD_imm11_pseudo 64
    %36.sub_dim_size:ed = COPY %36.sub_mod
    %38:vec512 = COPY %11
    %36.sub_dim_count:ed = COPY %36.sub_mod
    undef %34.sub_dim_count:ed = COPY %36.sub_mod

  bb.1:
    successors: %bb.1(0x80000000)

    %4:ep = MOV_PD_imm11_pseudo 0
    $r1 = MOV_RLC_imm11_pseudo 1
    $r2 = MOV_RLC_imm11_pseudo 0
    dead %4:ep, %36.sub_dim_count:ed = PADD_2D_pseudo_split %4, %36.sub_mod, %36.sub_dim_size, %36.sub_dim_stride, %36.sub_dim_count
    ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    PseudoJL &__umodsi3, csr_aie2p, implicit-def $lr, implicit killed $r1, implicit killed $r2, implicit-def $r0
    %15:er = COPY killed $r0
    %33:er = EQZ %15
    %19:vec512 = VINSERT_16_mIdxImm0 %11, %33
    %22:ep = MOV_PD_imm11_pseudo 0
    %38:vec512 = VBOR %19, %38
    ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    %34.sub_mod:ed = COPY %36.sub_mod
    %34.sub_dim_size:ed = COPY %36.sub_dim_size
    %34.sub_dim_stride:ed = COPY %36.sub_dim_stride
    dead %22:ep, %34.sub_dim_count:ed = PADD_2D_pseudo_split %22, %34.sub_mod, %34.sub_dim_size, %34.sub_dim_stride, %34.sub_dim_count
    PseudoJ_jump_imm %bb.1

...
