# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
#
# RUN: llc -mtriple=aie2p -run-pass=aie-spill-slot-opt,prologepilog -o - %s \
# RUN:     | FileCheck %s


# This test verifies that AIE Spill Slot Optimization does not crash when a
# stack slot has mixed accesses: both vector (VST_dmx_sts_x_spill) and scalar (ST_R_SPILL).
#
# The fix: if any spill on a slot cannot be decomposed, skip the entire slot.
# This ensures we never partially rewrite a slot.

---
# Test: Mix of vector and scalar spills to same 64-byte slot.
# The all-or-nothing fix ensures we don't decompose this slot at all,
# because VST_dmx_sts_x_spill is not profitable (64 bytes = slot size).
name:            mixed_vector_scalar_spill_crash
alignment:       16
tracksRegLiveness: true
stack:
  - { id: 0, type: spill-slot, size: 64, alignment: 64 }
body:             |
  ; CHECK-LABEL: name: mixed_vector_scalar_spill_crash
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   VST_dmx_sts_x_spill killed renamable $x0, -64, implicit $sp :: (store (s512) into %stack.0)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   ST_dms_sts_spill killed $r0, -64, implicit $sp :: (store (s32) into %stack.0)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   $r6 = LDA_dms_lda_spill -64, implicit $sp :: (load (s32) from %stack.0)
  ; CHECK-NEXT:   renamable $x2 = VLDA_dmx_lda_x_spill -64, implicit $sp :: (load (s512) from %stack.0)
  ; CHECK-NEXT:   $r1 = COPY killed renamable $r6
  ; CHECK-NEXT:   frame-destroy PADDXM_pstm_sp_imm -64, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $r1, implicit $x2
  bb.0.entry:
    successors: %bb.1
    liveins: $x0

    VST_dmx_sts_x_spill killed renamable $x0, %stack.0, implicit $sp :: (store (s512) into %stack.0)

  bb.1:
    successors: %bb.2
    liveins: $r0

    ; 32-bit scalar spill - would be profitable, but slot is skipped
    ST_R_SPILL killed renamable $r0, %stack.0, implicit $sp :: (store (s32) into %stack.0)

  bb.2:
    ; 32-bit scalar reload
    renamable $r6 = LDA_R_SPILL %stack.0, implicit $sp :: (load (s32) from %stack.0)

    ; 512-bit vector reload
    renamable $x2 = VLDA_dmx_lda_x_spill %stack.0, implicit $sp :: (load (s512) from %stack.0)

    $r1 = COPY killed renamable $r6
    PseudoRET implicit $lr, implicit $r1, implicit $x2
...
