# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
#

# RUN: llc -mtriple=aie2p --start-before=register-coalescer --stop-after=virtregrewriter -o - -verify-machineinstrs  %s | FileCheck %s

# Only spill subreg cml register (1024 bits) instead of full dm register (2048 bits)
---
name:            spill-subreg
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: spill-subreg
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p2, $r0, $r1, $r2, $r3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $m0 = COPY $r0
  ; CHECK-NEXT:   renamable $dn0 = COPY $r1
  ; CHECK-NEXT:   renamable $dj0 = COPY $r2
  ; CHECK-NEXT:   renamable $dc0 = COPY $r3
  ; CHECK-NEXT:   $cml0, $p2, $dc0 = VLDA_2D_CONV_fp32_bf16_dmx_lda_ups_bf_split killed $p2, $m0, $dn0, $dj0, killed $dc0 :: (load (<32 x s16>))
  ; CHECK-NEXT:   VST_DM_SPILL renamable $dm0, %stack.0, implicit $sp :: (store (s2048) into %stack.0, align 64)
  ; CHECK-NEXT:   $cml1, $p2, $dc0 = VLDA_2D_CONV_fp32_bf16_dmx_lda_ups_bf_split killed $p2, $m0, $dn0, $dj0, killed $dc0 :: (load (<32 x s16>))
  ; CHECK-NEXT:   $cml2, $p2, $dc0 = VLDA_2D_CONV_fp32_bf16_dmx_lda_ups_bf_split killed $p2, $m0, $dn0, $dj0, killed $dc0 :: (load (<32 x s16>))
  ; CHECK-NEXT:   $cml3, $p2, $dc0 = VLDA_2D_CONV_fp32_bf16_dmx_lda_ups_bf_split killed $p2, $m0, $dn0, $dj0, killed $dc0 :: (load (<32 x s16>))
  ; CHECK-NEXT:   renamable $x0 = IMPLICIT_DEF
  ; CHECK-NEXT:   renamable $x2 = IMPLICIT_DEF
  ; CHECK-NEXT:   renamable $r0 = IMPLICIT_DEF
  ; CHECK-NEXT:   $cml4, dead $p2, dead $dc0 = VLDA_2D_CONV_fp32_bf16_dmx_lda_ups_bf_split killed $p2, killed $m0, killed $dn0, killed $dj0, killed $dc0 :: (load (<32 x s16>))
  ; CHECK-NEXT:   renamable $p0 = IMPLICIT_DEF
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $dm1:0x000000000000000C, $dm2:0x000000000000000C, $dm3:0x000000000000000C, $dm4:0x000000000000000C, $p0, $r0, $x0, $x2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $dm0 = VLDA_DM_SPILL %stack.0, implicit $sp :: (load (s2048) from %stack.0, align 64)
  ; CHECK-NEXT:   renamable $dm0 = VMAC_f_vmac_bf_vmul_bf_core_X_X killed renamable $dm0, renamable $x0, renamable $x2, renamable $r0, implicit-def dead $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   renamable $p0 = VST_CONV_bf16_fp32_dmx_sts_srs_bf_pstm_nrm_imm killed renamable $cml0, killed renamable $p0, 64, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crrnd :: (store (<32 x s16>))
  ; CHECK-NEXT:   renamable $dm0 = VMAC_f_vmac_bf_vmul_bf_core_X_X renamable $dm1, renamable $x0, renamable $x2, renamable $r0, implicit-def dead $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   renamable $p0 = VST_CONV_bf16_fp32_dmx_sts_srs_bf_pstm_nrm_imm killed renamable $cml0, killed renamable $p0, 64, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crrnd :: (store (<32 x s16>))
  ; CHECK-NEXT:   renamable $dm0 = VMAC_f_vmac_bf_vmul_bf_core_X_X renamable $dm2, renamable $x0, renamable $x2, renamable $r0, implicit-def dead $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   renamable $p0 = VST_CONV_bf16_fp32_dmx_sts_srs_bf_pstm_nrm_imm killed renamable $cml0, killed renamable $p0, 64, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crrnd :: (store (<32 x s16>))
  ; CHECK-NEXT:   renamable $dm0 = VMAC_f_vmac_bf_vmul_bf_core_X_X renamable $dm3, renamable $x0, renamable $x2, renamable $r0, implicit-def dead $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   renamable $p0 = VST_CONV_bf16_fp32_dmx_sts_srs_bf_pstm_nrm_imm killed renamable $cml0, killed renamable $p0, 64, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crrnd :: (store (<32 x s16>))
  ; CHECK-NEXT:   renamable $dm0 = VMAC_f_vmac_bf_vmul_bf_core_X_X renamable $dm4, renamable $x0, renamable $x2, renamable $r0, implicit-def dead $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   renamable $p0 = VST_CONV_bf16_fp32_dmx_sts_srs_bf_pstm_nrm_imm killed renamable $cml0, killed renamable $p0, 64, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crrnd :: (store (<32 x s16>))
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  bb.0.entry:
    liveins: $r0, $r1, $r2, $r3, $p2

    %0:em = COPY $r0
    %1:edn = COPY $r1
    %2:edj = COPY $r2
    %3:edc = COPY $r3
    %4:ep_as_32bit = COPY $p2
    %5:ecml, %4:ep_as_32bit, %3:edc = VLDA_2D_CONV_fp32_bf16_dmx_lda_ups_bf_split %4, %0, %1, %2, %3 :: (load (<32 x s16>))
    %15:ecml, %4:ep_as_32bit, %3:edc = VLDA_2D_CONV_fp32_bf16_dmx_lda_ups_bf_split %4, %0, %1, %2, %3 :: (load (<32 x s16>))
    %25:ecml, %4:ep_as_32bit, %3:edc = VLDA_2D_CONV_fp32_bf16_dmx_lda_ups_bf_split %4, %0, %1, %2, %3 :: (load (<32 x s16>))
    %35:ecml, %4:ep_as_32bit, %3:edc = VLDA_2D_CONV_fp32_bf16_dmx_lda_ups_bf_split %4, %0, %1, %2, %3 :: (load (<32 x s16>))
    %45:ecml, %4:ep_as_32bit, %3:edc = VLDA_2D_CONV_fp32_bf16_dmx_lda_ups_bf_split %4, %0, %1, %2, %3 :: (load (<32 x s16>))
    %6:vec512 = IMPLICIT_DEF
    %7:vec512 = IMPLICIT_DEF
    %8:er = IMPLICIT_DEF
    %9:ep_as_32bit = IMPLICIT_DEF

  bb.1:
    undef %10.sub_1024_acc_lo:acc2048 = COPY %5
    undef %20.sub_1024_acc_lo:acc2048 = COPY %15
    undef %30.sub_1024_acc_lo:acc2048 = COPY %25
    undef %40.sub_1024_acc_lo:acc2048 = COPY %35
    undef %50.sub_1024_acc_lo:acc2048 = COPY %45
    %11:acc2048 = VMAC_f_vmac_bf_vmul_bf_core_X_X %10, %6, %7, %8, implicit-def dead $srfpflags, implicit $crfpmask
    %21:acc2048 = VMAC_f_vmac_bf_vmul_bf_core_X_X %20, %6, %7, %8, implicit-def dead $srfpflags, implicit $crfpmask
    %31:acc2048 = VMAC_f_vmac_bf_vmul_bf_core_X_X %30, %6, %7, %8, implicit-def dead $srfpflags, implicit $crfpmask
    %41:acc2048 = VMAC_f_vmac_bf_vmul_bf_core_X_X %40, %6, %7, %8, implicit-def dead $srfpflags, implicit $crfpmask
    %51:acc2048 = VMAC_f_vmac_bf_vmul_bf_core_X_X %50, %6, %7, %8, implicit-def dead $srfpflags, implicit $crfpmask
    %9:ep_as_32bit = VST_CONV_bf16_fp32_dmx_sts_srs_bf_pstm_nrm_imm %11.sub_1024_acc_lo, %9, 64, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crrnd :: (store (<32 x s16>))
    %9:ep_as_32bit = VST_CONV_bf16_fp32_dmx_sts_srs_bf_pstm_nrm_imm %21.sub_1024_acc_lo, %9, 64, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crrnd :: (store (<32 x s16>))
    %9:ep_as_32bit = VST_CONV_bf16_fp32_dmx_sts_srs_bf_pstm_nrm_imm %31.sub_1024_acc_lo, %9, 64, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crrnd :: (store (<32 x s16>))
    %9:ep_as_32bit = VST_CONV_bf16_fp32_dmx_sts_srs_bf_pstm_nrm_imm %41.sub_1024_acc_lo, %9, 64, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crrnd :: (store (<32 x s16>))
    %9:ep_as_32bit = VST_CONV_bf16_fp32_dmx_sts_srs_bf_pstm_nrm_imm %51.sub_1024_acc_lo, %9, 64, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crrnd :: (store (<32 x s16>))
    PseudoJ_jump_imm %bb.1
...
