# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
#

# RUN: llc -mtriple=aie2p --start-before=greedy --stop-after=virtregrewriter -o - -verify-machineinstrs  %s | FileCheck %s

# properly spill stacks and reload proper subregisters
---
name:            reg-sequence
alignment:       16
tracksRegLiveness: true
frameInfo:
  adjustsStack:    true
body:             |
  ; CHECK-LABEL: name: reg-sequence
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $r0 = MOV_RLC_imm11_pseudo 0
  ; CHECK-NEXT:   renamable $x0 = VBCST_16 killed renamable $r0
  ; CHECK-NEXT:   renamable $m0 = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   renamable $p6 = COPY $p0
  ; CHECK-NEXT:   renamable $dj0 = COPY renamable $m0
  ; CHECK-NEXT:   renamable $dn4 = COPY renamable $m0
  ; CHECK-NEXT:   renamable $dj1 = MOV_PD_imm11_pseudo 1
  ; CHECK-NEXT:   renamable $dn1 = COPY renamable $m0
  ; CHECK-NEXT:   renamable $dc4 = COPY renamable $m0
  ; CHECK-NEXT:   renamable $dc0 = COPY renamable $m0
  ; CHECK-NEXT:   renamable $p7 = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   VST_512_COMPOSED_REG_SPILL renamable $x0, %stack.8, implicit $sp :: (store (s512) into %stack.8)
  ; CHECK-NEXT:   renamable $dc1 = COPY renamable $m0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $dc0, $dc1, $dc4, $dj0, $dj1, $dn1, $dn4, $m0, $p6, $p7, $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   VST_512_COMPOSED_REG_SPILL killed renamable $x0, %stack.9, implicit $sp :: (store (s512) into %stack.9)
  ; CHECK-NEXT:   renamable $r0 = LDA_u16_idx_imm renamable $p7, 0 :: (load (s16) from `ptr null`, align 8)
  ; CHECK-NEXT:   renamable $p0 = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   $r1 = MOV_RLC_imm11_pseudo 1
  ; CHECK-NEXT:   $r2 = MOV_RLC_imm11_pseudo 0
  ; CHECK-NEXT:   renamable $dn0 = COPY killed renamable $r0
  ; CHECK-NEXT:   renamable $dj4 = COPY renamable $dj0
  ; CHECK-NEXT:   dead $p0, $dc0, $dc4 = PADD_3D_pseudo_split killed $p0, $m0, killed $dn0, $dj0, killed $dc0, undef $m4, $dn4, killed $dj4, killed $dc4
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   ST_R_SPILL killed renamable $dn4, %stack.4, implicit $sp :: (store (s32) into %stack.4)
  ; CHECK-NEXT:   ST_R_SPILL killed renamable $dc4, %stack.3, implicit $sp :: (store (s32) into %stack.3)
  ; CHECK-NEXT:   ST_R_SPILL killed renamable $m0, %stack.2, implicit $sp :: (store (s32) into %stack.2)
  ; CHECK-NEXT:   ST_R_SPILL killed renamable $dj0, %stack.1, implicit $sp :: (store (s32) into %stack.1)
  ; CHECK-NEXT:   ST_R_SPILL killed renamable $dc0, %stack.0, implicit $sp :: (store (s32) into %stack.0)
  ; CHECK-NEXT:   ST_R_SPILL killed renamable $dj1, %stack.7, implicit $sp :: (store (s32) into %stack.7)
  ; CHECK-NEXT:   ST_R_SPILL killed renamable $dn1, %stack.6, implicit $sp :: (store (s32) into %stack.6)
  ; CHECK-NEXT:   ST_R_SPILL killed renamable $dc1, %stack.5, implicit $sp :: (store (s32) into %stack.5)
  ; CHECK-NEXT:   PseudoJL &__umodsi3, csr_aie2p, implicit-def $lr, implicit killed $r1, implicit killed $r2, implicit-def $r0
  ; CHECK-NEXT:   renamable $dc1 = LDA_R_SPILL %stack.5, implicit $sp :: (load (s32) from %stack.5)
  ; CHECK-NEXT:   renamable $dn1 = LDA_R_SPILL %stack.6, implicit $sp :: (load (s32) from %stack.6)
  ; CHECK-NEXT:   renamable $dj1 = LDA_R_SPILL %stack.7, implicit $sp :: (load (s32) from %stack.7)
  ; CHECK-NEXT:   renamable $dc0 = LDA_R_SPILL %stack.0, implicit $sp :: (load (s32) from %stack.0)
  ; CHECK-NEXT:   renamable $dj0 = LDA_R_SPILL %stack.1, implicit $sp :: (load (s32) from %stack.1)
  ; CHECK-NEXT:   renamable $m0 = LDA_R_SPILL %stack.2, implicit $sp :: (load (s32) from %stack.2)
  ; CHECK-NEXT:   renamable $dc4 = LDA_R_SPILL %stack.3, implicit $sp :: (load (s32) from %stack.3)
  ; CHECK-NEXT:   renamable $dn4 = LDA_R_SPILL %stack.4, implicit $sp :: (load (s32) from %stack.4)
  ; CHECK-NEXT:   renamable $r0 = EQZ killed renamable $r0
  ; CHECK-NEXT:   renamable $x0 = VLDA_dmx_lda_x_spill %stack.8, implicit $sp :: (load (s512) from %stack.8)
  ; CHECK-NEXT:   renamable $x0 = VINSERT_16_mIdxImm0 killed renamable $x0, killed renamable $r0
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   renamable $x2 = VLDA_dmx_lda_x_spill %stack.9, implicit $sp :: (load (s512) from %stack.9)
  ; CHECK-NEXT:   renamable $x2 = VBOR killed renamable $x0, killed renamable $x2
  ; CHECK-NEXT:   VST_dmx_sts_x_spill killed renamable $x2, %stack.9, implicit $sp :: (store (s512) into %stack.9)
  ; CHECK-NEXT:   renamable $x0 = VLDA_dmx_lda_x_spill %stack.9, implicit $sp :: (load (s512) from %stack.9)
  ; CHECK-NEXT:   renamable $m1 = COPY renamable $m0
  ; CHECK-NEXT:   renamable $p0 = COPY renamable $p6
  ; CHECK-NEXT:   dead $p0, $dc1 = PADD_2D_pseudo_split killed $p0, killed $m1, $dn1, $dj1, killed $dc1
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $p0

    %0:er = MOV_RLC_imm11_pseudo 0
    %1:vec512 = VBCST_16 %0
    undef %2.sub_mod:eds = MOV_PD_imm11_pseudo 0
    %3:ep = COPY $p0
    %2.sub_dim_stride:eds = COPY %2.sub_mod
    %2.sub_hi_dim_then_sub_dim_size:eds = COPY %2.sub_mod
    undef %4.sub_dim_stride:ed = MOV_PD_imm11_pseudo 1
    %4.sub_dim_size:ed = COPY %2.sub_mod
    %2.sub_hi_dim_then_sub_dim_count:eds = COPY %2.sub_mod
    %2.sub_dim_count:eds = COPY %2.sub_mod
    %5:ep = MOV_PD_imm11_pseudo 0
    %6:vec512 = COPY %1
    %4.sub_dim_count:ed = COPY %2.sub_mod

  bb.1:
    successors: %bb.1(0x80000000)

    %7:er = LDA_u16_idx_imm %5, 0 :: (load (s16) from `ptr null`, align 8)
    %8:ep = MOV_PD_imm11_pseudo 0
    $r1 = MOV_RLC_imm11_pseudo 1
    $r2 = MOV_RLC_imm11_pseudo 0
    %2.sub_dim_size:eds = COPY %7
    %2.sub_hi_dim_then_sub_dim_stride:eds = COPY %2.sub_dim_stride
    dead %8:ep, %2.sub_dim_count:eds, %2.sub_hi_dim_then_sub_dim_count:eds = PADD_3D_pseudo_split %8, %2.sub_mod, %2.sub_dim_size, %2.sub_dim_stride, %2.sub_dim_count, undef %2.sub_hi_dim_then_sub_mod, %2.sub_hi_dim_then_sub_dim_size, %2.sub_hi_dim_then_sub_dim_stride, %2.sub_hi_dim_then_sub_dim_count
    ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    PseudoJL &__umodsi3, csr_aie2p, implicit-def $lr, implicit killed $r1, implicit killed $r2, implicit-def $r0
    %9:er = COPY killed $r0
    %10:er = EQZ %9
    %11:vec512 = VINSERT_16_mIdxImm0 %1, %10
    ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    %6:vec512 = VBOR %11, %6
    %4.sub_mod:ed = COPY %2.sub_mod
    %12:ep = COPY %3
    dead %12:ep, %4.sub_dim_count:ed = PADD_2D_pseudo_split %12, %4.sub_mod, %4.sub_dim_size, %4.sub_dim_stride, %4.sub_dim_count
    PseudoJ_jump_imm %bb.1

...
