# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
#
# Regression tests for AIE Spill Slot Optimization passes.
# These tests verify correct behavior and absence of crashes.

# RUN: llc -mtriple=aie2p --verify-machineinstrs \
# RUN:     -run-pass=aie-spill-slot-opt,prologepilog -o - %s | \
# RUN:     FileCheck %s

# =============================================================================
# Section 1: Spill Decomposition Regressions
# =============================================================================

---
# Test 1: Partial subreg definition - only CML defined, spill should handle correctly
name:            partial_def_scalar_spill
alignment:       16
tracksRegLiveness: true
stack:
  - { id: 0, type: spill-slot, size: 256, alignment: 64 }
body:             |
  ; CHECK-LABEL: name: partial_def_scalar_spill
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   frame-setup PADDXM_pstm_sp_imm 128, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   $cml3 = IMPLICIT_DEF
  ; CHECK-NEXT:   VST_dmx_sts_bm_spill killed renamable $bmll3, -128, implicit $sp :: (store (s512) into %stack.1)
  ; CHECK-NEXT:   VST_dmx_sts_bm_spill killed renamable $bmlh3, -64, implicit $sp :: (store (s512) into %stack.2)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   renamable $bmll2 = VLDA_dmx_lda_bm_spill -128, implicit $sp :: (load (s512) from %stack.1)
  ; CHECK-NEXT:   renamable $bmlh2 = VLDA_dmx_lda_bm_spill -64, implicit $sp :: (load (s512) from %stack.2)
  ; CHECK-NEXT:   frame-destroy PADDXM_pstm_sp_imm -128, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $dm2
  bb.0:

  $cml3 = IMPLICIT_DEF
  VST_DM_SPILL killed renamable $dm3, %stack.0, implicit $sp :: (store (s2048) into %stack.0, align 64)


  bb.1:
  renamable $dm2 = VLDA_DM_SPILL %stack.0, implicit $sp :: (load (s2048) from %stack.0, align 64)

  PseudoRET implicit $lr, implicit $dm2

...

---
# Test 2: Incremental subreg definitions - bmll0 then bmlh0 defined in sequence
# Only store instructions that are live at the spill location.
# Note: we do not want to store $cml0 in both spill stores, because part of
# the register is not defined!
name:            incremental_def_scalar_spill
alignment:       16
tracksRegLiveness: true
stack:
  - { id: 0, type: spill-slot, size: 256, alignment: 64 }
body:             |
  ; CHECK-LABEL: name: incremental_def_scalar_spill
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   frame-setup PADDXM_pstm_sp_imm 128, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   $bmll0 = IMPLICIT_DEF
  ; CHECK-NEXT:   VST_dmx_sts_bm_spill killed renamable $bmll0, -128, implicit $sp :: (store (s512) into %stack.1)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $bmlh0 = IMPLICIT_DEF
  ; CHECK-NEXT:   VST_dmx_sts_bm_spill killed renamable $bmlh0, -64, implicit $sp :: (store (s512) into %stack.2)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   renamable $bmll2 = VLDA_dmx_lda_bm_spill -128, implicit $sp :: (load (s512) from %stack.1)
  ; CHECK-NEXT:   renamable $bmlh2 = VLDA_dmx_lda_bm_spill -64, implicit $sp :: (load (s512) from %stack.2)
  ; CHECK-NEXT:   frame-destroy PADDXM_pstm_sp_imm -128, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit $dm2
  bb.0:

  $bmll0 = IMPLICIT_DEF
  VST_DM_SPILL killed renamable $dm0, %stack.0, implicit $sp :: (store (s2048) into %stack.0, align 64)


  bb.1:

  $bmlh0 = IMPLICIT_DEF
  VST_DM_SPILL killed renamable $dm0, %stack.0, implicit $sp :: (store (s2048) into %stack.0, align 64)

  bb.2:
  renamable $dm2 = VLDA_DM_SPILL %stack.0, implicit $sp :: (load (s2048) from %stack.0, align 64)

  PseudoRET implicit $lr, implicit $dm2

...



# =============================================================================
# Section 2: Stack Slot Minimization Regressions
# =============================================================================

---
# Test 3: Neutral scalar spills - simple R register spills should not increase stack size
# Verifies that for simple R register (32-bit scalar) spills, the stack minimization
# passes don't increase stack size. This is a neutral case where no decomposition
# opportunities exist.
#
# Expected behavior:
# - Original: 3 spill slots x 4 bytes = 12 bytes
# - After passes: 3 spill slots x 4 bytes = 12 bytes (same size, different FIs)
name:            neutral_scalar_spills
alignment:       16
tracksRegLiveness: true
stack:
  - { id: 0, type: spill-slot, size: 4, alignment: 4 }
  - { id: 1, type: spill-slot, size: 4, alignment: 4 }
  - { id: 2, type: spill-slot, size: 4, alignment: 4 }
body:             |
  bb.0:
  liveins: $r0, $r1, $r2


    ; CHECK-LABEL: name: neutral_scalar_spills
    ; CHECK: liveins: $r0, $r1, $r2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: ST_dms_sts_spill $r0, -64, implicit $sp :: (store (s32) into %stack.0)
    ; CHECK-NEXT: ST_dms_sts_spill $r1, -60, implicit $sp :: (store (s32) into %stack.1)
    ; CHECK-NEXT: ST_dms_sts_spill $r2, -56, implicit $sp :: (store (s32) into %stack.2)
    ; CHECK-NEXT: $r2 = LDA_dms_lda_spill -56, implicit $sp :: (load (s32) from %stack.2)
    ; CHECK-NEXT: $r1 = LDA_dms_lda_spill -64, implicit $sp :: (load (s32) from %stack.0)
    ; CHECK-NEXT: frame-destroy PADDXM_pstm_sp_imm -64, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r1, implicit $r2
  ST_R_SPILL $r0, %stack.0, implicit $sp :: (store (s32) into %stack.0)
  ST_R_SPILL $r1, %stack.1, implicit $sp :: (store (s32) into %stack.1)
  ST_R_SPILL $r2, %stack.2, implicit $sp :: (store (s32) into %stack.2)

  $r1 = LDA_R_SPILL %stack.1, implicit $sp :: (load (s32) from %stack.1)
  $r2 = LDA_R_SPILL %stack.2, implicit $sp :: (load (s32) from %stack.2)

  $r1 = LDA_R_SPILL %stack.0, implicit $sp :: (load (s32) from %stack.0)

  PseudoRET implicit $lr, implicit $r1, implicit $r2

...

---
# Test 4: Invalid frame index crash regression
# Verifies the fix for the dangling FI reference bug that caused:
#   llc: MIRPrinter.cpp:960: Assertion `ObjectInfo != StackObjectOperandMapping.end()
#        && "Invalid frame index"' failed.
#
# Root cause: Phase 4 (replaceStackInstructions) only updated FIs in instructions
# collected during Phase 1, but some instructions (added later or not scanned) still
# referenced old FIs. Phase 5 (removeOldStackSlots) then deleted those FIs, causing
# crashes in MIRPrinter.
#
# This test verifies:
# 1. The passes complete without crashes
# 2. Stack slot sizes are preserved correctly
name:            invalid_fi_regression
alignment:       16
tracksRegLiveness: true
stack:
  - { id: 0, type: spill-slot, size: 4, alignment: 4 }
  - { id: 1, type: spill-slot, size: 64, alignment: 64 }
  - { id: 2, type: spill-slot, size: 4, alignment: 4 }
  - { id: 3, type: spill-slot, size: 64, alignment: 64 }
  - { id: 4, type: spill-slot, size: 256, alignment: 64 }
body:             |
  bb.0:
  liveins: $r0, $x0, $dm0


    ; CHECK-LABEL: name: invalid_fi_regression
    ; CHECK: liveins: $r0, $x0, $dm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: frame-setup PADDXM_pstm_sp_imm 512, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: ST_dms_sts_spill $r0, -512, implicit $sp :: (store (s32) into %stack.0)
    ; CHECK-NEXT: VST_dmx_sts_x_spill $x0, -448, implicit $sp :: (store (s512) into %stack.1)
    ; CHECK-NEXT: VST_dmx_sts_bm_spill $bmll0, -256, implicit $sp :: (store (s512) into %stack.5)
    ; CHECK-NEXT: VST_dmx_sts_bm_spill $bmlh0, -192, implicit $sp :: (store (s512) into %stack.6)
    ; CHECK-NEXT: VST_dmx_sts_bm_spill $bmhl0, -128, implicit $sp :: (store (s512) into %stack.7)
    ; CHECK-NEXT: VST_dmx_sts_bm_spill $bmhh0, -64, implicit $sp :: (store (s512) into %stack.8)
    ; CHECK-NEXT: $r0 = LDA_dms_lda_spill -512, implicit $sp :: (load (s32) from %stack.0)
    ; CHECK-NEXT: $x0 = VLDA_dmx_lda_x_spill -448, implicit $sp :: (load (s512) from %stack.1)
    ; CHECK-NEXT: ST_dms_sts_spill $r0, -384, implicit $sp :: (store (s32) into %stack.2)
    ; CHECK-NEXT: VST_dmx_sts_x_spill $x0, -320, implicit $sp :: (store (s512) into %stack.3)
    ; CHECK-NEXT: frame-destroy PADDXM_pstm_sp_imm -512, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: PseudoRET implicit $lr
  ST_R_SPILL $r0, %stack.0, implicit $sp :: (store (s32) into %stack.0)
  VST_dmx_sts_x_spill $x0, %stack.1, implicit $sp :: (store (s512) into %stack.1)

  VST_DM_SPILL $dm0, %stack.4, implicit $sp :: (store (s2048) into %stack.4, align 64)

  $r0 = LDA_R_SPILL %stack.0, implicit $sp :: (load (s32) from %stack.0)
  $x0 = VLDA_dmx_lda_x_spill %stack.1, implicit $sp :: (load (s512) from %stack.1)
  $dm0 = VLDA_DM_SPILL %stack.4, implicit $sp :: (load (s2048) from %stack.4, align 64)

  ST_R_SPILL $r0, %stack.2, implicit $sp :: (store (s32) into %stack.2)
  VST_dmx_sts_x_spill $x0, %stack.3, implicit $sp :: (store (s512) into %stack.3)

  $r0 = LDA_R_SPILL %stack.2, implicit $sp :: (load (s32) from %stack.2)

  PseudoRET implicit $lr

...
