# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024-2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -O2 -mtriple=aie2p -verify-machineinstrs -run-pass=aie-split-instrs-replace %s -o - | FileCheck %s


---
name:            PADDA_2D_unused_livein
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $dc4, $dj4, $dn4, $m4, $p0, $r0

    ; CHECK-LABEL: name: PADDA_2D_unused_livein
    ; CHECK: liveins: $d4:0x0000000000200E00, $dc4, $dj4, $dn4, $m4, $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $m4 = COPY $r0
    ; CHECK-NEXT: $p0, $dc4 = PADDA_2D killed $p0, $d4
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $p0, implicit killed renamable $dc4
    renamable $m4 = COPY $r0
    $p0, $dc4 = PADDA_2D_split killed $p0, killed $m4, killed $dn4, killed $dj4, killed $dc4
    PseudoRET implicit $lr, implicit killed renamable $p0, implicit killed renamable $dc4
...

# Verify how liveins are rewritten when the sub-regs are defined in different
# BBs. Currently, we only update liveins in the the "use MBB".
---
name:            PADDA_2D_sources_in_multi_bb
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: PADDA_2D_sources_in_multi_bb
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; CHECK-NEXT:   liveins: $p0, $r0, $r1, $r2, $r3, $r4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $m4 = COPY $r0
  ; CHECK-NEXT:   renamable $dn4 = COPY $r1
  ; CHECK-NEXT:   renamable $dc4 = COPY $r3
  ; CHECK-NEXT:   PseudoJNZ killed renamable $r4, %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $r2, $dc4, $dn4, $m4, $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $dj4 = COPY killed renamable $r2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $r2, $dc4, $dn4, $m4, $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $dj4 = COPY killed renamable $dc4
  ; CHECK-NEXT:   renamable $dc4 = COPY killed renamable $r2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   liveins: $d4:0x0000000000200E00, $dc4, $dj4, $dn4, $m4, $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $p0, $dc4 = PADDA_2D killed $p0, $d4
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit killed renamable $p0, implicit killed renamable $dc4
  bb.0.entry:
    successors: %bb.2, %bb.1
    liveins: $p0, $r0, $r1, $r2, $r3, $r4

    renamable $m4 = COPY $r0
    renamable $dn4 = COPY $r1
    renamable $dc4 = COPY $r3
    PseudoJNZ killed renamable $r4, %bb.2

  bb.1:
    successors: %bb.3
    liveins: $r2, $dc4, $dn4, $m4, $p0
    renamable $dj4 = COPY killed renamable $r2
    PseudoJ_jump_imm %bb.3

  bb.2:
    successors: %bb.3
    liveins: $r2, $dc4, $dn4, $m4, $p0
    renamable $dj4 = COPY killed renamable $dc4
    renamable $dc4 = COPY killed renamable $r2

  bb.3:
    liveins: $dc4, $dj4, $dn4, $m4, $p0
    $p0, $dc4 = PADDA_2D_split killed $p0, killed $m4, killed $dn4, killed $dj4, killed $dc4
    PseudoRET implicit $lr, implicit killed renamable $p0, implicit killed renamable $dc4
...

# Verify how liveins are rewritten when the sub-regs are defined in different
# BBs. Currently, we only update liveins in the the "use MBB".
---
name:            PADDA_3D_sources_in_multi_bb
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: PADDA_3D_sources_in_multi_bb
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; CHECK-NEXT:   liveins: $p0, $r0, $r1, $r2, $r3, $r4, $m0, $dn0, $dj0, $dc0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $dn4 = COPY $r1
  ; CHECK-NEXT:   renamable $dc4 = COPY $r3
  ; CHECK-NEXT:   PseudoJNZ killed renamable $r4, %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $r2, $dc4, $dn4, $p0, $m0, $dn0, $dj0, $dc0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $dj4 = COPY killed renamable $r2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $r2, $dc4, $dn4, $p0, $m0, $dn0, $dj0, $dc0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $dj4 = COPY killed renamable $dc4
  ; CHECK-NEXT:   renamable $dc4 = COPY killed renamable $r2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   liveins: $dc0, $dc4, $dj0, $dj4, $dn0, $dn4, $m0, $p0, $d0_3d:0x0001C00000200E00
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $p0, $dc0, $dc4 = PADDA_3D killed $p0, $d0_3d
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit killed renamable $p0, implicit killed renamable $dc0, implicit killed renamable $dc4
  bb.0.entry:
    successors: %bb.2, %bb.1
    liveins: $p0, $r0, $r1, $r2, $r3, $r4, $m0, $dn0, $dj0, $dc0
    renamable $dn4 = COPY $r1
    renamable $dc4 = COPY $r3
    PseudoJNZ killed renamable $r4, %bb.2

  bb.1:
    successors: %bb.3
    liveins: $r2, $dc4, $dn4, $p0, $m0, $dn0, $dj0, $dc0
    renamable $dj4 = COPY killed renamable $r2
    PseudoJ_jump_imm %bb.3

  bb.2:
    successors: %bb.3
    liveins: $r2, $dc4, $dn4, $p0, $m0, $dn0, $dj0, $dc0
    renamable $dj4 = COPY killed renamable $dc4
    renamable $dc4 = COPY killed renamable $r2

  bb.3:
    liveins: $dc4, $dj4, $dn4, $p0, $m0, $dn0, $dj0, $dc0
    $p0, $dc0, $dc4 = PADDA_3D_split killed $p0, killed $m0, killed $dn0, killed $dj0, killed $dc0, killed undef $m4, killed $dn4, killed $dj4, killed $dc4
    PseudoRET implicit $lr, implicit killed renamable $p0, implicit killed renamable $dc0, implicit killed renamable $dc4
...

---
name:            test_split_2D_opIdx3
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $dc4, $dj4, $dn4, $m4, $p0, $r0

    ; CHECK-LABEL: name: test_split_2D_opIdx3
    ; CHECK: liveins: $d4:0x0000000000200E00, $dc4, $dj4, $dn4, $m4, $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $p0, $dc4 = PADDA_2D killed $p0, $d4
    ; CHECK-NEXT: $p0, $dc4 = PADDB_2D killed $p0, $d4
    ; CHECK-NEXT: $p0, $dc4 = PADDS_2D killed $p0, $d4
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $p0, implicit killed renamable $dc4
    $p0, $dc4 = PADDA_2D_split killed $p0, $m4, $dn4, $dj4, killed $dc4
    $p0, $dc4 = PADDB_2D_split killed $p0, $m4, $dn4, $dj4, killed $dc4
    $p0, $dc4 = PADDS_2D_split killed $p0, killed $m4, killed $dn4, killed $dj4, killed $dc4
    PseudoRET implicit $lr, implicit killed renamable $p0, implicit killed renamable $dc4
...

---
name:            test_split_2D_opIdx4
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $sfh, $d1, $p0

    ; CHECK-LABEL: name: test_split_2D_opIdx4
    ; CHECK: liveins: $sfh, $d1, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $r4, $p0, $dc1 = LDA_2D_dms_lda killed $p0, $d1
    ; CHECK-NEXT: dead $p0, dead $dc1 = VST_2D_dmx_sts_fifohl $sfh, killed $p0, $d1
    $r4, $p0, $dc1 = LDA_2D_dms_lda_split killed $p0, $m1, $dn1, $dj1, $dc1
    dead $p0, dead $dc1 = VST_2D_dmx_sts_fifohl_split $sfh, killed $p0, $m1, $dn1, $dj1, $dc1
...

---
name:            test_split_2D_opIdx5
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $d1, $p0, $s0

    ; CHECK-LABEL: name: test_split_2D_opIdx5
    ; CHECK: liveins: $d1, $p0, $s0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $bmhh0, dead $p0, dead $dc1 = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s0, killed $p0, $d1, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $bmhh0, dead $p0, dead $dc1 = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0_split $s0, killed $p0, $m1, $dn1, $dj1, $dc1, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0

...

---
name:            test_split_2D_opIdx7
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $sf, $p0, $p1, $r26

    ; CHECK-LABEL: name: test_split_2D_opIdx7
    ; CHECK: liveins: $sf, $p0, $p1, $r26
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $m0 = MOV_PD_imm11_pseudo 0
    ; CHECK-NEXT: renamable $dn0 = LDA_dms_lda_idx_imm killed renamable $p1, 0 :: (load (s20), align 4)
    ; CHECK-NEXT: renamable $dj0 = COPY renamable $m0
    ; CHECK-NEXT: renamable $dc0 = COPY renamable $dn0
    ; CHECK-NEXT: renamable $p2 = COPY $p0
    ; CHECK-NEXT: $sf, dead $p2, $r26, dead $dc0 = VST_FLUSH_512_2D $sf, killed $p2, $r26, $d0, implicit-def $srfifo_of
    ; CHECK-NEXT: PseudoRET implicit $lr
    renamable $m0 = MOV_PD_imm11_pseudo 0
    renamable $dn0 = LDA_dms_lda_idx_imm killed renamable $p1, 0 :: (load (s20), align 4)
    renamable $dj0 = COPY renamable $m0
    renamable $dc0 = COPY renamable $dn0
    renamable $p2 = COPY $p0
    $sf, dead $p2, $r26, dead $dc0 = VST_FLUSH_512_2D_split $sf, killed $p2, $r26, killed $m0, killed $dn0, killed $dj0, killed $dc0, implicit-def $srfifo_of
    PseudoRET implicit $lr
...

---
name:            test_split_2D_opIdx8
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $p1

    ; CHECK-LABEL: name: test_split_2D_opIdx8
    ; CHECK: liveins: $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $m0 = MOV_PD_imm11_pseudo 0
    ; CHECK-NEXT: renamable $dn0 = LDA_dms_lda_idx_imm killed renamable $p1, 0 :: (load (s20), align 4)
    ; CHECK-NEXT: renamable $r24 = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: renamable $dj0 = COPY renamable $m0
    ; CHECK-NEXT: renamable $dc0 = COPY renamable $dn0
    ; CHECK-NEXT: $x0, dead $p0, dead $lf0, dead $r24, dead $dc0 = VLD_POP_512_2D_pseudo killed $p0, undef $lf0, $r24, $d0, implicit-def $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $x0
    renamable $m0 = MOV_PD_imm11_pseudo 0
    renamable $dn0 = LDA_dms_lda_idx_imm killed renamable $p1, 0 :: (load (s20), align 4)
    renamable $r24 = MOV_RLC_imm11_pseudo 0
    renamable $dj0 = COPY renamable $m0
    renamable $dc0 = COPY renamable $dn0
    $x0, dead $p0, dead $lf0, dead $r24, dead $dc0 = VLD_POP_512_2D_pseudo_split killed $p0, undef $lf0, $r24, killed $m0, killed $dn0, killed $dj0, killed $dc0, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit killed renamable $x0
...

---
name:            test_split_3D_opIdx4
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $dc4, $dj4, $dn4, $p0, $m0, $dn0, $dj0, $dc0
    ; CHECK-LABEL: name: test_split_3D_opIdx4
    ; CHECK: liveins: $dc0, $dc4, $dj0, $dj4, $dn0, $dn4, $m0, $p0, $d0_3d:0x0001C00000200E00
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $p0, $dc0, $dc4 = PADDA_3D killed $p0, $d0_3d
    ; CHECK-NEXT: $p0, $dc0, $dc4 = PADDB_3D killed $p0, $d0_3d
    ; CHECK-NEXT: $p0, $dc0, $dc4 = PADDS_3D killed $p0, $d0_3d
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $p0, implicit killed renamable $dc0, implicit killed renamable $dc4
    $p0, $dc0, $dc4 = PADDA_3D_split killed $p0, $m0, $dn0, $dj0, $dc0, undef $m4, $dn4, $dj4, $dc4
    $p0, $dc0, $dc4 = PADDB_3D_split killed $p0, $m0, $dn0, $dj0, $dc0, undef $m4, $dn4, $dj4, $dc4
    $p0, $dc0, $dc4 = PADDS_3D_split killed $p0, killed $m0, killed $dn0, killed $dj0, killed $dc0, killed undef $m4, killed $dn4, killed $dj4, killed $dc4
    PseudoRET implicit $lr, implicit killed renamable $p0, implicit killed renamable $dc0, implicit killed renamable $dc4
...

---
name:            test_split_3D_opIdx5
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $d1_3d

    ; CHECK-LABEL: name: test_split_3D_opIdx5
    ; CHECK: liveins: $p0, $d1_3d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $r4, dead $p0, dead $dc1, dead $dc5 = LDA_3D_dms_lda killed $p0, $d1_3d
    $r4, dead $p0, dead $dc1, dead $dc5 = LDA_3D_dms_lda_split killed $p0, $m1, $dn1, $dj1, $dc1, undef $m5, $dn5, $dj5, $dc5
...

---
name:            test_split_3D_opIdx6
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $s0, $d1_3d

    ; CHECK-LABEL: name: test_split_3D_opIdx6
    ; CHECK: liveins: $p0, $s0, $d1_3d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: dead $dm0, dead $p0, dead $dc1, dead $dc5 = VLDA_3D_UPS_4x_dmx_lda_ups_x2d_upsSign0 $s0, killed $p0, $d1_3d, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    dead $dm0, dead $p0, dead $dc1, dead $dc5 = VLDA_3D_UPS_4x_dmx_lda_ups_x2d_upsSign0_split $s0, killed $p0, $m1, $dn1, $dj1, $dc1, undef $m5, $dn5, $dj5, $dc5, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0

...

---
name:            test_split_3D_opIdx8
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $sf, $p0, $r26

    ; CHECK-LABEL: name: test_split_3D_opIdx8
    ; CHECK: liveins: $sf, $p0, $r26
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $m0 = MOV_PD_imm11_pseudo 0
    ; CHECK-NEXT: renamable $dj4 = MOV_PD_imm11_pseudo 128
    ; CHECK-NEXT: renamable $dj0 = COPY renamable $m0
    ; CHECK-NEXT: renamable $dn0 = COPY renamable $dj4
    ; CHECK-NEXT: renamable $dc0 = COPY renamable $m0
    ; CHECK-NEXT: renamable $dc4 = COPY renamable $m0
    ; CHECK-NEXT: renamable $dn4 = COPY renamable $dn0
    ; CHECK-NEXT: renamable $p2 = COPY $p0
    ; CHECK-NEXT: $sf, dead $p2, $r26, dead $dc0, dead $dc4 = VST_FLUSH_512_3D $sf, killed $p2, $r26, $d0_3d, implicit-def $srfifo_of
    ; CHECK-NEXT: PseudoRET implicit $lr
    renamable $m0 = MOV_PD_imm11_pseudo 0
    renamable $dj4 = MOV_PD_imm11_pseudo 128
    renamable $dj0 = COPY renamable $m0
    renamable $dn0 = COPY renamable $dj4
    renamable $dc0 = COPY renamable $m0
    renamable $dc4 = COPY renamable $m0
    renamable $dn4 = COPY renamable $dn0
    renamable $p2 = COPY $p0
    $sf, dead $p2, $r26, dead $dc0, dead $dc4 = VST_FLUSH_512_3D_split $sf, killed $p2, $r26, killed $m0, killed $dn0, killed $dj0, killed $dc0, undef $m4, killed $dn4, killed $dj4, killed $dc4, implicit-def $srfifo_of
    PseudoRET implicit $lr
...

---
name:            test_split_3D_opIdx9
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_split_3D_opIdx9
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $m0 = MOV_PD_imm11_pseudo 0
    ; CHECK-NEXT: renamable $dj4 = MOV_PD_imm11_pseudo 128
    ; CHECK-NEXT: renamable $r24 = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: renamable $dj0 = COPY renamable $m0
    ; CHECK-NEXT: renamable $dn0 = COPY renamable $dj4
    ; CHECK-NEXT: renamable $dc0 = COPY renamable $m0
    ; CHECK-NEXT: renamable $dc4 = COPY renamable $m0
    ; CHECK-NEXT: renamable $dn4 = COPY renamable $dn0
    ; CHECK-NEXT: $x0, dead $p0, dead $lf0, dead $r24, dead $dc0, dead $dc4 = VLD_POP_512_3D_pseudo killed $p0, undef $lf0, $r24, $d0_3d, implicit-def $srfifo_uf
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $x0
    renamable $m0 = MOV_PD_imm11_pseudo 0
    renamable $dj4 = MOV_PD_imm11_pseudo 128
    renamable $r24 = MOV_RLC_imm11_pseudo 0
    renamable $dj0 = COPY renamable $m0
    renamable $dn0 = COPY renamable $dj4
    renamable $dc0 = COPY renamable $m0
    renamable $dc4 = COPY renamable $m0
    renamable $dn4 = COPY renamable $dn0
    $x0, dead $p0, dead $lf0, dead $r24, dead $dc0, dead $dc4 = VLD_POP_512_3D_pseudo_split killed $p0, undef $lf0, $r24, killed $m0, killed $dn0, killed $dj0, killed $dc0, undef $m4, killed $dn4, killed $dj4, killed $dc4, implicit-def $srfifo_uf
    PseudoRET implicit $lr, implicit killed renamable $x0
...
