# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -O2 -mtriple=aie2p -verify-machineinstrs -start-before=greedy \
# RUN: -stop-after=aie-unallocated-superreg-rewrite %s -o - | FileCheck %s

# This example exposes some bundled copies that should be expanded. Please note
# that the bundled copies related to 3d instructions should not be expanded here
# because they already have physical registers assigned (are allocated).

---
name:            test_expand_copy_bundle
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: test_expand_copy_bundle
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo:%[0-9]+]]:em_as_32bit = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:edjl = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:ednl = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:ednh = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   undef [[COPY3:%[0-9]+]].sub_dim_size:eds = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]].sub_dim_count:eds = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo:%[0-9]+]]:erf2 = MOV_RLC_imm11_pseudo 0
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]].sub_hi_dim_then_sub_dim_size:eds = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]].sub_mod:eds = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]].sub_dim_stride:eds = COPY [[COPY]]
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]].sub_hi_dim_then_sub_dim_stride:eds = COPY [[COPY]]
  ; CHECK-NEXT:   undef [[VBCST_32_:%[0-9]+]].sub_512_lo:vec1024 = VBCST_32 [[MOV_RLC_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:ednl = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:ednh = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:ednl = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:edch = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:edcl = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:edch = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:edcl = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:edcl = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:edch = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[VBCST_32_:%[0-9]+]].sub_512_hi:vec1024 = COPY [[VBCST_32_]].sub_512_lo
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:eldfiforeg = COPY [[VBCST_32_]]
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo1:%[0-9]+]]:eps = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]]:edjh = COPY [[COPY]]
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo2:%[0-9]+]]:ep = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   dead [[MOV_PD_imm11_pseudo2:%[0-9]+]]:ep, dead [[COPY11:%[0-9]+]]:edcl, [[COPY12:%[0-9]+]]:edch = PADD_3D_pseudo_split [[MOV_PD_imm11_pseudo2]], [[MOV_PD_imm11_pseudo]], [[COPY1]], [[COPY]], [[COPY11]], undef %29:em_as_32bit, [[COPY2]], [[COPY14]], [[COPY12]]
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]]:eds = COPY [[COPY3]]
  ; CHECK-NEXT:   undef [[COPY16:%[0-9]+]].sub_ptr:epsrfldf = COPY [[MOV_PD_imm11_pseudo1]]
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]].sub_fifo:epsrfldf = COPY [[COPY13]]
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]].sub_avail:epsrfldf = COPY [[MOV_RLC_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY17:%[0-9]+]]:spill_edn_to_er = COPY [[COPY4]]
  ; CHECK-NEXT:   [[COPY18:%[0-9]+]]:spill_edn_to_er = COPY [[COPY5]]
  ; CHECK-NEXT:   undef [[COPY19:%[0-9]+]].sub_lo_dim:eds = COPY [[COPY15]].sub_lo_dim {
  ; CHECK-NEXT:     internal [[COPY19]].sub_hi_dim_then_sub_dim_count:eds = COPY [[COPY15]].sub_hi_dim_then_sub_dim_count
  ; CHECK-NEXT:     internal [[COPY19]].sub_hi_dim_then_sub_dim_size:eds = COPY [[COPY15]].sub_hi_dim_then_sub_dim_size
  ; CHECK-NEXT:     internal [[COPY19]].sub_hi_dim_then_sub_dim_stride:eds = COPY [[COPY15]].sub_hi_dim_then_sub_dim_stride
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   dead [[VLD_POP_576_3D_pseudo_split:%[0-9]+]]:vec576, dead [[COPY16:%[0-9]+]].sub_ptr:epsrfldf, dead [[COPY16:%[0-9]+]].sub_fifo:epsrfldf, dead [[COPY16:%[0-9]+]].sub_avail:epsrfldf, [[COPY19:%[0-9]+]].sub_dim_count:eds, [[COPY19:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLD_POP_576_3D_pseudo_split [[COPY16]].sub_ptr, [[COPY16]].sub_fifo, [[COPY16]].sub_avail, [[COPY19]].sub_mod, [[COPY19]].sub_dim_size, [[COPY19]].sub_dim_stride, [[COPY19]].sub_dim_count, undef [[COPY19]].sub_hi_dim_then_sub_mod, [[COPY19]].sub_hi_dim_then_sub_dim_size, [[COPY19]].sub_hi_dim_then_sub_dim_stride, [[COPY19]].sub_hi_dim_then_sub_dim_count, implicit-def $srfifo_uf :: (load unknown-size from `ptr addrspace(5) null`, align 1, addrspace 5)
  ; CHECK-NEXT:   [[COPY20:%[0-9]+]]:spill_edc_to_er = COPY [[COPY19]].sub_dim_count
  ; CHECK-NEXT:   [[COPY21:%[0-9]+]]:spill_edc_to_er = COPY [[COPY19]].sub_hi_dim_then_sub_dim_count
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:ednl = COPY [[COPY17]] {
  ; CHECK-NEXT:     internal [[COPY5]]:ednh = COPY [[COPY18]]
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   [[COPY22:%[0-9]+]]:em_as_32bit = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY23:%[0-9]+]]:edjl = COPY [[COPY]]
  ; CHECK-NEXT:   [[COPY24:%[0-9]+]]:edcl = COPY [[COPY20]]
  ; CHECK-NEXT:   [[COPY25:%[0-9]+]]:edjh = COPY [[COPY]]
  ; CHECK-NEXT:   [[COPY26:%[0-9]+]]:edch = COPY [[COPY21]]
  ; CHECK-NEXT:   undef [[COPY27:%[0-9]+]].sub_ptr:epsrfldf = COPY [[MOV_PD_imm11_pseudo1]]
  ; CHECK-NEXT:   [[COPY27:%[0-9]+]].sub_fifo:epsrfldf = COPY [[COPY13]]
  ; CHECK-NEXT:   [[COPY27:%[0-9]+]].sub_avail:epsrfldf = COPY [[MOV_RLC_imm11_pseudo]]
  ; CHECK-NEXT:   dead [[VLD_POP_576_3D_pseudo_split1:%[0-9]+]]:vec576, dead [[COPY27:%[0-9]+]].sub_ptr:epsrfldf, dead [[COPY27:%[0-9]+]].sub_fifo:epsrfldf, dead [[COPY27:%[0-9]+]].sub_avail:epsrfldf, dead [[COPY24:%[0-9]+]]:edcl, dead [[COPY26:%[0-9]+]]:edch = VLD_POP_576_3D_pseudo_split [[COPY27]].sub_ptr, [[COPY27]].sub_fifo, [[COPY27]].sub_avail, [[COPY22]], [[COPY4]], [[COPY23]], [[COPY24]], undef %53:em_as_32bit, [[COPY5]], [[COPY25]], [[COPY26]], implicit-def $srfifo_uf :: (load unknown-size from `ptr addrspace(5) null`, align 1, addrspace 5)
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo3:%[0-9]+]]:ep = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[COPY28:%[0-9]+]]:ednh = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY29:%[0-9]+]]:em_as_32bit = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY30:%[0-9]+]]:edjl = COPY [[COPY]]
  ; CHECK-NEXT:   [[COPY31:%[0-9]+]]:edjh = COPY [[COPY]]
  ; CHECK-NEXT:   dead [[MOV_PD_imm11_pseudo3:%[0-9]+]]:ep, dead [[COPY8:%[0-9]+]]:edcl, [[COPY7:%[0-9]+]]:edch = PADD_3D_pseudo_split [[MOV_PD_imm11_pseudo3]], [[COPY29]], [[COPY6]], [[COPY30]], [[COPY8]], undef %37:em_as_32bit, [[COPY28]], [[COPY31]], [[COPY7]]
  ; CHECK-NEXT:   [[COPY32:%[0-9]+]]:em_as_32bit = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY33:%[0-9]+]]:ednl = COPY [[COPY28]]
  ; CHECK-NEXT:   [[COPY34:%[0-9]+]]:edjl = COPY [[COPY]]
  ; CHECK-NEXT:   [[COPY35:%[0-9]+]]:ednh = COPY [[COPY28]]
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:edcl = MOV_PD_imm11_pseudo 1
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo4:%[0-9]+]]:ep = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[COPY36:%[0-9]+]]:edjh = COPY [[COPY]]
  ; CHECK-NEXT:   dead [[MOV_PD_imm11_pseudo4:%[0-9]+]]:ep, dead [[COPY10:%[0-9]+]]:edcl, [[COPY9:%[0-9]+]]:edch = PADD_3D_pseudo_split [[MOV_PD_imm11_pseudo4]], [[COPY32]], [[COPY33]], [[COPY34]], [[COPY10]], undef %45:em_as_32bit, [[COPY35]], [[COPY36]], [[COPY9]]
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:edcl = MOV_PD_imm11_pseudo 1
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:edcl = MOV_PD_imm11_pseudo 1
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  bb.0:
    successors: %bb.1(0x80000000)

    undef %90.sub_mod:eds = MOV_PD_imm11_pseudo 0
    %90.sub_dim_stride:eds = COPY %90.sub_mod
    %90.sub_dim_size:eds = COPY %90.sub_mod
    %90.sub_hi_dim_then_sub_dim_size:eds = COPY %90.sub_mod
    undef %83.sub_dim_size:eds = COPY %90.sub_mod
    %83.sub_dim_count:eds = COPY %90.sub_mod
    %22:erf2 = MOV_RLC_imm11_pseudo 0
    %83.sub_hi_dim_then_sub_dim_size:eds = COPY %90.sub_mod
    %83.sub_hi_dim_then_sub_dim_count:eds = COPY %90.sub_mod
    %83.sub_mod:eds = COPY %90.sub_mod
    %83.sub_dim_stride:eds = COPY %90.sub_dim_stride
    %83.sub_hi_dim_then_sub_dim_stride:eds = COPY %90.sub_dim_stride
    undef %21.sub_512_lo:vec1024 = VBCST_32 %22
    undef %77.sub_dim_size:eds = COPY %90.sub_mod
    %77.sub_hi_dim_then_sub_dim_size:eds = COPY %90.sub_mod
    undef %71.sub_dim_size:eds = COPY %90.sub_mod
    %71.sub_hi_dim_then_sub_dim_count:eds = COPY %90.sub_mod
    %71.sub_dim_count:eds = COPY %90.sub_mod
    undef %66.sub_hi_dim_then_sub_dim_count:eds = COPY %90.sub_mod
    %66.sub_dim_count:eds = COPY %90.sub_mod
    %90.sub_dim_count:eds = COPY %90.sub_mod
    %90.sub_hi_dim_then_sub_dim_count:eds = COPY %90.sub_mod
    %21.sub_512_hi:vec1024 = COPY %21.sub_512_lo
    %64:eldfiforeg = COPY %21
    %20:eps = MOV_PD_imm11_pseudo 0

  bb.1:
    successors: %bb.1(0x80000000)

    %90.sub_hi_dim_then_sub_dim_stride:eds = COPY %90.sub_dim_stride
    %8:ep = MOV_PD_imm11_pseudo 0
    dead %8:ep, %90.sub_dim_count:eds, %90.sub_hi_dim_then_sub_dim_count:eds = PADD_3D_pseudo_split %8, %90.sub_mod, %90.sub_dim_size, %90.sub_dim_stride, %90.sub_dim_count, undef %90.sub_hi_dim_then_sub_mod, %90.sub_hi_dim_then_sub_dim_size, %90.sub_hi_dim_then_sub_dim_stride, %90.sub_hi_dim_then_sub_dim_count
    %104:eds = COPY %83
    undef %103.sub_ptr:epsrfldf = COPY %20
    %103.sub_fifo:epsrfldf = COPY %64
    %103.sub_avail:epsrfldf = COPY %22
    dead %82:vec576, dead %103.sub_ptr:epsrfldf, dead %103.sub_fifo:epsrfldf, dead %103.sub_avail:epsrfldf, %104.sub_dim_count:eds, %104.sub_hi_dim_then_sub_dim_count:eds = VLD_POP_576_3D_pseudo_split %103.sub_ptr, %103.sub_fifo, %103.sub_avail, %104.sub_mod, %104.sub_dim_size, %104.sub_dim_stride, %104.sub_dim_count, undef %104.sub_hi_dim_then_sub_mod, %104.sub_hi_dim_then_sub_dim_size, %104.sub_hi_dim_then_sub_dim_stride, %104.sub_hi_dim_then_sub_dim_count, implicit-def $srfifo_uf :: (load unknown-size from `ptr addrspace(5) null`, align 1, addrspace 5)
    %77.sub_mod:eds = COPY %90.sub_mod
    %77.sub_dim_stride:eds = COPY %90.sub_dim_stride
    %77.sub_dim_count:eds = COPY %104.sub_dim_count
    %77.sub_hi_dim_then_sub_dim_stride:eds = COPY %90.sub_dim_stride
    %77.sub_hi_dim_then_sub_dim_count:eds = COPY %104.sub_hi_dim_then_sub_dim_count
    undef %105.sub_ptr:epsrfldf = COPY %20
    %105.sub_fifo:epsrfldf = COPY %64
    %105.sub_avail:epsrfldf = COPY %22
    dead %76:vec576, dead %105.sub_ptr:epsrfldf, dead %105.sub_fifo:epsrfldf, dead %105.sub_avail:epsrfldf, %77.sub_dim_count:eds, %77.sub_hi_dim_then_sub_dim_count:eds = VLD_POP_576_3D_pseudo_split %105.sub_ptr, %105.sub_fifo, %105.sub_avail, %77.sub_mod, %77.sub_dim_size, %77.sub_dim_stride, %77.sub_dim_count, undef %77.sub_hi_dim_then_sub_mod, %77.sub_hi_dim_then_sub_dim_size, %77.sub_hi_dim_then_sub_dim_stride, %77.sub_hi_dim_then_sub_dim_count, implicit-def $srfifo_uf :: (load unknown-size from `ptr addrspace(5) null`, align 1, addrspace 5)
    %33:ep = MOV_PD_imm11_pseudo 0
    %71.sub_hi_dim_then_sub_dim_size:eds = COPY %90.sub_mod
    %71.sub_mod:eds = COPY %90.sub_mod
    %71.sub_dim_stride:eds = COPY %90.sub_dim_stride
    %71.sub_hi_dim_then_sub_dim_stride:eds = COPY %90.sub_dim_stride
    dead %33:ep, %71.sub_dim_count:eds, %71.sub_hi_dim_then_sub_dim_count:eds = PADD_3D_pseudo_split %33, %71.sub_mod, %71.sub_dim_size, %71.sub_dim_stride, %71.sub_dim_count, undef %71.sub_hi_dim_then_sub_mod, %71.sub_hi_dim_then_sub_dim_size, %71.sub_hi_dim_then_sub_dim_stride, %71.sub_hi_dim_then_sub_dim_count
    %66.sub_mod:eds = COPY %90.sub_mod
    %66.sub_dim_size:eds = COPY %71.sub_hi_dim_then_sub_dim_size
    %66.sub_dim_stride:eds = COPY %90.sub_dim_stride
    %66.sub_hi_dim_then_sub_dim_size:eds = COPY %71.sub_hi_dim_then_sub_dim_size
    %71.sub_dim_count:eds = MOV_PD_imm11_pseudo 1
    %39:ep = MOV_PD_imm11_pseudo 0
    %66.sub_hi_dim_then_sub_dim_stride:eds = COPY %90.sub_dim_stride
    dead %39:ep, %66.sub_dim_count:eds, %66.sub_hi_dim_then_sub_dim_count:eds = PADD_3D_pseudo_split %39, %66.sub_mod, %66.sub_dim_size, %66.sub_dim_stride, %66.sub_dim_count, undef %66.sub_hi_dim_then_sub_mod, %66.sub_hi_dim_then_sub_dim_size, %66.sub_hi_dim_then_sub_dim_stride, %66.sub_hi_dim_then_sub_dim_count
    %66.sub_dim_count:eds = MOV_PD_imm11_pseudo 1
    %90.sub_dim_count:eds = MOV_PD_imm11_pseudo 1
    PseudoJ_jump_imm %bb.1

...
