# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple=aie2p --aie-staged-ra -verify-machineinstrs \
# RUN:     --start-before=greedy --stop-after=virtregrewriter %s -o - \
# RUN: | FileCheck %s --check-prefix=COMMON


# Staged execution: run each stage separately and compare to full pipeline
# RUN: llc -mtriple=aie2p --aie-staged-ra -verify-machineinstrs \
# RUN:     --start-before=greedy --stop-after=greedy,0 %s -o - \
# RUN: | llc -mtriple=aie2p --aie-staged-ra -verify-machineinstrs -x mir \
# RUN:        --start-after=greedy,0 --stop-after=greedy,1 -o - \
# RUN: | llc -mtriple=aie2p --aie-staged-ra -verify-machineinstrs -x mir \
# RUN:        --start-after=greedy,1 --stop-after=greedy,2 -o - \
# RUN: | llc -mtriple=aie2p --aie-staged-ra -verify-machineinstrs -x mir \
# RUN:        --start-after=greedy,2 --stop-after=greedy,3 -o - \
# RUN: | llc -mtriple=aie2p --aie-staged-ra -verify-machineinstrs -x mir \
# RUN:        --start-after=greedy,3 --stop-after=virtregrewriter -o - \
# RUN: | FileCheck %s --check-prefix=COMMON


# Test the full staged RA pipeline vs. staged RA pipeline run stage-by-stage.
# This test verifies that VirtRegMap MIR serialization/deserialization works:
#   1. VirtRegMap is correctly serialized to MIR after each greedy stage
#      (assigned-register and stack-slot fields appear in output)
#   2. VirtRegMap is correctly deserialized from MIR before the next stage
#      (MIRParser populates MIRVirtRegMapInfo from assigned-register/stack-slot)
#   3. LiveRegMatrix is correctly initialized from deserialized VirtRegMap
#      (LiveRegMatrix::init() populates the interference matrix from VRM)
# If any of these are broken, the staged execution will produce different
# results than the end-to-end run, causing this test to fail.
#
# This test is based on llvm/test/CodeGen/AIE/aie2p/ra/staged-ra-spill.mir

---
name:            end2end_vs_staged_reg_alloc
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $p0, $p1, $d1, $d2, $d3, $d4, $d5, $d6, $d7

    ; COMMON-LABEL: name: end2end_vs_staged_reg_alloc
    ; COMMON: liveins: $d1, $d2, $d3, $d4, $d5, $d6, $d7, $p0, $p1
    ; COMMON-NEXT: {{  $}}
    ; COMMON-NEXT: renamable $dn0 = LDA_dms_lda_idx_imm renamable $p1, 0
    ; COMMON-NEXT: renamable $m0 = LDA_dms_lda_idx_imm renamable $p1, 4
    ; COMMON-NEXT: renamable $r0 = LDA_dms_lda_idx_imm renamable $p1, 8
    ; COMMON-NEXT: renamable $dj0 = MOV_PD_imm11_pseudo 12
    ; COMMON-NEXT: renamable $r1 = LDA_dms_lda_idx renamable $p1, killed renamable $dj0
    ; COMMON-NEXT: renamable $dc0 = COPY killed renamable $r1
    ; COMMON-NEXT: renamable $dj0 = COPY killed renamable $r0
    ; COMMON-NEXT: renamable $r1 = LDA_dms_lda_idx_imm renamable $p1, 16
    ; COMMON-NEXT: renamable $r3 = LDA_dms_lda_idx_imm renamable $p1, 20
    ; COMMON-NEXT: renamable $r2 = LDA_dms_lda_idx_imm renamable $p1, 24
    ; COMMON-NEXT: renamable $r0 = LDA_dms_lda_idx_imm killed renamable $p1, 28
    ; COMMON-NEXT: $p0, $dc0 = PADDA_2D_split killed $p0, killed $m0, killed $dn0, killed $dj0, killed $dc0
    ; COMMON-NEXT: renamable $r4 = COPY killed renamable $dc0
    ; COMMON-NEXT: renamable $dc0 = COPY killed renamable $r0
    ; COMMON-NEXT: renamable $dn0 = COPY killed renamable $r1
    ; COMMON-NEXT: renamable $dj0 = COPY killed renamable $r2
    ; COMMON-NEXT: renamable $m0 = COPY killed renamable $r3
    ; COMMON-NEXT: $p0, dead $dc0 = PADDA_2D_split killed $p0, killed $m0, killed $dn0, killed $dj0, killed $dc0
    ; COMMON-NEXT: PseudoRET implicit $lr, implicit killed renamable $p0, implicit killed renamable $r4, implicit $d1, implicit $d2, implicit $d3, implicit $d4, implicit $d5, implicit $d6, implicit $d7
    %20:ep = COPY $p0
    %21:ep = COPY $p1
    undef %100.sub_dim_size:ed = LDA_dms_lda_idx_imm %21, 0
    %100.sub_mod:ed = LDA_dms_lda_idx_imm %21, 4
    %100.sub_dim_stride:ed = LDA_dms_lda_idx_imm %21, 8
    %7:edj = MOV_PD_imm11_pseudo 12
    %8:er = LDA_dms_lda_idx %21, %7
    %100.sub_dim_count:ed = COPY %8
    undef %101.sub_dim_size:ed = LDA_dms_lda_idx_imm %21, 16
    %101.sub_mod:ed = LDA_dms_lda_idx_imm %21, 20
    %101.sub_dim_stride:ed = LDA_dms_lda_idx_imm %21, 24
    %101.sub_dim_count:ed = LDA_dms_lda_idx_imm %21, 28
    %20:ep, %100.sub_dim_count:ed = PADDA_2D_split %20, %100.sub_mod, %100.sub_dim_size, %100.sub_dim_stride, %100.sub_dim_count
    %20:ep, %101.sub_dim_count:ed = PADDA_2D_split %20, %101.sub_mod, %101.sub_dim_size, %101.sub_dim_stride, %101.sub_dim_count
    PseudoRET implicit $lr, implicit %20, implicit %100.sub_dim_count, implicit $d1, implicit $d2, implicit $d3, implicit $d4, implicit $d5, implicit $d6, implicit $d7
...
