; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie2p --aie-staged-ra-fine-grained-alloc=false -verify-machineinstrs --stop-before=prologepilog %s -o - | FileCheck %s

; Disabling the Machine Verifier allows this unit-test to run to the end.
; The verifier complains that we spill a SubRegister that is dead.
; In our specific case we do not care about the Value in the Subregister and thus the faulty behaviour is acceptable.

; Flow:
; Greedy requests to split a 3D register.
; In bb.2 the last 3D padd creates a dead value (sub_hi_dim_then_sub_dim_count).
; This value is never used again (bb.0 and bb.5 define the sublane).

; Control Flow Overview:
; bb2 -> bb.4 -> bb.5 -> bb.6
;  ^               |
;  |               v       v ---+
;  |      bb.0 -> bb.1 -> bb.3 -+
;  |                       |
;  +-----------------------+

; InlineSpilling can only spill full registers.
; Thus we spill the full register - even the dead subregister.
; Machine Verifier correctly complains about this.

; Function Attrs: nounwind readnone
define void @heavy_3d_user(i32 %dimsAI.sroa.5.0.copyload.i, i32 %dimsAI.sroa.7.0.copyload.i, i32 %dimsAI.sroa.9.0.copyload.i, i32 %dimsAO.sroa.7.0.copyload.i, i32 %dimsAO.sroa.4.0.copyload.i, i32 %dimsAO.sroa.6.0.copyload.i, i32 %dimsAO.sroa.0.0.copyload.i, i32 %dimsAO.sroa.5.0.copyload.i, i32 %dimsW.sroa.4.0.copyload.i, i32 %dimsW.sroa.6.0.copyload.i, i20 %0, i1 %1, i32 %dimsAI.sroa.11.0.copyload.i) {
  ; CHECK-LABEL: name: heavy_3d_user
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $r0, $r1, $r2, $r3, $r4, $r5, $r6, $r7
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $p1 = PseudoFI %fixed-stack.3, implicit $sp
  ; CHECK-NEXT:   renamable $dj0, renamable $p1 = LDA_dms_lda_pstm_nrm_imm killed renamable $p1, -4 :: (invariant load (s20) from %fixed-stack.3, align 4)
  ; CHECK-NEXT:   renamable $dj4, renamable $p1 = LDA_dms_lda_pstm_nrm_imm killed renamable $p1, -4 :: (invariant load (s20) from %fixed-stack.2, align 8)
  ; CHECK-NEXT:   ST_DS_SPILL renamable $d0_3d, %stack.1, implicit $sp :: (store (s256) into %stack.1, align 4)
  ; CHECK-NEXT:   renamable $m0 = LDA_dms_lda_idx_imm renamable $p1, -4 :: (invariant load (s20) from %fixed-stack.0, align 16)
  ; CHECK-NEXT:   ST_DS_SPILL renamable $d0_3d, %stack.2, implicit $sp :: (store (s256) into %stack.2, align 4)
  ; CHECK-NEXT:   renamable $r8 = LDA_dms_lda_idx_imm killed renamable $p1, 0 :: (invariant load (s32) from %fixed-stack.1)
  ; CHECK-NEXT:   renamable $m0 = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   renamable $dj4 = MOV_PD_imm11_pseudo 1
  ; CHECK-NEXT:   ST_DS_SPILL renamable $d0_3d, %stack.0, implicit $sp :: (store (s256) into %stack.0, align 4)
  ; CHECK-NEXT:   renamable $p3 = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   renamable $p6 = COPY $p0
  ; CHECK-NEXT:   renamable $r16 = MOV_RLC_imm11_pseudo 0
  ; CHECK-NEXT:   $p0 = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   renamable $x0 = VBCST_32 killed renamable $r16
  ; CHECK-NEXT:   $p1 = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   ST_R_SPILL $r0, %stack.3, implicit $sp :: (store (s32) into %stack.3)
  ; CHECK-NEXT:   renamable $r9 = COPY $r1
  ; CHECK-NEXT:   renamable $r10 = COPY $r2
  ; CHECK-NEXT:   renamable $r11 = COPY $r3
  ; CHECK-NEXT:   renamable $r12 = COPY $r4
  ; CHECK-NEXT:   $p2 = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   renamable $r13 = COPY $r5
  ; CHECK-NEXT:   renamable $r14 = COPY $r6
  ; CHECK-NEXT:   renamable $r15 = COPY $r7
  ; CHECK-NEXT:   renamable $x1 = COPY renamable $x0
  ; CHECK-NEXT:   VST_Y_SPILL killed renamable $y0, %stack.5, implicit $sp :: (store (s1024) into %stack.5, align 64)
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoJL_IND killed renamable $p3, csr_aie2p, implicit-def $lr, implicit $p0, implicit $p1, implicit $p2
  ; CHECK-NEXT:   renamable $y1 = VLDA_Y_SPILL %stack.5, implicit $sp :: (load (s1024) from %stack.5, align 64)
  ; CHECK-NEXT:   renamable $r3 = MOV_RLC_imm11_pseudo 0
  ; CHECK-NEXT:   renamable $r0 = MOV_RLC_imm11_pseudo 1
  ; CHECK-NEXT:   renamable $d3_3d = LDA_DS_SPILL %stack.2, implicit $sp :: (load (s256) from %stack.2, align 4)
  ; CHECK-NEXT:   renamable $dj3 = LDA_R_SPILL %stack.3, implicit $sp :: (load (s32) from %stack.3)
  ; CHECK-NEXT:   renamable $dn7 = COPY killed renamable $r9
  ; CHECK-NEXT:   renamable $dj7 = COPY killed renamable $r10
  ; CHECK-NEXT:   renamable $m0 = COPY killed renamable $r11
  ; CHECK-NEXT:   renamable $dj0 = COPY killed renamable $r12
  ; CHECK-NEXT:   renamable $dj4 = COPY killed renamable $r13
  ; CHECK-NEXT:   renamable $dn0 = COPY killed renamable $r14
  ; CHECK-NEXT:   renamable $dn4 = COPY killed renamable $r15
  ; CHECK-NEXT:   renamable $dc3 = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   renamable $d1_3d = LDA_DS_SPILL %stack.0, implicit $sp :: (load (s256) from %stack.0, align 4)
  ; CHECK-NEXT:   renamable $m2 = COPY renamable $m1
  ; CHECK-NEXT:   internal renamable $dj6 = COPY renamable $dj5
  ; CHECK-NEXT:   renamable $dn3 = COPY $m1
  ; CHECK-NEXT:   renamable $m1 = COPY $dj5
  ; CHECK-NEXT:   renamable $dc5 = COPY renamable $m2
  ; CHECK-NEXT:   renamable $dc1 = COPY renamable $m2
  ; CHECK-NEXT:   renamable $dc4 = COPY renamable $m2
  ; CHECK-NEXT:   renamable $dc0 = COPY renamable $m2
  ; CHECK-NEXT:   ST_DS_SPILL renamable $d0_3d, %stack.2, implicit $sp :: (store (s256) into %stack.2, align 4)
  ; CHECK-NEXT:   renamable $d0_3d = LDA_DS_SPILL %stack.1, implicit $sp :: (load (s256) from %stack.1, align 4)
  ; CHECK-NEXT:   renamable $dc4 = COPY $dj5
  ; CHECK-NEXT:   renamable $dc0 = COPY renamable $m2
  ; CHECK-NEXT:   ST_DS_SPILL renamable $d0_3d, %stack.1, implicit $sp :: (store (s256) into %stack.1, align 4)
  ; CHECK-NEXT:   renamable $dc6 = COPY renamable $m2
  ; CHECK-NEXT:   ST_DS_SPILL renamable $d2_3d, %stack.3, implicit $sp :: (store (s256) into %stack.3, align 4)
  ; CHECK-NEXT:   renamable $dc0 = COPY $m2
  ; CHECK-NEXT:   renamable $m0 = COPY renamable $m2
  ; CHECK-NEXT:   renamable $dj4 = COPY $dj5
  ; CHECK-NEXT:   ST_DS_SPILL renamable $d0_3d, %stack.0, implicit $sp :: (store (s256) into %stack.0, align 4)
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   renamable $lf0 = COPY renamable $y1
  ; CHECK-NEXT:   renamable $r1 = AND renamable $r8, renamable $r0
  ; CHECK-NEXT:   renamable $dc7 = COPY renamable $dc3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.for.body.i:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $dc5, $lf0, $m1, $p6, $r0, $r1, $r3, $r8, $y1:0x0000000000000033, $d1_3d:0x0000400000200200, $d3_3d:0x0001800000200E00, $dc7
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $dj1 = COPY renamable $p6
  ; CHECK-NEXT:   renamable $dn1 = COPY renamable $dn3
  ; CHECK-NEXT:   renamable $dn5 = COPY renamable $dn3
  ; CHECK-NEXT:   renamable $dj5 = COPY $p6
  ; CHECK-NEXT:   renamable $m2 = COPY renamable $m1
  ; CHECK-NEXT:   renamable $dc6 = COPY renamable $dc5
  ; CHECK-NEXT:   ST_DS_SPILL renamable $d2_3d, %stack.4, implicit $sp :: (store (s256) into %stack.4, align 4)
  ; CHECK-NEXT:   renamable $p1 = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   renamable $lf1 = COPY renamable $lf0
  ; CHECK-NEXT:   renamable $r25 = COPY renamable $r3
  ; CHECK-NEXT:   dead $ex0, dead $p1, dead $lf1, dead $r25, dead $dc1, dead $dc5 = VLD_POP_576_3D_pseudo killed $p1, $lf1, $r25, $d1_3d, implicit-def $srfifo_uf :: (load unknown-size from `ptr addrspace(5) null`, align 1, addrspace 5)
  ; CHECK-NEXT:   renamable $d1_3d = LDA_DS_SPILL %stack.3, implicit $sp :: (load (s256) from %stack.3, align 4)
  ; CHECK-NEXT:   renamable $d0_3d = LDA_DS_SPILL %stack.0, implicit $sp :: (load (s256) from %stack.0, align 4)
  ; CHECK-NEXT:   renamable $dj1 = COPY renamable $m0
  ; CHECK-NEXT:   renamable $p0 = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   renamable $dc1 = COPY killed renamable $dc0
  ; CHECK-NEXT:   renamable $m1 = COPY renamable $m0
  ; CHECK-NEXT:   renamable $dj5 = COPY renamable $dj4
  ; CHECK-NEXT:   ST_DS_SPILL renamable $d1_3d, %stack.0, implicit $sp :: (store (s256) into %stack.0, align 4)
  ; CHECK-NEXT:   renamable $dn1 = COPY renamable $dn3
  ; CHECK-NEXT:   renamable $dc1 = COPY renamable $dc3
  ; CHECK-NEXT:   renamable $dn5 = COPY renamable $dn3
  ; CHECK-NEXT:   renamable $dj5 = COPY $m0
  ; CHECK-NEXT:   dead $p0, $dc1, $dc5 = PADD_3D_pseudo killed $p0, $d1_3d
  ; CHECK-NEXT:   renamable $p0 = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   ST_DS_SPILL renamable $d1_3d, %stack.3, implicit $sp :: (store (s256) into %stack.3, align 4)
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.for.cond.cleanup124.i:
  ; CHECK-NEXT:   successors: %bb.4(0x40000000), %bb.5(0x40000000)
  ; CHECK-NEXT:   liveins: $lf0, $p6, $r0, $r1, $r3, $r8, $y1:0x0000000000000033, $d1_3d:0x0000000000000200, $d3_3d:0x0001800000200E00, $dc7
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $p0 = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   renamable $p1 = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   renamable $d0_3d = LDA_DS_SPILL %stack.1, implicit $sp :: (load (s256) from %stack.1, align 4)
  ; CHECK-NEXT:   renamable $d2_3d = LDA_DS_SPILL %stack.0, implicit $sp :: (load (s256) from %stack.0, align 4)
  ; CHECK-NEXT:   renamable $dn0 = COPY renamable $m2
  ; CHECK-NEXT:   renamable $m0 = COPY renamable $m2
  ; CHECK-NEXT:   renamable $dn4 = COPY $m2
  ; CHECK-NEXT:   renamable $d2_3d = LDA_DS_SPILL %stack.2, implicit $sp :: (load (s256) from %stack.2, align 4)
  ; CHECK-NEXT:   dead $p0, $dc2, $dc6 = PADD_3D_pseudo killed $p0, $d2_3d
  ; CHECK-NEXT:   ST_DS_SPILL killed renamable $d2_3d, %stack.2, implicit $sp :: (store (s256) into %stack.2, align 4)
  ; CHECK-NEXT:   dead $p1, $dc0, dead $dc4 = PADD_3D_pseudo killed $p1, $d0_3d
  ; CHECK-NEXT:   ST_DS_SPILL renamable $d0_3d, %stack.1, implicit $sp :: (store (s256) into %stack.1, align 4)
  ; CHECK-NEXT:   PseudoJNZ renamable $r1, %bb.4
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.for.body125.i:
  ; CHECK-NEXT:   successors: %bb.3(0x7c000000), %bb.2(0x04000000)
  ; CHECK-NEXT:   liveins: $lf0, $p0, $p6, $r0, $r1, $r3, $r8, $y1:0x0000000000000033, $d3_3d:0x0001800000200E00, $dc7
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $d1_3d = COPY renamable $d3_3d
  ; CHECK-NEXT:   renamable $lf1 = COPY renamable $y1
  ; CHECK-NEXT:   renamable $p1 = COPY renamable $p0
  ; CHECK-NEXT:   renamable $r25 = COPY renamable $r3
  ; CHECK-NEXT:   dead $ex4, dead $p1, dead $lf1, dead $r25, $dc1, $dc5 = VLD_POP_576_3D_pseudo killed $p1, $lf1, $r25, $d1_3d, implicit-def $srfifo_uf :: (load unknown-size from `ptr addrspace(5) null`, align 1, addrspace 5)
  ; CHECK-NEXT:   PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.3
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4.if.else.i14:
  ; CHECK-NEXT:   successors: %bb.5(0x80000000)
  ; CHECK-NEXT:   liveins: $lf0, $p6, $r0, $r1, $r3, $r8, $y1:0x0000000000000033, $d1_3d:0x0000000000000200, $d3_3d:0x0001800000200E00, $dc7
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5.if.end239.i:
  ; CHECK-NEXT:   successors: %bb.6(0x04000000), %bb.1(0x7c000000)
  ; CHECK-NEXT:   liveins: $lf0, $p6, $r0, $r1, $r3, $r8, $y1:0x0000000000000033, $d1_3d:0x0000000000000200, $d3_3d:0x0001800000200E00, $dc7
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $p0 = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   renamable $r2 = XOR renamable $r8, renamable $r0
  ; CHECK-NEXT:   renamable $d2_3d = LDA_DS_SPILL %stack.0, implicit $sp :: (load (s256) from %stack.0, align 4)
  ; CHECK-NEXT:   renamable $dj2 = COPY renamable $m2
  ; CHECK-NEXT:   renamable $dn2 = COPY renamable $m2
  ; CHECK-NEXT:   renamable $dn6 = COPY renamable $m2
  ; CHECK-NEXT:   renamable $dc6 = COPY renamable $m2
  ; CHECK-NEXT:   renamable $r2 = AND killed renamable $r2, renamable $r0
  ; CHECK-NEXT:   dead $p0, $dc2, dead $dc6 = PADD_3D_pseudo killed $p0, $d2_3d
  ; CHECK-NEXT:   renamable $dc0 = COPY killed renamable $dc2
  ; CHECK-NEXT:   renamable $m0 = COPY renamable $m2
  ; CHECK-NEXT:   renamable $dj4 = COPY renamable $dj6
  ; CHECK-NEXT:   ST_DS_SPILL renamable $d0_3d, %stack.0, implicit $sp :: (store (s256) into %stack.0, align 4)
  ; CHECK-NEXT:   renamable $d0_3d = LDA_DS_SPILL %stack.1, implicit $sp :: (load (s256) from %stack.1, align 4)
  ; CHECK-NEXT:   renamable $dc4 = COPY killed renamable $m2
  ; CHECK-NEXT:   ST_DS_SPILL killed renamable $d0_3d, %stack.1, implicit $sp :: (store (s256) into %stack.1, align 4)
  ; CHECK-NEXT:   renamable $d2_3d = LDA_DS_SPILL %stack.4, implicit $sp :: (load (s256) from %stack.4, align 4)
  ; CHECK-NEXT:   renamable $m1 = COPY killed renamable $m2
  ; CHECK-NEXT:   internal renamable $dc5 = COPY renamable $dc6
  ; CHECK-NEXT:   PseudoJNZ killed renamable $r2, %bb.1
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.6
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6.ret.exit:
  ; CHECK-NEXT:   PseudoRET implicit $lr
entry:
  tail call void null(ptr null, ptr null, ptr null)
  %2 = trunc i32 %dimsAI.sroa.11.0.copyload.i to i20
  %3 = trunc i32 %dimsAI.sroa.5.0.copyload.i to i20
  %4 = trunc i32 %dimsAI.sroa.7.0.copyload.i to i20
  %5 = trunc i32 %dimsAI.sroa.9.0.copyload.i to i20
  %6 = trunc i32 %dimsAO.sroa.7.0.copyload.i to i20
  %7 = trunc i32 %dimsAO.sroa.4.0.copyload.i to i20
  %8 = trunc i32 %dimsAO.sroa.6.0.copyload.i to i20
  %9 = trunc i32 %dimsAO.sroa.0.0.copyload.i to i20
  %10 = trunc i32 %dimsAO.sroa.5.0.copyload.i to i20
  %11 = trunc i32 %dimsW.sroa.4.0.copyload.i to i20
  %12 = trunc i32 %dimsW.sroa.6.0.copyload.i to i20
  br label %for.body.i

for.body.i:                                       ; preds = %if.end239.i, %entry
  %dimsAI.sroa.13.0458.i = phi i32 [ 0, %entry ], [ %40, %if.end239.i ]
  %dimsAO.sroa.10.0457.i = phi i32 [ 0, %entry ], [ %29, %if.end239.i ]
  %dimsAO.sroa.8.0456.i = phi i32 [ 0, %entry ], [ %27, %if.end239.i ]
  %dimsW.sroa.10.0455.i = phi i32 [ 1, %entry ], [ 0, %if.end239.i ]
  %dimsW.sroa.8.0454.i = phi i32 [ 0, %entry ], [ %34, %if.end239.i ]
  %iterator_psum_cnt1.0452.i = phi i32 [ 0, %entry ], [ %22, %if.end239.i ]
  %iterator_pout_cnt0.0451.i = phi i32 [ 0, %entry ], [ %45, %if.end239.i ]
  %13 = trunc i32 0 to i20
  %14 = trunc i32 %iterator_psum_cnt1.0452.i to i20
  %15 = tail call { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr null, i20 0, i20 0, i20 0, i20 0, i20 %13, i20 0, i20 %14)
  %16 = extractvalue { ptr, i20, i20 } %15, 2
  %17 = trunc i32 %dimsAI.sroa.13.0458.i to i20
  %18 = tail call { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.3d.bfp16.p5.p5(ptr addrspace(5) null, <32 x i32> zeroinitializer, i32 0, i20 1, i20 0, i20 %17, i20 %0, i20 0, i20 0, i20 %0)
  %19 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %18, 5
  %20 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %18, 6
  br label %for.body125.i

for.cond.cleanup124.i:                            ; preds = %for.body125.i
  %21 = extractvalue { ptr, i20, i20 } %15, 1
  %22 = zext i20 %16 to i32
  %23 = trunc i32 %dimsAO.sroa.8.0456.i to i20
  %24 = trunc i32 %dimsAO.sroa.10.0457.i to i20
  %25 = tail call { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr null, i20 %6, i20 %7, i20 %8, i20 %9, i20 %23, i20 %10, i20 %24)
  %26 = extractvalue { ptr, i20, i20 } %25, 1
  %27 = zext i20 %26 to i32
  %28 = extractvalue { ptr, i20, i20 } %25, 2
  %29 = zext i20 %28 to i32
  %30 = trunc i32 %dimsW.sroa.8.0454.i to i20
  %31 = trunc i32 %dimsW.sroa.10.0455.i to i20
  %32 = tail call { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr null, i20 0, i20 %11, i20 %12, i20 0, i20 %30, i20 0, i20 %31)
  %33 = extractvalue { ptr, i20, i20 } %32, 1
  %34 = zext i20 %33 to i32
  %35 = extractvalue { ptr, i20, i20 } %32, 2
  br i1 %1, label %if.else.i14, label %if.end239.i

for.body125.i:                                    ; preds = %for.body125.i, %for.body.i
  %36 = trunc i32 0 to i20
  %37 = trunc i32 0 to i20
  %38 = tail call { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.3d.bfp16.p5.p5(ptr addrspace(5) null, <32 x i32> zeroinitializer, i32 0, i20 %2, i20 0, i20 %36, i20 %3, i20 %4, i20 %37, i20 %5)
  %39 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %38, 3
  %40 = zext i20 %39 to i32
  %41 = call i1 @llvm.loop.decrement.i32(i32 0)
  br i1 %41, label %for.body125.i, label %for.cond.cleanup124.i

if.else.i14:                                      ; preds = %for.cond.cleanup124.i
  %add.ptr.i327.i = getelementptr i8, ptr null, i20 0
  br label %if.end239.i

if.end239.i:                                      ; preds = %if.else.i14, %for.cond.cleanup124.i
  %42 = trunc i32 %iterator_pout_cnt0.0451.i to i20
  %43 = tail call { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr null, i20 0, i20 0, i20 1, i20 0, i20 %42, i20 0, i20 0)
  %44 = extractvalue { ptr, i20, i20 } %43, 1
  %45 = zext i20 %44 to i32
  %46 = extractvalue { ptr, i20, i20 } %43, 2
  br i1 %1, label %ret.exit, label %for.body.i

ret.exit: ; preds = %if.end239.i
  ret void
}

; Function Attrs: nounwind memory(none)
declare { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr, i20, i20, i20, i20, i20, i20, i20) #0

; Function Attrs: nounwind memory(argmem: read)
declare { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.3d.bfp16.p5.p5(ptr addrspace(5), <32 x i32>, i32, i20, i20, i20, i20, i20, i20, i20) #1

; Function Attrs: nocallback noduplicate nofree nosync nounwind willreturn
declare i1 @llvm.loop.decrement.i32(i32) #2

; uselistorder directives
uselistorder ptr @llvm.aie2p.add.3d, { 3, 2, 1, 0 }
uselistorder ptr @llvm.aie2p.fifo.ld.pop.576.3d.bfp16.p5.p5, { 1, 0 }

attributes #0 = { nounwind memory(none) }
attributes #1 = { nounwind memory(argmem: read) }
attributes #2 = { nocallback noduplicate nofree nosync nounwind willreturn }

