# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: : not --crash llc -mtriple=aie2p -start-before=greedy %s -o /dev/null --filetype=obj
# RUN: llc -mtriple=aie2p -start-before=greedy -stop-before=virtregrewriter %s -o - | FileCheck %s
# Verify that staged register allocation does not produce an invalid
# rematerialization of a MOV_PD_imm11_pseudo into a composed eds (3D)
# register. The bug occurs when rewriteSuperReg (in AIESuperRegUtils) rewrites
# sub-register definitions in-place (stripping sub-register indices), leaving
# stale VNInfos in ancestor intervals. A later Greedy pass traces back via
# VRM.getOriginal(), finds the rewritten instruction (now a scalar def), and
# rematerializes it as a full eds-class def, producing a register class
# mismatch (e.g. renamable $d3_3d = MOV_PD_imm11_pseudo 128).

---
name:            stale_remat_test
alignment:       32
tracksRegLiveness: true
noPhis:          true
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    true
  hasCalls:        true
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  isCalleeSavedInfoValid: false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
body:             |
  ; CHECK-LABEL: name: stale_remat_test
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
  ; CHECK-NEXT:   [[VBCST_32_:%[0-9]+]]:vec512 = VBCST_32 [[MOV_RLC_imm11_pseudo]]
  ; CHECK-NEXT:   VST_dmx_sts_x_spill [[VBCST_32_]], %stack.1, implicit $sp :: (store (s512) into %stack.1)
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo:%[0-9]+]]:ep_as_32bit = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   dead [[VBCST_32_1:%[0-9]+]]:vec512 = VBCST_32 [[MOV_RLC_imm11_pseudo]]
  ; CHECK-NEXT:   [[VBCST_32_2:%[0-9]+]]:vec512 = VBCST_32 [[MOV_RLC_imm11_pseudo]]
  ; CHECK-NEXT:   VST_dmx_sts_x_spill [[VBCST_32_2]], %stack.0, implicit $sp :: (store (s512) into %stack.0)
  ; CHECK-NEXT:   $p0 = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:er = COPY $r0
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   PseudoJL_IND [[MOV_PD_imm11_pseudo]], csr_aie2p, implicit-def $lr, implicit $p0
  ; CHECK-NEXT:   [[VLDA_512_COMPOSED_REG_SPILL:%[0-9]+]]:vec512 = VLDA_512_COMPOSED_REG_SPILL %stack.1, implicit $sp :: (load (s512) from %stack.1)
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edn_as_32bit = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   undef [[COPY1:%[0-9]+]].sub_dim_size:eds = COPY [[MOV_PD_imm11_pseudo1]]
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo2:%[0-9]+]]:magusrc_and_magudst_and_spill_edj_to_er = MOV_PD_imm11_pseudo 128
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]].sub_dim_stride:eds = COPY [[MOV_PD_imm11_pseudo2]]
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:spill_em_to_er = COPY [[COPY1]].sub_dim_size
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:spill_edj_to_er = COPY [[COPY1]].sub_dim_size
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:spill_edj_to_er = COPY [[COPY1]].sub_dim_size
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:spill_edc_to_er = COPY [[COPY1]].sub_dim_size
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:spill_edc_to_er = COPY [[COPY1]].sub_dim_size
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:spill_edn_to_er = COPY [[COPY1]].sub_dim_size
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:spill_edn_to_er = COPY [[COPY1]].sub_dim_size
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x04000000), %bb.1(0x7c000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[XOR:%[0-9]+]]:er = XOR [[COPY]], [[MOV_RLC_imm11_pseudo1]]
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo3:%[0-9]+]]:ep = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[AND:%[0-9]+]]:er = AND [[XOR]], [[MOV_RLC_imm11_pseudo1]]
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:edcl = COPY [[COPY5]]
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:ednl = COPY [[COPY7]]
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:edjl = COPY [[COPY3]]
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:em_as_32bit = COPY [[COPY2]]
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:edch = COPY [[COPY6]]
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]]:ednh = COPY [[COPY8]]
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]]:edjh = COPY [[COPY4]]
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo3:%[0-9]+]]:ep, dead [[COPY9:%[0-9]+]]:edcl, dead [[COPY13:%[0-9]+]]:edch = PADD_3D_pseudo_split [[MOV_PD_imm11_pseudo3]], [[COPY12]], [[COPY10]], [[COPY11]], [[COPY9]], undef %48:em_as_32bit, [[COPY14]], [[COPY15]], [[COPY13]]
  ; CHECK-NEXT:   VST_dmx_sts_x_idx_imm [[VLDA_512_COMPOSED_REG_SPILL]], [[MOV_PD_imm11_pseudo3]], 0 :: (store (<64 x s16>))
  ; CHECK-NEXT:   PseudoJNZ [[AND]], %bb.1
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo2:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 1
  ; CHECK-NEXT:   [[AND1:%[0-9]+]]:er = AND [[COPY]], [[MOV_RLC_imm11_pseudo2]]
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo4:%[0-9]+]]:eds = MOV_PD_imm11_pseudo 128
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo4:%[0-9]+]].sub_mod:eds = COPY [[MOV_PD_imm11_pseudo4]].sub_dim_size
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]]:spill_edj_to_er = COPY [[MOV_PD_imm11_pseudo4]].sub_dim_size
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo5:%[0-9]+]]:ep_as_32bit = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[COPY17:%[0-9]+]]:spill_edj_to_er = COPY [[MOV_PD_imm11_pseudo4]].sub_dim_size
  ; CHECK-NEXT:   [[COPY18:%[0-9]+]]:spill_edc_to_er = COPY [[MOV_PD_imm11_pseudo4]].sub_dim_size
  ; CHECK-NEXT:   [[COPY19:%[0-9]+]]:edjl = COPY [[MOV_PD_imm11_pseudo4]].sub_dim_size
  ; CHECK-NEXT:   [[COPY20:%[0-9]+]]:edjh = COPY [[MOV_PD_imm11_pseudo4]].sub_dim_size
  ; CHECK-NEXT:   [[COPY21:%[0-9]+]]:spill_edj_to_er = COPY [[MOV_PD_imm11_pseudo4]].sub_dim_size
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo6:%[0-9]+]]:ep_as_32bit = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[COPY22:%[0-9]+]]:spill_edj_to_er = COPY [[MOV_PD_imm11_pseudo4]].sub_dim_size
  ; CHECK-NEXT:   [[COPY23:%[0-9]+]]:spill_edj_to_er = COPY [[MOV_PD_imm11_pseudo4]].sub_dim_size
  ; CHECK-NEXT:   [[COPY24:%[0-9]+]]:edch = COPY [[MOV_PD_imm11_pseudo4]].sub_dim_size
  ; CHECK-NEXT:   [[COPY25:%[0-9]+]]:edch = COPY [[MOV_PD_imm11_pseudo4]].sub_dim_size
  ; CHECK-NEXT:   [[COPY26:%[0-9]+]]:edcl = COPY [[MOV_PD_imm11_pseudo4]].sub_dim_size
  ; CHECK-NEXT:   [[COPY27:%[0-9]+]]:spill_edc_to_er = COPY [[MOV_PD_imm11_pseudo4]].sub_dim_size
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo7:%[0-9]+]]:magusrc_and_magudst_and_spill_em_to_er = MOV_PD_imm11_pseudo 1
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo3:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
  ; CHECK-NEXT:   [[VLDA_512_COMPOSED_REG_SPILL1:%[0-9]+]]:vec512 = VLDA_512_COMPOSED_REG_SPILL %stack.0, implicit $sp :: (load (s512) from %stack.0)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.5(0x40000000), %bb.4(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   PseudoJNZ [[AND1]], %bb.5
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   successors: %bb.5(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   dead [[COPY28:%[0-9]+]]:erf2 = COPY [[MOV_RLC_imm11_pseudo3]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5:
  ; CHECK-NEXT:   successors: %bb.7(0x40000000), %bb.6(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   undef [[COPY29:%[0-9]+]].sub_dim_size:eds = COPY [[MOV_PD_imm11_pseudo4]].sub_dim_size {
  ; CHECK-NEXT:     internal [[COPY29]].sub_dim_stride:eds = COPY [[MOV_PD_imm11_pseudo4]].sub_dim_stride
  ; CHECK-NEXT:     internal [[COPY29]].sub_mod:eds = COPY [[MOV_PD_imm11_pseudo4]].sub_mod
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   [[COPY30:%[0-9]+]]:spill_em_to_er = COPY [[COPY29]].sub_mod
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo8:%[0-9]+]]:ep = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[COPY31:%[0-9]+]]:spill_edn_to_er = COPY [[COPY29]].sub_dim_size
  ; CHECK-NEXT:   [[COPY32:%[0-9]+]]:spill_edn_to_er = COPY [[COPY29]].sub_dim_size
  ; CHECK-NEXT:   [[COPY33:%[0-9]+]]:spill_edc_to_er = COPY [[COPY24]]
  ; CHECK-NEXT:   [[COPY34:%[0-9]+]]:edcl = COPY [[COPY18]]
  ; CHECK-NEXT:   [[COPY35:%[0-9]+]]:ednl = COPY [[COPY31]]
  ; CHECK-NEXT:   [[COPY36:%[0-9]+]]:edjl = COPY [[COPY16]]
  ; CHECK-NEXT:   [[COPY37:%[0-9]+]]:em_as_32bit = COPY [[COPY30]]
  ; CHECK-NEXT:   [[COPY38:%[0-9]+]]:edch = COPY [[COPY33]]
  ; CHECK-NEXT:   [[COPY39:%[0-9]+]]:ednh = COPY [[COPY32]]
  ; CHECK-NEXT:   [[COPY40:%[0-9]+]]:edjh = COPY [[COPY17]]
  ; CHECK-NEXT:   dead [[MOV_PD_imm11_pseudo8:%[0-9]+]]:ep, [[COPY34:%[0-9]+]]:edcl, dead [[COPY38:%[0-9]+]]:edch = PADD_3D_pseudo_split [[MOV_PD_imm11_pseudo8]], [[COPY37]], [[COPY35]], [[COPY36]], [[COPY34]], undef %64:em_as_32bit, [[COPY39]], [[COPY40]], [[COPY38]]
  ; CHECK-NEXT:   [[COPY41:%[0-9]+]]:em_as_32bit = COPY [[COPY29]].sub_mod
  ; CHECK-NEXT:   [[COPY42:%[0-9]+]]:ednl = COPY [[COPY29]].sub_dim_size
  ; CHECK-NEXT:   [[COPY43:%[0-9]+]]:ednh = COPY [[COPY29]].sub_dim_size
  ; CHECK-NEXT:   dead [[MOV_PD_imm11_pseudo5:%[0-9]+]]:ep_as_32bit, [[COPY26:%[0-9]+]]:edcl, dead [[COPY25:%[0-9]+]]:edch = PADD_3D_pseudo_split [[MOV_PD_imm11_pseudo5]], [[COPY41]], [[COPY42]], [[COPY19]], [[COPY26]], undef %56:em_as_32bit, [[COPY43]], [[COPY20]], [[COPY25]]
  ; CHECK-NEXT:   [[COPY44:%[0-9]+]]:spill_edc_to_er = COPY [[COPY29]].sub_dim_size
  ; CHECK-NEXT:   [[COPY45:%[0-9]+]]:spill_em_to_er = COPY [[COPY29]].sub_mod
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo9:%[0-9]+]]:ep = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[COPY46:%[0-9]+]]:spill_edn_to_er = COPY [[COPY29]].sub_dim_size
  ; CHECK-NEXT:   [[COPY47:%[0-9]+]]:spill_edn_to_er = COPY [[COPY29]].sub_dim_size
  ; CHECK-NEXT:   undef [[COPY48:%[0-9]+]].sub_dim_size:eds = COPY [[COPY29]].sub_dim_size
  ; CHECK-NEXT:   [[COPY48:%[0-9]+]].sub_dim_stride:eds = COPY [[COPY29]].sub_dim_stride
  ; CHECK-NEXT:   [[COPY48:%[0-9]+]].sub_mod:eds = COPY [[COPY29]].sub_mod
  ; CHECK-NEXT:   [[COPY49:%[0-9]+]]:edcl = COPY [[COPY27]]
  ; CHECK-NEXT:   [[COPY50:%[0-9]+]]:ednl = COPY [[COPY46]]
  ; CHECK-NEXT:   [[COPY51:%[0-9]+]]:edjl = COPY [[COPY21]]
  ; CHECK-NEXT:   [[COPY52:%[0-9]+]]:em_as_32bit = COPY [[COPY45]]
  ; CHECK-NEXT:   [[COPY53:%[0-9]+]]:edch = COPY [[COPY44]]
  ; CHECK-NEXT:   [[COPY54:%[0-9]+]]:ednh = COPY [[COPY47]]
  ; CHECK-NEXT:   [[COPY55:%[0-9]+]]:edjh = COPY [[COPY22]]
  ; CHECK-NEXT:   dead [[MOV_PD_imm11_pseudo9:%[0-9]+]]:ep, [[COPY49:%[0-9]+]]:edcl, dead [[COPY53:%[0-9]+]]:edch = PADD_3D_pseudo_split [[MOV_PD_imm11_pseudo9]], [[COPY52]], [[COPY50]], [[COPY51]], [[COPY49]], undef %72:em_as_32bit, [[COPY54]], [[COPY55]], [[COPY53]]
  ; CHECK-NEXT:   [[COPY56:%[0-9]+]]:edjh = COPY [[COPY48]].sub_dim_size
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo10:%[0-9]+]]:ep = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[COPY57:%[0-9]+]]:em_as_32bit = COPY [[COPY48]].sub_mod
  ; CHECK-NEXT:   [[COPY58:%[0-9]+]]:ednl = COPY [[COPY48]].sub_dim_size
  ; CHECK-NEXT:   [[COPY59:%[0-9]+]]:edcl = COPY [[COPY34]]
  ; CHECK-NEXT:   [[COPY60:%[0-9]+]]:ednh = COPY [[COPY48]].sub_dim_size
  ; CHECK-NEXT:   [[COPY61:%[0-9]+]]:edch = COPY [[COPY44]]
  ; CHECK-NEXT:   [[COPY62:%[0-9]+]]:edj_as_32bit = COPY [[COPY23]]
  ; CHECK-NEXT:   dead [[MOV_PD_imm11_pseudo10:%[0-9]+]]:ep, dead [[COPY59:%[0-9]+]]:edcl, [[COPY61:%[0-9]+]]:edch = PADD_3D_pseudo_split [[MOV_PD_imm11_pseudo10]], [[COPY57]], [[COPY58]], [[COPY62]], [[COPY59]], undef %94:em_as_32bit, [[COPY60]], [[COPY56]], [[COPY61]]
  ; CHECK-NEXT:   [[COPY63:%[0-9]+]]:spill_edj_to_er = COPY [[COPY62]]
  ; CHECK-NEXT:   [[COPY64:%[0-9]+]]:spill_edc_to_er = COPY [[COPY61]]
  ; CHECK-NEXT:   VST_dmx_sts_x_idx_imm [[VLDA_512_COMPOSED_REG_SPILL1]], [[MOV_PD_imm11_pseudo6]], 0 :: (store (<32 x s16>))
  ; CHECK-NEXT:   [[COPY48:%[0-9]+]].sub_hi_dim_then_sub_dim_stride:eds = COPY [[COPY48]].sub_dim_size
  ; CHECK-NEXT:   [[COPY48:%[0-9]+]].sub_dim_count:eds = COPY [[COPY26]]
  ; CHECK-NEXT:   [[COPY48:%[0-9]+]].sub_hi_dim_then_sub_dim_size:eds = COPY [[COPY48]].sub_dim_size
  ; CHECK-NEXT:   [[COPY48:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = COPY [[COPY44]]
  ; CHECK-NEXT:   undef [[COPY65:%[0-9]+]].sub_lo_dim:eds = COPY [[COPY48]].sub_lo_dim
  ; CHECK-NEXT:   [[COPY65:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = COPY [[COPY48]].sub_hi_dim_then_sub_dim_count
  ; CHECK-NEXT:   [[COPY65:%[0-9]+]].sub_hi_dim_then_sub_dim_size:eds = COPY [[COPY48]].sub_hi_dim_then_sub_dim_size
  ; CHECK-NEXT:   [[COPY65:%[0-9]+]].sub_hi_dim_then_sub_dim_stride:eds = COPY [[COPY48]].sub_hi_dim_then_sub_dim_stride
  ; CHECK-NEXT:   PseudoJNZ [[AND1]], %bb.7
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.6
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6:
  ; CHECK-NEXT:   successors: %bb.7(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   dead [[COPY66:%[0-9]+]]:erf2 = COPY [[MOV_RLC_imm11_pseudo3]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.7:
  ; CHECK-NEXT:   successors: %bb.8(0x04000000), %bb.3(0x7c000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo5:%[0-9]+]]:ep_as_32bit = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[XOR1:%[0-9]+]]:er = XOR [[COPY]], [[MOV_RLC_imm11_pseudo2]]
  ; CHECK-NEXT:   undef [[COPY67:%[0-9]+]].sub_lo_dim:eds = COPY [[COPY65]].sub_lo_dim
  ; CHECK-NEXT:   [[COPY67:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = COPY [[COPY65]].sub_hi_dim_then_sub_dim_count
  ; CHECK-NEXT:   [[COPY67:%[0-9]+]].sub_hi_dim_then_sub_dim_size:eds = COPY [[COPY65]].sub_hi_dim_then_sub_dim_size
  ; CHECK-NEXT:   [[COPY67:%[0-9]+]].sub_hi_dim_then_sub_dim_stride:eds = COPY [[COPY65]].sub_hi_dim_then_sub_dim_stride
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo5:%[0-9]+]]:ep_as_32bit, [[COPY67:%[0-9]+]].sub_dim_count:eds, [[COPY67:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = PADD_3D_pseudo_split [[MOV_PD_imm11_pseudo5]], [[COPY67]].sub_mod, [[COPY67]].sub_dim_size, [[COPY67]].sub_dim_stride, [[COPY67]].sub_dim_count, undef [[COPY67]].sub_hi_dim_then_sub_mod, [[COPY67]].sub_hi_dim_then_sub_dim_size, [[COPY67]].sub_hi_dim_then_sub_dim_stride, [[COPY67]].sub_hi_dim_then_sub_dim_count
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo11:%[0-9]+]]:ep = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[AND2:%[0-9]+]]:er = AND [[XOR1]], [[MOV_RLC_imm11_pseudo2]]
  ; CHECK-NEXT:   [[COPY68:%[0-9]+]]:edjh = COPY [[COPY67]].sub_dim_size
  ; CHECK-NEXT:   [[COPY69:%[0-9]+]]:edch = COPY [[COPY67]].sub_dim_size
  ; CHECK-NEXT:   [[COPY70:%[0-9]+]]:em_as_32bit = COPY [[COPY67]].sub_mod
  ; CHECK-NEXT:   [[COPY71:%[0-9]+]]:ednl = COPY [[COPY67]].sub_dim_size
  ; CHECK-NEXT:   [[COPY72:%[0-9]+]]:edjl = COPY [[COPY67]].sub_dim_stride
  ; CHECK-NEXT:   [[COPY73:%[0-9]+]]:ednh = COPY [[COPY67]].sub_dim_size
  ; CHECK-NEXT:   dead [[MOV_PD_imm11_pseudo11:%[0-9]+]]:ep, [[COPY49:%[0-9]+]]:edcl, dead [[COPY69:%[0-9]+]]:edch = PADD_3D_pseudo_split [[MOV_PD_imm11_pseudo11]], [[COPY70]], [[COPY71]], [[COPY72]], [[COPY49]], undef %72:em_as_32bit, [[COPY73]], [[COPY68]], [[COPY69]]
  ; CHECK-NEXT:   [[COPY74:%[0-9]+]]:edcl = COPY [[COPY67]].sub_dim_size
  ; CHECK-NEXT:   [[COPY75:%[0-9]+]]:edch = COPY [[COPY67]].sub_dim_size
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo6:%[0-9]+]]:ep_as_32bit = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[COPY76:%[0-9]+]]:em_as_32bit = COPY [[COPY67]].sub_mod
  ; CHECK-NEXT:   [[COPY77:%[0-9]+]]:ednl = COPY [[COPY67]].sub_dim_size
  ; CHECK-NEXT:   [[COPY78:%[0-9]+]]:edjl = COPY [[COPY68]]
  ; CHECK-NEXT:   [[COPY79:%[0-9]+]]:ednh = COPY [[COPY67]].sub_dim_size
  ; CHECK-NEXT:   [[COPY80:%[0-9]+]]:edjh = COPY [[COPY68]]
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo6:%[0-9]+]]:ep_as_32bit, dead [[COPY74:%[0-9]+]]:edcl, dead [[COPY75:%[0-9]+]]:edch = PADD_3D_pseudo_split [[MOV_PD_imm11_pseudo6]], [[COPY76]], [[COPY77]], [[COPY78]], [[COPY74]], undef %86:em_as_32bit, [[COPY79]], [[COPY80]], [[COPY75]]
  ; CHECK-NEXT:   [[COPY27:%[0-9]+]]:spill_edc_to_er = COPY [[COPY49]]
  ; CHECK-NEXT:   undef [[MOV_PD_imm11_pseudo4:%[0-9]+]].sub_lo_dim:eds = COPY [[COPY67]].sub_lo_dim
  ; CHECK-NEXT:   [[COPY25:%[0-9]+]]:edch = COPY [[MOV_PD_imm11_pseudo7]]
  ; CHECK-NEXT:   [[COPY26:%[0-9]+]]:edcl = COPY [[MOV_PD_imm11_pseudo4]].sub_dim_count
  ; CHECK-NEXT:   [[COPY23:%[0-9]+]]:spill_edj_to_er = COPY [[COPY63]]
  ; CHECK-NEXT:   [[COPY24:%[0-9]+]]:edch = COPY [[COPY64]]
  ; CHECK-NEXT:   PseudoJNZ [[AND2]], %bb.3
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.8
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.8:
  ; CHECK-NEXT:   successors: %bb.9(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY81:%[0-9]+]]:spill_edj_to_er = COPY [[MOV_PD_imm11_pseudo7]]
  ; CHECK-NEXT:   [[COPY82:%[0-9]+]]:spill_edc_to_er = COPY [[MOV_PD_imm11_pseudo4]].sub_dim_size
  ; CHECK-NEXT:   [[COPY83:%[0-9]+]]:spill_edn_to_er = COPY [[MOV_PD_imm11_pseudo4]].sub_dim_size
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.9:
  ; CHECK-NEXT:   successors: %bb.9(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY84:%[0-9]+]]:edc = COPY [[COPY82]]
  ; CHECK-NEXT:   [[COPY85:%[0-9]+]]:edn = COPY [[COPY83]]
  ; CHECK-NEXT:   [[COPY86:%[0-9]+]]:edj = COPY [[COPY81]]
  ; CHECK-NEXT:   [[COPY87:%[0-9]+]]:em = COPY [[MOV_PD_imm11_pseudo7]]
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo:%[0-9]+]]:ep_as_32bit, dead [[COPY84:%[0-9]+]]:edc = PADD_2D_pseudo_split [[MOV_PD_imm11_pseudo]], [[COPY87]], [[COPY85]], [[COPY86]], [[COPY84]]
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.9
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $r0

    undef %103.sub_dim_size:eds = MOV_PD_imm11_pseudo 0
    %18:erf2 = MOV_RLC_imm11_pseudo 0
    %103.sub_dim_stride:eds = MOV_PD_imm11_pseudo 128
    %7:vec512 = VBCST_32 %18
    %139:ep_as_32bit = MOV_PD_imm11_pseudo 0
    %16:vec512 = VBCST_32 %18
    %28:vec512 = VBCST_32 %18
    undef %89.sub_mod:ed = MOV_PD_imm11_pseudo 1
    $p0 = MOV_PD_imm11_pseudo 0
    %1:er = COPY $r0
    ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    PseudoJL_IND %139, csr_aie2p, implicit-def $lr, implicit killed $p0
    ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    %85:er = MOV_RLC_imm11_pseudo 1
    undef %127.sub_mod:eds = COPY %103.sub_dim_size
    %127.sub_dim_stride:eds = COPY %103.sub_dim_size
    %127.sub_hi_dim_then_sub_dim_stride:eds = COPY %103.sub_dim_size
    %127.sub_dim_count:eds = COPY %103.sub_dim_size
    %127.sub_hi_dim_then_sub_dim_count:eds = COPY %103.sub_dim_size
    %127.sub_dim_size:eds = COPY %103.sub_dim_size
    %127.sub_hi_dim_then_sub_dim_size:eds = COPY %103.sub_dim_size

  bb.1:
    successors: %bb.2(0x04000000), %bb.1(0x7c000000)

    %84:er = XOR %1, %85
    %3:ep = MOV_PD_imm11_pseudo 0
    %81:er = AND %84, %85
    %140:eds = COPY %127
    %3:ep, dead %140.sub_dim_count:eds, dead %140.sub_hi_dim_then_sub_dim_count:eds = PADD_3D_pseudo_split %3, %140.sub_mod, %140.sub_dim_size, %140.sub_dim_stride, %140.sub_dim_count, undef %140.sub_hi_dim_then_sub_mod, %140.sub_hi_dim_then_sub_dim_size, %140.sub_hi_dim_then_sub_dim_stride, %140.sub_hi_dim_then_sub_dim_count
    VST_dmx_sts_x_idx_imm %7, %3, 0 :: (store (<64 x s16>))
    PseudoJNZ %81, %bb.1
    PseudoJ_jump_imm %bb.2

  bb.2:
    successors: %bb.3(0x80000000)

    %87:er = MOV_RLC_imm11_pseudo 1
    %80:er = AND %1, %87
    %103.sub_mod:eds = COPY %103.sub_dim_size
    undef %121.sub_dim_stride:eds = COPY %103.sub_dim_size
    %133:ep_as_32bit = MOV_PD_imm11_pseudo 0
    %121.sub_hi_dim_then_sub_dim_stride:eds = COPY %103.sub_dim_size
    %121.sub_dim_count:eds = COPY %103.sub_dim_size
    undef %117.sub_dim_stride:eds = COPY %103.sub_dim_size
    %117.sub_hi_dim_then_sub_dim_stride:eds = COPY %103.sub_dim_size
    undef %112.sub_dim_stride:eds = COPY %103.sub_dim_size
    %134:ep_as_32bit = MOV_PD_imm11_pseudo 0
    %112.sub_hi_dim_then_sub_dim_stride:eds = COPY %103.sub_dim_size
    undef %107.sub_dim_stride:eds = COPY %103.sub_dim_size
    %107.sub_hi_dim_then_sub_dim_count:eds = COPY %103.sub_dim_size
    %117.sub_hi_dim_then_sub_dim_count:eds = COPY %103.sub_dim_size
    %117.sub_dim_count:eds = COPY %103.sub_dim_size
    %112.sub_dim_count:eds = COPY %103.sub_dim_size

  bb.3:
    successors: %bb.5(0x40000000), %bb.4(0x40000000)

    PseudoJNZ %80, %bb.5
    PseudoJ_jump_imm %bb.4

  bb.4:
    successors: %bb.5(0x80000000)

    %126:erf2 = COPY %18

  bb.5:
    successors: %bb.7(0x40000000), %bb.6(0x40000000)

    %121.sub_mod:eds = COPY %103.sub_mod
    %20:ep = MOV_PD_imm11_pseudo 0
    %121.sub_dim_size:eds = COPY %103.sub_dim_size
    %121.sub_hi_dim_then_sub_dim_size:eds = COPY %103.sub_dim_size
    %121.sub_hi_dim_then_sub_dim_count:eds = COPY %107.sub_hi_dim_then_sub_dim_count
    %141:eds = COPY %121
    dead %20:ep, %141.sub_dim_count:eds, %141.sub_hi_dim_then_sub_dim_count:eds = PADD_3D_pseudo_split %20, %141.sub_mod, %141.sub_dim_size, %141.sub_dim_stride, %141.sub_dim_count, undef %141.sub_hi_dim_then_sub_mod, %141.sub_hi_dim_then_sub_dim_size, %141.sub_hi_dim_then_sub_dim_stride, %141.sub_hi_dim_then_sub_dim_count
    %117.sub_mod:eds = COPY %103.sub_mod
    %117.sub_dim_size:eds = COPY %103.sub_dim_size
    %117.sub_hi_dim_then_sub_dim_size:eds = COPY %103.sub_dim_size
    dead %133:ep_as_32bit, %117.sub_dim_count:eds, %117.sub_hi_dim_then_sub_dim_count:eds = PADD_3D_pseudo_split %133, %117.sub_mod, %117.sub_dim_size, %117.sub_dim_stride, %117.sub_dim_count, undef %117.sub_hi_dim_then_sub_mod, %117.sub_hi_dim_then_sub_dim_size, %117.sub_hi_dim_then_sub_dim_stride, %117.sub_hi_dim_then_sub_dim_count
    %112.sub_hi_dim_then_sub_dim_count:eds = COPY %103.sub_dim_size
    %112.sub_mod:eds = COPY %103.sub_mod
    %31:ep = MOV_PD_imm11_pseudo 0
    %112.sub_dim_size:eds = COPY %103.sub_dim_size
    %112.sub_hi_dim_then_sub_dim_size:eds = COPY %103.sub_dim_size
    %98:eds = COPY %112
    dead %31:ep, %98.sub_dim_count:eds, %98.sub_hi_dim_then_sub_dim_count:eds = PADD_3D_pseudo_split %31, %98.sub_mod, %98.sub_dim_size, %98.sub_dim_stride, %98.sub_dim_count, undef %98.sub_hi_dim_then_sub_mod, %98.sub_hi_dim_then_sub_dim_size, %98.sub_hi_dim_then_sub_dim_stride, %98.sub_hi_dim_then_sub_dim_count
    %107.sub_hi_dim_then_sub_dim_stride:eds = COPY %103.sub_dim_size
    %34:ep = MOV_PD_imm11_pseudo 0
    %107.sub_mod:eds = COPY %103.sub_mod
    %107.sub_dim_size:eds = COPY %103.sub_dim_size
    %107.sub_dim_count:eds = COPY %141.sub_dim_count
    %107.sub_hi_dim_then_sub_dim_size:eds = COPY %103.sub_dim_size
    %107.sub_hi_dim_then_sub_dim_count:eds = COPY %112.sub_hi_dim_then_sub_dim_count
    dead %34:ep, %107.sub_dim_count:eds, %107.sub_hi_dim_then_sub_dim_count:eds = PADD_3D_pseudo_split %34, %107.sub_mod, %107.sub_dim_size, %107.sub_dim_stride, %107.sub_dim_count, undef %107.sub_hi_dim_then_sub_mod, %107.sub_hi_dim_then_sub_dim_size, %107.sub_hi_dim_then_sub_dim_stride, %107.sub_hi_dim_then_sub_dim_count
    VST_dmx_sts_x_idx_imm %28, %134, 0 :: (store (<32 x s16>))
    %103.sub_hi_dim_then_sub_dim_stride:eds = COPY %103.sub_dim_size
    %103.sub_dim_count:eds = COPY %117.sub_dim_count
    %103.sub_hi_dim_then_sub_dim_size:eds = COPY %103.sub_dim_size
    %103.sub_hi_dim_then_sub_dim_count:eds = COPY %112.sub_hi_dim_then_sub_dim_count
    PseudoJNZ %80, %bb.7
    PseudoJ_jump_imm %bb.6

  bb.6:
    successors: %bb.7(0x80000000)

    %102:erf2 = COPY %18

  bb.7:
    successors: %bb.8(0x04000000), %bb.3(0x7c000000)

    %133:ep_as_32bit = MOV_PD_imm11_pseudo 0
    %77:er = XOR %1, %87
    %133:ep_as_32bit, %103.sub_dim_count:eds, %103.sub_hi_dim_then_sub_dim_count:eds = PADD_3D_pseudo_split %133, %103.sub_mod, %103.sub_dim_size, %103.sub_dim_stride, %103.sub_dim_count, undef %103.sub_hi_dim_then_sub_mod, %103.sub_hi_dim_then_sub_dim_size, %103.sub_hi_dim_then_sub_dim_stride, %103.sub_hi_dim_then_sub_dim_count
    %44:ep = MOV_PD_imm11_pseudo 0
    %74:er = AND %77, %87
    %98.sub_hi_dim_then_sub_dim_stride:eds = COPY %103.sub_dim_size
    %98.sub_hi_dim_then_sub_dim_count:eds = COPY %103.sub_dim_size
    %98.sub_mod:eds = COPY %103.sub_mod
    %98.sub_dim_size:eds = COPY %103.sub_dim_size
    %98.sub_dim_stride:eds = COPY %103.sub_dim_stride
    %98.sub_hi_dim_then_sub_dim_size:eds = COPY %103.sub_dim_size
    dead %44:ep, %98.sub_dim_count:eds, %98.sub_hi_dim_then_sub_dim_count:eds = PADD_3D_pseudo_split %44, %98.sub_mod, %98.sub_dim_size, %98.sub_dim_stride, %98.sub_dim_count, undef %98.sub_hi_dim_then_sub_mod, %98.sub_hi_dim_then_sub_dim_size, %98.sub_hi_dim_then_sub_dim_stride, %98.sub_hi_dim_then_sub_dim_count
    undef %92.sub_dim_count:eds = COPY %103.sub_dim_size
    %92.sub_hi_dim_then_sub_dim_count:eds = COPY %103.sub_dim_size
    %134:ep_as_32bit = MOV_PD_imm11_pseudo 0
    %92.sub_mod:eds = COPY %103.sub_mod
    %92.sub_dim_size:eds = COPY %103.sub_dim_size
    %92.sub_dim_stride:eds = COPY %98.sub_hi_dim_then_sub_dim_stride
    %92.sub_hi_dim_then_sub_dim_size:eds = COPY %103.sub_dim_size
    %92.sub_hi_dim_then_sub_dim_stride:eds = COPY %98.sub_hi_dim_then_sub_dim_stride
    %134:ep_as_32bit, dead %92.sub_dim_count:eds, dead %92.sub_hi_dim_then_sub_dim_count:eds = PADD_3D_pseudo_split %134, %92.sub_mod, %92.sub_dim_size, %92.sub_dim_stride, %92.sub_dim_count, undef %92.sub_hi_dim_then_sub_mod, %92.sub_hi_dim_then_sub_dim_size, %92.sub_hi_dim_then_sub_dim_stride, %92.sub_hi_dim_then_sub_dim_count
    %112.sub_dim_count:eds = COPY %98.sub_dim_count
    %117.sub_hi_dim_then_sub_dim_count:eds = COPY %89.sub_mod
    %117.sub_dim_count:eds = COPY %103.sub_dim_count
    PseudoJNZ %74, %bb.3
    PseudoJ_jump_imm %bb.8

  bb.8:
    successors: %bb.9(0x80000000)

    %89.sub_dim_stride:ed = COPY %89.sub_mod
    %89.sub_dim_count:ed = COPY %103.sub_dim_size
    %89.sub_dim_size:ed = COPY %103.sub_dim_size

  bb.9:
    successors: %bb.9(0x80000000)

    %148:ed = COPY %89
    %139:ep_as_32bit, dead %148.sub_dim_count:ed = PADD_2D_pseudo_split %139, %148.sub_mod, %148.sub_dim_size, %148.sub_dim_stride, %148.sub_dim_count
    PseudoJ_jump_imm %bb.9

...
