# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5

# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
#
# RUN: llc -O2 -mtriple=aie2p -start-before=greedy \
# RUN:     -stop-before=aie-unallocated-superreg-rewrite -verify-machineinstrs %s -o - | FileCheck %s

# The goal of this test is to check if we properly insert undef flag on the def side
# of a expanded full copy.  On a sub-register def operand, it refers to the part of the
# register that isn't written. A sub-register def implicitly reads the other parts of the
# register being redefined unless the <undef> flag is set, and a missing flag can
# force the related register to be inserted in liveout set of the predecessors block,
# causing dominance problems.

---
name:            use_all_2d_regs
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: use_all_2d_regs
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   undef [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_stride:ed = MOV_PD_imm11_pseudo 1
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_mod:ed = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edn = MOV_PD_imm11_pseudo -1
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:em = COPY [[MOV_PD_imm11_pseudo]].sub_dim_stride
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:edj = COPY [[MOV_PD_imm11_pseudo]].sub_mod
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:edn = COPY [[MOV_PD_imm11_pseudo]].sub_mod
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:edn = COPY [[MOV_PD_imm11_pseudo]].sub_mod
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:edn = COPY [[MOV_PD_imm11_pseudo]].sub_mod
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:edn = COPY [[MOV_PD_imm11_pseudo]].sub_mod
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:edn = COPY [[MOV_PD_imm11_pseudo]].sub_mod
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_size:ed = COPY [[MOV_PD_imm11_pseudo]].sub_mod
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:edc = COPY [[MOV_PD_imm11_pseudo]].sub_mod
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:edc = COPY [[MOV_PD_imm11_pseudo]].sub_mod
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:edc = COPY [[MOV_PD_imm11_pseudo]].sub_mod
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:edc = COPY [[MOV_PD_imm11_pseudo]].sub_mod
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:edc = COPY [[MOV_PD_imm11_pseudo]].sub_mod
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:edc = COPY [[MOV_PD_imm11_pseudo]].sub_mod
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:edc = COPY [[MOV_PD_imm11_pseudo]].sub_mod
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo:%[0-9]+]].sub_dim_count:ed = COPY [[MOV_PD_imm11_pseudo]].sub_mod
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]]:ed = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]]:edc = COPY [[MOV_PD_imm11_pseudo]].sub_mod
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo2:%[0-9]+]]:ep = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo3:%[0-9]+]]:ep = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo4:%[0-9]+]]:ep = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo5:%[0-9]+]]:ep = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   dead [[MOV_PD_imm11_pseudo2:%[0-9]+]]:ep, [[COPY7:%[0-9]+]]:edc = PADD_2D_pseudo_split [[MOV_PD_imm11_pseudo2]], [[COPY]], [[MOV_PD_imm11_pseudo1]], [[COPY1]], [[COPY7]]
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo6:%[0-9]+]]:ep = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]]:em = COPY [[COPY]]
  ; CHECK-NEXT:   [[COPY17:%[0-9]+]]:edj = COPY [[COPY1]]
  ; CHECK-NEXT:   dead [[MOV_PD_imm11_pseudo3:%[0-9]+]]:ep, [[COPY10:%[0-9]+]]:edc = PADD_2D_pseudo_split [[MOV_PD_imm11_pseudo3]], [[COPY16]], [[COPY2]], [[COPY17]], [[COPY10]]
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo7:%[0-9]+]]:ep = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[COPY18:%[0-9]+]]:em = COPY [[COPY]]
  ; CHECK-NEXT:   [[COPY19:%[0-9]+]]:edj = COPY [[COPY1]]
  ; CHECK-NEXT:   dead [[MOV_PD_imm11_pseudo4:%[0-9]+]]:ep, [[COPY8:%[0-9]+]]:edc = PADD_2D_pseudo_split [[MOV_PD_imm11_pseudo4]], [[COPY18]], [[COPY3]], [[COPY19]], [[COPY8]]
  ; CHECK-NEXT:   [[COPY20:%[0-9]+]]:em = COPY [[COPY]]
  ; CHECK-NEXT:   [[COPY21:%[0-9]+]]:edn = COPY [[MOV_PD_imm11_pseudo1]]
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo8:%[0-9]+]]:ep = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[COPY22:%[0-9]+]]:edj = COPY [[COPY1]]
  ; CHECK-NEXT:   dead [[MOV_PD_imm11_pseudo5:%[0-9]+]]:ep, [[COPY11:%[0-9]+]]:edc = PADD_2D_pseudo_split [[MOV_PD_imm11_pseudo5]], [[COPY20]], [[COPY21]], [[COPY22]], [[COPY11]]
  ; CHECK-NEXT:   [[COPY23:%[0-9]+]]:em = COPY [[COPY]]
  ; CHECK-NEXT:   [[COPY24:%[0-9]+]]:edj = COPY [[COPY1]]
  ; CHECK-NEXT:   dead [[MOV_PD_imm11_pseudo6:%[0-9]+]]:ep, [[COPY9:%[0-9]+]]:edc = PADD_2D_pseudo_split [[MOV_PD_imm11_pseudo6]], [[COPY23]], [[COPY4]], [[COPY24]], [[COPY9]]
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo9:%[0-9]+]]:ep = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[COPY25:%[0-9]+]]:em = COPY [[COPY]]
  ; CHECK-NEXT:   [[COPY26:%[0-9]+]]:edj = COPY [[COPY1]]
  ; CHECK-NEXT:   dead [[MOV_PD_imm11_pseudo7:%[0-9]+]]:ep, [[COPY12:%[0-9]+]]:edc = PADD_2D_pseudo_split [[MOV_PD_imm11_pseudo7]], [[COPY25]], [[COPY5]], [[COPY26]], [[COPY12]]
  ; CHECK-NEXT:   undef [[COPY27:%[0-9]+]].sub_dim_count:ed = COPY [[COPY10]] {
  ; CHECK-NEXT:     internal [[COPY27]].sub_dim_size:ed = COPY [[COPY2]]
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   [[COPY28:%[0-9]+]]:edc = COPY [[COPY14]].sub_dim_count
  ; CHECK-NEXT:   [[COPY29:%[0-9]+]]:edn = COPY [[COPY14]].sub_dim_size
  ; CHECK-NEXT:   [[COPY30:%[0-9]+]]:edj = COPY [[COPY14]].sub_dim_stride
  ; CHECK-NEXT:   [[COPY31:%[0-9]+]]:em = COPY [[COPY14]].sub_mod
  ; CHECK-NEXT:   dead [[MOV_PD_imm11_pseudo9:%[0-9]+]]:ep, [[COPY28:%[0-9]+]]:edc = PADD_2D_pseudo_split [[MOV_PD_imm11_pseudo9]], [[COPY31]], [[COPY29]], [[COPY30]], [[COPY28]]
  ; CHECK-NEXT:   [[COPY32:%[0-9]+]]:em = COPY [[COPY]]
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo10:%[0-9]+]]:ep = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[COPY33:%[0-9]+]]:edj = COPY [[COPY1]]
  ; CHECK-NEXT:   dead [[MOV_PD_imm11_pseudo8:%[0-9]+]]:ep, [[COPY13:%[0-9]+]]:edc = PADD_2D_pseudo_split [[MOV_PD_imm11_pseudo8]], [[COPY32]], [[COPY6]], [[COPY33]], [[COPY13]]
  ; CHECK-NEXT:   [[COPY34:%[0-9]+]]:edn = COPY [[COPY31]]
  ; CHECK-NEXT:   undef [[COPY14:%[0-9]+]].sub_dim_count:ed = COPY [[COPY28]]
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]].sub_dim_size:ed = COPY [[COPY29]]
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]].sub_dim_stride:ed = COPY [[COPY30]]
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]].sub_mod:ed = COPY [[COPY31]]
  ; CHECK-NEXT:   [[COPY35:%[0-9]+]]:em = COPY [[COPY31]]
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:edc = COPY [[COPY27]].sub_dim_count {
  ; CHECK-NEXT:     internal [[COPY2]]:edn = COPY [[COPY27]].sub_dim_size
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   [[COPY36:%[0-9]+]]:edj = COPY [[COPY1]]
  ; CHECK-NEXT:   dead [[MOV_PD_imm11_pseudo10:%[0-9]+]]:ep, [[COPY15:%[0-9]+]]:edc = PADD_2D_pseudo_split [[MOV_PD_imm11_pseudo10]], [[COPY35]], [[COPY34]], [[COPY36]], [[COPY15]]
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  bb.0:
    successors: %bb.1(0x80000000)

    undef %80.sub_dim_stride:ed = MOV_PD_imm11_pseudo 1
    %80.sub_mod:ed = MOV_PD_imm11_pseudo 0
    undef %105.sub_dim_size:ed = MOV_PD_imm11_pseudo -1
    %105.sub_mod:ed = COPY %80.sub_dim_stride
    %105.sub_dim_stride:ed = COPY %80.sub_mod
    undef %101.sub_dim_size:ed = COPY %80.sub_mod
    undef %97.sub_dim_size:ed = COPY %80.sub_mod
    undef %90.sub_dim_size:ed = COPY %80.sub_mod
    undef %86.sub_dim_size:ed = COPY %80.sub_mod
    undef %82.sub_dim_size:ed = COPY %80.sub_mod
    %80.sub_dim_size:ed = COPY %80.sub_mod
    %105.sub_dim_count:ed = COPY %80.sub_mod
    %97.sub_dim_count:ed = COPY %80.sub_mod
    %90.sub_dim_count:ed = COPY %80.sub_mod
    %101.sub_dim_count:ed = COPY %80.sub_mod
    undef %94.sub_dim_count:ed = COPY %80.sub_mod
    %86.sub_dim_count:ed = COPY %80.sub_mod
    %82.sub_dim_count:ed = COPY %80.sub_mod
    %80.sub_dim_count:ed = COPY %80.sub_mod
    undef %77.sub_dim_count:ed = COPY %80.sub_mod

  bb.1:
    successors: %bb.1(0x80000000)

    %10:ep = MOV_PD_imm11_pseudo 0
    %18:ep = MOV_PD_imm11_pseudo 0
    %22:ep = MOV_PD_imm11_pseudo 0
    %26:ep = MOV_PD_imm11_pseudo 0
    dead %10:ep, %105.sub_dim_count:ed = PADD_2D_pseudo_split %10, %105.sub_mod, %105.sub_dim_size, %105.sub_dim_stride, %105.sub_dim_count
    %30:ep = MOV_PD_imm11_pseudo 0
    %101.sub_mod:ed = COPY %105.sub_mod
    %101.sub_dim_stride:ed = COPY %105.sub_dim_stride
    dead %18:ep, %101.sub_dim_count:ed = PADD_2D_pseudo_split %18, %101.sub_mod, %101.sub_dim_size, %101.sub_dim_stride, %101.sub_dim_count
    %34:ep = MOV_PD_imm11_pseudo 0
    %97.sub_mod:ed = COPY %105.sub_mod
    %97.sub_dim_stride:ed = COPY %105.sub_dim_stride
    dead %22:ep, %97.sub_dim_count:ed = PADD_2D_pseudo_split %22, %97.sub_mod, %97.sub_dim_size, %97.sub_dim_stride, %97.sub_dim_count
    %94.sub_mod:ed = COPY %105.sub_mod
    %94.sub_dim_size:ed = COPY %105.sub_dim_size
    %38:ep = MOV_PD_imm11_pseudo 0
    %94.sub_dim_stride:ed = COPY %105.sub_dim_stride
    dead %26:ep, %94.sub_dim_count:ed = PADD_2D_pseudo_split %26, %94.sub_mod, %94.sub_dim_size, %94.sub_dim_stride, %94.sub_dim_count
    %90.sub_mod:ed = COPY %105.sub_mod
    %90.sub_dim_stride:ed = COPY %105.sub_dim_stride
    dead %30:ep, %90.sub_dim_count:ed = PADD_2D_pseudo_split %30, %90.sub_mod, %90.sub_dim_size, %90.sub_dim_stride, %90.sub_dim_count
    %42:ep = MOV_PD_imm11_pseudo 0
    %86.sub_mod:ed = COPY %105.sub_mod
    %86.sub_dim_stride:ed = COPY %105.sub_dim_stride
    dead %34:ep, %86.sub_dim_count:ed = PADD_2D_pseudo_split %34, %86.sub_mod, %86.sub_dim_size, %86.sub_dim_stride, %86.sub_dim_count
    dead %42:ep, %80.sub_dim_count:ed = PADD_2D_pseudo_split %42, %80.sub_mod, %80.sub_dim_size, %80.sub_dim_stride, %80.sub_dim_count
    %82.sub_mod:ed = COPY %105.sub_mod
    %46:ep = MOV_PD_imm11_pseudo 0
    %82.sub_dim_stride:ed = COPY %105.sub_dim_stride
    dead %38:ep, %82.sub_dim_count:ed = PADD_2D_pseudo_split %38, %82.sub_mod, %82.sub_dim_size, %82.sub_dim_stride, %82.sub_dim_count
    %77.sub_dim_size:ed = COPY %80.sub_mod
    %77.sub_mod:ed = COPY %80.sub_mod
    %77.sub_dim_stride:ed = COPY %105.sub_dim_stride
    dead %46:ep, %77.sub_dim_count:ed = PADD_2D_pseudo_split %46, %77.sub_mod, %77.sub_dim_size, %77.sub_dim_stride, %77.sub_dim_count
    PseudoJ_jump_imm %bb.1

...
