# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2p --aie-staged-ra-fine-grained-alloc=false --start-before=greedy --stop-after=aie-superreg-rewrite -o - -verify-machineinstrs %s  | FileCheck %s

# This test verifies the SuperRegRewriter correctly marks dead subregister copies,
# allowing the machine verifier to pass successfully.
#
# Background: When fine-grained allocation is disabled (--aie-staged-ra-fine-grained-alloc=false),
# InlineSpilling may spill full registers even when some subregisters are dead.
# The SuperRegRewriter fix detects effectively-empty live intervals (where a sublane
# is defined but immediately dead at the same SlotIndex) and marks the corresponding
# copy instructions as dead.
#
# Flow:
# Greedy requests to split a 3D register.
# In bb.2 the last 3D padd creates a dead value (sub_hi_dim_then_sub_dim_count).
# This value is never used again (bb.0 and bb.5 define the sublane).
#
# Control Flow Overview:
# bb2 -> bb.4 -> bb.5 -> bb.6
#  ^               |
#  |               v       v ---+
#  |      bb.0 -> bb.1 -> bb.3 -+
#  |                       |
#  +-----------------------+
#
# InlineSpilling can only spill full registers.
# Thus we spill the full register - even the dead subregister.
# Without the fix, these copies lack proper dead markings.

---
name:            heavy_3d_user
alignment:       16
legalized:       true
tracksRegLiveness: true
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    4
  adjustsStack:    true
  hasCalls:        true
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  isCalleeSavedInfoValid: false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:
  - { id: 0, type: default, offset: -16, size: 4, alignment: 16, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 1, type: default, offset: -12, size: 4, alignment: 4, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 2, type: default, offset: -8, size: 4, alignment: 8, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 3, type: default, offset: -4, size: 4, alignment: 4, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
body:             |
  ; CHECK-LABEL: name: heavy_3d_user
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $r0, $r1, $r2, $r3, $r4, $r5, $r6, $r7
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PseudoFI:%[0-9]+]]:ep_as_32bit = PseudoFI %fixed-stack.0, implicit $sp
  ; CHECK-NEXT:   [[LDA_dms_lda_pstm_nrm_imm:%[0-9]+]]:edj_as_32bit_and_edjl, [[PseudoFI:%[0-9]+]]:ep_as_32bit = LDA_dms_lda_pstm_nrm_imm [[PseudoFI]], -4 :: (invariant load (s20) from %fixed-stack.0, align 4)
  ; CHECK-NEXT:   [[LDA_dms_lda_pstm_nrm_imm1:%[0-9]+]]:edj_as_32bit_and_edjh, [[PseudoFI:%[0-9]+]]:ep_as_32bit = LDA_dms_lda_pstm_nrm_imm [[PseudoFI]], -4 :: (invariant load (s20) from %fixed-stack.1, align 8)
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:edjl = COPY [[LDA_dms_lda_pstm_nrm_imm]] {
  ; CHECK-NEXT:     internal %137:edjh = COPY [[LDA_dms_lda_pstm_nrm_imm1]]
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   undef [[COPY1:%[0-9]+]].sub_dim_stride:eds = COPY [[COPY]] {
  ; CHECK-NEXT:     internal [[COPY1]].sub_hi_dim_then_sub_dim_stride:eds = COPY %137
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   ST_DS_SPILL [[COPY1]], %stack.3, implicit $sp :: (store (s256) into %stack.3, align 4)
  ; CHECK-NEXT:   undef [[LDA_dms_lda_idx_imm:%[0-9]+]].sub_mod:eds = LDA_dms_lda_idx_imm [[PseudoFI]], -4 :: (invariant load (s20) from %fixed-stack.3, align 16)
  ; CHECK-NEXT:   ST_DS_SPILL [[LDA_dms_lda_idx_imm]], %stack.5, implicit $sp :: (store (s256) into %stack.5, align 4)
  ; CHECK-NEXT:   [[LDA_dms_lda_idx_imm1:%[0-9]+]]:er = LDA_dms_lda_idx_imm [[PseudoFI]], 0 :: (invariant load (s32) from %fixed-stack.2)
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo:%[0-9]+]]:em_as_32bit = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo1:%[0-9]+]]:edjh = MOV_PD_imm11_pseudo 1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:em_as_32bit = COPY [[MOV_PD_imm11_pseudo]] {
  ; CHECK-NEXT:     internal %143:edjh = COPY [[MOV_PD_imm11_pseudo1]]
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   undef [[COPY3:%[0-9]+]].sub_mod:eds = COPY [[COPY2]] {
  ; CHECK-NEXT:     internal [[COPY3]].sub_hi_dim_then_sub_dim_stride:eds = COPY %143
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   ST_DS_SPILL [[COPY3]], %stack.0, implicit $sp :: (store (s256) into %stack.0, align 4)
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo2:%[0-9]+]]:ep = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:ep = COPY $p0
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo:%[0-9]+]]:erf2 = MOV_RLC_imm11_pseudo 0
  ; CHECK-NEXT:   $p0 = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   undef [[VBCST_32_:%[0-9]+]].sub_512_lo:vec1024 = VBCST_32 [[MOV_RLC_imm11_pseudo]]
  ; CHECK-NEXT:   $p1 = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:er = COPY $r0
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:er = COPY $r1
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:er = COPY $r2
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:er = COPY $r3
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:er = COPY $r4
  ; CHECK-NEXT:   $p2 = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:er = COPY $r5
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:er = COPY $r6
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:er = COPY $r7
  ; CHECK-NEXT:   [[VBCST_32_:%[0-9]+]].sub_512_hi:vec1024 = COPY [[VBCST_32_]].sub_512_lo
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo3:%[0-9]+]]:eps = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   PseudoJL_IND [[MOV_PD_imm11_pseudo2]], csr_aie2p, implicit-def $lr, implicit $p0, implicit killed $p1, implicit killed $p2
  ; CHECK-NEXT:   [[LDA_DS_SPILL:%[0-9]+]]:eds = LDA_DS_SPILL %stack.0, implicit $sp :: (load (s256) from %stack.0, align 4)
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:em_as_32bit = COPY [[LDA_DS_SPILL]].sub_mod {
  ; CHECK-NEXT:     internal %144:edjh = COPY [[LDA_DS_SPILL]].sub_hi_dim_then_sub_dim_stride
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]]:em_as_32bit = COPY [[COPY13]] {
  ; CHECK-NEXT:     internal %113:edjh = COPY %144
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 1
  ; CHECK-NEXT:   [[LDA_DS_SPILL1:%[0-9]+]]:eds = LDA_DS_SPILL %stack.5, implicit $sp :: (load (s256) from %stack.5, align 4)
  ; CHECK-NEXT:   undef [[COPY15:%[0-9]+]].sub_mod:eds = COPY [[LDA_DS_SPILL1]].sub_mod
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]].sub_dim_stride:eds = COPY [[COPY5]]
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]].sub_hi_dim_then_sub_dim_size:eds = COPY [[COPY6]]
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]].sub_hi_dim_then_sub_dim_stride:eds = COPY [[COPY7]]
  ; CHECK-NEXT:   undef [[COPY16:%[0-9]+]].sub_mod:eds = COPY [[COPY8]]
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]].sub_dim_stride:eds = COPY [[COPY9]]
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]].sub_hi_dim_then_sub_dim_stride:eds = COPY [[COPY10]]
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]].sub_dim_size:eds = COPY [[COPY11]]
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]].sub_hi_dim_then_sub_dim_size:eds = COPY [[COPY12]]
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]].sub_dim_count:eds = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]].sub_dim_size:eds = COPY [[COPY14]]
  ; CHECK-NEXT:   undef [[COPY17:%[0-9]+]].sub_lo_dim:eds = COPY [[COPY15]].sub_lo_dim {
  ; CHECK-NEXT:     internal [[COPY17]].sub_hi_dim_then_sub_dim_size:eds = COPY [[COPY15]].sub_hi_dim_then_sub_dim_size
  ; CHECK-NEXT:     internal [[COPY17]].sub_hi_dim_then_sub_dim_stride:eds = COPY [[COPY15]].sub_hi_dim_then_sub_dim_stride
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   [[COPY18:%[0-9]+]]:em_as_32bit = COPY %113
  ; CHECK-NEXT:   [[COPY19:%[0-9]+]]:edch = COPY [[COPY14]]
  ; CHECK-NEXT:   undef [[COPY20:%[0-9]+]].sub_mod:eds = COPY [[COPY18]] {
  ; CHECK-NEXT:     internal [[COPY20]].sub_hi_dim_then_sub_dim_count:eds = COPY [[COPY19]]
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   ST_DS_SPILL [[COPY20]], %stack.2, implicit $sp :: (store (s256) into %stack.2, align 4)
  ; CHECK-NEXT:   undef [[COPY21:%[0-9]+]].sub_dim_count:eds = COPY [[COPY14]]
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = COPY [[COPY14]]
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]].sub_dim_count:eds = COPY [[COPY14]]
  ; CHECK-NEXT:   undef [[COPY22:%[0-9]+]].sub_lo_dim:eds = COPY [[COPY16]].sub_lo_dim {
  ; CHECK-NEXT:     internal [[COPY22]].sub_hi_dim_then_sub_dim_count:eds = COPY [[COPY16]].sub_hi_dim_then_sub_dim_count
  ; CHECK-NEXT:     internal [[COPY22]].sub_hi_dim_then_sub_dim_size:eds = COPY [[COPY16]].sub_hi_dim_then_sub_dim_size
  ; CHECK-NEXT:     internal [[COPY22]].sub_hi_dim_then_sub_dim_stride:eds = COPY [[COPY16]].sub_hi_dim_then_sub_dim_stride
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   ST_DS_SPILL [[COPY22]], %stack.1, implicit $sp :: (store (s256) into %stack.1, align 4)
  ; CHECK-NEXT:   [[LDA_DS_SPILL2:%[0-9]+]]:eds = LDA_DS_SPILL %stack.3, implicit $sp :: (load (s256) from %stack.3, align 4)
  ; CHECK-NEXT:   [[COPY23:%[0-9]+]]:edjl = COPY [[LDA_DS_SPILL2]].sub_dim_stride {
  ; CHECK-NEXT:     internal %138:edjh = COPY [[LDA_DS_SPILL2]].sub_hi_dim_then_sub_dim_stride
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   [[COPY24:%[0-9]+]]:edjl = COPY [[COPY23]] {
  ; CHECK-NEXT:     internal %132:edjh = COPY %138
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   [[COPY25:%[0-9]+]]:edch = COPY %113
  ; CHECK-NEXT:   [[COPY26:%[0-9]+]]:edcl = COPY [[COPY14]]
  ; CHECK-NEXT:   undef [[COPY27:%[0-9]+]].sub_dim_count:eds = COPY [[COPY26]] {
  ; CHECK-NEXT:     internal [[COPY27]].sub_dim_stride:eds = COPY [[COPY24]]
  ; CHECK-NEXT:     internal [[COPY27]].sub_hi_dim_then_sub_dim_count:eds = COPY [[COPY25]]
  ; CHECK-NEXT:     internal [[COPY27]].sub_hi_dim_then_sub_dim_stride:eds = COPY %132
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   ST_DS_SPILL [[COPY27]], %stack.3, implicit $sp :: (store (s256) into %stack.3, align 4)
  ; CHECK-NEXT:   undef [[COPY28:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = COPY [[COPY14]]
  ; CHECK-NEXT:   ST_DS_SPILL [[COPY28]], %stack.4, implicit $sp :: (store (s256) into %stack.4, align 4)
  ; CHECK-NEXT:   [[COPY29:%[0-9]+]]:edcl = COPY [[COPY14]]
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   [[COPY30:%[0-9]+]]:eldfiforeg = COPY [[VBCST_32_]]
  ; CHECK-NEXT:   [[AND:%[0-9]+]]:er = AND [[LDA_dms_lda_idx_imm1]], [[MOV_RLC_imm11_pseudo1]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY31:%[0-9]+]]:edcl = COPY [[COPY21]].sub_dim_count
  ; CHECK-NEXT:   [[LDA_DS_SPILL3:%[0-9]+]]:eds = LDA_DS_SPILL %stack.2, implicit $sp :: (load (s256) from %stack.2, align 4)
  ; CHECK-NEXT:   [[COPY32:%[0-9]+]]:em_as_32bit = COPY [[LDA_DS_SPILL3]].sub_mod {
  ; CHECK-NEXT:     internal %126:edch = COPY [[LDA_DS_SPILL3]].sub_hi_dim_then_sub_dim_count
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   [[COPY33:%[0-9]+]]:edjl = COPY [[COPY4]]
  ; CHECK-NEXT:   undef [[COPY34:%[0-9]+]].sub_lo_dim:eds = COPY [[COPY17]].sub_lo_dim {
  ; CHECK-NEXT:     internal [[COPY34]].sub_hi_dim_then_sub_dim_size:eds = COPY [[COPY17]].sub_hi_dim_then_sub_dim_size
  ; CHECK-NEXT:     internal [[COPY34]].sub_hi_dim_then_sub_dim_stride:eds = COPY [[COPY17]].sub_hi_dim_then_sub_dim_stride
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   [[COPY35:%[0-9]+]]:ednl = COPY [[COPY34]].sub_dim_size
  ; CHECK-NEXT:   [[COPY36:%[0-9]+]]:edcl = COPY [[COPY31]]
  ; CHECK-NEXT:   [[COPY37:%[0-9]+]]:ednh = COPY [[COPY34]].sub_dim_size
  ; CHECK-NEXT:   [[COPY38:%[0-9]+]]:edjh = COPY [[COPY33]]
  ; CHECK-NEXT:   undef [[COPY39:%[0-9]+]].sub_mod:eds = COPY [[COPY32]] {
  ; CHECK-NEXT:     internal [[COPY39]].sub_hi_dim_then_sub_dim_count:eds = COPY %126
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   ST_DS_SPILL [[COPY39]], %stack.2, implicit $sp :: (store (s256) into %stack.2, align 4)
  ; CHECK-NEXT:   [[COPY40:%[0-9]+]]:edcl = COPY [[COPY36]]
  ; CHECK-NEXT:   [[COPY41:%[0-9]+]]:ednl = COPY [[COPY35]]
  ; CHECK-NEXT:   [[COPY42:%[0-9]+]]:edjl = COPY [[COPY33]]
  ; CHECK-NEXT:   [[COPY43:%[0-9]+]]:em_as_32bit = COPY [[COPY32]]
  ; CHECK-NEXT:   [[COPY44:%[0-9]+]]:edch = COPY %126
  ; CHECK-NEXT:   [[COPY45:%[0-9]+]]:ednh = COPY [[COPY37]]
  ; CHECK-NEXT:   [[COPY46:%[0-9]+]]:edjh = COPY [[COPY38]]
  ; CHECK-NEXT:   undef [[COPY47:%[0-9]+]].sub_ptr:epsrfldf = COPY [[MOV_PD_imm11_pseudo3]]
  ; CHECK-NEXT:   [[COPY47:%[0-9]+]].sub_fifo:epsrfldf = COPY [[COPY30]]
  ; CHECK-NEXT:   [[COPY47:%[0-9]+]].sub_avail:epsrfldf = COPY [[MOV_RLC_imm11_pseudo]]
  ; CHECK-NEXT:   dead [[VLD_POP_576_3D_pseudo_split:%[0-9]+]]:vec576, dead [[COPY47:%[0-9]+]].sub_ptr:epsrfldf, dead [[COPY47:%[0-9]+]].sub_fifo:epsrfldf, dead [[COPY47:%[0-9]+]].sub_avail:epsrfldf, dead [[COPY40:%[0-9]+]]:edcl, dead [[COPY44:%[0-9]+]]:edch = VLD_POP_576_3D_pseudo_split [[COPY47]].sub_ptr, [[COPY47]].sub_fifo, [[COPY47]].sub_avail, [[COPY43]], [[COPY41]], [[COPY42]], [[COPY40]], undef %99:em_as_32bit, [[COPY45]], [[COPY46]], [[COPY44]], implicit-def $srfifo_uf :: (load unknown-size from `ptr addrspace(5) null`, align 1, addrspace 5)
  ; CHECK-NEXT:   [[LDA_DS_SPILL4:%[0-9]+]]:eds = LDA_DS_SPILL %stack.4, implicit $sp :: (load (s256) from %stack.4, align 4)
  ; CHECK-NEXT:   undef [[COPY48:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = COPY [[LDA_DS_SPILL4]].sub_hi_dim_then_sub_dim_count
  ; CHECK-NEXT:   [[COPY48:%[0-9]+]].sub_dim_stride:eds = COPY [[COPY14]]
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo4:%[0-9]+]]:ep = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   undef [[COPY49:%[0-9]+]].sub_dim_count:eds = COPY [[COPY29]] {
  ; CHECK-NEXT:     internal [[COPY49]].sub_mod:eds = COPY [[COPY14]]
  ; CHECK-NEXT:     internal [[COPY49]].sub_hi_dim_then_sub_dim_stride:eds = COPY %113
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   ST_DS_SPILL [[COPY49]], %stack.0, implicit $sp :: (store (s256) into %stack.0, align 4)
  ; CHECK-NEXT:   [[COPY48:%[0-9]+]].sub_mod:eds = COPY [[COPY14]]
  ; CHECK-NEXT:   [[COPY48:%[0-9]+]].sub_dim_size:eds = COPY [[COPY34]].sub_dim_size
  ; CHECK-NEXT:   [[COPY48:%[0-9]+]].sub_dim_count:eds = COPY [[COPY34]].sub_dim_count
  ; CHECK-NEXT:   [[COPY48:%[0-9]+]].sub_hi_dim_then_sub_dim_size:eds = COPY [[COPY34]].sub_dim_size
  ; CHECK-NEXT:   [[COPY48:%[0-9]+]].sub_hi_dim_then_sub_dim_stride:eds = COPY [[COPY48]].sub_dim_stride
  ; CHECK-NEXT:   dead [[MOV_PD_imm11_pseudo4:%[0-9]+]]:ep, [[COPY48:%[0-9]+]].sub_dim_count:eds, [[COPY48:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = PADD_3D_pseudo_split [[MOV_PD_imm11_pseudo4]], [[COPY48]].sub_mod, [[COPY48]].sub_dim_size, [[COPY48]].sub_dim_stride, [[COPY48]].sub_dim_count, undef [[COPY48]].sub_hi_dim_then_sub_mod, [[COPY48]].sub_hi_dim_then_sub_dim_size, [[COPY48]].sub_hi_dim_then_sub_dim_stride, [[COPY48]].sub_hi_dim_then_sub_dim_count
  ; CHECK-NEXT:   ST_DS_SPILL [[COPY48]], %stack.4, implicit $sp :: (store (s256) into %stack.4, align 4)
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.4(0x40000000), %bb.5(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   undef [[COPY17:%[0-9]+]].sub_lo_dim:eds = COPY [[COPY34]].sub_lo_dim {
  ; CHECK-NEXT:     internal [[COPY17]].sub_hi_dim_then_sub_dim_size:eds = COPY [[COPY34]].sub_hi_dim_then_sub_dim_size
  ; CHECK-NEXT:     internal [[COPY17]].sub_hi_dim_then_sub_dim_stride:eds = COPY [[COPY34]].sub_hi_dim_then_sub_dim_stride
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo5:%[0-9]+]]:ep = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo6:%[0-9]+]]:ep = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[LDA_DS_SPILL5:%[0-9]+]]:eds = LDA_DS_SPILL %stack.3, implicit $sp :: (load (s256) from %stack.3, align 4)
  ; CHECK-NEXT:   [[COPY50:%[0-9]+]]:edcl = COPY [[LDA_DS_SPILL5]].sub_dim_count {
  ; CHECK-NEXT:     internal %106:edjl = COPY [[LDA_DS_SPILL5]].sub_dim_stride
  ; CHECK-NEXT:     internal %104:edch = COPY [[LDA_DS_SPILL5]].sub_hi_dim_then_sub_dim_count
  ; CHECK-NEXT:     internal %105:edjh = COPY [[LDA_DS_SPILL5]].sub_hi_dim_then_sub_dim_stride
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   [[LDA_DS_SPILL6:%[0-9]+]]:eds = LDA_DS_SPILL %stack.0, implicit $sp :: (load (s256) from %stack.0, align 4)
  ; CHECK-NEXT:   dead [[COPY51:%[0-9]+]]:edcl = COPY [[LDA_DS_SPILL6]].sub_dim_count {
  ; CHECK-NEXT:     internal %109:em_as_32bit = COPY [[LDA_DS_SPILL6]].sub_mod
  ; CHECK-NEXT:     internal dead %108:edjh = COPY [[LDA_DS_SPILL6]].sub_hi_dim_then_sub_dim_stride
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   [[COPY52:%[0-9]+]]:ednl = COPY %109
  ; CHECK-NEXT:   [[COPY53:%[0-9]+]]:em_as_32bit = COPY %109
  ; CHECK-NEXT:   [[COPY54:%[0-9]+]]:ednh = COPY [[COPY52]]
  ; CHECK-NEXT:   [[LDA_DS_SPILL7:%[0-9]+]]:eds = LDA_DS_SPILL %stack.1, implicit $sp :: (load (s256) from %stack.1, align 4)
  ; CHECK-NEXT:   dead [[MOV_PD_imm11_pseudo5:%[0-9]+]]:ep, [[LDA_DS_SPILL7:%[0-9]+]].sub_dim_count:eds, [[LDA_DS_SPILL7:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = PADD_3D_pseudo_split [[MOV_PD_imm11_pseudo5]], [[LDA_DS_SPILL7]].sub_mod, [[LDA_DS_SPILL7]].sub_dim_size, [[LDA_DS_SPILL7]].sub_dim_stride, [[LDA_DS_SPILL7]].sub_dim_count, undef [[LDA_DS_SPILL7]].sub_hi_dim_then_sub_mod, [[LDA_DS_SPILL7]].sub_hi_dim_then_sub_dim_size, [[LDA_DS_SPILL7]].sub_hi_dim_then_sub_dim_stride, [[LDA_DS_SPILL7]].sub_hi_dim_then_sub_dim_count
  ; CHECK-NEXT:   ST_DS_SPILL [[LDA_DS_SPILL7]], %stack.1, implicit $sp :: (store (s256) into %stack.1, align 4)
  ; CHECK-NEXT:   dead [[MOV_PD_imm11_pseudo6:%[0-9]+]]:ep, [[COPY50:%[0-9]+]]:edcl, dead [[PADD_3D_pseudo_split:%[0-9]+]]:edch = PADD_3D_pseudo_split [[MOV_PD_imm11_pseudo6]], [[COPY53]], [[COPY52]], %106, [[COPY50]], undef %107:em_as_32bit, [[COPY54]], %105, [[PADD_3D_pseudo_split]]
  ; CHECK-NEXT:   undef [[COPY55:%[0-9]+]].sub_dim_count:eds = COPY [[COPY50]] {
  ; CHECK-NEXT:     internal [[COPY55]].sub_dim_stride:eds = COPY %106
  ; CHECK-NEXT:     internal [[COPY55]].sub_hi_dim_then_sub_dim_stride:eds = COPY %105
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   ST_DS_SPILL [[COPY55]], %stack.3, implicit $sp :: (store (s256) into %stack.3, align 4)
  ; CHECK-NEXT:   PseudoJNZ [[AND]], %bb.4
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.3(0x7c000000), %bb.2(0x04000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY34:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = COPY [[COPY34]].sub_dim_count
  ; CHECK-NEXT:   [[COPY21:%[0-9]+]]:eds = COPY [[COPY34]]
  ; CHECK-NEXT:   undef [[COPY56:%[0-9]+]].sub_fifo:epsrfldf = COPY [[VBCST_32_]]
  ; CHECK-NEXT:   [[COPY56:%[0-9]+]].sub_ptr:epsrfldf = COPY [[MOV_PD_imm11_pseudo3]]
  ; CHECK-NEXT:   [[COPY56:%[0-9]+]].sub_avail:epsrfldf = COPY [[MOV_RLC_imm11_pseudo]]
  ; CHECK-NEXT:   dead [[VLD_POP_576_3D_pseudo_split1:%[0-9]+]]:vec576, dead [[COPY56:%[0-9]+]].sub_ptr:epsrfldf, dead [[COPY56:%[0-9]+]].sub_fifo:epsrfldf, dead [[COPY56:%[0-9]+]].sub_avail:epsrfldf, [[COPY21:%[0-9]+]].sub_dim_count:eds, [[COPY21:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VLD_POP_576_3D_pseudo_split [[COPY56]].sub_ptr, [[COPY56]].sub_fifo, [[COPY56]].sub_avail, [[COPY21]].sub_mod, [[COPY21]].sub_dim_size, [[COPY21]].sub_dim_stride, [[COPY21]].sub_dim_count, undef [[COPY21]].sub_hi_dim_then_sub_mod, [[COPY21]].sub_hi_dim_then_sub_dim_size, [[COPY21]].sub_hi_dim_then_sub_dim_stride, [[COPY21]].sub_hi_dim_then_sub_dim_count, implicit-def $srfifo_uf :: (load unknown-size from `ptr addrspace(5) null`, align 1, addrspace 5)
  ; CHECK-NEXT:   PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.3, implicit $ls, implicit $le
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   successors: %bb.5(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5:
  ; CHECK-NEXT:   successors: %bb.6(0x04000000), %bb.1(0x7c000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo7:%[0-9]+]]:ep = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[XOR:%[0-9]+]]:er = XOR [[LDA_dms_lda_idx_imm1]], [[MOV_RLC_imm11_pseudo1]]
  ; CHECK-NEXT:   [[LDA_DS_SPILL8:%[0-9]+]]:eds = LDA_DS_SPILL %stack.0, implicit $sp :: (load (s256) from %stack.0, align 4)
  ; CHECK-NEXT:   [[COPY29:%[0-9]+]]:edcl = COPY [[LDA_DS_SPILL8]].sub_dim_count {
  ; CHECK-NEXT:     internal [[COPY14]]:em_as_32bit = COPY [[LDA_DS_SPILL8]].sub_mod
  ; CHECK-NEXT:     internal %113:edjh = COPY [[LDA_DS_SPILL8]].sub_hi_dim_then_sub_dim_stride
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   [[COPY57:%[0-9]+]]:edjl = COPY [[COPY14]]
  ; CHECK-NEXT:   [[COPY58:%[0-9]+]]:ednl = COPY [[COPY14]]
  ; CHECK-NEXT:   [[COPY59:%[0-9]+]]:ednh = COPY [[COPY14]]
  ; CHECK-NEXT:   [[COPY60:%[0-9]+]]:edch = COPY [[COPY14]]
  ; CHECK-NEXT:   [[AND1:%[0-9]+]]:er = AND [[XOR]], [[MOV_RLC_imm11_pseudo1]]
  ; CHECK-NEXT:   dead [[MOV_PD_imm11_pseudo7:%[0-9]+]]:ep, [[COPY29:%[0-9]+]]:edcl, dead [[COPY60:%[0-9]+]]:edch = PADD_3D_pseudo_split [[MOV_PD_imm11_pseudo7]], [[COPY14]], [[COPY58]], [[COPY57]], [[COPY29]], undef %118:em_as_32bit, [[COPY59]], %113, [[COPY60]]
  ; CHECK-NEXT:   [[LDA_DS_SPILL9:%[0-9]+]]:eds = LDA_DS_SPILL %stack.3, implicit $sp :: (load (s256) from %stack.3, align 4)
  ; CHECK-NEXT:   [[LDA_DS_SPILL9:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = COPY [[COPY14]]
  ; CHECK-NEXT:   ST_DS_SPILL [[LDA_DS_SPILL9]], %stack.3, implicit $sp :: (store (s256) into %stack.3, align 4)
  ; CHECK-NEXT:   PseudoJNZ [[AND1]], %bb.1
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.6
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6:
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $p0, $r0, $r1, $r2, $r3, $r4, $r5, $r6, $r7

    %16:ep_as_32bit = PseudoFI %fixed-stack.3, implicit $sp
    undef %139.sub_dim_stride:eds, %16:ep_as_32bit = LDA_dms_lda_pstm_nrm_imm %16, -4 :: (invariant load (s20) from %fixed-stack.3, align 4)
    %139.sub_hi_dim_then_sub_dim_stride:eds, %16:ep_as_32bit = LDA_dms_lda_pstm_nrm_imm %16, -4 :: (invariant load (s20) from %fixed-stack.2, align 8)
    undef %145.sub_mod:eds = LDA_dms_lda_idx_imm %16, -4 :: (invariant load (s20) from %fixed-stack.0, align 16)
    %15:er = LDA_dms_lda_idx_imm %16, 0 :: (invariant load (s32) from %fixed-stack.1)
    undef %134.sub_mod:eds = MOV_PD_imm11_pseudo 0
    %134.sub_hi_dim_then_sub_dim_stride:eds = MOV_PD_imm11_pseudo 1
    %18:ep = MOV_PD_imm11_pseudo 0
    %10:ep = COPY $p0
    %37:erf2 = MOV_RLC_imm11_pseudo 0
    $p0 = MOV_PD_imm11_pseudo 0
    undef %53.sub_512_lo:vec1024 = VBCST_32 %37
    $p1 = MOV_PD_imm11_pseudo 0
    %0:er = COPY $r0
    %1:er = COPY $r1
    %2:er = COPY $r2
    %3:er = COPY $r3
    %4:er = COPY $r4
    $p2 = MOV_PD_imm11_pseudo 0
    %5:er = COPY $r5
    %6:er = COPY $r6
    %7:er = COPY $r7
    %53.sub_512_hi:vec1024 = COPY %53.sub_512_lo
    ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    %52:eps = MOV_PD_imm11_pseudo 0
    PseudoJL_IND %18, csr_aie2p, implicit-def $lr, implicit $p0, implicit killed $p1, implicit killed $p2
    %124:er = MOV_RLC_imm11_pseudo 1
    %145.sub_dim_stride:eds = COPY %0
    %145.sub_hi_dim_then_sub_dim_size:eds = COPY %1
    %145.sub_hi_dim_then_sub_dim_stride:eds = COPY %2
    undef %142.sub_mod:eds = COPY %3
    %142.sub_dim_stride:eds = COPY %4
    %142.sub_hi_dim_then_sub_dim_stride:eds = COPY %5
    %142.sub_dim_size:eds = COPY %6
    %142.sub_hi_dim_then_sub_dim_size:eds = COPY %7
    %145.sub_dim_count:eds = MOV_PD_imm11_pseudo 0
    %145.sub_dim_size:eds = COPY %134.sub_mod
    undef %148.sub_mod:eds = COPY %134.sub_hi_dim_then_sub_dim_stride
    %148.sub_hi_dim_then_sub_dim_count:eds = COPY %134.sub_mod
    undef %172.sub_dim_count:eds = COPY %134.sub_mod
    %142.sub_hi_dim_then_sub_dim_count:eds = COPY %134.sub_mod
    %142.sub_dim_count:eds = COPY %134.sub_mod
    %139.sub_hi_dim_then_sub_dim_count:eds = COPY %134.sub_hi_dim_then_sub_dim_stride
    %139.sub_dim_count:eds = COPY %134.sub_mod
    undef %153.sub_hi_dim_then_sub_dim_count:eds = COPY %134.sub_mod
    %134.sub_dim_count:eds = COPY %134.sub_mod
    ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    %130:eldfiforeg = COPY %53
    %120:er = AND %15, %124

  bb.1:
    successors: %bb.3(0x80000000)

    %148.sub_dim_stride:eds = COPY %10
    %148.sub_dim_size:eds = COPY %145.sub_dim_size
    %148.sub_dim_count:eds = COPY %172.sub_dim_count
    %148.sub_hi_dim_then_sub_dim_size:eds = COPY %145.sub_dim_size
    %148.sub_hi_dim_then_sub_dim_stride:eds = COPY %148.sub_dim_stride
    %168:eds = COPY %148
    undef %167.sub_ptr:epsrfldf = COPY %52
    %167.sub_fifo:epsrfldf = COPY %130
    %167.sub_avail:epsrfldf = COPY %37
    dead %147:vec576, dead %167.sub_ptr:epsrfldf, dead %167.sub_fifo:epsrfldf, dead %167.sub_avail:epsrfldf, dead %168.sub_dim_count:eds, dead %168.sub_hi_dim_then_sub_dim_count:eds = VLD_POP_576_3D_pseudo_split %167.sub_ptr, %167.sub_fifo, %167.sub_avail, %168.sub_mod, %168.sub_dim_size, %168.sub_dim_stride, %168.sub_dim_count, undef %168.sub_hi_dim_then_sub_mod, %168.sub_hi_dim_then_sub_dim_size, %168.sub_hi_dim_then_sub_dim_stride, %168.sub_hi_dim_then_sub_dim_count, implicit-def $srfifo_uf :: (load unknown-size from `ptr addrspace(5) null`, align 1, addrspace 5)
    %153.sub_dim_stride:eds = COPY %134.sub_mod
    %40:ep = MOV_PD_imm11_pseudo 0
    %153.sub_mod:eds = COPY %134.sub_mod
    %153.sub_dim_size:eds = COPY %145.sub_dim_size
    %153.sub_dim_count:eds = COPY %145.sub_dim_count
    %153.sub_hi_dim_then_sub_dim_size:eds = COPY %145.sub_dim_size
    %153.sub_hi_dim_then_sub_dim_stride:eds = COPY %153.sub_dim_stride
    dead %40:ep, %153.sub_dim_count:eds, %153.sub_hi_dim_then_sub_dim_count:eds = PADD_3D_pseudo_split %40, %153.sub_mod, %153.sub_dim_size, %153.sub_dim_stride, %153.sub_dim_count, undef %153.sub_hi_dim_then_sub_mod, %153.sub_hi_dim_then_sub_dim_size, %153.sub_hi_dim_then_sub_dim_stride, %153.sub_hi_dim_then_sub_dim_count
    PseudoJ_jump_imm %bb.3

  bb.2:
    successors: %bb.4(0x40000000), %bb.5(0x40000000)

    %69:ep = MOV_PD_imm11_pseudo 0
    %76:ep = MOV_PD_imm11_pseudo 0
    %139.sub_dim_size:eds = COPY %134.sub_mod
    %139.sub_mod:eds = COPY %134.sub_mod
    %139.sub_hi_dim_then_sub_dim_size:eds = COPY %139.sub_dim_size
    dead %69:ep, %142.sub_dim_count:eds, %142.sub_hi_dim_then_sub_dim_count:eds = PADD_3D_pseudo_split %69, %142.sub_mod, %142.sub_dim_size, %142.sub_dim_stride, %142.sub_dim_count, undef %142.sub_hi_dim_then_sub_mod, %142.sub_hi_dim_then_sub_dim_size, %142.sub_hi_dim_then_sub_dim_stride, %142.sub_hi_dim_then_sub_dim_count
    dead %76:ep, %139.sub_dim_count:eds, %139.sub_hi_dim_then_sub_dim_count:eds = PADD_3D_pseudo_split %76, %139.sub_mod, %139.sub_dim_size, %139.sub_dim_stride, %139.sub_dim_count, undef %139.sub_hi_dim_then_sub_mod, %139.sub_hi_dim_then_sub_dim_size, %139.sub_hi_dim_then_sub_dim_stride, %139.sub_hi_dim_then_sub_dim_count
    PseudoJNZ %120, %bb.4
    PseudoJ_jump_imm %bb.5

  bb.3:
    successors: %bb.3(0x7c000000), %bb.2(0x04000000)

    %145.sub_hi_dim_then_sub_dim_count:eds = COPY %145.sub_dim_count
    %172:eds = COPY %145
    undef %171.sub_fifo:epsrfldf = COPY %53
    %171.sub_ptr:epsrfldf = COPY %52
    %171.sub_avail:epsrfldf = COPY %37
    dead %144:vec576, dead %171.sub_ptr:epsrfldf, dead %171.sub_fifo:epsrfldf, dead %171.sub_avail:epsrfldf, %172.sub_dim_count:eds, %172.sub_hi_dim_then_sub_dim_count:eds = VLD_POP_576_3D_pseudo_split %171.sub_ptr, %171.sub_fifo, %171.sub_avail, %172.sub_mod, %172.sub_dim_size, %172.sub_dim_stride, %172.sub_dim_count, undef %172.sub_hi_dim_then_sub_mod, %172.sub_hi_dim_then_sub_dim_size, %172.sub_hi_dim_then_sub_dim_stride, %172.sub_hi_dim_then_sub_dim_count, implicit-def $srfifo_uf :: (load unknown-size from `ptr addrspace(5) null`, align 1, addrspace 5)
    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.3, implicit $ls, implicit $le
    PseudoJ_jump_imm %bb.2

  bb.4:
    successors: %bb.5(0x80000000)

  bb.5:
    successors: %bb.6(0x04000000), %bb.1(0x7c000000)

    %81:ep = MOV_PD_imm11_pseudo 0
    %118:er = XOR %15, %124
    %134.sub_dim_stride:eds = COPY %134.sub_mod
    %134.sub_dim_size:eds = COPY %134.sub_mod
    %134.sub_hi_dim_then_sub_dim_size:eds = COPY %134.sub_mod
    %134.sub_hi_dim_then_sub_dim_count:eds = COPY %134.sub_mod
    %115:er = AND %118, %124
    dead %81:ep, %134.sub_dim_count:eds, %134.sub_hi_dim_then_sub_dim_count:eds = PADD_3D_pseudo_split %81, %134.sub_mod, %134.sub_dim_size, %134.sub_dim_stride, %134.sub_dim_count, undef %134.sub_hi_dim_then_sub_mod, %134.sub_hi_dim_then_sub_dim_size, %134.sub_hi_dim_then_sub_dim_stride, %134.sub_hi_dim_then_sub_dim_count
    %139.sub_hi_dim_then_sub_dim_count:eds = COPY %134.sub_mod
    PseudoJNZ %115, %bb.1
    PseudoJ_jump_imm %bb.6

  bb.6:
    PseudoRET implicit $lr

...
