# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2p -verify-machineinstrs --run-pass=aie-subregs %s -o - | FileCheck %s

---
name:            test_vld_2d
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r0, $r1, $r2, $r3, $p0, $m0, $s0, $s1, $s2, $s3
    ; CHECK-LABEL: name: test_vld_2d
    ; CHECK: liveins: $r0, $r1, $r2, $r3, $p0, $m0, $s0, $s1, $s2, $s3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:em = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edn = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:edj = COPY $r2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:edc = COPY $r3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[COPY]], %subreg.sub_mod, [[COPY1]], %subreg.sub_dim_size, [[COPY2]], %subreg.sub_dim_stride, [[COPY3]], %subreg.sub_dim_count
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $bmhh0, %6:ep, [[COPY5]].sub_dim_count:ed = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s0, [[COPY4]], [[COPY5]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $bmll2, %8:ep, [[COPY6]].sub_dim_count:ed = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign1 $s1, [[COPY4]], [[COPY6]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $cmh4, %10:ep, [[COPY7]].sub_dim_count:ed = VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign0 $s2, [[COPY4]], [[COPY7]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $cml2, %12:ep, [[COPY8]].sub_dim_count:ed = VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign1 $s3, [[COPY4]], [[COPY8]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $cml0, %14:ep, [[COPY9]].sub_dim_count:ed = VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign0 $s0, [[COPY4]], [[COPY9]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $cml2, %16:ep, [[COPY10]].sub_dim_count:ed = VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign1 $s1, [[COPY4]], [[COPY10]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $dm4, %18:ep, [[COPY11]].sub_dim_count:ed = VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign0 $s2, [[COPY4]], [[COPY11]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $dm2, %20:ep, [[COPY12]].sub_dim_count:ed = VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign1 $s3, [[COPY4]], [[COPY12]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    %0:em =  COPY $r0
    %1:edn = COPY $r1
    %2:edj = COPY $r2
    %3:edc = COPY $r3
    %4:ep = COPY $p0
    %10:ed = REG_SEQUENCE %0, %subreg.sub_mod, %1, %subreg.sub_dim_size, %2, %subreg.sub_dim_stride, %3, %subreg.sub_dim_count
    $bmhh0, %40:ep, %41:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s0, %4, %10, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $bmll2, %50:ep, %51:edc = VLDA_2D_UPS_2x_dmw_lda_ups_w2b_upsSign1 $s1, %4, %10, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    $cmh4, %60:ep, %61:edc = VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign0 $s2, %4, %10, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $cml2, %70:ep, %71:edc = VLDA_2D_UPS_2x_dmx_lda_ups_x2c_upsSign1 $s3, %4, %10, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    $cml0, %80:ep, %81:edc = VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign0  $s0, %4, %10, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $cml2, %90:ep, %91:edc = VLDA_2D_UPS_4x_dmw_lda_ups_w2c_upsSign1  $s1, %4, %10, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    $dm4, %100:ep, %101:edc = VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign0 $s2, %4, %10, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $dm2, %110:ep, %111:edc = VLDA_2D_UPS_4x_dmx_lda_ups_x2d_upsSign1 $s3, %4, %10, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
...

---
name:            test_vld_3d
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $d0_3d, $p0, $s0, $s1, $s2, $s3
    ; CHECK-LABEL: name: test_vld_3d
    ; CHECK: liveins: $d0_3d, $p0, $s0, $s1, $s2, $s3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eds = COPY $d0_3d
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $bmhh0, %2:ep, [[COPY2]].sub_dim_count:eds, [[COPY2]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s0, [[COPY]], [[COPY2]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $bmll2, %5:ep, [[COPY3]].sub_dim_count:eds, [[COPY3]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_UPS_2x_dmw_lda_ups_w2b_upsSign1 $s1, [[COPY]], [[COPY3]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $cml4, %8:ep, [[COPY4]].sub_dim_count:eds, [[COPY4]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_UPS_2x_dmx_lda_ups_x2c_upsSign0 $s2, [[COPY]], [[COPY4]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $cmh3, %11:ep, [[COPY5]].sub_dim_count:eds, [[COPY5]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_UPS_2x_dmx_lda_ups_x2c_upsSign1 $s3, [[COPY]], [[COPY5]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $cml0, %14:ep, [[COPY6]].sub_dim_count:eds, [[COPY6]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_UPS_4x_dmw_lda_ups_w2c_upsSign0 $s0, [[COPY]], [[COPY6]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $cml2, %17:ep, [[COPY7]].sub_dim_count:eds, [[COPY7]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_UPS_4x_dmw_lda_ups_w2c_upsSign1 $s1, [[COPY]], [[COPY7]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $dm1, %20:ep, [[COPY8]].sub_dim_count:eds, [[COPY8]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_UPS_4x_dmx_lda_ups_x2d_upsSign0 $s2, [[COPY]], [[COPY8]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $dm3, %23:ep, [[COPY9]].sub_dim_count:eds, [[COPY9]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_UPS_4x_dmx_lda_ups_x2d_upsSign1 $s3, [[COPY]], [[COPY9]], implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    %0:ep = COPY $p0
    %10:eds = COPY $d0_3d
    $bmhh0, %40:ep, %41:edcl, %42:edch = VLDA_3D_UPS_2x_dmw_lda_ups_w2b_upsSign0 $s0, %0, %10, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $bmll2, %50:ep, %51:edcl, %52:edch = VLDA_3D_UPS_2x_dmw_lda_ups_w2b_upsSign1 $s1, %0, %10, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    $cml4, %60:ep, %61:edcl, %62:edch = VLDA_3D_UPS_2x_dmx_lda_ups_x2c_upsSign0 $s2, %0, %10, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $cmh3, %70:ep, %71:edcl, %72:edch = VLDA_3D_UPS_2x_dmx_lda_ups_x2c_upsSign1 $s3, %0, %10, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    $cml0, %80:ep, %81:edcl, %82:edch = VLDA_3D_UPS_4x_dmw_lda_ups_w2c_upsSign0  $s0, %0, %10, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $cml2, %90:ep, %91:edcl, %92:edch = VLDA_3D_UPS_4x_dmw_lda_ups_w2c_upsSign1  $s1, %0, %10, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
    $dm1, %100:ep, %101:edcl, %102:edch = VLDA_3D_UPS_4x_dmx_lda_ups_x2d_upsSign0 $s2, %0, %10, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    $dm3, %110:ep, %111:edcl, %112:edch = VLDA_3D_UPS_4x_dmx_lda_ups_x2d_upsSign1 $s3, %0, %10, implicit-def $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign1
...
