# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2p -verify-machineinstrs --run-pass=aie-subregs %s -o - | FileCheck %s


---
name:            test_composed_subreg
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $dj0, $p1, $p0, $lf0, $r24
    ; CHECK-LABEL: name: test_composed_subreg
    ; CHECK: liveins: $dj0, $p1, $p0, $lf0, $r24
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eps = COPY killed $p0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:eldfiforeg = COPY killed $lf0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:erf2 = COPY $r24
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY1]], %subreg.sub_ptr, [[COPY2]], %subreg.sub_fifo, [[COPY3]], %subreg.sub_avail
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_avail:epsrfldf = VLDB_FILL_512 [[REG_SEQUENCE]].sub_ptr, [[REG_SEQUENCE]].sub_fifo, [[REG_SEQUENCE]].sub_avail
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:eldfifolreg = COPY [[REG_SEQUENCE]].sub_lo_fifo
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:eldfifohreg = COPY [[REG_SEQUENCE]].sub_hi_fifo
    ; CHECK-NEXT: VST_dmx_sts_fifohl_idx_imm killed [[COPY5]], [[COPY]], 64 :: (store (<16 x s32>))
    ; CHECK-NEXT: VST_dmx_sts_fifohl_idx_imm killed [[COPY4]], [[COPY]], 0 :: (store (<16 x s32>))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %1:ep = COPY $p0
    %100:eps = COPY killed $p0
    %101:eldfiforeg = COPY killed $lf0
    %102:erf2 = COPY $r24
    %7:ep_as_32bit_and_eps, %8:eldfiforeg, %9:erf2 = VLDB_FILL_512 killed %100:eps, killed %101:eldfiforeg, killed %102:erf2
    %10:eldfifolreg = COPY %8.sub_lo_fifo:eldfiforeg
    %11:eldfifohreg = COPY killed %8.sub_hi_fifo:eldfiforeg
    VST_dmx_sts_fifohl_idx_imm killed %11:eldfifohreg, %1:ep, 64 :: (store (<16 x s32>) )
    VST_dmx_sts_fifohl_idx_imm killed %10:eldfifolreg, %1:ep, 0 :: (store (<16 x s32>) )
    PseudoRET implicit $lr
...
