# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2p -verify-machineinstrs --run-pass=aie-subregs %s -o - | FileCheck %s

---
name:            test_vld_2d
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r0, $r1, $r2, $r3, $p0, $m0, $s0, $s1, $s2, $s3
    ; CHECK-LABEL: name: test_vld_2d
    ; CHECK: liveins: $r0, $r1, $r2, $r3, $p0, $m0, $s0, $s1, $s2, $s3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:em = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edn = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:edj = COPY $r2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:edc = COPY $r3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[COPY]], %subreg.sub_mod, [[COPY1]], %subreg.sub_dim_size, [[COPY2]], %subreg.sub_dim_stride, [[COPY3]], %subreg.sub_dim_count
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $wl0, %6:ep, [[COPY5]].sub_dim_count:ed = VLDA_2D_dmw_lda_w [[COPY4]], [[COPY5]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $bmll0, %8:ep, [[COPY6]].sub_dim_count:ed = VLDA_2D_dmx_lda_bm [[COPY4]], [[COPY6]]
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $lfl0, %10:ep, [[COPY7]].sub_dim_count:ed = VLDA_2D_dmx_lda_fifohl [[COPY4]], [[COPY7]]
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $x0, %12:ep, [[COPY8]].sub_dim_count:ed = VLDA_2D_dmx_lda_x [[COPY4]], [[COPY8]]
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $wl0, %14:ep, [[COPY9]].sub_dim_count:ed = VLDA_2D_128 [[COPY4]], [[COPY9]]
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $wl0, %16:ep, [[COPY10]].sub_dim_count:ed = VLDB_2D_dmw_ldb [[COPY4]], [[COPY10]]
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $x0, %18:ep, [[COPY11]].sub_dim_count:ed = VLDB_2D_dmx_ldb_x [[COPY4]], [[COPY11]]
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $wl0, %20:ep, [[COPY12]].sub_dim_count:ed = VLDB_2D_128 [[COPY4]], [[COPY12]]
    %0:em =  COPY $r0
    %1:edn = COPY $r1
    %2:edj = COPY $r2
    %3:edc = COPY $r3
    %4:ep = COPY $p0
    %10:ed = REG_SEQUENCE %0, %subreg.sub_mod, %1, %subreg.sub_dim_size, %2, %subreg.sub_dim_stride, %3, %subreg.sub_dim_count
    $wl0, %20:ep, %21:edc = VLDA_2D_dmw_lda_w %4, %10
    $bmll0, %120:ep, %121:edc = VLDA_2D_dmx_lda_bm %4, %10
    $lfl0, %130:ep, %131:edc = VLDA_2D_dmx_lda_fifohl %4, %10
    $x0, %140:ep, %141:edc = VLDA_2D_dmx_lda_x %4, %10
    $wl0, %150:ep, %151:edc = VLDA_2D_128 %4, %10
    $wl0, %160:ep, %161:edc = VLDB_2D_dmw_ldb %4, %10
    $x0, %170:ep, %171:edc = VLDB_2D_dmx_ldb_x %4, %10
    $wl0, %180:ep, %181:edc = VLDB_2D_128 %4, %10
...

---
name:            test_vld_3d
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $d0_3d, $p0, $s0, $s1, $s2, $s3
    ; CHECK-LABEL: name: test_vld_3d
    ; CHECK: liveins: $d0_3d, $p0, $s0, $s1, $s2, $s3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eds = COPY $d0_3d
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $wl0, %2:ep, [[COPY2]].sub_dim_count:eds, [[COPY2]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_dmw_lda_w [[COPY]], [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $bmll0, %5:ep, [[COPY3]].sub_dim_count:eds, [[COPY3]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_dmx_lda_bm [[COPY]], [[COPY3]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $lfl0, %8:ep, [[COPY4]].sub_dim_count:eds, [[COPY4]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_dmx_lda_fifohl [[COPY]], [[COPY4]]
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $x0, %11:ep, [[COPY5]].sub_dim_count:eds, [[COPY5]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_dmx_lda_x [[COPY]], [[COPY5]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $wl0, %14:ep, [[COPY6]].sub_dim_count:eds, [[COPY6]].sub_hi_dim_then_sub_dim_count:eds = VLDA_3D_128 [[COPY]], [[COPY6]]
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $wl0, %17:ep, [[COPY7]].sub_dim_count:eds, [[COPY7]].sub_hi_dim_then_sub_dim_count:eds = VLDB_3D_dmw_ldb [[COPY]], [[COPY7]]
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $x0, %20:ep, [[COPY8]].sub_dim_count:eds, [[COPY8]].sub_hi_dim_then_sub_dim_count:eds = VLDB_3D_dmx_ldb_x [[COPY]], [[COPY8]]
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $wl0, %23:ep, [[COPY9]].sub_dim_count:eds, [[COPY9]].sub_hi_dim_then_sub_dim_count:eds = VLDB_3D_128 [[COPY]], [[COPY9]]
    %0:ep = COPY $p0
    %10:eds = COPY $d0_3d
    $wl0, %20:ep, %21:edcl, %22:edch = VLDA_3D_dmw_lda_w %0, %10
    $bmll0, %120:ep, %121:edcl, %122:edch = VLDA_3D_dmx_lda_bm %0, %10
    $lfl0, %140:ep, %141:edcl, %142:edch = VLDA_3D_dmx_lda_fifohl %0, %10
    $x0, %150:ep, %151:edcl, %152:edch = VLDA_3D_dmx_lda_x %0, %10
    $wl0, %160:ep, %161:edcl, %162:edch = VLDA_3D_128 %0, %10
    $wl0, %170:ep, %171:edcl, %172:edch = VLDB_3D_dmw_ldb %0, %10
    $x0, %180:ep, %181:edcl, %182:edch = VLDB_3D_dmx_ldb_x %0, %10
    $wl0, %190:ep, %191:edcl, %192:edch = VLDB_3D_128 %0, %10
...
