# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2p -verify-machineinstrs --run-pass=aie-subregs %s -o - | FileCheck %s

---
name:            test_vld_2d
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r0, $r1, $r2, $r3, $p0, $m0, $s0, $s1, $s2, $s3
    ; CHECK-LABEL: name: test_vld_2d
    ; CHECK: liveins: $r0, $r1, $r2, $r3, $p0, $m0, $s0, $s1, $s2, $s3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:em = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edn = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:edj = COPY $r2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:edc = COPY $r3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[COPY]], %subreg.sub_mod, [[COPY1]], %subreg.sub_dim_size, [[COPY2]], %subreg.sub_dim_stride, [[COPY3]], %subreg.sub_dim_count
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $x0, %6:ep, [[COPY5]].sub_dim_count:ed = VLDB_2D_UNPACK_dmw_ldb_unpack_unpackSign0 [[COPY4]], [[COPY5]], implicit $crunpacksize, implicit $unpacksign0
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $x1, %8:ep, [[COPY6]].sub_dim_count:ed = VLDB_2D_UNPACK_dmw_ldb_unpack_unpackSign1 [[COPY4]], [[COPY6]], implicit $crunpacksize, implicit $unpacksign1
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $y3, %10:ep, [[COPY7]].sub_dim_count:ed = VLDB_2D_UNPACK_dmx_ldb_unpack_unpackSign0 [[COPY4]], [[COPY7]], implicit $crunpacksize, implicit $unpacksign0
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $y5, %12:ep, [[COPY8]].sub_dim_count:ed = VLDB_2D_UNPACK_dmx_ldb_unpack_unpackSign1 [[COPY4]], [[COPY8]], implicit $crunpacksize, implicit $unpacksign1
    %0:em =  COPY $r0
    %1:edn = COPY $r1
    %2:edj = COPY $r2
    %3:edc = COPY $r3
    %4:ep = COPY $p0
    %10:ed = REG_SEQUENCE %0, %subreg.sub_mod, %1, %subreg.sub_dim_size, %2, %subreg.sub_dim_stride, %3, %subreg.sub_dim_count
    $x0, %150:ep, %151:edc = VLDB_2D_UNPACK_dmw_ldb_unpack_unpackSign0 %4, %10, implicit $crunpacksize, implicit $unpacksign0
    $x1, %160:ep, %161:edc = VLDB_2D_UNPACK_dmw_ldb_unpack_unpackSign1 %4, %10, implicit $crunpacksize, implicit $unpacksign1
    $y3, %170:ep, %171:edc = VLDB_2D_UNPACK_dmx_ldb_unpack_unpackSign0 %4, %10, implicit $crunpacksize, implicit $unpacksign0
    $y5, %180:ep, %181:edc = VLDB_2D_UNPACK_dmx_ldb_unpack_unpackSign1 %4, %10, implicit $crunpacksize, implicit $unpacksign1
...

---
name:            test_vld_3d
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $d0_3d, $p0, $s0, $s1, $s2, $s3
    ; CHECK-LABEL: name: test_vld_3d
    ; CHECK: liveins: $d0_3d, $p0, $s0, $s1, $s2, $s3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eds = COPY $d0_3d
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $x0, %2:ep, [[COPY2]].sub_dim_count:eds, [[COPY2]].sub_hi_dim_then_sub_dim_count:eds = VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign0 [[COPY]], [[COPY2]], implicit $crunpacksize, implicit $unpacksign0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $x1, %5:ep, [[COPY3]].sub_dim_count:eds, [[COPY3]].sub_hi_dim_then_sub_dim_count:eds = VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign1 [[COPY]], [[COPY3]], implicit $crunpacksize, implicit $unpacksign1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $y3, %8:ep, [[COPY4]].sub_dim_count:eds, [[COPY4]].sub_hi_dim_then_sub_dim_count:eds = VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign0 [[COPY]], [[COPY4]], implicit $crunpacksize, implicit $unpacksign0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $y4, %11:ep, [[COPY5]].sub_dim_count:eds, [[COPY5]].sub_hi_dim_then_sub_dim_count:eds = VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign1 [[COPY]], [[COPY5]], implicit $crunpacksize, implicit $unpacksign1
    %0:ep = COPY $p0
    %10:eds = COPY $d0_3d
    $x0, %150:ep, %151:edcl, %152:edch = VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign0 %0, %10, implicit $crunpacksize, implicit $unpacksign0
    $x1, %160:ep, %161:edcl, %162:edch = VLDB_3D_UNPACK_dmw_ldb_unpack_unpackSign1 %0, %10, implicit $crunpacksize, implicit $unpacksign1
    $y3, %170:ep, %171:edcl, %172:edch = VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign0 %0, %10, implicit $crunpacksize, implicit $unpacksign0
    $y4, %180:ep, %181:edcl, %182:edch = VLDB_3D_UNPACK_dmx_ldb_unpack_unpackSign1 %0, %10, implicit $crunpacksize, implicit $unpacksign1
...
