# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2p -verify-machineinstrs --run-pass=aie-subregs %s -o - | FileCheck %s

---
name:            test_vst_flush_2d
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r0, $r1, $r2, $r3, $p0, $m0, $s0, $s1, $s2, $s3, $wl3, $bmll0, $cml0, $cmh3, $x0, $y0, $sf, $r26

    ; CHECK-LABEL: name: test_vst_flush_2d
    ; CHECK: liveins: $r0, $r1, $r2, $r3, $p0, $m0, $s0, $s1, $s2, $s3, $wl3, $bmll0, $cml0, $cmh3, $x0, $y0, $sf, $r26
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:em = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edn = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:edj = COPY $r2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:edc = COPY $r3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:mpfs = COPY $p0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[COPY]], %subreg.sub_mod, [[COPY1]], %subreg.sub_dim_size, [[COPY2]], %subreg.sub_dim_stride, [[COPY3]], %subreg.sub_dim_count
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $sf, %6:mpfs, $r26, [[COPY5]].sub_dim_count:ed = VST_FLUSH_512_2D $sf, [[COPY4]], $r26, [[COPY5]], implicit-def $srfifo_of
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $sf, %8:mpfs, $r26, [[COPY6]].sub_dim_count:ed = VST_FLUSH_512_CONV_2D $sf, [[COPY4]], $r26, [[COPY6]], implicit-def $srfifo_of
    %0:em =  COPY $r0
    %1:edn = COPY $r1
    %2:edj = COPY $r2
    %3:edc = COPY $r3
    %4:mpfs = COPY $p0

    %10:ed = REG_SEQUENCE %0, %subreg.sub_mod, %1, %subreg.sub_dim_size, %2, %subreg.sub_dim_stride, %3, %subreg.sub_dim_count
    $sf, %30:mpfs, $r26, %31:edc = VST_FLUSH_512_2D $sf, %4, $r26, %10, implicit-def $srfifo_of
    $sf, %180:mpfs, $r26, %181:edc = VST_FLUSH_512_CONV_2D $sf, %4, $r26, %10, implicit-def $srfifo_of
...

---
name:            test_vst_flush_3d
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r0, $r1, $r2, $r3, $p0, $m0, $s0, $s1, $s2, $s3, $wl3, $bmll0, $cml0, $cmh2, $x0, $y0, $sf, $r26

    ; CHECK-LABEL: name: test_vst_flush_3d
    ; CHECK: liveins: $r0, $r1, $r2, $r3, $p0, $m0, $s0, $s1, $s2, $s3, $wl3, $bmll0, $cml0, $cmh2, $x0, $y0, $sf, $r26
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:mpfs = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eds = COPY $d0_3d
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $sf, %2:mpfs, $r26, [[COPY2]].sub_dim_count:eds, [[COPY2]].sub_hi_dim_then_sub_dim_count:eds = VST_FLUSH_512_3D $sf, [[COPY]], $r26, [[COPY2]], implicit-def $srfifo_of
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: $sf, %5:mpfs, $r26, [[COPY3]].sub_dim_count:eds, [[COPY3]].sub_hi_dim_then_sub_dim_count:eds = VST_FLUSH_512_CONV_3D $sf, [[COPY]], $r26, [[COPY3]], implicit-def $srfifo_of
    %0:mpfs = COPY $p0
    %10:eds = COPY $d0_3d
    $sf, %30:mpfs, $r26, %31:edcl, %32:edch = VST_FLUSH_512_3D $sf, %0, $r26, %10, implicit-def $srfifo_of
    $sf, %340:mpfs, $r26, %341:edcl, %342:edch = VST_FLUSH_512_CONV_3D $sf, %0, $r26, %10, implicit-def $srfifo_of
...

