# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2p -verify-machineinstrs --run-pass=aie-subregs %s -o - | FileCheck %s

---
name:            test_vst_2d
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r0, $r1, $r2, $r3, $p0, $m0, $s0, $s1, $s2, $s3, $wl3, $bmll0, $cml0, $cmh3, $x0, $y0

    ; CHECK-LABEL: name: test_vst_2d
    ; CHECK: liveins: $r0, $r1, $r2, $r3, $p0, $m0, $s0, $s1, $s2, $s3, $wl3, $bmll0, $cml0, $cmh3, $x0, $y0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:em = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edn = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:edj = COPY $r2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:edc = COPY $r3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[COPY]], %subreg.sub_mod, [[COPY1]], %subreg.sub_dim_size, [[COPY2]], %subreg.sub_dim_stride, [[COPY3]], %subreg.sub_dim_count
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VST_2D_CONV_bf16_fp32_dmw_sts_srs_bf:%[0-9]+]]:ep, [[COPY5:%[0-9]+]].sub_dim_count:ed = VST_2D_CONV_bf16_fp32_dmw_sts_srs_bf $bmll0, [[COPY4]], [[COPY5]], implicit-def $srf2fflags, implicit $crf2fmask, implicit $crrnd
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VST_2D_CONV_bf16_fp32_dmx_sts_srs_bf:%[0-9]+]]:ep, [[COPY6:%[0-9]+]].sub_dim_count:ed = VST_2D_CONV_bf16_fp32_dmx_sts_srs_bf $cmh3, [[COPY4]], [[COPY6]], implicit-def $srf2fflags, implicit $crf2fmask, implicit $crrnd
    %0:em =  COPY $r0
    %1:edn = COPY $r1
    %2:edj = COPY $r2
    %3:edc = COPY $r3
    %4:ep = COPY $p0

    %10:ed = REG_SEQUENCE %0, %subreg.sub_mod, %1, %subreg.sub_dim_size, %2, %subreg.sub_dim_stride, %3, %subreg.sub_dim_count
    %130:ep, %131:edc = VST_2D_CONV_bf16_fp32_dmw_sts_srs_bf $bmll0, %4, %10, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crrnd
    %140:ep, %141:edc = VST_2D_CONV_bf16_fp32_dmx_sts_srs_bf $cmh3, %4, %10, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crrnd
...

---
name:            test_vst_3d
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r0, $r1, $r2, $r3, $p0, $m0, $s0, $s1, $s2, $s3, $wl3, $bmll0, $cml0, $cmh2, $x0, $y0

    ; CHECK-LABEL: name: test_vst_3d
    ; CHECK: liveins: $r0, $r1, $r2, $r3, $p0, $m0, $s0, $s1, $s2, $s3, $wl3, $bmll0, $cml0, $cmh2, $x0, $y0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eds = COPY $d0_3d
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_3D_CONV_bf16_fp32_dmw_sts_srs_bf:%[0-9]+]]:ep, [[COPY2:%[0-9]+]].sub_dim_count:eds, [[COPY2:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_CONV_bf16_fp32_dmw_sts_srs_bf $bmll0, [[COPY]], [[COPY2]], implicit-def $srf2fflags, implicit $crf2fmask, implicit $crrnd
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_3D_CONV_bf16_fp32_dmx_sts_srs_bf:%[0-9]+]]:ep, [[COPY3:%[0-9]+]].sub_dim_count:eds, [[COPY3:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_CONV_bf16_fp32_dmx_sts_srs_bf $cmh2, [[COPY]], [[COPY3]], implicit-def $srf2fflags, implicit $crf2fmask, implicit $crrnd
    %0:ep = COPY $p0
    %10:eds = COPY $d0_3d
    %290:ep, %291:edcl, %292:edch = VST_3D_CONV_bf16_fp32_dmw_sts_srs_bf $bmll0, %0, %10, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crrnd
    %300:ep, %301:edcl, %302:edch = VST_3D_CONV_bf16_fp32_dmx_sts_srs_bf $cmh2, %0, %10, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crrnd
...

