# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2p -verify-machineinstrs --run-pass=aie-subregs %s -o - | FileCheck %s

# The goal of this test is to verify that we are keeping the `undef` flag after aie-subregs pass.

---
name:            test_vlda_fillx_512_undef_erf
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $lf0, $r24, $r30, $lfe
    ; CHECK-LABEL: name: test_vlda_fillx_512_undef_erf
    ; CHECK: liveins: $p0, $lf0, $r24, $r30, $lfe
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:eps = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eldfiforeg = COPY $lf0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:erf2 = IMPLICIT_DEF
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, undef [[DEF]], %subreg.sub_avail
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_avail:epsrfldf = VLDB_FILLX_512 $r30, $r30, [[REG_SEQUENCE]].sub_ptr, [[REG_SEQUENCE]].sub_fifo, undef [[REG_SEQUENCE]].sub_avail, implicit-def $lfe, implicit $lfe
    %100:eps = COPY $p0
    %101:eldfiforeg = COPY $lf0
    %102:erf2 = IMPLICIT_DEF
    %200:eps, %300:eldfiforeg, %400:erf2 = VLDB_FILLX_512 $r30, $r30, %100, %101, undef %102, implicit-def $lfe, implicit $lfe
...


---
name:            test_vlda_fillx_512_undef_eldfiforeg
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_vlda_fillx_512_undef_eldfiforeg
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:eps = COPY killed $p0
    ; CHECK-NEXT: [[MOV_RLC_imm11_pseudo:%[0-9]+]]:erf2 = MOV_RLC_imm11_pseudo 0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, undef %5:eldfiforeg, %subreg.sub_fifo, [[MOV_RLC_imm11_pseudo]], %subreg.sub_avail
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_avail:epsrfldf = VLDA_FILL_512 [[REG_SEQUENCE]].sub_ptr, undef [[REG_SEQUENCE]].sub_fifo, [[REG_SEQUENCE]].sub_avail
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:eps = COPY killed $p0
    %7:erf2 = MOV_RLC_imm11_pseudo 0
    dead %3:eps, dead %4:eldfiforeg, dead %5:erf2 = VLDA_FILL_512 killed %0, undef %8:eldfiforeg, killed %7
    PseudoRET implicit $lr

...
