# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2p -verify-machineinstrs --run-pass=aie-subregs %s -o - | FileCheck %s

---
name:            test_vst_2d
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r0, $r1, $r2, $r3, $p0, $m0, $s0, $s1, $s2, $s3, $wl3, $bmll0, $cml0, $cmh3, $x0, $y0

    ; CHECK-LABEL: name: test_vst_2d
    ; CHECK: liveins: $r0, $r1, $r2, $r3, $p0, $m0, $s0, $s1, $s2, $s3, $wl3, $bmll0, $cml0, $cmh3, $x0, $y0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:em = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edn = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:edj = COPY $r2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:edc = COPY $r3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[COPY]], %subreg.sub_mod, [[COPY1]], %subreg.sub_dim_size, [[COPY2]], %subreg.sub_dim_stride, [[COPY3]], %subreg.sub_dim_count
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VST_2D_SRS_2x_dmw_sts_srs_bm_srsSign0_:%[0-9]+]]:ep, [[COPY5:%[0-9]+]].sub_dim_count:ed = VST_2D_SRS_2x_dmw_sts_srs_bm_srsSign0 $bmll0, $s0, [[COPY4]], [[COPY5]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VST_2D_SRS_2x_dmw_sts_srs_bm_srsSign1_:%[0-9]+]]:ep, [[COPY6:%[0-9]+]].sub_dim_count:ed = VST_2D_SRS_2x_dmw_sts_srs_bm_srsSign1 $bmll0, $s1, [[COPY4]], [[COPY6]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VST_2D_SRS_2x_dm_sts_srs_cm_srsSign0_:%[0-9]+]]:ep, [[COPY7:%[0-9]+]].sub_dim_count:ed = VST_2D_SRS_2x_dm_sts_srs_cm_srsSign0 $cml0, $s1, [[COPY4]], [[COPY7]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VST_2D_SRS_2x_dm_sts_srs_cm_srsSign1_:%[0-9]+]]:ep, [[COPY8:%[0-9]+]].sub_dim_count:ed = VST_2D_SRS_2x_dm_sts_srs_cm_srsSign1 $cml0, $s2, [[COPY4]], [[COPY8]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VST_2D_SRS_4x_dm_sts_srs_cm_srsSign0_:%[0-9]+]]:ep, [[COPY9:%[0-9]+]].sub_dim_count:ed = VST_2D_SRS_4x_dm_sts_srs_cm_srsSign0 $cml0, $s3, [[COPY4]], [[COPY9]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VST_2D_SRS_4x_dm_sts_srs_cm_srsSign1_:%[0-9]+]]:ep, [[COPY10:%[0-9]+]].sub_dim_count:ed = VST_2D_SRS_4x_dm_sts_srs_cm_srsSign1 $cml0, $s0, [[COPY4]], [[COPY10]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VST_2D_SRS_4x_dmx_sts_srs_dm_srsSign0_:%[0-9]+]]:ep, [[COPY11:%[0-9]+]].sub_dim_count:ed = VST_2D_SRS_4x_dmx_sts_srs_dm_srsSign0 $dm0, $s0, [[COPY4]], [[COPY11]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[VST_2D_SRS_4x_dmx_sts_srs_dm_srsSign1_:%[0-9]+]]:ep, [[COPY12:%[0-9]+]].sub_dim_count:ed = VST_2D_SRS_4x_dmx_sts_srs_dm_srsSign1 $dm0, $s0, [[COPY4]], [[COPY12]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    %0:em =  COPY $r0
    %1:edn = COPY $r1
    %2:edj = COPY $r2
    %3:edc = COPY $r3
    %4:ep = COPY $p0

    %10:ed = REG_SEQUENCE %0, %subreg.sub_mod, %1, %subreg.sub_dim_size, %2, %subreg.sub_dim_stride, %3, %subreg.sub_dim_count
    %50:ep, %51:edc = VST_2D_SRS_2x_dmw_sts_srs_bm_srsSign0 $bmll0, $s0, %4, %10, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    %60:ep, %61:edc = VST_2D_SRS_2x_dmw_sts_srs_bm_srsSign1 $bmll0, $s1, %4, %10, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    %90:ep, %91:edc = VST_2D_SRS_2x_dm_sts_srs_cm_srsSign0 $cml0, $s1, %4, %10, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    %100:ep, %101:edc = VST_2D_SRS_2x_dm_sts_srs_cm_srsSign1 $cml0, $s2, %4, %10, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    %110:ep, %111:edc = VST_2D_SRS_4x_dm_sts_srs_cm_srsSign0  $cml0, $s3, %4, %10, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    %120:ep, %121:edc = VST_2D_SRS_4x_dm_sts_srs_cm_srsSign1  $cml0, $s0, %4, %10, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    %130:ep, %131:edc = VST_2D_SRS_4x_dmx_sts_srs_dm_srsSign0  $dm0, $s0, %4, %10, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    %140:ep, %141:edc = VST_2D_SRS_4x_dmx_sts_srs_dm_srsSign1  $dm0, $s0, %4, %10, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
...

---
name:            test_vst_3d
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r0, $r1, $r2, $r3, $p0, $m0, $s0, $s1, $s2, $s3, $wl3, $bmll0, $cml0, $cmh2, $x0, $y0

    ; CHECK-LABEL: name: test_vst_3d
    ; CHECK: liveins: $r0, $r1, $r2, $r3, $p0, $m0, $s0, $s1, $s2, $s3, $wl3, $bmll0, $cml0, $cmh2, $x0, $y0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eds = COPY $d0_3d
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_3D_SRS_2x_dmw_sts_srs_bm_srsSign0_:%[0-9]+]]:ep, [[COPY2:%[0-9]+]].sub_dim_count:eds, [[COPY2:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_SRS_2x_dmw_sts_srs_bm_srsSign0 $bmll0, $s0, [[COPY]], [[COPY2]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_3D_SRS_2x_dmw_sts_srs_bm_srsSign1_:%[0-9]+]]:ep, [[COPY3:%[0-9]+]].sub_dim_count:eds, [[COPY3:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_SRS_2x_dmw_sts_srs_bm_srsSign1 $bmll0, $s0, [[COPY]], [[COPY3]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_3D_SRS_2x_dm_sts_srs_cm_srsSign0_:%[0-9]+]]:ep, [[COPY4:%[0-9]+]].sub_dim_count:eds, [[COPY4:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_SRS_2x_dm_sts_srs_cm_srsSign0 $cml0, $s2, [[COPY]], [[COPY4]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_3D_SRS_2x_dm_sts_srs_cm_srsSign1_:%[0-9]+]]:ep, [[COPY5:%[0-9]+]].sub_dim_count:eds, [[COPY5:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_SRS_2x_dm_sts_srs_cm_srsSign1 $cml0, $s2, [[COPY]], [[COPY5]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_3D_SRS_4x_dm_sts_srs_cm_srsSign0_:%[0-9]+]]:ep, [[COPY6:%[0-9]+]].sub_dim_count:eds, [[COPY6:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_SRS_4x_dm_sts_srs_cm_srsSign0 $cml0, $s2, [[COPY]], [[COPY6]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_3D_SRS_4x_dm_sts_srs_cm_srsSign1_:%[0-9]+]]:ep, [[COPY7:%[0-9]+]].sub_dim_count:eds, [[COPY7:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_SRS_4x_dm_sts_srs_cm_srsSign1 $cml0, $s2, [[COPY]], [[COPY7]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_3D_SRS_4x_dmx_sts_srs_dm_srsSign0_:%[0-9]+]]:ep, [[COPY8:%[0-9]+]].sub_dim_count:eds, [[COPY8:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_SRS_4x_dmx_sts_srs_dm_srsSign0 $dm0, $s0, [[COPY]], [[COPY8]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[VST_3D_SRS_4x_dmx_sts_srs_dm_srsSign0_:%[0-9]+]]:ep, [[COPY9:%[0-9]+]].sub_dim_count:eds, [[COPY9:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = VST_3D_SRS_4x_dmx_sts_srs_dm_srsSign1 $dm0, $s0, [[COPY]], [[COPY9]], implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    %0:ep = COPY $p0
    %10:eds = COPY $d0_3d
    %210:ep, %211:edcl, %212:edch = VST_3D_SRS_2x_dmw_sts_srs_bm_srsSign0 $bmll0, $s0, %0, %10, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    %220:ep, %221:edcl, %222:edch = VST_3D_SRS_2x_dmw_sts_srs_bm_srsSign1 $bmll0, $s0, %0, %10, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    %250:ep, %251:edcl, %252:edch = VST_3D_SRS_2x_dm_sts_srs_cm_srsSign0 $cml0, $s2, %0, %10, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    %260:ep, %261:edcl, %262:edch = VST_3D_SRS_2x_dm_sts_srs_cm_srsSign1 $cml0, $s2, %0, %10, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    %270:ep, %271:edcl, %272:edch = VST_3D_SRS_4x_dm_sts_srs_cm_srsSign0  $cml0, $s2, %0, %10, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    %280:ep, %281:edcl, %282:edch = VST_3D_SRS_4x_dm_sts_srs_cm_srsSign1  $cml0, $s2, %0, %10, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
    %120:ep, %231:edcl, %232:edch = VST_3D_SRS_4x_dmx_sts_srs_dm_srsSign0  $dm0, $s0, %0, %10, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign0
    %120:ep, %241:edcl, %242:edch = VST_3D_SRS_4x_dmx_sts_srs_dm_srsSign1  $dm0, $s0, %0, %10, implicit-def $srsrs_of, implicit $crrnd, implicit $crsrsmode, implicit $crsat, implicit $srssign1
...
