# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2p -verify-machineinstrs --run-pass=aie-subregs %s -o - | FileCheck %s

---
name:            test_vlda_pop_fill_normal_1d
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $d0_3d, $p0, $s0, $r0, $r1, $r2, $r3, $x0, $m0, $r30, $lfe, $lf0, $r24
    ; CHECK-LABEL: name: test_vlda_pop_fill_normal_1d
    ; CHECK: liveins: $d0_3d, $p0, $s0, $r0, $r1, $r2, $r3, $x0, $m0, $r30, $lfe, $lf0, $r24
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:eps = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eldfiforeg = COPY $lf0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:erf2 = COPY $r24
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_avail:epsrfldf = VLDB_FILL_512 [[REG_SEQUENCE]].sub_ptr, [[REG_SEQUENCE]].sub_fifo, [[REG_SEQUENCE]].sub_avail
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: $x0, [[REG_SEQUENCE1]].sub_ptr:epsrfldf, [[REG_SEQUENCE1]].sub_fifo:epsrfldf, [[REG_SEQUENCE1]].sub_avail:epsrfldf = VLDA_POP_512_normal_pop [[REG_SEQUENCE1]].sub_ptr, [[REG_SEQUENCE1]].sub_fifo, [[REG_SEQUENCE1]].sub_avail, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE2:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: $x0, [[REG_SEQUENCE2]].sub_ptr:epsrfldf, [[REG_SEQUENCE2]].sub_fifo:epsrfldf, [[REG_SEQUENCE2]].sub_avail:epsrfldf = VLDB_POP_512_normal_pop [[REG_SEQUENCE2]].sub_ptr, [[REG_SEQUENCE2]].sub_fifo, [[REG_SEQUENCE2]].sub_avail, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE3:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: $x0, [[REG_SEQUENCE3]].sub_ptr:epsrfldf, [[REG_SEQUENCE3]].sub_fifo:epsrfldf, [[REG_SEQUENCE3]].sub_avail:epsrfldf = VLDA_POP_512_fifo_1d_pop [[REG_SEQUENCE3]].sub_ptr, [[REG_SEQUENCE3]].sub_fifo, [[REG_SEQUENCE3]].sub_avail, $m0, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE4:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: $x0, [[REG_SEQUENCE4]].sub_ptr:epsrfldf, [[REG_SEQUENCE4]].sub_fifo:epsrfldf, [[REG_SEQUENCE4]].sub_avail:epsrfldf = VLDB_POP_512_fifo_1d_pop [[REG_SEQUENCE4]].sub_ptr, [[REG_SEQUENCE4]].sub_fifo, [[REG_SEQUENCE4]].sub_avail, $m0, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE5:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: $ex3, [[REG_SEQUENCE5]].sub_ptr:epsrfldf, [[REG_SEQUENCE5]].sub_fifo:epsrfldf, [[REG_SEQUENCE5]].sub_avail:epsrfldf = VLDA_POP_544_fifo_1d_pop [[REG_SEQUENCE5]].sub_ptr, [[REG_SEQUENCE5]].sub_fifo, [[REG_SEQUENCE5]].sub_avail, $m0, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE6:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: $ex3, [[REG_SEQUENCE6]].sub_ptr:epsrfldf, [[REG_SEQUENCE6]].sub_fifo:epsrfldf, [[REG_SEQUENCE6]].sub_avail:epsrfldf = VLDA_POP_544_normal_pop [[REG_SEQUENCE6]].sub_ptr, [[REG_SEQUENCE6]].sub_fifo, [[REG_SEQUENCE6]].sub_avail, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE7:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: $ex9, [[REG_SEQUENCE7]].sub_ptr:epsrfldf, [[REG_SEQUENCE7]].sub_fifo:epsrfldf, [[REG_SEQUENCE7]].sub_avail:epsrfldf = VLDA_POP_576_fifo_1d_pop [[REG_SEQUENCE7]].sub_ptr, [[REG_SEQUENCE7]].sub_fifo, [[REG_SEQUENCE7]].sub_avail, $m4, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE8:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: $ex5, [[REG_SEQUENCE8]].sub_ptr:epsrfldf, [[REG_SEQUENCE8]].sub_fifo:epsrfldf, [[REG_SEQUENCE8]].sub_avail:epsrfldf = VLDA_POP_576_normal_pop [[REG_SEQUENCE8]].sub_ptr, [[REG_SEQUENCE8]].sub_fifo, [[REG_SEQUENCE8]].sub_avail, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE9:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: $qx0, [[REG_SEQUENCE9]].sub_ptr:epsrfldf, [[REG_SEQUENCE9]].sub_fifo:epsrfldf, [[REG_SEQUENCE9]].sub_avail:epsrfldf = VLDA_POP_640_fifo_1d_pop [[REG_SEQUENCE9]].sub_ptr, [[REG_SEQUENCE9]].sub_fifo, [[REG_SEQUENCE9]].sub_avail, $m0, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE10:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: $qx2, [[REG_SEQUENCE10]].sub_ptr:epsrfldf, [[REG_SEQUENCE10]].sub_fifo:epsrfldf, [[REG_SEQUENCE10]].sub_avail:epsrfldf = VLDA_POP_640_normal_pop [[REG_SEQUENCE10]].sub_ptr, [[REG_SEQUENCE10]].sub_fifo, [[REG_SEQUENCE10]].sub_avail, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE11:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: $qex0, [[REG_SEQUENCE11]].sub_ptr:epsrfldf, [[REG_SEQUENCE11]].sub_fifo:epsrfldf, [[REG_SEQUENCE11]].sub_avail:epsrfldf = VLDA_POP_704_fifo_1d_pop [[REG_SEQUENCE11]].sub_ptr, [[REG_SEQUENCE11]].sub_fifo, [[REG_SEQUENCE11]].sub_avail, $m0, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE12:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: $qex0, [[REG_SEQUENCE12]].sub_ptr:epsrfldf, [[REG_SEQUENCE12]].sub_fifo:epsrfldf, [[REG_SEQUENCE12]].sub_avail:epsrfldf = VLDA_POP_704_normal_pop [[REG_SEQUENCE12]].sub_ptr, [[REG_SEQUENCE12]].sub_fifo, [[REG_SEQUENCE12]].sub_avail, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE13:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: $ex3, [[REG_SEQUENCE13]].sub_ptr:epsrfldf, [[REG_SEQUENCE13]].sub_fifo:epsrfldf, [[REG_SEQUENCE13]].sub_avail:epsrfldf = VLDB_POP_544_fifo_1d_pop [[REG_SEQUENCE13]].sub_ptr, [[REG_SEQUENCE13]].sub_fifo, [[REG_SEQUENCE13]].sub_avail, $m0, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE14:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: $ex3, [[REG_SEQUENCE14]].sub_ptr:epsrfldf, [[REG_SEQUENCE14]].sub_fifo:epsrfldf, [[REG_SEQUENCE14]].sub_avail:epsrfldf = VLDA_POP_544_normal_pop [[REG_SEQUENCE14]].sub_ptr, [[REG_SEQUENCE14]].sub_fifo, [[REG_SEQUENCE14]].sub_avail, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE15:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: $ex9, [[REG_SEQUENCE15]].sub_ptr:epsrfldf, [[REG_SEQUENCE15]].sub_fifo:epsrfldf, [[REG_SEQUENCE15]].sub_avail:epsrfldf = VLDB_POP_576_fifo_1d_pop [[REG_SEQUENCE15]].sub_ptr, [[REG_SEQUENCE15]].sub_fifo, [[REG_SEQUENCE15]].sub_avail, $m4, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE16:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: $ex5, [[REG_SEQUENCE16]].sub_ptr:epsrfldf, [[REG_SEQUENCE16]].sub_fifo:epsrfldf, [[REG_SEQUENCE16]].sub_avail:epsrfldf = VLDB_POP_576_normal_pop [[REG_SEQUENCE16]].sub_ptr, [[REG_SEQUENCE16]].sub_fifo, [[REG_SEQUENCE16]].sub_avail, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE17:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: $qx0, [[REG_SEQUENCE17]].sub_ptr:epsrfldf, [[REG_SEQUENCE17]].sub_fifo:epsrfldf, [[REG_SEQUENCE17]].sub_avail:epsrfldf = VLDB_POP_640_fifo_1d_pop [[REG_SEQUENCE17]].sub_ptr, [[REG_SEQUENCE17]].sub_fifo, [[REG_SEQUENCE17]].sub_avail, $m0, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE18:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: $qx2, [[REG_SEQUENCE18]].sub_ptr:epsrfldf, [[REG_SEQUENCE18]].sub_fifo:epsrfldf, [[REG_SEQUENCE18]].sub_avail:epsrfldf = VLDB_POP_640_normal_pop [[REG_SEQUENCE18]].sub_ptr, [[REG_SEQUENCE18]].sub_fifo, [[REG_SEQUENCE18]].sub_avail, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE19:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: $qex0, [[REG_SEQUENCE19]].sub_ptr:epsrfldf, [[REG_SEQUENCE19]].sub_fifo:epsrfldf, [[REG_SEQUENCE19]].sub_avail:epsrfldf = VLDB_POP_704_fifo_1d_pop [[REG_SEQUENCE19]].sub_ptr, [[REG_SEQUENCE19]].sub_fifo, [[REG_SEQUENCE19]].sub_avail, $m0, implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE20:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: $qex0, [[REG_SEQUENCE20]].sub_ptr:epsrfldf, [[REG_SEQUENCE20]].sub_fifo:epsrfldf, [[REG_SEQUENCE20]].sub_avail:epsrfldf = VLDB_POP_704_normal_pop [[REG_SEQUENCE20]].sub_ptr, [[REG_SEQUENCE20]].sub_fifo, [[REG_SEQUENCE20]].sub_avail, implicit-def $srfifo_uf
    %100:eps = COPY $p0
    %101:eldfiforeg = COPY $lf0
    %102:erf2 = COPY $r24
    %30:eps, %31:eldfiforeg, %32:erf2 = VLDB_FILL_512 %100, %101, %102
    $x0, %60:eps, %61:eldfiforeg, %62:erf2 = VLDA_POP_512_normal_pop %100, %101, %102, implicit-def $srfifo_uf
    $x0, %70:eps, %71:eldfiforeg, %72:erf2 = VLDB_POP_512_normal_pop %100, %101, %102, implicit-def $srfifo_uf
    $x0, %80:eps, %81:eldfiforeg, %82:erf2 = VLDA_POP_512_fifo_1d_pop %100, %101, %102, $m0, implicit-def $srfifo_uf
    $x0, %90:eps, %91:eldfiforeg, %92:erf2 = VLDB_POP_512_fifo_1d_pop %100, %101, %102, $m0, implicit-def $srfifo_uf
    $ex3, %110:eps, %111:eldfiforeg, %112:erf2 = VLDA_POP_544_fifo_1d_pop %100, %101, %102, $m0, implicit-def $srfifo_uf
    $ex3, %120:eps, %121:eldfiforeg, %122:erf2 = VLDA_POP_544_normal_pop %100, %101, %102, implicit-def $srfifo_uf
    $ex9, %130:eps, %131:eldfiforeg, %132:erf2 = VLDA_POP_576_fifo_1d_pop %100, %101, %102, $m4, implicit-def $srfifo_uf
    $ex5, %140:eps, %141:eldfiforeg, %142:erf2 = VLDA_POP_576_normal_pop %100, %101, %102, implicit-def $srfifo_uf
    $qx0, %150:eps, %151:eldfiforeg, %152:erf2 = VLDA_POP_640_fifo_1d_pop %100, %101, %102, $m0, implicit-def $srfifo_uf
    $qx2, %160:eps, %161:eldfiforeg, %162:erf2 = VLDA_POP_640_normal_pop %100, %101, %102, implicit-def $srfifo_uf
    $qex0, %170:eps, %171:eldfiforeg, %172:erf2 = VLDA_POP_704_fifo_1d_pop %100, %101, %102, $m0, implicit-def $srfifo_uf
    $qex0, %180:eps, %181:eldfiforeg, %182:erf2 = VLDA_POP_704_normal_pop %100, %101, %102, implicit-def $srfifo_uf
    $ex3, %190:eps, %191:eldfiforeg, %192:erf2 = VLDB_POP_544_fifo_1d_pop %100, %101, %102, $m0, implicit-def $srfifo_uf
    $ex3, %194:eps, %195:eldfiforeg, %196:erf2 = VLDA_POP_544_normal_pop %100, %101, %102, implicit-def $srfifo_uf
    $ex9, %551:eps, %552:eldfiforeg, %553:erf2 = VLDB_POP_576_fifo_1d_pop %100, %101, %102, $m4, implicit-def $srfifo_uf
    $ex5, %661:eps, %662:eldfiforeg, %663:erf2 = VLDB_POP_576_normal_pop %100, %101, %102, implicit-def $srfifo_uf
    $qx0, %771:eps, %772:eldfiforeg, %773:erf2 = VLDB_POP_640_fifo_1d_pop %100, %101, %102, $m0, implicit-def $srfifo_uf
    $qx2, %881:eps, %882:eldfiforeg, %883:erf2 = VLDB_POP_640_normal_pop %100, %101, %102, implicit-def $srfifo_uf
    $qex0, %991:eps, %992:eldfiforeg, %993:erf2 = VLDB_POP_704_fifo_1d_pop %100, %101, %102, $m0, implicit-def $srfifo_uf
    $qex0, %331:eps, %332:eldfiforeg, %333:erf2 = VLDB_POP_704_normal_pop %100, %101, %102, implicit-def $srfifo_uf
...


---
name:            test_vlda_pop_fill_2d
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $d0_3d, $p0, $s0, $r0, $r1, $r2, $r3, $r30, $lf0, $r24
    ; CHECK-LABEL: name: test_vlda_pop_fill_2d
    ; CHECK: liveins: $d0_3d, $p0, $s0, $r0, $r1, $r2, $r3, $r30, $lf0, $r24
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:eps = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eldfiforeg = COPY $lf0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:erf2 = COPY $r24
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:em = COPY $r0
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:edn = COPY $r1
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:edj = COPY $r2
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:edc = COPY $r3
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[COPY7]], %subreg.sub_mod, [[COPY4]], %subreg.sub_dim_size, [[COPY5]], %subreg.sub_dim_stride, [[COPY6]], %subreg.sub_dim_count
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $x11, [[REG_SEQUENCE1]].sub_ptr:epsrfldf, [[REG_SEQUENCE1]].sub_fifo:epsrfldf, [[REG_SEQUENCE1]].sub_avail:epsrfldf, [[COPY8]].sub_dim_count:ed = VLDA_POP_512_2D [[REG_SEQUENCE1]].sub_ptr, [[REG_SEQUENCE1]].sub_fifo, [[REG_SEQUENCE1]].sub_avail, [[COPY8]], implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE2:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $ex8, [[REG_SEQUENCE2]].sub_ptr:epsrfldf, [[REG_SEQUENCE2]].sub_fifo:epsrfldf, [[REG_SEQUENCE2]].sub_avail:epsrfldf, [[COPY9]].sub_dim_count:ed = VLDA_POP_544_2D [[REG_SEQUENCE2]].sub_ptr, [[REG_SEQUENCE2]].sub_fifo, [[REG_SEQUENCE2]].sub_avail, [[COPY9]], implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE3:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $ex3, [[REG_SEQUENCE3]].sub_ptr:epsrfldf, [[REG_SEQUENCE3]].sub_fifo:epsrfldf, [[REG_SEQUENCE3]].sub_avail:epsrfldf, [[COPY10]].sub_dim_count:ed = VLDA_POP_576_2D [[REG_SEQUENCE3]].sub_ptr, [[REG_SEQUENCE3]].sub_fifo, [[REG_SEQUENCE3]].sub_avail, [[COPY10]], implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE4:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $qx2, [[REG_SEQUENCE4]].sub_ptr:epsrfldf, [[REG_SEQUENCE4]].sub_fifo:epsrfldf, [[REG_SEQUENCE4]].sub_avail:epsrfldf, [[COPY11]].sub_dim_count:ed = VLDA_POP_640_2D [[REG_SEQUENCE4]].sub_ptr, [[REG_SEQUENCE4]].sub_fifo, [[REG_SEQUENCE4]].sub_avail, [[COPY11]], implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE5:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $qex3, [[REG_SEQUENCE5]].sub_ptr:epsrfldf, [[REG_SEQUENCE5]].sub_fifo:epsrfldf, [[REG_SEQUENCE5]].sub_avail:epsrfldf, [[COPY12]].sub_dim_count:ed = VLDA_POP_704_2D [[REG_SEQUENCE5]].sub_ptr, [[REG_SEQUENCE5]].sub_fifo, [[REG_SEQUENCE5]].sub_avail, [[COPY12]], implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE6:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $x11, [[REG_SEQUENCE6]].sub_ptr:epsrfldf, [[REG_SEQUENCE6]].sub_fifo:epsrfldf, [[REG_SEQUENCE6]].sub_avail:epsrfldf, [[COPY13]].sub_dim_count:ed = VLDB_POP_512_2D [[REG_SEQUENCE6]].sub_ptr, [[REG_SEQUENCE6]].sub_fifo, [[REG_SEQUENCE6]].sub_avail, [[COPY13]], implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE7:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $ex8, [[REG_SEQUENCE7]].sub_ptr:epsrfldf, [[REG_SEQUENCE7]].sub_fifo:epsrfldf, [[REG_SEQUENCE7]].sub_avail:epsrfldf, [[COPY14]].sub_dim_count:ed = VLDB_POP_544_2D [[REG_SEQUENCE7]].sub_ptr, [[REG_SEQUENCE7]].sub_fifo, [[REG_SEQUENCE7]].sub_avail, [[COPY14]], implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE8:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $ex3, [[REG_SEQUENCE8]].sub_ptr:epsrfldf, [[REG_SEQUENCE8]].sub_fifo:epsrfldf, [[REG_SEQUENCE8]].sub_avail:epsrfldf, [[COPY15]].sub_dim_count:ed = VLDB_POP_576_2D [[REG_SEQUENCE8]].sub_ptr, [[REG_SEQUENCE8]].sub_fifo, [[REG_SEQUENCE8]].sub_avail, [[COPY15]], implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE9:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY16:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $qx2, [[REG_SEQUENCE9]].sub_ptr:epsrfldf, [[REG_SEQUENCE9]].sub_fifo:epsrfldf, [[REG_SEQUENCE9]].sub_avail:epsrfldf, [[COPY16]].sub_dim_count:ed = VLDB_POP_640_2D [[REG_SEQUENCE9]].sub_ptr, [[REG_SEQUENCE9]].sub_fifo, [[REG_SEQUENCE9]].sub_avail, [[COPY16]], implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE10:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY17:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: $qex3, [[REG_SEQUENCE10]].sub_ptr:epsrfldf, [[REG_SEQUENCE10]].sub_fifo:epsrfldf, [[REG_SEQUENCE10]].sub_avail:epsrfldf, [[COPY17]].sub_dim_count:ed = VLDB_POP_704_2D [[REG_SEQUENCE10]].sub_ptr, [[REG_SEQUENCE10]].sub_fifo, [[REG_SEQUENCE10]].sub_avail, [[COPY17]], implicit-def $srfifo_uf
    %100:eps = COPY $p0
    %101:eldfiforeg = COPY $lf0
    %102:erf2 = COPY $r24
    %0:em =  COPY $r0
    %1:edn = COPY $r1
    %2:edj = COPY $r2
    %3:edc = COPY $r3
    %4:ep = COPY $p0
    %10:ed = REG_SEQUENCE %4, %subreg.sub_mod, %1, %subreg.sub_dim_size, %2, %subreg.sub_dim_stride, %3, %subreg.sub_dim_count
    $x11, %471:eps, %21:eldfiforeg, %22:erf2, %474:edc = VLDA_POP_512_2D %100, %101, %102, %10, implicit-def $srfifo_uf
    $ex8, %511:eps, %23:eldfiforeg, %24:erf2, %514:edc = VLDA_POP_544_2D %100, %101, %102, %10, implicit-def $srfifo_uf
    $ex3, %551:eps, %25:eldfiforeg, %26:erf2, %554:edc = VLDA_POP_576_2D %100, %101, %102, %10, implicit-def $srfifo_uf
    $qx2, %591:eps, %27:eldfiforeg, %28:erf2, %594:edc = VLDA_POP_640_2D %100, %101, %102, %10, implicit-def $srfifo_uf
    $qex3, %631:eps, %29:eldfiforeg, %30:erf2, %634:edc = VLDA_POP_704_2D %100, %101, %102, %10, implicit-def $srfifo_uf
    $x11, %4710:eps, %31:eldfiforeg, %32:erf2, %4740:edc = VLDB_POP_512_2D %100, %101, %102, %10, implicit-def $srfifo_uf
    $ex8, %5110:eps, %33:eldfiforeg, %34:erf2, %5140:edc = VLDB_POP_544_2D %100, %101, %102, %10, implicit-def $srfifo_uf
    $ex3, %5510:eps, %35:eldfiforeg, %36:erf2, %5540:edc = VLDB_POP_576_2D %100, %101, %102, %10, implicit-def $srfifo_uf
    $qx2, %5910:eps, %37:eldfiforeg, %38:erf2, %5940:edc = VLDB_POP_640_2D %100, %101, %102, %10, implicit-def $srfifo_uf
    $qex3, %6310:eps, %39:eldfiforeg, %40:erf2, %6340:edc = VLDB_POP_704_2D %100, %101, %102, %10, implicit-def $srfifo_uf
...

---
name:            test_vlda_pop_fill_3d
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $d0_3d, $p0, $s0, $lf0, $r24
    ; CHECK-LABEL: name: test_vlda_pop_fill_3d
    ; CHECK: liveins: $d0_3d, $p0, $s0, $lf0, $r24
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:eps = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eldfiforeg = COPY $lf0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:erf2 = COPY $r24
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:eds = COPY $d0_3d
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:eds = COPY [[COPY3]]
    ; CHECK-NEXT: $x11, [[REG_SEQUENCE]].sub_ptr:epsrfldf, [[REG_SEQUENCE]].sub_fifo:epsrfldf, [[REG_SEQUENCE]].sub_avail:epsrfldf, [[COPY4]].sub_dim_count:eds, [[COPY4]].sub_hi_dim_then_sub_dim_count:eds = VLDA_POP_512_3D [[REG_SEQUENCE]].sub_ptr, [[REG_SEQUENCE]].sub_fifo, [[REG_SEQUENCE]].sub_avail, [[COPY4]], implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:eds = COPY [[COPY3]]
    ; CHECK-NEXT: $ex8, [[REG_SEQUENCE1]].sub_ptr:epsrfldf, [[REG_SEQUENCE1]].sub_fifo:epsrfldf, [[REG_SEQUENCE1]].sub_avail:epsrfldf, [[COPY5]].sub_dim_count:eds, [[COPY5]].sub_hi_dim_then_sub_dim_count:eds = VLDA_POP_544_3D [[REG_SEQUENCE1]].sub_ptr, [[REG_SEQUENCE1]].sub_fifo, [[REG_SEQUENCE1]].sub_avail, [[COPY5]], implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE2:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:eds = COPY [[COPY3]]
    ; CHECK-NEXT: $ex3, [[REG_SEQUENCE2]].sub_ptr:epsrfldf, [[REG_SEQUENCE2]].sub_fifo:epsrfldf, [[REG_SEQUENCE2]].sub_avail:epsrfldf, [[COPY6]].sub_dim_count:eds, [[COPY6]].sub_hi_dim_then_sub_dim_count:eds = VLDA_POP_576_3D [[REG_SEQUENCE2]].sub_ptr, [[REG_SEQUENCE2]].sub_fifo, [[REG_SEQUENCE2]].sub_avail, [[COPY6]], implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE3:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:eds = COPY [[COPY3]]
    ; CHECK-NEXT: $qx2, [[REG_SEQUENCE3]].sub_ptr:epsrfldf, [[REG_SEQUENCE3]].sub_fifo:epsrfldf, [[REG_SEQUENCE3]].sub_avail:epsrfldf, [[COPY7]].sub_dim_count:eds, [[COPY7]].sub_hi_dim_then_sub_dim_count:eds = VLDA_POP_640_3D [[REG_SEQUENCE3]].sub_ptr, [[REG_SEQUENCE3]].sub_fifo, [[REG_SEQUENCE3]].sub_avail, [[COPY7]], implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE4:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:eds = COPY [[COPY3]]
    ; CHECK-NEXT: $qex3, [[REG_SEQUENCE4]].sub_ptr:epsrfldf, [[REG_SEQUENCE4]].sub_fifo:epsrfldf, [[REG_SEQUENCE4]].sub_avail:epsrfldf, [[COPY8]].sub_dim_count:eds, [[COPY8]].sub_hi_dim_then_sub_dim_count:eds = VLDA_POP_704_3D [[REG_SEQUENCE4]].sub_ptr, [[REG_SEQUENCE4]].sub_fifo, [[REG_SEQUENCE4]].sub_avail, [[COPY8]], implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE5:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:eds = COPY [[COPY3]]
    ; CHECK-NEXT: $x11, [[REG_SEQUENCE5]].sub_ptr:epsrfldf, [[REG_SEQUENCE5]].sub_fifo:epsrfldf, [[REG_SEQUENCE5]].sub_avail:epsrfldf, [[COPY9]].sub_dim_count:eds, [[COPY9]].sub_hi_dim_then_sub_dim_count:eds = VLDA_POP_512_3D [[REG_SEQUENCE5]].sub_ptr, [[REG_SEQUENCE5]].sub_fifo, [[REG_SEQUENCE5]].sub_avail, [[COPY9]], implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE6:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:eds = COPY [[COPY3]]
    ; CHECK-NEXT: $ex8, [[REG_SEQUENCE6]].sub_ptr:epsrfldf, [[REG_SEQUENCE6]].sub_fifo:epsrfldf, [[REG_SEQUENCE6]].sub_avail:epsrfldf, [[COPY10]].sub_dim_count:eds, [[COPY10]].sub_hi_dim_then_sub_dim_count:eds = VLDA_POP_544_3D [[REG_SEQUENCE6]].sub_ptr, [[REG_SEQUENCE6]].sub_fifo, [[REG_SEQUENCE6]].sub_avail, [[COPY10]], implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE7:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:eds = COPY [[COPY3]]
    ; CHECK-NEXT: $ex3, [[REG_SEQUENCE7]].sub_ptr:epsrfldf, [[REG_SEQUENCE7]].sub_fifo:epsrfldf, [[REG_SEQUENCE7]].sub_avail:epsrfldf, [[COPY11]].sub_dim_count:eds, [[COPY11]].sub_hi_dim_then_sub_dim_count:eds = VLDB_POP_576_3D [[REG_SEQUENCE7]].sub_ptr, [[REG_SEQUENCE7]].sub_fifo, [[REG_SEQUENCE7]].sub_avail, [[COPY11]], implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE8:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:eds = COPY [[COPY3]]
    ; CHECK-NEXT: $qx2, [[REG_SEQUENCE8]].sub_ptr:epsrfldf, [[REG_SEQUENCE8]].sub_fifo:epsrfldf, [[REG_SEQUENCE8]].sub_avail:epsrfldf, [[COPY12]].sub_dim_count:eds, [[COPY12]].sub_hi_dim_then_sub_dim_count:eds = VLDB_POP_640_3D [[REG_SEQUENCE8]].sub_ptr, [[REG_SEQUENCE8]].sub_fifo, [[REG_SEQUENCE8]].sub_avail, [[COPY12]], implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE9:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:eds = COPY [[COPY3]]
    ; CHECK-NEXT: $qex3, [[REG_SEQUENCE9]].sub_ptr:epsrfldf, [[REG_SEQUENCE9]].sub_fifo:epsrfldf, [[REG_SEQUENCE9]].sub_avail:epsrfldf, [[COPY13]].sub_dim_count:eds, [[COPY13]].sub_hi_dim_then_sub_dim_count:eds = VLDB_POP_704_3D [[REG_SEQUENCE9]].sub_ptr, [[REG_SEQUENCE9]].sub_fifo, [[REG_SEQUENCE9]].sub_avail, [[COPY13]], implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE10:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:eds = COPY [[COPY3]]
    ; CHECK-NEXT: $x11, [[REG_SEQUENCE10]].sub_ptr:epsrfldf, [[REG_SEQUENCE10]].sub_fifo:epsrfldf, [[REG_SEQUENCE10]].sub_avail:epsrfldf, [[COPY14]].sub_dim_count:eds, [[COPY14]].sub_hi_dim_then_sub_dim_count:eds = VLDB_POP_512_3D [[REG_SEQUENCE10]].sub_ptr, [[REG_SEQUENCE10]].sub_fifo, [[REG_SEQUENCE10]].sub_avail, [[COPY14]], implicit-def $srfifo_uf
    ; CHECK-NEXT: [[REG_SEQUENCE11:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:eds = COPY [[COPY3]]
    ; CHECK-NEXT: $ex8, [[REG_SEQUENCE11]].sub_ptr:epsrfldf, [[REG_SEQUENCE11]].sub_fifo:epsrfldf, [[REG_SEQUENCE11]].sub_avail:epsrfldf, [[COPY15]].sub_dim_count:eds, [[COPY15]].sub_hi_dim_then_sub_dim_count:eds = VLDB_POP_544_3D [[REG_SEQUENCE11]].sub_ptr, [[REG_SEQUENCE11]].sub_fifo, [[REG_SEQUENCE11]].sub_avail, [[COPY15]], implicit-def $srfifo_uf
    %100:eps = COPY $p0
    %101:eldfiforeg = COPY $lf0
    %102:erf2 = COPY $r24
    %10:eds = COPY $d0_3d
    $x11, %471:eps, %21:eldfiforeg, %22:erf2, %474:edcl, %4790:edch = VLDA_POP_512_3D %100, %101, %102, %10, implicit-def $srfifo_uf
    $ex8, %511:eps, %23:eldfiforeg, %24:erf2, %514:edcl, %4741:edch = VLDA_POP_544_3D %100, %101, %102, %10, implicit-def $srfifo_uf
    $ex3, %551:eps, %25:eldfiforeg, %26:erf2, %554:edcl, %4742:edch = VLDA_POP_576_3D %100, %101, %102, %10, implicit-def $srfifo_uf
    $qx2, %591:eps, %27:eldfiforeg, %28:erf2, %594:edcl, %4743:edch = VLDA_POP_640_3D %100, %101, %102, %10, implicit-def $srfifo_uf
    $qex3, %631:eps, %29:eldfiforeg, %30:erf2, %634:edcl, %4744:edch = VLDA_POP_704_3D %100, %101, %102, %10, implicit-def $srfifo_uf
    $x11, %4710:eps, %31:eldfiforeg, %32:erf2, %4740:edcl, %4745:edch = VLDA_POP_512_3D %100, %101, %102, %10, implicit-def $srfifo_uf
    $ex8, %5110:eps, %33:eldfiforeg, %34:erf2, %5140:edcl, %4746:edch = VLDA_POP_544_3D %100, %101, %102, %10, implicit-def $srfifo_uf
    $ex3, %5510:eps, %35:eldfiforeg, %36:erf2, %5540:edcl, %4747:edch = VLDB_POP_576_3D %100, %101, %102, %10, implicit-def $srfifo_uf
    $qx2, %5910:eps, %37:eldfiforeg, %38:erf2, %5940:edcl, %4748:edch = VLDB_POP_640_3D %100, %101, %102, %10, implicit-def $srfifo_uf
    $qex3, %6310:eps, %39:eldfiforeg, %40:erf2, %6340:edcl, %4749:edch = VLDB_POP_704_3D %100, %101, %102, %10, implicit-def $srfifo_uf
    $x11, %4716:eps, %216:eldfiforeg, %226:erf2, %4246:edcl, %4190:edch = VLDB_POP_512_3D %100, %101, %102, %10, implicit-def $srfifo_uf
    $ex8, %5111:eps, %123:eldfiforeg, %124:erf2, %1514:edcl, %4341:edch = VLDB_POP_544_3D %100, %101, %102, %10, implicit-def $srfifo_uf
...



---
name:            test_vlda_popx_512
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $lf0, $r24, $r30, $lfe
    ; CHECK-LABEL: name: test_vlda_popx_512
    ; CHECK: liveins: $p0, $lf0, $r24, $r30, $lfe
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:eps = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eldfiforeg = COPY $lf0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:erf2 = COPY $r24
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: $x11, [[REG_SEQUENCE]].sub_ptr:epsrfldf, [[REG_SEQUENCE]].sub_fifo:epsrfldf, [[REG_SEQUENCE]].sub_avail:epsrfldf = VLDB_POPX_512 $r30, $r30, [[REG_SEQUENCE]].sub_ptr, [[REG_SEQUENCE]].sub_fifo, [[REG_SEQUENCE]].sub_avail, implicit-def $lfe, implicit-def $srfifo_uf, implicit $lfe
    %100:eps = COPY $p0
    %101:eldfiforeg = COPY $lf0
    %102:erf2 = COPY $r24
    $x11, %200:eps, %300:eldfiforeg, %400:erf2 = VLDB_POPX_512 $r30, $r30, %100, %101, %102, implicit-def $lfe, implicit-def $srfifo_uf, implicit $lfe
...

---
name:            test_vlda_fillx_512
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $lf0, $r24, $r30, $lfe
    ; CHECK-LABEL: name: test_vlda_fillx_512
    ; CHECK: liveins: $p0, $lf0, $r24, $r30, $lfe
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:eps = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eldfiforeg = COPY $lf0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:erf2 = COPY $r24
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:epsrfldf = REG_SEQUENCE [[COPY]], %subreg.sub_ptr, [[COPY1]], %subreg.sub_fifo, [[COPY2]], %subreg.sub_avail
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]].sub_ptr:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_fifo:epsrfldf, [[REG_SEQUENCE:%[0-9]+]].sub_avail:epsrfldf = VLDB_FILLX_512 $r30, $r30, [[REG_SEQUENCE]].sub_ptr, [[REG_SEQUENCE]].sub_fifo, [[REG_SEQUENCE]].sub_avail, implicit-def $lfe, implicit $lfe
    %100:eps = COPY $p0
    %101:eldfiforeg = COPY $lf0
    %102:erf2 = COPY $r24
    %200:eps, %300:eldfiforeg, %400:erf2 = VLDB_FILLX_512 $r30, $r30, %100, %101, %102, implicit-def $lfe, implicit $lfe
...
