# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2p -verify-machineinstrs --run-pass=aie-subregs %s -o - | FileCheck %s

---
name:            test_st_2d
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r0, $r1, $r2, $r3, $r4, $p0
    ; CHECK-LABEL: name: test_st_2d
    ; CHECK: liveins: $r0, $r1, $r2, $r3, $r4, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:em = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edn = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:edj = COPY $r2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:edc = COPY $r3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:ed = REG_SEQUENCE [[COPY]], %subreg.sub_mod, [[COPY1]], %subreg.sub_dim_size, [[COPY2]], %subreg.sub_dim_stride, [[COPY3]], %subreg.sub_dim_count
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[ST_2D_dms_sts:%[0-9]+]]:ep, [[COPY5:%[0-9]+]].sub_dim_count:ed = ST_2D_dms_sts $r4, [[COPY4]], [[COPY5]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[ST_2D_s8_:%[0-9]+]]:ep, [[COPY6:%[0-9]+]].sub_dim_count:ed = ST_2D_s8 $r4, [[COPY4]], [[COPY6]], implicit-def $pe2_ads, implicit $pe2_ads
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:ed = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: [[ST_2D_s16_:%[0-9]+]]:ep, [[COPY7:%[0-9]+]].sub_dim_count:ed = ST_2D_s16 $r4, [[COPY4]], [[COPY7]], implicit-def $pe2_ads, implicit $pe2_ads
    %0:em =  COPY $r0
    %1:edn = COPY $r1
    %2:edj = COPY $r2
    %3:edc = COPY $r3
    %4:ep = COPY $p0
    %10:ed = REG_SEQUENCE %0, %subreg.sub_mod, %1, %subreg.sub_dim_size, %2, %subreg.sub_dim_stride, %3, %subreg.sub_dim_count
    %140:ep, %141:edc = ST_2D_dms_sts $r4, %4, %10
    %142:ep, %143:edc = ST_2D_s8 $r4, %4, %10, implicit-def $pe2_ads, implicit $pe2_ads
    %144:ep, %145:edc = ST_2D_s16 $r4, %4, %10, implicit-def $pe2_ads, implicit $pe2_ads
...

---
name:            test_st_3d
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $r0, $p0, $d0_3d
    ; CHECK-LABEL: name: test_st_3d
    ; CHECK: liveins: $r0, $p0, $d0_3d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eds = COPY $d0_3d
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[ST_3D_dms_sts:%[0-9]+]]:ep, [[COPY2:%[0-9]+]].sub_dim_count:eds, [[COPY2:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = ST_3D_dms_sts $r0, [[COPY]], [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[ST_3D_s16_:%[0-9]+]]:ep, [[COPY3:%[0-9]+]].sub_dim_count:eds, [[COPY3:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = ST_3D_s16 $r0, [[COPY]], [[COPY3]], implicit-def $pe2_ads, implicit $pe2_ads
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:eds = COPY [[COPY1]]
    ; CHECK-NEXT: [[ST_3D_s8_:%[0-9]+]]:ep, [[COPY4:%[0-9]+]].sub_dim_count:eds, [[COPY4:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = ST_3D_s8 $r0, [[COPY]], [[COPY4]], implicit-def $pe2_ads, implicit $pe2_ads
    %0:ep = COPY $p0
    %10:eds = COPY $d0_3d
    %140:ep, %141:edcl, %142:edch = ST_3D_dms_sts $r0, %0, %10
    %143:ep, %144:edcl, %145:edch = ST_3D_s16 $r0, %0, %10, implicit-def $pe2_ads, implicit $pe2_ads
    %146:ep, %147:edcl, %148:edch = ST_3D_s8 $r0, %0, %10, implicit-def $pe2_ads, implicit $pe2_ads
...
