# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2p -verify-machineinstrs -start-before=greedy -stop-after=aie-unallocated-superreg-rewrite %s -o - | FileCheck %s

# This test verifies that aie-unallocated-superreg-rewrite can expand copy bundles related to registers
# that are not rewrite candidates, but may be affected by some other registers, creating bundle cycles later on.

---
name:            expand_bundles
alignment:       16
exposesReturnsTwice: false
legalized:       true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: expand_bundles
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:er = COPY $r0
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 1
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo:%[0-9]+]]:em_as_32bit = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:edjl = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:ednl = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:ednh = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[AND:%[0-9]+]]:er = AND [[COPY]], [[MOV_RLC_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:ednl = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:ednh = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   undef [[MOV_PD_imm11_pseudo1:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo1:%[0-9]+]].sub_dim_size:eds = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo1:%[0-9]+]].sub_hi_dim_then_sub_dim_size:eds = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:edc = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:edc = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:spill_edn_to_er = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:edcl = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:edcl = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo1:%[0-9]+]].sub_dim_count:eds = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:spill_edc_to_er = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:spill_edc_to_er = COPY [[COPY11]]
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:spill_edn_to_er = COPY [[COPY8]]
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]]:edcl = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]]:edch = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]]:spill_edc_to_er = COPY [[COPY14]]
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.4(0x04000000), %bb.1(0x7c000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo1:%[0-9]+]].sub_mod:eds = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo1:%[0-9]+]].sub_dim_stride:eds = COPY [[COPY1]]
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo1:%[0-9]+]].sub_hi_dim_then_sub_dim_stride:eds = COPY [[COPY1]]
  ; CHECK-NEXT:   [[COPY17:%[0-9]+]]:eds = COPY [[MOV_PD_imm11_pseudo1]]
  ; CHECK-NEXT:   [[COPY18:%[0-9]+]]:spill_edc_to_er = COPY [[COPY12]]
  ; CHECK-NEXT:   [[COPY19:%[0-9]+]]:spill_edn_to_er = COPY [[COPY13]]
  ; CHECK-NEXT:   [[COPY20:%[0-9]+]]:spill_edc_to_er = COPY [[COPY18]]
  ; CHECK-NEXT:   [[COPY21:%[0-9]+]]:spill_edn_to_er = COPY [[COPY19]]
  ; CHECK-NEXT:   [[COPY22:%[0-9]+]]:spill_edc_to_er = COPY [[COPY20]]
  ; CHECK-NEXT:   [[COPY23:%[0-9]+]]:spill_edn_to_er = COPY [[COPY21]]
  ; CHECK-NEXT:   [[COPY24:%[0-9]+]]:spill_edn_to_er = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY25:%[0-9]+]]:spill_edc_to_er = COPY [[COPY22]]
  ; CHECK-NEXT:   [[COPY26:%[0-9]+]]:spill_edn_to_er = COPY [[COPY23]]
  ; CHECK-NEXT:   [[COPY27:%[0-9]+]]:spill_edn_to_er = COPY [[COPY24]]
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo2:%[0-9]+]]:ep = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[COPY28:%[0-9]+]]:spill_edc_to_er = COPY [[COPY25]]
  ; CHECK-NEXT:   [[COPY29:%[0-9]+]]:spill_edn_to_er = COPY [[COPY26]]
  ; CHECK-NEXT:   [[COPY30:%[0-9]+]]:spill_edn_to_er = COPY [[COPY27]]
  ; CHECK-NEXT:   [[COPY31:%[0-9]+]]:spill_edc_to_er = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   undef [[COPY32:%[0-9]+]].sub_dim_count:eds = COPY [[COPY28]]
  ; CHECK-NEXT:   [[COPY32:%[0-9]+]].sub_dim_size:eds = COPY [[COPY29]]
  ; CHECK-NEXT:   [[COPY32:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = COPY [[COPY31]]
  ; CHECK-NEXT:   [[COPY32:%[0-9]+]].sub_hi_dim_then_sub_dim_size:eds = COPY [[COPY30]]
  ; CHECK-NEXT:   [[COPY32:%[0-9]+]].sub_mod:eds = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY32:%[0-9]+]].sub_dim_stride:eds = COPY [[COPY1]]
  ; CHECK-NEXT:   undef [[COPY33:%[0-9]+]].sub_lo_dim:eds = COPY [[COPY32]].sub_lo_dim
  ; CHECK-NEXT:   [[COPY33:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = COPY [[COPY32]].sub_hi_dim_then_sub_dim_count
  ; CHECK-NEXT:   [[COPY33:%[0-9]+]].sub_hi_dim_then_sub_dim_size:eds = COPY [[COPY32]].sub_hi_dim_then_sub_dim_size
  ; CHECK-NEXT:   [[COPY33:%[0-9]+]].sub_hi_dim_then_sub_dim_stride:eds = COPY [[COPY1]]
  ; CHECK-NEXT:   undef [[COPY34:%[0-9]+]].sub_lo_dim:eds = COPY [[COPY33]].sub_lo_dim
  ; CHECK-NEXT:   [[COPY34:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = COPY [[COPY33]].sub_hi_dim_then_sub_dim_count
  ; CHECK-NEXT:   [[COPY34:%[0-9]+]].sub_hi_dim_then_sub_dim_size:eds = COPY [[COPY33]].sub_hi_dim_then_sub_dim_size
  ; CHECK-NEXT:   [[COPY34:%[0-9]+]].sub_hi_dim_then_sub_dim_stride:eds = COPY [[COPY33]].sub_hi_dim_then_sub_dim_stride
  ; CHECK-NEXT:   undef [[COPY35:%[0-9]+]].sub_lo_dim:eds = COPY [[COPY34]].sub_lo_dim
  ; CHECK-NEXT:   [[COPY35:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = COPY [[COPY34]].sub_hi_dim_then_sub_dim_count
  ; CHECK-NEXT:   [[COPY35:%[0-9]+]].sub_hi_dim_then_sub_dim_size:eds = COPY [[COPY34]].sub_hi_dim_then_sub_dim_size
  ; CHECK-NEXT:   [[COPY35:%[0-9]+]].sub_hi_dim_then_sub_dim_stride:eds = COPY [[COPY34]].sub_hi_dim_then_sub_dim_stride
  ; CHECK-NEXT:   dead [[MOV_PD_imm11_pseudo2:%[0-9]+]]:ep, [[COPY35:%[0-9]+]].sub_dim_count:eds, [[COPY35:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = PADD_3D_pseudo_split [[MOV_PD_imm11_pseudo2]], [[COPY35]].sub_mod, [[COPY35]].sub_dim_size, [[COPY35]].sub_dim_stride, [[COPY35]].sub_dim_count, undef [[COPY35]].sub_hi_dim_then_sub_mod, [[COPY35]].sub_hi_dim_then_sub_dim_size, [[COPY35]].sub_hi_dim_then_sub_dim_stride, [[COPY35]].sub_hi_dim_then_sub_dim_count
  ; CHECK-NEXT:   [[COPY36:%[0-9]+]]:spill_edc_to_er = COPY [[COPY35]].sub_dim_count
  ; CHECK-NEXT:   [[COPY37:%[0-9]+]]:spill_edn_to_er = COPY [[COPY35]].sub_dim_size
  ; CHECK-NEXT:   [[COPY38:%[0-9]+]]:spill_edn_to_er = COPY [[COPY35]].sub_hi_dim_then_sub_dim_size
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo3:%[0-9]+]]:ep = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   undef [[COPY39:%[0-9]+]].sub_lo_dim:eds = COPY [[COPY17]].sub_lo_dim
  ; CHECK-NEXT:   [[COPY39:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = COPY [[COPY17]].sub_hi_dim_then_sub_dim_count
  ; CHECK-NEXT:   [[COPY39:%[0-9]+]].sub_hi_dim_then_sub_dim_size:eds = COPY [[COPY17]].sub_hi_dim_then_sub_dim_size
  ; CHECK-NEXT:   [[COPY39:%[0-9]+]].sub_hi_dim_then_sub_dim_stride:eds = COPY [[COPY17]].sub_hi_dim_then_sub_dim_stride
  ; CHECK-NEXT:   dead [[MOV_PD_imm11_pseudo3:%[0-9]+]]:ep, [[COPY39:%[0-9]+]].sub_dim_count:eds, [[COPY39:%[0-9]+]].sub_hi_dim_then_sub_dim_count:eds = PADD_3D_pseudo_split [[MOV_PD_imm11_pseudo3]], [[COPY39]].sub_mod, [[COPY39]].sub_dim_size, [[COPY39]].sub_dim_stride, [[COPY39]].sub_dim_count, undef [[COPY39]].sub_hi_dim_then_sub_mod, [[COPY39]].sub_hi_dim_then_sub_dim_size, [[COPY39]].sub_hi_dim_then_sub_dim_stride, [[COPY39]].sub_hi_dim_then_sub_dim_count
  ; CHECK-NEXT:   [[COPY40:%[0-9]+]]:spill_edc_to_er = COPY [[COPY39]].sub_dim_count
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]]:edcl = COPY [[COPY16]]
  ; CHECK-NEXT:   [[COPY41:%[0-9]+]]:em_as_32bit = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY42:%[0-9]+]]:ednl = COPY [[COPY38]]
  ; CHECK-NEXT:   [[COPY43:%[0-9]+]]:edjl = COPY [[COPY1]]
  ; CHECK-NEXT:   [[COPY44:%[0-9]+]]:ednh = COPY [[COPY38]]
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo4:%[0-9]+]]:ep = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[COPY45:%[0-9]+]]:edjh = COPY [[COPY1]]
  ; CHECK-NEXT:   [[COPY46:%[0-9]+]]:edch = COPY [[MOV_PD_imm11_pseudo1]].sub_hi_dim_then_sub_dim_count
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo1:%[0-9]+]].sub_dim_count:eds = COPY [[COPY40]]
  ; CHECK-NEXT:   dead [[MOV_PD_imm11_pseudo4:%[0-9]+]]:ep, [[COPY14:%[0-9]+]]:edcl, dead [[COPY46:%[0-9]+]]:edch = PADD_3D_pseudo_split [[MOV_PD_imm11_pseudo4]], [[COPY41]], [[COPY42]], [[COPY43]], [[COPY14]], undef %68:em_as_32bit, [[COPY44]], [[COPY45]], [[COPY46]]
  ; CHECK-NEXT:   [[COPY47:%[0-9]+]]:edcl = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo5:%[0-9]+]]:ep = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[COPY48:%[0-9]+]]:em_as_32bit = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY49:%[0-9]+]]:ednl = COPY [[COPY38]]
  ; CHECK-NEXT:   [[COPY50:%[0-9]+]]:edjl = COPY [[COPY1]]
  ; CHECK-NEXT:   [[COPY51:%[0-9]+]]:spill_edc_to_er = COPY [[COPY36]]
  ; CHECK-NEXT:   [[COPY52:%[0-9]+]]:spill_edn_to_er = COPY [[COPY37]]
  ; CHECK-NEXT:   dead [[COPY53:%[0-9]+]]:spill_edn_to_er = COPY [[COPY38]]
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:spill_edc_to_er = COPY [[COPY51]]
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:spill_edn_to_er = COPY [[COPY52]]
  ; CHECK-NEXT:   [[COPY54:%[0-9]+]]:ednh = COPY [[COPY38]]
  ; CHECK-NEXT:   [[COPY55:%[0-9]+]]:edjh = COPY [[COPY1]]
  ; CHECK-NEXT:   dead [[MOV_PD_imm11_pseudo5:%[0-9]+]]:ep, dead [[COPY47:%[0-9]+]]:edcl, [[COPY15:%[0-9]+]]:edch = PADD_3D_pseudo_split [[MOV_PD_imm11_pseudo5]], [[COPY48]], [[COPY49]], [[COPY50]], [[COPY47]], undef %60:em_as_32bit, [[COPY54]], [[COPY55]], [[COPY15]]
  ; CHECK-NEXT:   PseudoJNZ [[AND]], %bb.4
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.3(0x7c000000), %bb.2(0x04000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo6:%[0-9]+]]:ep = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[COPY56:%[0-9]+]]:edjh = COPY [[COPY1]]
  ; CHECK-NEXT:   [[COPY57:%[0-9]+]]:edch = COPY [[COPY6]]
  ; CHECK-NEXT:   dead [[MOV_PD_imm11_pseudo6:%[0-9]+]]:ep, [[COPY9:%[0-9]+]]:edcl, dead [[COPY57:%[0-9]+]]:edch = PADD_3D_pseudo_split [[MOV_PD_imm11_pseudo6]], [[MOV_PD_imm11_pseudo]], [[COPY2]], [[COPY1]], [[COPY9]], undef %44:em_as_32bit, [[COPY3]], [[COPY56]], [[COPY57]]
  ; CHECK-NEXT:   [[MOV_PD_imm11_pseudo7:%[0-9]+]]:ep = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   [[COPY58:%[0-9]+]]:em_as_32bit = COPY [[MOV_PD_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY59:%[0-9]+]]:edjl = COPY [[COPY1]]
  ; CHECK-NEXT:   [[COPY60:%[0-9]+]]:edjh = COPY [[COPY1]]
  ; CHECK-NEXT:   [[COPY61:%[0-9]+]]:edch = COPY [[COPY7]]
  ; CHECK-NEXT:   dead [[MOV_PD_imm11_pseudo7:%[0-9]+]]:ep, [[COPY10:%[0-9]+]]:edcl, dead [[COPY61:%[0-9]+]]:edch = PADD_3D_pseudo_split [[MOV_PD_imm11_pseudo7]], [[COPY58]], [[COPY4]], [[COPY59]], [[COPY10]], undef %52:em_as_32bit, [[COPY5]], [[COPY60]], [[COPY61]]
  ; CHECK-NEXT:   PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.3, implicit $ls, implicit $le
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $r0

    %1:er = COPY $r0
    %75:er = MOV_RLC_imm11_pseudo 1
    undef %105.sub_mod:eds = MOV_PD_imm11_pseudo 0
    %105.sub_dim_stride:eds = COPY %105.sub_mod
    %105.sub_dim_size:eds = COPY %105.sub_mod
    %105.sub_hi_dim_then_sub_dim_size:eds = COPY %105.sub_mod
    %71:er = AND %1, %75
    undef %99.sub_dim_size:eds = COPY %105.sub_mod
    %99.sub_hi_dim_then_sub_dim_size:eds = COPY %105.sub_mod
    undef %93.sub_hi_dim_then_sub_dim_count:eds = MOV_PD_imm11_pseudo 0
    %93.sub_dim_size:eds = COPY %105.sub_mod
    %93.sub_hi_dim_then_sub_dim_size:eds = COPY %105.sub_mod
    %110:edc = COPY %105.sub_mod
    %104:edc = COPY %105.sub_mod
    undef %87.sub_dim_size:eds = COPY %105.sub_mod
    %105.sub_dim_count:eds = COPY %105.sub_mod
    %99.sub_dim_count:eds = COPY %105.sub_mod
    %93.sub_dim_count:eds = COPY %105.sub_mod
    %87.sub_dim_count:eds = COPY %105.sub_mod
    undef %82.sub_dim_count:eds = COPY %105.sub_mod
    undef %76.sub_hi_dim_then_sub_dim_count:eds = COPY %105.sub_mod

  bb.1:
    successors: %bb.3(0x80000000)

    PseudoJ_jump_imm %bb.3

  bb.2:
    successors: %bb.4(0x04000000), %bb.1(0x7c000000)

    %93.sub_mod:eds = COPY %105.sub_mod
    %93.sub_dim_stride:eds = COPY %105.sub_dim_stride
    %93.sub_hi_dim_then_sub_dim_stride:eds = COPY %105.sub_dim_stride
    %119:eds = COPY %93
    %87.sub_hi_dim_then_sub_dim_size:eds = COPY %105.sub_mod
    %31:ep = MOV_PD_imm11_pseudo 0
    %87.sub_hi_dim_then_sub_dim_count:eds = COPY %105.sub_mod
    %87.sub_mod:eds = COPY %105.sub_mod
    %87.sub_dim_stride:eds = COPY %105.sub_dim_stride
    %87.sub_hi_dim_then_sub_dim_stride:eds = COPY %105.sub_dim_stride
    dead %31:ep, %87.sub_dim_count:eds, %87.sub_hi_dim_then_sub_dim_count:eds = PADD_3D_pseudo_split %31, %87.sub_mod, %87.sub_dim_size, %87.sub_dim_stride, %87.sub_dim_count, undef %87.sub_hi_dim_then_sub_mod, %87.sub_hi_dim_then_sub_dim_size, %87.sub_hi_dim_then_sub_dim_stride, %87.sub_hi_dim_then_sub_dim_count
    %26:ep = MOV_PD_imm11_pseudo 0
    dead %26:ep, %119.sub_dim_count:eds, %119.sub_hi_dim_then_sub_dim_count:eds = PADD_3D_pseudo_split %26, %119.sub_mod, %119.sub_dim_size, %119.sub_dim_stride, %119.sub_dim_count, undef %119.sub_hi_dim_then_sub_mod, %119.sub_hi_dim_then_sub_dim_size, %119.sub_hi_dim_then_sub_dim_stride, %119.sub_hi_dim_then_sub_dim_count
    %82.sub_mod:eds = COPY %105.sub_mod
    %82.sub_dim_size:eds = COPY %87.sub_hi_dim_then_sub_dim_size
    %82.sub_dim_stride:eds = COPY %105.sub_dim_stride
    %82.sub_hi_dim_then_sub_dim_size:eds = COPY %87.sub_hi_dim_then_sub_dim_size
    %37:ep = MOV_PD_imm11_pseudo 0
    %82.sub_hi_dim_then_sub_dim_stride:eds = COPY %105.sub_dim_stride
    %82.sub_hi_dim_then_sub_dim_count:eds = COPY %93.sub_hi_dim_then_sub_dim_count
    %93.sub_dim_count:eds = COPY %119.sub_dim_count
    dead %37:ep, %82.sub_dim_count:eds, %82.sub_hi_dim_then_sub_dim_count:eds = PADD_3D_pseudo_split %37, %82.sub_mod, %82.sub_dim_size, %82.sub_dim_stride, %82.sub_dim_count, undef %82.sub_hi_dim_then_sub_mod, %82.sub_hi_dim_then_sub_dim_size, %82.sub_hi_dim_then_sub_dim_stride, %82.sub_hi_dim_then_sub_dim_count
    %76.sub_dim_count:eds = COPY %105.sub_mod
    %42:ep = MOV_PD_imm11_pseudo 0
    %76.sub_mod:eds = COPY %105.sub_mod
    %76.sub_dim_size:eds = COPY %87.sub_hi_dim_then_sub_dim_size
    %76.sub_dim_stride:eds = COPY %105.sub_dim_stride
    %76.sub_hi_dim_then_sub_dim_size:eds = COPY %87.sub_hi_dim_then_sub_dim_size
    %76.sub_hi_dim_then_sub_dim_stride:eds = COPY %105.sub_dim_stride
    dead %42:ep, %76.sub_dim_count:eds, %76.sub_hi_dim_then_sub_dim_count:eds = PADD_3D_pseudo_split %42, %76.sub_mod, %76.sub_dim_size, %76.sub_dim_stride, %76.sub_dim_count, undef %76.sub_hi_dim_then_sub_mod, %76.sub_hi_dim_then_sub_dim_size, %76.sub_hi_dim_then_sub_dim_stride, %76.sub_hi_dim_then_sub_dim_count
    PseudoJNZ %71, %bb.4
    PseudoJ_jump_imm %bb.1

  bb.3:
    successors: %bb.3(0x7c000000), %bb.2(0x04000000)

    %11:ep = MOV_PD_imm11_pseudo 0
    %105.sub_hi_dim_then_sub_dim_stride:eds = COPY %105.sub_dim_stride
    %105.sub_hi_dim_then_sub_dim_count:eds = COPY %110
    dead %11:ep, %105.sub_dim_count:eds, %105.sub_hi_dim_then_sub_dim_count:eds = PADD_3D_pseudo_split %11, %105.sub_mod, %105.sub_dim_size, %105.sub_dim_stride, %105.sub_dim_count, undef %105.sub_hi_dim_then_sub_mod, %105.sub_hi_dim_then_sub_dim_size, %105.sub_hi_dim_then_sub_dim_stride, %105.sub_hi_dim_then_sub_dim_count
    %18:ep = MOV_PD_imm11_pseudo 0
    %99.sub_mod:eds = COPY %105.sub_mod
    %99.sub_dim_stride:eds = COPY %105.sub_dim_stride
    %99.sub_hi_dim_then_sub_dim_stride:eds = COPY %105.sub_dim_stride
    %99.sub_hi_dim_then_sub_dim_count:eds = COPY %104
    dead %18:ep, %99.sub_dim_count:eds, %99.sub_hi_dim_then_sub_dim_count:eds = PADD_3D_pseudo_split %18, %99.sub_mod, %99.sub_dim_size, %99.sub_dim_stride, %99.sub_dim_count, undef %99.sub_hi_dim_then_sub_mod, %99.sub_hi_dim_then_sub_dim_size, %99.sub_hi_dim_then_sub_dim_stride, %99.sub_hi_dim_then_sub_dim_count
    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.3, implicit $ls, implicit $le
    PseudoJ_jump_imm %bb.2

  bb.4:
    PseudoRET implicit $lr

...
