# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
#
# Test for WAW register renaming revert when register classes have overlapping
# physical registers.
#
# This test verifies the fix for a crash in revertAllocation() where:
# 1. A candidate from a failed register class (e.g., eXo) needs to revert to
#    its original register (e.g., $x1)
# 2. A candidate from a successful register class (e.g., VEC512) was newly
#    assigned to the same register ($x1) during reallocation
# 3. Without the fix, reverting caused an "Overlapping insert" assertion in
#    LiveIntervalUnion because $x1 was still occupied
#
# The fix detects when a successful class candidate's new assignment conflicts
# with registers needed for reverting failed classes, and reverts those
# conflicting candidates as well.

# RUN: llc -mtriple=aie2p -verify-machineinstrs \
# RUN:     --start-before=greedy --stop-after=virtregrewriter \
# RUN:     %s -o - | FileCheck %s

---
name:            overlapping_failure_reg_classes
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: overlapping_failure_reg_classes
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $r0, $x0, $y2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $r1 = MOV_RLC_imm11_pseudo 0
  ; CHECK-NEXT:   renamable $r2 = MOV_RLC_imm11_pseudo 1
  ; CHECK-NEXT:   renamable $x6 = VBCST_32 renamable $r1
  ; CHECK-NEXT:   renamable $x8 = VBCST_32 renamable $r2
  ; CHECK-NEXT:   renamable $x7 = VBCST_16 renamable $r1
  ; CHECK-NEXT:   renamable $x9 = COPY renamable $x8
  ; CHECK-NEXT:   renamable $x11 = COPY renamable $x6
  ; CHECK-NEXT:   renamable $x10 = COPY renamable $x6
  ; CHECK-NEXT:   renamable $p0 = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   renamable $dm0 = VCLR
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT:   liveins: $dm0, $p0, $r0, $r1, $r2, $x0, $x6, $x7, $y2, $y4:0x0000000000000033, $y5:0x0000000000000033
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   dead renamable $x1 = IMPLICIT_DEF
  ; CHECK-NEXT:   LoopStart renamable $r0, -1
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $dm0, $p0, $r0, $r1, $r2, $x0, $x6, $x7, $y2, $y4:0x0000000000000033, $y5:0x0000000000000033
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   dead renamable $wh1 = VLD_w_idx_imm_pseudo renamable $p0, 0 :: (load (<8 x s32>) from `ptr addrspace(5) null`, addrspace 5)
  ; CHECK-NEXT:   renamable $wl1 = VLD_w_idx_imm_pseudo renamable $p0, 0 :: (load (<8 x s32>) from `ptr addrspace(5) null`, addrspace 5)
  ; CHECK-NEXT:   renamable $dm3 = VMAC_vmul_cm_core_Y_X renamable $dm0, renamable $y2, renamable $x0, renamable $r2
  ; CHECK-NEXT:   renamable $dm2 = VMAC_vmul_cm_core_Y_X renamable $dm0, renamable $y5, renamable $x7, renamable $r1
  ; CHECK-NEXT:   dead renamable $x3 = IMPLICIT_DEF
  ; CHECK-NEXT:   renamable $dm1 = VMAC_vmul_cm_core_Y_X renamable $dm0, renamable $y4, renamable $x0, renamable $r1
  ; CHECK-NEXT:   renamable $dm4 = COPY renamable $dm0
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.3(0x7c000000), %bb.4(0x04000000)
  ; CHECK-NEXT:   liveins: $dm0, $dm1, $dm2, $dm3, $dm4, $p0, $r0, $r1, $r2, $x0, $x1:0x0000000000000002, $x6, $x7, $y2, $y4:0x0000000000000033, $y5:0x0000000000000033
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $x2 = COPY renamable $x6
  ; CHECK-NEXT:   renamable $x3 = COPY renamable $x1
  ; CHECK-NEXT:   renamable $dm4 = VMAC_vmul_cm_core_Y_X killed renamable $dm4, killed renamable $y1, renamable $x0, renamable $r1
  ; CHECK-NEXT:   renamable $wl1 = VLD_w_idx_imm_pseudo renamable $p0, 0 :: (load unknown-size from `ptr addrspace(5) null`, align 32, addrspace 5)
  ; CHECK-NEXT:   dead renamable $wh1 = VLD_w_idx_imm_pseudo renamable $p0, 0 :: (load unknown-size from `ptr addrspace(5) null`, align 32, addrspace 5)
  ; CHECK-NEXT:   renamable $dm3 = VMAC_vmul_cm_core_Y_X killed renamable $dm3, renamable $y2, renamable $x0, renamable $r2
  ; CHECK-NEXT:   renamable $dm2 = VMAC_vmul_cm_core_Y_X killed renamable $dm2, renamable $y5, renamable $x7, renamable $r1
  ; CHECK-NEXT:   dead renamable $wl2 = IMPLICIT_DEF
  ; CHECK-NEXT:   renamable $dm1 = VMAC_vmul_cm_core_Y_X killed renamable $dm1, renamable $y4, renamable $x0, renamable $r1
  ; CHECK-NEXT:   dead renamable $x3 = IMPLICIT_DEF
  ; CHECK-NEXT:   dead renamable $x2 = IMPLICIT_DEF
  ; CHECK-NEXT:   PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.3, implicit $ls, implicit $le
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $dm0, $p0, $r0, $r1, $r2, $x0, $x6, $x7, $y2, $y4:0x0000000000000033, $y5:0x0000000000000033
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  bb.0.entry:
    successors: %bb.1(0x80000000)
    liveins: $r0, $x0, $y2

    %12:er = MOV_RLC_imm11_pseudo 0
    %18:er = MOV_RLC_imm11_pseudo 1
    %37:exe = VBCST_32 %12
    undef %24.sub_512_lo:vec1024 = VBCST_32 %18
    %1:vec1024 = COPY $y2
    %0:er = COPY $r0
    %2:vec512 = COPY $x0
    %21:vec512 = VBCST_16 %12
    %24.sub_512_hi:vec1024 = COPY %24.sub_512_lo
    undef %20.sub_512_hi:vec1024 = COPY %37
    %20.sub_512_lo:vec1024 = COPY %37
    %10:ep = MOV_PD_imm11_pseudo 0
    %33:acc2048 = VCLR

  bb.1:
    successors: %bb.2(0x80000000)

    dead %3:vec512 = IMPLICIT_DEF
    LoopStart %0, -1
    PseudoJ_jump_imm %bb.2

  bb.2:
    successors: %bb.3(0x80000000)

    dead %58:vec256 = VLD_w_idx_imm_pseudo %10, 0 :: (load (<8 x s32>) from `ptr addrspace(5) null`, addrspace 5)
    undef %99.sub_256_lo:exo = VLD_w_idx_imm_pseudo %10, 0 :: (load (<8 x s32>) from `ptr addrspace(5) null`, addrspace 5)
    %95:acc2048 = VMAC_vmul_cm_core_Y_X %33, %1, %2, %18
    %96:acc2048 = VMAC_vmul_cm_core_Y_X %33, %20, %21, %12
    dead %59:vec512 = IMPLICIT_DEF
    %97:acc2048 = VMAC_vmul_cm_core_Y_X %33, %24, %2, %12
    %98:acc2048 = COPY %33
    PseudoJ_jump_imm %bb.3

  bb.3:
    successors: %bb.3(0x7c000000), %bb.4(0x04000000)

    undef %75.sub_512_lo:vec1024 = COPY %37
    %75.sub_512_hi:vec1024 = COPY %99
    %98:acc2048 = VMAC_vmul_cm_core_Y_X %98, %75, %2, %12
    undef %99.sub_256_lo:exo = VLD_w_idx_imm_pseudo %10, 0 :: (load unknown-size from `ptr addrspace(5) null`, align 32, addrspace 5)
    dead %67:vec256 = VLD_w_idx_imm_pseudo %10, 0 :: (load unknown-size from `ptr addrspace(5) null`, align 32, addrspace 5)
    %95:acc2048 = VMAC_vmul_cm_core_Y_X %95, %1, %2, %18
    %96:acc2048 = VMAC_vmul_cm_core_Y_X %96, %20, %21, %12
    dead %82:ewl = IMPLICIT_DEF
    %97:acc2048 = VMAC_vmul_cm_core_Y_X %97, %24, %2, %12
    dead %68:vec512 = IMPLICIT_DEF
    dead %74:vec512 = IMPLICIT_DEF
    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.3, implicit $ls, implicit $le
    PseudoJ_jump_imm %bb.4

  bb.4:
    successors: %bb.1(0x80000000)

    PseudoJ_jump_imm %bb.1

...
