# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
# NOTE: Example file for Write After Write Register Renaming in Loop test
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates


# RUN: llc -mtriple=aie2p -verify-machineinstrs --start-before=greedy --stop-after=virtregrewriter %s -o - | FileCheck %s

# Workaround WAW register renaming pass for llvm bug #48911. We must not crash here.
# dm4 from `$dm4 = VLDA_DM_SPILL %stack.0...` is skipped from waw rewriter.

--- |
  define void @test_spill_no_waw_rewriter(i1 %exitcond.not) {
  entry:
    br label %for.body15

  for.body15:                                       ; preds = %for.body15, %entry
    br i1 %exitcond.not, label %for.body.i.preheader, label %for.body15

  for.body.i.preheader:                             ; preds = %for.body15
    br label %for.body.i

  for.body.i:                                       ; preds = %for.body.i.preheader, %for.body.i
    %0 = shufflevector <16 x i64> zeroinitializer, <16 x i64> zeroinitializer, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
    %s0 = bitcast <32 x i64> %0 to <64 x float>
    %1 = tail call <64 x float> @llvm.aie2p.ACC2048.accfloat.add.conf(<64 x float> %s0, <64 x float> <float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00>, i32 1)
    %2 = bitcast <64 x float> %1 to <32 x i64>
    %s172 = shufflevector <32 x i64> %2, <32 x i64> zeroinitializer, <16 x i32> <i32 0, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
    %s173 = trunc <16 x i64> %s172 to <16 x i32>
    %s175 = shufflevector <16 x i32> zeroinitializer, <16 x i32> %s173, <8 x i32> <i32 0, i32 1, i32 2, i32 16, i32 4, i32 5, i32 6, i32 7>
    %s251 = shufflevector <16 x i32> zeroinitializer, <16 x i32> zeroinitializer, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
    %s3 = bitcast <32 x i32> %s251 to <16 x i64>
    %s253 = shufflevector <16 x i64> %s3, <16 x i64> zeroinitializer, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
    %3 = bitcast <32 x i64> %s253 to <64 x float>
    %4 = tail call <64 x float> @llvm.aie2p.ACC2048.accfloat.add.conf(<64 x float> <float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00>, <64 x float> %3, i32 1)
    %5 = tail call <64 x float> @llvm.aie2p.ACC2048.accfloat.add.conf(<64 x float> %4, <64 x float> zeroinitializer, i32 1)
    %6 = bitcast <64 x float> %5 to <32 x i64>
    %s260 = shufflevector <32 x i64> %6, <32 x i64> zeroinitializer, <16 x i32> <i32 0, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
    %s261 = trunc <16 x i64> %s260 to <16 x i32>
    %s105 = shufflevector <8 x i32> zeroinitializer, <8 x i32> %s175, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 8, i32 9, i32 10, i32 11>
    %s152 = shufflevector <8 x i32> %s105, <8 x i32> zeroinitializer, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
    %s100 = shufflevector <16 x i32> %s261, <16 x i32> zeroinitializer, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
    %7 = bitcast <16 x i32> %s152 to <32 x bfloat>
    %8 = bitcast <32 x i32> %s100 to <32 x float>
    %9 = tail call <32 x float> @llvm.aie2p.I512.I512.ACC1024.bf.msc.conf(<32 x bfloat> %7, <32 x bfloat> zeroinitializer, <32 x float> %8, i32 1)
    %10 = bitcast <32 x float> %9 to <32 x i32>
    %11 = bitcast <32 x i32> %10 to <16 x i64>
    %s101 = shufflevector <16 x i64> %11, <16 x i64> zeroinitializer, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
    %12 = bitcast <32 x i64> %s101 to <64 x float>
    %13 = tail call <64 x float> @llvm.aie2p.ACC2048.accfloat.add.conf(<64 x float> %12, <64 x float> zeroinitializer, i32 1)
    %14 = bitcast <64 x float> %13 to <32 x i64>
    %s102 = shufflevector <32 x i64> %14, <32 x i64> zeroinitializer, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
    %15 = bitcast <16 x i64> %s102 to <32 x i32>
    %s103 = shufflevector <32 x i32> %15, <32 x i32> zeroinitializer, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
    %s104 = shufflevector <8 x i32> %s103, <8 x i32> zeroinitializer, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
    %16 = tail call <16 x i64> @llvm.aie2p.acc64.v16.I512.ups(<16 x i32> %s104, i32 0, i32 0)
    br i1 %exitcond.not, label %if.end65, label %for.body.i

  if.end65:                                         ; preds = %for.body.i
    ret void
  }

  declare <64 x float> @llvm.aie2p.ACC2048.accfloat.add.conf(<64 x float>, <64 x float>, i32) #0

  declare <32 x float> @llvm.aie2p.I512.I512.ACC1024.bf.msc.conf(<32 x bfloat>, <32 x bfloat>, <32 x float>, i32) #0

  declare <16 x i64> @llvm.aie2p.acc64.v16.I512.ups(<16 x i32>, i32, i32) #1

  attributes #0 = { nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read) }
  attributes #1 = { nounwind memory(inaccessiblemem: read) }

...
---
name:            test_spill_no_waw_rewriter
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
isOutlined:      false
debugInstrRef:   false
failsVerification: false
tracksDebugUserValues: false
body:             |
  ; CHECK-LABEL: name: test_spill_no_waw_rewriter
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $r16 = MOV_RLC_imm11_pseudo 0
  ; CHECK-NEXT:   renamable $r17 = COPY renamable $r16
  ; CHECK-NEXT:   renamable $x2 = VBCST_64 renamable $l8
  ; CHECK-NEXT:   renamable $r1 = MOVXM 1065353216
  ; CHECK-NEXT:   renamable $x4 = VBCST_32 killed renamable $r1
  ; CHECK-NEXT:   renamable $x0 = VBCST_32 renamable $r16
  ; CHECK-NEXT:   renamable $bmll1 = COPY killed renamable $x2
  ; CHECK-NEXT:   renamable $bmlh1 = COPY renamable $bmll1
  ; CHECK-NEXT:   renamable $x5 = COPY renamable $x4
  ; CHECK-NEXT:   renamable $cml2 = COPY renamable $y2
  ; CHECK-NEXT:   renamable $cmh2 = COPY killed renamable $y2
  ; CHECK-NEXT:   renamable $r1 = MOV_RLC_imm11_pseudo 1
  ; CHECK-NEXT:   renamable $wh2 = COPY renamable $wl0
  ; CHECK-NEXT:   renamable $x4 = VBCST_16 renamable $r16
  ; CHECK-NEXT:   renamable $dm4 = VCLR
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.for.body15:
  ; CHECK-NEXT:   successors: %bb.2(0x04000000), %bb.1(0x7c000000)
  ; CHECK-NEXT:   liveins: $dm1:0x000000000000000C, $dm2:0x000000001800000C, $dm4, $l8:0x0000000000010000, $r0, $r1, $x2:0x0000000000000001, $x4, $y0:0x0000000000000003
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $r2 = XOR renamable $r0, renamable $r1
  ; CHECK-NEXT:   renamable $r2 = AND killed renamable $r2, renamable $r1
  ; CHECK-NEXT:   PseudoJNZ killed renamable $r2, %bb.1
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.for.body.i.preheader:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $dm1:0x000000000000000C, $dm2:0x000000001800000C, $dm4, $l8:0x0000000000010000, $r0, $r1, $x2:0x0000000000000001, $x4, $y0:0x0000000000000003
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $r6 = VEXTRACT_32_vec_extract_imm_vaddSign1 renamable $x0, 0, implicit $vaddsign1
  ; CHECK-NEXT:   renamable $r7 = VEXTRACT_32_vec_extract_imm_vaddSign1 renamable $x0, 1, implicit $vaddsign1
  ; CHECK-NEXT:   renamable $r17 = VEXTRACT_32_vec_extract_imm_vaddSign1 renamable $x0, 2, implicit $vaddsign1
  ; CHECK-NEXT:   renamable $r2 = VEXTRACT_32_vec_extract_imm_vaddSign1 renamable $x0, 4, implicit $vaddsign1
  ; CHECK-NEXT:   renamable $r3 = VEXTRACT_32_vec_extract_imm_vaddSign1 renamable $x0, 5, implicit $vaddsign1
  ; CHECK-NEXT:   renamable $r4 = VEXTRACT_32_vec_extract_imm_vaddSign1 renamable $x0, 6, implicit $vaddsign1
  ; CHECK-NEXT:   renamable $r5 = VEXTRACT_32_vec_extract_imm_vaddSign1 renamable $x0, 7, implicit $vaddsign1
  ; CHECK-NEXT:   renamable $x6 = VPUSH_hi_32 undef renamable $x0, killed renamable $r6
  ; CHECK-NEXT:   renamable $x6 = VPUSH_hi_32 killed renamable $x6, killed renamable $r7
  ; CHECK-NEXT:   renamable $x6 = VPUSH_hi_32 killed renamable $x6, killed renamable $r17
  ; CHECK-NEXT:   renamable $r6 = MOV_RLC_imm11_pseudo 4
  ; CHECK-NEXT:   renamable $r7 = MOV_RLC_imm11_pseudo 1
  ; CHECK-NEXT:   renamable $x1 = COPY renamable $x0
  ; CHECK-NEXT:   renamable $bmlh3 = COPY renamable $x0
  ; CHECK-NEXT:   renamable $s0 = COPY killed renamable $r16
  ; CHECK-NEXT:   $crupsmode = MOV_scalar_imm11_pseudo 1
  ; CHECK-NEXT:   VST_DM_SPILL killed renamable $dm4, %stack.0, implicit $sp :: (store (s2048) into %stack.0, align 64)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.for.body.i:
  ; CHECK-NEXT:   successors: %bb.4(0x04000000), %bb.3(0x7c000000)
  ; CHECK-NEXT:   liveins: $dm1:0x000000000000000C, $dm2:0x000000001800000C, $dm3:0x0000000000000004, $r0, $r1, $r2, $r3, $r4, $r5, $r6, $r7, $s0, $x2:0x0000000000000001, $x4, $x6, $y0:0x0000000000000033
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $dm4 = VADD_f_vmac_cm2_add_reg renamable $dm1, renamable $dm2, renamable $r1, implicit-def dead $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   renamable $cml0 = COPY renamable $y0
  ; CHECK-NEXT:   renamable $dm0 = VADD_f_vmac_cm2_add_reg renamable $dm2, renamable $dm0, renamable $r1, implicit-def dead $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   renamable $y4 = COPY killed renamable $cml4
  ; CHECK-NEXT:   renamable $dm4 = VLDA_DM_SPILL %stack.0, implicit $sp :: (load (s2048) from %stack.0, align 64)
  ; CHECK-NEXT:   renamable $x10 = VSHUFFLE_vec_shuffle_x killed renamable $x8, renamable $x9, renamable $r6
  ; CHECK-NEXT:   renamable $r16 = VEXTRACT_32_vec_extract_imm_vaddSign1 killed renamable $x10, 0, implicit $vaddsign1
  ; CHECK-NEXT:   renamable $dm0 = VADD_f_vmac_cm2_add_reg killed renamable $dm0, renamable $dm4, renamable $r1, implicit-def dead $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   renamable $x3 = VPUSH_hi_32 renamable $x6, killed renamable $r16
  ; CHECK-NEXT:   renamable $x5 = VPUSH_hi_32 killed renamable $x3, renamable $r2
  ; CHECK-NEXT:   renamable $x7 = VPUSH_hi_32 killed renamable $x5, renamable $r3
  ; CHECK-NEXT:   renamable $x9 = VPUSH_hi_32 killed renamable $x7, renamable $r4
  ; CHECK-NEXT:   renamable $x8 = VPUSH_hi_32 killed renamable $x9, renamable $r5
  ; CHECK-NEXT:   renamable $y5 = COPY killed renamable $cml0
  ; CHECK-NEXT:   renamable $x11 = VSHUFFLE_vec_shuffle_x killed renamable $x10, renamable $x11, renamable $r6
  ; CHECK-NEXT:   renamable $r16 = VEXTRACT_32_vec_extract_imm_vaddSign1 renamable $x0, 0, implicit $vaddsign1
  ; CHECK-NEXT:   renamable $r17 = VEXTRACT_32_vec_extract_imm_vaddSign1 renamable $x0, 1, implicit $vaddsign1
  ; CHECK-NEXT:   renamable $r18 = VEXTRACT_32_vec_extract_imm_vaddSign1 renamable $x0, 2, implicit $vaddsign1
  ; CHECK-NEXT:   renamable $r19 = VEXTRACT_32_vec_extract_imm_vaddSign1 renamable $x0, 3, implicit $vaddsign1
  ; CHECK-NEXT:   renamable $wl2 = COPY killed renamable $wh8
  ; CHECK-NEXT:   renamable $r20 = VEXTRACT_32_vec_extract_imm_vaddSign1 renamable $x2, 0, implicit $vaddsign1
  ; CHECK-NEXT:   renamable $r21 = VEXTRACT_32_vec_extract_imm_vaddSign1 renamable $x2, 1, implicit $vaddsign1
  ; CHECK-NEXT:   renamable $r22 = VEXTRACT_32_vec_extract_imm_vaddSign1 renamable $x2, 2, implicit $vaddsign1
  ; CHECK-NEXT:   renamable $r23 = VEXTRACT_32_vec_extract_imm_vaddSign1 renamable $x2, 3, implicit $vaddsign1
  ; CHECK-NEXT:   renamable $x10 = VPUSH_hi_32 undef renamable $x0, killed renamable $r16
  ; CHECK-NEXT:   renamable $x10 = VPUSH_hi_32 killed renamable $x10, killed renamable $r17
  ; CHECK-NEXT:   renamable $x10 = VPUSH_hi_32 killed renamable $x10, killed renamable $r18
  ; CHECK-NEXT:   renamable $x10 = VPUSH_hi_32 killed renamable $x10, killed renamable $r19
  ; CHECK-NEXT:   renamable $x10 = VPUSH_hi_32 killed renamable $x10, killed renamable $r20
  ; CHECK-NEXT:   renamable $x10 = VPUSH_hi_32 killed renamable $x10, killed renamable $r21
  ; CHECK-NEXT:   renamable $x10 = VPUSH_hi_32 killed renamable $x10, killed renamable $r22
  ; CHECK-NEXT:   renamable $x10 = VPUSH_hi_32 killed renamable $x10, killed renamable $r23
  ; CHECK-NEXT:   renamable $wl2 = COPY killed renamable $wh10
  ; CHECK-NEXT:   renamable $bmll3 = COPY killed renamable $x11
  ; CHECK-NEXT:   renamable $dm0 = VMSC_f_vmac_bf_vmul_bf_core_X_X renamable $dm3, renamable $x2, renamable $x4, renamable $r1, implicit-def dead $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   renamable $dm0 = VADD_f_vmac_cm2_add_reg killed renamable $dm0, killed renamable $dm4, renamable $r1, implicit-def dead $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   renamable $y4 = COPY killed renamable $cml0
  ; CHECK-NEXT:   renamable $wh8 = COPY renamable $wh2
  ; CHECK-NEXT:   renamable $r16 = XOR renamable $r0, renamable $r7
  ; CHECK-NEXT:   dead renamable $cmh3 = VUPS_2x_mv_ups_x2c_upsSign0 killed renamable $x8, renamable $s0, implicit-def dead $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
  ; CHECK-NEXT:   renamable $r16 = AND killed renamable $r16, renamable $r7
  ; CHECK-NEXT:   PseudoJNZ killed renamable $r16, %bb.3
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4.if.end65:
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.0.entry:
    successors: %bb.1(0x80000000)
    liveins: $r0

    undef %4.sub_l_even:el = MOV_RLC_imm11_pseudo 0
    %4.sub_l_odd:el = COPY %4.sub_l_even
    %48:vec512 = VBCST_64 %4
    %8:er = MOVXM 1065353216
    undef %124.sub_512_lo:vec1024 = VBCST_32 %8
    undef %60.sub_512_lo:vec1024 = VBCST_32 %4.sub_l_even
    %1:er = COPY $r0
    undef %58.sub_512_acc_lo:acc2048 = COPY %48
    %58.sub_512_acc_hi:acc2048 = COPY %58.sub_512_acc_lo
    %124.sub_512_hi:vec1024 = COPY %124.sub_512_lo
    undef %7.sub_1024_acc_lo:acc2048 = COPY %124
    %7.sub_1024_acc_hi:acc2048 = COPY %124
    %9:er = MOV_RLC_imm11_pseudo 1
    undef %63.sub_256_hi:vec512 = COPY %60.sub_256_lo
    %34:vec512 = VBCST_16 %4.sub_l_even
    %23:acc2048 = VCLR

  bb.1.for.body15:
    successors: %bb.2(0x04000000), %bb.1(0x7c000000)

    %120:er = XOR %1, %9
    %117:er = AND %120, %9
    PseudoJNZ %117, %bb.1
    PseudoJ_jump_imm %bb.2

  bb.2.for.body.i.preheader:
    successors: %bb.3(0x80000000)

    %105:er = VEXTRACT_32_vec_extract_imm_vaddSign1 %60.sub_512_lo, 0, implicit $vaddsign1
    %106:er = VEXTRACT_32_vec_extract_imm_vaddSign1 %60.sub_512_lo, 1, implicit $vaddsign1
    %107:er = VEXTRACT_32_vec_extract_imm_vaddSign1 %60.sub_512_lo, 2, implicit $vaddsign1
    %110:er = VEXTRACT_32_vec_extract_imm_vaddSign1 %60.sub_512_lo, 4, implicit $vaddsign1
    %112:er = VEXTRACT_32_vec_extract_imm_vaddSign1 %60.sub_512_lo, 5, implicit $vaddsign1
    %114:er = VEXTRACT_32_vec_extract_imm_vaddSign1 %60.sub_512_lo, 6, implicit $vaddsign1
    %116:er = VEXTRACT_32_vec_extract_imm_vaddSign1 %60.sub_512_lo, 7, implicit $vaddsign1
    %138:vec512 = VPUSH_hi_32 undef %127:vec512, %105
    %139:vec512 = VPUSH_hi_32 %138, %106
    %140:vec512 = VPUSH_hi_32 %139, %107
    %168:er = MOV_RLC_imm11_pseudo 4
    %77:er = MOV_RLC_imm11_pseudo 1
    %60.sub_512_hi:vec1024 = COPY %60.sub_512_lo
    undef %155.sub_512_acc_hi:acc2048 = COPY %60.sub_512_lo
    %153:es = COPY %4.sub_l_even
    $crupsmode = MOV_scalar_imm11_pseudo 1

  bb.3.for.body.i:
    successors: %bb.4(0x04000000), %bb.3(0x7c000000)

    %6:acc2048 = VADD_f_vmac_cm2_add_reg %58, %7, %9, implicit-def dead $srfpflags, implicit $crfpmask
    undef %61.sub_1024_acc_lo:acc2048 = COPY %60
    %21:acc2048 = VADD_f_vmac_cm2_add_reg %7, %61, %9, implicit-def dead $srfpflags, implicit $crfpmask
    %169:vec1024 = COPY %6.sub_1024_acc_lo
    %13:vec512 = VSHUFFLE_vec_shuffle_x %169.sub_512_lo, %169.sub_512_hi, %168
    %108:er = VEXTRACT_32_vec_extract_imm_vaddSign1 %13, 0, implicit $vaddsign1
    %22:acc2048 = VADD_f_vmac_cm2_add_reg %21, %23, %9, implicit-def dead $srfpflags, implicit $crfpmask
    %141:vec512 = VPUSH_hi_32 %140, %108
    %142:vec512 = VPUSH_hi_32 %141, %110
    %143:vec512 = VPUSH_hi_32 %142, %112
    %144:vec512 = VPUSH_hi_32 %143, %114
    %145:vec512 = VPUSH_hi_32 %144, %116
    %163:vec1024 = COPY %22.sub_1024_acc_lo
    %27:vec512 = VSHUFFLE_vec_shuffle_x %163.sub_512_lo, %163.sub_512_hi, %168
    %79:er = VEXTRACT_32_vec_extract_imm_vaddSign1 %60.sub_512_lo, 0, implicit $vaddsign1
    %80:er = VEXTRACT_32_vec_extract_imm_vaddSign1 %60.sub_512_lo, 1, implicit $vaddsign1
    %82:er = VEXTRACT_32_vec_extract_imm_vaddSign1 %60.sub_512_lo, 2, implicit $vaddsign1
    %84:er = VEXTRACT_32_vec_extract_imm_vaddSign1 %60.sub_512_lo, 3, implicit $vaddsign1
    undef %96.sub_256_lo:vec512 = COPY %145.sub_256_hi
    %85:er = VEXTRACT_32_vec_extract_imm_vaddSign1 %96, 0, implicit $vaddsign1
    %86:er = VEXTRACT_32_vec_extract_imm_vaddSign1 %96, 1, implicit $vaddsign1
    %87:er = VEXTRACT_32_vec_extract_imm_vaddSign1 %96, 2, implicit $vaddsign1
    %88:er = VEXTRACT_32_vec_extract_imm_vaddSign1 %96, 3, implicit $vaddsign1
    %128:vec512 = VPUSH_hi_32 undef %127:vec512, %79
    %129:vec512 = VPUSH_hi_32 %128, %80
    %130:vec512 = VPUSH_hi_32 %129, %82
    %131:vec512 = VPUSH_hi_32 %130, %84
    %132:vec512 = VPUSH_hi_32 %131, %85
    %133:vec512 = VPUSH_hi_32 %132, %86
    %134:vec512 = VPUSH_hi_32 %133, %87
    %135:vec512 = VPUSH_hi_32 %134, %88
    %63.sub_256_lo:vec512 = COPY %135.sub_256_hi
    %155.sub_512_acc_lo:acc2048 = COPY %27
    %65:acc2048 = VMSC_f_vmac_bf_vmul_bf_core_X_X %155, %63, %34, %9, implicit-def dead $srfpflags, implicit $crfpmask
    %39:acc2048 = VADD_f_vmac_cm2_add_reg %65, %23, %9, implicit-def dead $srfpflags, implicit $crfpmask
    %42:vec1024 = COPY %39.sub_1024_acc_lo
    %42.sub_256_hi:vec1024 = COPY %63.sub_256_hi
    %76:er = XOR %1, %77
    dead %46:acc1024 = VUPS_2x_mv_ups_x2c_upsSign0 %42.sub_512_lo, %153, implicit-def dead $srups_of, implicit $crsat, implicit $crupsmode, implicit $upssign0
    %73:er = AND %76, %77
    PseudoJNZ %73, %bb.3
    PseudoJ_jump_imm %bb.4

  bb.4.if.end65:
    PseudoRET implicit $lr

...
