# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
# NOTE: Example file for Write After Write Register Renaming in Loop test
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates

# Basic test for the WAW register renaming pass with swp-aware policy.
# We change the allocation order by estimating the cycle in which
# each instruction runs in the pipelined schedule

# RUN: llc -mtriple=aie2p -verify-machineinstrs \
# RUN:     --aie-reg-rewrite-mode=swpaware-auto \
# RUN:     --start-before=greedy --stop-after=virtregrewriter \
# RUN:     %s -o - | FileCheck %s

---
name:            conv2d_dw_bf16
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: conv2d_dw_bf16
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $p1, $p2, $p3, $p4, $p5, $r0, $r1, $r2, $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   dead renamable $p6 = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   renamable $dj4 = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   renamable $dn0 = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   renamable $dn4 = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   renamable $m1 = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   renamable $dj1 = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   renamable $dn1 = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   renamable $dc0 = MOV_PD_imm11_pseudo 0
  ; CHECK-NEXT:   renamable $r0 = MOV_RLC_imm11_pseudo 16
  ; CHECK-NEXT:   renamable $r3 = MOV_RLC_imm11_pseudo 32
  ; CHECK-NEXT:   renamable $r4 = MOV_RLC_imm11_pseudo 48
  ; CHECK-NEXT:   renamable $r5 = MOV_RLC_imm11_pseudo 60
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT:   liveins: $dc0, $dj1, $dj4, $dn0, $dn1, $dn4, $m1, $p0, $p1, $p2, $p3, $p4, $p5, $r0, $r1, $r2, $r3, $r4, $r5, $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $cml2 = VLDA_CONV_fp32_bf16_dmx_lda_ups_bf_idx_imm killed renamable $p3, 0, implicit-def $cmh2 :: (load (<32 x s16>), addrspace 6)
  ; CHECK-NEXT:   renamable $m0 = COPY killed renamable $p4
  ; CHECK-NEXT:   renamable $dj0 = COPY killed renamable $p5
  ; CHECK-NEXT:   renamable $dc4 = COPY renamable $dc0
  ; CHECK-NEXT:   LoopStart killed renamable $r1, 0
  ; CHECK-NEXT:   renamable $dc1 = COPY renamable $dc0
  ; CHECK-NEXT:   renamable $cml4 = COPY renamable $cml2, implicit-def $cmh4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.2(0x7c000000), %bb.3(0x04000000)
  ; CHECK-NEXT:   liveins: $dc0, $dc1, $dc4, $dj0, $dj1, $dj4, $dm2:0x000000001800000C, $dm4:0x000000001800000C, $dn0, $dn1, $dn4, $m0, $m1, $p0, $p1, $p2, $r0, $r2, $r3, $r4, $r5, $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $x2, $p2, $dc1 = VLD_2D_x_pseudo_split killed $p2, $m1, $dn1, $dj1, killed $dc1 :: (load (<16 x s32>), addrspace 6)
  ; CHECK-NEXT:   renamable $x4, renamable $p1 = VLD_x_pstm_nrm_imm_pseudo killed renamable $p1, 64 :: (load (<32 x s16>), addrspace 5)
  ; CHECK-NEXT:   renamable $x6, renamable $p1 = VLD_x_pstm_nrm_imm_pseudo killed renamable $p1, 64 :: (load (<32 x s16>), addrspace 5)
  ; CHECK-NEXT:   $x8, $p1, $dc0, $dc4 = VLD_3D_x_pseudo_split killed $p1, $m0, $dn0, $dj0, killed $dc0, undef $m4, $dn4, $dj4, killed $dc4 :: (load (<32 x s16>), addrspace 5)
  ; CHECK-NEXT:   renamable $x10 = VEXTBCST_128_vec_extract_broadcast_imm renamable $x2, 0
  ; CHECK-NEXT:   renamable $x1 = VSHIFT renamable $x4, renamable $x6, renamable $r0
  ; CHECK-NEXT:   renamable $dm3 = VMAC_f_vmac_bf_vmul_bf_core_X_X killed renamable $dm2, renamable $x4, renamable $x10, renamable $r5, implicit-def dead $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   renamable $x3 = VEXTBCST_128_vec_extract_broadcast_imm renamable $x2, 1
  ; CHECK-NEXT:   renamable $dm4 = VMAC_f_vmac_bf_vmul_bf_core_X_X killed renamable $dm4, renamable $x6, killed renamable $x10, renamable $r5, implicit-def dead $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   renamable $x7 = VSHIFT renamable $x6, renamable $x8, renamable $r0
  ; CHECK-NEXT:   renamable $x5 = VSHIFT renamable $x4, renamable $x6, renamable $r3
  ; CHECK-NEXT:   renamable $dm3 = VMAC_f_vmac_bf_vmul_bf_core_X_X killed renamable $dm3, killed renamable $x1, renamable $x3, renamable $r5, implicit-def dead $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   renamable $x9 = VEXTBCST_128_vec_extract_broadcast_imm renamable $x2, 2
  ; CHECK-NEXT:   renamable $dm1 = VMAC_f_vmac_bf_vmul_bf_core_X_X killed renamable $dm4, killed renamable $x7, killed renamable $x3, renamable $r5, implicit-def dead $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   renamable $x10 = VSHIFT renamable $x6, renamable $x8, renamable $r3
  ; CHECK-NEXT:   renamable $x4 = VSHIFT killed renamable $x4, renamable $x6, renamable $r4
  ; CHECK-NEXT:   renamable $dm0 = VMAC_f_vmac_bf_vmul_bf_core_X_X killed renamable $dm3, killed renamable $x5, renamable $x9, renamable $r5, implicit-def dead $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   renamable $x11 = VEXTBCST_128_vec_extract_broadcast_imm killed renamable $x2, 3
  ; CHECK-NEXT:   renamable $dm1 = VMAC_f_vmac_bf_vmul_bf_core_X_X killed renamable $dm1, killed renamable $x10, killed renamable $x9, renamable $r5, implicit-def dead $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   renamable $x6 = VSHIFT killed renamable $x6, killed renamable $x8, renamable $r4
  ; CHECK-NEXT:   renamable $dm2 = VMAC_f_vmac_bf_vmul_bf_core_X_X killed renamable $dm0, killed renamable $x4, renamable $x11, renamable $r5, implicit-def dead $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   renamable $dm4 = VMAC_f_vmac_bf_vmul_bf_core_X_X killed renamable $dm1, killed renamable $x6, killed renamable $x11, renamable $r5, implicit-def dead $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.2, implicit $ls, implicit $le
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   liveins: $dm2:0x000000000000000C, $dm4:0x000000000000000C, $p0, $r2, $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $x2 = VCONV_bf16_fp32_mv_x_srs_bf killed renamable $cml2, implicit-def dead $srf2fflags, implicit $crf2fmask, implicit $crrnd
  ; CHECK-NEXT:   renamable $x4 = VCONV_bf16_fp32_mv_x_srs_bf killed renamable $cml4, implicit-def dead $srf2fflags, implicit $crf2fmask, implicit $crrnd
  ; CHECK-NEXT:   renamable $x2 = VSHUFFLE_vec_shuffle_x killed renamable $x2, killed renamable $x4, killed renamable $r2
  ; CHECK-NEXT:   renamable $x0, dead renamable $r16 = VMAX_LT_bf16 killed renamable $x2, killed renamable $x0
  ; CHECK-NEXT:   VST_dmx_sts_x_idx_imm killed renamable $x0, killed renamable $p0, 0 :: (store (<32 x s16>))
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $p0, $p1, $p2, $p3, $p4, $p5, $r0, $r1, $r2, $x0

    %1:ep = COPY $p0
    %4:ep = COPY $p3
    %6:ep = COPY $p4
    %7:ep = COPY $p5
    %5:er = COPY $r1
    %24:er = COPY $r2
    %22:vec512 = COPY $x0
    %167:ep_as_32bit = COPY $p1
    %168:ep_as_32bit = COPY $p2
    %32:ep_as_32bit =  MOV_PD_imm11_pseudo 0
    undef %165.sub_hi_dim_then_sub_dim_stride:eds = MOV_PD_imm11_pseudo 0
    %165.sub_dim_size:eds = MOV_PD_imm11_pseudo 0
    %165.sub_hi_dim_then_sub_dim_size:eds = MOV_PD_imm11_pseudo 0
    undef %164.sub_mod:ed = MOV_PD_imm11_pseudo 0
    %164.sub_dim_stride:ed =  MOV_PD_imm11_pseudo 0
    %164.sub_dim_size:ed =  MOV_PD_imm11_pseudo 0
    %165.sub_dim_count:eds = MOV_PD_imm11_pseudo 0
    %78:er = MOV_RLC_imm11_pseudo 16
    %80:er = MOV_RLC_imm11_pseudo 32
    %82:er = MOV_RLC_imm11_pseudo 48
    %105:er = MOV_RLC_imm11_pseudo 60

  bb.1:
    successors: %bb.2(0x80000000)

    undef %162.sub_1024_acc_lo:acc2048 = VLDA_CONV_fp32_bf16_dmx_lda_ups_bf_idx_imm %4, 0 :: (load (<32 x s16>), addrspace 6)
    %165.sub_mod:eds = COPY %6
    %165.sub_dim_stride:eds = COPY %7
    %165.sub_hi_dim_then_sub_dim_count:eds = COPY %165.sub_dim_count
    LoopStart %5, 0
    %164.sub_dim_count:ed = COPY %165.sub_dim_count
    undef %154.sub_1024_acc_lo:acc2048 = COPY %162.sub_1024_acc_lo

  bb.2:
    successors: %bb.2(0x7c000000), %bb.3(0x04000000)

    %86:vec512, %168:ep_as_32bit, %164.sub_dim_count:ed = VLD_2D_x_pseudo_split %168, %164.sub_mod, %164.sub_dim_size, %164.sub_dim_stride, %164.sub_dim_count :: (load (<16 x s32>), addrspace 6)
    %61:vec512, %167:ep_as_32bit = VLD_x_pstm_nrm_imm_pseudo %167, 64 :: (load (<32 x s16>), addrspace 5)
    %64:vec512, %167:ep_as_32bit = VLD_x_pstm_nrm_imm_pseudo %167, 64 :: (load (<32 x s16>), addrspace 5)
    %67:vec512, %167:ep_as_32bit, %165.sub_dim_count:eds, %165.sub_hi_dim_then_sub_dim_count:eds = VLD_3D_x_pseudo_split %167, %165.sub_mod, %165.sub_dim_size, %165.sub_dim_stride, %165.sub_dim_count, undef %165.sub_hi_dim_then_sub_mod, %165.sub_hi_dim_then_sub_dim_size, %165.sub_hi_dim_then_sub_dim_stride, %165.sub_hi_dim_then_sub_dim_count :: (load (<32 x s16>), addrspace 5)
    %102:vec512 = VEXTBCST_128_vec_extract_broadcast_imm %86, 0
    %76:vec512 = VSHIFT %61, %64, %78
    %163:acc2048 = VMAC_f_vmac_bf_vmul_bf_core_X_X %162, %61, %102, %105, implicit-def dead $srfpflags, implicit $crfpmask
    %93:vec512 = VEXTBCST_128_vec_extract_broadcast_imm %86, 1
    %155:acc2048 = VMAC_f_vmac_bf_vmul_bf_core_X_X %154, %64, %102, %105, implicit-def dead $srfpflags, implicit $crfpmask
    %83:vec512 = VSHIFT %64, %67, %78
    %79:vec512 = VSHIFT %61, %64, %80
    %161:acc2048 = VMAC_f_vmac_bf_vmul_bf_core_X_X %163, %76, %93, %105, implicit-def dead $srfpflags, implicit $crfpmask
    %96:vec512 = VEXTBCST_128_vec_extract_broadcast_imm %86, 2
    %153:acc2048 = VMAC_f_vmac_bf_vmul_bf_core_X_X %155, %83, %93, %105, implicit-def dead $srfpflags, implicit $crfpmask
    %84:vec512 = VSHIFT %64, %67, %80
    %81:vec512 = VSHIFT %61, %64, %82
    %159:acc2048 = VMAC_f_vmac_bf_vmul_bf_core_X_X %161, %79, %96, %105, implicit-def dead $srfpflags, implicit $crfpmask
    %99:vec512 = VEXTBCST_128_vec_extract_broadcast_imm %86, 3
    %151:acc2048 = VMAC_f_vmac_bf_vmul_bf_core_X_X %153, %84, %96, %105, implicit-def dead $srfpflags, implicit $crfpmask
    %85:vec512 = VSHIFT %64, %67, %82
    %162:acc2048 = VMAC_f_vmac_bf_vmul_bf_core_X_X %159, %81, %99, %105, implicit-def dead $srfpflags, implicit $crfpmask
    %154:acc2048 = VMAC_f_vmac_bf_vmul_bf_core_X_X %151, %85, %99, %105, implicit-def dead $srfpflags, implicit $crfpmask
    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.2, implicit $ls, implicit $le
    PseudoJ_jump_imm %bb.3

  bb.3:
    %114:vec512 = VCONV_bf16_fp32_mv_x_srs_bf %162.sub_1024_acc_lo, implicit-def dead $srf2fflags, implicit $crf2fmask, implicit $crrnd
    %115:vec512 = VCONV_bf16_fp32_mv_x_srs_bf %154.sub_1024_acc_lo, implicit-def dead $srf2fflags, implicit $crf2fmask, implicit $crrnd
    %118:vec512 = VSHUFFLE_vec_shuffle_x %114, %115, %24
    %120:vec512, dead %121:mr16_vcompare = VMAX_LT_bf16 %118, %22
    VST_dmx_sts_x_idx_imm %120, %1, 0 :: (store (<32 x s16>))
    PseudoRET implicit $lr

...
