# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
# NOTE: Example file for Write After Write Register Renaming in Loop test
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates

# Basic test for the WAW register renaming pass. Check AIE2 tests for more
# coverage. Additional pass options are disabled because we are testing the
# basic mechanism.

# RUN: llc -mtriple=aie2p -verify-machineinstrs --aie-reg-rewrite-mode=basic \
# RUN:   --start-before=greedy --stop-after=virtregrewriter \
# RUN:   %s -o - | FileCheck %s

# Make sure VLD and VMAX define different X registers.
---
name:            simple_waw_replacement
alignment:       16
legalized:       true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: simple_waw_replacement
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $p1, $r0, $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   LoopStart $r0, 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $d0, $d2, $p0, $p1, $p2, $x0, $d1_3d
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $x6, renamable $p0 = VLDA_dmx_lda_x_pstm_nrm_imm killed renamable $p0, 64
  ; CHECK-NEXT:   renamable $x8, dead renamable $r16 = VMAX_LT_32_vaddSign1 killed renamable $x6, renamable $x0, implicit $vaddsign1
  ; CHECK-NEXT:   renamable $p1 = VST_dmx_sts_x_pstm_nrm_imm killed renamable $x8, killed renamable $p1, 64
  ; CHECK-NEXT:   PseudoLoopEnd <mcsymbol .L_1120>, %bb.1, implicit $ls, implicit $le
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.0.entry:
  successors: %bb.1
  liveins: $r0, $p0, $p1, $x0
  %0:ep = COPY $p0
  %1:vec512 = COPY $x0
  %2:ep = COPY $p1
  LoopStart $r0, 0
  bb.1:
    successors: %bb.1, %bb.2
    liveins: $p0, $p1, $p2, $d0, $d1_3d, $d2

    %10:vec512, %0:ep = VLDA_dmx_lda_x_pstm_nrm_imm %0, 64
    %11:vec512, %12:mr16_vcompare = VMAX_LT_32_vaddSign1 %10, %1, implicit $vaddsign1
    %2:ep = VST_dmx_sts_x_pstm_nrm_imm %11, %2, 64
    PseudoLoopEnd <mcsymbol .L_1120>, %bb.1, implicit $ls, implicit $le
  bb.2:
    PseudoRET implicit $lr
...

# Make sure the VSHUFFLE get two new EX registers.
# This is based on the innermost loop of Conv2D_bfp16
---
name:            vec576_reg
alignment:       16
legalized:       true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: vec576_reg
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $dm0, $m1, $p0, $p1, $p2, $p3, $p4, $p5, $r0, $r1, $r2, $r3, $r4, $r5, $r6, $d0_3d
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $p0 = KILL $p0, implicit-def $lf0
  ; CHECK-NEXT:   renamable $p1 = KILL $p1, implicit-def $lf1
  ; CHECK-NEXT:   renamable $r1 = MOV_RLC_imm11_pseudo 780
  ; CHECK-NEXT:   LoopStart $r0, 0
  ; CHECK-NEXT:   renamable $r24 = MOV_RLC_imm11_pseudo 0
  ; CHECK-NEXT:   renamable $r25 = MOV_RLC_imm11_pseudo 0
  ; CHECK-NEXT:   renamable $dm2 = COPY $dm0
  ; CHECK-NEXT:   renamable $dm1 = COPY $dm0
  ; CHECK-NEXT:   renamable $dm4 = COPY $dm0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x7c000000), %bb.2(0x04000000)
  ; CHECK-NEXT:   liveins: $dm0, $dm1, $dm2, $dm4, $m1, $plfr0:0x0000000000484040, $plfr1:0x0000000000484040, $r1, $r4, $d0_3d:0x0003C00000200E00
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $p1, $lf1, $r25 = VLD_FILL_512_pseudo $p1, $lf1, $r25
  ; CHECK-NEXT:   $p1, $lf1, $r25 = VLD_FILL_512_pseudo $p1, $lf1, $r25
  ; CHECK-NEXT:   $p0, $lf0, $r24 = VLD_FILL_512_pseudo $p0, $lf0, $r24
  ; CHECK-NEXT:   $ex1, $p1, $lf1, $r25 = VLD_POP_576_normal_pop_pseudo $p1, $lf1, $r25, implicit-def $srfifo_uf
  ; CHECK-NEXT:   $ex3, $p1, $lf1, $r25, $dc0, $dc4 = VLD_POP_576_3D_pseudo $p1, $lf1, $r25, $d0_3d, implicit-def $srfifo_uf
  ; CHECK-NEXT:   $ex5, $p0, $lf0, $r24 = VLD_POP_576_normal_pop_pseudo $p0, $lf0, $r24, implicit-def $srfifo_uf
  ; CHECK-NEXT:   $ex7, $p0, $lf0, $r24 = VLD_POP_576_fifo_1d_pop_pseudo $p0, $lf0, $r24, $m1, implicit-def $srfifo_uf
  ; CHECK-NEXT:   renamable $ex9 = VSHUFFLE_vec_shuffle_ex renamable $ex1, renamable $ex3, renamable $r4
  ; CHECK-NEXT:   renamable $ex11 = VSHUFFLE_vec_shuffle_ex killed renamable $ex1, killed renamable $ex3, renamable $r4
  ; CHECK-NEXT:   renamable $dm4 = VMAC_f_vmac_bfp_vmul_bfp_core_EX_EX killed renamable $dm4, renamable $ex9, renamable $ex5, renamable $r1, implicit-def dead $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   renamable $dm0 = VMAC_f_vmac_bfp_vmul_bfp_core_EX_EX killed renamable $dm0, renamable $ex11, killed renamable $ex5, renamable $r1, implicit-def dead $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   renamable $dm1 = VMAC_f_vmac_bfp_vmul_bfp_core_EX_EX killed renamable $dm1, killed renamable $ex9, renamable $ex7, renamable $r1, implicit-def dead $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   renamable $dm2 = VMAC_f_vmac_bfp_vmul_bfp_core_EX_EX killed renamable $dm2, killed renamable $ex11, killed renamable $ex7, renamable $r1, implicit-def dead $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.1, implicit $ls, implicit $le
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   liveins: $dm0, $dm1, $dm2, $dm4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit killed renamable $dm2, implicit killed renamable $dm1, implicit killed renamable $dm0, implicit killed renamable $dm4
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $p0, $p1, $p2, $p3, $p4, $p5, $r0, $r1, $r2, $r3, $r4, $r5, $r6, $dm0, $d0_3d, $m1

    undef %193.sub_ptr:epsrfldf = COPY $p0
    undef %190.sub_ptr:epsrfldf = COPY $p1
    %17:em = COPY $m1
    %18:er = COPY $r4
    %156:eds = COPY $d0_3d
    %105:er = MOV_RLC_imm11_pseudo 780
    LoopStart $r0, 0
    %193.sub_avail:epsrfldf = MOV_RLC_imm11_pseudo 0
    %190.sub_avail:epsrfldf = MOV_RLC_imm11_pseudo 0
    %6:acc2048 = COPY $dm0
    %7:acc2048 = COPY $dm0
    %8:acc2048 = COPY $dm0
    %9:acc2048 = COPY $dm0

  bb.1:
    successors: %bb.1(0x7c000000), %bb.2(0x04000000)

    %190.sub_ptr:epsrfldf, %190.sub_fifo:epsrfldf, %190.sub_avail:epsrfldf = VLD_FILL_512_pseudo %190.sub_ptr, %190.sub_fifo, %190.sub_avail
    %190.sub_ptr:epsrfldf, %190.sub_fifo:epsrfldf, %190.sub_avail:epsrfldf = VLD_FILL_512_pseudo %190.sub_ptr, %190.sub_fifo, %190.sub_avail
    %193.sub_ptr:epsrfldf, %193.sub_fifo:epsrfldf, %193.sub_avail:epsrfldf = VLD_FILL_512_pseudo %193.sub_ptr, %193.sub_fifo, %193.sub_avail
    %150:vec576, %190.sub_ptr:epsrfldf, %190.sub_fifo:epsrfldf, %190.sub_avail:epsrfldf = VLD_POP_576_normal_pop_pseudo %190.sub_ptr, %190.sub_fifo, %190.sub_avail, implicit-def $srfifo_uf
    %151:vec576, %190.sub_ptr:epsrfldf, %190.sub_fifo:epsrfldf, %190.sub_avail:epsrfldf, %156.sub_dim_count:eds, %156.sub_hi_dim_then_sub_dim_count:eds = VLD_POP_576_3D_pseudo %190.sub_ptr, %190.sub_fifo, %190.sub_avail, %156, implicit-def $srfifo_uf
    %146:vec576, %193.sub_ptr:epsrfldf, %193.sub_fifo:epsrfldf, %193.sub_avail:epsrfldf = VLD_POP_576_normal_pop_pseudo %193.sub_ptr, %193.sub_fifo, %193.sub_avail, implicit-def $srfifo_uf
    %142:vec576, %193.sub_ptr:epsrfldf, %193.sub_fifo:epsrfldf, %193.sub_avail:epsrfldf = VLD_POP_576_fifo_1d_pop_pseudo %193.sub_ptr, %193.sub_fifo, %193.sub_avail, %17, implicit-def $srfifo_uf
    %145:vec576 = VSHUFFLE_vec_shuffle_ex %150, %151, %18
    %143:vec576 = VSHUFFLE_vec_shuffle_ex %150, %151, %18
    %9:acc2048 = VMAC_f_vmac_bfp_vmul_bfp_core_EX_EX %9, %145, %146, %105, implicit-def dead $srfpflags, implicit $crfpmask
    %8:acc2048 = VMAC_f_vmac_bfp_vmul_bfp_core_EX_EX %8, %143, %146, %105, implicit-def dead $srfpflags, implicit $crfpmask
    %7:acc2048 = VMAC_f_vmac_bfp_vmul_bfp_core_EX_EX %7, %145, %142, %105, implicit-def dead $srfpflags, implicit $crfpmask
    %6:acc2048 = VMAC_f_vmac_bfp_vmul_bfp_core_EX_EX %6, %143, %142, %105, implicit-def dead $srfpflags, implicit $crfpmask
    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.1, implicit $ls, implicit $le
    PseudoJ_jump_imm %bb.2

  bb.2:
    PseudoRET implicit $lr, implicit %6, implicit %7, implicit %8, implicit %9
...
