; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie < %s \
; RUN:   | FileCheck %s
; RUN: llc -mtriple=aie -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; Register-immediate instructions.

define i32 @addi(i32 %a) nounwind {




;




; CHECK-LABEL: addi:
; CHECK:       // %bb.0:
; CHECK-NEXT:    add r0, r6, #1
; CHECK:         ret lr
  %1 = add i32 %a, 1
  ret i32 %1
}

define i32 @slti(i32 %a) nounwind {




;





; CHECK-LABEL: slti:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov.u20 r12, #2
; CHECK-NEXT:    lt r0, r6, r12
; CHECK:         ret lr
  %1 = icmp slt i32 %a, 2
  %2 = zext i1 %1 to i32
  ret i32 %2
}

define i32 @sltiu(i32 %a) nounwind {




;





; CHECK-LABEL: sltiu:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov.u20 r12, #3
; CHECK-NEXT:    ltu r0, r6, r12
; CHECK:         ret lr
  %1 = icmp ult i32 %a, 3
  %2 = zext i1 %1 to i32
  ret i32 %2
}

define i32 @xori(i32 %a) nounwind {




;




; CHECK-LABEL: xori:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov.u20 r12, #4
; CHECK-NEXT:    xor r0, r6, r12
; CHECK:         ret lr
  %1 = xor i32 %a, 4
  ret i32 %1
}

define i32 @ori(i32 %a) nounwind {




;




; CHECK-LABEL: ori:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov.u20 r12, #5
; CHECK-NEXT:    or r0, r6, r12
; CHECK:         ret lr
  %1 = or i32 %a, 5
  ret i32 %1
}

define i32 @andi(i32 %a) nounwind {




;




; CHECK-LABEL: andi:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov.u20 r12, #6
; CHECK-NEXT:    and r0, r6, r12
; CHECK:         ret lr
  %1 = and i32 %a, 6
  ret i32 %1
}

define i32 @slli(i32 %a) nounwind {




;




; CHECK-LABEL: slli:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov.u20 r12, #7
; CHECK-NEXT:    lshl r0, r6, r12
; CHECK:         ret lr
  %1 = shl i32 %a, 7
  ret i32 %1
}

define i32 @srli(i32 %a) nounwind {
;
; CHECK-LABEL: srli:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.u20 r12, #8
; CHECK-NEXT:    mov.u20 r13, #0
; CHECK-NEXT:    sub r12, r13, r12
; CHECK-NEXT:    lshl r0, r6, r12
; CHECK:         ret lr
  %1 = lshr i32 %a, 8
  ret i32 %1
}

define i32 @srai(i32 %a) nounwind {
;
; CHECK-LABEL: srai:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.u20 r12, #9
; CHECK-NEXT:    mov.u20 r13, #0
; CHECK-NEXT:    sub r12, r13, r12
; CHECK-NEXT:    ashl r0, r6, r12
; CHECK:         ret lr
  %1 = ashr i32 %a, 9
  ret i32 %1
}

; Register-register instructions

define i32 @add(i32 %a, i32 %b) nounwind {




;




; CHECK-LABEL: add:
; CHECK:       // %bb.0:
; CHECK-NEXT:    add r0, r6, r7
; CHECK:         ret lr
  %1 = add i32 %a, %b
  ret i32 %1
}

define i32 @sub(i32 %a, i32 %b) nounwind {




;




; CHECK-LABEL: sub:
; CHECK:       // %bb.0:
; CHECK-NEXT:    sub r0, r6, r7
; CHECK:         ret lr
  %1 = sub i32 %a, %b
  ret i32 %1
}

define i32 @sll(i32 %a, i32 %b) nounwind {




;




; CHECK-LABEL: sll:
; CHECK:       // %bb.0:
; CHECK-NEXT:    lshl r0, r6, r7
; CHECK:         ret lr
  %1 = shl i32 %a, %b
  ret i32 %1
}

define i32 @slt(i32 %a, i32 %b) nounwind {




;






; CHECK-LABEL: slt:
; CHECK:       // %bb.0:
; CHECK-NEXT:    lt r0, r6, r7
; CHECK:         ret lr
  %1 = icmp slt i32 %a, %b
  %2 = zext i1 %1 to i32
  ret i32 %2
}

define i32 @sltu(i32 %a, i32 %b) nounwind {




;






; CHECK-LABEL: sltu:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ltu r0, r6, r7
; CHECK:         ret lr
  %1 = icmp ult i32 %a, %b
  %2 = zext i1 %1 to i32
  ret i32 %2
}

define i32 @xor(i32 %a, i32 %b) nounwind {




;




; CHECK-LABEL: xor:
; CHECK:       // %bb.0:
; CHECK-NEXT:    xor r0, r6, r7
; CHECK:         ret lr
  %1 = xor i32 %a, %b
  ret i32 %1
}

define i32 @srl(i32 %a, i32 %b) nounwind {
;
; CHECK-LABEL: srl:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.u20 r12, #0
; CHECK-NEXT:    sub r12, r12, r7
; CHECK-NEXT:    lshl r0, r6, r12
; CHECK:         ret lr
  %1 = lshr i32 %a, %b
  ret i32 %1
}

define i32 @sra(i32 %a, i32 %b) nounwind {
;
; CHECK-LABEL: sra:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.u20 r12, #0
; CHECK-NEXT:    sub r12, r12, r7
; CHECK-NEXT:    ashl r0, r6, r12
; CHECK:         ret lr
  %1 = ashr i32 %a, %b
  ret i32 %1
}

define i32 @or(i32 %a, i32 %b) nounwind {




;




; CHECK-LABEL: or:
; CHECK:       // %bb.0:
; CHECK-NEXT:    or r0, r6, r7
; CHECK:         ret lr
  %1 = or i32 %a, %b
  ret i32 %1
}

define i32 @and(i32 %a, i32 %b) nounwind {




;




; CHECK-LABEL: and:
; CHECK:       // %bb.0:
; CHECK-NEXT:    and r0, r6, r7
; CHECK:         ret lr
  %1 = and i32 %a, %b
  ret i32 %1
}
