; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie --issue-limit=1 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; These tests are identical to those in alu32.ll but operate on i8. They check
; that legalisation of these non-native types doesn't introduce unnecessary
; inefficiencies.

define signext i8 @addi(i8 signext %a) nounwind {
; CHECK-LABEL: addi:
; CHECK:       // %bb.0:
; CHECK-NEXT:    add r12, r6, #1
; CHECK-NEXT:    se.8 r0, r12
; CHECK:         ret lr
  %1 = add i8 %a, 1
  ret i8 %1
}

define signext i8 @slti(i8 signext %a) nounwind {
;
; CHECK-LABEL: slti:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov.u20 r12, #2
; CHECK-NEXT:    lt r0, r6, r12
; CHECK:         ret lr
  %1 = icmp slt i8 %a, 2
  %2 = zext i1 %1 to i8
  ret i8 %2
}

define signext i8 @sltiu(i8 zeroext %a) nounwind {
;
; CHECK-LABEL: sltiu:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov.u20 r12, #3
; CHECK-NEXT:    ltu r0, r6, r12
; CHECK:         ret lr
  %1 = icmp ult i8 %a, 3
  %2 = zext i1 %1 to i8
  ret i8 %2
}

define signext i8 @xori(i8 signext %a) nounwind {
;
; CHECK-LABEL: xori:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov.u20 r12, #4
; CHECK-NEXT:    xor r0, r6, r12
; CHECK:         ret lr
  %1 = xor i8 %a, 4
  ret i8 %1
}

define signext i8 @ori(i8 signext %a) nounwind {
;
; CHECK-LABEL: ori:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov.u20 r12, #5
; CHECK-NEXT:    or r0, r6, r12
; CHECK:         ret lr
  %1 = or i8 %a, 5
  ret i8 %1
}

define signext i8 @andi(i8 signext %a) nounwind {
;
; CHECK-LABEL: andi:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov.u20 r12, #6
; CHECK-NEXT:    and r0, r6, r12
; CHECK:         ret lr
  %1 = and i8 %a, 6
  ret i8 %1
}

define signext i8 @slli(i8 signext %a) nounwind {
;
; CHECK-LABEL: slli:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov.u20 r12, #7
; CHECK-NEXT:    lshl r12, r6, r12
; CHECK-NEXT:    se.8 r0, r12
; CHECK:         ret lr
  %1 = shl i8 %a, 7
  ret i8 %1
}

define signext i8 @srli(i8 signext %a) nounwind {
;
; CHECK-LABEL: srli:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.u20 r12, #6
; CHECK-NEXT:    mov.u20 r13, #0
; CHECK-NEXT:    sub r12, r13, r12
; CHECK-NEXT:    mov.u20 r13, #192
; CHECK-NEXT:    and r13, r6, r13
; CHECK-NEXT:    lshl r0, r13, r12
; CHECK-NEXT:    ret lr

  %1 = lshr i8 %a, 6
  ret i8 %1
}

define signext i8 @srai(i8 signext %a) nounwind {
;
; CHECK-LABEL: srai:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.u20 r12, #5
; CHECK-NEXT:    mov.u20 r13, #0
; CHECK-NEXT:    sub r12, r13, r12
; CHECK-NEXT:    ashl r0, r6, r12
; CHECK-NEXT:    ret lr

  %1 = ashr i8 %a, 5
  ret i8 %1
}


define signext i8 @add(i8 signext %a, i8 signext %b) nounwind {
;
; CHECK-LABEL: add:
; CHECK:       // %bb.0:
; CHECK-NEXT:    add r12, r6, r7
; CHECK-NEXT:    se.8 r0, r12
; CHECK:         ret lr
  %1 = add i8 %a, %b
  ret i8 %1
}

define signext i8 @sub(i8 signext %a, i8 signext %b) nounwind {
;
; CHECK-LABEL: sub:
; CHECK:       // %bb.0:
; CHECK-NEXT:    sub r12, r6, r7
; CHECK-NEXT:    se.8 r0, r12
; CHECK:         ret lr
  %1 = sub i8 %a, %b
  ret i8 %1
}

define signext i8 @sll(i8 signext %a, i8 signext %b) nounwind {
;
; CHECK-LABEL: sll:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ze.8 r12, r7
; CHECK-NEXT:    lshl r12, r6, r12
; CHECK-NEXT:    se.8 r0, r12
; CHECK:         ret lr
  %1 = shl i8 %a, %b
  ret i8 %1
}

define signext i8 @slt(i8 signext %a, i8 signext %b) nounwind {
;
; CHECK-LABEL: slt:
; CHECK:       // %bb.0:
; CHECK-NEXT:    lt r0, r6, r7
; CHECK:         ret lr
  %1 = icmp slt i8 %a, %b
  %2 = zext i1 %1 to i8
  ret i8 %2
}

define signext i8 @sltu(i8 signext %a, i8 signext %b) nounwind {
;
; CHECK-LABEL: sltu:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ltu r0, r6, r7
; CHECK:         ret lr
  %1 = icmp ult i8 %a, %b
  %2 = zext i1 %1 to i8
  ret i8 %2
}

define signext i8 @xor(i8 signext %a, i8 signext %b) nounwind {
;
; CHECK-LABEL: xor:
; CHECK:       // %bb.0:
; CHECK-NEXT:    xor r0, r6, r7
; CHECK:         ret lr
  %1 = xor i8 %a, %b
  ret i8 %1
}

define signext i8 @srl(i8 signext %a, i8 signext %b) nounwind {
;
; CHECK-LABEL: srl:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ze.8 r12, r7
; CHECK-NEXT:    mov.u20 r13, #0
; CHECK-NEXT:    sub r12, r13, r12
; CHECK-NEXT:    ze.8 r13, r6
; CHECK-NEXT:    lshl r12, r13, r12
; CHECK-NEXT:    se.8 r0, r12
; CHECK-NEXT:    ret lr

  %1 = lshr i8 %a, %b
  ret i8 %1
}

define signext i8 @sra(i8 signext %a, i8 signext %b) nounwind {
;
; CHECK-LABEL: sra:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ze.8 r12, r7
; CHECK-NEXT:    mov.u20 r13, #0
; CHECK-NEXT:    sub r12, r13, r12
; CHECK-NEXT:    ashl r0, r6, r12
; CHECK-NEXT:    ret lr

  %1 = ashr i8 %a, %b
  ret i8 %1
}

define signext i8 @or(i8 signext %a, i8 signext %b) nounwind {
;
; CHECK-LABEL: or:
; CHECK:       // %bb.0:
; CHECK-NEXT:    or r0, r6, r7
; CHECK:         ret lr
  %1 = or i8 %a, %b
  ret i8 %1
}

define signext i8 @and(i8 signext %a, i8 signext %b) nounwind {
;
; CHECK-LABEL: and:
; CHECK:       // %bb.0:
; CHECK-NEXT:    and r0, r6, r7
; CHECK:         ret lr
  %1 = and i8 %a, %b
  ret i8 %1
}
