; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie --stop-after=prologepilog < %s \
; RUN:   | FileCheck -check-prefix=FPELIM %s
; RUN: llc -mtriple=aie --stop-after=prologepilog -frame-pointer=all < %s \
; RUN:   | FileCheck -check-prefix=WITHFP %s


%struct.key_t = type { i32, [16 x i8] }

define i32 @test() nounwind {
;
;
  ; FPELIM-LABEL: name: test
  ; FPELIM: bb.0 (%ir-block.0):
  ; FPELIM-NEXT:   frame-setup PADDA_sp_imm 32, implicit-def $sp, implicit $sp
  ; FPELIM-NEXT:   renamable $cs0 = MOV_S12 16
  ; FPELIM-NEXT:   $r12 = MV_SPECIAL2R $sp
  ; FPELIM-NEXT:   $p0 = MOV killed $r12
  ; FPELIM-NEXT:   $p0 = PADDA_nrm_imm $p0, -32
  ; FPELIM-NEXT:   renamable $r0 = MOV_U20 0
  ; FPELIM-NEXT:   ST_idx_GPR renamable $r0, renamable $p0, killed renamable $cs0 :: (store (s32) into %ir.1 + 16)
  ; FPELIM-NEXT:   renamable $cs0 = MOV_S12 12
  ; FPELIM-NEXT:   ST_idx_GPR renamable $r0, renamable $p0, killed renamable $cs0 :: (store (s32) into %ir.1 + 12)
  ; FPELIM-NEXT:   renamable $cs0 = MOV_S12 8
  ; FPELIM-NEXT:   ST_idx_GPR renamable $r0, renamable $p0, killed renamable $cs0 :: (store (s32) into %ir.1 + 8)
  ; FPELIM-NEXT:   renamable $cs0 = MOV_S12 4
  ; FPELIM-NEXT:   ST_idx_GPR renamable $r0, killed renamable $p0, killed renamable $cs0 :: (store (s32) into %ir.1 + 4)
  ; FPELIM-NEXT:   ST_SPIL_GPR renamable $r0, -32, implicit $sp :: (store (s32) into %ir.1)
  ; FPELIM-NEXT:   frame-destroy PADDA_sp_imm -32, implicit-def $sp, implicit $sp
  ; FPELIM-NEXT:   PseudoRET implicit $lr, implicit $r0
  ; WITHFP-LABEL: name: test
  ; WITHFP: bb.0 (%ir-block.0):
  ; WITHFP-NEXT:   frame-setup PADDA_sp_imm 32, implicit-def $sp, implicit $sp
  ; WITHFP-NEXT:   $r12 = frame-setup MV_SPECIAL2R $sp
  ; WITHFP-NEXT:   $p7 = frame-setup MOV killed $r12
  ; WITHFP-NEXT:   $p7 = frame-setup PADDA_nrm_imm $p7, -32
  ; WITHFP-NEXT:   renamable $cs0 = MOV_S12 16
  ; WITHFP-NEXT:   $p0 = MOV $p7
  ; WITHFP-NEXT:   $p0 = PADDA_nrm_imm $p0, -32
  ; WITHFP-NEXT:   renamable $r0 = MOV_U20 0
  ; WITHFP-NEXT:   ST_idx_GPR renamable $r0, renamable $p0, killed renamable $cs0 :: (store (s32) into %ir.1 + 16)
  ; WITHFP-NEXT:   renamable $cs0 = MOV_S12 12
  ; WITHFP-NEXT:   ST_idx_GPR renamable $r0, renamable $p0, killed renamable $cs0 :: (store (s32) into %ir.1 + 12)
  ; WITHFP-NEXT:   renamable $cs0 = MOV_S12 8
  ; WITHFP-NEXT:   ST_idx_GPR renamable $r0, renamable $p0, killed renamable $cs0 :: (store (s32) into %ir.1 + 8)
  ; WITHFP-NEXT:   renamable $cs0 = MOV_S12 4
  ; WITHFP-NEXT:   ST_idx_GPR renamable $r0, killed renamable $p0, killed renamable $cs0 :: (store (s32) into %ir.1 + 4)
  ; WITHFP-NEXT:   ST_SPIL_GPR renamable $r0, -32, implicit $sp :: (store (s32) into %ir.1)
  ; WITHFP-NEXT:   frame-destroy PADDA_sp_imm -32, implicit-def $sp, implicit $sp
  ; WITHFP-NEXT:   PseudoRET implicit $lr, implicit $r0
  %key = alloca %struct.key_t, align 4
  %1 = bitcast %struct.key_t* %key to i8*
  call void @llvm.memset.p0i8.i64(i8* align 4 %1, i8 0, i64 20, i1 false)
;  %2 = getelementptr inbounds %struct.key_t, %struct.key_t* %key, i64 0, i32 1, i64 0
;  call void @test1(i8* %2) #3
  ret i32 0
}

declare void @llvm.memset.p0i8.i64(i8* nocapture, i8, i64, i1)

declare void @test1(i8*)
