# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie -run-pass postrapseudos -verify-machineinstrs -o - %s | FileCheck %s

# Verify AIEInstrInfo.cpp: copyPhysReg()
---
name:            run_physreg_copies
body: |
  bb.0:
    ; CHECK-LABEL: name: run_physreg_copies
    ; CHECK: $p0 = MOV $p1
    ; CHECK-NEXT: $r15 = MV_SPECIAL2R $sp
    ; CHECK-NEXT: $p0 = MOV $r15
    ; CHECK-NEXT: $r15 = MOV $p2
    ; CHECK-NEXT: $sp = MV_R2SPECIAL $r15
    ; CHECK-NEXT: $p0 = MOV $m0
    ; CHECK-NEXT: $p0 = MOV $cs0
    ; CHECK-NEXT: $r7 = MV_SPECIAL2R $sp
    ; CHECK-NEXT: $sp = MV_R2SPECIAL $r7
    ; CHECK-NEXT: $r7 = MOV $cl0
    ; CHECK-NEXT: $cl0 = MOV $r8
    ; CHECK-NEXT: $r15 = MV_SPECIAL2R $sp
    ; CHECK-NEXT: $lr = MV_R2SPECIAL $r15
    ; CHECK-NEXT: $r15 = MV_SPECIAL2R $lr
    ; CHECK-NEXT: $sp = MV_R2SPECIAL $r15
    ; CHECK-NEXT: $r15 = MV_SPECIAL2R $mc1
    ; CHECK-NEXT: $md0 = MV_R2SPECIAL $r15
    ; CHECK-NEXT: $vl1 = MV_V $vl0
    ; CHECK-NEXT: $wr1 = MV_W $wr0
    ; CHECK-NEXT: $xb = MV_X $xa
    ; CHECK-NEXT: $xd = MV_X $xa
    ; CHECK-NEXT: $r8 = S2V_EXT_R32 killed $vl0, 0
    ; CHECK-NEXT: $wr0 = S2V_SHIFTW0_R32 undef $wr0, $r8
    ; CHECK-NEXT: $r15 = S2V_EXT_R32 killed $vl0, 0
    ; CHECK-NEXT: $cl0 = MOV $r15
    ; CHECK-NEXT: $r15 = MOV $cl1
    ; CHECK-NEXT: $wr0 = S2V_SHIFTW0_R32 undef $wr0, $r15
    ; CHECK-NEXT: $aml0 = ACCUMULATOR_MOVE $amh0
    $p0 = COPY $p1
    $p0 = COPY $sp
    $sp = COPY $p2
    $p0 = COPY $m0
    $p0 = COPY $cs0
    $r7 = COPY $sp
    $sp = COPY $r7
    $r7 = COPY $cl0
    $cl0 = COPY $r8
    $lr = COPY $sp
    $sp = COPY $lr
    $md0 = COPY $mc1
    $vl1 = COPY $vl0
    $wr1 = COPY $wr0
    $xb = COPY $xa
    $yd = COPY $ya
    $r8 = COPY $wr0
    $wr0 = COPY $r8
    $cl0 = COPY $wr0
    $wr0 = COPY $cl1
    $aml0 = COPY $amh0

...
