; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2023-2026 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie < %s | FileCheck %s

; These tests check that we can spill vector registers in a reasonable way.
; These spills are awkward, since they require multiple small spills to complete.
; Calling this function can overwrite any vector register, so
; induces a spill of the vector register to get to the return value.
declare i32 @external_func(i32) nounwind

define i64 @test_i64(i32 %a, i64 %d) nounwind {
; CHECK-LABEL: test_i64:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    padda [sp], #32
; CHECK-NEXT:    nop
; CHECK-NEXT:    st.spil r10, [sp, #-28] // 4-byte Folded Spill
; CHECK-NEXT:    st.spil r11, [sp, #-24] // 4-byte Folded Spill
; CHECK-NEXT:    st.spil lr, [sp, #-32] // 4-byte Folded Spill
; CHECK-NEXT:    mov r10, r8
; CHECK-NEXT:    mov r11, r7
; CHECK-NEXT:    jal external_func
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
; CHECK-NEXT:    nop ; ldb lr, [sp, #-32]; mov r0, r11 // 4-byte Folded Reload
; CHECK-NEXT:    mov r1, r10
; CHECK-NEXT:    lda.spil r11, [sp, #-24] // 4-byte Folded Reload
; CHECK-NEXT:    lda.spil r10, [sp, #-28] // 4-byte Folded Reload
; CHECK-NEXT:    padda [sp], #-32
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
  %1 = call i32 @external_func(i32 %a)
  ret i64 %d
}

define <4 x i32> @test_128vec(i32 %a, <4 x i32> %d) nounwind {
; CHECK-LABEL: test_128vec:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    padda [sp], #32
; CHECK-NEXT:    nop
; CHECK-NEXT:    st.spil lr, [sp, #-16] // 4-byte Folded Spill
; CHECK-NEXT:    vst.spil vl0, [sp, #-32] // 16-byte Folded Spill
; CHECK-NEXT:    jal external_func
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
; CHECK-NEXT:    vlda.spil vl0, [sp, #-32] // 16-byte Folded Reload
; CHECK-NEXT:    padda [sp], #-32; ldb lr, [sp, #-16]; nop // 4-byte Folded Reload
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
  %1 = call i32 @external_func(i32 %a)
  ret <4 x i32> %d
}

define <8 x i32> @test_256vec(i32 %a, <8 x i32> %d) nounwind {
; CHECK-LABEL: test_256vec:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    padda [sp], #64
; CHECK-NEXT:    nop
; CHECK-NEXT:    st.spil lr, [sp, #-32] // 4-byte Folded Spill
; CHECK-NEXT:    vst.spil wr0, [sp, #-64] // 32-byte Folded Spill
; CHECK-NEXT:    jal external_func
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
; CHECK-NEXT:    vlda.spil wr0, [sp, #-64] // 32-byte Folded Reload
; CHECK-NEXT:    padda [sp], #-64; ldb lr, [sp, #-32]; nop // 4-byte Folded Reload
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
  %1 = call i32 @external_func(i32 %a)
  ret <8 x i32> %d
}

define <16 x i32> @test_512vec(i32 %a, <16 x i32> %d) nounwind {
; CHECK-LABEL: test_512vec:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    padda [sp], #128
; CHECK-NEXT:    nop
; CHECK-NEXT:    st.spil lr, [sp, #-64] // 4-byte Folded Spill
; CHECK-NEXT:    vst.spil wr0, [sp, #-128] // 32-byte Folded Spill
; CHECK-NEXT:    vst.spil wr1, [sp, #-96] // 32-byte Folded Spill
; CHECK-NEXT:    jal external_func
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
; CHECK-NEXT:    vlda.spil wr0, [sp, #-128] // 32-byte Folded Reload
; CHECK-NEXT:    vlda.spil wr1, [sp, #-96] // 32-byte Folded Reload
; CHECK-NEXT:    padda [sp], #-128; ldb lr, [sp, #-64]; nop // 4-byte Folded Reload
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
  %1 = call i32 @external_func(i32 %a)
  ret <16 x i32> %d
}

define <32 x i32> @test_1024vec(i32 %a, <32 x i32> %d) nounwind {
; CHECK-LABEL: test_1024vec:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    padda [sp], #256
; CHECK-NEXT:    nop
; CHECK-NEXT:    st.spil lr, [sp, #-128] // 4-byte Folded Spill
; CHECK-NEXT:    vst.spil wr0, [sp, #-256] // 32-byte Folded Spill
; CHECK-NEXT:    vst.spil wr1, [sp, #-224] // 32-byte Folded Spill
; CHECK-NEXT:    vst.spil wr2, [sp, #-192] // 32-byte Folded Spill
; CHECK-NEXT:    vst.spil wr3, [sp, #-160] // 32-byte Folded Spill
; CHECK-NEXT:    jal external_func
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
; CHECK-NEXT:    vlda.spil wr0, [sp, #-256] // 32-byte Folded Reload
; CHECK-NEXT:    vlda.spil wr1, [sp, #-224] // 32-byte Folded Reload
; CHECK-NEXT:    vlda.spil wr2, [sp, #-192] // 32-byte Folded Reload
; CHECK-NEXT:    vlda.spil wr3, [sp, #-160] // 32-byte Folded Reload
; CHECK-NEXT:    padda [sp], #-256; ldb lr, [sp, #-128]; nop // 4-byte Folded Reload
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
  %1 = call i32 @external_func(i32 %a)
  ret <32 x i32> %d
}
