; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

define i32 @zext_i8(i32 %a) {
; CHECK-LABEL: zext_i8:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ze.8 r0, r6
; CHECK-NEXT:    ret lr
    %res = and i32 %a, 255
    ret i32 %res
}

define i32 @zext_i8_minus_1(i32 %a) {
; CHECK-LABEL: zext_i8_minus_1:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.u20 r12, #254
; CHECK-NEXT:    and r0, r6, r12
; CHECK-NEXT:    ret lr
    %res = and i32 %a, 254
    ret i32 %res
}

define i32 @zext_i8_plus_1(i32 %a) {
; CHECK-LABEL: zext_i8_plus_1:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.u20 r12, #256
; CHECK-NEXT:    and r0, r6, r12
; CHECK-NEXT:    ret lr
    %res = and i32 %a, 256
    ret i32 %res
}


define i32 @zext_i16(i32 %a) {
; CHECK-LABEL: zext_i16:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ze.16 r0, r6
; CHECK-NEXT:    ret lr
    %res = and i32 %a, 65535
    ret i32 %res
}

define i32 @zext_i16_minus_1(i32 %a) {
; CHECK-LABEL: zext_i16_minus_1:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.u20 r12, #65534
; CHECK-NEXT:    and r0, r6, r12
; CHECK-NEXT:    ret lr
    %res = and i32 %a, 65534
    ret i32 %res
}

define i32 @zext_i16_plus_1(i32 %a) {
; CHECK-LABEL: zext_i16_plus_1:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.u20 r12, #65536
; CHECK-NEXT:    and r0, r6, r12
; CHECK-NEXT:    ret lr
    %res = and i32 %a, 65536
    ret i32 %res
}
