// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
//===- aie2-undef-accumulator-float.cpp -------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//
// RUN: %clang -O2 %s --target=aie2 -S -emit-llvm -o - | FileCheck %s

// CHECK-LABEL: @_Z21test_undef_v8accfloatv(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <4 x i64> @llvm.aie2.v8accfloat()
// CHECK-NEXT:    ret <4 x i64> [[TMP0]]
//
v8accfloat test_undef_v8accfloat()
{
  return undef_v8accfloat();
}

// CHECK-LABEL: @_Z22test_undef_v16accfloatv(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i64> @llvm.aie2.v16accfloat()
// CHECK-NEXT:    ret <8 x i64> [[TMP0]]
//
v16accfloat test_undef_v16accfloat()
{
  return undef_v16accfloat();
}

// CHECK-LABEL: @_Z22test_undef_v32accfloatv(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i64> @llvm.aie2.v32accfloat()
// CHECK-NEXT:    ret <16 x i64> [[TMP0]]
//
v32accfloat test_undef_v32accfloat()
{
  return undef_v32accfloat();
}
