// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
//===- aie2-intrinsics.c ----------------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//
// RUN: %clang -O0 %s --target=aie2 -S -emit-llvm -o - | FileCheck %s
// CHECK-LABEL: @events(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.aie2.event(i32 0)
// CHECK-NEXT:    call void @llvm.aie2.event(i32 1)
// CHECK-NEXT:    call void @llvm.aie2.event(i32 2)
// CHECK-NEXT:    call void @llvm.aie2.event(i32 3)
// CHECK-NEXT:    ret void
//
void events() {
  event0();
  event1();
  event_warning();
  event_error();
}
