// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --function-signature --return-type --skip-function-body
//===- aie2-abi-accumulator.cpp ---------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//
// RUN: %clang --target=aie2 -nostdlibinc -S -emit-llvm %s -o - | FileCheck %s

#include <stdint.h>

extern "C" {

/****** accumulator vector ******/

// CHECK-LABEL: define {{[^@]*}}<4 x i64> @ret_v8acc32
// CHECK-SAME: () #[[ATTR0:[0-9]+]] {
v8acc32 ret_v8acc32(void) {
  volatile v8acc32 ret;
  return ret;
}
// CHECK-LABEL: define {{[^@]*}}void @pass_v8acc32
// CHECK-SAME: (<4 x i64> noundef [[TMP0:%.*]]) #[[ATTR0:[0-9]+]] {
void pass_v8acc32(v8acc32) {}

// CHECK-LABEL: define {{[^@]*}}<8 x i64> @ret_v16acc32
// CHECK-SAME: () #[[ATTR0:[0-9]+]] {
v16acc32 ret_v16acc32(void) {
  volatile v16acc32 ret;
  return ret;
}
// CHECK-LABEL: define {{[^@]*}}void @pass_v16acc32
// CHECK-SAME: (<8 x i64> noundef [[TMP0:%.*]]) #[[ATTR0:[0-9]+]] {
void pass_v16acc32(v16acc32) {}

// CHECK-LABEL: define {{[^@]*}}<16 x i64> @ret_v32acc32
// CHECK-SAME: () #[[ATTR0:[0-9]+]] {
v32acc32 ret_v32acc32(void) {
  volatile v32acc32 ret;
  return ret;
}
// CHECK-LABEL: define {{[^@]*}}void @pass_v32acc32
// CHECK-SAME: (<16 x i64> noundef [[TMP0:%.*]]) #[[ATTR0:[0-9]+]] {
void pass_v32acc32(v32acc32) {}

// CHECK-LABEL: define {{[^@]*}}<4 x i64> @ret_v4acc64
// CHECK-SAME: () #[[ATTR0:[0-9]+]] {
v4acc64 ret_v4acc64(void) {
  volatile v4acc64 ret;
  return ret;
}
// CHECK-LABEL: define {{[^@]*}}void @pass_v4acc64
// CHECK-SAME: (<4 x i64> noundef [[TMP0:%.*]]) #[[ATTR0:[0-9]+]] {
void pass_v4acc64(v4acc64) {}

// CHECK-LABEL: define {{[^@]*}}<8 x i64> @ret_v8acc64
// CHECK-SAME: () #[[ATTR0:[0-9]+]] {
v8acc64 ret_v8acc64(void) {
  volatile v8acc64 ret;
  return ret;
}
// CHECK-LABEL: define {{[^@]*}}void @pass_v8acc64
// CHECK-SAME: (<8 x i64> noundef [[TMP0:%.*]]) #[[ATTR0:[0-9]+]] {
void pass_v8acc64(v8acc64) {}

// CHECK-LABEL: define {{[^@]*}}<16 x i64> @ret_v16acc64
// CHECK-SAME: () #[[ATTR0:[0-9]+]] {
v16acc64 ret_v16acc64(void) {
  volatile v16acc64 ret;
  return ret;
}
// CHECK-LABEL: define {{[^@]*}}void @pass_v16acc64
// CHECK-SAME: (<16 x i64> noundef [[TMP0:%.*]]) #[[ATTR0:[0-9]+]] {
void pass_v16acc64(v16acc64) {}
}
