// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 4

//===- aie2-scl2vec-intrinsic.cpp ---------------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//

// RUN: %clang -O1 %s --target=aie2 -nostdlibinc -S -emit-llvm -o - | FileCheck %s -check-prefix=AIE2


// AIE2-LABEL: define dso_local noundef <16 x i32> @_Z18test_broadcast_s64x(
// AIE2-SAME: i64 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast i64 [[B]] to <2 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast64.I512(<2 x i32> [[TMP0]])
// AIE2-NEXT:    ret <16 x i32> [[TMP1]]
//
v16int32 test_broadcast_s64 (long long b) {
   return  broadcast_s64(b);
}

// AIE2-LABEL: define dso_local noundef <16 x i32> @_Z27test_broadcast_to_v16uint32y(
// AIE2-SAME: i64 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast i64 [[B]] to <2 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbroadcast64.I512(<2 x i32> [[TMP0]])
// AIE2-NEXT:    ret <16 x i32> [[TMP1]]
//
v16uint32 test_broadcast_to_v16uint32(unsigned long long b) {
  return broadcast_to_v16uint32(b);
}

// AIE2-LABEL: define dso_local noundef <16 x i64> @_Z31test_broadcast_zero_to_v32acc32v(
// AIE2-SAME: ) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i64> @llvm.aie2.vbroadcast.zero.acc1024()
// AIE2-NEXT:    ret <16 x i64> [[TMP0]]
//
v32acc32 test_broadcast_zero_to_v32acc32 () {
   return broadcast_zero_to_v32acc32();
}

// AIE2-LABEL: define dso_local noundef i64 @_Z12test_ext_u64Dv64_DU8_ii(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.aie2.vextract.elem64.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[SIGN]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to i64
// AIE2-NEXT:    ret i64 [[TMP2]]
//
unsigned long long test_ext_u64(v128uint4 v, int idx, int sign) {
  return (unsigned long long)(ext_u64(v, idx, sign));
}


// AIE2-LABEL: define dso_local noundef i64 @_Z12test_ext_u64Dv64_hii(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.aie2.vextract.elem64.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[SIGN]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to i64
// AIE2-NEXT:    ret i64 [[TMP2]]
//
unsigned long long test_ext_u64(v64uint8 v, int idx, int sign) {
  return (unsigned long long)(ext_u64(v, idx, sign));
}


// AIE2-LABEL: define dso_local noundef i64 @_Z12test_ext_u64Dv32_sii(
// AIE2-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.aie2.vextract.elem64.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[SIGN]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to i64
// AIE2-NEXT:    ret i64 [[TMP2]]
//
unsigned long long test_ext_u64(v32int16 v, int idx, int sign) {
  return (unsigned long long)(ext_u64(v, idx, sign));
}


// AIE2-LABEL: define dso_local noundef i64 @_Z12test_ext_u64Dv16_iii(
// AIE2-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.aie2.vextract.elem64.I512(<16 x i32> [[V]], i32 [[IDX]], i32 [[SIGN]])
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[TMP0]] to i64
// AIE2-NEXT:    ret i64 [[TMP1]]
//
unsigned long long test_ext_u64(v16int32 v, int idx, int sign) {
  return (unsigned long long)(ext_u64(v, idx, sign));
}

// AIE2-LABEL: define dso_local noundef i64 @_Z12test_ext_u64Dv32_8bfloat16ii(
// AIE2-SAME: <32 x bfloat> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <32 x bfloat> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.aie2.vextract.elem64.I512(<16 x i32> [[TMP0]], i32 [[IDX]], i32 [[SIGN]])
// AIE2-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to i64
// AIE2-NEXT:    ret i64 [[TMP2]]
//
unsigned long long test_ext_u64(v32bfloat16 v, int idx, int sign) {
  return ext_u64(v, idx, sign);
}


// AIE2-LABEL: define dso_local noundef <16 x i32> @_Z16test_shuffle_s64Dv2_ij(
// AIE2-SAME: <2 x i32> noundef [[B:%.*]], i32 noundef [[M:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbcst.shuffle64(<2 x i32> [[B]], i32 [[M]])
// AIE2-NEXT:    ret <16 x i32> [[TMP0]]
//
v16int32 test_shuffle_s64 (v2int32 b, unsigned int m) {
   return shuffle_v2s32(b,m);
}

// AIE2-LABEL: define dso_local noundef <16 x i32> @_Z16test_shuffle_s64xj(
// AIE2-SAME: i64 noundef [[B:%.*]], i32 noundef [[M:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast i64 [[B]] to <2 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vbcst.shuffle64(<2 x i32> [[TMP0]], i32 [[M]])
// AIE2-NEXT:    ret <16 x i32> [[TMP1]]
//
v16int32 test_shuffle_s64(long long b, unsigned int m) {
  return shuffle_s64(b, m);
}

// AIE2-LABEL: define dso_local noundef <16 x i32> @_Z11test_insertDv16_iiy(
// AIE2-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i64 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast i64 [[B]] to <2 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2.vinsert64.I512(<16 x i32> [[V]], i32 [[IDX]], <2 x i32> [[TMP0]])
// AIE2-NEXT:    ret <16 x i32> [[TMP1]]
//
v16int32 test_insert(v16int32 v, int idx, unsigned long long b) {
  return insert(v, idx, b);
}

// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_DU8_iy(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i64 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast i64 [[B]] to <2 x i32>
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert64.I512(<16 x i32> [[TMP0]], i32 [[IDX]], <2 x i32> [[TMP1]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP3]]
//
v128uint4 test_insert(v128uint4 v, int idx, unsigned long long b) {
  return insert(v, idx, b);
}

// AIE2-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_hiy(
// AIE2-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i64 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast i64 [[B]] to <2 x i32>
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert64.I512(<16 x i32> [[TMP0]], i32 [[IDX]], <2 x i32> [[TMP1]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <64 x i8>
// AIE2-NEXT:    ret <64 x i8> [[TMP3]]
//
v64uint8 test_insert(v64uint8 v, int idx, unsigned long long b) {
  return insert(v, idx, b);
}

//
// AIE2-LABEL: define dso_local noundef <32 x i16> @_Z11test_insertDv32_tiy(
// AIE2-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i64 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2-NEXT:  entry:
// AIE2-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[V]] to <16 x i32>
// AIE2-NEXT:    [[TMP1:%.*]] = bitcast i64 [[B]] to <2 x i32>
// AIE2-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vinsert64.I512(<16 x i32> [[TMP0]], i32 [[IDX]], <2 x i32> [[TMP1]])
// AIE2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i32> [[TMP2]] to <32 x i16>
// AIE2-NEXT:    ret <32 x i16> [[TMP3]]
//
v32uint16 test_insert(v32uint16 v, int idx, unsigned long long b) {
  return insert(v, idx, b);
}
