// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 4
//===- aie2-demangle-bf16.cpp -----------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//
// RUN: %clang -O0 --target=aie2-none-unknown-elf -S -emit-llvm -o - %s | llvm-cxxfilt | FileCheck %s


void foo(__bf16 &b);
void foo(v2bfloat16 &b);
void foo(v4bfloat16 &b);
void foo(v8bfloat16 &b);
void foo(v16bfloat16 &b);
void foo(v32bfloat16 &b);
void foo(v64bfloat16 &b);

struct bar {};

void foo (__bf16, bar &, bar &);

// CHECK-LABEL: define dso_local noundef i32 @main(
// CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A:%.*]] = alloca bfloat, align 2
// CHECK-NEXT:    [[B:%.*]] = alloca <2 x bfloat>, align 4
// CHECK-NEXT:    [[C:%.*]] = alloca <4 x bfloat>, align 8
// CHECK-NEXT:    [[D:%.*]] = alloca <8 x bfloat>, align 16
// CHECK-NEXT:    [[E:%.*]] = alloca <16 x bfloat>, align 32
// CHECK-NEXT:    [[F:%.*]] = alloca <32 x bfloat>, align 32
// CHECK-NEXT:    [[G:%.*]] = alloca <64 x bfloat>, align 32
// CHECK-NEXT:    [[BAR:%.*]] = alloca [[STRUCT_BAR:%.*]], align 1
// CHECK-NEXT:    store i32 0, ptr [[RETVAL]], align 4
// CHECK-NEXT:    call void @foo(bfloat16&)(ptr nonnull align 2 dereferenceable(2) [[A]])
// CHECK-NEXT:    call void @foo(bfloat16 vector[2]&)(ptr nonnull align 4 dereferenceable(4) [[B]])
// CHECK-NEXT:    call void @foo(bfloat16 vector[4]&)(ptr nonnull align 8 dereferenceable(8) [[C]])
// CHECK-NEXT:    call void @foo(bfloat16 vector[8]&)(ptr nonnull align 16 dereferenceable(16) [[D]])
// CHECK-NEXT:    call void @foo(bfloat16 vector[16]&)(ptr nonnull align 32 dereferenceable(32) [[E]])
// CHECK-NEXT:    call void @foo(bfloat16 vector[32]&)(ptr nonnull align 32 dereferenceable(64) [[F]])
// CHECK-NEXT:    call void @foo(bfloat16 vector[64]&)(ptr nonnull align 32 dereferenceable(128) [[G]])
// CHECK-NEXT:    [[TMP0:%.*]] = load bfloat, ptr [[A]], align 2
// CHECK-NEXT:    call void @foo(bfloat16, bar&, bar&)(bfloat noundef [[TMP0]], ptr nonnull align 1 dereferenceable(1) [[BAR]], ptr nonnull align 1 dereferenceable(1) [[BAR]])
// CHECK-NEXT:    ret i32 0
//
int main() {
    __bf16 a;
    v2bfloat16 b;
    v4bfloat16 c;
    v8bfloat16 d;
    v16bfloat16 e;
    v32bfloat16 f;
    v64bfloat16 g;

    foo(a);
    foo(b);
    foo(c);
    foo(d);
    foo(e);
    foo(f);
    foo(g);
    bar BAR;
    foo(a, BAR, BAR);
    return 0;
}
