// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
//===- aie2-undef-bfloat.cpp ------------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//
// RUN: %clang -O2 %s --target=aie2 -S -emit-llvm -o - | FileCheck %s

// CHECK-LABEL: @_Z21test_undef_v8bfloat16v(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x bfloat> @llvm.aie2.v8bfloat16()
// CHECK-NEXT:    ret <8 x bfloat> [[TMP0]]
//
v8bfloat16 test_undef_v8bfloat16() {
  return undef_v8bfloat16();
}

// CHECK-LABEL: @_Z22test_undef_v16bfloat16v(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2.v16bfloat16()
// CHECK-NEXT:    ret <16 x bfloat> [[TMP0]]
//
v16bfloat16 test_undef_v16bfloat16() {
  return undef_v16bfloat16();
}

// CHECK-LABEL: @_Z22test_undef_v32bfloat16v(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2.v32bfloat16()
// CHECK-NEXT:    ret <32 x bfloat> [[TMP0]]
//
v32bfloat16 test_undef_v32bfloat16() {
  return undef_v32bfloat16();
}

// CHECK-LABEL: @_Z22test_undef_v64bfloat16v(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x bfloat> @llvm.aie2.v64bfloat16()
// CHECK-NEXT:    ret <64 x bfloat> [[TMP0]]
//
v64bfloat16 test_undef_v64bfloat16() {
  return undef_v64bfloat16();
}
