# NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc --mtriple=aie2p -O2 --start-before=postmisched \
# RUN:   --aie-loop-min-tripcount=15 %s -o - | FileCheck %s

# Test that FILL pseudo instructions from different FIFO streams get
# separated into different load slots when memory bank info is unavailable.
# Extracted from GEMM_Bf16xbfp16_0 kernel inner loop (for.body.i22.i.i).
#
# The loop has FILL/POP instructions on two streams (p0/lf0 and p1/lf1)
# without address space info, plus fixed VLDA bm-loads creating slot
# pressure. Without fill stream separation, the greedy materializer
# puts both streams on the same slot, increasing loop II from 10 to 12+.

--- |
  define dso_local void @fill_stream_separation(ptr noalias %pA, ptr noalias %pB, ptr noalias %psum_ld, ptr noalias %psum_st, i32 %n) {
  ; CHECK-LABEL: fill_stream_separation:
  ; CHECK:         .p2align 4
  ; CHECK-NEXT:  // %bb.0:
  ; CHECK-NEXT:    mova r1, #0; nopb ; nops ; nopxm ; nopv
  ; CHECK-NEXT:    nopa ; ge r1, r1, r0
  ; CHECK-NEXT:    jnz r1, #.LBB0_4
  ; CHECK-NEXT:    nop // Delay Slot 5
  ; CHECK-NEXT:    nop // Delay Slot 4
  ; CHECK-NEXT:    nop // Delay Slot 3
  ; CHECK-NEXT:    nop // Delay Slot 2
  ; CHECK-NEXT:    nop // Delay Slot 1
  ; CHECK-NEXT:  // %bb.1:
  ; CHECK-NEXT:    vlda.fill.512 [p1, lf1, r25]; vldb.fill.512 [p0, lf0, r24]
  ; CHECK-NEXT:    vlda bmhh0, [p7, #192]; vldb.pop.576 ex3, [p1, lf1, r25]
  ; CHECK-NEXT:    vlda bmhl0, [p7, #128]; vldb.pop.576 ex6, [p1, lf1, r25]
  ; CHECK-NEXT:    vlda bmlh0, [p7, #64]; vldb.pop.576 ex11, [p1, lf1, r25]
  ; CHECK-NEXT:    vlda.2d bmll0, [p7], d2; vldb.pop.576 ex10, [p0, lf0, r24]
  ; CHECK-NEXT:    vlda bmhh2, [p7, #192]; vldb.pop.576 ex4, [p1, lf1, r25]
  ; CHECK-NEXT:    vlda bmhl2, [p7, #128]; vldb.pop.576 ex1, [p1, lf1, r25]
  ; CHECK-NEXT:    vlda.pop.576 ex1, [p1, lf1, r25]; vldb.pop.576 ex8, [p0, lf0, r24]
  ; CHECK-NEXT:    vlda bmlh2, [p7, #64]; vldb.pop.576 ex6, [p0, lf0, r24]
  ; CHECK-NEXT:    vlda.2d bmll2, [p7], d2; vldb.pop.576 ex10, [p1, lf1, r25]
  ; CHECK-NEXT:    vlda.pop.576.2d ex1, [p1, lf1, r25, d3]; vldb.pop.576.2d ex8, [p0, lf0, r24, d1]
  ; CHECK-NEXT:    vlda.fill.512 [p1, lf1, r25]; vldb.fill.512 [p0, lf0, r24]
  ; CHECK-NEXT:    vlda bmhh0, [p7, #192]; vldb.pop.576 ex3, [p1, lf1, r25]; vmac.f dm4, dm0, ex10, ex3, r2
  ; CHECK-NEXT:    vlda bmhl0, [p7, #128]; vldb.pop.576 ex6, [p1, lf1, r25]
  ; CHECK-NEXT:    vlda bmlh0, [p7, #64]; vldb.pop.576 ex11, [p1, lf1, r25]; vmac.f dm2, dm2, ex10, ex1, r2
  ; CHECK-NEXT:    vlda.2d bmll0, [p7], d2; vldb.pop.576 ex10, [p0, lf0, r24]; vmac.f dm3, dm4, ex8, ex6, r2
  ; CHECK-NEXT:    vlda bmhh2, [p7, #192]; vldb.pop.576 ex4, [p1, lf1, r25]
  ; CHECK-NEXT:    vlda bmhl2, [p7, #128]; vldb.pop.576 ex1, [p1, lf1, r25]; vmac.f dm3, dm2, ex8, ex1, r2
  ; CHECK-NEXT:    vlda.pop.576 ex1, [p1, lf1, r25]; vldb.pop.576 ex8, [p0, lf0, r24]; vmac.f dm1, dm3, ex6, ex11, r2
  ; CHECK-NEXT:    vlda bmlh2, [p7, #64]; vldb.pop.576 ex6, [p0, lf0, r24]
  ; CHECK-NEXT:    vlda.2d bmll2, [p7], d2; vldb.pop.576 ex10, [p1, lf1, r25]; vmac.f dm1, dm3, ex6, ex10, r2
  ; CHECK-NEXT:    vlda.pop.576.2d ex1, [p1, lf1, r25, d3]; vldb.pop.576.2d ex8, [p0, lf0, r24, d1]; vmac.f dm3, dm1, ex8, ex4, r2
  ; CHECK-NEXT:    vlda.fill.512 [p1, lf1, r25]; vldb.fill.512 [p0, lf0, r24]
  ; CHECK-NEXT:    vlda bmhh0, [p7, #192]; vldb.pop.576 ex3, [p1, lf1, r25]; vmac.f dm4, dm0, ex10, ex3, r2
  ; CHECK-NEXT:    vlda bmhl0, [p7, #128]; vldb.pop.576 ex6, [p1, lf1, r25]; vmac.f dm1, dm1, ex8, ex1, r2
  ; CHECK-NEXT:    vlda bmlh0, [p7, #64]; vldb.pop.576 ex11, [p1, lf1, r25]; vmac.f dm2, dm2, ex10, ex1, r2
  ; CHECK-NEXT:    vlda.2d bmll0, [p7], d2; vldb.pop.576 ex10, [p0, lf0, r24]; vmac.f dm3, dm4, ex8, ex6, r2
  ; CHECK-NEXT:    vlda bmhh2, [p7, #192]; vldb.pop.576 ex4, [p1, lf1, r25]; vst bmhh3, [p3, #192]
  ; CHECK-NEXT:    vlda bmhl2, [p7, #128]; vldb.pop.576 ex1, [p1, lf1, r25]; vst bmhl3, [p3, #128]; vmac.f dm3, dm2, ex8, ex1, r2
  ; CHECK-NEXT:    vlda.pop.576 ex1, [p1, lf1, r25]; vldb.pop.576 ex8, [p0, lf0, r24]; vst bmlh3, [p3, #64]; vmac.f dm1, dm3, ex6, ex11, r2
  ; CHECK-NEXT:    vlda bmlh2, [p7, #64]; vldb.pop.576 ex6, [p0, lf0, r24]; vst.2d bmll3, [p3], d0; add.nc lc, r0, #-3
  ; CHECK-NEXT:    vlda.2d bmll2, [p7], d2; vldb.pop.576 ex10, [p1, lf1, r25]; vst bmhh1, [p3, #192]; movxm ls, #.LBB0_2; vmac.f dm1, dm3, ex6, ex10, r2
  ; CHECK-NEXT:    vlda.pop.576.2d ex1, [p1, lf1, r25, d3]; vldb.pop.576.2d ex8, [p0, lf0, r24, d1]; vst bmhl1, [p3, #128]; movxm le, #.L_LEnd0; vmac.f dm3, dm1, ex8, ex4, r2
  ; CHECK-NEXT:    .p2align 4
  ; CHECK-NEXT:  .LBB0_2: // =>This Inner Loop Header: Depth=1
  ; CHECK-NEXT:    vlda.fill.512 [p1, lf1, r25]; vldb.fill.512 [p0, lf0, r24]; vst bmlh1, [p3, #64]; nopxm ; nopv
  ; CHECK-NEXT:    vlda bmhh0, [p7, #192]; vldb.pop.576 ex3, [p1, lf1, r25]; nopx ; vst.2d bmll1, [p3], d0; vmac.f dm4, dm0, ex10, ex3, r2
  ; CHECK-NEXT:    vlda bmhl0, [p7, #128]; vldb.pop.576 ex6, [p1, lf1, r25]; vmac.f dm1, dm1, ex8, ex1, r2
  ; CHECK-NEXT:    vlda bmlh0, [p7, #64]; vldb.pop.576 ex11, [p1, lf1, r25]; vmac.f dm2, dm2, ex10, ex1, r2
  ; CHECK-NEXT:    vlda.2d bmll0, [p7], d2; vldb.pop.576 ex10, [p0, lf0, r24]; vmac.f dm3, dm4, ex8, ex6, r2
  ; CHECK-NEXT:    vlda bmhh2, [p7, #192]; vldb.pop.576 ex4, [p1, lf1, r25]; vst bmhh3, [p3, #192]
  ; CHECK-NEXT:    vlda bmhl2, [p7, #128]; vldb.pop.576 ex1, [p1, lf1, r25]; vst bmhl3, [p3, #128]; vmac.f dm3, dm2, ex8, ex1, r2
  ; CHECK-NEXT:    vlda.pop.576 ex1, [p1, lf1, r25]; vldb.pop.576 ex8, [p0, lf0, r24]; vst bmlh3, [p3, #64]; vmac.f dm1, dm3, ex6, ex11, r2
  ; CHECK-NEXT:    vlda bmlh2, [p7, #64]; vldb.pop.576 ex6, [p0, lf0, r24]; vst.2d bmll3, [p3], d0
  ; CHECK-NEXT:    vlda.2d bmll2, [p7], d2; vldb.pop.576 ex10, [p1, lf1, r25]; vst bmhh1, [p3, #192]; vmac.f dm1, dm3, ex6, ex10, r2
  ; CHECK-NEXT:  .L_LEnd0:
  ; CHECK-NEXT:    vlda.pop.576.2d ex1, [p1, lf1, r25, d3]; vldb.pop.576.2d ex8, [p0, lf0, r24, d1]; vst bmhl1, [p3, #128]; nopxm ; vmac.f dm3, dm1, ex8, ex4, r2
  ; CHECK-NEXT:  // %bb.3:
  ; CHECK-NEXT:    nopa ; nopb ; vst bmlh1, [p3, #64]; nopxm ; nopv
  ; CHECK-NEXT:    vst.2d bmll1, [p3], d0; nopx ; vmac.f dm4, dm0, ex10, ex3, r2
  ; CHECK-NEXT:    vmac.f dm1, dm1, ex8, ex1, r2
  ; CHECK-NEXT:    vmac.f dm2, dm2, ex10, ex1, r2
  ; CHECK-NEXT:    vmac.f dm3, dm4, ex8, ex6, r2
  ; CHECK-NEXT:    vst bmhh3, [p3, #192]
  ; CHECK-NEXT:    vst bmhl3, [p3, #128]; vmac.f dm3, dm2, ex8, ex1, r2
  ; CHECK-NEXT:    vst bmlh3, [p3, #64]; vmac.f dm1, dm3, ex6, ex11, r2
  ; CHECK-NEXT:    vst.2d bmll3, [p3], d0
  ; CHECK-NEXT:    vst bmhh1, [p3, #192]; vmac.f dm1, dm3, ex6, ex10, r2
  ; CHECK-NEXT:    vst bmhl1, [p3, #128]; vmac.f dm3, dm1, ex8, ex4, r2
  ; CHECK-NEXT:    vst bmlh1, [p3, #64]
  ; CHECK-NEXT:    vst.2d bmll1, [p3], d0
  ; CHECK-NEXT:    vmac.f dm1, dm1, ex8, ex1, r2
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    vst bmhh3, [p3, #192]
  ; CHECK-NEXT:    vst bmhl3, [p3, #128]
  ; CHECK-NEXT:    vst bmlh3, [p3, #64]
  ; CHECK-NEXT:    vst.2d bmll3, [p3], d0
  ; CHECK-NEXT:    vst bmhh1, [p3, #192]
  ; CHECK-NEXT:    vst bmhl1, [p3, #128]
  ; CHECK-NEXT:    vst bmlh1, [p3, #64]
  ; CHECK-NEXT:    vst.2d bmll1, [p3], d0
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    .p2align 4
  ; CHECK-NEXT:  .LBB0_4:
  ; CHECK-NEXT:    nopa ; ret lr
  ; CHECK-NEXT:    nop // Delay Slot 5
  ; CHECK-NEXT:    nop // Delay Slot 4
  ; CHECK-NEXT:    nop // Delay Slot 3
  ; CHECK-NEXT:    nop // Delay Slot 2
  ; CHECK-NEXT:    nop // Delay Slot 1
  entry:
    %pA0 = getelementptr i8, ptr %pA, i32 0
    %pA1 = getelementptr i8, ptr %pA, i32 64
    %pA2 = getelementptr i8, ptr %pA, i32 128
    %pA3 = getelementptr i8, ptr %pA, i32 192
    %pA4 = getelementptr i8, ptr %pA, i32 256
    %pB0 = getelementptr i8, ptr %pB, i32 0
    %pB1 = getelementptr i8, ptr %pB, i32 64
    %pB2 = getelementptr i8, ptr %pB, i32 128
    %pB3 = getelementptr i8, ptr %pB, i32 192
    %pB4 = getelementptr i8, ptr %pB, i32 256
    %pB5 = getelementptr i8, ptr %pB, i32 320
    %pB6 = getelementptr i8, ptr %pB, i32 384
    %pB7 = getelementptr i8, ptr %pB, i32 448
    %pB8 = getelementptr i8, ptr %pB, i32 512
    %ld0 = getelementptr i8, ptr %psum_ld, i32 0
    %ld1 = getelementptr i8, ptr %psum_ld, i32 256
    %st0 = getelementptr i8, ptr %psum_st, i32 0
    %st1 = getelementptr i8, ptr %psum_st, i32 256
    ret void
  }

  ; TBAA
  !0 = !{!"omnipotent char", !1, i64 0}
  !1 = !{!"Simple C++ TBAA"}
  !2 = !{!0, !0, i64 0}

  ; Alias scope domains
  !3 = distinct !{!3, !"gemm_outer"}
  !4 = distinct !{!4, !"gemm_inner"}

  ; Scopes
  !10 = distinct !{!10, !3, !"pA"}
  !11 = distinct !{!11, !3, !"pB"}
  !12 = distinct !{!12, !3, !"output"}
  !13 = distinct !{!13, !3, !"output_tdm"}
  !14 = distinct !{!14, !3, !"param"}
  !20 = distinct !{!20, !4, !"pA"}
  !21 = distinct !{!21, !4, !"pB"}
  !22 = distinct !{!22, !4, !"load_psum"}
  !23 = distinct !{!23, !4, !"store_psum"}
  !24 = distinct !{!24, !4, !"param"}

  ; stream p0: alias.scope / noalias
  !30 = !{!20, !10}
  !31 = !{!21, !22, !23, !24, !11, !12, !13, !14}

  ; bm loads: alias.scope / noalias
  !32 = !{!22, !12}
  !33 = !{!20, !21, !23, !24, !10, !11, !13, !14}

  ; stores: alias.scope / noalias
  !34 = !{!23, !12}
  !35 = !{!20, !21, !22, !24, !10, !11, !13, !14}

  ; stream p1: alias.scope / noalias
  !36 = !{!21, !11}
  !37 = !{!20, !22, !23, !24, !10, !12, !13, !14}
...
---
name:            fill_stream_separation
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0 (align 16):
    successors: %bb.1(0x50000000), %bb.3(0x30000000)
    liveins: $p0, $p1, $r0

    $r1 = MOVA 0
    $r1 = GE $r1, $r0
    JNZ $r1, %bb.3
    DelayedSchedBarrier

  bb.1:
    successors: %bb.2(0x80000000)
    liveins: $p0, $p1, $r0

    $lc = ADD_NC_mv_add_ri $r0, 0
    $ls = MOVXM %bb.2
    $le = MOVXM <mcsymbol .L_LEnd0>

  bb.2 (align 16):
    successors: %bb.2(0x7c000000), %bb.3(0x04000000)
    liveins: $d0:0x0000000000200E00, $d1:0x0000000000200E00, $d2:0x0000000000200E00, $d3:0x0000000000200E00, $dc0, $dc1, $dc2, $dc3, $dc4, $dj0, $dj1, $dj2, $dj3, $dn0, $dn1, $dn2, $dn3, $m0, $m1, $m2, $m3, $p2, $p3, $p4, $p5, $p6, $p7, $plfr0:0x0000000000484040, $plfr1:0x0000000000484040, $r0, $r1, $r2, $r3, $r7, $r8

    ; FILL/POP from stream p0 (no addrspace -> no memory bank info)
    $p0, $lf0, $r24 = VLD_FILL_512_pseudo $p0, $lf0, $r24 :: (load unknown-size from %ir.pA0, align 1, !alias.scope !30, !noalias !31)
    $ex11, $p0, $lf0, $r24 = VLD_POP_576_normal_pop_pseudo $p0, $lf0, $r24, implicit-def $srfifo_uf :: (load unknown-size from %ir.pA1, align 1, !alias.scope !30, !noalias !31)
    $ex9, $p0, $lf0, $r24 = VLD_POP_576_normal_pop_pseudo $p0, $lf0, $r24, implicit-def $srfifo_uf :: (load unknown-size from %ir.pA2, align 1, !alias.scope !30, !noalias !31)
    $ex7, $p0, $lf0, $r24 = VLD_POP_576_normal_pop_pseudo $p0, $lf0, $r24, implicit-def $srfifo_uf :: (load unknown-size from %ir.pA3, align 1, !alias.scope !30, !noalias !31)
    $ex5, $p0, $lf0, $r24, $dc1 = VLD_POP_576_2D_pseudo $p0, $lf0, $r24, $d1, implicit-def $srfifo_uf :: (load unknown-size from %ir.pA4, align 1, !alias.scope !30, !noalias !31)

    ; FILL/POP from stream p1 (no addrspace -> no memory bank info)
    $p1, $lf1, $r25 = VLD_FILL_512_pseudo $p1, $lf1, $r25 :: (load unknown-size from %ir.pB0, align 1, !alias.scope !36, !noalias !37)
    $ex3, $p1, $lf1, $r25 = VLD_POP_576_normal_pop_pseudo $p1, $lf1, $r25, implicit-def $srfifo_uf :: (load unknown-size from %ir.pB1, align 1, !alias.scope !36, !noalias !37)
    $ex1, $p1, $lf1, $r25 = VLD_POP_576_normal_pop_pseudo $p1, $lf1, $r25, implicit-def $srfifo_uf :: (load unknown-size from %ir.pB2, align 1, !alias.scope !36, !noalias !37)
    $ex10, $p1, $lf1, $r25 = VLD_POP_576_normal_pop_pseudo $p1, $lf1, $r25, implicit-def $srfifo_uf :: (load unknown-size from %ir.pB3, align 1, !alias.scope !36, !noalias !37)
    $ex8, $p1, $lf1, $r25 = VLD_POP_576_normal_pop_pseudo $p1, $lf1, $r25, implicit-def $srfifo_uf :: (load unknown-size from %ir.pB4, align 1, !alias.scope !36, !noalias !37)
    $ex6, $p1, $lf1, $r25 = VLD_POP_576_normal_pop_pseudo $p1, $lf1, $r25, implicit-def $srfifo_uf :: (load unknown-size from %ir.pB5, align 1, !alias.scope !36, !noalias !37)
    $ex4, $p1, $lf1, $r25 = VLD_POP_576_normal_pop_pseudo $p1, $lf1, $r25, implicit-def $srfifo_uf :: (load unknown-size from %ir.pB6, align 1, !alias.scope !36, !noalias !37)
    $ex2, $p1, $lf1, $r25 = VLD_POP_576_normal_pop_pseudo $p1, $lf1, $r25, implicit-def $srfifo_uf :: (load unknown-size from %ir.pB7, align 1, !alias.scope !36, !noalias !37)
    $ex0, $p1, $lf1, $r25, $dc3 = VLD_POP_576_2D_pseudo $p1, $lf1, $r25, $d3, implicit-def $srfifo_uf :: (load unknown-size from %ir.pB8, align 1, !alias.scope !36, !noalias !37)

    ; bm loads (fixed on VLDA slot, addrspace 5 -> memory bank 0)
    renamable $bmhh4 = VLDA_dmx_lda_bm_idx_imm renamable $p7, 192 :: (load (<16 x s32>) from %ir.ld0, !tbaa !2, !alias.scope !32, !noalias !33, addrspace 5)
    renamable $bmhl4 = VLDA_dmx_lda_bm_idx_imm renamable $p7, 128 :: (load (<16 x s32>) from %ir.ld0 + 64, !tbaa !2, !alias.scope !32, !noalias !33, addrspace 5)
    renamable $bmlh4 = VLDA_dmx_lda_bm_idx_imm renamable $p7, 64 :: (load (<16 x s32>) from %ir.ld0 + 128, !tbaa !2, !alias.scope !32, !noalias !33, addrspace 5)
    $bmll4, $p7, $dc2 = VLDA_2D_dmx_lda_bm killed $p7, $d2 :: (load (<16 x s32>) from %ir.ld0 + 192, !tbaa !2, !alias.scope !32, !noalias !33, addrspace 5)

    renamable $dm3 = VMAC_f_vmac_bfp_vmul_bfp_core_EX_EX killed renamable $dm4, renamable $ex11, killed renamable $ex3, renamable $r2, implicit-def dead $srfpflags, implicit $crfpmask
    renamable $dm2 = VMAC_f_vmac_bfp_vmul_bfp_core_EX_EX killed renamable $dm3, renamable $ex9, killed renamable $ex1, renamable $r2, implicit-def dead $srfpflags, implicit $crfpmask
    renamable $dm1 = VMAC_f_vmac_bfp_vmul_bfp_core_EX_EX killed renamable $dm2, renamable $ex7, killed renamable $ex10, renamable $r2, implicit-def dead $srfpflags, implicit $crfpmask
    renamable $dm0 = VMAC_f_vmac_bfp_vmul_bfp_core_EX_EX killed renamable $dm1, renamable $ex5, killed renamable $ex8, renamable $r2, implicit-def dead $srfpflags, implicit $crfpmask

    VST_dmx_sts_bm_idx_imm renamable $bmhh0, renamable $p3, 192 :: (store (<16 x s32>) into %ir.st0, !tbaa !2, !alias.scope !34, !noalias !35, addrspace 5)
    VST_dmx_sts_bm_idx_imm renamable $bmhl0, renamable $p3, 128 :: (store (<16 x s32>) into %ir.st0 + 64, !tbaa !2, !alias.scope !34, !noalias !35, addrspace 5)
    VST_dmx_sts_bm_idx_imm renamable $bmlh0, renamable $p3, 64 :: (store (<16 x s32>) into %ir.st0 + 128, !tbaa !2, !alias.scope !34, !noalias !35, addrspace 5)
    $p3, $dc0 = VST_2D_dmx_sts_bm killed $bmll0, killed $p3, $d0 :: (store (<16 x s32>) into %ir.st0 + 192, !tbaa !2, !alias.scope !34, !noalias !35, addrspace 5)

    renamable $bmhh4 = VLDA_dmx_lda_bm_idx_imm renamable $p7, 192 :: (load (<16 x s32>) from %ir.ld1, !tbaa !2, !alias.scope !32, !noalias !33, addrspace 5)
    renamable $bmhl4 = VLDA_dmx_lda_bm_idx_imm renamable $p7, 128 :: (load (<16 x s32>) from %ir.ld1 + 64, !tbaa !2, !alias.scope !32, !noalias !33, addrspace 5)
    renamable $bmlh4 = VLDA_dmx_lda_bm_idx_imm renamable $p7, 64 :: (load (<16 x s32>) from %ir.ld1 + 128, !tbaa !2, !alias.scope !32, !noalias !33, addrspace 5)
    $bmll4, $p7, $dc2 = VLDA_2D_dmx_lda_bm killed $p7, $d2 :: (load (<16 x s32>) from %ir.ld1 + 192, !tbaa !2, !alias.scope !32, !noalias !33, addrspace 5)

    renamable $dm3 = VMAC_f_vmac_bfp_vmul_bfp_core_EX_EX killed renamable $dm4, killed renamable $ex11, killed renamable $ex6, renamable $r2, implicit-def dead $srfpflags, implicit $crfpmask
    renamable $dm2 = VMAC_f_vmac_bfp_vmul_bfp_core_EX_EX killed renamable $dm3, killed renamable $ex9, killed renamable $ex4, renamable $r2, implicit-def dead $srfpflags, implicit $crfpmask
    renamable $dm1 = VMAC_f_vmac_bfp_vmul_bfp_core_EX_EX killed renamable $dm2, killed renamable $ex7, killed renamable $ex2, renamable $r2, implicit-def dead $srfpflags, implicit $crfpmask
    renamable $dm0 = VMAC_f_vmac_bfp_vmul_bfp_core_EX_EX killed renamable $dm1, killed renamable $ex5, killed renamable $ex0, renamable $r2, implicit-def dead $srfpflags, implicit $crfpmask

    VST_dmx_sts_bm_idx_imm renamable $bmhh0, renamable $p3, 192 :: (store (<16 x s32>) into %ir.st1, !tbaa !2, !alias.scope !34, !noalias !35, addrspace 5)
    VST_dmx_sts_bm_idx_imm renamable $bmhl0, renamable $p3, 128 :: (store (<16 x s32>) into %ir.st1 + 64, !tbaa !2, !alias.scope !34, !noalias !35, addrspace 5)
    VST_dmx_sts_bm_idx_imm renamable $bmlh0, renamable $p3, 64 :: (store (<16 x s32>) into %ir.st1 + 128, !tbaa !2, !alias.scope !34, !noalias !35, addrspace 5)
    $p3, $dc0 = VST_2D_dmx_sts_bm killed $bmll0, killed $p3, $d0 :: (store (<16 x s32>) into %ir.st1 + 192, !tbaa !2, !alias.scope !34, !noalias !35, addrspace 5)

    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.2

  bb.3 (align 16):
    RET implicit $lr
    DelayedSchedBarrier
