# NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates


# RUN: llc  --mtriple=aie2p -O2 --start-before=postmisched \
# RUN:   -aie-preassign-multi-slot-instr=true -verify-machineinstrs \
# RUN:   --aie-loop-min-tripcount=10 %s -o - | FileCheck %s


# overloading Slots with memory banks and needing to reassign Slots:
# addrspace 5 (Memory Bank A) -> unused slot B
# addrspace 6 (Memory Bank B) -> unused slot A
# addrspace 7 (Memory Bank C) -> reassign already used Slot
--- |
  define dso_local void @reassign_slots(ptr addrspace(5) noalias nocapture writeonly %d, ptr addrspace(6) noalias nocapture readonly %s, i32 noundef %n) local_unnamed_addr #0 {
  ; CHECK-LABEL: reassign_slots:
  ; CHECK:         .p2align 4
  ; CHECK-NEXT:  // %bb.0:
  ; CHECK-NEXT:    mova r1, #0; nopb ; nops ; nopxm ; nopv
  ; CHECK-NEXT:    nopa ; ge r1, r1, r0
  ; CHECK-NEXT:    jnz r1, #.LBB0_4
  ; CHECK-NEXT:    nop // Delay Slot 5
  ; CHECK-NEXT:    nop // Delay Slot 4
  ; CHECK-NEXT:    nop // Delay Slot 3
  ; CHECK-NEXT:    nop // Delay Slot 2
  ; CHECK-NEXT:    nop // Delay Slot 1
  ; CHECK-NEXT:  // %bb.1:
  ; CHECK-NEXT:    add.nc lc, r0, #0
  ; CHECK-NEXT:    movxm ls, #.LBB0_2
  ; CHECK-NEXT:    nopa ; nopb ; nops ; movxm le, #.L_LEnd0; nopv
  ; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; nopv
  ; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; nopv
  ; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; nopv
  ; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; nopv
  ; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; nopv
  ; CHECK-NEXT:    .p2align 4
  ; CHECK-NEXT:  .LBB0_2: // =>This Inner Loop Header: Depth=1
  ; CHECK-NEXT:    vlda.fill.512 [p1, lf1, r25]; vldb.fill.512 [p0, lf0, r24]; nops ; nopxm ; nopv
  ; CHECK-NEXT:  .L_LEnd0:
  ; CHECK-NEXT:    vlda.fill.512 [p0, lf0, r24]; nopb ; nops ; nopxm ; nopv
  ; CHECK-NEXT:  // %bb.3:
  ; CHECK-NEXT:    .p2align 4
  ; CHECK-NEXT:  .LBB0_4:
  ; CHECK-NEXT:    nopa ; ret lr
  ; CHECK-NEXT:    nop // Delay Slot 5
  ; CHECK-NEXT:    nop // Delay Slot 4
  ; CHECK-NEXT:    nop // Delay Slot 3
  ; CHECK-NEXT:    nop // Delay Slot 2
  ; CHECK-NEXT:    nop // Delay Slot 1
  entry:
    ret void
  }
...
---
name:            reassign_slots
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0 (align 16):
    successors: %bb.1(0x50000000), %bb.3(0x30000000)
    liveins: $p0, $p1, $r0

    $r1 = MOVA 0
    $r1 = GE $r1, $r0
    JNZ $r1, %bb.3
    DelayedSchedBarrier

  bb.1:
    successors: %bb.2(0x80000000)
    liveins: $p0, $p1, $r0

    $lc = ADD_NC_mv_add_ri $r0, 0
    $ls = MOVXM %bb.2
    $le = MOVXM <mcsymbol .L_LEnd0>

  bb.2 (align 16):
   successors: %bb.2(0x7c000000), %bb.3(0x04000000)
    liveins: $p0, $p1, $lf0, $lf1, $r24, $r25

    $p0, $lf0, $r24 = VLD_FILL_512_pseudo killed $p0, killed $lf0, killed $r24 :: (load (<32 x s16>), addrspace 5)
    $p1, $lf1, $r25 = VLD_FILL_512_pseudo killed $p1, killed $lf1, killed $r25 :: (load (<32 x s16>), addrspace 6)
    $p0, $lf0, $r24 = VLD_FILL_512_pseudo killed $p0, killed $lf0, killed $r24 :: (load (<32 x s16>), addrspace 7)

    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.2, implicit $ls, implicit $le

  bb.3 (align 16):
    RET implicit $lr
    DelayedSchedBarrier
