# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py

# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024-2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc --mtriple=aie2 --run-pass=postmisched %s -o - | FileCheck %s

# Check that memory edges carry the right latency.
# We make the test more sensitive by using a hwloop
# VST_SRS is a late memory writer, for which we have the memory latency
# across the loop edge. VLDA is a late register writer, for which we have
# the register latency in the loop body
---
name:            memoryLCD
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: memoryLCD
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $s0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $p0, $s0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $cm0 = VLDA_UPS_S32_D8_ag_idx_imm $s0, $p0, 0, implicit-def $srups_of, implicit $crsat, implicit $crupssign
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   VST_SRS_D8_S32_ag_idx_imm $p0, 0, killed $cm0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   PseudoLoopEnd %bb.2, %bb.1, implicit $ls, implicit $le
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $wl0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $wl1 = VMOV_mv_w killed $wl0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   liveins: $wl1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   RET implicit $lr
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   DelayedSchedBarrier implicit killed $wl1
  bb.0:
    liveins: $p0, $s0
    successors: %bb.1
  bb.1:
    liveins: $p0, $s0
    successors: %bb.1, %bb.2
    $cm0 = VLDA_UPS_S32_D8_ag_idx_imm $s0, $p0, 0, implicit-def $srups_of, implicit $crsat, implicit $crupssign
    VST_SRS_D8_S32_ag_idx_imm $p0, 0, $cm0, $s0, implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign

    PseudoLoopEnd %bb.2, %bb.1, implicit $ls, implicit $le
  bb.2:
    liveins: $wl0
    successors: %bb.3
    $wl1 = VMOV_mv_w $wl0
  bb.3:
    liveins: $wl1
    RET implicit $lr
    DelayedSchedBarrier implicit $wl1
...

