# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4

# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates


# We have a loop with an epilogue shared by a guard branch

# RUN: llc --mtriple=aie2 --run-pass=postmisched %s -o - | FileCheck %s
---
name:            cpy
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: cpy
  ; CHECK: bb.0.entry (align 16):
  ; CHECK-NEXT:   successors: %bb.1(0x50000000), %bb.3(0x30000000)
  ; CHECK-NEXT:   liveins: $p0, $p1, $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $r1 = MOVA_lda_cg 0
  ; CHECK-NEXT:   $r1 = GE killed $r1, $r0
  ; CHECK-NEXT:   JNZ killed $r1, %bb.3
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   DelayedSchedBarrier
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $p1, $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $r0 = ADD_NC_GPR killed $r0, -1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.2(0x7c000000), %bb.3(0x04000000)
  ; CHECK-NEXT:   liveins: $p0, $p1, $p2, $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $r1, $p1 = LDA_dms_lda_pstm_nrm_imm killed $p1, 4
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   $r0 = ADD_add_r_ri killed $r0, -1, implicit-def $srcarry
  ; CHECK-NEXT:   JNZ $r0, %bb.2
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   $r1 = nsw ADD_add_r_ri killed $r1, 1, implicit-def $srcarry
  ; CHECK-NEXT:   $p0 = ST_dms_sts_pstm_nrm_imm killed $r1, killed $p0, 4
  ; CHECK-NEXT:   DelayedSchedBarrier
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   RET implicit $lr
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   DelayedSchedBarrier
  bb.0.entry (align 16):
    successors: %bb.1(0x50000000), %bb.3(0x30000000)
    liveins: $p0, $p1, $r0

    $r1 = MOV_RLC_imm10_pseudo 0
    $r1 = GE $r1, $r0
    JNZ $r1, %bb.3
    DelayedSchedBarrier

  bb.1:
    successors: %bb.2(0x80000000)
    liveins: $p0, $p1, $r0

    $r0 = ADD_NC_GPR $r0, -1

  bb.2:
    successors: %bb.2(0x7c000000), %bb.3(0x04000000)
    liveins: $p0, $p1, $p2, $r0

    $r1, $p1 = LDA_dms_lda_pstm_nrm_imm $p1, 4
    $r1 = nsw ADD_add_r_ri $r1, 1, implicit-def $srcarry
    $p0 = ST_dms_sts_pstm_nrm_imm $r1, $p0, 4
    $r0 = ADD_add_r_ri $r0, -1, implicit-def $srcarry
    JNZ $r0,%bb.2
    DelayedSchedBarrier

  bb.3:
    RET implicit $lr
    DelayedSchedBarrier

...
