# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2ps -run-pass machineverifier %s -o - | FileCheck %s

# Tests 3 representative control and status registers to check if the corresponding classes have been
# reserved, otherwise the verifier would complain about the use of an undefined physical register

---
name:      reserved_regs_cr_sr
tracksRegLiveness: true
body:      |
  bb.0 (align 16):
    ; CHECK-LABEL: name: reserved_regs_cr_sr
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:mlockid_reg(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[EQ:%[0-9]+]]:mr27_select = EQ [[C]](s32), [[C]](s32)
    ; CHECK-NEXT: [[SQRT_nlf_sqrt:%[0-9]+]]:mlockid_reg = SQRT_nlf_sqrt [[C]](s32), implicit-def dead $srfpnlf, implicit $crfpnlfmask
    ; CHECK-NEXT: [[VPACK_mv_pack_w_packSign0_:%[0-9]+]]:vec256 = VPACK_mv_pack_w_packSign0 $x0, implicit $crpacksize, implicit $crsat, implicit $packsign0
    ; CHECK-NEXT: $r0 = COPY [[EQ]]
    ; CHECK-NEXT: $r1 = COPY [[SQRT_nlf_sqrt]]
    ; CHECK-NEXT: $wl0 = COPY [[VPACK_mv_pack_w_packSign0_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $l0, implicit $wl0
    liveins : $x0
    %0:mlockid_reg(s32) = G_CONSTANT i32 0
    %4:mr27_select = EQ %0:mlockid_reg, %0:mlockid_reg
    %5:mlockid_reg = SQRT_nlf_sqrt %0, implicit-def dead $srfpnlf, implicit $crfpnlfmask
    %6:vec256 = VPACK_mv_pack_w_packSign0 $x0, implicit $crpacksize, implicit $crsat, implicit $packsign0
    $r0 = COPY %4
    $r1 = COPY %5
    $wl0 = COPY %6
    PseudoRET implicit $lr, implicit $l0, implicit $wl0
...

---
name:      reserved_regs_special
tracksRegLiveness: true
alignment:    16
body:      |
  bb.0 (align 16):
    liveins: $r13, $p1, $p0, $r30, $r24, $d3, $lf0
    ; CHECK-LABEL: name: reserved_regs_special
    ; CHECK: liveins: $r13, $p1, $p0, $r30, $r24, $d3, $lf0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $l4 = LDA_dml_lda_scalar_L_spill -4096, implicit $sp
    ; CHECK-NEXT: $p1, $dc3 = ST_2D_s16 $r13, $p1, $d3, implicit-def $pe2_ads, implicit $pe2_ads
    ; CHECK-NEXT: RET implicit $lr, implicit $pc
    $l4 = LDA_dml_lda_scalar_L_spill -4096, implicit $sp
    $p1, $dc3 = ST_2D_s16 $r13, $p1, $d3, implicit-def $pe2_ads, implicit $pe2_ads
    RET implicit $lr, implicit $pc
...
