// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
//===- aie2p-ups-intrinsics.cpp --------------------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//
// RUN: %clang -O2 %s --target=aie2p -nostdlibinc -S -emit-llvm -o - | FileCheck %s

// CHECK-LABEL: @_Z28test_v64acc32_sups_with_signDv64_aii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i32> @llvm.aie2p.acc32.v64.I512.ups(<64 x i8> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <64 x i32> [[TMP0]]
//
v64acc32 test_v64acc32_sups_with_sign(v64int8 a, int shft, int sign) {
   return sups(a,shft,sign);
}

// CHECK-LABEL: @_Z33test_v64acc32_sups_with_sign_confDv64_aiii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef <64 x i32> @llvm.aie2p.acc32.v64.I512.ups(<64 x i8> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    ret <64 x i32> [[TMP1]]
//
v64acc32 test_v64acc32_sups_with_sign_conf(v64int8 a, int shft, int sign, int sat) {
   return sups_conf(a,shft,sign,sat);
}

// CHECK-LABEL: @_Z28test_v64acc32_sups_with_signDv64_ai(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i32> @llvm.aie2p.acc32.v64.I512.ups(<64 x i8> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    ret <64 x i32> [[TMP0]]
//
v64acc32 test_v64acc32_sups_with_sign(v64int8 a, int shft) {
  return sups(a, shft);
}

// CHECK-LABEL: @_Z33test_v64acc32_sups_with_sign_confDv64_aii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef <64 x i32> @llvm.aie2p.acc32.v64.I512.ups(<64 x i8> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    ret <64 x i32> [[TMP1]]
//
v64acc32 test_v64acc32_sups_with_sign_conf(v64int8 a, int shft, int sat) {
  return sups_conf(a, shft, sat);
}

// CHECK-LABEL: @_Z29test_ups_to_v64acc32_wit_signDv64_aii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i32> @llvm.aie2p.acc32.v64.I512.ups(<64 x i8> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <64 x i32> [[TMP0]]
//
v64acc32 test_ups_to_v64acc32_wit_sign(v64int8 a, int shft, int sign) {
  return ups_to_v64acc32(a, shft, sign);
}

// CHECK-LABEL: @_Z34test_ups_to_v64acc32_wit_sign_confDv64_aiii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef <64 x i32> @llvm.aie2p.acc32.v64.I512.ups(<64 x i8> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    ret <64 x i32> [[TMP1]]
//
v64acc32 test_ups_to_v64acc32_wit_sign_conf(v64int8 a, int shft, int sign, int sat) {
  return ups_to_v64acc32_conf(a, shft, sign, sat);
}
// CHECK-LABEL: @_Z28test_ups_to_v64acc32_no_signDv64_ai(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i32> @llvm.aie2p.acc32.v64.I512.ups(<64 x i8> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    ret <64 x i32> [[TMP0]]
//
v64acc32 test_ups_to_v64acc32_no_sign(v64int8 a, int shft) {
  return ups_to_v64acc32(a, shft);
}

// CHECK-LABEL: @_Z33test_ups_to_v64acc32_no_sign_confDv64_aii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef <64 x i32> @llvm.aie2p.acc32.v64.I512.ups(<64 x i8> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    ret <64 x i32> [[TMP1]]
//
v64acc32 test_ups_to_v64acc32_no_sign_conf(v64int8 a, int shft, int sat) {
  return ups_to_v64acc32_conf(a, shft, sat);
}

// CHECK-LABEL: @_Z19test_lups_with_signDv32_sii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i64> @llvm.aie2p.acc64.v32.I512.ups(<32 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <32 x i64> [[TMP0]]
//
v32acc64 test_lups_with_sign(v32int16 a, int shft, int sign) {
   return lups(a,shft,sign);
}

// CHECK-LABEL: @_Z24test_lups_with_sign_confDv32_siii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef <32 x i64> @llvm.aie2p.acc64.v32.I512.ups(<32 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    ret <32 x i64> [[TMP1]]
//
v32acc64 test_lups_with_sign_conf(v32int16 a, int shft, int sign, int sat) {
   return lups_conf(a,shft,sign, sat);
}
// CHECK-LABEL: @_Z17test_lups_no_signDv32_si(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i64> @llvm.aie2p.acc64.v32.I512.ups(<32 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    ret <32 x i64> [[TMP0]]
//
v32acc64 test_lups_no_sign(v32int16 a, int shft) {
  return lups(a, shft);
}

// CHECK-LABEL: @_Z22test_lups_no_sign_confDv32_sii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i64> @llvm.aie2p.acc64.v32.I512.ups(<32 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SAT:%.*]])
// CHECK-NEXT:    ret <32 x i64> [[TMP0]]
//
v32acc64 test_lups_no_sign_conf(v32int16 a, int shft, int sat) {
  return lups(a, shft, sat);
}

// CHECK-LABEL: @_Z30test_ups_to_v32acc64_with_signDv32_sii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i64> @llvm.aie2p.acc64.v32.I512.ups(<32 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <32 x i64> [[TMP0]]
//
v32acc64 test_ups_to_v32acc64_with_sign(v32int16 a, int shft, int sign) {
  return ups_to_v32acc64(a, shft, sign);
}

// CHECK-LABEL: @_Z28test_ups_to_v32acc64_no_signDv32_si(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i64> @llvm.aie2p.acc64.v32.I512.ups(<32 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    ret <32 x i64> [[TMP0]]
//
v32acc64 test_ups_to_v32acc64_no_sign(v32int16 a, int shft) {
  return ups_to_v32acc64(a, shft, __SIGN_SIGNED);
}


// CHECK-LABEL: @_Z23test_ups_to_v16accfloatDv8_f(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x float> @llvm.aie2p.v8float.to.v16accfloat(<8 x float> [[A:%.*]])
// CHECK-NEXT:    ret <16 x float> [[TMP0]]
//
v16accfloat test_ups_to_v16accfloat(v8float a) {
  return ups_to_v16accfloat(a);
}

// CHECK-LABEL: @_Z23test_ups_to_v32accfloatDv16_f(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x float> @llvm.aie2p.v16float.to.v32accfloat(<16 x float> [[A:%.*]])
// CHECK-NEXT:    ret <32 x float> [[TMP0]]
//
v32accfloat test_ups_to_v32accfloat(v16float a) {
  return ups_to_v32accfloat(a);
}
