// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 4
//===- aie2-bank-annotation.cpp----------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//
// This test shows that the translation of __aie_dm_resource_* to the correct address space only works with a pointer
// passed to the intrinsic, if we pass an annotated reference to a pointer however (e.g. *&p), it is not translated
// to the correct address space.
// RUN: %clang -O2 --target=aie2p -nostdlibinc -fno-unroll-loops -S -emit-llvm %s -o - | FileCheck %s


// CHECK-LABEL: define dso_local void @_Z32test_intrinsic_annotated_pointerPU3AS522v64bfp16ebs8_unaligned12v64bfp16ebs8R12fifo_state_t(
// CHECK-SAME: ptr addrspace(5) [[P:%.*]], [[STRUCT_V64BFP16EBS8:%.*]] [[V_COERCE:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[V_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[V_COERCE]], 1
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// CHECK-NEXT:    [[TMP2:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA2:![0-9]+]]
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA5:![0-9]+]]
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.576.bfp16.p5.p5(ptr addrspace(5) [[P]], <64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <32 x i32> [[TMP2]], i32 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    ret void
//
void test_intrinsic_annotated_pointer(v64bfp16ebs8_unaligned __aie_dm_resource_a * p, v64bfp16ebs8 v,
                       fifo_state_t &s) {
  return fifo_st_push(p, v, s);
}

// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z43test_intrinsic_annotated_pointer_fillx_popxPU3AS522v64bfp16ebs8_unalignedPU3AS6Dv64_DB8_R12fifo_state_t(
// CHECK-SAME: ptr addrspace(5) [[P_UNALIGNED:%.*]], ptr addrspace(6) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// CHECK-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// CHECK-NEXT:    [[TMP0:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA5]]
// CHECK-NEXT:    [[TMP2:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr addrspace(5), <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.fillx.p5.p5(ptr addrspace(5) [[P_UNALIGNED]], <32 x i32> [[TMP0]], i32 [[TMP1]], <16 x i32> [[TMP2]], i32 2015)
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32> } [[TMP3]], 1
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32> } [[TMP3]], 2
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32> } [[TMP3]], 3
// CHECK-NEXT:    store <16 x i32> [[TMP6]], ptr [[EXTRA3_I_I]], align 64
// CHECK-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP5]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    [[TMP7:%.*]] = tail call { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p6.p6(ptr addrspace(6) [[P]], <32 x i32> [[TMP4]], i32 [[TMP5]], <16 x i32> [[TMP6]], i32 2015)
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, <16 x i32> } [[TMP7]], 0
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, <16 x i32> } [[TMP7]], 2
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, <16 x i32> } [[TMP7]], 3
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, <16 x i32> } [[TMP7]], 4
// CHECK-NEXT:    store <16 x i32> [[TMP11]], ptr [[EXTRA3_I_I]], align 64
// CHECK-NEXT:    store <32 x i32> [[TMP9]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP10]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    ret <64 x i8> [[TMP8]]
//
v128uint4 test_intrinsic_annotated_pointer_fillx_popx(v64bfp16ebs8_unaligned __aie_dm_resource_a * p_unaligned, v128int4 __aie_dm_resource_b *p, fifo_state_t &s) {
  fifo_ld_fillx(p_unaligned, s);
  return  fifo_ld_popx(p, s);
}

// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z41test_intrinsic_annotated_pointer_fill_popPU3AS522v64bfp16ebs8_unalignedPU3AS6Dv64_DB8_R12fifo_state_t(
// CHECK-SAME: ptr addrspace(5) [[P_UNALIGNED:%.*]], ptr addrspace(6) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA5]]
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p5.p5(ptr addrspace(5) [[P_UNALIGNED]], <32 x i32> [[TMP0]], i32 [[TMP1]])
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP2]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP2]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP3]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP4]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    [[TMP5:%.*]] = tail call { <64 x i8>, ptr addrspace(6), <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.unaligned.p6.p6(ptr addrspace(6) [[P]], <32 x i32> [[TMP3]], i32 [[TMP4]])
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32 } [[TMP5]], 0
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32 } [[TMP5]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32 } [[TMP5]], 3
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    ret <64 x i8> [[TMP6]]
//
v128uint4 test_intrinsic_annotated_pointer_fill_pop(v64bfp16ebs8_unaligned __aie_dm_resource_a * p_unaligned, v128int4 __aie_dm_resource_b *p, fifo_state_t &s) {
  fifo_ld_fill(p_unaligned, s);
  return  fifo_ld_pop(p, s);
}

// CHECK-LABEL: define dso_local void @_Z42test_intrinsic_annotated_pointer_referenceRPU3AS522v64bfp16ebs8_unaligned12v64bfp16ebs8R12fifo_state_t(
// CHECK-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], [[STRUCT_V64BFP16EBS8:%.*]] [[V_COERCE:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR1:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[V_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[V_COERCE]], 1
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr addrspace(5), ptr [[P]], align 4, !tbaa [[TBAA7:![0-9]+]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA5]]
// CHECK-NEXT:    [[TMP5:%.*]] = tail call { ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.576.bfp16.p5.p5(ptr addrspace(5) [[TMP2]], <64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <32 x i32> [[TMP3]], i32 [[TMP4]])
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP5]], 0
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP5]], 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP5]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr addrspace(5) [[TMP6]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_intrinsic_annotated_pointer_reference(v64bfp16ebs8_unaligned __aie_dm_resource_a * &p, v64bfp16ebs8 v,
                       fifo_state_t &s) {
  return fifo_st_push(p, v, s);

}


// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z53test_intrinsic_annotated_pointer_reference_fillx_popxRPU3AS522v64bfp16ebs8_unalignedRPU3AS6Dv64_DB8_R12fifo_state_t(
// CHECK-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P_UNALIGNED:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR2:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// CHECK-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr addrspace(5), ptr [[P_UNALIGNED]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA5]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr addrspace(5), <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.fillx.p5.p5(ptr addrspace(5) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// CHECK-NEXT:    store <16 x i32> [[TMP8]], ptr [[EXTRA3_I_I]], align 64
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr addrspace(5) [[TMP5]], ptr [[P_UNALIGNED]], align 4
// CHECK-NEXT:    [[TMP9:%.*]] = load ptr addrspace(6), ptr [[P]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP10:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA5]]
// CHECK-NEXT:    [[TMP12:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP13:%.*]] = tail call { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p6.p6(ptr addrspace(6) [[TMP9]], <32 x i32> [[TMP10]], i32 [[TMP11]], <16 x i32> [[TMP12]], i32 2015)
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, <16 x i32> } [[TMP13]], 0
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, <16 x i32> } [[TMP13]], 1
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, <16 x i32> } [[TMP13]], 2
// CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, <16 x i32> } [[TMP13]], 3
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, <16 x i32> } [[TMP13]], 4
// CHECK-NEXT:    store <16 x i32> [[TMP18]], ptr [[EXTRA3_I_I]], align 64
// CHECK-NEXT:    store <32 x i32> [[TMP16]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr addrspace(6) [[TMP15]], ptr [[P]], align 4
// CHECK-NEXT:    ret <64 x i8> [[TMP14]]
//
v128uint4 test_intrinsic_annotated_pointer_reference_fillx_popx(v64bfp16ebs8_unaligned __aie_dm_resource_a * &p_unaligned, v128int4 __aie_dm_resource_b *&p, fifo_state_t &s) {
  fifo_ld_fillx(p_unaligned, s);
  return  fifo_ld_popx(p, s);
}

// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z51test_intrinsic_annotated_pointer_reference_fill_popRPU3AS522v64bfp16ebs8_unalignedRPU3AS6Dv64_DB8_R12fifo_state_t(
// CHECK-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P_UNALIGNED:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR2]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr addrspace(5), ptr [[P_UNALIGNED]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA5]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p5.p5(ptr addrspace(5) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr addrspace(5) [[TMP4]], ptr [[P_UNALIGNED]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = load ptr addrspace(6), ptr [[P]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP8:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA5]]
// CHECK-NEXT:    [[TMP10:%.*]] = tail call { <64 x i8>, ptr addrspace(6), <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.unaligned.p6.p6(ptr addrspace(6) [[TMP7]], <32 x i32> [[TMP8]], i32 [[TMP9]])
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32 } [[TMP10]], 0
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32 } [[TMP10]], 1
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32 } [[TMP10]], 2
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32 } [[TMP10]], 3
// CHECK-NEXT:    store <32 x i32> [[TMP13]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP14]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr addrspace(6) [[TMP12]], ptr [[P]], align 4
// CHECK-NEXT:    ret <64 x i8> [[TMP11]]
//
v128uint4 test_intrinsic_annotated_pointer_reference_fill_pop(v64bfp16ebs8_unaligned __aie_dm_resource_a * &p_unaligned, v128int4 __aie_dm_resource_b *&p, fifo_state_t &s) {
  fifo_ld_fill(p_unaligned, s);
  return  fifo_ld_pop(p, s);
}

// CHECK-LABEL: define dso_local void @_Z47test_intrinsic_annotated_pointer_reference_loopRPU3AS522v64bfp16ebs8_unaligned12v64bfp16ebs8i(
// CHECK-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], [[STRUCT_V64BFP16EBS8:%.*]] [[V_COERCE:%.*]], i32 noundef [[NUM:%.*]]) local_unnamed_addr #[[ATTR3:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP6:%.*]] = icmp sgt i32 [[NUM]], 0
// CHECK-NEXT:    br i1 [[CMP6]], label [[FOR_BODY_LR_PH:%.*]], label [[FOR_COND_CLEANUP:%.*]]
// CHECK:       for.body.lr.ph:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[V_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[V_COERCE]], 1
// CHECK-NEXT:    [[DOTPRE:%.*]] = load ptr addrspace(5), ptr [[P]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    br label [[FOR_BODY:%.*]]
// CHECK:       for.cond.cleanup:
// CHECK-NEXT:    ret void
// CHECK:       for.body:
// CHECK-NEXT:    [[TMP2:%.*]] = phi ptr addrspace(5) [ [[DOTPRE]], [[FOR_BODY_LR_PH]] ], [ [[TMP8:%.*]], [[FOR_BODY]] ]
// CHECK-NEXT:    [[I_09:%.*]] = phi i32 [ 0, [[FOR_BODY_LR_PH]] ], [ [[INC:%.*]], [[FOR_BODY]] ]
// CHECK-NEXT:    [[S_SROA_0_08:%.*]] = phi <32 x i32> [ undef, [[FOR_BODY_LR_PH]] ], [ [[TMP9:%.*]], [[FOR_BODY]] ]
// CHECK-NEXT:    [[S_SROA_6_07:%.*]] = phi i32 [ 0, [[FOR_BODY_LR_PH]] ], [ [[TMP10:%.*]], [[FOR_BODY]] ]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.576.bfp16.p5.p5(ptr addrspace(5) [[TMP2]], <64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <32 x i32> [[S_SROA_0_08]], i32 [[S_SROA_6_07]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    [[TMP7:%.*]] = tail call { ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p5.p5(ptr addrspace(5) [[TMP4]], <32 x i32> [[TMP5]], i32 [[TMP6]])
// CHECK-NEXT:    [[TMP8]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP7]], 0
// CHECK-NEXT:    [[TMP9]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP7]], 1
// CHECK-NEXT:    [[TMP10]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP7]], 2
// CHECK-NEXT:    store ptr addrspace(5) [[TMP8]], ptr [[P]], align 4
// CHECK-NEXT:    [[INC]] = add nuw nsw i32 [[I_09]], 1
// CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i32 [[INC]], [[NUM]]
// CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label [[FOR_COND_CLEANUP]], label [[FOR_BODY]], !llvm.loop [[LOOP10:![0-9]+]]
//
void test_intrinsic_annotated_pointer_reference_loop(
    v64bfp16ebs8_unaligned __aie_dm_resource_a *&p, v64bfp16ebs8 v, int num) {
  fifo_state_t s;
  s.pos = 0;
  for (int i = 0; i < num; ++i) {
    fifo_st_push(p, v, s);
    fifo_st_flush(p, s);
  }
}

// CHECK-LABEL: define dso_local void @_Z45test_intrinsic_default_pointer_reference_loopRP22v64bfp16ebs8_unaligned12v64bfp16ebs8i(
// CHECK-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], [[STRUCT_V64BFP16EBS8:%.*]] [[V_COERCE:%.*]], i32 noundef [[NUM:%.*]]) local_unnamed_addr #[[ATTR3]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP6:%.*]] = icmp sgt i32 [[NUM]], 0
// CHECK-NEXT:    br i1 [[CMP6]], label [[FOR_BODY_LR_PH:%.*]], label [[FOR_COND_CLEANUP:%.*]]
// CHECK:       for.body.lr.ph:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[V_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[V_COERCE]], 1
// CHECK-NEXT:    [[DOTPRE:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    br label [[FOR_BODY:%.*]]
// CHECK:       for.cond.cleanup:
// CHECK-NEXT:    ret void
// CHECK:       for.body:
// CHECK-NEXT:    [[TMP2:%.*]] = phi ptr [ [[DOTPRE]], [[FOR_BODY_LR_PH]] ], [ [[TMP8:%.*]], [[FOR_BODY]] ]
// CHECK-NEXT:    [[I_09:%.*]] = phi i32 [ 0, [[FOR_BODY_LR_PH]] ], [ [[INC:%.*]], [[FOR_BODY]] ]
// CHECK-NEXT:    [[S_SROA_0_08:%.*]] = phi <32 x i32> [ undef, [[FOR_BODY_LR_PH]] ], [ [[TMP9:%.*]], [[FOR_BODY]] ]
// CHECK-NEXT:    [[S_SROA_6_07:%.*]] = phi i32 [ 0, [[FOR_BODY_LR_PH]] ], [ [[TMP10:%.*]], [[FOR_BODY]] ]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.576.bfp16.p0.p0(ptr [[TMP2]], <64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <32 x i32> [[S_SROA_0_08]], i32 [[S_SROA_6_07]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    [[TMP7:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP4]], <32 x i32> [[TMP5]], i32 [[TMP6]])
// CHECK-NEXT:    [[TMP8]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP7]], 0
// CHECK-NEXT:    [[TMP9]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP7]], 1
// CHECK-NEXT:    [[TMP10]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP7]], 2
// CHECK-NEXT:    store ptr [[TMP8]], ptr [[P]], align 4
// CHECK-NEXT:    [[INC]] = add nuw nsw i32 [[I_09]], 1
// CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i32 [[INC]], [[NUM]]
// CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label [[FOR_COND_CLEANUP]], label [[FOR_BODY]], !llvm.loop [[LOOP13:![0-9]+]]
//
void test_intrinsic_default_pointer_reference_loop(
    v64bfp16ebs8_unaligned *&p, v64bfp16ebs8 v, int num) {
  fifo_state_t s;
  s.pos = 0;
  for (int i = 0; i < num; ++i) {
    fifo_st_push(p, v, s);
    fifo_st_flush(p, s);
  }
}
//.
// CHECK: [[TBAA2]] = !{[[META3:![0-9]+]], [[META3]], i64 0}
// CHECK: [[META3]] = !{!"omnipotent char", [[META4:![0-9]+]], i64 0}
// CHECK: [[META4]] = !{!"Simple C++ TBAA"}
// CHECK: [[TBAA5]] = !{[[META6:![0-9]+]], [[META6]], i64 0}
// CHECK: [[META6]] = !{!"int", [[META3]], i64 0}
// CHECK: [[TBAA7]] = !{[[META8:![0-9]+]], [[META8]], i64 0}
// CHECK: [[META8]] = !{!"p1 void", [[META9:![0-9]+]], i64 0}
// CHECK: [[META9]] = !{!"any pointer", [[META3]], i64 0}
// CHECK: [[LOOP10]] = distinct !{[[LOOP10]], [[META11:![0-9]+]], [[META12:![0-9]+]]}
// CHECK: [[META11]] = !{!"llvm.loop.mustprogress"}
// CHECK: [[META12]] = !{!"llvm.loop.unroll.disable"}
// CHECK: [[LOOP13]] = distinct !{[[LOOP13]], [[META11]], [[META12]]}
//.
