// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 4
//===-------------------- AIEngine AIE2p intrinsics ------------------------===
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//

//* Automatically generated file, do not edit! *
//
// RUN: %clang -O2 %s --target=aie2p -nostdlibinc -S -emit-llvm -o - | FileCheck %s

// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z17test_mul_8x8_8x8T12v64bfp16ebs8S_(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], [[STRUCT_V64BFP16EBS8]] [[B_COERCE:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mul.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <8 x i8> [[TMP3]], i32 780)
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <64 x i32> [[TMP4]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP5]]
//
v64accfloat test_mul_8x8_8x8T(v64bfp16ebs8 a, v64bfp16ebs8 b) {
  return mul_8x8_8x8T(a, b);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z20test_negmul_8x8_8x8T12v64bfp16ebs8S_(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], [[STRUCT_V64BFP16EBS8]] [[B_COERCE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.negmul.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <8 x i8> [[TMP3]], i32 780)
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <64 x i32> [[TMP4]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP5]]
//
v64accfloat test_negmul_8x8_8x8T(v64bfp16ebs8 a, v64bfp16ebs8 b) {
  return negmul_8x8_8x8T(a, b);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z17test_mac_8x8_8x8T12v64bfp16ebs8S_Dv64_u10__accfloat(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], [[STRUCT_V64BFP16EBS8]] [[B_COERCE:%.*]], <64 x float> inreg noundef [[ACC:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <64 x float> [[ACC]] to <64 x i32>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mac.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <8 x i8> [[TMP3]], <64 x i32> [[TMP4]], i32 780)
// CHECK-NEXT:    [[TMP6:%.*]] = bitcast <64 x i32> [[TMP5]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP6]]
//
v64accfloat test_mac_8x8_8x8T(v64bfp16ebs8 a, v64bfp16ebs8 b, v64accfloat acc) {
  return mac_8x8_8x8T(a, b, acc);
}
//
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z17test_msc_8x8_8x8T12v64bfp16ebs8S_Dv64_u10__accfloat(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], [[STRUCT_V64BFP16EBS8]] [[B_COERCE:%.*]], <64 x float> inreg noundef [[ACC:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <64 x float> [[ACC]] to <64 x i32>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.msc.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <8 x i8> [[TMP3]], <64 x i32> [[TMP4]], i32 780)
// CHECK-NEXT:    [[TMP6:%.*]] = bitcast <64 x i32> [[TMP5]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP6]]
//
v64accfloat test_msc_8x8_8x8T(v64bfp16ebs8 a, v64bfp16ebs8 b, v64accfloat acc) {
  return msc_8x8_8x8T(a, b, acc);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z20test_addmac_8x8_8x8T12v64bfp16ebs8S_Dv64_u10__accfloatS0_(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], [[STRUCT_V64BFP16EBS8]] [[B_COERCE:%.*]], <64 x float> inreg noundef [[ACC1:%.*]], <64 x float> inreg noundef [[ACC2:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <64 x float> [[ACC1]] to <64 x i32>
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <64 x float> [[ACC2]] to <64 x i32>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.addmac.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <8 x i8> [[TMP3]], <64 x i32> [[TMP4]], <64 x i32> [[TMP5]], i32 780)
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <64 x i32> [[TMP6]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP7]]
//
v64accfloat test_addmac_8x8_8x8T(v64bfp16ebs8 a, v64bfp16ebs8 b,
                                 v64accfloat acc1, v64accfloat acc2) {
  return addmac_8x8_8x8T(a, b, acc1, acc2);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z20test_addmsc_8x8_8x8T12v64bfp16ebs8S_Dv64_u10__accfloatS0_(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], [[STRUCT_V64BFP16EBS8]] [[B_COERCE:%.*]], <64 x float> inreg noundef [[ACC1:%.*]], <64 x float> inreg noundef [[ACC2:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <64 x float> [[ACC1]] to <64 x i32>
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <64 x float> [[ACC2]] to <64 x i32>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.addmsc.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <8 x i8> [[TMP3]], <64 x i32> [[TMP4]], <64 x i32> [[TMP5]], i32 780)
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <64 x i32> [[TMP6]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP7]]
//
v64accfloat test_addmsc_8x8_8x8T(v64bfp16ebs8 a, v64bfp16ebs8 b,
                                 v64accfloat acc1, v64accfloat acc2) {
  return addmsc_8x8_8x8T(a, b, acc1, acc2);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z17test_mul_8x8_8x8T12v64bfp16ebs8iS_i(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], i32 noundef [[SGN_X:%.*]], [[STRUCT_V64BFP16EBS8]] [[B_COERCE:%.*]], i32 noundef [[SGN_Y:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[SHL14_I_I:%.*]] = shl i32 [[SGN_X]], 9
// CHECK-NEXT:    [[SHL15_I_I:%.*]] = shl i32 [[SGN_Y]], 8
// CHECK-NEXT:    [[OR16_I_I:%.*]] = or i32 [[SHL14_I_I]], [[SHL15_I_I]]
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or disjoint i32 [[OR16_I_I]], 12
// CHECK-NEXT:    [[TMP4:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mul.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <8 x i8> [[TMP3]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <64 x i32> [[TMP4]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP5]]
//
v64accfloat test_mul_8x8_8x8T(v64bfp16ebs8 a, int sgn_x, v64bfp16ebs8 b,
                              int sgn_y) {
  return mul_8x8_8x8T(a, sgn_x, b, sgn_y);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z20test_negmul_8x8_8x8T12v64bfp16ebs8iS_i(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], i32 noundef [[SGN_X:%.*]], [[STRUCT_V64BFP16EBS8]] [[B_COERCE:%.*]], i32 noundef [[SGN_Y:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[SHL14_I_I:%.*]] = shl i32 [[SGN_X]], 9
// CHECK-NEXT:    [[SHL15_I_I:%.*]] = shl i32 [[SGN_Y]], 8
// CHECK-NEXT:    [[OR16_I_I:%.*]] = or i32 [[SHL14_I_I]], [[SHL15_I_I]]
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or disjoint i32 [[OR16_I_I]], 12
// CHECK-NEXT:    [[TMP4:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.negmul.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <8 x i8> [[TMP3]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <64 x i32> [[TMP4]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP5]]
//
v64accfloat test_negmul_8x8_8x8T(v64bfp16ebs8 a, int sgn_x, v64bfp16ebs8 b,
                                 int sgn_y) {
  return negmul_8x8_8x8T(a, sgn_x, b, sgn_y);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z17test_mac_8x8_8x8T12v64bfp16ebs8iS_iDv64_u10__accfloat(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], i32 noundef [[SGN_X:%.*]], [[STRUCT_V64BFP16EBS8]] [[B_COERCE:%.*]], i32 noundef [[SGN_Y:%.*]], <64 x float> inreg noundef [[ACC:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[SHL14_I_I:%.*]] = shl i32 [[SGN_X]], 9
// CHECK-NEXT:    [[SHL15_I_I:%.*]] = shl i32 [[SGN_Y]], 8
// CHECK-NEXT:    [[OR16_I_I:%.*]] = or i32 [[SHL14_I_I]], [[SHL15_I_I]]
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or disjoint i32 [[OR16_I_I]], 12
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <64 x float> [[ACC]] to <64 x i32>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mac.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <8 x i8> [[TMP3]], <64 x i32> [[TMP4]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP6:%.*]] = bitcast <64 x i32> [[TMP5]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP6]]
//
v64accfloat test_mac_8x8_8x8T(v64bfp16ebs8 a, int sgn_x, v64bfp16ebs8 b,
                              int sgn_y, v64accfloat acc) {
  return mac_8x8_8x8T(a, sgn_x, b, sgn_y, acc);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z17test_msc_8x8_8x8T12v64bfp16ebs8iS_iDv64_u10__accfloat(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], i32 noundef [[SGN_X:%.*]], [[STRUCT_V64BFP16EBS8]] [[B_COERCE:%.*]], i32 noundef [[SGN_Y:%.*]], <64 x float> inreg noundef [[ACC:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[SHL14_I_I:%.*]] = shl i32 [[SGN_X]], 9
// CHECK-NEXT:    [[SHL15_I_I:%.*]] = shl i32 [[SGN_Y]], 8
// CHECK-NEXT:    [[OR16_I_I:%.*]] = or i32 [[SHL14_I_I]], [[SHL15_I_I]]
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or disjoint i32 [[OR16_I_I]], 12
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <64 x float> [[ACC]] to <64 x i32>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.msc.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <8 x i8> [[TMP3]], <64 x i32> [[TMP4]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP6:%.*]] = bitcast <64 x i32> [[TMP5]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP6]]
//
v64accfloat test_msc_8x8_8x8T(v64bfp16ebs8 a, int sgn_x, v64bfp16ebs8 b,
                              int sgn_y, v64accfloat acc) {
  return msc_8x8_8x8T(a, sgn_x, b, sgn_y, acc);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z20test_addmac_8x8_8x8T12v64bfp16ebs8iS_iDv64_u10__accfloatS0_(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], i32 noundef [[SGN_X:%.*]], [[STRUCT_V64BFP16EBS8]] [[B_COERCE:%.*]], i32 noundef [[SGN_Y:%.*]], <64 x float> inreg noundef [[ACC1:%.*]], <64 x float> inreg noundef [[ACC2:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[SHL14_I_I:%.*]] = shl i32 [[SGN_X]], 9
// CHECK-NEXT:    [[SHL15_I_I:%.*]] = shl i32 [[SGN_Y]], 8
// CHECK-NEXT:    [[OR16_I_I:%.*]] = or i32 [[SHL14_I_I]], [[SHL15_I_I]]
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or disjoint i32 [[OR16_I_I]], 12
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <64 x float> [[ACC1]] to <64 x i32>
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <64 x float> [[ACC2]] to <64 x i32>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.addmac.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <8 x i8> [[TMP3]], <64 x i32> [[TMP4]], <64 x i32> [[TMP5]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <64 x i32> [[TMP6]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP7]]
//
v64accfloat test_addmac_8x8_8x8T(v64bfp16ebs8 a, int sgn_x, v64bfp16ebs8 b,
                                 int sgn_y, v64accfloat acc1,
                                 v64accfloat acc2) {
  return addmac_8x8_8x8T(a, sgn_x, b, sgn_y, acc1, acc2);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z20test_addmsc_8x8_8x8T12v64bfp16ebs8iS_iDv64_u10__accfloatS0_(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], i32 noundef [[SGN_X:%.*]], [[STRUCT_V64BFP16EBS8]] [[B_COERCE:%.*]], i32 noundef [[SGN_Y:%.*]], <64 x float> inreg noundef [[ACC1:%.*]], <64 x float> inreg noundef [[ACC2:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[SHL14_I_I:%.*]] = shl i32 [[SGN_X]], 9
// CHECK-NEXT:    [[SHL15_I_I:%.*]] = shl i32 [[SGN_Y]], 8
// CHECK-NEXT:    [[OR16_I_I:%.*]] = or i32 [[SHL14_I_I]], [[SHL15_I_I]]
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or disjoint i32 [[OR16_I_I]], 12
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <64 x float> [[ACC1]] to <64 x i32>
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <64 x float> [[ACC2]] to <64 x i32>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.addmsc.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <8 x i8> [[TMP3]], <64 x i32> [[TMP4]], <64 x i32> [[TMP5]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <64 x i32> [[TMP6]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP7]]
//
v64accfloat test_addmsc_8x8_8x8T(v64bfp16ebs8 a, int sgn_x, v64bfp16ebs8 b,
                                 int sgn_y, v64accfloat acc1,
                                 v64accfloat acc2) {
  return addmsc_8x8_8x8T(a, sgn_x, b, sgn_y, acc1, acc2);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z22test_mul_8x8_8x8T_conf12v64bfp16ebs8S_i(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], [[STRUCT_V64BFP16EBS8]] [[B_COERCE:%.*]], i32 noundef [[SUB_MUL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[SHL2_I_I:%.*]] = shl i32 [[SUB_MUL]], 11
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or disjoint i32 [[SHL2_I_I]], 780
// CHECK-NEXT:    [[TMP4:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mul.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <8 x i8> [[TMP3]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <64 x i32> [[TMP4]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP5]]
//
v64accfloat test_mul_8x8_8x8T_conf(v64bfp16ebs8 a, v64bfp16ebs8 b,
                                   int sub_mul) {
  return mul_8x8_8x8T_conf(a, b, sub_mul);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z25test_negmul_8x8_8x8T_conf12v64bfp16ebs8S_i(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], [[STRUCT_V64BFP16EBS8]] [[B_COERCE:%.*]], i32 noundef [[SUB_MUL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[SHL2_I_I:%.*]] = shl i32 [[SUB_MUL]], 11
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or disjoint i32 [[SHL2_I_I]], 780
// CHECK-NEXT:    [[TMP4:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.negmul.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <8 x i8> [[TMP3]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <64 x i32> [[TMP4]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP5]]
//
v64accfloat test_negmul_8x8_8x8T_conf(v64bfp16ebs8 a, v64bfp16ebs8 b,
                                      int sub_mul) {
  return negmul_8x8_8x8T_conf(a, b, sub_mul);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z22test_mac_8x8_8x8T_conf12v64bfp16ebs8S_Dv64_u10__accfloatiii(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], [[STRUCT_V64BFP16EBS8]] [[B_COERCE:%.*]], <64 x float> inreg noundef [[ACC:%.*]], i32 noundef [[ZERO_ACC:%.*]], i32 noundef [[SUB_MUL:%.*]], i32 noundef [[SUB_ACC1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[SHL2_I_I:%.*]] = shl i32 [[SUB_MUL]], 11
// CHECK-NEXT:    [[SHL4_I_I:%.*]] = shl i32 [[SUB_ACC1]], 12
// CHECK-NEXT:    [[OR5_I_I:%.*]] = or i32 [[ZERO_ACC]], [[SHL2_I_I]]
// CHECK-NEXT:    [[OR13_I_I:%.*]] = or i32 [[OR5_I_I]], [[SHL4_I_I]]
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or i32 [[OR13_I_I]], 780
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <64 x float> [[ACC]] to <64 x i32>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mac.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <8 x i8> [[TMP3]], <64 x i32> [[TMP4]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP6:%.*]] = bitcast <64 x i32> [[TMP5]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP6]]
//
v64accfloat test_mac_8x8_8x8T_conf(v64bfp16ebs8 a, v64bfp16ebs8 b,
                                   v64accfloat acc, int zero_acc, int sub_mul,
                                   int sub_acc1) {
  return mac_8x8_8x8T_conf(a, b, acc, zero_acc, sub_mul, sub_acc1);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z22test_msc_8x8_8x8T_conf12v64bfp16ebs8S_Dv64_u10__accfloatiii(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], [[STRUCT_V64BFP16EBS8]] [[B_COERCE:%.*]], <64 x float> inreg noundef [[ACC:%.*]], i32 noundef [[ZERO_ACC:%.*]], i32 noundef [[SUB_MUL:%.*]], i32 noundef [[SUB_ACC1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[SHL2_I_I:%.*]] = shl i32 [[SUB_MUL]], 11
// CHECK-NEXT:    [[SHL4_I_I:%.*]] = shl i32 [[SUB_ACC1]], 12
// CHECK-NEXT:    [[OR5_I_I:%.*]] = or i32 [[ZERO_ACC]], [[SHL2_I_I]]
// CHECK-NEXT:    [[OR13_I_I:%.*]] = or i32 [[OR5_I_I]], [[SHL4_I_I]]
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or i32 [[OR13_I_I]], 780
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <64 x float> [[ACC]] to <64 x i32>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.msc.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <8 x i8> [[TMP3]], <64 x i32> [[TMP4]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP6:%.*]] = bitcast <64 x i32> [[TMP5]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP6]]
//
v64accfloat test_msc_8x8_8x8T_conf(v64bfp16ebs8 a, v64bfp16ebs8 b,
                                   v64accfloat acc, int zero_acc, int sub_mul,
                                   int sub_acc1) {
  return msc_8x8_8x8T_conf(a, b, acc, zero_acc, sub_mul, sub_acc1);
}
//
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z25test_addmac_8x8_8x8T_conf12v64bfp16ebs8S_Dv64_u10__accfloatS0_iiii(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], [[STRUCT_V64BFP16EBS8]] [[B_COERCE:%.*]], <64 x float> inreg noundef [[ACC1:%.*]], <64 x float> inreg noundef [[ACC2:%.*]], i32 noundef [[ZERO_ACC1:%.*]], i32 noundef [[SUB_MUL:%.*]], i32 noundef [[SUB_ACC1:%.*]], i32 noundef [[SUB_ACC2:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[SHL2_I_I:%.*]] = shl i32 [[SUB_MUL]], 11
// CHECK-NEXT:    [[SHL4_I_I:%.*]] = shl i32 [[SUB_ACC1]], 12
// CHECK-NEXT:    [[SHL6_I_I:%.*]] = shl i32 [[SUB_ACC2]], 13
// CHECK-NEXT:    [[OR5_I_I:%.*]] = or i32 [[ZERO_ACC1]], [[SHL2_I_I]]
// CHECK-NEXT:    [[OR7_I_I:%.*]] = or i32 [[OR5_I_I]], [[SHL4_I_I]]
// CHECK-NEXT:    [[OR13_I_I:%.*]] = or i32 [[OR7_I_I]], [[SHL6_I_I]]
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or i32 [[OR13_I_I]], 780
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <64 x float> [[ACC1]] to <64 x i32>
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <64 x float> [[ACC2]] to <64 x i32>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.addmac.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <8 x i8> [[TMP3]], <64 x i32> [[TMP4]], <64 x i32> [[TMP5]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <64 x i32> [[TMP6]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP7]]
//
v64accfloat test_addmac_8x8_8x8T_conf(v64bfp16ebs8 a, v64bfp16ebs8 b,
                                      v64accfloat acc1, v64accfloat acc2,
                                      int zero_acc1, int sub_mul, int sub_acc1,
                                      int sub_acc2) {
  return addmac_8x8_8x8T_conf(a, b, acc1, acc2, zero_acc1, sub_mul, sub_acc1,
                              sub_acc2);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z25test_addmsc_8x8_8x8T_conf12v64bfp16ebs8S_Dv64_u10__accfloatS0_iiii(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], [[STRUCT_V64BFP16EBS8]] [[B_COERCE:%.*]], <64 x float> inreg noundef [[ACC1:%.*]], <64 x float> inreg noundef [[ACC2:%.*]], i32 noundef [[ZERO_ACC1:%.*]], i32 noundef [[SUB_MUL:%.*]], i32 noundef [[SUB_ACC1:%.*]], i32 noundef [[SUB_ACC2:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[SHL2_I_I:%.*]] = shl i32 [[SUB_MUL]], 11
// CHECK-NEXT:    [[SHL4_I_I:%.*]] = shl i32 [[SUB_ACC1]], 12
// CHECK-NEXT:    [[SHL6_I_I:%.*]] = shl i32 [[SUB_ACC2]], 13
// CHECK-NEXT:    [[OR5_I_I:%.*]] = or i32 [[ZERO_ACC1]], [[SHL2_I_I]]
// CHECK-NEXT:    [[OR7_I_I:%.*]] = or i32 [[OR5_I_I]], [[SHL4_I_I]]
// CHECK-NEXT:    [[OR13_I_I:%.*]] = or i32 [[OR7_I_I]], [[SHL6_I_I]]
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or i32 [[OR13_I_I]], 780
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <64 x float> [[ACC1]] to <64 x i32>
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <64 x float> [[ACC2]] to <64 x i32>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.addmsc.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <8 x i8> [[TMP3]], <64 x i32> [[TMP4]], <64 x i32> [[TMP5]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <64 x i32> [[TMP6]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP7]]
//
v64accfloat test_addmsc_8x8_8x8T_conf(v64bfp16ebs8 a, v64bfp16ebs8 b,
                                      v64accfloat acc1, v64accfloat acc2,
                                      int zero_acc1, int sub_mul, int sub_acc1,
                                      int sub_acc2) {
  return addmsc_8x8_8x8T_conf(a, b, acc1, acc2, zero_acc1, sub_mul, sub_acc1,
                              sub_acc2);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z22test_mul_8x8_8x8T_conf12v64bfp16ebs8iS_ii(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], i32 noundef [[SGN_X:%.*]], [[STRUCT_V64BFP16EBS8]] [[B_COERCE:%.*]], i32 noundef [[SGN_Y:%.*]], i32 noundef [[SUB_MUL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[SHL2_I_I:%.*]] = shl i32 [[SUB_MUL]], 11
// CHECK-NEXT:    [[SHL14_I_I:%.*]] = shl i32 [[SGN_X]], 9
// CHECK-NEXT:    [[SHL15_I_I:%.*]] = shl i32 [[SGN_Y]], 8
// CHECK-NEXT:    [[OR16_I_I:%.*]] = or i32 [[SHL14_I_I]], [[SHL15_I_I]]
// CHECK-NEXT:    [[OR17_I_I:%.*]] = or i32 [[OR16_I_I]], [[SHL2_I_I]]
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or disjoint i32 [[OR17_I_I]], 12
// CHECK-NEXT:    [[TMP4:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mul.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <8 x i8> [[TMP3]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <64 x i32> [[TMP4]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP5]]
//
v64accfloat test_mul_8x8_8x8T_conf(v64bfp16ebs8 a, int sgn_x, v64bfp16ebs8 b,
                                   int sgn_y, int sub_mul) {
  return mul_8x8_8x8T_conf(a, sgn_x, b, sgn_y, sub_mul);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z25test_negmul_8x8_8x8T_conf12v64bfp16ebs8iS_ii(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], i32 noundef [[SGN_X:%.*]], [[STRUCT_V64BFP16EBS8]] [[B_COERCE:%.*]], i32 noundef [[SGN_Y:%.*]], i32 noundef [[SUB_MUL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[SHL2_I_I:%.*]] = shl i32 [[SUB_MUL]], 11
// CHECK-NEXT:    [[SHL14_I_I:%.*]] = shl i32 [[SGN_X]], 9
// CHECK-NEXT:    [[SHL15_I_I:%.*]] = shl i32 [[SGN_Y]], 8
// CHECK-NEXT:    [[OR16_I_I:%.*]] = or i32 [[SHL14_I_I]], [[SHL15_I_I]]
// CHECK-NEXT:    [[OR17_I_I:%.*]] = or i32 [[OR16_I_I]], [[SHL2_I_I]]
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or disjoint i32 [[OR17_I_I]], 12
// CHECK-NEXT:    [[TMP4:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.negmul.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <8 x i8> [[TMP3]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <64 x i32> [[TMP4]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP5]]
//
v64accfloat test_negmul_8x8_8x8T_conf(v64bfp16ebs8 a, int sgn_x, v64bfp16ebs8 b,
                                      int sgn_y, int sub_mul) {
  return negmul_8x8_8x8T_conf(a, sgn_x, b, sgn_y, sub_mul);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z22test_mac_8x8_8x8T_conf12v64bfp16ebs8iS_iDv64_u10__accfloatiii(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], i32 noundef [[SGN_X:%.*]], [[STRUCT_V64BFP16EBS8]] [[B_COERCE:%.*]], i32 noundef [[SGN_Y:%.*]], <64 x float> inreg noundef [[ACC:%.*]], i32 noundef [[ZERO_ACC:%.*]], i32 noundef [[SUB_MUL:%.*]], i32 noundef [[SUB_ACC1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[SHL2_I_I:%.*]] = shl i32 [[SUB_MUL]], 11
// CHECK-NEXT:    [[SHL4_I_I:%.*]] = shl i32 [[SUB_ACC1]], 12
// CHECK-NEXT:    [[SHL14_I_I:%.*]] = shl i32 [[SGN_X]], 9
// CHECK-NEXT:    [[SHL15_I_I:%.*]] = shl i32 [[SGN_Y]], 8
// CHECK-NEXT:    [[OR5_I_I:%.*]] = or i32 [[SHL14_I_I]], [[SHL15_I_I]]
// CHECK-NEXT:    [[OR16_I_I:%.*]] = or i32 [[OR5_I_I]], [[ZERO_ACC]]
// CHECK-NEXT:    [[OR13_I_I:%.*]] = or i32 [[OR16_I_I]], [[SHL2_I_I]]
// CHECK-NEXT:    [[OR17_I_I:%.*]] = or i32 [[OR13_I_I]], [[SHL4_I_I]]
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or i32 [[OR17_I_I]], 12
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <64 x float> [[ACC]] to <64 x i32>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mac.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <8 x i8> [[TMP3]], <64 x i32> [[TMP4]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP6:%.*]] = bitcast <64 x i32> [[TMP5]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP6]]
//
v64accfloat test_mac_8x8_8x8T_conf(v64bfp16ebs8 a, int sgn_x, v64bfp16ebs8 b,
                                   int sgn_y, v64accfloat acc, int zero_acc,
                                   int sub_mul, int sub_acc1) {
  return mac_8x8_8x8T_conf(a, sgn_x, b, sgn_y, acc, zero_acc, sub_mul,
                           sub_acc1);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z22test_msc_8x8_8x8T_conf12v64bfp16ebs8iS_iDv64_u10__accfloatiii(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], i32 noundef [[SGN_X:%.*]], [[STRUCT_V64BFP16EBS8]] [[B_COERCE:%.*]], i32 noundef [[SGN_Y:%.*]], <64 x float> inreg noundef [[ACC:%.*]], i32 noundef [[ZERO_ACC:%.*]], i32 noundef [[SUB_MUL:%.*]], i32 noundef [[SUB_ACC1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[SHL2_I_I:%.*]] = shl i32 [[SUB_MUL]], 11
// CHECK-NEXT:    [[SHL4_I_I:%.*]] = shl i32 [[SUB_ACC1]], 12
// CHECK-NEXT:    [[SHL14_I_I:%.*]] = shl i32 [[SGN_X]], 9
// CHECK-NEXT:    [[SHL15_I_I:%.*]] = shl i32 [[SGN_Y]], 8
// CHECK-NEXT:    [[OR5_I_I:%.*]] = or i32 [[SHL14_I_I]], [[SHL15_I_I]]
// CHECK-NEXT:    [[OR16_I_I:%.*]] = or i32 [[OR5_I_I]], [[ZERO_ACC]]
// CHECK-NEXT:    [[OR13_I_I:%.*]] = or i32 [[OR16_I_I]], [[SHL2_I_I]]
// CHECK-NEXT:    [[OR17_I_I:%.*]] = or i32 [[OR13_I_I]], [[SHL4_I_I]]
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or i32 [[OR17_I_I]], 12
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <64 x float> [[ACC]] to <64 x i32>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.msc.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <8 x i8> [[TMP3]], <64 x i32> [[TMP4]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP6:%.*]] = bitcast <64 x i32> [[TMP5]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP6]]
//
v64accfloat test_msc_8x8_8x8T_conf(v64bfp16ebs8 a, int sgn_x, v64bfp16ebs8 b,
                                   int sgn_y, v64accfloat acc, int zero_acc,
                                   int sub_mul, int sub_acc1) {
  return msc_8x8_8x8T_conf(a, sgn_x, b, sgn_y, acc, zero_acc, sub_mul,
                           sub_acc1);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z25test_addmac_8x8_8x8T_conf12v64bfp16ebs8iS_iDv64_u10__accfloatS0_iiii(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], i32 noundef [[SGN_X:%.*]], [[STRUCT_V64BFP16EBS8]] [[B_COERCE:%.*]], i32 noundef [[SGN_Y:%.*]], <64 x float> inreg noundef [[ACC1:%.*]], <64 x float> inreg noundef [[ACC2:%.*]], i32 noundef [[ZERO_ACC1:%.*]], i32 noundef [[SUB_MUL:%.*]], i32 noundef [[SUB_ACC1:%.*]], i32 noundef [[SUB_ACC2:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[SHL2_I_I:%.*]] = shl i32 [[SUB_MUL]], 11
// CHECK-NEXT:    [[SHL4_I_I:%.*]] = shl i32 [[SUB_ACC1]], 12
// CHECK-NEXT:    [[SHL6_I_I:%.*]] = shl i32 [[SUB_ACC2]], 13
// CHECK-NEXT:    [[SHL14_I_I:%.*]] = shl i32 [[SGN_X]], 9
// CHECK-NEXT:    [[SHL15_I_I:%.*]] = shl i32 [[SGN_Y]], 8
// CHECK-NEXT:    [[OR5_I_I:%.*]] = or i32 [[SHL14_I_I]], [[SHL15_I_I]]
// CHECK-NEXT:    [[OR7_I_I:%.*]] = or i32 [[OR5_I_I]], [[ZERO_ACC1]]
// CHECK-NEXT:    [[OR16_I_I:%.*]] = or i32 [[OR7_I_I]], [[SHL2_I_I]]
// CHECK-NEXT:    [[OR13_I_I:%.*]] = or i32 [[OR16_I_I]], [[SHL4_I_I]]
// CHECK-NEXT:    [[OR17_I_I:%.*]] = or i32 [[OR13_I_I]], [[SHL6_I_I]]
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or i32 [[OR17_I_I]], 12
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <64 x float> [[ACC1]] to <64 x i32>
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <64 x float> [[ACC2]] to <64 x i32>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.addmac.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <8 x i8> [[TMP3]], <64 x i32> [[TMP4]], <64 x i32> [[TMP5]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <64 x i32> [[TMP6]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP7]]
//
v64accfloat test_addmac_8x8_8x8T_conf(v64bfp16ebs8 a, int sgn_x, v64bfp16ebs8 b,
                                      int sgn_y, v64accfloat acc1,
                                      v64accfloat acc2, int zero_acc1,
                                      int sub_mul, int sub_acc1, int sub_acc2) {
  return addmac_8x8_8x8T_conf(a, sgn_x, b, sgn_y, acc1, acc2, zero_acc1,
                              sub_mul, sub_acc1, sub_acc2);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z25test_addmsc_8x8_8x8T_conf12v64bfp16ebs8iS_iDv64_u10__accfloatS0_iiii(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], i32 noundef [[SGN_X:%.*]], [[STRUCT_V64BFP16EBS8]] [[B_COERCE:%.*]], i32 noundef [[SGN_Y:%.*]], <64 x float> inreg noundef [[ACC1:%.*]], <64 x float> inreg noundef [[ACC2:%.*]], i32 noundef [[ZERO_ACC1:%.*]], i32 noundef [[SUB_MUL:%.*]], i32 noundef [[SUB_ACC1:%.*]], i32 noundef [[SUB_ACC2:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[SHL2_I_I:%.*]] = shl i32 [[SUB_MUL]], 11
// CHECK-NEXT:    [[SHL4_I_I:%.*]] = shl i32 [[SUB_ACC1]], 12
// CHECK-NEXT:    [[SHL6_I_I:%.*]] = shl i32 [[SUB_ACC2]], 13
// CHECK-NEXT:    [[SHL14_I_I:%.*]] = shl i32 [[SGN_X]], 9
// CHECK-NEXT:    [[SHL15_I_I:%.*]] = shl i32 [[SGN_Y]], 8
// CHECK-NEXT:    [[OR5_I_I:%.*]] = or i32 [[SHL14_I_I]], [[SHL15_I_I]]
// CHECK-NEXT:    [[OR7_I_I:%.*]] = or i32 [[OR5_I_I]], [[ZERO_ACC1]]
// CHECK-NEXT:    [[OR16_I_I:%.*]] = or i32 [[OR7_I_I]], [[SHL2_I_I]]
// CHECK-NEXT:    [[OR13_I_I:%.*]] = or i32 [[OR16_I_I]], [[SHL4_I_I]]
// CHECK-NEXT:    [[OR17_I_I:%.*]] = or i32 [[OR13_I_I]], [[SHL6_I_I]]
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or i32 [[OR17_I_I]], 12
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <64 x float> [[ACC1]] to <64 x i32>
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <64 x float> [[ACC2]] to <64 x i32>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.addmsc.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <8 x i8> [[TMP3]], <64 x i32> [[TMP4]], <64 x i32> [[TMP5]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <64 x i32> [[TMP6]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP7]]
//
v64accfloat test_addmsc_8x8_8x8T_conf(v64bfp16ebs8 a, int sgn_x, v64bfp16ebs8 b,
                                      int sgn_y, v64accfloat acc1,
                                      v64accfloat acc2, int zero_acc1,
                                      int sub_mul, int sub_acc1, int sub_acc2) {
  return addmsc_8x8_8x8T_conf(a, sgn_x, b, sgn_y, acc1, acc2, zero_acc1,
                              sub_mul, sub_acc1, sub_acc2);
};

// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z18test_mul_4x8_8x16T12v64bfp16ebs813v128bfp16ebs8(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], [[STRUCT_V128BFP16EBS8:%.*]] [[B_COERCE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 2
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 3
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.mul.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <64 x i8> [[TMP3]], <8 x i8> [[TMP4]], <8 x i8> [[TMP5]], i32 972)
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <64 x i32> [[TMP6]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP7]]
//
v64accfloat test_mul_4x8_8x16T(v64bfp16ebs8 a, v128bfp16ebs8 b) {
  return mul_4x8_8x16T(a, b);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z21test_negmul_4x8_8x16T12v64bfp16ebs813v128bfp16ebs8(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], [[STRUCT_V128BFP16EBS8:%.*]] [[B_COERCE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 2
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 3
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.negmul.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <64 x i8> [[TMP3]], <8 x i8> [[TMP4]], <8 x i8> [[TMP5]], i32 972)
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <64 x i32> [[TMP6]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP7]]
//
v64accfloat test_negmul_4x8_8x16T(v64bfp16ebs8 a, v128bfp16ebs8 b) {
  return negmul_4x8_8x16T(a, b);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z18test_mac_4x8_8x16T12v64bfp16ebs813v128bfp16ebs8Dv64_u10__accfloat(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], [[STRUCT_V128BFP16EBS8:%.*]] [[B_COERCE:%.*]], <64 x float> inreg noundef [[ACC:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 2
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 3
// CHECK-NEXT:    [[TMP6:%.*]] = bitcast <64 x float> [[ACC]] to <64 x i32>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.mac.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <64 x i8> [[TMP3]], <8 x i8> [[TMP4]], <8 x i8> [[TMP5]], <64 x i32> [[TMP6]], i32 972)
// CHECK-NEXT:    [[TMP8:%.*]] = bitcast <64 x i32> [[TMP7]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP8]]
//
v64accfloat test_mac_4x8_8x16T(v64bfp16ebs8 a, v128bfp16ebs8 b,
                               v64accfloat acc) {
  return mac_4x8_8x16T(a, b, acc);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z18test_msc_4x8_8x16T12v64bfp16ebs813v128bfp16ebs8Dv64_u10__accfloat(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], [[STRUCT_V128BFP16EBS8:%.*]] [[B_COERCE:%.*]], <64 x float> inreg noundef [[ACC:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 2
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 3
// CHECK-NEXT:    [[TMP6:%.*]] = bitcast <64 x float> [[ACC]] to <64 x i32>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.msc.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <64 x i8> [[TMP3]], <8 x i8> [[TMP4]], <8 x i8> [[TMP5]], <64 x i32> [[TMP6]], i32 972)
// CHECK-NEXT:    [[TMP8:%.*]] = bitcast <64 x i32> [[TMP7]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP8]]
//
v64accfloat test_msc_4x8_8x16T(v64bfp16ebs8 a, v128bfp16ebs8 b,
                               v64accfloat acc) {
  return msc_4x8_8x16T(a, b, acc);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z21test_addmac_4x8_8x16T12v64bfp16ebs813v128bfp16ebs8Dv64_u10__accfloatS1_(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], [[STRUCT_V128BFP16EBS8:%.*]] [[B_COERCE:%.*]], <64 x float> inreg noundef [[ACC1:%.*]], <64 x float> inreg noundef [[ACC2:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 2
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 3
// CHECK-NEXT:    [[TMP6:%.*]] = bitcast <64 x float> [[ACC1]] to <64 x i32>
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <64 x float> [[ACC2]] to <64 x i32>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.addmac.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <64 x i8> [[TMP3]], <8 x i8> [[TMP4]], <8 x i8> [[TMP5]], <64 x i32> [[TMP6]], <64 x i32> [[TMP7]], i32 972)
// CHECK-NEXT:    [[TMP9:%.*]] = bitcast <64 x i32> [[TMP8]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP9]]
//
v64accfloat test_addmac_4x8_8x16T(v64bfp16ebs8 a, v128bfp16ebs8 b,
                                  v64accfloat acc1, v64accfloat acc2) {
  return addmac_4x8_8x16T(a, b, acc1, acc2);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z21test_addmsc_4x8_8x16T12v64bfp16ebs813v128bfp16ebs8Dv64_u10__accfloatS1_(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], [[STRUCT_V128BFP16EBS8:%.*]] [[B_COERCE:%.*]], <64 x float> inreg noundef [[ACC1:%.*]], <64 x float> inreg noundef [[ACC2:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 2
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 3
// CHECK-NEXT:    [[TMP6:%.*]] = bitcast <64 x float> [[ACC1]] to <64 x i32>
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <64 x float> [[ACC2]] to <64 x i32>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.addmsc.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <64 x i8> [[TMP3]], <8 x i8> [[TMP4]], <8 x i8> [[TMP5]], <64 x i32> [[TMP6]], <64 x i32> [[TMP7]], i32 972)
// CHECK-NEXT:    [[TMP9:%.*]] = bitcast <64 x i32> [[TMP8]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP9]]
//
v64accfloat test_addmsc_4x8_8x16T(v64bfp16ebs8 a, v128bfp16ebs8 b,
                                  v64accfloat acc1, v64accfloat acc2) {
  return addmsc_4x8_8x16T(a, b, acc1, acc2);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z18test_mul_4x8_8x16T12v64bfp16ebs8i13v128bfp16ebs8i(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], i32 noundef [[SGN_X:%.*]], [[STRUCT_V128BFP16EBS8:%.*]] [[B_COERCE:%.*]], i32 noundef [[SGN_Y:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 2
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 3
// CHECK-NEXT:    [[SHL14_I_I:%.*]] = shl i32 [[SGN_X]], 9
// CHECK-NEXT:    [[SHL15_I_I:%.*]] = shl i32 [[SGN_Y]], 8
// CHECK-NEXT:    [[OR16_I_I:%.*]] = or i32 [[SHL14_I_I]], [[SHL15_I_I]]
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or disjoint i32 [[OR16_I_I]], 204
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.mul.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <64 x i8> [[TMP3]], <8 x i8> [[TMP4]], <8 x i8> [[TMP5]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <64 x i32> [[TMP6]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP7]]
//
v64accfloat test_mul_4x8_8x16T(v64bfp16ebs8 a, int sgn_x, v128bfp16ebs8 b,
                               int sgn_y) {
  return mul_4x8_8x16T(a, sgn_x, b, sgn_y);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z21test_negmul_4x8_8x16T12v64bfp16ebs8i13v128bfp16ebs8i(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], i32 noundef [[SGN_X:%.*]], [[STRUCT_V128BFP16EBS8:%.*]] [[B_COERCE:%.*]], i32 noundef [[SGN_Y:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 2
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 3
// CHECK-NEXT:    [[SHL14_I_I:%.*]] = shl i32 [[SGN_X]], 9
// CHECK-NEXT:    [[SHL15_I_I:%.*]] = shl i32 [[SGN_Y]], 8
// CHECK-NEXT:    [[OR16_I_I:%.*]] = or i32 [[SHL14_I_I]], [[SHL15_I_I]]
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or disjoint i32 [[OR16_I_I]], 204
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.negmul.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <64 x i8> [[TMP3]], <8 x i8> [[TMP4]], <8 x i8> [[TMP5]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <64 x i32> [[TMP6]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP7]]
//
v64accfloat test_negmul_4x8_8x16T(v64bfp16ebs8 a, int sgn_x, v128bfp16ebs8 b,
                                  int sgn_y) {
  return negmul_4x8_8x16T(a, sgn_x, b, sgn_y);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z18test_mac_4x8_8x16T12v64bfp16ebs8i13v128bfp16ebs8iDv64_u10__accfloat(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], i32 noundef [[SGN_X:%.*]], [[STRUCT_V128BFP16EBS8:%.*]] [[B_COERCE:%.*]], i32 noundef [[SGN_Y:%.*]], <64 x float> inreg noundef [[ACC:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 2
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 3
// CHECK-NEXT:    [[SHL14_I_I:%.*]] = shl i32 [[SGN_X]], 9
// CHECK-NEXT:    [[SHL15_I_I:%.*]] = shl i32 [[SGN_Y]], 8
// CHECK-NEXT:    [[OR16_I_I:%.*]] = or i32 [[SHL14_I_I]], [[SHL15_I_I]]
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or disjoint i32 [[OR16_I_I]], 204
// CHECK-NEXT:    [[TMP6:%.*]] = bitcast <64 x float> [[ACC]] to <64 x i32>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.mac.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <64 x i8> [[TMP3]], <8 x i8> [[TMP4]], <8 x i8> [[TMP5]], <64 x i32> [[TMP6]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP8:%.*]] = bitcast <64 x i32> [[TMP7]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP8]]
//
v64accfloat test_mac_4x8_8x16T(v64bfp16ebs8 a, int sgn_x, v128bfp16ebs8 b,
                               int sgn_y, v64accfloat acc) {
  return mac_4x8_8x16T(a, sgn_x, b, sgn_y, acc);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z18test_msc_4x8_8x16T12v64bfp16ebs8i13v128bfp16ebs8iDv64_u10__accfloat(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], i32 noundef [[SGN_X:%.*]], [[STRUCT_V128BFP16EBS8:%.*]] [[B_COERCE:%.*]], i32 noundef [[SGN_Y:%.*]], <64 x float> inreg noundef [[ACC:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 2
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 3
// CHECK-NEXT:    [[SHL14_I_I:%.*]] = shl i32 [[SGN_X]], 9
// CHECK-NEXT:    [[SHL15_I_I:%.*]] = shl i32 [[SGN_Y]], 8
// CHECK-NEXT:    [[OR16_I_I:%.*]] = or i32 [[SHL14_I_I]], [[SHL15_I_I]]
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or disjoint i32 [[OR16_I_I]], 204
// CHECK-NEXT:    [[TMP6:%.*]] = bitcast <64 x float> [[ACC]] to <64 x i32>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.msc.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <64 x i8> [[TMP3]], <8 x i8> [[TMP4]], <8 x i8> [[TMP5]], <64 x i32> [[TMP6]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP8:%.*]] = bitcast <64 x i32> [[TMP7]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP8]]
//
v64accfloat test_msc_4x8_8x16T(v64bfp16ebs8 a, int sgn_x, v128bfp16ebs8 b,
                               int sgn_y, v64accfloat acc) {
  return msc_4x8_8x16T(a, sgn_x, b, sgn_y, acc);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z21test_addmac_4x8_8x16T12v64bfp16ebs8i13v128bfp16ebs8iDv64_u10__accfloatS1_(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], i32 noundef [[SGN_X:%.*]], [[STRUCT_V128BFP16EBS8:%.*]] [[B_COERCE:%.*]], i32 noundef [[SGN_Y:%.*]], <64 x float> inreg noundef [[ACC1:%.*]], <64 x float> inreg noundef [[ACC2:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 2
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 3
// CHECK-NEXT:    [[SHL14_I_I:%.*]] = shl i32 [[SGN_X]], 9
// CHECK-NEXT:    [[SHL15_I_I:%.*]] = shl i32 [[SGN_Y]], 8
// CHECK-NEXT:    [[OR16_I_I:%.*]] = or i32 [[SHL14_I_I]], [[SHL15_I_I]]
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or disjoint i32 [[OR16_I_I]], 204
// CHECK-NEXT:    [[TMP6:%.*]] = bitcast <64 x float> [[ACC1]] to <64 x i32>
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <64 x float> [[ACC2]] to <64 x i32>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.addmac.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <64 x i8> [[TMP3]], <8 x i8> [[TMP4]], <8 x i8> [[TMP5]], <64 x i32> [[TMP6]], <64 x i32> [[TMP7]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP9:%.*]] = bitcast <64 x i32> [[TMP8]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP9]]
//
v64accfloat test_addmac_4x8_8x16T(v64bfp16ebs8 a, int sgn_x, v128bfp16ebs8 b,
                                  int sgn_y, v64accfloat acc1,
                                  v64accfloat acc2) {
  return addmac_4x8_8x16T(a, sgn_x, b, sgn_y, acc1, acc2);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z21test_addmsc_4x8_8x16T12v64bfp16ebs8i13v128bfp16ebs8iDv64_u10__accfloatS1_(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], i32 noundef [[SGN_X:%.*]], [[STRUCT_V128BFP16EBS8:%.*]] [[B_COERCE:%.*]], i32 noundef [[SGN_Y:%.*]], <64 x float> inreg noundef [[ACC1:%.*]], <64 x float> inreg noundef [[ACC2:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 2
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 3
// CHECK-NEXT:    [[SHL14_I_I:%.*]] = shl i32 [[SGN_X]], 9
// CHECK-NEXT:    [[SHL15_I_I:%.*]] = shl i32 [[SGN_Y]], 8
// CHECK-NEXT:    [[OR16_I_I:%.*]] = or i32 [[SHL14_I_I]], [[SHL15_I_I]]
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or disjoint i32 [[OR16_I_I]], 204
// CHECK-NEXT:    [[TMP6:%.*]] = bitcast <64 x float> [[ACC1]] to <64 x i32>
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <64 x float> [[ACC2]] to <64 x i32>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.addmsc.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <64 x i8> [[TMP3]], <8 x i8> [[TMP4]], <8 x i8> [[TMP5]], <64 x i32> [[TMP6]], <64 x i32> [[TMP7]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP9:%.*]] = bitcast <64 x i32> [[TMP8]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP9]]
//
v64accfloat test_addmsc_4x8_8x16T(v64bfp16ebs8 a, int sgn_x, v128bfp16ebs8 b,
                                  int sgn_y, v64accfloat acc1,
                                  v64accfloat acc2) {
  return addmsc_4x8_8x16T(a, sgn_x, b, sgn_y, acc1, acc2);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z23test_mul_4x8_8x16T_conf12v64bfp16ebs813v128bfp16ebs8i(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], [[STRUCT_V128BFP16EBS8:%.*]] [[B_COERCE:%.*]], i32 noundef [[SUB_MUL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 2
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 3
// CHECK-NEXT:    [[SHL2_I_I:%.*]] = shl i32 [[SUB_MUL]], 11
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or disjoint i32 [[SHL2_I_I]], 972
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.mul.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <64 x i8> [[TMP3]], <8 x i8> [[TMP4]], <8 x i8> [[TMP5]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <64 x i32> [[TMP6]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP7]]
//
v64accfloat test_mul_4x8_8x16T_conf(v64bfp16ebs8 a, v128bfp16ebs8 b,
                                    int sub_mul) {
  return mul_4x8_8x16T_conf(a, b, sub_mul);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z26test_negmul_4x8_8x16T_conf12v64bfp16ebs813v128bfp16ebs8i(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], [[STRUCT_V128BFP16EBS8:%.*]] [[B_COERCE:%.*]], i32 noundef [[SUB_MUL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 2
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 3
// CHECK-NEXT:    [[SHL2_I_I:%.*]] = shl i32 [[SUB_MUL]], 11
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or disjoint i32 [[SHL2_I_I]], 972
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.negmul.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <64 x i8> [[TMP3]], <8 x i8> [[TMP4]], <8 x i8> [[TMP5]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <64 x i32> [[TMP6]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP7]]
//
v64accfloat test_negmul_4x8_8x16T_conf(v64bfp16ebs8 a, v128bfp16ebs8 b,
                                       int sub_mul) {
  return negmul_4x8_8x16T_conf(a, b, sub_mul);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z23test_mac_4x8_8x16T_conf12v64bfp16ebs813v128bfp16ebs8Dv64_u10__accfloatiii(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], [[STRUCT_V128BFP16EBS8:%.*]] [[B_COERCE:%.*]], <64 x float> inreg noundef [[ACC:%.*]], i32 noundef [[ZERO_ACC:%.*]], i32 noundef [[SUB_MUL:%.*]], i32 noundef [[SUB_ACC1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 2
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 3
// CHECK-NEXT:    [[SHL2_I_I:%.*]] = shl i32 [[SUB_MUL]], 11
// CHECK-NEXT:    [[SHL4_I_I:%.*]] = shl i32 [[SUB_ACC1]], 12
// CHECK-NEXT:    [[OR5_I_I:%.*]] = or i32 [[ZERO_ACC]], [[SHL2_I_I]]
// CHECK-NEXT:    [[OR11_I_I:%.*]] = or i32 [[OR5_I_I]], [[SHL4_I_I]]
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or i32 [[OR11_I_I]], 972
// CHECK-NEXT:    [[TMP6:%.*]] = bitcast <64 x float> [[ACC]] to <64 x i32>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.mac.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <64 x i8> [[TMP3]], <8 x i8> [[TMP4]], <8 x i8> [[TMP5]], <64 x i32> [[TMP6]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP8:%.*]] = bitcast <64 x i32> [[TMP7]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP8]]
//
v64accfloat test_mac_4x8_8x16T_conf(v64bfp16ebs8 a, v128bfp16ebs8 b,
                                    v64accfloat acc, int zero_acc, int sub_mul,
                                    int sub_acc1) {
  return mac_4x8_8x16T_conf(a, b, acc, zero_acc, sub_mul, sub_acc1);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z23test_msc_4x8_8x16T_conf12v64bfp16ebs813v128bfp16ebs8Dv64_u10__accfloatiii(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], [[STRUCT_V128BFP16EBS8:%.*]] [[B_COERCE:%.*]], <64 x float> inreg noundef [[ACC:%.*]], i32 noundef [[ZERO_ACC:%.*]], i32 noundef [[SUB_MUL:%.*]], i32 noundef [[SUB_ACC1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 2
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 3
// CHECK-NEXT:    [[SHL2_I_I:%.*]] = shl i32 [[SUB_MUL]], 11
// CHECK-NEXT:    [[SHL4_I_I:%.*]] = shl i32 [[SUB_ACC1]], 12
// CHECK-NEXT:    [[OR5_I_I:%.*]] = or i32 [[ZERO_ACC]], [[SHL2_I_I]]
// CHECK-NEXT:    [[OR11_I_I:%.*]] = or i32 [[OR5_I_I]], [[SHL4_I_I]]
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or i32 [[OR11_I_I]], 972
// CHECK-NEXT:    [[TMP6:%.*]] = bitcast <64 x float> [[ACC]] to <64 x i32>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.msc.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <64 x i8> [[TMP3]], <8 x i8> [[TMP4]], <8 x i8> [[TMP5]], <64 x i32> [[TMP6]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP8:%.*]] = bitcast <64 x i32> [[TMP7]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP8]]
//
v64accfloat test_msc_4x8_8x16T_conf(v64bfp16ebs8 a, v128bfp16ebs8 b,
                                    v64accfloat acc, int zero_acc, int sub_mul,
                                    int sub_acc1) {
  return msc_4x8_8x16T_conf(a, b, acc, zero_acc, sub_mul, sub_acc1);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z26test_addmac_4x8_8x16T_conf12v64bfp16ebs813v128bfp16ebs8Dv64_u10__accfloatS1_iiii(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], [[STRUCT_V128BFP16EBS8:%.*]] [[B_COERCE:%.*]], <64 x float> inreg noundef [[ACC1:%.*]], <64 x float> inreg noundef [[ACC2:%.*]], i32 noundef [[ZERO_ACC1:%.*]], i32 noundef [[SUB_MUL:%.*]], i32 noundef [[SUB_ACC1:%.*]], i32 noundef [[SUB_ACC2:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 2
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 3
// CHECK-NEXT:    [[SHL2_I_I:%.*]] = shl i32 [[SUB_MUL]], 11
// CHECK-NEXT:    [[SHL4_I_I:%.*]] = shl i32 [[SUB_ACC1]], 12
// CHECK-NEXT:    [[SHL6_I_I:%.*]] = shl i32 [[SUB_ACC2]], 13
// CHECK-NEXT:    [[OR5_I_I:%.*]] = or i32 [[ZERO_ACC1]], [[SHL2_I_I]]
// CHECK-NEXT:    [[OR7_I_I:%.*]] = or i32 [[OR5_I_I]], [[SHL4_I_I]]
// CHECK-NEXT:    [[OR11_I_I:%.*]] = or i32 [[OR7_I_I]], [[SHL6_I_I]]
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or i32 [[OR11_I_I]], 972
// CHECK-NEXT:    [[TMP6:%.*]] = bitcast <64 x float> [[ACC1]] to <64 x i32>
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <64 x float> [[ACC2]] to <64 x i32>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.addmac.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <64 x i8> [[TMP3]], <8 x i8> [[TMP4]], <8 x i8> [[TMP5]], <64 x i32> [[TMP6]], <64 x i32> [[TMP7]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP9:%.*]] = bitcast <64 x i32> [[TMP8]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP9]]
//
v64accfloat test_addmac_4x8_8x16T_conf(v64bfp16ebs8 a, v128bfp16ebs8 b,
                                       v64accfloat acc1, v64accfloat acc2,
                                       int zero_acc1, int sub_mul, int sub_acc1,
                                       int sub_acc2) {
  return addmac_4x8_8x16T_conf(a, b, acc1, acc2, zero_acc1, sub_mul, sub_acc1,
                               sub_acc2);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z26test_addmsc_4x8_8x16T_conf12v64bfp16ebs813v128bfp16ebs8Dv64_u10__accfloatS1_iiii(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], [[STRUCT_V128BFP16EBS8:%.*]] [[B_COERCE:%.*]], <64 x float> inreg noundef [[ACC1:%.*]], <64 x float> inreg noundef [[ACC2:%.*]], i32 noundef [[ZERO_ACC1:%.*]], i32 noundef [[SUB_MUL:%.*]], i32 noundef [[SUB_ACC1:%.*]], i32 noundef [[SUB_ACC2:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 2
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 3
// CHECK-NEXT:    [[SHL2_I_I:%.*]] = shl i32 [[SUB_MUL]], 11
// CHECK-NEXT:    [[SHL4_I_I:%.*]] = shl i32 [[SUB_ACC1]], 12
// CHECK-NEXT:    [[SHL6_I_I:%.*]] = shl i32 [[SUB_ACC2]], 13
// CHECK-NEXT:    [[OR5_I_I:%.*]] = or i32 [[ZERO_ACC1]], [[SHL2_I_I]]
// CHECK-NEXT:    [[OR7_I_I:%.*]] = or i32 [[OR5_I_I]], [[SHL4_I_I]]
// CHECK-NEXT:    [[OR11_I_I:%.*]] = or i32 [[OR7_I_I]], [[SHL6_I_I]]
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or i32 [[OR11_I_I]], 972
// CHECK-NEXT:    [[TMP6:%.*]] = bitcast <64 x float> [[ACC1]] to <64 x i32>
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <64 x float> [[ACC2]] to <64 x i32>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.addmsc.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <64 x i8> [[TMP3]], <8 x i8> [[TMP4]], <8 x i8> [[TMP5]], <64 x i32> [[TMP6]], <64 x i32> [[TMP7]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP9:%.*]] = bitcast <64 x i32> [[TMP8]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP9]]
//
v64accfloat test_addmsc_4x8_8x16T_conf(v64bfp16ebs8 a, v128bfp16ebs8 b,
                                       v64accfloat acc1, v64accfloat acc2,
                                       int zero_acc1, int sub_mul, int sub_acc1,
                                       int sub_acc2) {
  return addmsc_4x8_8x16T_conf(a, b, acc1, acc2, zero_acc1, sub_mul, sub_acc1,
                               sub_acc2);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z23test_mul_4x8_8x16T_conf12v64bfp16ebs8i13v128bfp16ebs8ii(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], i32 noundef [[SGN_X:%.*]], [[STRUCT_V128BFP16EBS8:%.*]] [[B_COERCE:%.*]], i32 noundef [[SGN_Y:%.*]], i32 noundef [[SUB_MUL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 2
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 3
// CHECK-NEXT:    [[SHL2_I_I:%.*]] = shl i32 [[SUB_MUL]], 11
// CHECK-NEXT:    [[SHL14_I_I:%.*]] = shl i32 [[SGN_X]], 9
// CHECK-NEXT:    [[SHL15_I_I:%.*]] = shl i32 [[SGN_Y]], 8
// CHECK-NEXT:    [[OR16_I_I:%.*]] = or i32 [[SHL14_I_I]], [[SHL15_I_I]]
// CHECK-NEXT:    [[OR11_I_I:%.*]] = or i32 [[OR16_I_I]], [[SHL2_I_I]]
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or disjoint i32 [[OR11_I_I]], 204
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.mul.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <64 x i8> [[TMP3]], <8 x i8> [[TMP4]], <8 x i8> [[TMP5]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <64 x i32> [[TMP6]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP7]]
//
v64accfloat test_mul_4x8_8x16T_conf(v64bfp16ebs8 a, int sgn_x, v128bfp16ebs8 b,
                                    int sgn_y, int sub_mul) {
  return mul_4x8_8x16T_conf(a, sgn_x, b, sgn_y, sub_mul);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z26test_negmul_4x8_8x16T_conf12v64bfp16ebs8i13v128bfp16ebs8ii(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], i32 noundef [[SGN_X:%.*]], [[STRUCT_V128BFP16EBS8:%.*]] [[B_COERCE:%.*]], i32 noundef [[SGN_Y:%.*]], i32 noundef [[SUB_MUL:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 2
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 3
// CHECK-NEXT:    [[SHL2_I_I:%.*]] = shl i32 [[SUB_MUL]], 11
// CHECK-NEXT:    [[SHL14_I_I:%.*]] = shl i32 [[SGN_X]], 9
// CHECK-NEXT:    [[SHL15_I_I:%.*]] = shl i32 [[SGN_Y]], 8
// CHECK-NEXT:    [[OR16_I_I:%.*]] = or i32 [[SHL14_I_I]], [[SHL15_I_I]]
// CHECK-NEXT:    [[OR11_I_I:%.*]] = or i32 [[OR16_I_I]], [[SHL2_I_I]]
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or disjoint i32 [[OR11_I_I]], 204
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.negmul.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <64 x i8> [[TMP3]], <8 x i8> [[TMP4]], <8 x i8> [[TMP5]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <64 x i32> [[TMP6]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP7]]
//
v64accfloat test_negmul_4x8_8x16T_conf(v64bfp16ebs8 a, int sgn_x,
                                       v128bfp16ebs8 b, int sgn_y,
                                       int sub_mul) {
  return negmul_4x8_8x16T_conf(a, sgn_x, b, sgn_y, sub_mul);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z23test_mac_4x8_8x16T_conf12v64bfp16ebs8i13v128bfp16ebs8iDv64_u10__accfloatiii(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], i32 noundef [[SGN_X:%.*]], [[STRUCT_V128BFP16EBS8:%.*]] [[B_COERCE:%.*]], i32 noundef [[SGN_Y:%.*]], <64 x float> inreg noundef [[ACC:%.*]], i32 noundef [[ZERO_ACC:%.*]], i32 noundef [[SUB_MUL:%.*]], i32 noundef [[SUB_ACC1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 2
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 3
// CHECK-NEXT:    [[SHL2_I_I:%.*]] = shl i32 [[SUB_MUL]], 11
// CHECK-NEXT:    [[SHL4_I_I:%.*]] = shl i32 [[SUB_ACC1]], 12
// CHECK-NEXT:    [[SHL14_I_I:%.*]] = shl i32 [[SGN_X]], 9
// CHECK-NEXT:    [[SHL15_I_I:%.*]] = shl i32 [[SGN_Y]], 8
// CHECK-NEXT:    [[OR11_I_I:%.*]] = or disjoint i32 [[SHL14_I_I]], 204
// CHECK-NEXT:    [[OR16_I_I:%.*]] = or i32 [[SHL15_I_I]], [[OR11_I_I]]
// CHECK-NEXT:    [[OR13_I_I:%.*]] = or i32 [[OR16_I_I]], [[ZERO_ACC]]
// CHECK-NEXT:    [[OR17_I_I:%.*]] = or i32 [[OR13_I_I]], [[SHL2_I_I]]
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or i32 [[OR17_I_I]], [[SHL4_I_I]]
// CHECK-NEXT:    [[TMP6:%.*]] = bitcast <64 x float> [[ACC]] to <64 x i32>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.mac.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <64 x i8> [[TMP3]], <8 x i8> [[TMP4]], <8 x i8> [[TMP5]], <64 x i32> [[TMP6]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP8:%.*]] = bitcast <64 x i32> [[TMP7]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP8]]
//
v64accfloat test_mac_4x8_8x16T_conf(v64bfp16ebs8 a, int sgn_x, v128bfp16ebs8 b,
                                    int sgn_y, v64accfloat acc, int zero_acc,
                                    int sub_mul, int sub_acc1) {
  return mac_4x8_8x16T_conf(a, sgn_x, b, sgn_y, acc, zero_acc, sub_mul,
                            sub_acc1);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z23test_msc_4x8_8x16T_conf12v64bfp16ebs8i13v128bfp16ebs8iDv64_u10__accfloatiii(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], i32 noundef [[SGN_X:%.*]], [[STRUCT_V128BFP16EBS8:%.*]] [[B_COERCE:%.*]], i32 noundef [[SGN_Y:%.*]], <64 x float> inreg noundef [[ACC:%.*]], i32 noundef [[ZERO_ACC:%.*]], i32 noundef [[SUB_MUL:%.*]], i32 noundef [[SUB_ACC1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 2
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 3
// CHECK-NEXT:    [[SHL2_I_I:%.*]] = shl i32 [[SUB_MUL]], 11
// CHECK-NEXT:    [[SHL4_I_I:%.*]] = shl i32 [[SUB_ACC1]], 12
// CHECK-NEXT:    [[SHL14_I_I:%.*]] = shl i32 [[SGN_X]], 9
// CHECK-NEXT:    [[SHL15_I_I:%.*]] = shl i32 [[SGN_Y]], 8
// CHECK-NEXT:    [[OR11_I_I:%.*]] = or disjoint i32 [[SHL14_I_I]], 204
// CHECK-NEXT:    [[OR16_I_I:%.*]] = or i32 [[SHL15_I_I]], [[OR11_I_I]]
// CHECK-NEXT:    [[OR13_I_I:%.*]] = or i32 [[OR16_I_I]], [[ZERO_ACC]]
// CHECK-NEXT:    [[OR17_I_I:%.*]] = or i32 [[OR13_I_I]], [[SHL2_I_I]]
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or i32 [[OR17_I_I]], [[SHL4_I_I]]
// CHECK-NEXT:    [[TMP6:%.*]] = bitcast <64 x float> [[ACC]] to <64 x i32>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.msc.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <64 x i8> [[TMP3]], <8 x i8> [[TMP4]], <8 x i8> [[TMP5]], <64 x i32> [[TMP6]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP8:%.*]] = bitcast <64 x i32> [[TMP7]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP8]]
//
v64accfloat test_msc_4x8_8x16T_conf(v64bfp16ebs8 a, int sgn_x, v128bfp16ebs8 b,
                                    int sgn_y, v64accfloat acc, int zero_acc,
                                    int sub_mul, int sub_acc1) {
  return msc_4x8_8x16T_conf(a, sgn_x, b, sgn_y, acc, zero_acc, sub_mul,
                            sub_acc1);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z26test_addmac_4x8_8x16T_conf12v64bfp16ebs8i13v128bfp16ebs8iDv64_u10__accfloatS1_iiii(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], i32 noundef [[SGN_X:%.*]], [[STRUCT_V128BFP16EBS8:%.*]] [[B_COERCE:%.*]], i32 noundef [[SGN_Y:%.*]], <64 x float> inreg noundef [[ACC1:%.*]], <64 x float> inreg noundef [[ACC2:%.*]], i32 noundef [[ZERO_ACC1:%.*]], i32 noundef [[SUB_MUL:%.*]], i32 noundef [[SUB_ACC1:%.*]], i32 noundef [[SUB_ACC2:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 2
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 3
// CHECK-NEXT:    [[SHL2_I_I:%.*]] = shl i32 [[SUB_MUL]], 11
// CHECK-NEXT:    [[SHL4_I_I:%.*]] = shl i32 [[SUB_ACC1]], 12
// CHECK-NEXT:    [[SHL6_I_I:%.*]] = shl i32 [[SUB_ACC2]], 13
// CHECK-NEXT:    [[SHL14_I_I:%.*]] = shl i32 [[SGN_X]], 9
// CHECK-NEXT:    [[SHL15_I_I:%.*]] = shl i32 [[SGN_Y]], 8
// CHECK-NEXT:    [[OR7_I_I:%.*]] = or disjoint i32 [[SHL14_I_I]], 204
// CHECK-NEXT:    [[OR11_I_I:%.*]] = or i32 [[SHL15_I_I]], [[OR7_I_I]]
// CHECK-NEXT:    [[OR16_I_I:%.*]] = or i32 [[OR11_I_I]], [[ZERO_ACC1]]
// CHECK-NEXT:    [[OR13_I_I:%.*]] = or i32 [[OR16_I_I]], [[SHL2_I_I]]
// CHECK-NEXT:    [[OR17_I_I:%.*]] = or i32 [[OR13_I_I]], [[SHL4_I_I]]
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or i32 [[OR17_I_I]], [[SHL6_I_I]]
// CHECK-NEXT:    [[TMP6:%.*]] = bitcast <64 x float> [[ACC1]] to <64 x i32>
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <64 x float> [[ACC2]] to <64 x i32>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.addmac.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <64 x i8> [[TMP3]], <8 x i8> [[TMP4]], <8 x i8> [[TMP5]], <64 x i32> [[TMP6]], <64 x i32> [[TMP7]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP9:%.*]] = bitcast <64 x i32> [[TMP8]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP9]]
//
v64accfloat test_addmac_4x8_8x16T_conf(v64bfp16ebs8 a, int sgn_x,
                                       v128bfp16ebs8 b, int sgn_y,
                                       v64accfloat acc1, v64accfloat acc2,
                                       int zero_acc1, int sub_mul, int sub_acc1,
                                       int sub_acc2) {
  return addmac_4x8_8x16T_conf(a, sgn_x, b, sgn_y, acc1, acc2, zero_acc1,
                               sub_mul, sub_acc1, sub_acc2);
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z26test_addmsc_4x8_8x16T_conf12v64bfp16ebs8i13v128bfp16ebs8iDv64_u10__accfloatS1_iiii(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], i32 noundef [[SGN_X:%.*]], [[STRUCT_V128BFP16EBS8:%.*]] [[B_COERCE:%.*]], i32 noundef [[SGN_Y:%.*]], <64 x float> inreg noundef [[ACC1:%.*]], <64 x float> inreg noundef [[ACC2:%.*]], i32 noundef [[ZERO_ACC1:%.*]], i32 noundef [[SUB_MUL:%.*]], i32 noundef [[SUB_ACC1:%.*]], i32 noundef [[SUB_ACC2:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 2
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[B_COERCE]], 3
// CHECK-NEXT:    [[SHL2_I_I:%.*]] = shl i32 [[SUB_MUL]], 11
// CHECK-NEXT:    [[SHL4_I_I:%.*]] = shl i32 [[SUB_ACC1]], 12
// CHECK-NEXT:    [[SHL6_I_I:%.*]] = shl i32 [[SUB_ACC2]], 13
// CHECK-NEXT:    [[SHL14_I_I:%.*]] = shl i32 [[SGN_X]], 9
// CHECK-NEXT:    [[SHL15_I_I:%.*]] = shl i32 [[SGN_Y]], 8
// CHECK-NEXT:    [[OR7_I_I:%.*]] = or disjoint i32 [[SHL14_I_I]], 204
// CHECK-NEXT:    [[OR11_I_I:%.*]] = or i32 [[SHL15_I_I]], [[OR7_I_I]]
// CHECK-NEXT:    [[OR16_I_I:%.*]] = or i32 [[OR11_I_I]], [[ZERO_ACC1]]
// CHECK-NEXT:    [[OR13_I_I:%.*]] = or i32 [[OR16_I_I]], [[SHL2_I_I]]
// CHECK-NEXT:    [[OR17_I_I:%.*]] = or i32 [[OR13_I_I]], [[SHL4_I_I]]
// CHECK-NEXT:    [[OR19_I_I:%.*]] = or i32 [[OR17_I_I]], [[SHL6_I_I]]
// CHECK-NEXT:    [[TMP6:%.*]] = bitcast <64 x float> [[ACC1]] to <64 x i32>
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <64 x float> [[ACC2]] to <64 x i32>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.addmsc.conf(<64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <64 x i8> [[TMP2]], <64 x i8> [[TMP3]], <8 x i8> [[TMP4]], <8 x i8> [[TMP5]], <64 x i32> [[TMP6]], <64 x i32> [[TMP7]], i32 [[OR19_I_I]])
// CHECK-NEXT:    [[TMP9:%.*]] = bitcast <64 x i32> [[TMP8]] to <64 x float>
// CHECK-NEXT:    ret <64 x float> [[TMP9]]
//
v64accfloat test_addmsc_4x8_8x16T_conf(v64bfp16ebs8 a, int sgn_x,
                                       v128bfp16ebs8 b, int sgn_y,
                                       v64accfloat acc1, v64accfloat acc2,
                                       int zero_acc1, int sub_mul, int sub_acc1,
                                       int sub_acc2) {
  return addmsc_4x8_8x16T_conf(a, sgn_x, b, sgn_y, acc1, acc2, zero_acc1,
                               sub_mul, sub_acc1, sub_acc2);
};
