// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
//===- aie2-abi-unaligned.cpp ----------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//
// RUN: %clang --target=aie2p -nostdlibinc -S -emit-llvm %s -o - | FileCheck %s

#include <stdint.h>

extern "C" {

// CHECK-LABEL: @ret_fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca [[STRUCT_FIFO_STATE_T:%.*]], align 64
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 64 [[RETVAL]], i8 0, i64 256, i1 false)
// CHECK-NEXT:    [[FIFO:%.*]] = getelementptr inbounds nuw [[STRUCT_FIFO_STATE_T]], ptr [[RETVAL]], i32 0, i32 0
// CHECK-NEXT:    [[POS:%.*]] = getelementptr inbounds nuw [[STRUCT_FIFO_STATE_T]], ptr [[RETVAL]], i32 0, i32 1
// CHECK-NEXT:    [[EXTRA:%.*]] = getelementptr inbounds nuw [[STRUCT_FIFO_STATE_T]], ptr [[RETVAL]], i32 0, i32 2
// CHECK-NEXT:    [[TMP0:%.*]] = load [[STRUCT_FIFO_STATE_T]], ptr [[RETVAL]], align 64
// CHECK-NEXT:    ret [[STRUCT_FIFO_STATE_T]] [[TMP0]]
//
fifo_state_t ret_fifo_state_t(void) { return {}; }

// CHECK-LABEL: @pass_fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = alloca [[STRUCT_FIFO_STATE_T:%.*]], align 64
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw [[STRUCT_FIFO_STATE_T]], ptr [[TMP0]], i32 0, i32 0
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_FIFO_STATE_T]] [[DOTCOERCE:%.*]], 0
// CHECK-NEXT:    store <32 x i32> [[TMP2]], ptr [[TMP1]], align 64
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw [[STRUCT_FIFO_STATE_T]], ptr [[TMP0]], i32 0, i32 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_FIFO_STATE_T]] [[DOTCOERCE]], 1
// CHECK-NEXT:    store i32 [[TMP4]], ptr [[TMP3]], align 64
// CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw [[STRUCT_FIFO_STATE_T]], ptr [[TMP0]], i32 0, i32 2
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_FIFO_STATE_T]] [[DOTCOERCE]], 2
// CHECK-NEXT:    store <16 x i32> [[TMP6]], ptr [[TMP5]], align 64
// CHECK-NEXT:    ret void
//
void pass_fifo_state_t(fifo_state_t) {}


}
