// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
//===- aie2p-locks.cpp -----------------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
//
//===---------------------------------------------------------------------===//
// RUN: %clang -O2 --target=aie2p -nostdlibinc -S -emit-llvm %s -o - | FileCheck %s

// Acquire and release instructions
void
// CHECK-LABEL: @_Z18test_acquire_equaljj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.aie2p.acquire(i32 [[ID:%.*]], i32 [[VAL:%.*]])
// CHECK-NEXT:    ret void
//
test_acquire_equal(unsigned id, unsigned val) {
  return acquire_equal(id, val);
}
void
// CHECK-LABEL: @_Z18test_acquire_equaljji(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.aie2p.acquire.cond(i32 [[ID:%.*]], i32 [[VAL:%.*]], i32 [[COND:%.*]])
// CHECK-NEXT:    ret void
//
test_acquire_equal(unsigned id, unsigned val, int cond) {
  return acquire_equal(id, val, cond);
}
void
// CHECK-LABEL: @_Z26test_acquire_greater_equaljj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB_I:%.*]] = sub i32 0, [[VAL:%.*]]
// CHECK-NEXT:    tail call void @llvm.aie2p.acquire(i32 [[ID:%.*]], i32 [[SUB_I]])
// CHECK-NEXT:    ret void
//
test_acquire_greater_equal(unsigned id, unsigned val) {
  return acquire_greater_equal(id, val);
}
void
// CHECK-LABEL: @_Z26test_acquire_greater_equaljjj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB_I:%.*]] = sub i32 0, [[VAL:%.*]]
// CHECK-NEXT:    tail call void @llvm.aie2p.acquire.cond(i32 [[ID:%.*]], i32 [[SUB_I]], i32 [[COND:%.*]])
// CHECK-NEXT:    ret void
//
test_acquire_greater_equal(unsigned id, unsigned val, unsigned cond) {
  return acquire_greater_equal(id, val, cond);
}
void
// CHECK-LABEL: @_Z12test_releaseji(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.aie2p.release(i32 [[ID:%.*]], i32 [[VAL:%.*]])
// CHECK-NEXT:    ret void
//
test_release(unsigned id, int val) { return release(id, val); }
void
// CHECK-LABEL: @_Z12test_releasejii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.aie2p.release.cond(i32 [[ID:%.*]], i32 [[VAL:%.*]], i32 [[COND:%.*]])
// CHECK-NEXT:    ret void
//
test_release(unsigned id, int val, int cond) {
  return release(id, val, cond);
}
// Acquire and release instructions considering a memory pointer
// The below definitions with ptr arg is not officially used anywhere.
// The ptr arg is intentionally not used.
void
// CHECK-LABEL: @_Z18test_acquire_equalPKvjji(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.aie2p.acquire.cond(i32 [[ID:%.*]], i32 [[VAL:%.*]], i32 [[COND:%.*]])
// CHECK-NEXT:    ret void
//
test_acquire_equal(const void *a, unsigned id, unsigned val, int cond) {
  return acquire_equal(a, id, val, cond);
}
void
// CHECK-LABEL: @_Z26test_acquire_greater_equalPKvjj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB_I_I:%.*]] = sub i32 0, [[VAL:%.*]]
// CHECK-NEXT:    tail call void @llvm.aie2p.acquire(i32 [[ID:%.*]], i32 [[SUB_I_I]])
// CHECK-NEXT:    ret void
//
test_acquire_greater_equal(const void *a, unsigned id, unsigned val) {
  return acquire_greater_equal(a, id, val);
}
void
// CHECK-LABEL: @_Z26test_acquire_greater_equalPKvjjj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB_I_I:%.*]] = sub i32 0, [[VAL:%.*]]
// CHECK-NEXT:    tail call void @llvm.aie2p.acquire.cond(i32 [[ID:%.*]], i32 [[SUB_I_I]], i32 [[COND:%.*]])
// CHECK-NEXT:    ret void
//
test_acquire_greater_equal(const void *a, unsigned id, unsigned val, unsigned cond) {
  return acquire_greater_equal(a, id, val, cond);
}
void
// CHECK-LABEL: @_Z12test_releasePvji(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.aie2p.release(i32 [[ID:%.*]], i32 [[VAL:%.*]])
// CHECK-NEXT:    ret void
//
test_release(void *a, unsigned id, int val) { return release(a, id, val); }
void
// CHECK-LABEL: @_Z12test_releasePvjii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.aie2p.release.cond(i32 [[ID:%.*]], i32 [[VAL:%.*]], i32 [[COND:%.*]])
// CHECK-NEXT:    ret void
//
test_release(void *a, unsigned id, int val, int cond) {
  return release(a, id, val, cond);
}
// CHECK-LABEL: @_Z9test_donev(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.aie2p.sched.barrier()
// CHECK-NEXT:    tail call void @llvm.aie2p.done()
// CHECK-NEXT:    tail call void @llvm.aie2p.sched.barrier()
// CHECK-NEXT:    ret void
//
void test_done(void) {
    done();
}
