// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
//===- aie2p-set-mode.cpp ----------------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//
// RUN: %clang -O2 %s --target=aie2p -nostdlibinc -S -emit-llvm -o - | FileCheck %s

// CHECK-LABEL: @_Z20test_get_fp2bfp_maskv(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 5)
// CHECK-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_get_fp2bfp_mask(){
  return get_fp2bfp_mask();
}

// CHECK-LABEL: @_Z20test_set_fp2bfp_maskj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 5, i32 [[VAL:%.*]])
// CHECK-NEXT:    ret void
//
void test_set_fp2bfp_mask(unsigned int val){
  return set_fp2bfp_mask(val);
}
// CHECK-LABEL: @_Z15test_set_srs_ofv(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.aie2p.set.status.reg(i32 28, i32 1)
// CHECK-NEXT:    ret void
//
void test_set_srs_of(){
  return set_srs_of();
}

// CHECK-LABEL: @_Z16set_srs_of_inputj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.aie2p.set.status.reg(i32 28, i32 [[VAL:%.*]])
// CHECK-NEXT:    ret void
//
void set_srs_of_input(unsigned int val){
  return set_srs_of(val);
}

// CHECK-LABEL: @_Z15test_clr_srs_ofv(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.aie2p.set.status.reg(i32 28, i32 0)
// CHECK-NEXT:    ret void
//
void test_clr_srs_of(){
  return clr_srs_of();
}

// CHECK-LABEL: @_Z15test_get_ups_ofv(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.status.reg(i32 29)
// CHECK-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_get_ups_of(){
  return get_ups_of();
}

// CHECK-LABEL: @_Z23test_get_fpmulmac_flagsv(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.status.reg(i32 33)
// CHECK-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_get_fpmulmac_flags(){
  return get_fpmulmac_flags();
}

// CHECK-LABEL: @_Z23test_set_fpmulmac_flagsj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.aie2p.set.status.reg(i32 33, i32 [[VAL:%.*]])
// CHECK-NEXT:    ret void
//
void test_set_fpmulmac_flags(unsigned int val){
  return set_fpmulmac_flags(val);
}

// CHECK-LABEL: @_Z21test_get_fp2int_flagsv(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.status.reg(i32 34)
// CHECK-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_get_fp2int_flags(){
  return get_fp2int_flags();
}

// CHECK-LABEL: @_Z21test_set_fp2int_flagsj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.aie2p.set.status.reg(i32 34, i32 [[VAL:%.*]])
// CHECK-NEXT:    ret void
//
void test_set_fp2int_flags(unsigned int val){
  return set_fp2int_flags(val);
}

// CHECK-LABEL: @_Z20test_get_fpf2f_flagsv(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.status.reg(i32 35)
// CHECK-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_get_fpf2f_flags(){
  return get_fpf2f_flags();
}

// CHECK-LABEL: @_Z20test_set_fpf2f_flagsj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.aie2p.set.status.reg(i32 35, i32 [[VAL:%.*]])
// CHECK-NEXT:    ret void
//
void test_set_fpf2f_flags(unsigned int val){
  return set_fpf2f_flags(val);
}

// CHECK-LABEL: @_Z22test_get_fpf2bfp_flagsv(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.status.reg(i32 36)
// CHECK-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_get_fpf2bfp_flags(){
  return get_fpf2bfp_flags();
}

// CHECK-LABEL: @_Z22test_set_fpf2bfp_flagsj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.aie2p.set.status.reg(i32 36, i32 [[VAL:%.*]])
// CHECK-NEXT:    ret void
//
void test_set_fpf2bfp_flags(unsigned int val){
  return set_fpf2bfp_flags(val);
}

// CHECK-LABEL: @_Z18test_get_sparse_ofv(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.status.reg(i32 30)
// CHECK-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_get_sparse_of(){
  return get_sparse_of();
}

// CHECK-LABEL: @_Z18test_set_sparse_ofv(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.aie2p.set.status.reg(i32 30, i32 1)
// CHECK-NEXT:    ret void
//
void test_set_sparse_of(){
  return set_sparse_of();
}

// CHECK-LABEL: @_Z18test_clr_sparse_ofv(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.aie2p.set.status.reg(i32 30, i32 0)
// CHECK-NEXT:    ret void
//
void test_clr_sparse_of(){
  return clr_sparse_of();
}

// CHECK-LABEL: @_Z19test_clr_fifo_ld_ufv(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.aie2p.set.status.reg(i32 32, i32 0)
// CHECK-NEXT:    ret void
//
void test_clr_fifo_ld_uf(){
  return clr_fifo_ld_uf();
}
