// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 4
//===- aie2p-abi-bfp16.cpp -------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//



// RUN: %clang %s --target=aie2p -nostdlibinc -S -emit-llvm -o - | FileCheck %s
#include <stdint.h>

extern "C" {
// CHECK:   %struct.v64bfp16ebs16 = type <{ <64 x i8>, <8 x i8> }>
// CHECK:   %struct.v64bfp16ebs8 = type <{ <64 x i8>, <8 x i8> }>
// CHECK:  %struct.v128bfp16ebs16 = type <{ <64 x i8>, <64 x i8>, <8 x i8>, <8 x i8> }>
// CHECK:  %struct.v128bfp16ebs8 = type <{ <64 x i8>, <64 x i8>, <8 x i8>, <8 x i8> }>

// CHECK-LABEL: define dso_local void @pass_v64bfp16ebs16(
// CHECK-SAME: [[STRUCT_V64BFP16EBS16:%.*]] [[DOTCOERCE:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = alloca [[STRUCT_V64BFP16EBS16]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw [[STRUCT_V64BFP16EBS16]], ptr [[TMP0]], i32 0, i32 0
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64BFP16EBS16]] [[DOTCOERCE]], 0
// CHECK-NEXT:    store <64 x i8> [[TMP2]], ptr [[TMP1]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw [[STRUCT_V64BFP16EBS16]], ptr [[TMP0]], i32 0, i32 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V64BFP16EBS16]] [[DOTCOERCE]], 1
// CHECK-NEXT:    store <8 x i8> [[TMP4]], ptr [[TMP3]], align 8
// CHECK-NEXT:    ret void
//
    void pass_v64bfp16ebs16(v64bfp16ebs16){}
// CHECK-LABEL: define dso_local %struct.v64bfp16ebs16 @ret_v64bfp16ebs16(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca [[STRUCT_V64BFP16EBS16:%.*]], align 8
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 8 [[RETVAL]], i8 0, i64 72, i1 false)
// CHECK-NEXT:    [[MANTISSA:%.*]] = getelementptr inbounds nuw [[STRUCT_V64BFP16EBS16]], ptr [[RETVAL]], i32 0, i32 0
// CHECK-NEXT:    [[EXPONENT:%.*]] = getelementptr inbounds nuw [[STRUCT_V64BFP16EBS16]], ptr [[RETVAL]], i32 0, i32 1
// CHECK-NEXT:    [[TMP0:%.*]] = load [[STRUCT_V64BFP16EBS16]], ptr [[RETVAL]], align 8
// CHECK-NEXT:    ret [[STRUCT_V64BFP16EBS16]] [[TMP0]]
//
    v64bfp16ebs16 ret_v64bfp16ebs16() { return {}; }
// CHECK-LABEL: define dso_local void @pass_v64bfp16ebs8(
// CHECK-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[DOTCOERCE:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = alloca [[STRUCT_V64BFP16EBS8]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw [[STRUCT_V64BFP16EBS8]], ptr [[TMP0]], i32 0, i32 0
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[DOTCOERCE]], 0
// CHECK-NEXT:    store <64 x i8> [[TMP2]], ptr [[TMP1]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw [[STRUCT_V64BFP16EBS8]], ptr [[TMP0]], i32 0, i32 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[DOTCOERCE]], 1
// CHECK-NEXT:    store <8 x i8> [[TMP4]], ptr [[TMP3]], align 8
// CHECK-NEXT:    ret void
//
    void pass_v64bfp16ebs8(v64bfp16ebs8) {}
// CHECK-LABEL: define dso_local %struct.v64bfp16ebs8 @ret_v64bfp16ebs8(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca [[STRUCT_V64BFP16EBS8:%.*]], align 8
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 8 [[RETVAL]], i8 0, i64 72, i1 false)
// CHECK-NEXT:    [[MANTISSA:%.*]] = getelementptr inbounds nuw [[STRUCT_V64BFP16EBS8]], ptr [[RETVAL]], i32 0, i32 0
// CHECK-NEXT:    [[EXPONENT:%.*]] = getelementptr inbounds nuw [[STRUCT_V64BFP16EBS8]], ptr [[RETVAL]], i32 0, i32 1
// CHECK-NEXT:    [[TMP0:%.*]] = load [[STRUCT_V64BFP16EBS8]], ptr [[RETVAL]], align 8
// CHECK-NEXT:    ret [[STRUCT_V64BFP16EBS8]] [[TMP0]]
//
    v64bfp16ebs8 ret_v64bfp16ebs8(void) { return {}; }
// CHECK-LABEL: define dso_local void @pass_v128bfp16ebs16(
// CHECK-SAME: [[STRUCT_V128BFP16EBS16:%.*]] [[DOTCOERCE:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = alloca [[STRUCT_V128BFP16EBS16]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw [[STRUCT_V128BFP16EBS16]], ptr [[TMP0]], i32 0, i32 0
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128BFP16EBS16]] [[DOTCOERCE]], 0
// CHECK-NEXT:    store <64 x i8> [[TMP2]], ptr [[TMP1]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw [[STRUCT_V128BFP16EBS16]], ptr [[TMP0]], i32 0, i32 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128BFP16EBS16]] [[DOTCOERCE]], 1
// CHECK-NEXT:    store <64 x i8> [[TMP4]], ptr [[TMP3]], align 8
// CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw [[STRUCT_V128BFP16EBS16]], ptr [[TMP0]], i32 0, i32 2
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V128BFP16EBS16]] [[DOTCOERCE]], 2
// CHECK-NEXT:    store <8 x i8> [[TMP6]], ptr [[TMP5]], align 8
// CHECK-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw [[STRUCT_V128BFP16EBS16]], ptr [[TMP0]], i32 0, i32 3
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V128BFP16EBS16]] [[DOTCOERCE]], 3
// CHECK-NEXT:    store <8 x i8> [[TMP8]], ptr [[TMP7]], align 8
// CHECK-NEXT:    ret void
//
    void pass_v128bfp16ebs16(v128bfp16ebs16) {}
// CHECK-LABEL: define dso_local %struct.v128bfp16ebs16 @ret_v128bfp16ebs16(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca [[STRUCT_V128BFP16EBS16:%.*]], align 8
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 8 [[RETVAL]], i8 0, i64 144, i1 false)
// CHECK-NEXT:    [[MANTISSAX0:%.*]] = getelementptr inbounds nuw [[STRUCT_V128BFP16EBS16]], ptr [[RETVAL]], i32 0, i32 0
// CHECK-NEXT:    [[MANTISSAX1:%.*]] = getelementptr inbounds nuw [[STRUCT_V128BFP16EBS16]], ptr [[RETVAL]], i32 0, i32 1
// CHECK-NEXT:    [[EXPONENTE0:%.*]] = getelementptr inbounds nuw [[STRUCT_V128BFP16EBS16]], ptr [[RETVAL]], i32 0, i32 2
// CHECK-NEXT:    [[EXPONENTE1:%.*]] = getelementptr inbounds nuw [[STRUCT_V128BFP16EBS16]], ptr [[RETVAL]], i32 0, i32 3
// CHECK-NEXT:    [[TMP0:%.*]] = load [[STRUCT_V128BFP16EBS16]], ptr [[RETVAL]], align 8
// CHECK-NEXT:    ret [[STRUCT_V128BFP16EBS16]] [[TMP0]]
//
    v128bfp16ebs16 ret_v128bfp16ebs16(void) { return {}; }
// CHECK-LABEL: define dso_local void @pass_v128bfp16ebs8(
// CHECK-SAME: [[STRUCT_V128BFP16EBS8:%.*]] [[DOTCOERCE:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = alloca [[STRUCT_V128BFP16EBS8]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw [[STRUCT_V128BFP16EBS8]], ptr [[TMP0]], i32 0, i32 0
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[DOTCOERCE]], 0
// CHECK-NEXT:    store <64 x i8> [[TMP2]], ptr [[TMP1]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw [[STRUCT_V128BFP16EBS8]], ptr [[TMP0]], i32 0, i32 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[DOTCOERCE]], 1
// CHECK-NEXT:    store <64 x i8> [[TMP4]], ptr [[TMP3]], align 8
// CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw [[STRUCT_V128BFP16EBS8]], ptr [[TMP0]], i32 0, i32 2
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[DOTCOERCE]], 2
// CHECK-NEXT:    store <8 x i8> [[TMP6]], ptr [[TMP5]], align 8
// CHECK-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw [[STRUCT_V128BFP16EBS8]], ptr [[TMP0]], i32 0, i32 3
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[DOTCOERCE]], 3
// CHECK-NEXT:    store <8 x i8> [[TMP8]], ptr [[TMP7]], align 8
// CHECK-NEXT:    ret void
//
    void pass_v128bfp16ebs8(v128bfp16ebs8) {}
// CHECK-LABEL: define dso_local %struct.v128bfp16ebs8 @ret_v128bfp16ebs8(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca [[STRUCT_V128BFP16EBS8:%.*]], align 8
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 8 [[RETVAL]], i8 0, i64 144, i1 false)
// CHECK-NEXT:    [[MANTISSAX0:%.*]] = getelementptr inbounds nuw [[STRUCT_V128BFP16EBS8]], ptr [[RETVAL]], i32 0, i32 0
// CHECK-NEXT:    [[MANTISSAX1:%.*]] = getelementptr inbounds nuw [[STRUCT_V128BFP16EBS8]], ptr [[RETVAL]], i32 0, i32 1
// CHECK-NEXT:    [[EXPONENTE0:%.*]] = getelementptr inbounds nuw [[STRUCT_V128BFP16EBS8]], ptr [[RETVAL]], i32 0, i32 2
// CHECK-NEXT:    [[EXPONENTE1:%.*]] = getelementptr inbounds nuw [[STRUCT_V128BFP16EBS8]], ptr [[RETVAL]], i32 0, i32 3
// CHECK-NEXT:    [[TMP0:%.*]] = load [[STRUCT_V128BFP16EBS8]], ptr [[RETVAL]], align 8
// CHECK-NEXT:    ret [[STRUCT_V128BFP16EBS8]] [[TMP0]]
//
    v128bfp16ebs8 ret_v128bfp16ebs8(void) { return {}; }
}
