// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 4

//===- aie2p-scl2vec-intrinsic.cpp ---------------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2024-2025 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//

// RUN: %clang -O1 %s --target=aie2p -nostdlibinc -S -emit-llvm -o - | FileCheck %s -check-prefix=AIE2P

// AIE2P-LABEL: define dso_local noundef <16 x i32> @_Z18test_broadcast_s64Dv2_j(
// AIE2P-SAME: <2 x i32> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECINIT30_I_I:%.*]] = shufflevector <2 x i32> [[B]], <2 x i32> poison, <16 x i32> <i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1>
// AIE2P-NEXT:    ret <16 x i32> [[VECINIT30_I_I]]
//
v16int32 test_broadcast_s64 (mask64 b) {
   return  broadcast_s64(b);
}

// AIE2P-LABEL: define dso_local noundef <16 x i32> @_Z27test_broadcast_to_v16uint32Dv2_j(
// AIE2P-SAME: <2 x i32> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECINIT30_I_I:%.*]] = shufflevector <2 x i32> [[B]], <2 x i32> poison, <16 x i32> <i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1>
// AIE2P-NEXT:    ret <16 x i32> [[VECINIT30_I_I]]
//
v16uint32 test_broadcast_to_v16uint32(mask64 b) {
  return broadcast_to_v16uint32(b);
}

// AIE2P-LABEL: define dso_local inreg noundef <16 x float> @_Z29test_broadcast_to_v16accfloatDv2_f(
// AIE2P-SAME: <2 x float> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = shufflevector <2 x float> [[B]], <2 x float> poison, <16 x i32> <i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1>
// AIE2P-NEXT:    ret <16 x float> [[TMP0]]
//
v16accfloat test_broadcast_to_v16accfloat(v2float b){
   return broadcast_to_v16accfloat(b);
}

// AIE2P-LABEL: define dso_local noundef <16 x float> @_Z26test_broadcast_to_v16floatDv2_f(
// AIE2P-SAME: <2 x float> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = shufflevector <2 x float> [[B]], <2 x float> poison, <16 x i32> <i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1>
// AIE2P-NEXT:    ret <16 x float> [[TMP0]]
//
v16float test_broadcast_to_v16float(v2float b){
   return broadcast_to_v16float(b);
}

// AIE2P-LABEL: define dso_local noundef <16 x float> @_Z30test_broadcast_one_to_v16floatv(
// AIE2P-SAME: ) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    ret <16 x float> splat (float 1.000000e+00)
//
v16float test_broadcast_one_to_v16float() { return broadcast_one_to_v16float(); }

// AIE2P-LABEL: define dso_local noundef <16 x i32> @_Z23test_broadcast_elem_128Dv16_ii(
// AIE2P-SAME: <16 x i32> noundef [[A:%.*]], i32 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1:[0-9]+]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vextract.broadcast128.I512(<16 x i32> [[A]], i32 [[B]])
// AIE2P-NEXT:    ret <16 x i32> [[TMP0]]
//
v16int32 test_broadcast_elem_128(v16int32 a, int b){
   return broadcast_elem_128(a, b);
}

// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z13test_upd_elemDv64_DB8_iS_(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i8 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <64 x i8> [[V]], i8 [[B]], i32 [[IDX]]
// AIE2P-NEXT:    ret <64 x i8> [[VECINS_I_I]]
//
  v128int4 test_upd_elem(v128int4 v, int idx, v2int4 b) {
    return upd_elem(v, idx, b);
  }
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z13test_upd_elemDv64_DB8_iDv2_S_(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <2 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <32 x i16>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i8> [[B]] to i16
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <32 x i16> [[TMP0]], i16 [[TMP1]], i32 [[IDX]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <32 x i16> [[VECINS_I_I]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
  v128int4 test_upd_elem(v128int4 v, int idx, v4int4 b) {
    return upd_elem(v, idx, b);
  }
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z13test_upd_elemDv64_DB8_iDv4_S_(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <4 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <4 x i8> [[B]] to i32
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x i32> [[TMP0]], i32 [[TMP1]], i32 [[IDX]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[VECINS_I_I]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
  v128int4 test_upd_elem(v128int4 v, int idx, v8int4 b) {
    return upd_elem(v, idx, b);
  }
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z13test_upd_elemDv64_DB8_iDv8_S_(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <8 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <8 x i8> [[B]] to <2 x i32>
// AIE2P-NEXT:    [[MUL_I_I:%.*]] = shl nsw i32 [[IDX]], 1
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <2 x i32> [[TMP1]], i64 0
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x i32> [[TMP0]], i32 [[VECEXT_I_I]], i32 [[MUL_I_I]]
// AIE2P-NEXT:    [[VECEXT1_I_I:%.*]] = extractelement <2 x i32> [[TMP1]], i64 1
// AIE2P-NEXT:    [[ADD_I_I:%.*]] = or disjoint i32 [[MUL_I_I]], 1
// AIE2P-NEXT:    [[VECINS2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I]], i32 [[VECEXT1_I_I]], i32 [[ADD_I_I]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[VECINS2_I_I]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
  v128int4 test_upd_elem(v128int4 v, int idx, v16int4 b) {
    return upd_elem(v, idx, b);
  }
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z13test_upd_elemDv64_aiDv2_a(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <2 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <32 x i16>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i8> [[B]] to i16
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <32 x i16> [[TMP0]], i16 [[TMP1]], i32 [[IDX]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <32 x i16> [[VECINS_I_I]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
  v64int8 test_upd_elem(v64int8 v, int idx, v2int8 b) {
    return upd_elem(v, idx, b);
  }
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z13test_upd_elemDv64_aiDv4_a(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <4 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <4 x i8> [[B]] to i32
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x i32> [[TMP0]], i32 [[TMP1]], i32 [[IDX]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[VECINS_I_I]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
  v64int8 test_upd_elem(v64int8 v, int idx, v4int8 b) {
    return upd_elem(v, idx, b);
  }
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z13test_upd_elemDv64_aiDv8_a(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <8 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <8 x i8> [[B]] to <2 x i32>
// AIE2P-NEXT:    [[MUL_I_I:%.*]] = shl nsw i32 [[IDX]], 1
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <2 x i32> [[TMP1]], i64 0
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x i32> [[TMP0]], i32 [[VECEXT_I_I]], i32 [[MUL_I_I]]
// AIE2P-NEXT:    [[VECEXT1_I_I:%.*]] = extractelement <2 x i32> [[TMP1]], i64 1
// AIE2P-NEXT:    [[ADD_I_I:%.*]] = or disjoint i32 [[MUL_I_I]], 1
// AIE2P-NEXT:    [[VECINS2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I]], i32 [[VECEXT1_I_I]], i32 [[ADD_I_I]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[VECINS2_I_I]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
  v64int8 test_upd_elem(v64int8 v, int idx, v8int8 b) {
    return upd_elem(v, idx, b);
  }
// AIE2P-LABEL: define dso_local noundef <32 x i16> @_Z13test_upd_elemDv32_siDv2_s(
// AIE2P-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <2 x i16> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i16> [[B]] to i32
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x i32> [[TMP0]], i32 [[TMP1]], i32 [[IDX]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[VECINS_I_I]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
  v32int16 test_upd_elem(v32int16 v, int idx, v2int16 b) {
    return upd_elem(v, idx, b);
  }
// AIE2P-LABEL: define dso_local noundef <32 x i16> @_Z13test_upd_elemDv32_siDv4_s(
// AIE2P-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <4 x i16> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <4 x i16> [[B]] to <2 x i32>
// AIE2P-NEXT:    [[MUL_I_I:%.*]] = shl nsw i32 [[IDX]], 1
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <2 x i32> [[TMP1]], i64 0
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x i32> [[TMP0]], i32 [[VECEXT_I_I]], i32 [[MUL_I_I]]
// AIE2P-NEXT:    [[VECEXT1_I_I:%.*]] = extractelement <2 x i32> [[TMP1]], i64 1
// AIE2P-NEXT:    [[ADD_I_I:%.*]] = or disjoint i32 [[MUL_I_I]], 1
// AIE2P-NEXT:    [[VECINS2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I]], i32 [[VECEXT1_I_I]], i32 [[ADD_I_I]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[VECINS2_I_I]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
  v32int16 test_upd_elem(v32int16 v, int idx, v4int16 b) {
    return upd_elem(v, idx, b);
  }
// AIE2P-LABEL: define dso_local noundef <16 x i32> @_Z13test_upd_elemDv16_iiDv2_i(
// AIE2P-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <2 x i32> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[MUL_I_I:%.*]] = shl nsw i32 [[IDX]], 1
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <2 x i32> [[B]], i64 0
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x i32> [[V]], i32 [[VECEXT_I_I]], i32 [[MUL_I_I]]
// AIE2P-NEXT:    [[VECEXT1_I_I:%.*]] = extractelement <2 x i32> [[B]], i64 1
// AIE2P-NEXT:    [[ADD_I_I:%.*]] = or disjoint i32 [[MUL_I_I]], 1
// AIE2P-NEXT:    [[VECINS2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I]], i32 [[VECEXT1_I_I]], i32 [[ADD_I_I]]
// AIE2P-NEXT:    ret <16 x i32> [[VECINS2_I_I]]
//
  v16int32 test_upd_elem(v16int32 v, int idx, v2int32 b) {
    return upd_elem(v, idx, b);
  }
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z13test_upd_elemDv64_DU8_iS_(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i8 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <64 x i8> [[V]], i8 [[B]], i32 [[IDX]]
// AIE2P-NEXT:    ret <64 x i8> [[VECINS_I_I]]
//
  v128uint4 test_upd_elem(v128uint4 v, int idx, v2uint4 b) {
    return upd_elem(v, idx, b);
  }

// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z13test_upd_elemDv64_DU8_iDv2_S_(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <2 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = extractelement <2 x i8> [[B]], i64 0
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <64 x i8> [[V]], i8 [[CONV_I_I]], i32 [[IDX]]
// AIE2P-NEXT:    ret <64 x i8> [[VECINS_I_I]]
//
  v128uint4 test_upd_elem(v128uint4 v, int idx, v4uint4 b) {
    return upd_elem(v, idx, b);
  }
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z13test_upd_elemDv64_DU8_iDv4_S_(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <4 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I_I:%.*]] = extractelement <4 x i8> [[B]], i64 0
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <64 x i8> [[V]], i8 [[CONV_I_I]], i32 [[IDX]]
// AIE2P-NEXT:    ret <64 x i8> [[VECINS_I_I]]
//
  v128uint4 test_upd_elem(v128uint4 v, int idx, v8uint4 b) {
    return upd_elem(v, idx, b);
  }

// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z13test_upd_elemDv64_DU8_iDv8_S_(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <8 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <8 x i8> [[B]] to <2 x i32>
// AIE2P-NEXT:    [[MUL_I_I:%.*]] = shl nsw i32 [[IDX]], 1
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <2 x i32> [[TMP1]], i64 0
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x i32> [[TMP0]], i32 [[VECEXT_I_I]], i32 [[MUL_I_I]]
// AIE2P-NEXT:    [[VECEXT1_I_I:%.*]] = extractelement <2 x i32> [[TMP1]], i64 1
// AIE2P-NEXT:    [[ADD_I_I:%.*]] = or disjoint i32 [[MUL_I_I]], 1
// AIE2P-NEXT:    [[VECINS2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I]], i32 [[VECEXT1_I_I]], i32 [[ADD_I_I]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[VECINS2_I_I]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
  v128uint4 test_upd_elem(v128uint4 v, int idx, v16uint4 b) {
    return upd_elem(v, idx, b);
  }
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z13test_upd_elemDv64_hih(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i8 noundef zeroext [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <64 x i8> [[V]], i8 [[B]], i32 [[IDX]]
// AIE2P-NEXT:    ret <64 x i8> [[VECINS_I_I]]
//
  v64uint8 test_upd_elem(v64uint8 v, int idx, unsigned char b) {
    return upd_elem(v, idx, b);
  }
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z13test_upd_elemDv64_hiDv2_h(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <2 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <32 x i16>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i8> [[B]] to i16
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <32 x i16> [[TMP0]], i16 [[TMP1]], i32 [[IDX]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <32 x i16> [[VECINS_I_I]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
  v64uint8 test_upd_elem(v64uint8 v, int idx, v2uint8 b) {
    return upd_elem(v, idx, b);
  }
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z13test_upd_elemDv64_hiDv4_h(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <4 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <4 x i8> [[B]] to i32
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x i32> [[TMP0]], i32 [[TMP1]], i32 [[IDX]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[VECINS_I_I]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
  v64uint8 test_upd_elem(v64uint8 v, int idx, v4uint8 b) {
    return upd_elem(v, idx, b);
  }
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z13test_upd_elemDv64_hiDv8_h(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <8 x i8> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <8 x i8> [[B]] to <2 x i32>
// AIE2P-NEXT:    [[MUL_I_I:%.*]] = shl nsw i32 [[IDX]], 1
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <2 x i32> [[TMP1]], i64 0
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x i32> [[TMP0]], i32 [[VECEXT_I_I]], i32 [[MUL_I_I]]
// AIE2P-NEXT:    [[VECEXT1_I_I:%.*]] = extractelement <2 x i32> [[TMP1]], i64 1
// AIE2P-NEXT:    [[ADD_I_I:%.*]] = or disjoint i32 [[MUL_I_I]], 1
// AIE2P-NEXT:    [[VECINS2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I]], i32 [[VECEXT1_I_I]], i32 [[ADD_I_I]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[VECINS2_I_I]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP2]]
//
  v64uint8 test_upd_elem(v64uint8 v, int idx, v8uint8 b) {
    return upd_elem(v, idx, b);
  }

// AIE2P-LABEL: define dso_local noundef <32 x i16> @_Z13test_upd_elemDv32_tiDv2_t(
// AIE2P-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <2 x i16> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <2 x i16> [[B]] to i32
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x i32> [[TMP0]], i32 [[TMP1]], i32 [[IDX]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[VECINS_I_I]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
  v32uint16 test_upd_elem(v32uint16 v, int idx, v2uint16 b) {
    return upd_elem(v, idx, b);
  }
// AIE2P-LABEL: define dso_local noundef <32 x i16> @_Z13test_upd_elemDv32_tiDv4_t(
// AIE2P-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <4 x i16> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <4 x i16> [[B]] to <2 x i32>
// AIE2P-NEXT:    [[MUL_I_I:%.*]] = shl nsw i32 [[IDX]], 1
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <2 x i32> [[TMP1]], i64 0
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x i32> [[TMP0]], i32 [[VECEXT_I_I]], i32 [[MUL_I_I]]
// AIE2P-NEXT:    [[VECEXT1_I_I:%.*]] = extractelement <2 x i32> [[TMP1]], i64 1
// AIE2P-NEXT:    [[ADD_I_I:%.*]] = or disjoint i32 [[MUL_I_I]], 1
// AIE2P-NEXT:    [[VECINS2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I]], i32 [[VECEXT1_I_I]], i32 [[ADD_I_I]]
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[VECINS2_I_I]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP2]]
//
  v32uint16 test_upd_elem(v32uint16 v, int idx, v4uint16 b) {
    return upd_elem(v, idx, b);
  }
// AIE2P-LABEL: define dso_local noundef <16 x i32> @_Z13test_upd_elemDv16_jij(
// AIE2P-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x i32> [[V]], i32 [[B]], i32 [[IDX]]
// AIE2P-NEXT:    ret <16 x i32> [[VECINS_I_I]]
//
  v16uint32 test_upd_elem(v16uint32 v, int idx, unsigned int b) {
    return upd_elem(v, idx, b);
  }
// AIE2P-LABEL: define dso_local noundef <16 x i32> @_Z13test_upd_elemDv16_jiDv2_j(
// AIE2P-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <2 x i32> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[MUL_I_I:%.*]] = shl nsw i32 [[IDX]], 1
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <2 x i32> [[B]], i64 0
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x i32> [[V]], i32 [[VECEXT_I_I]], i32 [[MUL_I_I]]
// AIE2P-NEXT:    [[VECEXT1_I_I:%.*]] = extractelement <2 x i32> [[B]], i64 1
// AIE2P-NEXT:    [[ADD_I_I:%.*]] = or disjoint i32 [[MUL_I_I]], 1
// AIE2P-NEXT:    [[VECINS2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I]], i32 [[VECEXT1_I_I]], i32 [[ADD_I_I]]
// AIE2P-NEXT:    ret <16 x i32> [[VECINS2_I_I]]
//
  v16uint32 test_upd_elem(v16uint32 v, int idx, v2uint32 b) {
    return upd_elem(v, idx, b);
  }

// AIE2P-LABEL: define dso_local noundef <16 x float> @_Z13test_upd_elemDv16_fif(
// AIE2P-SAME: <16 x float> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], float noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x float> [[V]], float [[B]], i32 [[IDX]]
// AIE2P-NEXT:    ret <16 x float> [[VECINS_I_I]]
//
  v16float test_upd_elem(v16float v, int idx, float b) {
    return upd_elem(v, idx,b);
  }
// AIE2P-LABEL: define dso_local noundef <32 x bfloat> @_Z13test_upd_elemDv32_8bfloat16iS_(
// AIE2P-SAME: <32 x bfloat> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], bfloat noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <32 x bfloat> [[V]], bfloat [[B]], i32 [[IDX]]
// AIE2P-NEXT:    ret <32 x bfloat> [[VECINS_I_I]]
//
  v32bfloat16 test_upd_elem(v32bfloat16 v, int idx, bfloat16 b) {
    return upd_elem(v, idx, b);
  }
// AIE2P-LABEL: define dso_local noundef <32 x bfloat> @_Z13test_upd_elemDv32_8bfloat16iDv2_S_(
// AIE2P-SAME: <32 x bfloat> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <2 x bfloat> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2p.vinsert32.bf512(<32 x bfloat> [[V]], i32 [[IDX]], <2 x bfloat> [[B]])
// AIE2P-NEXT:    ret <32 x bfloat> [[TMP0]]
//
  v32bfloat16 test_upd_elem(v32bfloat16 v, int idx, v2bfloat16 b) {
    return upd_elem(v, idx, b);
  }
//
// AIE2P-LABEL: define dso_local noundef <32 x bfloat> @_Z13test_upd_elemDv32_8bfloat16iDv4_S_(
// AIE2P-SAME: <32 x bfloat> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <4 x bfloat> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2p.vinsert64.bf512(<32 x bfloat> [[V]], i32 [[IDX]], <4 x bfloat> [[B]])
// AIE2P-NEXT:    ret <32 x bfloat> [[TMP0]]
//
  v32bfloat16 test_upd_elem(v32bfloat16 v, int idx, v4bfloat16 b) {
    return upd_elem(v, idx, b);
  }

// AIE2P-LABEL: define dso_local noundef <32 x bfloat> @_Z13test_upd_elemDv32_8bfloat16iy(
// AIE2P-SAME: <32 x bfloat> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i64 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast i64 [[B]] to <4 x bfloat>
// AIE2P-NEXT:    [[TMP1:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2p.vinsert64.bf512(<32 x bfloat> [[V]], i32 [[IDX]], <4 x bfloat> [[TMP0]])
// AIE2P-NEXT:    ret <32 x bfloat> [[TMP1]]
//
  v32bfloat16 test_upd_elem(v32bfloat16 v, int idx, unsigned long long b) {
    return upd_elem(v, idx, b);
  }

// AIE2P-LABEL: define dso_local inreg noundef <16 x float> @_Z16test_shiftl_elemDv16_u10__accfloatf(
// AIE2P-SAME: <16 x float> inreg noundef [[A:%.*]], float noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = insertelement <16 x float> poison, float [[B]], i64 0
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[A]] to <16 x i32>
// AIE2P-NEXT:    [[TMP2:%.*]] = bitcast <16 x float> [[TMP0]] to <16 x i32>
// AIE2P-NEXT:    [[TMP3:%.*]] = shufflevector <16 x i32> [[TMP2]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> [[TMP1]], <16 x i32> [[TMP3]], i32 0, i32 range(i32 4, 61) 4)
// AIE2P-NEXT:    [[TMP5:%.*]] = bitcast <16 x i32> [[TMP4]] to <16 x float>
// AIE2P-NEXT:    ret <16 x float> [[TMP5]]
//
  v16accfloat test_shiftl_elem(v16accfloat a, float b){
   return shiftl_elem(a, b);
  }

// AIE2P-LABEL: define dso_local inreg noundef <16 x float> @_Z16test_shiftr_elemDv16_u10__accfloatf(
// AIE2P-SAME: <16 x float> inreg noundef [[A:%.*]], float noundef [[B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = insertelement <16 x float> poison, float [[B]], i64 0
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x float> [[TMP0]] to <16 x i32>
// AIE2P-NEXT:    [[TMP2:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <16 x i32> zeroinitializer
// AIE2P-NEXT:    [[TMP3:%.*]] = bitcast <16 x float> [[A]] to <16 x i32>
// AIE2P-NEXT:    [[TMP4:%.*]] = tail call <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> [[TMP2]], <16 x i32> [[TMP3]], i32 0, i32 range(i32 4, 61) 60)
// AIE2P-NEXT:    [[TMP5:%.*]] = bitcast <16 x i32> [[TMP4]] to <16 x float>
// AIE2P-NEXT:    ret <16 x float> [[TMP5]]
//
  v16accfloat test_shiftr_elem(v16accfloat a, float b){
   return shiftr_elem(a, b);
  }

// AIE2P-LABEL: define dso_local noundef float @_Z13test_ext_elemDv16_fii(
// AIE2P-SAME: <16 x float> noundef [[A:%.*]], i32 noundef [[B:%.*]], i32 noundef [[C:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <16 x float> [[A]], i32 [[B]]
// AIE2P-NEXT:    ret float [[VECEXT_I_I]]
//
  float test_ext_elem(v16float a, int b, int c){
   return ext_elem(a, b, c);
  }

// AIE2P-LABEL: define dso_local noundef <2 x float> @_Z16test_ext_v2floatDv16_fii(
// AIE2P-SAME: <16 x float> noundef [[A:%.*]], i32 noundef [[B:%.*]], i32 noundef [[C:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <16 x float> [[A]], i32 [[B]]
// AIE2P-NEXT:    [[ADD_I:%.*]] = add nsw i32 [[B]], 1
// AIE2P-NEXT:    [[VECEXT_I6_I:%.*]] = extractelement <16 x float> [[A]], i32 [[ADD_I]]
// AIE2P-NEXT:    [[VECINIT_I:%.*]] = insertelement <2 x float> poison, float [[VECEXT_I_I]], i64 0
// AIE2P-NEXT:    [[VECINIT2_I:%.*]] = insertelement <2 x float> [[VECINIT_I]], float [[VECEXT_I6_I]], i64 1
// AIE2P-NEXT:    ret <2 x float> [[VECINIT2_I]]
//
  v2float test_ext_v2float(v16float a, int b, int c){
   return ext_v2float(a, b, c);
  }

// AIE2P-LABEL: define dso_local noundef float @_Z17test_extract_elemDv16_fii(
// AIE2P-SAME: <16 x float> noundef [[A:%.*]], i32 noundef [[B:%.*]], i32 noundef [[C:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <16 x float> [[A]], i32 [[B]]
// AIE2P-NEXT:    ret float [[VECEXT_I_I]]
//
float test_extract_elem(v16float a, int b, int c){
   return extract_elem(a, b, c);
}

// AIE2P-LABEL: define dso_local noundef <2 x float> @_Z20test_extract_v2floatDv16_fii(
// AIE2P-SAME: <16 x float> noundef [[A:%.*]], i32 noundef [[B:%.*]], i32 noundef [[C:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECEXT_I_I_I:%.*]] = extractelement <16 x float> [[A]], i32 [[B]]
// AIE2P-NEXT:    [[ADD_I_I:%.*]] = add nsw i32 [[B]], 1
// AIE2P-NEXT:    [[VECEXT_I6_I_I:%.*]] = extractelement <16 x float> [[A]], i32 [[ADD_I_I]]
// AIE2P-NEXT:    [[VECINIT_I_I:%.*]] = insertelement <2 x float> poison, float [[VECEXT_I_I_I]], i64 0
// AIE2P-NEXT:    [[VECINIT2_I_I:%.*]] = insertelement <2 x float> [[VECINIT_I_I]], float [[VECEXT_I6_I_I]], i64 1
// AIE2P-NEXT:    ret <2 x float> [[VECINIT2_I_I]]
//
v2float test_extract_v2float(v16float a, int b, int c){
 return extract_v2float(a, b, c);
}

// AIE2P-LABEL: define dso_local noundef <2 x float> @_Z20test_extract_v2floatDv16_fi(
// AIE2P-SAME: <16 x float> noundef [[A:%.*]], i32 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[VECEXT_I_I_I_I:%.*]] = extractelement <16 x float> [[A]], i32 [[B]]
// AIE2P-NEXT:    [[ADD_I_I_I:%.*]] = add nsw i32 [[B]], 1
// AIE2P-NEXT:    [[VECEXT_I6_I_I_I:%.*]] = extractelement <16 x float> [[A]], i32 [[ADD_I_I_I]]
// AIE2P-NEXT:    [[VECINIT_I_I_I:%.*]] = insertelement <2 x float> poison, float [[VECEXT_I_I_I_I]], i64 0
// AIE2P-NEXT:    [[VECINIT2_I_I_I:%.*]] = insertelement <2 x float> [[VECINIT_I_I_I]], float [[VECEXT_I6_I_I_I]], i64 1
// AIE2P-NEXT:    ret <2 x float> [[VECINIT2_I_I_I]]
//
v2float test_extract_v2float(v16float a, int b){
 return extract_v2float(a, b);
}

// AIE2P-LABEL: define dso_local noundef <2 x i32> @_Z15test_ext_mask64Dv64_DU8_ii(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[MUL_I_I:%.*]] = shl nsw i32 [[IDX]], 1
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i32 [[MUL_I_I]]
// AIE2P-NEXT:    [[VECINIT_I_I:%.*]] = insertelement <2 x i32> poison, i32 [[VECEXT_I_I]], i64 0
// AIE2P-NEXT:    [[ADD_I_I:%.*]] = or disjoint i32 [[MUL_I_I]], 1
// AIE2P-NEXT:    [[VECEXT1_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i32 [[ADD_I_I]]
// AIE2P-NEXT:    [[VECINIT2_I_I:%.*]] = insertelement <2 x i32> [[VECINIT_I_I]], i32 [[VECEXT1_I_I]], i64 1
// AIE2P-NEXT:    ret <2 x i32> [[VECINIT2_I_I]]
//
mask64 test_ext_mask64(v128uint4 v, int idx, int sign) {
  return (mask64)(ext_mask64(v, idx, sign));
}


// AIE2P-LABEL: define dso_local noundef <2 x i32> @_Z15test_ext_mask64Dv64_hii(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[MUL_I_I:%.*]] = shl nsw i32 [[IDX]], 1
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i32 [[MUL_I_I]]
// AIE2P-NEXT:    [[VECINIT_I_I:%.*]] = insertelement <2 x i32> poison, i32 [[VECEXT_I_I]], i64 0
// AIE2P-NEXT:    [[ADD_I_I:%.*]] = or disjoint i32 [[MUL_I_I]], 1
// AIE2P-NEXT:    [[VECEXT1_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i32 [[ADD_I_I]]
// AIE2P-NEXT:    [[VECINIT2_I_I:%.*]] = insertelement <2 x i32> [[VECINIT_I_I]], i32 [[VECEXT1_I_I]], i64 1
// AIE2P-NEXT:    ret <2 x i32> [[VECINIT2_I_I]]
//
mask64 test_ext_mask64(v64uint8 v, int idx, int sign) {
  return (mask64)(ext_mask64(v, idx, sign));
}


// AIE2P-LABEL: define dso_local noundef <2 x i32> @_Z15test_ext_mask64Dv32_sii(
// AIE2P-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[MUL_I_I:%.*]] = shl nsw i32 [[IDX]], 1
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i32 [[MUL_I_I]]
// AIE2P-NEXT:    [[VECINIT_I_I:%.*]] = insertelement <2 x i32> poison, i32 [[VECEXT_I_I]], i64 0
// AIE2P-NEXT:    [[ADD_I_I:%.*]] = or disjoint i32 [[MUL_I_I]], 1
// AIE2P-NEXT:    [[VECEXT1_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i32 [[ADD_I_I]]
// AIE2P-NEXT:    [[VECINIT2_I_I:%.*]] = insertelement <2 x i32> [[VECINIT_I_I]], i32 [[VECEXT1_I_I]], i64 1
// AIE2P-NEXT:    ret <2 x i32> [[VECINIT2_I_I]]
//
mask64 test_ext_mask64(v32int16 v, int idx, int sign) {
  return (mask64)(ext_mask64(v, idx, sign));
}


// AIE2P-LABEL: define dso_local noundef <2 x i32> @_Z15test_ext_mask64Dv16_iii(
// AIE2P-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[MUL_I_I:%.*]] = shl nsw i32 [[IDX]], 1
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <16 x i32> [[V]], i32 [[MUL_I_I]]
// AIE2P-NEXT:    [[VECINIT_I_I:%.*]] = insertelement <2 x i32> poison, i32 [[VECEXT_I_I]], i64 0
// AIE2P-NEXT:    [[ADD_I_I:%.*]] = or disjoint i32 [[MUL_I_I]], 1
// AIE2P-NEXT:    [[VECEXT1_I_I:%.*]] = extractelement <16 x i32> [[V]], i32 [[ADD_I_I]]
// AIE2P-NEXT:    [[VECINIT2_I_I:%.*]] = insertelement <2 x i32> [[VECINIT_I_I]], i32 [[VECEXT1_I_I]], i64 1
// AIE2P-NEXT:    ret <2 x i32> [[VECINIT2_I_I]]
//
mask64 test_ext_mask64(v16int32 v, int idx, int sign) {
  return (mask64)(ext_mask64(v, idx, sign));
}

// AIE2P-LABEL: define dso_local noundef <2 x i32> @_Z15test_ext_mask64Dv32_8bfloat16ii(
// AIE2P-SAME: <32 x bfloat> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[SIGN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x bfloat> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[MUL_I_I:%.*]] = shl nsw i32 [[IDX]], 1
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i32 [[MUL_I_I]]
// AIE2P-NEXT:    [[VECINIT_I_I:%.*]] = insertelement <2 x i32> poison, i32 [[VECEXT_I_I]], i64 0
// AIE2P-NEXT:    [[ADD_I_I:%.*]] = or disjoint i32 [[MUL_I_I]], 1
// AIE2P-NEXT:    [[VECEXT1_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i32 [[ADD_I_I]]
// AIE2P-NEXT:    [[VECINIT2_I_I:%.*]] = insertelement <2 x i32> [[VECINIT_I_I]], i32 [[VECEXT1_I_I]], i64 1
// AIE2P-NEXT:    ret <2 x i32> [[VECINIT2_I_I]]
//
mask64 test_ext_mask64(v32bfloat16 v, int idx, int sign) {
  return ext_mask64(v, idx, sign);
}

// AIE2P-LABEL: define dso_local inreg noundef <16 x i32> @_Z12test_shuffleDv16_u7__acc32S_j(
// AIE2P-SAME: <16 x i32> inreg noundef [[A:%.*]], <16 x i32> inreg noundef [[B:%.*]], i32 noundef [[C:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vshuffle(<16 x i32> [[A]], <16 x i32> [[B]], i32 [[C]])
// AIE2P-NEXT:    ret <16 x i32> [[TMP0]]
//
v16acc32 test_shuffle(v16acc32 a, v16acc32 b, unsigned c){
   return shuffle(a, b, c);
}

// AIE2P-LABEL: define dso_local noundef <16 x i32> @_Z16test_shuffle_s64Dv2_jj(
// AIE2P-SAME: <2 x i32> noundef [[B:%.*]], i32 noundef [[M:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vbcst.shuffle64(<2 x i32> [[B]], i32 [[M]])
// AIE2P-NEXT:    ret <16 x i32> [[TMP0]]
//
v16int32 test_shuffle_s64 (mask64 b, unsigned int m) {
   return shuffle_v2s32(b,m);
}

// AIE2P-LABEL: define dso_local noundef <16 x i32> @_Z16test_shuffle_u64Dv2_jj(
// AIE2P-SAME: <2 x i32> noundef [[B:%.*]], i32 noundef [[M:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.vbcst.shuffle64(<2 x i32> [[B]], i32 [[M]])
// AIE2P-NEXT:    ret <16 x i32> [[TMP0]]
//
v16int32 test_shuffle_u64(mask64 b, unsigned int m) {
  return shuffle_u64(b, m);
}

// AIE2P-LABEL: define dso_local noundef <16 x i32> @_Z11test_insertDv16_iiDv2_j(
// AIE2P-SAME: <16 x i32> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <2 x i32> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[MUL_I_I:%.*]] = shl nsw i32 [[IDX]], 1
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <2 x i32> [[B]], i64 0
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x i32> [[V]], i32 [[VECEXT_I_I]], i32 [[MUL_I_I]]
// AIE2P-NEXT:    [[VECEXT1_I_I:%.*]] = extractelement <2 x i32> [[B]], i64 1
// AIE2P-NEXT:    [[ADD_I_I:%.*]] = or disjoint i32 [[MUL_I_I]], 1
// AIE2P-NEXT:    [[VECINS2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I]], i32 [[VECEXT1_I_I]], i32 [[ADD_I_I]]
// AIE2P-NEXT:    ret <16 x i32> [[VECINS2_I_I]]
//
v16int32 test_insert(v16int32 v, int idx, mask64 b) {
  return insert(v, idx, b);
}

// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_DU8_iDv2_j(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <2 x i32> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[MUL_I_I:%.*]] = shl nsw i32 [[IDX]], 1
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <2 x i32> [[B]], i64 0
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x i32> [[TMP0]], i32 [[VECEXT_I_I]], i32 [[MUL_I_I]]
// AIE2P-NEXT:    [[VECEXT1_I_I:%.*]] = extractelement <2 x i32> [[B]], i64 1
// AIE2P-NEXT:    [[ADD_I_I:%.*]] = or disjoint i32 [[MUL_I_I]], 1
// AIE2P-NEXT:    [[VECINS2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I]], i32 [[VECEXT1_I_I]], i32 [[ADD_I_I]]
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[VECINS2_I_I]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
v128uint4 test_insert(v128uint4 v, int idx, mask64 b) {
  return insert(v, idx, b);
}

// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z11test_insertDv64_hiDv2_j(
// AIE2P-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <2 x i32> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[MUL_I_I:%.*]] = shl nsw i32 [[IDX]], 1
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <2 x i32> [[B]], i64 0
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x i32> [[TMP0]], i32 [[VECEXT_I_I]], i32 [[MUL_I_I]]
// AIE2P-NEXT:    [[VECEXT1_I_I:%.*]] = extractelement <2 x i32> [[B]], i64 1
// AIE2P-NEXT:    [[ADD_I_I:%.*]] = or disjoint i32 [[MUL_I_I]], 1
// AIE2P-NEXT:    [[VECINS2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I]], i32 [[VECEXT1_I_I]], i32 [[ADD_I_I]]
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[VECINS2_I_I]] to <64 x i8>
// AIE2P-NEXT:    ret <64 x i8> [[TMP1]]
//
v64uint8 test_insert(v64uint8 v, int idx, mask64 b) {
  return insert(v, idx, b);
}

// AIE2P-LABEL: define dso_local noundef <32 x i16> @_Z11test_insertDv32_tiDv2_j(
// AIE2P-SAME: <32 x i16> noundef [[V:%.*]], i32 noundef [[IDX:%.*]], <2 x i32> noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16> [[V]] to <16 x i32>
// AIE2P-NEXT:    [[MUL_I_I:%.*]] = shl nsw i32 [[IDX]], 1
// AIE2P-NEXT:    [[VECEXT_I_I:%.*]] = extractelement <2 x i32> [[B]], i64 0
// AIE2P-NEXT:    [[VECINS_I_I:%.*]] = insertelement <16 x i32> [[TMP0]], i32 [[VECEXT_I_I]], i32 [[MUL_I_I]]
// AIE2P-NEXT:    [[VECEXT1_I_I:%.*]] = extractelement <2 x i32> [[B]], i64 1
// AIE2P-NEXT:    [[ADD_I_I:%.*]] = or disjoint i32 [[MUL_I_I]], 1
// AIE2P-NEXT:    [[VECINS2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I]], i32 [[VECEXT1_I_I]], i32 [[ADD_I_I]]
// AIE2P-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[VECINS2_I_I]] to <32 x i16>
// AIE2P-NEXT:    ret <32 x i16> [[TMP1]]
//
v32uint16 test_insert(v32uint16 v, int idx, mask64 b) {
  return insert(v, idx, b);
}

v64int8
// AIE2P-LABEL: define dso_local noundef <64 x i8> @_Z25test_broadcast_to_v64int8i(
// AIE2P-SAME: i32 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[CONV_I:%.*]] = trunc i32 [[B]] to i8
// AIE2P-NEXT:    [[SPLAT_SPLATINSERT_I_I:%.*]] = insertelement <64 x i8> poison, i8 [[CONV_I]], i64 0
// AIE2P-NEXT:    [[SPLAT_SPLAT_I_I:%.*]] = shufflevector <64 x i8> [[SPLAT_SPLATINSERT_I_I]], <64 x i8> poison, <64 x i32> zeroinitializer
// AIE2P-NEXT:    ret <64 x i8> [[SPLAT_SPLAT_I_I]]
//
test_broadcast_to_v64int8(int b) {
  return broadcast_to_v64int8(b);
}
// AIE2P-LABEL: define dso_local inreg noundef <16 x i64> @_Z31test_broadcast_zero_to_v16acc64v(
// AIE2P-SAME: ) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    ret <16 x i64> zeroinitializer
//
v16acc64 test_broadcast_zero_to_v16acc64() {
  return broadcast_zero_to_v16acc64();
}
// AIE2P-LABEL: define dso_local inreg noundef <32 x i64> @_Z31test_broadcast_zero_to_v32acc64v(
// AIE2P-SAME: ) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    ret <32 x i64> zeroinitializer
//
v32acc64 test_broadcast_zero_to_v32acc64() { return broadcast_zero_to_v32acc64(); }
// AIE2P-LABEL: define dso_local inreg noundef <64 x i32> @_Z31test_broadcast_zero_to_v64acc32v(
// AIE2P-SAME: ) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    ret <64 x i32> zeroinitializer
//
v64acc32 test_broadcast_zero_to_v64acc32() { return broadcast_zero_to_v64acc32(); }
// AIE2P-LABEL: define dso_local inreg noundef <16 x float> @_Z34test_broadcast_zero_to_v16accfloatv(
// AIE2P-SAME: ) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    ret <16 x float> zeroinitializer
//
v16accfloat test_broadcast_zero_to_v16accfloat() {
  return broadcast_zero_to_v16accfloat();
}
// AIE2P-LABEL: define dso_local inreg noundef <32 x float> @_Z34test_broadcast_zero_to_v32accfloatv(
// AIE2P-SAME: ) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    ret <32 x float> zeroinitializer
//
v32accfloat test_broadcast_zero_to_v32accfloat() {
  return broadcast_zero_to_v32accfloat();
}
// AIE2P-LABEL: define dso_local inreg noundef <64 x float> @_Z34test_broadcast_zero_to_v64accfloatv(
// AIE2P-SAME: ) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    ret <64 x float> zeroinitializer
//
v64accfloat test_broadcast_zero_to_v64accfloat() {
  return broadcast_zero_to_v64accfloat();
}

// AIE2P-LABEL: define dso_local %struct.v64bfp16ebs8 @_Z12shuffle_test12v64bfp16ebs8S_j(
// AIE2P-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], [[STRUCT_V64BFP16EBS8]] [[B_COERCE:%.*]], i32 noundef [[MODE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[A_COERCE_FCA_0_EXTRACT_I:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// AIE2P-NEXT:    [[A_COERCE_FCA_1_EXTRACT_I:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// AIE2P-NEXT:    [[B_COERCE_FCA_0_EXTRACT_I:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 0
// AIE2P-NEXT:    [[B_COERCE_FCA_1_EXTRACT_I:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[B_COERCE]], 1
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <8 x i8> } @llvm.aie2p.vshuffle.576.bfp16(<64 x i8> [[A_COERCE_FCA_0_EXTRACT_I]], <8 x i8> [[A_COERCE_FCA_1_EXTRACT_I]], <64 x i8> [[B_COERCE_FCA_0_EXTRACT_I]], <8 x i8> [[B_COERCE_FCA_1_EXTRACT_I]], i32 [[MODE]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <8 x i8> } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <8 x i8> } [[TMP0]], 1
// AIE2P-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS8]] poison, <64 x i8> [[TMP1]], 0
// AIE2P-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS8]] [[DOTFCA_0_INSERT_I]], <8 x i8> [[TMP2]], 1
// AIE2P-NEXT:    ret [[STRUCT_V64BFP16EBS8]] [[DOTFCA_1_INSERT_I]]
//
v64bfp16ebs8 shuffle_test(v64bfp16ebs8 a, v64bfp16ebs8 b, unsigned int mode) {
  return shuffle(a, b, mode);
}

// AIE2P-LABEL: define dso_local %struct.v64bfp16ebs16 @_Z12shuffle_test13v64bfp16ebs16S_j(
// AIE2P-SAME: [[STRUCT_V64BFP16EBS16:%.*]] [[A_COERCE:%.*]], [[STRUCT_V64BFP16EBS16]] [[B_COERCE:%.*]], i32 noundef [[MODE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[A_COERCE_FCA_0_EXTRACT_I:%.*]] = extractvalue [[STRUCT_V64BFP16EBS16]] [[A_COERCE]], 0
// AIE2P-NEXT:    [[A_COERCE_FCA_1_EXTRACT_I:%.*]] = extractvalue [[STRUCT_V64BFP16EBS16]] [[A_COERCE]], 1
// AIE2P-NEXT:    [[B_COERCE_FCA_0_EXTRACT_I:%.*]] = extractvalue [[STRUCT_V64BFP16EBS16]] [[B_COERCE]], 0
// AIE2P-NEXT:    [[B_COERCE_FCA_1_EXTRACT_I:%.*]] = extractvalue [[STRUCT_V64BFP16EBS16]] [[B_COERCE]], 1
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <8 x i8> } @llvm.aie2p.vshuffle.576.bfp16(<64 x i8> [[A_COERCE_FCA_0_EXTRACT_I]], <8 x i8> [[A_COERCE_FCA_1_EXTRACT_I]], <64 x i8> [[B_COERCE_FCA_0_EXTRACT_I]], <8 x i8> [[B_COERCE_FCA_1_EXTRACT_I]], i32 [[MODE]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <8 x i8> } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <8 x i8> } [[TMP0]], 1
// AIE2P-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS16]] poison, <64 x i8> [[TMP1]], 0
// AIE2P-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS16]] [[DOTFCA_0_INSERT_I]], <8 x i8> [[TMP2]], 1
// AIE2P-NEXT:    ret [[STRUCT_V64BFP16EBS16]] [[DOTFCA_1_INSERT_I]]
//
v64bfp16ebs16 shuffle_test(v64bfp16ebs16 a, v64bfp16ebs16 b, unsigned int mode) {
  return shuffle(a, b, mode);
}

// AIE2P-LABEL: define dso_local %struct.v64bfp16ebs8 @_Z12shuffle_test12v64bfp16ebs8j(
// AIE2P-SAME: [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], i32 noundef [[MODE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[A_COERCE_FCA_0_EXTRACT_I_I:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 0
// AIE2P-NEXT:    [[A_COERCE_FCA_1_EXTRACT_I_I:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <8 x i8> } @llvm.aie2p.vshuffle.576.bfp16(<64 x i8> [[A_COERCE_FCA_0_EXTRACT_I_I]], <8 x i8> [[A_COERCE_FCA_1_EXTRACT_I_I]], <64 x i8> undef, <8 x i8> undef, i32 [[MODE]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <8 x i8> } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <8 x i8> } [[TMP0]], 1
// AIE2P-NEXT:    [[DOTFCA_0_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS8]] poison, <64 x i8> [[TMP1]], 0
// AIE2P-NEXT:    [[DOTFCA_1_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS8]] [[DOTFCA_0_INSERT_I_I]], <8 x i8> [[TMP2]], 1
// AIE2P-NEXT:    ret [[STRUCT_V64BFP16EBS8]] [[DOTFCA_1_INSERT_I_I]]
//
v64bfp16ebs8 shuffle_test(v64bfp16ebs8 a, unsigned mode) {
  return shuffle(a ,mode);
}

// AIE2P-LABEL: define dso_local %struct.v64bfp16ebs16 @_Z12shuffle_test13v64bfp16ebs16j(
// AIE2P-SAME: [[STRUCT_V64BFP16EBS16:%.*]] [[A_COERCE:%.*]], i32 noundef [[MODE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2P-NEXT:  entry:
// AIE2P-NEXT:    [[A_COERCE_FCA_0_EXTRACT_I_I:%.*]] = extractvalue [[STRUCT_V64BFP16EBS16]] [[A_COERCE]], 0
// AIE2P-NEXT:    [[A_COERCE_FCA_1_EXTRACT_I_I:%.*]] = extractvalue [[STRUCT_V64BFP16EBS16]] [[A_COERCE]], 1
// AIE2P-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <8 x i8> } @llvm.aie2p.vshuffle.576.bfp16(<64 x i8> [[A_COERCE_FCA_0_EXTRACT_I_I]], <8 x i8> [[A_COERCE_FCA_1_EXTRACT_I_I]], <64 x i8> undef, <8 x i8> undef, i32 [[MODE]])
// AIE2P-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <8 x i8> } [[TMP0]], 0
// AIE2P-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <8 x i8> } [[TMP0]], 1
// AIE2P-NEXT:    [[DOTFCA_0_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS16]] poison, <64 x i8> [[TMP1]], 0
// AIE2P-NEXT:    [[DOTFCA_1_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS16]] [[DOTFCA_0_INSERT_I_I]], <8 x i8> [[TMP2]], 1
// AIE2P-NEXT:    ret [[STRUCT_V64BFP16EBS16]] [[DOTFCA_1_INSERT_I_I]]
//
v64bfp16ebs16 shuffle_test(v64bfp16ebs16 a, unsigned mode) {
  return shuffle(a,  mode);
}
