// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
//===- aie2p-ldst.cpp --------------------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2024-2026 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//
// RUN: %clang -O2 %s --target=aie2p -nostdlibinc -S -emit-llvm -o - | FileCheck %s

// CHECK-LABEL: @_Z24test_unpack_v32i16_v32i8Dv32_a(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.unpack.I512.I16.I8(<32 x i8> [[V:%.*]], i32 1)
// CHECK-NEXT:    ret <32 x i16> [[TMP0]]
//
v32int16 test_unpack_v32i16_v32i8(v32int8 v) {
  return unpack(v);
}

// CHECK-LABEL: @_Z21test_pack_v64i4_v64i8Dv64_hi(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i8> @llvm.aie2p.pack.I512.I4.I8(<64 x i8> [[V:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <32 x i8> [[TMP0]]
//
v64uint4 test_pack_v64i4_v64i8(v64uint8 v, int sign) {
  return pack(v, sign);
}

// CHECK-LABEL: @_Z23test_unpack_v64i8_v64i4Dv32_DU8_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i8> @llvm.aie2p.unpack.I512.I8.I4(<32 x i8> [[V:%.*]], i32 0)
// CHECK-NEXT:    ret <64 x i8> [[TMP0]]
//
v64uint8 test_unpack_v64i8_v64i4(v64uint4 v) {
  return unpack(v);
}

// CHECK-LABEL: @_Z22test_pack_v64i8_v64i16Dv64_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i8> @llvm.aie2p.pack.I1024.I8.I16(<64 x i16> [[V:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <64 x i8> [[TMP0]]
//
v64uint8 test_pack_v64i8_v64i16(v64uint16 v, int sign) {
  return pack(v, sign);
}

// CHECK-LABEL: @_Z24test_unpack_v64i16_v64i8Dv64_h(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i16> @llvm.aie2p.unpack.I1024.I16.I8(<64 x i8> [[V:%.*]], i32 0)
// CHECK-NEXT:    ret <64 x i16> [[TMP0]]
//
v64uint16 test_unpack_v64i16_v64i8(v64uint8 v) {
  return unpack(v);
}

// CHECK-LABEL: @_Z18test_fifo_st_resetRrPDv64_DB8_S0_R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2:![0-9]+]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7:![0-9]+]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10:![0-9]+]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <64 x i8> [[V:%.*]] to <16 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP2]], <32 x i32> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_reset(v128int4 * restrict &p, v128int4 v, fifo_state_t &s) {
  return fifo_st_reset(p, v, s);
}

// CHECK-LABEL: @_Z17test_fifo_st_pushRrPDv64_DB8_S0_R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11:![0-9]+]]
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <64 x i8> [[V:%.*]] to <16 x i32>
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP3]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_push(v128int4 * restrict &p, v128int4 v, fifo_state_t &s) {
  return fifo_st_push(p, v, s);
}

// CHECK-LABEL: @_Z18test_fifo_st_flushRrPDv64_DB8_R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush(v128int4 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush(p, s);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_1d_byteRrPDv64_DB8_R12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_1d_byte(v128int4 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_2d_byteRrPDv64_DB8_R12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_2d_byte(v128int4 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_3d_byteRrPDv64_DB8_R12fifo_state_tiiRiiiS6_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_3d_byte(v128int4 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1, int size2,
                                addr_t &count2, int inc2) {
  return fifo_st_flush_3d_byte(p, s, off, size1, count1, inc1, size2,
                               count2, inc2);
}

// CHECK-LABEL: @_Z23test_fifo_st_flush_bareRrPDv64_DB8_R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare(v128int4 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_bare(p, s);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_1d_byteRrPDv64_DB8_R12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_1d_byte(v128int4 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_bare_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_2d_byteRrPDv64_DB8_R12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_2d_byte(v128int4 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_bare_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_3d_byteRrPDv64_DB8_R12fifo_state_tiiRiiiS6_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_3d_byte(v128int4 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_bare_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// CHECK-LABEL: @_Z23test_fifo_st_flush_convRrPDv64_DB8_R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv(v128int4 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_conv(p, s);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_1d_byteRrPDv64_DB8_R12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_1d_byte(v128int4 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_conv_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_2d_byteRrPDv64_DB8_R12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_2d_byte(v128int4 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_conv_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_3d_byteRrPDv64_DB8_R12fifo_state_tiiRiiiS6_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_3d_byte(v128int4 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_conv_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// CHECK-LABEL: @_Z18test_fifo_st_resetRrPDv64_DU8_S0_R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <64 x i8> [[V:%.*]] to <16 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP2]], <32 x i32> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_reset(v128uint4 * restrict &p, v128uint4 v, fifo_state_t &s) {
  return fifo_st_reset(p, v, s);
}

// CHECK-LABEL: @_Z17test_fifo_st_pushRrPDv64_DU8_S0_R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <64 x i8> [[V:%.*]] to <16 x i32>
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP3]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_push(v128uint4 * restrict &p, v128uint4 v, fifo_state_t &s) {
  return fifo_st_push(p, v, s);
}

// CHECK-LABEL: @_Z18test_fifo_st_flushRrPDv64_DU8_R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush(v128uint4 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush(p, s);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_1d_byteRrPDv64_DU8_R12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_1d_byte(v128uint4 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_2d_byteRrPDv64_DU8_R12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_2d_byte(v128uint4 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_3d_byteRrPDv64_DU8_R12fifo_state_tiiRiiiS6_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_3d_byte(v128uint4 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1, int size2,
                                addr_t &count2, int inc2) {
  return fifo_st_flush_3d_byte(p, s, off, size1, count1, inc1, size2,
                               count2, inc2);
}

// CHECK-LABEL: @_Z23test_fifo_st_flush_bareRrPDv64_DU8_R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare(v128uint4 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_bare(p, s);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_1d_byteRrPDv64_DU8_R12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_1d_byte(v128uint4 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_bare_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_2d_byteRrPDv64_DU8_R12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_2d_byte(v128uint4 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_bare_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_3d_byteRrPDv64_DU8_R12fifo_state_tiiRiiiS6_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_3d_byte(v128uint4 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_bare_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// CHECK-LABEL: @_Z23test_fifo_st_flush_convRrPDv64_DU8_R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv(v128uint4 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_conv(p, s);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_1d_byteRrPDv64_DU8_R12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_1d_byte(v128uint4 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_conv_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_2d_byteRrPDv64_DU8_R12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_2d_byte(v128uint4 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_conv_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_3d_byteRrPDv64_DU8_R12fifo_state_tiiRiiiS6_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_3d_byte(v128uint4 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_conv_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// CHECK-LABEL: @_Z18test_fifo_st_resetRrPDv64_aS_R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <64 x i8> [[V:%.*]] to <16 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP2]], <32 x i32> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_reset(v64int8 * restrict &p, v64int8 v, fifo_state_t &s) {
  return fifo_st_reset(p, v, s);
}

// CHECK-LABEL: @_Z17test_fifo_st_pushRrPDv64_aS_R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <64 x i8> [[V:%.*]] to <16 x i32>
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP3]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_push(v64int8 * restrict &p, v64int8 v, fifo_state_t &s) {
  return fifo_st_push(p, v, s);
}

// CHECK-LABEL: @_Z18test_fifo_st_flushRrPDv64_aR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush(v64int8 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush(p, s);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_1d_byteRrPDv64_aR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_1d_byte(v64int8 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_2d_byteRrPDv64_aR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_2d_byte(v64int8 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_3d_byteRrPDv64_aR12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_3d_byte(v64int8 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1, int size2,
                                addr_t &count2, int inc2) {
  return fifo_st_flush_3d_byte(p, s, off, size1, count1, inc1, size2,
                               count2, inc2);
}

// CHECK-LABEL: @_Z23test_fifo_st_flush_bareRrPDv64_aR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare(v64int8 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_bare(p, s);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_1d_byteRrPDv64_aR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_1d_byte(v64int8 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_bare_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_2d_byteRrPDv64_aR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_2d_byte(v64int8 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_bare_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_3d_byteRrPDv64_aR12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_3d_byte(v64int8 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_bare_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// CHECK-LABEL: @_Z23test_fifo_st_flush_convRrPDv64_aR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv(v64int8 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_conv(p, s);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_1d_byteRrPDv64_aR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_1d_byte(v64int8 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_conv_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_2d_byteRrPDv64_aR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_2d_byte(v64int8 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_conv_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_3d_byteRrPDv64_aR12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_3d_byte(v64int8 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_conv_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// CHECK-LABEL: @_Z18test_fifo_st_resetRrPDv64_hS_R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <64 x i8> [[V:%.*]] to <16 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP2]], <32 x i32> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_reset(v64uint8 * restrict &p, v64uint8 v, fifo_state_t &s) {
  return fifo_st_reset(p, v, s);
}

// CHECK-LABEL: @_Z17test_fifo_st_pushRrPDv64_hS_R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <64 x i8> [[V:%.*]] to <16 x i32>
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP3]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_push(v64uint8 * restrict &p, v64uint8 v, fifo_state_t &s) {
  return fifo_st_push(p, v, s);
}

// CHECK-LABEL: @_Z18test_fifo_st_flushRrPDv64_hR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush(v64uint8 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush(p, s);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_1d_byteRrPDv64_hR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_1d_byte(v64uint8 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_2d_byteRrPDv64_hR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_2d_byte(v64uint8 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_3d_byteRrPDv64_hR12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_3d_byte(v64uint8 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1, int size2,
                                addr_t &count2, int inc2) {
  return fifo_st_flush_3d_byte(p, s, off, size1, count1, inc1, size2,
                               count2, inc2);
}

// CHECK-LABEL: @_Z23test_fifo_st_flush_bareRrPDv64_hR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare(v64uint8 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_bare(p, s);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_1d_byteRrPDv64_hR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_1d_byte(v64uint8 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_bare_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_2d_byteRrPDv64_hR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_2d_byte(v64uint8 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_bare_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_3d_byteRrPDv64_hR12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_3d_byte(v64uint8 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_bare_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// CHECK-LABEL: @_Z23test_fifo_st_flush_convRrPDv64_hR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv(v64uint8 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_conv(p, s);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_1d_byteRrPDv64_hR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_1d_byte(v64uint8 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_conv_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_2d_byteRrPDv64_hR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_2d_byte(v64uint8 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_conv_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_3d_byteRrPDv64_hR12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_3d_byte(v64uint8 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_conv_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// CHECK-LABEL: @_Z18test_fifo_st_resetRrPDv32_sS_R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i16> [[V:%.*]] to <16 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP2]], <32 x i32> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_reset(v32int16 * restrict &p, v32int16 v, fifo_state_t &s) {
  return fifo_st_reset(p, v, s);
}

// CHECK-LABEL: @_Z17test_fifo_st_pushRrPDv32_sS_R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <32 x i16> [[V:%.*]] to <16 x i32>
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP3]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_push(v32int16 * restrict &p, v32int16 v, fifo_state_t &s) {
  return fifo_st_push(p, v, s);
}

// CHECK-LABEL: @_Z18test_fifo_st_flushRrPDv32_sR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush(v32int16 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush(p, s);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_1d_byteRrPDv32_sR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_1d_byte(v32int16 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_2d_byteRrPDv32_sR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_2d_byte(v32int16 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_3d_byteRrPDv32_sR12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_3d_byte(v32int16 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1, int size2,
                                addr_t &count2, int inc2) {
  return fifo_st_flush_3d_byte(p, s, off, size1, count1, inc1, size2,
                               count2, inc2);
}

// CHECK-LABEL: @_Z23test_fifo_st_flush_bareRrPDv32_sR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare(v32int16 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_bare(p, s);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_1d_byteRrPDv32_sR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_1d_byte(v32int16 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_bare_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_2d_byteRrPDv32_sR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_2d_byte(v32int16 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_bare_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_3d_byteRrPDv32_sR12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_3d_byte(v32int16 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_bare_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// CHECK-LABEL: @_Z23test_fifo_st_flush_convRrPDv32_sR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv(v32int16 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_conv(p, s);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_1d_byteRrPDv32_sR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_1d_byte(v32int16 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_conv_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_2d_byteRrPDv32_sR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_2d_byte(v32int16 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_conv_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_3d_byteRrPDv32_sR12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_3d_byte(v32int16 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_conv_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// CHECK-LABEL: @_Z18test_fifo_st_resetRrPDv32_tS_R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i16> [[V:%.*]] to <16 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP2]], <32 x i32> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_reset(v32uint16 * restrict &p, v32uint16 v, fifo_state_t &s) {
  return fifo_st_reset(p, v, s);
}

// CHECK-LABEL: @_Z17test_fifo_st_pushRrPDv32_tS_R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <32 x i16> [[V:%.*]] to <16 x i32>
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP3]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_push(v32uint16 * restrict &p, v32uint16 v, fifo_state_t &s) {
  return fifo_st_push(p, v, s);
}

// CHECK-LABEL: @_Z18test_fifo_st_flushRrPDv32_tR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush(v32uint16 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush(p, s);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_1d_byteRrPDv32_tR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_1d_byte(v32uint16 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_2d_byteRrPDv32_tR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_2d_byte(v32uint16 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_3d_byteRrPDv32_tR12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_3d_byte(v32uint16 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1, int size2,
                                addr_t &count2, int inc2) {
  return fifo_st_flush_3d_byte(p, s, off, size1, count1, inc1, size2,
                               count2, inc2);
}

// CHECK-LABEL: @_Z23test_fifo_st_flush_bareRrPDv32_tR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare(v32uint16 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_bare(p, s);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_1d_byteRrPDv32_tR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_1d_byte(v32uint16 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_bare_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_2d_byteRrPDv32_tR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_2d_byte(v32uint16 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_bare_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_3d_byteRrPDv32_tR12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_3d_byte(v32uint16 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_bare_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// CHECK-LABEL: @_Z23test_fifo_st_flush_convRrPDv32_tR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv(v32uint16 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_conv(p, s);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_1d_byteRrPDv32_tR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_1d_byte(v32uint16 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_conv_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_2d_byteRrPDv32_tR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_2d_byte(v32uint16 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_conv_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_3d_byteRrPDv32_tR12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_3d_byte(v32uint16 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_conv_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// CHECK-LABEL: @_Z18test_fifo_st_resetRrPDv16_iS_R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[V:%.*]], <32 x i32> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// CHECK-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_reset(v16int32 * restrict &p, v16int32 v, fifo_state_t &s) {
  return fifo_st_reset(p, v, s);
}

// CHECK-LABEL: @_Z17test_fifo_st_pushRrPDv16_iS_R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[V:%.*]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_push(v16int32 * restrict &p, v16int32 v, fifo_state_t &s) {
  return fifo_st_push(p, v, s);
}

// CHECK-LABEL: @_Z18test_fifo_st_flushRrPDv16_iR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush(v16int32 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush(p, s);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_1d_byteRrPDv16_iR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_1d_byte(v16int32 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_2d_byteRrPDv16_iR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_2d_byte(v16int32 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_3d_byteRrPDv16_iR12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_3d_byte(v16int32 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1, int size2,
                                addr_t &count2, int inc2) {
  return fifo_st_flush_3d_byte(p, s, off, size1, count1, inc1, size2,
                               count2, inc2);
}

// CHECK-LABEL: @_Z23test_fifo_st_flush_bareRrPDv16_iR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare(v16int32 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_bare(p, s);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_1d_byteRrPDv16_iR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_1d_byte(v16int32 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_bare_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_2d_byteRrPDv16_iR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_2d_byte(v16int32 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_bare_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_3d_byteRrPDv16_iR12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_3d_byte(v16int32 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_bare_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// CHECK-LABEL: @_Z23test_fifo_st_flush_convRrPDv16_iR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv(v16int32 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_conv(p, s);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_1d_byteRrPDv16_iR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_1d_byte(v16int32 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_conv_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_2d_byteRrPDv16_iR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_2d_byte(v16int32 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_conv_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_3d_byteRrPDv16_iR12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_3d_byte(v16int32 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_conv_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// CHECK-LABEL: @_Z18test_fifo_st_resetRrPDv16_jS_R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[V:%.*]], <32 x i32> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// CHECK-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_reset(v16uint32 * restrict &p, v16uint32 v, fifo_state_t &s) {
  return fifo_st_reset(p, v, s);
}

// CHECK-LABEL: @_Z17test_fifo_st_pushRrPDv16_jS_R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[V:%.*]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_push(v16uint32 * restrict &p, v16uint32 v, fifo_state_t &s) {
  return fifo_st_push(p, v, s);
}

// CHECK-LABEL: @_Z18test_fifo_st_flushRrPDv16_jR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush(v16uint32 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush(p, s);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_1d_byteRrPDv16_jR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_1d_byte(v16uint32 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_2d_byteRrPDv16_jR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_2d_byte(v16uint32 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_3d_byteRrPDv16_jR12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_3d_byte(v16uint32 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1, int size2,
                                addr_t &count2, int inc2) {
  return fifo_st_flush_3d_byte(p, s, off, size1, count1, inc1, size2,
                               count2, inc2);
}

// CHECK-LABEL: @_Z23test_fifo_st_flush_bareRrPDv16_jR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare(v16uint32 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_bare(p, s);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_1d_byteRrPDv16_jR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_1d_byte(v16uint32 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_bare_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_2d_byteRrPDv16_jR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_2d_byte(v16uint32 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_bare_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_3d_byteRrPDv16_jR12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_3d_byte(v16uint32 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_bare_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// CHECK-LABEL: @_Z23test_fifo_st_flush_convRrPDv16_jR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv(v16uint32 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_conv(p, s);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_1d_byteRrPDv16_jR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_1d_byte(v16uint32 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_conv_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_2d_byteRrPDv16_jR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_2d_byte(v16uint32 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_conv_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_3d_byteRrPDv16_jR12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_3d_byte(v16uint32 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_conv_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// CHECK-LABEL: @_Z18test_fifo_st_resetRrPDv32_8bfloat16S0_R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x bfloat> [[V:%.*]] to <16 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP2]], <32 x i32> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_reset(v32bfloat16 * restrict &p, v32bfloat16 v, fifo_state_t &s) {
  return fifo_st_reset(p, v, s);
}

// CHECK-LABEL: @_Z17test_fifo_st_pushRrPDv32_8bfloat16S0_R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <32 x bfloat> [[V:%.*]] to <16 x i32>
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP3]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_push(v32bfloat16 * restrict &p, v32bfloat16 v, fifo_state_t &s) {
  return fifo_st_push(p, v, s);
}

// CHECK-LABEL: @_Z18test_fifo_st_flushRrPDv32_8bfloat16R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush(v32bfloat16 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush(p, s);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_1d_byteRrPDv32_8bfloat16R12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_1d_byte(v32bfloat16 * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_2d_byteRrPDv32_8bfloat16R12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_2d_byte(v32bfloat16 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_3d_byteRrPDv32_8bfloat16R12fifo_state_tiiRiiiS6_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_3d_byte(v32bfloat16 * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1, int size2,
                                addr_t &count2, int inc2) {
  return fifo_st_flush_3d_byte(p, s, off, size1, count1, inc1, size2,
                               count2, inc2);
}

// CHECK-LABEL: @_Z23test_fifo_st_flush_bareRrPDv32_8bfloat16R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare(v32bfloat16 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_bare(p, s);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_1d_byteRrPDv32_8bfloat16R12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_1d_byte(v32bfloat16 * restrict &p, fifo_state_t &s,
                                     int off) {
  return fifo_st_flush_bare_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_2d_byteRrPDv32_8bfloat16R12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_2d_byte(v32bfloat16 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_bare_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_3d_byteRrPDv32_8bfloat16R12fifo_state_tiiRiiiS6_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_3d_byte(v32bfloat16 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_bare_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// CHECK-LABEL: @_Z23test_fifo_st_flush_convRrPDv32_8bfloat16R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv(v32bfloat16 * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_conv(p, s);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_1d_byteRrPDv32_8bfloat16R12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_1d_byte(v32bfloat16 * restrict &p, fifo_state_t &s,
                                     int off) {
  return fifo_st_flush_conv_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_2d_byteRrPDv32_8bfloat16R12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_2d_byte(v32bfloat16 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_conv_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_3d_byteRrPDv32_8bfloat16R12fifo_state_tiiRiiiS6_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_3d_byte(v32bfloat16 * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_conv_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// CHECK-LABEL: @_Z18test_fifo_st_resetRrPDv16_fS_R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x float> [[V:%.*]] to <16 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP2]], <32 x i32> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_reset(v16float * restrict &p, v16float v, fifo_state_t &s) {
  return fifo_st_reset(p, v, s);
}

// CHECK-LABEL: @_Z17test_fifo_st_pushRrPDv16_fS_R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <16 x float> [[V:%.*]] to <16 x i32>
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP3]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_push(v16float * restrict &p, v16float v, fifo_state_t &s) {
  return fifo_st_push(p, v, s);
}

// CHECK-LABEL: @_Z18test_fifo_st_flushRrPDv16_fR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush(v16float * restrict &p, fifo_state_t &s) {
  return fifo_st_flush(p, s);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_1d_byteRrPDv16_fR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_1d_byte(v16float * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_2d_byteRrPDv16_fR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_2d_byte(v16float * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_3d_byteRrPDv16_fR12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_3d_byte(v16float * restrict &p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1, int size2,
                                addr_t &count2, int inc2) {
  return fifo_st_flush_3d_byte(p, s, off, size1, count1, inc1, size2,
                               count2, inc2);
}

// CHECK-LABEL: @_Z23test_fifo_st_flush_bareRrPDv16_fR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare(v16float * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_bare(p, s);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_1d_byteRrPDv16_fR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_1d_byte(v16float * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_bare_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_2d_byteRrPDv16_fR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_2d_byte(v16float * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_bare_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_3d_byteRrPDv16_fR12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_3d_byte(v16float * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_bare_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// CHECK-LABEL: @_Z23test_fifo_st_flush_convRrPDv16_fR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv(v16float * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_conv(p, s);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_1d_byteRrPDv16_fR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_1d_byte(v16float * restrict &p, fifo_state_t &s, int off) {
  return fifo_st_flush_conv_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_2d_byteRrPDv16_fR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_2d_byte(v16float * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_conv_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_3d_byteRrPDv16_fR12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_3d_byte(v16float * restrict &p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_conv_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// CHECK-LABEL: @_Z18test_fifo_st_resetRrP22v64bfp16ebs8_unaligned12v64bfp16ebs8R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8:%.*]] [[V_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[V_COERCE]], 1
// CHECK-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.576.bfp16.p0.p0(ptr [[TMP2]], <64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <32 x i32> [[TMP3]], i32 0)
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_reset(v64bfp16ebs8_unaligned * restrict &p, v64bfp16ebs8 v,
                          fifo_state_t &s) {
  return fifo_st_reset(p, v, s);
}

// CHECK-LABEL: @_Z17test_fifo_st_pushRrP22v64bfp16ebs8_unaligned12v64bfp16ebs8R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8:%.*]] [[V_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[V_COERCE]], 1
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP5:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.576.bfp16.p0.p0(ptr [[TMP2]], <64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <32 x i32> [[TMP3]], i32 [[TMP4]])
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP5]], 0
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP5]], 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP5]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_push(v64bfp16ebs8_unaligned * restrict &p, v64bfp16ebs8 v,
                       fifo_state_t &s) {
  return fifo_st_push(p, v, s);
}

// CHECK-LABEL: @_Z18test_fifo_st_flushRrP22v64bfp16ebs8_unalignedR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush(v64bfp16ebs8_unaligned * restrict &p, fifo_state_t &s) {
  return fifo_st_flush(p, s);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_1d_byteRrP22v64bfp16ebs8_unalignedR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_1d_byte(v64bfp16ebs8_unaligned * restrict &p, fifo_state_t &s,
                                int off) {
  return fifo_st_flush_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_2d_byteRrP22v64bfp16ebs8_unalignedR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_2d_byte(v64bfp16ebs8_unaligned * restrict &p, fifo_state_t &s,
                                int off, int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_3d_byteRrP22v64bfp16ebs8_unalignedR12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_3d_byte(v64bfp16ebs8_unaligned * restrict &p, fifo_state_t &s,
                                int off, int size1, addr_t &count1, int inc1,
                                int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_3d_byte(p, s, off, size1, count1, inc1, size2,
                               count2, inc2);
}

// CHECK-LABEL: @_Z23test_fifo_st_flush_bareRrP22v64bfp16ebs8_unalignedR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare(v64bfp16ebs8_unaligned * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_bare(p, s);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_1d_byteRrP22v64bfp16ebs8_unalignedR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_1d_byte(v64bfp16ebs8_unaligned * restrict &p,
                                     fifo_state_t &s, int off) {
  return fifo_st_flush_bare_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_2d_byteRrP22v64bfp16ebs8_unalignedR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_2d_byte(v64bfp16ebs8_unaligned * restrict &p,
                                     fifo_state_t &s, int off, int size1,
                                     addr_t &count1, int inc1) {
  return fifo_st_flush_bare_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_3d_byteRrP22v64bfp16ebs8_unalignedR12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_3d_byte(v64bfp16ebs8_unaligned * restrict &p,
                                     fifo_state_t &s, int off, int size1,
                                     addr_t &count1, int inc1, int size2,
                                     addr_t &count2, int inc2) {
  return fifo_st_flush_bare_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// CHECK-LABEL: @_Z23test_fifo_st_flush_convRrP22v64bfp16ebs8_unalignedR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv(v64bfp16ebs8_unaligned * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_conv(p, s);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_1d_byteRrP22v64bfp16ebs8_unalignedR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_1d_byte(v64bfp16ebs8_unaligned * restrict &p,
                                     fifo_state_t &s, int off) {
  return fifo_st_flush_conv_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_2d_byteRrP22v64bfp16ebs8_unalignedR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_2d_byte(v64bfp16ebs8_unaligned * restrict &p,
                                     fifo_state_t &s, int off, int size1,
                                     addr_t &count1, int inc1) {
  return fifo_st_flush_conv_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_3d_byteRrP22v64bfp16ebs8_unalignedR12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_3d_byte(v64bfp16ebs8_unaligned * restrict &p,
                                     fifo_state_t &s, int off, int size1,
                                     addr_t &count1, int inc1, int size2,
                                     addr_t &count2, int inc2) {
  return fifo_st_flush_conv_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// CHECK-LABEL: @_Z18test_fifo_st_resetRrP23v64bfp16ebs16_unaligned13v64bfp16ebs16R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS16:%.*]] [[V_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS16]] [[V_COERCE]], 1
// CHECK-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.544.bfp16.p0.p0(ptr [[TMP2]], <64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <32 x i32> [[TMP3]], i32 0)
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_reset(v64bfp16ebs16_unaligned * restrict &p, v64bfp16ebs16 v,
                          fifo_state_t &s) {
  return fifo_st_reset(p, v, s);
}

// CHECK-LABEL: @_Z17test_fifo_st_pushRrP23v64bfp16ebs16_unaligned13v64bfp16ebs16R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS16:%.*]] [[V_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS16]] [[V_COERCE]], 1
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP5:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.544.bfp16.p0.p0(ptr [[TMP2]], <64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <32 x i32> [[TMP3]], i32 [[TMP4]])
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP5]], 0
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP5]], 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP5]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_push(v64bfp16ebs16_unaligned * restrict &p, v64bfp16ebs16 v,
                       fifo_state_t &s) {
  return fifo_st_push(p, v, s);
}

// CHECK-LABEL: @_Z18test_fifo_st_flushRrP23v64bfp16ebs16_unalignedR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush(v64bfp16ebs16_unaligned * restrict &p, fifo_state_t &s) {
  return fifo_st_flush(p, s);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_1d_byteRrP23v64bfp16ebs16_unalignedR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_1d_byte(v64bfp16ebs16_unaligned * restrict &p, fifo_state_t &s,
                                int off) {
  return fifo_st_flush_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_2d_byteRrP23v64bfp16ebs16_unalignedR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_2d_byte(v64bfp16ebs16_unaligned * restrict &p, fifo_state_t &s,
                                int off, int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_3d_byteRrP23v64bfp16ebs16_unalignedR12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_3d_byte(v64bfp16ebs16_unaligned * restrict &p, fifo_state_t &s,
                                int off, int size1, addr_t &count1, int inc1,
                                int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_3d_byte(p, s, off, size1, count1, inc1, size2,
                               count2, inc2);
}

// CHECK-LABEL: @_Z23test_fifo_st_flush_bareRrP23v64bfp16ebs16_unalignedR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare(v64bfp16ebs16_unaligned * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_bare(p, s);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_1d_byteRrP23v64bfp16ebs16_unalignedR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_1d_byte(v64bfp16ebs16_unaligned * restrict &p,
                                     fifo_state_t &s, int off) {
  return fifo_st_flush_bare_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_2d_byteRrP23v64bfp16ebs16_unalignedR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_2d_byte(v64bfp16ebs16_unaligned * restrict &p,
                                     fifo_state_t &s, int off, int size1,
                                     addr_t &count1, int inc1) {
  return fifo_st_flush_bare_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_3d_byteRrP23v64bfp16ebs16_unalignedR12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_3d_byte(v64bfp16ebs16_unaligned * restrict &p,
                                     fifo_state_t &s, int off, int size1,
                                     addr_t &count1, int inc1, int size2,
                                     addr_t &count2, int inc2) {
  return fifo_st_flush_bare_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// CHECK-LABEL: @_Z23test_fifo_st_flush_convRrP23v64bfp16ebs16_unalignedR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv(v64bfp16ebs16_unaligned * restrict &p, fifo_state_t &s) {
  return fifo_st_flush_conv(p, s);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_1d_byteRrP23v64bfp16ebs16_unalignedR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_1d_byte(v64bfp16ebs16_unaligned * restrict &p,
                                     fifo_state_t &s, int off) {
  return fifo_st_flush_conv_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_2d_byteRrP23v64bfp16ebs16_unalignedR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_2d_byte(v64bfp16ebs16_unaligned * restrict &p,
                                     fifo_state_t &s, int off, int size1,
                                     addr_t &count1, int inc1) {
  return fifo_st_flush_conv_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_3d_byteRrP23v64bfp16ebs16_unalignedR12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_3d_byte(v64bfp16ebs16_unaligned * restrict &p,
                                     fifo_state_t &s, int off, int size1,
                                     addr_t &count1, int inc1, int size2,
                                     addr_t &count2, int inc2) {
  return fifo_st_flush_conv_3d_byte(p, s, off, size1, count1, inc1,
                                    size2, count2, inc2);
}

// CHECK-LABEL: @_Z18test_fifo_st_resetPU3AS522v64bfp16ebs8_unaligned12v64bfp16ebs8R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8:%.*]] [[V_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[V_COERCE]], 1
// CHECK-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP2:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.576.bfp16.p5.p5(ptr addrspace(5) [[P:%.*]], <64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <32 x i32> [[TMP2]], i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// CHECK-NEXT:    ret void
//
void test_fifo_st_reset(v64bfp16ebs8_unaligned __aie_dm_resource_a * restrict p, v64bfp16ebs8 v,
                          fifo_state_t &s) {
  return fifo_st_reset(p, v, s);
}

// CHECK-LABEL: @_Z17test_fifo_st_pushPU3AS522v64bfp16ebs8_unaligned12v64bfp16ebs8R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8:%.*]] [[V_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[V_COERCE]], 1
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP2:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.576.bfp16.p5.p5(ptr addrspace(5) [[P:%.*]], <64 x i8> [[TMP0]], <8 x i8> [[TMP1]], <32 x i32> [[TMP2]], i32 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    ret void
//
void test_fifo_st_push(v64bfp16ebs8_unaligned __aie_dm_resource_a * restrict p, v64bfp16ebs8 v,
                       fifo_state_t &s) {
  return fifo_st_push(p, v, s);
}

// CHECK-LABEL: @_Z18test_fifo_st_flushPU3AS522v64bfp16ebs8_unalignedR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p5.p5(ptr addrspace(5) [[P:%.*]], <32 x i32> [[TMP0]], i32 [[TMP1]])
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP2]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP2]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP3]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP4]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush(v64bfp16ebs8_unaligned __aie_dm_resource_a * restrict p, fifo_state_t &s) {
  return fifo_st_flush(p, s);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_1d_bytePU3AS522v64bfp16ebs8_unalignedR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP2:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p5.p5(ptr addrspace(5) [[P:%.*]], <32 x i32> [[TMP0]], i32 [[TMP1]], i20 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP5]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_1d_byte(v64bfp16ebs8_unaligned __aie_dm_resource_a * restrict p, fifo_state_t &s,
                                int off) {
  return fifo_st_flush_1d_byte(p, s, off);
}

// CHECK
// CHECK-LABEL: @_Z26test_fifo_st_flush_2d_bytePU3AS522v64bfp16ebs8_unalignedR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP2:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP5:%.*]] = trunc i32 [[TMP4]] to i20
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = tail call { ptr addrspace(5), <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p5.p5(ptr addrspace(5) [[P:%.*]], <32 x i32> [[TMP0]], i32 [[TMP1]], i20 [[TMP2]], i20 [[TMP3]], i20 [[TMP5]], i20 [[TMP6]])
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20 } [[TMP7]], 1
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20 } [[TMP7]], 2
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20 } [[TMP7]], 3
// CHECK-NEXT:    [[TMP11:%.*]] = zext i20 [[TMP10]] to i32
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP8]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP9]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_2d_byte(v64bfp16ebs8_unaligned __aie_dm_resource_a * restrict p, fifo_state_t &s,
                                int off, int size1, addr_t &count1, int inc1) {
  return fifo_st_flush_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_3d_bytePU3AS522v64bfp16ebs8_unalignedR12fifo_state_tiiRiiiS4_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP2:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP5:%.*]] = trunc i32 [[TMP4]] to i20
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP9:%.*]] = trunc i32 [[TMP8]] to i20
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = tail call { ptr addrspace(5), <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p5.p5(ptr addrspace(5) [[P:%.*]], <32 x i32> [[TMP0]], i32 [[TMP1]], i20 [[TMP2]], i20 [[TMP3]], i20 [[TMP5]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP9]], i20 [[TMP10]])
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20 } [[TMP11]], 1
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20 } [[TMP11]], 2
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20 } [[TMP11]], 3
// CHECK-NEXT:    [[TMP15:%.*]] = zext i20 [[TMP14]] to i32
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20 } [[TMP11]], 4
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP12]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_3d_byte(v64bfp16ebs8_unaligned __aie_dm_resource_a * restrict p, fifo_state_t &s,
                                int off, int size1, addr_t &count1, int inc1,
                                int size2, addr_t &count2, int inc2) {
  return fifo_st_flush_3d_byte(p, s, off, size1, count1, inc1, size2,
                               count2, inc2);
}

// CHECK-LABEL: @_Z18test_fifo_ld_resetRPDv64_DB8_R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// CHECK-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_ld_reset(v128int4 *&p, fifo_state_t &s) {
  return fifo_ld_reset(p, s);
}

// CHECK-LABEL: @_Z17test_fifo_ld_fillRPDv64_DB8_R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_ld_fill(v128int4 *&p, fifo_state_t &s) {
  return fifo_ld_fill(p, s);
}

// CHECK-LABEL: @_Z16test_fifo_ld_popRPDv64_DB8_R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 3
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret <64 x i8> [[TMP4]]
//
v128int4 test_fifo_ld_pop(v128int4 *&p, fifo_state_t &s) {
  return fifo_ld_pop(p, s);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_1d_byteRPDv64_DB8_R12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.1d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 3
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// CHECK-NEXT:    ret <64 x i8> [[TMP5]]
//
v128int4 test_fifo_ld_pop_1d_byte(v128int4 *&p, fifo_state_t &s, int off) {
  return fifo_ld_pop_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_2d_byteRPDv64_DB8_R12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.ld.pop.2d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 4
// CHECK-NEXT:    [[TMP14:%.*]] = zext i20 [[TMP13]] to i32
// CHECK-NEXT:    store i32 [[TMP14]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP12]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// CHECK-NEXT:    ret <64 x i8> [[TMP9]]
//
v128int4 test_fifo_ld_pop_2d_byte(v128int4 *&p, fifo_state_t &s, int off,
                                  int size1, addr_t &count1, int inc1) {
  return fifo_ld_pop_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_3d_byteRPDv64_DB8_R12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.ld.pop.3d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 5
// CHECK-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// CHECK-NEXT:    store i32 [[TMP18]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP20]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP16]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP14]], ptr [[P]], align 4
// CHECK-NEXT:    ret <64 x i8> [[TMP13]]
//
v128int4 test_fifo_ld_pop_3d_byte(v128int4 *&p, fifo_state_t &s, int off,
                                  int size1, addr_t &count1, int inc1,
                                  int size2, addr_t &count2, int inc2) {
  return fifo_ld_pop_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}


// CHECK-LABEL: @_Z18test_fifo_ld_resetRPDv64_DU8_R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// CHECK-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_ld_reset(v128uint4 *&p, fifo_state_t &s) {
  return fifo_ld_reset(p, s);
}

// CHECK-LABEL: @_Z17test_fifo_ld_fillRPDv64_DU8_R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_ld_fill(v128uint4 *&p, fifo_state_t &s) {
  return fifo_ld_fill(p, s);
}

// CHECK-LABEL: @_Z16test_fifo_ld_popRPDv64_DU8_R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 3
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret <64 x i8> [[TMP4]]
//
v128uint4 test_fifo_ld_pop(v128uint4 *&p, fifo_state_t &s) {
  return fifo_ld_pop(p, s);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_1d_byteRPDv64_DU8_R12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.1d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 3
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// CHECK-NEXT:    ret <64 x i8> [[TMP5]]
//
v128uint4 test_fifo_ld_pop_1d_byte(v128uint4 *&p, fifo_state_t &s, int off) {
  return fifo_ld_pop_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_2d_byteRPDv64_DU8_R12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.ld.pop.2d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 4
// CHECK-NEXT:    [[TMP14:%.*]] = zext i20 [[TMP13]] to i32
// CHECK-NEXT:    store i32 [[TMP14]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP12]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// CHECK-NEXT:    ret <64 x i8> [[TMP9]]
//
v128uint4 test_fifo_ld_pop_2d_byte(v128uint4 *&p, fifo_state_t &s, int off,
                                   int size1, addr_t &count1, int inc1) {
  return fifo_ld_pop_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_3d_byteRPDv64_DU8_R12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.ld.pop.3d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 5
// CHECK-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// CHECK-NEXT:    store i32 [[TMP18]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP20]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP16]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP14]], ptr [[P]], align 4
// CHECK-NEXT:    ret <64 x i8> [[TMP13]]
//
v128uint4 test_fifo_ld_pop_3d_byte(v128uint4 *&p, fifo_state_t &s, int off,
                                   int size1, addr_t &count1, int inc1,
                                   int size2, addr_t &count2, int inc2) {
  return fifo_ld_pop_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}


// CHECK-LABEL: @_Z18test_fifo_ld_resetRPDv64_aR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// CHECK-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_ld_reset(v64int8 *&p, fifo_state_t &s) {
  return fifo_ld_reset(p, s);
}

// CHECK-LABEL: @_Z17test_fifo_ld_fillRPDv64_aR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_ld_fill(v64int8 *&p, fifo_state_t &s) {
  return fifo_ld_fill(p, s);
}

// CHECK-LABEL: @_Z16test_fifo_ld_popRPDv64_aR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 3
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret <64 x i8> [[TMP4]]
//
v64int8 test_fifo_ld_pop(v64int8 *&p, fifo_state_t &s) {
  return fifo_ld_pop(p, s);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_1d_byteRPDv64_aR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.1d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 3
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// CHECK-NEXT:    ret <64 x i8> [[TMP5]]
//
v64int8 test_fifo_ld_pop_1d_byte(v64int8 *&p, fifo_state_t &s, int off) {
  return fifo_ld_pop_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_2d_byteRPDv64_aR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.ld.pop.2d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 4
// CHECK-NEXT:    [[TMP14:%.*]] = zext i20 [[TMP13]] to i32
// CHECK-NEXT:    store i32 [[TMP14]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP12]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// CHECK-NEXT:    ret <64 x i8> [[TMP9]]
//
v64int8 test_fifo_ld_pop_2d_byte(v64int8 *&p, fifo_state_t &s, int off,
                                 int size1, addr_t &count1, int inc1) {
  return fifo_ld_pop_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_3d_byteRPDv64_aR12fifo_state_tiiRiiiS4_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.ld.pop.3d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 5
// CHECK-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// CHECK-NEXT:    store i32 [[TMP18]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP20]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP16]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP14]], ptr [[P]], align 4
// CHECK-NEXT:    ret <64 x i8> [[TMP13]]
//
v64int8 test_fifo_ld_pop_3d_byte(v64int8 *&p, fifo_state_t &s, int off,
                                 int size1, addr_t &count1, int inc1, int size2,
                                 addr_t &count2, int inc2) {
  return fifo_ld_pop_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}

// CHECK-LABEL: @_Z18test_fifo_ld_resetRPDv64_hR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// CHECK-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_ld_reset(v64uint8 *&p, fifo_state_t &s) {
  return fifo_ld_reset(p, s);
}

// CHECK-LABEL: @_Z17test_fifo_ld_fillRPDv64_hR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_ld_fill(v64uint8 *&p, fifo_state_t &s) {
  return fifo_ld_fill(p, s);
}

// CHECK-LABEL: @_Z16test_fifo_ld_popRPDv64_hR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 3
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret <64 x i8> [[TMP4]]
//
v64uint8 test_fifo_ld_pop(v64uint8 *&p, fifo_state_t &s) {
  return fifo_ld_pop(p, s);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_1d_byteRPDv64_hR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.1d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 3
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// CHECK-NEXT:    ret <64 x i8> [[TMP5]]
//
v64uint8 test_fifo_ld_pop_1d_byte(v64uint8 *&p, fifo_state_t &s, int off) {
  return fifo_ld_pop_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_2d_byteRPDv64_hR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.ld.pop.2d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 4
// CHECK-NEXT:    [[TMP14:%.*]] = zext i20 [[TMP13]] to i32
// CHECK-NEXT:    store i32 [[TMP14]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP12]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// CHECK-NEXT:    ret <64 x i8> [[TMP9]]
//
v64uint8 test_fifo_ld_pop_2d_byte(v64uint8 *&p, fifo_state_t &s, int off,
                                  int size1, addr_t &count1, int inc1) {
  return fifo_ld_pop_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_3d_byteRPDv64_hR12fifo_state_tiiRiiiS4_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.ld.pop.3d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 5
// CHECK-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// CHECK-NEXT:    store i32 [[TMP18]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP20]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP16]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP14]], ptr [[P]], align 4
// CHECK-NEXT:    ret <64 x i8> [[TMP13]]
//
v64uint8 test_fifo_ld_pop_3d_byte(v64uint8 *&p, fifo_state_t &s, int off,
                                  int size1, addr_t &count1, int inc1,
                                  int size2, addr_t &count2, int inc2) {
  return fifo_ld_pop_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}

// CHECK-LABEL: @_Z18test_fifo_ld_resetRPDv32_sR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// CHECK-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_ld_reset(v32int16 *&p, fifo_state_t &s) {
  return fifo_ld_reset(p, s);
}

// CHECK-LABEL: @_Z17test_fifo_ld_fillRPDv32_sR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_ld_fill(v32int16 *&p, fifo_state_t &s) {
  return fifo_ld_fill(p, s);
}

// CHECK-LABEL: @_Z16test_fifo_ld_popRPDv32_sR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 3
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP8:%.*]] = bitcast <64 x i8> [[TMP4]] to <32 x i16>
// CHECK-NEXT:    ret <32 x i16> [[TMP8]]
//
v32int16 test_fifo_ld_pop(v32int16 *&p, fifo_state_t &s) {
  return fifo_ld_pop(p, s);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_1d_byteRPDv32_sR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.1d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 3
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP9:%.*]] = bitcast <64 x i8> [[TMP5]] to <32 x i16>
// CHECK-NEXT:    ret <32 x i16> [[TMP9]]
//
v32int16 test_fifo_ld_pop_1d_byte(v32int16 *&p, fifo_state_t &s, int off) {
  return fifo_ld_pop_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_2d_byteRPDv32_sR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.ld.pop.2d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 4
// CHECK-NEXT:    [[TMP14:%.*]] = zext i20 [[TMP13]] to i32
// CHECK-NEXT:    store i32 [[TMP14]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP12]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP15:%.*]] = bitcast <64 x i8> [[TMP9]] to <32 x i16>
// CHECK-NEXT:    ret <32 x i16> [[TMP15]]
//
v32int16 test_fifo_ld_pop_2d_byte(v32int16 *&p, fifo_state_t &s, int off,
                                  int size1, addr_t &count1, int inc1) {
  return fifo_ld_pop_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_3d_byteRPDv32_sR12fifo_state_tiiRiiiS4_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.ld.pop.3d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 5
// CHECK-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// CHECK-NEXT:    store i32 [[TMP18]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP20]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP16]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP14]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP21:%.*]] = bitcast <64 x i8> [[TMP13]] to <32 x i16>
// CHECK-NEXT:    ret <32 x i16> [[TMP21]]
//
v32int16 test_fifo_ld_pop_3d_byte(v32int16 *&p, fifo_state_t &s, int off,
                                  int size1, addr_t &count1, int inc1,
                                  int size2, addr_t &count2, int inc2) {
  return fifo_ld_pop_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}

// CHECK-LABEL: @_Z18test_fifo_ld_resetRPDv32_tR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// CHECK-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_ld_reset(v32uint16 *&p, fifo_state_t &s) {
  return fifo_ld_reset(p, s);
}

// CHECK-LABEL: @_Z17test_fifo_ld_fillRPDv32_tR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_ld_fill(v32uint16 *&p, fifo_state_t &s) {
  return fifo_ld_fill(p, s);
}

// CHECK-LABEL: @_Z16test_fifo_ld_popRPDv32_tR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 3
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP8:%.*]] = bitcast <64 x i8> [[TMP4]] to <32 x i16>
// CHECK-NEXT:    ret <32 x i16> [[TMP8]]
//
v32uint16 test_fifo_ld_pop(v32uint16 *&p, fifo_state_t &s) {
  return fifo_ld_pop(p, s);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_1d_byteRPDv32_tR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.1d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 3
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP9:%.*]] = bitcast <64 x i8> [[TMP5]] to <32 x i16>
// CHECK-NEXT:    ret <32 x i16> [[TMP9]]
//
v32uint16 test_fifo_ld_pop_1d_byte(v32uint16 *&p, fifo_state_t &s, int off) {
  return fifo_ld_pop_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_2d_byteRPDv32_tR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.ld.pop.2d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 4
// CHECK-NEXT:    [[TMP14:%.*]] = zext i20 [[TMP13]] to i32
// CHECK-NEXT:    store i32 [[TMP14]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP12]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP15:%.*]] = bitcast <64 x i8> [[TMP9]] to <32 x i16>
// CHECK-NEXT:    ret <32 x i16> [[TMP15]]
//
v32uint16 test_fifo_ld_pop_2d_byte(v32uint16 *&p, fifo_state_t &s, int off,
                                   int size1, addr_t &count1, int inc1) {
  return fifo_ld_pop_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_3d_byteRPDv32_tR12fifo_state_tiiRiiiS4_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.ld.pop.3d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 5
// CHECK-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// CHECK-NEXT:    store i32 [[TMP18]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP20]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP16]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP14]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP21:%.*]] = bitcast <64 x i8> [[TMP13]] to <32 x i16>
// CHECK-NEXT:    ret <32 x i16> [[TMP21]]
//
v32uint16 test_fifo_ld_pop_3d_byte(v32uint16 *&p, fifo_state_t &s, int off,
                                   int size1, addr_t &count1, int inc1,
                                   int size2, addr_t &count2, int inc2) {
  return fifo_ld_pop_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}

// CHECK-LABEL: @_Z18test_fifo_ld_resetRPDv16_iR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// CHECK-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_ld_reset(v16int32 *&p, fifo_state_t &s) {
  return fifo_ld_reset(p, s);
}

// CHECK-LABEL: @_Z17test_fifo_ld_fillRPDv16_iR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_ld_fill(v16int32 *&p, fifo_state_t &s) {
  return fifo_ld_fill(p, s);
}

// CHECK-LABEL: @_Z16test_fifo_ld_popRPDv16_iR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 3
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP8:%.*]] = bitcast <64 x i8> [[TMP4]] to <16 x i32>
// CHECK-NEXT:    ret <16 x i32> [[TMP8]]
//
v16int32 test_fifo_ld_pop(v16int32 *&p, fifo_state_t &s) {
  return fifo_ld_pop(p, s);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_1d_byteRPDv16_iR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.1d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 3
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP9:%.*]] = bitcast <64 x i8> [[TMP5]] to <16 x i32>
// CHECK-NEXT:    ret <16 x i32> [[TMP9]]
//
v16int32 test_fifo_ld_pop_1d_byte(v16int32 *&p, fifo_state_t &s, int off) {
  return fifo_ld_pop_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_2d_byteRPDv16_iR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.ld.pop.2d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 4
// CHECK-NEXT:    [[TMP14:%.*]] = zext i20 [[TMP13]] to i32
// CHECK-NEXT:    store i32 [[TMP14]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP12]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP15:%.*]] = bitcast <64 x i8> [[TMP9]] to <16 x i32>
// CHECK-NEXT:    ret <16 x i32> [[TMP15]]
//
v16int32 test_fifo_ld_pop_2d_byte(v16int32 *&p, fifo_state_t &s, int off,
                                  int size1, addr_t &count1, int inc1) {
  return fifo_ld_pop_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_3d_byteRPDv16_iR12fifo_state_tiiRiiiS4_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.ld.pop.3d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 5
// CHECK-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// CHECK-NEXT:    store i32 [[TMP18]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP20]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP16]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP14]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP21:%.*]] = bitcast <64 x i8> [[TMP13]] to <16 x i32>
// CHECK-NEXT:    ret <16 x i32> [[TMP21]]
//
v16int32 test_fifo_ld_pop_3d_byte(v16int32 *&p, fifo_state_t &s, int off,
                                  int size1, addr_t &count1, int inc1,
                                  int size2, addr_t &count2, int inc2) {
  return fifo_ld_pop_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}


// CHECK-LABEL: @_Z18test_fifo_ld_resetRPDv16_jR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// CHECK-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_ld_reset(v16uint32 *&p, fifo_state_t &s) {
  return fifo_ld_reset(p, s);
}

// CHECK-LABEL: @_Z17test_fifo_ld_fillRPDv16_jR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_ld_fill(v16uint32 *&p, fifo_state_t &s) {
  return fifo_ld_fill(p, s);
}

// CHECK-LABEL: @_Z16test_fifo_ld_popRPDv16_jR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 3
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP8:%.*]] = bitcast <64 x i8> [[TMP4]] to <16 x i32>
// CHECK-NEXT:    ret <16 x i32> [[TMP8]]
//
v16uint32 test_fifo_ld_pop(v16uint32 *&p, fifo_state_t &s) {
  return fifo_ld_pop(p, s);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_1d_byteRPDv16_jR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.1d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 3
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP9:%.*]] = bitcast <64 x i8> [[TMP5]] to <16 x i32>
// CHECK-NEXT:    ret <16 x i32> [[TMP9]]
//
v16uint32 test_fifo_ld_pop_1d_byte(v16uint32 *&p, fifo_state_t &s, int off) {
  return fifo_ld_pop_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_2d_byteRPDv16_jR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.ld.pop.2d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 4
// CHECK-NEXT:    [[TMP14:%.*]] = zext i20 [[TMP13]] to i32
// CHECK-NEXT:    store i32 [[TMP14]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP12]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP15:%.*]] = bitcast <64 x i8> [[TMP9]] to <16 x i32>
// CHECK-NEXT:    ret <16 x i32> [[TMP15]]
//
v16uint32 test_fifo_ld_pop_2d_byte(v16uint32 *&p, fifo_state_t &s, int off,
                                   int size1, addr_t &count1, int inc1) {
  return fifo_ld_pop_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_3d_byteRPDv16_jR12fifo_state_tiiRiiiS4_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.ld.pop.3d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 5
// CHECK-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// CHECK-NEXT:    store i32 [[TMP18]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP20]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP16]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP14]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP21:%.*]] = bitcast <64 x i8> [[TMP13]] to <16 x i32>
// CHECK-NEXT:    ret <16 x i32> [[TMP21]]
//
v16uint32 test_fifo_ld_pop_3d_byte(v16uint32 *&p, fifo_state_t &s, int off,
                                   int size1, addr_t &count1, int inc1,
                                   int size2, addr_t &count2, int inc2) {
  return fifo_ld_pop_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}


// CHECK-LABEL: @_Z18test_fifo_ld_resetRPDv32_8bfloat16R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// CHECK-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_ld_reset(v32bfloat16 *&p, fifo_state_t &s) {
  return fifo_ld_reset(p, s);
}

// CHECK-LABEL: @_Z17test_fifo_ld_fillRPDv32_8bfloat16R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_ld_fill(v32bfloat16 *&p, fifo_state_t &s) {
  return fifo_ld_fill(p, s);
}

// CHECK-LABEL: @_Z16test_fifo_ld_popRPDv32_8bfloat16R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 3
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP8:%.*]] = bitcast <64 x i8> [[TMP4]] to <32 x bfloat>
// CHECK-NEXT:    ret <32 x bfloat> [[TMP8]]
//
v32bfloat16 test_fifo_ld_pop(v32bfloat16 *&p, fifo_state_t &s) {
  return fifo_ld_pop(p, s);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_1d_byteRPDv32_8bfloat16R12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.1d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 3
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP9:%.*]] = bitcast <64 x i8> [[TMP5]] to <32 x bfloat>
// CHECK-NEXT:    ret <32 x bfloat> [[TMP9]]
//
v32bfloat16 test_fifo_ld_pop_1d_byte(v32bfloat16 *&p, fifo_state_t &s,
                                     int off) {
  return fifo_ld_pop_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_2d_byteRPDv32_8bfloat16R12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.ld.pop.2d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 4
// CHECK-NEXT:    [[TMP14:%.*]] = zext i20 [[TMP13]] to i32
// CHECK-NEXT:    store i32 [[TMP14]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP12]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP15:%.*]] = bitcast <64 x i8> [[TMP9]] to <32 x bfloat>
// CHECK-NEXT:    ret <32 x bfloat> [[TMP15]]
//
v32bfloat16 test_fifo_ld_pop_2d_byte(v32bfloat16 *&p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  return fifo_ld_pop_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_3d_byteRPDv32_8bfloat16R12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.ld.pop.3d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 5
// CHECK-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// CHECK-NEXT:    store i32 [[TMP18]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP20]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP16]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP14]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP21:%.*]] = bitcast <64 x i8> [[TMP13]] to <32 x bfloat>
// CHECK-NEXT:    ret <32 x bfloat> [[TMP21]]
//
v32bfloat16 test_fifo_ld_pop_3d_byte(v32bfloat16 *&p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  return fifo_ld_pop_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}


// CHECK-LABEL: @_Z18test_fifo_ld_resetRPDv16_fR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// CHECK-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_ld_reset(v16float *&p, fifo_state_t &s) {
  return fifo_ld_reset(p, s);
}

// CHECK-LABEL: @_Z17test_fifo_ld_fillRPDv16_fR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_ld_fill(v16float *&p, fifo_state_t &s) {
  return fifo_ld_fill(p, s);
}

// CHECK-LABEL: @_Z16test_fifo_ld_popRPDv16_fR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP3]], 3
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP8:%.*]] = bitcast <64 x i8> [[TMP4]] to <16 x float>
// CHECK-NEXT:    ret <16 x float> [[TMP8]]
//
v16float test_fifo_ld_pop(v16float *&p, fifo_state_t &s) {
  return fifo_ld_pop(p, s);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_1d_byteRPDv16_fR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.1d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } [[TMP4]], 3
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP9:%.*]] = bitcast <64 x i8> [[TMP5]] to <16 x float>
// CHECK-NEXT:    ret <16 x float> [[TMP9]]
//
v16float test_fifo_ld_pop_1d_byte(v16float *&p, fifo_state_t &s, int off) {
  return fifo_ld_pop_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_2d_byteRPDv16_fR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.ld.pop.2d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } [[TMP8]], 4
// CHECK-NEXT:    [[TMP14:%.*]] = zext i20 [[TMP13]] to i32
// CHECK-NEXT:    store i32 [[TMP14]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP12]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP15:%.*]] = bitcast <64 x i8> [[TMP9]] to <16 x float>
// CHECK-NEXT:    ret <16 x float> [[TMP15]]
//
v16float test_fifo_ld_pop_2d_byte(v16float *&p, fifo_state_t &s, int off,
                                  int size1, addr_t &count1, int inc1) {
  return fifo_ld_pop_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_3d_byteRPDv16_fR12fifo_state_tiiRiiiS4_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.ld.pop.3d.unaligned.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// CHECK-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 5
// CHECK-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// CHECK-NEXT:    store i32 [[TMP18]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP20]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP16]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP14]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP21:%.*]] = bitcast <64 x i8> [[TMP13]] to <16 x float>
// CHECK-NEXT:    ret <16 x float> [[TMP21]]
//
v16float test_fifo_ld_pop_3d_byte(v16float *&p, fifo_state_t &s, int off,
                                  int size1, addr_t &count1, int inc1,
                                  int size2, addr_t &count2, int inc2) {
  return fifo_ld_pop_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}


// CHECK-LABEL: @_Z18test_fifo_ld_resetRP22v64bfp16ebs8_unalignedR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// CHECK-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_ld_reset(v64bfp16ebs8_unaligned *&p, fifo_state_t &s) {
  return fifo_ld_reset(p, s);
}

// CHECK-LABEL: @_Z17test_fifo_ld_fillRP22v64bfp16ebs8_unalignedR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_ld_fill(v64bfp16ebs8_unaligned *&p, fifo_state_t &s) {
  return fifo_ld_fill(p, s);
}

// CHECK-LABEL: @_Z16test_fifo_ld_popRP22v64bfp16ebs8_unalignedR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.bfp16.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 0
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 1
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 2
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 3
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 4
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS8:%.*]] poison, <64 x i8> [[TMP7]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS8]] [[DOTFCA_0_INSERT_I]], <8 x i8> [[TMP8]], 1
// CHECK-NEXT:    ret [[STRUCT_V64BFP16EBS8]] [[DOTFCA_1_INSERT_I]]
//
v64bfp16ebs8 test_fifo_ld_pop(v64bfp16ebs8_unaligned *&p, fifo_state_t &s) {
  return fifo_ld_pop(p, s);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_1d_byteRP22v64bfp16ebs8_unalignedR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.1d.bfp16.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP4]], 0
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP4]], 1
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP4]], 2
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP4]], 3
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP4]], 4
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS8:%.*]] poison, <64 x i8> [[TMP8]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS8]] [[DOTFCA_0_INSERT_I]], <8 x i8> [[TMP9]], 1
// CHECK-NEXT:    ret [[STRUCT_V64BFP16EBS8]] [[DOTFCA_1_INSERT_I]]
//
v64bfp16ebs8 test_fifo_ld_pop_1d_byte(v64bfp16ebs8_unaligned *&p,
                                      fifo_state_t &s, int off) {
  return fifo_ld_pop_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_2d_byteRP22v64bfp16ebs8_unalignedR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.2d.bfp16.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } [[TMP8]], 0
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } [[TMP8]], 1
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } [[TMP8]], 2
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } [[TMP8]], 4
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } [[TMP8]], 5
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS8:%.*]] poison, <64 x i8> [[TMP14]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS8]] [[DOTFCA_0_INSERT_I]], <8 x i8> [[TMP15]], 1
// CHECK-NEXT:    ret [[STRUCT_V64BFP16EBS8]] [[DOTFCA_1_INSERT_I]]
//
v64bfp16ebs8 test_fifo_ld_pop_2d_byte(v64bfp16ebs8_unaligned *&p,
                                      fifo_state_t &s, int off, int size1,
                                      addr_t &count1, int inc1) {
  return fifo_ld_pop_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_3d_byteRP22v64bfp16ebs8_unalignedR12fifo_state_tiiRiiiS4_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.3d.bfp16.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } [[TMP12]], 0
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } [[TMP12]], 1
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } [[TMP12]], 2
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } [[TMP12]], 5
// CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } [[TMP12]], 6
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS8:%.*]] poison, <64 x i8> [[TMP20]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS8]] [[DOTFCA_0_INSERT_I]], <8 x i8> [[TMP21]], 1
// CHECK-NEXT:    ret [[STRUCT_V64BFP16EBS8]] [[DOTFCA_1_INSERT_I]]
//
v64bfp16ebs8 test_fifo_ld_pop_3d_byte(v64bfp16ebs8_unaligned *&p,
                                      fifo_state_t &s, int off, int size1,
                                      addr_t &count1, int inc1, int size2,
                                      addr_t &count2, int inc2) {
  return fifo_ld_pop_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}


// CHECK-LABEL: @_Z18test_fifo_ld_resetRP23v64bfp16ebs16_unalignedR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// CHECK-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_ld_reset(v64bfp16ebs16_unaligned *&p, fifo_state_t &s) {
  return fifo_ld_reset(p, s);
}

// CHECK-LABEL: @_Z17test_fifo_ld_fillRP23v64bfp16ebs16_unalignedR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_ld_fill(v64bfp16ebs16_unaligned *&p, fifo_state_t &s) {
  return fifo_ld_fill(p, s);
}

// CHECK-LABEL: @_Z16test_fifo_ld_popRP23v64bfp16ebs16_unalignedR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.544.bfp16.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 0
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 1
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 2
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 3
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 4
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS16:%.*]] poison, <64 x i8> [[TMP7]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS16]] [[DOTFCA_0_INSERT_I]], <8 x i8> [[TMP8]], 1
// CHECK-NEXT:    ret [[STRUCT_V64BFP16EBS16]] [[DOTFCA_1_INSERT_I]]
//
v64bfp16ebs16 test_fifo_ld_pop(v64bfp16ebs16_unaligned *&p, fifo_state_t &s) {
  return fifo_ld_pop(p, s);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_1d_byteRP23v64bfp16ebs16_unalignedR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.544.1d.bfp16.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP4]], 0
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP4]], 1
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP4]], 2
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP4]], 3
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP4]], 4
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS16:%.*]] poison, <64 x i8> [[TMP8]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS16]] [[DOTFCA_0_INSERT_I]], <8 x i8> [[TMP9]], 1
// CHECK-NEXT:    ret [[STRUCT_V64BFP16EBS16]] [[DOTFCA_1_INSERT_I]]
//
v64bfp16ebs16 test_fifo_ld_pop_1d_byte(v64bfp16ebs16_unaligned *&p,
                                       fifo_state_t &s, int off) {
  return fifo_ld_pop_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_2d_byteRP23v64bfp16ebs16_unalignedR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.544.2d.bfp16.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } [[TMP8]], 0
// CHECK-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } [[TMP8]], 1
// CHECK-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } [[TMP8]], 2
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } [[TMP8]], 3
// CHECK-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } [[TMP8]], 4
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } [[TMP8]], 5
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS16:%.*]] poison, <64 x i8> [[TMP14]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS16]] [[DOTFCA_0_INSERT_I]], <8 x i8> [[TMP15]], 1
// CHECK-NEXT:    ret [[STRUCT_V64BFP16EBS16]] [[DOTFCA_1_INSERT_I]]
//
v64bfp16ebs16 test_fifo_ld_pop_2d_byte(v64bfp16ebs16_unaligned *&p,
                                       fifo_state_t &s, int off, int size1,
                                       addr_t &count1, int inc1) {
  return fifo_ld_pop_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_3d_byteRP23v64bfp16ebs16_unalignedR12fifo_state_tiiRiiiS4_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.544.3d.bfp16.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } [[TMP12]], 0
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } [[TMP12]], 1
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } [[TMP12]], 2
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } [[TMP12]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } [[TMP12]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } [[TMP12]], 5
// CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } [[TMP12]], 6
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS16:%.*]] poison, <64 x i8> [[TMP20]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS16]] [[DOTFCA_0_INSERT_I]], <8 x i8> [[TMP21]], 1
// CHECK-NEXT:    ret [[STRUCT_V64BFP16EBS16]] [[DOTFCA_1_INSERT_I]]
//
v64bfp16ebs16 test_fifo_ld_pop_3d_byte(v64bfp16ebs16_unaligned *&p,
                                       fifo_state_t &s, int off, int size1,
                                       addr_t &count1, int inc1, int size2,
                                       addr_t &count2, int inc2) {
  return fifo_ld_pop_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}

// CHECK-LABEL: @_Z18test_fifo_ld_resetPU3AS6Dv32_sR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP0:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP1:%.*]] = tail call { ptr addrspace(6), <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p6.p6(ptr addrspace(6) [[P:%.*]], <32 x i32> [[TMP0]], i32 0)
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32 } [[TMP1]], 1
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32 } [[TMP1]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP2]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP3]], ptr [[POS_I]], align 64
// CHECK-NEXT:    ret void
//
void test_fifo_ld_reset(v32int16 __aie_dm_resource_b *p, fifo_state_t &s) {
  return fifo_ld_reset(p, s);
}

// CHECK-LABEL: @_Z17test_fifo_ld_fillPU3AS6Dv32_sR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { ptr addrspace(6), <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p6.p6(ptr addrspace(6) [[P:%.*]], <32 x i32> [[TMP0]], i32 [[TMP1]])
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32 } [[TMP2]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32 } [[TMP2]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP3]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP4]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    ret void
//
void test_fifo_ld_fill(v32int16 __aie_dm_resource_b *p, fifo_state_t &s) {
  return fifo_ld_fill(p, s);
}

// CHECK-LABEL: @_Z16test_fifo_ld_popPU3AS6Dv32_sR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { <64 x i8>, ptr addrspace(6), <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.unaligned.p6.p6(ptr addrspace(6) [[P:%.*]], <32 x i32> [[TMP0]], i32 [[TMP1]])
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32 } [[TMP2]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32 } [[TMP2]], 2
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32 } [[TMP2]], 3
// CHECK-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP5]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    [[TMP6:%.*]] = bitcast <64 x i8> [[TMP3]] to <32 x i16>
// CHECK-NEXT:    ret <32 x i16> [[TMP6]]
//
v32int16 test_fifo_ld_pop(v32int16 __aie_dm_resource_b *p, fifo_state_t &s) {
  return fifo_ld_pop(p, s);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_1d_bytePU3AS6Dv32_sR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP2:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr addrspace(6), <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.1d.unaligned.p6.p6(ptr addrspace(6) [[P:%.*]], <32 x i32> [[TMP0]], i32 [[TMP1]], i20 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32 } [[TMP3]], 3
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <64 x i8> [[TMP4]] to <32 x i16>
// CHECK-NEXT:    ret <32 x i16> [[TMP7]]
//
v32int16 test_fifo_ld_pop_1d_byte(v32int16 __aie_dm_resource_b *p, fifo_state_t &s, int off) {
  return fifo_ld_pop_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_2d_bytePU3AS6Dv32_sR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP2:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP5:%.*]] = trunc i32 [[TMP4]] to i20
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = tail call { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, i20 } @llvm.aie2p.fifo.ld.pop.2d.unaligned.p6.p6(ptr addrspace(6) [[P:%.*]], <32 x i32> [[TMP0]], i32 [[TMP1]], i20 [[TMP2]], i20 [[TMP3]], i20 [[TMP5]], i20 [[TMP6]])
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, i20 } [[TMP7]], 0
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, i20 } [[TMP7]], 2
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, i20 } [[TMP7]], 3
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, i20 } [[TMP7]], 4
// CHECK-NEXT:    [[TMP12:%.*]] = zext i20 [[TMP11]] to i32
// CHECK-NEXT:    store i32 [[TMP12]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP9]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP10]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    [[TMP13:%.*]] = bitcast <64 x i8> [[TMP8]] to <32 x i16>
// CHECK-NEXT:    ret <32 x i16> [[TMP13]]
//
v32int16 test_fifo_ld_pop_2d_byte(v32int16 __aie_dm_resource_b *p, fifo_state_t &s, int off,
                                  int size1, addr_t &count1, int inc1) {
  return fifo_ld_pop_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_3d_bytePU3AS6Dv32_sR12fifo_state_tiiRiiiS4_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP2:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP5:%.*]] = trunc i32 [[TMP4]] to i20
// CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP9:%.*]] = trunc i32 [[TMP8]] to i20
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = tail call { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.ld.pop.3d.unaligned.p6.p6(ptr addrspace(6) [[P:%.*]], <32 x i32> [[TMP0]], i32 [[TMP1]], i20 [[TMP2]], i20 [[TMP3]], i20 [[TMP5]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP9]], i20 [[TMP10]])
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, i20, i20 } [[TMP11]], 0
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, i20, i20 } [[TMP11]], 2
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, i20, i20 } [[TMP11]], 3
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, i20, i20 } [[TMP11]], 4
// CHECK-NEXT:    [[TMP16:%.*]] = zext i20 [[TMP15]] to i32
// CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr addrspace(6), <32 x i32>, i32, i20, i20 } [[TMP11]], 5
// CHECK-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// CHECK-NEXT:    store i32 [[TMP16]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP18]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP13]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP14]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    [[TMP19:%.*]] = bitcast <64 x i8> [[TMP12]] to <32 x i16>
// CHECK-NEXT:    ret <32 x i16> [[TMP19]]
//
v32int16 test_fifo_ld_pop_3d_byte(v32int16 __aie_dm_resource_b *p, fifo_state_t &s, int off,
                                  int size1, addr_t &count1, int inc1,
                                  int size2, addr_t &count2, int inc2) {
  return fifo_ld_pop_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}


// CHECK-LABEL: @_Z18test_fifo_ld_fillxRP22v64bfp16ebs8_unalignedR12fifo_state_tii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// CHECK-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP:%.*]], 6
// CHECK-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK:%.*]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.fillx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// CHECK-NEXT:    store <16 x i32> [[TMP8]], ptr [[EXTRA3_I]], align 64
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_ld_fillx(v64bfp16ebs8_unaligned *&p, fifo_state_t &s, int step, int mask) {
  return fifo_ld_fillx(p, s, step, mask);
}

// CHECK-LABEL: @_Z18test_fifo_ld_fillxRP22v64bfp16ebs8_unalignedR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.fillx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// CHECK-NEXT:    store <16 x i32> [[TMP8]], ptr [[EXTRA3_I_I]], align 64
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_ld_fillx(v64bfp16ebs8_unaligned *&p, fifo_state_t &s) {
  return fifo_ld_fillx(p, s);
}

// CHECK-LABEL: @_Z18test_fifo_ld_fillxRP23v64bfp16ebs16_unalignedR12fifo_state_tii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// CHECK-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP:%.*]], 6
// CHECK-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK:%.*]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.fillx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// CHECK-NEXT:    store <16 x i32> [[TMP8]], ptr [[EXTRA3_I]], align 64
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_ld_fillx(v64bfp16ebs16_unaligned *&p, fifo_state_t &s, int step, int mask) {
  return fifo_ld_fillx(p, s, step, mask);
}

// CHECK-LABEL: @_Z18test_fifo_ld_fillxRP23v64bfp16ebs16_unalignedR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.fillx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// CHECK-NEXT:    store <16 x i32> [[TMP8]], ptr [[EXTRA3_I_I]], align 64
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_ld_fillx(v64bfp16ebs16_unaligned *&p, fifo_state_t &s) {
  return fifo_ld_fillx(p, s);
}


// CHECK-LABEL: @_Z17test_fifo_ld_popxRPDv64_DB8_R12fifo_state_tii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// CHECK-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP:%.*]], 6
// CHECK-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK:%.*]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// CHECK-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I]], align 64
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// CHECK-NEXT:    ret <64 x i8> [[TMP5]]
//
v128int4 test_fifo_ld_popx(v128int4 *&p, fifo_state_t &s, int step, int mask) {
  return fifo_ld_popx(p, s, step, mask);
}

// CHECK-LABEL: @_Z17test_fifo_ld_popxRPDv64_DB8_R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// CHECK-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I_I]], align 64
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// CHECK-NEXT:    ret <64 x i8> [[TMP5]]
//
v128int4 test_fifo_ld_popx(v128int4 *&p, fifo_state_t &s) {
  return fifo_ld_popx(p, s);
}

// CHECK-LABEL: @_Z17test_fifo_ld_popxRPDv64_DU8_R12fifo_state_tii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// CHECK-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP:%.*]], 6
// CHECK-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK:%.*]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// CHECK-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I]], align 64
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// CHECK-NEXT:    ret <64 x i8> [[TMP5]]
//
v128uint4 test_fifo_ld_popx(v128uint4 *&p, fifo_state_t &s, int step, int mask) {
  return fifo_ld_popx(p, s, step, mask);
}

// CHECK-LABEL: @_Z17test_fifo_ld_popxRPDv64_DU8_R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// CHECK-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I_I]], align 64
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// CHECK-NEXT:    ret <64 x i8> [[TMP5]]
//
v128uint4 test_fifo_ld_popx(v128uint4 *&p, fifo_state_t &s) {
  return fifo_ld_popx(p, s);
}

// CHECK-LABEL: @_Z17test_fifo_ld_popxRPDv64_aR12fifo_state_tii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// CHECK-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP:%.*]], 6
// CHECK-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK:%.*]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// CHECK-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I]], align 64
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// CHECK-NEXT:    ret <64 x i8> [[TMP5]]
//
v64int8 test_fifo_ld_popx(v64int8 *&p, fifo_state_t &s, int step, int mask) {
  return fifo_ld_popx(p, s, step, mask);
}

// CHECK-LABEL: @_Z17test_fifo_ld_popxRPDv64_aR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// CHECK-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I_I]], align 64
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// CHECK-NEXT:    ret <64 x i8> [[TMP5]]
//
v64int8 test_fifo_ld_popx(v64int8 *&p, fifo_state_t &s) {
  return fifo_ld_popx(p, s);
}

// CHECK-LABEL: @_Z17test_fifo_ld_popxRPDv64_hR12fifo_state_tii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// CHECK-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP:%.*]], 6
// CHECK-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK:%.*]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// CHECK-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I]], align 64
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// CHECK-NEXT:    ret <64 x i8> [[TMP5]]
//
v64uint8 test_fifo_ld_popx(v64uint8 *&p, fifo_state_t &s, int step, int mask) {
  return fifo_ld_popx(p, s, step, mask);
}

// CHECK-LABEL: @_Z17test_fifo_ld_popxRPDv64_hR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// CHECK-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I_I]], align 64
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// CHECK-NEXT:    ret <64 x i8> [[TMP5]]
//
v64uint8 test_fifo_ld_popx(v64uint8 *&p, fifo_state_t &s) {
  return fifo_ld_popx(p, s);
}

// CHECK-LABEL: @_Z17test_fifo_ld_popxRPDv32_sR12fifo_state_tii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// CHECK-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP:%.*]], 6
// CHECK-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK:%.*]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// CHECK-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I]], align 64
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <32 x i16>
// CHECK-NEXT:    ret <32 x i16> [[TMP10]]
//
v32int16 test_fifo_ld_popx(v32int16 *&p, fifo_state_t &s, int step, int mask) {
  return fifo_ld_popx(p, s, step, mask);
}

// CHECK-LABEL: @_Z17test_fifo_ld_popxRPDv32_sR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// CHECK-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I_I]], align 64
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <32 x i16>
// CHECK-NEXT:    ret <32 x i16> [[TMP10]]
//
v32int16 test_fifo_ld_popx(v32int16 *&p, fifo_state_t &s) {
  return fifo_ld_popx(p, s);
}

// CHECK-LABEL: @_Z17test_fifo_ld_popxRPDv32_tR12fifo_state_tii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// CHECK-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP:%.*]], 6
// CHECK-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK:%.*]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// CHECK-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I]], align 64
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <32 x i16>
// CHECK-NEXT:    ret <32 x i16> [[TMP10]]
//
v32uint16 test_fifo_ld_popx(v32uint16 *&p, fifo_state_t &s, int step, int mask) {
  return fifo_ld_popx(p, s, step, mask);
}

// CHECK-LABEL: @_Z17test_fifo_ld_popxRPDv32_tR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// CHECK-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I_I]], align 64
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <32 x i16>
// CHECK-NEXT:    ret <32 x i16> [[TMP10]]
//
v32uint16 test_fifo_ld_popx(v32uint16 *&p, fifo_state_t &s) {
  return fifo_ld_popx(p, s);
}

// CHECK-LABEL: @_Z17test_fifo_ld_popxRPDv16_iR12fifo_state_tii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// CHECK-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP:%.*]], 6
// CHECK-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK:%.*]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// CHECK-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I]], align 64
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <16 x i32>
// CHECK-NEXT:    ret <16 x i32> [[TMP10]]
//
v16int32 test_fifo_ld_popx(v16int32 *&p, fifo_state_t &s, int step, int mask) {
  return fifo_ld_popx(p, s, step, mask);
}

// CHECK-LABEL: @_Z17test_fifo_ld_popxRPDv16_iR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// CHECK-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I_I]], align 64
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <16 x i32>
// CHECK-NEXT:    ret <16 x i32> [[TMP10]]
//
v16int32 test_fifo_ld_popx(v16int32 *&p, fifo_state_t &s) {
  return fifo_ld_popx(p, s);
}

// CHECK-LABEL: @_Z17test_fifo_ld_popxRPDv16_jR12fifo_state_tii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// CHECK-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP:%.*]], 6
// CHECK-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK:%.*]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// CHECK-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I]], align 64
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <16 x i32>
// CHECK-NEXT:    ret <16 x i32> [[TMP10]]
//
v16uint32 test_fifo_ld_popx(v16uint32 *&p, fifo_state_t &s, int step, int mask) {
  return fifo_ld_popx(p, s, step, mask);
}

// CHECK-LABEL: @_Z17test_fifo_ld_popxRPDv16_jR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// CHECK-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I_I]], align 64
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <16 x i32>
// CHECK-NEXT:    ret <16 x i32> [[TMP10]]
//
v16uint32 test_fifo_ld_popx(v16uint32 *&p, fifo_state_t &s) {
  return fifo_ld_popx(p, s);
}

// CHECK-LABEL: @_Z17test_fifo_ld_popxRPDv32_8bfloat16R12fifo_state_tii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// CHECK-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP:%.*]], 6
// CHECK-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK:%.*]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// CHECK-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I]], align 64
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <32 x bfloat>
// CHECK-NEXT:    ret <32 x bfloat> [[TMP10]]
//
v32bfloat16 test_fifo_ld_popx(v32bfloat16 *&p, fifo_state_t &s, int step, int mask) {
  return fifo_ld_popx(p, s, step, mask);
}

// CHECK-LABEL: @_Z17test_fifo_ld_popxRPDv32_8bfloat16R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// CHECK-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I_I]], align 64
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <32 x bfloat>
// CHECK-NEXT:    ret <32 x bfloat> [[TMP10]]
//
v32bfloat16 test_fifo_ld_popx(v32bfloat16 *&p, fifo_state_t &s) {
  return fifo_ld_popx(p, s);
}

// CHECK-LABEL: @_Z17test_fifo_ld_popxRPDv16_fR12fifo_state_tii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// CHECK-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP:%.*]], 6
// CHECK-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK:%.*]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// CHECK-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I]], align 64
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <16 x float>
// CHECK-NEXT:    ret <16 x float> [[TMP10]]
//
v16float test_fifo_ld_popx(v16float *&p, fifo_state_t &s, int step, int mask) {
  return fifo_ld_popx(p, s, step, mask);
}

// CHECK-LABEL: @_Z17test_fifo_ld_popxRPDv16_fR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// CHECK-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I_I]], align 64
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <16 x float>
// CHECK-NEXT:    ret <16 x float> [[TMP10]]
//
v16float test_fifo_ld_popx(v16float *&p, fifo_state_t &s) {
  return fifo_ld_popx(p, s);
}


// CHECK-LABEL: @_Z18test_fifo_ld_resetRrP23v128bfp16ebs8_unalignedR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    store i32 0, ptr [[POS_I_I]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP5]], ptr [[POS_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_ld_reset(v128bfp16ebs8_unaligned *restrict &p, fifo_state_t &s) {
  fifo_ld_reset(p, s);
}

// CHECK-LABEL: @_Z17test_fifo_ld_fillRrP23v128bfp16ebs8_unalignedR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_ld_fill(v128bfp16ebs8_unaligned *restrict &p, fifo_state_t &s) {
  fifo_ld_fill(p, s);
}

// CHECK-LABEL: @_Z16test_fifo_ld_popRrP23v128bfp16ebs8_unalignedR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.bfp16.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 0
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 1
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 2
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 3
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 4
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I21_I:%.*]] = insertvalue [[STRUCT_V128BFP16EBS8:%.*]] poison, <64 x i8> [[TMP7]], 0
// CHECK-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP10:%.*]] = tail call { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.bfp16.p0.p0(ptr [[TMP9]], <32 x i32> [[TMP5]], i32 [[TMP6]])
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP10]], 0
// CHECK-NEXT:    store ptr [[TMP11]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP10]], 1
// CHECK-NEXT:    store <32 x i32> [[TMP12]], ptr [[S]], align 128
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP10]], 2
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP10]], 3
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP10]], 4
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I26_I:%.*]] = insertvalue [[STRUCT_V128BFP16EBS8]] [[DOTFCA_0_INSERT_I21_I]], <64 x i8> [[TMP14]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I27_I:%.*]] = insertvalue [[STRUCT_V128BFP16EBS8]] [[DOTFCA_1_INSERT_I26_I]], <8 x i8> [[TMP8]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I28_I:%.*]] = insertvalue [[STRUCT_V128BFP16EBS8]] [[DOTFCA_2_INSERT_I27_I]], <8 x i8> [[TMP15]], 3
// CHECK-NEXT:    ret [[STRUCT_V128BFP16EBS8]] [[DOTFCA_3_INSERT_I28_I]]
//
v128bfp16ebs8 test_fifo_ld_pop(v128bfp16ebs8_unaligned *restrict &p,
                               fifo_state_t &s) {
  return fifo_ld_pop(p, s);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_1d_byteRrP23v128bfp16ebs8_unalignedR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.bfp16.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 0
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 1
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 2
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 3
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 4
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I21_I:%.*]] = insertvalue [[STRUCT_V128BFP16EBS8:%.*]] poison, <64 x i8> [[TMP7]], 0
// CHECK-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = tail call { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.1d.bfp16.p0.p0(ptr [[TMP9]], <32 x i32> [[TMP5]], i32 [[TMP6]], i20 [[TMP10]])
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP11]], 0
// CHECK-NEXT:    store ptr [[TMP12]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP11]], 1
// CHECK-NEXT:    store <32 x i32> [[TMP13]], ptr [[S]], align 128
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP11]], 2
// CHECK-NEXT:    store i32 [[TMP14]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP11]], 3
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP11]], 4
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I26_I:%.*]] = insertvalue [[STRUCT_V128BFP16EBS8]] [[DOTFCA_0_INSERT_I21_I]], <64 x i8> [[TMP15]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I27_I:%.*]] = insertvalue [[STRUCT_V128BFP16EBS8]] [[DOTFCA_1_INSERT_I26_I]], <8 x i8> [[TMP8]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I28_I:%.*]] = insertvalue [[STRUCT_V128BFP16EBS8]] [[DOTFCA_2_INSERT_I27_I]], <8 x i8> [[TMP16]], 3
// CHECK-NEXT:    ret [[STRUCT_V128BFP16EBS8]] [[DOTFCA_3_INSERT_I28_I]]
//
v128bfp16ebs8 test_fifo_ld_pop_1d_byte(v128bfp16ebs8_unaligned *restrict &p,
                                       fifo_state_t &s, int off) {
  return fifo_ld_pop_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_2d_byteRrP23v128bfp16ebs8_unalignedR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.bfp16.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 0
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 1
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 2
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 3
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 4
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I21_I:%.*]] = insertvalue [[STRUCT_V128BFP16EBS8:%.*]] poison, <64 x i8> [[TMP7]], 0
// CHECK-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP13:%.*]] = trunc i32 [[TMP12]] to i20
// CHECK-NEXT:    [[TMP14:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP15:%.*]] = tail call { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.2d.bfp16.p0.p0(ptr [[TMP9]], <32 x i32> [[TMP5]], i32 [[TMP6]], i20 [[TMP10]], i20 [[TMP11]], i20 [[TMP13]], i20 [[TMP14]])
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } [[TMP15]], 0
// CHECK-NEXT:    store ptr [[TMP16]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } [[TMP15]], 1
// CHECK-NEXT:    store <32 x i32> [[TMP17]], ptr [[S]], align 128
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } [[TMP15]], 2
// CHECK-NEXT:    store i32 [[TMP18]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } [[TMP15]], 3
// CHECK-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// CHECK-NEXT:    store i32 [[TMP20]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } [[TMP15]], 4
// CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } [[TMP15]], 5
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I26_I:%.*]] = insertvalue [[STRUCT_V128BFP16EBS8]] [[DOTFCA_0_INSERT_I21_I]], <64 x i8> [[TMP21]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I27_I:%.*]] = insertvalue [[STRUCT_V128BFP16EBS8]] [[DOTFCA_1_INSERT_I26_I]], <8 x i8> [[TMP8]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I28_I:%.*]] = insertvalue [[STRUCT_V128BFP16EBS8]] [[DOTFCA_2_INSERT_I27_I]], <8 x i8> [[TMP22]], 3
// CHECK-NEXT:    ret [[STRUCT_V128BFP16EBS8]] [[DOTFCA_3_INSERT_I28_I]]
//
v128bfp16ebs8 test_fifo_ld_pop_2d_byte(v128bfp16ebs8_unaligned *restrict &p,
                                       fifo_state_t &s, int off, int size1,
                                       addr_t &count1, int inc1) {
  return fifo_ld_pop_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_3d_byteRrP23v128bfp16ebs8_unalignedR12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.bfp16.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 0
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 1
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 2
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 3
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 4
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I21_I:%.*]] = insertvalue [[STRUCT_V128BFP16EBS8:%.*]] poison, <64 x i8> [[TMP7]], 0
// CHECK-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP13:%.*]] = trunc i32 [[TMP12]] to i20
// CHECK-NEXT:    [[TMP14:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP15:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP16:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP17:%.*]] = trunc i32 [[TMP16]] to i20
// CHECK-NEXT:    [[TMP18:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP19:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.3d.bfp16.p0.p0(ptr [[TMP9]], <32 x i32> [[TMP5]], i32 [[TMP6]], i20 [[TMP10]], i20 [[TMP11]], i20 [[TMP13]], i20 [[TMP14]], i20 [[TMP15]], i20 [[TMP17]], i20 [[TMP18]])
// CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } [[TMP19]], 0
// CHECK-NEXT:    store ptr [[TMP20]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } [[TMP19]], 1
// CHECK-NEXT:    store <32 x i32> [[TMP21]], ptr [[S]], align 128
// CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } [[TMP19]], 2
// CHECK-NEXT:    store i32 [[TMP22]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    [[TMP23:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } [[TMP19]], 3
// CHECK-NEXT:    [[TMP24:%.*]] = zext i20 [[TMP23]] to i32
// CHECK-NEXT:    [[TMP25:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } [[TMP19]], 4
// CHECK-NEXT:    [[TMP26:%.*]] = zext i20 [[TMP25]] to i32
// CHECK-NEXT:    store i32 [[TMP24]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP26]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    [[TMP27:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } [[TMP19]], 5
// CHECK-NEXT:    [[TMP28:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } [[TMP19]], 6
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I26_I:%.*]] = insertvalue [[STRUCT_V128BFP16EBS8]] [[DOTFCA_0_INSERT_I21_I]], <64 x i8> [[TMP27]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I27_I:%.*]] = insertvalue [[STRUCT_V128BFP16EBS8]] [[DOTFCA_1_INSERT_I26_I]], <8 x i8> [[TMP8]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I28_I:%.*]] = insertvalue [[STRUCT_V128BFP16EBS8]] [[DOTFCA_2_INSERT_I27_I]], <8 x i8> [[TMP28]], 3
// CHECK-NEXT:    ret [[STRUCT_V128BFP16EBS8]] [[DOTFCA_3_INSERT_I28_I]]
//
v128bfp16ebs8 test_fifo_ld_pop_3d_byte(v128bfp16ebs8_unaligned *restrict &p,
                                       fifo_state_t &s, int off, int size1,
                                       addr_t &count1, int inc1, int size2,
                                       addr_t &count2, int inc2) {
  return fifo_ld_pop_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}

// CHECK-LABEL: @_Z18test_fifo_ld_resetRrP24v128bfp16ebs16_unalignedR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    store i32 0, ptr [[POS_I_I]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP5]], ptr [[POS_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP3]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_ld_reset(v128bfp16ebs16_unaligned *restrict &p,
                        fifo_state_t &s) {
  fifo_ld_reset(p, s);
}

// CHECK-LABEL: @_Z17test_fifo_ld_fillRrP24v128bfp16ebs16_unalignedR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_ld_fill(v128bfp16ebs16_unaligned *restrict &p, fifo_state_t &s) {
  fifo_ld_fill(p, s);
}

// CHECK-LABEL: @_Z16test_fifo_ld_popRrP24v128bfp16ebs16_unalignedR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.544.bfp16.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 0
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 1
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 2
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 3
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 4
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I21_I:%.*]] = insertvalue [[STRUCT_V128BFP16EBS16:%.*]] poison, <64 x i8> [[TMP7]], 0
// CHECK-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP10:%.*]] = tail call { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.544.bfp16.p0.p0(ptr [[TMP9]], <32 x i32> [[TMP5]], i32 [[TMP6]])
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP10]], 0
// CHECK-NEXT:    store ptr [[TMP11]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP10]], 1
// CHECK-NEXT:    store <32 x i32> [[TMP12]], ptr [[S]], align 128
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP10]], 2
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP10]], 3
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP10]], 4
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I26_I:%.*]] = insertvalue [[STRUCT_V128BFP16EBS16]] [[DOTFCA_0_INSERT_I21_I]], <64 x i8> [[TMP14]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I27_I:%.*]] = insertvalue [[STRUCT_V128BFP16EBS16]] [[DOTFCA_1_INSERT_I26_I]], <8 x i8> [[TMP8]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I28_I:%.*]] = insertvalue [[STRUCT_V128BFP16EBS16]] [[DOTFCA_2_INSERT_I27_I]], <8 x i8> [[TMP15]], 3
// CHECK-NEXT:    ret [[STRUCT_V128BFP16EBS16]] [[DOTFCA_3_INSERT_I28_I]]
//
v128bfp16ebs16 test_fifo_ld_pop(v128bfp16ebs16_unaligned *restrict &p,
                                fifo_state_t &s) {
  return fifo_ld_pop(p, s);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_1d_byteRrP24v128bfp16ebs16_unalignedR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.544.bfp16.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 0
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 1
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 2
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 3
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 4
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I21_I:%.*]] = insertvalue [[STRUCT_V128BFP16EBS16:%.*]] poison, <64 x i8> [[TMP7]], 0
// CHECK-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = tail call { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.544.1d.bfp16.p0.p0(ptr [[TMP9]], <32 x i32> [[TMP5]], i32 [[TMP6]], i20 [[TMP10]])
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP11]], 0
// CHECK-NEXT:    store ptr [[TMP12]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP11]], 1
// CHECK-NEXT:    store <32 x i32> [[TMP13]], ptr [[S]], align 128
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP11]], 2
// CHECK-NEXT:    store i32 [[TMP14]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP11]], 3
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP11]], 4
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I26_I:%.*]] = insertvalue [[STRUCT_V128BFP16EBS16]] [[DOTFCA_0_INSERT_I21_I]], <64 x i8> [[TMP15]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I27_I:%.*]] = insertvalue [[STRUCT_V128BFP16EBS16]] [[DOTFCA_1_INSERT_I26_I]], <8 x i8> [[TMP8]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I28_I:%.*]] = insertvalue [[STRUCT_V128BFP16EBS16]] [[DOTFCA_2_INSERT_I27_I]], <8 x i8> [[TMP16]], 3
// CHECK-NEXT:    ret [[STRUCT_V128BFP16EBS16]] [[DOTFCA_3_INSERT_I28_I]]
//
v128bfp16ebs16 test_fifo_ld_pop_1d_byte(v128bfp16ebs16_unaligned *restrict &p,
                                        fifo_state_t &s, int off) {
  return fifo_ld_pop_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_2d_byteRrP24v128bfp16ebs16_unalignedR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.544.bfp16.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 0
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 1
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 2
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 3
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 4
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I21_I:%.*]] = insertvalue [[STRUCT_V128BFP16EBS16:%.*]] poison, <64 x i8> [[TMP7]], 0
// CHECK-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP13:%.*]] = trunc i32 [[TMP12]] to i20
// CHECK-NEXT:    [[TMP14:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP15:%.*]] = tail call { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.544.2d.bfp16.p0.p0(ptr [[TMP9]], <32 x i32> [[TMP5]], i32 [[TMP6]], i20 [[TMP10]], i20 [[TMP11]], i20 [[TMP13]], i20 [[TMP14]])
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } [[TMP15]], 0
// CHECK-NEXT:    store ptr [[TMP16]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } [[TMP15]], 1
// CHECK-NEXT:    store <32 x i32> [[TMP17]], ptr [[S]], align 128
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } [[TMP15]], 2
// CHECK-NEXT:    store i32 [[TMP18]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } [[TMP15]], 3
// CHECK-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// CHECK-NEXT:    store i32 [[TMP20]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } [[TMP15]], 4
// CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } [[TMP15]], 5
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I26_I:%.*]] = insertvalue [[STRUCT_V128BFP16EBS16]] [[DOTFCA_0_INSERT_I21_I]], <64 x i8> [[TMP21]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I27_I:%.*]] = insertvalue [[STRUCT_V128BFP16EBS16]] [[DOTFCA_1_INSERT_I26_I]], <8 x i8> [[TMP8]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I28_I:%.*]] = insertvalue [[STRUCT_V128BFP16EBS16]] [[DOTFCA_2_INSERT_I27_I]], <8 x i8> [[TMP22]], 3
// CHECK-NEXT:    ret [[STRUCT_V128BFP16EBS16]] [[DOTFCA_3_INSERT_I28_I]]
//
v128bfp16ebs16 test_fifo_ld_pop_2d_byte(v128bfp16ebs16_unaligned *restrict &p,
                                        fifo_state_t &s, int off, int size1,
                                        addr_t &count1, int inc1) {
  return fifo_ld_pop_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z24test_fifo_ld_pop_3d_byteRrP24v128bfp16ebs16_unalignedR12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.544.bfp16.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 0
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 1
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 2
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 3
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } [[TMP3]], 4
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I21_I:%.*]] = insertvalue [[STRUCT_V128BFP16EBS16:%.*]] poison, <64 x i8> [[TMP7]], 0
// CHECK-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP12:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP13:%.*]] = trunc i32 [[TMP12]] to i20
// CHECK-NEXT:    [[TMP14:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP15:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP16:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP17:%.*]] = trunc i32 [[TMP16]] to i20
// CHECK-NEXT:    [[TMP18:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP19:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.544.3d.bfp16.p0.p0(ptr [[TMP9]], <32 x i32> [[TMP5]], i32 [[TMP6]], i20 [[TMP10]], i20 [[TMP11]], i20 [[TMP13]], i20 [[TMP14]], i20 [[TMP15]], i20 [[TMP17]], i20 [[TMP18]])
// CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } [[TMP19]], 0
// CHECK-NEXT:    store ptr [[TMP20]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } [[TMP19]], 1
// CHECK-NEXT:    store <32 x i32> [[TMP21]], ptr [[S]], align 128
// CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } [[TMP19]], 2
// CHECK-NEXT:    store i32 [[TMP22]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    [[TMP23:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } [[TMP19]], 3
// CHECK-NEXT:    [[TMP24:%.*]] = zext i20 [[TMP23]] to i32
// CHECK-NEXT:    [[TMP25:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } [[TMP19]], 4
// CHECK-NEXT:    [[TMP26:%.*]] = zext i20 [[TMP25]] to i32
// CHECK-NEXT:    store i32 [[TMP24]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP26]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    [[TMP27:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } [[TMP19]], 5
// CHECK-NEXT:    [[TMP28:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } [[TMP19]], 6
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I26_I:%.*]] = insertvalue [[STRUCT_V128BFP16EBS16]] [[DOTFCA_0_INSERT_I21_I]], <64 x i8> [[TMP27]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I27_I:%.*]] = insertvalue [[STRUCT_V128BFP16EBS16]] [[DOTFCA_1_INSERT_I26_I]], <8 x i8> [[TMP8]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I28_I:%.*]] = insertvalue [[STRUCT_V128BFP16EBS16]] [[DOTFCA_2_INSERT_I27_I]], <8 x i8> [[TMP28]], 3
// CHECK-NEXT:    ret [[STRUCT_V128BFP16EBS16]] [[DOTFCA_3_INSERT_I28_I]]
//
v128bfp16ebs16 test_fifo_ld_pop_3d_byte(v128bfp16ebs16_unaligned *restrict &p,
                                        fifo_state_t &s, int off, int size1,
                                        addr_t &count1, int inc1, int size2,
                                        addr_t &count2, int inc2) {
  return fifo_ld_pop_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}

// CHECK-LABEL: @_Z18test_fifo_st_resetRrP23v128bfp16ebs8_unaligned13v128bfp16ebs8R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8:%.*]] [[V_COERCE:%.*]], 2
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[V_COERCE]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.576.bfp16.p0.p0(ptr [[TMP2]], <64 x i8> [[TMP1]], <8 x i8> [[TMP0]], <32 x i32> [[TMP3]], i32 0)
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[V_COERCE]], 3
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[V_COERCE]], 1
// CHECK-NEXT:    [[TMP10:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr [[POS_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.576.bfp16.p0.p0(ptr [[TMP5]], <64 x i8> [[TMP9]], <8 x i8> [[TMP8]], <32 x i32> [[TMP10]], i32 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP12]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_reset(v128bfp16ebs8_unaligned *restrict &p, v128bfp16ebs8 v,
                        fifo_state_t &s) {
  fifo_st_reset(p, v, s);
}

// CHECK-LABEL: @_Z17test_fifo_st_pushRrP23v128bfp16ebs8_unaligned13v128bfp16ebs8R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8:%.*]] [[V_COERCE:%.*]], 2
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[V_COERCE]], 0
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP5:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.576.bfp16.p0.p0(ptr [[TMP2]], <64 x i8> [[TMP1]], <8 x i8> [[TMP0]], <32 x i32> [[TMP3]], i32 [[TMP4]])
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP5]], 0
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP5]], 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP5]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[V_COERCE]], 3
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue [[STRUCT_V128BFP16EBS8]] [[V_COERCE]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP12:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP13:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.576.bfp16.p0.p0(ptr [[TMP6]], <64 x i8> [[TMP10]], <8 x i8> [[TMP9]], <32 x i32> [[TMP11]], i32 [[TMP12]])
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP13]], 0
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP13]], 1
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP13]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP16]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP14]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_push(v128bfp16ebs8_unaligned *restrict &p, v128bfp16ebs8 v,
                       fifo_state_t &s) {
  fifo_st_push(p, v, s);
}

// CHECK-LABEL: @_Z18test_fifo_st_flushRrP23v128bfp16ebs8_unalignedR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP9:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP4]], <32 x i32> [[TMP7]], i32 [[TMP8]])
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP9]], 0
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP9]], 1
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP9]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP12]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush(v128bfp16ebs8_unaligned *restrict &p, fifo_state_t &s) {
  fifo_st_flush(p, s);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_1d_byteRrP23v128bfp16ebs8_unalignedR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP9:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP10:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP4]], <32 x i32> [[TMP7]], i32 [[TMP8]], i20 [[TMP9]])
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP10]], 0
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP10]], 1
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP10]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP12]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP11]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_1d_byte(v128bfp16ebs8_unaligned *restrict &p,
                                fifo_state_t &s, int off) {
  fifo_st_flush_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_2d_byteRrP23v128bfp16ebs8_unalignedR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP9:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP12:%.*]] = trunc i32 [[TMP11]] to i20
// CHECK-NEXT:    [[TMP13:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP14:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP4]], <32 x i32> [[TMP7]], i32 [[TMP8]], i20 [[TMP9]], i20 [[TMP10]], i20 [[TMP12]], i20 [[TMP13]])
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP14]], 0
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP14]], 1
// CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP14]], 2
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP14]], 3
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP16]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP15]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_2d_byte(v128bfp16ebs8_unaligned *restrict &p,
                                fifo_state_t &s, int off, int size1,
                                addr_t &count1, int inc1) {
  fifo_st_flush_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_3d_byteRrP23v128bfp16ebs8_unalignedR12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP9:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP12:%.*]] = trunc i32 [[TMP11]] to i20
// CHECK-NEXT:    [[TMP13:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP14:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP15:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP16:%.*]] = trunc i32 [[TMP15]] to i20
// CHECK-NEXT:    [[TMP17:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP18:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP4]], <32 x i32> [[TMP7]], i32 [[TMP8]], i20 [[TMP9]], i20 [[TMP10]], i20 [[TMP12]], i20 [[TMP13]], i20 [[TMP14]], i20 [[TMP16]], i20 [[TMP17]])
// CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP18]], 0
// CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP18]], 1
// CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP18]], 2
// CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP18]], 3
// CHECK-NEXT:    [[TMP23:%.*]] = zext i20 [[TMP22]] to i32
// CHECK-NEXT:    [[TMP24:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP18]], 4
// CHECK-NEXT:    [[TMP25:%.*]] = zext i20 [[TMP24]] to i32
// CHECK-NEXT:    store i32 [[TMP23]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP25]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP20]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP21]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP19]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_3d_byte(v128bfp16ebs8_unaligned *restrict &p,
                                fifo_state_t &s, int off, int size1,
                                addr_t &count1, int inc1, int size2,
                                addr_t &count2, int inc2) {
  fifo_st_flush_3d_byte(p, s, off, size1, count1, inc1, size2, count2, inc2);
}

// CHECK-LABEL: @_Z23test_fifo_st_flush_bareRrP23v128bfp16ebs8_unalignedR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP9:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP4]], <32 x i32> [[TMP7]], i32 [[TMP8]])
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP9]], 0
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP9]], 1
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP9]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP12]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare(v128bfp16ebs8_unaligned *restrict &p,
                             fifo_state_t &s) {
  fifo_st_flush_bare(p, s);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_1d_byteRrP23v128bfp16ebs8_unalignedR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP9:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP10:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP4]], <32 x i32> [[TMP7]], i32 [[TMP8]], i20 [[TMP9]])
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP10]], 0
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP10]], 1
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP10]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP12]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP11]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_1d_byte(v128bfp16ebs8_unaligned *restrict &p,
                                     fifo_state_t &s, int off) {
  fifo_st_flush_bare_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_2d_byteRrP23v128bfp16ebs8_unalignedR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP9:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP12:%.*]] = trunc i32 [[TMP11]] to i20
// CHECK-NEXT:    [[TMP13:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP14:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP4]], <32 x i32> [[TMP7]], i32 [[TMP8]], i20 [[TMP9]], i20 [[TMP10]], i20 [[TMP12]], i20 [[TMP13]])
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP14]], 0
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP14]], 1
// CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP14]], 2
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP14]], 3
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP16]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP15]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_2d_byte(v128bfp16ebs8_unaligned *restrict &p,
                                     fifo_state_t &s, int off, int size1,
                                     addr_t &count1, int inc1) {
  fifo_st_flush_bare_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_3d_byteRrP23v128bfp16ebs8_unalignedR12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP9:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP12:%.*]] = trunc i32 [[TMP11]] to i20
// CHECK-NEXT:    [[TMP13:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP14:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP15:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP16:%.*]] = trunc i32 [[TMP15]] to i20
// CHECK-NEXT:    [[TMP17:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP18:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP4]], <32 x i32> [[TMP7]], i32 [[TMP8]], i20 [[TMP9]], i20 [[TMP10]], i20 [[TMP12]], i20 [[TMP13]], i20 [[TMP14]], i20 [[TMP16]], i20 [[TMP17]])
// CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP18]], 0
// CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP18]], 1
// CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP18]], 2
// CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP18]], 3
// CHECK-NEXT:    [[TMP23:%.*]] = zext i20 [[TMP22]] to i32
// CHECK-NEXT:    [[TMP24:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP18]], 4
// CHECK-NEXT:    [[TMP25:%.*]] = zext i20 [[TMP24]] to i32
// CHECK-NEXT:    store i32 [[TMP23]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP25]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP20]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP21]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP19]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_3d_byte(v128bfp16ebs8_unaligned *restrict &p,
                                     fifo_state_t &s, int off, int size1,
                                     addr_t &count1, int inc1, int size2,
                                     addr_t &count2, int inc2) {
  fifo_st_flush_bare_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}

// CHECK-LABEL: @_Z23test_fifo_st_flush_convRrP23v128bfp16ebs8_unalignedR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP9:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP4]], <32 x i32> [[TMP7]], i32 [[TMP8]])
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP9]], 0
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP9]], 1
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP9]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP12]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv(v128bfp16ebs8_unaligned *restrict &p,
                             fifo_state_t &s) {
  fifo_st_flush_conv(p, s);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_1d_byteRrP23v128bfp16ebs8_unalignedR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP9:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP10:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP4]], <32 x i32> [[TMP7]], i32 [[TMP8]], i20 [[TMP9]])
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP10]], 0
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP10]], 1
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP10]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP12]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP11]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_1d_byte(v128bfp16ebs8_unaligned *restrict &p,
                                     fifo_state_t &s, int off) {
  fifo_st_flush_conv_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_2d_byteRrP23v128bfp16ebs8_unalignedR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP9:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP12:%.*]] = trunc i32 [[TMP11]] to i20
// CHECK-NEXT:    [[TMP13:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP14:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP4]], <32 x i32> [[TMP7]], i32 [[TMP8]], i20 [[TMP9]], i20 [[TMP10]], i20 [[TMP12]], i20 [[TMP13]])
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP14]], 0
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP14]], 1
// CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP14]], 2
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP14]], 3
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP16]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP15]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_2d_byte(v128bfp16ebs8_unaligned *restrict &p,
                                     fifo_state_t &s, int off, int size1,
                                     addr_t &count1, int inc1) {
  fifo_st_flush_conv_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_3d_byteRrP23v128bfp16ebs8_unalignedR12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP9:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP12:%.*]] = trunc i32 [[TMP11]] to i20
// CHECK-NEXT:    [[TMP13:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP14:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP15:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP16:%.*]] = trunc i32 [[TMP15]] to i20
// CHECK-NEXT:    [[TMP17:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP18:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP4]], <32 x i32> [[TMP7]], i32 [[TMP8]], i20 [[TMP9]], i20 [[TMP10]], i20 [[TMP12]], i20 [[TMP13]], i20 [[TMP14]], i20 [[TMP16]], i20 [[TMP17]])
// CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP18]], 0
// CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP18]], 1
// CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP18]], 2
// CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP18]], 3
// CHECK-NEXT:    [[TMP23:%.*]] = zext i20 [[TMP22]] to i32
// CHECK-NEXT:    [[TMP24:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP18]], 4
// CHECK-NEXT:    [[TMP25:%.*]] = zext i20 [[TMP24]] to i32
// CHECK-NEXT:    store i32 [[TMP23]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP25]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP20]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP21]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP19]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_3d_byte(v128bfp16ebs8_unaligned *restrict &p,
                                     fifo_state_t &s, int off, int size1,
                                     addr_t &count1, int inc1, int size2,
                                     addr_t &count2, int inc2) {
  fifo_st_flush_conv_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}

// CHECK-LABEL: @_Z18test_fifo_st_resetRrP24v128bfp16ebs16_unaligned14v128bfp16ebs16R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V128BFP16EBS16:%.*]] [[V_COERCE:%.*]], 2
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V128BFP16EBS16]] [[V_COERCE]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.544.bfp16.p0.p0(ptr [[TMP2]], <64 x i8> [[TMP1]], <8 x i8> [[TMP0]], <32 x i32> [[TMP3]], i32 0)
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[POS_I]], align 64
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V128BFP16EBS16]] [[V_COERCE]], 3
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue [[STRUCT_V128BFP16EBS16]] [[V_COERCE]], 1
// CHECK-NEXT:    [[TMP10:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr [[POS_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.544.bfp16.p0.p0(ptr [[TMP5]], <64 x i8> [[TMP9]], <8 x i8> [[TMP8]], <32 x i32> [[TMP10]], i32 [[TMP11]])
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP12]], 0
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP12]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP12]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP15]], ptr [[POS_I]], align 64
// CHECK-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_reset(v128bfp16ebs16_unaligned *restrict &p, v128bfp16ebs16 v,
                        fifo_state_t &s) {
  fifo_st_reset(p, v, s);
}

// CHECK-LABEL: @_Z17test_fifo_st_pushRrP24v128bfp16ebs16_unaligned14v128bfp16ebs16R12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V128BFP16EBS16:%.*]] [[V_COERCE:%.*]], 2
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V128BFP16EBS16]] [[V_COERCE]], 0
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP5:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.544.bfp16.p0.p0(ptr [[TMP2]], <64 x i8> [[TMP1]], <8 x i8> [[TMP0]], <32 x i32> [[TMP3]], i32 [[TMP4]])
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP5]], 0
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP5]], 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP5]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue [[STRUCT_V128BFP16EBS16]] [[V_COERCE]], 3
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue [[STRUCT_V128BFP16EBS16]] [[V_COERCE]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP12:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP13:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.544.bfp16.p0.p0(ptr [[TMP6]], <64 x i8> [[TMP10]], <8 x i8> [[TMP9]], <32 x i32> [[TMP11]], i32 [[TMP12]])
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP13]], 0
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP13]], 1
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP13]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP16]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP14]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_push(v128bfp16ebs16_unaligned *restrict &p, v128bfp16ebs16 v,
                       fifo_state_t &s) {
  fifo_st_push(p, v, s);
}

// CHECK-LABEL: @_Z18test_fifo_st_flushRrP24v128bfp16ebs16_unalignedR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP9:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP4]], <32 x i32> [[TMP7]], i32 [[TMP8]])
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP9]], 0
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP9]], 1
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP9]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP12]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush(v128bfp16ebs16_unaligned *restrict &p,
                        fifo_state_t &s) {
  fifo_st_flush(p, s);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_1d_byteRrP24v128bfp16ebs16_unalignedR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP9:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP10:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP4]], <32 x i32> [[TMP7]], i32 [[TMP8]], i20 [[TMP9]])
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP10]], 0
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP10]], 1
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP10]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP12]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP11]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_1d_byte(v128bfp16ebs16_unaligned *restrict &p,
                                fifo_state_t &s, int off) {
  fifo_st_flush_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_2d_byteRrP24v128bfp16ebs16_unalignedR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP9:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP12:%.*]] = trunc i32 [[TMP11]] to i20
// CHECK-NEXT:    [[TMP13:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP14:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP4]], <32 x i32> [[TMP7]], i32 [[TMP8]], i20 [[TMP9]], i20 [[TMP10]], i20 [[TMP12]], i20 [[TMP13]])
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP14]], 0
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP14]], 1
// CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP14]], 2
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP14]], 3
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP16]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP15]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_2d_byte(v128bfp16ebs16_unaligned *restrict &p,
                                fifo_state_t &s, int off, int size1,
                                addr_t &count1, int inc1) {
  fifo_st_flush_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z26test_fifo_st_flush_3d_byteRrP24v128bfp16ebs16_unalignedR12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP9:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP12:%.*]] = trunc i32 [[TMP11]] to i20
// CHECK-NEXT:    [[TMP13:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP14:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP15:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP16:%.*]] = trunc i32 [[TMP15]] to i20
// CHECK-NEXT:    [[TMP17:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP18:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP4]], <32 x i32> [[TMP7]], i32 [[TMP8]], i20 [[TMP9]], i20 [[TMP10]], i20 [[TMP12]], i20 [[TMP13]], i20 [[TMP14]], i20 [[TMP16]], i20 [[TMP17]])
// CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP18]], 0
// CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP18]], 1
// CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP18]], 2
// CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP18]], 3
// CHECK-NEXT:    [[TMP23:%.*]] = zext i20 [[TMP22]] to i32
// CHECK-NEXT:    [[TMP24:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP18]], 4
// CHECK-NEXT:    [[TMP25:%.*]] = zext i20 [[TMP24]] to i32
// CHECK-NEXT:    store i32 [[TMP23]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP25]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP20]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP21]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP19]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_3d_byte(v128bfp16ebs16_unaligned *restrict &p,
                                fifo_state_t &s, int off, int size1,
                                addr_t &count1, int inc1, int size2,
                                addr_t &count2, int inc2) {
  fifo_st_flush_3d_byte(p, s, off, size1, count1, inc1, size2, count2, inc2);
}

// CHECK-LABEL: @_Z23test_fifo_st_flush_bareRrP24v128bfp16ebs16_unalignedR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP9:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP4]], <32 x i32> [[TMP7]], i32 [[TMP8]])
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP9]], 0
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP9]], 1
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP9]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP12]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare(v128bfp16ebs16_unaligned *restrict &p,
                             fifo_state_t &s) {
  fifo_st_flush_bare(p, s);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_1d_byteRrP24v128bfp16ebs16_unalignedR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP9:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP10:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP4]], <32 x i32> [[TMP7]], i32 [[TMP8]], i20 [[TMP9]])
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP10]], 0
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP10]], 1
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP10]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP12]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP11]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_1d_byte(v128bfp16ebs16_unaligned *restrict &p,
                                     fifo_state_t &s, int off) {
  fifo_st_flush_bare_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_2d_byteRrP24v128bfp16ebs16_unalignedR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP9:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP12:%.*]] = trunc i32 [[TMP11]] to i20
// CHECK-NEXT:    [[TMP13:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP14:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP4]], <32 x i32> [[TMP7]], i32 [[TMP8]], i20 [[TMP9]], i20 [[TMP10]], i20 [[TMP12]], i20 [[TMP13]])
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP14]], 0
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP14]], 1
// CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP14]], 2
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP14]], 3
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP16]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP15]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_2d_byte(v128bfp16ebs16_unaligned *restrict &p,
                                     fifo_state_t &s, int off, int size1,
                                     addr_t &count1, int inc1) {
  fifo_st_flush_bare_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_bare_3d_byteRrP24v128bfp16ebs16_unalignedR12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP9:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP12:%.*]] = trunc i32 [[TMP11]] to i20
// CHECK-NEXT:    [[TMP13:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP14:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP15:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP16:%.*]] = trunc i32 [[TMP15]] to i20
// CHECK-NEXT:    [[TMP17:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP18:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP4]], <32 x i32> [[TMP7]], i32 [[TMP8]], i20 [[TMP9]], i20 [[TMP10]], i20 [[TMP12]], i20 [[TMP13]], i20 [[TMP14]], i20 [[TMP16]], i20 [[TMP17]])
// CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP18]], 0
// CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP18]], 1
// CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP18]], 2
// CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP18]], 3
// CHECK-NEXT:    [[TMP23:%.*]] = zext i20 [[TMP22]] to i32
// CHECK-NEXT:    [[TMP24:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP18]], 4
// CHECK-NEXT:    [[TMP25:%.*]] = zext i20 [[TMP24]] to i32
// CHECK-NEXT:    store i32 [[TMP23]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP25]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP20]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP21]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP19]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_bare_3d_byte(v128bfp16ebs16_unaligned *restrict &p,
                                     fifo_state_t &s, int off, int size1,
                                     addr_t &count1, int inc1, int size2,
                                     addr_t &count2, int inc2) {
  fifo_st_flush_bare_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}

// CHECK-LABEL: @_Z23test_fifo_st_flush_convRrP24v128bfp16ebs16_unalignedR12fifo_state_t(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP9:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP4]], <32 x i32> [[TMP7]], i32 [[TMP8]])
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP9]], 0
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP9]], 1
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP9]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP12]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP10]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv(v128bfp16ebs16_unaligned *restrict &p,
                             fifo_state_t &s) {
  fifo_st_flush_conv(p, s);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_1d_byteRrP24v128bfp16ebs16_unalignedR12fifo_state_ti(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP9:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP10:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr [[TMP4]], <32 x i32> [[TMP7]], i32 [[TMP8]], i20 [[TMP9]])
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP10]], 0
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP10]], 1
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP10]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP12]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP11]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_1d_byte(v128bfp16ebs16_unaligned *restrict &p,
                                     fifo_state_t &s, int off) {
  fifo_st_flush_conv_1d_byte(p, s, off);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_2d_byteRrP24v128bfp16ebs16_unalignedR12fifo_state_tiiRii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP9:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP12:%.*]] = trunc i32 [[TMP11]] to i20
// CHECK-NEXT:    [[TMP13:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP14:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP4]], <32 x i32> [[TMP7]], i32 [[TMP8]], i20 [[TMP9]], i20 [[TMP10]], i20 [[TMP12]], i20 [[TMP13]])
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP14]], 0
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP14]], 1
// CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP14]], 2
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP14]], 3
// CHECK-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP16]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP17]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP15]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_2d_byte(v128bfp16ebs16_unaligned *restrict &p,
                                     fifo_state_t &s, int off, int size1,
                                     addr_t &count1, int inc1) {
  fifo_st_flush_conv_2d_byte(p, s, off, size1, count1, inc1);
}

// CHECK-LABEL: @_Z31test_fifo_st_flush_conv_3d_byteRrP24v128bfp16ebs16_unalignedR12fifo_state_tiiRiiiS5_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S:%.*]], i20 128
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P:%.*]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// CHECK-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP9:%.*]] = trunc i32 [[OFF:%.*]] to i20
// CHECK-NEXT:    [[TMP10:%.*]] = trunc i32 [[SIZE1:%.*]] to i20
// CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr [[COUNT1:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP12:%.*]] = trunc i32 [[TMP11]] to i20
// CHECK-NEXT:    [[TMP13:%.*]] = trunc i32 [[INC1:%.*]] to i20
// CHECK-NEXT:    [[TMP14:%.*]] = trunc i32 [[SIZE2:%.*]] to i20
// CHECK-NEXT:    [[TMP15:%.*]] = load i32, ptr [[COUNT2:%.*]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    [[TMP16:%.*]] = trunc i32 [[TMP15]] to i20
// CHECK-NEXT:    [[TMP17:%.*]] = trunc i32 [[INC2:%.*]] to i20
// CHECK-NEXT:    [[TMP18:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.p0.p0(ptr [[TMP4]], <32 x i32> [[TMP7]], i32 [[TMP8]], i20 [[TMP9]], i20 [[TMP10]], i20 [[TMP12]], i20 [[TMP13]], i20 [[TMP14]], i20 [[TMP16]], i20 [[TMP17]])
// CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP18]], 0
// CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP18]], 1
// CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP18]], 2
// CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP18]], 3
// CHECK-NEXT:    [[TMP23:%.*]] = zext i20 [[TMP22]] to i32
// CHECK-NEXT:    [[TMP24:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP18]], 4
// CHECK-NEXT:    [[TMP25:%.*]] = zext i20 [[TMP24]] to i32
// CHECK-NEXT:    store i32 [[TMP23]], ptr [[COUNT1]], align 4
// CHECK-NEXT:    store i32 [[TMP25]], ptr [[COUNT2]], align 4
// CHECK-NEXT:    store <32 x i32> [[TMP20]], ptr [[S]], align 128
// CHECK-NEXT:    store i32 [[TMP21]], ptr [[POS1_I_I]], align 64
// CHECK-NEXT:    store ptr [[TMP19]], ptr [[P]], align 4
// CHECK-NEXT:    ret void
//
void test_fifo_st_flush_conv_3d_byte(v128bfp16ebs16_unaligned *restrict &p,
                                     fifo_state_t &s, int off, int size1,
                                     addr_t &count1, int inc1, int size2,
                                     addr_t &count2, int inc2) {
  fifo_st_flush_conv_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}
