// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
//===- aie2p-srs-intrinsics.cpp ---------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//
// RUN: %clang -O2 %s --target=aie2p -nostdlibinc -S -emit-llvm -o - | FileCheck %s


// CHECK-LABEL: @_Z30v32acc64_to_v32int16_ssrs_testDv32_u7__acc64ii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.I512.v32.acc64.srs(<32 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <32 x i16> [[TMP0]]
//
v32int16 v32acc64_to_v32int16_ssrs_test(v32acc64 acc, int shft, int sign){
  return ssrs(acc, shft, sign);
}

// CHECK-LABEL: @_Z35v32acc64_to_v32int16_ssrs_conf_testDv32_u7__acc64iijj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.I512.v32.acc64.srs(<32 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// CHECK-NEXT:    ret <32 x i16> [[TMP2]]
//
v32int16 v32acc64_to_v32int16_ssrs_conf_test(v32acc64 acc, int shft, int sign, crsat_t sat, crrnd_t rnd){
  return ssrs_conf(acc, shft, sign, sat, rnd);
}
// CHECK-LABEL: @_Z31v32acc64_to_v32int16_ussrs_testDv32_u7__acc64ii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.I512.v32.acc64.srs(<32 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i16> [[TMP0]] to <64 x i8>
// CHECK-NEXT:    ret <64 x i8> [[TMP1]]
//
v64uint8 v32acc64_to_v32int16_ussrs_test(v32acc64 acc, int shft, int sign){
  return ussrs(acc, shft, sign);
}

// CHECK-LABEL: @_Z36v32acc64_to_v32int16_ussrs_conf_testDv32_u7__acc64iijj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.I512.v32.acc64.srs(<32 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <32 x i16> [[TMP2]] to <64 x i8>
// CHECK-NEXT:    ret <64 x i8> [[TMP3]]
//
v64uint8 v32acc64_to_v32int16_ussrs_conf_test(v32acc64 acc, int shft, int sign, crsat_t sat, crrnd_t rnd){
  return ussrs_conf(acc, shft, sign, sat, rnd);
}

// CHECK-LABEL: @_Z37v32acc64_to_v32int16_ssrs_nosign_testDv32_u7__acc64i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.I512.v32.acc64.srs(<32 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    ret <32 x i16> [[TMP0]]
//
v32int16 v32acc64_to_v32int16_ssrs_nosign_test(v32acc64 acc, int shft){
  return ssrs(acc, shft);
}

// CHECK-LABEL: @_Z42v32acc64_to_v32int16_ssrs_conf_nosign_testDv32_u7__acc64ijj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.I512.v32.acc64.srs(<32 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// CHECK-NEXT:    ret <32 x i16> [[TMP2]]
//
v32int16 v32acc64_to_v32int16_ssrs_conf_nosign_test(v32acc64 acc, int shft, crsat_t sat, crrnd_t rnd){
  return ssrs_conf(acc, shft, sat, rnd);
}
// CHECK-LABEL: @_Z38v32acc64_to_v32int16_ussrs_nosign_testDv32_u7__acc64i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.I512.v32.acc64.srs(<32 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i16> [[TMP0]] to <64 x i8>
// CHECK-NEXT:    ret <64 x i8> [[TMP1]]
//
v64uint8 v32acc64_to_v32int16_ussrs_nosign_test(v32acc64 acc, int shft){
  return ussrs(acc, shft);
}

// CHECK-LABEL: @_Z43v32acc64_to_v32int16_ussrs_conf_nosign_testDv32_u7__acc64ijj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.I512.v32.acc64.srs(<32 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <32 x i16> [[TMP2]] to <64 x i8>
// CHECK-NEXT:    ret <64 x i8> [[TMP3]]
//
v64uint8 v32acc64_to_v32int16_ussrs_conf_nosign_test(v32acc64 acc, int shft, crsat_t sat, crrnd_t rnd){
  return ussrs_conf(acc, shft, sat, rnd);
}
// CHECK-LABEL: @_Z29v64acc32_to_v64int8_ssrs_testDv64_u7__acc32ii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i8> @llvm.aie2p.I512.v64.acc32.srs(<64 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <64 x i8> [[TMP0]]
//
v64int8 v64acc32_to_v64int8_ssrs_test(v64acc32 acc, int shft, int sign){
  return ssrs(acc, shft, sign);
}

// CHECK-LABEL: @_Z34v64acc32_to_v64int8_ssrs_conf_testDv64_u7__acc32iijj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <64 x i8> @llvm.aie2p.I512.v64.acc32.srs(<64 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// CHECK-NEXT:    ret <64 x i8> [[TMP2]]
//
v64int8 v64acc32_to_v64int8_ssrs_conf_test(v64acc32 acc, int shft, int sign, crsat_t sat, crrnd_t rnd){
  return ssrs_conf(acc, shft, sign, sat, rnd);
}
// CHECK-LABEL: @_Z30v64acc32_to_v64int8_ussrs_testDv64_u7__acc32ii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i8> @llvm.aie2p.I512.v64.acc32.srs(<64 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <64 x i8> [[TMP0]]
//
v64uint8 v64acc32_to_v64int8_ussrs_test(v64acc32 acc, int shft, int sign){
  return ussrs(acc, shft, sign);
}

// CHECK-LABEL: @_Z35v64acc32_to_v64int8_ussrs_conf_testDv64_u7__acc32iijj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <64 x i8> @llvm.aie2p.I512.v64.acc32.srs(<64 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// CHECK-NEXT:    ret <64 x i8> [[TMP2]]
//
v64uint8 v64acc32_to_v64int8_ussrs_conf_test(v64acc32 acc, int shft, int sign, crsat_t sat, crrnd_t rnd){
  return ussrs_conf(acc, shft, sign, sat, rnd);
}

// CHECK-LABEL: @_Z36v64acc32_to_v64int8_ssrs_nosign_testDv64_u7__acc32i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i8> @llvm.aie2p.I512.v64.acc32.srs(<64 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    ret <64 x i8> [[TMP0]]
//
v64int8 v64acc32_to_v64int8_ssrs_nosign_test(v64acc32 acc, int shft){
  return ssrs(acc, shft);
}

// CHECK-LABEL: @_Z41v64acc32_to_v64int8_ssrs_conf_nosign_testDv64_u7__acc32ijj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <64 x i8> @llvm.aie2p.I512.v64.acc32.srs(<64 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// CHECK-NEXT:    ret <64 x i8> [[TMP2]]
//
v64int8 v64acc32_to_v64int8_ssrs_conf_nosign_test(v64acc32 acc, int shft, crsat_t sat, crrnd_t rnd){
  return ssrs_conf(acc, shft, sat, rnd);
}
// CHECK-LABEL: @_Z37v64acc32_to_v64int8_ussrs_nosign_testDv64_u7__acc32i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i8> @llvm.aie2p.I512.v64.acc32.srs(<64 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// CHECK-NEXT:    ret <64 x i8> [[TMP0]]
//
v64uint8 v64acc32_to_v64int8_ussrs_nosign_test(v64acc32 acc, int shft){
  return ussrs(acc, shft);
}

// CHECK-LABEL: @_Z42v64acc32_to_v64int8_ussrs_conf_nosign_testDv64_u7__acc32ijj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <64 x i8> @llvm.aie2p.I512.v64.acc32.srs(<64 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// CHECK-NEXT:    ret <64 x i8> [[TMP2]]
//
v64uint8 v64acc32_to_v64int8_ussrs_conf_nosign_test(v64acc32 acc, int shft, crsat_t sat, crrnd_t rnd){
  return ussrs_conf(acc, shft, sat, rnd);
}

// Floating-point accumulator to block floating-point vector register

// CHECK-LABEL: @_Z20test_to_v64bfp16ebs8Dv64_u10__accfloat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <8 x i8> } @llvm.aie2p.v64accfloat.to.v64bfp16ebs8(<64 x float> [[A:%.*]])
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <8 x i8> } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <8 x i8> } [[TMP0]], 1
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS8:%.*]] poison, <64 x i8> [[TMP1]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS8]] [[DOTFCA_0_INSERT_I]], <8 x i8> [[TMP2]], 1
// CHECK-NEXT:    ret [[STRUCT_V64BFP16EBS8]] [[DOTFCA_1_INSERT_I]]
//
v64bfp16ebs8 test_to_v64bfp16ebs8(v64accfloat a) {
  return to_v64bfp16ebs8(a);
}

// CHECK-LABEL: @_Z21test_to_v64bfp16ebs16Dv64_u10__accfloat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <8 x i8> } @llvm.aie2p.v64accfloat.to.v64bfp16ebs16(<64 x float> [[A:%.*]])
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <8 x i8> } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <8 x i8> } [[TMP0]], 1
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS16:%.*]] poison, <64 x i8> [[TMP1]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS16]] [[DOTFCA_0_INSERT_I]], <8 x i8> [[TMP2]], 1
// CHECK-NEXT:    ret [[STRUCT_V64BFP16EBS16]] [[DOTFCA_1_INSERT_I]]
//
v64bfp16ebs16 test_to_v64bfp16ebs16(v64accfloat a) {
  return to_v64bfp16ebs16(a);
}

// CHECK-LABEL: @_Z21test_to_v64bfp16ebs1612v64bfp16ebs8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[A_COERCE_FCA_0_EXTRACT_I:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-NEXT:    [[A_COERCE_FCA_1_EXTRACT_I:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <8 x i8> } @llvm.aie2p.v64bfp16ebs8.to.v64bfp16ebs16(<64 x i8> [[A_COERCE_FCA_0_EXTRACT_I]], <8 x i8> [[A_COERCE_FCA_1_EXTRACT_I]])
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <8 x i8> } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <8 x i8> } [[TMP0]], 1
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS16:%.*]] poison, <64 x i8> [[TMP1]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS16]] [[DOTFCA_0_INSERT_I]], <8 x i8> [[TMP2]], 1
// CHECK-NEXT:    ret [[STRUCT_V64BFP16EBS16]] [[DOTFCA_1_INSERT_I]]
//
v64bfp16ebs16 test_to_v64bfp16ebs16(v64bfp16ebs8 a) {
  return to_v64bfp16ebs16(a);
}

// CHECK-LABEL: @_Z25test_to_v64bfp16ebs8_confDv64_u10__accfloatj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP1:%.*]] = tail call { <64 x i8>, <8 x i8> } @llvm.aie2p.v64accfloat.to.v64bfp16ebs8(<64 x float> [[A:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <8 x i8> } [[TMP1]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <64 x i8>, <8 x i8> } [[TMP1]], 1
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS8:%.*]] poison, <64 x i8> [[TMP2]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS8]] [[DOTFCA_0_INSERT_I_I]], <8 x i8> [[TMP3]], 1
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP0]])
// CHECK-NEXT:    ret [[STRUCT_V64BFP16EBS8]] [[DOTFCA_1_INSERT_I_I]]
//
v64bfp16ebs8 test_to_v64bfp16ebs8_conf(v64accfloat a, crrnd_t rnd) {
  return to_v64bfp16ebs8_conf(a, rnd);
}

// CHECK-LABEL: @_Z26test_to_v64bfp16ebs16_confDv64_u10__accfloatj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP1:%.*]] = tail call { <64 x i8>, <8 x i8> } @llvm.aie2p.v64accfloat.to.v64bfp16ebs16(<64 x float> [[A:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <8 x i8> } [[TMP1]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <64 x i8>, <8 x i8> } [[TMP1]], 1
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS16:%.*]] poison, <64 x i8> [[TMP2]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS16]] [[DOTFCA_0_INSERT_I_I]], <8 x i8> [[TMP3]], 1
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP0]])
// CHECK-NEXT:    ret [[STRUCT_V64BFP16EBS16]] [[DOTFCA_1_INSERT_I_I]]
//
v64bfp16ebs16 test_to_v64bfp16ebs16_conf(v64accfloat a, crrnd_t rnd) {
  return to_v64bfp16ebs16_conf(a, rnd);
}

// CHECK-LABEL: @_Z26test_to_v64bfp16ebs16_conf12v64bfp16ebs8j(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[A_COERCE_FCA_0_EXTRACT_I_I:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-NEXT:    [[A_COERCE_FCA_1_EXTRACT_I_I:%.*]] = extractvalue [[STRUCT_V64BFP16EBS8]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP1:%.*]] = tail call { <64 x i8>, <8 x i8> } @llvm.aie2p.v64bfp16ebs8.to.v64bfp16ebs16(<64 x i8> [[A_COERCE_FCA_0_EXTRACT_I_I]], <8 x i8> [[A_COERCE_FCA_1_EXTRACT_I_I]])
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <8 x i8> } [[TMP1]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <64 x i8>, <8 x i8> } [[TMP1]], 1
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS16:%.*]] poison, <64 x i8> [[TMP2]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS16]] [[DOTFCA_0_INSERT_I_I]], <8 x i8> [[TMP3]], 1
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP0]])
// CHECK-NEXT:    ret [[STRUCT_V64BFP16EBS16]] [[DOTFCA_1_INSERT_I_I]]
//
v64bfp16ebs16 test_to_v64bfp16ebs16_conf(v64bfp16ebs8 a, crrnd_t rnd) {
  return to_v64bfp16ebs16_conf(a, rnd);
}

// CHECK-LABEL: @_Z20test_to_v64bfp16ebs8Dv64_f(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <8 x i8> } @llvm.aie2p.v64accfloat.to.v64bfp16ebs8(<64 x float> [[A:%.*]])
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <8 x i8> } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <8 x i8> } [[TMP0]], 1
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS8:%.*]] poison, <64 x i8> [[TMP1]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS8]] [[DOTFCA_0_INSERT_I_I]], <8 x i8> [[TMP2]], 1
// CHECK-NEXT:    ret [[STRUCT_V64BFP16EBS8]] [[DOTFCA_1_INSERT_I_I]]
//
v64bfp16ebs8 test_to_v64bfp16ebs8(v64float a) {
  return to_v64bfp16ebs8(a);
}
// CHECK-LABEL: @_Z21test_to_v64bfp16ebs16Dv64_f(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <64 x i8>, <8 x i8> } @llvm.aie2p.v64accfloat.to.v64bfp16ebs16(<64 x float> [[A:%.*]])
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <64 x i8>, <8 x i8> } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <8 x i8> } [[TMP0]], 1
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS16:%.*]] poison, <64 x i8> [[TMP1]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS16]] [[DOTFCA_0_INSERT_I_I]], <8 x i8> [[TMP2]], 1
// CHECK-NEXT:    ret [[STRUCT_V64BFP16EBS16]] [[DOTFCA_1_INSERT_I_I]]
//
v64bfp16ebs16 test_to_v64bfp16ebs16(v64float a) {
  return to_v64bfp16ebs16(a);
}

// CHECK-LABEL: @_Z25test_to_v64bfp16ebs8_confDv64_fj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP1:%.*]] = tail call { <64 x i8>, <8 x i8> } @llvm.aie2p.v64accfloat.to.v64bfp16ebs8(<64 x float> [[A:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <8 x i8> } [[TMP1]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <64 x i8>, <8 x i8> } [[TMP1]], 1
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS8:%.*]] poison, <64 x i8> [[TMP2]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS8]] [[DOTFCA_0_INSERT_I_I]], <8 x i8> [[TMP3]], 1
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP0]])
// CHECK-NEXT:    ret [[STRUCT_V64BFP16EBS8]] [[DOTFCA_1_INSERT_I_I]]
//
v64bfp16ebs8 test_to_v64bfp16ebs8_conf(v64float a, crrnd_t rnd) {
  return to_v64bfp16ebs8_conf(a, rnd);
}

// CHECK-LABEL: @_Z26test_to_v64bfp16ebs16_confDv64_fj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP1:%.*]] = tail call { <64 x i8>, <8 x i8> } @llvm.aie2p.v64accfloat.to.v64bfp16ebs16(<64 x float> [[A:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <64 x i8>, <8 x i8> } [[TMP1]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <64 x i8>, <8 x i8> } [[TMP1]], 1
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS16:%.*]] poison, <64 x i8> [[TMP2]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64BFP16EBS16]] [[DOTFCA_0_INSERT_I_I]], <8 x i8> [[TMP3]], 1
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP0]])
// CHECK-NEXT:    ret [[STRUCT_V64BFP16EBS16]] [[DOTFCA_1_INSERT_I_I]]
//
v64bfp16ebs16 test_to_v64bfp16ebs16_conf(v64float a, crrnd_t rnd) {
  return to_v64bfp16ebs16_conf(a, rnd);
}
// CHECK-LABEL: @_Z15test_to_v32int8Dv32_u7__acc32ii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i8> @llvm.aie2p.I256.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <32 x i8> [[TMP0]]
//
v32int8 test_to_v32int8(v32acc32 acc, int shft, int sign) {
  return to_v32int8(acc, shft, sign);
}
// CHECK-LABEL: @_Z20test_to_v32int8_confDv32_u7__acc32iijj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i8> @llvm.aie2p.I256.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// CHECK-NEXT:    ret <32 x i8> [[TMP2]]
//
v32int8 test_to_v32int8_conf(v32acc32 acc, int shft, int sign, crsat_t sat,
                    crrnd_t rnd) {
  return to_v32int8_conf(acc, shft, sign, sat, rnd);
}
// CHECK-LABEL: @_Z16test_to_v32uint8Dv32_u7__acc32ii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i8> @llvm.aie2p.I256.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <32 x i8> [[TMP0]]
//
v32uint8 test_to_v32uint8(v32acc32 acc, int shft, int sign) {
  return to_v32uint8(acc, shft, sign);
}
// CHECK-LABEL: @_Z21test_to_v32uint8_confDv32_u7__acc32iijj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i8> @llvm.aie2p.I256.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// CHECK-NEXT:    ret <32 x i8> [[TMP2]]
//
v32uint8 test_to_v32uint8_conf(v32acc32 acc, int shft, int sign, crsat_t sat,
                     crrnd_t rnd) {
  return to_v32uint8_conf(acc, shft, sign, sat, rnd);
}
// CHECK-LABEL: @_Z16test_to_v32int16Dv32_u7__acc32ii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.I512.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <32 x i16> [[TMP0]]
//
v32int16 test_to_v32int16(v32acc32 acc, int shft, int sign) {
  return to_v32int16(acc, shft, sign);
}
// CHECK-LABEL: @_Z21test_to_v32int16_confDv32_u7__acc32iijj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.I512.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// CHECK-NEXT:    ret <32 x i16> [[TMP2]]
//
v32int16 test_to_v32int16_conf(v32acc32 acc, int shft, int sign, crsat_t sat,
                     crrnd_t rnd) {
  return to_v32int16_conf(acc, shft, sign, sat, rnd);
}
// CHECK-LABEL: @_Z17test_to_v32uint16Dv32_u7__acc32ii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.I512.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <32 x i16> [[TMP0]]
//
v32uint16 test_to_v32uint16(v32acc32 acc, int shft, int sign) {
  return to_v32uint16(acc, shft, sign);
}
// CHECK-LABEL: @_Z22test_to_v32uint16_confDv32_u7__acc32iijj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.I512.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// CHECK-NEXT:    ret <32 x i16> [[TMP2]]
//
v32uint16 test_to_v32uint16_conf(v32acc32 acc, int shft, int sign, crsat_t sat,
                      crrnd_t rnd) {
  return to_v32uint16_conf(acc, shft, sign, sat, rnd);
}
// CHECK-LABEL: @_Z16test_to_v16int16Dv16_u7__acc32ii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i16> @llvm.aie2p.I256.v16.acc32.srs(<16 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <16 x i16> [[TMP0]]
//
v16int16 test_to_v16int16(v16acc32 acc, int shft, int sign) {
  return to_v16int16(acc, shft, sign);
}
// CHECK-LABEL: @_Z21test_to_v16int16_confDv16_u7__acc32iijj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i16> @llvm.aie2p.I256.v16.acc32.srs(<16 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// CHECK-NEXT:    ret <16 x i16> [[TMP2]]
//
v16int16 test_to_v16int16_conf(v16acc32 acc, int shft, int sign, crsat_t sat,
                     crrnd_t rnd) {
  return to_v16int16_conf(acc, shft, sign, sat, rnd);
}
// CHECK-LABEL: @_Z17test_to_v16uint16Dv16_u7__acc32ii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i16> @llvm.aie2p.I256.v16.acc32.srs(<16 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <16 x i16> [[TMP0]]
//
v16uint16 test_to_v16uint16(v16acc32 acc, int shft, int sign) {
  return to_v16uint16(acc, shft, sign);
}
// CHECK-LABEL: @_Z22test_to_v16uint16_confDv16_u7__acc32iijj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i16> @llvm.aie2p.I256.v16.acc32.srs(<16 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// CHECK-NEXT:    ret <16 x i16> [[TMP2]]
//
v16uint16 test_to_v16uint16_conf(v16acc32 acc, int shft, int sign, crsat_t sat,
                      crrnd_t rnd) {
  return to_v16uint16_conf(acc, shft, sign, sat, rnd);
}
// CHECK-LABEL: @_Z16test_to_v16int16Dv16_u7__acc64ii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i16> @llvm.aie2p.I256.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <16 x i16> [[TMP0]]
//
v16int16 test_to_v16int16(v16acc64 acc, int shft, int sign) {
  return to_v16int16(acc, shft, sign);
}
// CHECK-LABEL: @_Z21test_to_v16int16_confDv16_u7__acc64iijj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i16> @llvm.aie2p.I256.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// CHECK-NEXT:    ret <16 x i16> [[TMP2]]
//
v16int16 test_to_v16int16_conf(v16acc64 acc, int shft, int sign, crsat_t sat,
                     crrnd_t rnd) {
  return to_v16int16_conf(acc, shft, sign, sat, rnd);
}
// CHECK-LABEL: @_Z17test_to_v16uint16Dv16_u7__acc64ii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i16> @llvm.aie2p.I256.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <16 x i16> [[TMP0]]
//
v16uint16 test_to_v16uint16(v16acc64 acc, int shft, int sign) {
  return to_v16uint16(acc, shft, sign);
}
// CHECK-LABEL: @_Z22test_to_v16uint16_confDv16_u7__acc64iijj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i16> @llvm.aie2p.I256.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// CHECK-NEXT:    ret <16 x i16> [[TMP2]]
//
v16uint16 test_to_v16uint16_conf(v16acc64 acc, int shft, int sign, crsat_t sat,
                      crrnd_t rnd) {
  return to_v16uint16_conf(acc, shft, sign, sat, rnd);
}
// CHECK-LABEL: @_Z15test_to_v8int32Dv8_u7__acc64ii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.I256.v8.acc64.srs(<8 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <8 x i32> [[TMP0]]
//
v8int32 test_to_v8int32(v8acc64 acc, int shft, int sign) {
  return to_v8int32(acc, shft, sign);
}
// CHECK-LABEL: @_Z20test_to_v8int32_confDv8_u7__acc64iijj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.I256.v8.acc64.srs(<8 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// CHECK-NEXT:    ret <8 x i32> [[TMP2]]
//
v8int32 test_to_v8int32_conf(v8acc64 acc, int shft, int sign, crsat_t sat, crrnd_t rnd) {
  return to_v8int32_conf(acc, shft, sign, sat, rnd);
}
// CHECK-LABEL: @_Z16test_to_v8uint32Dv8_u7__acc64ii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.I256.v8.acc64.srs(<8 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <8 x i32> [[TMP0]]
//
v8uint32 test_to_v8uint32(v8acc64 acc, int shft, int sign) {
  return to_v8uint32(acc, shft, sign);
}
// CHECK-LABEL: @_Z21test_to_v8uint32_confDv8_u7__acc64iijj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.I256.v8.acc64.srs(<8 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// CHECK-NEXT:    ret <8 x i32> [[TMP2]]
//
v8uint32 test_to_v8uint32_conf(v8acc64 acc, int shft, int sign, crsat_t sat, crrnd_t rnd) {
  return to_v8uint32_conf(acc, shft, sign, sat, rnd);
}
// CHECK-LABEL: @_Z16test_to_v16int32Dv16_u7__acc64ii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.I512.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <16 x i32> [[TMP0]]
//
v16int32 test_to_v16int32(v16acc64 acc, int shft, int sign) {
  return to_v16int32(acc, shft, sign);
}
// CHECK-LABEL: @_Z21test_to_v16int32_confDv16_u7__acc64iijj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.I512.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// CHECK-NEXT:    ret <16 x i32> [[TMP2]]
//
v16int32 test_to_v16int32_conf(v16acc64 acc, int shft, int sign, crsat_t sat,
                     crrnd_t rnd) {
  return to_v16int32_conf(acc, shft, sign, sat, rnd);
}
// CHECK-LABEL: @_Z17test_to_v16uint32Dv16_u7__acc64ii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.I512.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <16 x i32> [[TMP0]]
//
v16uint32 test_to_v16uint32(v16acc64 acc, int shft, int sign) {
  return to_v16uint32(acc, shft, sign);
}
// CHECK-LABEL: @_Z22test_to_v16uint32_confDv16_u7__acc64iijj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.I512.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// CHECK-NEXT:    ret <16 x i32> [[TMP2]]
//
v16uint32 test_to_v16uint32_conf(v16acc64 acc, int shft, int sign, crsat_t sat,
                      crrnd_t rnd) {
  return to_v16uint32_conf(acc, shft, sign, sat, rnd);
}
// CHECK-LABEL: @_Z15test_to_v32int8Dv32_u7__acc32i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i8> @llvm.aie2p.I256.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    ret <32 x i8> [[TMP0]]
//
v32int8 test_to_v32int8(v32acc32 acc, int shft) {
  return to_v32int8(acc, shft);
}
// CHECK-LABEL: @_Z20test_to_v32int8_confDv32_u7__acc32ijj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i8> @llvm.aie2p.I256.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// CHECK-NEXT:    ret <32 x i8> [[TMP2]]
//
v32int8 test_to_v32int8_conf(v32acc32 acc, int shft, crsat_t sat,
                                   crrnd_t rnd) {
  return to_v32int8_conf(acc, shft, sat, rnd);
}
// CHECK-LABEL: @_Z16test_to_v32uint8Dv32_u7__acc32i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i8> @llvm.aie2p.I256.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// CHECK-NEXT:    ret <32 x i8> [[TMP0]]
//
v32uint8 test_to_v32uint8(v32acc32 acc, int shft) {
  return to_v32uint8(acc, shft);
}
// CHECK-LABEL: @_Z21test_to_v32uint8_confDv32_u7__acc32ijj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i8> @llvm.aie2p.I256.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// CHECK-NEXT:    ret <32 x i8> [[TMP2]]
//
v32uint8 test_to_v32uint8_conf(v32acc32 acc, int shft, crsat_t sat,
                                     crrnd_t rnd) {
  return to_v32uint8_conf(acc, shft, sat, rnd);
}
// CHECK-LABEL: @_Z16test_to_v32int16Dv32_u7__acc32i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.I512.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    ret <32 x i16> [[TMP0]]
//
v32int16 test_to_v32int16(v32acc32 acc, int shft) {
  return to_v32int16(acc, shft);
}
// CHECK-LABEL: @_Z21test_to_v32int16_confDv32_u7__acc32ijj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.I512.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// CHECK-NEXT:    ret <32 x i16> [[TMP2]]
//
v32int16 test_to_v32int16_conf(v32acc32 acc, int shft, crsat_t sat,
                                     crrnd_t rnd) {
  return to_v32int16_conf(acc, shft, sat, rnd);
}
// CHECK-LABEL: @_Z17test_to_v32uint16Dv32_u7__acc32i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.I512.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// CHECK-NEXT:    ret <32 x i16> [[TMP0]]
//
v32uint16 test_to_v32uint16(v32acc32 acc, int shft) {
  return to_v32uint16(acc, shft);
}
// CHECK-LABEL: @_Z22test_to_v32uint16_confDv32_u7__acc32ijj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i16> @llvm.aie2p.I512.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// CHECK-NEXT:    ret <32 x i16> [[TMP2]]
//
v32uint16 test_to_v32uint16_conf(v32acc32 acc, int shft, crsat_t sat,
                                       crrnd_t rnd) {
  return to_v32uint16_conf(acc, shft, sat, rnd);
}
// CHECK-LABEL: @_Z16test_to_v16int16Dv16_u7__acc32i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i16> @llvm.aie2p.I256.v16.acc32.srs(<16 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    ret <16 x i16> [[TMP0]]
//
v16int16 test_to_v16int16(v16acc32 acc, int shft) {
  return to_v16int16(acc, shft);
}
// CHECK-LABEL: @_Z21test_to_v16int16_confDv16_u7__acc32ijj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i16> @llvm.aie2p.I256.v16.acc32.srs(<16 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// CHECK-NEXT:    ret <16 x i16> [[TMP2]]
//
v16int16 test_to_v16int16_conf(v16acc32 acc, int shft, crsat_t sat,
                                     crrnd_t rnd) {
  return to_v16int16_conf(acc, shft, sat, rnd);
}
// CHECK-LABEL: @_Z17test_to_v16uint16Dv16_u7__acc32i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i16> @llvm.aie2p.I256.v16.acc32.srs(<16 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// CHECK-NEXT:    ret <16 x i16> [[TMP0]]
//
v16uint16 test_to_v16uint16(v16acc32 acc, int shft) {
  return to_v16uint16(acc, shft);
}
// CHECK-LABEL: @_Z22test_to_v16uint16_confDv16_u7__acc32ijj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i16> @llvm.aie2p.I256.v16.acc32.srs(<16 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// CHECK-NEXT:    ret <16 x i16> [[TMP2]]
//
v16uint16 test_to_v16uint16_conf(v16acc32 acc, int shft, crsat_t sat,
                                       crrnd_t rnd) {
  return to_v16uint16_conf(acc, shft, sat, rnd);
}
// CHECK-LABEL: @_Z16test_to_v16int16Dv16_u7__acc64i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i16> @llvm.aie2p.I256.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    ret <16 x i16> [[TMP0]]
//
v16int16 test_to_v16int16(v16acc64 acc, int shft) {
  return to_v16int16(acc, shft);
}
// CHECK-LABEL: @_Z21test_to_v16int16_confDv16_u7__acc64ijj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i16> @llvm.aie2p.I256.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// CHECK-NEXT:    ret <16 x i16> [[TMP2]]
//
v16int16 test_to_v16int16_conf(v16acc64 acc, int shft, crsat_t sat,
                                     crrnd_t rnd) {
  return to_v16int16_conf(acc, shft, sat, rnd);
}
// CHECK-LABEL: @_Z17test_to_v16uint16Dv16_u7__acc64i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i16> @llvm.aie2p.I256.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// CHECK-NEXT:    ret <16 x i16> [[TMP0]]
//
v16uint16 test_to_v16uint16(v16acc64 acc, int shft) {
  return to_v16uint16(acc, shft);
}
// CHECK-LABEL: @_Z22test_to_v16uint16_confDv16_u7__acc64ijj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i16> @llvm.aie2p.I256.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// CHECK-NEXT:    ret <16 x i16> [[TMP2]]
//
v16uint16 test_to_v16uint16_conf(v16acc64 acc, int shft, crsat_t sat,
                                       crrnd_t rnd) {
  return to_v16uint16_conf(acc, shft, sat, rnd);
}
// CHECK-LABEL: @_Z16test_to_v16int32Dv16_u7__acc64i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.I512.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    ret <16 x i32> [[TMP0]]
//
v16int32 test_to_v16int32(v16acc64 acc, int shft) {
  return to_v16int32(acc, shft);
}
// CHECK-LABEL: @_Z21test_to_v16int32_confDv16_u7__acc64ijj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.I512.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// CHECK-NEXT:    ret <16 x i32> [[TMP2]]
//
v16int32 test_to_v16int32_conf(v16acc64 acc, int shft, crsat_t sat,
                                     crrnd_t rnd) {
  return to_v16int32_conf(acc, shft, sat, rnd);
}
// CHECK-LABEL: @_Z17test_to_v16uint32Dv16_u7__acc64i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.I512.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// CHECK-NEXT:    ret <16 x i32> [[TMP0]]
//
v16uint32 test_to_v16uint32(v16acc64 acc, int shft) {
  return to_v16uint32(acc, shft);
}
// CHECK-LABEL: @_Z22test_to_v16uint32_confDv16_u7__acc64ijj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i32> @llvm.aie2p.I512.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// CHECK-NEXT:    ret <16 x i32> [[TMP2]]
//
v16uint32 test_to_v16uint32_conf(v16acc64 acc, int shft, crsat_t sat,
                                       crrnd_t rnd) {
  return to_v16uint32_conf(acc, shft, sat, rnd);
}
// CHECK-LABEL: @_Z15test_to_v8int32Dv8_u7__acc64i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.I256.v8.acc64.srs(<8 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    ret <8 x i32> [[TMP0]]
//
v8int32 test_to_v8int32(v8acc64 acc, int shft) {
  return to_v8int32(acc, shft);
}
// CHECK-LABEL: @_Z20test_to_v8int32_confDv8_u7__acc64ijj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.I256.v8.acc64.srs(<8 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// CHECK-NEXT:    ret <8 x i32> [[TMP2]]
//
v8int32 test_to_v8int32_conf(v8acc64 acc, int shft, crsat_t sat,
                                   crrnd_t rnd) {
  return to_v8int32_conf(acc, shft, sat, rnd);
}
// CHECK-LABEL: @_Z16test_to_v8uint32Dv8_u7__acc64i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.I256.v8.acc64.srs(<8 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// CHECK-NEXT:    ret <8 x i32> [[TMP0]]
//
v8uint32 test_to_v8uint32(v8acc64 acc, int shft) {
  return to_v8uint32(acc, shft);
}
// CHECK-LABEL: @_Z21test_to_v8uint32_confDv8_u7__acc64ijj(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2p.get.ctrl.reg(i32 1)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[SAT:%.*]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[RND:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <8 x i32> @llvm.aie2p.I256.v8.acc64.srs(<8 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 0, i32 [[TMP0]])
// CHECK-NEXT:    tail call void @llvm.aie2p.set.ctrl.reg(i32 1, i32 [[TMP1]])
// CHECK-NEXT:    ret <8 x i32> [[TMP2]]
//
v8uint32 test_to_v8uint32_conf(v8acc64 acc, int shft, crsat_t sat,
                                     crrnd_t rnd) {
  return to_v8uint32_conf(acc, shft, sat, rnd);
}
