// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 4
//===- test-vector-accfloat.cc ---------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//
// RUN: %clang -O2 %s --target=aie2p -nostdlibinc -S -emit-llvm -o - | FileCheck %s

// CHECK-LABEL: define dso_local void @_Z16preserve_read_tmj(
// CHECK-SAME: i32 noundef [[CHANNEL:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = xor i32 [[CHANNEL]], 524288
// CHECK-NEXT:    [[CONV_I:%.*]] = trunc i32 [[TMP0]] to i20
// CHECK-NEXT:    [[TMP1:%.*]] = inttoptr i20 [[CONV_I]] to ptr
// CHECK-NEXT:    br label [[WHILE_COND:%.*]]
// CHECK:       while.cond:
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef i32 @llvm.aie2p.read.tm(ptr [[TMP1]])
// CHECK-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP2]], 0
// CHECK-NEXT:    br i1 [[CMP_NOT]], label [[WHILE_END:%.*]], label [[WHILE_COND]], !llvm.loop [[LOOP2:![0-9]+]]
// CHECK:       while.end:
// CHECK-NEXT:    ret void
//
void preserve_read_tm(uint32 channel) {
    while ((read_tm(channel)) != 0) {}
}
//.
// CHECK: [[LOOP2]] = distinct !{[[LOOP2]], [[META3:![0-9]+]]}
// CHECK: [[META3]] = !{!"llvm.loop.mustprogress"}
//.
