// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 4
//===- test-vector-accfloat.cc ---------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//



// RUN: %clang -O2 %s --target=aie2p -nostdlibinc -S -emit-llvm -o - | FileCheck %s
// CHECK-LABEL: define dso_local inreg noundef <8 x float> @_Z15test_v8accfloatDv8_u10__accfloat(
// CHECK-SAME: <8 x float> inreg noundef returned [[A:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <8 x float> [[A]]
//
v8accfloat test_v8accfloat(v8accfloat a) {
 return a;
}
// CHECK-LABEL: define dso_local inreg noundef <16 x float> @_Z16test_v16accfloatDv16_u10__accfloat(
// CHECK-SAME: <16 x float> inreg noundef returned [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <16 x float> [[A]]
//
v16accfloat test_v16accfloat(v16accfloat a) {
 return a;
}
// CHECK-LABEL: define dso_local inreg noundef <32 x float> @_Z16test_v32accfloatDv32_u10__accfloat(
// CHECK-SAME: <32 x float> inreg noundef returned [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <32 x float> [[A]]
//
v32accfloat test_v32accfloat(v32accfloat a) {
 return a;
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z16test_v64accfloatDv64_u10__accfloat(
// CHECK-SAME: <64 x float> inreg noundef returned [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <64 x float> [[A]]
//
v64accfloat test_v64accfloat(v64accfloat a) {
 return a;
}
