# NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates

# This test exercises experimental modules
#   	AIERegDefUseTracker
#	AIEScheduleInterpreter
#	AIEPostRegAlloc
# using the motivating GEMM example skipping WAWRegRewriter.
# We rewrite suitable physregs to virtual regs, create the dependence graph,
# pipeline, then reallocate the virtual regs


# RUN: llc -verify-machineinstrs --mtriple=aie2p -O2 \
# RUN:   --start-before=postmisched \
# RUN:   --aie-postpipeliner-vreg-mode=1 \
# RUN:   --aie-postpipeliner-phys-mode=0 \
# RUN:   --aie-wawreg-rewrite=0 \
# RUN:   --aie-preassign-multi-slot-instr=1 \
# RUN:   --aie-materialize-pipeline=0 \
# RUN:   --aie-postpipeliner-maxii=10 \
# RUN:   -o - %s | FileCheck %s

# derived from GEMM_Bfp16_opt_0

--- |
  define dso_local void @gemm(ptr addrspace(5) noalias nocapture writeonly %d, ptr addrspace(6) noalias nocapture readonly %s, i32 noundef %n) local_unnamed_addr {
  ; CHECK-LABEL: gemm:
  ; CHECK:         .p2align 4
  ; CHECK-NEXT:  // %bb.0: // %entry
  ; CHECK-NEXT:    add.nc lc, r0, #0
  ; CHECK-NEXT:    movxm ls, #.LBB0_1
  ; CHECK-NEXT:    movxm le, #.L_LEnd0
  ; CHECK-NEXT:    .p2align 4
  ; CHECK-NEXT:  .LBB0_1: // %for.body
  ; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
  ; CHECK-NEXT:    nopa ; vldb.3d x2, [p6], d0; nopx ; mov p5, p6
  ; CHECK-NEXT:    padda [p5], m4; vldb x4, [p5, #64]
  ; CHECK-NEXT:    vldb x6, [p5], #64
  ; CHECK-NEXT:    vldb x8, [p5, #0]
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    mov p3, p7
  ; CHECK-NEXT:    vshuffle x10, x2, x4, r0
  ; CHECK-NEXT:    vlda.3d.conv.fp32.bf16 cml4, [p7], d1; vshuffle x11, x2, x4, r1
  ; CHECK-NEXT:    vlda.conv.fp32.bf16 cmh4, [p3, #64]; vshuffle x4, x6, x8, r0
  ; CHECK-NEXT:    vshuffle x5, x6, x8, r1
  ; CHECK-NEXT:    padda [p3], m5; vmul.f dm4, y5, y0, r2
  ; CHECK-NEXT:    vlda.conv.fp32.bf16 cml4, [p3], #64; vmul.f dm4, y2, y0, r2
  ; CHECK-NEXT:    vlda.conv.fp32.bf16 cmh4, [p3, #0]
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    vconv.bfp16ebs8.fp32 ex2, dm4
  ; CHECK-NEXT:    vconv.bfp16ebs8.fp32 ex6, dm4
  ; CHECK-NEXT:    vconv.bfp16ebs8.fp32 ex4, dm4
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    vconv.bfp16ebs8.fp32 ex8, dm4
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    vmac.f dm3, dm3, ex2, ex6, r3
  ; CHECK-NEXT:    vmac.f dm2, dm2, ex2, ex4, r3
  ; CHECK-NEXT:    vmac.f dm1, dm1, ex8, ex6, r3
  ; CHECK-NEXT:  .L_LEnd0:
  ; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; vmac.f dm0, dm0, ex8, ex4, r3
  ; CHECK-NEXT:    .p2align 4
  ; CHECK-NEXT:  // %bb.2:
  ; CHECK-NEXT:    nopa ; ret lr
  ; CHECK-NEXT:    nop // Delay Slot 5
  ; CHECK-NEXT:    nop // Delay Slot 4
  ; CHECK-NEXT:    nop // Delay Slot 3
  ; CHECK-NEXT:    nop // Delay Slot 2
  ; CHECK-NEXT:    nop // Delay Slot 1
  entry:
    %cmp5 = icmp sgt i32 %n, 0
    br i1 %cmp5, label %for.body.preheader, label %for.cond.cleanup

  for.body.preheader:                               ; preds = %entry
    call void @llvm.set.loop.iterations.i32(i32 %n)
    br label %for.body

  for.body:                                         ; preds = %for.body.preheader, %for.body
    %d.addr.07 = phi ptr addrspace(5) [ %incdec.ptr, %for.body ], [ %d, %for.body.preheader ]
    %s.addr.06 = phi ptr addrspace(6) [ %incdec.ptr1, %for.body ], [ %s, %for.body.preheader ]
    %0 = load i32, ptr addrspace(6) %s.addr.06, align 4
    %add = add nsw i32 %0, 1
    store i32 %add, ptr addrspace(5) %d.addr.07, align 4
    %incdec.ptr = getelementptr inbounds i32, ptr addrspace(5) %d.addr.07, i20 1
    %incdec.ptr1 = getelementptr inbounds i32, ptr addrspace(6) %s.addr.06, i20 1
    %1 = call i1 @llvm.loop.decrement.i32(i32 1)
    br i1 %1, label %for.body, label %for.cond.cleanup, !llvm.loop !0

  for.cond.cleanup:                                 ; preds = %for.body, %entry
    ret void

  }

  declare void @llvm.set.loop.iterations.i32(i32)
  declare i1 @llvm.loop.decrement.i32(i32)

  !0 = distinct !{!0, !1, !2}
  !1 = !{!"llvm.loop.mustprogress"}
  !2 = !{!"llvm.loop.itercount.range", i64 10}

...
---
name:            gemm
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry (align 16):
    successors: %bb.2
    liveins: $p0, $p1, $r0

    $lc = ADD_NC_mv_add_ri $r0, 0
    $ls = MOVXM %bb.2
    $le = MOVXM <mcsymbol .L_LEnd0>

  bb.2.for.body (align 16):
    successors: %bb.2, %bb.3
    liveins: $dc0, $dc1, $dc2, $dc3, $dc4, $dc5, $dj0, $dj1, $dj2, $dj3, $dj4, $dj5, $dj7, $dm0:0x000000001800000C, $dm1:0x000000001800000C, $dm2:0x000000001800000C, $dm3:0x000000001800000C, $dn0, $dn1, $dn2, $dn4, $dn5, $m0, $m1, $m2, $m3, $m4, $m5, $p0, $p1, $p2, $p4, $p6, $p7, $r0, $r1, $r2, $r3, $r4, $r8, $y0:0x0000000000000033, $d0_3d:0x0003C00000200E00, $d1_3d:0x0003C00000200E00, $dn3

    $p5 = MOV_alu_mv_mv_mv_scl $p6
    $x2, $p6, $dc0, $dc4 = VLD_3D_x_pseudo killed $p6, $d0_3d :: (load (<16 x s32>))
    renamable $x4 = VLD_x_idx_imm_pseudo renamable $p5, 64 :: (load (<16 x s32>))
    $p3 = MOV_alu_mv_mv_mv_scl $p7
    $cml4, $p7, $dc1, $dc5 = VLDA_3D_CONV_fp32_bf16_dmx_lda_ups_bf killed $p7, $d1_3d :: (load (<32 x s16>))
    renamable $cmh4 = VLDA_CONV_fp32_bf16_dmx_lda_ups_bf_idx_imm renamable $p3, 64 :: (load (<32 x s16>))
    renamable $p5 = PADD_mod_pseudo killed renamable $p5, renamable $m4
    renamable $x6, renamable $p5 = VLD_x_pstm_nrm_imm_pseudo killed renamable $p5, 64 :: (load (<16 x s32>))
    renamable $x8 = VLD_x_idx_imm_pseudo killed renamable $p5, 0 :: (load (<16 x s32>))
    renamable $x10 = VSHUFFLE_vec_shuffle_x renamable $x2, renamable $x4, renamable $r0
    renamable $x11 = VSHUFFLE_vec_shuffle_x killed renamable $x2, killed renamable $x4, renamable $r1
    renamable $ex2 = VCONV_bfp16ebs8_fp32 killed renamable $dm4, implicit-def $srf2bflags, implicit $crf2bmask, implicit $crrnd
    renamable $dm4 = VMUL_f_vmul_bf_vmul_bf_core_Y_Y killed renamable $y5, renamable $y0, renamable $r2, implicit-def dead $srfpflags, implicit $crfpmask
    renamable $x4 = VSHUFFLE_vec_shuffle_x renamable $x6, renamable $x8, renamable $r0
    renamable $x5 = VSHUFFLE_vec_shuffle_x killed renamable $x6, killed renamable $x8, renamable $r1
    renamable $ex6 = VCONV_bfp16ebs8_fp32 killed renamable $dm4, implicit-def $srf2bflags, implicit $crf2bmask, implicit $crrnd
    renamable $dm4 = VMUL_f_vmul_bf_vmul_bf_core_Y_Y killed renamable $y2, renamable $y0, renamable $r2, implicit-def dead $srfpflags, implicit $crfpmask
    renamable $p3 = PADD_mod_pseudo killed renamable $p3, renamable $m5
    renamable $ex4 = VCONV_bfp16ebs8_fp32 killed renamable $dm4, implicit-def $srf2bflags, implicit $crf2bmask, implicit $crrnd
    renamable $cml4, renamable $p3 = VLDA_CONV_fp32_bf16_dmx_lda_ups_bf_pstm_nrm_imm killed renamable $p3, 64 :: (load (<32 x s16>))
    renamable $cmh4 = VLDA_CONV_fp32_bf16_dmx_lda_ups_bf_idx_imm killed renamable $p3, 0 :: (load (<32 x s16>))
    renamable $ex8 = VCONV_bfp16ebs8_fp32 killed renamable $dm4, implicit-def $srf2bflags, implicit $crf2bmask, implicit $crrnd
    renamable $dm3 = VMAC_f_vmac_bfp_vmul_bfp_core_EX_EX killed renamable $dm3, renamable $ex2, renamable $ex6, renamable $r3, implicit-def dead $srfpflags, implicit $crfpmask
    renamable $dm2 = VMAC_f_vmac_bfp_vmul_bfp_core_EX_EX killed renamable $dm2, killed renamable $ex2, renamable $ex4, renamable $r3, implicit-def dead $srfpflags, implicit $crfpmask
    renamable $dm1 = VMAC_f_vmac_bfp_vmul_bfp_core_EX_EX killed renamable $dm1, renamable $ex8, killed renamable $ex6, renamable $r3, implicit-def dead $srfpflags, implicit $crfpmask,
    renamable $dm0 = VMAC_f_vmac_bfp_vmul_bfp_core_EX_EX killed renamable $dm0, killed renamable $ex8, killed renamable $ex4, renamable $r3, implicit-def dead $srfpflags, implicit $crfpmask

    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.2

  bb.3 (align 16):
    RET implicit $lr
    DelayedSchedBarrier

...
