// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
//===- aie2ps-acc-ops.cpp -------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//

// RUN: %clang %s --target=aie2ps -nostdlibinc -S -emit-llvm -o - | FileCheck %s

// CHECK-LABEL: define dso_local inreg noundef <16 x float> @_Z12test_acc_addDv16_u10__accfloatS_(
// CHECK-SAME: <16 x float> inreg noundef [[A:%.*]], <16 x float> inreg noundef [[B:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <16 x float>, align 64
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <16 x float>, align 64
// CHECK-NEXT:    store <16 x float> [[A]], ptr [[A_ADDR]], align 64
// CHECK-NEXT:    store <16 x float> [[B]], ptr [[B_ADDR]], align 64
// CHECK-NEXT:    [[TMP0:%.*]] = load <16 x float>, ptr [[A_ADDR]], align 64
// CHECK-NEXT:    [[TMP1:%.*]] = load <16 x float>, ptr [[B_ADDR]], align 64
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x float> [[TMP0]], <16 x float> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <16 x float> [[TMP1]], <16 x float> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[TMP4:%.*]] = call <32 x float> @llvm.aie2ps.ACC1024.accfloat.add.conf(<32 x float> [[TMP2]], <32 x float> [[TMP3]], i32 60)
// CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <32 x float> [[TMP4]], <32 x float> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x float> [[TMP5]]
//
v16accfloat test_acc_add(v16accfloat a, v16accfloat b) {
  return a + b;
}
// CHECK-LABEL: define dso_local inreg noundef <32 x float> @_Z12test_acc_addDv32_u10__accfloatS_(
// CHECK-SAME: <32 x float> inreg noundef [[A:%.*]], <32 x float> inreg noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <32 x float>, align 64
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <32 x float>, align 64
// CHECK-NEXT:    store <32 x float> [[A]], ptr [[A_ADDR]], align 64
// CHECK-NEXT:    store <32 x float> [[B]], ptr [[B_ADDR]], align 64
// CHECK-NEXT:    [[TMP0:%.*]] = load <32 x float>, ptr [[A_ADDR]], align 64
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x float>, ptr [[B_ADDR]], align 64
// CHECK-NEXT:    [[TMP2:%.*]] = call <32 x float> @llvm.aie2ps.ACC1024.accfloat.add.conf(<32 x float> [[TMP0]], <32 x float> [[TMP1]], i32 60)
// CHECK-NEXT:    ret <32 x float> [[TMP2]]
//
v32accfloat test_acc_add(v32accfloat a, v32accfloat b) {
  return a + b;
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z12test_acc_addDv64_u10__accfloatS_(
// CHECK-SAME: <64 x float> inreg noundef [[A:%.*]], <64 x float> inreg noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <64 x float>, align 64
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <64 x float>, align 64
// CHECK-NEXT:    store <64 x float> [[A]], ptr [[A_ADDR]], align 64
// CHECK-NEXT:    store <64 x float> [[B]], ptr [[B_ADDR]], align 64
// CHECK-NEXT:    [[TMP0:%.*]] = load <64 x float>, ptr [[A_ADDR]], align 64
// CHECK-NEXT:    [[TMP1:%.*]] = load <64 x float>, ptr [[B_ADDR]], align 64
// CHECK-NEXT:    [[TMP2:%.*]] = call <64 x float> @llvm.aie2ps.ACC2048.accfloat.add.conf(<64 x float> [[TMP0]], <64 x float> [[TMP1]], i32 60)
// CHECK-NEXT:    ret <64 x float> [[TMP2]]
//
v64accfloat test_acc_add(v64accfloat a, v64accfloat b) {
  return a + b;
}
// CHECK-LABEL: define dso_local inreg noundef <16 x float> @_Z19test_acc_add_assignDv16_u10__accfloatS_(
// CHECK-SAME: <16 x float> inreg noundef [[A:%.*]], <16 x float> inreg noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <16 x float>, align 64
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <16 x float>, align 64
// CHECK-NEXT:    store <16 x float> [[A]], ptr [[A_ADDR]], align 64
// CHECK-NEXT:    store <16 x float> [[B]], ptr [[B_ADDR]], align 64
// CHECK-NEXT:    [[TMP0:%.*]] = load <16 x float>, ptr [[B_ADDR]], align 64
// CHECK-NEXT:    [[TMP1:%.*]] = load <16 x float>, ptr [[A_ADDR]], align 64
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x float> [[TMP1]], <16 x float> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <16 x float> [[TMP0]], <16 x float> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[TMP4:%.*]] = call <32 x float> @llvm.aie2ps.ACC1024.accfloat.add.conf(<32 x float> [[TMP2]], <32 x float> [[TMP3]], i32 60)
// CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <32 x float> [[TMP4]], <32 x float> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    store <16 x float> [[TMP5]], ptr [[A_ADDR]], align 64
// CHECK-NEXT:    [[TMP6:%.*]] = load <16 x float>, ptr [[A_ADDR]], align 64
// CHECK-NEXT:    ret <16 x float> [[TMP6]]
//
v16accfloat test_acc_add_assign(v16accfloat a, v16accfloat b) {
  a += b;
  return a;
}
// CHECK-LABEL: define dso_local inreg noundef <32 x float> @_Z19test_acc_add_assignDv32_u10__accfloatS_(
// CHECK-SAME: <32 x float> inreg noundef [[A:%.*]], <32 x float> inreg noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <32 x float>, align 64
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <32 x float>, align 64
// CHECK-NEXT:    store <32 x float> [[A]], ptr [[A_ADDR]], align 64
// CHECK-NEXT:    store <32 x float> [[B]], ptr [[B_ADDR]], align 64
// CHECK-NEXT:    [[TMP0:%.*]] = load <32 x float>, ptr [[B_ADDR]], align 64
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x float>, ptr [[A_ADDR]], align 64
// CHECK-NEXT:    [[TMP2:%.*]] = call <32 x float> @llvm.aie2ps.ACC1024.accfloat.add.conf(<32 x float> [[TMP1]], <32 x float> [[TMP0]], i32 60)
// CHECK-NEXT:    store <32 x float> [[TMP2]], ptr [[A_ADDR]], align 64
// CHECK-NEXT:    [[TMP3:%.*]] = load <32 x float>, ptr [[A_ADDR]], align 64
// CHECK-NEXT:    ret <32 x float> [[TMP3]]
//
v32accfloat test_acc_add_assign(v32accfloat a, v32accfloat b) {
  a += b;
  return a;
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z19test_acc_add_assignDv64_u10__accfloatS_(
// CHECK-SAME: <64 x float> inreg noundef [[A:%.*]], <64 x float> inreg noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <64 x float>, align 64
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <64 x float>, align 64
// CHECK-NEXT:    store <64 x float> [[A]], ptr [[A_ADDR]], align 64
// CHECK-NEXT:    store <64 x float> [[B]], ptr [[B_ADDR]], align 64
// CHECK-NEXT:    [[TMP0:%.*]] = load <64 x float>, ptr [[B_ADDR]], align 64
// CHECK-NEXT:    [[TMP1:%.*]] = load <64 x float>, ptr [[A_ADDR]], align 64
// CHECK-NEXT:    [[TMP2:%.*]] = call <64 x float> @llvm.aie2ps.ACC2048.accfloat.add.conf(<64 x float> [[TMP1]], <64 x float> [[TMP0]], i32 60)
// CHECK-NEXT:    store <64 x float> [[TMP2]], ptr [[A_ADDR]], align 64
// CHECK-NEXT:    [[TMP3:%.*]] = load <64 x float>, ptr [[A_ADDR]], align 64
// CHECK-NEXT:    ret <64 x float> [[TMP3]]
//
v64accfloat test_acc_add_assign(v64accfloat a, v64accfloat b) {
  a += b;
  return a;
}
// CHECK-LABEL: define dso_local inreg noundef <16 x float> @_Z12test_acc_subDv16_u10__accfloatS_(
// CHECK-SAME: <16 x float> inreg noundef [[A:%.*]], <16 x float> inreg noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <16 x float>, align 64
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <16 x float>, align 64
// CHECK-NEXT:    store <16 x float> [[A]], ptr [[A_ADDR]], align 64
// CHECK-NEXT:    store <16 x float> [[B]], ptr [[B_ADDR]], align 64
// CHECK-NEXT:    [[TMP0:%.*]] = load <16 x float>, ptr [[A_ADDR]], align 64
// CHECK-NEXT:    [[TMP1:%.*]] = load <16 x float>, ptr [[B_ADDR]], align 64
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x float> [[TMP0]], <16 x float> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <16 x float> [[TMP1]], <16 x float> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[TMP4:%.*]] = call <32 x float> @llvm.aie2ps.ACC1024.accfloat.sub.conf(<32 x float> [[TMP2]], <32 x float> [[TMP3]], i32 60)
// CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <32 x float> [[TMP4]], <32 x float> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x float> [[TMP5]]
//
v16accfloat test_acc_sub(v16accfloat a, v16accfloat b) {
  return a - b;
}

// CHECK-LABEL: define dso_local inreg noundef <32 x float> @_Z12test_acc_subDv32_u10__accfloatS_(
// CHECK-SAME: <32 x float> inreg noundef [[A:%.*]], <32 x float> inreg noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <32 x float>, align 64
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <32 x float>, align 64
// CHECK-NEXT:    store <32 x float> [[A]], ptr [[A_ADDR]], align 64
// CHECK-NEXT:    store <32 x float> [[B]], ptr [[B_ADDR]], align 64
// CHECK-NEXT:    [[TMP0:%.*]] = load <32 x float>, ptr [[A_ADDR]], align 64
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x float>, ptr [[B_ADDR]], align 64
// CHECK-NEXT:    [[TMP2:%.*]] = call <32 x float> @llvm.aie2ps.ACC1024.accfloat.sub.conf(<32 x float> [[TMP0]], <32 x float> [[TMP1]], i32 60)
// CHECK-NEXT:    ret <32 x float> [[TMP2]]
//
v32accfloat test_acc_sub(v32accfloat a, v32accfloat b) {
  return a - b;
}

// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z12test_acc_subDv64_u10__accfloatS_(
// CHECK-SAME: <64 x float> inreg noundef [[A:%.*]], <64 x float> inreg noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <64 x float>, align 64
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <64 x float>, align 64
// CHECK-NEXT:    store <64 x float> [[A]], ptr [[A_ADDR]], align 64
// CHECK-NEXT:    store <64 x float> [[B]], ptr [[B_ADDR]], align 64
// CHECK-NEXT:    [[TMP0:%.*]] = load <64 x float>, ptr [[A_ADDR]], align 64
// CHECK-NEXT:    [[TMP1:%.*]] = load <64 x float>, ptr [[B_ADDR]], align 64
// CHECK-NEXT:    [[TMP2:%.*]] = call <64 x float> @llvm.aie2ps.ACC2048.accfloat.sub.conf(<64 x float> [[TMP0]], <64 x float> [[TMP1]], i32 60)
// CHECK-NEXT:    ret <64 x float> [[TMP2]]
//
v64accfloat test_acc_sub(v64accfloat a, v64accfloat b) {
  return a - b;
}
// CHECK-LABEL: define dso_local inreg noundef <16 x float> @_Z19test_acc_sub_assignDv16_u10__accfloatS_(
// CHECK-SAME: <16 x float> inreg noundef [[A:%.*]], <16 x float> inreg noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <16 x float>, align 64
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <16 x float>, align 64
// CHECK-NEXT:    store <16 x float> [[A]], ptr [[A_ADDR]], align 64
// CHECK-NEXT:    store <16 x float> [[B]], ptr [[B_ADDR]], align 64
// CHECK-NEXT:    [[TMP0:%.*]] = load <16 x float>, ptr [[B_ADDR]], align 64
// CHECK-NEXT:    [[TMP1:%.*]] = load <16 x float>, ptr [[A_ADDR]], align 64
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x float> [[TMP1]], <16 x float> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <16 x float> [[TMP0]], <16 x float> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[TMP4:%.*]] = call <32 x float> @llvm.aie2ps.ACC1024.accfloat.sub.conf(<32 x float> [[TMP2]], <32 x float> [[TMP3]], i32 60)
// CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <32 x float> [[TMP4]], <32 x float> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    store <16 x float> [[TMP5]], ptr [[A_ADDR]], align 64
// CHECK-NEXT:    [[TMP6:%.*]] = load <16 x float>, ptr [[A_ADDR]], align 64
// CHECK-NEXT:    ret <16 x float> [[TMP6]]
//
v16accfloat test_acc_sub_assign(v16accfloat a, v16accfloat b) {
  a -= b;
  return a;
}
// CHECK-LABEL: define dso_local inreg noundef <32 x float> @_Z19test_acc_sub_assignDv32_u10__accfloatS_(
// CHECK-SAME: <32 x float> inreg noundef [[A:%.*]], <32 x float> inreg noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <32 x float>, align 64
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <32 x float>, align 64
// CHECK-NEXT:    store <32 x float> [[A]], ptr [[A_ADDR]], align 64
// CHECK-NEXT:    store <32 x float> [[B]], ptr [[B_ADDR]], align 64
// CHECK-NEXT:    [[TMP0:%.*]] = load <32 x float>, ptr [[B_ADDR]], align 64
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x float>, ptr [[A_ADDR]], align 64
// CHECK-NEXT:    [[TMP2:%.*]] = call <32 x float> @llvm.aie2ps.ACC1024.accfloat.sub.conf(<32 x float> [[TMP1]], <32 x float> [[TMP0]], i32 60)
// CHECK-NEXT:    store <32 x float> [[TMP2]], ptr [[A_ADDR]], align 64
// CHECK-NEXT:    [[TMP3:%.*]] = load <32 x float>, ptr [[A_ADDR]], align 64
// CHECK-NEXT:    ret <32 x float> [[TMP3]]
//
v32accfloat test_acc_sub_assign(v32accfloat a, v32accfloat b) {
  a -= b;
  return a;
}
// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z19test_acc_sub_assignDv64_u10__accfloatS_(
// CHECK-SAME: <64 x float> inreg noundef [[A:%.*]], <64 x float> inreg noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <64 x float>, align 64
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <64 x float>, align 64
// CHECK-NEXT:    store <64 x float> [[A]], ptr [[A_ADDR]], align 64
// CHECK-NEXT:    store <64 x float> [[B]], ptr [[B_ADDR]], align 64
// CHECK-NEXT:    [[TMP0:%.*]] = load <64 x float>, ptr [[B_ADDR]], align 64
// CHECK-NEXT:    [[TMP1:%.*]] = load <64 x float>, ptr [[A_ADDR]], align 64
// CHECK-NEXT:    [[TMP2:%.*]] = call <64 x float> @llvm.aie2ps.ACC2048.accfloat.sub.conf(<64 x float> [[TMP1]], <64 x float> [[TMP0]], i32 60)
// CHECK-NEXT:    store <64 x float> [[TMP2]], ptr [[A_ADDR]], align 64
// CHECK-NEXT:    [[TMP3:%.*]] = load <64 x float>, ptr [[A_ADDR]], align 64
// CHECK-NEXT:    ret <64 x float> [[TMP3]]
//
v64accfloat test_acc_sub_assign(v64accfloat a, v64accfloat b) {
  a -= b;
  return a;
}
