// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
//===- aie2ps-ups-intrinsics.cpp --------------------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//
// RUN: %clang -O2 %s --target=aie2ps -nostdlibinc -S -emit-llvm -o - | FileCheck %s

// CHECK-LABEL: @_Z19test_to_v16accfloatDv16_8bfloat16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x float> @llvm.aie2ps.v16bf16.to.v16accfloat(<16 x bfloat> [[A:%.*]])
// CHECK-NEXT:    ret <16 x float> [[TMP0]]
//
v16accfloat test_to_v16accfloat(v16bfloat16 a) {
   return to_v16accfloat(a);
}

// CHECK-LABEL: @_Z31test_to_v16accfloat_v16bfloat16Dv16_8bfloat16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x float> @llvm.aie2ps.v16bf16.to.v16accfloat(<16 x bfloat> [[A:%.*]])
// CHECK-NEXT:    ret <16 x float> [[TMP0]]
//
v16accfloat test_to_v16accfloat_v16bfloat16(v16bfloat16 a) {
  return to_v16accfloat(a);
}

// CHECK-LABEL: @_Z31test_to_v32accfloat_v32bfloat16Dv32_8bfloat16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x float> @llvm.aie2ps.v32bf16.to.v32accfloat(<32 x bfloat> [[A:%.*]])
// CHECK-NEXT:    ret <32 x float> [[TMP0]]
//
v32accfloat test_to_v32accfloat_v32bfloat16(v32bfloat16 a) {
  return to_v32accfloat(a);
}

// CHECK-LABEL: @_Z29test_ups_to_v64acc32_wit_signDv64_aii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i32> @llvm.aie2ps.acc32.v64.I512.ups(<64 x i8> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <64 x i32> [[TMP0]]
//
v64acc32 test_ups_to_v64acc32_wit_sign(v64int8 a, int shft, int sign) {
  return to_v64acc32(a, shft, sign);
}

// CHECK-LABEL: @_Z34test_ups_to_v64acc32_wit_sign_confDv64_aiii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[CONV2_I:%.*]] = and i32 [[SAT:%.*]], 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV2_I]])
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef <64 x i32> @llvm.aie2ps.acc32.v64.I512.ups(<64 x i8> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    [[CONV5_I:%.*]] = and i32 [[TMP0]], 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV5_I]])
// CHECK-NEXT:    ret <64 x i32> [[TMP1]]
//
v64acc32 test_ups_to_v64acc32_wit_sign_conf(v64int8 a, int shft, int sign, int sat) {
  return to_v64acc32_conf(a, shft, sign, sat);
}
// CHECK-LABEL: @_Z28test_ups_to_v64acc32_no_signDv64_ai(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <64 x i32> @llvm.aie2ps.acc32.v64.I512.ups(<64 x i8> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    ret <64 x i32> [[TMP0]]
//
v64acc32 test_ups_to_v64acc32_no_sign(v64int8 a, int shft) {
  return to_v64acc32(a, shft);
}

// CHECK-LABEL: @_Z33test_ups_to_v64acc32_no_sign_confDv64_aii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[CONV2_I:%.*]] = and i32 [[SAT:%.*]], 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV2_I]])
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef <64 x i32> @llvm.aie2ps.acc32.v64.I512.ups(<64 x i8> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    [[CONV5_I:%.*]] = and i32 [[TMP0]], 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV5_I]])
// CHECK-NEXT:    ret <64 x i32> [[TMP1]]
//
v64acc32 test_ups_to_v64acc32_no_sign_conf(v64int8 a, int shft, int sat) {
  return to_v64acc32_conf(a, shft, sat);
}

// CHECK-LABEL: @_Z30test_ups_to_v32acc64_with_signDv32_sii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i64> @llvm.aie2ps.acc64.v32.I512.ups(<32 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <32 x i64> [[TMP0]]
//
v32acc64 test_ups_to_v32acc64_with_sign(v32int16 a, int shft, int sign) {
  return to_v32acc64(a, shft, sign);
}

// CHECK-LABEL: @_Z28test_ups_to_v32acc64_no_signDv32_si(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i64> @llvm.aie2ps.acc64.v32.I512.ups(<32 x i16> [[A:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    ret <32 x i64> [[TMP0]]
//
v32acc64 test_ups_to_v32acc64_no_sign(v32int16 a, int shft) {
  return to_v32acc64(a, shft, __SIGN_SIGNED);
}


// CHECK-LABEL: @_Z23test_ups_to_v16accfloatDv16_DF16_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x float> @llvm.aie2ps.v16float16.to.v16accfloat(<16 x half> [[A:%.*]])
// CHECK-NEXT:    ret <16 x float> [[TMP0]]
//
v16accfloat test_ups_to_v16accfloat(v16float16 a) {
  return to_v16accfloat(a);
}

// CHECK-LABEL: @_Z23test_ups_to_v32accfloatDv32_DF16_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x float> @llvm.aie2ps.v32float16.to.v32accfloat(<32 x half> [[A:%.*]])
// CHECK-NEXT:    ret <32 x float> [[TMP0]]
//
v32accfloat test_ups_to_v32accfloat(v32float16 a) {
  return to_v32accfloat(a);
}

// CHECK-LABEL: @_Z8test_upsDv16_DF16_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x float> @llvm.aie2ps.v16float16.to.v16accfloat(<16 x half> [[A:%.*]])
// CHECK-NEXT:    ret <16 x float> [[TMP0]]
//
v16accfloat test_ups(v16float16 a) {
  return ups(a);
}

// CHECK-LABEL: @_Z8test_upsDv32_DF16_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x float> @llvm.aie2ps.v32float16.to.v32accfloat(<32 x half> [[A:%.*]])
// CHECK-NEXT:    ret <32 x float> [[TMP0]]
//
v32accfloat test_ups(v32float16 a) {
  return ups(a);
}
