// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//
// RUN: %clang -O2 %s --target=aie2ps -nostdlibinc -S -emit-llvm -o - | FileCheck %s


// CHECK-LABEL: @_Z23test_extract_v16float16Dv32_7float16i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x half> [[A:%.*]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i32> [[COND_I_I]] to <16 x half>
// CHECK-NEXT:    ret <16 x half> [[TMP1]]
//
v16float16 test_extract_v16float16 (v32float16 a, int idx) { return extract_v16float16(a, idx); }
// CHECK-LABEL: @_Z11test_insertDv32_7float16iDv16_S_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x half> [[A:%.*]] to <16 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x half> [[B:%.*]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[COND_I_I]] to <32 x half>
// CHECK-NEXT:    ret <32 x half> [[TMP2]]
//
v32float16 test_insert (v32float16 a, int idx, v16float16 b) { return insert(a, idx, b); }
// CHECK-LABEL: @_Z19test_set_v32float16iDv16_7float16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x half> [[B:%.*]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[COND_I_I]] to <32 x half>
// CHECK-NEXT:    ret <32 x half> [[TMP1]]
//
v32float16 test_set_v32float16 (int idx, v16float16 b) { return set_v32float16(idx, b); }
// CHECK-LABEL: @_Z11test_concatDv16_7float16S0_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x half> [[A0:%.*]] to <8 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x half> [[A1:%.*]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> [[TMP1]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[SHUFFLE_I_I]] to <32 x half>
// CHECK-NEXT:    ret <32 x half> [[TMP2]]
//
v32float16 test_concat (v16float16 a0, v16float16 a1) { return concat(a0, a1); }
// CHECK-LABEL: @_Z23test_extract_v32bfloat810v64bfloat8i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <64 x i8> [[TMP0]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i32> [[COND_I_I]] to <32 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V32BFLOAT8:%.*]] poison, <32 x i8> [[TMP2]], 0
// CHECK-NEXT:    ret [[STRUCT_V32BFLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v32bfloat8 test_extract_v32bfloat8 (v64bfloat8 a, int idx) { return extract_v32bfloat8(a, idx); }
// CHECK-LABEL: @_Z11test_insert10v64bfloat8i10v32bfloat8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V32BFLOAT8:%.*]] [[B_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <64 x i8> [[TMP0]] to <16 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <32 x i8> [[TMP1]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP3]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[TMP2]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[TMP2]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <16 x i32> [[COND_I_I]] to <64 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFLOAT8]] poison, <64 x i8> [[TMP4]], 0
// CHECK-NEXT:    ret [[STRUCT_V64BFLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v64bfloat8 test_insert (v64bfloat8 a, int idx, v32bfloat8 b) { return insert(a, idx, b); }
// CHECK-LABEL: @_Z19test_set_v64bfloat8i10v32bfloat8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V32BFLOAT8:%.*]] [[B_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i8> [[TMP0]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[COND_I_I]] to <64 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFLOAT8:%.*]] poison, <64 x i8> [[TMP2]], 0
// CHECK-NEXT:    ret [[STRUCT_V64BFLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v64bfloat8 test_set_v64bfloat8 (int idx, v32bfloat8 b) { return set_v64bfloat8(idx, b); }
// CHECK-LABEL: @_Z11test_concat10v32bfloat8S_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V32BFLOAT8:%.*]] [[A0_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V32BFLOAT8]] [[A1_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i8> [[TMP0]] to <8 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <32 x i8> [[TMP1]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP2]], <8 x i32> [[TMP3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <16 x i32> [[SHUFFLE_I_I]] to <64 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFLOAT8:%.*]] poison, <64 x i8> [[TMP4]], 0
// CHECK-NEXT:    ret [[STRUCT_V64BFLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v64bfloat8 test_concat (v32bfloat8 a0, v32bfloat8 a1) { return concat(a0, a1); }
// CHECK-LABEL: @_Z22test_extract_v32float89v64float8i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64FLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <64 x i8> [[TMP0]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i32> [[COND_I_I]] to <32 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V32FLOAT8:%.*]] poison, <32 x i8> [[TMP2]], 0
// CHECK-NEXT:    ret [[STRUCT_V32FLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v32float8 test_extract_v32float8 (v64float8 a, int idx) { return extract_v32float8(a, idx); }
// CHECK-LABEL: @_Z11test_insert9v64float8i9v32float8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64FLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V32FLOAT8:%.*]] [[B_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <64 x i8> [[TMP0]] to <16 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <32 x i8> [[TMP1]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP3]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[TMP2]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[TMP2]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <16 x i32> [[COND_I_I]] to <64 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64FLOAT8]] poison, <64 x i8> [[TMP4]], 0
// CHECK-NEXT:    ret [[STRUCT_V64FLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v64float8 test_insert (v64float8 a, int idx, v32float8 b) { return insert(a, idx, b); }
// CHECK-LABEL: @_Z18test_set_v64float8i9v32float8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V32FLOAT8:%.*]] [[B_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i8> [[TMP0]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[COND_I_I]] to <64 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64FLOAT8:%.*]] poison, <64 x i8> [[TMP2]], 0
// CHECK-NEXT:    ret [[STRUCT_V64FLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v64float8 test_set_v64float8 (int idx, v32float8 b) { return set_v64float8(idx, b); }
// CHECK-LABEL: @_Z11test_concat9v32float8S_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V32FLOAT8:%.*]] [[A0_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V32FLOAT8]] [[A1_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i8> [[TMP0]] to <8 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <32 x i8> [[TMP1]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP2]], <8 x i32> [[TMP3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <16 x i32> [[SHUFFLE_I_I]] to <64 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64FLOAT8:%.*]] poison, <64 x i8> [[TMP4]], 0
// CHECK-NEXT:    ret [[STRUCT_V64FLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v64float8 test_concat (v32float8 a0, v32float8 a1) { return concat(a0, a1); }
// CHECK-LABEL: @_Z23test_extract_v16float16Dv64_7float16i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x half> [[A:%.*]] to <32 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[COND9_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE2_I_I]], <8 x i32> [[SHUFFLE3_I_I]]
// CHECK-NEXT:    [[AND10_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I:%.*]] = icmp eq i32 [[AND10_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I]], <8 x i32> [[COND_I_I]], <8 x i32> [[COND9_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i32> [[COND15_I_I]] to <16 x half>
// CHECK-NEXT:    ret <16 x half> [[TMP1]]
//
v16float16 test_extract_v16float16 (v64float16 a, int idx) { return extract_v16float16(a, idx); }
// CHECK-LABEL: @_Z11test_insertDv64_7float16iDv16_S_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x half> [[A:%.*]] to <32 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x half> [[B:%.*]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE2_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE7_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE3_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE5_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE1_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE4_I_I:%.*]] = shufflevector <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[TMP0]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE4_I_I]], <32 x i32> [[SHUFFLE5_I_I]]
// CHECK-NEXT:    [[COND13_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE6_I_I]], <32 x i32> [[SHUFFLE7_I_I]]
// CHECK-NEXT:    [[AND14_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL15_NOT_I_I:%.*]] = icmp eq i32 [[AND14_I_I]], 0
// CHECK-NEXT:    [[COND19_I_I:%.*]] = select i1 [[TOBOOL15_NOT_I_I]], <32 x i32> [[COND_I_I]], <32 x i32> [[COND13_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[COND19_I_I]] to <64 x half>
// CHECK-NEXT:    ret <64 x half> [[TMP2]]
//
v64float16 test_insert (v64float16 a, int idx, v16float16 b) { return insert(a, idx, b); }
// CHECK-LABEL: @_Z19test_set_v64float16iDv16_7float16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x half> [[B:%.*]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[COND9_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE2_I_I]], <32 x i32> [[SHUFFLE3_I_I]]
// CHECK-NEXT:    [[AND10_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I:%.*]] = icmp eq i32 [[AND10_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I]], <32 x i32> [[COND_I_I]], <32 x i32> [[COND9_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i32> [[COND15_I_I]] to <64 x half>
// CHECK-NEXT:    ret <64 x half> [[TMP1]]
//
v64float16 test_set_v64float16 (int idx, v16float16 b) { return set_v64float16(idx, b); }
// CHECK-LABEL: @_Z11test_concatDv16_7float16S0_S0_S0_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x half> [[A0:%.*]] to <8 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x half> [[A1:%.*]] to <8 x i32>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x half> [[A2:%.*]] to <8 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <16 x half> [[A3:%.*]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> [[TMP1]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP2]], <8 x i32> [[TMP3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I]] to <64 x half>
// CHECK-NEXT:    ret <64 x half> [[TMP4]]
//
v64float16 test_concat (v16float16 a0, v16float16 a1, v16float16 a2, v16float16 a3) { return concat(a0, a1, a2, a3); }
// CHECK-LABEL: @_Z23test_extract_v32float16Dv64_7float16i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x half> [[A:%.*]] to <32 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[COND_I_I]] to <32 x half>
// CHECK-NEXT:    ret <32 x half> [[TMP1]]
//
v32float16 test_extract_v32float16 (v64float16 a, int idx) { return extract_v32float16(a, idx); }
// CHECK-LABEL: @_Z11test_insertDv64_7float16iDv32_S_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x half> [[A:%.*]] to <32 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x half> [[B:%.*]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[TMP0]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE1_I_I]], <32 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[COND_I_I]] to <64 x half>
// CHECK-NEXT:    ret <64 x half> [[TMP2]]
//
v64float16 test_insert (v64float16 a, int idx, v32float16 b) { return insert(a, idx, b); }
// CHECK-LABEL: @_Z19test_set_v64float16iDv32_7float16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x half> [[B:%.*]] to <16 x i32>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i32> [[COND_I_I]] to <64 x half>
// CHECK-NEXT:    ret <64 x half> [[TMP1]]
//
v64float16 test_set_v64float16 (int idx, v32float16 b) { return set_v64float16(idx, b); }
// CHECK-LABEL: @_Z11test_concatDv32_7float16S0_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x half> [[A0:%.*]] to <16 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x half> [[A1:%.*]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE_I_I]] to <64 x half>
// CHECK-NEXT:    ret <64 x half> [[TMP2]]
//
v64float16 test_concat (v32float16 a0, v32float16 a1) { return concat(a0, a1); }

// CHECK-LABEL: @_Z23test_extract_v32bfloat811v128bfloat8i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V128BFLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <128 x i8> [[TMP0]] to <32 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <32 x i32> [[TMP1]], <32 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[TMP1]], <32 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <32 x i32> [[TMP1]], <32 x i32> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <32 x i32> [[TMP1]], <32 x i32> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[COND9_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE2_I_I]], <8 x i32> [[SHUFFLE3_I_I]]
// CHECK-NEXT:    [[AND10_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I:%.*]] = icmp eq i32 [[AND10_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I]], <8 x i32> [[COND_I_I]], <8 x i32> [[COND9_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i32> [[COND15_I_I]] to <32 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V32BFLOAT8:%.*]] poison, <32 x i8> [[TMP2]], 0
// CHECK-NEXT:    ret [[STRUCT_V32BFLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v32bfloat8 test_extract_v32bfloat8 (v128bfloat8 a, int idx) { return extract_v32bfloat8(a, idx); }
// CHECK-LABEL: @_Z11test_insert11v128bfloat8i10v32bfloat8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V128BFLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V32BFLOAT8:%.*]] [[B_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <128 x i8> [[TMP0]] to <32 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <32 x i8> [[TMP1]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[TMP3]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <8 x i32> [[TMP3]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <32 x i32> [[TMP2]], <32 x i32> [[SHUFFLE2_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE7_I_I:%.*]] = shufflevector <32 x i32> [[TMP2]], <32 x i32> [[SHUFFLE3_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP3]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE5_I_I:%.*]] = shufflevector <32 x i32> [[TMP2]], <32 x i32> [[SHUFFLE1_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP3]], <8 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE4_I_I:%.*]] = shufflevector <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[TMP2]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE4_I_I]], <32 x i32> [[SHUFFLE5_I_I]]
// CHECK-NEXT:    [[COND13_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE6_I_I]], <32 x i32> [[SHUFFLE7_I_I]]
// CHECK-NEXT:    [[AND14_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL15_NOT_I_I:%.*]] = icmp eq i32 [[AND14_I_I]], 0
// CHECK-NEXT:    [[COND19_I_I:%.*]] = select i1 [[TOBOOL15_NOT_I_I]], <32 x i32> [[COND_I_I]], <32 x i32> [[COND13_I_I]]
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <32 x i32> [[COND19_I_I]] to <128 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V128BFLOAT8]] poison, <128 x i8> [[TMP4]], 0
// CHECK-NEXT:    ret [[STRUCT_V128BFLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v128bfloat8 test_insert (v128bfloat8 a, int idx, v32bfloat8 b) { return insert(a, idx, b); }
// CHECK-LABEL: @_Z20test_set_v128bfloat8i10v32bfloat8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V32BFLOAT8:%.*]] [[B_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i8> [[TMP0]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[COND9_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE2_I_I]], <32 x i32> [[SHUFFLE3_I_I]]
// CHECK-NEXT:    [[AND10_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I:%.*]] = icmp eq i32 [[AND10_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I]], <32 x i32> [[COND_I_I]], <32 x i32> [[COND9_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[COND15_I_I]] to <128 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V128BFLOAT8:%.*]] poison, <128 x i8> [[TMP2]], 0
// CHECK-NEXT:    ret [[STRUCT_V128BFLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v128bfloat8 test_set_v128bfloat8 (int idx, v32bfloat8 b) { return set_v128bfloat8(idx, b); }
// CHECK-LABEL: @_Z11test_concat10v32bfloat8S_S_S_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V32BFLOAT8:%.*]] [[A0_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V32BFLOAT8]] [[A1_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V32BFLOAT8]] [[A2_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V32BFLOAT8]] [[A3_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <32 x i8> [[TMP0]] to <8 x i32>
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <32 x i8> [[TMP1]] to <8 x i32>
// CHECK-NEXT:    [[TMP6:%.*]] = bitcast <32 x i8> [[TMP2]] to <8 x i32>
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <32 x i8> [[TMP3]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP4]], <8 x i32> [[TMP5]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP6]], <8 x i32> [[TMP7]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP8:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I]] to <128 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V128BFLOAT8:%.*]] poison, <128 x i8> [[TMP8]], 0
// CHECK-NEXT:    ret [[STRUCT_V128BFLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v128bfloat8 test_concat (v32bfloat8 a0, v32bfloat8 a1, v32bfloat8 a2, v32bfloat8 a3) { return concat(a0, a1, a2, a3); }
// CHECK-LABEL: @_Z23test_extract_v64bfloat811v128bfloat8i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V128BFLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <128 x i8> [[TMP0]] to <32 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <32 x i32> [[TMP1]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[TMP1]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[COND_I_I]] to <64 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFLOAT8:%.*]] poison, <64 x i8> [[TMP2]], 0
// CHECK-NEXT:    ret [[STRUCT_V64BFLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v64bfloat8 test_extract_v64bfloat8 (v128bfloat8 a, int idx) { return extract_v64bfloat8(a, idx); }
//
// CHECK-LABEL: @_Z11test_insert11v128bfloat8i10v64bfloat8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V128BFLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFLOAT8:%.*]] [[B_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <128 x i8> [[TMP0]] to <32 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <64 x i8> [[TMP1]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP3]], <16 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <32 x i32> [[TMP2]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[TMP2]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE1_I_I]], <32 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <32 x i32> [[COND_I_I]] to <128 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V128BFLOAT8]] poison, <128 x i8> [[TMP4]], 0
// CHECK-NEXT:    ret [[STRUCT_V128BFLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v128bfloat8 test_insert (v128bfloat8 a, int idx, v64bfloat8 b) { return insert(a, idx, b); }
// CHECK-LABEL: @_Z20test_set_v128bfloat8i10v64bfloat8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFLOAT8:%.*]] [[B_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <64 x i8> [[TMP0]] to <16 x i32>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[COND_I_I]] to <128 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V128BFLOAT8:%.*]] poison, <128 x i8> [[TMP2]], 0
// CHECK-NEXT:    ret [[STRUCT_V128BFLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v128bfloat8 test_set_v128bfloat8 (int idx, v64bfloat8 b) { return set_v128bfloat8(idx, b); }
//
// CHECK-LABEL: @_Z11test_concat10v64bfloat8S_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFLOAT8:%.*]] [[A0_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFLOAT8]] [[A1_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <64 x i8> [[TMP0]] to <16 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <64 x i8> [[TMP1]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP2]], <16 x i32> [[TMP3]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <32 x i32> [[SHUFFLE_I_I]] to <128 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V128BFLOAT8:%.*]] poison, <128 x i8> [[TMP4]], 0
// CHECK-NEXT:    ret [[STRUCT_V128BFLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v128bfloat8 test_concat (v64bfloat8 a0, v64bfloat8 a1) { return concat(a0, a1); }
// CHECK-LABEL: @_Z22test_extract_v32float810v128float8i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V128FLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <128 x i8> [[TMP0]] to <32 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <32 x i32> [[TMP1]], <32 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[TMP1]], <32 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <32 x i32> [[TMP1]], <32 x i32> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <32 x i32> [[TMP1]], <32 x i32> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[COND9_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE2_I_I]], <8 x i32> [[SHUFFLE3_I_I]]
// CHECK-NEXT:    [[AND10_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I:%.*]] = icmp eq i32 [[AND10_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I]], <8 x i32> [[COND_I_I]], <8 x i32> [[COND9_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i32> [[COND15_I_I]] to <32 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V32FLOAT8:%.*]] poison, <32 x i8> [[TMP2]], 0
// CHECK-NEXT:    ret [[STRUCT_V32FLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v32float8 test_extract_v32float8 (v128float8 a, int idx) { return extract_v32float8(a, idx); }
// CHECK-LABEL: @_Z11test_insert10v128float8i9v32float8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V128FLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V32FLOAT8:%.*]] [[B_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <128 x i8> [[TMP0]] to <32 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <32 x i8> [[TMP1]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[TMP3]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <8 x i32> [[TMP3]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <32 x i32> [[TMP2]], <32 x i32> [[SHUFFLE2_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE7_I_I:%.*]] = shufflevector <32 x i32> [[TMP2]], <32 x i32> [[SHUFFLE3_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP3]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE5_I_I:%.*]] = shufflevector <32 x i32> [[TMP2]], <32 x i32> [[SHUFFLE1_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP3]], <8 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE4_I_I:%.*]] = shufflevector <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[TMP2]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE4_I_I]], <32 x i32> [[SHUFFLE5_I_I]]
// CHECK-NEXT:    [[COND13_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE6_I_I]], <32 x i32> [[SHUFFLE7_I_I]]
// CHECK-NEXT:    [[AND14_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL15_NOT_I_I:%.*]] = icmp eq i32 [[AND14_I_I]], 0
// CHECK-NEXT:    [[COND19_I_I:%.*]] = select i1 [[TOBOOL15_NOT_I_I]], <32 x i32> [[COND_I_I]], <32 x i32> [[COND13_I_I]]
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <32 x i32> [[COND19_I_I]] to <128 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V128FLOAT8]] poison, <128 x i8> [[TMP4]], 0
// CHECK-NEXT:    ret [[STRUCT_V128FLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v128float8 test_insert (v128float8 a, int idx, v32float8 b) { return insert(a, idx, b); }
// CHECK-LABEL: @_Z19test_set_v128float8i9v32float8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V32FLOAT8:%.*]] [[B_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i8> [[TMP0]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE3_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[COND9_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE2_I_I]], <32 x i32> [[SHUFFLE3_I_I]]
// CHECK-NEXT:    [[AND10_I_I:%.*]] = and i32 [[IDX]], 2
// CHECK-NEXT:    [[TOBOOL11_NOT_I_I:%.*]] = icmp eq i32 [[AND10_I_I]], 0
// CHECK-NEXT:    [[COND15_I_I:%.*]] = select i1 [[TOBOOL11_NOT_I_I]], <32 x i32> [[COND_I_I]], <32 x i32> [[COND9_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[COND15_I_I]] to <128 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V128FLOAT8:%.*]] poison, <128 x i8> [[TMP2]], 0
// CHECK-NEXT:    ret [[STRUCT_V128FLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v128float8 test_set_v128float8 (int idx, v32float8 b) { return set_v128float8(idx, b); }
// CHECK-LABEL: @_Z11test_concat9v32float8S_S_S_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V32FLOAT8:%.*]] [[A0_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V32FLOAT8]] [[A1_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V32FLOAT8]] [[A2_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V32FLOAT8]] [[A3_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <32 x i8> [[TMP0]] to <8 x i32>
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <32 x i8> [[TMP1]] to <8 x i32>
// CHECK-NEXT:    [[TMP6:%.*]] = bitcast <32 x i8> [[TMP2]] to <8 x i32>
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <32 x i8> [[TMP3]] to <8 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP4]], <8 x i32> [[TMP5]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP6]], <8 x i32> [[TMP7]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP8:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I]] to <128 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V128FLOAT8:%.*]] poison, <128 x i8> [[TMP8]], 0
// CHECK-NEXT:    ret [[STRUCT_V128FLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v128float8 test_concat (v32float8 a0, v32float8 a1, v32float8 a2, v32float8 a3) { return concat(a0, a1, a2, a3); }
// CHECK-LABEL: @_Z22test_extract_v64float810v128float8i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V128FLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <128 x i8> [[TMP0]] to <32 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <32 x i32> [[TMP1]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[TMP1]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <16 x i32> [[SHUFFLE_I_I]], <16 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[COND_I_I]] to <64 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64FLOAT8:%.*]] poison, <64 x i8> [[TMP2]], 0
// CHECK-NEXT:    ret [[STRUCT_V64FLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v64float8 test_extract_v64float8 (v128float8 a, int idx) { return extract_v64float8(a, idx); }
// CHECK-LABEL: @_Z11test_insert10v128float8i9v64float8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V128FLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64FLOAT8:%.*]] [[B_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <128 x i8> [[TMP0]] to <32 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <64 x i8> [[TMP1]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP3]], <16 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <32 x i32> [[TMP2]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[TMP2]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE1_I_I]], <32 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <32 x i32> [[COND_I_I]] to <128 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V128FLOAT8]] poison, <128 x i8> [[TMP4]], 0
// CHECK-NEXT:    ret [[STRUCT_V128FLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v128float8 test_insert (v128float8 a, int idx, v64float8 b) { return insert(a, idx, b); }
// CHECK-LABEL: @_Z19test_set_v128float8i9v64float8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64FLOAT8:%.*]] [[B_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <64 x i8> [[TMP0]] to <16 x i32>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <32 x i32> [[SHUFFLE_I_I]], <32 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[COND_I_I]] to <128 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V128FLOAT8:%.*]] poison, <128 x i8> [[TMP2]], 0
// CHECK-NEXT:    ret [[STRUCT_V128FLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v128float8 test_set_v128float8 (int idx, v64float8 b) { return set_v128float8(idx, b); }
// CHECK-LABEL: @_Z11test_concat9v64float8S_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64FLOAT8:%.*]] [[A0_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64FLOAT8]] [[A1_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <64 x i8> [[TMP0]] to <16 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <64 x i8> [[TMP1]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP2]], <16 x i32> [[TMP3]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <32 x i32> [[SHUFFLE_I_I]] to <128 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V128FLOAT8:%.*]] poison, <128 x i8> [[TMP4]], 0
// CHECK-NEXT:    ret [[STRUCT_V128FLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v128float8 test_concat (v64float8 a0, v64float8 a1) { return concat(a0, a1); }

// CHECK-LABEL: @_Z22test_extract_v8float16Dv32_7float16i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x half> [[A:%.*]] to <16 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <16 x i32> @llvm.aie2ps.vextract.broadcast128.I512(<16 x i32> [[TMP0]], i32 [[IDX:%.*]])
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[SHUFFLE_I_I]] to <8 x half>
// CHECK-NEXT:    ret <8 x half> [[TMP2]]
//
v8float16 test_extract_v8float16 ( v32float16 a, int idx ) { return extract_v8float16(a, idx); }
// CHECK-LABEL: @_Z19test_set_v32float16iDv8_7float16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x half> [[A:%.*]] to <4 x i32>
// CHECK-NEXT:    [[REM_I_I:%.*]] = srem i32 [[IDX:%.*]], 4
// CHECK-NEXT:    switch i32 [[REM_I_I]], label [[IF_ELSE_I_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[IF_THEN_I_I:%.*]]
// CHECK-NEXT:      i32 1, label [[IF_THEN4_I_I:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN10_I_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then.i.i:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    br label [[_ZL14SET_V32FLOAT16IDV8_7FLOAT16_EXIT:%.*]]
// CHECK:       if.then4.i.i:
// CHECK-NEXT:    [[SHUFFLE5_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE5_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    br label [[_ZL14SET_V32FLOAT16IDV8_7FLOAT16_EXIT]]
// CHECK:       if.then10.i.i:
// CHECK-NEXT:    [[SHUFFLE11_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE12_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE11_I_I]], <8 x i32> undef, <16 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    br label [[_ZL14SET_V32FLOAT16IDV8_7FLOAT16_EXIT]]
// CHECK:       if.else.i.i:
// CHECK-NEXT:    [[SHUFFLE13_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE14_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE13_I_I]], <8 x i32> undef, <16 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    br label [[_ZL14SET_V32FLOAT16IDV8_7FLOAT16_EXIT]]
// CHECK:       _ZL14set_v32float16iDv8_7float16.exit:
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = phi <16 x i32> [ [[SHUFFLE1_I_I]], [[IF_THEN_I_I]] ], [ [[SHUFFLE6_I_I]], [[IF_THEN4_I_I]] ], [ [[SHUFFLE12_I_I]], [[IF_THEN10_I_I]] ], [ [[SHUFFLE14_I_I]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[RETVAL_0_I_I]] to <32 x half>
// CHECK-NEXT:    ret <32 x half> [[TMP1]]
//
v32float16 test_set_v32float16 ( int idx, v8float16 a ) { return set_v32float16(idx, a); }
// CHECK-LABEL: @_Z22test_extract_v8float16Dv16_7float16i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x half> [[A:%.*]] to <8 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP1]], 0
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <4 x i32> [[SHUFFLE_I_I]], <4 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[RETVAL_0_I_I]] to <8 x half>
// CHECK-NEXT:    ret <8 x half> [[TMP2]]
//
v8float16 test_extract_v8float16 ( v16float16 a, int idx ) { return extract_v8float16(a, idx); }
// CHECK-LABEL: @_Z19test_set_v16float16iDv8_7float16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x half> [[A:%.*]] to <4 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP1]], 0
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i32> [[RETVAL_0_I_I]] to <16 x half>
// CHECK-NEXT:    ret <16 x half> [[TMP2]]
//
v16float16 test_set_v16float16 (int idx, v8float16 a ) { return set_v16float16(idx, a); }
// CHECK-LABEL: @_Z11test_insertDv32_7float16iDv8_S_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x half> [[V:%.*]] to <16 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x half> [[B:%.*]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[REM_I_I:%.*]] = srem i32 [[IDX:%.*]], 4
// CHECK-NEXT:    switch i32 [[REM_I_I]], label [[IF_ELSE_I_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[IF_THEN_I_I:%.*]]
// CHECK-NEXT:      i32 1, label [[IF_THEN5_I_I:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN10_I_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then.i.i:
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERTDV32_7FLOAT16IDV8_S__EXIT:%.*]]
// CHECK:       if.then5.i.i:
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 0, i32 1, i32 2, i32 3, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERTDV32_7FLOAT16IDV8_S__EXIT]]
// CHECK:       if.then10.i.i:
// CHECK-NEXT:    [[SHUFFLE11_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 0, i32 1, i32 2, i32 3, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERTDV32_7FLOAT16IDV8_S__EXIT]]
// CHECK:       if.else.i.i:
// CHECK-NEXT:    [[SHUFFLE12_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP0]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    br label [[_ZL6INSERTDV32_7FLOAT16IDV8_S__EXIT]]
// CHECK:       _ZL6insertDv32_7float16iDv8_S_.exit:
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = phi <16 x i32> [ [[SHUFFLE2_I_I]], [[IF_THEN_I_I]] ], [ [[SHUFFLE6_I_I]], [[IF_THEN5_I_I]] ], [ [[SHUFFLE11_I_I]], [[IF_THEN10_I_I]] ], [ [[SHUFFLE12_I_I]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[RETVAL_0_I_I]] to <32 x half>
// CHECK-NEXT:    ret <32 x half> [[TMP2]]
//
v32float16 test_insert (v32float16 v, int idx, v8float16 b ) { return insert(v, idx, b); }
//
// CHECK-LABEL: @_Z11test_insertDv16_7float16iDv8_S_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x half> [[A:%.*]] to <8 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x half> [[B:%.*]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP2]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[TMP0]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[TMP0]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <8 x i32> [[SHUFFLE1_I_I]], <8 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <8 x i32> [[RETVAL_0_I_I]] to <16 x half>
// CHECK-NEXT:    ret <16 x half> [[TMP3]]
//
v16float16 test_insert (v16float16 a, int idx, v8float16 b ) { return insert(a, idx, b); }
//
// CHECK-LABEL: @_Z11test_concatDv8_7float16S0_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x half> [[V0:%.*]] to <4 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x half> [[V1:%.*]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> [[TMP1]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i32> [[SHUFFLE_I_I]] to <16 x half>
// CHECK-NEXT:    ret <16 x half> [[TMP2]]
//
v16float16 test_concat (v8float16 v0, v8float16 v1 ) { return concat(v0, v1); }
// CHECK-LABEL: @_Z11test_concatDv8_7float16S0_S0_S0_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x half> [[V0:%.*]] to <4 x i32>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x half> [[V1:%.*]] to <4 x i32>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x half> [[V2:%.*]] to <4 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <8 x half> [[V3:%.*]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> [[TMP1]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <4 x i32> [[TMP2]], <4 x i32> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <16 x i32> [[SHUFFLE2_I_I]] to <32 x half>
// CHECK-NEXT:    ret <32 x half> [[TMP4]]
//
v32float16 test_concat (v8float16 v0, v8float16 v1, v8float16 v2, v8float16 v3 ) { return concat(v0, v1, v2, v3); }




// CHECK-LABEL: @_Z23test_extract_v16bfloat810v64bfloat8i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <64 x i8> [[TMP0]] to <16 x i32>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2ps.vextract.broadcast128.I512(<16 x i32> [[TMP1]], i32 [[IDX:%.*]])
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP2]], <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <4 x i32> [[SHUFFLE_I_I]] to <16 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V16BFLOAT8:%.*]] poison, <16 x i8> [[TMP3]], 0
// CHECK-NEXT:    ret [[STRUCT_V16BFLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v16bfloat8 test_extract_v16bfloat8 ( v64bfloat8 a, int idx ) { return extract_v16bfloat8(a, idx); }
// CHECK-LABEL: @_Z22test_extract_v16float89v64float8i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64FLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <64 x i8> [[TMP0]] to <16 x i32>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2ps.vextract.broadcast128.I512(<16 x i32> [[TMP1]], i32 [[IDX:%.*]])
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP2]], <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <4 x i32> [[SHUFFLE_I_I]] to <16 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V16FLOAT8:%.*]] poison, <16 x i8> [[TMP3]], 0
// CHECK-NEXT:    ret [[STRUCT_V16FLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v16float8 test_extract_v16float8 ( v64float8 a, int idx ) { return extract_v16float8(a, idx); }
// CHECK-LABEL: @_Z19test_set_v64bfloat8i10v16bfloat8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V16BFLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i8> [[TMP0]] to <4 x i32>
// CHECK-NEXT:    [[REM_I_I:%.*]] = srem i32 [[IDX:%.*]], 4
// CHECK-NEXT:    switch i32 [[REM_I_I]], label [[IF_ELSE_I_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[IF_THEN_I_I:%.*]]
// CHECK-NEXT:      i32 1, label [[IF_THEN4_I_I:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN10_I_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then.i.i:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    br label [[_ZL14SET_V64BFLOAT8I10V16BFLOAT8_EXIT:%.*]]
// CHECK:       if.then4.i.i:
// CHECK-NEXT:    [[SHUFFLE5_I_I:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE5_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    br label [[_ZL14SET_V64BFLOAT8I10V16BFLOAT8_EXIT]]
// CHECK:       if.then10.i.i:
// CHECK-NEXT:    [[SHUFFLE11_I_I:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE12_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE11_I_I]], <8 x i32> undef, <16 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    br label [[_ZL14SET_V64BFLOAT8I10V16BFLOAT8_EXIT]]
// CHECK:       if.else.i.i:
// CHECK-NEXT:    [[SHUFFLE13_I_I:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE14_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE13_I_I]], <8 x i32> undef, <16 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    br label [[_ZL14SET_V64BFLOAT8I10V16BFLOAT8_EXIT]]
// CHECK:       _ZL14set_v64bfloat8i10v16bfloat8.exit:
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = phi <16 x i32> [ [[SHUFFLE1_I_I]], [[IF_THEN_I_I]] ], [ [[SHUFFLE6_I_I]], [[IF_THEN4_I_I]] ], [ [[SHUFFLE12_I_I]], [[IF_THEN10_I_I]] ], [ [[SHUFFLE14_I_I]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[RETVAL_0_I_I]] to <64 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFLOAT8:%.*]] poison, <64 x i8> [[TMP2]], 0
// CHECK-NEXT:    ret [[STRUCT_V64BFLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v64bfloat8 test_set_v64bfloat8 ( int idx, v16bfloat8 a ) { return set_v64bfloat8(idx, a); }
// CHECK-LABEL: @_Z18test_set_v64float8i9v16float8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V16FLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i8> [[TMP0]] to <4 x i32>
// CHECK-NEXT:    [[REM_I_I:%.*]] = srem i32 [[IDX:%.*]], 4
// CHECK-NEXT:    switch i32 [[REM_I_I]], label [[IF_ELSE_I_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[IF_THEN_I_I:%.*]]
// CHECK-NEXT:      i32 1, label [[IF_THEN4_I_I:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN10_I_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then.i.i:
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    br label [[_ZL13SET_V64FLOAT8I9V16FLOAT8_EXIT:%.*]]
// CHECK:       if.then4.i.i:
// CHECK-NEXT:    [[SHUFFLE5_I_I:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE5_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    br label [[_ZL13SET_V64FLOAT8I9V16FLOAT8_EXIT]]
// CHECK:       if.then10.i.i:
// CHECK-NEXT:    [[SHUFFLE11_I_I:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE12_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE11_I_I]], <8 x i32> undef, <16 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    br label [[_ZL13SET_V64FLOAT8I9V16FLOAT8_EXIT]]
// CHECK:       if.else.i.i:
// CHECK-NEXT:    [[SHUFFLE13_I_I:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE14_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE13_I_I]], <8 x i32> undef, <16 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    br label [[_ZL13SET_V64FLOAT8I9V16FLOAT8_EXIT]]
// CHECK:       _ZL13set_v64float8i9v16float8.exit:
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = phi <16 x i32> [ [[SHUFFLE1_I_I]], [[IF_THEN_I_I]] ], [ [[SHUFFLE6_I_I]], [[IF_THEN4_I_I]] ], [ [[SHUFFLE12_I_I]], [[IF_THEN10_I_I]] ], [ [[SHUFFLE14_I_I]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i32> [[RETVAL_0_I_I]] to <64 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64FLOAT8:%.*]] poison, <64 x i8> [[TMP2]], 0
// CHECK-NEXT:    ret [[STRUCT_V64FLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v64float8 test_set_v64float8 ( int idx, v16float8 a ) { return set_v64float8(idx, a); }

// CHECK-LABEL: @_Z23test_extract_v16bfloat810v32bfloat8i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V32BFLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i8> [[TMP0]] to <8 x i32>
// CHECK-NEXT:    [[TMP2:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP2]], 0
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <4 x i32> [[SHUFFLE_I_I]], <4 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <4 x i32> [[RETVAL_0_I_I]] to <16 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V16BFLOAT8:%.*]] poison, <16 x i8> [[TMP3]], 0
// CHECK-NEXT:    ret [[STRUCT_V16BFLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v16bfloat8 test_extract_v16bfloat8 ( v32bfloat8 a, int idx ) { return extract_v16bfloat8(a, idx); }
// CHECK-LABEL: @_Z22test_extract_v16float89v32float8i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V32FLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <32 x i8> [[TMP0]] to <8 x i32>
// CHECK-NEXT:    [[TMP2:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP2]], 0
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <4 x i32> [[SHUFFLE_I_I]], <4 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <4 x i32> [[RETVAL_0_I_I]] to <16 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V16FLOAT8:%.*]] poison, <16 x i8> [[TMP3]], 0
// CHECK-NEXT:    ret [[STRUCT_V16FLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v16float8 test_extract_v16float8 ( v32float8 a, int idx ) { return extract_v16float8(a, idx); }
// CHECK-LABEL: @_Z19test_set_v32bfloat8i10v16bfloat8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V16BFLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i8> [[TMP0]] to <4 x i32>
// CHECK-NEXT:    [[TMP2:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP2]], 0
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <8 x i32> [[RETVAL_0_I_I]] to <32 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V32BFLOAT8:%.*]] poison, <32 x i8> [[TMP3]], 0
// CHECK-NEXT:    ret [[STRUCT_V32BFLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v32bfloat8 test_set_v32bfloat8 (int idx, v16bfloat8 a ) { return set_v32bfloat8(idx, a); }
// CHECK-LABEL: @_Z18test_set_v32float8i9v16float8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V16FLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i8> [[TMP0]] to <4 x i32>
// CHECK-NEXT:    [[TMP2:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP2]], 0
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <8 x i32> [[RETVAL_0_I_I]] to <32 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V32FLOAT8:%.*]] poison, <32 x i8> [[TMP3]], 0
// CHECK-NEXT:    ret [[STRUCT_V32FLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v32float8 test_set_v32float8 (int idx, v16float8 a ) { return set_v32float8(idx, a); }



//
// CHECK-LABEL: @_Z11test_insert10v64bfloat8i10v16bfloat8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFLOAT8:%.*]] [[V_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V16BFLOAT8:%.*]] [[B_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <64 x i8> [[TMP0]] to <16 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <16 x i8> [[TMP1]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP3]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[REM_I_I:%.*]] = srem i32 [[IDX:%.*]], 4
// CHECK-NEXT:    switch i32 [[REM_I_I]], label [[IF_ELSE_I_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[IF_THEN_I_I:%.*]]
// CHECK-NEXT:      i32 1, label [[IF_THEN5_I_I:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN10_I_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then.i.i:
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP2]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERT10V64BFLOAT8I10V16BFLOAT8_EXIT:%.*]]
// CHECK:       if.then5.i.i:
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP2]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 0, i32 1, i32 2, i32 3, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERT10V64BFLOAT8I10V16BFLOAT8_EXIT]]
// CHECK:       if.then10.i.i:
// CHECK-NEXT:    [[SHUFFLE11_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP2]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 0, i32 1, i32 2, i32 3, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERT10V64BFLOAT8I10V16BFLOAT8_EXIT]]
// CHECK:       if.else.i.i:
// CHECK-NEXT:    [[SHUFFLE12_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP2]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    br label [[_ZL6INSERT10V64BFLOAT8I10V16BFLOAT8_EXIT]]
// CHECK:       _ZL6insert10v64bfloat8i10v16bfloat8.exit:
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = phi <16 x i32> [ [[SHUFFLE2_I_I]], [[IF_THEN_I_I]] ], [ [[SHUFFLE6_I_I]], [[IF_THEN5_I_I]] ], [ [[SHUFFLE11_I_I]], [[IF_THEN10_I_I]] ], [ [[SHUFFLE12_I_I]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <16 x i32> [[RETVAL_0_I_I]] to <64 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFLOAT8]] poison, <64 x i8> [[TMP4]], 0
// CHECK-NEXT:    ret [[STRUCT_V64BFLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v64bfloat8 test_insert (v64bfloat8 v, int idx, v16bfloat8 b ) { return insert(v, idx, b); }
// CHECK-LABEL: @_Z11test_insert9v64float8i9v16float8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64FLOAT8:%.*]] [[V_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V16FLOAT8:%.*]] [[B_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <64 x i8> [[TMP0]] to <16 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <16 x i8> [[TMP1]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP3]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[REM_I_I:%.*]] = srem i32 [[IDX:%.*]], 4
// CHECK-NEXT:    switch i32 [[REM_I_I]], label [[IF_ELSE_I_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[IF_THEN_I_I:%.*]]
// CHECK-NEXT:      i32 1, label [[IF_THEN5_I_I:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN10_I_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then.i.i:
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP2]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERT9V64FLOAT8I9V16FLOAT8_EXIT:%.*]]
// CHECK:       if.then5.i.i:
// CHECK-NEXT:    [[SHUFFLE6_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP2]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 0, i32 1, i32 2, i32 3, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERT9V64FLOAT8I9V16FLOAT8_EXIT]]
// CHECK:       if.then10.i.i:
// CHECK-NEXT:    [[SHUFFLE11_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP2]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 0, i32 1, i32 2, i32 3, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    br label [[_ZL6INSERT9V64FLOAT8I9V16FLOAT8_EXIT]]
// CHECK:       if.else.i.i:
// CHECK-NEXT:    [[SHUFFLE12_I_I:%.*]] = shufflevector <16 x i32> [[SHUFFLE1_I_I]], <16 x i32> [[TMP2]], <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    br label [[_ZL6INSERT9V64FLOAT8I9V16FLOAT8_EXIT]]
// CHECK:       _ZL6insert9v64float8i9v16float8.exit:
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = phi <16 x i32> [ [[SHUFFLE2_I_I]], [[IF_THEN_I_I]] ], [ [[SHUFFLE6_I_I]], [[IF_THEN5_I_I]] ], [ [[SHUFFLE11_I_I]], [[IF_THEN10_I_I]] ], [ [[SHUFFLE12_I_I]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <16 x i32> [[RETVAL_0_I_I]] to <64 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64FLOAT8]] poison, <64 x i8> [[TMP4]], 0
// CHECK-NEXT:    ret [[STRUCT_V64FLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v64float8 test_insert (v64float8 v, int idx, v16float8 b ) { return insert(v, idx, b); }
// CHECK-LABEL: @_Z11test_insert10v32bfloat8i10v16bfloat8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V32BFLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V16BFLOAT8:%.*]] [[B_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i8> [[TMP0]] to <8 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <16 x i8> [[TMP1]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP3]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP4:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP4]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[TMP2]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[TMP2]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <8 x i32> [[SHUFFLE1_I_I]], <8 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <8 x i32> [[RETVAL_0_I_I]] to <32 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V32BFLOAT8]] poison, <32 x i8> [[TMP5]], 0
// CHECK-NEXT:    ret [[STRUCT_V32BFLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v32bfloat8 test_insert (v32bfloat8 a, int idx, v16bfloat8 b ) { return insert(a, idx, b); }
// CHECK-LABEL: @_Z11test_insert9v32float8i9v16float8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V32FLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V16FLOAT8:%.*]] [[B_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i8> [[TMP0]] to <8 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <16 x i8> [[TMP1]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP3]], <4 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP4:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[TMP4]], 0
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[TMP2]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[TMP2]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[RETVAL_0_I_I:%.*]] = select i1 [[CMP_I_I]], <8 x i32> [[SHUFFLE1_I_I]], <8 x i32> [[SHUFFLE2_I_I]]
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <8 x i32> [[RETVAL_0_I_I]] to <32 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V32FLOAT8]] poison, <32 x i8> [[TMP5]], 0
// CHECK-NEXT:    ret [[STRUCT_V32FLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v32float8 test_insert (v32float8 a, int idx, v16float8 b ) { return insert(a, idx, b); }
// CHECK-LABEL: @_Z11test_concat10v16bfloat8S_S_S_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V16BFLOAT8:%.*]] [[V0_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V16BFLOAT8]] [[V1_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V16BFLOAT8]] [[V2_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V16BFLOAT8]] [[V3_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <16 x i8> [[TMP0]] to <4 x i32>
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <16 x i8> [[TMP1]] to <4 x i32>
// CHECK-NEXT:    [[TMP6:%.*]] = bitcast <16 x i8> [[TMP2]] to <4 x i32>
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <16 x i8> [[TMP3]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP4]], <4 x i32> [[TMP5]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <4 x i32> [[TMP6]], <4 x i32> [[TMP7]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP8:%.*]] = bitcast <16 x i32> [[SHUFFLE2_I_I]] to <64 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFLOAT8:%.*]] poison, <64 x i8> [[TMP8]], 0
// CHECK-NEXT:    ret [[STRUCT_V64BFLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v64bfloat8 test_concat (v16bfloat8 v0, v16bfloat8 v1, v16bfloat8 v2, v16bfloat8 v3 ) { return concat(v0, v1, v2, v3); }
//
// CHECK-LABEL: @_Z11test_concat9v16float8S_S_S_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V16FLOAT8:%.*]] [[V0_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V16FLOAT8]] [[V1_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V16FLOAT8]] [[V2_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V16FLOAT8]] [[V3_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <16 x i8> [[TMP0]] to <4 x i32>
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <16 x i8> [[TMP1]] to <4 x i32>
// CHECK-NEXT:    [[TMP6:%.*]] = bitcast <16 x i8> [[TMP2]] to <4 x i32>
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <16 x i8> [[TMP3]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP4]], <4 x i32> [[TMP5]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <4 x i32> [[TMP6]], <4 x i32> [[TMP7]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE2_I_I:%.*]] = shufflevector <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP8:%.*]] = bitcast <16 x i32> [[SHUFFLE2_I_I]] to <64 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64FLOAT8:%.*]] poison, <64 x i8> [[TMP8]], 0
// CHECK-NEXT:    ret [[STRUCT_V64FLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v64float8 test_concat (v16float8 v0, v16float8 v1, v16float8 v2, v16float8 v3 ) { return concat(v0, v1, v2, v3); }
//
// CHECK-LABEL: @_Z11test_concat10v16bfloat8S_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V16BFLOAT8:%.*]] [[V0_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V16BFLOAT8]] [[V1_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[TMP0]] to <4 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <16 x i8> [[TMP1]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP2]], <4 x i32> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <8 x i32> [[SHUFFLE_I_I]] to <32 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V32BFLOAT8:%.*]] poison, <32 x i8> [[TMP4]], 0
// CHECK-NEXT:    ret [[STRUCT_V32BFLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v32bfloat8 test_concat (v16bfloat8 v0, v16bfloat8 v1 ) { return concat(v0, v1); }
// CHECK-LABEL: @_Z11test_concat9v16float8S_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V16FLOAT8:%.*]] [[V0_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V16FLOAT8]] [[V1_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[TMP0]] to <4 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <16 x i8> [[TMP1]] to <4 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <4 x i32> [[TMP2]], <4 x i32> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <8 x i32> [[SHUFFLE_I_I]] to <32 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V32FLOAT8:%.*]] poison, <32 x i8> [[TMP4]], 0
// CHECK-NEXT:    ret [[STRUCT_V32FLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v32float8 test_concat (v16float8 v0, v16float8 v1 ) { return concat(v0, v1); }

// CHECK-LABEL: @_Z11test_insert6v64mx9ii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64MX9:%.*]] [[M_COERCE:%.*]], 2
// CHECK-NEXT:    [[VECINS_I:%.*]] = insertelement <2 x i32> [[TMP0]], i32 [[EXP:%.*]], i32 [[IDX:%.*]]
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX9]] [[M_COERCE]], <2 x i32> [[VECINS_I]], 2
// CHECK-NEXT:    ret [[STRUCT_V64MX9]] [[DOTFCA_2_INSERT_I]]
//
v64mx9 test_insert (v64mx9 m, int idx, int exp) { return insert(m, idx, exp); }
// CHECK-LABEL: @_Z11test_insert6v64mx9iDv4_a(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64MX9:%.*]] [[M_COERCE:%.*]], 1
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64MX9]] [[M_COERCE]], 2
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <4 x i8> [[PRIME:%.*]] to i32
// CHECK-NEXT:    [[VECINS_I:%.*]] = insertelement <2 x i32> [[TMP0]], i32 [[TMP2]], i32 [[IDX:%.*]]
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX9]] [[M_COERCE]], <2 x i32> [[VECINS_I]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX9]] [[DOTFCA_1_INSERT_I]], <2 x i32> [[TMP1]], 2
// CHECK-NEXT:    ret [[STRUCT_V64MX9]] [[DOTFCA_2_INSERT_I]]
//
v64mx9 test_insert (v64mx9 m, int idx, v4int8 prime) { return insert(m, idx, prime); }
// CHECK-LABEL: @_Z21test_extract_exponent6v64mx9i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64MX9:%.*]] [[M_COERCE:%.*]], 2
// CHECK-NEXT:    [[VECEXT_I:%.*]] = extractelement <2 x i32> [[TMP0]], i32 [[IDX:%.*]]
// CHECK-NEXT:    ret i32 [[VECEXT_I]]
//
int test_extract_exponent (v64mx9 m, int idx) { return extract_exponent(m, idx); }
// CHECK-LABEL: @_Z18test_extract_prime6v64mx9i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64MX9:%.*]] [[M_COERCE:%.*]], 1
// CHECK-NEXT:    [[VECEXT_I:%.*]] = extractelement <2 x i32> [[TMP0]], i32 [[IDX:%.*]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i32 [[VECEXT_I]] to <4 x i8>
// CHECK-NEXT:    ret <4 x i8> [[TMP1]]
//
v4int8 test_extract_prime (v64mx9 m, int idx) { return extract_prime(m, idx); }
// CHECK-LABEL: @_Z20test_extract_v32int86v64mx9i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64MX9:%.*]] [[M_COERCE:%.*]], 0
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[IDX:%.*]], 1
// CHECK-NEXT:    [[TOBOOL_NOT_I_I:%.*]] = icmp eq i32 [[AND_I_I]], 0
// CHECK-NEXT:    [[COND_I_I:%.*]] = select i1 [[TOBOOL_NOT_I_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[SHUFFLE1_I_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i32> [[COND_I_I]] to <32 x i8>
// CHECK-NEXT:    ret <32 x i8> [[TMP1]]
//
v32int8 test_extract_v32int8 (v64mx9 m, int idx) { return extract_v32int8(m, idx); }
// CHECK-LABEL: @_Z20test_extract_v64int87v128mx9i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V128MX9:%.*]] [[M_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V128MX9]] [[M_COERCE]], 1
// CHECK-NEXT:    [[RETVAL_0_IN_I:%.*]] = select i1 [[CMP_I]], <16 x i32> [[TMP0]], <16 x i32> [[TMP1]]
// CHECK-NEXT:    [[RETVAL_0_I:%.*]] = bitcast <16 x i32> [[RETVAL_0_IN_I]] to <64 x i8>
// CHECK-NEXT:    ret <64 x i8> [[RETVAL_0_I]]
//
v64int8 test_extract_v64int8 (v128mx9 m, int idx) { return extract_v64int8(m, idx); }
// CHECK-LABEL: @_Z11test_insert7v128mx9iDv64_a(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V128MX9:%.*]] [[M_COERCE:%.*]], 1
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <64 x i8> [[V:%.*]] to <16 x i32>
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128MX9]] [[M_COERCE]], 0
// CHECK-NEXT:    [[RETVAL_SROA_0_0_I:%.*]] = select i1 [[CMP_I]], <16 x i32> [[TMP1]], <16 x i32> [[TMP2]]
// CHECK-NEXT:    [[RETVAL_SROA_3_0_I:%.*]] = select i1 [[CMP_I]], <16 x i32> [[TMP0]], <16 x i32> [[TMP1]]
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128MX9]] [[M_COERCE]], 5
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128MX9]] [[M_COERCE]], 4
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128MX9]] [[M_COERCE]], 3
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V128MX9]] [[M_COERCE]], 2
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX9]] poison, <16 x i32> [[RETVAL_SROA_0_0_I]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX9]] [[DOTFCA_0_INSERT_I]], <16 x i32> [[RETVAL_SROA_3_0_I]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX9]] [[DOTFCA_1_INSERT_I]], <2 x i32> [[TMP6]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX9]] [[DOTFCA_2_INSERT_I]], <2 x i32> [[TMP5]], 3
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX9]] [[DOTFCA_3_INSERT_I]], <2 x i32> [[TMP4]], 4
// CHECK-NEXT:    [[DOTFCA_5_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX9]] [[DOTFCA_4_INSERT_I]], <2 x i32> [[TMP3]], 5
// CHECK-NEXT:    ret [[STRUCT_V128MX9]] [[DOTFCA_5_INSERT_I]]
//
v128mx9 test_insert (v128mx9 m, int idx, v64int8 v) { return insert(m, idx, v); }
// CHECK-LABEL: @_Z11test_insert7v128mx9i6v64mx9(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64MX9:%.*]] [[V_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64MX9]] [[V_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64MX9]] [[V_COERCE]], 2
// CHECK-NEXT:    [[CMP_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    br i1 [[CMP_I]], label [[IF_THEN_I:%.*]], label [[IF_END_I:%.*]]
// CHECK:       if.then.i:
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128MX9:%.*]] [[M_COERCE:%.*]], 5
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128MX9]] [[M_COERCE]], 3
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128MX9]] [[M_COERCE]], 1
// CHECK-NEXT:    br label [[_ZL6INSERT7V128MX9I6V64MX9_EXIT:%.*]]
// CHECK:       if.end.i:
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V128MX9]] [[M_COERCE]], 4
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V128MX9]] [[M_COERCE]], 2
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V128MX9]] [[M_COERCE]], 0
// CHECK-NEXT:    br label [[_ZL6INSERT7V128MX9I6V64MX9_EXIT]]
// CHECK:       _ZL6insert7v128mx9i6v64mx9.exit:
// CHECK-NEXT:    [[RETVAL_SROA_0_0_I:%.*]] = phi <16 x i32> [ [[TMP0]], [[IF_THEN_I]] ], [ [[TMP8]], [[IF_END_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_3_0_I:%.*]] = phi <16 x i32> [ [[TMP5]], [[IF_THEN_I]] ], [ [[TMP0]], [[IF_END_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_6_0_I:%.*]] = phi <2 x i32> [ [[TMP1]], [[IF_THEN_I]] ], [ [[TMP7]], [[IF_END_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_9_0_I:%.*]] = phi <2 x i32> [ [[TMP4]], [[IF_THEN_I]] ], [ [[TMP1]], [[IF_END_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_12_0_I:%.*]] = phi <2 x i32> [ [[TMP2]], [[IF_THEN_I]] ], [ [[TMP6]], [[IF_END_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_15_0_I:%.*]] = phi <2 x i32> [ [[TMP3]], [[IF_THEN_I]] ], [ [[TMP2]], [[IF_END_I]] ]
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX9]] poison, <16 x i32> [[RETVAL_SROA_0_0_I]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX9]] [[DOTFCA_0_INSERT_I]], <16 x i32> [[RETVAL_SROA_3_0_I]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX9]] [[DOTFCA_1_INSERT_I]], <2 x i32> [[RETVAL_SROA_6_0_I]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX9]] [[DOTFCA_2_INSERT_I]], <2 x i32> [[RETVAL_SROA_9_0_I]], 3
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX9]] [[DOTFCA_3_INSERT_I]], <2 x i32> [[RETVAL_SROA_12_0_I]], 4
// CHECK-NEXT:    [[DOTFCA_5_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX9]] [[DOTFCA_4_INSERT_I]], <2 x i32> [[RETVAL_SROA_15_0_I]], 5
// CHECK-NEXT:    ret [[STRUCT_V128MX9]] [[DOTFCA_5_INSERT_I]]
//
v128mx9 test_insert (v128mx9 m, int idx, v64mx9 v) { return insert(m, idx, v); }
// CHECK-LABEL: @_Z16test_set_v128mx9i6v64mx9(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64MX9:%.*]] [[V_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64MX9]] [[V_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64MX9]] [[V_COERCE]], 2
// CHECK-NEXT:    [[CMP_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    [[DOT_I:%.*]] = select i1 [[CMP_I]], <16 x i32> undef, <16 x i32> [[TMP0]]
// CHECK-NEXT:    [[DOT22_I:%.*]] = select i1 [[CMP_I]], <16 x i32> [[TMP0]], <16 x i32> undef
// CHECK-NEXT:    [[DOT23_I:%.*]] = select i1 [[CMP_I]], <2 x i32> [[TMP1]], <2 x i32> undef
// CHECK-NEXT:    [[DOT24_I:%.*]] = select i1 [[CMP_I]], <2 x i32> undef, <2 x i32> [[TMP1]]
// CHECK-NEXT:    [[DOT25_I:%.*]] = select i1 [[CMP_I]], <2 x i32> [[TMP2]], <2 x i32> undef
// CHECK-NEXT:    [[DOT26_I:%.*]] = select i1 [[CMP_I]], <2 x i32> undef, <2 x i32> [[TMP2]]
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX9:%.*]] poison, <16 x i32> [[DOT22_I]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX9]] [[DOTFCA_0_INSERT_I]], <16 x i32> [[DOT_I]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX9]] [[DOTFCA_1_INSERT_I]], <2 x i32> [[DOT23_I]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX9]] [[DOTFCA_2_INSERT_I]], <2 x i32> [[DOT24_I]], 3
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX9]] [[DOTFCA_3_INSERT_I]], <2 x i32> [[DOT25_I]], 4
// CHECK-NEXT:    [[DOTFCA_5_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX9]] [[DOTFCA_4_INSERT_I]], <2 x i32> [[DOT26_I]], 5
// CHECK-NEXT:    ret [[STRUCT_V128MX9]] [[DOTFCA_5_INSERT_I]]
//
v128mx9 test_set_v128mx9 (int idx, v64mx9 v) { return set_v128mx9(idx, v); }
// CHECK-LABEL: @_Z19test_set_v128bfp16pi6v64mx9(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64MX9:%.*]] [[V_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64MX9]] [[V_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64MX9]] [[V_COERCE]], 2
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    [[DOT_I_I:%.*]] = select i1 [[CMP_I_I]], <16 x i32> undef, <16 x i32> [[TMP0]]
// CHECK-NEXT:    [[DOT22_I_I:%.*]] = select i1 [[CMP_I_I]], <16 x i32> [[TMP0]], <16 x i32> undef
// CHECK-NEXT:    [[DOT23_I_I:%.*]] = select i1 [[CMP_I_I]], <2 x i32> [[TMP1]], <2 x i32> undef
// CHECK-NEXT:    [[DOT24_I_I:%.*]] = select i1 [[CMP_I_I]], <2 x i32> undef, <2 x i32> [[TMP1]]
// CHECK-NEXT:    [[DOT25_I_I:%.*]] = select i1 [[CMP_I_I]], <2 x i32> [[TMP2]], <2 x i32> undef
// CHECK-NEXT:    [[DOT26_I_I:%.*]] = select i1 [[CMP_I_I]], <2 x i32> undef, <2 x i32> [[TMP2]]
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX9:%.*]] poison, <16 x i32> [[DOT22_I_I]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX9]] [[DOTFCA_0_INSERT_I_I]], <16 x i32> [[DOT_I_I]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX9]] [[DOTFCA_1_INSERT_I_I]], <2 x i32> [[DOT23_I_I]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX9]] [[DOTFCA_2_INSERT_I_I]], <2 x i32> [[DOT24_I_I]], 3
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX9]] [[DOTFCA_3_INSERT_I_I]], <2 x i32> [[DOT25_I_I]], 4
// CHECK-NEXT:    [[DOTFCA_5_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX9]] [[DOTFCA_4_INSERT_I_I]], <2 x i32> [[DOT26_I_I]], 5
// CHECK-NEXT:    ret [[STRUCT_V128MX9]] [[DOTFCA_5_INSERT_I_I]]
//
v128bfp16p test_set_v128bfp16p (int idx, v64bfp16p v) { return set_v128bfp16p(idx, v); }
// CHECK-LABEL: @_Z11test_concat6v64mx9S_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64MX9:%.*]] [[V0_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64MX9]] [[V0_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64MX9]] [[V0_COERCE]], 2
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64MX9]] [[V1_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V64MX9]] [[V1_COERCE]], 1
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V64MX9]] [[V1_COERCE]], 2
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX9:%.*]] poison, <16 x i32> [[TMP0]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX9]] [[DOTFCA_0_INSERT_I]], <16 x i32> [[TMP3]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX9]] [[DOTFCA_1_INSERT_I]], <2 x i32> [[TMP1]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX9]] [[DOTFCA_2_INSERT_I]], <2 x i32> [[TMP4]], 3
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX9]] [[DOTFCA_3_INSERT_I]], <2 x i32> [[TMP2]], 4
// CHECK-NEXT:    [[DOTFCA_5_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX9]] [[DOTFCA_4_INSERT_I]], <2 x i32> [[TMP5]], 5
// CHECK-NEXT:    ret [[STRUCT_V128MX9]] [[DOTFCA_5_INSERT_I]]
//
v128mx9 test_concat (v64mx9 v0, v64mx9 v1) { return concat(v0, v1); }
// CHECK-LABEL: @_Z11test_insert7v128mx9ii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP_I:%.*]] = icmp slt i32 [[IDX:%.*]], 2
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V128MX9:%.*]] [[M_COERCE:%.*]], 4
// CHECK-NEXT:    [[REM_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[VECINS_I_I:%.*]] = insertelement <2 x i32> [[TMP0]], i32 [[EXP:%.*]], i32 [[REM_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V128MX9]] [[M_COERCE]], 5
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX9]] [[M_COERCE]], <2 x i32> [[VECINS_I_I]], 4
// CHECK-NEXT:    [[VECINS_I59_I:%.*]] = insertelement <2 x i32> [[TMP1]], i32 [[EXP]], i32 [[REM_I]]
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I_PN_I:%.*]] = select i1 [[CMP_I]], [[STRUCT_V128MX9]] [[DOTFCA_4_INSERT_I_I]], [[STRUCT_V128MX9]] [[M_COERCE]]
// CHECK-NEXT:    [[DOTPN_I:%.*]] = select i1 [[CMP_I]], <2 x i32> [[TMP1]], <2 x i32> [[VECINS_I59_I]]
// CHECK-NEXT:    [[CALL6_PN_I:%.*]] = insertvalue [[STRUCT_V128MX9]] [[DOTFCA_4_INSERT_I_PN_I]], <2 x i32> [[DOTPN_I]], 5
// CHECK-NEXT:    ret [[STRUCT_V128MX9]] [[CALL6_PN_I]]
//
v128mx9 test_insert (v128mx9 m, int idx, int exp) { return insert(m, idx, exp); }
// CHECK-LABEL: @_Z11test_insert7v128mx9iDv4_a(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP_I:%.*]] = icmp slt i32 [[IDX:%.*]], 2
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V128MX9:%.*]] [[M_COERCE:%.*]], 2
// CHECK-NEXT:    [[REM_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <4 x i8> [[PRIME:%.*]] to i32
// CHECK-NEXT:    [[VECINS_I_I:%.*]] = insertelement <2 x i32> [[TMP0]], i32 [[TMP1]], i32 [[REM_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128MX9]] [[M_COERCE]], 3
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I59_I:%.*]] = insertvalue [[STRUCT_V128MX9]] [[M_COERCE]], <2 x i32> [[VECINS_I_I]], 2
// CHECK-NEXT:    [[VECINS_I60_I:%.*]] = insertelement <2 x i32> [[TMP2]], i32 [[TMP1]], i32 [[REM_I]]
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I59_PN_I:%.*]] = select i1 [[CMP_I]], [[STRUCT_V128MX9]] [[DOTFCA_2_INSERT_I59_I]], [[STRUCT_V128MX9]] [[M_COERCE]]
// CHECK-NEXT:    [[DOTPN69_I:%.*]] = select i1 [[CMP_I]], <2 x i32> [[TMP2]], <2 x i32> [[VECINS_I60_I]]
// CHECK-NEXT:    [[DOTPN_I:%.*]] = extractvalue [[STRUCT_V128MX9]] [[M_COERCE]], 5
// CHECK-NEXT:    [[DOTPN68_I:%.*]] = extractvalue [[STRUCT_V128MX9]] [[M_COERCE]], 4
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I_PN_I:%.*]] = insertvalue [[STRUCT_V128MX9]] [[DOTFCA_2_INSERT_I59_PN_I]], <2 x i32> [[DOTPN69_I]], 3
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I_PN_I:%.*]] = insertvalue [[STRUCT_V128MX9]] [[DOTFCA_3_INSERT_I_PN_I]], <2 x i32> [[DOTPN68_I]], 4
// CHECK-NEXT:    [[CALL6_PN_I:%.*]] = insertvalue [[STRUCT_V128MX9]] [[DOTFCA_4_INSERT_I_PN_I]], <2 x i32> [[DOTPN_I]], 5
// CHECK-NEXT:    ret [[STRUCT_V128MX9]] [[CALL6_PN_I]]
//
v128mx9 test_insert (v128mx9 m, int idx, v4int8 prime) { return insert(m, idx, prime); }
// CHECK-LABEL: @_Z21test_extract_exponent7v128mx9i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP_I:%.*]] = icmp slt i32 [[IDX:%.*]], 2
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V128MX9:%.*]] [[M_COERCE:%.*]], 4
// CHECK-NEXT:    [[REM_I:%.*]] = srem i32 [[IDX]], 2
// CHECK-NEXT:    [[VECEXT_I:%.*]] = extractelement <2 x i32> [[TMP0]], i32 [[REM_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V128MX9]] [[M_COERCE]], 5
// CHECK-NEXT:    [[REM1_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[VECEXT2_I:%.*]] = extractelement <2 x i32> [[TMP1]], i32 [[REM1_I]]
// CHECK-NEXT:    [[COND_I:%.*]] = select i1 [[CMP_I]], i32 [[VECEXT_I]], i32 [[VECEXT2_I]]
// CHECK-NEXT:    ret i32 [[COND_I]]
//
int test_extract_exponent (v128mx9 m, int idx) { return extract_exponent(m, idx); }
// CHECK-LABEL: @_Z18test_extract_prime7v128mx9i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP_I:%.*]] = icmp slt i32 [[IDX:%.*]], 2
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V128MX9:%.*]] [[M_COERCE:%.*]], 2
// CHECK-NEXT:    [[REM_I:%.*]] = srem i32 [[IDX]], 2
// CHECK-NEXT:    [[VECEXT_I:%.*]] = extractelement <2 x i32> [[TMP0]], i32 [[REM_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V128MX9]] [[M_COERCE]], 3
// CHECK-NEXT:    [[REM1_I:%.*]] = and i32 [[IDX]], 1
// CHECK-NEXT:    [[VECEXT2_I:%.*]] = extractelement <2 x i32> [[TMP1]], i32 [[REM1_I]]
// CHECK-NEXT:    [[COND_I:%.*]] = select i1 [[CMP_I]], i32 [[VECEXT_I]], i32 [[VECEXT2_I]]
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast i32 [[COND_I]] to <4 x i8>
// CHECK-NEXT:    ret <4 x i8> [[TMP2]]
//
v4int8 test_extract_prime (v128mx9 m, int idx) { return extract_prime(m, idx); }
// CHECK-LABEL: @_Z11test_insert7v256mx9i7v128mx9(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V128MX9:%.*]] [[A_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V128MX9]] [[A_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128MX9]] [[A_COERCE]], 2
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128MX9]] [[A_COERCE]], 3
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128MX9]] [[A_COERCE]], 4
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128MX9]] [[A_COERCE]], 5
// CHECK-NEXT:    [[CMP_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    br i1 [[CMP_I]], label [[IF_THEN_I:%.*]], label [[IF_END_I:%.*]]
// CHECK:       if.then.i:
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V256MX9:%.*]] [[M_COERCE:%.*]], 1
// CHECK-NEXT:    [[DOTFCA_5_EXTRACT21_I:%.*]] = extractvalue [[STRUCT_V128MX9]] [[TMP6]], 5
// CHECK-NEXT:    [[DOTFCA_4_EXTRACT19_I:%.*]] = extractvalue [[STRUCT_V128MX9]] [[TMP6]], 4
// CHECK-NEXT:    [[DOTFCA_3_EXTRACT17_I:%.*]] = extractvalue [[STRUCT_V128MX9]] [[TMP6]], 3
// CHECK-NEXT:    [[DOTFCA_2_EXTRACT15_I:%.*]] = extractvalue [[STRUCT_V128MX9]] [[TMP6]], 2
// CHECK-NEXT:    [[DOTFCA_1_EXTRACT13_I:%.*]] = extractvalue [[STRUCT_V128MX9]] [[TMP6]], 1
// CHECK-NEXT:    [[DOTFCA_0_EXTRACT11_I:%.*]] = extractvalue [[STRUCT_V128MX9]] [[TMP6]], 0
// CHECK-NEXT:    br label [[_ZL6INSERT7V256MX9I7V128MX9_EXIT:%.*]]
// CHECK:       if.end.i:
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V256MX9]] [[M_COERCE]], 0
// CHECK-NEXT:    [[DOTFCA_5_EXTRACT_I:%.*]] = extractvalue [[STRUCT_V128MX9]] [[TMP7]], 5
// CHECK-NEXT:    [[DOTFCA_4_EXTRACT_I:%.*]] = extractvalue [[STRUCT_V128MX9]] [[TMP7]], 4
// CHECK-NEXT:    [[DOTFCA_3_EXTRACT_I:%.*]] = extractvalue [[STRUCT_V128MX9]] [[TMP7]], 3
// CHECK-NEXT:    [[DOTFCA_2_EXTRACT_I:%.*]] = extractvalue [[STRUCT_V128MX9]] [[TMP7]], 2
// CHECK-NEXT:    [[DOTFCA_1_EXTRACT_I:%.*]] = extractvalue [[STRUCT_V128MX9]] [[TMP7]], 1
// CHECK-NEXT:    [[DOTFCA_0_EXTRACT_I:%.*]] = extractvalue [[STRUCT_V128MX9]] [[TMP7]], 0
// CHECK-NEXT:    br label [[_ZL6INSERT7V256MX9I7V128MX9_EXIT]]
// CHECK:       _ZL6insert7v256mx9i7v128mx9.exit:
// CHECK-NEXT:    [[RETVAL_SROA_0_0_I:%.*]] = phi <16 x i32> [ [[TMP0]], [[IF_THEN_I]] ], [ [[DOTFCA_0_EXTRACT_I]], [[IF_END_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_3_0_I:%.*]] = phi <16 x i32> [ [[TMP1]], [[IF_THEN_I]] ], [ [[DOTFCA_1_EXTRACT_I]], [[IF_END_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_6_0_I:%.*]] = phi <2 x i32> [ [[TMP2]], [[IF_THEN_I]] ], [ [[DOTFCA_2_EXTRACT_I]], [[IF_END_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_9_0_I:%.*]] = phi <2 x i32> [ [[TMP3]], [[IF_THEN_I]] ], [ [[DOTFCA_3_EXTRACT_I]], [[IF_END_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_12_0_I:%.*]] = phi <2 x i32> [ [[TMP4]], [[IF_THEN_I]] ], [ [[DOTFCA_4_EXTRACT_I]], [[IF_END_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_15_0_I:%.*]] = phi <2 x i32> [ [[TMP5]], [[IF_THEN_I]] ], [ [[DOTFCA_5_EXTRACT_I]], [[IF_END_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_18_0_I:%.*]] = phi <16 x i32> [ [[DOTFCA_0_EXTRACT11_I]], [[IF_THEN_I]] ], [ [[TMP0]], [[IF_END_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_21_0_I:%.*]] = phi <16 x i32> [ [[DOTFCA_1_EXTRACT13_I]], [[IF_THEN_I]] ], [ [[TMP1]], [[IF_END_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_24_0_I:%.*]] = phi <2 x i32> [ [[DOTFCA_2_EXTRACT15_I]], [[IF_THEN_I]] ], [ [[TMP2]], [[IF_END_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_27_0_I:%.*]] = phi <2 x i32> [ [[DOTFCA_3_EXTRACT17_I]], [[IF_THEN_I]] ], [ [[TMP3]], [[IF_END_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_30_0_I:%.*]] = phi <2 x i32> [ [[DOTFCA_4_EXTRACT19_I]], [[IF_THEN_I]] ], [ [[TMP4]], [[IF_END_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_33_0_I:%.*]] = phi <2 x i32> [ [[DOTFCA_5_EXTRACT21_I]], [[IF_THEN_I]] ], [ [[TMP5]], [[IF_END_I]] ]
// CHECK-NEXT:    [[DOTFCA_0_0_INSERT32:%.*]] = insertvalue [[STRUCT_V256MX9]] poison, <16 x i32> [[RETVAL_SROA_0_0_I]], 0, 0
// CHECK-NEXT:    [[DOTFCA_0_1_INSERT33:%.*]] = insertvalue [[STRUCT_V256MX9]] [[DOTFCA_0_0_INSERT32]], <16 x i32> [[RETVAL_SROA_3_0_I]], 0, 1
// CHECK-NEXT:    [[DOTFCA_0_2_INSERT34:%.*]] = insertvalue [[STRUCT_V256MX9]] [[DOTFCA_0_1_INSERT33]], <2 x i32> [[RETVAL_SROA_6_0_I]], 0, 2
// CHECK-NEXT:    [[DOTFCA_0_3_INSERT35:%.*]] = insertvalue [[STRUCT_V256MX9]] [[DOTFCA_0_2_INSERT34]], <2 x i32> [[RETVAL_SROA_9_0_I]], 0, 3
// CHECK-NEXT:    [[DOTFCA_0_4_INSERT36:%.*]] = insertvalue [[STRUCT_V256MX9]] [[DOTFCA_0_3_INSERT35]], <2 x i32> [[RETVAL_SROA_12_0_I]], 0, 4
// CHECK-NEXT:    [[DOTFCA_0_5_INSERT37:%.*]] = insertvalue [[STRUCT_V256MX9]] [[DOTFCA_0_4_INSERT36]], <2 x i32> [[RETVAL_SROA_15_0_I]], 0, 5
// CHECK-NEXT:    [[DOTFCA_1_0_INSERT38:%.*]] = insertvalue [[STRUCT_V256MX9]] [[DOTFCA_0_5_INSERT37]], <16 x i32> [[RETVAL_SROA_18_0_I]], 1, 0
// CHECK-NEXT:    [[DOTFCA_1_1_INSERT39:%.*]] = insertvalue [[STRUCT_V256MX9]] [[DOTFCA_1_0_INSERT38]], <16 x i32> [[RETVAL_SROA_21_0_I]], 1, 1
// CHECK-NEXT:    [[DOTFCA_1_2_INSERT40:%.*]] = insertvalue [[STRUCT_V256MX9]] [[DOTFCA_1_1_INSERT39]], <2 x i32> [[RETVAL_SROA_24_0_I]], 1, 2
// CHECK-NEXT:    [[DOTFCA_1_3_INSERT41:%.*]] = insertvalue [[STRUCT_V256MX9]] [[DOTFCA_1_2_INSERT40]], <2 x i32> [[RETVAL_SROA_27_0_I]], 1, 3
// CHECK-NEXT:    [[DOTFCA_1_4_INSERT42:%.*]] = insertvalue [[STRUCT_V256MX9]] [[DOTFCA_1_3_INSERT41]], <2 x i32> [[RETVAL_SROA_30_0_I]], 1, 4
// CHECK-NEXT:    [[DOTFCA_1_5_INSERT43:%.*]] = insertvalue [[STRUCT_V256MX9]] [[DOTFCA_1_4_INSERT42]], <2 x i32> [[RETVAL_SROA_33_0_I]], 1, 5
// CHECK-NEXT:    ret [[STRUCT_V256MX9]] [[DOTFCA_1_5_INSERT43]]
//
v256mx9 test_insert (v256mx9 m, int idx, v128mx9 a) { return insert(m, idx, a); }
// CHECK-LABEL: @_Z20test_extract_v128mx97v256mx9i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX9:%.*]] [[A_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX9]] [[A_COERCE]], 1
// CHECK-NEXT:    [[CMP_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    [[DOTPN_I:%.*]] = select i1 [[CMP_I]], [[STRUCT_V128MX9:%.*]] [[TMP0]], [[STRUCT_V128MX9]] [[TMP1]]
// CHECK-NEXT:    ret [[STRUCT_V128MX9]] [[DOTPN_I]]
//
v128mx9 test_extract_v128mx9 (v256mx9 a, int idx) { return extract_v128mx9(a, idx); }
// CHECK-LABEL: @_Z23test_extract_v128bfp16p7v256mx9i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX9:%.*]] [[A_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX9]] [[A_COERCE]], 1
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    [[DOTPN_I_I:%.*]] = select i1 [[CMP_I_I]], [[STRUCT_V128MX9:%.*]] [[TMP0]], [[STRUCT_V128MX9]] [[TMP1]]
// CHECK-NEXT:    ret [[STRUCT_V128MX9]] [[DOTPN_I_I]]
//
v128bfp16p test_extract_v128bfp16p (v256bfp16p a, int idx) { return extract_v128bfp16p(a, idx); }
//
// CHECK-LABEL: @_Z11test_insert7v256mx9i6v64mx9(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    unreachable
//
v256mx9 test_insert (v256mx9 m, int idx, v64mx9 a) { return insert(m, idx, a); }
// CHECK-LABEL: @_Z19test_extract_v64mx97v128mx9i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V128MX9:%.*]] [[A_COERCE:%.*]], 4
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V128MX9]] [[A_COERCE]], 2
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128MX9]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128MX9]] [[A_COERCE]], 5
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128MX9]] [[A_COERCE]], 3
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128MX9]] [[A_COERCE]], 1
// CHECK-NEXT:    [[RETVAL_SROA_0_0_I:%.*]] = select i1 [[CMP_I]], <16 x i32> [[TMP2]], <16 x i32> [[TMP5]]
// CHECK-NEXT:    [[RETVAL_SROA_3_0_I:%.*]] = select i1 [[CMP_I]], <2 x i32> [[TMP1]], <2 x i32> [[TMP4]]
// CHECK-NEXT:    [[RETVAL_SROA_6_0_I:%.*]] = select i1 [[CMP_I]], <2 x i32> [[TMP0]], <2 x i32> [[TMP3]]
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX9:%.*]] poison, <16 x i32> [[RETVAL_SROA_0_0_I]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX9]] [[DOTFCA_0_INSERT_I]], <2 x i32> [[RETVAL_SROA_3_0_I]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX9]] [[DOTFCA_1_INSERT_I]], <2 x i32> [[RETVAL_SROA_6_0_I]], 2
// CHECK-NEXT:    ret [[STRUCT_V64MX9]] [[DOTFCA_2_INSERT_I]]
//
v64mx9 test_extract_v64mx9 (v128mx9 a, int idx) { return extract_v64mx9(a, idx); }
// CHECK-LABEL: @_Z22test_extract_v64bfp16p7v128mx9i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V128MX9:%.*]] [[A_COERCE:%.*]], 4
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V128MX9]] [[A_COERCE]], 2
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128MX9]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128MX9]] [[A_COERCE]], 5
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128MX9]] [[A_COERCE]], 3
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128MX9]] [[A_COERCE]], 1
// CHECK-NEXT:    [[RETVAL_SROA_0_0_I_I:%.*]] = select i1 [[CMP_I_I]], <16 x i32> [[TMP2]], <16 x i32> [[TMP5]]
// CHECK-NEXT:    [[RETVAL_SROA_3_0_I_I:%.*]] = select i1 [[CMP_I_I]], <2 x i32> [[TMP1]], <2 x i32> [[TMP4]]
// CHECK-NEXT:    [[RETVAL_SROA_6_0_I_I:%.*]] = select i1 [[CMP_I_I]], <2 x i32> [[TMP0]], <2 x i32> [[TMP3]]
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64MX9:%.*]] poison, <16 x i32> [[RETVAL_SROA_0_0_I_I]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64MX9]] [[DOTFCA_0_INSERT_I_I]], <2 x i32> [[RETVAL_SROA_3_0_I_I]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64MX9]] [[DOTFCA_1_INSERT_I_I]], <2 x i32> [[RETVAL_SROA_6_0_I_I]], 2
// CHECK-NEXT:    ret [[STRUCT_V64MX9]] [[DOTFCA_2_INSERT_I_I]]
//
v64bfp16p test_extract_v64bfp16p (v128bfp16p a, int idx) { return extract_v64bfp16p(a, idx); }

// CHECK-LABEL: @_Z17test_extract_expo6v64mx6i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64MX6:%.*]] [[M_COERCE:%.*]], 3
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64MX6]] [[M_COERCE]], 2
// CHECK-NEXT:    [[RETVAL_0_I:%.*]] = select i1 [[CMP_I]], i32 [[TMP0]], i32 [[TMP1]]
// CHECK-NEXT:    ret i32 [[RETVAL_0_I]]
//
int test_extract_expo (v64mx6 m, int idx) { return extract_expo(m, idx); }
// CHECK-LABEL: @_Z11test_insert6v64mx6ii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64MX6:%.*]] [[M_COERCE:%.*]], 2
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64MX6]] [[M_COERCE]], 3
// CHECK-NEXT:    [[M_SROA_3_0_I:%.*]] = select i1 [[CMP_I]], i32 [[TMP0]], i32 [[EXPO:%.*]]
// CHECK-NEXT:    [[M_SROA_5_0_I:%.*]] = select i1 [[CMP_I]], i32 [[EXPO]], i32 [[TMP1]]
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX6]] [[M_COERCE]], i32 [[M_SROA_3_0_I]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX6]] [[DOTFCA_2_INSERT_I]], i32 [[M_SROA_5_0_I]], 3
// CHECK-NEXT:    ret [[STRUCT_V64MX6]] [[DOTFCA_3_INSERT_I]]
//
v64mx6 test_insert (v64mx6 m, int idx, int expo) { return insert(m, idx, expo); }
//
// CHECK-LABEL: @_Z17test_extract_expo6v64mx4i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64MX4:%.*]] [[M_COERCE:%.*]], 3
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64MX4]] [[M_COERCE]], 2
// CHECK-NEXT:    [[RETVAL_0_I:%.*]] = select i1 [[CMP_I]], i32 [[TMP0]], i32 [[TMP1]]
// CHECK-NEXT:    ret i32 [[RETVAL_0_I]]
//
int test_extract_expo (v64mx4 m, int idx) { return extract_expo(m, idx); }
// CHECK-LABEL: @_Z11test_insert6v64mx4ii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64MX4:%.*]] [[M_COERCE:%.*]], 2
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64MX4]] [[M_COERCE]], 3
// CHECK-NEXT:    [[M_SROA_3_0_I:%.*]] = select i1 [[CMP_I]], i32 [[TMP0]], i32 [[EXPO:%.*]]
// CHECK-NEXT:    [[M_SROA_5_0_I:%.*]] = select i1 [[CMP_I]], i32 [[EXPO]], i32 [[TMP1]]
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX4]] [[M_COERCE]], i32 [[M_SROA_3_0_I]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX4]] [[DOTFCA_2_INSERT_I]], i32 [[M_SROA_5_0_I]], 3
// CHECK-NEXT:    ret [[STRUCT_V64MX4]] [[DOTFCA_3_INSERT_I]]
//
v64mx4 test_insert (v64mx4 m, int idx, int expo) { return insert(m, idx, expo); }
//
// CHECK-LABEL: @_Z25test_extract_msb_v16uint47v256mx6i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX6:%.*]] [[M_COERCE:%.*]], 5
// CHECK-NEXT:    switch i32 [[IDX:%.*]], label [[IF_ELSE6_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[IF_THEN_I:%.*]]
// CHECK-NEXT:      i32 1, label [[_ZL20EXTRACT_MSB_V16UINT47V256MX6I_EXIT:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN5_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then.i:
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 4
// CHECK-NEXT:    br label [[_ZL20EXTRACT_MSB_V16UINT47V256MX6I_EXIT]]
// CHECK:       if.then5.i:
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 6
// CHECK-NEXT:    br label [[_ZL20EXTRACT_MSB_V16UINT47V256MX6I_EXIT]]
// CHECK:       if.else6.i:
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 7
// CHECK-NEXT:    br label [[_ZL20EXTRACT_MSB_V16UINT47V256MX6I_EXIT]]
// CHECK:       _ZL20extract_msb_v16uint47v256mx6i.exit:
// CHECK-NEXT:    [[TEMP_0_I:%.*]] = phi <2 x i32> [ [[TMP1]], [[IF_THEN_I]] ], [ [[TMP2]], [[IF_THEN5_I]] ], [ [[TMP3]], [[IF_ELSE6_I]] ], [ [[TMP0]], [[ENTRY:%.*]] ]
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <2 x i32> [[TEMP_0_I]] to <8 x i8>
// CHECK-NEXT:    ret <8 x i8> [[TMP4]]
//
v16uint4 test_extract_msb_v16uint4 (v256mx6 m, int idx) { return extract_msb_v16uint4(m, idx); }
// CHECK-LABEL: @_Z25test_extract_msb_v32uint47v256mx6i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX6:%.*]] [[M_COERCE:%.*]], 5
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 4
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to <8 x i8>
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <8 x i8> [[TMP2]], <8 x i8> poison, <16 x i32> <i32 0, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i8> [[TMP2]], <8 x i8> poison, <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 4, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <2 x i32> [[TMP0]] to <8 x i8>
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i8> [[TMP5]], <8 x i8> poison, <16 x i32> <i32 0, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <8 x i8> [[TMP5]], <8 x i8> poison, <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 4, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <16 x i8> [[TMP3]], <16 x i8> <i8 poison, i8 poison, i8 poison, i8 poison, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0>, <16 x i32> <i32 0, i32 poison, i32 poison, i32 poison, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> [[TMP4]], <16 x i32> <i32 0, i32 20, i32 poison, i32 poison, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <16 x i8> [[TMP9]], <16 x i8> [[TMP6]], <16 x i32> <i32 0, i32 1, i32 16, i32 poison, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[VECINIT23_I:%.*]] = shufflevector <16 x i8> [[TMP10]], <16 x i8> [[TMP7]], <16 x i32> <i32 0, i32 1, i32 2, i32 20, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 7
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 6
// CHECK-NEXT:    [[TMP13:%.*]] = bitcast <2 x i32> [[TMP12]] to <8 x i8>
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <8 x i8> [[TMP13]], <8 x i8> poison, <16 x i32> <i32 0, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[TMP15:%.*]] = shufflevector <8 x i8> [[TMP13]], <8 x i8> poison, <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 4, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[TMP16:%.*]] = bitcast <2 x i32> [[TMP11]] to <8 x i8>
// CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <8 x i8> [[TMP16]], <8 x i8> poison, <16 x i32> <i32 0, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <8 x i8> [[TMP16]], <8 x i8> poison, <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 4, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[TMP19:%.*]] = shufflevector <16 x i8> [[TMP14]], <16 x i8> <i8 poison, i8 poison, i8 poison, i8 poison, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0>, <16 x i32> <i32 0, i32 poison, i32 poison, i32 poison, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <16 x i8> [[TMP19]], <16 x i8> [[TMP15]], <16 x i32> <i32 0, i32 20, i32 poison, i32 poison, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP21:%.*]] = shufflevector <16 x i8> [[TMP20]], <16 x i8> [[TMP17]], <16 x i32> <i32 0, i32 1, i32 16, i32 poison, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[VECINIT50_I:%.*]] = shufflevector <16 x i8> [[TMP21]], <16 x i8> [[TMP18]], <16 x i32> <i32 0, i32 1, i32 2, i32 20, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[RETVAL_0_I:%.*]] = select i1 [[CMP_I]], <16 x i8> [[VECINIT23_I]], <16 x i8> [[VECINIT50_I]]
// CHECK-NEXT:    ret <16 x i8> [[RETVAL_0_I]]
//
v32uint4 test_extract_msb_v32uint4 (v256mx6 m, int idx) { return extract_msb_v32uint4(m, idx); }
// CHECK-LABEL: @_Z11test_update7v256mx6iDv8_DU8_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX6:%.*]] [[S_COERCE:%.*]], 4
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 5
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 6
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 7
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <8 x i8> [[M:%.*]] to <2 x i32>
// CHECK-NEXT:    switch i32 [[IDX:%.*]], label [[IF_ELSE6_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[_ZL6UPDATE7V256MX6IDV8_DU8__EXIT:%.*]]
// CHECK-NEXT:      i32 1, label [[IF_THEN2_I:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN5_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then2.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX6IDV8_DU8__EXIT]]
// CHECK:       if.then5.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX6IDV8_DU8__EXIT]]
// CHECK:       if.else6.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX6IDV8_DU8__EXIT]]
// CHECK:       _ZL6update7v256mx6iDv8_DU8_.exit:
// CHECK-NEXT:    [[S_SROA_5_0_I:%.*]] = phi <2 x i32> [ [[TMP0]], [[IF_THEN2_I]] ], [ [[TMP0]], [[IF_THEN5_I]] ], [ [[TMP0]], [[IF_ELSE6_I]] ], [ [[TMP4]], [[ENTRY:%.*]] ]
// CHECK-NEXT:    [[S_SROA_7_0_I:%.*]] = phi <2 x i32> [ [[TMP4]], [[IF_THEN2_I]] ], [ [[TMP1]], [[IF_THEN5_I]] ], [ [[TMP1]], [[IF_ELSE6_I]] ], [ [[TMP1]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_9_0_I:%.*]] = phi <2 x i32> [ [[TMP2]], [[IF_THEN2_I]] ], [ [[TMP4]], [[IF_THEN5_I]] ], [ [[TMP2]], [[IF_ELSE6_I]] ], [ [[TMP2]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_11_0_I:%.*]] = phi <2 x i32> [ [[TMP3]], [[IF_THEN2_I]] ], [ [[TMP3]], [[IF_THEN5_I]] ], [ [[TMP4]], [[IF_ELSE6_I]] ], [ [[TMP3]], [[ENTRY]] ]
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 15
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 14
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 13
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 12
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 11
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 10
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 9
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 8
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[S_COERCE]], <2 x i32> [[S_SROA_5_0_I]], 4
// CHECK-NEXT:    [[DOTFCA_5_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_4_INSERT_I]], <2 x i32> [[S_SROA_7_0_I]], 5
// CHECK-NEXT:    [[DOTFCA_6_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_5_INSERT_I]], <2 x i32> [[S_SROA_9_0_I]], 6
// CHECK-NEXT:    [[DOTFCA_7_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_6_INSERT_I]], <2 x i32> [[S_SROA_11_0_I]], 7
// CHECK-NEXT:    [[DOTFCA_8_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_7_INSERT_I]], i32 [[TMP12]], 8
// CHECK-NEXT:    [[DOTFCA_9_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_8_INSERT_I]], i32 [[TMP11]], 9
// CHECK-NEXT:    [[DOTFCA_10_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_9_INSERT_I]], i32 [[TMP10]], 10
// CHECK-NEXT:    [[DOTFCA_11_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_10_INSERT_I]], i32 [[TMP9]], 11
// CHECK-NEXT:    [[DOTFCA_12_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_11_INSERT_I]], i32 [[TMP8]], 12
// CHECK-NEXT:    [[DOTFCA_13_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_12_INSERT_I]], i32 [[TMP7]], 13
// CHECK-NEXT:    [[DOTFCA_14_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_13_INSERT_I]], i32 [[TMP6]], 14
// CHECK-NEXT:    [[DOTFCA_15_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_14_INSERT_I]], i32 [[TMP5]], 15
// CHECK-NEXT:    ret [[STRUCT_V256MX6]] [[DOTFCA_15_INSERT_I]]
//
v256mx6 test_update (v256mx6 s, int idx, v16uint4 m) { return update(s, idx, m); }
//
// CHECK-LABEL: @_Z11test_update7v256mx6iDv16_DU8_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i8> [[M:%.*]] to <4 x i32>
// CHECK-NEXT:    [[VECINIT3_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[VECINIT9_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[CMP_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    br i1 [[CMP_I]], label [[IF_THEN_I:%.*]], label [[IF_ELSE_I:%.*]]
// CHECK:       if.then.i:
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX6:%.*]] [[S_COERCE:%.*]], 7
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 6
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX6IDV16_DU8__EXIT:%.*]]
// CHECK:       if.else.i:
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 5
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 4
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX6IDV16_DU8__EXIT]]
// CHECK:       _ZL6update7v256mx6iDv16_DU8_.exit:
// CHECK-NEXT:    [[S_SROA_5_0_I:%.*]] = phi <2 x i32> [ [[VECINIT3_I]], [[IF_THEN_I]] ], [ [[TMP4]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[S_SROA_7_0_I:%.*]] = phi <2 x i32> [ [[VECINIT9_I]], [[IF_THEN_I]] ], [ [[TMP3]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[S_SROA_9_0_I:%.*]] = phi <2 x i32> [ [[TMP2]], [[IF_THEN_I]] ], [ [[VECINIT3_I]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[S_SROA_11_0_I:%.*]] = phi <2 x i32> [ [[TMP1]], [[IF_THEN_I]] ], [ [[VECINIT9_I]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 15
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 14
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 13
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 12
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 11
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 10
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 9
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 8
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[S_COERCE]], <2 x i32> [[S_SROA_5_0_I]], 4
// CHECK-NEXT:    [[DOTFCA_5_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_4_INSERT_I]], <2 x i32> [[S_SROA_7_0_I]], 5
// CHECK-NEXT:    [[DOTFCA_6_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_5_INSERT_I]], <2 x i32> [[S_SROA_9_0_I]], 6
// CHECK-NEXT:    [[DOTFCA_7_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_6_INSERT_I]], <2 x i32> [[S_SROA_11_0_I]], 7
// CHECK-NEXT:    [[DOTFCA_8_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_7_INSERT_I]], i32 [[TMP12]], 8
// CHECK-NEXT:    [[DOTFCA_9_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_8_INSERT_I]], i32 [[TMP11]], 9
// CHECK-NEXT:    [[DOTFCA_10_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_9_INSERT_I]], i32 [[TMP10]], 10
// CHECK-NEXT:    [[DOTFCA_11_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_10_INSERT_I]], i32 [[TMP9]], 11
// CHECK-NEXT:    [[DOTFCA_12_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_11_INSERT_I]], i32 [[TMP8]], 12
// CHECK-NEXT:    [[DOTFCA_13_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_12_INSERT_I]], i32 [[TMP7]], 13
// CHECK-NEXT:    [[DOTFCA_14_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_13_INSERT_I]], i32 [[TMP6]], 14
// CHECK-NEXT:    [[DOTFCA_15_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_14_INSERT_I]], i32 [[TMP5]], 15
// CHECK-NEXT:    ret [[STRUCT_V256MX6]] [[DOTFCA_15_INSERT_I]]
//
v256mx6 test_update (v256mx6 s, int idx, v32uint4 m) { return update(s, idx, m); }
// CHECK-LABEL: @_Z21test_extract_expo_int7v256mx6i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    switch i32 [[IDX:%.*]], label [[SW_DEFAULT_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[SW_BB_I:%.*]]
// CHECK-NEXT:      i32 1, label [[SW_BB1_I:%.*]]
// CHECK-NEXT:      i32 2, label [[SW_BB2_I:%.*]]
// CHECK-NEXT:      i32 3, label [[SW_BB3_I:%.*]]
// CHECK-NEXT:      i32 4, label [[SW_BB4_I:%.*]]
// CHECK-NEXT:      i32 5, label [[SW_BB5_I:%.*]]
// CHECK-NEXT:      i32 6, label [[SW_BB6_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       sw.bb.i:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX6:%.*]] [[M_COERCE:%.*]], 12
// CHECK-NEXT:    br label [[_ZL16EXTRACT_EXPO_INT7V256MX6I_EXIT:%.*]]
// CHECK:       sw.bb1.i:
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 13
// CHECK-NEXT:    br label [[_ZL16EXTRACT_EXPO_INT7V256MX6I_EXIT]]
// CHECK:       sw.bb2.i:
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 14
// CHECK-NEXT:    br label [[_ZL16EXTRACT_EXPO_INT7V256MX6I_EXIT]]
// CHECK:       sw.bb3.i:
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 15
// CHECK-NEXT:    br label [[_ZL16EXTRACT_EXPO_INT7V256MX6I_EXIT]]
// CHECK:       sw.bb4.i:
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 8
// CHECK-NEXT:    br label [[_ZL16EXTRACT_EXPO_INT7V256MX6I_EXIT]]
// CHECK:       sw.bb5.i:
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 9
// CHECK-NEXT:    br label [[_ZL16EXTRACT_EXPO_INT7V256MX6I_EXIT]]
// CHECK:       sw.bb6.i:
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 10
// CHECK-NEXT:    br label [[_ZL16EXTRACT_EXPO_INT7V256MX6I_EXIT]]
// CHECK:       sw.default.i:
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 11
// CHECK-NEXT:    br label [[_ZL16EXTRACT_EXPO_INT7V256MX6I_EXIT]]
// CHECK:       _ZL16extract_expo_int7v256mx6i.exit:
// CHECK-NEXT:    [[RETVAL_0_I:%.*]] = phi i32 [ [[TMP7]], [[SW_DEFAULT_I]] ], [ [[TMP6]], [[SW_BB6_I]] ], [ [[TMP5]], [[SW_BB5_I]] ], [ [[TMP4]], [[SW_BB4_I]] ], [ [[TMP3]], [[SW_BB3_I]] ], [ [[TMP2]], [[SW_BB2_I]] ], [ [[TMP1]], [[SW_BB1_I]] ], [ [[TMP0]], [[SW_BB_I]] ]
// CHECK-NEXT:    ret i32 [[RETVAL_0_I]]
//
int test_extract_expo_int (v256mx6 m, int idx) { return extract_expo_int(m, idx); }
// CHECK-LABEL: @_Z24test_extract_expo_v8int87v256mx6i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    switch i32 [[IDX:%.*]], label [[SW_DEFAULT_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[SW_BB_I:%.*]]
// CHECK-NEXT:      i32 1, label [[SW_BB9_I:%.*]]
// CHECK-NEXT:      i32 2, label [[SW_BB20_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       sw.bb.i:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX6:%.*]] [[M_COERCE:%.*]], 13
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 12
// CHECK-NEXT:    br label [[_ZL19EXTRACT_EXPO_V8INT87V256MX6I_EXIT:%.*]]
// CHECK:       sw.bb9.i:
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 15
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 14
// CHECK-NEXT:    br label [[_ZL19EXTRACT_EXPO_V8INT87V256MX6I_EXIT]]
// CHECK:       sw.bb20.i:
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 9
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 8
// CHECK-NEXT:    br label [[_ZL19EXTRACT_EXPO_V8INT87V256MX6I_EXIT]]
// CHECK:       sw.default.i:
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 11
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 10
// CHECK-NEXT:    br label [[_ZL19EXTRACT_EXPO_V8INT87V256MX6I_EXIT]]
// CHECK:       _ZL19extract_expo_v8int87v256mx6i.exit:
// CHECK-NEXT:    [[DOTSINK41_I:%.*]] = phi i32 [ [[TMP7]], [[SW_DEFAULT_I]] ], [ [[TMP5]], [[SW_BB20_I]] ], [ [[TMP3]], [[SW_BB9_I]] ], [ [[TMP1]], [[SW_BB_I]] ]
// CHECK-NEXT:    [[DOTSINK_I:%.*]] = phi i32 [ [[TMP6]], [[SW_DEFAULT_I]] ], [ [[TMP4]], [[SW_BB20_I]] ], [ [[TMP2]], [[SW_BB9_I]] ], [ [[TMP0]], [[SW_BB_I]] ]
// CHECK-NEXT:    [[CONV31_I:%.*]] = trunc i32 [[DOTSINK41_I]] to i8
// CHECK-NEXT:    [[CONV33_I:%.*]] = trunc i32 [[DOTSINK_I]] to i8
// CHECK-NEXT:    [[TMP8:%.*]] = insertelement <8 x i8> <i8 poison, i8 poison, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0>, i8 [[CONV31_I]], i64 0
// CHECK-NEXT:    [[VECINIT40_I:%.*]] = insertelement <8 x i8> [[TMP8]], i8 [[CONV33_I]], i64 1
// CHECK-NEXT:    ret <8 x i8> [[VECINIT40_I]]
//
v8int8 test_extract_expo_v8int8 (v256mx6 m, int idx) { return extract_expo_v8int8(m, idx); }
// CHECK-LABEL: @_Z11test_update7v256mx6ii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX6:%.*]] [[S_COERCE:%.*]], 8
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 9
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 10
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 11
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 12
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 13
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 14
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 15
// CHECK-NEXT:    switch i32 [[IDX:%.*]], label [[SW_DEFAULT_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[_ZL6UPDATE7V256MX6II_EXIT:%.*]]
// CHECK-NEXT:      i32 1, label [[SW_BB1_I:%.*]]
// CHECK-NEXT:      i32 2, label [[SW_BB2_I:%.*]]
// CHECK-NEXT:      i32 3, label [[SW_BB3_I:%.*]]
// CHECK-NEXT:      i32 4, label [[SW_BB4_I:%.*]]
// CHECK-NEXT:      i32 5, label [[SW_BB5_I:%.*]]
// CHECK-NEXT:      i32 6, label [[SW_BB6_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       sw.bb1.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX6II_EXIT]]
// CHECK:       sw.bb2.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX6II_EXIT]]
// CHECK:       sw.bb3.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX6II_EXIT]]
// CHECK:       sw.bb4.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX6II_EXIT]]
// CHECK:       sw.bb5.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX6II_EXIT]]
// CHECK:       sw.bb6.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX6II_EXIT]]
// CHECK:       sw.default.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX6II_EXIT]]
// CHECK:       _ZL6update7v256mx6ii.exit:
// CHECK-NEXT:    [[S_SROA_9_0_I:%.*]] = phi i32 [ [[TMP0]], [[SW_DEFAULT_I]] ], [ [[TMP0]], [[SW_BB6_I]] ], [ [[TMP0]], [[SW_BB5_I]] ], [ [[M:%.*]], [[SW_BB4_I]] ], [ [[TMP0]], [[SW_BB3_I]] ], [ [[TMP0]], [[SW_BB2_I]] ], [ [[TMP0]], [[SW_BB1_I]] ], [ [[TMP0]], [[ENTRY:%.*]] ]
// CHECK-NEXT:    [[S_SROA_11_0_I:%.*]] = phi i32 [ [[TMP1]], [[SW_DEFAULT_I]] ], [ [[TMP1]], [[SW_BB6_I]] ], [ [[M]], [[SW_BB5_I]] ], [ [[TMP1]], [[SW_BB4_I]] ], [ [[TMP1]], [[SW_BB3_I]] ], [ [[TMP1]], [[SW_BB2_I]] ], [ [[TMP1]], [[SW_BB1_I]] ], [ [[TMP1]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_13_0_I:%.*]] = phi i32 [ [[TMP2]], [[SW_DEFAULT_I]] ], [ [[M]], [[SW_BB6_I]] ], [ [[TMP2]], [[SW_BB5_I]] ], [ [[TMP2]], [[SW_BB4_I]] ], [ [[TMP2]], [[SW_BB3_I]] ], [ [[TMP2]], [[SW_BB2_I]] ], [ [[TMP2]], [[SW_BB1_I]] ], [ [[TMP2]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_15_0_I:%.*]] = phi i32 [ [[M]], [[SW_DEFAULT_I]] ], [ [[TMP3]], [[SW_BB6_I]] ], [ [[TMP3]], [[SW_BB5_I]] ], [ [[TMP3]], [[SW_BB4_I]] ], [ [[TMP3]], [[SW_BB3_I]] ], [ [[TMP3]], [[SW_BB2_I]] ], [ [[TMP3]], [[SW_BB1_I]] ], [ [[TMP3]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_17_0_I:%.*]] = phi i32 [ [[TMP4]], [[SW_DEFAULT_I]] ], [ [[TMP4]], [[SW_BB6_I]] ], [ [[TMP4]], [[SW_BB5_I]] ], [ [[TMP4]], [[SW_BB4_I]] ], [ [[TMP4]], [[SW_BB3_I]] ], [ [[TMP4]], [[SW_BB2_I]] ], [ [[TMP4]], [[SW_BB1_I]] ], [ [[M]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_19_0_I:%.*]] = phi i32 [ [[TMP5]], [[SW_DEFAULT_I]] ], [ [[TMP5]], [[SW_BB6_I]] ], [ [[TMP5]], [[SW_BB5_I]] ], [ [[TMP5]], [[SW_BB4_I]] ], [ [[TMP5]], [[SW_BB3_I]] ], [ [[TMP5]], [[SW_BB2_I]] ], [ [[M]], [[SW_BB1_I]] ], [ [[TMP5]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_21_0_I:%.*]] = phi i32 [ [[TMP6]], [[SW_DEFAULT_I]] ], [ [[TMP6]], [[SW_BB6_I]] ], [ [[TMP6]], [[SW_BB5_I]] ], [ [[TMP6]], [[SW_BB4_I]] ], [ [[TMP6]], [[SW_BB3_I]] ], [ [[M]], [[SW_BB2_I]] ], [ [[TMP6]], [[SW_BB1_I]] ], [ [[TMP6]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_23_0_I:%.*]] = phi i32 [ [[TMP7]], [[SW_DEFAULT_I]] ], [ [[TMP7]], [[SW_BB6_I]] ], [ [[TMP7]], [[SW_BB5_I]] ], [ [[TMP7]], [[SW_BB4_I]] ], [ [[M]], [[SW_BB3_I]] ], [ [[TMP7]], [[SW_BB2_I]] ], [ [[TMP7]], [[SW_BB1_I]] ], [ [[TMP7]], [[ENTRY]] ]
// CHECK-NEXT:    [[DOTFCA_8_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[S_COERCE]], i32 [[S_SROA_9_0_I]], 8
// CHECK-NEXT:    [[DOTFCA_9_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_8_INSERT_I]], i32 [[S_SROA_11_0_I]], 9
// CHECK-NEXT:    [[DOTFCA_10_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_9_INSERT_I]], i32 [[S_SROA_13_0_I]], 10
// CHECK-NEXT:    [[DOTFCA_11_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_10_INSERT_I]], i32 [[S_SROA_15_0_I]], 11
// CHECK-NEXT:    [[DOTFCA_12_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_11_INSERT_I]], i32 [[S_SROA_17_0_I]], 12
// CHECK-NEXT:    [[DOTFCA_13_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_12_INSERT_I]], i32 [[S_SROA_19_0_I]], 13
// CHECK-NEXT:    [[DOTFCA_14_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_13_INSERT_I]], i32 [[S_SROA_21_0_I]], 14
// CHECK-NEXT:    [[DOTFCA_15_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_14_INSERT_I]], i32 [[S_SROA_23_0_I]], 15
// CHECK-NEXT:    ret [[STRUCT_V256MX6]] [[DOTFCA_15_INSERT_I]]
//
v256mx6 test_update (v256mx6 s, int idx, int m) { return update(s, idx, m); }
// CHECK-LABEL: @_Z11test_update7v256mx6iDv8_a(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX6:%.*]] [[S_COERCE:%.*]], 8
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 9
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 10
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 11
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 12
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 13
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 14
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 15
// CHECK-NEXT:    [[TMP8:%.*]] = bitcast <8 x i8> [[M:%.*]] to <2 x i32>
// CHECK-NEXT:    [[VECEXT14_I:%.*]] = extractelement <2 x i32> [[TMP8]], i64 0
// CHECK-NEXT:    [[VECEXT16_I:%.*]] = extractelement <2 x i32> [[TMP8]], i64 1
// CHECK-NEXT:    switch i32 [[IDX:%.*]], label [[SW_DEFAULT_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[_ZL6UPDATE7V256MX6IDV8_A_EXIT:%.*]]
// CHECK-NEXT:      i32 1, label [[SW_BB3_I:%.*]]
// CHECK-NEXT:      i32 2, label [[SW_BB8_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       sw.bb3.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX6IDV8_A_EXIT]]
// CHECK:       sw.bb8.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX6IDV8_A_EXIT]]
// CHECK:       sw.default.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX6IDV8_A_EXIT]]
// CHECK:       _ZL6update7v256mx6iDv8_a.exit:
// CHECK-NEXT:    [[S_SROA_9_0_I:%.*]] = phi i32 [ [[TMP0]], [[SW_DEFAULT_I]] ], [ [[VECEXT14_I]], [[SW_BB8_I]] ], [ [[TMP0]], [[SW_BB3_I]] ], [ [[TMP0]], [[ENTRY:%.*]] ]
// CHECK-NEXT:    [[S_SROA_11_0_I:%.*]] = phi i32 [ [[TMP1]], [[SW_DEFAULT_I]] ], [ [[VECEXT16_I]], [[SW_BB8_I]] ], [ [[TMP1]], [[SW_BB3_I]] ], [ [[TMP1]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_13_0_I:%.*]] = phi i32 [ [[VECEXT14_I]], [[SW_DEFAULT_I]] ], [ [[TMP2]], [[SW_BB8_I]] ], [ [[TMP2]], [[SW_BB3_I]] ], [ [[TMP2]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_15_0_I:%.*]] = phi i32 [ [[VECEXT16_I]], [[SW_DEFAULT_I]] ], [ [[TMP3]], [[SW_BB8_I]] ], [ [[TMP3]], [[SW_BB3_I]] ], [ [[TMP3]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_17_0_I:%.*]] = phi i32 [ [[TMP4]], [[SW_DEFAULT_I]] ], [ [[TMP4]], [[SW_BB8_I]] ], [ [[TMP4]], [[SW_BB3_I]] ], [ [[VECEXT14_I]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_19_0_I:%.*]] = phi i32 [ [[TMP5]], [[SW_DEFAULT_I]] ], [ [[TMP5]], [[SW_BB8_I]] ], [ [[TMP5]], [[SW_BB3_I]] ], [ [[VECEXT16_I]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_21_0_I:%.*]] = phi i32 [ [[TMP6]], [[SW_DEFAULT_I]] ], [ [[TMP6]], [[SW_BB8_I]] ], [ [[VECEXT14_I]], [[SW_BB3_I]] ], [ [[TMP6]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_23_0_I:%.*]] = phi i32 [ [[TMP7]], [[SW_DEFAULT_I]] ], [ [[TMP7]], [[SW_BB8_I]] ], [ [[VECEXT16_I]], [[SW_BB3_I]] ], [ [[TMP7]], [[ENTRY]] ]
// CHECK-NEXT:    [[DOTFCA_8_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[S_COERCE]], i32 [[S_SROA_9_0_I]], 8
// CHECK-NEXT:    [[DOTFCA_9_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_8_INSERT_I]], i32 [[S_SROA_11_0_I]], 9
// CHECK-NEXT:    [[DOTFCA_10_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_9_INSERT_I]], i32 [[S_SROA_13_0_I]], 10
// CHECK-NEXT:    [[DOTFCA_11_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_10_INSERT_I]], i32 [[S_SROA_15_0_I]], 11
// CHECK-NEXT:    [[DOTFCA_12_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_11_INSERT_I]], i32 [[S_SROA_17_0_I]], 12
// CHECK-NEXT:    [[DOTFCA_13_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_12_INSERT_I]], i32 [[S_SROA_19_0_I]], 13
// CHECK-NEXT:    [[DOTFCA_14_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_13_INSERT_I]], i32 [[S_SROA_21_0_I]], 14
// CHECK-NEXT:    [[DOTFCA_15_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_14_INSERT_I]], i32 [[S_SROA_23_0_I]], 15
// CHECK-NEXT:    ret [[STRUCT_V256MX6]] [[DOTFCA_15_INSERT_I]]
//
v256mx6 test_update (v256mx6 s, int idx, v8int8 m) { return update(s, idx, m); }
// CHECK-LABEL: @_Z21test_extract_v64uint47v256mx6i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX6:%.*]] [[M_COERCE:%.*]], 1
// CHECK-NEXT:    switch i32 [[IDX:%.*]], label [[IF_ELSE6_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[IF_THEN_I:%.*]]
// CHECK-NEXT:      i32 1, label [[_ZL16EXTRACT_V64UINT47V256MX6I_EXIT:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN5_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then.i:
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 0
// CHECK-NEXT:    br label [[_ZL16EXTRACT_V64UINT47V256MX6I_EXIT]]
// CHECK:       if.then5.i:
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 2
// CHECK-NEXT:    br label [[_ZL16EXTRACT_V64UINT47V256MX6I_EXIT]]
// CHECK:       if.else6.i:
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 3
// CHECK-NEXT:    br label [[_ZL16EXTRACT_V64UINT47V256MX6I_EXIT]]
// CHECK:       _ZL16extract_v64uint47v256mx6i.exit:
// CHECK-NEXT:    [[TEMP_0_I:%.*]] = phi <8 x i32> [ [[TMP1]], [[IF_THEN_I]] ], [ [[TMP2]], [[IF_THEN5_I]] ], [ [[TMP3]], [[IF_ELSE6_I]] ], [ [[TMP0]], [[ENTRY:%.*]] ]
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <8 x i32> [[TEMP_0_I]] to <32 x i8>
// CHECK-NEXT:    ret <32 x i8> [[TMP4]]
//
v64uint4 test_extract_v64uint4 (v256mx6 m, int idx) { return extract_v64uint4(m, idx); }
// CHECK-LABEL: @_Z22test_extract_v128uint47v256mx6i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX6:%.*]] [[M_COERCE:%.*]], 1
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 3
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 2
// CHECK-NEXT:    [[TEMP0_0_I:%.*]] = select i1 [[CMP_I]], <8 x i32> [[TMP1]], <8 x i32> [[TMP3]]
// CHECK-NEXT:    [[TEMP1_0_I:%.*]] = select i1 [[CMP_I]], <8 x i32> [[TMP0]], <8 x i32> [[TMP2]]
// CHECK-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <8 x i32> [[TEMP0_0_I]], <8 x i32> [[TEMP1_0_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <16 x i32> [[SHUFFLE_I_I_I]] to <64 x i8>
// CHECK-NEXT:    ret <64 x i8> [[TMP4]]
//
v128uint4 test_extract_v128uint4 (v256mx6 m, int idx) { return extract_v128uint4(m, idx); }
// CHECK-LABEL: @_Z11test_update7v256mx6iDv32_DU8_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX6:%.*]] [[S_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 2
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 3
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <32 x i8> [[M:%.*]] to <8 x i32>
// CHECK-NEXT:    switch i32 [[IDX:%.*]], label [[IF_ELSE6_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[_ZL6UPDATE7V256MX6IDV32_DU8__EXIT:%.*]]
// CHECK-NEXT:      i32 1, label [[IF_THEN2_I:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN5_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then2.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX6IDV32_DU8__EXIT]]
// CHECK:       if.then5.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX6IDV32_DU8__EXIT]]
// CHECK:       if.else6.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX6IDV32_DU8__EXIT]]
// CHECK:       _ZL6update7v256mx6iDv32_DU8_.exit:
// CHECK-NEXT:    [[S_SROA_3_0_I:%.*]] = phi <8 x i32> [ [[TMP4]], [[IF_THEN2_I]] ], [ [[TMP1]], [[IF_THEN5_I]] ], [ [[TMP1]], [[IF_ELSE6_I]] ], [ [[TMP1]], [[ENTRY:%.*]] ]
// CHECK-NEXT:    [[S_SROA_0_0_I:%.*]] = phi <8 x i32> [ [[TMP0]], [[IF_THEN2_I]] ], [ [[TMP0]], [[IF_THEN5_I]] ], [ [[TMP0]], [[IF_ELSE6_I]] ], [ [[TMP4]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_5_0_I:%.*]] = phi <8 x i32> [ [[TMP2]], [[IF_THEN2_I]] ], [ [[TMP4]], [[IF_THEN5_I]] ], [ [[TMP2]], [[IF_ELSE6_I]] ], [ [[TMP2]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_7_0_I:%.*]] = phi <8 x i32> [ [[TMP3]], [[IF_THEN2_I]] ], [ [[TMP3]], [[IF_THEN5_I]] ], [ [[TMP4]], [[IF_ELSE6_I]] ], [ [[TMP3]], [[ENTRY]] ]
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 15
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 14
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 13
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 12
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 11
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 10
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 9
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 8
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 7
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 6
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 5
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 4
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] poison, <8 x i32> [[S_SROA_0_0_I]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_0_INSERT_I]], <8 x i32> [[S_SROA_3_0_I]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_1_INSERT_I]], <8 x i32> [[S_SROA_5_0_I]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_2_INSERT_I]], <8 x i32> [[S_SROA_7_0_I]], 3
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_3_INSERT_I]], <2 x i32> [[TMP16]], 4
// CHECK-NEXT:    [[DOTFCA_5_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_4_INSERT_I]], <2 x i32> [[TMP15]], 5
// CHECK-NEXT:    [[DOTFCA_6_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_5_INSERT_I]], <2 x i32> [[TMP14]], 6
// CHECK-NEXT:    [[DOTFCA_7_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_6_INSERT_I]], <2 x i32> [[TMP13]], 7
// CHECK-NEXT:    [[DOTFCA_8_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_7_INSERT_I]], i32 [[TMP12]], 8
// CHECK-NEXT:    [[DOTFCA_9_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_8_INSERT_I]], i32 [[TMP11]], 9
// CHECK-NEXT:    [[DOTFCA_10_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_9_INSERT_I]], i32 [[TMP10]], 10
// CHECK-NEXT:    [[DOTFCA_11_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_10_INSERT_I]], i32 [[TMP9]], 11
// CHECK-NEXT:    [[DOTFCA_12_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_11_INSERT_I]], i32 [[TMP8]], 12
// CHECK-NEXT:    [[DOTFCA_13_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_12_INSERT_I]], i32 [[TMP7]], 13
// CHECK-NEXT:    [[DOTFCA_14_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_13_INSERT_I]], i32 [[TMP6]], 14
// CHECK-NEXT:    [[DOTFCA_15_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_14_INSERT_I]], i32 [[TMP5]], 15
// CHECK-NEXT:    ret [[STRUCT_V256MX6]] [[DOTFCA_15_INSERT_I]]
//
v256mx6 test_update (v256mx6 s, int idx, v64uint4 m) { return update(s, idx, m); }
// CHECK-LABEL: @_Z11test_update7v256mx6iDv64_DU8_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX6:%.*]] [[S_COERCE:%.*]], 1
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 2
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 3
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <64 x i8> [[M:%.*]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP3]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I28_I:%.*]] = shufflevector <16 x i32> [[TMP3]], <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[CMP_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 0
// CHECK-NEXT:    [[COND_I:%.*]] = select i1 [[CMP_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[TMP4]]
// CHECK-NEXT:    [[COND7_I:%.*]] = select i1 [[CMP_I]], <8 x i32> [[SHUFFLE1_I28_I]], <8 x i32> [[TMP0]]
// CHECK-NEXT:    [[COND13_I:%.*]] = select i1 [[CMP_I]], <8 x i32> [[TMP1]], <8 x i32> [[SHUFFLE_I_I]]
// CHECK-NEXT:    [[COND19_I:%.*]] = select i1 [[CMP_I]], <8 x i32> [[TMP2]], <8 x i32> [[SHUFFLE1_I28_I]]
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 15
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 14
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 13
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 12
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 11
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 10
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 9
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 8
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 7
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 6
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 5
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 4
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] poison, <8 x i32> [[COND_I]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_0_INSERT_I]], <8 x i32> [[COND7_I]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_1_INSERT_I]], <8 x i32> [[COND13_I]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_2_INSERT_I]], <8 x i32> [[COND19_I]], 3
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_3_INSERT_I]], <2 x i32> [[TMP16]], 4
// CHECK-NEXT:    [[DOTFCA_5_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_4_INSERT_I]], <2 x i32> [[TMP15]], 5
// CHECK-NEXT:    [[DOTFCA_6_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_5_INSERT_I]], <2 x i32> [[TMP14]], 6
// CHECK-NEXT:    [[DOTFCA_7_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_6_INSERT_I]], <2 x i32> [[TMP13]], 7
// CHECK-NEXT:    [[DOTFCA_8_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_7_INSERT_I]], i32 [[TMP12]], 8
// CHECK-NEXT:    [[DOTFCA_9_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_8_INSERT_I]], i32 [[TMP11]], 9
// CHECK-NEXT:    [[DOTFCA_10_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_9_INSERT_I]], i32 [[TMP10]], 10
// CHECK-NEXT:    [[DOTFCA_11_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_10_INSERT_I]], i32 [[TMP9]], 11
// CHECK-NEXT:    [[DOTFCA_12_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_11_INSERT_I]], i32 [[TMP8]], 12
// CHECK-NEXT:    [[DOTFCA_13_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_12_INSERT_I]], i32 [[TMP7]], 13
// CHECK-NEXT:    [[DOTFCA_14_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_13_INSERT_I]], i32 [[TMP6]], 14
// CHECK-NEXT:    [[DOTFCA_15_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_14_INSERT_I]], i32 [[TMP5]], 15
// CHECK-NEXT:    ret [[STRUCT_V256MX6]] [[DOTFCA_15_INSERT_I]]
//
v256mx6 test_update (v256mx6 s, int idx, v128uint4 m) { return update(s, idx, m); }
// CHECK-LABEL: @_Z19test_extract_v64mx67v256mx6i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX6:%.*]] [[M_COERCE:%.*]], 1
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 5
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 9
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 13
// CHECK-NEXT:    switch i32 [[IDX:%.*]], label [[IF_ELSE14_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[IF_THEN_I:%.*]]
// CHECK-NEXT:      i32 1, label [[_ZL14EXTRACT_V64MX67V256MX6I_EXIT:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN9_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then.i:
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 12
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 8
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 4
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 0
// CHECK-NEXT:    br label [[_ZL14EXTRACT_V64MX67V256MX6I_EXIT]]
// CHECK:       if.then9.i:
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 14
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 10
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 6
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 2
// CHECK-NEXT:    br label [[_ZL14EXTRACT_V64MX67V256MX6I_EXIT]]
// CHECK:       if.else14.i:
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 15
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 11
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 7
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 3
// CHECK-NEXT:    br label [[_ZL14EXTRACT_V64MX67V256MX6I_EXIT]]
// CHECK:       _ZL14extract_v64mx67v256mx6i.exit:
// CHECK-NEXT:    [[RETVAL_SROA_0_0_I:%.*]] = phi <8 x i32> [ [[TMP7]], [[IF_THEN_I]] ], [ [[TMP11]], [[IF_THEN9_I]] ], [ [[TMP15]], [[IF_ELSE14_I]] ], [ [[TMP0]], [[ENTRY:%.*]] ]
// CHECK-NEXT:    [[RETVAL_SROA_5_0_I:%.*]] = phi <2 x i32> [ [[TMP6]], [[IF_THEN_I]] ], [ [[TMP10]], [[IF_THEN9_I]] ], [ [[TMP14]], [[IF_ELSE14_I]] ], [ [[TMP1]], [[ENTRY]] ]
// CHECK-NEXT:    [[RETVAL_SROA_10_0_I:%.*]] = phi i32 [ [[TMP5]], [[IF_THEN_I]] ], [ [[TMP9]], [[IF_THEN9_I]] ], [ [[TMP13]], [[IF_ELSE14_I]] ], [ [[TMP2]], [[ENTRY]] ]
// CHECK-NEXT:    [[RETVAL_SROA_15_0_I:%.*]] = phi i32 [ [[TMP4]], [[IF_THEN_I]] ], [ [[TMP8]], [[IF_THEN9_I]] ], [ [[TMP12]], [[IF_ELSE14_I]] ], [ [[TMP3]], [[ENTRY]] ]
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX6:%.*]] poison, <8 x i32> [[RETVAL_SROA_0_0_I]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX6]] [[DOTFCA_0_INSERT_I]], <2 x i32> [[RETVAL_SROA_5_0_I]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX6]] [[DOTFCA_1_INSERT_I]], i32 [[RETVAL_SROA_10_0_I]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX6]] [[DOTFCA_2_INSERT_I]], i32 [[RETVAL_SROA_15_0_I]], 3
// CHECK-NEXT:    ret [[STRUCT_V64MX6]] [[DOTFCA_3_INSERT_I]]
//
v64mx6 test_extract_v64mx6 (v256mx6 m, int idx) { return extract_v64mx6(m, idx); }
// CHECK-LABEL: @_Z22test_extract_v64bfp13p7v256mx6i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX6:%.*]] [[M_COERCE:%.*]], 1
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 5
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 9
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 13
// CHECK-NEXT:    switch i32 [[IDX:%.*]], label [[IF_ELSE14_I_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[IF_THEN_I_I:%.*]]
// CHECK-NEXT:      i32 1, label [[_ZL17EXTRACT_V64BFP13P7V256MX6I_EXIT:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN9_I_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then.i.i:
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 12
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 8
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 4
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 0
// CHECK-NEXT:    br label [[_ZL17EXTRACT_V64BFP13P7V256MX6I_EXIT]]
// CHECK:       if.then9.i.i:
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 14
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 10
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 6
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 2
// CHECK-NEXT:    br label [[_ZL17EXTRACT_V64BFP13P7V256MX6I_EXIT]]
// CHECK:       if.else14.i.i:
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 15
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 11
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 7
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 3
// CHECK-NEXT:    br label [[_ZL17EXTRACT_V64BFP13P7V256MX6I_EXIT]]
// CHECK:       _ZL17extract_v64bfp13p7v256mx6i.exit:
// CHECK-NEXT:    [[RETVAL_SROA_0_0_I_I:%.*]] = phi <8 x i32> [ [[TMP7]], [[IF_THEN_I_I]] ], [ [[TMP11]], [[IF_THEN9_I_I]] ], [ [[TMP15]], [[IF_ELSE14_I_I]] ], [ [[TMP0]], [[ENTRY:%.*]] ]
// CHECK-NEXT:    [[RETVAL_SROA_5_0_I_I:%.*]] = phi <2 x i32> [ [[TMP6]], [[IF_THEN_I_I]] ], [ [[TMP10]], [[IF_THEN9_I_I]] ], [ [[TMP14]], [[IF_ELSE14_I_I]] ], [ [[TMP1]], [[ENTRY]] ]
// CHECK-NEXT:    [[RETVAL_SROA_10_0_I_I:%.*]] = phi i32 [ [[TMP5]], [[IF_THEN_I_I]] ], [ [[TMP9]], [[IF_THEN9_I_I]] ], [ [[TMP13]], [[IF_ELSE14_I_I]] ], [ [[TMP2]], [[ENTRY]] ]
// CHECK-NEXT:    [[RETVAL_SROA_15_0_I_I:%.*]] = phi i32 [ [[TMP4]], [[IF_THEN_I_I]] ], [ [[TMP8]], [[IF_THEN9_I_I]] ], [ [[TMP12]], [[IF_ELSE14_I_I]] ], [ [[TMP3]], [[ENTRY]] ]
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64MX6:%.*]] poison, <8 x i32> [[RETVAL_SROA_0_0_I_I]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64MX6]] [[DOTFCA_0_INSERT_I_I]], <2 x i32> [[RETVAL_SROA_5_0_I_I]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64MX6]] [[DOTFCA_1_INSERT_I_I]], i32 [[RETVAL_SROA_10_0_I_I]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64MX6]] [[DOTFCA_2_INSERT_I_I]], i32 [[RETVAL_SROA_15_0_I_I]], 3
// CHECK-NEXT:    ret [[STRUCT_V64MX6]] [[DOTFCA_3_INSERT_I_I]]
//
v64bfp13p test_extract_v64bfp13p (v256bfp13p m, int idx) { return extract_v64bfp13p(m, idx); }
// CHECK-LABEL: @_Z11test_update7v256mx6i6v64mx6(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX6:%.*]] [[S_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 2
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 3
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 4
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 5
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 6
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 7
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 8
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 9
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 10
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 11
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 12
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 13
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 14
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 15
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue [[STRUCT_V64MX6:%.*]] [[M_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP17:%.*]] = extractvalue [[STRUCT_V64MX6]] [[M_COERCE]], 1
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue [[STRUCT_V64MX6]] [[M_COERCE]], 2
// CHECK-NEXT:    [[TMP19:%.*]] = extractvalue [[STRUCT_V64MX6]] [[M_COERCE]], 3
// CHECK-NEXT:    switch i32 [[IDX:%.*]], label [[IF_ELSE14_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[_ZL6UPDATE7V256MX6I6V64MX6_EXIT:%.*]]
// CHECK-NEXT:      i32 1, label [[IF_THEN2_I:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN9_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then2.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX6I6V64MX6_EXIT]]
// CHECK:       if.then9.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX6I6V64MX6_EXIT]]
// CHECK:       if.else14.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX6I6V64MX6_EXIT]]
// CHECK:       _ZL6update7v256mx6i6v64mx6.exit:
// CHECK-NEXT:    [[S_SROA_21_0_I:%.*]] = phi i32 [ [[TMP10]], [[IF_THEN2_I]] ], [ [[TMP18]], [[IF_THEN9_I]] ], [ [[TMP10]], [[IF_ELSE14_I]] ], [ [[TMP10]], [[ENTRY:%.*]] ]
// CHECK-NEXT:    [[S_SROA_19_0_I:%.*]] = phi i32 [ [[TMP18]], [[IF_THEN2_I]] ], [ [[TMP9]], [[IF_THEN9_I]] ], [ [[TMP9]], [[IF_ELSE14_I]] ], [ [[TMP9]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_17_0_I:%.*]] = phi i32 [ [[TMP8]], [[IF_THEN2_I]] ], [ [[TMP8]], [[IF_THEN9_I]] ], [ [[TMP8]], [[IF_ELSE14_I]] ], [ [[TMP18]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_15_0_I:%.*]] = phi <2 x i32> [ [[TMP7]], [[IF_THEN2_I]] ], [ [[TMP7]], [[IF_THEN9_I]] ], [ [[TMP17]], [[IF_ELSE14_I]] ], [ [[TMP7]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_13_0_I:%.*]] = phi <2 x i32> [ [[TMP6]], [[IF_THEN2_I]] ], [ [[TMP17]], [[IF_THEN9_I]] ], [ [[TMP6]], [[IF_ELSE14_I]] ], [ [[TMP6]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_11_0_I:%.*]] = phi <2 x i32> [ [[TMP17]], [[IF_THEN2_I]] ], [ [[TMP5]], [[IF_THEN9_I]] ], [ [[TMP5]], [[IF_ELSE14_I]] ], [ [[TMP5]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_9_0_I:%.*]] = phi <2 x i32> [ [[TMP4]], [[IF_THEN2_I]] ], [ [[TMP4]], [[IF_THEN9_I]] ], [ [[TMP4]], [[IF_ELSE14_I]] ], [ [[TMP17]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_7_0_I:%.*]] = phi <8 x i32> [ [[TMP3]], [[IF_THEN2_I]] ], [ [[TMP3]], [[IF_THEN9_I]] ], [ [[TMP16]], [[IF_ELSE14_I]] ], [ [[TMP3]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_5_0_I:%.*]] = phi <8 x i32> [ [[TMP2]], [[IF_THEN2_I]] ], [ [[TMP16]], [[IF_THEN9_I]] ], [ [[TMP2]], [[IF_ELSE14_I]] ], [ [[TMP2]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_3_0_I:%.*]] = phi <8 x i32> [ [[TMP16]], [[IF_THEN2_I]] ], [ [[TMP1]], [[IF_THEN9_I]] ], [ [[TMP1]], [[IF_ELSE14_I]] ], [ [[TMP1]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_0_0_I:%.*]] = phi <8 x i32> [ [[TMP0]], [[IF_THEN2_I]] ], [ [[TMP0]], [[IF_THEN9_I]] ], [ [[TMP0]], [[IF_ELSE14_I]] ], [ [[TMP16]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_23_0_I:%.*]] = phi i32 [ [[TMP11]], [[IF_THEN2_I]] ], [ [[TMP11]], [[IF_THEN9_I]] ], [ [[TMP18]], [[IF_ELSE14_I]] ], [ [[TMP11]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_25_0_I:%.*]] = phi i32 [ [[TMP12]], [[IF_THEN2_I]] ], [ [[TMP12]], [[IF_THEN9_I]] ], [ [[TMP12]], [[IF_ELSE14_I]] ], [ [[TMP19]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_27_0_I:%.*]] = phi i32 [ [[TMP19]], [[IF_THEN2_I]] ], [ [[TMP13]], [[IF_THEN9_I]] ], [ [[TMP13]], [[IF_ELSE14_I]] ], [ [[TMP13]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_29_0_I:%.*]] = phi i32 [ [[TMP14]], [[IF_THEN2_I]] ], [ [[TMP19]], [[IF_THEN9_I]] ], [ [[TMP14]], [[IF_ELSE14_I]] ], [ [[TMP14]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_31_0_I:%.*]] = phi i32 [ [[TMP15]], [[IF_THEN2_I]] ], [ [[TMP15]], [[IF_THEN9_I]] ], [ [[TMP19]], [[IF_ELSE14_I]] ], [ [[TMP15]], [[ENTRY]] ]
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] poison, <8 x i32> [[S_SROA_0_0_I]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_0_INSERT_I]], <8 x i32> [[S_SROA_3_0_I]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_1_INSERT_I]], <8 x i32> [[S_SROA_5_0_I]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_2_INSERT_I]], <8 x i32> [[S_SROA_7_0_I]], 3
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_3_INSERT_I]], <2 x i32> [[S_SROA_9_0_I]], 4
// CHECK-NEXT:    [[DOTFCA_5_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_4_INSERT_I]], <2 x i32> [[S_SROA_11_0_I]], 5
// CHECK-NEXT:    [[DOTFCA_6_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_5_INSERT_I]], <2 x i32> [[S_SROA_13_0_I]], 6
// CHECK-NEXT:    [[DOTFCA_7_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_6_INSERT_I]], <2 x i32> [[S_SROA_15_0_I]], 7
// CHECK-NEXT:    [[DOTFCA_8_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_7_INSERT_I]], i32 [[S_SROA_17_0_I]], 8
// CHECK-NEXT:    [[DOTFCA_9_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_8_INSERT_I]], i32 [[S_SROA_19_0_I]], 9
// CHECK-NEXT:    [[DOTFCA_10_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_9_INSERT_I]], i32 [[S_SROA_21_0_I]], 10
// CHECK-NEXT:    [[DOTFCA_11_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_10_INSERT_I]], i32 [[S_SROA_23_0_I]], 11
// CHECK-NEXT:    [[DOTFCA_12_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_11_INSERT_I]], i32 [[S_SROA_25_0_I]], 12
// CHECK-NEXT:    [[DOTFCA_13_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_12_INSERT_I]], i32 [[S_SROA_27_0_I]], 13
// CHECK-NEXT:    [[DOTFCA_14_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_13_INSERT_I]], i32 [[S_SROA_29_0_I]], 14
// CHECK-NEXT:    [[DOTFCA_15_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_14_INSERT_I]], i32 [[S_SROA_31_0_I]], 15
// CHECK-NEXT:    ret [[STRUCT_V256MX6]] [[DOTFCA_15_INSERT_I]]
//
v256mx6 test_update (v256mx6 s, int idx, v64mx6 m) { return update(s, idx, m); }
// CHECK-LABEL: @_Z20test_extract_v128mx67v256mx6i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    br i1 [[CMP_I]], label [[IF_THEN_I:%.*]], label [[IF_ELSE_I:%.*]]
// CHECK:       if.then.i:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX6:%.*]] [[M_COERCE:%.*]], 13
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 12
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 9
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 8
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 5
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 4
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 0
// CHECK-NEXT:    br label [[_ZL15EXTRACT_V128MX67V256MX6I_EXIT:%.*]]
// CHECK:       if.else.i:
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 15
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 14
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 11
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 10
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 7
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 6
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 3
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 2
// CHECK-NEXT:    [[CMP9_I:%.*]] = icmp eq i32 [[IDX]], 1
// CHECK-NEXT:    tail call void @llvm.assume(i1 [[CMP9_I]])
// CHECK-NEXT:    br label [[_ZL15EXTRACT_V128MX67V256MX6I_EXIT]]
// CHECK:       _ZL15extract_v128mx67v256mx6i.exit:
// CHECK-NEXT:    [[RETVAL_SROA_0_0_I:%.*]] = phi <8 x i32> [ [[TMP7]], [[IF_THEN_I]] ], [ [[TMP15]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_3_0_I:%.*]] = phi <8 x i32> [ [[TMP6]], [[IF_THEN_I]] ], [ [[TMP14]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_6_0_I:%.*]] = phi <2 x i32> [ [[TMP5]], [[IF_THEN_I]] ], [ [[TMP13]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_9_0_I:%.*]] = phi <2 x i32> [ [[TMP4]], [[IF_THEN_I]] ], [ [[TMP12]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_12_0_I:%.*]] = phi i32 [ [[TMP3]], [[IF_THEN_I]] ], [ [[TMP11]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_15_0_I:%.*]] = phi i32 [ [[TMP2]], [[IF_THEN_I]] ], [ [[TMP10]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_18_0_I:%.*]] = phi i32 [ [[TMP1]], [[IF_THEN_I]] ], [ [[TMP9]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_21_0_I:%.*]] = phi i32 [ [[TMP0]], [[IF_THEN_I]] ], [ [[TMP8]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX6:%.*]] poison, <8 x i32> [[RETVAL_SROA_0_0_I]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_0_INSERT_I]], <8 x i32> [[RETVAL_SROA_3_0_I]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_1_INSERT_I]], <2 x i32> [[RETVAL_SROA_6_0_I]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_2_INSERT_I]], <2 x i32> [[RETVAL_SROA_9_0_I]], 3
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_3_INSERT_I]], i32 [[RETVAL_SROA_12_0_I]], 4
// CHECK-NEXT:    [[DOTFCA_5_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_4_INSERT_I]], i32 [[RETVAL_SROA_15_0_I]], 5
// CHECK-NEXT:    [[DOTFCA_6_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_5_INSERT_I]], i32 [[RETVAL_SROA_18_0_I]], 6
// CHECK-NEXT:    [[DOTFCA_7_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_6_INSERT_I]], i32 [[RETVAL_SROA_21_0_I]], 7
// CHECK-NEXT:    ret [[STRUCT_V128MX6]] [[DOTFCA_7_INSERT_I]]
//
v128mx6 test_extract_v128mx6 (v256mx6 m, int idx) { return extract_v128mx6(m, idx); }
// CHECK-LABEL: @_Z23test_extract_v128bfp13p7v256mx6i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    br i1 [[CMP_I_I]], label [[IF_THEN_I_I:%.*]], label [[IF_ELSE_I_I:%.*]]
// CHECK:       if.then.i.i:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX6:%.*]] [[M_COERCE:%.*]], 13
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 12
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 9
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 8
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 5
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 4
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 0
// CHECK-NEXT:    br label [[_ZL18EXTRACT_V128BFP13P7V256MX6I_EXIT:%.*]]
// CHECK:       if.else.i.i:
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 15
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 14
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 11
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 10
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 7
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 6
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 3
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue [[STRUCT_V256MX6]] [[M_COERCE]], 2
// CHECK-NEXT:    [[CMP9_I_I:%.*]] = icmp eq i32 [[IDX]], 1
// CHECK-NEXT:    tail call void @llvm.assume(i1 [[CMP9_I_I]])
// CHECK-NEXT:    br label [[_ZL18EXTRACT_V128BFP13P7V256MX6I_EXIT]]
// CHECK:       _ZL18extract_v128bfp13p7v256mx6i.exit:
// CHECK-NEXT:    [[RETVAL_SROA_0_0_I_I:%.*]] = phi <8 x i32> [ [[TMP7]], [[IF_THEN_I_I]] ], [ [[TMP15]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_3_0_I_I:%.*]] = phi <8 x i32> [ [[TMP6]], [[IF_THEN_I_I]] ], [ [[TMP14]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_6_0_I_I:%.*]] = phi <2 x i32> [ [[TMP5]], [[IF_THEN_I_I]] ], [ [[TMP13]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_9_0_I_I:%.*]] = phi <2 x i32> [ [[TMP4]], [[IF_THEN_I_I]] ], [ [[TMP12]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_12_0_I_I:%.*]] = phi i32 [ [[TMP3]], [[IF_THEN_I_I]] ], [ [[TMP11]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_15_0_I_I:%.*]] = phi i32 [ [[TMP2]], [[IF_THEN_I_I]] ], [ [[TMP10]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_18_0_I_I:%.*]] = phi i32 [ [[TMP1]], [[IF_THEN_I_I]] ], [ [[TMP9]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_21_0_I_I:%.*]] = phi i32 [ [[TMP0]], [[IF_THEN_I_I]] ], [ [[TMP8]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX6:%.*]] poison, <8 x i32> [[RETVAL_SROA_0_0_I_I]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_0_INSERT_I_I]], <8 x i32> [[RETVAL_SROA_3_0_I_I]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_1_INSERT_I_I]], <2 x i32> [[RETVAL_SROA_6_0_I_I]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_2_INSERT_I_I]], <2 x i32> [[RETVAL_SROA_9_0_I_I]], 3
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_3_INSERT_I_I]], i32 [[RETVAL_SROA_12_0_I_I]], 4
// CHECK-NEXT:    [[DOTFCA_5_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_4_INSERT_I_I]], i32 [[RETVAL_SROA_15_0_I_I]], 5
// CHECK-NEXT:    [[DOTFCA_6_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_5_INSERT_I_I]], i32 [[RETVAL_SROA_18_0_I_I]], 6
// CHECK-NEXT:    [[DOTFCA_7_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_6_INSERT_I_I]], i32 [[RETVAL_SROA_21_0_I_I]], 7
// CHECK-NEXT:    ret [[STRUCT_V128MX6]] [[DOTFCA_7_INSERT_I_I]]
//
v128bfp13p test_extract_v128bfp13p (v256bfp13p m, int idx) { return extract_v128bfp13p(m, idx); }
// CHECK-LABEL: @_Z11test_update7v256mx6i7v128mx6(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX6:%.*]] [[S_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 2
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 3
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 4
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 5
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 6
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 7
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 8
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 9
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 10
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 11
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 12
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 13
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 14
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue [[STRUCT_V256MX6]] [[S_COERCE]], 15
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue [[STRUCT_V128MX6:%.*]] [[M_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP17:%.*]] = extractvalue [[STRUCT_V128MX6]] [[M_COERCE]], 1
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue [[STRUCT_V128MX6]] [[M_COERCE]], 2
// CHECK-NEXT:    [[TMP19:%.*]] = extractvalue [[STRUCT_V128MX6]] [[M_COERCE]], 3
// CHECK-NEXT:    [[TMP20:%.*]] = extractvalue [[STRUCT_V128MX6]] [[M_COERCE]], 4
// CHECK-NEXT:    [[TMP21:%.*]] = extractvalue [[STRUCT_V128MX6]] [[M_COERCE]], 5
// CHECK-NEXT:    [[TMP22:%.*]] = extractvalue [[STRUCT_V128MX6]] [[M_COERCE]], 6
// CHECK-NEXT:    [[TMP23:%.*]] = extractvalue [[STRUCT_V128MX6]] [[M_COERCE]], 7
// CHECK-NEXT:    switch i32 [[IDX:%.*]], label [[IF_END19_FOLD_SPLIT_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[_ZL6UPDATE7V256MX6I7V128MX6_EXIT:%.*]]
// CHECK-NEXT:      i32 1, label [[IF_THEN10_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then10.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX6I7V128MX6_EXIT]]
// CHECK:       if.end19.fold.split.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX6I7V128MX6_EXIT]]
// CHECK:       _ZL6update7v256mx6i7v128mx6.exit:
// CHECK-NEXT:    [[S_SROA_13_0_I:%.*]] = phi <2 x i32> [ [[TMP18]], [[IF_THEN10_I]] ], [ [[TMP6]], [[ENTRY:%.*]] ], [ [[TMP6]], [[IF_END19_FOLD_SPLIT_I]] ]
// CHECK-NEXT:    [[S_SROA_11_0_I:%.*]] = phi <2 x i32> [ [[TMP5]], [[IF_THEN10_I]] ], [ [[TMP19]], [[ENTRY]] ], [ [[TMP5]], [[IF_END19_FOLD_SPLIT_I]] ]
// CHECK-NEXT:    [[S_SROA_9_0_I:%.*]] = phi <2 x i32> [ [[TMP4]], [[IF_THEN10_I]] ], [ [[TMP18]], [[ENTRY]] ], [ [[TMP4]], [[IF_END19_FOLD_SPLIT_I]] ]
// CHECK-NEXT:    [[S_SROA_7_0_I:%.*]] = phi <8 x i32> [ [[TMP17]], [[IF_THEN10_I]] ], [ [[TMP3]], [[ENTRY]] ], [ [[TMP3]], [[IF_END19_FOLD_SPLIT_I]] ]
// CHECK-NEXT:    [[S_SROA_5_0_I:%.*]] = phi <8 x i32> [ [[TMP16]], [[IF_THEN10_I]] ], [ [[TMP2]], [[ENTRY]] ], [ [[TMP2]], [[IF_END19_FOLD_SPLIT_I]] ]
// CHECK-NEXT:    [[S_SROA_3_0_I:%.*]] = phi <8 x i32> [ [[TMP1]], [[IF_THEN10_I]] ], [ [[TMP17]], [[ENTRY]] ], [ [[TMP1]], [[IF_END19_FOLD_SPLIT_I]] ]
// CHECK-NEXT:    [[S_SROA_0_0_I:%.*]] = phi <8 x i32> [ [[TMP0]], [[IF_THEN10_I]] ], [ [[TMP16]], [[ENTRY]] ], [ [[TMP0]], [[IF_END19_FOLD_SPLIT_I]] ]
// CHECK-NEXT:    [[S_SROA_15_0_I:%.*]] = phi <2 x i32> [ [[TMP19]], [[IF_THEN10_I]] ], [ [[TMP7]], [[ENTRY]] ], [ [[TMP7]], [[IF_END19_FOLD_SPLIT_I]] ]
// CHECK-NEXT:    [[S_SROA_17_0_I:%.*]] = phi i32 [ [[TMP8]], [[IF_THEN10_I]] ], [ [[TMP20]], [[ENTRY]] ], [ [[TMP8]], [[IF_END19_FOLD_SPLIT_I]] ]
// CHECK-NEXT:    [[S_SROA_19_0_I:%.*]] = phi i32 [ [[TMP9]], [[IF_THEN10_I]] ], [ [[TMP21]], [[ENTRY]] ], [ [[TMP9]], [[IF_END19_FOLD_SPLIT_I]] ]
// CHECK-NEXT:    [[S_SROA_21_0_I:%.*]] = phi i32 [ [[TMP20]], [[IF_THEN10_I]] ], [ [[TMP10]], [[ENTRY]] ], [ [[TMP10]], [[IF_END19_FOLD_SPLIT_I]] ]
// CHECK-NEXT:    [[S_SROA_23_0_I:%.*]] = phi i32 [ [[TMP21]], [[IF_THEN10_I]] ], [ [[TMP11]], [[ENTRY]] ], [ [[TMP11]], [[IF_END19_FOLD_SPLIT_I]] ]
// CHECK-NEXT:    [[S_SROA_25_0_I:%.*]] = phi i32 [ [[TMP12]], [[IF_THEN10_I]] ], [ [[TMP22]], [[ENTRY]] ], [ [[TMP12]], [[IF_END19_FOLD_SPLIT_I]] ]
// CHECK-NEXT:    [[S_SROA_27_0_I:%.*]] = phi i32 [ [[TMP13]], [[IF_THEN10_I]] ], [ [[TMP23]], [[ENTRY]] ], [ [[TMP13]], [[IF_END19_FOLD_SPLIT_I]] ]
// CHECK-NEXT:    [[S_SROA_29_0_I:%.*]] = phi i32 [ [[TMP22]], [[IF_THEN10_I]] ], [ [[TMP14]], [[ENTRY]] ], [ [[TMP14]], [[IF_END19_FOLD_SPLIT_I]] ]
// CHECK-NEXT:    [[S_SROA_31_0_I:%.*]] = phi i32 [ [[TMP23]], [[IF_THEN10_I]] ], [ [[TMP15]], [[ENTRY]] ], [ [[TMP15]], [[IF_END19_FOLD_SPLIT_I]] ]
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] poison, <8 x i32> [[S_SROA_0_0_I]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_0_INSERT_I]], <8 x i32> [[S_SROA_3_0_I]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_1_INSERT_I]], <8 x i32> [[S_SROA_5_0_I]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_2_INSERT_I]], <8 x i32> [[S_SROA_7_0_I]], 3
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_3_INSERT_I]], <2 x i32> [[S_SROA_9_0_I]], 4
// CHECK-NEXT:    [[DOTFCA_5_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_4_INSERT_I]], <2 x i32> [[S_SROA_11_0_I]], 5
// CHECK-NEXT:    [[DOTFCA_6_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_5_INSERT_I]], <2 x i32> [[S_SROA_13_0_I]], 6
// CHECK-NEXT:    [[DOTFCA_7_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_6_INSERT_I]], <2 x i32> [[S_SROA_15_0_I]], 7
// CHECK-NEXT:    [[DOTFCA_8_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_7_INSERT_I]], i32 [[S_SROA_17_0_I]], 8
// CHECK-NEXT:    [[DOTFCA_9_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_8_INSERT_I]], i32 [[S_SROA_19_0_I]], 9
// CHECK-NEXT:    [[DOTFCA_10_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_9_INSERT_I]], i32 [[S_SROA_21_0_I]], 10
// CHECK-NEXT:    [[DOTFCA_11_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_10_INSERT_I]], i32 [[S_SROA_23_0_I]], 11
// CHECK-NEXT:    [[DOTFCA_12_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_11_INSERT_I]], i32 [[S_SROA_25_0_I]], 12
// CHECK-NEXT:    [[DOTFCA_13_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_12_INSERT_I]], i32 [[S_SROA_27_0_I]], 13
// CHECK-NEXT:    [[DOTFCA_14_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_13_INSERT_I]], i32 [[S_SROA_29_0_I]], 14
// CHECK-NEXT:    [[DOTFCA_15_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_14_INSERT_I]], i32 [[S_SROA_31_0_I]], 15
// CHECK-NEXT:    ret [[STRUCT_V256MX6]] [[DOTFCA_15_INSERT_I]]
//
v256mx6 test_update (v256mx6 s, int idx, v128mx6 m) { return update(s, idx, m); }
// CHECK-LABEL: @_Z16test_set_v256mx6i7v128mx6(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V128MX6:%.*]] [[M_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V128MX6]] [[M_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128MX6]] [[M_COERCE]], 2
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128MX6]] [[M_COERCE]], 3
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128MX6]] [[M_COERCE]], 4
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128MX6]] [[M_COERCE]], 5
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V128MX6]] [[M_COERCE]], 6
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V128MX6]] [[M_COERCE]], 7
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6:%.*]] poison, <8 x i32> [[TMP0]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_0_INSERT_I]], <8 x i32> [[TMP1]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_1_INSERT_I]], <8 x i32> [[TMP0]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_2_INSERT_I]], <8 x i32> [[TMP1]], 3
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_3_INSERT_I]], <2 x i32> [[TMP2]], 4
// CHECK-NEXT:    [[DOTFCA_5_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_4_INSERT_I]], <2 x i32> [[TMP3]], 5
// CHECK-NEXT:    [[DOTFCA_6_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_5_INSERT_I]], <2 x i32> [[TMP2]], 6
// CHECK-NEXT:    [[DOTFCA_7_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_6_INSERT_I]], <2 x i32> [[TMP3]], 7
// CHECK-NEXT:    [[DOTFCA_8_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_7_INSERT_I]], i32 [[TMP4]], 8
// CHECK-NEXT:    [[DOTFCA_9_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_8_INSERT_I]], i32 [[TMP5]], 9
// CHECK-NEXT:    [[DOTFCA_10_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_9_INSERT_I]], i32 [[TMP4]], 10
// CHECK-NEXT:    [[DOTFCA_11_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_10_INSERT_I]], i32 [[TMP5]], 11
// CHECK-NEXT:    [[DOTFCA_12_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_11_INSERT_I]], i32 [[TMP6]], 12
// CHECK-NEXT:    [[DOTFCA_13_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_12_INSERT_I]], i32 [[TMP7]], 13
// CHECK-NEXT:    [[DOTFCA_14_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_13_INSERT_I]], i32 [[TMP6]], 14
// CHECK-NEXT:    [[DOTFCA_15_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_14_INSERT_I]], i32 [[TMP7]], 15
// CHECK-NEXT:    ret [[STRUCT_V256MX6]] [[DOTFCA_15_INSERT_I]]
//
v256mx6 test_set_v256mx6 (int idx, v128mx6 m) { return set_v256mx6(idx, m); }
// CHECK-LABEL: @_Z19test_set_v256bfp13pi7v128mx6(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V128MX6:%.*]] [[M_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V128MX6]] [[M_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128MX6]] [[M_COERCE]], 2
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128MX6]] [[M_COERCE]], 3
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128MX6]] [[M_COERCE]], 4
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128MX6]] [[M_COERCE]], 5
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V128MX6]] [[M_COERCE]], 6
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V128MX6]] [[M_COERCE]], 7
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX6:%.*]] poison, <8 x i32> [[TMP0]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_0_INSERT_I_I]], <8 x i32> [[TMP1]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_1_INSERT_I_I]], <8 x i32> [[TMP0]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_2_INSERT_I_I]], <8 x i32> [[TMP1]], 3
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_3_INSERT_I_I]], <2 x i32> [[TMP2]], 4
// CHECK-NEXT:    [[DOTFCA_5_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_4_INSERT_I_I]], <2 x i32> [[TMP3]], 5
// CHECK-NEXT:    [[DOTFCA_6_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_5_INSERT_I_I]], <2 x i32> [[TMP2]], 6
// CHECK-NEXT:    [[DOTFCA_7_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_6_INSERT_I_I]], <2 x i32> [[TMP3]], 7
// CHECK-NEXT:    [[DOTFCA_8_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_7_INSERT_I_I]], i32 [[TMP4]], 8
// CHECK-NEXT:    [[DOTFCA_9_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_8_INSERT_I_I]], i32 [[TMP5]], 9
// CHECK-NEXT:    [[DOTFCA_10_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_9_INSERT_I_I]], i32 [[TMP4]], 10
// CHECK-NEXT:    [[DOTFCA_11_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_10_INSERT_I_I]], i32 [[TMP5]], 11
// CHECK-NEXT:    [[DOTFCA_12_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_11_INSERT_I_I]], i32 [[TMP6]], 12
// CHECK-NEXT:    [[DOTFCA_13_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_12_INSERT_I_I]], i32 [[TMP7]], 13
// CHECK-NEXT:    [[DOTFCA_14_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_13_INSERT_I_I]], i32 [[TMP6]], 14
// CHECK-NEXT:    [[DOTFCA_15_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_14_INSERT_I_I]], i32 [[TMP7]], 15
// CHECK-NEXT:    ret [[STRUCT_V256MX6]] [[DOTFCA_15_INSERT_I_I]]
//
v256bfp13p test_set_v256bfp13p (int idx, v128bfp13p m) { return set_v256bfp13p(idx, m); }
// CHECK-LABEL: @_Z11test_concat7v128mx6S_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V128MX6:%.*]] [[V0_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V128MX6]] [[V0_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128MX6]] [[V0_COERCE]], 2
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128MX6]] [[V0_COERCE]], 3
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128MX6]] [[V0_COERCE]], 4
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128MX6]] [[V0_COERCE]], 5
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V128MX6]] [[V0_COERCE]], 6
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V128MX6]] [[V0_COERCE]], 7
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V128MX6]] [[V1_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue [[STRUCT_V128MX6]] [[V1_COERCE]], 1
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue [[STRUCT_V128MX6]] [[V1_COERCE]], 2
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue [[STRUCT_V128MX6]] [[V1_COERCE]], 3
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue [[STRUCT_V128MX6]] [[V1_COERCE]], 4
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue [[STRUCT_V128MX6]] [[V1_COERCE]], 5
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue [[STRUCT_V128MX6]] [[V1_COERCE]], 6
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue [[STRUCT_V128MX6]] [[V1_COERCE]], 7
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6:%.*]] poison, <8 x i32> [[TMP0]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_0_INSERT_I]], <8 x i32> [[TMP1]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_1_INSERT_I]], <8 x i32> [[TMP8]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_2_INSERT_I]], <8 x i32> [[TMP9]], 3
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_3_INSERT_I]], <2 x i32> [[TMP2]], 4
// CHECK-NEXT:    [[DOTFCA_5_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_4_INSERT_I]], <2 x i32> [[TMP3]], 5
// CHECK-NEXT:    [[DOTFCA_6_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_5_INSERT_I]], <2 x i32> [[TMP10]], 6
// CHECK-NEXT:    [[DOTFCA_7_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_6_INSERT_I]], <2 x i32> [[TMP11]], 7
// CHECK-NEXT:    [[DOTFCA_8_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_7_INSERT_I]], i32 [[TMP4]], 8
// CHECK-NEXT:    [[DOTFCA_9_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_8_INSERT_I]], i32 [[TMP5]], 9
// CHECK-NEXT:    [[DOTFCA_10_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_9_INSERT_I]], i32 [[TMP12]], 10
// CHECK-NEXT:    [[DOTFCA_11_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_10_INSERT_I]], i32 [[TMP13]], 11
// CHECK-NEXT:    [[DOTFCA_12_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_11_INSERT_I]], i32 [[TMP6]], 12
// CHECK-NEXT:    [[DOTFCA_13_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_12_INSERT_I]], i32 [[TMP7]], 13
// CHECK-NEXT:    [[DOTFCA_14_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_13_INSERT_I]], i32 [[TMP14]], 14
// CHECK-NEXT:    [[DOTFCA_15_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_14_INSERT_I]], i32 [[TMP15]], 15
// CHECK-NEXT:    ret [[STRUCT_V256MX6]] [[DOTFCA_15_INSERT_I]]
//
v256mx6             test_concat (v128mx6 v0, v128mx6 v1) { return concat(v0, v1); }

// CHECK-LABEL: @_Z25test_extract_msb_v16uint47v256mx4i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX4:%.*]] [[M_COERCE:%.*]], 5
// CHECK-NEXT:    switch i32 [[IDX:%.*]], label [[IF_ELSE6_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[IF_THEN_I:%.*]]
// CHECK-NEXT:      i32 1, label [[_ZL20EXTRACT_MSB_V16UINT47V256MX4I_EXIT:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN5_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then.i:
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 4
// CHECK-NEXT:    br label [[_ZL20EXTRACT_MSB_V16UINT47V256MX4I_EXIT]]
// CHECK:       if.then5.i:
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 6
// CHECK-NEXT:    br label [[_ZL20EXTRACT_MSB_V16UINT47V256MX4I_EXIT]]
// CHECK:       if.else6.i:
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 7
// CHECK-NEXT:    br label [[_ZL20EXTRACT_MSB_V16UINT47V256MX4I_EXIT]]
// CHECK:       _ZL20extract_msb_v16uint47v256mx4i.exit:
// CHECK-NEXT:    [[TEMP_0_I:%.*]] = phi <2 x i32> [ [[TMP1]], [[IF_THEN_I]] ], [ [[TMP2]], [[IF_THEN5_I]] ], [ [[TMP3]], [[IF_ELSE6_I]] ], [ [[TMP0]], [[ENTRY:%.*]] ]
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <2 x i32> [[TEMP_0_I]] to <8 x i8>
// CHECK-NEXT:    ret <8 x i8> [[TMP4]]
//
v16uint4 test_extract_msb_v16uint4 (v256mx4 m, int idx) { return extract_msb_v16uint4(m, idx); }
// CHECK-LABEL: @_Z25test_extract_msb_v32uint47v256mx4i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX4:%.*]] [[M_COERCE:%.*]], 5
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 4
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to <8 x i8>
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <8 x i8> [[TMP2]], <8 x i8> poison, <16 x i32> <i32 0, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i8> [[TMP2]], <8 x i8> poison, <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 4, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <2 x i32> [[TMP0]] to <8 x i8>
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i8> [[TMP5]], <8 x i8> poison, <16 x i32> <i32 0, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <8 x i8> [[TMP5]], <8 x i8> poison, <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 4, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <16 x i8> [[TMP3]], <16 x i8> <i8 poison, i8 poison, i8 poison, i8 poison, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0>, <16 x i32> <i32 0, i32 poison, i32 poison, i32 poison, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> [[TMP4]], <16 x i32> <i32 0, i32 20, i32 poison, i32 poison, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <16 x i8> [[TMP9]], <16 x i8> [[TMP6]], <16 x i32> <i32 0, i32 1, i32 16, i32 poison, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[VECINIT23_I:%.*]] = shufflevector <16 x i8> [[TMP10]], <16 x i8> [[TMP7]], <16 x i32> <i32 0, i32 1, i32 2, i32 20, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 7
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 6
// CHECK-NEXT:    [[TMP13:%.*]] = bitcast <2 x i32> [[TMP12]] to <8 x i8>
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <8 x i8> [[TMP13]], <8 x i8> poison, <16 x i32> <i32 0, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[TMP15:%.*]] = shufflevector <8 x i8> [[TMP13]], <8 x i8> poison, <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 4, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[TMP16:%.*]] = bitcast <2 x i32> [[TMP11]] to <8 x i8>
// CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <8 x i8> [[TMP16]], <8 x i8> poison, <16 x i32> <i32 0, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <8 x i8> [[TMP16]], <8 x i8> poison, <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 4, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[TMP19:%.*]] = shufflevector <16 x i8> [[TMP14]], <16 x i8> <i8 poison, i8 poison, i8 poison, i8 poison, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0>, <16 x i32> <i32 0, i32 poison, i32 poison, i32 poison, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <16 x i8> [[TMP19]], <16 x i8> [[TMP15]], <16 x i32> <i32 0, i32 20, i32 poison, i32 poison, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP21:%.*]] = shufflevector <16 x i8> [[TMP20]], <16 x i8> [[TMP17]], <16 x i32> <i32 0, i32 1, i32 16, i32 poison, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[VECINIT50_I:%.*]] = shufflevector <16 x i8> [[TMP21]], <16 x i8> [[TMP18]], <16 x i32> <i32 0, i32 1, i32 2, i32 20, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[RETVAL_0_I:%.*]] = select i1 [[CMP_I]], <16 x i8> [[VECINIT23_I]], <16 x i8> [[VECINIT50_I]]
// CHECK-NEXT:    ret <16 x i8> [[RETVAL_0_I]]
//
v32uint4 test_extract_msb_v32uint4 (v256mx4 m, int idx) { return extract_msb_v32uint4(m, idx); }
// CHECK-LABEL: @_Z11test_update7v256mx4iDv8_DU8_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX4:%.*]] [[S_COERCE:%.*]], 4
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 5
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 6
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 7
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <8 x i8> [[M:%.*]] to <2 x i32>
// CHECK-NEXT:    switch i32 [[IDX:%.*]], label [[IF_ELSE6_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[_ZL6UPDATE7V256MX4IDV8_DU8__EXIT:%.*]]
// CHECK-NEXT:      i32 1, label [[IF_THEN2_I:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN5_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then2.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX4IDV8_DU8__EXIT]]
// CHECK:       if.then5.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX4IDV8_DU8__EXIT]]
// CHECK:       if.else6.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX4IDV8_DU8__EXIT]]
// CHECK:       _ZL6update7v256mx4iDv8_DU8_.exit:
// CHECK-NEXT:    [[S_SROA_5_0_I:%.*]] = phi <2 x i32> [ [[TMP0]], [[IF_THEN2_I]] ], [ [[TMP0]], [[IF_THEN5_I]] ], [ [[TMP0]], [[IF_ELSE6_I]] ], [ [[TMP4]], [[ENTRY:%.*]] ]
// CHECK-NEXT:    [[S_SROA_7_0_I:%.*]] = phi <2 x i32> [ [[TMP4]], [[IF_THEN2_I]] ], [ [[TMP1]], [[IF_THEN5_I]] ], [ [[TMP1]], [[IF_ELSE6_I]] ], [ [[TMP1]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_9_0_I:%.*]] = phi <2 x i32> [ [[TMP2]], [[IF_THEN2_I]] ], [ [[TMP4]], [[IF_THEN5_I]] ], [ [[TMP2]], [[IF_ELSE6_I]] ], [ [[TMP2]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_11_0_I:%.*]] = phi <2 x i32> [ [[TMP3]], [[IF_THEN2_I]] ], [ [[TMP3]], [[IF_THEN5_I]] ], [ [[TMP4]], [[IF_ELSE6_I]] ], [ [[TMP3]], [[ENTRY]] ]
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 15
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 14
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 13
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 12
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 11
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 10
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 9
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 8
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[S_COERCE]], <2 x i32> [[S_SROA_5_0_I]], 4
// CHECK-NEXT:    [[DOTFCA_5_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_4_INSERT_I]], <2 x i32> [[S_SROA_7_0_I]], 5
// CHECK-NEXT:    [[DOTFCA_6_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_5_INSERT_I]], <2 x i32> [[S_SROA_9_0_I]], 6
// CHECK-NEXT:    [[DOTFCA_7_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_6_INSERT_I]], <2 x i32> [[S_SROA_11_0_I]], 7
// CHECK-NEXT:    [[DOTFCA_8_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_7_INSERT_I]], i32 [[TMP12]], 8
// CHECK-NEXT:    [[DOTFCA_9_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_8_INSERT_I]], i32 [[TMP11]], 9
// CHECK-NEXT:    [[DOTFCA_10_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_9_INSERT_I]], i32 [[TMP10]], 10
// CHECK-NEXT:    [[DOTFCA_11_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_10_INSERT_I]], i32 [[TMP9]], 11
// CHECK-NEXT:    [[DOTFCA_12_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_11_INSERT_I]], i32 [[TMP8]], 12
// CHECK-NEXT:    [[DOTFCA_13_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_12_INSERT_I]], i32 [[TMP7]], 13
// CHECK-NEXT:    [[DOTFCA_14_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_13_INSERT_I]], i32 [[TMP6]], 14
// CHECK-NEXT:    [[DOTFCA_15_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_14_INSERT_I]], i32 [[TMP5]], 15
// CHECK-NEXT:    ret [[STRUCT_V256MX4]] [[DOTFCA_15_INSERT_I]]
//
v256mx4 test_update (v256mx4 s, int idx, v16uint4 m) { return update(s, idx, m); }
// CHECK-LABEL: @_Z11test_update7v256mx4iDv16_DU8_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i8> [[M:%.*]] to <4 x i32>
// CHECK-NEXT:    [[VECINIT3_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[VECINIT9_I:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[CMP_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    br i1 [[CMP_I]], label [[IF_THEN_I:%.*]], label [[IF_ELSE_I:%.*]]
// CHECK:       if.then.i:
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX4:%.*]] [[S_COERCE:%.*]], 7
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 6
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX4IDV16_DU8__EXIT:%.*]]
// CHECK:       if.else.i:
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 5
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 4
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX4IDV16_DU8__EXIT]]
// CHECK:       _ZL6update7v256mx4iDv16_DU8_.exit:
// CHECK-NEXT:    [[S_SROA_5_0_I:%.*]] = phi <2 x i32> [ [[VECINIT3_I]], [[IF_THEN_I]] ], [ [[TMP4]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[S_SROA_7_0_I:%.*]] = phi <2 x i32> [ [[VECINIT9_I]], [[IF_THEN_I]] ], [ [[TMP3]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[S_SROA_9_0_I:%.*]] = phi <2 x i32> [ [[TMP2]], [[IF_THEN_I]] ], [ [[VECINIT3_I]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[S_SROA_11_0_I:%.*]] = phi <2 x i32> [ [[TMP1]], [[IF_THEN_I]] ], [ [[VECINIT9_I]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 15
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 14
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 13
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 12
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 11
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 10
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 9
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 8
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[S_COERCE]], <2 x i32> [[S_SROA_5_0_I]], 4
// CHECK-NEXT:    [[DOTFCA_5_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_4_INSERT_I]], <2 x i32> [[S_SROA_7_0_I]], 5
// CHECK-NEXT:    [[DOTFCA_6_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_5_INSERT_I]], <2 x i32> [[S_SROA_9_0_I]], 6
// CHECK-NEXT:    [[DOTFCA_7_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_6_INSERT_I]], <2 x i32> [[S_SROA_11_0_I]], 7
// CHECK-NEXT:    [[DOTFCA_8_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_7_INSERT_I]], i32 [[TMP12]], 8
// CHECK-NEXT:    [[DOTFCA_9_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_8_INSERT_I]], i32 [[TMP11]], 9
// CHECK-NEXT:    [[DOTFCA_10_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_9_INSERT_I]], i32 [[TMP10]], 10
// CHECK-NEXT:    [[DOTFCA_11_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_10_INSERT_I]], i32 [[TMP9]], 11
// CHECK-NEXT:    [[DOTFCA_12_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_11_INSERT_I]], i32 [[TMP8]], 12
// CHECK-NEXT:    [[DOTFCA_13_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_12_INSERT_I]], i32 [[TMP7]], 13
// CHECK-NEXT:    [[DOTFCA_14_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_13_INSERT_I]], i32 [[TMP6]], 14
// CHECK-NEXT:    [[DOTFCA_15_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_14_INSERT_I]], i32 [[TMP5]], 15
// CHECK-NEXT:    ret [[STRUCT_V256MX4]] [[DOTFCA_15_INSERT_I]]
//
v256mx4 test_update (v256mx4 s, int idx, v32uint4 m) { return update(s, idx, m); }
// CHECK-LABEL: @_Z21test_extract_expo_int7v256mx4i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    switch i32 [[IDX:%.*]], label [[SW_DEFAULT_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[SW_BB_I:%.*]]
// CHECK-NEXT:      i32 1, label [[SW_BB1_I:%.*]]
// CHECK-NEXT:      i32 2, label [[SW_BB2_I:%.*]]
// CHECK-NEXT:      i32 3, label [[SW_BB3_I:%.*]]
// CHECK-NEXT:      i32 4, label [[SW_BB4_I:%.*]]
// CHECK-NEXT:      i32 5, label [[SW_BB5_I:%.*]]
// CHECK-NEXT:      i32 6, label [[SW_BB6_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       sw.bb.i:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX4:%.*]] [[M_COERCE:%.*]], 12
// CHECK-NEXT:    br label [[_ZL16EXTRACT_EXPO_INT7V256MX4I_EXIT:%.*]]
// CHECK:       sw.bb1.i:
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 13
// CHECK-NEXT:    br label [[_ZL16EXTRACT_EXPO_INT7V256MX4I_EXIT]]
// CHECK:       sw.bb2.i:
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 14
// CHECK-NEXT:    br label [[_ZL16EXTRACT_EXPO_INT7V256MX4I_EXIT]]
// CHECK:       sw.bb3.i:
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 15
// CHECK-NEXT:    br label [[_ZL16EXTRACT_EXPO_INT7V256MX4I_EXIT]]
// CHECK:       sw.bb4.i:
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 8
// CHECK-NEXT:    br label [[_ZL16EXTRACT_EXPO_INT7V256MX4I_EXIT]]
// CHECK:       sw.bb5.i:
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 9
// CHECK-NEXT:    br label [[_ZL16EXTRACT_EXPO_INT7V256MX4I_EXIT]]
// CHECK:       sw.bb6.i:
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 10
// CHECK-NEXT:    br label [[_ZL16EXTRACT_EXPO_INT7V256MX4I_EXIT]]
// CHECK:       sw.default.i:
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 11
// CHECK-NEXT:    br label [[_ZL16EXTRACT_EXPO_INT7V256MX4I_EXIT]]
// CHECK:       _ZL16extract_expo_int7v256mx4i.exit:
// CHECK-NEXT:    [[RETVAL_0_I:%.*]] = phi i32 [ [[TMP7]], [[SW_DEFAULT_I]] ], [ [[TMP6]], [[SW_BB6_I]] ], [ [[TMP5]], [[SW_BB5_I]] ], [ [[TMP4]], [[SW_BB4_I]] ], [ [[TMP3]], [[SW_BB3_I]] ], [ [[TMP2]], [[SW_BB2_I]] ], [ [[TMP1]], [[SW_BB1_I]] ], [ [[TMP0]], [[SW_BB_I]] ]
// CHECK-NEXT:    ret i32 [[RETVAL_0_I]]
//
int test_extract_expo_int (v256mx4 m, int idx) { return extract_expo_int(m, idx); }
// CHECK-LABEL: @_Z24test_extract_expo_v8int87v256mx4i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    switch i32 [[IDX:%.*]], label [[SW_DEFAULT_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[SW_BB_I:%.*]]
// CHECK-NEXT:      i32 1, label [[SW_BB9_I:%.*]]
// CHECK-NEXT:      i32 2, label [[SW_BB20_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       sw.bb.i:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX4:%.*]] [[M_COERCE:%.*]], 13
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 12
// CHECK-NEXT:    br label [[_ZL19EXTRACT_EXPO_V8INT87V256MX4I_EXIT:%.*]]
// CHECK:       sw.bb9.i:
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 15
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 14
// CHECK-NEXT:    br label [[_ZL19EXTRACT_EXPO_V8INT87V256MX4I_EXIT]]
// CHECK:       sw.bb20.i:
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 9
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 8
// CHECK-NEXT:    br label [[_ZL19EXTRACT_EXPO_V8INT87V256MX4I_EXIT]]
// CHECK:       sw.default.i:
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 11
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 10
// CHECK-NEXT:    br label [[_ZL19EXTRACT_EXPO_V8INT87V256MX4I_EXIT]]
// CHECK:       _ZL19extract_expo_v8int87v256mx4i.exit:
// CHECK-NEXT:    [[DOTSINK41_I:%.*]] = phi i32 [ [[TMP7]], [[SW_DEFAULT_I]] ], [ [[TMP5]], [[SW_BB20_I]] ], [ [[TMP3]], [[SW_BB9_I]] ], [ [[TMP1]], [[SW_BB_I]] ]
// CHECK-NEXT:    [[DOTSINK_I:%.*]] = phi i32 [ [[TMP6]], [[SW_DEFAULT_I]] ], [ [[TMP4]], [[SW_BB20_I]] ], [ [[TMP2]], [[SW_BB9_I]] ], [ [[TMP0]], [[SW_BB_I]] ]
// CHECK-NEXT:    [[CONV31_I:%.*]] = trunc i32 [[DOTSINK41_I]] to i8
// CHECK-NEXT:    [[CONV33_I:%.*]] = trunc i32 [[DOTSINK_I]] to i8
// CHECK-NEXT:    [[TMP8:%.*]] = insertelement <8 x i8> <i8 poison, i8 poison, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0>, i8 [[CONV31_I]], i64 0
// CHECK-NEXT:    [[VECINIT40_I:%.*]] = insertelement <8 x i8> [[TMP8]], i8 [[CONV33_I]], i64 1
// CHECK-NEXT:    ret <8 x i8> [[VECINIT40_I]]
//
v8int8 test_extract_expo_v8int8 (v256mx4 m, int idx) { return extract_expo_v8int8(m, idx); }
// CHECK-LABEL: @_Z11test_update7v256mx4ii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX4:%.*]] [[S_COERCE:%.*]], 8
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 9
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 10
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 11
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 12
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 13
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 14
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 15
// CHECK-NEXT:    switch i32 [[IDX:%.*]], label [[SW_DEFAULT_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[_ZL6UPDATE7V256MX4II_EXIT:%.*]]
// CHECK-NEXT:      i32 1, label [[SW_BB1_I:%.*]]
// CHECK-NEXT:      i32 2, label [[SW_BB2_I:%.*]]
// CHECK-NEXT:      i32 3, label [[SW_BB3_I:%.*]]
// CHECK-NEXT:      i32 4, label [[SW_BB4_I:%.*]]
// CHECK-NEXT:      i32 5, label [[SW_BB5_I:%.*]]
// CHECK-NEXT:      i32 6, label [[SW_BB6_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       sw.bb1.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX4II_EXIT]]
// CHECK:       sw.bb2.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX4II_EXIT]]
// CHECK:       sw.bb3.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX4II_EXIT]]
// CHECK:       sw.bb4.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX4II_EXIT]]
// CHECK:       sw.bb5.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX4II_EXIT]]
// CHECK:       sw.bb6.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX4II_EXIT]]
// CHECK:       sw.default.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX4II_EXIT]]
// CHECK:       _ZL6update7v256mx4ii.exit:
// CHECK-NEXT:    [[S_SROA_9_0_I:%.*]] = phi i32 [ [[TMP0]], [[SW_DEFAULT_I]] ], [ [[TMP0]], [[SW_BB6_I]] ], [ [[TMP0]], [[SW_BB5_I]] ], [ [[M:%.*]], [[SW_BB4_I]] ], [ [[TMP0]], [[SW_BB3_I]] ], [ [[TMP0]], [[SW_BB2_I]] ], [ [[TMP0]], [[SW_BB1_I]] ], [ [[TMP0]], [[ENTRY:%.*]] ]
// CHECK-NEXT:    [[S_SROA_11_0_I:%.*]] = phi i32 [ [[TMP1]], [[SW_DEFAULT_I]] ], [ [[TMP1]], [[SW_BB6_I]] ], [ [[M]], [[SW_BB5_I]] ], [ [[TMP1]], [[SW_BB4_I]] ], [ [[TMP1]], [[SW_BB3_I]] ], [ [[TMP1]], [[SW_BB2_I]] ], [ [[TMP1]], [[SW_BB1_I]] ], [ [[TMP1]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_13_0_I:%.*]] = phi i32 [ [[TMP2]], [[SW_DEFAULT_I]] ], [ [[M]], [[SW_BB6_I]] ], [ [[TMP2]], [[SW_BB5_I]] ], [ [[TMP2]], [[SW_BB4_I]] ], [ [[TMP2]], [[SW_BB3_I]] ], [ [[TMP2]], [[SW_BB2_I]] ], [ [[TMP2]], [[SW_BB1_I]] ], [ [[TMP2]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_15_0_I:%.*]] = phi i32 [ [[M]], [[SW_DEFAULT_I]] ], [ [[TMP3]], [[SW_BB6_I]] ], [ [[TMP3]], [[SW_BB5_I]] ], [ [[TMP3]], [[SW_BB4_I]] ], [ [[TMP3]], [[SW_BB3_I]] ], [ [[TMP3]], [[SW_BB2_I]] ], [ [[TMP3]], [[SW_BB1_I]] ], [ [[TMP3]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_17_0_I:%.*]] = phi i32 [ [[TMP4]], [[SW_DEFAULT_I]] ], [ [[TMP4]], [[SW_BB6_I]] ], [ [[TMP4]], [[SW_BB5_I]] ], [ [[TMP4]], [[SW_BB4_I]] ], [ [[TMP4]], [[SW_BB3_I]] ], [ [[TMP4]], [[SW_BB2_I]] ], [ [[TMP4]], [[SW_BB1_I]] ], [ [[M]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_19_0_I:%.*]] = phi i32 [ [[TMP5]], [[SW_DEFAULT_I]] ], [ [[TMP5]], [[SW_BB6_I]] ], [ [[TMP5]], [[SW_BB5_I]] ], [ [[TMP5]], [[SW_BB4_I]] ], [ [[TMP5]], [[SW_BB3_I]] ], [ [[TMP5]], [[SW_BB2_I]] ], [ [[M]], [[SW_BB1_I]] ], [ [[TMP5]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_21_0_I:%.*]] = phi i32 [ [[TMP6]], [[SW_DEFAULT_I]] ], [ [[TMP6]], [[SW_BB6_I]] ], [ [[TMP6]], [[SW_BB5_I]] ], [ [[TMP6]], [[SW_BB4_I]] ], [ [[TMP6]], [[SW_BB3_I]] ], [ [[M]], [[SW_BB2_I]] ], [ [[TMP6]], [[SW_BB1_I]] ], [ [[TMP6]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_23_0_I:%.*]] = phi i32 [ [[TMP7]], [[SW_DEFAULT_I]] ], [ [[TMP7]], [[SW_BB6_I]] ], [ [[TMP7]], [[SW_BB5_I]] ], [ [[TMP7]], [[SW_BB4_I]] ], [ [[M]], [[SW_BB3_I]] ], [ [[TMP7]], [[SW_BB2_I]] ], [ [[TMP7]], [[SW_BB1_I]] ], [ [[TMP7]], [[ENTRY]] ]
// CHECK-NEXT:    [[DOTFCA_8_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[S_COERCE]], i32 [[S_SROA_9_0_I]], 8
// CHECK-NEXT:    [[DOTFCA_9_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_8_INSERT_I]], i32 [[S_SROA_11_0_I]], 9
// CHECK-NEXT:    [[DOTFCA_10_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_9_INSERT_I]], i32 [[S_SROA_13_0_I]], 10
// CHECK-NEXT:    [[DOTFCA_11_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_10_INSERT_I]], i32 [[S_SROA_15_0_I]], 11
// CHECK-NEXT:    [[DOTFCA_12_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_11_INSERT_I]], i32 [[S_SROA_17_0_I]], 12
// CHECK-NEXT:    [[DOTFCA_13_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_12_INSERT_I]], i32 [[S_SROA_19_0_I]], 13
// CHECK-NEXT:    [[DOTFCA_14_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_13_INSERT_I]], i32 [[S_SROA_21_0_I]], 14
// CHECK-NEXT:    [[DOTFCA_15_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_14_INSERT_I]], i32 [[S_SROA_23_0_I]], 15
// CHECK-NEXT:    ret [[STRUCT_V256MX4]] [[DOTFCA_15_INSERT_I]]
//
v256mx4 test_update (v256mx4 s, int idx, int m) { return update(s, idx, m); }
// CHECK-LABEL: @_Z11test_update7v256mx4iDv8_a(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX4:%.*]] [[S_COERCE:%.*]], 8
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 9
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 10
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 11
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 12
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 13
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 14
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 15
// CHECK-NEXT:    [[TMP8:%.*]] = bitcast <8 x i8> [[M:%.*]] to <2 x i32>
// CHECK-NEXT:    [[VECEXT14_I:%.*]] = extractelement <2 x i32> [[TMP8]], i64 0
// CHECK-NEXT:    [[VECEXT16_I:%.*]] = extractelement <2 x i32> [[TMP8]], i64 1
// CHECK-NEXT:    switch i32 [[IDX:%.*]], label [[SW_DEFAULT_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[_ZL6UPDATE7V256MX4IDV8_A_EXIT:%.*]]
// CHECK-NEXT:      i32 1, label [[SW_BB3_I:%.*]]
// CHECK-NEXT:      i32 2, label [[SW_BB8_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       sw.bb3.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX4IDV8_A_EXIT]]
// CHECK:       sw.bb8.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX4IDV8_A_EXIT]]
// CHECK:       sw.default.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX4IDV8_A_EXIT]]
// CHECK:       _ZL6update7v256mx4iDv8_a.exit:
// CHECK-NEXT:    [[S_SROA_9_0_I:%.*]] = phi i32 [ [[TMP0]], [[SW_DEFAULT_I]] ], [ [[VECEXT14_I]], [[SW_BB8_I]] ], [ [[TMP0]], [[SW_BB3_I]] ], [ [[TMP0]], [[ENTRY:%.*]] ]
// CHECK-NEXT:    [[S_SROA_11_0_I:%.*]] = phi i32 [ [[TMP1]], [[SW_DEFAULT_I]] ], [ [[VECEXT16_I]], [[SW_BB8_I]] ], [ [[TMP1]], [[SW_BB3_I]] ], [ [[TMP1]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_13_0_I:%.*]] = phi i32 [ [[VECEXT14_I]], [[SW_DEFAULT_I]] ], [ [[TMP2]], [[SW_BB8_I]] ], [ [[TMP2]], [[SW_BB3_I]] ], [ [[TMP2]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_15_0_I:%.*]] = phi i32 [ [[VECEXT16_I]], [[SW_DEFAULT_I]] ], [ [[TMP3]], [[SW_BB8_I]] ], [ [[TMP3]], [[SW_BB3_I]] ], [ [[TMP3]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_17_0_I:%.*]] = phi i32 [ [[TMP4]], [[SW_DEFAULT_I]] ], [ [[TMP4]], [[SW_BB8_I]] ], [ [[TMP4]], [[SW_BB3_I]] ], [ [[VECEXT14_I]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_19_0_I:%.*]] = phi i32 [ [[TMP5]], [[SW_DEFAULT_I]] ], [ [[TMP5]], [[SW_BB8_I]] ], [ [[TMP5]], [[SW_BB3_I]] ], [ [[VECEXT16_I]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_21_0_I:%.*]] = phi i32 [ [[TMP6]], [[SW_DEFAULT_I]] ], [ [[TMP6]], [[SW_BB8_I]] ], [ [[VECEXT14_I]], [[SW_BB3_I]] ], [ [[TMP6]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_23_0_I:%.*]] = phi i32 [ [[TMP7]], [[SW_DEFAULT_I]] ], [ [[TMP7]], [[SW_BB8_I]] ], [ [[VECEXT16_I]], [[SW_BB3_I]] ], [ [[TMP7]], [[ENTRY]] ]
// CHECK-NEXT:    [[DOTFCA_8_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[S_COERCE]], i32 [[S_SROA_9_0_I]], 8
// CHECK-NEXT:    [[DOTFCA_9_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_8_INSERT_I]], i32 [[S_SROA_11_0_I]], 9
// CHECK-NEXT:    [[DOTFCA_10_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_9_INSERT_I]], i32 [[S_SROA_13_0_I]], 10
// CHECK-NEXT:    [[DOTFCA_11_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_10_INSERT_I]], i32 [[S_SROA_15_0_I]], 11
// CHECK-NEXT:    [[DOTFCA_12_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_11_INSERT_I]], i32 [[S_SROA_17_0_I]], 12
// CHECK-NEXT:    [[DOTFCA_13_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_12_INSERT_I]], i32 [[S_SROA_19_0_I]], 13
// CHECK-NEXT:    [[DOTFCA_14_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_13_INSERT_I]], i32 [[S_SROA_21_0_I]], 14
// CHECK-NEXT:    [[DOTFCA_15_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_14_INSERT_I]], i32 [[S_SROA_23_0_I]], 15
// CHECK-NEXT:    ret [[STRUCT_V256MX4]] [[DOTFCA_15_INSERT_I]]
//
v256mx4 test_update (v256mx4 s, int idx, v8int8 m) { return update(s, idx, m); }
// CHECK-LABEL: @_Z21test_extract_v64uint47v256mx4i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX4:%.*]] [[M_COERCE:%.*]], 1
// CHECK-NEXT:    switch i32 [[IDX:%.*]], label [[IF_ELSE6_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[IF_THEN_I:%.*]]
// CHECK-NEXT:      i32 1, label [[_ZL16EXTRACT_V64UINT47V256MX4I_EXIT:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN5_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then.i:
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 0
// CHECK-NEXT:    br label [[_ZL16EXTRACT_V64UINT47V256MX4I_EXIT]]
// CHECK:       if.then5.i:
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 2
// CHECK-NEXT:    br label [[_ZL16EXTRACT_V64UINT47V256MX4I_EXIT]]
// CHECK:       if.else6.i:
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 3
// CHECK-NEXT:    br label [[_ZL16EXTRACT_V64UINT47V256MX4I_EXIT]]
// CHECK:       _ZL16extract_v64uint47v256mx4i.exit:
// CHECK-NEXT:    [[TEMP_0_I:%.*]] = phi <8 x i32> [ [[TMP1]], [[IF_THEN_I]] ], [ [[TMP2]], [[IF_THEN5_I]] ], [ [[TMP3]], [[IF_ELSE6_I]] ], [ [[TMP0]], [[ENTRY:%.*]] ]
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <8 x i32> [[TEMP_0_I]] to <32 x i8>
// CHECK-NEXT:    ret <32 x i8> [[TMP4]]
//
v64uint4 test_extract_v64uint4 (v256mx4 m, int idx) { return extract_v64uint4(m, idx); }
// CHECK-LABEL: @_Z22test_extract_v128uint47v256mx4i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX4:%.*]] [[M_COERCE:%.*]], 1
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 3
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 2
// CHECK-NEXT:    [[TEMP0_0_I:%.*]] = select i1 [[CMP_I]], <8 x i32> [[TMP1]], <8 x i32> [[TMP3]]
// CHECK-NEXT:    [[TEMP1_0_I:%.*]] = select i1 [[CMP_I]], <8 x i32> [[TMP0]], <8 x i32> [[TMP2]]
// CHECK-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <8 x i32> [[TEMP0_0_I]], <8 x i32> [[TEMP1_0_I]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <16 x i32> [[SHUFFLE_I_I_I]] to <64 x i8>
// CHECK-NEXT:    ret <64 x i8> [[TMP4]]
//
v128uint4 test_extract_v128uint4 (v256mx4 m, int idx) { return extract_v128uint4(m, idx); }
// CHECK-LABEL: @_Z11test_update7v256mx4iDv32_DU8_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX4:%.*]] [[S_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 2
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 3
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <32 x i8> [[M:%.*]] to <8 x i32>
// CHECK-NEXT:    switch i32 [[IDX:%.*]], label [[IF_ELSE6_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[_ZL6UPDATE7V256MX4IDV32_DU8__EXIT:%.*]]
// CHECK-NEXT:      i32 1, label [[IF_THEN2_I:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN5_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then2.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX4IDV32_DU8__EXIT]]
// CHECK:       if.then5.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX4IDV32_DU8__EXIT]]
// CHECK:       if.else6.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX4IDV32_DU8__EXIT]]
// CHECK:       _ZL6update7v256mx4iDv32_DU8_.exit:
// CHECK-NEXT:    [[S_SROA_3_0_I:%.*]] = phi <8 x i32> [ [[TMP4]], [[IF_THEN2_I]] ], [ [[TMP1]], [[IF_THEN5_I]] ], [ [[TMP1]], [[IF_ELSE6_I]] ], [ [[TMP1]], [[ENTRY:%.*]] ]
// CHECK-NEXT:    [[S_SROA_0_0_I:%.*]] = phi <8 x i32> [ [[TMP0]], [[IF_THEN2_I]] ], [ [[TMP0]], [[IF_THEN5_I]] ], [ [[TMP0]], [[IF_ELSE6_I]] ], [ [[TMP4]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_5_0_I:%.*]] = phi <8 x i32> [ [[TMP2]], [[IF_THEN2_I]] ], [ [[TMP4]], [[IF_THEN5_I]] ], [ [[TMP2]], [[IF_ELSE6_I]] ], [ [[TMP2]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_7_0_I:%.*]] = phi <8 x i32> [ [[TMP3]], [[IF_THEN2_I]] ], [ [[TMP3]], [[IF_THEN5_I]] ], [ [[TMP4]], [[IF_ELSE6_I]] ], [ [[TMP3]], [[ENTRY]] ]
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 15
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 14
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 13
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 12
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 11
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 10
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 9
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 8
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 7
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 6
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 5
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 4
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] poison, <8 x i32> [[S_SROA_0_0_I]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_0_INSERT_I]], <8 x i32> [[S_SROA_3_0_I]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_1_INSERT_I]], <8 x i32> [[S_SROA_5_0_I]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_2_INSERT_I]], <8 x i32> [[S_SROA_7_0_I]], 3
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_3_INSERT_I]], <2 x i32> [[TMP16]], 4
// CHECK-NEXT:    [[DOTFCA_5_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_4_INSERT_I]], <2 x i32> [[TMP15]], 5
// CHECK-NEXT:    [[DOTFCA_6_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_5_INSERT_I]], <2 x i32> [[TMP14]], 6
// CHECK-NEXT:    [[DOTFCA_7_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_6_INSERT_I]], <2 x i32> [[TMP13]], 7
// CHECK-NEXT:    [[DOTFCA_8_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_7_INSERT_I]], i32 [[TMP12]], 8
// CHECK-NEXT:    [[DOTFCA_9_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_8_INSERT_I]], i32 [[TMP11]], 9
// CHECK-NEXT:    [[DOTFCA_10_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_9_INSERT_I]], i32 [[TMP10]], 10
// CHECK-NEXT:    [[DOTFCA_11_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_10_INSERT_I]], i32 [[TMP9]], 11
// CHECK-NEXT:    [[DOTFCA_12_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_11_INSERT_I]], i32 [[TMP8]], 12
// CHECK-NEXT:    [[DOTFCA_13_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_12_INSERT_I]], i32 [[TMP7]], 13
// CHECK-NEXT:    [[DOTFCA_14_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_13_INSERT_I]], i32 [[TMP6]], 14
// CHECK-NEXT:    [[DOTFCA_15_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_14_INSERT_I]], i32 [[TMP5]], 15
// CHECK-NEXT:    ret [[STRUCT_V256MX4]] [[DOTFCA_15_INSERT_I]]
//
v256mx4 test_update (v256mx4 s, int idx, v64uint4 m) { return update(s, idx, m); }
// CHECK-LABEL: @_Z11test_update7v256mx4iDv64_DU8_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX4:%.*]] [[S_COERCE:%.*]], 1
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 2
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 3
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <64 x i8> [[M:%.*]] to <16 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I:%.*]] = shufflevector <16 x i32> [[TMP3]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE1_I28_I:%.*]] = shufflevector <16 x i32> [[TMP3]], <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[CMP_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 0
// CHECK-NEXT:    [[COND_I:%.*]] = select i1 [[CMP_I]], <8 x i32> [[SHUFFLE_I_I]], <8 x i32> [[TMP4]]
// CHECK-NEXT:    [[COND7_I:%.*]] = select i1 [[CMP_I]], <8 x i32> [[SHUFFLE1_I28_I]], <8 x i32> [[TMP0]]
// CHECK-NEXT:    [[COND13_I:%.*]] = select i1 [[CMP_I]], <8 x i32> [[TMP1]], <8 x i32> [[SHUFFLE_I_I]]
// CHECK-NEXT:    [[COND19_I:%.*]] = select i1 [[CMP_I]], <8 x i32> [[TMP2]], <8 x i32> [[SHUFFLE1_I28_I]]
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 15
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 14
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 13
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 12
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 11
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 10
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 9
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 8
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 7
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 6
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 5
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 4
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] poison, <8 x i32> [[COND_I]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_0_INSERT_I]], <8 x i32> [[COND7_I]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_1_INSERT_I]], <8 x i32> [[COND13_I]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_2_INSERT_I]], <8 x i32> [[COND19_I]], 3
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_3_INSERT_I]], <2 x i32> [[TMP16]], 4
// CHECK-NEXT:    [[DOTFCA_5_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_4_INSERT_I]], <2 x i32> [[TMP15]], 5
// CHECK-NEXT:    [[DOTFCA_6_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_5_INSERT_I]], <2 x i32> [[TMP14]], 6
// CHECK-NEXT:    [[DOTFCA_7_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_6_INSERT_I]], <2 x i32> [[TMP13]], 7
// CHECK-NEXT:    [[DOTFCA_8_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_7_INSERT_I]], i32 [[TMP12]], 8
// CHECK-NEXT:    [[DOTFCA_9_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_8_INSERT_I]], i32 [[TMP11]], 9
// CHECK-NEXT:    [[DOTFCA_10_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_9_INSERT_I]], i32 [[TMP10]], 10
// CHECK-NEXT:    [[DOTFCA_11_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_10_INSERT_I]], i32 [[TMP9]], 11
// CHECK-NEXT:    [[DOTFCA_12_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_11_INSERT_I]], i32 [[TMP8]], 12
// CHECK-NEXT:    [[DOTFCA_13_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_12_INSERT_I]], i32 [[TMP7]], 13
// CHECK-NEXT:    [[DOTFCA_14_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_13_INSERT_I]], i32 [[TMP6]], 14
// CHECK-NEXT:    [[DOTFCA_15_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_14_INSERT_I]], i32 [[TMP5]], 15
// CHECK-NEXT:    ret [[STRUCT_V256MX4]] [[DOTFCA_15_INSERT_I]]
//
v256mx4 test_update (v256mx4 s, int idx, v128uint4 m) { return update(s, idx, m); }
// CHECK-LABEL: @_Z19test_extract_v64mx47v256mx4i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX4:%.*]] [[M_COERCE:%.*]], 1
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 5
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 9
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 13
// CHECK-NEXT:    switch i32 [[IDX:%.*]], label [[IF_ELSE14_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[IF_THEN_I:%.*]]
// CHECK-NEXT:      i32 1, label [[_ZL14EXTRACT_V64MX47V256MX4I_EXIT:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN9_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then.i:
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 12
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 8
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 4
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 0
// CHECK-NEXT:    br label [[_ZL14EXTRACT_V64MX47V256MX4I_EXIT]]
// CHECK:       if.then9.i:
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 14
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 10
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 6
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 2
// CHECK-NEXT:    br label [[_ZL14EXTRACT_V64MX47V256MX4I_EXIT]]
// CHECK:       if.else14.i:
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 15
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 11
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 7
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 3
// CHECK-NEXT:    br label [[_ZL14EXTRACT_V64MX47V256MX4I_EXIT]]
// CHECK:       _ZL14extract_v64mx47v256mx4i.exit:
// CHECK-NEXT:    [[RETVAL_SROA_0_0_I:%.*]] = phi <8 x i32> [ [[TMP7]], [[IF_THEN_I]] ], [ [[TMP11]], [[IF_THEN9_I]] ], [ [[TMP15]], [[IF_ELSE14_I]] ], [ [[TMP0]], [[ENTRY:%.*]] ]
// CHECK-NEXT:    [[RETVAL_SROA_5_0_I:%.*]] = phi <2 x i32> [ [[TMP6]], [[IF_THEN_I]] ], [ [[TMP10]], [[IF_THEN9_I]] ], [ [[TMP14]], [[IF_ELSE14_I]] ], [ [[TMP1]], [[ENTRY]] ]
// CHECK-NEXT:    [[RETVAL_SROA_10_0_I:%.*]] = phi i32 [ [[TMP5]], [[IF_THEN_I]] ], [ [[TMP9]], [[IF_THEN9_I]] ], [ [[TMP13]], [[IF_ELSE14_I]] ], [ [[TMP2]], [[ENTRY]] ]
// CHECK-NEXT:    [[RETVAL_SROA_15_0_I:%.*]] = phi i32 [ [[TMP4]], [[IF_THEN_I]] ], [ [[TMP8]], [[IF_THEN9_I]] ], [ [[TMP12]], [[IF_ELSE14_I]] ], [ [[TMP3]], [[ENTRY]] ]
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX4:%.*]] poison, <8 x i32> [[RETVAL_SROA_0_0_I]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX4]] [[DOTFCA_0_INSERT_I]], <2 x i32> [[RETVAL_SROA_5_0_I]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX4]] [[DOTFCA_1_INSERT_I]], i32 [[RETVAL_SROA_10_0_I]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX4]] [[DOTFCA_2_INSERT_I]], i32 [[RETVAL_SROA_15_0_I]], 3
// CHECK-NEXT:    ret [[STRUCT_V64MX4]] [[DOTFCA_3_INSERT_I]]
//
v64mx4 test_extract_v64mx4 (v256mx4 m, int idx) { return extract_v64mx4(m, idx); }
// CHECK-LABEL: @_Z22test_extract_v64bfp11p7v256mx4i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX4:%.*]] [[M_COERCE:%.*]], 1
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 5
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 9
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 13
// CHECK-NEXT:    switch i32 [[IDX:%.*]], label [[IF_ELSE14_I_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[IF_THEN_I_I:%.*]]
// CHECK-NEXT:      i32 1, label [[_ZL17EXTRACT_V64BFP11P7V256MX4I_EXIT:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN9_I_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then.i.i:
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 12
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 8
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 4
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 0
// CHECK-NEXT:    br label [[_ZL17EXTRACT_V64BFP11P7V256MX4I_EXIT]]
// CHECK:       if.then9.i.i:
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 14
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 10
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 6
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 2
// CHECK-NEXT:    br label [[_ZL17EXTRACT_V64BFP11P7V256MX4I_EXIT]]
// CHECK:       if.else14.i.i:
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 15
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 11
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 7
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 3
// CHECK-NEXT:    br label [[_ZL17EXTRACT_V64BFP11P7V256MX4I_EXIT]]
// CHECK:       _ZL17extract_v64bfp11p7v256mx4i.exit:
// CHECK-NEXT:    [[RETVAL_SROA_0_0_I_I:%.*]] = phi <8 x i32> [ [[TMP7]], [[IF_THEN_I_I]] ], [ [[TMP11]], [[IF_THEN9_I_I]] ], [ [[TMP15]], [[IF_ELSE14_I_I]] ], [ [[TMP0]], [[ENTRY:%.*]] ]
// CHECK-NEXT:    [[RETVAL_SROA_5_0_I_I:%.*]] = phi <2 x i32> [ [[TMP6]], [[IF_THEN_I_I]] ], [ [[TMP10]], [[IF_THEN9_I_I]] ], [ [[TMP14]], [[IF_ELSE14_I_I]] ], [ [[TMP1]], [[ENTRY]] ]
// CHECK-NEXT:    [[RETVAL_SROA_10_0_I_I:%.*]] = phi i32 [ [[TMP5]], [[IF_THEN_I_I]] ], [ [[TMP9]], [[IF_THEN9_I_I]] ], [ [[TMP13]], [[IF_ELSE14_I_I]] ], [ [[TMP2]], [[ENTRY]] ]
// CHECK-NEXT:    [[RETVAL_SROA_15_0_I_I:%.*]] = phi i32 [ [[TMP4]], [[IF_THEN_I_I]] ], [ [[TMP8]], [[IF_THEN9_I_I]] ], [ [[TMP12]], [[IF_ELSE14_I_I]] ], [ [[TMP3]], [[ENTRY]] ]
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64MX4:%.*]] poison, <8 x i32> [[RETVAL_SROA_0_0_I_I]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64MX4]] [[DOTFCA_0_INSERT_I_I]], <2 x i32> [[RETVAL_SROA_5_0_I_I]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64MX4]] [[DOTFCA_1_INSERT_I_I]], i32 [[RETVAL_SROA_10_0_I_I]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64MX4]] [[DOTFCA_2_INSERT_I_I]], i32 [[RETVAL_SROA_15_0_I_I]], 3
// CHECK-NEXT:    ret [[STRUCT_V64MX4]] [[DOTFCA_3_INSERT_I_I]]
//
v64bfp11p test_extract_v64bfp11p (v256bfp11p m, int idx) { return extract_v64bfp11p(m, idx); }
// CHECK-LABEL: @_Z11test_update7v256mx4i6v64mx4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX4:%.*]] [[S_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 2
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 3
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 4
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 5
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 6
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 7
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 8
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 9
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 10
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 11
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 12
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 13
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 14
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 15
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue [[STRUCT_V64MX4:%.*]] [[M_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP17:%.*]] = extractvalue [[STRUCT_V64MX4]] [[M_COERCE]], 1
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue [[STRUCT_V64MX4]] [[M_COERCE]], 2
// CHECK-NEXT:    [[TMP19:%.*]] = extractvalue [[STRUCT_V64MX4]] [[M_COERCE]], 3
// CHECK-NEXT:    switch i32 [[IDX:%.*]], label [[IF_ELSE14_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[_ZL6UPDATE7V256MX4I6V64MX4_EXIT:%.*]]
// CHECK-NEXT:      i32 1, label [[IF_THEN2_I:%.*]]
// CHECK-NEXT:      i32 2, label [[IF_THEN9_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then2.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX4I6V64MX4_EXIT]]
// CHECK:       if.then9.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX4I6V64MX4_EXIT]]
// CHECK:       if.else14.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX4I6V64MX4_EXIT]]
// CHECK:       _ZL6update7v256mx4i6v64mx4.exit:
// CHECK-NEXT:    [[S_SROA_21_0_I:%.*]] = phi i32 [ [[TMP10]], [[IF_THEN2_I]] ], [ [[TMP18]], [[IF_THEN9_I]] ], [ [[TMP10]], [[IF_ELSE14_I]] ], [ [[TMP10]], [[ENTRY:%.*]] ]
// CHECK-NEXT:    [[S_SROA_19_0_I:%.*]] = phi i32 [ [[TMP18]], [[IF_THEN2_I]] ], [ [[TMP9]], [[IF_THEN9_I]] ], [ [[TMP9]], [[IF_ELSE14_I]] ], [ [[TMP9]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_17_0_I:%.*]] = phi i32 [ [[TMP8]], [[IF_THEN2_I]] ], [ [[TMP8]], [[IF_THEN9_I]] ], [ [[TMP8]], [[IF_ELSE14_I]] ], [ [[TMP18]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_15_0_I:%.*]] = phi <2 x i32> [ [[TMP7]], [[IF_THEN2_I]] ], [ [[TMP7]], [[IF_THEN9_I]] ], [ [[TMP17]], [[IF_ELSE14_I]] ], [ [[TMP7]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_13_0_I:%.*]] = phi <2 x i32> [ [[TMP6]], [[IF_THEN2_I]] ], [ [[TMP17]], [[IF_THEN9_I]] ], [ [[TMP6]], [[IF_ELSE14_I]] ], [ [[TMP6]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_11_0_I:%.*]] = phi <2 x i32> [ [[TMP17]], [[IF_THEN2_I]] ], [ [[TMP5]], [[IF_THEN9_I]] ], [ [[TMP5]], [[IF_ELSE14_I]] ], [ [[TMP5]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_9_0_I:%.*]] = phi <2 x i32> [ [[TMP4]], [[IF_THEN2_I]] ], [ [[TMP4]], [[IF_THEN9_I]] ], [ [[TMP4]], [[IF_ELSE14_I]] ], [ [[TMP17]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_7_0_I:%.*]] = phi <8 x i32> [ [[TMP3]], [[IF_THEN2_I]] ], [ [[TMP3]], [[IF_THEN9_I]] ], [ [[TMP16]], [[IF_ELSE14_I]] ], [ [[TMP3]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_5_0_I:%.*]] = phi <8 x i32> [ [[TMP2]], [[IF_THEN2_I]] ], [ [[TMP16]], [[IF_THEN9_I]] ], [ [[TMP2]], [[IF_ELSE14_I]] ], [ [[TMP2]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_3_0_I:%.*]] = phi <8 x i32> [ [[TMP16]], [[IF_THEN2_I]] ], [ [[TMP1]], [[IF_THEN9_I]] ], [ [[TMP1]], [[IF_ELSE14_I]] ], [ [[TMP1]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_0_0_I:%.*]] = phi <8 x i32> [ [[TMP0]], [[IF_THEN2_I]] ], [ [[TMP0]], [[IF_THEN9_I]] ], [ [[TMP0]], [[IF_ELSE14_I]] ], [ [[TMP16]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_23_0_I:%.*]] = phi i32 [ [[TMP11]], [[IF_THEN2_I]] ], [ [[TMP11]], [[IF_THEN9_I]] ], [ [[TMP18]], [[IF_ELSE14_I]] ], [ [[TMP11]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_25_0_I:%.*]] = phi i32 [ [[TMP12]], [[IF_THEN2_I]] ], [ [[TMP12]], [[IF_THEN9_I]] ], [ [[TMP12]], [[IF_ELSE14_I]] ], [ [[TMP19]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_27_0_I:%.*]] = phi i32 [ [[TMP19]], [[IF_THEN2_I]] ], [ [[TMP13]], [[IF_THEN9_I]] ], [ [[TMP13]], [[IF_ELSE14_I]] ], [ [[TMP13]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_29_0_I:%.*]] = phi i32 [ [[TMP14]], [[IF_THEN2_I]] ], [ [[TMP19]], [[IF_THEN9_I]] ], [ [[TMP14]], [[IF_ELSE14_I]] ], [ [[TMP14]], [[ENTRY]] ]
// CHECK-NEXT:    [[S_SROA_31_0_I:%.*]] = phi i32 [ [[TMP15]], [[IF_THEN2_I]] ], [ [[TMP15]], [[IF_THEN9_I]] ], [ [[TMP19]], [[IF_ELSE14_I]] ], [ [[TMP15]], [[ENTRY]] ]
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] poison, <8 x i32> [[S_SROA_0_0_I]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_0_INSERT_I]], <8 x i32> [[S_SROA_3_0_I]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_1_INSERT_I]], <8 x i32> [[S_SROA_5_0_I]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_2_INSERT_I]], <8 x i32> [[S_SROA_7_0_I]], 3
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_3_INSERT_I]], <2 x i32> [[S_SROA_9_0_I]], 4
// CHECK-NEXT:    [[DOTFCA_5_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_4_INSERT_I]], <2 x i32> [[S_SROA_11_0_I]], 5
// CHECK-NEXT:    [[DOTFCA_6_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_5_INSERT_I]], <2 x i32> [[S_SROA_13_0_I]], 6
// CHECK-NEXT:    [[DOTFCA_7_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_6_INSERT_I]], <2 x i32> [[S_SROA_15_0_I]], 7
// CHECK-NEXT:    [[DOTFCA_8_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_7_INSERT_I]], i32 [[S_SROA_17_0_I]], 8
// CHECK-NEXT:    [[DOTFCA_9_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_8_INSERT_I]], i32 [[S_SROA_19_0_I]], 9
// CHECK-NEXT:    [[DOTFCA_10_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_9_INSERT_I]], i32 [[S_SROA_21_0_I]], 10
// CHECK-NEXT:    [[DOTFCA_11_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_10_INSERT_I]], i32 [[S_SROA_23_0_I]], 11
// CHECK-NEXT:    [[DOTFCA_12_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_11_INSERT_I]], i32 [[S_SROA_25_0_I]], 12
// CHECK-NEXT:    [[DOTFCA_13_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_12_INSERT_I]], i32 [[S_SROA_27_0_I]], 13
// CHECK-NEXT:    [[DOTFCA_14_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_13_INSERT_I]], i32 [[S_SROA_29_0_I]], 14
// CHECK-NEXT:    [[DOTFCA_15_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_14_INSERT_I]], i32 [[S_SROA_31_0_I]], 15
// CHECK-NEXT:    ret [[STRUCT_V256MX4]] [[DOTFCA_15_INSERT_I]]
//
v256mx4 test_update (v256mx4 s, int idx, v64mx4 m) { return update(s, idx, m); }
// CHECK-LABEL: @_Z20test_extract_v128mx47v256mx4i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    br i1 [[CMP_I]], label [[IF_THEN_I:%.*]], label [[IF_ELSE_I:%.*]]
// CHECK:       if.then.i:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX4:%.*]] [[M_COERCE:%.*]], 13
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 12
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 9
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 8
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 5
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 4
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 0
// CHECK-NEXT:    br label [[_ZL15EXTRACT_V128MX47V256MX4I_EXIT:%.*]]
// CHECK:       if.else.i:
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 15
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 14
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 11
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 10
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 7
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 6
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 3
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 2
// CHECK-NEXT:    [[CMP9_I:%.*]] = icmp eq i32 [[IDX]], 1
// CHECK-NEXT:    tail call void @llvm.assume(i1 [[CMP9_I]])
// CHECK-NEXT:    br label [[_ZL15EXTRACT_V128MX47V256MX4I_EXIT]]
// CHECK:       _ZL15extract_v128mx47v256mx4i.exit:
// CHECK-NEXT:    [[RETVAL_SROA_0_0_I:%.*]] = phi <8 x i32> [ [[TMP7]], [[IF_THEN_I]] ], [ [[TMP15]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_3_0_I:%.*]] = phi <8 x i32> [ [[TMP6]], [[IF_THEN_I]] ], [ [[TMP14]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_6_0_I:%.*]] = phi <2 x i32> [ [[TMP5]], [[IF_THEN_I]] ], [ [[TMP13]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_9_0_I:%.*]] = phi <2 x i32> [ [[TMP4]], [[IF_THEN_I]] ], [ [[TMP12]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_12_0_I:%.*]] = phi i32 [ [[TMP3]], [[IF_THEN_I]] ], [ [[TMP11]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_15_0_I:%.*]] = phi i32 [ [[TMP2]], [[IF_THEN_I]] ], [ [[TMP10]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_18_0_I:%.*]] = phi i32 [ [[TMP1]], [[IF_THEN_I]] ], [ [[TMP9]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_21_0_I:%.*]] = phi i32 [ [[TMP0]], [[IF_THEN_I]] ], [ [[TMP8]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4:%.*]] poison, <8 x i32> [[RETVAL_SROA_0_0_I]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_0_INSERT_I]], <8 x i32> [[RETVAL_SROA_3_0_I]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_1_INSERT_I]], <2 x i32> [[RETVAL_SROA_6_0_I]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_2_INSERT_I]], <2 x i32> [[RETVAL_SROA_9_0_I]], 3
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_3_INSERT_I]], i32 [[RETVAL_SROA_12_0_I]], 4
// CHECK-NEXT:    [[DOTFCA_5_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_4_INSERT_I]], i32 [[RETVAL_SROA_15_0_I]], 5
// CHECK-NEXT:    [[DOTFCA_6_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_5_INSERT_I]], i32 [[RETVAL_SROA_18_0_I]], 6
// CHECK-NEXT:    [[DOTFCA_7_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_6_INSERT_I]], i32 [[RETVAL_SROA_21_0_I]], 7
// CHECK-NEXT:    ret [[STRUCT_V128MX4]] [[DOTFCA_7_INSERT_I]]
//
v128mx4 test_extract_v128mx4 (v256mx4 m, int idx) { return extract_v128mx4(m, idx); }
// CHECK-LABEL: @_Z23test_extract_v128bfp11p7v256mx4i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    br i1 [[CMP_I_I]], label [[IF_THEN_I_I:%.*]], label [[IF_ELSE_I_I:%.*]]
// CHECK:       if.then.i.i:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX4:%.*]] [[M_COERCE:%.*]], 13
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 12
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 9
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 8
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 5
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 4
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 0
// CHECK-NEXT:    br label [[_ZL18EXTRACT_V128BFP11P7V256MX4I_EXIT:%.*]]
// CHECK:       if.else.i.i:
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 15
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 14
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 11
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 10
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 7
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 6
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 3
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue [[STRUCT_V256MX4]] [[M_COERCE]], 2
// CHECK-NEXT:    [[CMP9_I_I:%.*]] = icmp eq i32 [[IDX]], 1
// CHECK-NEXT:    tail call void @llvm.assume(i1 [[CMP9_I_I]])
// CHECK-NEXT:    br label [[_ZL18EXTRACT_V128BFP11P7V256MX4I_EXIT]]
// CHECK:       _ZL18extract_v128bfp11p7v256mx4i.exit:
// CHECK-NEXT:    [[RETVAL_SROA_0_0_I_I:%.*]] = phi <8 x i32> [ [[TMP7]], [[IF_THEN_I_I]] ], [ [[TMP15]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_3_0_I_I:%.*]] = phi <8 x i32> [ [[TMP6]], [[IF_THEN_I_I]] ], [ [[TMP14]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_6_0_I_I:%.*]] = phi <2 x i32> [ [[TMP5]], [[IF_THEN_I_I]] ], [ [[TMP13]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_9_0_I_I:%.*]] = phi <2 x i32> [ [[TMP4]], [[IF_THEN_I_I]] ], [ [[TMP12]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_12_0_I_I:%.*]] = phi i32 [ [[TMP3]], [[IF_THEN_I_I]] ], [ [[TMP11]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_15_0_I_I:%.*]] = phi i32 [ [[TMP2]], [[IF_THEN_I_I]] ], [ [[TMP10]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_18_0_I_I:%.*]] = phi i32 [ [[TMP1]], [[IF_THEN_I_I]] ], [ [[TMP9]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_21_0_I_I:%.*]] = phi i32 [ [[TMP0]], [[IF_THEN_I_I]] ], [ [[TMP8]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX4:%.*]] poison, <8 x i32> [[RETVAL_SROA_0_0_I_I]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_0_INSERT_I_I]], <8 x i32> [[RETVAL_SROA_3_0_I_I]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_1_INSERT_I_I]], <2 x i32> [[RETVAL_SROA_6_0_I_I]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_2_INSERT_I_I]], <2 x i32> [[RETVAL_SROA_9_0_I_I]], 3
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_3_INSERT_I_I]], i32 [[RETVAL_SROA_12_0_I_I]], 4
// CHECK-NEXT:    [[DOTFCA_5_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_4_INSERT_I_I]], i32 [[RETVAL_SROA_15_0_I_I]], 5
// CHECK-NEXT:    [[DOTFCA_6_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_5_INSERT_I_I]], i32 [[RETVAL_SROA_18_0_I_I]], 6
// CHECK-NEXT:    [[DOTFCA_7_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_6_INSERT_I_I]], i32 [[RETVAL_SROA_21_0_I_I]], 7
// CHECK-NEXT:    ret [[STRUCT_V128MX4]] [[DOTFCA_7_INSERT_I_I]]
//
v128bfp11p test_extract_v128bfp11p (v256bfp11p m, int idx) { return extract_v128bfp11p(m, idx); }
// CHECK-LABEL: @_Z11test_update7v256mx4i7v128mx4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256MX4:%.*]] [[S_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 2
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 3
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 4
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 5
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 6
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 7
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 8
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 9
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 10
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 11
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 12
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 13
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 14
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue [[STRUCT_V256MX4]] [[S_COERCE]], 15
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue [[STRUCT_V128MX4:%.*]] [[M_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP17:%.*]] = extractvalue [[STRUCT_V128MX4]] [[M_COERCE]], 1
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue [[STRUCT_V128MX4]] [[M_COERCE]], 2
// CHECK-NEXT:    [[TMP19:%.*]] = extractvalue [[STRUCT_V128MX4]] [[M_COERCE]], 3
// CHECK-NEXT:    [[TMP20:%.*]] = extractvalue [[STRUCT_V128MX4]] [[M_COERCE]], 4
// CHECK-NEXT:    [[TMP21:%.*]] = extractvalue [[STRUCT_V128MX4]] [[M_COERCE]], 5
// CHECK-NEXT:    [[TMP22:%.*]] = extractvalue [[STRUCT_V128MX4]] [[M_COERCE]], 6
// CHECK-NEXT:    [[TMP23:%.*]] = extractvalue [[STRUCT_V128MX4]] [[M_COERCE]], 7
// CHECK-NEXT:    switch i32 [[IDX:%.*]], label [[IF_END19_FOLD_SPLIT_I:%.*]] [
// CHECK-NEXT:      i32 0, label [[_ZL6UPDATE7V256MX4I7V128MX4_EXIT:%.*]]
// CHECK-NEXT:      i32 1, label [[IF_THEN10_I:%.*]]
// CHECK-NEXT:    ]
// CHECK:       if.then10.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX4I7V128MX4_EXIT]]
// CHECK:       if.end19.fold.split.i:
// CHECK-NEXT:    br label [[_ZL6UPDATE7V256MX4I7V128MX4_EXIT]]
// CHECK:       _ZL6update7v256mx4i7v128mx4.exit:
// CHECK-NEXT:    [[S_SROA_13_0_I:%.*]] = phi <2 x i32> [ [[TMP18]], [[IF_THEN10_I]] ], [ [[TMP6]], [[ENTRY:%.*]] ], [ [[TMP6]], [[IF_END19_FOLD_SPLIT_I]] ]
// CHECK-NEXT:    [[S_SROA_11_0_I:%.*]] = phi <2 x i32> [ [[TMP5]], [[IF_THEN10_I]] ], [ [[TMP19]], [[ENTRY]] ], [ [[TMP5]], [[IF_END19_FOLD_SPLIT_I]] ]
// CHECK-NEXT:    [[S_SROA_9_0_I:%.*]] = phi <2 x i32> [ [[TMP4]], [[IF_THEN10_I]] ], [ [[TMP18]], [[ENTRY]] ], [ [[TMP4]], [[IF_END19_FOLD_SPLIT_I]] ]
// CHECK-NEXT:    [[S_SROA_7_0_I:%.*]] = phi <8 x i32> [ [[TMP17]], [[IF_THEN10_I]] ], [ [[TMP3]], [[ENTRY]] ], [ [[TMP3]], [[IF_END19_FOLD_SPLIT_I]] ]
// CHECK-NEXT:    [[S_SROA_5_0_I:%.*]] = phi <8 x i32> [ [[TMP16]], [[IF_THEN10_I]] ], [ [[TMP2]], [[ENTRY]] ], [ [[TMP2]], [[IF_END19_FOLD_SPLIT_I]] ]
// CHECK-NEXT:    [[S_SROA_3_0_I:%.*]] = phi <8 x i32> [ [[TMP1]], [[IF_THEN10_I]] ], [ [[TMP17]], [[ENTRY]] ], [ [[TMP1]], [[IF_END19_FOLD_SPLIT_I]] ]
// CHECK-NEXT:    [[S_SROA_0_0_I:%.*]] = phi <8 x i32> [ [[TMP0]], [[IF_THEN10_I]] ], [ [[TMP16]], [[ENTRY]] ], [ [[TMP0]], [[IF_END19_FOLD_SPLIT_I]] ]
// CHECK-NEXT:    [[S_SROA_15_0_I:%.*]] = phi <2 x i32> [ [[TMP19]], [[IF_THEN10_I]] ], [ [[TMP7]], [[ENTRY]] ], [ [[TMP7]], [[IF_END19_FOLD_SPLIT_I]] ]
// CHECK-NEXT:    [[S_SROA_17_0_I:%.*]] = phi i32 [ [[TMP8]], [[IF_THEN10_I]] ], [ [[TMP20]], [[ENTRY]] ], [ [[TMP8]], [[IF_END19_FOLD_SPLIT_I]] ]
// CHECK-NEXT:    [[S_SROA_19_0_I:%.*]] = phi i32 [ [[TMP9]], [[IF_THEN10_I]] ], [ [[TMP21]], [[ENTRY]] ], [ [[TMP9]], [[IF_END19_FOLD_SPLIT_I]] ]
// CHECK-NEXT:    [[S_SROA_21_0_I:%.*]] = phi i32 [ [[TMP20]], [[IF_THEN10_I]] ], [ [[TMP10]], [[ENTRY]] ], [ [[TMP10]], [[IF_END19_FOLD_SPLIT_I]] ]
// CHECK-NEXT:    [[S_SROA_23_0_I:%.*]] = phi i32 [ [[TMP21]], [[IF_THEN10_I]] ], [ [[TMP11]], [[ENTRY]] ], [ [[TMP11]], [[IF_END19_FOLD_SPLIT_I]] ]
// CHECK-NEXT:    [[S_SROA_25_0_I:%.*]] = phi i32 [ [[TMP12]], [[IF_THEN10_I]] ], [ [[TMP22]], [[ENTRY]] ], [ [[TMP12]], [[IF_END19_FOLD_SPLIT_I]] ]
// CHECK-NEXT:    [[S_SROA_27_0_I:%.*]] = phi i32 [ [[TMP13]], [[IF_THEN10_I]] ], [ [[TMP23]], [[ENTRY]] ], [ [[TMP13]], [[IF_END19_FOLD_SPLIT_I]] ]
// CHECK-NEXT:    [[S_SROA_29_0_I:%.*]] = phi i32 [ [[TMP22]], [[IF_THEN10_I]] ], [ [[TMP14]], [[ENTRY]] ], [ [[TMP14]], [[IF_END19_FOLD_SPLIT_I]] ]
// CHECK-NEXT:    [[S_SROA_31_0_I:%.*]] = phi i32 [ [[TMP23]], [[IF_THEN10_I]] ], [ [[TMP15]], [[ENTRY]] ], [ [[TMP15]], [[IF_END19_FOLD_SPLIT_I]] ]
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] poison, <8 x i32> [[S_SROA_0_0_I]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_0_INSERT_I]], <8 x i32> [[S_SROA_3_0_I]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_1_INSERT_I]], <8 x i32> [[S_SROA_5_0_I]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_2_INSERT_I]], <8 x i32> [[S_SROA_7_0_I]], 3
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_3_INSERT_I]], <2 x i32> [[S_SROA_9_0_I]], 4
// CHECK-NEXT:    [[DOTFCA_5_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_4_INSERT_I]], <2 x i32> [[S_SROA_11_0_I]], 5
// CHECK-NEXT:    [[DOTFCA_6_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_5_INSERT_I]], <2 x i32> [[S_SROA_13_0_I]], 6
// CHECK-NEXT:    [[DOTFCA_7_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_6_INSERT_I]], <2 x i32> [[S_SROA_15_0_I]], 7
// CHECK-NEXT:    [[DOTFCA_8_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_7_INSERT_I]], i32 [[S_SROA_17_0_I]], 8
// CHECK-NEXT:    [[DOTFCA_9_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_8_INSERT_I]], i32 [[S_SROA_19_0_I]], 9
// CHECK-NEXT:    [[DOTFCA_10_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_9_INSERT_I]], i32 [[S_SROA_21_0_I]], 10
// CHECK-NEXT:    [[DOTFCA_11_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_10_INSERT_I]], i32 [[S_SROA_23_0_I]], 11
// CHECK-NEXT:    [[DOTFCA_12_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_11_INSERT_I]], i32 [[S_SROA_25_0_I]], 12
// CHECK-NEXT:    [[DOTFCA_13_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_12_INSERT_I]], i32 [[S_SROA_27_0_I]], 13
// CHECK-NEXT:    [[DOTFCA_14_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_13_INSERT_I]], i32 [[S_SROA_29_0_I]], 14
// CHECK-NEXT:    [[DOTFCA_15_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_14_INSERT_I]], i32 [[S_SROA_31_0_I]], 15
// CHECK-NEXT:    ret [[STRUCT_V256MX4]] [[DOTFCA_15_INSERT_I]]
//
v256mx4 test_update (v256mx4 s, int idx, v128mx4 m) { return update(s, idx, m); }
// CHECK-LABEL: @_Z16test_set_v256mx4i7v128mx4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V128MX4:%.*]] [[M_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V128MX4]] [[M_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128MX4]] [[M_COERCE]], 2
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128MX4]] [[M_COERCE]], 3
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128MX4]] [[M_COERCE]], 4
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128MX4]] [[M_COERCE]], 5
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V128MX4]] [[M_COERCE]], 6
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V128MX4]] [[M_COERCE]], 7
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4:%.*]] poison, <8 x i32> [[TMP0]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_0_INSERT_I]], <8 x i32> [[TMP1]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_1_INSERT_I]], <8 x i32> [[TMP0]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_2_INSERT_I]], <8 x i32> [[TMP1]], 3
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_3_INSERT_I]], <2 x i32> [[TMP2]], 4
// CHECK-NEXT:    [[DOTFCA_5_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_4_INSERT_I]], <2 x i32> [[TMP3]], 5
// CHECK-NEXT:    [[DOTFCA_6_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_5_INSERT_I]], <2 x i32> [[TMP2]], 6
// CHECK-NEXT:    [[DOTFCA_7_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_6_INSERT_I]], <2 x i32> [[TMP3]], 7
// CHECK-NEXT:    [[DOTFCA_8_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_7_INSERT_I]], i32 [[TMP4]], 8
// CHECK-NEXT:    [[DOTFCA_9_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_8_INSERT_I]], i32 [[TMP5]], 9
// CHECK-NEXT:    [[DOTFCA_10_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_9_INSERT_I]], i32 [[TMP4]], 10
// CHECK-NEXT:    [[DOTFCA_11_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_10_INSERT_I]], i32 [[TMP5]], 11
// CHECK-NEXT:    [[DOTFCA_12_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_11_INSERT_I]], i32 [[TMP6]], 12
// CHECK-NEXT:    [[DOTFCA_13_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_12_INSERT_I]], i32 [[TMP7]], 13
// CHECK-NEXT:    [[DOTFCA_14_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_13_INSERT_I]], i32 [[TMP6]], 14
// CHECK-NEXT:    [[DOTFCA_15_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_14_INSERT_I]], i32 [[TMP7]], 15
// CHECK-NEXT:    ret [[STRUCT_V256MX4]] [[DOTFCA_15_INSERT_I]]
//
v256mx4 test_set_v256mx4 (int idx, v128mx4 m) { return set_v256mx4(idx, m); }
// CHECK-LABEL: @_Z19test_set_v256bfp11pi7v128mx4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V128MX4:%.*]] [[M_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V128MX4]] [[M_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128MX4]] [[M_COERCE]], 2
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128MX4]] [[M_COERCE]], 3
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128MX4]] [[M_COERCE]], 4
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128MX4]] [[M_COERCE]], 5
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V128MX4]] [[M_COERCE]], 6
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V128MX4]] [[M_COERCE]], 7
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX4:%.*]] poison, <8 x i32> [[TMP0]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_0_INSERT_I_I]], <8 x i32> [[TMP1]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_1_INSERT_I_I]], <8 x i32> [[TMP0]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_2_INSERT_I_I]], <8 x i32> [[TMP1]], 3
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_3_INSERT_I_I]], <2 x i32> [[TMP2]], 4
// CHECK-NEXT:    [[DOTFCA_5_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_4_INSERT_I_I]], <2 x i32> [[TMP3]], 5
// CHECK-NEXT:    [[DOTFCA_6_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_5_INSERT_I_I]], <2 x i32> [[TMP2]], 6
// CHECK-NEXT:    [[DOTFCA_7_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_6_INSERT_I_I]], <2 x i32> [[TMP3]], 7
// CHECK-NEXT:    [[DOTFCA_8_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_7_INSERT_I_I]], i32 [[TMP4]], 8
// CHECK-NEXT:    [[DOTFCA_9_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_8_INSERT_I_I]], i32 [[TMP5]], 9
// CHECK-NEXT:    [[DOTFCA_10_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_9_INSERT_I_I]], i32 [[TMP4]], 10
// CHECK-NEXT:    [[DOTFCA_11_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_10_INSERT_I_I]], i32 [[TMP5]], 11
// CHECK-NEXT:    [[DOTFCA_12_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_11_INSERT_I_I]], i32 [[TMP6]], 12
// CHECK-NEXT:    [[DOTFCA_13_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_12_INSERT_I_I]], i32 [[TMP7]], 13
// CHECK-NEXT:    [[DOTFCA_14_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_13_INSERT_I_I]], i32 [[TMP6]], 14
// CHECK-NEXT:    [[DOTFCA_15_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_14_INSERT_I_I]], i32 [[TMP7]], 15
// CHECK-NEXT:    ret [[STRUCT_V256MX4]] [[DOTFCA_15_INSERT_I_I]]
//
v256bfp11p test_set_v256bfp11p (int idx, v128bfp11p m) { return set_v256bfp11p(idx, m); }
// CHECK-LABEL: @_Z11test_concat7v128mx4S_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V128MX4:%.*]] [[V0_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V0_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V0_COERCE]], 2
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V0_COERCE]], 3
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V0_COERCE]], 4
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V0_COERCE]], 5
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V0_COERCE]], 6
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V0_COERCE]], 7
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V1_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V1_COERCE]], 1
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V1_COERCE]], 2
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V1_COERCE]], 3
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V1_COERCE]], 4
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V1_COERCE]], 5
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V1_COERCE]], 6
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V1_COERCE]], 7
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4:%.*]] poison, <8 x i32> [[TMP0]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_0_INSERT_I]], <8 x i32> [[TMP1]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_1_INSERT_I]], <8 x i32> [[TMP8]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_2_INSERT_I]], <8 x i32> [[TMP9]], 3
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_3_INSERT_I]], <2 x i32> [[TMP2]], 4
// CHECK-NEXT:    [[DOTFCA_5_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_4_INSERT_I]], <2 x i32> [[TMP3]], 5
// CHECK-NEXT:    [[DOTFCA_6_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_5_INSERT_I]], <2 x i32> [[TMP10]], 6
// CHECK-NEXT:    [[DOTFCA_7_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_6_INSERT_I]], <2 x i32> [[TMP11]], 7
// CHECK-NEXT:    [[DOTFCA_8_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_7_INSERT_I]], i32 [[TMP4]], 8
// CHECK-NEXT:    [[DOTFCA_9_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_8_INSERT_I]], i32 [[TMP5]], 9
// CHECK-NEXT:    [[DOTFCA_10_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_9_INSERT_I]], i32 [[TMP12]], 10
// CHECK-NEXT:    [[DOTFCA_11_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_10_INSERT_I]], i32 [[TMP13]], 11
// CHECK-NEXT:    [[DOTFCA_12_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_11_INSERT_I]], i32 [[TMP6]], 12
// CHECK-NEXT:    [[DOTFCA_13_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_12_INSERT_I]], i32 [[TMP7]], 13
// CHECK-NEXT:    [[DOTFCA_14_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_13_INSERT_I]], i32 [[TMP14]], 14
// CHECK-NEXT:    [[DOTFCA_15_INSERT_I:%.*]] = insertvalue [[STRUCT_V256MX4]] [[DOTFCA_14_INSERT_I]], i32 [[TMP15]], 15
// CHECK-NEXT:    ret [[STRUCT_V256MX4]] [[DOTFCA_15_INSERT_I]]
//
v256mx4             test_concat (v128mx4 v0, v128mx4 v1) { return concat(v0, v1); }
// CHECK-LABEL: @_Z19test_extract_v64mx67v128mx6i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    br i1 [[CMP_I]], label [[IF_THEN_I:%.*]], label [[IF_ELSE_I:%.*]]
// CHECK:       if.then.i:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V128MX6:%.*]] [[M_COERCE:%.*]], 6
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V128MX6]] [[M_COERCE]], 4
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128MX6]] [[M_COERCE]], 2
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128MX6]] [[M_COERCE]], 0
// CHECK-NEXT:    br label [[_ZL14EXTRACT_V64MX67V128MX6I_EXIT:%.*]]
// CHECK:       if.else.i:
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128MX6]] [[M_COERCE]], 7
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128MX6]] [[M_COERCE]], 5
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V128MX6]] [[M_COERCE]], 3
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V128MX6]] [[M_COERCE]], 1
// CHECK-NEXT:    [[CMP1_I:%.*]] = icmp eq i32 [[IDX]], 1
// CHECK-NEXT:    tail call void @llvm.assume(i1 [[CMP1_I]])
// CHECK-NEXT:    br label [[_ZL14EXTRACT_V64MX67V128MX6I_EXIT]]
// CHECK:       _ZL14extract_v64mx67v128mx6i.exit:
// CHECK-NEXT:    [[RETVAL_SROA_0_0_I:%.*]] = phi <8 x i32> [ [[TMP3]], [[IF_THEN_I]] ], [ [[TMP7]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_3_0_I:%.*]] = phi <2 x i32> [ [[TMP2]], [[IF_THEN_I]] ], [ [[TMP6]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_6_0_I:%.*]] = phi i32 [ [[TMP1]], [[IF_THEN_I]] ], [ [[TMP5]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_9_0_I:%.*]] = phi i32 [ [[TMP0]], [[IF_THEN_I]] ], [ [[TMP4]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX6:%.*]] poison, <8 x i32> [[RETVAL_SROA_0_0_I]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX6]] [[DOTFCA_0_INSERT_I]], <2 x i32> [[RETVAL_SROA_3_0_I]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX6]] [[DOTFCA_1_INSERT_I]], i32 [[RETVAL_SROA_6_0_I]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX6]] [[DOTFCA_2_INSERT_I]], i32 [[RETVAL_SROA_9_0_I]], 3
// CHECK-NEXT:    ret [[STRUCT_V64MX6]] [[DOTFCA_3_INSERT_I]]
//
v64mx6 test_extract_v64mx6 (v128mx6 m, int idx) { return extract_v64mx6(m, idx); }
// CHECK-LABEL: @_Z22test_extract_v64bfp13p7v128mx6i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    br i1 [[CMP_I_I]], label [[IF_THEN_I_I:%.*]], label [[IF_ELSE_I_I:%.*]]
// CHECK:       if.then.i.i:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V128MX6:%.*]] [[M_COERCE:%.*]], 6
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V128MX6]] [[M_COERCE]], 4
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128MX6]] [[M_COERCE]], 2
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128MX6]] [[M_COERCE]], 0
// CHECK-NEXT:    br label [[_ZL17EXTRACT_V64BFP13P7V128MX6I_EXIT:%.*]]
// CHECK:       if.else.i.i:
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128MX6]] [[M_COERCE]], 7
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128MX6]] [[M_COERCE]], 5
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V128MX6]] [[M_COERCE]], 3
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V128MX6]] [[M_COERCE]], 1
// CHECK-NEXT:    [[CMP1_I_I:%.*]] = icmp eq i32 [[IDX]], 1
// CHECK-NEXT:    tail call void @llvm.assume(i1 [[CMP1_I_I]])
// CHECK-NEXT:    br label [[_ZL17EXTRACT_V64BFP13P7V128MX6I_EXIT]]
// CHECK:       _ZL17extract_v64bfp13p7v128mx6i.exit:
// CHECK-NEXT:    [[RETVAL_SROA_0_0_I_I:%.*]] = phi <8 x i32> [ [[TMP3]], [[IF_THEN_I_I]] ], [ [[TMP7]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_3_0_I_I:%.*]] = phi <2 x i32> [ [[TMP2]], [[IF_THEN_I_I]] ], [ [[TMP6]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_6_0_I_I:%.*]] = phi i32 [ [[TMP1]], [[IF_THEN_I_I]] ], [ [[TMP5]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_9_0_I_I:%.*]] = phi i32 [ [[TMP0]], [[IF_THEN_I_I]] ], [ [[TMP4]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64MX6:%.*]] poison, <8 x i32> [[RETVAL_SROA_0_0_I_I]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64MX6]] [[DOTFCA_0_INSERT_I_I]], <2 x i32> [[RETVAL_SROA_3_0_I_I]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64MX6]] [[DOTFCA_1_INSERT_I_I]], i32 [[RETVAL_SROA_6_0_I_I]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64MX6]] [[DOTFCA_2_INSERT_I_I]], i32 [[RETVAL_SROA_9_0_I_I]], 3
// CHECK-NEXT:    ret [[STRUCT_V64MX6]] [[DOTFCA_3_INSERT_I_I]]
//
v64bfp13p test_extract_v64bfp13p (v128bfp13p m, int idx) { return extract_v64bfp13p(m, idx); }
// CHECK-LABEL: @_Z11test_insert7v128mx6i6v64mx6(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64MX6:%.*]] [[M_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64MX6]] [[M_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64MX6]] [[M_COERCE]], 2
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64MX6]] [[M_COERCE]], 3
// CHECK-NEXT:    [[CMP_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    br i1 [[CMP_I]], label [[IF_THEN_I:%.*]], label [[IF_ELSE_I:%.*]]
// CHECK:       if.then.i:
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128MX6:%.*]] [[S_COERCE:%.*]], 7
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128MX6]] [[S_COERCE]], 5
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V128MX6]] [[S_COERCE]], 3
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V128MX6]] [[S_COERCE]], 1
// CHECK-NEXT:    br label [[_ZL6INSERT7V128MX6I6V64MX6_EXIT:%.*]]
// CHECK:       if.else.i:
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V128MX6]] [[S_COERCE]], 6
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue [[STRUCT_V128MX6]] [[S_COERCE]], 4
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue [[STRUCT_V128MX6]] [[S_COERCE]], 2
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue [[STRUCT_V128MX6]] [[S_COERCE]], 0
// CHECK-NEXT:    [[CMP5_I:%.*]] = icmp eq i32 [[IDX]], 1
// CHECK-NEXT:    tail call void @llvm.assume(i1 [[CMP5_I]])
// CHECK-NEXT:    br label [[_ZL6INSERT7V128MX6I6V64MX6_EXIT]]
// CHECK:       _ZL6insert7v128mx6i6v64mx6.exit:
// CHECK-NEXT:    [[RETVAL_SROA_0_0_I:%.*]] = phi <8 x i32> [ [[TMP0]], [[IF_THEN_I]] ], [ [[TMP11]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_3_0_I:%.*]] = phi <8 x i32> [ [[TMP7]], [[IF_THEN_I]] ], [ [[TMP0]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_6_0_I:%.*]] = phi <2 x i32> [ [[TMP1]], [[IF_THEN_I]] ], [ [[TMP10]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_9_0_I:%.*]] = phi <2 x i32> [ [[TMP6]], [[IF_THEN_I]] ], [ [[TMP1]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_12_0_I:%.*]] = phi i32 [ [[TMP2]], [[IF_THEN_I]] ], [ [[TMP9]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_15_0_I:%.*]] = phi i32 [ [[TMP5]], [[IF_THEN_I]] ], [ [[TMP2]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_18_0_I:%.*]] = phi i32 [ [[TMP3]], [[IF_THEN_I]] ], [ [[TMP8]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_21_0_I:%.*]] = phi i32 [ [[TMP4]], [[IF_THEN_I]] ], [ [[TMP3]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX6]] poison, <8 x i32> [[RETVAL_SROA_0_0_I]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_0_INSERT_I]], <8 x i32> [[RETVAL_SROA_3_0_I]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_1_INSERT_I]], <2 x i32> [[RETVAL_SROA_6_0_I]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_2_INSERT_I]], <2 x i32> [[RETVAL_SROA_9_0_I]], 3
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_3_INSERT_I]], i32 [[RETVAL_SROA_12_0_I]], 4
// CHECK-NEXT:    [[DOTFCA_5_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_4_INSERT_I]], i32 [[RETVAL_SROA_15_0_I]], 5
// CHECK-NEXT:    [[DOTFCA_6_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_5_INSERT_I]], i32 [[RETVAL_SROA_18_0_I]], 6
// CHECK-NEXT:    [[DOTFCA_7_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_6_INSERT_I]], i32 [[RETVAL_SROA_21_0_I]], 7
// CHECK-NEXT:    ret [[STRUCT_V128MX6]] [[DOTFCA_7_INSERT_I]]
//
v128mx6 test_insert (v128mx6 s, int idx, v64mx6 m) { return insert(s, idx, m); }
// CHECK-LABEL: @_Z16test_set_v128mx6i6v64mx6(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64MX6:%.*]] [[M_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64MX6]] [[M_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64MX6]] [[M_COERCE]], 2
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64MX6]] [[M_COERCE]], 3
// CHECK-NEXT:    [[CMP_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    br i1 [[CMP_I]], label [[_ZL11SET_V128MX6I6V64MX6_EXIT:%.*]], label [[IF_ELSE_I:%.*]]
// CHECK:       if.else.i:
// CHECK-NEXT:    [[CMP5_I:%.*]] = icmp eq i32 [[IDX]], 1
// CHECK-NEXT:    tail call void @llvm.assume(i1 [[CMP5_I]])
// CHECK-NEXT:    br label [[_ZL11SET_V128MX6I6V64MX6_EXIT]]
// CHECK:       _ZL11set_v128mx6i6v64mx6.exit:
// CHECK-NEXT:    [[RETVAL_SROA_6_0_I:%.*]] = phi <2 x i32> [ undef, [[IF_ELSE_I]] ], [ [[TMP1]], [[ENTRY:%.*]] ]
// CHECK-NEXT:    [[RETVAL_SROA_3_0_I:%.*]] = phi <8 x i32> [ [[TMP0]], [[IF_ELSE_I]] ], [ undef, [[ENTRY]] ]
// CHECK-NEXT:    [[RETVAL_SROA_0_0_I:%.*]] = phi <8 x i32> [ undef, [[IF_ELSE_I]] ], [ [[TMP0]], [[ENTRY]] ]
// CHECK-NEXT:    [[RETVAL_SROA_9_0_I:%.*]] = phi <2 x i32> [ [[TMP1]], [[IF_ELSE_I]] ], [ undef, [[ENTRY]] ]
// CHECK-NEXT:    [[RETVAL_SROA_12_0_I:%.*]] = phi i32 [ undef, [[IF_ELSE_I]] ], [ [[TMP2]], [[ENTRY]] ]
// CHECK-NEXT:    [[RETVAL_SROA_15_0_I:%.*]] = phi i32 [ [[TMP2]], [[IF_ELSE_I]] ], [ undef, [[ENTRY]] ]
// CHECK-NEXT:    [[RETVAL_SROA_18_0_I:%.*]] = phi i32 [ undef, [[IF_ELSE_I]] ], [ [[TMP3]], [[ENTRY]] ]
// CHECK-NEXT:    [[RETVAL_SROA_21_0_I:%.*]] = phi i32 [ [[TMP3]], [[IF_ELSE_I]] ], [ undef, [[ENTRY]] ]
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX6:%.*]] poison, <8 x i32> [[RETVAL_SROA_0_0_I]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_0_INSERT_I]], <8 x i32> [[RETVAL_SROA_3_0_I]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_1_INSERT_I]], <2 x i32> [[RETVAL_SROA_6_0_I]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_2_INSERT_I]], <2 x i32> [[RETVAL_SROA_9_0_I]], 3
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_3_INSERT_I]], i32 [[RETVAL_SROA_12_0_I]], 4
// CHECK-NEXT:    [[DOTFCA_5_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_4_INSERT_I]], i32 [[RETVAL_SROA_15_0_I]], 5
// CHECK-NEXT:    [[DOTFCA_6_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_5_INSERT_I]], i32 [[RETVAL_SROA_18_0_I]], 6
// CHECK-NEXT:    [[DOTFCA_7_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_6_INSERT_I]], i32 [[RETVAL_SROA_21_0_I]], 7
// CHECK-NEXT:    ret [[STRUCT_V128MX6]] [[DOTFCA_7_INSERT_I]]
//
v128mx6 test_set_v128mx6 (int idx, v64mx6 m) { return set_v128mx6(idx, m); }
// CHECK-LABEL: @_Z19test_set_v128bfp13pi6v64mx6(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64MX6:%.*]] [[M_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64MX6]] [[M_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64MX6]] [[M_COERCE]], 2
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64MX6]] [[M_COERCE]], 3
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    br i1 [[CMP_I_I]], label [[_ZL14SET_V128BFP13PI6V64MX6_EXIT:%.*]], label [[IF_ELSE_I_I:%.*]]
// CHECK:       if.else.i.i:
// CHECK-NEXT:    [[CMP5_I_I:%.*]] = icmp eq i32 [[IDX]], 1
// CHECK-NEXT:    tail call void @llvm.assume(i1 [[CMP5_I_I]])
// CHECK-NEXT:    br label [[_ZL14SET_V128BFP13PI6V64MX6_EXIT]]
// CHECK:       _ZL14set_v128bfp13pi6v64mx6.exit:
// CHECK-NEXT:    [[RETVAL_SROA_6_0_I_I:%.*]] = phi <2 x i32> [ undef, [[IF_ELSE_I_I]] ], [ [[TMP1]], [[ENTRY:%.*]] ]
// CHECK-NEXT:    [[RETVAL_SROA_3_0_I_I:%.*]] = phi <8 x i32> [ [[TMP0]], [[IF_ELSE_I_I]] ], [ undef, [[ENTRY]] ]
// CHECK-NEXT:    [[RETVAL_SROA_0_0_I_I:%.*]] = phi <8 x i32> [ undef, [[IF_ELSE_I_I]] ], [ [[TMP0]], [[ENTRY]] ]
// CHECK-NEXT:    [[RETVAL_SROA_9_0_I_I:%.*]] = phi <2 x i32> [ [[TMP1]], [[IF_ELSE_I_I]] ], [ undef, [[ENTRY]] ]
// CHECK-NEXT:    [[RETVAL_SROA_12_0_I_I:%.*]] = phi i32 [ undef, [[IF_ELSE_I_I]] ], [ [[TMP2]], [[ENTRY]] ]
// CHECK-NEXT:    [[RETVAL_SROA_15_0_I_I:%.*]] = phi i32 [ [[TMP2]], [[IF_ELSE_I_I]] ], [ undef, [[ENTRY]] ]
// CHECK-NEXT:    [[RETVAL_SROA_18_0_I_I:%.*]] = phi i32 [ undef, [[IF_ELSE_I_I]] ], [ [[TMP3]], [[ENTRY]] ]
// CHECK-NEXT:    [[RETVAL_SROA_21_0_I_I:%.*]] = phi i32 [ [[TMP3]], [[IF_ELSE_I_I]] ], [ undef, [[ENTRY]] ]
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX6:%.*]] poison, <8 x i32> [[RETVAL_SROA_0_0_I_I]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_0_INSERT_I_I]], <8 x i32> [[RETVAL_SROA_3_0_I_I]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_1_INSERT_I_I]], <2 x i32> [[RETVAL_SROA_6_0_I_I]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_2_INSERT_I_I]], <2 x i32> [[RETVAL_SROA_9_0_I_I]], 3
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_3_INSERT_I_I]], i32 [[RETVAL_SROA_12_0_I_I]], 4
// CHECK-NEXT:    [[DOTFCA_5_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_4_INSERT_I_I]], i32 [[RETVAL_SROA_15_0_I_I]], 5
// CHECK-NEXT:    [[DOTFCA_6_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_5_INSERT_I_I]], i32 [[RETVAL_SROA_18_0_I_I]], 6
// CHECK-NEXT:    [[DOTFCA_7_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_6_INSERT_I_I]], i32 [[RETVAL_SROA_21_0_I_I]], 7
// CHECK-NEXT:    ret [[STRUCT_V128MX6]] [[DOTFCA_7_INSERT_I_I]]
//
v128bfp13p test_set_v128bfp13p (int idx, v64bfp13p m) { return set_v128bfp13p(idx, m); }
// CHECK-LABEL: @_Z11test_concat6v64mx6S_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64MX6:%.*]] [[V0_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64MX6]] [[V0_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64MX6]] [[V0_COERCE]], 2
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64MX6]] [[V0_COERCE]], 3
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V64MX6]] [[V1_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V64MX6]] [[V1_COERCE]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V64MX6]] [[V1_COERCE]], 2
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V64MX6]] [[V1_COERCE]], 3
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX6:%.*]] poison, <8 x i32> [[TMP0]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_0_INSERT_I]], <8 x i32> [[TMP4]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_1_INSERT_I]], <2 x i32> [[TMP1]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_2_INSERT_I]], <2 x i32> [[TMP5]], 3
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_3_INSERT_I]], i32 [[TMP2]], 4
// CHECK-NEXT:    [[DOTFCA_5_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_4_INSERT_I]], i32 [[TMP6]], 5
// CHECK-NEXT:    [[DOTFCA_6_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_5_INSERT_I]], i32 [[TMP3]], 6
// CHECK-NEXT:    [[DOTFCA_7_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX6]] [[DOTFCA_6_INSERT_I]], i32 [[TMP7]], 7
// CHECK-NEXT:    ret [[STRUCT_V128MX6]] [[DOTFCA_7_INSERT_I]]
//
v128mx6             test_concat (v64mx6 v0, v64mx6 v1) { return concat(v0, v1); }
// CHECK-LABEL: @_Z19test_extract_v64mx47v128mx4i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    br i1 [[CMP_I]], label [[IF_THEN_I:%.*]], label [[IF_ELSE_I:%.*]]
// CHECK:       if.then.i:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V128MX4:%.*]] [[M_COERCE:%.*]], 6
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V128MX4]] [[M_COERCE]], 4
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128MX4]] [[M_COERCE]], 2
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128MX4]] [[M_COERCE]], 0
// CHECK-NEXT:    br label [[_ZL14EXTRACT_V64MX47V128MX4I_EXIT:%.*]]
// CHECK:       if.else.i:
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128MX4]] [[M_COERCE]], 7
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128MX4]] [[M_COERCE]], 5
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V128MX4]] [[M_COERCE]], 3
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V128MX4]] [[M_COERCE]], 1
// CHECK-NEXT:    [[CMP1_I:%.*]] = icmp eq i32 [[IDX]], 1
// CHECK-NEXT:    tail call void @llvm.assume(i1 [[CMP1_I]])
// CHECK-NEXT:    br label [[_ZL14EXTRACT_V64MX47V128MX4I_EXIT]]
// CHECK:       _ZL14extract_v64mx47v128mx4i.exit:
// CHECK-NEXT:    [[RETVAL_SROA_0_0_I:%.*]] = phi <8 x i32> [ [[TMP3]], [[IF_THEN_I]] ], [ [[TMP7]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_3_0_I:%.*]] = phi <2 x i32> [ [[TMP2]], [[IF_THEN_I]] ], [ [[TMP6]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_6_0_I:%.*]] = phi i32 [ [[TMP1]], [[IF_THEN_I]] ], [ [[TMP5]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_9_0_I:%.*]] = phi i32 [ [[TMP0]], [[IF_THEN_I]] ], [ [[TMP4]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX4:%.*]] poison, <8 x i32> [[RETVAL_SROA_0_0_I]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX4]] [[DOTFCA_0_INSERT_I]], <2 x i32> [[RETVAL_SROA_3_0_I]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX4]] [[DOTFCA_1_INSERT_I]], i32 [[RETVAL_SROA_6_0_I]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX4]] [[DOTFCA_2_INSERT_I]], i32 [[RETVAL_SROA_9_0_I]], 3
// CHECK-NEXT:    ret [[STRUCT_V64MX4]] [[DOTFCA_3_INSERT_I]]
//
v64mx4 test_extract_v64mx4 (v128mx4 m, int idx) { return extract_v64mx4(m, idx); }
// CHECK-LABEL: @_Z22test_extract_v64bfp11p7v128mx4i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    br i1 [[CMP_I_I]], label [[IF_THEN_I_I:%.*]], label [[IF_ELSE_I_I:%.*]]
// CHECK:       if.then.i.i:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V128MX4:%.*]] [[M_COERCE:%.*]], 6
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V128MX4]] [[M_COERCE]], 4
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128MX4]] [[M_COERCE]], 2
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128MX4]] [[M_COERCE]], 0
// CHECK-NEXT:    br label [[_ZL17EXTRACT_V64BFP11P7V128MX4I_EXIT:%.*]]
// CHECK:       if.else.i.i:
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128MX4]] [[M_COERCE]], 7
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128MX4]] [[M_COERCE]], 5
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V128MX4]] [[M_COERCE]], 3
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V128MX4]] [[M_COERCE]], 1
// CHECK-NEXT:    [[CMP1_I_I:%.*]] = icmp eq i32 [[IDX]], 1
// CHECK-NEXT:    tail call void @llvm.assume(i1 [[CMP1_I_I]])
// CHECK-NEXT:    br label [[_ZL17EXTRACT_V64BFP11P7V128MX4I_EXIT]]
// CHECK:       _ZL17extract_v64bfp11p7v128mx4i.exit:
// CHECK-NEXT:    [[RETVAL_SROA_0_0_I_I:%.*]] = phi <8 x i32> [ [[TMP3]], [[IF_THEN_I_I]] ], [ [[TMP7]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_3_0_I_I:%.*]] = phi <2 x i32> [ [[TMP2]], [[IF_THEN_I_I]] ], [ [[TMP6]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_6_0_I_I:%.*]] = phi i32 [ [[TMP1]], [[IF_THEN_I_I]] ], [ [[TMP5]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_9_0_I_I:%.*]] = phi i32 [ [[TMP0]], [[IF_THEN_I_I]] ], [ [[TMP4]], [[IF_ELSE_I_I]] ]
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64MX4:%.*]] poison, <8 x i32> [[RETVAL_SROA_0_0_I_I]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64MX4]] [[DOTFCA_0_INSERT_I_I]], <2 x i32> [[RETVAL_SROA_3_0_I_I]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64MX4]] [[DOTFCA_1_INSERT_I_I]], i32 [[RETVAL_SROA_6_0_I_I]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64MX4]] [[DOTFCA_2_INSERT_I_I]], i32 [[RETVAL_SROA_9_0_I_I]], 3
// CHECK-NEXT:    ret [[STRUCT_V64MX4]] [[DOTFCA_3_INSERT_I_I]]
//
v64bfp11p test_extract_v64bfp11p (v128bfp11p m, int idx) { return extract_v64bfp11p(m, idx); }
// CHECK-LABEL: @_Z11test_insert7v128mx4i6v64mx4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64MX4:%.*]] [[M_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64MX4]] [[M_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64MX4]] [[M_COERCE]], 2
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64MX4]] [[M_COERCE]], 3
// CHECK-NEXT:    [[CMP_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    br i1 [[CMP_I]], label [[IF_THEN_I:%.*]], label [[IF_ELSE_I:%.*]]
// CHECK:       if.then.i:
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128MX4:%.*]] [[S_COERCE:%.*]], 7
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128MX4]] [[S_COERCE]], 5
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V128MX4]] [[S_COERCE]], 3
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V128MX4]] [[S_COERCE]], 1
// CHECK-NEXT:    br label [[_ZL6INSERT7V128MX4I6V64MX4_EXIT:%.*]]
// CHECK:       if.else.i:
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V128MX4]] [[S_COERCE]], 6
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue [[STRUCT_V128MX4]] [[S_COERCE]], 4
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue [[STRUCT_V128MX4]] [[S_COERCE]], 2
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue [[STRUCT_V128MX4]] [[S_COERCE]], 0
// CHECK-NEXT:    [[CMP5_I:%.*]] = icmp eq i32 [[IDX]], 1
// CHECK-NEXT:    tail call void @llvm.assume(i1 [[CMP5_I]])
// CHECK-NEXT:    br label [[_ZL6INSERT7V128MX4I6V64MX4_EXIT]]
// CHECK:       _ZL6insert7v128mx4i6v64mx4.exit:
// CHECK-NEXT:    [[RETVAL_SROA_0_0_I:%.*]] = phi <8 x i32> [ [[TMP0]], [[IF_THEN_I]] ], [ [[TMP11]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_3_0_I:%.*]] = phi <8 x i32> [ [[TMP7]], [[IF_THEN_I]] ], [ [[TMP0]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_6_0_I:%.*]] = phi <2 x i32> [ [[TMP1]], [[IF_THEN_I]] ], [ [[TMP10]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_9_0_I:%.*]] = phi <2 x i32> [ [[TMP6]], [[IF_THEN_I]] ], [ [[TMP1]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_12_0_I:%.*]] = phi i32 [ [[TMP2]], [[IF_THEN_I]] ], [ [[TMP9]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_15_0_I:%.*]] = phi i32 [ [[TMP5]], [[IF_THEN_I]] ], [ [[TMP2]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_18_0_I:%.*]] = phi i32 [ [[TMP3]], [[IF_THEN_I]] ], [ [[TMP8]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[RETVAL_SROA_21_0_I:%.*]] = phi i32 [ [[TMP4]], [[IF_THEN_I]] ], [ [[TMP3]], [[IF_ELSE_I]] ]
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] poison, <8 x i32> [[RETVAL_SROA_0_0_I]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_0_INSERT_I]], <8 x i32> [[RETVAL_SROA_3_0_I]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_1_INSERT_I]], <2 x i32> [[RETVAL_SROA_6_0_I]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_2_INSERT_I]], <2 x i32> [[RETVAL_SROA_9_0_I]], 3
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_3_INSERT_I]], i32 [[RETVAL_SROA_12_0_I]], 4
// CHECK-NEXT:    [[DOTFCA_5_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_4_INSERT_I]], i32 [[RETVAL_SROA_15_0_I]], 5
// CHECK-NEXT:    [[DOTFCA_6_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_5_INSERT_I]], i32 [[RETVAL_SROA_18_0_I]], 6
// CHECK-NEXT:    [[DOTFCA_7_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_6_INSERT_I]], i32 [[RETVAL_SROA_21_0_I]], 7
// CHECK-NEXT:    ret [[STRUCT_V128MX4]] [[DOTFCA_7_INSERT_I]]
//
v128mx4 test_insert (v128mx4 s, int idx, v64mx4 m) { return insert(s, idx, m); }
// CHECK-LABEL: @_Z16test_set_v128mx4i6v64mx4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64MX4:%.*]] [[M_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64MX4]] [[M_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64MX4]] [[M_COERCE]], 2
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64MX4]] [[M_COERCE]], 3
// CHECK-NEXT:    [[CMP_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    br i1 [[CMP_I]], label [[_ZL11SET_V128MX4I6V64MX4_EXIT:%.*]], label [[IF_ELSE_I:%.*]]
// CHECK:       if.else.i:
// CHECK-NEXT:    [[CMP5_I:%.*]] = icmp eq i32 [[IDX]], 1
// CHECK-NEXT:    tail call void @llvm.assume(i1 [[CMP5_I]])
// CHECK-NEXT:    br label [[_ZL11SET_V128MX4I6V64MX4_EXIT]]
// CHECK:       _ZL11set_v128mx4i6v64mx4.exit:
// CHECK-NEXT:    [[RETVAL_SROA_6_0_I:%.*]] = phi <2 x i32> [ undef, [[IF_ELSE_I]] ], [ [[TMP1]], [[ENTRY:%.*]] ]
// CHECK-NEXT:    [[RETVAL_SROA_3_0_I:%.*]] = phi <8 x i32> [ [[TMP0]], [[IF_ELSE_I]] ], [ undef, [[ENTRY]] ]
// CHECK-NEXT:    [[RETVAL_SROA_0_0_I:%.*]] = phi <8 x i32> [ undef, [[IF_ELSE_I]] ], [ [[TMP0]], [[ENTRY]] ]
// CHECK-NEXT:    [[RETVAL_SROA_9_0_I:%.*]] = phi <2 x i32> [ [[TMP1]], [[IF_ELSE_I]] ], [ undef, [[ENTRY]] ]
// CHECK-NEXT:    [[RETVAL_SROA_12_0_I:%.*]] = phi i32 [ undef, [[IF_ELSE_I]] ], [ [[TMP2]], [[ENTRY]] ]
// CHECK-NEXT:    [[RETVAL_SROA_15_0_I:%.*]] = phi i32 [ [[TMP2]], [[IF_ELSE_I]] ], [ undef, [[ENTRY]] ]
// CHECK-NEXT:    [[RETVAL_SROA_18_0_I:%.*]] = phi i32 [ undef, [[IF_ELSE_I]] ], [ [[TMP3]], [[ENTRY]] ]
// CHECK-NEXT:    [[RETVAL_SROA_21_0_I:%.*]] = phi i32 [ [[TMP3]], [[IF_ELSE_I]] ], [ undef, [[ENTRY]] ]
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4:%.*]] poison, <8 x i32> [[RETVAL_SROA_0_0_I]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_0_INSERT_I]], <8 x i32> [[RETVAL_SROA_3_0_I]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_1_INSERT_I]], <2 x i32> [[RETVAL_SROA_6_0_I]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_2_INSERT_I]], <2 x i32> [[RETVAL_SROA_9_0_I]], 3
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_3_INSERT_I]], i32 [[RETVAL_SROA_12_0_I]], 4
// CHECK-NEXT:    [[DOTFCA_5_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_4_INSERT_I]], i32 [[RETVAL_SROA_15_0_I]], 5
// CHECK-NEXT:    [[DOTFCA_6_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_5_INSERT_I]], i32 [[RETVAL_SROA_18_0_I]], 6
// CHECK-NEXT:    [[DOTFCA_7_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_6_INSERT_I]], i32 [[RETVAL_SROA_21_0_I]], 7
// CHECK-NEXT:    ret [[STRUCT_V128MX4]] [[DOTFCA_7_INSERT_I]]
//
v128mx4 test_set_v128mx4 (int idx, v64mx4 m) { return set_v128mx4(idx, m); }
// CHECK-LABEL: @_Z19test_set_v128bfp11pi6v64mx4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64MX4:%.*]] [[M_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64MX4]] [[M_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64MX4]] [[M_COERCE]], 2
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64MX4]] [[M_COERCE]], 3
// CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp eq i32 [[IDX:%.*]], 0
// CHECK-NEXT:    br i1 [[CMP_I_I]], label [[_ZL14SET_V128BFP11PI6V64MX4_EXIT:%.*]], label [[IF_ELSE_I_I:%.*]]
// CHECK:       if.else.i.i:
// CHECK-NEXT:    [[CMP5_I_I:%.*]] = icmp eq i32 [[IDX]], 1
// CHECK-NEXT:    tail call void @llvm.assume(i1 [[CMP5_I_I]])
// CHECK-NEXT:    br label [[_ZL14SET_V128BFP11PI6V64MX4_EXIT]]
// CHECK:       _ZL14set_v128bfp11pi6v64mx4.exit:
// CHECK-NEXT:    [[RETVAL_SROA_6_0_I_I:%.*]] = phi <2 x i32> [ undef, [[IF_ELSE_I_I]] ], [ [[TMP1]], [[ENTRY:%.*]] ]
// CHECK-NEXT:    [[RETVAL_SROA_3_0_I_I:%.*]] = phi <8 x i32> [ [[TMP0]], [[IF_ELSE_I_I]] ], [ undef, [[ENTRY]] ]
// CHECK-NEXT:    [[RETVAL_SROA_0_0_I_I:%.*]] = phi <8 x i32> [ undef, [[IF_ELSE_I_I]] ], [ [[TMP0]], [[ENTRY]] ]
// CHECK-NEXT:    [[RETVAL_SROA_9_0_I_I:%.*]] = phi <2 x i32> [ [[TMP1]], [[IF_ELSE_I_I]] ], [ undef, [[ENTRY]] ]
// CHECK-NEXT:    [[RETVAL_SROA_12_0_I_I:%.*]] = phi i32 [ undef, [[IF_ELSE_I_I]] ], [ [[TMP2]], [[ENTRY]] ]
// CHECK-NEXT:    [[RETVAL_SROA_15_0_I_I:%.*]] = phi i32 [ [[TMP2]], [[IF_ELSE_I_I]] ], [ undef, [[ENTRY]] ]
// CHECK-NEXT:    [[RETVAL_SROA_18_0_I_I:%.*]] = phi i32 [ undef, [[IF_ELSE_I_I]] ], [ [[TMP3]], [[ENTRY]] ]
// CHECK-NEXT:    [[RETVAL_SROA_21_0_I_I:%.*]] = phi i32 [ [[TMP3]], [[IF_ELSE_I_I]] ], [ undef, [[ENTRY]] ]
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX4:%.*]] poison, <8 x i32> [[RETVAL_SROA_0_0_I_I]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_0_INSERT_I_I]], <8 x i32> [[RETVAL_SROA_3_0_I_I]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_1_INSERT_I_I]], <2 x i32> [[RETVAL_SROA_6_0_I_I]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_2_INSERT_I_I]], <2 x i32> [[RETVAL_SROA_9_0_I_I]], 3
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_3_INSERT_I_I]], i32 [[RETVAL_SROA_12_0_I_I]], 4
// CHECK-NEXT:    [[DOTFCA_5_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_4_INSERT_I_I]], i32 [[RETVAL_SROA_15_0_I_I]], 5
// CHECK-NEXT:    [[DOTFCA_6_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_5_INSERT_I_I]], i32 [[RETVAL_SROA_18_0_I_I]], 6
// CHECK-NEXT:    [[DOTFCA_7_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_6_INSERT_I_I]], i32 [[RETVAL_SROA_21_0_I_I]], 7
// CHECK-NEXT:    ret [[STRUCT_V128MX4]] [[DOTFCA_7_INSERT_I_I]]
//
v128bfp11p test_set_v128bfp11p (int idx, v64bfp11p m) { return set_v128bfp11p(idx, m); }
// CHECK-LABEL: @_Z11test_concat6v64mx4S_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64MX4:%.*]] [[V0_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64MX4]] [[V0_COERCE]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64MX4]] [[V0_COERCE]], 2
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64MX4]] [[V0_COERCE]], 3
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V64MX4]] [[V1_COERCE:%.*]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V64MX4]] [[V1_COERCE]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V64MX4]] [[V1_COERCE]], 2
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V64MX4]] [[V1_COERCE]], 3
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4:%.*]] poison, <8 x i32> [[TMP0]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_0_INSERT_I]], <8 x i32> [[TMP4]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_1_INSERT_I]], <2 x i32> [[TMP1]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_2_INSERT_I]], <2 x i32> [[TMP5]], 3
// CHECK-NEXT:    [[DOTFCA_4_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_3_INSERT_I]], i32 [[TMP2]], 4
// CHECK-NEXT:    [[DOTFCA_5_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_4_INSERT_I]], i32 [[TMP6]], 5
// CHECK-NEXT:    [[DOTFCA_6_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_5_INSERT_I]], i32 [[TMP3]], 6
// CHECK-NEXT:    [[DOTFCA_7_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_6_INSERT_I]], i32 [[TMP7]], 7
// CHECK-NEXT:    ret [[STRUCT_V128MX4]] [[DOTFCA_7_INSERT_I]]
//
v128mx4             test_concat (v64mx4 v0, v64mx4 v1) { return concat(v0, v1); }
