// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 4
//===- aie2ps-abi-bfp16.cpp -------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//



// RUN: %clang %s --target=aie2ps -nostdlibinc -S -emit-llvm -o - | FileCheck %s

extern "C" {


// CHECK-LABEL: define dso_local void @pass_v32mx9(
// CHECK-SAME: [[STRUCT_V64MX9:%.*]] [[DOTCOERCE:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = alloca [[STRUCT_V64MX9]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw [[STRUCT_V64MX9]], ptr [[TMP0]], i32 0, i32 0
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64MX9]] [[DOTCOERCE]], 0
// CHECK-NEXT:    store <16 x i32> [[TMP2]], ptr [[TMP1]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw [[STRUCT_V64MX9]], ptr [[TMP0]], i32 0, i32 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V64MX9]] [[DOTCOERCE]], 1
// CHECK-NEXT:    store <2 x i32> [[TMP4]], ptr [[TMP3]], align 8
// CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw [[STRUCT_V64MX9]], ptr [[TMP0]], i32 0, i32 2
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V64MX9]] [[DOTCOERCE]], 2
// CHECK-NEXT:    store <2 x i32> [[TMP6]], ptr [[TMP5]], align 8
// CHECK-NEXT:    ret void
//
    void pass_v32mx9(v64mx9){}

// CHECK-LABEL: define dso_local %struct.v64mx9 @ret_v32mx9(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca [[STRUCT_V64MX9:%.*]], align 8
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 8 [[RETVAL]], i8 0, i64 80, i1 false)
// CHECK-NEXT:    [[MANTISSA:%.*]] = getelementptr inbounds nuw [[STRUCT_V64MX9]], ptr [[RETVAL]], i32 0, i32 0
// CHECK-NEXT:    [[TILESHIFT:%.*]] = getelementptr inbounds nuw [[STRUCT_V64MX9]], ptr [[RETVAL]], i32 0, i32 1
// CHECK-NEXT:    [[EXPONENT:%.*]] = getelementptr inbounds nuw [[STRUCT_V64MX9]], ptr [[RETVAL]], i32 0, i32 2
// CHECK-NEXT:    [[TMP0:%.*]] = load [[STRUCT_V64MX9]], ptr [[RETVAL]], align 8
// CHECK-NEXT:    ret [[STRUCT_V64MX9]] [[TMP0]]
//
    v64mx9 ret_v32mx9() { return {}; }

// CHECK-LABEL: define dso_local void @pass_v64mx9(
// CHECK-SAME: [[STRUCT_V64MX9:%.*]] [[DOTCOERCE:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = alloca [[STRUCT_V64MX9]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw [[STRUCT_V64MX9]], ptr [[TMP0]], i32 0, i32 0
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64MX9]] [[DOTCOERCE]], 0
// CHECK-NEXT:    store <16 x i32> [[TMP2]], ptr [[TMP1]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw [[STRUCT_V64MX9]], ptr [[TMP0]], i32 0, i32 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V64MX9]] [[DOTCOERCE]], 1
// CHECK-NEXT:    store <2 x i32> [[TMP4]], ptr [[TMP3]], align 8
// CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw [[STRUCT_V64MX9]], ptr [[TMP0]], i32 0, i32 2
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V64MX9]] [[DOTCOERCE]], 2
// CHECK-NEXT:    store <2 x i32> [[TMP6]], ptr [[TMP5]], align 8
// CHECK-NEXT:    ret void
//
    void pass_v64mx9(v64mx9){}
// CHECK-LABEL: define dso_local %struct.v64mx9 @ret_v64mx9(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca [[STRUCT_V64MX9:%.*]], align 8
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 8 [[RETVAL]], i8 0, i64 80, i1 false)
// CHECK-NEXT:    [[MANTISSA:%.*]] = getelementptr inbounds nuw [[STRUCT_V64MX9]], ptr [[RETVAL]], i32 0, i32 0
// CHECK-NEXT:    [[TILESHIFT:%.*]] = getelementptr inbounds nuw [[STRUCT_V64MX9]], ptr [[RETVAL]], i32 0, i32 1
// CHECK-NEXT:    [[EXPONENT:%.*]] = getelementptr inbounds nuw [[STRUCT_V64MX9]], ptr [[RETVAL]], i32 0, i32 2
// CHECK-NEXT:    [[TMP0:%.*]] = load [[STRUCT_V64MX9]], ptr [[RETVAL]], align 8
// CHECK-NEXT:    ret [[STRUCT_V64MX9]] [[TMP0]]
//
    v64mx9 ret_v64mx9() { return {}; }
// CHECK-LABEL: define dso_local void @pass_v128mx9(
// CHECK-SAME: [[STRUCT_V128MX9:%.*]] [[DOTCOERCE:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = alloca [[STRUCT_V128MX9]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX9]], ptr [[TMP0]], i32 0, i32 0
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128MX9]] [[DOTCOERCE]], 0
// CHECK-NEXT:    store <16 x i32> [[TMP2]], ptr [[TMP1]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX9]], ptr [[TMP0]], i32 0, i32 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128MX9]] [[DOTCOERCE]], 1
// CHECK-NEXT:    store <16 x i32> [[TMP4]], ptr [[TMP3]], align 8
// CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX9]], ptr [[TMP0]], i32 0, i32 2
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V128MX9]] [[DOTCOERCE]], 2
// CHECK-NEXT:    store <2 x i32> [[TMP6]], ptr [[TMP5]], align 8
// CHECK-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX9]], ptr [[TMP0]], i32 0, i32 3
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V128MX9]] [[DOTCOERCE]], 3
// CHECK-NEXT:    store <2 x i32> [[TMP8]], ptr [[TMP7]], align 8
// CHECK-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX9]], ptr [[TMP0]], i32 0, i32 4
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue [[STRUCT_V128MX9]] [[DOTCOERCE]], 4
// CHECK-NEXT:    store <2 x i32> [[TMP10]], ptr [[TMP9]], align 8
// CHECK-NEXT:    [[TMP11:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX9]], ptr [[TMP0]], i32 0, i32 5
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue [[STRUCT_V128MX9]] [[DOTCOERCE]], 5
// CHECK-NEXT:    store <2 x i32> [[TMP12]], ptr [[TMP11]], align 8
// CHECK-NEXT:    ret void
//
    void pass_v128mx9(v128mx9) {}
// CHECK-LABEL: define dso_local %struct.v128mx9 @ret_v128mx9(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca [[STRUCT_V128MX9:%.*]], align 8
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 8 [[RETVAL]], i8 0, i64 160, i1 false)
// CHECK-NEXT:    [[MANTISSAX0:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX9]], ptr [[RETVAL]], i32 0, i32 0
// CHECK-NEXT:    [[MANTISSAX1:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX9]], ptr [[RETVAL]], i32 0, i32 1
// CHECK-NEXT:    [[TILESHIFTG0:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX9]], ptr [[RETVAL]], i32 0, i32 2
// CHECK-NEXT:    [[TILESHIFTG1:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX9]], ptr [[RETVAL]], i32 0, i32 3
// CHECK-NEXT:    [[EXPONENTE0:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX9]], ptr [[RETVAL]], i32 0, i32 4
// CHECK-NEXT:    [[EXPONENTE1:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX9]], ptr [[RETVAL]], i32 0, i32 5
// CHECK-NEXT:    [[TMP0:%.*]] = load [[STRUCT_V128MX9]], ptr [[RETVAL]], align 8
// CHECK-NEXT:    ret [[STRUCT_V128MX9]] [[TMP0]]
//
    v128mx9 ret_v128mx9(void) { return {}; }
// CHECK-LABEL: define dso_local void @pass_v256mx9(
// CHECK-SAME: [[STRUCT_V256MX9:%.*]] [[DOTCOERCE:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = alloca [[STRUCT_V256MX9]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX9]], ptr [[TMP0]], i32 0, i32 0
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX9]] [[DOTCOERCE]], 0
// CHECK-NEXT:    store [[STRUCT_V128MX9:%.*]] [[TMP2]], ptr [[TMP1]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX9]], ptr [[TMP0]], i32 0, i32 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V256MX9]] [[DOTCOERCE]], 1
// CHECK-NEXT:    store [[STRUCT_V128MX9]] [[TMP4]], ptr [[TMP3]], align 8
// CHECK-NEXT:    ret void
//
    void pass_v256mx9(v256mx9) {}
// CHECK-LABEL: define dso_local %struct.v256mx9 @ret_v256mx9(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca [[STRUCT_V256MX9:%.*]], align 8
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 8 [[RETVAL]], i8 0, i64 320, i1 false)
// CHECK-NEXT:    [[L:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX9]], ptr [[RETVAL]], i32 0, i32 0
// CHECK-NEXT:    [[MANTISSAX0:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX9:%.*]], ptr [[L]], i32 0, i32 0
// CHECK-NEXT:    [[MANTISSAX1:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX9]], ptr [[L]], i32 0, i32 1
// CHECK-NEXT:    [[TILESHIFTG0:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX9]], ptr [[L]], i32 0, i32 2
// CHECK-NEXT:    [[TILESHIFTG1:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX9]], ptr [[L]], i32 0, i32 3
// CHECK-NEXT:    [[EXPONENTE0:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX9]], ptr [[L]], i32 0, i32 4
// CHECK-NEXT:    [[EXPONENTE1:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX9]], ptr [[L]], i32 0, i32 5
// CHECK-NEXT:    [[H:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX9]], ptr [[RETVAL]], i32 0, i32 1
// CHECK-NEXT:    [[MANTISSAX01:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX9]], ptr [[H]], i32 0, i32 0
// CHECK-NEXT:    [[MANTISSAX12:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX9]], ptr [[H]], i32 0, i32 1
// CHECK-NEXT:    [[TILESHIFTG03:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX9]], ptr [[H]], i32 0, i32 2
// CHECK-NEXT:    [[TILESHIFTG14:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX9]], ptr [[H]], i32 0, i32 3
// CHECK-NEXT:    [[EXPONENTE05:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX9]], ptr [[H]], i32 0, i32 4
// CHECK-NEXT:    [[EXPONENTE16:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX9]], ptr [[H]], i32 0, i32 5
// CHECK-NEXT:    [[TMP0:%.*]] = load [[STRUCT_V256MX9]], ptr [[RETVAL]], align 8
// CHECK-NEXT:    ret [[STRUCT_V256MX9]] [[TMP0]]
//
    v256mx9 ret_v256mx9(void) { return {}; }

// CHECK-LABEL: define dso_local void @pass_v64mx6(
// CHECK-SAME: [[STRUCT_V64MX6:%.*]] [[DOTCOERCE:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = alloca [[STRUCT_V64MX6]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw [[STRUCT_V64MX6]], ptr [[TMP0]], i32 0, i32 0
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64MX6]] [[DOTCOERCE]], 0
// CHECK-NEXT:    store <8 x i32> [[TMP2]], ptr [[TMP1]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw [[STRUCT_V64MX6]], ptr [[TMP0]], i32 0, i32 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V64MX6]] [[DOTCOERCE]], 1
// CHECK-NEXT:    store <2 x i32> [[TMP4]], ptr [[TMP3]], align 8
// CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw [[STRUCT_V64MX6]], ptr [[TMP0]], i32 0, i32 2
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V64MX6]] [[DOTCOERCE]], 2
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[TMP5]], align 8
// CHECK-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw [[STRUCT_V64MX6]], ptr [[TMP0]], i32 0, i32 3
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V64MX6]] [[DOTCOERCE]], 3
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[TMP7]], align 4
// CHECK-NEXT:    ret void
//
    void pass_v64mx6(v64mx6){}
// CHECK-LABEL: define dso_local %struct.v64mx6 @ret_v64mx6(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca [[STRUCT_V64MX6:%.*]], align 8
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 8 [[RETVAL]], i8 0, i64 48, i1 false)
// CHECK-NEXT:    [[MANTISSA:%.*]] = getelementptr inbounds nuw [[STRUCT_V64MX6]], ptr [[RETVAL]], i32 0, i32 0
// CHECK-NEXT:    [[SIGN:%.*]] = getelementptr inbounds nuw [[STRUCT_V64MX6]], ptr [[RETVAL]], i32 0, i32 1
// CHECK-NEXT:    [[TILESHIFT:%.*]] = getelementptr inbounds nuw [[STRUCT_V64MX6]], ptr [[RETVAL]], i32 0, i32 2
// CHECK-NEXT:    [[EXPONENT:%.*]] = getelementptr inbounds nuw [[STRUCT_V64MX6]], ptr [[RETVAL]], i32 0, i32 3
// CHECK-NEXT:    [[TMP0:%.*]] = load [[STRUCT_V64MX6]], ptr [[RETVAL]], align 8
// CHECK-NEXT:    ret [[STRUCT_V64MX6]] [[TMP0]]
//
    v64mx6 ret_v64mx6() { return {}; }
// CHECK-LABEL: define dso_local void @pass_v128mx6(
// CHECK-SAME: [[STRUCT_V128MX6:%.*]] [[DOTCOERCE:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = alloca [[STRUCT_V128MX6]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX6]], ptr [[TMP0]], i32 0, i32 0
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128MX6]] [[DOTCOERCE]], 0
// CHECK-NEXT:    store <8 x i32> [[TMP2]], ptr [[TMP1]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX6]], ptr [[TMP0]], i32 0, i32 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128MX6]] [[DOTCOERCE]], 1
// CHECK-NEXT:    store <8 x i32> [[TMP4]], ptr [[TMP3]], align 8
// CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX6]], ptr [[TMP0]], i32 0, i32 2
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V128MX6]] [[DOTCOERCE]], 2
// CHECK-NEXT:    store <2 x i32> [[TMP6]], ptr [[TMP5]], align 8
// CHECK-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX6]], ptr [[TMP0]], i32 0, i32 3
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V128MX6]] [[DOTCOERCE]], 3
// CHECK-NEXT:    store <2 x i32> [[TMP8]], ptr [[TMP7]], align 8
// CHECK-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX6]], ptr [[TMP0]], i32 0, i32 4
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue [[STRUCT_V128MX6]] [[DOTCOERCE]], 4
// CHECK-NEXT:    store i32 [[TMP10]], ptr [[TMP9]], align 8
// CHECK-NEXT:    [[TMP11:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX6]], ptr [[TMP0]], i32 0, i32 5
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue [[STRUCT_V128MX6]] [[DOTCOERCE]], 5
// CHECK-NEXT:    store i32 [[TMP12]], ptr [[TMP11]], align 4
// CHECK-NEXT:    [[TMP13:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX6]], ptr [[TMP0]], i32 0, i32 6
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue [[STRUCT_V128MX6]] [[DOTCOERCE]], 6
// CHECK-NEXT:    store i32 [[TMP14]], ptr [[TMP13]], align 8
// CHECK-NEXT:    [[TMP15:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX6]], ptr [[TMP0]], i32 0, i32 7
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue [[STRUCT_V128MX6]] [[DOTCOERCE]], 7
// CHECK-NEXT:    store i32 [[TMP16]], ptr [[TMP15]], align 4
// CHECK-NEXT:    ret void
//
    void pass_v128mx6(v128mx6) {}
// CHECK-LABEL: define dso_local %struct.v128mx6 @ret_v128mx6(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca [[STRUCT_V128MX6:%.*]], align 8
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 8 [[RETVAL]], i8 0, i64 96, i1 false)
// CHECK-NEXT:    [[MANTISSAX0:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX6]], ptr [[RETVAL]], i32 0, i32 0
// CHECK-NEXT:    [[MANTISSAX1:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX6]], ptr [[RETVAL]], i32 0, i32 1
// CHECK-NEXT:    [[SIGNF0:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX6]], ptr [[RETVAL]], i32 0, i32 2
// CHECK-NEXT:    [[SIGNF1:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX6]], ptr [[RETVAL]], i32 0, i32 3
// CHECK-NEXT:    [[TILESHIFTG0:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX6]], ptr [[RETVAL]], i32 0, i32 4
// CHECK-NEXT:    [[TILESHIFTG1:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX6]], ptr [[RETVAL]], i32 0, i32 5
// CHECK-NEXT:    [[EXPONENTE0:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX6]], ptr [[RETVAL]], i32 0, i32 6
// CHECK-NEXT:    [[EXPONENTE1:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX6]], ptr [[RETVAL]], i32 0, i32 7
// CHECK-NEXT:    [[TMP0:%.*]] = load [[STRUCT_V128MX6]], ptr [[RETVAL]], align 8
// CHECK-NEXT:    ret [[STRUCT_V128MX6]] [[TMP0]]
//
    v128mx6 ret_v128mx6(void) { return {}; }
// CHECK-LABEL: define dso_local void @pass_v256mx6(
// CHECK-SAME: [[STRUCT_V256MX6:%.*]] [[DOTCOERCE:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = alloca [[STRUCT_V256MX6]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX6]], ptr [[TMP0]], i32 0, i32 0
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX6]] [[DOTCOERCE]], 0
// CHECK-NEXT:    store <8 x i32> [[TMP2]], ptr [[TMP1]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX6]], ptr [[TMP0]], i32 0, i32 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V256MX6]] [[DOTCOERCE]], 1
// CHECK-NEXT:    store <8 x i32> [[TMP4]], ptr [[TMP3]], align 8
// CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX6]], ptr [[TMP0]], i32 0, i32 2
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V256MX6]] [[DOTCOERCE]], 2
// CHECK-NEXT:    store <8 x i32> [[TMP6]], ptr [[TMP5]], align 8
// CHECK-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX6]], ptr [[TMP0]], i32 0, i32 3
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V256MX6]] [[DOTCOERCE]], 3
// CHECK-NEXT:    store <8 x i32> [[TMP8]], ptr [[TMP7]], align 8
// CHECK-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX6]], ptr [[TMP0]], i32 0, i32 4
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue [[STRUCT_V256MX6]] [[DOTCOERCE]], 4
// CHECK-NEXT:    store <2 x i32> [[TMP10]], ptr [[TMP9]], align 8
// CHECK-NEXT:    [[TMP11:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX6]], ptr [[TMP0]], i32 0, i32 5
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue [[STRUCT_V256MX6]] [[DOTCOERCE]], 5
// CHECK-NEXT:    store <2 x i32> [[TMP12]], ptr [[TMP11]], align 8
// CHECK-NEXT:    [[TMP13:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX6]], ptr [[TMP0]], i32 0, i32 6
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue [[STRUCT_V256MX6]] [[DOTCOERCE]], 6
// CHECK-NEXT:    store <2 x i32> [[TMP14]], ptr [[TMP13]], align 8
// CHECK-NEXT:    [[TMP15:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX6]], ptr [[TMP0]], i32 0, i32 7
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue [[STRUCT_V256MX6]] [[DOTCOERCE]], 7
// CHECK-NEXT:    store <2 x i32> [[TMP16]], ptr [[TMP15]], align 8
// CHECK-NEXT:    [[TMP17:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX6]], ptr [[TMP0]], i32 0, i32 8
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue [[STRUCT_V256MX6]] [[DOTCOERCE]], 8
// CHECK-NEXT:    store i32 [[TMP18]], ptr [[TMP17]], align 8
// CHECK-NEXT:    [[TMP19:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX6]], ptr [[TMP0]], i32 0, i32 9
// CHECK-NEXT:    [[TMP20:%.*]] = extractvalue [[STRUCT_V256MX6]] [[DOTCOERCE]], 9
// CHECK-NEXT:    store i32 [[TMP20]], ptr [[TMP19]], align 4
// CHECK-NEXT:    [[TMP21:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX6]], ptr [[TMP0]], i32 0, i32 10
// CHECK-NEXT:    [[TMP22:%.*]] = extractvalue [[STRUCT_V256MX6]] [[DOTCOERCE]], 10
// CHECK-NEXT:    store i32 [[TMP22]], ptr [[TMP21]], align 8
// CHECK-NEXT:    [[TMP23:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX6]], ptr [[TMP0]], i32 0, i32 11
// CHECK-NEXT:    [[TMP24:%.*]] = extractvalue [[STRUCT_V256MX6]] [[DOTCOERCE]], 11
// CHECK-NEXT:    store i32 [[TMP24]], ptr [[TMP23]], align 4
// CHECK-NEXT:    [[TMP25:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX6]], ptr [[TMP0]], i32 0, i32 12
// CHECK-NEXT:    [[TMP26:%.*]] = extractvalue [[STRUCT_V256MX6]] [[DOTCOERCE]], 12
// CHECK-NEXT:    store i32 [[TMP26]], ptr [[TMP25]], align 8
// CHECK-NEXT:    [[TMP27:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX6]], ptr [[TMP0]], i32 0, i32 13
// CHECK-NEXT:    [[TMP28:%.*]] = extractvalue [[STRUCT_V256MX6]] [[DOTCOERCE]], 13
// CHECK-NEXT:    store i32 [[TMP28]], ptr [[TMP27]], align 4
// CHECK-NEXT:    [[TMP29:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX6]], ptr [[TMP0]], i32 0, i32 14
// CHECK-NEXT:    [[TMP30:%.*]] = extractvalue [[STRUCT_V256MX6]] [[DOTCOERCE]], 14
// CHECK-NEXT:    store i32 [[TMP30]], ptr [[TMP29]], align 8
// CHECK-NEXT:    [[TMP31:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX6]], ptr [[TMP0]], i32 0, i32 15
// CHECK-NEXT:    [[TMP32:%.*]] = extractvalue [[STRUCT_V256MX6]] [[DOTCOERCE]], 15
// CHECK-NEXT:    store i32 [[TMP32]], ptr [[TMP31]], align 4
// CHECK-NEXT:    ret void
//
    void pass_v256mx6(v256mx6) {}
// CHECK-LABEL: define dso_local %struct.v256mx6 @ret_v256mx6(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca [[STRUCT_V256MX6:%.*]], align 8
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 8 [[RETVAL]], i8 0, i64 192, i1 false)
// CHECK-NEXT:    [[MANTISSAX0:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX6]], ptr [[RETVAL]], i32 0, i32 0
// CHECK-NEXT:    [[MANTISSAX1:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX6]], ptr [[RETVAL]], i32 0, i32 1
// CHECK-NEXT:    [[MANTISSAX2:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX6]], ptr [[RETVAL]], i32 0, i32 2
// CHECK-NEXT:    [[MANTISSAX3:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX6]], ptr [[RETVAL]], i32 0, i32 3
// CHECK-NEXT:    [[SIGNF0:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX6]], ptr [[RETVAL]], i32 0, i32 4
// CHECK-NEXT:    [[SIGNF1:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX6]], ptr [[RETVAL]], i32 0, i32 5
// CHECK-NEXT:    [[SIGNF2:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX6]], ptr [[RETVAL]], i32 0, i32 6
// CHECK-NEXT:    [[SIGNF3:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX6]], ptr [[RETVAL]], i32 0, i32 7
// CHECK-NEXT:    [[TILESHIFTG0:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX6]], ptr [[RETVAL]], i32 0, i32 8
// CHECK-NEXT:    [[TILESHIFTG1:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX6]], ptr [[RETVAL]], i32 0, i32 9
// CHECK-NEXT:    [[TILESHIFTG2:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX6]], ptr [[RETVAL]], i32 0, i32 10
// CHECK-NEXT:    [[TILESHIFTG3:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX6]], ptr [[RETVAL]], i32 0, i32 11
// CHECK-NEXT:    [[EXPONENTE0:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX6]], ptr [[RETVAL]], i32 0, i32 12
// CHECK-NEXT:    [[EXPONENTE1:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX6]], ptr [[RETVAL]], i32 0, i32 13
// CHECK-NEXT:    [[EXPONENTE2:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX6]], ptr [[RETVAL]], i32 0, i32 14
// CHECK-NEXT:    [[EXPONENTE3:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX6]], ptr [[RETVAL]], i32 0, i32 15
// CHECK-NEXT:    [[TMP0:%.*]] = load [[STRUCT_V256MX6]], ptr [[RETVAL]], align 8
// CHECK-NEXT:    ret [[STRUCT_V256MX6]] [[TMP0]]
//
    v256mx6 ret_v256mx6(void) { return {}; }

// CHECK-LABEL: define dso_local void @pass_v64mx4(
// CHECK-SAME: [[STRUCT_V64MX4:%.*]] [[DOTCOERCE:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = alloca [[STRUCT_V64MX4]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw [[STRUCT_V64MX4]], ptr [[TMP0]], i32 0, i32 0
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64MX4]] [[DOTCOERCE]], 0
// CHECK-NEXT:    store <8 x i32> [[TMP2]], ptr [[TMP1]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw [[STRUCT_V64MX4]], ptr [[TMP0]], i32 0, i32 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V64MX4]] [[DOTCOERCE]], 1
// CHECK-NEXT:    store <2 x i32> [[TMP4]], ptr [[TMP3]], align 8
// CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw [[STRUCT_V64MX4]], ptr [[TMP0]], i32 0, i32 2
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V64MX4]] [[DOTCOERCE]], 2
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[TMP5]], align 8
// CHECK-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw [[STRUCT_V64MX4]], ptr [[TMP0]], i32 0, i32 3
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V64MX4]] [[DOTCOERCE]], 3
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[TMP7]], align 4
// CHECK-NEXT:    ret void
//
    void pass_v64mx4(v64mx4){}
// CHECK-LABEL: define dso_local %struct.v64mx4 @ret_v64mx4(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca [[STRUCT_V64MX4:%.*]], align 8
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 8 [[RETVAL]], i8 0, i64 48, i1 false)
// CHECK-NEXT:    [[MANTISSA:%.*]] = getelementptr inbounds nuw [[STRUCT_V64MX4]], ptr [[RETVAL]], i32 0, i32 0
// CHECK-NEXT:    [[SIGN:%.*]] = getelementptr inbounds nuw [[STRUCT_V64MX4]], ptr [[RETVAL]], i32 0, i32 1
// CHECK-NEXT:    [[TILESHIFT:%.*]] = getelementptr inbounds nuw [[STRUCT_V64MX4]], ptr [[RETVAL]], i32 0, i32 2
// CHECK-NEXT:    [[EXPONENT:%.*]] = getelementptr inbounds nuw [[STRUCT_V64MX4]], ptr [[RETVAL]], i32 0, i32 3
// CHECK-NEXT:    [[TMP0:%.*]] = load [[STRUCT_V64MX4]], ptr [[RETVAL]], align 8
// CHECK-NEXT:    ret [[STRUCT_V64MX4]] [[TMP0]]
//
    v64mx4 ret_v64mx4() { return {}; }
// CHECK-LABEL: define dso_local void @pass_v128mx4(
// CHECK-SAME: [[STRUCT_V128MX4:%.*]] [[DOTCOERCE:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = alloca [[STRUCT_V128MX4]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX4]], ptr [[TMP0]], i32 0, i32 0
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128MX4]] [[DOTCOERCE]], 0
// CHECK-NEXT:    store <8 x i32> [[TMP2]], ptr [[TMP1]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX4]], ptr [[TMP0]], i32 0, i32 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128MX4]] [[DOTCOERCE]], 1
// CHECK-NEXT:    store <8 x i32> [[TMP4]], ptr [[TMP3]], align 8
// CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX4]], ptr [[TMP0]], i32 0, i32 2
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V128MX4]] [[DOTCOERCE]], 2
// CHECK-NEXT:    store <2 x i32> [[TMP6]], ptr [[TMP5]], align 8
// CHECK-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX4]], ptr [[TMP0]], i32 0, i32 3
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V128MX4]] [[DOTCOERCE]], 3
// CHECK-NEXT:    store <2 x i32> [[TMP8]], ptr [[TMP7]], align 8
// CHECK-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX4]], ptr [[TMP0]], i32 0, i32 4
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue [[STRUCT_V128MX4]] [[DOTCOERCE]], 4
// CHECK-NEXT:    store i32 [[TMP10]], ptr [[TMP9]], align 8
// CHECK-NEXT:    [[TMP11:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX4]], ptr [[TMP0]], i32 0, i32 5
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue [[STRUCT_V128MX4]] [[DOTCOERCE]], 5
// CHECK-NEXT:    store i32 [[TMP12]], ptr [[TMP11]], align 4
// CHECK-NEXT:    [[TMP13:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX4]], ptr [[TMP0]], i32 0, i32 6
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue [[STRUCT_V128MX4]] [[DOTCOERCE]], 6
// CHECK-NEXT:    store i32 [[TMP14]], ptr [[TMP13]], align 8
// CHECK-NEXT:    [[TMP15:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX4]], ptr [[TMP0]], i32 0, i32 7
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue [[STRUCT_V128MX4]] [[DOTCOERCE]], 7
// CHECK-NEXT:    store i32 [[TMP16]], ptr [[TMP15]], align 4
// CHECK-NEXT:    ret void
//
    void pass_v128mx4(v128mx4) {}
// CHECK-LABEL: define dso_local %struct.v128mx4 @ret_v128mx4(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca [[STRUCT_V128MX4:%.*]], align 8
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 8 [[RETVAL]], i8 0, i64 96, i1 false)
// CHECK-NEXT:    [[MANTISSAX0:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX4]], ptr [[RETVAL]], i32 0, i32 0
// CHECK-NEXT:    [[MANTISSAX1:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX4]], ptr [[RETVAL]], i32 0, i32 1
// CHECK-NEXT:    [[SIGNF0:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX4]], ptr [[RETVAL]], i32 0, i32 2
// CHECK-NEXT:    [[SIGNF1:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX4]], ptr [[RETVAL]], i32 0, i32 3
// CHECK-NEXT:    [[TILESHIFTG0:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX4]], ptr [[RETVAL]], i32 0, i32 4
// CHECK-NEXT:    [[TILESHIFTG1:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX4]], ptr [[RETVAL]], i32 0, i32 5
// CHECK-NEXT:    [[EXPONENTE0:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX4]], ptr [[RETVAL]], i32 0, i32 6
// CHECK-NEXT:    [[EXPONENTE1:%.*]] = getelementptr inbounds nuw [[STRUCT_V128MX4]], ptr [[RETVAL]], i32 0, i32 7
// CHECK-NEXT:    [[TMP0:%.*]] = load [[STRUCT_V128MX4]], ptr [[RETVAL]], align 8
// CHECK-NEXT:    ret [[STRUCT_V128MX4]] [[TMP0]]
//
    v128mx4 ret_v128mx4(void) { return {}; }
// CHECK-LABEL: define dso_local void @pass_v256mx4(
// CHECK-SAME: [[STRUCT_V256MX4:%.*]] [[DOTCOERCE:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = alloca [[STRUCT_V256MX4]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX4]], ptr [[TMP0]], i32 0, i32 0
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V256MX4]] [[DOTCOERCE]], 0
// CHECK-NEXT:    store <8 x i32> [[TMP2]], ptr [[TMP1]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX4]], ptr [[TMP0]], i32 0, i32 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V256MX4]] [[DOTCOERCE]], 1
// CHECK-NEXT:    store <8 x i32> [[TMP4]], ptr [[TMP3]], align 8
// CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX4]], ptr [[TMP0]], i32 0, i32 2
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V256MX4]] [[DOTCOERCE]], 2
// CHECK-NEXT:    store <8 x i32> [[TMP6]], ptr [[TMP5]], align 8
// CHECK-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX4]], ptr [[TMP0]], i32 0, i32 3
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[STRUCT_V256MX4]] [[DOTCOERCE]], 3
// CHECK-NEXT:    store <8 x i32> [[TMP8]], ptr [[TMP7]], align 8
// CHECK-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX4]], ptr [[TMP0]], i32 0, i32 4
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue [[STRUCT_V256MX4]] [[DOTCOERCE]], 4
// CHECK-NEXT:    store <2 x i32> [[TMP10]], ptr [[TMP9]], align 8
// CHECK-NEXT:    [[TMP11:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX4]], ptr [[TMP0]], i32 0, i32 5
// CHECK-NEXT:    [[TMP12:%.*]] = extractvalue [[STRUCT_V256MX4]] [[DOTCOERCE]], 5
// CHECK-NEXT:    store <2 x i32> [[TMP12]], ptr [[TMP11]], align 8
// CHECK-NEXT:    [[TMP13:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX4]], ptr [[TMP0]], i32 0, i32 6
// CHECK-NEXT:    [[TMP14:%.*]] = extractvalue [[STRUCT_V256MX4]] [[DOTCOERCE]], 6
// CHECK-NEXT:    store <2 x i32> [[TMP14]], ptr [[TMP13]], align 8
// CHECK-NEXT:    [[TMP15:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX4]], ptr [[TMP0]], i32 0, i32 7
// CHECK-NEXT:    [[TMP16:%.*]] = extractvalue [[STRUCT_V256MX4]] [[DOTCOERCE]], 7
// CHECK-NEXT:    store <2 x i32> [[TMP16]], ptr [[TMP15]], align 8
// CHECK-NEXT:    [[TMP17:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX4]], ptr [[TMP0]], i32 0, i32 8
// CHECK-NEXT:    [[TMP18:%.*]] = extractvalue [[STRUCT_V256MX4]] [[DOTCOERCE]], 8
// CHECK-NEXT:    store i32 [[TMP18]], ptr [[TMP17]], align 8
// CHECK-NEXT:    [[TMP19:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX4]], ptr [[TMP0]], i32 0, i32 9
// CHECK-NEXT:    [[TMP20:%.*]] = extractvalue [[STRUCT_V256MX4]] [[DOTCOERCE]], 9
// CHECK-NEXT:    store i32 [[TMP20]], ptr [[TMP19]], align 4
// CHECK-NEXT:    [[TMP21:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX4]], ptr [[TMP0]], i32 0, i32 10
// CHECK-NEXT:    [[TMP22:%.*]] = extractvalue [[STRUCT_V256MX4]] [[DOTCOERCE]], 10
// CHECK-NEXT:    store i32 [[TMP22]], ptr [[TMP21]], align 8
// CHECK-NEXT:    [[TMP23:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX4]], ptr [[TMP0]], i32 0, i32 11
// CHECK-NEXT:    [[TMP24:%.*]] = extractvalue [[STRUCT_V256MX4]] [[DOTCOERCE]], 11
// CHECK-NEXT:    store i32 [[TMP24]], ptr [[TMP23]], align 4
// CHECK-NEXT:    [[TMP25:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX4]], ptr [[TMP0]], i32 0, i32 12
// CHECK-NEXT:    [[TMP26:%.*]] = extractvalue [[STRUCT_V256MX4]] [[DOTCOERCE]], 12
// CHECK-NEXT:    store i32 [[TMP26]], ptr [[TMP25]], align 8
// CHECK-NEXT:    [[TMP27:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX4]], ptr [[TMP0]], i32 0, i32 13
// CHECK-NEXT:    [[TMP28:%.*]] = extractvalue [[STRUCT_V256MX4]] [[DOTCOERCE]], 13
// CHECK-NEXT:    store i32 [[TMP28]], ptr [[TMP27]], align 4
// CHECK-NEXT:    [[TMP29:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX4]], ptr [[TMP0]], i32 0, i32 14
// CHECK-NEXT:    [[TMP30:%.*]] = extractvalue [[STRUCT_V256MX4]] [[DOTCOERCE]], 14
// CHECK-NEXT:    store i32 [[TMP30]], ptr [[TMP29]], align 8
// CHECK-NEXT:    [[TMP31:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX4]], ptr [[TMP0]], i32 0, i32 15
// CHECK-NEXT:    [[TMP32:%.*]] = extractvalue [[STRUCT_V256MX4]] [[DOTCOERCE]], 15
// CHECK-NEXT:    store i32 [[TMP32]], ptr [[TMP31]], align 4
// CHECK-NEXT:    ret void
//
    void pass_v256mx4(v256mx4) {}
// CHECK-LABEL: define dso_local %struct.v256mx4 @ret_v256mx4(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca [[STRUCT_V256MX4:%.*]], align 8
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 8 [[RETVAL]], i8 0, i64 192, i1 false)
// CHECK-NEXT:    [[MANTISSAX0:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX4]], ptr [[RETVAL]], i32 0, i32 0
// CHECK-NEXT:    [[MANTISSAX1:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX4]], ptr [[RETVAL]], i32 0, i32 1
// CHECK-NEXT:    [[MANTISSAX2:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX4]], ptr [[RETVAL]], i32 0, i32 2
// CHECK-NEXT:    [[MANTISSAX3:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX4]], ptr [[RETVAL]], i32 0, i32 3
// CHECK-NEXT:    [[SIGNF0:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX4]], ptr [[RETVAL]], i32 0, i32 4
// CHECK-NEXT:    [[SIGNF1:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX4]], ptr [[RETVAL]], i32 0, i32 5
// CHECK-NEXT:    [[SIGNF2:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX4]], ptr [[RETVAL]], i32 0, i32 6
// CHECK-NEXT:    [[SIGNF3:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX4]], ptr [[RETVAL]], i32 0, i32 7
// CHECK-NEXT:    [[TILESHIFTG0:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX4]], ptr [[RETVAL]], i32 0, i32 8
// CHECK-NEXT:    [[TILESHIFTG1:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX4]], ptr [[RETVAL]], i32 0, i32 9
// CHECK-NEXT:    [[TILESHIFTG2:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX4]], ptr [[RETVAL]], i32 0, i32 10
// CHECK-NEXT:    [[TILESHIFTG3:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX4]], ptr [[RETVAL]], i32 0, i32 11
// CHECK-NEXT:    [[EXPONENTE0:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX4]], ptr [[RETVAL]], i32 0, i32 12
// CHECK-NEXT:    [[EXPONENTE1:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX4]], ptr [[RETVAL]], i32 0, i32 13
// CHECK-NEXT:    [[EXPONENTE2:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX4]], ptr [[RETVAL]], i32 0, i32 14
// CHECK-NEXT:    [[EXPONENTE3:%.*]] = getelementptr inbounds nuw [[STRUCT_V256MX4]], ptr [[RETVAL]], i32 0, i32 15
// CHECK-NEXT:    [[TMP0:%.*]] = load [[STRUCT_V256MX4]], ptr [[RETVAL]], align 8
// CHECK-NEXT:    ret [[STRUCT_V256MX4]] [[TMP0]]
//
    v256mx4 ret_v256mx4(void) { return {}; }
}
