// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
//===- aie2ps-set-mode.cpp ----------------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//
// RUN: %clang -O2 %s --target=aie2ps -nostdlibinc -S -emit-llvm -o - | FileCheck %s -check-prefix=CHECK-AIE2PS

// CHECK-AIE2PS-LABEL: @_Z21test_set_bfloat8_confj(
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 21, i32 [[VAL:%.*]])
// CHECK-AIE2PS-NEXT:    ret void
//
void test_set_bfloat8_conf (unsigned int val) {
  return set_bfloat8_conf(val);
}

// CHECK-AIE2PS-LABEL: @_Z20test_set_float8_confj(
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 22, i32 [[VAL:%.*]])
// CHECK-AIE2PS-NEXT:    ret void
//
void test_set_float8_conf (unsigned int val) {
  return set_float8_conf(val);
}

// CHECK-AIE2PS-LABEL: @_Z25test_set_fp_conv_sat_confj(
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 23, i32 [[VAL:%.*]])
// CHECK-AIE2PS-NEXT:    ret void
//
void test_set_fp_conv_sat_conf (unsigned int val) {
  return set_fp_conv_sat_conf(val);
}

// CHECK-AIE2PS-LABEL: @_Z17test_set_nlf_maskj(
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 24, i32 [[VAL:%.*]])
// CHECK-AIE2PS-NEXT:    ret void
//
void test_set_nlf_mask(unsigned int val) { return set_nlf_mask(val); }

// CHECK-AIE2PS-LABEL: @_Z19test_set_fx2fl_maskj(
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 25, i32 [[VAL:%.*]])
// CHECK-AIE2PS-NEXT:    ret void
//
void test_set_fx2fl_mask(unsigned int val) { return set_fx2fl_mask(val); }

// CHECK-AIE2PS-LABEL: @_Z19test_set_fl2fx_maskj(
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 26, i32 [[VAL:%.*]])
// CHECK-AIE2PS-NEXT:    ret void
//
void test_set_fl2fx_mask(unsigned int val) { return set_fl2fx_mask(val); }

// CHECK-AIE2PS-LABEL: @_Z12test_set_nlfj(
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.status.reg(i32 40, i32 [[VAL:%.*]])
// CHECK-AIE2PS-NEXT:    ret void
//
void test_set_nlf(unsigned int val) { return set_nlf(val); }

// CHECK-AIE2PS-LABEL: @_Z14test_set_fx2flj(
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.status.reg(i32 41, i32 [[VAL:%.*]])
// CHECK-AIE2PS-NEXT:    ret void
//
void test_set_fx2fl(unsigned int val) { return set_fx2fl(val); }

// CHECK-AIE2PS-LABEL: @_Z14test_set_fl2fxj(
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.status.reg(i32 42, i32 [[VAL:%.*]])
// CHECK-AIE2PS-NEXT:    ret void
//
void test_set_fl2fx(unsigned int val) { return set_fl2fx(val); }

// CHECK-AIE2PS-LABEL: @_Z21test_get_bfloat8_confv(
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 21)
// CHECK-AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_get_bfloat8_conf() { return get_bfloat8_conf(); }

// CHECK-AIE2PS-LABEL: @_Z20test_get_float8_confv(
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 22)
// CHECK-AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_get_float8_conf() { return get_float8_conf(); }

// CHECK-AIE2PS-LABEL: @_Z25test_get_fp_conv_sat_confv(
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 23)
// CHECK-AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_get_fp_conv_sat_conf() { return get_fp_conv_sat_conf(); }

// CHECK-AIE2PS-LABEL: @_Z17test_get_nlf_maskv(
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 24)
// CHECK-AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_get_nlf_mask() { return get_nlf_mask(); }

// CHECK-AIE2PS-LABEL: @_Z19test_get_fx2fl_maskv(
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 25)
// CHECK-AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_get_fx2fl_mask() { return get_fx2fl_mask(); }

// CHECK-AIE2PS-LABEL: @_Z19test_get_fl2fx_maskv(
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 26)
// CHECK-AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_get_fl2fx_mask() { return get_fl2fx_mask(); }

// CHECK-AIE2PS-LABEL: @_Z12test_get_nlfv(
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.status.reg(i32 40)
// CHECK-AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_get_nlf() { return get_nlf(); }

// CHECK-AIE2PS-LABEL: @_Z14test_get_fx2flv(
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.status.reg(i32 41)
// CHECK-AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_get_fx2fl() { return get_fx2fl(); }

// CHECK-AIE2PS-LABEL: @_Z14test_get_fl2fxv(
// CHECK-AIE2PS-NEXT:  entry:
// CHECK-AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.status.reg(i32 42)
// CHECK-AIE2PS-NEXT:    ret i32 [[TMP0]]
//
unsigned int test_get_fl2fx() { return get_fl2fx(); }
