// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 4
//===-------------------- AIEngine AIE2ps tests --------------------------===
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//

// RUN: %clang -O2 %s --target=aie2ps -nostdlibinc -S -emit-llvm -o - | FileCheck %s -check-prefix=AIE2PS

// AIE2PS-LABEL: define dso_local noundef <32 x i8> @_Z14test_pack_confDv32_sDU2_(
// AIE2PS-SAME: <32 x i16> noundef [[V:%.*]], i2 noundef [[SAT:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[CONV2_I:%.*]] = zext i2 [[SAT]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV2_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef <32 x i8> @llvm.aie2ps.pack.I512.I8.I16(<32 x i16> [[V]], i32 1)
// AIE2PS-NEXT:    [[CONV5_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV5_I]])
// AIE2PS-NEXT:    ret <32 x i8> [[TMP1]]
//
v32int8 test_pack_conf(v32int16 v, crsat_t sat) { return pack_conf(v, sat); }

// AIE2PS-LABEL: define dso_local noundef <32 x i8> @_Z14test_pack_confDv64_aiDU2_(
// AIE2PS-SAME: <64 x i8> noundef [[V:%.*]], i32 noundef [[SIGN:%.*]], i2 noundef [[SAT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[CONV2_I:%.*]] = zext i2 [[SAT]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV2_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef <32 x i8> @llvm.aie2ps.pack.I512.I4.I8(<64 x i8> [[V]], i32 1)
// AIE2PS-NEXT:    [[CONV5_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV5_I]])
// AIE2PS-NEXT:    ret <32 x i8> [[TMP1]]
//
v64int4 test_pack_conf(v64int8 v, int sign, crsat_t sat) {
  return pack_conf(v, sat);
}

// AIE2PS-LABEL: define dso_local noundef <64 x i8> @_Z14test_pack_confDv64_sDU2_(
// AIE2PS-SAME: <64 x i16> noundef [[V:%.*]], i2 noundef [[SAT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[CONV2_I:%.*]] = zext i2 [[SAT]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV2_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef <64 x i8> @llvm.aie2ps.pack.I1024.I8.I16(<64 x i16> [[V]], i32 1)
// AIE2PS-NEXT:    [[CONV5_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV5_I]])
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v64int8 test_pack_conf(v64int16 v, crsat_t sat) { return pack_conf(v, sat); }

// AIE2PS-LABEL: define dso_local noundef <64 x i8> @_Z14test_pack_confDv128_hiDU2_(
// AIE2PS-SAME: <128 x i8> noundef [[V:%.*]], i32 noundef [[SIGN:%.*]], i2 noundef [[SAT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// AIE2PS-NEXT:    [[CONV2_I:%.*]] = zext i2 [[SAT]] to i32
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV2_I]])
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call noundef <64 x i8> @llvm.aie2ps.pack.I1024.I4.I8(<128 x i8> [[V]], i32 0)
// AIE2PS-NEXT:    [[CONV5_I:%.*]] = and i32 [[TMP0]], 3
// AIE2PS-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV5_I]])
// AIE2PS-NEXT:    ret <64 x i8> [[TMP1]]
//
v128uint4 test_pack_conf(v128uint8 v, int sign, crsat_t sat) {
  return pack_conf(v, sat);
}

// AIE2PS-LABEL: define dso_local void @_Z18test_fifo_ld_resetRrPU3AS59v64float8R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) initializes((128, 132)) [[S:%.*]]) local_unnamed_addr #[[ATTR1:[0-9]+]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2:![0-9]+]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(5), ptr [[P]], align 4, !tbaa [[TBAA7:![0-9]+]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10:![0-9]+]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p5.p5(ptr addrspace(5) [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP2]], 1
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP2]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(5) [[TMP3]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_reset(v64float8 __aie_dm_resource_a *restrict &p,
                        fifo_state_t &s) {
  fifo_ld_reset(p, s);
}
// AIE2PS-LABEL: define dso_local void @_Z17test_fifo_ld_fillRrPU3AS59v64float8R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(5), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11:![0-9]+]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p5.p5(ptr addrspace(5) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(5) [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_fill(v64float8 __aie_dm_resource_a *restrict &p,
                       fifo_state_t &s) {
  fifo_ld_fill(p, s);
}
// AIE2PS-LABEL: define dso_local void @_Z16test_fifo_ld_popRrPU3AS59v64float8R12fifo_state_t(
// AIE2PS-SAME: ptr dead_on_unwind noalias writable writeonly sret([[STRUCT_V64FLOAT8:%.*]]) align 64 captures(none) initializes((0, 64)) [[AGG_RESULT:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR2:[0-9]+]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    tail call void @llvm.experimental.noalias.scope.decl(metadata [[META12:![0-9]+]])
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(5), ptr [[P]], align 4, !tbaa [[TBAA7]], !noalias [[META12]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]], !noalias [[META12]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]], !noalias [[META12]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.512.unaligned.p5.p5(ptr addrspace(5) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]]), !noalias [[META12]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 3
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128, !noalias [[META12]]
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64, !noalias [[META12]]
// AIE2PS-NEXT:    store ptr addrspace(5) [[TMP5]], ptr [[P]], align 4, !noalias [[META12]]
// AIE2PS-NEXT:    store <64 x i8> [[TMP4]], ptr [[AGG_RESULT]], align 64, !tbaa [[TBAA10]], !alias.scope [[META12]]
// AIE2PS-NEXT:    ret void
//
v64float8 test_fifo_ld_pop(v64float8 __aie_dm_resource_a *restrict &p,
                           fifo_state_t &s) {
  return fifo_ld_pop(p, s);
}
// AIE2PS-LABEL: define dso_local void @_Z24test_fifo_ld_pop_1d_byteRrPU3AS59v64float8R12fifo_state_ti(
// AIE2PS-SAME: ptr dead_on_unwind noalias writable writeonly sret([[STRUCT_V64FLOAT8:%.*]]) align 64 captures(none) initializes((0, 64)) [[AGG_RESULT:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]]) local_unnamed_addr #[[ATTR2]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    tail call void @llvm.experimental.noalias.scope.decl(metadata [[META15:![0-9]+]])
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(5), ptr [[P]], align 4, !tbaa [[TBAA7]], !noalias [[META15]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]], !noalias [[META15]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]], !noalias [[META15]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.1d.unaligned.p5.p5(ptr addrspace(5) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]]), !noalias [[META15]]
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } [[TMP4]], 3
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128, !noalias [[META15]]
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64, !noalias [[META15]]
// AIE2PS-NEXT:    store ptr addrspace(5) [[TMP6]], ptr [[P]], align 4, !noalias [[META15]]
// AIE2PS-NEXT:    store <64 x i8> [[TMP5]], ptr [[AGG_RESULT]], align 64, !tbaa [[TBAA10]], !alias.scope [[META15]]
// AIE2PS-NEXT:    ret void
//
v64float8 test_fifo_ld_pop_1d_byte(v64float8 __aie_dm_resource_a *restrict &p,
                                   fifo_state_t &s, int off) {
  return fifo_ld_pop_1d_byte(p, s, off);
}
// AIE2PS-LABEL: define dso_local void @_Z24test_fifo_ld_pop_2d_byteRrPU3AS59v64float8R12fifo_state_tiiRii(
// AIE2PS-SAME: ptr dead_on_unwind noalias writable writeonly sret([[STRUCT_V64FLOAT8:%.*]]) align 64 captures(none) initializes((0, 64)) [[AGG_RESULT:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]]) local_unnamed_addr #[[ATTR2]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    tail call void @llvm.experimental.noalias.scope.decl(metadata [[META18:![0-9]+]])
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(5), ptr [[P]], align 4, !tbaa [[TBAA7]], !noalias [[META18]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]], !noalias [[META18]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]], !noalias [[META18]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]], !noalias [[META18]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.ld.pop.2d.unaligned.p5.p5(ptr addrspace(5) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]]), !noalias [[META18]]
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20 } [[TMP8]], 4
// AIE2PS-NEXT:    [[TMP14:%.*]] = zext i20 [[TMP13]] to i32
// AIE2PS-NEXT:    store i32 [[TMP14]], ptr [[COUNT1]], align 4, !noalias [[META18]]
// AIE2PS-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128, !noalias [[META18]]
// AIE2PS-NEXT:    store i32 [[TMP12]], ptr [[POS1_I]], align 64, !noalias [[META18]]
// AIE2PS-NEXT:    store ptr addrspace(5) [[TMP10]], ptr [[P]], align 4, !noalias [[META18]]
// AIE2PS-NEXT:    store <64 x i8> [[TMP9]], ptr [[AGG_RESULT]], align 64, !tbaa [[TBAA10]], !alias.scope [[META18]]
// AIE2PS-NEXT:    ret void
//
v64float8 test_fifo_ld_pop_2d_byte(v64float8 __aie_dm_resource_a *restrict &p,
                                   fifo_state_t &s, int off, int size1,
                                   addr_t &count1, int inc1) {
  return fifo_ld_pop_2d_byte(p, s, off, size1, count1, inc1);
}
// AIE2PS-LABEL: define dso_local void @_Z24test_fifo_ld_pop_3d_byteRrPU3AS59v64float8R12fifo_state_tiiRiiiS6_i(
// AIE2PS-SAME: ptr dead_on_unwind noalias writable writeonly sret([[STRUCT_V64FLOAT8:%.*]]) align 64 captures(none) initializes((0, 64)) [[AGG_RESULT:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]], i32 noundef [[SIZE2:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT2:%.*]], i32 noundef [[INC2:%.*]]) local_unnamed_addr #[[ATTR2]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    tail call void @llvm.experimental.noalias.scope.decl(metadata [[META21:![0-9]+]])
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(5), ptr [[P]], align 4, !tbaa [[TBAA7]], !noalias [[META21]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]], !noalias [[META21]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]], !noalias [[META21]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]], !noalias [[META21]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2]], align 4, !tbaa [[TBAA11]], !noalias [[META21]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.ld.pop.3d.unaligned.p5.p5(ptr addrspace(5) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]]), !noalias [[META21]]
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } [[TMP12]], 5
// AIE2PS-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// AIE2PS-NEXT:    store i32 [[TMP18]], ptr [[COUNT1]], align 4, !noalias [[META21]]
// AIE2PS-NEXT:    store i32 [[TMP20]], ptr [[COUNT2]], align 4, !noalias [[META21]]
// AIE2PS-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128, !noalias [[META21]]
// AIE2PS-NEXT:    store i32 [[TMP16]], ptr [[POS1_I]], align 64, !noalias [[META21]]
// AIE2PS-NEXT:    store ptr addrspace(5) [[TMP14]], ptr [[P]], align 4, !noalias [[META21]]
// AIE2PS-NEXT:    store <64 x i8> [[TMP13]], ptr [[AGG_RESULT]], align 64, !tbaa [[TBAA10]], !alias.scope [[META21]]
// AIE2PS-NEXT:    ret void
//
v64float8 test_fifo_ld_pop_3d_byte(v64float8 __aie_dm_resource_a *restrict &p,
                                   fifo_state_t &s, int off, int size1,
                                   addr_t &count1, int inc1, int size2,
                                   addr_t &count2, int inc2) {
  return fifo_ld_pop_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}
// AIE2PS-LABEL: define dso_local void @_Z17test_fifo_ld_popxRrP9v64float8R12fifo_state_tii(
// AIE2PS-SAME: ptr dead_on_unwind noalias writable writeonly sret([[STRUCT_V64FLOAT8:%.*]]) align 64 captures(none) initializes((0, 64)) [[AGG_RESULT:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[MASK:%.*]]) local_unnamed_addr #[[ATTR2]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    tail call void @llvm.experimental.noalias.scope.decl(metadata [[META24:![0-9]+]])
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP]], 6
// AIE2PS-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK]]
// AIE2PS-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]], !noalias [[META24]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]], !noalias [[META24]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]], !noalias [[META24]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]], !noalias [[META24]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]]), !noalias [[META24]]
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2PS-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I]], align 64, !noalias [[META24]]
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128, !noalias [[META24]]
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64, !noalias [[META24]]
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4, !noalias [[META24]]
// AIE2PS-NEXT:    store <64 x i8> [[TMP5]], ptr [[AGG_RESULT]], align 64, !tbaa [[TBAA10]], !alias.scope [[META24]]
// AIE2PS-NEXT:    ret void
//
v64float8 test_fifo_ld_popx(v64float8 *restrict &p, fifo_state_t &s, int step,
                            int mask) {
  return fifo_ld_popx(p, s, step, mask);
}
// AIE2PS-LABEL: define dso_local void @_Z17test_fifo_ld_popxRrP9v64float8R12fifo_state_t(
// AIE2PS-SAME: ptr dead_on_unwind noalias writable writeonly sret([[STRUCT_V64FLOAT8:%.*]]) align 64 captures(none) initializes((0, 64)) [[AGG_RESULT:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR2]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    tail call void @llvm.experimental.noalias.scope.decl(metadata [[META27:![0-9]+]])
// AIE2PS-NEXT:    tail call void @llvm.experimental.noalias.scope.decl(metadata [[META30:![0-9]+]])
// AIE2PS-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]], !noalias [[META33:![0-9]+]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]], !noalias [[META33]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]], !noalias [[META33]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]], !noalias [[META33]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015), !noalias [[META33]]
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2PS-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I_I]], align 64, !noalias [[META33]]
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128, !noalias [[META33]]
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64, !noalias [[META33]]
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4, !noalias [[META33]]
// AIE2PS-NEXT:    store <64 x i8> [[TMP5]], ptr [[AGG_RESULT]], align 64, !tbaa [[TBAA10]], !alias.scope [[META33]]
// AIE2PS-NEXT:    ret void
//
v64float8 test_fifo_ld_popx(v64float8 *restrict &p, fifo_state_t &s) {
  return fifo_ld_popx(p, s);
}
// AIE2PS-LABEL: define dso_local void @_Z18test_fifo_ld_resetRPU3AS510v64bfloat8R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) initializes((128, 132)) [[S:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(5), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p5.p5(ptr addrspace(5) [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP2]], 1
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP2]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(5) [[TMP3]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_reset(v64bfloat8 __aie_dm_resource_a *&p, fifo_state_t &s) {
  fifo_ld_reset(p, s);
}
// AIE2PS-LABEL: define dso_local void @_Z17test_fifo_ld_fillRPU3AS510v64bfloat8R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(5), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p5.p5(ptr addrspace(5) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(5) [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_fill(v64bfloat8 __aie_dm_resource_a *&p, fifo_state_t &s) {
  fifo_ld_fill(p, s);
}
// AIE2PS-LABEL: define dso_local void @_Z16test_fifo_ld_popRPU3AS510v64bfloat8R12fifo_state_t(
// AIE2PS-SAME: ptr dead_on_unwind noalias writable writeonly sret([[STRUCT_V64BFLOAT8:%.*]]) align 64 captures(none) initializes((0, 64)) [[AGG_RESULT:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR2]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    tail call void @llvm.experimental.noalias.scope.decl(metadata [[META34:![0-9]+]])
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(5), ptr [[P]], align 4, !tbaa [[TBAA7]], !noalias [[META34]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]], !noalias [[META34]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]], !noalias [[META34]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.512.unaligned.p5.p5(ptr addrspace(5) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]]), !noalias [[META34]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 3
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128, !noalias [[META34]]
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64, !noalias [[META34]]
// AIE2PS-NEXT:    store ptr addrspace(5) [[TMP5]], ptr [[P]], align 4, !noalias [[META34]]
// AIE2PS-NEXT:    store <64 x i8> [[TMP4]], ptr [[AGG_RESULT]], align 64, !tbaa [[TBAA10]], !alias.scope [[META34]]
// AIE2PS-NEXT:    ret void
//
v64bfloat8 test_fifo_ld_pop(v64bfloat8 __aie_dm_resource_a *&p,
                            fifo_state_t &s) {
  return fifo_ld_pop(p, s);
}
// AIE2PS-LABEL: define dso_local void @_Z24test_fifo_ld_pop_1d_byteRPU3AS510v64bfloat8R12fifo_state_ti(
// AIE2PS-SAME: ptr dead_on_unwind noalias writable writeonly sret([[STRUCT_V64BFLOAT8:%.*]]) align 64 captures(none) initializes((0, 64)) [[AGG_RESULT:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]]) local_unnamed_addr #[[ATTR2]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    tail call void @llvm.experimental.noalias.scope.decl(metadata [[META37:![0-9]+]])
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(5), ptr [[P]], align 4, !tbaa [[TBAA7]], !noalias [[META37]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]], !noalias [[META37]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]], !noalias [[META37]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.1d.unaligned.p5.p5(ptr addrspace(5) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]]), !noalias [[META37]]
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } [[TMP4]], 3
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128, !noalias [[META37]]
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64, !noalias [[META37]]
// AIE2PS-NEXT:    store ptr addrspace(5) [[TMP6]], ptr [[P]], align 4, !noalias [[META37]]
// AIE2PS-NEXT:    store <64 x i8> [[TMP5]], ptr [[AGG_RESULT]], align 64, !tbaa [[TBAA10]], !alias.scope [[META37]]
// AIE2PS-NEXT:    ret void
//
v64bfloat8 test_fifo_ld_pop_1d_byte(v64bfloat8 __aie_dm_resource_a *&p,
                                    fifo_state_t &s, int off) {
  return fifo_ld_pop_1d_byte(p, s, off);
}
// AIE2PS-LABEL: define dso_local void @_Z24test_fifo_ld_pop_2d_byteRPU3AS510v64bfloat8R12fifo_state_tiiRii(
// AIE2PS-SAME: ptr dead_on_unwind noalias writable writeonly sret([[STRUCT_V64BFLOAT8:%.*]]) align 64 captures(none) initializes((0, 64)) [[AGG_RESULT:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]]) local_unnamed_addr #[[ATTR2]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    tail call void @llvm.experimental.noalias.scope.decl(metadata [[META40:![0-9]+]])
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(5), ptr [[P]], align 4, !tbaa [[TBAA7]], !noalias [[META40]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]], !noalias [[META40]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]], !noalias [[META40]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]], !noalias [[META40]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.ld.pop.2d.unaligned.p5.p5(ptr addrspace(5) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]]), !noalias [[META40]]
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20 } [[TMP8]], 4
// AIE2PS-NEXT:    [[TMP14:%.*]] = zext i20 [[TMP13]] to i32
// AIE2PS-NEXT:    store i32 [[TMP14]], ptr [[COUNT1]], align 4, !noalias [[META40]]
// AIE2PS-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128, !noalias [[META40]]
// AIE2PS-NEXT:    store i32 [[TMP12]], ptr [[POS1_I]], align 64, !noalias [[META40]]
// AIE2PS-NEXT:    store ptr addrspace(5) [[TMP10]], ptr [[P]], align 4, !noalias [[META40]]
// AIE2PS-NEXT:    store <64 x i8> [[TMP9]], ptr [[AGG_RESULT]], align 64, !tbaa [[TBAA10]], !alias.scope [[META40]]
// AIE2PS-NEXT:    ret void
//
v64bfloat8 test_fifo_ld_pop_2d_byte(v64bfloat8 __aie_dm_resource_a *&p,
                                    fifo_state_t &s, int off, int size1,
                                    addr_t &count1, int inc1) {
  return fifo_ld_pop_2d_byte(p, s, off, size1, count1, inc1);
}
// AIE2PS-LABEL: define dso_local void @_Z24test_fifo_ld_pop_3d_byteRPU3AS510v64bfloat8R12fifo_state_tiiRiiiS5_i(
// AIE2PS-SAME: ptr dead_on_unwind noalias writable writeonly sret([[STRUCT_V64BFLOAT8:%.*]]) align 64 captures(none) initializes((0, 64)) [[AGG_RESULT:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]], i32 noundef [[SIZE2:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT2:%.*]], i32 noundef [[INC2:%.*]]) local_unnamed_addr #[[ATTR2]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    tail call void @llvm.experimental.noalias.scope.decl(metadata [[META43:![0-9]+]])
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(5), ptr [[P]], align 4, !tbaa [[TBAA7]], !noalias [[META43]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]], !noalias [[META43]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]], !noalias [[META43]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]], !noalias [[META43]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2]], align 4, !tbaa [[TBAA11]], !noalias [[META43]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.ld.pop.3d.unaligned.p5.p5(ptr addrspace(5) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]]), !noalias [[META43]]
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } [[TMP12]], 5
// AIE2PS-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// AIE2PS-NEXT:    store i32 [[TMP18]], ptr [[COUNT1]], align 4, !noalias [[META43]]
// AIE2PS-NEXT:    store i32 [[TMP20]], ptr [[COUNT2]], align 4, !noalias [[META43]]
// AIE2PS-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128, !noalias [[META43]]
// AIE2PS-NEXT:    store i32 [[TMP16]], ptr [[POS1_I]], align 64, !noalias [[META43]]
// AIE2PS-NEXT:    store ptr addrspace(5) [[TMP14]], ptr [[P]], align 4, !noalias [[META43]]
// AIE2PS-NEXT:    store <64 x i8> [[TMP13]], ptr [[AGG_RESULT]], align 64, !tbaa [[TBAA10]], !alias.scope [[META43]]
// AIE2PS-NEXT:    ret void
//
v64bfloat8 test_fifo_ld_pop_3d_byte(v64bfloat8 __aie_dm_resource_a *&p,
                                    fifo_state_t &s, int off, int size1,
                                    addr_t &count1, int inc1, int size2,
                                    addr_t &count2, int inc2) {
  return fifo_ld_pop_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}
// AIE2PS-LABEL: define dso_local void @_Z17test_fifo_ld_popxRP10v64bfloat8R12fifo_state_tii(
// AIE2PS-SAME: ptr dead_on_unwind noalias writable writeonly sret([[STRUCT_V64BFLOAT8:%.*]]) align 64 captures(none) initializes((0, 64)) [[AGG_RESULT:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[MASK:%.*]]) local_unnamed_addr #[[ATTR2]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    tail call void @llvm.experimental.noalias.scope.decl(metadata [[META46:![0-9]+]])
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP]], 6
// AIE2PS-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK]]
// AIE2PS-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]], !noalias [[META46]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]], !noalias [[META46]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]], !noalias [[META46]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]], !noalias [[META46]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]]), !noalias [[META46]]
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2PS-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I]], align 64, !noalias [[META46]]
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128, !noalias [[META46]]
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64, !noalias [[META46]]
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4, !noalias [[META46]]
// AIE2PS-NEXT:    store <64 x i8> [[TMP5]], ptr [[AGG_RESULT]], align 64, !tbaa [[TBAA10]], !alias.scope [[META46]]
// AIE2PS-NEXT:    ret void
//
v64bfloat8 test_fifo_ld_popx(v64bfloat8 *&p, fifo_state_t &s, int step,
                             int mask) {
  return fifo_ld_popx(p, s, step, mask);
}
// AIE2PS-LABEL: define dso_local void @_Z17test_fifo_ld_popxRP10v64bfloat8R12fifo_state_t(
// AIE2PS-SAME: ptr dead_on_unwind noalias writable writeonly sret([[STRUCT_V64BFLOAT8:%.*]]) align 64 captures(none) initializes((0, 64)) [[AGG_RESULT:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR2]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    tail call void @llvm.experimental.noalias.scope.decl(metadata [[META49:![0-9]+]])
// AIE2PS-NEXT:    tail call void @llvm.experimental.noalias.scope.decl(metadata [[META52:![0-9]+]])
// AIE2PS-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]], !noalias [[META55:![0-9]+]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]], !noalias [[META55]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]], !noalias [[META55]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]], !noalias [[META55]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015), !noalias [[META55]]
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2PS-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I_I]], align 64, !noalias [[META55]]
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128, !noalias [[META55]]
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64, !noalias [[META55]]
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4, !noalias [[META55]]
// AIE2PS-NEXT:    store <64 x i8> [[TMP5]], ptr [[AGG_RESULT]], align 64, !tbaa [[TBAA10]], !alias.scope [[META55]]
// AIE2PS-NEXT:    ret void
//
v64bfloat8 test_fifo_ld_popx(v64bfloat8 *&p, fifo_state_t &s) {
  return fifo_ld_popx(p, s);
}
// AIE2PS-LABEL: define dso_local void @_Z18test_fifo_ld_resetRPU3AS5Dv32_7float16R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) initializes((128, 132)) [[S:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(5), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p5.p5(ptr addrspace(5) [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP2]], 1
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP2]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(5) [[TMP3]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_reset(v32float16 __aie_dm_resource_a *&p, fifo_state_t &s) {
  fifo_ld_reset(p, s);
}
// AIE2PS-LABEL: define dso_local void @_Z17test_fifo_ld_fillRPU3AS5Dv32_7float16R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(5), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p5.p5(ptr addrspace(5) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(5) [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_fill(v32float16 __aie_dm_resource_a *&p, fifo_state_t &s) {
  fifo_ld_fill(p, s);
}
// AIE2PS-LABEL: define dso_local noundef <32 x half> @_Z16test_fifo_ld_popRPU3AS5Dv32_7float16R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(5), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.512.unaligned.p5.p5(ptr addrspace(5) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 3
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(5) [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP8:%.*]] = bitcast <64 x i8> [[TMP4]] to <32 x half>
// AIE2PS-NEXT:    ret <32 x half> [[TMP8]]
//
v32float16 test_fifo_ld_pop(v32float16 __aie_dm_resource_a *&p,
                            fifo_state_t &s) {
  return fifo_ld_pop(p, s);
}
// AIE2PS-LABEL: define dso_local noundef <32 x half> @_Z24test_fifo_ld_pop_1d_byteRPU3AS5Dv32_7float16R12fifo_state_ti(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(5), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.1d.unaligned.p5.p5(ptr addrspace(5) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } [[TMP4]], 3
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(5) [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP9:%.*]] = bitcast <64 x i8> [[TMP5]] to <32 x half>
// AIE2PS-NEXT:    ret <32 x half> [[TMP9]]
//
v32float16 test_fifo_ld_pop_1d_byte(v32float16 __aie_dm_resource_a *&p,
                                    fifo_state_t &s, int off) {
  return fifo_ld_pop_1d_byte(p, s, off);
}
// AIE2PS-LABEL: define dso_local noundef <32 x half> @_Z24test_fifo_ld_pop_2d_byteRPU3AS5Dv32_7float16R12fifo_state_tiiRii(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(5), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.ld.pop.2d.unaligned.p5.p5(ptr addrspace(5) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20 } [[TMP8]], 4
// AIE2PS-NEXT:    [[TMP14:%.*]] = zext i20 [[TMP13]] to i32
// AIE2PS-NEXT:    store i32 [[TMP14]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP12]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(5) [[TMP10]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP15:%.*]] = bitcast <64 x i8> [[TMP9]] to <32 x half>
// AIE2PS-NEXT:    ret <32 x half> [[TMP15]]
//
v32float16 test_fifo_ld_pop_2d_byte(v32float16 __aie_dm_resource_a *&p,
                                    fifo_state_t &s, int off, int size1,
                                    addr_t &count1, int inc1) {
  return fifo_ld_pop_2d_byte(p, s, off, size1, count1, inc1);
}
// AIE2PS-LABEL: define dso_local noundef <32 x half> @_Z24test_fifo_ld_pop_3d_byteRPU3AS5Dv32_7float16R12fifo_state_tiiRiiiS6_i(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]], i32 noundef [[SIZE2:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT2:%.*]], i32 noundef [[INC2:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(5), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.ld.pop.3d.unaligned.p5.p5(ptr addrspace(5) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } [[TMP12]], 5
// AIE2PS-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// AIE2PS-NEXT:    store i32 [[TMP18]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP20]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP16]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(5) [[TMP14]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP21:%.*]] = bitcast <64 x i8> [[TMP13]] to <32 x half>
// AIE2PS-NEXT:    ret <32 x half> [[TMP21]]
//
v32float16 test_fifo_ld_pop_3d_byte(v32float16 __aie_dm_resource_a *&p,
                                    fifo_state_t &s, int off, int size1,
                                    addr_t &count1, int inc1, int size2,
                                    addr_t &count2, int inc2) {
  return fifo_ld_pop_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}
// AIE2PS-LABEL: define dso_local noundef <32 x half> @_Z17test_fifo_ld_popxRPDv32_7float16R12fifo_state_tii(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[MASK:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP]], 6
// AIE2PS-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK]]
// AIE2PS-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2PS-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I]], align 64
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <32 x half>
// AIE2PS-NEXT:    ret <32 x half> [[TMP10]]
//
v32float16 test_fifo_ld_popx(v32float16 *&p, fifo_state_t &s, int step,
                             int mask) {
  return fifo_ld_popx(p, s, step, mask);
}
// AIE2PS-LABEL: define dso_local noundef <32 x half> @_Z17test_fifo_ld_popxRPDv32_7float16R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2PS-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I_I]], align 64
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <32 x half>
// AIE2PS-NEXT:    ret <32 x half> [[TMP10]]
//
v32float16 test_fifo_ld_popx(v32float16 *&p, fifo_state_t &s) {
  return fifo_ld_popx(p, s);
}
// AIE2PS-LABEL: define dso_local void @_Z18test_fifo_ld_resetRrPU3AS5Dv32_8bfloat16R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) initializes((128, 132)) [[S:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(5), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p5.p5(ptr addrspace(5) [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP2]], 1
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP2]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(5) [[TMP3]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_reset(v32bfloat16 __aie_dm_resource_a *restrict &p,
                        fifo_state_t &s) {
  fifo_ld_reset(p, s);
}
// AIE2PS-LABEL: define dso_local void @_Z17test_fifo_ld_fillRrPU3AS5Dv32_8bfloat16R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(5), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p5.p5(ptr addrspace(5) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(5) [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_fill(v32bfloat16 __aie_dm_resource_a *restrict &p,
                       fifo_state_t &s) {
  fifo_ld_fill(p, s);
}
// AIE2PS-LABEL: define dso_local noundef <32 x bfloat> @_Z16test_fifo_ld_popRrPU3AS5Dv32_8bfloat16R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(5), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.512.unaligned.p5.p5(ptr addrspace(5) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } [[TMP3]], 3
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(5) [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP8:%.*]] = bitcast <64 x i8> [[TMP4]] to <32 x bfloat>
// AIE2PS-NEXT:    ret <32 x bfloat> [[TMP8]]
//
v32bfloat16 test_fifo_ld_pop(v32bfloat16 __aie_dm_resource_a *restrict &p,
                             fifo_state_t &s) {
  return fifo_ld_pop(p, s);
}
v32bfloat16
// AIE2PS-LABEL: define dso_local noundef <32 x bfloat> @_Z24test_fifo_ld_pop_1d_byteRrPU3AS5Dv32_8bfloat16R12fifo_state_ti(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(5), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.pop.1d.unaligned.p5.p5(ptr addrspace(5) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32 } [[TMP4]], 3
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(5) [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP9:%.*]] = bitcast <64 x i8> [[TMP5]] to <32 x bfloat>
// AIE2PS-NEXT:    ret <32 x bfloat> [[TMP9]]
//
test_fifo_ld_pop_1d_byte(v32bfloat16 __aie_dm_resource_a *restrict &p,
                         fifo_state_t &s, int off) {
  return fifo_ld_pop_1d_byte(p, s, off);
}
v32bfloat16
// AIE2PS-LABEL: define dso_local noundef <32 x bfloat> @_Z24test_fifo_ld_pop_2d_byteRrPU3AS5Dv32_8bfloat16R12fifo_state_tiiRii(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(5), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.ld.pop.2d.unaligned.p5.p5(ptr addrspace(5) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20 } [[TMP8]], 4
// AIE2PS-NEXT:    [[TMP14:%.*]] = zext i20 [[TMP13]] to i32
// AIE2PS-NEXT:    store i32 [[TMP14]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP11]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP12]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(5) [[TMP10]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP15:%.*]] = bitcast <64 x i8> [[TMP9]] to <32 x bfloat>
// AIE2PS-NEXT:    ret <32 x bfloat> [[TMP15]]
//
test_fifo_ld_pop_2d_byte(v32bfloat16 __aie_dm_resource_a *restrict &p,
                         fifo_state_t &s, int off, int size1, addr_t &count1,
                         int inc1) {
  return fifo_ld_pop_2d_byte(p, s, off, size1, count1, inc1);
}
v32bfloat16
// AIE2PS-LABEL: define dso_local noundef <32 x bfloat> @_Z24test_fifo_ld_pop_3d_byteRrPU3AS5Dv32_8bfloat16R12fifo_state_tiiRiiiS7_i(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]], i32 noundef [[SIZE2:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT2:%.*]], i32 noundef [[INC2:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(5), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.ld.pop.3d.unaligned.p5.p5(ptr addrspace(5) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP18:%.*]] = zext i20 [[TMP17]] to i32
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } [[TMP12]], 5
// AIE2PS-NEXT:    [[TMP20:%.*]] = zext i20 [[TMP19]] to i32
// AIE2PS-NEXT:    store i32 [[TMP18]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP20]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP15]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP16]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(5) [[TMP14]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP21:%.*]] = bitcast <64 x i8> [[TMP13]] to <32 x bfloat>
// AIE2PS-NEXT:    ret <32 x bfloat> [[TMP21]]
//
test_fifo_ld_pop_3d_byte(v32bfloat16 __aie_dm_resource_a *restrict &p,
                         fifo_state_t &s, int off, int size1, addr_t &count1,
                         int inc1, int size2, addr_t &count2, int inc2) {
  return fifo_ld_pop_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}
// AIE2PS-LABEL: define dso_local noundef <32 x bfloat> @_Z17test_fifo_ld_popxRrPDv32_8bfloat16R12fifo_state_tii(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[MASK:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP]], 6
// AIE2PS-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK]]
// AIE2PS-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2PS-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I]], align 64
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <32 x bfloat>
// AIE2PS-NEXT:    ret <32 x bfloat> [[TMP10]]
//
v32bfloat16 test_fifo_ld_popx(v32bfloat16 *restrict &p, fifo_state_t &s,
                              int step, int mask) {
  return fifo_ld_popx(p, s, step, mask);
}
// AIE2PS-LABEL: define dso_local noundef <32 x bfloat> @_Z17test_fifo_ld_popxRrPDv32_8bfloat16R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[EXTRA3_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I_I]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.popx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 4
// AIE2PS-NEXT:    store <16 x i32> [[TMP9]], ptr [[EXTRA3_I_I]], align 64
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = bitcast <64 x i8> [[TMP5]] to <32 x bfloat>
// AIE2PS-NEXT:    ret <32 x bfloat> [[TMP10]]
//
v32bfloat16 test_fifo_ld_popx(v32bfloat16 *restrict &p, fifo_state_t &s) {
  return fifo_ld_popx(p, s);
}
// AIE2PS-LABEL: define dso_local void @_Z18test_fifo_ld_resetRPU3AS616v64mx9_unalignedR12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) initializes((128, 132)) [[S:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(6), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { ptr addrspace(6), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p6.p6(ptr addrspace(6) [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32 } [[TMP2]], 1
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32 } [[TMP2]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(6) [[TMP3]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_reset(v64mx9_unaligned __aie_dm_resource_b *&p,
                        fifo_state_t &s) {
  fifo_ld_reset(p, s);
}
// AIE2PS-LABEL: define dso_local void @_Z17test_fifo_ld_fillRPU3AS616v64mx9_unalignedR12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(6), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr addrspace(6), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p6.p6(ptr addrspace(6) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(6) [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_fill(v64mx9_unaligned __aie_dm_resource_b *&p,
                       fifo_state_t &s) {
  fifo_ld_fill(p, s);
}
// AIE2PS-LABEL: define dso_local %struct.v64mx9 @_Z16test_fifo_ld_popRPU3AS616v64mx9_unalignedR12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR3:[0-9]+]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(6), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.fifo.ld.pop.BFP640.p6.p6(ptr addrspace(6) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } [[TMP3]], 0
// AIE2PS-NEXT:    store ptr addrspace(6) [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } [[TMP3]], 1
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } [[TMP3]], 2
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } [[TMP3]], 3
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } [[TMP3]], 4
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } [[TMP3]], 5
// AIE2PS-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX9:%.*]] poison, <16 x i32> [[TMP7]], 0
// AIE2PS-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX9]] [[DOTFCA_0_INSERT_I]], <2 x i32> [[TMP8]], 1
// AIE2PS-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX9]] [[DOTFCA_1_INSERT_I]], <2 x i32> [[TMP9]], 2
// AIE2PS-NEXT:    ret [[STRUCT_V64MX9]] [[DOTFCA_2_INSERT_I]]
//
v64mx9 test_fifo_ld_pop(v64mx9_unaligned __aie_dm_resource_b *&p,
                        fifo_state_t &s) {
  return fifo_ld_pop(p, s);
}
// AIE2PS-LABEL: define dso_local %struct.v64mx9 @_Z24test_fifo_ld_pop_1d_byteRPU3AS616v64mx9_unalignedR12fifo_state_ti(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]]) local_unnamed_addr #[[ATTR3]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(6), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.fifo.ld.pop.1d.BFP640.p6.p6(ptr addrspace(6) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } [[TMP4]], 0
// AIE2PS-NEXT:    store ptr addrspace(6) [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } [[TMP4]], 1
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } [[TMP4]], 2
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } [[TMP4]], 3
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } [[TMP4]], 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, <16 x i32>, <2 x i32>, <2 x i32> } [[TMP4]], 5
// AIE2PS-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX9:%.*]] poison, <16 x i32> [[TMP8]], 0
// AIE2PS-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX9]] [[DOTFCA_0_INSERT_I]], <2 x i32> [[TMP9]], 1
// AIE2PS-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX9]] [[DOTFCA_1_INSERT_I]], <2 x i32> [[TMP10]], 2
// AIE2PS-NEXT:    ret [[STRUCT_V64MX9]] [[DOTFCA_2_INSERT_I]]
//
v64mx9 test_fifo_ld_pop_1d_byte(v64mx9_unaligned __aie_dm_resource_b *&p,
                                fifo_state_t &s, int off) {
  return fifo_ld_pop_1d_byte(p, s, off);
}
// AIE2PS-LABEL: define dso_local %struct.v64mx9 @_Z24test_fifo_ld_pop_2d_byteRPU3AS616v64mx9_unalignedR12fifo_state_tiiRii(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]]) local_unnamed_addr #[[ATTR3]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(6), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr addrspace(6), <32 x i32>, i32, i20, <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.fifo.ld.pop.2d.BFP640.p6.p6(ptr addrspace(6) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, <16 x i32>, <2 x i32>, <2 x i32> } [[TMP8]], 0
// AIE2PS-NEXT:    store ptr addrspace(6) [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, <16 x i32>, <2 x i32>, <2 x i32> } [[TMP8]], 1
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, <16 x i32>, <2 x i32>, <2 x i32> } [[TMP8]], 2
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, <16 x i32>, <2 x i32>, <2 x i32> } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, <16 x i32>, <2 x i32>, <2 x i32> } [[TMP8]], 4
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, <16 x i32>, <2 x i32>, <2 x i32> } [[TMP8]], 5
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, <16 x i32>, <2 x i32>, <2 x i32> } [[TMP8]], 6
// AIE2PS-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX9:%.*]] poison, <16 x i32> [[TMP14]], 0
// AIE2PS-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX9]] [[DOTFCA_0_INSERT_I]], <2 x i32> [[TMP15]], 1
// AIE2PS-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX9]] [[DOTFCA_1_INSERT_I]], <2 x i32> [[TMP16]], 2
// AIE2PS-NEXT:    ret [[STRUCT_V64MX9]] [[DOTFCA_2_INSERT_I]]
//
v64mx9 test_fifo_ld_pop_2d_byte(v64mx9_unaligned __aie_dm_resource_b *&p,
                                fifo_state_t &s, int off, int size1,
                                addr_t &count1, int inc1) {
  return fifo_ld_pop_2d_byte(p, s, off, size1, count1, inc1);
}
// AIE2PS-LABEL: define dso_local %struct.v64mx9 @_Z24test_fifo_ld_pop_3d_byteRPU3AS616v64mx9_unalignedR12fifo_state_tiiRiiiS5_i(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]], i32 noundef [[SIZE2:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT2:%.*]], i32 noundef [[INC2:%.*]]) local_unnamed_addr #[[ATTR3]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(6), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr addrspace(6), <32 x i32>, i32, i20, i20, <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.fifo.ld.pop.3d.BFP640.p6.p6(ptr addrspace(6) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, i20, <16 x i32>, <2 x i32>, <2 x i32> } [[TMP12]], 0
// AIE2PS-NEXT:    store ptr addrspace(6) [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, i20, <16 x i32>, <2 x i32>, <2 x i32> } [[TMP12]], 1
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, i20, <16 x i32>, <2 x i32>, <2 x i32> } [[TMP12]], 2
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, i20, <16 x i32>, <2 x i32>, <2 x i32> } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, i20, <16 x i32>, <2 x i32>, <2 x i32> } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    [[TMP20:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, i20, <16 x i32>, <2 x i32>, <2 x i32> } [[TMP12]], 5
// AIE2PS-NEXT:    [[TMP21:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, i20, <16 x i32>, <2 x i32>, <2 x i32> } [[TMP12]], 6
// AIE2PS-NEXT:    [[TMP22:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, i20, <16 x i32>, <2 x i32>, <2 x i32> } [[TMP12]], 7
// AIE2PS-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX9:%.*]] poison, <16 x i32> [[TMP20]], 0
// AIE2PS-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX9]] [[DOTFCA_0_INSERT_I]], <2 x i32> [[TMP21]], 1
// AIE2PS-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX9]] [[DOTFCA_1_INSERT_I]], <2 x i32> [[TMP22]], 2
// AIE2PS-NEXT:    ret [[STRUCT_V64MX9]] [[DOTFCA_2_INSERT_I]]
//
v64mx9 test_fifo_ld_pop_3d_byte(v64mx9_unaligned __aie_dm_resource_b *&p,
                                fifo_state_t &s, int off, int size1,
                                addr_t &count1, int inc1, int size2,
                                addr_t &count2, int inc2) {
  return fifo_ld_pop_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}
// AIE2PS-LABEL: define dso_local void @_Z18test_fifo_ld_fillxRP16v64mx9_unalignedR12fifo_state_tii(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[MASK:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2PS-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP]], 6
// AIE2PS-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.fillx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2PS-NEXT:    store <16 x i32> [[TMP8]], ptr [[EXTRA3_I]], align 64
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_fillx(v64mx9_unaligned *&p, fifo_state_t &s, int step,
                        int mask) {
  fifo_ld_fillx(p, s, step, mask);
}
// AIE2PS-LABEL: define dso_local void @_Z18test_fifo_ld_fillxRP16v64mx9_unalignedR12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.fillx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2PS-NEXT:    store <16 x i32> [[TMP8]], ptr [[EXTRA3_I]], align 64
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_fillx(v64mx9_unaligned *&p, fifo_state_t &s) {
  fifo_ld_fillx(p, s, 31, 31);
}
// AIE2PS-LABEL: define dso_local void @_Z18test_fifo_ld_resetRrPU3AS617v128mx4_unalignedR12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) initializes((128, 132)) [[S:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(6), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { ptr addrspace(6), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p6.p6(ptr addrspace(6) [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32 } [[TMP2]], 1
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32 } [[TMP2]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP4]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP5]], ptr [[POS_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(6) [[TMP3]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_reset(v128mx4_unaligned __aie_dm_resource_b *restrict &p,
                        fifo_state_t &s) {
  fifo_ld_reset(p, s);
}
// AIE2PS-LABEL: define dso_local void @_Z17test_fifo_ld_fillRrPU3AS617v128mx4_unalignedR12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(6), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr addrspace(6), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p6.p6(ptr addrspace(6) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(6) [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_fill(v128mx4_unaligned __aie_dm_resource_b *restrict &p,
                       fifo_state_t &s) {
  fifo_ld_fill(p, s);
}
// AIE2PS-LABEL: define dso_local %struct.v128mx4 @_Z16test_fifo_ld_popRrPU3AS617v128mx4_unalignedR12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR3]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(6), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr addrspace(6), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } @llvm.aie2ps.fifo.ld.pop.BFP768.p6.p6(ptr addrspace(6) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    store ptr addrspace(6) [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP3]], 3
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP3]], 4
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP3]], 5
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP3]], 6
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP3]], 7
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP3]], 8
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP3]], 9
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP3]], 10
// AIE2PS-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4:%.*]] poison, <8 x i32> [[TMP7]], 0
// AIE2PS-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_0_INSERT_I]], <8 x i32> [[TMP8]], 1
// AIE2PS-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_1_INSERT_I]], <2 x i32> [[TMP9]], 2
// AIE2PS-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_2_INSERT_I]], <2 x i32> [[TMP10]], 3
// AIE2PS-NEXT:    [[DOTFCA_4_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_3_INSERT_I]], i32 [[TMP11]], 4
// AIE2PS-NEXT:    [[DOTFCA_5_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_4_INSERT_I]], i32 [[TMP12]], 5
// AIE2PS-NEXT:    [[DOTFCA_6_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_5_INSERT_I]], i32 [[TMP13]], 6
// AIE2PS-NEXT:    [[DOTFCA_7_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_6_INSERT_I]], i32 [[TMP14]], 7
// AIE2PS-NEXT:    ret [[STRUCT_V128MX4]] [[DOTFCA_7_INSERT_I]]
//
v128mx4 test_fifo_ld_pop(v128mx4_unaligned __aie_dm_resource_b *restrict &p,
                         fifo_state_t &s) {
  return fifo_ld_pop(p, s);
}
// AIE2PS-LABEL: define dso_local %struct.v128mx4 @_Z24test_fifo_ld_pop_1d_byteRrPU3AS617v128mx4_unalignedR12fifo_state_ti(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]]) local_unnamed_addr #[[ATTR3]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(6), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr addrspace(6), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } @llvm.aie2ps.fifo.ld.pop.1d.BFP768.p6.p6(ptr addrspace(6) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    store ptr addrspace(6) [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP4]], 3
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP4]], 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP4]], 5
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP4]], 6
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP4]], 7
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP4]], 8
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP4]], 9
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP4]], 10
// AIE2PS-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4:%.*]] poison, <8 x i32> [[TMP8]], 0
// AIE2PS-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_0_INSERT_I]], <8 x i32> [[TMP9]], 1
// AIE2PS-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_1_INSERT_I]], <2 x i32> [[TMP10]], 2
// AIE2PS-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_2_INSERT_I]], <2 x i32> [[TMP11]], 3
// AIE2PS-NEXT:    [[DOTFCA_4_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_3_INSERT_I]], i32 [[TMP12]], 4
// AIE2PS-NEXT:    [[DOTFCA_5_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_4_INSERT_I]], i32 [[TMP13]], 5
// AIE2PS-NEXT:    [[DOTFCA_6_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_5_INSERT_I]], i32 [[TMP14]], 6
// AIE2PS-NEXT:    [[DOTFCA_7_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_6_INSERT_I]], i32 [[TMP15]], 7
// AIE2PS-NEXT:    ret [[STRUCT_V128MX4]] [[DOTFCA_7_INSERT_I]]
//
v128mx4 test_fifo_ld_pop_1d_byte(v128mx4_unaligned __aie_dm_resource_b *restrict &p,
                         fifo_state_t &s, int off) {
  return fifo_ld_pop_1d_byte(p, s, off);
}
// AIE2PS-LABEL: define dso_local %struct.v128mx4 @_Z24test_fifo_ld_pop_2d_byteRrPU3AS617v128mx4_unalignedR12fifo_state_tiiRii(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]]) local_unnamed_addr #[[ATTR3]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(6), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr addrspace(6), <32 x i32>, i32, i20, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } @llvm.aie2ps.fifo.ld.pop.2d.BFP768.p6.p6(ptr addrspace(6) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP8]], 0
// AIE2PS-NEXT:    store ptr addrspace(6) [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP8]], 1
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP8]], 2
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP8]], 4
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP8]], 5
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP8]], 6
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP8]], 7
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP8]], 8
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP8]], 9
// AIE2PS-NEXT:    [[TMP20:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP8]], 10
// AIE2PS-NEXT:    [[TMP21:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP8]], 11
// AIE2PS-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4:%.*]] poison, <8 x i32> [[TMP14]], 0
// AIE2PS-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_0_INSERT_I]], <8 x i32> [[TMP15]], 1
// AIE2PS-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_1_INSERT_I]], <2 x i32> [[TMP16]], 2
// AIE2PS-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_2_INSERT_I]], <2 x i32> [[TMP17]], 3
// AIE2PS-NEXT:    [[DOTFCA_4_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_3_INSERT_I]], i32 [[TMP18]], 4
// AIE2PS-NEXT:    [[DOTFCA_5_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_4_INSERT_I]], i32 [[TMP19]], 5
// AIE2PS-NEXT:    [[DOTFCA_6_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_5_INSERT_I]], i32 [[TMP20]], 6
// AIE2PS-NEXT:    [[DOTFCA_7_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_6_INSERT_I]], i32 [[TMP21]], 7
// AIE2PS-NEXT:    ret [[STRUCT_V128MX4]] [[DOTFCA_7_INSERT_I]]
//
v128mx4 test_fifo_ld_pop_2d_byte(v128mx4_unaligned __aie_dm_resource_b *restrict &p,
                         fifo_state_t &s, int off, int size1, addr_t &count1,
                         int inc1) {
  return fifo_ld_pop_2d_byte(p, s, off, size1, count1, inc1);
}
// AIE2PS-LABEL: define dso_local %struct.v128mx4 @_Z24test_fifo_ld_pop_3d_byteRrPU3AS617v128mx4_unalignedR12fifo_state_tiiRiiiS6_i(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]], i32 noundef [[SIZE2:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT2:%.*]], i32 noundef [[INC2:%.*]]) local_unnamed_addr #[[ATTR3]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(6), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr addrspace(6), <32 x i32>, i32, i20, i20, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } @llvm.aie2ps.fifo.ld.pop.3d.BFP768.p6.p6(ptr addrspace(6) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, i20, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP12]], 0
// AIE2PS-NEXT:    store ptr addrspace(6) [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, i20, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP12]], 1
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, i20, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP12]], 2
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, i20, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, i20, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    [[TMP20:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, i20, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP12]], 5
// AIE2PS-NEXT:    [[TMP21:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, i20, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP12]], 6
// AIE2PS-NEXT:    [[TMP22:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, i20, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP12]], 7
// AIE2PS-NEXT:    [[TMP23:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, i20, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP12]], 8
// AIE2PS-NEXT:    [[TMP24:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, i20, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP12]], 9
// AIE2PS-NEXT:    [[TMP25:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, i20, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP12]], 10
// AIE2PS-NEXT:    [[TMP26:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, i20, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP12]], 11
// AIE2PS-NEXT:    [[TMP27:%.*]] = extractvalue { ptr addrspace(6), <32 x i32>, i32, i20, i20, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP12]], 12
// AIE2PS-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4:%.*]] poison, <8 x i32> [[TMP20]], 0
// AIE2PS-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_0_INSERT_I]], <8 x i32> [[TMP21]], 1
// AIE2PS-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_1_INSERT_I]], <2 x i32> [[TMP22]], 2
// AIE2PS-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_2_INSERT_I]], <2 x i32> [[TMP23]], 3
// AIE2PS-NEXT:    [[DOTFCA_4_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_3_INSERT_I]], i32 [[TMP24]], 4
// AIE2PS-NEXT:    [[DOTFCA_5_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_4_INSERT_I]], i32 [[TMP25]], 5
// AIE2PS-NEXT:    [[DOTFCA_6_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_5_INSERT_I]], i32 [[TMP26]], 6
// AIE2PS-NEXT:    [[DOTFCA_7_INSERT_I:%.*]] = insertvalue [[STRUCT_V128MX4]] [[DOTFCA_6_INSERT_I]], i32 [[TMP27]], 7
// AIE2PS-NEXT:    ret [[STRUCT_V128MX4]] [[DOTFCA_7_INSERT_I]]
//
v128mx4 test_fifo_ld_pop_3d_byte(v128mx4_unaligned __aie_dm_resource_b *restrict &p,
                         fifo_state_t &s, int off, int size1, addr_t &count1,
                         int inc1, int size2, addr_t &count2, int inc2) {
  return fifo_ld_pop_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}
// AIE2PS-LABEL: define dso_local void @_Z18test_fifo_ld_fillxRrP17v128mx4_unalignedR12fifo_state_tii(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[MASK:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2PS-NEXT:    [[SHL_I:%.*]] = shl i32 [[STEP]], 6
// AIE2PS-NEXT:    [[OR_I:%.*]] = or i32 [[SHL_I]], [[MASK]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.fillx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 [[OR_I]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2PS-NEXT:    store <16 x i32> [[TMP8]], ptr [[EXTRA3_I]], align 64
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_fillx(v128mx4_unaligned *restrict &p, fifo_state_t &s,
                        int step, int mask) {
  fifo_ld_fillx(p, s, step, mask);
}
// AIE2PS-LABEL: define dso_local void @_Z18test_fifo_ld_fillxRrP17v128mx4_unalignedR12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[EXTRA3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 192
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[EXTRA3_I]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.fillx.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], <16 x i32> [[TMP3]], i32 2015)
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 2
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } [[TMP4]], 3
// AIE2PS-NEXT:    store <16 x i32> [[TMP8]], ptr [[EXTRA3_I]], align 64
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_fillx(v128mx4_unaligned *restrict &p, fifo_state_t &s) {
  fifo_ld_fillx(p, s, 31, 31);
}
// AIE2PS-LABEL: define dso_local void @_Z18test_fifo_ld_resetRPU4AS1417v256mx6_unalignedR12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) initializes((128, 132)) [[FIFO:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[FIFO]], i20 128
// AIE2PS-NEXT:    store i32 0, ptr [[POS_I_I]], align 64, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(14), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[FIFO]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { ptr addrspace(14), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p14.p14(ptr addrspace(14) [[TMP0]], <32 x i32> [[TMP1]], i32 0)
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { ptr addrspace(14), <32 x i32>, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(14), <32 x i32>, i32 } [[TMP2]], 1
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(14), <32 x i32>, i32 } [[TMP2]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP4]], ptr [[FIFO]], align 128
// AIE2PS-NEXT:    store i32 [[TMP5]], ptr [[POS_I_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(14) [[TMP3]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_reset(v256mx6_unaligned __aie_dm_resource_cd *&p,
                        fifo_state_t &fifo) {
  fifo_ld_reset(p, fifo);
}
// AIE2PS-LABEL: define dso_local void @_Z17test_fifo_ld_fillRPU4AS1417v256mx6_unalignedR12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[FIFO:%.*]]) local_unnamed_addr #[[ATTR1]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[FIFO]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(14), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[FIFO]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr addrspace(14), <32 x i32>, i32 } @llvm.aie2ps.fifo.ld.fill.p14.p14(ptr addrspace(14) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(14), <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(14), <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(14), <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[FIFO]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(14) [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_ld_fill(v256mx6_unaligned __aie_dm_resource_cd *&p,
                       fifo_state_t &fifo) {
  fifo_ld_fill(p, fifo);
}
// AIE2PS-LABEL: define dso_local %struct.v256mx6 @_Z16test_fifo_ld_popRPU4AS1417v256mx6_unalignedR12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[FIFO:%.*]]) local_unnamed_addr #[[ATTR3]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[FIFO]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(14), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[FIFO]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr addrspace(14), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } @llvm.aie2ps.fifo.ld.pop.BFP768.p14.p14(ptr addrspace(14) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(14), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    store ptr addrspace(14) [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(14), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[FIFO]], align 128
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(14), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I_I]], align 64
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr addrspace(14), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP3]], 3
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { ptr addrspace(14), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP3]], 4
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr addrspace(14), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP3]], 5
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr addrspace(14), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP3]], 6
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr addrspace(14), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP3]], 7
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr addrspace(14), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP3]], 8
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr addrspace(14), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP3]], 9
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr addrspace(14), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP3]], 10
// AIE2PS-NEXT:    [[DOTFCA_0_INSERT_I59_I:%.*]] = insertvalue [[STRUCT_V256MX6:%.*]] poison, <8 x i32> [[TMP7]], 0
// AIE2PS-NEXT:    [[DOTFCA_1_INSERT_I60_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_0_INSERT_I59_I]], <8 x i32> [[TMP8]], 1
// AIE2PS-NEXT:    [[DOTFCA_2_INSERT_I61_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_1_INSERT_I60_I]], <8 x i32> undef, 2
// AIE2PS-NEXT:    [[DOTFCA_3_INSERT_I62_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_2_INSERT_I61_I]], <8 x i32> undef, 3
// AIE2PS-NEXT:    [[DOTFCA_4_INSERT_I63_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_3_INSERT_I62_I]], <2 x i32> [[TMP9]], 4
// AIE2PS-NEXT:    [[DOTFCA_5_INSERT_I64_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_4_INSERT_I63_I]], <2 x i32> [[TMP10]], 5
// AIE2PS-NEXT:    [[DOTFCA_6_INSERT_I65_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_5_INSERT_I64_I]], <2 x i32> undef, 6
// AIE2PS-NEXT:    [[DOTFCA_7_INSERT_I66_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_6_INSERT_I65_I]], <2 x i32> undef, 7
// AIE2PS-NEXT:    [[DOTFCA_8_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_7_INSERT_I66_I]], i32 [[TMP11]], 8
// AIE2PS-NEXT:    [[DOTFCA_9_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_8_INSERT_I_I]], i32 [[TMP12]], 9
// AIE2PS-NEXT:    [[DOTFCA_10_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_9_INSERT_I_I]], i32 undef, 10
// AIE2PS-NEXT:    [[DOTFCA_11_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_10_INSERT_I_I]], i32 undef, 11
// AIE2PS-NEXT:    [[DOTFCA_12_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_11_INSERT_I_I]], i32 [[TMP13]], 12
// AIE2PS-NEXT:    [[DOTFCA_13_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_12_INSERT_I_I]], i32 [[TMP14]], 13
// AIE2PS-NEXT:    [[DOTFCA_14_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_13_INSERT_I_I]], i32 undef, 14
// AIE2PS-NEXT:    [[DOTFCA_15_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_14_INSERT_I_I]], i32 undef, 15
// AIE2PS-NEXT:    [[TMP15:%.*]] = load ptr addrspace(14), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP16:%.*]] = tail call { ptr addrspace(14), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } @llvm.aie2ps.fifo.ld.pop.BFP768.p14.p14(ptr addrspace(14) [[TMP15]], <32 x i32> [[TMP5]], i32 [[TMP6]])
// AIE2PS-NEXT:    [[TMP17:%.*]] = extractvalue { ptr addrspace(14), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP16]], 0
// AIE2PS-NEXT:    store ptr addrspace(14) [[TMP17]], ptr [[P]], align 4
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr addrspace(14), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP16]], 1
// AIE2PS-NEXT:    store <32 x i32> [[TMP18]], ptr [[FIFO]], align 128
// AIE2PS-NEXT:    [[TMP19:%.*]] = extractvalue { ptr addrspace(14), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP16]], 2
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[POS1_I_I]], align 64
// AIE2PS-NEXT:    [[TMP20:%.*]] = extractvalue { ptr addrspace(14), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP16]], 3
// AIE2PS-NEXT:    [[TMP21:%.*]] = extractvalue { ptr addrspace(14), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP16]], 4
// AIE2PS-NEXT:    [[TMP22:%.*]] = extractvalue { ptr addrspace(14), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP16]], 5
// AIE2PS-NEXT:    [[TMP23:%.*]] = extractvalue { ptr addrspace(14), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP16]], 6
// AIE2PS-NEXT:    [[TMP24:%.*]] = extractvalue { ptr addrspace(14), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP16]], 7
// AIE2PS-NEXT:    [[TMP25:%.*]] = extractvalue { ptr addrspace(14), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP16]], 8
// AIE2PS-NEXT:    [[TMP26:%.*]] = extractvalue { ptr addrspace(14), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP16]], 9
// AIE2PS-NEXT:    [[TMP27:%.*]] = extractvalue { ptr addrspace(14), <32 x i32>, i32, <8 x i32>, <8 x i32>, <2 x i32>, <2 x i32>, i32, i32, i32, i32 } [[TMP16]], 10
// AIE2PS-NEXT:    [[DOTFCA_2_INSERT_I76_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_15_INSERT_I_I]], <8 x i32> [[TMP20]], 2
// AIE2PS-NEXT:    [[DOTFCA_3_INSERT_I77_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_2_INSERT_I76_I]], <8 x i32> [[TMP21]], 3
// AIE2PS-NEXT:    [[DOTFCA_4_INSERT_I78_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_3_INSERT_I77_I]], <2 x i32> [[TMP9]], 4
// AIE2PS-NEXT:    [[DOTFCA_5_INSERT_I79_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_4_INSERT_I78_I]], <2 x i32> [[TMP10]], 5
// AIE2PS-NEXT:    [[DOTFCA_6_INSERT_I80_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_5_INSERT_I79_I]], <2 x i32> [[TMP22]], 6
// AIE2PS-NEXT:    [[DOTFCA_7_INSERT_I81_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_6_INSERT_I80_I]], <2 x i32> [[TMP23]], 7
// AIE2PS-NEXT:    [[DOTFCA_8_INSERT_I82_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_7_INSERT_I81_I]], i32 [[TMP11]], 8
// AIE2PS-NEXT:    [[DOTFCA_9_INSERT_I83_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_8_INSERT_I82_I]], i32 [[TMP12]], 9
// AIE2PS-NEXT:    [[DOTFCA_10_INSERT_I84_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_9_INSERT_I83_I]], i32 [[TMP24]], 10
// AIE2PS-NEXT:    [[DOTFCA_11_INSERT_I85_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_10_INSERT_I84_I]], i32 [[TMP25]], 11
// AIE2PS-NEXT:    [[DOTFCA_12_INSERT_I86_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_11_INSERT_I85_I]], i32 [[TMP13]], 12
// AIE2PS-NEXT:    [[DOTFCA_13_INSERT_I87_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_12_INSERT_I86_I]], i32 [[TMP14]], 13
// AIE2PS-NEXT:    [[DOTFCA_14_INSERT_I88_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_13_INSERT_I87_I]], i32 [[TMP26]], 14
// AIE2PS-NEXT:    [[DOTFCA_15_INSERT_I89_I:%.*]] = insertvalue [[STRUCT_V256MX6]] [[DOTFCA_14_INSERT_I88_I]], i32 [[TMP27]], 15
// AIE2PS-NEXT:    ret [[STRUCT_V256MX6]] [[DOTFCA_15_INSERT_I89_I]]
//
v256mx6 test_fifo_ld_pop(v256mx6_unaligned __aie_dm_resource_cd *&p,
                         fifo_state_t &fifo) {
  return fifo_ld_pop(p, fifo);
}
// AIE2PS-LABEL: define dso_local void @_Z18test_fifo_st_resetP10v64bfloat8S_RS0_RDv32_iRi(
// AIE2PS-SAME: ptr [[P:%.*]], [[STRUCT_V64BFLOAT8:%.*]] [[V_COERCE:%.*]], ptr nonnull writeonly align 4 captures(none) dereferenceable(4) initializes((0, 3)) [[P_O:%.*]], ptr nonnull writeonly align 64 captures(none) dereferenceable(128) initializes((0, 128)) [[FIFO_O:%.*]], ptr nonnull writeonly align 4 captures(none) dereferenceable(4) initializes((0, 4)) [[POS_O:%.*]]) local_unnamed_addr #[[ATTR4:[0-9]+]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFLOAT8]] [[V_COERCE]], 0
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <64 x i8> [[TMP0]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512.p0.p0(ptr [[P]], <16 x i32> [[TMP1]], <32 x i32> undef, i32 0)
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// AIE2PS-NEXT:    store i32 [[TMP5]], ptr [[POS_O]], align 4
// AIE2PS-NEXT:    store ptr [[TMP3]], ptr [[P_O]], align 4, !tbaa [[TBAA56:![0-9]+]]
// AIE2PS-NEXT:    store <32 x i32> [[TMP4]], ptr [[FIFO_O]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_reset(v64bfloat8 *p, v64bfloat8 v, v64bfloat8 *&p_o,
                        sparse_fifo_t &fifo_o, int &pos_o) {
  fifo_st_reset(p, v, p_o, fifo_o, pos_o);
}
// AIE2PS-LABEL: define dso_local void @_Z18test_fifo_st_resetRP10v64bfloat8S_R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], [[STRUCT_V64BFLOAT8:%.*]] [[V_COERCE:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) initializes((128, 132)) [[S:%.*]]) local_unnamed_addr #[[ATTR5:[0-9]+]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFLOAT8]] [[V_COERCE]], 0
// AIE2PS-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast <64 x i8> [[TMP0]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512.p0.p0(ptr [[TMP1]], <16 x i32> [[TMP3]], <32 x i32> [[TMP2]], i32 0)
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_reset(v64bfloat8 *&p, v64bfloat8 v, fifo_state_t &s) {
  fifo_st_reset(p, v, s);
}
// AIE2PS-LABEL: define dso_local void @_Z17test_fifo_st_pushRP10v64bfloat8S_R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], [[STRUCT_V64BFLOAT8:%.*]] [[V_COERCE:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFLOAT8]] [[V_COERCE]], 0
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = bitcast <64 x i8> [[TMP0]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP5:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512.p0.p0(ptr [[TMP1]], <16 x i32> [[TMP4]], <32 x i32> [[TMP2]], i32 [[TMP3]])
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP5]], 0
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP5]], 1
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP5]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_push(v64bfloat8 *&p, v64bfloat8 v, fifo_state_t &s) {
  fifo_st_push(p, v, s);
}
// AIE2PS-LABEL: define dso_local void @_Z18test_fifo_st_flushRP10v64bfloat8R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush(v64bfloat8 *&p, fifo_state_t &s) {
  fifo_st_flush(p, s);
}
// AIE2PS-LABEL: define dso_local void @_Z26test_fifo_st_flush_1d_byteRP10v64bfloat8R12fifo_state_ti(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_1d_byte(v64bfloat8 *&p, fifo_state_t &s, int off) {
  fifo_st_flush_1d_byte(p, s, off);
}
// AIE2PS-LABEL: define dso_local void @_Z26test_fifo_st_flush_2d_byteRP10v64bfloat8R12fifo_state_tiiRii(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_2d_byte(v64bfloat8 *&p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1) {
  fifo_st_flush_2d_byte(p, s, off, size1, count1, inc1);
}
// AIE2PS-LABEL: define dso_local void @_Z26test_fifo_st_flush_3d_byteRP10v64bfloat8R12fifo_state_tiiRiiiS4_i(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]], i32 noundef [[SIZE2:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT2:%.*]], i32 noundef [[INC2:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_3d_byte(v64bfloat8 *&p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1, int size2,
                                addr_t &count2, int inc2) {
  fifo_st_flush_3d_byte(p, s, off, size1, count1, inc1, size2, count2, inc2);
}
// AIE2PS-LABEL: define dso_local void @_Z23test_fifo_st_flush_bareRP10v64bfloat8R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare(v64bfloat8 *&p, fifo_state_t &s) {
  fifo_st_flush_bare(p, s);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_bare_1d_byteRP10v64bfloat8R12fifo_state_ti(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_1d_byte(v64bfloat8 *&p, fifo_state_t &s, int off) {
  fifo_st_flush_bare_1d_byte(p, s, off);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_bare_2d_byteRP10v64bfloat8R12fifo_state_tiiRii(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_2d_byte(v64bfloat8 *&p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  fifo_st_flush_bare_2d_byte(p, s, off, size1, count1, inc1);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_bare_3d_byteRP10v64bfloat8R12fifo_state_tiiRiiiS4_i(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]], i32 noundef [[SIZE2:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT2:%.*]], i32 noundef [[INC2:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_3d_byte(v64bfloat8 *&p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  fifo_st_flush_bare_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}
// AIE2PS-LABEL: define dso_local void @_Z23test_fifo_st_flush_convRP10v64bfloat8R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv(v64bfloat8 *&p, fifo_state_t &s) {
  fifo_st_flush_conv(p, s);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_conv_1d_byteRP10v64bfloat8R12fifo_state_ti(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_1d_byte(v64bfloat8 *&p, fifo_state_t &s, int off) {
  fifo_st_flush_conv_1d_byte(p, s, off);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_conv_2d_byteRP10v64bfloat8R12fifo_state_tiiRii(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_2d_byte(v64bfloat8 *&p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  fifo_st_flush_conv_2d_byte(p, s, off, size1, count1, inc1);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_conv_3d_byteRP10v64bfloat8R12fifo_state_tiiRiiiS4_i(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]], i32 noundef [[SIZE2:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT2:%.*]], i32 noundef [[INC2:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_3d_byte(v64bfloat8 *&p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  fifo_st_flush_conv_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}
// AIE2PS-LABEL: define dso_local void @_Z18test_fifo_st_resetP9v64float8S_RS0_RDv32_iRi(
// AIE2PS-SAME: ptr noalias [[P:%.*]], [[STRUCT_V64FLOAT8:%.*]] [[V_COERCE:%.*]], ptr nonnull writeonly align 4 captures(none) dereferenceable(4) initializes((0, 3)) [[P_O:%.*]], ptr nonnull writeonly align 64 captures(none) dereferenceable(128) initializes((0, 128)) [[FIFO_O:%.*]], ptr nonnull writeonly align 4 captures(none) dereferenceable(4) initializes((0, 4)) [[POS_O:%.*]]) local_unnamed_addr #[[ATTR4]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64FLOAT8]] [[V_COERCE]], 0
// AIE2PS-NEXT:    [[TMP1:%.*]] = bitcast <64 x i8> [[TMP0]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP2:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512.p0.p0(ptr [[P]], <16 x i32> [[TMP1]], <32 x i32> undef, i32 0)
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 0
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 1
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP2]], 2
// AIE2PS-NEXT:    store i32 [[TMP5]], ptr [[POS_O]], align 4
// AIE2PS-NEXT:    store ptr [[TMP3]], ptr [[P_O]], align 4, !tbaa [[TBAA58:![0-9]+]]
// AIE2PS-NEXT:    store <32 x i32> [[TMP4]], ptr [[FIFO_O]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_reset(v64float8 *restrict p, v64float8 v, v64float8 *&p_o,
                        sparse_fifo_t &fifo_o, int &pos_o) {
  fifo_st_reset(p, v, p_o, fifo_o, pos_o);
}
// AIE2PS-LABEL: define dso_local void @_Z18test_fifo_st_resetRrP9v64float8S_R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], [[STRUCT_V64FLOAT8:%.*]] [[V_COERCE:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) initializes((128, 132)) [[S:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64FLOAT8]] [[V_COERCE]], 0
// AIE2PS-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast <64 x i8> [[TMP0]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512.p0.p0(ptr [[TMP1]], <16 x i32> [[TMP3]], <32 x i32> [[TMP2]], i32 0)
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_reset(v64float8 *restrict &p, v64float8 v, fifo_state_t &s) {
  fifo_st_reset(p, v, s);
}
// AIE2PS-LABEL: define dso_local void @_Z17test_fifo_st_pushRrP9v64float8S_R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], [[STRUCT_V64FLOAT8:%.*]] [[V_COERCE:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64FLOAT8]] [[V_COERCE]], 0
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = bitcast <64 x i8> [[TMP0]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP5:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512.p0.p0(ptr [[TMP1]], <16 x i32> [[TMP4]], <32 x i32> [[TMP2]], i32 [[TMP3]])
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP5]], 0
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP5]], 1
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP5]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_push(v64float8 *restrict &p, v64float8 v, fifo_state_t &s) {
  fifo_st_push(p, v, s);
}
// AIE2PS-LABEL: define dso_local void @_Z18test_fifo_st_flushRrP9v64float8R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush(v64float8 *restrict &p, fifo_state_t &s) {
  fifo_st_flush(p, s);
}
// AIE2PS-LABEL: define dso_local void @_Z26test_fifo_st_flush_1d_byteRrP9v64float8R12fifo_state_ti(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_1d_byte(v64float8 *restrict &p, fifo_state_t &s,
                                int off) {
  fifo_st_flush_1d_byte(p, s, off);
}
// AIE2PS-LABEL: define dso_local void @_Z26test_fifo_st_flush_2d_byteRrP9v64float8R12fifo_state_tiiRii(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_2d_byte(v64float8 *restrict &p, fifo_state_t &s,
                                int off, int size1, addr_t &count1, int inc1) {
  fifo_st_flush_2d_byte(p, s, off, size1, count1, inc1);
}
// AIE2PS-LABEL: define dso_local void @_Z26test_fifo_st_flush_3d_byteRrP9v64float8R12fifo_state_tiiRiiiS5_i(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]], i32 noundef [[SIZE2:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT2:%.*]], i32 noundef [[INC2:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_3d_byte(v64float8 *restrict &p, fifo_state_t &s,
                                int off, int size1, addr_t &count1, int inc1,
                                int size2, addr_t &count2, int inc2) {
  fifo_st_flush_3d_byte(p, s, off, size1, count1, inc1, size2, count2, inc2);
}
// AIE2PS-LABEL: define dso_local void @_Z23test_fifo_st_flush_bareRrP9v64float8R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare(v64float8 *restrict &p, fifo_state_t &s) {
  fifo_st_flush_bare(p, s);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_bare_1d_byteRrP9v64float8R12fifo_state_ti(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_1d_byte(v64float8 *restrict &p, fifo_state_t &s,
                                     int off) {
  fifo_st_flush_bare_1d_byte(p, s, off);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_bare_2d_byteRrP9v64float8R12fifo_state_tiiRii(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_2d_byte(v64float8 *restrict &p, fifo_state_t &s,
                                     int off, int size1, addr_t &count1,
                                     int inc1) {
  fifo_st_flush_bare_2d_byte(p, s, off, size1, count1, inc1);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_bare_3d_byteRrP9v64float8R12fifo_state_tiiRiiiS5_i(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]], i32 noundef [[SIZE2:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT2:%.*]], i32 noundef [[INC2:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_3d_byte(v64float8 *restrict &p, fifo_state_t &s,
                                     int off, int size1, addr_t &count1,
                                     int inc1, int size2, addr_t &count2,
                                     int inc2) {
  fifo_st_flush_bare_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}
// AIE2PS-LABEL: define dso_local void @_Z23test_fifo_st_flush_convRrP9v64float8R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv(v64float8 *restrict &p, fifo_state_t &s) {
  fifo_st_flush_conv(p, s);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_conv_1d_byteRrP9v64float8R12fifo_state_ti(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_1d_byte(v64float8 *restrict &p, fifo_state_t &s,
                                     int off) {
  fifo_st_flush_conv_1d_byte(p, s, off);
}
//
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_conv_2d_byteRrP9v64float8R12fifo_state_tiiRii(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_2d_byte(v64float8 *restrict &p, fifo_state_t &s,
                                     int off, int size1, addr_t &count1,
                                     int inc1) {
  fifo_st_flush_conv_2d_byte(p, s, off, size1, count1, inc1);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_conv_3d_byteRrP9v64float8R12fifo_state_tiiRiiiS5_i(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]], i32 noundef [[SIZE2:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT2:%.*]], i32 noundef [[INC2:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_3d_byte(v64float8 *restrict &p, fifo_state_t &s,
                                     int off, int size1, addr_t &count1,
                                     int inc1, int size2, addr_t &count2,
                                     int inc2) {
  fifo_st_flush_conv_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}
// AIE2PS-LABEL: define dso_local void @_Z18test_fifo_st_resetPDv32_7float16S0_RS1_RDv32_iRi(
// AIE2PS-SAME: ptr noalias [[P:%.*]], <32 x half> noundef [[V:%.*]], ptr nonnull writeonly align 4 captures(none) dereferenceable(4) initializes((0, 3)) [[P_O:%.*]], ptr nonnull writeonly align 64 captures(none) dereferenceable(128) initializes((0, 128)) [[FIFO_O:%.*]], ptr nonnull writeonly align 4 captures(none) dereferenceable(4) initializes((0, 4)) [[POS_O:%.*]]) local_unnamed_addr #[[ATTR4]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <32 x half> [[V]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512.p0.p0(ptr [[P]], <16 x i32> [[TMP0]], <32 x i32> undef, i32 0)
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP1]], 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP1]], 1
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP1]], 2
// AIE2PS-NEXT:    store i32 [[TMP4]], ptr [[POS_O]], align 4
// AIE2PS-NEXT:    store ptr [[TMP2]], ptr [[P_O]], align 4, !tbaa [[TBAA60:![0-9]+]]
// AIE2PS-NEXT:    store <32 x i32> [[TMP3]], ptr [[FIFO_O]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_reset(v32float16 *restrict p, v32float16 v, v32float16 *&p_o,
                        sparse_fifo_t &fifo_o, int &pos_o) {
  fifo_st_reset(p, v, p_o, fifo_o, pos_o);
}
// AIE2PS-LABEL: define dso_local void @_Z18test_fifo_st_resetRrPDv32_7float16S0_R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], <32 x half> noundef [[V:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) initializes((128, 132)) [[S:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <32 x half> [[V]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP2]], <32 x i32> [[TMP1]], i32 0)
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_reset(v32float16 *restrict &p, v32float16 v,
                        fifo_state_t &s) {
  fifo_st_reset(p, v, s);
}
// AIE2PS-LABEL: define dso_local void @_Z17test_fifo_st_pushRrPDv32_7float16S0_R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], <32 x half> noundef [[V:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast <32 x half> [[V]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP3]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_push(v32float16 *restrict &p, v32float16 v, fifo_state_t &s) {
  fifo_st_push(p, v, s);
}
// AIE2PS-LABEL: define dso_local void @_Z18test_fifo_st_flushRrPDv32_7float16R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush(v32float16 *restrict &p, fifo_state_t &s) {
  fifo_st_flush(p, s);
}
// AIE2PS-LABEL: define dso_local void @_Z26test_fifo_st_flush_1d_byteRrPDv32_7float16R12fifo_state_ti(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_1d_byte(v32float16 *restrict &p, fifo_state_t &s,
                                int off) {
  fifo_st_flush_1d_byte(p, s, off);
}
// AIE2PS-LABEL: define dso_local void @_Z26test_fifo_st_flush_2d_byteRrPDv32_7float16R12fifo_state_tiiRii(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_2d_byte(v32float16 *restrict &p, fifo_state_t &s,
                                int off, int size1, addr_t &count1, int inc1) {
  fifo_st_flush_2d_byte(p, s, off, size1, count1, inc1);
}
// AIE2PS-LABEL: define dso_local void @_Z26test_fifo_st_flush_3d_byteRrPDv32_7float16R12fifo_state_tiiRiiiS6_i(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]], i32 noundef [[SIZE2:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT2:%.*]], i32 noundef [[INC2:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_3d_byte(v32float16 *restrict &p, fifo_state_t &s,
                                int off, int size1, addr_t &count1, int inc1,
                                int size2, addr_t &count2, int inc2) {
  fifo_st_flush_3d_byte(p, s, off, size1, count1, inc1, size2, count2, inc2);
}
// AIE2PS-LABEL: define dso_local void @_Z23test_fifo_st_flush_bareRrPDv32_7float16R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare(v32float16 *restrict &p, fifo_state_t &s) {
  fifo_st_flush_bare(p, s);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_bare_1d_byteRrPDv32_7float16R12fifo_state_ti(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_1d_byte(v32float16 *restrict &p, fifo_state_t &s,
                                     int off) {
  fifo_st_flush_bare_1d_byte(p, s, off);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_bare_2d_byteRrPDv32_7float16R12fifo_state_tiiRii(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_2d_byte(v32float16 *restrict &p, fifo_state_t &s,
                                     int off, int size1, addr_t &count1,
                                     int inc1) {
  fifo_st_flush_bare_2d_byte(p, s, off, size1, count1, inc1);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_bare_3d_byteRrPDv32_7float16R12fifo_state_tiiRiiiS6_i(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]], i32 noundef [[SIZE2:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT2:%.*]], i32 noundef [[INC2:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_3d_byte(v32float16 *restrict &p, fifo_state_t &s,
                                     int off, int size1, addr_t &count1,
                                     int inc1, int size2, addr_t &count2,
                                     int inc2) {
  fifo_st_flush_bare_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}
// AIE2PS-LABEL: define dso_local void @_Z23test_fifo_st_flush_convRrPDv32_7float16R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv(v32float16 *restrict &p, fifo_state_t &s) {
  fifo_st_flush_conv(p, s);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_conv_1d_byteRrPDv32_7float16R12fifo_state_ti(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_1d_byte(v32float16 *restrict &p, fifo_state_t &s,
                                     int off) {
  fifo_st_flush_conv_1d_byte(p, s, off);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_conv_2d_byteRrPDv32_7float16R12fifo_state_tiiRii(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_2d_byte(v32float16 *restrict &p, fifo_state_t &s,
                                     int off, int size1, addr_t &count1,
                                     int inc1) {
  fifo_st_flush_conv_2d_byte(p, s, off, size1, count1, inc1);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_conv_3d_byteRrPDv32_7float16R12fifo_state_tiiRiiiS6_i(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]], i32 noundef [[SIZE2:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT2:%.*]], i32 noundef [[INC2:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_3d_byte(v32float16 *restrict &p, fifo_state_t &s,
                                     int off, int size1, addr_t &count1,
                                     int inc1, int size2, addr_t &count2,
                                     int inc2) {
  fifo_st_flush_conv_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}
// AIE2PS-LABEL: define dso_local void @_Z18test_fifo_st_resetPDv32_8bfloat16S0_RS1_RDv32_iRi(
// AIE2PS-SAME: ptr [[P:%.*]], <32 x bfloat> noundef [[V:%.*]], ptr nonnull writeonly align 4 captures(none) dereferenceable(4) initializes((0, 3)) [[P_O:%.*]], ptr nonnull writeonly align 64 captures(none) dereferenceable(128) initializes((0, 128)) [[FIFO_O:%.*]], ptr nonnull writeonly align 4 captures(none) dereferenceable(4) initializes((0, 4)) [[POS_O:%.*]]) local_unnamed_addr #[[ATTR4]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = bitcast <32 x bfloat> [[V]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP1:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512.p0.p0(ptr [[P]], <16 x i32> [[TMP0]], <32 x i32> undef, i32 0)
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP1]], 0
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP1]], 1
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP1]], 2
// AIE2PS-NEXT:    store i32 [[TMP4]], ptr [[POS_O]], align 4
// AIE2PS-NEXT:    store ptr [[TMP2]], ptr [[P_O]], align 4, !tbaa [[TBAA60]]
// AIE2PS-NEXT:    store <32 x i32> [[TMP3]], ptr [[FIFO_O]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_reset(v32bfloat16 *p, v32bfloat16 v, v32bfloat16 *&p_o,
                        sparse_fifo_t &fifo_o, int &pos_o) {
  fifo_st_reset(p, v, p_o, fifo_o, pos_o);
}
// AIE2PS-LABEL: define dso_local void @_Z18test_fifo_st_resetRPDv32_8bfloat16S0_R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], <32 x bfloat> noundef [[V:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) initializes((128, 132)) [[S:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = bitcast <32 x bfloat> [[V]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP2]], <32 x i32> [[TMP1]], i32 0)
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_reset(v32bfloat16 *&p, v32bfloat16 v, fifo_state_t &s) {
  fifo_st_reset(p, v, s);
}
// AIE2PS-LABEL: define dso_local void @_Z17test_fifo_st_pushRPDv32_8bfloat16S0_R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], <32 x bfloat> noundef [[V:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = bitcast <32 x bfloat> [[V]] to <16 x i32>
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.512.p0.p0(ptr [[TMP0]], <16 x i32> [[TMP3]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_push(v32bfloat16 *&p, v32bfloat16 v, fifo_state_t &s) {
  fifo_st_push(p, v, s);
}
// AIE2PS-LABEL: define dso_local void @_Z18test_fifo_st_flushRPDv32_8bfloat16R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush(v32bfloat16 *&p, fifo_state_t &s) {
  fifo_st_flush(p, s);
}
// AIE2PS-LABEL: define dso_local void @_Z26test_fifo_st_flush_1d_byteRPDv32_8bfloat16R12fifo_state_ti(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_1d_byte(v32bfloat16 *&p, fifo_state_t &s, int off) {
  fifo_st_flush_1d_byte(p, s, off);
}
// AIE2PS-LABEL: define dso_local void @_Z26test_fifo_st_flush_2d_byteRPDv32_8bfloat16R12fifo_state_tiiRii(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_2d_byte(v32bfloat16 *&p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1) {
  fifo_st_flush_2d_byte(p, s, off, size1, count1, inc1);
}
// AIE2PS-LABEL: define dso_local void @_Z26test_fifo_st_flush_3d_byteRPDv32_8bfloat16R12fifo_state_tiiRiiiS5_i(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]], i32 noundef [[SIZE2:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT2:%.*]], i32 noundef [[INC2:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_3d_byte(v32bfloat16 *&p, fifo_state_t &s, int off,
                                int size1, addr_t &count1, int inc1, int size2,
                                addr_t &count2, int inc2) {
  fifo_st_flush_3d_byte(p, s, off, size1, count1, inc1, size2, count2, inc2);
}
// AIE2PS-LABEL: define dso_local void @_Z23test_fifo_st_flush_bareRPDv32_8bfloat16R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare(v32bfloat16 *&p, fifo_state_t &s) {
  fifo_st_flush_bare(p, s);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_bare_1d_byteRPDv32_8bfloat16R12fifo_state_ti(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_1d_byte(v32bfloat16 *&p, fifo_state_t &s,
                                     int off) {
  fifo_st_flush_bare_1d_byte(p, s, off);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_bare_2d_byteRPDv32_8bfloat16R12fifo_state_tiiRii(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_2d_byte(v32bfloat16 *&p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  fifo_st_flush_bare_2d_byte(p, s, off, size1, count1, inc1);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_bare_3d_byteRPDv32_8bfloat16R12fifo_state_tiiRiiiS5_i(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]], i32 noundef [[SIZE2:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT2:%.*]], i32 noundef [[INC2:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_3d_byte(v32bfloat16 *&p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  fifo_st_flush_bare_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}
// AIE2PS-LABEL: define dso_local void @_Z23test_fifo_st_flush_convRPDv32_8bfloat16R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv(v32bfloat16 *&p, fifo_state_t &s) {
  fifo_st_flush_conv(p, s);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_conv_1d_byteRPDv32_8bfloat16R12fifo_state_ti(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr, <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_1d_byte(v32bfloat16 *&p, fifo_state_t &s,
                                     int off) {
  fifo_st_flush_conv_1d_byte(p, s, off);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_conv_2d_byteRPDv32_8bfloat16R12fifo_state_tiiRii(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_2d_byte(v32bfloat16 *&p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1) {
  fifo_st_flush_conv_2d_byte(p, s, off, size1, count1, inc1);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_conv_3d_byteRPDv32_8bfloat16R12fifo_state_tiiRiiiS5_i(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]], i32 noundef [[SIZE2:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT2:%.*]], i32 noundef [[INC2:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.conv.p0.p0(ptr [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_3d_byte(v32bfloat16 *&p, fifo_state_t &s, int off,
                                     int size1, addr_t &count1, int inc1,
                                     int size2, addr_t &count2, int inc2) {
  fifo_st_flush_conv_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}
// AIE2PS-LABEL: define dso_local void @_Z18test_fifo_st_resetPU3AS816v64mx9_unaligned6v64mx9RS1_RDv32_iRi(
// AIE2PS-SAME: ptr addrspace(8) [[P:%.*]], [[STRUCT_V64MX9:%.*]] [[V_COERCE:%.*]], ptr nonnull writeonly align 4 captures(none) dereferenceable(4) initializes((0, 3)) [[P_O:%.*]], ptr nonnull writeonly align 64 captures(none) dereferenceable(128) initializes((0, 128)) [[FIFO_O:%.*]], ptr nonnull writeonly align 4 captures(none) dereferenceable(4) initializes((0, 4)) [[POS_O:%.*]]) local_unnamed_addr #[[ATTR6:[0-9]+]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64MX9]] [[V_COERCE]], 0
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64MX9]] [[V_COERCE]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64MX9]] [[V_COERCE]], 2
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.BFP640.p8.p8(ptr addrspace(8) [[P]], <32 x i32> undef, i32 0, <16 x i32> [[TMP0]], <2 x i32> [[TMP1]], <2 x i32> [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS_O]], align 4
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP4]], ptr [[P_O]], align 4, !tbaa [[TBAA61:![0-9]+]]
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[FIFO_O]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_reset(v64mx9_unaligned __aie_dm_resource_d *p, v64mx9 v,
                        v64mx9_unaligned __aie_dm_resource_d *&p_o,
                        sparse_fifo_t &fifo_o, int &pos_o) {
  fifo_st_reset(p, v, p_o, fifo_o, pos_o);
}
// AIE2PS-LABEL: define dso_local void @_Z18test_fifo_st_resetRPU3AS816v64mx9_unaligned6v64mx9R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], [[STRUCT_V64MX9:%.*]] [[V_COERCE:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) initializes((128, 132)) [[S:%.*]]) local_unnamed_addr #[[ATTR7:[0-9]+]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64MX9]] [[V_COERCE]], 0
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64MX9]] [[V_COERCE]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64MX9]] [[V_COERCE]], 2
// AIE2PS-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP5:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.BFP640.p8.p8(ptr addrspace(8) [[TMP3]], <32 x i32> [[TMP4]], i32 0, <16 x i32> [[TMP0]], <2 x i32> [[TMP1]], <2 x i32> [[TMP2]])
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP5]], 0
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP5]], 1
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP5]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP7]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP8]], ptr [[POS_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP6]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_reset(v64mx9_unaligned __aie_dm_resource_d *&p, v64mx9 v,
                        fifo_state_t &s) {
  fifo_st_reset(p, v, s);
}
// AIE2PS-LABEL: define dso_local void @_Z17test_fifo_st_pushRPU3AS816v64mx9_unaligned6v64mx9R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], [[STRUCT_V64MX9:%.*]] [[V_COERCE:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR7]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64MX9]] [[V_COERCE]], 0
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64MX9]] [[V_COERCE]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64MX9]] [[V_COERCE]], 2
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP3:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.BFP640.p8.p8(ptr addrspace(8) [[TMP3]], <32 x i32> [[TMP4]], i32 [[TMP5]], <16 x i32> [[TMP0]], <2 x i32> [[TMP1]], <2 x i32> [[TMP2]])
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP6]], 1
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP6]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP8]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP9]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP7]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_push(v64mx9_unaligned __aie_dm_resource_d *&p, v64mx9 v,
                       fifo_state_t &s) {
  fifo_st_push(p, v, s);
}
// AIE2PS-LABEL: define dso_local void @_Z18test_fifo_st_flushRPU3AS816v64mx9_unalignedR12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush(v64mx9_unaligned __aie_dm_resource_d *&p,
                        fifo_state_t &s) {
  fifo_st_flush(p, s);
}
// AIE2PS-LABEL: define dso_local void @_Z26test_fifo_st_flush_1d_byteRPU3AS816v64mx9_unalignedR12fifo_state_ti(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_1d_byte(v64mx9_unaligned __aie_dm_resource_d *&p,
                                fifo_state_t &s, int off) {
  fifo_st_flush_1d_byte(p, s, off);
}
// AIE2PS-LABEL: define dso_local void @_Z26test_fifo_st_flush_2d_byteRPU3AS816v64mx9_unalignedR12fifo_state_tiiRii(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_2d_byte(v64mx9_unaligned __aie_dm_resource_d *&p,
                                fifo_state_t &s, int off, int size1,
                                addr_t &count1, int inc1) {
  fifo_st_flush_2d_byte(p, s, off, size1, count1, inc1);
}
// AIE2PS-LABEL: define dso_local void @_Z26test_fifo_st_flush_3d_byteRPU3AS816v64mx9_unalignedR12fifo_state_tiiRiiiS5_i(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]], i32 noundef [[SIZE2:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT2:%.*]], i32 noundef [[INC2:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_3d_byte(v64mx9_unaligned __aie_dm_resource_d *&p,
                                fifo_state_t &s, int off, int size1,
                                addr_t &count1, int inc1, int size2,
                                addr_t &count2, int inc2) {
  fifo_st_flush_3d_byte(p, s, off, size1, count1, inc1, size2, count2, inc2);
}
// AIE2PS-LABEL: define dso_local void @_Z23test_fifo_st_flush_bareRPU3AS816v64mx9_unalignedR12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare(v64mx9_unaligned __aie_dm_resource_d *&p,
                             fifo_state_t &s) {
  fifo_st_flush_bare(p, s);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_bare_1d_byteRPU3AS816v64mx9_unalignedR12fifo_state_ti(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_1d_byte(v64mx9_unaligned __aie_dm_resource_d *&p,
                                     fifo_state_t &s, int off) {
  fifo_st_flush_bare_1d_byte(p, s, off);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_bare_2d_byteRPU3AS816v64mx9_unalignedR12fifo_state_tiiRii(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_2d_byte(v64mx9_unaligned __aie_dm_resource_d *&p,
                                     fifo_state_t &s, int off, int size1,
                                     addr_t &count1, int inc1) {
  fifo_st_flush_bare_2d_byte(p, s, off, size1, count1, inc1);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_bare_3d_byteRPU3AS816v64mx9_unalignedR12fifo_state_tiiRiiiS5_i(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]], i32 noundef [[SIZE2:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT2:%.*]], i32 noundef [[INC2:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_3d_byte(v64mx9_unaligned __aie_dm_resource_d *&p,
                                     fifo_state_t &s, int off, int size1,
                                     addr_t &count1, int inc1, int size2,
                                     addr_t &count2, int inc2) {
  fifo_st_flush_bare_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}
// AIE2PS-LABEL: define dso_local void @_Z23test_fifo_st_flush_convRPU3AS816v64mx9_unalignedR12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.conv.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv(v64mx9_unaligned __aie_dm_resource_d *&p,
                             fifo_state_t &s) {
  fifo_st_flush_conv(p, s);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_conv_1d_byteRPU3AS816v64mx9_unalignedR12fifo_state_ti(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.conv.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_1d_byte(v64mx9_unaligned __aie_dm_resource_d *&p,
                                     fifo_state_t &s, int off) {
  fifo_st_flush_conv_1d_byte(p, s, off);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_conv_2d_byteRPU3AS816v64mx9_unalignedR12fifo_state_tiiRii(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.conv.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_2d_byte(v64mx9_unaligned __aie_dm_resource_d *&p,
                                     fifo_state_t &s, int off, int size1,
                                     addr_t &count1, int inc1) {
  fifo_st_flush_conv_2d_byte(p, s, off, size1, count1, inc1);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_conv_3d_byteRPU3AS816v64mx9_unalignedR12fifo_state_tiiRiiiS5_i(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]], i32 noundef [[SIZE2:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT2:%.*]], i32 noundef [[INC2:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.conv.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_3d_byte(v64mx9_unaligned __aie_dm_resource_d *&p,
                                     fifo_state_t &s, int off, int size1,
                                     addr_t &count1, int inc1, int size2,
                                     addr_t &count2, int inc2) {
  fifo_st_flush_conv_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}

// AIE2PS-LABEL: define dso_local void @_Z18test_fifo_st_resetPU3AS816v64mx6_unaligned6v64mx6RS1_RDv32_iRi(
// AIE2PS-SAME: ptr addrspace(8) [[P:%.*]], [[STRUCT_V64MX6:%.*]] [[V_COERCE:%.*]], ptr nonnull writeonly align 4 captures(none) dereferenceable(4) initializes((0, 3)) [[P_O:%.*]], ptr nonnull writeonly align 64 captures(none) dereferenceable(128) initializes((0, 128)) [[FIFO_O:%.*]], ptr nonnull writeonly align 4 captures(none) dereferenceable(4) initializes((0, 4)) [[POS_O:%.*]]) local_unnamed_addr #[[ATTR6]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64MX6]] [[V_COERCE]], 0
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64MX6]] [[V_COERCE]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64MX6]] [[V_COERCE]], 2
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64MX6]] [[V_COERCE]], 3
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.BFP384.p8.p8(ptr addrspace(8) [[P]], <32 x i32> undef, i32 0, <8 x i32> [[TMP0]], <2 x i32> [[TMP1]], i32 [[TMP2]], i32 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS_O]], align 4
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP5]], ptr [[P_O]], align 4, !tbaa [[TBAA63:![0-9]+]]
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[FIFO_O]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_reset(v64mx6_unaligned __aie_dm_resource_d *p, v64mx6 v,
                        v64mx6_unaligned __aie_dm_resource_d *&p_o,
                        sparse_fifo_t &fifo_o, int &pos_o) {
  fifo_st_reset(p, v, p_o, fifo_o, pos_o);
}
// AIE2PS-LABEL: define dso_local void @_Z18test_fifo_st_resetRPU3AS816v64mx6_unaligned6v64mx6R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], [[STRUCT_V64MX6:%.*]] [[V_COERCE:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) initializes((128, 132)) [[S:%.*]]) local_unnamed_addr #[[ATTR7]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64MX6]] [[V_COERCE]], 0
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64MX6]] [[V_COERCE]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64MX6]] [[V_COERCE]], 2
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64MX6]] [[V_COERCE]], 3
// AIE2PS-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP4:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP5:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.BFP384.p8.p8(ptr addrspace(8) [[TMP4]], <32 x i32> [[TMP5]], i32 0, <8 x i32> [[TMP0]], <2 x i32> [[TMP1]], i32 [[TMP2]], i32 [[TMP3]])
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP6]], 0
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP6]], 1
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP6]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP8]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP9]], ptr [[POS_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP7]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_reset(v64mx6_unaligned __aie_dm_resource_d *&p, v64mx6 v,
                        fifo_state_t &s) {
  fifo_st_reset(p, v, s);
}
// AIE2PS-LABEL: define dso_local void @_Z17test_fifo_st_pushRPU3AS816v64mx6_unaligned6v64mx6R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], [[STRUCT_V64MX6:%.*]] [[V_COERCE:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR7]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64MX6]] [[V_COERCE]], 0
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64MX6]] [[V_COERCE]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V64MX6]] [[V_COERCE]], 2
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V64MX6]] [[V_COERCE]], 3
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP4:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP5:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP7:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.BFP384.p8.p8(ptr addrspace(8) [[TMP4]], <32 x i32> [[TMP5]], i32 [[TMP6]], <8 x i32> [[TMP0]], <2 x i32> [[TMP1]], i32 [[TMP2]], i32 [[TMP3]])
// AIE2PS-NEXT:    [[TMP8:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP7]], 0
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP7]], 1
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP7]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP9]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP10]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP8]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_push(v64mx6_unaligned __aie_dm_resource_d *&p, v64mx6 v,
                       fifo_state_t &s) {
  fifo_st_push(p, v, s);
}
// AIE2PS-LABEL: define dso_local void @_Z18test_fifo_st_flushRPU3AS816v64mx6_unalignedR12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush(v64mx6_unaligned __aie_dm_resource_d *&p,
                        fifo_state_t &s) {
  fifo_st_flush(p, s);
}
// AIE2PS-LABEL: define dso_local void @_Z26test_fifo_st_flush_1d_byteRPU3AS816v64mx6_unalignedR12fifo_state_ti(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_1d_byte(v64mx6_unaligned __aie_dm_resource_d *&p,
                                fifo_state_t &s, int off) {
  fifo_st_flush_1d_byte(p, s, off);
}
// AIE2PS-LABEL: define dso_local void @_Z26test_fifo_st_flush_2d_byteRPU3AS816v64mx6_unalignedR12fifo_state_tiiRii(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_2d_byte(v64mx6_unaligned __aie_dm_resource_d *&p,
                                fifo_state_t &s, int off, int size1,
                                addr_t &count1, int inc1) {
  fifo_st_flush_2d_byte(p, s, off, size1, count1, inc1);
}
// AIE2PS-LABEL: define dso_local void @_Z26test_fifo_st_flush_3d_byteRPU3AS816v64mx6_unalignedR12fifo_state_tiiRiiiS5_i(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]], i32 noundef [[SIZE2:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT2:%.*]], i32 noundef [[INC2:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_3d_byte(v64mx6_unaligned __aie_dm_resource_d *&p,
                                fifo_state_t &s, int off, int size1,
                                addr_t &count1, int inc1, int size2,
                                addr_t &count2, int inc2) {
  fifo_st_flush_3d_byte(p, s, off, size1, count1, inc1, size2, count2, inc2);
}
// AIE2PS-LABEL: define dso_local void @_Z23test_fifo_st_flush_bareRPU3AS816v64mx6_unalignedR12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare(v64mx6_unaligned __aie_dm_resource_d *&p,
                             fifo_state_t &s) {
  fifo_st_flush_bare(p, s);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_bare_1d_byteRPU3AS816v64mx6_unalignedR12fifo_state_ti(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_1d_byte(v64mx6_unaligned __aie_dm_resource_d *&p,
                                     fifo_state_t &s, int off) {
  fifo_st_flush_bare_1d_byte(p, s, off);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_bare_2d_byteRPU3AS816v64mx6_unalignedR12fifo_state_tiiRii(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_2d_byte(v64mx6_unaligned __aie_dm_resource_d *&p,
                                     fifo_state_t &s, int off, int size1,
                                     addr_t &count1, int inc1) {
  fifo_st_flush_bare_2d_byte(p, s, off, size1, count1, inc1);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_bare_3d_byteRPU3AS816v64mx6_unalignedR12fifo_state_tiiRiiiS5_i(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]], i32 noundef [[SIZE2:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT2:%.*]], i32 noundef [[INC2:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_3d_byte(v64mx6_unaligned __aie_dm_resource_d *&p,
                                     fifo_state_t &s, int off, int size1,
                                     addr_t &count1, int inc1, int size2,
                                     addr_t &count2, int inc2) {
  fifo_st_flush_bare_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}
// AIE2PS-LABEL: define dso_local void @_Z23test_fifo_st_flush_convRPU3AS816v64mx6_unalignedR12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.conv.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv(v64mx6_unaligned __aie_dm_resource_d *&p,
                             fifo_state_t &s) {
  fifo_st_flush_conv(p, s);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_conv_1d_byteRPU3AS816v64mx6_unalignedR12fifo_state_ti(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.conv.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_1d_byte(v64mx6_unaligned __aie_dm_resource_d *&p,
                                     fifo_state_t &s, int off) {
  fifo_st_flush_conv_1d_byte(p, s, off);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_conv_2d_byteRPU3AS816v64mx6_unalignedR12fifo_state_tiiRii(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.conv.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_2d_byte(v64mx6_unaligned __aie_dm_resource_d *&p,
                                     fifo_state_t &s, int off, int size1,
                                     addr_t &count1, int inc1) {
  fifo_st_flush_conv_2d_byte(p, s, off, size1, count1, inc1);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_conv_3d_byteRPU3AS816v64mx6_unalignedR12fifo_state_tiiRiiiS5_i(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]], i32 noundef [[SIZE2:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT2:%.*]], i32 noundef [[INC2:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.conv.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_3d_byte(v64mx6_unaligned __aie_dm_resource_d *&p,
                                     fifo_state_t &s, int off, int size1,
                                     addr_t &count1, int inc1, int size2,
                                     addr_t &count2, int inc2) {
  fifo_st_flush_conv_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}

// AIE2PS-LABEL: define dso_local void @_Z18test_fifo_st_resetPU3AS817v128mx4_unaligned7v128mx4RS1_RDv32_iRi(
// AIE2PS-SAME: ptr addrspace(8) [[P:%.*]], [[STRUCT_V128MX4:%.*]] [[V_COERCE:%.*]], ptr nonnull writeonly align 4 captures(none) dereferenceable(4) initializes((0, 3)) [[P_O:%.*]], ptr nonnull writeonly align 64 captures(none) dereferenceable(128) initializes((0, 128)) [[FIFO_O:%.*]], ptr nonnull writeonly align 4 captures(none) dereferenceable(4) initializes((0, 4)) [[POS_O:%.*]]) local_unnamed_addr #[[ATTR6]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V_COERCE]], 0
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V_COERCE]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V_COERCE]], 2
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V_COERCE]], 3
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V_COERCE]], 4
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V_COERCE]], 5
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V_COERCE]], 6
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V_COERCE]], 7
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.BFP768.p8.p8(ptr addrspace(8) [[P]], <32 x i32> undef, i32 0, <8 x i32> [[TMP0]], <8 x i32> [[TMP1]], <2 x i32> [[TMP2]], <2 x i32> [[TMP3]], i32 [[TMP4]], i32 [[TMP5]], i32 [[TMP6]], i32 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP8]], 2
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS_O]], align 4
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP9]], ptr [[P_O]], align 4, !tbaa [[TBAA65:![0-9]+]]
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[FIFO_O]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_reset(v128mx4_unaligned __aie_dm_resource_d *p, v128mx4 v,
                        v128mx4_unaligned __aie_dm_resource_d *&p_o,
                        sparse_fifo_t &fifo_o, int &pos_o) {
  fifo_st_reset(p, v, p_o, fifo_o, pos_o);
}
// AIE2PS-LABEL: define dso_local void @_Z18test_fifo_st_resetRPU3AS817v128mx4_unaligned7v128mx4R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], [[STRUCT_V128MX4:%.*]] [[V_COERCE:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) initializes((128, 132)) [[S:%.*]]) local_unnamed_addr #[[ATTR7]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V_COERCE]], 0
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V_COERCE]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V_COERCE]], 2
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V_COERCE]], 3
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V_COERCE]], 4
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V_COERCE]], 5
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V_COERCE]], 6
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V_COERCE]], 7
// AIE2PS-NEXT:    [[POS_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    store i32 0, ptr [[POS_I]], align 64, !tbaa [[TBAA2]]
// AIE2PS-NEXT:    [[TMP8:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP9:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.BFP768.p8.p8(ptr addrspace(8) [[TMP8]], <32 x i32> [[TMP9]], i32 0, <8 x i32> [[TMP0]], <8 x i32> [[TMP1]], <2 x i32> [[TMP2]], <2 x i32> [[TMP3]], i32 [[TMP4]], i32 [[TMP5]], i32 [[TMP6]], i32 [[TMP7]])
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP10]], 0
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP10]], 1
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP10]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP12]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[POS_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP11]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_reset(v128mx4_unaligned __aie_dm_resource_d *&p, v128mx4 v,
                        fifo_state_t &s) {
  fifo_st_reset(p, v, s);
}
// AIE2PS-LABEL: define dso_local void @_Z17test_fifo_st_pushRPU3AS817v128mx4_unaligned7v128mx4R12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], [[STRUCT_V128MX4:%.*]] [[V_COERCE:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR7]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V_COERCE]], 0
// AIE2PS-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V_COERCE]], 1
// AIE2PS-NEXT:    [[TMP2:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V_COERCE]], 2
// AIE2PS-NEXT:    [[TMP3:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V_COERCE]], 3
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V_COERCE]], 4
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V_COERCE]], 5
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V_COERCE]], 6
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue [[STRUCT_V128MX4]] [[V_COERCE]], 7
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP8:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP9:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP11:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32 } @llvm.aie2ps.fifo.st.push.BFP768.p8.p8(ptr addrspace(8) [[TMP8]], <32 x i32> [[TMP9]], i32 [[TMP10]], <8 x i32> [[TMP0]], <8 x i32> [[TMP1]], <2 x i32> [[TMP2]], <2 x i32> [[TMP3]], i32 [[TMP4]], i32 [[TMP5]], i32 [[TMP6]], i32 [[TMP7]])
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP11]], 0
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP11]], 1
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP11]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP13]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP14]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP12]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_push(v128mx4_unaligned __aie_dm_resource_d *&p, v128mx4 v,
                       fifo_state_t &s) {
  fifo_st_push(p, v, s);
}
// AIE2PS-LABEL: define dso_local void @_Z18test_fifo_st_flushRPU3AS817v128mx4_unalignedR12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush(v128mx4_unaligned __aie_dm_resource_d *&p,
                        fifo_state_t &s) {
  fifo_st_flush(p, s);
}
// AIE2PS-LABEL: define dso_local void @_Z26test_fifo_st_flush_1d_byteRPU3AS817v128mx4_unalignedR12fifo_state_ti(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_1d_byte(v128mx4_unaligned __aie_dm_resource_d *&p,
                                fifo_state_t &s, int off) {
  fifo_st_flush_1d_byte(p, s, off);
}
// AIE2PS-LABEL: define dso_local void @_Z26test_fifo_st_flush_2d_byteRPU3AS817v128mx4_unalignedR12fifo_state_tiiRii(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_2d_byte(v128mx4_unaligned __aie_dm_resource_d *&p,
                                fifo_state_t &s, int off, int size1,
                                addr_t &count1, int inc1) {
  fifo_st_flush_2d_byte(p, s, off, size1, count1, inc1);
}
// AIE2PS-LABEL: define dso_local void @_Z26test_fifo_st_flush_3d_byteRPU3AS817v128mx4_unalignedR12fifo_state_tiiRiiiS5_i(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]], i32 noundef [[SIZE2:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT2:%.*]], i32 noundef [[INC2:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_3d_byte(v128mx4_unaligned __aie_dm_resource_d *&p,
                                fifo_state_t &s, int off, int size1,
                                addr_t &count1, int inc1, int size2,
                                addr_t &count2, int inc2) {
  fifo_st_flush_3d_byte(p, s, off, size1, count1, inc1, size2, count2, inc2);
}
// AIE2PS-LABEL: define dso_local void @_Z23test_fifo_st_flush_bareRPU3AS817v128mx4_unalignedR12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare(v128mx4_unaligned __aie_dm_resource_d *&p,
                             fifo_state_t &s) {
  fifo_st_flush_bare(p, s);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_bare_1d_byteRPU3AS817v128mx4_unalignedR12fifo_state_ti(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_1d_byte(v128mx4_unaligned __aie_dm_resource_d *&p,
                                     fifo_state_t &s, int off) {
  fifo_st_flush_bare_1d_byte(p, s, off);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_bare_2d_byteRPU3AS817v128mx4_unalignedR12fifo_state_tiiRii(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_2d_byte(v128mx4_unaligned __aie_dm_resource_d *&p,
                                     fifo_state_t &s, int off, int size1,
                                     addr_t &count1, int inc1) {
  fifo_st_flush_bare_2d_byte(p, s, off, size1, count1, inc1);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_bare_3d_byteRPU3AS817v128mx4_unalignedR12fifo_state_tiiRiiiS5_i(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]], i32 noundef [[SIZE2:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT2:%.*]], i32 noundef [[INC2:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_bare_3d_byte(v128mx4_unaligned __aie_dm_resource_d *&p,
                                     fifo_state_t &s, int off, int size1,
                                     addr_t &count1, int inc1, int size2,
                                     addr_t &count2, int inc2) {
  fifo_st_flush_bare_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}
// AIE2PS-LABEL: define dso_local void @_Z23test_fifo_st_flush_convRPU3AS817v128mx4_unalignedR12fifo_state_t(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.conv.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]])
// AIE2PS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP3]], 0
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP3]], 1
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP3]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP5]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP6]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP4]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv(v128mx4_unaligned __aie_dm_resource_d *&p,
                             fifo_state_t &s) {
  fifo_st_flush_conv(p, s);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_conv_1d_byteRPU3AS817v128mx4_unalignedR12fifo_state_ti(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32 } @llvm.aie2ps.fifo.st.flush.1d.conv.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]])
// AIE2PS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP4]], 0
// AIE2PS-NEXT:    [[TMP6:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP4]], 1
// AIE2PS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32 } [[TMP4]], 2
// AIE2PS-NEXT:    store <32 x i32> [[TMP6]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP7]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP5]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_1d_byte(v128mx4_unaligned __aie_dm_resource_d *&p,
                                     fifo_state_t &s, int off) {
  fifo_st_flush_conv_1d_byte(p, s, off);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_conv_2d_byteRPU3AS817v128mx4_unalignedR12fifo_state_tiiRii(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32, i20 } @llvm.aie2ps.fifo.st.flush.2d.conv.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]])
// AIE2PS-NEXT:    [[TMP9:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 0
// AIE2PS-NEXT:    [[TMP10:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 1
// AIE2PS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 2
// AIE2PS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20 } [[TMP8]], 3
// AIE2PS-NEXT:    [[TMP13:%.*]] = zext i20 [[TMP12]] to i32
// AIE2PS-NEXT:    store i32 [[TMP13]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP10]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP11]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP9]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_2d_byte(v128mx4_unaligned __aie_dm_resource_d *&p,
                                     fifo_state_t &s, int off, int size1,
                                     addr_t &count1, int inc1) {
  fifo_st_flush_conv_2d_byte(p, s, off, size1, count1, inc1);
}
// AIE2PS-LABEL: define dso_local void @_Z31test_fifo_st_flush_conv_3d_byteRPU3AS817v128mx4_unalignedR12fifo_state_tiiRiiiS5_i(
// AIE2PS-SAME: ptr nonnull align 4 captures(none) dereferenceable(4) [[P:%.*]], ptr nonnull align 64 captures(none) dereferenceable(256) [[S:%.*]], i32 noundef [[OFF:%.*]], i32 noundef [[SIZE1:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT1:%.*]], i32 noundef [[INC1:%.*]], i32 noundef [[SIZE2:%.*]], ptr nonnull align 4 captures(none) dereferenceable(4) [[COUNT2:%.*]], i32 noundef [[INC2:%.*]]) local_unnamed_addr #[[ATTR5]] {
// AIE2PS-NEXT:  entry:
// AIE2PS-NEXT:    [[POS1_I:%.*]] = getelementptr inbounds nuw i8, ptr [[S]], i20 128
// AIE2PS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(8), ptr [[P]], align 4, !tbaa [[TBAA7]]
// AIE2PS-NEXT:    [[TMP1:%.*]] = load <32 x i32>, ptr [[S]], align 64, !tbaa [[TBAA10]]
// AIE2PS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[POS1_I]], align 64, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP3:%.*]] = trunc i32 [[OFF]] to i20
// AIE2PS-NEXT:    [[TMP4:%.*]] = trunc i32 [[SIZE1]] to i20
// AIE2PS-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT1]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i20
// AIE2PS-NEXT:    [[TMP7:%.*]] = trunc i32 [[INC1]] to i20
// AIE2PS-NEXT:    [[TMP8:%.*]] = trunc i32 [[SIZE2]] to i20
// AIE2PS-NEXT:    [[TMP9:%.*]] = load i32, ptr [[COUNT2]], align 4, !tbaa [[TBAA11]]
// AIE2PS-NEXT:    [[TMP10:%.*]] = trunc i32 [[TMP9]] to i20
// AIE2PS-NEXT:    [[TMP11:%.*]] = trunc i32 [[INC2]] to i20
// AIE2PS-NEXT:    [[TMP12:%.*]] = tail call { ptr addrspace(8), <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.st.flush.3d.conv.p8.p8(ptr addrspace(8) [[TMP0]], <32 x i32> [[TMP1]], i32 [[TMP2]], i20 [[TMP3]], i20 [[TMP4]], i20 [[TMP6]], i20 [[TMP7]], i20 [[TMP8]], i20 [[TMP10]], i20 [[TMP11]])
// AIE2PS-NEXT:    [[TMP13:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 0
// AIE2PS-NEXT:    [[TMP14:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 1
// AIE2PS-NEXT:    [[TMP15:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 2
// AIE2PS-NEXT:    [[TMP16:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 3
// AIE2PS-NEXT:    [[TMP17:%.*]] = zext i20 [[TMP16]] to i32
// AIE2PS-NEXT:    [[TMP18:%.*]] = extractvalue { ptr addrspace(8), <32 x i32>, i32, i20, i20 } [[TMP12]], 4
// AIE2PS-NEXT:    [[TMP19:%.*]] = zext i20 [[TMP18]] to i32
// AIE2PS-NEXT:    store i32 [[TMP17]], ptr [[COUNT1]], align 4
// AIE2PS-NEXT:    store i32 [[TMP19]], ptr [[COUNT2]], align 4
// AIE2PS-NEXT:    store <32 x i32> [[TMP14]], ptr [[S]], align 128
// AIE2PS-NEXT:    store i32 [[TMP15]], ptr [[POS1_I]], align 64
// AIE2PS-NEXT:    store ptr addrspace(8) [[TMP13]], ptr [[P]], align 4
// AIE2PS-NEXT:    ret void
//
void test_fifo_st_flush_conv_3d_byte(v128mx4_unaligned __aie_dm_resource_d *&p,
                                     fifo_state_t &s, int off, int size1,
                                     addr_t &count1, int inc1, int size2,
                                     addr_t &count2, int inc2) {
  fifo_st_flush_conv_3d_byte(p, s, off, size1, count1, inc1, size2, count2,
                             inc2);
}
//.
// AIE2PS: [[TBAA2]] = !{[[META3:![0-9]+]], [[META6:![0-9]+]], i64 128}
// AIE2PS: [[META3]] = !{!"_ZTS12fifo_state_t", [[META4:![0-9]+]], i64 0, [[META6]], i64 128, [[META4]], i64 192}
// AIE2PS: [[META4]] = !{!"omnipotent char", [[META5:![0-9]+]], i64 0}
// AIE2PS: [[META5]] = !{!"Simple C++ TBAA"}
// AIE2PS: [[META6]] = !{!"int", [[META4]], i64 0}
// AIE2PS: [[TBAA7]] = !{[[META8:![0-9]+]], [[META8]], i64 0}
// AIE2PS: [[META8]] = !{!"p1 void", [[META9:![0-9]+]], i64 0}
// AIE2PS: [[META9]] = !{!"any pointer", [[META4]], i64 0}
// AIE2PS: [[TBAA10]] = !{[[META4]], [[META4]], i64 0}
// AIE2PS: [[TBAA11]] = !{[[META6]], [[META6]], i64 0}
// AIE2PS: [[META12]] = !{[[META13:![0-9]+]]}
// AIE2PS: [[META13]] = distinct !{[[META13]], [[META14:![0-9]+]], !"_ZL11fifo_ld_popRrPU3AS59v64float8R12fifo_state_t: %agg.result"}
// AIE2PS: [[META14]] = distinct !{[[META14]], !"_ZL11fifo_ld_popRrPU3AS59v64float8R12fifo_state_t"}
// AIE2PS: [[META15]] = !{[[META16:![0-9]+]]}
// AIE2PS: [[META16]] = distinct !{[[META16]], [[META17:![0-9]+]], !"_ZL19fifo_ld_pop_1d_byteRrPU3AS59v64float8R12fifo_state_ti: %agg.result"}
// AIE2PS: [[META17]] = distinct !{[[META17]], !"_ZL19fifo_ld_pop_1d_byteRrPU3AS59v64float8R12fifo_state_ti"}
// AIE2PS: [[META18]] = !{[[META19:![0-9]+]]}
// AIE2PS: [[META19]] = distinct !{[[META19]], [[META20:![0-9]+]], !"_ZL19fifo_ld_pop_2d_byteRrPU3AS59v64float8R12fifo_state_tiiRii: %agg.result"}
// AIE2PS: [[META20]] = distinct !{[[META20]], !"_ZL19fifo_ld_pop_2d_byteRrPU3AS59v64float8R12fifo_state_tiiRii"}
// AIE2PS: [[META21]] = !{[[META22:![0-9]+]]}
// AIE2PS: [[META22]] = distinct !{[[META22]], [[META23:![0-9]+]], !"_ZL19fifo_ld_pop_3d_byteRrPU3AS59v64float8R12fifo_state_tiiRiiiS6_i: %agg.result"}
// AIE2PS: [[META23]] = distinct !{[[META23]], !"_ZL19fifo_ld_pop_3d_byteRrPU3AS59v64float8R12fifo_state_tiiRiiiS6_i"}
// AIE2PS: [[META24]] = !{[[META25:![0-9]+]]}
// AIE2PS: [[META25]] = distinct !{[[META25]], [[META26:![0-9]+]], !"_ZL12fifo_ld_popxRrP9v64float8R12fifo_state_tii: %agg.result"}
// AIE2PS: [[META26]] = distinct !{[[META26]], !"_ZL12fifo_ld_popxRrP9v64float8R12fifo_state_tii"}
// AIE2PS: [[META27]] = !{[[META28:![0-9]+]]}
// AIE2PS: [[META28]] = distinct !{[[META28]], [[META29:![0-9]+]], !"_ZL12fifo_ld_popxRrP9v64float8R12fifo_state_t: %agg.result"}
// AIE2PS: [[META29]] = distinct !{[[META29]], !"_ZL12fifo_ld_popxRrP9v64float8R12fifo_state_t"}
// AIE2PS: [[META30]] = !{[[META31:![0-9]+]]}
// AIE2PS: [[META31]] = distinct !{[[META31]], [[META32:![0-9]+]], !"_ZL12fifo_ld_popxRrP9v64float8R12fifo_state_tii: %agg.result"}
// AIE2PS: [[META32]] = distinct !{[[META32]], !"_ZL12fifo_ld_popxRrP9v64float8R12fifo_state_tii"}
// AIE2PS: [[META33]] = !{[[META31]], [[META28]]}
// AIE2PS: [[META34]] = !{[[META35:![0-9]+]]}
// AIE2PS: [[META35]] = distinct !{[[META35]], [[META36:![0-9]+]], !"_ZL11fifo_ld_popRPU3AS510v64bfloat8R12fifo_state_t: %agg.result"}
// AIE2PS: [[META36]] = distinct !{[[META36]], !"_ZL11fifo_ld_popRPU3AS510v64bfloat8R12fifo_state_t"}
// AIE2PS: [[META37]] = !{[[META38:![0-9]+]]}
// AIE2PS: [[META38]] = distinct !{[[META38]], [[META39:![0-9]+]], !"_ZL19fifo_ld_pop_1d_byteRPU3AS510v64bfloat8R12fifo_state_ti: %agg.result"}
// AIE2PS: [[META39]] = distinct !{[[META39]], !"_ZL19fifo_ld_pop_1d_byteRPU3AS510v64bfloat8R12fifo_state_ti"}
// AIE2PS: [[META40]] = !{[[META41:![0-9]+]]}
// AIE2PS: [[META41]] = distinct !{[[META41]], [[META42:![0-9]+]], !"_ZL19fifo_ld_pop_2d_byteRPU3AS510v64bfloat8R12fifo_state_tiiRii: %agg.result"}
// AIE2PS: [[META42]] = distinct !{[[META42]], !"_ZL19fifo_ld_pop_2d_byteRPU3AS510v64bfloat8R12fifo_state_tiiRii"}
// AIE2PS: [[META43]] = !{[[META44:![0-9]+]]}
// AIE2PS: [[META44]] = distinct !{[[META44]], [[META45:![0-9]+]], !"_ZL19fifo_ld_pop_3d_byteRPU3AS510v64bfloat8R12fifo_state_tiiRiiiS5_i: %agg.result"}
// AIE2PS: [[META45]] = distinct !{[[META45]], !"_ZL19fifo_ld_pop_3d_byteRPU3AS510v64bfloat8R12fifo_state_tiiRiiiS5_i"}
// AIE2PS: [[META46]] = !{[[META47:![0-9]+]]}
// AIE2PS: [[META47]] = distinct !{[[META47]], [[META48:![0-9]+]], !"_ZL12fifo_ld_popxRP10v64bfloat8R12fifo_state_tii: %agg.result"}
// AIE2PS: [[META48]] = distinct !{[[META48]], !"_ZL12fifo_ld_popxRP10v64bfloat8R12fifo_state_tii"}
// AIE2PS: [[META49]] = !{[[META50:![0-9]+]]}
// AIE2PS: [[META50]] = distinct !{[[META50]], [[META51:![0-9]+]], !"_ZL12fifo_ld_popxRP10v64bfloat8R12fifo_state_t: %agg.result"}
// AIE2PS: [[META51]] = distinct !{[[META51]], !"_ZL12fifo_ld_popxRP10v64bfloat8R12fifo_state_t"}
// AIE2PS: [[META52]] = !{[[META53:![0-9]+]]}
// AIE2PS: [[META53]] = distinct !{[[META53]], [[META54:![0-9]+]], !"_ZL12fifo_ld_popxRP10v64bfloat8R12fifo_state_tii: %agg.result"}
// AIE2PS: [[META54]] = distinct !{[[META54]], !"_ZL12fifo_ld_popxRP10v64bfloat8R12fifo_state_tii"}
// AIE2PS: [[META55]] = !{[[META53]], [[META50]]}
// AIE2PS: [[TBAA56]] = !{[[META57:![0-9]+]], [[META57]], i64 0}
// AIE2PS: [[META57]] = !{!"p1 _ZTS10v64bfloat8", [[META9]], i64 0}
// AIE2PS: [[TBAA58]] = !{[[META59:![0-9]+]], [[META59]], i64 0}
// AIE2PS: [[META59]] = !{!"p1 _ZTS9v64float8", [[META9]], i64 0}
// AIE2PS: [[TBAA60]] = !{[[META9]], [[META9]], i64 0}
// AIE2PS: [[TBAA61]] = !{[[META62:![0-9]+]], [[META62]], i64 0}
// AIE2PS: [[META62]] = !{!"p1 _ZTS16v64mx9_unaligned", [[META9]], i64 0}
// AIE2PS: [[TBAA63]] = !{[[META64:![0-9]+]], [[META64]], i64 0}
// AIE2PS: [[META64]] = !{!"p1 _ZTS16v64mx6_unaligned", [[META9]], i64 0}
// AIE2PS: [[TBAA65]] = !{[[META66:![0-9]+]], [[META66]], i64 0}
// AIE2PS: [[META66]] = !{!"p1 _ZTS17v128mx4_unaligned", [[META9]], i64 0}
//.
