// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
//===- aie2p-vadd-intrinsics.cpp --------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//
// RUN: %clang -O2 %s --target=aie2ps -nostdlibinc -S -emit-llvm -o - | FileCheck %s -check-prefix=CHECK-COMMON -check-prefix=AIE2PS
//

//

//

v64bfloat8
// CHECK-COMMON-LABEL: @_Z22test_min_ge_v64bfloat810v64bfloat8S_Ry(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-COMMON-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFLOAT8]] [[B_COERCE:%.*]], 0
// CHECK-COMMON-NEXT:    [[TMP2:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vmin.gebfloat8(<64 x i8> [[TMP0]], <64 x i8> [[TMP1]])
// CHECK-COMMON-NEXT:    [[TMP3:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP2]], 1
// CHECK-COMMON-NEXT:    store <2 x i32> [[TMP3]], ptr [[CMP:%.*]], align 8
// CHECK-COMMON-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP2]], 0
// CHECK-COMMON-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFLOAT8]] poison, <64 x i8> [[TMP4]], 0
// CHECK-COMMON-NEXT:    ret [[STRUCT_V64BFLOAT8]] [[DOTFCA_0_INSERT_I]]
//
test_min_ge_v64bfloat8(v64bfloat8 a, v64bfloat8 b, unsigned long long &cmp) {
  return min_ge(a, b, cmp);
}
v64bfloat8
// CHECK-COMMON-LABEL: @_Z22test_max_lt_v64bfloat810v64bfloat8S_Ry(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-COMMON-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFLOAT8]] [[B_COERCE:%.*]], 0
// CHECK-COMMON-NEXT:    [[TMP2:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vmax.ltbfloat8(<64 x i8> [[TMP0]], <64 x i8> [[TMP1]])
// CHECK-COMMON-NEXT:    [[TMP3:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP2]], 1
// CHECK-COMMON-NEXT:    store <2 x i32> [[TMP3]], ptr [[CMP:%.*]], align 8
// CHECK-COMMON-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP2]], 0
// CHECK-COMMON-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFLOAT8]] poison, <64 x i8> [[TMP4]], 0
// CHECK-COMMON-NEXT:    ret [[STRUCT_V64BFLOAT8]] [[DOTFCA_0_INSERT_I]]
//
test_max_lt_v64bfloat8(v64bfloat8 a, v64bfloat8 b, unsigned long long &cmp) {
  return max_lt(a, b, cmp);
}
// CHECK-COMMON-LABEL: @_Z20test_band_v64bfloat810v64bfloat8S_(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-COMMON-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFLOAT8]] [[B_COERCE:%.*]], 0
// CHECK-COMMON-NEXT:    [[AND_I:%.*]] = and <64 x i8> [[TMP1]], [[TMP0]]
// CHECK-COMMON-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFLOAT8]] poison, <64 x i8> [[AND_I]], 0
// CHECK-COMMON-NEXT:    ret [[STRUCT_V64BFLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v64bfloat8 test_band_v64bfloat8(v64bfloat8 a, v64bfloat8 b) {
  return band(a, b);
}
// CHECK-COMMON-LABEL: @_Z19test_bor_v64bfloat810v64bfloat8S_(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-COMMON-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFLOAT8]] [[B_COERCE:%.*]], 0
// CHECK-COMMON-NEXT:    [[OR_I:%.*]] = or <64 x i8> [[TMP1]], [[TMP0]]
// CHECK-COMMON-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFLOAT8]] poison, <64 x i8> [[OR_I]], 0
// CHECK-COMMON-NEXT:    ret [[STRUCT_V64BFLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v64bfloat8 test_bor_v64bfloat8(v64bfloat8 a, v64bfloat8 b) {
  return bor(a, b);
}
// CHECK-COMMON-LABEL: @_Z19test_abs_v64bfloat810v64bfloat8(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-COMMON-NEXT:    [[AND_I_I:%.*]] = and <64 x i8> [[TMP0]], splat (i8 127)
// CHECK-COMMON-NEXT:    [[DOTFCA_0_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64BFLOAT8]] poison, <64 x i8> [[AND_I_I]], 0
// CHECK-COMMON-NEXT:    ret [[STRUCT_V64BFLOAT8]] [[DOTFCA_0_INSERT_I_I]]
//
v64bfloat8 test_abs_v64bfloat8(v64bfloat8 a) {
  return abs(a);
}
unsigned long long
// CHECK-COMMON-LABEL: @_Z18test_lt_v64bfloat810v64bfloat8S_(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-COMMON-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFLOAT8]] [[B_COERCE:%.*]], 0
// CHECK-COMMON-NEXT:    [[TMP2:%.*]] = tail call <2 x i32> @llvm.aie2ps.vltbfloat8(<64 x i8> [[TMP0]], <64 x i8> [[TMP1]])
// CHECK-COMMON-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// CHECK-COMMON-NEXT:    ret i64 [[TMP3]]
//
test_lt_v64bfloat8(v64bfloat8 a, v64bfloat8 b) {
  return lt(a, b);
}
unsigned long long
// CHECK-COMMON-LABEL: @_Z18test_ge_v64bfloat810v64bfloat8S_(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-COMMON-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFLOAT8]] [[B_COERCE:%.*]], 0
// CHECK-COMMON-NEXT:    [[TMP2:%.*]] = tail call <2 x i32> @llvm.aie2ps.vgebfloat8(<64 x i8> [[TMP0]], <64 x i8> [[TMP1]])
// CHECK-COMMON-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// CHECK-COMMON-NEXT:    ret i64 [[TMP3]]
//
test_ge_v64bfloat8(v64bfloat8 a, v64bfloat8 b) {
  return ge(a, b);
}
// CHECK-COMMON-LABEL: @_Z19test_eqz_v64bfloat810v64bfloat8(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-COMMON-NEXT:    [[AND_I_I_I:%.*]] = and <64 x i8> [[TMP0]], splat (i8 127)
// CHECK-COMMON-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.aie2ps.veqz8(<64 x i8> [[AND_I_I_I]])
// CHECK-COMMON-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to i64
// CHECK-COMMON-NEXT:    ret i64 [[TMP2]]
//
unsigned long long test_eqz_v64bfloat8(v64bfloat8 a) {
  return eqz(a);
}
// CHECK-COMMON-LABEL: @_Z19test_sel_v64bfloat810v64bfloat8S_y(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-COMMON-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64BFLOAT8]] [[B_COERCE:%.*]], 0
// CHECK-COMMON-NEXT:    [[TMP2:%.*]] = bitcast i64 [[S:%.*]] to <2 x i32>
// CHECK-COMMON-NEXT:    [[TMP3:%.*]] = tail call <64 x i8> @llvm.aie2ps.vsel8(<64 x i8> [[TMP0]], <64 x i8> [[TMP1]], <2 x i32> [[TMP2]])
// CHECK-COMMON-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFLOAT8]] poison, <64 x i8> [[TMP3]], 0
// CHECK-COMMON-NEXT:    ret [[STRUCT_V64BFLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v64bfloat8 test_sel_v64bfloat8(v64bfloat8 a, v64bfloat8 b, unsigned long long s) {
  return sel(a, b, s);
}
//
//
//
v64float8
// CHECK-COMMON-LABEL: @_Z21test_min_ge_v64float89v64float8S_Ry(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64FLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-COMMON-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64FLOAT8]] [[B_COERCE:%.*]], 0
// CHECK-COMMON-NEXT:    [[TMP2:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vmin.gefloat8(<64 x i8> [[TMP0]], <64 x i8> [[TMP1]])
// CHECK-COMMON-NEXT:    [[TMP3:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP2]], 1
// CHECK-COMMON-NEXT:    store <2 x i32> [[TMP3]], ptr [[CMP:%.*]], align 8
// CHECK-COMMON-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP2]], 0
// CHECK-COMMON-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64FLOAT8]] poison, <64 x i8> [[TMP4]], 0
// CHECK-COMMON-NEXT:    ret [[STRUCT_V64FLOAT8]] [[DOTFCA_0_INSERT_I]]
//
test_min_ge_v64float8(v64float8 a, v64float8 b, unsigned long long &cmp) {
  return min_ge(a, b, cmp);
}
v64float8
// CHECK-COMMON-LABEL: @_Z21test_max_lt_v64float89v64float8S_Ry(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64FLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-COMMON-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64FLOAT8]] [[B_COERCE:%.*]], 0
// CHECK-COMMON-NEXT:    [[TMP2:%.*]] = tail call { <64 x i8>, <2 x i32> } @llvm.aie2ps.vmax.ltfloat8(<64 x i8> [[TMP0]], <64 x i8> [[TMP1]])
// CHECK-COMMON-NEXT:    [[TMP3:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP2]], 1
// CHECK-COMMON-NEXT:    store <2 x i32> [[TMP3]], ptr [[CMP:%.*]], align 8
// CHECK-COMMON-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, <2 x i32> } [[TMP2]], 0
// CHECK-COMMON-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64FLOAT8]] poison, <64 x i8> [[TMP4]], 0
// CHECK-COMMON-NEXT:    ret [[STRUCT_V64FLOAT8]] [[DOTFCA_0_INSERT_I]]
//
test_max_lt_v64float8(v64float8 a, v64float8 b, unsigned long long &cmp) {
  return max_lt(a, b, cmp);
}

v32bfloat16
// CHECK-COMMON-LABEL: @_Z23test_max_lt_v32bfloat16Dv32_8bfloat16S0_Rj(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[TMP0:%.*]] = tail call { <32 x bfloat>, i32 } @llvm.aie2ps.vmax.ltbfloat16(<32 x bfloat> [[A:%.*]], <32 x bfloat> [[B:%.*]])
// CHECK-COMMON-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x bfloat>, i32 } [[TMP0]], 1
// CHECK-COMMON-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// CHECK-COMMON-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x bfloat>, i32 } [[TMP0]], 0
// CHECK-COMMON-NEXT:    ret <32 x bfloat> [[TMP2]]
//
test_max_lt_v32bfloat16(v32bfloat16 a, v32bfloat16 b, unsigned int &cmp) {
  return max_lt(a, b, cmp);
}

v32float16
// CHECK-COMMON-LABEL: @_Z22test_max_lt_v32float16Dv32_7float16S0_Rj(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[TMP0:%.*]] = tail call { <32 x half>, i32 } @llvm.aie2ps.vmax.ltfloat16(<32 x half> [[A:%.*]], <32 x half> [[B:%.*]])
// CHECK-COMMON-NEXT:    [[TMP1:%.*]] = extractvalue { <32 x half>, i32 } [[TMP0]], 1
// CHECK-COMMON-NEXT:    store i32 [[TMP1]], ptr [[CMP:%.*]], align 4
// CHECK-COMMON-NEXT:    [[TMP2:%.*]] = extractvalue { <32 x half>, i32 } [[TMP0]], 0
// CHECK-COMMON-NEXT:    ret <32 x half> [[TMP2]]
//
test_max_lt_v32float16(v32float16 a, v32float16 b, unsigned int &cmp) {
  return max_lt(a, b, cmp);
}
// CHECK-COMMON-LABEL: @_Z19test_band_v64float89v64float8S_(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64FLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-COMMON-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64FLOAT8]] [[B_COERCE:%.*]], 0
// CHECK-COMMON-NEXT:    [[AND_I:%.*]] = and <64 x i8> [[TMP1]], [[TMP0]]
// CHECK-COMMON-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64FLOAT8]] poison, <64 x i8> [[AND_I]], 0
// CHECK-COMMON-NEXT:    ret [[STRUCT_V64FLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v64float8 test_band_v64float8(v64float8 a, v64float8 b) {
  return band(a, b);
}
// CHECK-COMMON-LABEL: @_Z18test_bor_v64float89v64float8S_(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64FLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-COMMON-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64FLOAT8]] [[B_COERCE:%.*]], 0
// CHECK-COMMON-NEXT:    [[OR_I:%.*]] = or <64 x i8> [[TMP1]], [[TMP0]]
// CHECK-COMMON-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64FLOAT8]] poison, <64 x i8> [[OR_I]], 0
// CHECK-COMMON-NEXT:    ret [[STRUCT_V64FLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v64float8 test_bor_v64float8(v64float8 a, v64float8 b) {
  return bor(a, b);
}
// CHECK-COMMON-LABEL: @_Z18test_abs_v64float89v64float8(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64FLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-COMMON-NEXT:    [[AND_I_I:%.*]] = and <64 x i8> [[TMP0]], splat (i8 127)
// CHECK-COMMON-NEXT:    [[DOTFCA_0_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64FLOAT8]] poison, <64 x i8> [[AND_I_I]], 0
// CHECK-COMMON-NEXT:    ret [[STRUCT_V64FLOAT8]] [[DOTFCA_0_INSERT_I_I]]
//
v64float8 test_abs_v64float8(v64float8 a) {
  return abs(a);
}
unsigned long long
// CHECK-COMMON-LABEL: @_Z17test_lt_v64float89v64float8S_(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64FLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-COMMON-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64FLOAT8]] [[B_COERCE:%.*]], 0
// CHECK-COMMON-NEXT:    [[TMP2:%.*]] = tail call <2 x i32> @llvm.aie2ps.vltfloat8(<64 x i8> [[TMP0]], <64 x i8> [[TMP1]])
// CHECK-COMMON-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// CHECK-COMMON-NEXT:    ret i64 [[TMP3]]
//
test_lt_v64float8(v64float8 a, v64float8 b) {
  return lt(a, b);
}
unsigned long long
// CHECK-COMMON-LABEL: @_Z17test_ge_v64float89v64float8S_(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64FLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-COMMON-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64FLOAT8]] [[B_COERCE:%.*]], 0
// CHECK-COMMON-NEXT:    [[TMP2:%.*]] = tail call <2 x i32> @llvm.aie2ps.vgefloat8(<64 x i8> [[TMP0]], <64 x i8> [[TMP1]])
// CHECK-COMMON-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// CHECK-COMMON-NEXT:    ret i64 [[TMP3]]
//
test_ge_v64float8(v64float8 a, v64float8 b) {
  return ge(a, b);
}
//
// CHECK-COMMON-LABEL: @_Z18test_eqz_v64float89v64float8(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64FLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-COMMON-NEXT:    [[AND_I_I_I:%.*]] = and <64 x i8> [[TMP0]], splat (i8 127)
// CHECK-COMMON-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.aie2ps.veqz8(<64 x i8> [[AND_I_I_I]])
// CHECK-COMMON-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to i64
// CHECK-COMMON-NEXT:    ret i64 [[TMP2]]
//
unsigned long long test_eqz_v64float8(v64float8 a) {
  return eqz(a);
}
// CHECK-COMMON-LABEL: @_Z18test_sel_v64float89v64float8S_y(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64FLOAT8:%.*]] [[A_COERCE:%.*]], 0
// CHECK-COMMON-NEXT:    [[TMP1:%.*]] = extractvalue [[STRUCT_V64FLOAT8]] [[B_COERCE:%.*]], 0
// CHECK-COMMON-NEXT:    [[TMP2:%.*]] = bitcast i64 [[S:%.*]] to <2 x i32>
// CHECK-COMMON-NEXT:    [[TMP3:%.*]] = tail call <64 x i8> @llvm.aie2ps.vsel8(<64 x i8> [[TMP0]], <64 x i8> [[TMP1]], <2 x i32> [[TMP2]])
// CHECK-COMMON-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64FLOAT8]] poison, <64 x i8> [[TMP3]], 0
// CHECK-COMMON-NEXT:    ret [[STRUCT_V64FLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v64float8 test_sel_v64float8(v64float8 a, v64float8 b, unsigned long long s) {
  return sel(a, b, s);
}

// CHECK-COMMON-LABEL: @_Z20test_bfloat16_to_intDv16_8bfloat16i(
// CHECK-COMMON-NEXT:  entry:
// CHECK-COMMON-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.v16bf16.to.v16i32(<16 x bfloat> [[A:%.*]], i32 [[SHFT:%.*]])
// CHECK-COMMON-NEXT:    ret <16 x i32> [[TMP0]]
//
v16int32 test_bfloat16_to_int(v16bfloat16 a, int shft) {
  return bfloat16_to_int(a, shft);
}

//// NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
// AIE2PS: {{.*}}
