// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
//===- aie2ps-srs-intrinsics.cpp ---------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//
// RUN: %clang -O2 %s --target=aie2ps -nostdlibinc -S -emit-llvm -o - | FileCheck %s

// CHECK-LABEL: @_Z19test_to_v16bfloat16Dv16_u10__accfloat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x bfloat> @llvm.aie2ps.v16accfloat.to.v16bf16(<16 x float> [[ACC:%.*]])
// CHECK-NEXT:    ret <16 x bfloat> [[TMP0]]
//
v16bfloat16 test_to_v16bfloat16(v16accfloat acc) {
  return to_v16bfloat16(acc);
}

// CHECK-LABEL: @_Z15test_to_v32int8Dv32_u7__acc32ii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i8> @llvm.aie2ps.I256.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <32 x i8> [[TMP0]]
//
v32int8 test_to_v32int8(v32acc32 acc, int shft, int sign) {
  return to_v32int8(acc, shft, sign);
}

// CHECK-LABEL: @_Z20test_to_v32int8_confDv32_u7__acc32iiDU2_DU4_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// CHECK-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// CHECK-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i8> @llvm.aie2ps.I256.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// CHECK-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// CHECK-NEXT:    ret <32 x i8> [[TMP2]]
//
v32int8 test_to_v32int8_conf(v32acc32 acc, int shft, int sign, crsat_t sat,
                    crrnd_t rnd) {
  return to_v32int8_conf(acc, shft, sign, sat, rnd);
}

// CHECK-LABEL: @_Z16test_to_v32uint8Dv32_u7__acc32ii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i8> @llvm.aie2ps.I256.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <32 x i8> [[TMP0]]
//
v32uint8 test_to_v32uint8(v32acc32 acc, int shft, int sign) {
  return to_v32uint8(acc, shft, sign);
}

// CHECK-LABEL: @_Z21test_to_v32uint8_confDv32_u7__acc32iiDU2_DU4_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// CHECK-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// CHECK-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i8> @llvm.aie2ps.I256.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// CHECK-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// CHECK-NEXT:    ret <32 x i8> [[TMP2]]
//
v32uint8 test_to_v32uint8_conf(v32acc32 acc, int shft, int sign, crsat_t sat,
                     crrnd_t rnd) {
  return to_v32uint8_conf(acc, shft, sign, sat, rnd);
}

// CHECK-LABEL: @_Z16test_to_v32int16Dv32_u7__acc32ii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2ps.I512.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <32 x i16> [[TMP0]]
//
v32int16 test_to_v32int16(v32acc32 acc, int shft, int sign) {
  return to_v32int16(acc, shft, sign);
}

// CHECK-LABEL: @_Z21test_to_v32int16_confDv32_u7__acc32iiDU2_DU4_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// CHECK-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// CHECK-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i16> @llvm.aie2ps.I512.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// CHECK-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// CHECK-NEXT:    ret <32 x i16> [[TMP2]]
//
v32int16 test_to_v32int16_conf(v32acc32 acc, int shft, int sign, crsat_t sat,
                     crrnd_t rnd) {
  return to_v32int16_conf(acc, shft, sign, sat, rnd);
}

// CHECK-LABEL: @_Z17test_to_v32uint16Dv32_u7__acc32ii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2ps.I512.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <32 x i16> [[TMP0]]
//
v32uint16 test_to_v32uint16(v32acc32 acc, int shft, int sign) {
  return to_v32uint16(acc, shft, sign);
}

// CHECK-LABEL: @_Z22test_to_v32uint16_confDv32_u7__acc32iiDU2_DU4_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// CHECK-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// CHECK-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i16> @llvm.aie2ps.I512.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// CHECK-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// CHECK-NEXT:    ret <32 x i16> [[TMP2]]
//
v32uint16 test_to_v32uint16_conf(v32acc32 acc, int shft, int sign, crsat_t sat,
                      crrnd_t rnd) {
  return to_v32uint16_conf(acc, shft, sign, sat, rnd);
}

// CHECK-LABEL: @_Z16test_to_v16int16Dv16_u7__acc32ii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i16> @llvm.aie2ps.I256.v16.acc32.srs(<16 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <16 x i16> [[TMP0]]
//
v16int16 test_to_v16int16(v16acc32 acc, int shft, int sign) {
  return to_v16int16(acc, shft, sign);
}

// CHECK-LABEL: @_Z21test_to_v16int16_confDv16_u7__acc32iiDU2_DU4_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// CHECK-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// CHECK-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i16> @llvm.aie2ps.I256.v16.acc32.srs(<16 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// CHECK-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// CHECK-NEXT:    ret <16 x i16> [[TMP2]]
//
v16int16 test_to_v16int16_conf(v16acc32 acc, int shft, int sign, crsat_t sat,
                     crrnd_t rnd) {
  return to_v16int16_conf(acc, shft, sign, sat, rnd);
}

// CHECK-LABEL: @_Z17test_to_v16uint16Dv16_u7__acc32ii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i16> @llvm.aie2ps.I256.v16.acc32.srs(<16 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <16 x i16> [[TMP0]]
//
v16uint16 test_to_v16uint16(v16acc32 acc, int shft, int sign) {
  return to_v16uint16(acc, shft, sign);
}

// CHECK-LABEL: @_Z22test_to_v16uint16_confDv16_u7__acc32iiDU2_DU4_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// CHECK-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// CHECK-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i16> @llvm.aie2ps.I256.v16.acc32.srs(<16 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// CHECK-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// CHECK-NEXT:    ret <16 x i16> [[TMP2]]
//
v16uint16 test_to_v16uint16_conf(v16acc32 acc, int shft, int sign, crsat_t sat,
                      crrnd_t rnd) {
  return to_v16uint16_conf(acc, shft, sign, sat, rnd);
}

// CHECK-LABEL: @_Z16test_to_v16int16Dv16_u7__acc64ii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i16> @llvm.aie2ps.I256.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <16 x i16> [[TMP0]]
//
v16int16 test_to_v16int16(v16acc64 acc, int shft, int sign) {
  return to_v16int16(acc, shft, sign);
}

// CHECK-LABEL: @_Z21test_to_v16int16_confDv16_u7__acc64iiDU2_DU4_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// CHECK-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// CHECK-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i16> @llvm.aie2ps.I256.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// CHECK-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// CHECK-NEXT:    ret <16 x i16> [[TMP2]]
//
v16int16 test_to_v16int16_conf(v16acc64 acc, int shft, int sign, crsat_t sat,
                     crrnd_t rnd) {
  return to_v16int16_conf(acc, shft, sign, sat, rnd);
}

// CHECK-LABEL: @_Z17test_to_v16uint16Dv16_u7__acc64ii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i16> @llvm.aie2ps.I256.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <16 x i16> [[TMP0]]
//
v16uint16 test_to_v16uint16(v16acc64 acc, int shft, int sign) {
  return to_v16uint16(acc, shft, sign);
}

// CHECK-LABEL: @_Z22test_to_v16uint16_confDv16_u7__acc64iiDU2_DU4_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// CHECK-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// CHECK-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i16> @llvm.aie2ps.I256.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// CHECK-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// CHECK-NEXT:    ret <16 x i16> [[TMP2]]
//
v16uint16 test_to_v16uint16_conf(v16acc64 acc, int shft, int sign, crsat_t sat,
                      crrnd_t rnd) {
  return to_v16uint16_conf(acc, shft, sign, sat, rnd);
}

// CHECK-LABEL: @_Z15test_to_v8int32Dv8_u7__acc64ii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i32> @llvm.aie2ps.I256.v8.acc64.srs(<8 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <8 x i32> [[TMP0]]
//
v8int32 test_to_v8int32(v8acc64 acc, int shft, int sign) {
  return to_v8int32(acc, shft, sign);
}

// CHECK-LABEL: @_Z20test_to_v8int32_confDv8_u7__acc64iiDU2_DU4_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// CHECK-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// CHECK-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <8 x i32> @llvm.aie2ps.I256.v8.acc64.srs(<8 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// CHECK-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// CHECK-NEXT:    ret <8 x i32> [[TMP2]]
//
v8int32 test_to_v8int32_conf(v8acc64 acc, int shft, int sign, crsat_t sat, crrnd_t rnd) {
  return to_v8int32_conf(acc, shft, sign, sat, rnd);
}

// CHECK-LABEL: @_Z16test_to_v8uint32Dv8_u7__acc64ii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i32> @llvm.aie2ps.I256.v8.acc64.srs(<8 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <8 x i32> [[TMP0]]
//
v8uint32 test_to_v8uint32(v8acc64 acc, int shft, int sign) {
  return to_v8uint32(acc, shft, sign);
}

// CHECK-LABEL: @_Z21test_to_v8uint32_confDv8_u7__acc64iiDU2_DU4_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// CHECK-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// CHECK-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <8 x i32> @llvm.aie2ps.I256.v8.acc64.srs(<8 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// CHECK-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// CHECK-NEXT:    ret <8 x i32> [[TMP2]]
//
v8uint32 test_to_v8uint32_conf(v8acc64 acc, int shft, int sign, crsat_t sat, crrnd_t rnd) {
  return to_v8uint32_conf(acc, shft, sign, sat, rnd);
}

// CHECK-LABEL: @_Z16test_to_v16int32Dv16_u7__acc64ii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.I512.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <16 x i32> [[TMP0]]
//
v16int32 test_to_v16int32(v16acc64 acc, int shft, int sign) {
  return to_v16int32(acc, shft, sign);
}

// CHECK-LABEL: @_Z21test_to_v16int32_confDv16_u7__acc64iiDU2_DU4_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// CHECK-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// CHECK-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.I512.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// CHECK-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// CHECK-NEXT:    ret <16 x i32> [[TMP2]]
//
v16int32 test_to_v16int32_conf(v16acc64 acc, int shft, int sign, crsat_t sat,
                     crrnd_t rnd) {
  return to_v16int32_conf(acc, shft, sign, sat, rnd);
}

// CHECK-LABEL: @_Z17test_to_v16uint32Dv16_u7__acc64ii(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.I512.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    ret <16 x i32> [[TMP0]]
//
v16uint32 test_to_v16uint32(v16acc64 acc, int shft, int sign) {
  return to_v16uint32(acc, shft, sign);
}

// CHECK-LABEL: @_Z22test_to_v16uint32_confDv16_u7__acc64iiDU2_DU4_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// CHECK-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// CHECK-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.I512.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 [[SIGN:%.*]])
// CHECK-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// CHECK-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// CHECK-NEXT:    ret <16 x i32> [[TMP2]]
//
v16uint32 test_to_v16uint32_conf(v16acc64 acc, int shft, int sign, crsat_t sat,
                      crrnd_t rnd) {
  return to_v16uint32_conf(acc, shft, sign, sat, rnd);
}

// CHECK-LABEL: @_Z15test_to_v32int8Dv32_u7__acc32i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i8> @llvm.aie2ps.I256.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    ret <32 x i8> [[TMP0]]
//
v32int8 test_to_v32int8(v32acc32 acc, int shft) {
  return to_v32int8(acc, shft);
}

// CHECK-LABEL: @_Z20test_to_v32int8_confDv32_u7__acc32iDU2_DU4_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// CHECK-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// CHECK-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i8> @llvm.aie2ps.I256.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// CHECK-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// CHECK-NEXT:    ret <32 x i8> [[TMP2]]
//
v32int8 test_to_v32int8_conf(v32acc32 acc, int shft, crsat_t sat,
                                   crrnd_t rnd) {
  return to_v32int8_conf(acc, shft, sat, rnd);
}

// CHECK-LABEL: @_Z16test_to_v32uint8Dv32_u7__acc32i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i8> @llvm.aie2ps.I256.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// CHECK-NEXT:    ret <32 x i8> [[TMP0]]
//
v32uint8 test_to_v32uint8(v32acc32 acc, int shft) {
  return to_v32uint8(acc, shft);
}

// CHECK-LABEL: @_Z21test_to_v32uint8_confDv32_u7__acc32iDU2_DU4_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// CHECK-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// CHECK-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i8> @llvm.aie2ps.I256.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// CHECK-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// CHECK-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// CHECK-NEXT:    ret <32 x i8> [[TMP2]]
//
v32uint8 test_to_v32uint8_conf(v32acc32 acc, int shft, crsat_t sat,
                                     crrnd_t rnd) {
  return to_v32uint8_conf(acc, shft, sat, rnd);
}

// CHECK-LABEL: @_Z16test_to_v32int16Dv32_u7__acc32i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2ps.I512.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    ret <32 x i16> [[TMP0]]
//
v32int16 test_to_v32int16(v32acc32 acc, int shft) {
  return to_v32int16(acc, shft);
}

// CHECK-LABEL: @_Z21test_to_v32int16_confDv32_u7__acc32iDU2_DU4_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// CHECK-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// CHECK-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i16> @llvm.aie2ps.I512.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// CHECK-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// CHECK-NEXT:    ret <32 x i16> [[TMP2]]
//
v32int16 test_to_v32int16_conf(v32acc32 acc, int shft, crsat_t sat,
                                     crrnd_t rnd) {
  return to_v32int16_conf(acc, shft, sat, rnd);
}

// CHECK-LABEL: @_Z17test_to_v32uint16Dv32_u7__acc32i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x i16> @llvm.aie2ps.I512.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// CHECK-NEXT:    ret <32 x i16> [[TMP0]]
//
v32uint16 test_to_v32uint16(v32acc32 acc, int shft) {
  return to_v32uint16(acc, shft);
}

// CHECK-LABEL: @_Z22test_to_v32uint16_confDv32_u7__acc32iDU2_DU4_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// CHECK-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// CHECK-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <32 x i16> @llvm.aie2ps.I512.v32.acc32.srs(<32 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// CHECK-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// CHECK-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// CHECK-NEXT:    ret <32 x i16> [[TMP2]]
//
v32uint16 test_to_v32uint16_conf(v32acc32 acc, int shft, crsat_t sat,
                                       crrnd_t rnd) {
  return to_v32uint16_conf(acc, shft, sat, rnd);
}

// CHECK-LABEL: @_Z16test_to_v16int16Dv16_u7__acc32i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i16> @llvm.aie2ps.I256.v16.acc32.srs(<16 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    ret <16 x i16> [[TMP0]]
//
v16int16 test_to_v16int16(v16acc32 acc, int shft) {
  return to_v16int16(acc, shft);
}

// CHECK-LABEL: @_Z21test_to_v16int16_confDv16_u7__acc32iDU2_DU4_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// CHECK-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// CHECK-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i16> @llvm.aie2ps.I256.v16.acc32.srs(<16 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// CHECK-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// CHECK-NEXT:    ret <16 x i16> [[TMP2]]
//
v16int16 test_to_v16int16_conf(v16acc32 acc, int shft, crsat_t sat,
                                     crrnd_t rnd) {
  return to_v16int16_conf(acc, shft, sat, rnd);
}

// CHECK-LABEL: @_Z17test_to_v16uint16Dv16_u7__acc32i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i16> @llvm.aie2ps.I256.v16.acc32.srs(<16 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// CHECK-NEXT:    ret <16 x i16> [[TMP0]]
//
v16uint16 test_to_v16uint16(v16acc32 acc, int shft) {
  return to_v16uint16(acc, shft);
}

// CHECK-LABEL: @_Z22test_to_v16uint16_confDv16_u7__acc32iDU2_DU4_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// CHECK-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// CHECK-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i16> @llvm.aie2ps.I256.v16.acc32.srs(<16 x i32> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// CHECK-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// CHECK-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// CHECK-NEXT:    ret <16 x i16> [[TMP2]]
//
v16uint16 test_to_v16uint16_conf(v16acc32 acc, int shft, crsat_t sat,
                                       crrnd_t rnd) {
  return to_v16uint16_conf(acc, shft, sat, rnd);
}

// CHECK-LABEL: @_Z16test_to_v16int16Dv16_u7__acc64i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i16> @llvm.aie2ps.I256.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    ret <16 x i16> [[TMP0]]
//
v16int16 test_to_v16int16(v16acc64 acc, int shft) {
  return to_v16int16(acc, shft);
}

// CHECK-LABEL: @_Z21test_to_v16int16_confDv16_u7__acc64iDU2_DU4_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// CHECK-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// CHECK-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i16> @llvm.aie2ps.I256.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// CHECK-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// CHECK-NEXT:    ret <16 x i16> [[TMP2]]
//
v16int16 test_to_v16int16_conf(v16acc64 acc, int shft, crsat_t sat,
                                     crrnd_t rnd) {
  return to_v16int16_conf(acc, shft, sat, rnd);
}

// CHECK-LABEL: @_Z17test_to_v16uint16Dv16_u7__acc64i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i16> @llvm.aie2ps.I256.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// CHECK-NEXT:    ret <16 x i16> [[TMP0]]
//
v16uint16 test_to_v16uint16(v16acc64 acc, int shft) {
  return to_v16uint16(acc, shft);
}

// CHECK-LABEL: @_Z22test_to_v16uint16_confDv16_u7__acc64iDU2_DU4_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// CHECK-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// CHECK-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i16> @llvm.aie2ps.I256.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// CHECK-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// CHECK-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// CHECK-NEXT:    ret <16 x i16> [[TMP2]]
//
v16uint16 test_to_v16uint16_conf(v16acc64 acc, int shft, crsat_t sat,
                                       crrnd_t rnd) {
  return to_v16uint16_conf(acc, shft, sat, rnd);
}

// CHECK-LABEL: @_Z16test_to_v16int32Dv16_u7__acc64i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.I512.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    ret <16 x i32> [[TMP0]]
//
v16int32 test_to_v16int32(v16acc64 acc, int shft) {
  return to_v16int32(acc, shft);
}

// CHECK-LABEL: @_Z21test_to_v16int32_confDv16_u7__acc64iDU2_DU4_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// CHECK-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// CHECK-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.I512.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// CHECK-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// CHECK-NEXT:    ret <16 x i32> [[TMP2]]
//
v16int32 test_to_v16int32_conf(v16acc64 acc, int shft, crsat_t sat,
                                     crrnd_t rnd) {
  return to_v16int32_conf(acc, shft, sat, rnd);
}

// CHECK-LABEL: @_Z17test_to_v16uint32Dv16_u7__acc64i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.I512.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// CHECK-NEXT:    ret <16 x i32> [[TMP0]]
//
v16uint32 test_to_v16uint32(v16acc64 acc, int shft) {
  return to_v16uint32(acc, shft);
}

// CHECK-LABEL: @_Z22test_to_v16uint32_confDv16_u7__acc64iDU2_DU4_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// CHECK-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// CHECK-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.I512.v16.acc64.srs(<16 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// CHECK-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// CHECK-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// CHECK-NEXT:    ret <16 x i32> [[TMP2]]
//
v16uint32 test_to_v16uint32_conf(v16acc64 acc, int shft, crsat_t sat,
                                       crrnd_t rnd) {
  return to_v16uint32_conf(acc, shft, sat, rnd);
}

// CHECK-LABEL: @_Z15test_to_v8int32Dv8_u7__acc64i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i32> @llvm.aie2ps.I256.v8.acc64.srs(<8 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    ret <8 x i32> [[TMP0]]
//
v8int32 test_to_v8int32(v8acc64 acc, int shft) {
  return to_v8int32(acc, shft);
}

// CHECK-LABEL: @_Z20test_to_v8int32_confDv8_u7__acc64iDU2_DU4_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// CHECK-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// CHECK-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <8 x i32> @llvm.aie2ps.I256.v8.acc64.srs(<8 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 1)
// CHECK-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// CHECK-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// CHECK-NEXT:    ret <8 x i32> [[TMP2]]
//
v8int32 test_to_v8int32_conf(v8acc64 acc, int shft, crsat_t sat,
                                   crrnd_t rnd) {
  return to_v8int32_conf(acc, shft, sat, rnd);
}

// CHECK-LABEL: @_Z16test_to_v8uint32Dv8_u7__acc64i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <8 x i32> @llvm.aie2ps.I256.v8.acc64.srs(<8 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// CHECK-NEXT:    ret <8 x i32> [[TMP0]]
//
v8uint32 test_to_v8uint32(v8acc64 acc, int shft) {
  return to_v8uint32(acc, shft);
}

// CHECK-LABEL: @_Z21test_to_v8uint32_confDv8_u7__acc64iDU2_DU4_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// CHECK-NEXT:    [[CONV6_I:%.*]] = zext i2 [[SAT:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV6_I]])
// CHECK-NEXT:    [[CONV8_I:%.*]] = zext i4 [[RND:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV8_I]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call noundef <8 x i32> @llvm.aie2ps.I256.v8.acc64.srs(<8 x i64> [[ACC:%.*]], i32 [[SHFT:%.*]], i32 0)
// CHECK-NEXT:    [[CONV11_I:%.*]] = and i32 [[TMP0]], 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 0, i32 range(i32 0, 4) [[CONV11_I]])
// CHECK-NEXT:    [[CONV13_I:%.*]] = and i32 [[TMP1]], 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV13_I]])
// CHECK-NEXT:    ret <8 x i32> [[TMP2]]
//
v8uint32 test_to_v8uint32_conf(v8acc64 acc, int shft, crsat_t sat,
                                     crrnd_t rnd) {
  return to_v8uint32_conf(acc, shft, sat, rnd);
}

// CHECK-LABEL: @_Z19test_to_v32bfloat16Dv32_u10__accfloat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x bfloat> @llvm.aie2ps.v32accfloat.to.v32bf16(<32 x float> [[ACC:%.*]])
// CHECK-NEXT:    ret <32 x bfloat> [[TMP0]]
//
v32bfloat16 test_to_v32bfloat16(v32accfloat acc) {
  return to_v32bfloat16(acc);
}

// CHECK-LABEL: @_Z18test_to_v16float16Dv16_u10__accfloat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x half> @llvm.aie2ps.v16accfloat.to.v16float16(<16 x float> [[A:%.*]])
// CHECK-NEXT:    ret <16 x half> [[TMP0]]
//
v16float16 test_to_v16float16(v16accfloat a) {
  return to_v16float16(a);
}

// CHECK-LABEL: @_Z23test_to_v16float16_confDv16_u10__accfloatDU4_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// CHECK-NEXT:    [[CONV2_I:%.*]] = zext i4 [[RND:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV2_I]])
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x half> @llvm.aie2ps.v16accfloat.to.v16float16(<16 x float> [[A:%.*]])
// CHECK-NEXT:    [[CONV5_I:%.*]] = and i32 [[TMP0]], 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV5_I]])
// CHECK-NEXT:    ret <16 x half> [[TMP1]]
//
v16float16 test_to_v16float16_conf(v16accfloat a, crrnd_t rnd) {
  return to_v16float16_conf(a, rnd);
}

// CHECK-LABEL: @_Z18test_to_v32float16Dv32_u10__accfloat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <32 x half> @llvm.aie2ps.v32accfloat.to.v32float16(<32 x float> [[A:%.*]])
// CHECK-NEXT:    ret <32 x half> [[TMP0]]
//
v32float16 test_to_v32float16(v32accfloat a) {
  return to_v32float16(a);
}

// CHECK-LABEL: @_Z23test_to_v32float16_confDv32_u10__accfloatDU4_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// CHECK-NEXT:    [[CONV2_I:%.*]] = zext i4 [[RND:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV2_I]])
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef <32 x half> @llvm.aie2ps.v32accfloat.to.v32float16(<32 x float> [[A:%.*]])
// CHECK-NEXT:    [[CONV5_I:%.*]] = and i32 [[TMP0]], 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV5_I]])
// CHECK-NEXT:    ret <32 x half> [[TMP1]]
//
v32float16 test_to_v32float16_conf(v32accfloat a, crrnd_t rnd) {
  return to_v32float16_conf(a, rnd);
}

// CHECK-LABEL: @_Z17test_to_v32float8Dv32_u10__accfloat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <32 x i8> @llvm.aie2ps.v32accfloat.to.v32float8(<32 x float> [[A:%.*]], i32 0)
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V32FLOAT8:%.*]] poison, <32 x i8> [[TMP0]], 0
// CHECK-NEXT:    ret [[STRUCT_V32FLOAT8]] [[DOTFCA_0_INSERT_I_I]]
//
v32float8 test_to_v32float8(v32accfloat a) {
  return to_v32float8(a);
}

// CHECK-LABEL: @_Z22test_to_v32float8_confDv32_u10__accfloatDU4_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// CHECK-NEXT:    [[CONV3_I_I:%.*]] = zext i4 [[RND:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV3_I_I]])
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <32 x i8> @llvm.aie2ps.v32accfloat.to.v32float8(<32 x float> [[A:%.*]], i32 0)
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I_I_I:%.*]] = insertvalue [[STRUCT_V32FLOAT8:%.*]] poison, <32 x i8> [[TMP1]], 0
// CHECK-NEXT:    [[CONV7_I_I:%.*]] = and i32 [[TMP0]], 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV7_I_I]])
// CHECK-NEXT:    ret [[STRUCT_V32FLOAT8]] [[DOTFCA_0_INSERT_I_I_I]]
//
v32float8 test_to_v32float8_conf(v32accfloat a, crrnd_t rnd) {
  return to_v32float8_conf(a, rnd);
}

// CHECK-LABEL: @_Z17test_to_v32float8Dv32_u10__accfloatDU6_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CONV_I:%.*]] = zext i6 [[SHFT:%.*]] to i32
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <32 x i8> @llvm.aie2ps.v32accfloat.to.v32float8(<32 x float> [[A:%.*]], i32 [[CONV_I]])
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V32FLOAT8:%.*]] poison, <32 x i8> [[TMP0]], 0
// CHECK-NEXT:    ret [[STRUCT_V32FLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v32float8 test_to_v32float8(v32accfloat a, uint6_t shft) {
  return to_v32float8(a, shft);
}

// CHECK-LABEL: @_Z22test_to_v32float8_confDv32_u10__accfloatDU6_DU4_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// CHECK-NEXT:    [[CONV3_I:%.*]] = zext i4 [[RND:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV3_I]])
// CHECK-NEXT:    [[CONV_I_I:%.*]] = zext i6 [[SHFT:%.*]] to i32
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <32 x i8> @llvm.aie2ps.v32accfloat.to.v32float8(<32 x float> [[A:%.*]], i32 [[CONV_I_I]])
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V32FLOAT8:%.*]] poison, <32 x i8> [[TMP1]], 0
// CHECK-NEXT:    [[CONV7_I:%.*]] = and i32 [[TMP0]], 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV7_I]])
// CHECK-NEXT:    ret [[STRUCT_V32FLOAT8]] [[DOTFCA_0_INSERT_I_I]]
//
v32float8 test_to_v32float8_conf(v32accfloat a, uint6_t shft, crrnd_t rnd) {
  return to_v32float8_conf(a, shft, rnd);
}

// CHECK-LABEL: @_Z18test_to_v32bfloat8Dv32_u10__accfloat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <32 x i8> @llvm.aie2ps.v32accfloat.to.v32bfloat8(<32 x float> [[A:%.*]], i32 0)
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V32BFLOAT8:%.*]] poison, <32 x i8> [[TMP0]], 0
// CHECK-NEXT:    ret [[STRUCT_V32BFLOAT8]] [[DOTFCA_0_INSERT_I_I]]
//
v32bfloat8 test_to_v32bfloat8(v32accfloat a) {
  return to_v32bfloat8(a);
}

// CHECK-LABEL: @_Z23test_to_v32bfloat8_confDv32_u10__accfloatDU4_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// CHECK-NEXT:    [[CONV3_I_I:%.*]] = zext i4 [[RND:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV3_I_I]])
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <32 x i8> @llvm.aie2ps.v32accfloat.to.v32bfloat8(<32 x float> [[A:%.*]], i32 0)
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I_I_I:%.*]] = insertvalue [[STRUCT_V32BFLOAT8:%.*]] poison, <32 x i8> [[TMP1]], 0
// CHECK-NEXT:    [[CONV7_I_I:%.*]] = and i32 [[TMP0]], 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV7_I_I]])
// CHECK-NEXT:    ret [[STRUCT_V32BFLOAT8]] [[DOTFCA_0_INSERT_I_I_I]]
//
v32bfloat8 test_to_v32bfloat8_conf(v32accfloat a, crrnd_t rnd) {
  return to_v32bfloat8_conf(a, rnd);
}

// CHECK-LABEL: @_Z18test_to_v32bfloat8Dv32_u10__accfloatDU6_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CONV_I:%.*]] = zext i6 [[SHFT:%.*]] to i32
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <32 x i8> @llvm.aie2ps.v32accfloat.to.v32bfloat8(<32 x float> [[A:%.*]], i32 [[CONV_I]])
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V32BFLOAT8:%.*]] poison, <32 x i8> [[TMP0]], 0
// CHECK-NEXT:    ret [[STRUCT_V32BFLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v32bfloat8 test_to_v32bfloat8(v32accfloat a, uint6_t shft) {
  return to_v32bfloat8(a, shft);
}

// CHECK-LABEL: @_Z23test_to_v32bfloat8_confDv32_u10__accfloatDU6_DU4_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// CHECK-NEXT:    [[CONV3_I:%.*]] = zext i4 [[RND:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV3_I]])
// CHECK-NEXT:    [[CONV_I_I:%.*]] = zext i6 [[SHFT:%.*]] to i32
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <32 x i8> @llvm.aie2ps.v32accfloat.to.v32bfloat8(<32 x float> [[A:%.*]], i32 [[CONV_I_I]])
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V32BFLOAT8:%.*]] poison, <32 x i8> [[TMP1]], 0
// CHECK-NEXT:    [[CONV7_I:%.*]] = and i32 [[TMP0]], 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV7_I]])
// CHECK-NEXT:    ret [[STRUCT_V32BFLOAT8]] [[DOTFCA_0_INSERT_I_I]]
//
v32bfloat8 test_to_v32bfloat8_conf(v32accfloat a, uint6_t shft, crrnd_t rnd) {
  return to_v32bfloat8_conf(a, shft, rnd);
}

// CHECK-LABEL: @_Z14test_to_v64mx4Dv64_u10__accfloat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <8 x i32>, <2 x i32>, i32, i32 } @llvm.aie2ps.v64accfloat.to.v64mx4(<64 x float> [[A:%.*]])
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i32>, <2 x i32>, i32, i32 } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i32>, <2 x i32>, i32, i32 } [[TMP0]], 1
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i32>, <2 x i32>, i32, i32 } [[TMP0]], 2
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i32>, <2 x i32>, i32, i32 } [[TMP0]], 3
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX4:%.*]] poison, <8 x i32> [[TMP1]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX4]] [[DOTFCA_0_INSERT_I]], <2 x i32> [[TMP2]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX4]] [[DOTFCA_1_INSERT_I]], i32 [[TMP3]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX4]] [[DOTFCA_2_INSERT_I]], i32 [[TMP4]], 3
// CHECK-NEXT:    ret [[STRUCT_V64MX4]] [[DOTFCA_3_INSERT_I]]
//
v64mx4 test_to_v64mx4(v64accfloat a) {
  return to_v64mx4(a);
}

// CHECK-LABEL: @_Z19test_to_v64mx4_confDv64_u10__accfloatDU4_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// CHECK-NEXT:    [[CONV2_I:%.*]] = zext i4 [[RND:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV2_I]])
// CHECK-NEXT:    [[TMP1:%.*]] = tail call { <8 x i32>, <2 x i32>, i32, i32 } @llvm.aie2ps.v64accfloat.to.v64mx4(<64 x float> [[A:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i32>, <2 x i32>, i32, i32 } [[TMP1]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i32>, <2 x i32>, i32, i32 } [[TMP1]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i32>, <2 x i32>, i32, i32 } [[TMP1]], 2
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i32>, <2 x i32>, i32, i32 } [[TMP1]], 3
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64MX4:%.*]] poison, <8 x i32> [[TMP2]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64MX4]] [[DOTFCA_0_INSERT_I_I]], <2 x i32> [[TMP3]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64MX4]] [[DOTFCA_1_INSERT_I_I]], i32 [[TMP4]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64MX4]] [[DOTFCA_2_INSERT_I_I]], i32 [[TMP5]], 3
// CHECK-NEXT:    [[CONV5_I:%.*]] = and i32 [[TMP0]], 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV5_I]])
// CHECK-NEXT:    ret [[STRUCT_V64MX4]] [[DOTFCA_3_INSERT_I_I]]
//
v64mx4 test_to_v64mx4_conf(v64accfloat a, crrnd_t rnd) {
  return to_v64mx4_conf(a, rnd);
}

// CHECK-LABEL: @_Z14test_to_v64mx6Dv64_u10__accfloat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <8 x i32>, <2 x i32>, i32, i32 } @llvm.aie2ps.v64accfloat.to.v64mx6(<64 x float> [[A:%.*]])
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i32>, <2 x i32>, i32, i32 } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i32>, <2 x i32>, i32, i32 } [[TMP0]], 1
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i32>, <2 x i32>, i32, i32 } [[TMP0]], 2
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i32>, <2 x i32>, i32, i32 } [[TMP0]], 3
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX6:%.*]] poison, <8 x i32> [[TMP1]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX6]] [[DOTFCA_0_INSERT_I]], <2 x i32> [[TMP2]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX6]] [[DOTFCA_1_INSERT_I]], i32 [[TMP3]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX6]] [[DOTFCA_2_INSERT_I]], i32 [[TMP4]], 3
// CHECK-NEXT:    ret [[STRUCT_V64MX6]] [[DOTFCA_3_INSERT_I]]
//
v64mx6 test_to_v64mx6(v64accfloat a) {
  return to_v64mx6(a);
}

// CHECK-LABEL: @_Z19test_to_v64mx6_confDv64_u10__accfloatDU4_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// CHECK-NEXT:    [[CONV2_I:%.*]] = zext i4 [[RND:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV2_I]])
// CHECK-NEXT:    [[TMP1:%.*]] = tail call { <8 x i32>, <2 x i32>, i32, i32 } @llvm.aie2ps.v64accfloat.to.v64mx6(<64 x float> [[A:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i32>, <2 x i32>, i32, i32 } [[TMP1]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i32>, <2 x i32>, i32, i32 } [[TMP1]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i32>, <2 x i32>, i32, i32 } [[TMP1]], 2
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i32>, <2 x i32>, i32, i32 } [[TMP1]], 3
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64MX6:%.*]] poison, <8 x i32> [[TMP2]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64MX6]] [[DOTFCA_0_INSERT_I_I]], <2 x i32> [[TMP3]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64MX6]] [[DOTFCA_1_INSERT_I_I]], i32 [[TMP4]], 2
// CHECK-NEXT:    [[DOTFCA_3_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64MX6]] [[DOTFCA_2_INSERT_I_I]], i32 [[TMP5]], 3
// CHECK-NEXT:    [[CONV5_I:%.*]] = and i32 [[TMP0]], 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV5_I]])
// CHECK-NEXT:    ret [[STRUCT_V64MX6]] [[DOTFCA_3_INSERT_I_I]]
//
v64mx6 test_to_v64mx6_conf(v64accfloat a, crrnd_t rnd) {
  return to_v64mx6_conf(a, rnd);
}

// CHECK-LABEL: @_Z14test_to_v64mx9Dv64_u10__accfloat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.v64accfloat.to.v64mx9(<64 x float> [[A:%.*]])
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } [[TMP0]], 1
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } [[TMP0]], 2
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX9:%.*]] poison, <16 x i32> [[TMP1]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX9]] [[DOTFCA_0_INSERT_I]], <2 x i32> [[TMP2]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I:%.*]] = insertvalue [[STRUCT_V64MX9]] [[DOTFCA_1_INSERT_I]], <2 x i32> [[TMP3]], 2
// CHECK-NEXT:    ret [[STRUCT_V64MX9]] [[DOTFCA_2_INSERT_I]]
//
v64mx9 test_to_v64mx9(v64accfloat a) {
  return to_v64mx9(a);
}

// CHECK-LABEL: @_Z19test_to_v64mx9_confDv64_u10__accfloatDU4_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef i32 @llvm.aie2ps.get.ctrl.reg(i32 1)
// CHECK-NEXT:    [[CONV2_I:%.*]] = zext i4 [[RND:%.*]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV2_I]])
// CHECK-NEXT:    [[TMP1:%.*]] = tail call { <16 x i32>, <2 x i32>, <2 x i32> } @llvm.aie2ps.v64accfloat.to.v64mx9(<64 x float> [[A:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } [[TMP1]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } [[TMP1]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i32>, <2 x i32>, <2 x i32> } [[TMP1]], 2
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64MX9:%.*]] poison, <16 x i32> [[TMP2]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64MX9]] [[DOTFCA_0_INSERT_I_I]], <2 x i32> [[TMP3]], 1
// CHECK-NEXT:    [[DOTFCA_2_INSERT_I_I:%.*]] = insertvalue [[STRUCT_V64MX9]] [[DOTFCA_1_INSERT_I_I]], <2 x i32> [[TMP4]], 2
// CHECK-NEXT:    [[CONV5_I:%.*]] = and i32 [[TMP0]], 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.set.ctrl.reg(i32 1, i32 range(i32 0, 16) [[CONV5_I]])
// CHECK-NEXT:    ret [[STRUCT_V64MX9]] [[DOTFCA_2_INSERT_I_I]]
//
v64mx9 test_to_v64mx9_conf(v64accfloat a, crrnd_t rnd) {
  return to_v64mx9_conf(a, rnd);
}
