// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 4
//===- aie2ps-stream-intrinsic.cpp ------------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//

// RUN: %clang -O2 %s --target=aie2ps -nostdlibinc -S -emit-llvm -o - | FileCheck %s

// CHECK-LABEL: define dso_local noundef <32 x half> @_Z23test_get_scd_v32float16i(
// CHECK-SAME: i32 noundef [[EN:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2ps.scd.read.vec(i32 [[EN]])
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <32 x half>
// CHECK-NEXT:    ret <32 x half> [[TMP1]]
//
v32float16 test_get_scd_v32float16(int en) { return get_scd_v32float16(en); }

// CHECK-LABEL: define dso_local %struct.v64float8 @_Z22test_get_scd_v64float8i(
// CHECK-SAME: i32 noundef [[EN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2ps.scd.read.vec(i32 [[EN]])
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <64 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64FLOAT8:%.*]] poison, <64 x i8> [[TMP1]], 0
// CHECK-NEXT:    ret [[STRUCT_V64FLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v64float8 test_get_scd_v64float8(int en) { return get_scd_v64float8(en); }

// CHECK-LABEL: define dso_local %struct.v64bfloat8 @_Z23test_get_scd_v64bfloat8i(
// CHECK-SAME: i32 noundef [[EN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <16 x i32> @llvm.aie2ps.scd.read.vec(i32 [[EN]])
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP0]] to <64 x i8>
// CHECK-NEXT:    [[DOTFCA_0_INSERT_I:%.*]] = insertvalue [[STRUCT_V64BFLOAT8:%.*]] poison, <64 x i8> [[TMP1]], 0
// CHECK-NEXT:    ret [[STRUCT_V64BFLOAT8]] [[DOTFCA_0_INSERT_I]]
//
v64bfloat8 test_get_scd_v64bfloat8(int en) { return get_scd_v64bfloat8(en); }

// CHECK-LABEL: define dso_local noundef <64 x bfloat> @_Z24test_get_scd_v64bfloat16i(
// CHECK-SAME: i32 noundef [[EN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 [[EN]])
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 [[EN]])
// CHECK-NEXT:    [[SHUFFLE2_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I_I]] to <64 x bfloat>
// CHECK-NEXT:    ret <64 x bfloat> [[TMP2]]
//
v64bfloat16 test_get_scd_v64bfloat16(int en) { return get_scd_v64bfloat16(en); }

// CHECK-LABEL: define dso_local noundef <64 x half> @_Z23test_get_scd_v64float16i(
// CHECK-SAME: i32 noundef [[EN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 [[EN]])
// CHECK-NEXT:    [[TMP1:%.*]] = tail call noundef <16 x i32> @llvm.aie2ps.scd.read.vec(i32 [[EN]])
// CHECK-NEXT:    [[SHUFFLE2_I_I_I_I:%.*]] = shufflevector <16 x i32> [[TMP0]], <16 x i32> [[TMP1]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I_I]] to <64 x half>
// CHECK-NEXT:    ret <64 x half> [[TMP2]]
//
v64float16 test_get_scd_v64float16(int en) { return get_scd_v64float16(en); }

// CHECK-LABEL: define dso_local void @_Z12test_put_mcdDv32_7float16i(
// CHECK-SAME: <32 x half> noundef [[A:%.*]], i32 noundef [[EN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x half> [[A]] to <16 x i32>
// CHECK-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[TMP0]], i32 [[EN]])
// CHECK-NEXT:    ret void
//
void test_put_mcd(v32float16 a, int en) { put_mcd(a, en); }

// CHECK-LABEL: define dso_local void @_Z12test_put_mcd9v64float8i(
// CHECK-SAME: [[STRUCT_V64FLOAT8:%.*]] [[A_COERCE:%.*]], i32 noundef [[EN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64FLOAT8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <64 x i8> [[TMP0]] to <16 x i32>
// CHECK-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[TMP1]], i32 [[EN]])
// CHECK-NEXT:    ret void
//
void test_put_mcd(v64float8 a, int en) { put_mcd(a, en); }

// CHECK-LABEL: define dso_local void @_Z12test_put_mcd10v64bfloat8i(
// CHECK-SAME: [[STRUCT_V64BFLOAT8:%.*]] [[A_COERCE:%.*]], i32 noundef [[EN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFLOAT8]] [[A_COERCE]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <64 x i8> [[TMP0]] to <16 x i32>
// CHECK-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[TMP1]], i32 [[EN]])
// CHECK-NEXT:    ret void
//
void test_put_mcd(v64bfloat8 a, int en) { put_mcd(a, en); }

// CHECK-LABEL: define dso_local void @_Z12test_put_mcdDv64_7float16i(
// CHECK-SAME: <64 x half> noundef [[A:%.*]], i32 noundef [[EN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x half> [[A]] to <32 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE_I_I_I_I]], i32 [[EN]])
// CHECK-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE1_I_I_I_I]], i32 [[EN]])
// CHECK-NEXT:    ret void
//
void test_put_mcd(v64float16 a, int en) { put_mcd(a, en); }

// CHECK-LABEL: define dso_local void @_Z12test_put_mcdDv64_8bfloat16i(
// CHECK-SAME: <64 x bfloat> noundef [[A:%.*]], i32 noundef [[EN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x bfloat> [[A]] to <32 x i32>
// CHECK-NEXT:    [[SHUFFLE_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE_I_I_I_I]], i32 [[EN]])
// CHECK-NEXT:    [[SHUFFLE1_I_I_I_I:%.*]] = shufflevector <32 x i32> [[TMP0]], <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    tail call void @llvm.aie2ps.mcd.write.vec(<16 x i32> [[SHUFFLE1_I_I_I_I]], i32 [[EN]])
// CHECK-NEXT:    ret void
//
void test_put_mcd(v64bfloat16 a, int en) { put_mcd(a, en); }

// CHECK-LABEL: define dso_local void @_Z11test_put_msDv2_7float16i(
// CHECK-SAME: <2 x half> noundef [[VAL:%.*]], i32 noundef [[TLAST:%.*]]) local_unnamed_addr #[[ATTR1:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x half> [[VAL]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[TMP0]], i32 [[TLAST]])
// CHECK-NEXT:    ret void
//
void test_put_ms(v2float16 val, int tlast) { put_ms(val, tlast); }

// CHECK-LABEL: define dso_local void @_Z11test_put_msDv2_7float16(
// CHECK-SAME: <2 x half> noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR1]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x half> [[VAL]] to i32
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[TMP0]], i32 0)
// CHECK-NEXT:    ret void
//
void test_put_ms(v2float16 val) { put_ms(val); }

// CHECK-LABEL: define dso_local void @_Z14test_put_ms_nbDv2_7float16iRb(
// CHECK-SAME: <2 x half> noundef [[VAL:%.*]], i32 noundef [[TLAST:%.*]], ptr nonnull writeonly align 1 captures(none) dereferenceable(1) initializes((0, 1)) [[SUCCESS:%.*]]) local_unnamed_addr #[[ATTR1]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x half> [[VAL]] to i32
// CHECK-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2ps.put.ms.nb(i32 [[TMP0]], i32 [[TLAST]])
// CHECK-NEXT:    [[TOBOOL_I:%.*]] = icmp ne i32 [[TMP1]], 0
// CHECK-NEXT:    [[STOREDV_I:%.*]] = zext i1 [[TOBOOL_I]] to i8
// CHECK-NEXT:    store i8 [[STOREDV_I]], ptr [[SUCCESS]], align 1, !tbaa [[TBAA2:![0-9]+]]
// CHECK-NEXT:    ret void
//
void test_put_ms_nb(v2float16 val, int tlast, bool &success) {
  put_ms_nb(val, tlast, success);
}

// CHECK-LABEL: define dso_local void @_Z14test_put_ms_nbDv2_7float16Rb(
// CHECK-SAME: <2 x half> noundef [[VAL:%.*]], ptr nonnull writeonly align 1 captures(none) dereferenceable(1) initializes((0, 1)) [[SUCCESS:%.*]]) local_unnamed_addr #[[ATTR1]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x half> [[VAL]] to i32
// CHECK-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.aie2ps.put.ms.nb(i32 [[TMP0]], i32 0)
// CHECK-NEXT:    [[TOBOOL_I:%.*]] = icmp ne i32 [[TMP1]], 0
// CHECK-NEXT:    [[STOREDV_I:%.*]] = zext i1 [[TOBOOL_I]] to i8
// CHECK-NEXT:    store i8 [[STOREDV_I]], ptr [[SUCCESS]], align 1, !tbaa [[TBAA2]]
// CHECK-NEXT:    ret void
//
void test_put_ms_nb(v2float16 val, bool &success) { put_ms_nb(val, success); }

// CHECK-LABEL: define dso_local void @_Z11test_put_msDv8_7float16(
// CHECK-SAME: <8 x half> noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR1]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x half> [[VAL]] to <4 x i32>
// CHECK-NEXT:    [[VECEXT_I_I_I6_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 0
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I6_1_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 1
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_1_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I6_2_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 2
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_2_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I]], i32 0)
// CHECK-NEXT:    ret void
//
void test_put_ms(v8float16 val) { put_ms(val); }

// CHECK-LABEL: define dso_local void @_Z11test_put_msDv8_7float16i(
// CHECK-SAME: <8 x half> noundef [[VAL:%.*]], i32 noundef [[TLAST:%.*]]) local_unnamed_addr #[[ATTR1]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x half> [[VAL]] to <4 x i32>
// CHECK-NEXT:    [[VECEXT_I_I_I6_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 0
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I6_1_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 1
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_1_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I6_2_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 2
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_2_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I]], i32 [[TLAST]])
// CHECK-NEXT:    ret void
//
void test_put_ms(v8float16 val, int tlast) { put_ms(val, tlast); }

// CHECK-LABEL: define dso_local void @_Z11test_put_msDv8_8bfloat16(
// CHECK-SAME: <8 x bfloat> noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR1]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x bfloat> [[VAL]] to <4 x i32>
// CHECK-NEXT:    [[VECEXT_I_I_I6_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 0
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I6_1_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 1
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_1_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I6_2_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 2
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_2_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I]], i32 0)
// CHECK-NEXT:    ret void
//
void test_put_ms(v8bfloat16 val) { put_ms(val); }

// CHECK-LABEL: define dso_local void @_Z11test_put_msDv8_8bfloat16i(
// CHECK-SAME: <8 x bfloat> noundef [[VAL:%.*]], i32 noundef [[TLAST:%.*]]) local_unnamed_addr #[[ATTR1]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x bfloat> [[VAL]] to <4 x i32>
// CHECK-NEXT:    [[VECEXT_I_I_I6_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 0
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I6_1_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 1
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_1_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I6_2_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 2
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_2_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I_I:%.*]] = extractelement <4 x i32> [[TMP0]], i64 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I]], i32 [[TLAST]])
// CHECK-NEXT:    ret void
//
void test_put_ms(v8bfloat16 val, int tlast) { put_ms(val, tlast); }

// CHECK-LABEL: define dso_local void @_Z11test_put_msDv16_7float16(
// CHECK-SAME: <16 x half> noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR1]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x half> [[VAL]] to <8 x i32>
// CHECK-NEXT:    [[VECEXT_I_I_I6_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 0
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I6_1_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 1
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_1_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I6_2_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 2
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_2_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I6_3_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_3_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I6_4_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 4
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_4_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I6_5_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 5
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_5_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I6_6_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 6
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_6_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 7
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I]], i32 0)
// CHECK-NEXT:    ret void
//
void test_put_ms(v16float16 val) { put_ms(val); }

// CHECK-LABEL: define dso_local void @_Z11test_put_msDv16_7float16i(
// CHECK-SAME: <16 x half> noundef [[VAL:%.*]], i32 noundef [[TLAST:%.*]]) local_unnamed_addr #[[ATTR1]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x half> [[VAL]] to <8 x i32>
// CHECK-NEXT:    [[VECEXT_I_I_I6_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 0
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I6_1_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 1
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_1_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I6_2_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 2
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_2_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I6_3_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_3_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I6_4_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 4
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_4_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I6_5_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 5
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_5_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I6_6_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 6
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I6_6_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I_I:%.*]] = extractelement <8 x i32> [[TMP0]], i64 7
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I]], i32 [[TLAST]])
// CHECK-NEXT:    ret void
//
void test_put_ms(v16float16 val, int tlast) { put_ms(val, tlast); }

// CHECK-LABEL: define dso_local void @_Z11test_put_msDv32_7float16(
// CHECK-SAME: <32 x half> noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR1]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x half> [[VAL]] to <16 x i32>
// CHECK-NEXT:    [[VECEXT_I_I_I5_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 0
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_1_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 1
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_1_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_2_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 2
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_2_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_3_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_3_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_4_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 4
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_4_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_5_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 5
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_5_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_6_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 6
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_6_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_7_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 7
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_7_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_8_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 8
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_8_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_9_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 9
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_9_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_10_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 10
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_10_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_11_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 11
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_11_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_12_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 12
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_12_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_13_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 13
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_13_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_14_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 14
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_14_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I]], i32 0)
// CHECK-NEXT:    ret void
//
void test_put_ms(v32float16 val) { put_ms(val); }

// CHECK-LABEL: define dso_local void @_Z11test_put_msDv32_7float16i(
// CHECK-SAME: <32 x half> noundef [[VAL:%.*]], i32 noundef [[TLAST:%.*]]) local_unnamed_addr #[[ATTR1]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x half> [[VAL]] to <16 x i32>
// CHECK-NEXT:    [[VECEXT_I_I_I5_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 0
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_1_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 1
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_1_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_2_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 2
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_2_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_3_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_3_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_4_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 4
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_4_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_5_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 5
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_5_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_6_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 6
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_6_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_7_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 7
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_7_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_8_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 8
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_8_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_9_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 9
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_9_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_10_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 10
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_10_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_11_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 11
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_11_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_12_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 12
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_12_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_13_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 13
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_13_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_14_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 14
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_14_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I_I:%.*]] = extractelement <16 x i32> [[TMP0]], i64 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I]], i32 [[TLAST]])
// CHECK-NEXT:    ret void
//
void test_put_ms(v32float16 val, int tlast) { put_ms(val, tlast); }

// CHECK-LABEL: define dso_local void @_Z11test_put_msDv64_7float16ii(
// CHECK-SAME: <64 x half> noundef [[VAL:%.*]], i32 noundef [[EN:%.*]], i32 noundef [[TLAST:%.*]]) local_unnamed_addr #[[ATTR1]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x half> [[VAL]] to <32 x i32>
// CHECK-NEXT:    [[VECEXT_I_I_I5_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 0
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_I_I_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_1_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 1
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_1_I_I_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_2_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 2
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_2_I_I_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_3_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 3
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_3_I_I_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_4_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 4
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_4_I_I_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_5_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 5
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_5_I_I_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_6_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 6
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_6_I_I_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_7_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 7
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_7_I_I_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_8_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 8
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_8_I_I_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_9_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 9
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_9_I_I_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_10_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 10
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_10_I_I_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_11_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 11
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_11_I_I_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_12_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 12
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_12_I_I_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_13_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 13
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_13_I_I_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_14_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 14
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_14_I_I_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I_I_I_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 15
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_I_I4_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 16
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_I_I4_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_1_I_I5_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 17
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_1_I_I5_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_2_I_I6_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 18
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_2_I_I6_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_3_I_I7_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 19
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_3_I_I7_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_4_I_I8_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 20
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_4_I_I8_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_5_I_I9_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 21
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_5_I_I9_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_6_I_I10_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 22
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_6_I_I10_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_7_I_I11_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 23
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_7_I_I11_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_8_I_I12_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 24
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_8_I_I12_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_9_I_I13_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 25
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_9_I_I13_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_10_I_I14_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 26
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_10_I_I14_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_11_I_I15_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 27
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_11_I_I15_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_12_I_I16_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 28
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_12_I_I16_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_13_I_I17_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 29
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_13_I_I17_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I5_14_I_I18_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 30
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I5_14_I_I18_I]], i32 0)
// CHECK-NEXT:    [[VECEXT_I_I_I_I_I19_I:%.*]] = extractelement <32 x i32> [[TMP0]], i64 31
// CHECK-NEXT:    tail call void @llvm.aie2ps.put.ms(i32 [[VECEXT_I_I_I_I_I19_I]], i32 [[TLAST]])
// CHECK-NEXT:    ret void
//
void test_put_ms(v64float16 val, int en, int tlast) { put_ms(val, en, tlast); }

// CHECK-LABEL: define dso_local noundef <2 x half> @_Z21test_get_ss_v2float16v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR1]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast i32 [[TMP1]] to <2 x half>
// CHECK-NEXT:    ret <2 x half> [[TMP2]]
//
v2float16 test_get_ss_v2float16() { return get_ss_v2float16(); }

//
// CHECK-LABEL: define dso_local noundef <2 x half> @_Z21test_get_ss_v2float16Rb(
// CHECK-SAME: ptr nonnull writeonly align 1 captures(none) dereferenceable(1) initializes((0, 1)) [[TLAST:%.*]]) local_unnamed_addr #[[ATTR1]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <2 x half>
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// CHECK-NEXT:    [[STOREDV_I:%.*]] = and i8 [[TMP4]], 1
// CHECK-NEXT:    store i8 [[STOREDV_I]], ptr [[TLAST]], align 1, !tbaa [[TBAA2]]
// CHECK-NEXT:    ret <2 x half> [[TMP3]]
//
v2float16 test_get_ss_v2float16(bool &tlast) { return get_ss_v2float16(tlast); }

// CHECK-LABEL: define dso_local noundef <2 x half> @_Z24test_get_ss_nb_v2float16Rb(
// CHECK-SAME: ptr nonnull writeonly align 1 captures(none) dereferenceable(1) initializes((0, 1)) [[SUCCESS:%.*]]) local_unnamed_addr #[[ATTR1]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss.nb()
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <2 x half>
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// CHECK-NEXT:    [[TMP5:%.*]] = lshr i8 [[TMP4]], 1
// CHECK-NEXT:    [[STOREDV_I:%.*]] = and i8 [[TMP5]], 1
// CHECK-NEXT:    store i8 [[STOREDV_I]], ptr [[SUCCESS]], align 1, !tbaa [[TBAA2]]
// CHECK-NEXT:    ret <2 x half> [[TMP3]]
//
v2float16 test_get_ss_nb_v2float16(bool &success) { return get_ss_nb_v2float16(success); }

// CHECK-LABEL: define dso_local noundef <2 x half> @_Z24test_get_ss_nb_v2float16RbS_(
// CHECK-SAME: ptr nonnull writeonly align 1 captures(none) dereferenceable(1) initializes((0, 1)) [[SUCCESS:%.*]], ptr nonnull writeonly align 1 captures(none) dereferenceable(1) initializes((0, 1)) [[TLAST:%.*]]) local_unnamed_addr #[[ATTR1]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss.nb()
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast i32 [[TMP2]] to <2 x half>
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP1]] to i8
// CHECK-NEXT:    [[STOREDV_I:%.*]] = and i8 [[TMP4]], 1
// CHECK-NEXT:    store i8 [[STOREDV_I]], ptr [[TLAST]], align 1, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP5:%.*]] = lshr i8 [[TMP4]], 1
// CHECK-NEXT:    [[STOREDV3_I:%.*]] = and i8 [[TMP5]], 1
// CHECK-NEXT:    store i8 [[STOREDV3_I]], ptr [[SUCCESS]], align 1, !tbaa [[TBAA2]]
// CHECK-NEXT:    ret <2 x half> [[TMP3]]
//
v2float16 test_get_ss_nb_v2float16(bool &success, bool &tlast) {
  return get_ss_nb_v2float16(success, tlast);
}

// CHECK-LABEL: define dso_local noundef <8 x half> @_Z21test_get_ss_v8float16v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR1]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = insertelement <4 x i32> poison, i32 [[TMP1]], i64 0
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { i32, i32 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = insertelement <4 x i32> [[TMP2]], i32 [[TMP4]], i64 1
// CHECK-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// CHECK-NEXT:    [[TMP8:%.*]] = insertelement <4 x i32> [[TMP5]], i32 [[TMP7]], i64 2
// CHECK-NEXT:    [[TMP9:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { i32, i32 } [[TMP9]], 0
// CHECK-NEXT:    [[SHUFFLE_I_I_I:%.*]] = insertelement <4 x i32> [[TMP8]], i32 [[TMP10]], i64 3
// CHECK-NEXT:    [[TMP11:%.*]] = bitcast <4 x i32> [[SHUFFLE_I_I_I]] to <8 x half>
// CHECK-NEXT:    ret <8 x half> [[TMP11]]
//
v8float16 test_get_ss_v8float16() { return get_ss_v8float16(); }

// CHECK-LABEL: define dso_local noundef <16 x half> @_Z22test_get_ss_v16float16v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR1]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// CHECK-NEXT:    [[VECINS_I_I10_I:%.*]] = insertelement <16 x i32> poison, i32 [[TMP1]], i64 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// CHECK-NEXT:    [[VECINS_I_I10_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_I]], i32 [[TMP3]], i64 1
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[VECINS_I_I10_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_1_I]], i32 [[TMP5]], i64 2
// CHECK-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// CHECK-NEXT:    [[VECINS_I_I10_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_2_I]], i32 [[TMP7]], i64 3
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// CHECK-NEXT:    [[VECINS_I_I10_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_3_I]], i32 [[TMP9]], i64 4
// CHECK-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// CHECK-NEXT:    [[VECINS_I_I10_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_4_I]], i32 [[TMP11]], i64 5
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// CHECK-NEXT:    [[VECINS_I_I10_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_5_I]], i32 [[TMP13]], i64 6
// CHECK-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// CHECK-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I10_6_I]], i32 [[TMP15]], i64 7
// CHECK-NEXT:    [[SHUFFLE_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP16:%.*]] = bitcast <8 x i32> [[SHUFFLE_I_I_I]] to <16 x half>
// CHECK-NEXT:    ret <16 x half> [[TMP16]]
//
v16float16 test_get_ss_v16float16() { return get_ss_v16float16(); }

// CHECK-LABEL: define dso_local noundef <32 x half> @_Z22test_get_ss_v32float16v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR1]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// CHECK-NEXT:    [[VECINS_I_I9_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// CHECK-NEXT:    [[VECINS_I_I9_1_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I]], i32 [[TMP3]], i64 1
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[VECINS_I_I9_2_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I]], i32 [[TMP5]], i64 2
// CHECK-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// CHECK-NEXT:    [[VECINS_I_I9_3_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I]], i32 [[TMP7]], i64 3
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// CHECK-NEXT:    [[VECINS_I_I9_4_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I]], i32 [[TMP9]], i64 4
// CHECK-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// CHECK-NEXT:    [[VECINS_I_I9_5_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I]], i32 [[TMP11]], i64 5
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// CHECK-NEXT:    [[VECINS_I_I9_6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I]], i32 [[TMP13]], i64 6
// CHECK-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// CHECK-NEXT:    [[VECINS_I_I9_7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I]], i32 [[TMP15]], i64 7
// CHECK-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// CHECK-NEXT:    [[VECINS_I_I9_8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I]], i32 [[TMP17]], i64 8
// CHECK-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// CHECK-NEXT:    [[VECINS_I_I9_9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I]], i32 [[TMP19]], i64 9
// CHECK-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// CHECK-NEXT:    [[VECINS_I_I9_10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I]], i32 [[TMP21]], i64 10
// CHECK-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// CHECK-NEXT:    [[VECINS_I_I9_11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I]], i32 [[TMP23]], i64 11
// CHECK-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// CHECK-NEXT:    [[VECINS_I_I9_12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I]], i32 [[TMP25]], i64 12
// CHECK-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// CHECK-NEXT:    [[VECINS_I_I9_13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I]], i32 [[TMP27]], i64 13
// CHECK-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// CHECK-NEXT:    [[VECINS_I_I9_14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I]], i32 [[TMP29]], i64 14
// CHECK-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// CHECK-NEXT:    [[VECINS_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I]], i32 [[TMP31]], i64 15
// CHECK-NEXT:    [[TMP32:%.*]] = bitcast <16 x i32> [[VECINS_I_I_I]] to <32 x half>
// CHECK-NEXT:    ret <32 x half> [[TMP32]]
//
v32float16 test_get_ss_v32float16() { return get_ss_v32float16(); }

// CHECK-LABEL: define dso_local noundef <64 x half> @_Z22test_get_ss_v64float16v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR1]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i32 } [[TMP0]], 0
// CHECK-NEXT:    [[VECINS_I_I9_I_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP1]], i64 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i32 } [[TMP2]], 0
// CHECK-NEXT:    [[VECINS_I_I9_1_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I_I]], i32 [[TMP3]], i64 1
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i32 } [[TMP4]], 0
// CHECK-NEXT:    [[VECINS_I_I9_2_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I_I]], i32 [[TMP5]], i64 2
// CHECK-NEXT:    [[TMP6:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { i32, i32 } [[TMP6]], 0
// CHECK-NEXT:    [[VECINS_I_I9_3_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I_I]], i32 [[TMP7]], i64 3
// CHECK-NEXT:    [[TMP8:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { i32, i32 } [[TMP8]], 0
// CHECK-NEXT:    [[VECINS_I_I9_4_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I_I]], i32 [[TMP9]], i64 4
// CHECK-NEXT:    [[TMP10:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { i32, i32 } [[TMP10]], 0
// CHECK-NEXT:    [[VECINS_I_I9_5_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I_I]], i32 [[TMP11]], i64 5
// CHECK-NEXT:    [[TMP12:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i32 } [[TMP12]], 0
// CHECK-NEXT:    [[VECINS_I_I9_6_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I_I]], i32 [[TMP13]], i64 6
// CHECK-NEXT:    [[TMP14:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { i32, i32 } [[TMP14]], 0
// CHECK-NEXT:    [[VECINS_I_I9_7_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I_I]], i32 [[TMP15]], i64 7
// CHECK-NEXT:    [[TMP16:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { i32, i32 } [[TMP16]], 0
// CHECK-NEXT:    [[VECINS_I_I9_8_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I_I]], i32 [[TMP17]], i64 8
// CHECK-NEXT:    [[TMP18:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { i32, i32 } [[TMP18]], 0
// CHECK-NEXT:    [[VECINS_I_I9_9_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I_I]], i32 [[TMP19]], i64 9
// CHECK-NEXT:    [[TMP20:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i32 } [[TMP20]], 0
// CHECK-NEXT:    [[VECINS_I_I9_10_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I_I]], i32 [[TMP21]], i64 10
// CHECK-NEXT:    [[TMP22:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP23:%.*]] = extractvalue { i32, i32 } [[TMP22]], 0
// CHECK-NEXT:    [[VECINS_I_I9_11_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I_I]], i32 [[TMP23]], i64 11
// CHECK-NEXT:    [[TMP24:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP25:%.*]] = extractvalue { i32, i32 } [[TMP24]], 0
// CHECK-NEXT:    [[VECINS_I_I9_12_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I_I]], i32 [[TMP25]], i64 12
// CHECK-NEXT:    [[TMP26:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP27:%.*]] = extractvalue { i32, i32 } [[TMP26]], 0
// CHECK-NEXT:    [[VECINS_I_I9_13_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I_I]], i32 [[TMP27]], i64 13
// CHECK-NEXT:    [[TMP28:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i32 } [[TMP28]], 0
// CHECK-NEXT:    [[VECINS_I_I9_14_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I_I]], i32 [[TMP29]], i64 14
// CHECK-NEXT:    [[TMP30:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP31:%.*]] = extractvalue { i32, i32 } [[TMP30]], 0
// CHECK-NEXT:    [[VECINS_I_I_I_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I_I]], i32 [[TMP31]], i64 15
// CHECK-NEXT:    [[TMP32:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP33:%.*]] = extractvalue { i32, i32 } [[TMP32]], 0
// CHECK-NEXT:    [[VECINS_I_I9_I5_I:%.*]] = insertelement <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, i32 [[TMP33]], i64 0
// CHECK-NEXT:    [[TMP34:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP35:%.*]] = extractvalue { i32, i32 } [[TMP34]], 0
// CHECK-NEXT:    [[VECINS_I_I9_1_I6_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_I5_I]], i32 [[TMP35]], i64 1
// CHECK-NEXT:    [[TMP36:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP37:%.*]] = extractvalue { i32, i32 } [[TMP36]], 0
// CHECK-NEXT:    [[VECINS_I_I9_2_I7_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_1_I6_I]], i32 [[TMP37]], i64 2
// CHECK-NEXT:    [[TMP38:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP39:%.*]] = extractvalue { i32, i32 } [[TMP38]], 0
// CHECK-NEXT:    [[VECINS_I_I9_3_I8_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_2_I7_I]], i32 [[TMP39]], i64 3
// CHECK-NEXT:    [[TMP40:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP41:%.*]] = extractvalue { i32, i32 } [[TMP40]], 0
// CHECK-NEXT:    [[VECINS_I_I9_4_I9_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_3_I8_I]], i32 [[TMP41]], i64 4
// CHECK-NEXT:    [[TMP42:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP43:%.*]] = extractvalue { i32, i32 } [[TMP42]], 0
// CHECK-NEXT:    [[VECINS_I_I9_5_I10_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_4_I9_I]], i32 [[TMP43]], i64 5
// CHECK-NEXT:    [[TMP44:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP45:%.*]] = extractvalue { i32, i32 } [[TMP44]], 0
// CHECK-NEXT:    [[VECINS_I_I9_6_I11_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_5_I10_I]], i32 [[TMP45]], i64 6
// CHECK-NEXT:    [[TMP46:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP47:%.*]] = extractvalue { i32, i32 } [[TMP46]], 0
// CHECK-NEXT:    [[VECINS_I_I9_7_I12_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_6_I11_I]], i32 [[TMP47]], i64 7
// CHECK-NEXT:    [[TMP48:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP49:%.*]] = extractvalue { i32, i32 } [[TMP48]], 0
// CHECK-NEXT:    [[VECINS_I_I9_8_I13_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_7_I12_I]], i32 [[TMP49]], i64 8
// CHECK-NEXT:    [[TMP50:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP51:%.*]] = extractvalue { i32, i32 } [[TMP50]], 0
// CHECK-NEXT:    [[VECINS_I_I9_9_I14_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_8_I13_I]], i32 [[TMP51]], i64 9
// CHECK-NEXT:    [[TMP52:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP53:%.*]] = extractvalue { i32, i32 } [[TMP52]], 0
// CHECK-NEXT:    [[VECINS_I_I9_10_I15_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_9_I14_I]], i32 [[TMP53]], i64 10
// CHECK-NEXT:    [[TMP54:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP55:%.*]] = extractvalue { i32, i32 } [[TMP54]], 0
// CHECK-NEXT:    [[VECINS_I_I9_11_I16_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_10_I15_I]], i32 [[TMP55]], i64 11
// CHECK-NEXT:    [[TMP56:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP57:%.*]] = extractvalue { i32, i32 } [[TMP56]], 0
// CHECK-NEXT:    [[VECINS_I_I9_12_I17_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_11_I16_I]], i32 [[TMP57]], i64 12
// CHECK-NEXT:    [[TMP58:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP59:%.*]] = extractvalue { i32, i32 } [[TMP58]], 0
// CHECK-NEXT:    [[VECINS_I_I9_13_I18_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_12_I17_I]], i32 [[TMP59]], i64 13
// CHECK-NEXT:    [[TMP60:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP61:%.*]] = extractvalue { i32, i32 } [[TMP60]], 0
// CHECK-NEXT:    [[VECINS_I_I9_14_I19_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_13_I18_I]], i32 [[TMP61]], i64 14
// CHECK-NEXT:    [[TMP62:%.*]] = tail call { i32, i32 } @llvm.aie2ps.get.ss()
// CHECK-NEXT:    [[TMP63:%.*]] = extractvalue { i32, i32 } [[TMP62]], 0
// CHECK-NEXT:    [[VECINS_I_I_I20_I:%.*]] = insertelement <16 x i32> [[VECINS_I_I9_14_I19_I]], i32 [[TMP63]], i64 15
// CHECK-NEXT:    [[SHUFFLE2_I_I_I:%.*]] = shufflevector <16 x i32> [[VECINS_I_I_I_I]], <16 x i32> [[VECINS_I_I_I20_I]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP64:%.*]] = bitcast <32 x i32> [[SHUFFLE2_I_I_I]] to <64 x half>
// CHECK-NEXT:    ret <64 x half> [[TMP64]]
//
v64float16 test_get_ss_v64float16() { return get_ss_v64float16(); }
//.
// CHECK: [[TBAA2]] = !{[[META3:![0-9]+]], [[META3]], i64 0}
// CHECK: [[META3]] = !{!"bool", [[META4:![0-9]+]], i64 0}
// CHECK: [[META4]] = !{!"omnipotent char", [[META5:![0-9]+]], i64 0}
// CHECK: [[META5]] = !{!"Simple C++ TBAA"}
//.
