// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 4
//===- aie2ps-undef-intrinsic.cpp -------------------------------*- C++ -*-===//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//
// RUN: %clang -O2 %s --target=aie2ps -nostdlibinc -S -emit-llvm -o - | FileCheck %s

// CHECK-LABEL: define dso_local noundef <2 x float> @_Z18test_undef_v2floatv(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <2 x float> undef
//
v2float test_undef_v2float() { return undef_v2float(); }

// CHECK-LABEL: define dso_local noundef <16 x i8> @_Z18test_undef_v32int4v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <16 x i8> undef
//
v32int4 test_undef_v32int4() { return undef_v32int4(); }
// CHECK-LABEL: define dso_local noundef <16 x i8> @_Z19test_undef_v32uint4v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <16 x i8> undef
//
v32uint4 test_undef_v32uint4() { return undef_v32uint4(); }
// CHECK-LABEL: define dso_local noundef <16 x i8> @_Z18test_undef_v16int8v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <16 x i8> undef
//
v16int8 test_undef_v16int8() { return undef_v16int8(); }
// CHECK-LABEL: define dso_local noundef <16 x i8> @_Z19test_undef_v16uint8v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <16 x i8> undef
//
v16uint8 test_undef_v16uint8() { return undef_v16uint8(); }
// CHECK-LABEL: define dso_local noundef <8 x i16> @_Z18test_undef_v8int16v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <8 x i16> undef
//
v8int16 test_undef_v8int16() { return undef_v8int16(); }
// CHECK-LABEL: define dso_local noundef <8 x i16> @_Z19test_undef_v8uint16v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <8 x i16> undef
//
v8uint16 test_undef_v8uint16() { return undef_v8uint16(); }
// CHECK-LABEL: define dso_local noundef <4 x i32> @_Z18test_undef_v4int32v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <4 x i32> undef
//
v4int32 test_undef_v4int32() { return undef_v4int32(); }
// CHECK-LABEL: define dso_local noundef <4 x i32> @_Z19test_undef_v4uint32v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <4 x i32> undef
//
v4uint32 test_undef_v4uint32() { return undef_v4uint32(); }
// CHECK-LABEL: define dso_local noundef <8 x bfloat> @_Z21test_undef_v8bfloat16v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <8 x bfloat> undef
//
v8bfloat16 test_undef_v8bfloat16() { return undef_v8bfloat16(); }
// CHECK-LABEL: define dso_local noundef <8 x half> @_Z20test_undef_v8float16v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <8 x half> undef
//
v8float16 test_undef_v8float16() { return undef_v8float16(); }
// CHECK-LABEL: define dso_local %struct.v16bfloat8 @_Z21test_undef_v16bfloat8v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret [[STRUCT_V16BFLOAT8:%.*]] undef
//
v16bfloat8 test_undef_v16bfloat8() { return undef_v16bfloat8(); }
// CHECK-LABEL: define dso_local %struct.v16float8 @_Z20test_undef_v16float8v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret [[STRUCT_V16FLOAT8:%.*]] undef
//
v16float8 test_undef_v16float8() { return undef_v16float8(); }
// CHECK-LABEL: define dso_local noundef <4 x float> @_Z18test_undef_v4floatv(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <4 x float> undef
//
v4float test_undef_v4float() { return undef_v4float(); }

// CHECK-LABEL: define dso_local noundef <32 x i8> @_Z18test_undef_v64int4v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <32 x i8> undef
//
v64int4 test_undef_v64int4() { return undef_v64int4(); }
// CHECK-LABEL: define dso_local noundef <32 x i8> @_Z19test_undef_v64uint4v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <32 x i8> undef
//
v64uint4 test_undef_v64uint4() { return undef_v64uint4(); }
// CHECK-LABEL: define dso_local noundef <32 x i8> @_Z18test_undef_v32int8v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <32 x i8> undef
//
v32int8 test_undef_v32int8() { return undef_v32int8(); }
// CHECK-LABEL: define dso_local noundef <32 x i8> @_Z19test_undef_v32uint8v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <32 x i8> undef
//
v32uint8 test_undef_v32uint8() { return undef_v32uint8(); }
// CHECK-LABEL: define dso_local noundef <16 x i16> @_Z19test_undef_v16int16v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <16 x i16> undef
//
v16int16 test_undef_v16int16() { return undef_v16int16(); }
// CHECK-LABEL: define dso_local noundef <16 x i16> @_Z20test_undef_v16uint16v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <16 x i16> undef
//
v16uint16 test_undef_v16uint16() { return undef_v16uint16(); }
// CHECK-LABEL: define dso_local noundef <8 x i32> @_Z18test_undef_v8int32v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <8 x i32> undef
//
v8int32 test_undef_v8int32() { return undef_v8int32(); }
// CHECK-LABEL: define dso_local noundef <8 x i32> @_Z19test_undef_v8uint32v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <8 x i32> undef
//
v8uint32 test_undef_v8uint32() { return undef_v8uint32(); }
// CHECK-LABEL: define dso_local inreg noundef <8 x float> @_Z21test_undef_v8accfloatv(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <8 x float> undef
//
v8accfloat test_undef_v8accfloat() { return undef_v8accfloat(); }
// CHECK-LABEL: define dso_local inreg noundef <8 x i32> @_Z18test_undef_v8acc32v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <8 x i32> undef
//
v8acc32 test_undef_v8acc32() { return undef_v8acc32(); }
// CHECK-LABEL: define dso_local inreg noundef <4 x i64> @_Z18test_undef_v4acc64v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <4 x i64> undef
//
v4acc64 test_undef_v4acc64() { return undef_v4acc64(); }
// CHECK-LABEL: define dso_local noundef <16 x bfloat> @_Z22test_undef_v16bfloat16v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <16 x bfloat> undef
//
v16bfloat16 test_undef_v16bfloat16() { return undef_v16bfloat16(); }
// CHECK-LABEL: define dso_local noundef <16 x half> @_Z21test_undef_v16float16v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <16 x half> undef
//
v16float16 test_undef_v16float16() { return undef_v16float16(); }
// CHECK-LABEL: define dso_local %struct.v32bfloat8 @_Z21test_undef_v32bfloat8v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret [[STRUCT_V32BFLOAT8:%.*]] undef
//
v32bfloat8 test_undef_v32bfloat8() { return undef_v32bfloat8(); }
// CHECK-LABEL: define dso_local %struct.v32float8 @_Z20test_undef_v32float8v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret [[STRUCT_V32FLOAT8:%.*]] undef
//
v32float8 test_undef_v32float8() { return undef_v32float8(); }
// CHECK-LABEL: define dso_local noundef <8 x float> @_Z18test_undef_v8floatv(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <8 x float> undef
//
v8float test_undef_v8float() { return undef_v8float(); }

// CHECK-LABEL: define dso_local %struct.v32mx9 @_Z17test_undef_v32mx9v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret [[STRUCT_V32MX9:%.*]] undef
//
v32mx9 test_undef_v32mx9() { return undef_v32mx9(); }

// CHECK-LABEL: define dso_local %struct.v64mx6 @_Z17test_undef_v64mx6v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret [[STRUCT_V64MX6:%.*]] undef
//
v64mx6 test_undef_v64mx6() { return undef_v64mx6(); }
// CHECK-LABEL: define dso_local %struct.v64mx4 @_Z17test_undef_v64mx4v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret [[STRUCT_V64MX4:%.*]] undef
//
v64mx4 test_undef_v64mx4() { return undef_v64mx4(); }

// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z19test_undef_v128int4v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <64 x i8> undef
//
v128int4 test_undef_v128int4() { return undef_v128int4(); }
// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z20test_undef_v128uint4v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <64 x i8> undef
//
v128uint4 test_undef_v128uint4() { return undef_v128uint4(); }
// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z18test_undef_v64int8v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <64 x i8> undef
//
v64int8 test_undef_v64int8() { return undef_v64int8(); }
// CHECK-LABEL: define dso_local noundef <64 x i8> @_Z19test_undef_v64uint8v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <64 x i8> undef
//
v64uint8 test_undef_v64uint8() { return undef_v64uint8(); }
// CHECK-LABEL: define dso_local noundef <32 x i16> @_Z19test_undef_v32int16v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <32 x i16> undef
//
v32int16 test_undef_v32int16() { return undef_v32int16(); }
// CHECK-LABEL: define dso_local noundef <32 x i16> @_Z20test_undef_v32uint16v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <32 x i16> undef
//
v32uint16 test_undef_v32uint16() { return undef_v32uint16(); }
// CHECK-LABEL: define dso_local noundef <16 x i32> @_Z19test_undef_v16int32v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <16 x i32> undef
//
v16int32 test_undef_v16int32() { return undef_v16int32(); }
// CHECK-LABEL: define dso_local noundef <16 x i32> @_Z20test_undef_v16uint32v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <16 x i32> undef
//
v16uint32 test_undef_v16uint32() { return undef_v16uint32(); }
// CHECK-LABEL: define dso_local inreg noundef <16 x float> @_Z22test_undef_v16accfloatv(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <16 x float> undef
//
v16accfloat test_undef_v16accfloat() { return undef_v16accfloat(); }
// CHECK-LABEL: define dso_local inreg noundef <16 x i32> @_Z19test_undef_v16acc32v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <16 x i32> undef
//
v16acc32 test_undef_v16acc32() { return undef_v16acc32(); }
// CHECK-LABEL: define dso_local inreg noundef <8 x i64> @_Z18test_undef_v8acc64v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <8 x i64> undef
//
v8acc64 test_undef_v8acc64() { return undef_v8acc64(); }
// CHECK-LABEL: define dso_local noundef <32 x bfloat> @_Z22test_undef_v32bfloat16v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <32 x bfloat> undef
//
v32bfloat16 test_undef_v32bfloat16() { return undef_v32bfloat16(); }
// CHECK-LABEL: define dso_local noundef <32 x half> @_Z21test_undef_v32float16v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <32 x half> undef
//
v32float16 test_undef_v32float16() { return undef_v32float16(); }
// CHECK-LABEL: define dso_local %struct.v64bfloat8 @_Z21test_undef_v64bfloat8v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret [[STRUCT_V64BFLOAT8:%.*]] undef
//
v64bfloat8 test_undef_v64bfloat8() { return undef_v64bfloat8(); }
// CHECK-LABEL: define dso_local %struct.v64float8 @_Z20test_undef_v64float8v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret [[STRUCT_V64FLOAT8:%.*]] undef
//
v64float8 test_undef_v64float8() { return undef_v64float8(); }
// CHECK-LABEL: define dso_local noundef <16 x float> @_Z19test_undef_v16floatv(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <16 x float> undef
//
v16float test_undef_v16float() { return undef_v16float(); }

// CHECK-LABEL: define dso_local %struct.v64mx9 @_Z17test_undef_v64mx9v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret [[STRUCT_V64MX9:%.*]] undef
//
v64mx9 test_undef_v64mx9() { return undef_v64mx9(); }

// CHECK-LABEL: define dso_local %struct.v128mx6 @_Z18test_undef_v128mx6v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret [[STRUCT_V128MX6:%.*]] undef
//
v128mx6 test_undef_v128mx6() { return undef_v128mx6(); }
// CHECK-LABEL: define dso_local %struct.v128mx4 @_Z18test_undef_v128mx4v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret [[STRUCT_V128MX4:%.*]] undef
//
v128mx4 test_undef_v128mx4() { return undef_v128mx4(); }

// CHECK-LABEL: define dso_local noundef <128 x i8> @_Z19test_undef_v256int4v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <128 x i8> undef
//
v256int4 test_undef_v256int4() { return undef_v256int4(); }
// CHECK-LABEL: define dso_local noundef <128 x i8> @_Z20test_undef_v256uint4v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <128 x i8> undef
//
v256uint4 test_undef_v256uint4() { return undef_v256uint4(); }
// CHECK-LABEL: define dso_local noundef <128 x i8> @_Z19test_undef_v128int8v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <128 x i8> undef
//
v128int8 test_undef_v128int8() { return undef_v128int8(); }
// CHECK-LABEL: define dso_local noundef <128 x i8> @_Z20test_undef_v128uint8v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <128 x i8> undef
//
v128uint8 test_undef_v128uint8() { return undef_v128uint8(); }
// CHECK-LABEL: define dso_local noundef <64 x i16> @_Z19test_undef_v64int16v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <64 x i16> undef
//
v64int16 test_undef_v64int16() { return undef_v64int16(); }
// CHECK-LABEL: define dso_local noundef <64 x i16> @_Z20test_undef_v64uint16v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <64 x i16> undef
//
v64uint16 test_undef_v64uint16() { return undef_v64uint16(); }
// CHECK-LABEL: define dso_local noundef <32 x i32> @_Z19test_undef_v32int32v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <32 x i32> undef
//
v32int32 test_undef_v32int32() { return undef_v32int32(); }
// CHECK-LABEL: define dso_local noundef <32 x i32> @_Z20test_undef_v32uint32v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <32 x i32> undef
//
v32uint32 test_undef_v32uint32() { return undef_v32uint32(); }
// CHECK-LABEL: define dso_local inreg noundef <32 x float> @_Z22test_undef_v32accfloatv(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <32 x float> undef
//
v32accfloat test_undef_v32accfloat() { return undef_v32accfloat(); }
// CHECK-LABEL: define dso_local inreg noundef <32 x i32> @_Z19test_undef_v32acc32v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <32 x i32> undef
//
v32acc32 test_undef_v32acc32() { return undef_v32acc32(); }
// CHECK-LABEL: define dso_local inreg noundef <16 x i64> @_Z19test_undef_v16acc64v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <16 x i64> undef
//
v16acc64 test_undef_v16acc64() { return undef_v16acc64(); }
// CHECK-LABEL: define dso_local noundef <64 x bfloat> @_Z22test_undef_v64bfloat16v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <64 x bfloat> undef
//
v64bfloat16 test_undef_v64bfloat16() { return undef_v64bfloat16(); }
// CHECK-LABEL: define dso_local noundef <64 x half> @_Z21test_undef_v64float16v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <64 x half> undef
//
v64float16 test_undef_v64float16() { return undef_v64float16(); }
// CHECK-LABEL: define dso_local %struct.v128bfloat8 @_Z22test_undef_v128bfloat8v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret [[STRUCT_V128BFLOAT8:%.*]] undef
//
v128bfloat8 test_undef_v128bfloat8() { return undef_v128bfloat8(); }
// CHECK-LABEL: define dso_local %struct.v128float8 @_Z21test_undef_v128float8v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret [[STRUCT_V128FLOAT8:%.*]] undef
//
v128float8 test_undef_v128float8() { return undef_v128float8(); }
// CHECK-LABEL: define dso_local noundef <32 x float> @_Z19test_undef_v32floatv(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <32 x float> undef
//
v32float test_undef_v32float() { return undef_v32float(); }

// CHECK-LABEL: define dso_local %struct.v128mx9 @_Z18test_undef_v128mx9v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret [[STRUCT_V128MX9:%.*]] undef
//
v128mx9 test_undef_v128mx9() { return undef_v128mx9(); }

// CHECK-LABEL: define dso_local %struct.v256mx6 @_Z18test_undef_v256mx6v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret [[STRUCT_V256MX6:%.*]] undef
//
v256mx6 test_undef_v256mx6() { return undef_v256mx6(); }
// CHECK-LABEL: define dso_local %struct.v256mx4 @_Z18test_undef_v256mx4v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret [[STRUCT_V256MX4:%.*]] undef
//
v256mx4 test_undef_v256mx4() { return undef_v256mx4(); }

// CHECK-LABEL: define dso_local inreg noundef <64 x float> @_Z22test_undef_v64accfloatv(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <64 x float> undef
//
v64accfloat test_undef_v64accfloat() { return undef_v64accfloat(); }
// CHECK-LABEL: define dso_local inreg noundef <64 x i32> @_Z19test_undef_v64acc32v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <64 x i32> undef
//
v64acc32 test_undef_v64acc32() { return undef_v64acc32(); }
// CHECK-LABEL: define dso_local inreg noundef <32 x i64> @_Z19test_undef_v32acc64v(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <32 x i64> undef
//
v32acc64 test_undef_v32acc64() { return undef_v32acc64(); }
// CHECK-LABEL: define dso_local noundef <64 x float> @_Z19test_undef_v64floatv(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <64 x float> undef
//
v64float test_undef_v64float() { return undef_v64float(); }
