// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 4
//===- test-float.cc ------------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//

// RUN: %clang -O2 %s --target=aie2ps -nostdlibinc -S -emit-llvm -o - | FileCheck %s

// CHECK-LABEL: define dso_local noundef half @_Z12test_float167float16(
// CHECK-SAME: half noundef returned [[A:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret half [[A]]
//
float16 test_float16(float16 a) {
 return a;
}
// CHECK-LABEL: define dso_local %struct.float8 @_Z11test_float86float8(
// CHECK-SAME: [[STRUCT_FLOAT8:%.*]] returned [[A_COERCE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret [[STRUCT_FLOAT8]] [[A_COERCE]]
//
float8 test_float8(float8 a) {
 return a;
}
// CHECK-LABEL: define dso_local %struct.v4float8 @_Z13test_v4float88v4float8(
// CHECK-SAME: [[STRUCT_V4FLOAT8:%.*]] returned [[A_COERCE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret [[STRUCT_V4FLOAT8]] [[A_COERCE]]
//
v4float8 test_v4float8(v4float8 a) {
 return a;
}
// CHECK-LABEL: define dso_local %struct.v8float8 @_Z13test_v8float88v8float8(
// CHECK-SAME: [[STRUCT_V8FLOAT8:%.*]] returned [[A_COERCE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret [[STRUCT_V8FLOAT8]] [[A_COERCE]]
//
v8float8 test_v8float8(v8float8 a) {
 return a;
}
// CHECK-LABEL: define dso_local %struct.v16float8 @_Z14test_v16float89v16float8(
// CHECK-SAME: [[STRUCT_V16FLOAT8:%.*]] returned [[A_COERCE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret [[STRUCT_V16FLOAT8]] [[A_COERCE]]
//
v16float8 test_v16float8(v16float8 a) {
 return a;
}
// CHECK-LABEL: define dso_local %struct.v32float8 @_Z14test_v32float89v32float8(
// CHECK-SAME: [[STRUCT_V32FLOAT8:%.*]] returned [[A_COERCE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret [[STRUCT_V32FLOAT8]] [[A_COERCE]]
//
v32float8 test_v32float8(v32float8 a) {
 return a;
}
// CHECK-LABEL: define dso_local %struct.v64float8 @_Z14test_v64float89v64float8(
// CHECK-SAME: [[STRUCT_V64FLOAT8:%.*]] returned [[A_COERCE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret [[STRUCT_V64FLOAT8]] [[A_COERCE]]
//
v64float8 test_v64float8(v64float8 a) {
 return a;
}
// CHECK-LABEL: define dso_local %struct.v128float8 @_Z15test_v128float810v128float8(
// CHECK-SAME: [[STRUCT_V128FLOAT8:%.*]] returned [[A_COERCE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret [[STRUCT_V128FLOAT8]] [[A_COERCE]]
//
v128float8 test_v128float8(v128float8 a) {
 return a;
}
// CHECK-LABEL: define dso_local %struct.v256float8 @_Z15test_v256float810v256float8(
// CHECK-SAME: [[STRUCT_V256FLOAT8:%.*]] returned [[A_COERCE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret [[STRUCT_V256FLOAT8]] [[A_COERCE]]
//
v256float8 test_v256float8(v256float8 a) {
 return a;
}

// CHECK-LABEL: define dso_local noundef <2 x half> @_Z14test_v2float16Dv2_7float16(
// CHECK-SAME: <2 x half> noundef returned [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <2 x half> [[A]]
//
v2float16 test_v2float16(v2float16 a) {
 return a;
}
// CHECK-LABEL: define dso_local noundef <4 x half> @_Z14test_v4float16Dv4_7float16(
// CHECK-SAME: <4 x half> noundef returned [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <4 x half> [[A]]
//
v4float16 test_v4float16(v4float16 a) {
 return a;
}
// CHECK-LABEL: define dso_local noundef <8 x half> @_Z14test_v8float16Dv8_7float16(
// CHECK-SAME: <8 x half> noundef returned [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <8 x half> [[A]]
//
v8float16 test_v8float16(v8float16 a) {
 return a;
}
// CHECK-LABEL: define dso_local noundef <16 x half> @_Z15test_v16float16Dv16_7float16(
// CHECK-SAME: <16 x half> noundef returned [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <16 x half> [[A]]
//
v16float16 test_v16float16(v16float16 a) {
 return a;
}
// CHECK-LABEL: define dso_local noundef <32 x half> @_Z15test_v32float16Dv32_7float16(
// CHECK-SAME: <32 x half> noundef returned [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <32 x half> [[A]]
//
v32float16 test_v32float16(v32float16 a) {
 return a;
}
// CHECK-LABEL: define dso_local noundef <64 x half> @_Z15test_v64float16Dv64_7float16(
// CHECK-SAME: <64 x half> noundef returned [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <64 x half> [[A]]
//
v64float16 test_v64float16(v64float16 a) {
 return a;
}
// CHECK-LABEL: define dso_local noundef <128 x half> @_Z16test_v128float16Dv128_7float16(
// CHECK-SAME: <128 x half> noundef returned [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret <128 x half> [[A]]
//
v128float16 test_v128float16(v128float16 a) {
 return a;
}

_Static_assert(__alignof(float16) == 2);
