// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 4
//===- test-float.cc ------------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//

// RUN: %clang -O2 %s --target=aie2ps -nostdlibinc -S -emit-llvm -o - | FileCheck %s

// CHECK-LABEL: define dso_local %struct.bfloat8 @_Z12test_bfloat87bfloat8(
// CHECK-SAME: [[STRUCT_BFLOAT8:%.*]] returned [[A_COERCE:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret [[STRUCT_BFLOAT8]] [[A_COERCE]]
//
bfloat8 test_bfloat8(bfloat8 a) {
 return a;
}
// CHECK-LABEL: define dso_local %struct.v4bfloat8 @_Z14test_v4bfloat89v4bfloat8(
// CHECK-SAME: [[STRUCT_V4BFLOAT8:%.*]] returned [[A_COERCE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret [[STRUCT_V4BFLOAT8]] [[A_COERCE]]
//
v4bfloat8 test_v4bfloat8(v4bfloat8 a) {
 return a;
}
// CHECK-LABEL: define dso_local %struct.v8bfloat8 @_Z14test_v8bfloat89v8bfloat8(
// CHECK-SAME: [[STRUCT_V8BFLOAT8:%.*]] returned [[A_COERCE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret [[STRUCT_V8BFLOAT8]] [[A_COERCE]]
//
v8bfloat8 test_v8bfloat8(v8bfloat8 a) {
 return a;
}
// CHECK-LABEL: define dso_local %struct.v16bfloat8 @_Z15test_v16bfloat810v16bfloat8(
// CHECK-SAME: [[STRUCT_V16BFLOAT8:%.*]] returned [[A_COERCE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret [[STRUCT_V16BFLOAT8]] [[A_COERCE]]
//
v16bfloat8 test_v16bfloat8(v16bfloat8 a) {
 return a;
}
// CHECK-LABEL: define dso_local void @_Z15test_v32bfloat810v32bfloat8(
// CHECK-SAME: ptr dead_on_unwind noalias writable writeonly sret([[STRUCT_V32BFLOAT8:%.*]]) align 32 captures(none) initializes((0, 32)) [[AGG_RESULT:%.*]], [[STRUCT_V32BFLOAT8]] [[A_COERCE:%.*]]) local_unnamed_addr #[[ATTR1:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V32BFLOAT8]] [[A_COERCE]], 0
// CHECK-NEXT:    store <32 x i8> [[TMP0]], ptr [[AGG_RESULT]], align 32, !tbaa [[TBAA2:![0-9]+]]
// CHECK-NEXT:    ret void
//
v32bfloat8 test_v32bfloat8(v32bfloat8 a) {
 return a;
}
// CHECK-LABEL: define dso_local void @_Z15test_v64bfloat810v64bfloat8(
// CHECK-SAME: ptr dead_on_unwind noalias writable writeonly sret([[STRUCT_V64BFLOAT8:%.*]]) align 64 captures(none) initializes((0, 64)) [[AGG_RESULT:%.*]], [[STRUCT_V64BFLOAT8]] [[A_COERCE:%.*]]) local_unnamed_addr #[[ATTR1]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V64BFLOAT8]] [[A_COERCE]], 0
// CHECK-NEXT:    store <64 x i8> [[TMP0]], ptr [[AGG_RESULT]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    ret void
//
v64bfloat8 test_v64bfloat8(v64bfloat8 a) {
 return a;
}
// CHECK-LABEL: define dso_local void @_Z16test_v128bfloat811v128bfloat8(
// CHECK-SAME: ptr dead_on_unwind noalias writable writeonly sret([[STRUCT_V128BFLOAT8:%.*]]) align 64 captures(none) initializes((0, 128)) [[AGG_RESULT:%.*]], [[STRUCT_V128BFLOAT8]] [[A_COERCE:%.*]]) local_unnamed_addr #[[ATTR1]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V128BFLOAT8]] [[A_COERCE]], 0
// CHECK-NEXT:    store <128 x i8> [[TMP0]], ptr [[AGG_RESULT]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    ret void
//
v128bfloat8 test_v128bfloat8(v128bfloat8 a) {
 return a;
}
// CHECK-LABEL: define dso_local void @_Z16test_v256bfloat811v256bfloat8(
// CHECK-SAME: ptr dead_on_unwind noalias writable writeonly sret([[STRUCT_V256BFLOAT8:%.*]]) align 64 captures(none) initializes((0, 256)) [[AGG_RESULT:%.*]], [[STRUCT_V256BFLOAT8]] [[A_COERCE:%.*]]) local_unnamed_addr #[[ATTR1]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_V256BFLOAT8]] [[A_COERCE]], 0
// CHECK-NEXT:    store <64 x i32> [[TMP0]], ptr [[AGG_RESULT]], align 64, !tbaa [[TBAA2]]
// CHECK-NEXT:    ret void
//
v256bfloat8 test_v256bfloat8(v256bfloat8 a) {
 return a;
}

//.
// CHECK: [[TBAA2]] = !{[[META3:![0-9]+]], [[META3]], i64 0}
// CHECK: [[META3]] = !{!"omnipotent char", [[META4:![0-9]+]], i64 0}
// CHECK: [[META4]] = !{!"Simple C++ TBAA"}
//.
