// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
//===- test-float16.cc ------------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
//
//===----------------------------------------------------------------------===//

// RUN: %clang -O2 %s --target=aie2ps -nostdlibinc -S -emit-llvm -o - | FileCheck %s

// Minimal reproducer for clang crash with unary minus on _Float16
// original case: L1/regression/misc/GeluLUT/GeluTemplated_wts_lut_aie2_fp16

// CHECK-LABEL: define dso_local noundef half @_Z16test_minus_constv(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret half 0xH4500
//
float16 test_minus_const() {
    // Create a constexpr float16 value
    static constexpr float16 value = static_cast<float16>(-5.0f);

    // Unary minus on float16 constexpr causes the crash
    return -value;
}

// CHECK-LABEL: define dso_local noundef half @_Z19test_minus_variableDF16_(
// CHECK-SAME: half noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[FNEG:%.*]] = fneg half [[A]]
// CHECK-NEXT:    ret half [[FNEG]]
//
float16 test_minus_variable(float16 a) {
    return -a;
}

// CHECK-LABEL: define dso_local noundef half @_Z16test_bf16_to_f168bfloat16(
// CHECK-SAME: bfloat noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[FPEXT:%.*]] = fpext bfloat [[A]] to float
// CHECK-NEXT:    [[FPTRUNC:%.*]] = fptrunc float [[FPEXT]] to half
// CHECK-NEXT:    ret half [[FPTRUNC]]
//
float16 test_bf16_to_f16(bfloat16 a) {
  return a;
}

// CHECK-LABEL: define dso_local noundef bfloat @_Z16test_f16_to_bf16DF16_(
// CHECK-SAME: half noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[FPEXT:%.*]] = fpext half [[A]] to float
// CHECK-NEXT:    [[FPTRUNC:%.*]] = fptrunc float [[FPEXT]] to bfloat
// CHECK-NEXT:    ret bfloat [[FPTRUNC]]
//
bfloat16 test_f16_to_bf16(float16 a) {
  return a;
}
