; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie2p %s -o - | FileCheck %s

; Test postSWP capabilities related to AddAttributeBroadcasting plus some alias analysis
; tests related to SWP prologue and epilogue merging/scheduling.

; Function Attrs: nounwind memory(none)
declare <32 x float> @llvm.aie2p.v32bf16.to.v32accfloat(<32 x bfloat>) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read)
declare <64 x float> @llvm.aie2p.ACC2048.accfloat.add.conf(<64 x float>, <64 x float>, i32) #1

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read)
declare <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float>) #1

; Prologue test 1: In this first test, we have two scalar stores in the prologue block that may or may not alias with
; %ifm2 and %ifm1. %targetptr is guaranteed to not alias with input pointers while %targetptrmayalias
; may alias.

; Function Attrs: mustprogress noinline
define dso_local void @add_attribute_bcast_prologue1(ptr %ifm2, ptr %ifm1, i32 %div16, ptr noalias %ofm, ptr noalias %targetptr, ptr %targetptrmayalias) {
; CHECK-LABEL: add_attribute_bcast_prologue1:
; CHECK:       // %bb.0: // %newFuncRoot
; CHECK-NEXT:    mova m0, #32; nopb ; nopx ; st r0, [p4, #0]
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml1, [p1], m0
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml2, [p0], m0
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml0, [p0], m0
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml3, [p1], m0
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml1, [p1], m0; movx r1, #60
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml2, [p0], m0; vadd.f dm4, dm1, dm2, r1
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml0, [p0], m0; st r0, [p3, #0]; add.nc lc, r0, #-3
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml3, [p1], m0; movxm ls, #.LBB0_1; vadd.f dm3, dm3, dm0, r1
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml1, [p1], m0; nopb ; nops ; movxm le, #.L_LEnd0; nopv
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml2, [p0], m0; nopb ; nops ; nopxm ; vadd.f dm4, dm1, dm2, r1
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml0, [p0], m0; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml3, [p1], m0; nopb ; vst.conv.bf16.fp32 cml4, [p2], #64; nopxm ; vadd.f dm3, dm3, dm0, r1
; CHECK-NEXT:  .LBB0_1: // %for.body
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml1, [p1], m0; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml2, [p0], m0; nopb ; vst.conv.bf16.fp32 cml3, [p2], #64; nopxm ; vadd.f dm4, dm1, dm2, r1
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml0, [p0], m0; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:  .L_LEnd0:
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml3, [p1], m0; nopb ; vst.conv.bf16.fp32 cml4, [p2], #64; nopxm ; vadd.f dm3, dm3, dm0, r1
; CHECK-NEXT:  // %bb.2: // %for.cond.cleanup
; CHECK-NEXT:    nopa ; nopb ; nopxm ; nops
; CHECK-NEXT:    vst.conv.bf16.fp32 cml3, [p2], #64; vadd.f dm4, dm1, dm2, r1
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst.conv.bf16.fp32 cml4, [p2], #64; vadd.f dm3, dm3, dm0, r1
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst.conv.bf16.fp32 cml3, [p2], #64
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst.conv.bf16.fp32 cml4, [p2], #64
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst.conv.bf16.fp32 cml3, [p2], #64
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
newFuncRoot:
  br label %if.end

if.end:                                           ; preds = %newFuncRoot
  %0 = addrspacecast ptr %ifm2 to ptr addrspace(6)
  %1 = addrspacecast ptr %ifm1 to ptr addrspace(5)
  store i32 %div16, ptr %targetptr, align 4
  store i32 %div16, ptr %targetptrmayalias, align 4
  br label %for.body

for.body:                                         ; preds = %for.body, %if.end
  %lsr.iv = phi i32 [ %div16, %if.end ], [ %lsr.iv.next, %for.body ]
  %p_in1.023 = phi ptr addrspace(5) [ %1, %if.end ], [ %add.ptr.ascast.i.i.i, %for.body ]
  %p_in2.022 = phi ptr addrspace(6) [ %0, %if.end ], [ %add.ptr.ascast.i15.i.i, %for.body ]
  %p_out.0.in21 = phi ptr [ %ofm, %if.end ], [ %add.ptr.i18.i, %for.body ]
  %p_out.0 = addrspacecast ptr %p_out.0.in21 to ptr addrspace(7)
  %4 = load <32 x bfloat>, ptr addrspace(5) %p_in1.023, align 64, !tbaa !12
  %5 = addrspacecast ptr addrspace(5) %p_in1.023 to ptr
  %add.ptr.i.i = getelementptr inbounds i8, ptr %5, i20 32
  %add.ptr.ascast.i.i = addrspacecast ptr %add.ptr.i.i to ptr addrspace(5)
  %6 = load <32 x bfloat>, ptr addrspace(6) %p_in2.022, align 64, !tbaa !12
  %7 = addrspacecast ptr addrspace(6) %p_in2.022 to ptr
  %add.ptr.i16.i = getelementptr inbounds i8, ptr %7, i20 32
  %add.ptr.ascast.i17.i = addrspacecast ptr %add.ptr.i16.i to ptr addrspace(6)
  %8 = load <32 x bfloat>, ptr addrspace(5) %add.ptr.ascast.i.i, align 64, !tbaa !12
  %add.ptr.i.i.i = getelementptr inbounds i8, ptr %add.ptr.i.i, i20 32
  %add.ptr.ascast.i.i.i = addrspacecast ptr %add.ptr.i.i.i to ptr addrspace(5)
  %9 = load <32 x bfloat>, ptr addrspace(6) %add.ptr.ascast.i17.i, align 64, !tbaa !12
  %add.ptr.i14.i.i = getelementptr inbounds i8, ptr %add.ptr.i16.i, i20 32
  %add.ptr.ascast.i15.i.i = addrspacecast ptr %add.ptr.i14.i.i to ptr addrspace(6)
  %10 = tail call noundef <32 x float> @llvm.aie2p.v32bf16.to.v32accfloat(<32 x bfloat> %4)
  %11 = bitcast <32 x float> %10 to <16 x i64>
  %12 = tail call noundef <32 x float> @llvm.aie2p.v32bf16.to.v32accfloat(<32 x bfloat> %6)
  %13 = bitcast <32 x float> %12 to <16 x i64>
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i = shufflevector <16 x i64> %11, <16 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %14 = bitcast <32 x i64> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i to <64 x float>
  %shuffle.i.i1.i.i.i.i.i.i.i.i.i.i.i = shufflevector <16 x i64> %13, <16 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %15 = bitcast <32 x i64> %shuffle.i.i1.i.i.i.i.i.i.i.i.i.i.i to <64 x float>
  %16 = tail call noundef <64 x float> @llvm.aie2p.ACC2048.accfloat.add.conf(<64 x float> %14, <64 x float> %15, i32 60)
  %17 = bitcast <64 x float> %16 to <32 x i64>
  %shuffle.i.i2.i.i.i.i.i.i.i.i.i.i.i = shufflevector <32 x i64> %17, <32 x i64> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %18 = bitcast <16 x i64> %shuffle.i.i2.i.i.i.i.i.i.i.i.i.i.i to <32 x float>
  %19 = tail call noundef <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float> %18)
  %20 = tail call noundef <32 x float> @llvm.aie2p.v32bf16.to.v32accfloat(<32 x bfloat> %8)
  %21 = bitcast <32 x float> %20 to <16 x i64>
  %22 = tail call noundef <32 x float> @llvm.aie2p.v32bf16.to.v32accfloat(<32 x bfloat> %9)
  %23 = bitcast <32 x float> %22 to <16 x i64>
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i = shufflevector <16 x i64> %21, <16 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %24 = bitcast <32 x i64> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i to <64 x float>
  %shuffle.i.i1.i.i.i.i.i.i.i.i.i.i.i.i = shufflevector <16 x i64> %23, <16 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %25 = bitcast <32 x i64> %shuffle.i.i1.i.i.i.i.i.i.i.i.i.i.i.i to <64 x float>
  %26 = tail call noundef <64 x float> @llvm.aie2p.ACC2048.accfloat.add.conf(<64 x float> %24, <64 x float> %25, i32 60)
  %27 = bitcast <64 x float> %26 to <32 x i64>
  %shuffle.i.i2.i.i.i.i.i.i.i.i.i.i.i.i = shufflevector <32 x i64> %27, <32 x i64> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %28 = bitcast <16 x i64> %shuffle.i.i2.i.i.i.i.i.i.i.i.i.i.i.i to <32 x float>
  %29 = tail call noundef <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float> %28)
  store <32 x bfloat> %19, ptr addrspace(7) %p_out.0, align 64, !tbaa !12
  %add.ptr.i16.i.i = getelementptr inbounds nuw i8, ptr %p_out.0.in21, i20 64
  %add.ptr.ascast.i17.i.i = addrspacecast ptr %add.ptr.i16.i.i to ptr addrspace(7)
  store <32 x bfloat> %29, ptr addrspace(7) %add.ptr.ascast.i17.i.i, align 64, !tbaa !12
  %add.ptr.i18.i = getelementptr inbounds nuw i8, ptr %p_out.0.in21, i20 128
  %lsr.iv.next = add nsw i32 %lsr.iv, -1
  %exitcond.not = icmp eq i32 %lsr.iv.next, 0
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body, !llvm.loop !13

for.cond.cleanup:                                 ; preds = %for.body
  br label %for.cond.cleanup.ret.exitStub

for.cond.cleanup.ret.exitStub:                    ; preds = %for.cond.cleanup
  ret void
}

; Prologue test 2: In this test, we have one scalar store in the prologue block that  may not alias with
; %ifm2 1 and %ifm1. However, this store is a partword store, so we need to have enough distance from
; the loads.

; Function Attrs: mustprogress noinline
define dso_local void @add_attribute_bcast_prologue2(ptr %ifm2, ptr %ifm1, i32 %div16, ptr noalias %ofm, ptr noalias %targetptr) {
; CHECK-LABEL: add_attribute_bcast_prologue2:
; CHECK:       // %bb.0: // %newFuncRoot
; CHECK-NEXT:    st.s16 r0, [p3, #0]; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    nopx
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    mova m0, #32
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml1, [p1], m0
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml2, [p0], m0
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml0, [p0], m0
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml3, [p1], m0
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml1, [p1], m0; movx r1, #60
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml2, [p0], m0; vadd.f dm4, dm1, dm2, r1
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml0, [p0], m0; add.nc lc, r0, #-3
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml3, [p1], m0; movxm ls, #.LBB1_1; vadd.f dm3, dm3, dm0, r1
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml1, [p1], m0; nopb ; nops ; movxm le, #.L_LEnd1; nopv
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml2, [p0], m0; nopb ; nops ; nopxm ; vadd.f dm4, dm1, dm2, r1
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml0, [p0], m0; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml3, [p1], m0; nopb ; vst.conv.bf16.fp32 cml4, [p2], #64; nopxm ; vadd.f dm3, dm3, dm0, r1
; CHECK-NEXT:  .LBB1_1: // %for.body
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml1, [p1], m0; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml2, [p0], m0; nopb ; vst.conv.bf16.fp32 cml3, [p2], #64; nopxm ; vadd.f dm4, dm1, dm2, r1
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml0, [p0], m0; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:  .L_LEnd1:
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml3, [p1], m0; nopb ; vst.conv.bf16.fp32 cml4, [p2], #64; nopxm ; vadd.f dm3, dm3, dm0, r1
; CHECK-NEXT:  // %bb.2: // %for.cond.cleanup
; CHECK-NEXT:    nopa ; nopb ; nopxm ; nops
; CHECK-NEXT:    vst.conv.bf16.fp32 cml3, [p2], #64; vadd.f dm4, dm1, dm2, r1
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst.conv.bf16.fp32 cml4, [p2], #64; vadd.f dm3, dm3, dm0, r1
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst.conv.bf16.fp32 cml3, [p2], #64
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst.conv.bf16.fp32 cml4, [p2], #64
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst.conv.bf16.fp32 cml3, [p2], #64
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
newFuncRoot:
  br label %if.end

if.end:                                           ; preds = %newFuncRoot
  %0 = addrspacecast ptr %ifm2 to ptr addrspace(6)
  %1 = addrspacecast ptr %ifm1 to ptr addrspace(5)
  %divtrunc = trunc i32 %div16 to i16
  store i16 %divtrunc, ptr %targetptr, align 4
  br label %for.body

for.body:                                         ; preds = %for.body, %if.end
  %lsr.iv = phi i32 [ %div16, %if.end ], [ %lsr.iv.next, %for.body ]
  %p_in1.023 = phi ptr addrspace(5) [ %1, %if.end ], [ %add.ptr.ascast.i.i.i, %for.body ]
  %p_in2.022 = phi ptr addrspace(6) [ %0, %if.end ], [ %add.ptr.ascast.i15.i.i, %for.body ]
  %p_out.0.in21 = phi ptr [ %ofm, %if.end ], [ %add.ptr.i18.i, %for.body ]
  %p_out.0 = addrspacecast ptr %p_out.0.in21 to ptr addrspace(7)
  %4 = load <32 x bfloat>, ptr addrspace(5) %p_in1.023, align 64, !tbaa !12
  %5 = addrspacecast ptr addrspace(5) %p_in1.023 to ptr
  %add.ptr.i.i = getelementptr inbounds i8, ptr %5, i20 32
  %add.ptr.ascast.i.i = addrspacecast ptr %add.ptr.i.i to ptr addrspace(5)
  %6 = load <32 x bfloat>, ptr addrspace(6) %p_in2.022, align 64, !tbaa !12
  %7 = addrspacecast ptr addrspace(6) %p_in2.022 to ptr
  %add.ptr.i16.i = getelementptr inbounds i8, ptr %7, i20 32
  %add.ptr.ascast.i17.i = addrspacecast ptr %add.ptr.i16.i to ptr addrspace(6)
  %8 = load <32 x bfloat>, ptr addrspace(5) %add.ptr.ascast.i.i, align 64, !tbaa !12
  %add.ptr.i.i.i = getelementptr inbounds i8, ptr %add.ptr.i.i, i20 32
  %add.ptr.ascast.i.i.i = addrspacecast ptr %add.ptr.i.i.i to ptr addrspace(5)
  %9 = load <32 x bfloat>, ptr addrspace(6) %add.ptr.ascast.i17.i, align 64, !tbaa !12
  %add.ptr.i14.i.i = getelementptr inbounds i8, ptr %add.ptr.i16.i, i20 32
  %add.ptr.ascast.i15.i.i = addrspacecast ptr %add.ptr.i14.i.i to ptr addrspace(6)
  %10 = tail call noundef <32 x float> @llvm.aie2p.v32bf16.to.v32accfloat(<32 x bfloat> %4)
  %11 = bitcast <32 x float> %10 to <16 x i64>
  %12 = tail call noundef <32 x float> @llvm.aie2p.v32bf16.to.v32accfloat(<32 x bfloat> %6)
  %13 = bitcast <32 x float> %12 to <16 x i64>
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i = shufflevector <16 x i64> %11, <16 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %14 = bitcast <32 x i64> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i to <64 x float>
  %shuffle.i.i1.i.i.i.i.i.i.i.i.i.i.i = shufflevector <16 x i64> %13, <16 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %15 = bitcast <32 x i64> %shuffle.i.i1.i.i.i.i.i.i.i.i.i.i.i to <64 x float>
  %16 = tail call noundef <64 x float> @llvm.aie2p.ACC2048.accfloat.add.conf(<64 x float> %14, <64 x float> %15, i32 60)
  %17 = bitcast <64 x float> %16 to <32 x i64>
  %shuffle.i.i2.i.i.i.i.i.i.i.i.i.i.i = shufflevector <32 x i64> %17, <32 x i64> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %18 = bitcast <16 x i64> %shuffle.i.i2.i.i.i.i.i.i.i.i.i.i.i to <32 x float>
  %19 = tail call noundef <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float> %18)
  %20 = tail call noundef <32 x float> @llvm.aie2p.v32bf16.to.v32accfloat(<32 x bfloat> %8)
  %21 = bitcast <32 x float> %20 to <16 x i64>
  %22 = tail call noundef <32 x float> @llvm.aie2p.v32bf16.to.v32accfloat(<32 x bfloat> %9)
  %23 = bitcast <32 x float> %22 to <16 x i64>
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i = shufflevector <16 x i64> %21, <16 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %24 = bitcast <32 x i64> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i to <64 x float>
  %shuffle.i.i1.i.i.i.i.i.i.i.i.i.i.i.i = shufflevector <16 x i64> %23, <16 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %25 = bitcast <32 x i64> %shuffle.i.i1.i.i.i.i.i.i.i.i.i.i.i.i to <64 x float>
  %26 = tail call noundef <64 x float> @llvm.aie2p.ACC2048.accfloat.add.conf(<64 x float> %24, <64 x float> %25, i32 60)
  %27 = bitcast <64 x float> %26 to <32 x i64>
  %shuffle.i.i2.i.i.i.i.i.i.i.i.i.i.i.i = shufflevector <32 x i64> %27, <32 x i64> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %28 = bitcast <16 x i64> %shuffle.i.i2.i.i.i.i.i.i.i.i.i.i.i.i to <32 x float>
  %29 = tail call noundef <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float> %28)
  store <32 x bfloat> %19, ptr addrspace(7) %p_out.0, align 64, !tbaa !12
  %add.ptr.i16.i.i = getelementptr inbounds nuw i8, ptr %p_out.0.in21, i20 64
  %add.ptr.ascast.i17.i.i = addrspacecast ptr %add.ptr.i16.i.i to ptr addrspace(7)
  store <32 x bfloat> %29, ptr addrspace(7) %add.ptr.ascast.i17.i.i, align 64, !tbaa !12
  %add.ptr.i18.i = getelementptr inbounds nuw i8, ptr %p_out.0.in21, i20 128
  %lsr.iv.next = add nsw i32 %lsr.iv, -1
  %exitcond.not = icmp eq i32 %lsr.iv.next, 0
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body, !llvm.loop !13

for.cond.cleanup:                                 ; preds = %for.body
  br label %for.cond.cleanup.ret.exitStub

for.cond.cleanup.ret.exitStub:                    ; preds = %for.cond.cleanup
  ret void
}

; Epilogue test 1: In this test, we have two scalar stores in the epilogue block that may or may not alias with
; %ofm. %targetptr is guaranteed to not alias with the output pointer while %targetptrmayalias
; may alias.

; Function Attrs: mustprogress noinline
define dso_local void @add_attribute_bcast_epilogue1(ptr noalias %ifm2, ptr noalias %ifm1, i32 %div16, ptr %ofm, ptr noalias %targetptr, ptr %targetptrmayalias) {
; CHECK-LABEL: add_attribute_bcast_epilogue1:
; CHECK:       // %bb.0: // %newFuncRoot
; CHECK-NEXT:    mova m0, #32; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml1, [p1], m0
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml2, [p0], m0
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml0, [p0], m0
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml3, [p1], m0
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml1, [p1], m0; movx r1, #60
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml2, [p0], m0; vadd.f dm4, dm1, dm2, r1
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml0, [p0], m0; add.nc lc, r0, #-3
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml3, [p1], m0; movxm ls, #.LBB2_1; vadd.f dm3, dm3, dm0, r1
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml1, [p1], m0; nopb ; nops ; movxm le, #.L_LEnd2; nopv
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml2, [p0], m0; nopb ; nops ; nopxm ; vadd.f dm4, dm1, dm2, r1
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml0, [p0], m0; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml3, [p1], m0; nopb ; vst.conv.bf16.fp32 cml4, [p2], #64; nopxm ; vadd.f dm3, dm3, dm0, r1
; CHECK-NEXT:  .LBB2_1: // %for.body
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml1, [p1], m0; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml2, [p0], m0; nopb ; vst.conv.bf16.fp32 cml3, [p2], #64; nopxm ; vadd.f dm4, dm1, dm2, r1
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml0, [p0], m0; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:  .L_LEnd2:
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml3, [p1], m0; nopb ; vst.conv.bf16.fp32 cml4, [p2], #64; nopxm ; vadd.f dm3, dm3, dm0, r1
; CHECK-NEXT:  // %bb.2: // %for.cond.cleanup
; CHECK-NEXT:    nopa ; nopb ; nopx ; st r0, [p3, #0]
; CHECK-NEXT:    vst.conv.bf16.fp32 cml3, [p2], #64; vadd.f dm4, dm1, dm2, r1
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst.conv.bf16.fp32 cml4, [p2], #64; vadd.f dm3, dm3, dm0, r1
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst.conv.bf16.fp32 cml3, [p2], #64
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst.conv.bf16.fp32 cml4, [p2], #64
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst.conv.bf16.fp32 cml3, [p2], #64
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    st r0, [p4, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
newFuncRoot:
  br label %if.end

if.end:                                           ; preds = %newFuncRoot
  %0 = addrspacecast ptr %ifm2 to ptr addrspace(6)
  %1 = addrspacecast ptr %ifm1 to ptr addrspace(5)
  br label %for.body

for.body:                                         ; preds = %for.body, %if.end
  %lsr.iv = phi i32 [ %div16, %if.end ], [ %lsr.iv.next, %for.body ]
  %p_in1.023 = phi ptr addrspace(5) [ %1, %if.end ], [ %add.ptr.ascast.i.i.i, %for.body ]
  %p_in2.022 = phi ptr addrspace(6) [ %0, %if.end ], [ %add.ptr.ascast.i15.i.i, %for.body ]
  %p_out.0.in21 = phi ptr [ %ofm, %if.end ], [ %add.ptr.i18.i, %for.body ]
  %p_out.0 = addrspacecast ptr %p_out.0.in21 to ptr addrspace(7)
  %4 = load <32 x bfloat>, ptr addrspace(5) %p_in1.023, align 64, !tbaa !12
  %5 = addrspacecast ptr addrspace(5) %p_in1.023 to ptr
  %add.ptr.i.i = getelementptr inbounds i8, ptr %5, i20 32
  %add.ptr.ascast.i.i = addrspacecast ptr %add.ptr.i.i to ptr addrspace(5)
  %6 = load <32 x bfloat>, ptr addrspace(6) %p_in2.022, align 64, !tbaa !12
  %7 = addrspacecast ptr addrspace(6) %p_in2.022 to ptr
  %add.ptr.i16.i = getelementptr inbounds i8, ptr %7, i20 32
  %add.ptr.ascast.i17.i = addrspacecast ptr %add.ptr.i16.i to ptr addrspace(6)
  %8 = load <32 x bfloat>, ptr addrspace(5) %add.ptr.ascast.i.i, align 64, !tbaa !12
  %add.ptr.i.i.i = getelementptr inbounds i8, ptr %add.ptr.i.i, i20 32
  %add.ptr.ascast.i.i.i = addrspacecast ptr %add.ptr.i.i.i to ptr addrspace(5)
  %9 = load <32 x bfloat>, ptr addrspace(6) %add.ptr.ascast.i17.i, align 64, !tbaa !12
  %add.ptr.i14.i.i = getelementptr inbounds i8, ptr %add.ptr.i16.i, i20 32
  %add.ptr.ascast.i15.i.i = addrspacecast ptr %add.ptr.i14.i.i to ptr addrspace(6)
  %10 = tail call noundef <32 x float> @llvm.aie2p.v32bf16.to.v32accfloat(<32 x bfloat> %4)
  %11 = bitcast <32 x float> %10 to <16 x i64>
  %12 = tail call noundef <32 x float> @llvm.aie2p.v32bf16.to.v32accfloat(<32 x bfloat> %6)
  %13 = bitcast <32 x float> %12 to <16 x i64>
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i = shufflevector <16 x i64> %11, <16 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %14 = bitcast <32 x i64> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i to <64 x float>
  %shuffle.i.i1.i.i.i.i.i.i.i.i.i.i.i = shufflevector <16 x i64> %13, <16 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %15 = bitcast <32 x i64> %shuffle.i.i1.i.i.i.i.i.i.i.i.i.i.i to <64 x float>
  %16 = tail call noundef <64 x float> @llvm.aie2p.ACC2048.accfloat.add.conf(<64 x float> %14, <64 x float> %15, i32 60)
  %17 = bitcast <64 x float> %16 to <32 x i64>
  %shuffle.i.i2.i.i.i.i.i.i.i.i.i.i.i = shufflevector <32 x i64> %17, <32 x i64> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %18 = bitcast <16 x i64> %shuffle.i.i2.i.i.i.i.i.i.i.i.i.i.i to <32 x float>
  %19 = tail call noundef <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float> %18)
  %20 = tail call noundef <32 x float> @llvm.aie2p.v32bf16.to.v32accfloat(<32 x bfloat> %8)
  %21 = bitcast <32 x float> %20 to <16 x i64>
  %22 = tail call noundef <32 x float> @llvm.aie2p.v32bf16.to.v32accfloat(<32 x bfloat> %9)
  %23 = bitcast <32 x float> %22 to <16 x i64>
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i = shufflevector <16 x i64> %21, <16 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %24 = bitcast <32 x i64> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i to <64 x float>
  %shuffle.i.i1.i.i.i.i.i.i.i.i.i.i.i.i = shufflevector <16 x i64> %23, <16 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %25 = bitcast <32 x i64> %shuffle.i.i1.i.i.i.i.i.i.i.i.i.i.i.i to <64 x float>
  %26 = tail call noundef <64 x float> @llvm.aie2p.ACC2048.accfloat.add.conf(<64 x float> %24, <64 x float> %25, i32 60)
  %27 = bitcast <64 x float> %26 to <32 x i64>
  %shuffle.i.i2.i.i.i.i.i.i.i.i.i.i.i.i = shufflevector <32 x i64> %27, <32 x i64> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %28 = bitcast <16 x i64> %shuffle.i.i2.i.i.i.i.i.i.i.i.i.i.i.i to <32 x float>
  %29 = tail call noundef <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float> %28)
  store <32 x bfloat> %19, ptr addrspace(7) %p_out.0, align 64, !tbaa !12
  %add.ptr.i16.i.i = getelementptr inbounds nuw i8, ptr %p_out.0.in21, i20 64
  %add.ptr.ascast.i17.i.i = addrspacecast ptr %add.ptr.i16.i.i to ptr addrspace(7)
  store <32 x bfloat> %29, ptr addrspace(7) %add.ptr.ascast.i17.i.i, align 64, !tbaa !12
  %add.ptr.i18.i = getelementptr inbounds nuw i8, ptr %p_out.0.in21, i20 128
  %lsr.iv.next = add nsw i32 %lsr.iv, -1
  %exitcond.not = icmp eq i32 %lsr.iv.next, 0
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body, !llvm.loop !13

for.cond.cleanup:                                 ; preds = %for.body
  store i32 %div16, ptr %targetptr, align 4
  store i32 %div16, ptr %targetptrmayalias, align 4
  br label %for.cond.cleanup.ret.exitStub

for.cond.cleanup.ret.exitStub:                    ; preds = %for.cond.cleanup
  ret void
}

; Epilogue test 2: In this test, we have one scalar store in the epilogue block that may not alias with
; %ofm. However, this store is a partword store, so we need to have enough distance from
; the existing stores.

; Function Attrs: mustprogress noinline
define dso_local void @add_attribute_bcast_epilogue2(ptr noalias %ifm2, ptr noalias %ifm1, i32 %div16, ptr %ofm, ptr noalias %targetptr) {
; CHECK-LABEL: add_attribute_bcast_epilogue2:
; CHECK:       // %bb.0: // %newFuncRoot
; CHECK-NEXT:    mova m0, #32; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml1, [p1], m0
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml2, [p0], m0
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml0, [p0], m0
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml3, [p1], m0
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml1, [p1], m0; movx r1, #60
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml2, [p0], m0; vadd.f dm4, dm1, dm2, r1
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml0, [p0], m0; add.nc lc, r0, #-3
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml3, [p1], m0; movxm ls, #.LBB3_1; vadd.f dm3, dm3, dm0, r1
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml1, [p1], m0; nopb ; nops ; movxm le, #.L_LEnd3; nopv
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml2, [p0], m0; nopb ; nops ; nopxm ; vadd.f dm4, dm1, dm2, r1
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml0, [p0], m0; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml3, [p1], m0; nopb ; vst.conv.bf16.fp32 cml4, [p2], #64; nopxm ; vadd.f dm3, dm3, dm0, r1
; CHECK-NEXT:  .LBB3_1: // %for.body
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml1, [p1], m0; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml2, [p0], m0; nopb ; vst.conv.bf16.fp32 cml3, [p2], #64; nopxm ; vadd.f dm4, dm1, dm2, r1
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml0, [p0], m0; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:  .L_LEnd3:
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml3, [p1], m0; nopb ; vst.conv.bf16.fp32 cml4, [p2], #64; nopxm ; vadd.f dm3, dm3, dm0, r1
; CHECK-NEXT:  // %bb.2: // %for.cond.cleanup
; CHECK-NEXT:    nopa ; nopb ; nopx
; CHECK-NEXT:    vst.conv.bf16.fp32 cml3, [p2], #64; vadd.f dm4, dm1, dm2, r1
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst.conv.bf16.fp32 cml4, [p2], #64; vadd.f dm3, dm3, dm0, r1
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst.conv.bf16.fp32 cml3, [p2], #64
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst.conv.bf16.fp32 cml4, [p2], #64
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst.conv.bf16.fp32 cml3, [p2], #64
; CHECK-NEXT:    st.s16 r0, [p3, #0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
newFuncRoot:
  br label %if.end

if.end:                                           ; preds = %newFuncRoot
  %0 = addrspacecast ptr %ifm2 to ptr addrspace(6)
  %1 = addrspacecast ptr %ifm1 to ptr addrspace(5)
  br label %for.body

for.body:                                         ; preds = %for.body, %if.end
  %lsr.iv = phi i32 [ %div16, %if.end ], [ %lsr.iv.next, %for.body ]
  %p_in1.023 = phi ptr addrspace(5) [ %1, %if.end ], [ %add.ptr.ascast.i.i.i, %for.body ]
  %p_in2.022 = phi ptr addrspace(6) [ %0, %if.end ], [ %add.ptr.ascast.i15.i.i, %for.body ]
  %p_out.0.in21 = phi ptr [ %ofm, %if.end ], [ %add.ptr.i18.i, %for.body ]
  %p_out.0 = addrspacecast ptr %p_out.0.in21 to ptr addrspace(7)
  %4 = load <32 x bfloat>, ptr addrspace(5) %p_in1.023, align 64, !tbaa !12
  %5 = addrspacecast ptr addrspace(5) %p_in1.023 to ptr
  %add.ptr.i.i = getelementptr inbounds i8, ptr %5, i20 32
  %add.ptr.ascast.i.i = addrspacecast ptr %add.ptr.i.i to ptr addrspace(5)
  %6 = load <32 x bfloat>, ptr addrspace(6) %p_in2.022, align 64, !tbaa !12
  %7 = addrspacecast ptr addrspace(6) %p_in2.022 to ptr
  %add.ptr.i16.i = getelementptr inbounds i8, ptr %7, i20 32
  %add.ptr.ascast.i17.i = addrspacecast ptr %add.ptr.i16.i to ptr addrspace(6)
  %8 = load <32 x bfloat>, ptr addrspace(5) %add.ptr.ascast.i.i, align 64, !tbaa !12
  %add.ptr.i.i.i = getelementptr inbounds i8, ptr %add.ptr.i.i, i20 32
  %add.ptr.ascast.i.i.i = addrspacecast ptr %add.ptr.i.i.i to ptr addrspace(5)
  %9 = load <32 x bfloat>, ptr addrspace(6) %add.ptr.ascast.i17.i, align 64, !tbaa !12
  %add.ptr.i14.i.i = getelementptr inbounds i8, ptr %add.ptr.i16.i, i20 32
  %add.ptr.ascast.i15.i.i = addrspacecast ptr %add.ptr.i14.i.i to ptr addrspace(6)
  %10 = tail call noundef <32 x float> @llvm.aie2p.v32bf16.to.v32accfloat(<32 x bfloat> %4)
  %11 = bitcast <32 x float> %10 to <16 x i64>
  %12 = tail call noundef <32 x float> @llvm.aie2p.v32bf16.to.v32accfloat(<32 x bfloat> %6)
  %13 = bitcast <32 x float> %12 to <16 x i64>
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i = shufflevector <16 x i64> %11, <16 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %14 = bitcast <32 x i64> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i to <64 x float>
  %shuffle.i.i1.i.i.i.i.i.i.i.i.i.i.i = shufflevector <16 x i64> %13, <16 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %15 = bitcast <32 x i64> %shuffle.i.i1.i.i.i.i.i.i.i.i.i.i.i to <64 x float>
  %16 = tail call noundef <64 x float> @llvm.aie2p.ACC2048.accfloat.add.conf(<64 x float> %14, <64 x float> %15, i32 60)
  %17 = bitcast <64 x float> %16 to <32 x i64>
  %shuffle.i.i2.i.i.i.i.i.i.i.i.i.i.i = shufflevector <32 x i64> %17, <32 x i64> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %18 = bitcast <16 x i64> %shuffle.i.i2.i.i.i.i.i.i.i.i.i.i.i to <32 x float>
  %19 = tail call noundef <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float> %18)
  %20 = tail call noundef <32 x float> @llvm.aie2p.v32bf16.to.v32accfloat(<32 x bfloat> %8)
  %21 = bitcast <32 x float> %20 to <16 x i64>
  %22 = tail call noundef <32 x float> @llvm.aie2p.v32bf16.to.v32accfloat(<32 x bfloat> %9)
  %23 = bitcast <32 x float> %22 to <16 x i64>
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i = shufflevector <16 x i64> %21, <16 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %24 = bitcast <32 x i64> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i to <64 x float>
  %shuffle.i.i1.i.i.i.i.i.i.i.i.i.i.i.i = shufflevector <16 x i64> %23, <16 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %25 = bitcast <32 x i64> %shuffle.i.i1.i.i.i.i.i.i.i.i.i.i.i.i to <64 x float>
  %26 = tail call noundef <64 x float> @llvm.aie2p.ACC2048.accfloat.add.conf(<64 x float> %24, <64 x float> %25, i32 60)
  %27 = bitcast <64 x float> %26 to <32 x i64>
  %shuffle.i.i2.i.i.i.i.i.i.i.i.i.i.i.i = shufflevector <32 x i64> %27, <32 x i64> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %28 = bitcast <16 x i64> %shuffle.i.i2.i.i.i.i.i.i.i.i.i.i.i.i to <32 x float>
  %29 = tail call noundef <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float> %28)
  store <32 x bfloat> %19, ptr addrspace(7) %p_out.0, align 64, !tbaa !12
  %add.ptr.i16.i.i = getelementptr inbounds nuw i8, ptr %p_out.0.in21, i20 64
  %add.ptr.ascast.i17.i.i = addrspacecast ptr %add.ptr.i16.i.i to ptr addrspace(7)
  store <32 x bfloat> %29, ptr addrspace(7) %add.ptr.ascast.i17.i.i, align 64, !tbaa !12
  %add.ptr.i18.i = getelementptr inbounds nuw i8, ptr %p_out.0.in21, i20 128
  %lsr.iv.next = add nsw i32 %lsr.iv, -1
  %exitcond.not = icmp eq i32 %lsr.iv.next, 0
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body, !llvm.loop !13

for.cond.cleanup:                                 ; preds = %for.body
  %divtrunc = trunc i32 %div16 to i16
  store i16 %divtrunc, ptr %targetptr, align 4
  br label %for.cond.cleanup.ret.exitStub

for.cond.cleanup.ret.exitStub:                    ; preds = %for.cond.cleanup
  ret void
}

; Epilogue test 3: In this test, we have two scalar loads in the epilogue block that may or may not alias with
; %ofm. %targetptr is guaranteed to not alias with the output pointer while %targetptrmayalias
; may alias.

; Function Attrs: mustprogress noinline
define dso_local void @add_attribute_bcast_epilogue3(ptr noalias %ifm2, ptr noalias %ifm1, i32 %div16, ptr %ofm, ptr noalias %targetptr, ptr %targetptrmayalias) {
; CHECK-LABEL: add_attribute_bcast_epilogue3:
; CHECK:       // %bb.0: // %newFuncRoot
; CHECK-NEXT:    mova m0, #32; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml1, [p1], m0
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml2, [p0], m0
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml0, [p0], m0
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml3, [p1], m0
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml1, [p1], m0; movx r1, #60
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml2, [p0], m0; vadd.f dm4, dm1, dm2, r1
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml0, [p0], m0; add.nc lc, r0, #-3
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml3, [p1], m0; movxm ls, #.LBB4_1; vadd.f dm3, dm3, dm0, r1
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml1, [p1], m0; nopb ; nops ; movxm le, #.L_LEnd4; nopv
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml2, [p0], m0; nopb ; nops ; nopxm ; vadd.f dm4, dm1, dm2, r1
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml0, [p0], m0; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml3, [p1], m0; nopb ; vst.conv.bf16.fp32 cml4, [p2], #64; nopxm ; vadd.f dm3, dm3, dm0, r1
; CHECK-NEXT:  .LBB4_1: // %for.body
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml1, [p1], m0; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml2, [p0], m0; nopb ; vst.conv.bf16.fp32 cml3, [p2], #64; nopxm ; vadd.f dm4, dm1, dm2, r1
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml0, [p0], m0; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:  .L_LEnd4:
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml3, [p1], m0; nopb ; vst.conv.bf16.fp32 cml4, [p2], #64; nopxm ; vadd.f dm3, dm3, dm0, r1
; CHECK-NEXT:  // %bb.2: // %for.cond.cleanup
; CHECK-NEXT:    lda r1, [p3, #0]; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    vst.conv.bf16.fp32 cml3, [p2], #64; vadd.f dm4, dm1, dm2, r1
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst.conv.bf16.fp32 cml4, [p2], #64; vadd.f dm3, dm3, dm0, r1
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst.conv.bf16.fp32 cml3, [p2], #64
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst.conv.bf16.fp32 cml4, [p2], #64
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst.conv.bf16.fp32 cml3, [p2], #64
; CHECK-NEXT:    lda r0, [p4, #0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    add r0, r1, r0 // Delay Slot 3
; CHECK-NEXT:    st r0, [p3, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
newFuncRoot:
  br label %if.end

if.end:                                           ; preds = %newFuncRoot
  %0 = addrspacecast ptr %ifm2 to ptr addrspace(6)
  %1 = addrspacecast ptr %ifm1 to ptr addrspace(5)
  br label %for.body

for.body:                                         ; preds = %for.body, %if.end
  %lsr.iv = phi i32 [ %div16, %if.end ], [ %lsr.iv.next, %for.body ]
  %p_in1.023 = phi ptr addrspace(5) [ %1, %if.end ], [ %add.ptr.ascast.i.i.i, %for.body ]
  %p_in2.022 = phi ptr addrspace(6) [ %0, %if.end ], [ %add.ptr.ascast.i15.i.i, %for.body ]
  %p_out.0.in21 = phi ptr [ %ofm, %if.end ], [ %add.ptr.i18.i, %for.body ]
  %p_out.0 = addrspacecast ptr %p_out.0.in21 to ptr addrspace(7)
  %4 = load <32 x bfloat>, ptr addrspace(5) %p_in1.023, align 64, !tbaa !12
  %5 = addrspacecast ptr addrspace(5) %p_in1.023 to ptr
  %add.ptr.i.i = getelementptr inbounds i8, ptr %5, i20 32
  %add.ptr.ascast.i.i = addrspacecast ptr %add.ptr.i.i to ptr addrspace(5)
  %6 = load <32 x bfloat>, ptr addrspace(6) %p_in2.022, align 64, !tbaa !12
  %7 = addrspacecast ptr addrspace(6) %p_in2.022 to ptr
  %add.ptr.i16.i = getelementptr inbounds i8, ptr %7, i20 32
  %add.ptr.ascast.i17.i = addrspacecast ptr %add.ptr.i16.i to ptr addrspace(6)
  %8 = load <32 x bfloat>, ptr addrspace(5) %add.ptr.ascast.i.i, align 64, !tbaa !12
  %add.ptr.i.i.i = getelementptr inbounds i8, ptr %add.ptr.i.i, i20 32
  %add.ptr.ascast.i.i.i = addrspacecast ptr %add.ptr.i.i.i to ptr addrspace(5)
  %9 = load <32 x bfloat>, ptr addrspace(6) %add.ptr.ascast.i17.i, align 64, !tbaa !12
  %add.ptr.i14.i.i = getelementptr inbounds i8, ptr %add.ptr.i16.i, i20 32
  %add.ptr.ascast.i15.i.i = addrspacecast ptr %add.ptr.i14.i.i to ptr addrspace(6)
  %10 = tail call noundef <32 x float> @llvm.aie2p.v32bf16.to.v32accfloat(<32 x bfloat> %4)
  %11 = bitcast <32 x float> %10 to <16 x i64>
  %12 = tail call noundef <32 x float> @llvm.aie2p.v32bf16.to.v32accfloat(<32 x bfloat> %6)
  %13 = bitcast <32 x float> %12 to <16 x i64>
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i = shufflevector <16 x i64> %11, <16 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %14 = bitcast <32 x i64> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i to <64 x float>
  %shuffle.i.i1.i.i.i.i.i.i.i.i.i.i.i = shufflevector <16 x i64> %13, <16 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %15 = bitcast <32 x i64> %shuffle.i.i1.i.i.i.i.i.i.i.i.i.i.i to <64 x float>
  %16 = tail call noundef <64 x float> @llvm.aie2p.ACC2048.accfloat.add.conf(<64 x float> %14, <64 x float> %15, i32 60)
  %17 = bitcast <64 x float> %16 to <32 x i64>
  %shuffle.i.i2.i.i.i.i.i.i.i.i.i.i.i = shufflevector <32 x i64> %17, <32 x i64> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %18 = bitcast <16 x i64> %shuffle.i.i2.i.i.i.i.i.i.i.i.i.i.i to <32 x float>
  %19 = tail call noundef <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float> %18)
  %20 = tail call noundef <32 x float> @llvm.aie2p.v32bf16.to.v32accfloat(<32 x bfloat> %8)
  %21 = bitcast <32 x float> %20 to <16 x i64>
  %22 = tail call noundef <32 x float> @llvm.aie2p.v32bf16.to.v32accfloat(<32 x bfloat> %9)
  %23 = bitcast <32 x float> %22 to <16 x i64>
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i = shufflevector <16 x i64> %21, <16 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %24 = bitcast <32 x i64> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i to <64 x float>
  %shuffle.i.i1.i.i.i.i.i.i.i.i.i.i.i.i = shufflevector <16 x i64> %23, <16 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %25 = bitcast <32 x i64> %shuffle.i.i1.i.i.i.i.i.i.i.i.i.i.i.i to <64 x float>
  %26 = tail call noundef <64 x float> @llvm.aie2p.ACC2048.accfloat.add.conf(<64 x float> %24, <64 x float> %25, i32 60)
  %27 = bitcast <64 x float> %26 to <32 x i64>
  %shuffle.i.i2.i.i.i.i.i.i.i.i.i.i.i.i = shufflevector <32 x i64> %27, <32 x i64> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %28 = bitcast <16 x i64> %shuffle.i.i2.i.i.i.i.i.i.i.i.i.i.i.i to <32 x float>
  %29 = tail call noundef <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float> %28)
  store <32 x bfloat> %19, ptr addrspace(7) %p_out.0, align 64, !tbaa !12
  %add.ptr.i16.i.i = getelementptr inbounds nuw i8, ptr %p_out.0.in21, i20 64
  %add.ptr.ascast.i17.i.i = addrspacecast ptr %add.ptr.i16.i.i to ptr addrspace(7)
  store <32 x bfloat> %29, ptr addrspace(7) %add.ptr.ascast.i17.i.i, align 64, !tbaa !12
  %add.ptr.i18.i = getelementptr inbounds nuw i8, ptr %p_out.0.in21, i20 128
  %lsr.iv.next = add nsw i32 %lsr.iv, -1
  %exitcond.not = icmp eq i32 %lsr.iv.next, 0
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body, !llvm.loop !13

for.cond.cleanup:                                 ; preds = %for.body
  %load1 = load i32, ptr %targetptr, align 32
  %load2 = load i32, ptr %targetptrmayalias, align 4
  br label %for.cond.cleanup.ret.exitStub

for.cond.cleanup.ret.exitStub:                    ; preds = %for.cond.cleanup
  %and1 = add i32 %load1, %load2
  store i32 %and1, ptr %targetptr, align 4
  ret void
}


!4 = !{!5, !6, i64 32}
!5 = !{!"A", !6, i64 0, !7, i64 4, !7, i64 5, !7, i64 6, !7, i64 7, !7, i64 8, !7, i64 9, !9, i64 10, !7, i64 12, !7, i64 13, !9, i64 14, !6, i64 16, !6, i64 20, !6, i64 24, !10, i64 28, !6, i64 32, !6, i64 36}
!6 = !{!"int", !7, i64 0}
!7 = !{!"omnipotent char", !8, i64 0}
!8 = !{!"Simple C++ TBAA"}
!9 = !{!"short", !7, i64 0}
!10 = !{!"B", !9, i64 0}
!11 = !{!5, !6, i64 36}
!12 = !{!7, !7, i64 0}
!13 = distinct !{!13, !14, !15}
!14 = !{!"llvm.loop.mustprogress"}
!15 = !{!"llvm.loop.itercount.range", i64 6}
