; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie2p --aie-force-postpipeliner \
; RUN:   -aie-preassign-multi-slot-instr=true %s -o - | FileCheck %s

; This is a reduced version of the Conv2D_bfp16 kernel function which only contains
; the innermost loop. It was mostly obtained with llvm-extract, but stores were
; manually removed from the loop.

; Ultimately, we should target II=4

; Function Attrs: mustprogress
define dso_local void @conv2d_bfp16.for.body90.i(<32 x i32> %fW.sroa.0.1489.i, i32 %fW.sroa.14.1488.i, <32 x i32> %fA.sroa.0.1487.i, i32 %fA.sroa.18.1486.i, ptr addrspace(6) %pW.1485.i, ptr addrspace(5) %pA.1484.i, <64 x i32> %0, <64 x i32> %1, <64 x i32> %2, <64 x i32> %3, i32 %4, i32 %5, i20 %6, i20 %7, i20 %8, i20 %9, i20 %10, i20 %11, i32 %12, i32 %13, i32 %14, ptr %.out, ptr %.out1, ptr %.out2, ptr %.out3, ptr %.out4, ptr %.out5, ptr %pA.1.i.out, ptr %pW.1.i.out, ptr %fA.sroa.18.1.i.out, ptr %fA.sroa.0.1.i.out, ptr %fW.sroa.14.1.i.out, ptr %fW.sroa.0.1.i.out) #3 {
; CHECK-LABEL: conv2d_bfp16.for.body90.i:
; CHECK:       // %bb.0: // %newFuncRoot
; CHECK-NEXT:    nopa ; nopb ; nops ; paddxm [sp], #64; nopv
; CHECK-NEXT:    st p6, [sp, #-64]; nopb ; nopx // 4-byte Folded Spill
; CHECK-NEXT:    mov p6, sp
; CHECK-NEXT:    padda [p6], #-320
; CHECK-NEXT:    vlda bmhh4, [p6, #192]
; CHECK-NEXT:    vlda bmhl4, [p6, #128]
; CHECK-NEXT:    vlda bmlh4, [p6, #64]
; CHECK-NEXT:    vlda bmll4, [p6], #-256
; CHECK-NEXT:    vlda bmhh0, [p6, #192]
; CHECK-NEXT:    vlda bmhl0, [p6, #128]
; CHECK-NEXT:    vlda bmlh0, [p6, #64]
; CHECK-NEXT:    vlda bmll0, [p6], #-256
; CHECK-NEXT:    vlda bmhh1, [p6, #192]
; CHECK-NEXT:    vlda bmhl1, [p6, #128]
; CHECK-NEXT:    vlda bmlh1, [p6, #64]
; CHECK-NEXT:    vlda bmll1, [p6], #-256
; CHECK-NEXT:    vlda bmhh2, [p6, #192]
; CHECK-NEXT:    vlda bmhl2, [p6, #128]
; CHECK-NEXT:    vlda bmlh2, [p6, #64]; mov m0, #-4
; CHECK-NEXT:    vlda bmll2, [p6], m0
; CHECK-NEXT:    lda dj4, [p6], #-4
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    lda m1, [p6], #-12; st p7, [sp, #-60]; movx r25, #0 // 4-byte Folded Spill
; CHECK-NEXT:    mova dc4, #0; vldb.fill.512 [p1, lf1, r25]; mov dn0, p3
; CHECK-NEXT:    lda p7, [p6], #-4; vldb.fill.512 [p1, lf1, r25]; movs dj0, p4; mov dn4, p5
; CHECK-NEXT:    lda r3, [p6], #-4; vldb.pop.576 ex9, [p1, lf1, r25]; movx r24, #0; mov m0, p2; movs dc0, dc4
; CHECK-NEXT:    vlda.fill.512 [p0, lf0, r24]; vldb.pop.576.3d ex7, [p1, lf1, r25, d0]
; CHECK-NEXT:    vlda.pop.576 ex5, [p0, lf0, r24]; vldb.fill.512 [p1, lf1, r25]
; CHECK-NEXT:    lda r2, [p6, #0]; vldb.fill.512 [p1, lf1, r25]
; CHECK-NEXT:    vlda.pop.576 ex3, [p0, lf0, r24, m1]; vldb.pop.576 ex9, [p1, lf1, r25]
; CHECK-NEXT:    vlda.fill.512 [p0, lf0, r24]; vldb.pop.576.3d ex7, [p1, lf1, r25, d0]; add r1, r6, #-1
; CHECK-NEXT:    vlda.pop.576 ex5, [p0, lf0, r24]; vldb.fill.512 [p1, lf1, r25]; movxm ls, #.LBB0_1
; CHECK-NEXT:    lda p6, [p6, #-4]; vldb.fill.512 [p1, lf1, r25]; movxm le, #.L_LEnd0
; CHECK-NEXT:    vlda.pop.576 ex3, [p0, lf0, r24, m1]; vldb.pop.576 ex9, [p1, lf1, r25]; nops ; nopx ; add.nc lc, r1, #-4; nopv
; CHECK-NEXT:    vlda.fill.512 [p0, lf0, r24]; vldb.pop.576.3d ex7, [p1, lf1, r25, d0]; nops ; nopx ; vshuffle ex11, ex9, ex7, r4; nopv
; CHECK-NEXT:    vlda.pop.576 ex5, [p0, lf0, r24]; vldb.fill.512 [p1, lf1, r25]; nops ; nopx ; vshuffle ex1, ex9, ex7, r5; nopv
; CHECK-NEXT:    mova r0, #780; vldb.fill.512 [p1, lf1, r25]; nopm
; CHECK-NEXT:    vlda.pop.576 ex3, [p0, lf0, r24, m1]; vldb.pop.576 ex9, [p1, lf1, r25]; vmac.f dm2, dm2, ex11, ex5, r0
; CHECK-NEXT:    vlda.fill.512 [p0, lf0, r24]; vldb.pop.576.3d ex7, [p1, lf1, r25, d0]; vshuffle ex11, ex9, ex7, r4; vmac.f dm1, dm1, ex1, ex5, r0
; CHECK-NEXT:  .LBB0_1: // %for.body90.i
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    vlda.pop.576 ex5, [p0, lf0, r24]; vldb.fill.512 [p1, lf1, r25]; nopx ; vshuffle ex1, ex9, ex7, r5; vmac.f dm0, dm0, ex11, ex3, r0
; CHECK-NEXT:    vldb.fill.512 [p1, lf1, r25]; vmac.f dm4, dm4, ex1, ex3, r0
; CHECK-NEXT:    vlda.pop.576 ex3, [p0, lf0, r24, m1]; vldb.pop.576 ex9, [p1, lf1, r25]; vmac.f dm2, dm2, ex11, ex5, r0
; CHECK-NEXT:  .L_LEnd0:
; CHECK-NEXT:    vlda.fill.512 [p0, lf0, r24]; vldb.pop.576.3d ex7, [p1, lf1, r25, d0]; nops ; nopx ; vshuffle ex11, ex9, ex7, r4; vmac.f dm1, dm1, ex1, ex5, r0
; CHECK-NEXT:  // %bb.2: // %for.cond.cleanup89.i.exitStub
; CHECK-NEXT:    vlda.pop.576 ex5, [p0, lf0, r24]; nopb ; nops ; nopx ; vshuffle ex1, ex9, ex7, r5; vmac.f dm0, dm0, ex11, ex3, r0
; CHECK-NEXT:    vmac.f dm4, dm4, ex1, ex3, r0
; CHECK-NEXT:    vlda.pop.576 ex3, [p0, lf0, r24, m1]; vmac.f dm2, dm2, ex11, ex5, r0
; CHECK-NEXT:    movs p0, r3; vshuffle ex11, ex9, ex7, r4; vmac.f dm1, dm1, ex1, ex5, r0
; CHECK-NEXT:    vshuffle ex1, ex9, ex7, r5; vmac.f dm0, dm0, ex11, ex3, r0
; CHECK-NEXT:    vmac.f dm4, dm4, ex1, ex3, r0
; CHECK-NEXT:    vmac.f dm2, dm2, ex11, ex5, r0
; CHECK-NEXT:    vshuffle ex11, ex9, ex7, r4; vmac.f dm1, dm1, ex1, ex5, r0
; CHECK-NEXT:    vshuffle ex1, ex9, ex7, r5; vmac.f dm0, dm0, ex11, ex3, r0
; CHECK-NEXT:    vmac.f dm4, dm4, ex1, ex3, r0
; CHECK-NEXT:    vmac.f dm2, dm2, ex11, ex5, r0
; CHECK-NEXT:    vmac.f dm1, dm1, ex1, ex5, r0
; CHECK-NEXT:    vmac.f dm0, dm0, ex11, ex3, r0
; CHECK-NEXT:    vmac.f dm4, dm4, ex1, ex3, r0
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst bmhh2, [p7, #192]
; CHECK-NEXT:    vst bmhl2, [p7, #128]
; CHECK-NEXT:    vst bmlh2, [p7, #64]
; CHECK-NEXT:    vst bmll2, [p7, #0]
; CHECK-NEXT:    vst bmhh1, [p0, #192]
; CHECK-NEXT:    vst bmhl1, [p0, #128]
; CHECK-NEXT:    vst bmlh1, [p0, #64]
; CHECK-NEXT:    vst bmll1, [p0, #0]; mov p0, r2
; CHECK-NEXT:    vst bmhh0, [p0, #192]
; CHECK-NEXT:    lda p7, [sp, #-60]; vst bmhl0, [p0, #128] // 4-byte Folded Reload
; CHECK-NEXT:    lda p6, [sp, #-64]; vst bmlh0, [p0, #64] // 4-byte Folded Reload
; CHECK-NEXT:    vst bmll0, [p0, #0]; ret lr
; CHECK-NEXT:    vst bmhh4, [p6, #192] // Delay Slot 5
; CHECK-NEXT:    vst bmhl4, [p6, #128] // Delay Slot 4
; CHECK-NEXT:    vst bmlh4, [p6, #64] // Delay Slot 3
; CHECK-NEXT:    vst bmll4, [p6, #0]; paddxm [sp], #-64 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
newFuncRoot:
  br label %for.body90.i

for.body90.i:                                     ; preds = %newFuncRoot, %for.body90.i
  %fW.sroa.0.1502.i = phi <32 x i32> [ undef, %newFuncRoot ], [ %fW.sroa.0.1.i, %for.body90.i ]
  %fW.sroa.14.1501.i = phi i32 [ 0, %newFuncRoot ], [ %fW.sroa.14.1.i, %for.body90.i ]
  %fA.sroa.0.1500.i = phi <32 x i32> [ undef, %newFuncRoot ], [ %fA.sroa.0.1.i, %for.body90.i ]
  %fA.sroa.18.1499.i = phi i32 [ 0, %newFuncRoot ], [ %fA.sroa.18.1.i, %for.body90.i ]
  %pW.1498.i = phi ptr addrspace(6) [ %pW.1485.i, %newFuncRoot ], [ %pW.1.i, %for.body90.i ]
  %pA.1497.i = phi ptr addrspace(5) [ %pA.1484.i, %newFuncRoot ], [ %pA.1.i, %for.body90.i ]
  %i.0496.i = phi i32 [ 1, %newFuncRoot ], [ %inc.i, %for.body90.i ]
  %accs.sroa.26.1495.i = phi <64 x i32> [ %0, %newFuncRoot ], [ %60, %for.body90.i ]
  %accs.sroa.18.1494.i = phi <64 x i32> [ %1, %newFuncRoot ], [ %59, %for.body90.i ]
  %accs.sroa.10.1493.i = phi <64 x i32> [ %2, %newFuncRoot ], [ %58, %for.body90.i ]
  %accs.sroa.0.1492.i = phi <64 x i32> [ %3, %newFuncRoot ], [ %57, %for.body90.i ]
  %dimsAI.sroa.17.1491.i = phi i32 [ 0, %newFuncRoot ], [ %41, %for.body90.i ]
  %dimsAI.sroa.13.1490.i = phi i32 [ 0, %newFuncRoot ], [ %39, %for.body90.i ]
  %15 = tail call { ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr addrspace(5) %pA.1497.i, <32 x i32> %fA.sroa.0.1500.i, i32 %fA.sroa.18.1499.i), !alias.scope !4, !noalias !7
  %16 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %15, 0
  %17 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %15, 1
  %18 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %15, 2
  %19 = tail call { ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr addrspace(5) %16, <32 x i32> %17, i32 %18), !alias.scope !4, !noalias !7
  %20 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %19, 0
  %21 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %19, 1
  %22 = extractvalue { ptr addrspace(5), <32 x i32>, i32 } %19, 2
  %23 = tail call { ptr addrspace(6), <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr addrspace(6) %pW.1498.i, <32 x i32> %fW.sroa.0.1502.i, i32 %fW.sroa.14.1501.i), !alias.scope !11, !noalias !12
  %24 = extractvalue { ptr addrspace(6), <32 x i32>, i32 } %23, 0
  %25 = extractvalue { ptr addrspace(6), <32 x i32>, i32 } %23, 1
  %26 = extractvalue { ptr addrspace(6), <32 x i32>, i32 } %23, 2
  %27 = tail call { ptr addrspace(5), <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.bfp16.p0.p0(ptr addrspace(5) %20, <32 x i32> %21, i32 %22), !alias.scope !4, !noalias !7
  %28 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <64 x i8>, <8 x i8> } %27, 0
  %29 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <64 x i8>, <8 x i8> } %27, 1
  %30 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <64 x i8>, <8 x i8> } %27, 2
  %31 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <64 x i8>, <8 x i8> } %27, 3
  %32 = extractvalue { ptr addrspace(5), <32 x i32>, i32, <64 x i8>, <8 x i8> } %27, 4
  %33 = trunc nuw i32 %dimsAI.sroa.13.1490.i to i20
  %34 = trunc nuw i32 %dimsAI.sroa.17.1491.i to i20
  %35 = tail call { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.3d.bfp16.p0.p0(ptr addrspace(5) %28, <32 x i32> %29, i32 %30, i20 %6, i20 %7, i20 %33, i20 %8, i20 %9, i20 %34, i20 %10), !alias.scope !4, !noalias !7
  %36 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %35, 5
  %37 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %35, 6
  %38 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %35, 3
  %39 = zext i20 %38 to i32
  %40 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %35, 4
  %41 = zext i20 %40 to i32
  %42 = tail call { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.bfp16.p0.p0(ptr addrspace(6) %24, <32 x i32> %25, i32 %26), !alias.scope !11, !noalias !12
  %43 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %42, 0
  %44 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %42, 1
  %45 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %42, 2
  %46 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %42, 3
  %47 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %42, 4
  %48 = tail call { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.1d.bfp16.p0.p0(ptr addrspace(6) %43, <32 x i32> %44, i32 %45, i20 %11), !alias.scope !11, !noalias !12
  %49 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %48, 3
  %50 = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %48, 4
  %51 = tail call { <64 x i8>, <8 x i8> } @llvm.aie2p.vshuffle.576.bfp16(<64 x i8> %31, <8 x i8> %32, <64 x i8> %36, <8 x i8> %37, i32 %12)
  %52 = extractvalue { <64 x i8>, <8 x i8> } %51, 0
  %53 = extractvalue { <64 x i8>, <8 x i8> } %51, 1
  %54 = tail call { <64 x i8>, <8 x i8> } @llvm.aie2p.vshuffle.576.bfp16(<64 x i8> %31, <8 x i8> %32, <64 x i8> %36, <8 x i8> %37, i32 %13)
  %55 = extractvalue { <64 x i8>, <8 x i8> } %54, 0
  %56 = extractvalue { <64 x i8>, <8 x i8> } %54, 1
  %57 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mac.conf(<64 x i8> %52, <8 x i8> %53, <64 x i8> %46, <8 x i8> %47, <64 x i32> %accs.sroa.0.1492.i, i32 780)
  %58 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mac.conf(<64 x i8> %55, <8 x i8> %56, <64 x i8> %46, <8 x i8> %47, <64 x i32> %accs.sroa.10.1493.i, i32 780)
  %59 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mac.conf(<64 x i8> %52, <8 x i8> %53, <64 x i8> %49, <8 x i8> %50, <64 x i32> %accs.sroa.18.1494.i, i32 780)
  %60 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mac.conf(<64 x i8> %55, <8 x i8> %56, <64 x i8> %49, <8 x i8> %50, <64 x i32> %accs.sroa.26.1495.i, i32 780)
  %inc.i = add nuw i32 %i.0496.i, 1
  %pA.1.i = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %35, 0
  %pW.1.i = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %48, 0
  %fA.sroa.18.1.i = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %35, 2
  %fA.sroa.0.1.i = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %35, 1
  %fW.sroa.14.1.i = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %48, 2
  %fW.sroa.0.1.i = extractvalue { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } %48, 1
  %exitcond.not.i = icmp eq i32 %inc.i, %14
  br i1 %exitcond.not.i, label %for.cond.cleanup89.i.exitStub, label %for.body90.i, !llvm.loop !13

for.cond.cleanup89.i.exitStub:                    ; preds = %for.body90.i
  store <64 x i32> %57, ptr %.out2, align 256
  store <64 x i32> %58, ptr %.out3, align 256
  store <64 x i32> %59, ptr %.out4, align 256
  store <64 x i32> %60, ptr %.out5, align 256
  ret void
}

; Function Attrs: nounwind memory(argmem: read)
declare { ptr addrspace(5), <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p5.p5(ptr addrspace(5), <32 x i32>, i32) #0

; Function Attrs: nounwind memory(argmem: read)
declare { ptr addrspace(6), <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p6.p6(ptr addrspace(6), <32 x i32>, i32) #0

; Function Attrs: nounwind memory(argmem: read)
declare { ptr addrspace(5), <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.bfp16.p5.p5(ptr addrspace(5), <32 x i32>, i32) #0

; Function Attrs: nounwind memory(argmem: read)
declare { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.3d.bfp16.p5.p5(ptr addrspace(5), <32 x i32>, i32, i20, i20, i20, i20, i20, i20, i20) #0

; Function Attrs: nounwind memory(argmem: read)
declare { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.bfp16.p6.p6(ptr addrspace(6), <32 x i32>, i32) #0

; Function Attrs: nounwind memory(argmem: read)
declare { ptr addrspace(6), <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.1d.bfp16.p6.p6(ptr addrspace(6), <32 x i32>, i32, i20) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare { <64 x i8>, <8 x i8> } @llvm.aie2p.vshuffle.576.bfp16(<64 x i8>, <8 x i8>, <64 x i8>, <8 x i8>, i32) #1

; Function Attrs: nounwind memory(inaccessiblemem: read)
declare <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mac.conf(<64 x i8>, <8 x i8>, <64 x i8>, <8 x i8>, <64 x i32>, i32) #2

attributes #0 = { nounwind memory(argmem: read) }
attributes #1 = { nocallback nofree nosync nounwind willreturn memory(none) }
attributes #2 = { nounwind memory(inaccessiblemem: read) }
attributes #3 = { mustprogress "no-jump-tables"="true" "no-trapping-math"="true" "stack-protector-buffer-size"="8" }

!llvm.linker.options = !{}
!llvm.module.flags = !{!0, !1, !2}

!0 = !{i32 7, !"Dwarf Version", i32 4}
!1 = !{i32 2, !"Debug Info Version", i32 3}
!2 = !{i32 1, !"wchar_size", i32 4}
!4 = !{!5}
!5 = distinct !{!5, !6, !"_Z14conv2d_genericILh1EL5act_t0ELb0ELb0EEvPu6__bf16S1_S1_S1_R27conv2d_bf16_internal_params10out_mode_t: %input"}
!6 = distinct !{!6, !"_Z14conv2d_genericILh1EL5act_t0ELb0ELb0EEvPu6__bf16S1_S1_S1_R27conv2d_bf16_internal_params10out_mode_t"}
!7 = !{!8, !9, !10}
!8 = distinct !{!8, !6, !"_Z14conv2d_genericILh1EL5act_t0ELb0ELb0EEvPu6__bf16S1_S1_S1_R27conv2d_bf16_internal_params10out_mode_t: %weights"}
!9 = distinct !{!9, !6, !"_Z14conv2d_genericILh1EL5act_t0ELb0ELb0EEvPu6__bf16S1_S1_S1_R27conv2d_bf16_internal_params10out_mode_t: %acc_in"}
!10 = distinct !{!10, !6, !"_Z14conv2d_genericILh1EL5act_t0ELb0ELb0EEvPu6__bf16S1_S1_S1_R27conv2d_bf16_internal_params10out_mode_t: %output"}
!11 = !{!8}
!12 = !{!5, !9, !10}
!13 = distinct !{!13, !14, !15, !16}
!14 = !{!"llvm.loop.mustprogress"}
!15 = !{!"llvm.loop.itercount.range", i64 7}
!16 = !{!"llvm.loop.unroll.disable"}
