; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie2p --aie-reg-rewrite-mode=latencyaware %s -o - | FileCheck %s

; Test postSWP capabilities related to conv2d_dw_bf16.

; Function Attrs: nounwind memory(none)
declare <32 x float> @llvm.aie2p.v32bf16.to.v32accfloat(<32 x bfloat>) #0

; Function Attrs: nounwind memory(none)
declare { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr, i20, i20, i20, i20, i20, i20, i20) #0

; Function Attrs: nounwind memory(none)
declare <32 x bfloat> @llvm.aie2p.vshift.bf512.bf512(<32 x bfloat>, <32 x bfloat>, i32, i32) #0

; Function Attrs: nounwind memory(none)
declare { ptr, i20 } @llvm.aie2p.add.2d(ptr, i20, i20, i20, i20) #0

; Function Attrs: nounwind memory(none)
declare <16 x i32> @llvm.aie2p.vextract.broadcast128.I512(<16 x i32>, i32) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read)
declare <32 x float> @llvm.aie2p.I512.I512.ACC1024.bf.mac.conf(<32 x bfloat>, <32 x bfloat>, <32 x float>, i32) #1

; Function Attrs: nounwind memory(inaccessiblemem: read)
declare <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float>) #2

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare { <32 x bfloat>, i32 } @llvm.aie2p.vmax.ltbf16(<32 x bfloat>, <32 x bfloat>) #3

; Function Attrs: nounwind memory(none)
declare <16 x i32> @llvm.aie2p.vshuffle(<16 x i32>, <16 x i32>, i32) #0

; Function Attrs: mustprogress noinline
define dso_local void @conv2d_dw_bf16(i32 %0, ptr %output, ptr %input, ptr addrspace(6) %1, ptr %bias, i32 %2, i20 %3, i20 %4, i20 %5, i20 %6, i20 %7, i20 %8, i20 %9, i20 %10, i20 %11, i20 %12, i20 %13, i20 %14, i20 %15, i20 %16, i20 %17, i20 %18, <32 x bfloat> %splat.splat.i.i.i.i.i.i.i.i.i, i20 %idx.ext.i, i32 %19, i20 %20, i20 %21, i20 %22, i20 %23, i20 %24) {
; CHECK-LABEL: conv2d_dw_bf16:
; CHECK:       // %bb.0: // %newFuncRoot
; CHECK-NEXT:    paddxm [sp], #64
; CHECK-NEXT:    st p6, [sp, #-64]; nopx // 4-byte Folded Spill
; CHECK-NEXT:    mova m0, #-68; mov p6, sp
; CHECK-NEXT:    padda [p6], m0
; CHECK-NEXT:    lda dj4, [p6], #-4
; CHECK-NEXT:    lda dn0, [p6], #-4
; CHECK-NEXT:    lda dn4, [p6], #-4
; CHECK-NEXT:    lda m1, [p6], #-4
; CHECK-NEXT:    lda dj1, [p6, #0]
; CHECK-NEXT:    lda dn1, [p6, #-4]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    mova dc0, #0
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml4, [p3, #0]; mov dc1, dc0
; CHECK-NEXT:    vlda x7, [p1], #64; vldb.2d x9, [p2], d1; mov dj0, p5
; CHECK-NEXT:    vlda x5, [p1], #64; movs dc4, dc0; mov m0, p4
; CHECK-NEXT:    vlda.3d x3, [p1], d0
; CHECK-NEXT:    add.nc lc, r1, #-1
; CHECK-NEXT:    movxm ls, #.LBB0_1
; CHECK-NEXT:    movxm le, #.L_LEnd0
; CHECK-NEXT:    vmov cml3, cml4
; CHECK-NEXT:    mova r0, #16; vextbcst.128 x11, x9, #0
; CHECK-NEXT:    mova r5, #60; vshift x2, x7, x5, r0
; CHECK-NEXT:    vextbcst.128 x4, x9, #1; vmac.f dm0, dm4, x7, x11, r5
; CHECK-NEXT:    mova r3, #32; vshift x6, x5, x3, r0; vmac.f dm4, dm3, x5, x11, r5
; CHECK-NEXT:    mova r4, #48; vshift x8, x7, x5, r3
; CHECK-NEXT:  .LBB0_1: // %for.body28
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    vlda x7, [p1], #64; vldb.2d x9, [p2], d1; nopx ; vextbcst.128 x11, x9, #2; vmac.f dm3, dm0, x2, x4, r5
; CHECK-NEXT:    vlda x5, [p1], #64; vshift x2, x5, x3, r3; vmac.f dm2, dm4, x6, x4, r5
; CHECK-NEXT:    vlda.3d x3, [p1], d0; vshift x1, x7, x5, r4
; CHECK-NEXT:    vextbcst.128 x10, x9, #3; vmac.f dm1, dm3, x8, x11, r5
; CHECK-NEXT:    vshift x8, x5, x3, r4; vmac.f dm0, dm2, x2, x11, r5
; CHECK-NEXT:    nop
; CHECK-NEXT:    vmac.f dm4, dm1, x1, x10, r5
; CHECK-NEXT:    vextbcst.128 x11, x9, #0; vmac.f dm3, dm0, x8, x10, r5
; CHECK-NEXT:    vshift x2, x7, x5, r0
; CHECK-NEXT:    vextbcst.128 x4, x9, #1; vmac.f dm0, dm4, x7, x11, r5
; CHECK-NEXT:    vshift x6, x5, x3, r0; vmac.f dm4, dm3, x5, x11, r5
; CHECK-NEXT:  .L_LEnd0:
; CHECK-NEXT:    nopa ; nopb ; nops ; nopx ; vshift x8, x7, x5, r3; nopv
; CHECK-NEXT:  // %bb.2: // %for.cond.cleanup27
; CHECK-NEXT:    lda p6, [sp, #-64]; nopb ; nops ; nopx ; vextbcst.128 x11, x9, #2; vmac.f dm3, dm0, x2, x4, r5 // 4-byte Folded Reload
; CHECK-NEXT:    vshift x2, x5, x3, r3; vmac.f dm2, dm4, x6, x4, r5
; CHECK-NEXT:    vshift x1, x7, x5, r4
; CHECK-NEXT:    vextbcst.128 x10, x9, #3; vmac.f dm1, dm3, x8, x11, r5
; CHECK-NEXT:    vshift x8, x5, x3, r4; vmac.f dm0, dm2, x2, x11, r5
; CHECK-NEXT:    nop
; CHECK-NEXT:    vmac.f dm4, dm1, x1, x10, r5
; CHECK-NEXT:    vmac.f dm3, dm0, x8, x10, r5
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vconv.bf16.fp32 x2, cml4
; CHECK-NEXT:    vconv.bf16.fp32 x4, cml3
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    vshuffle x2, x2, x4, r2 // Delay Slot 5
; CHECK-NEXT:    vmax_lt.bf16 x0, r16, x2, x0 // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vst x0, [p0, #0]; paddxm [sp], #-64 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
newFuncRoot:
  br label %for.body

for.body:                                         ; preds = %newFuncRoot
  %p_bias.0 = addrspacecast ptr %bias to ptr addrspace(6)
  %25 = load <32 x bfloat>, ptr addrspace(6) %p_bias.0, align 64, !tbaa !4, !noalias !7
  %26 = tail call noundef <32 x float> @llvm.aie2p.v32bf16.to.v32accfloat(<32 x bfloat> %25)
  br label %for.body28

for.body28:                                       ; preds = %for.body28, %for.body
  %lsr.iv = phi i32 [ %2, %for.body ], [ %lsr.iv.next, %for.body28 ]
  %p_in.1.in78 = phi ptr [ %input, %for.body ], [ %38, %for.body28 ]
  %p_weight.177 = phi ptr addrspace(6) [ %1, %for.body ], [ %52, %for.body28 ]
  %iterator_inner_cnt0.176 = phi i32 [ 0, %for.body ], [ %35, %for.body28 ]
  %iterator_inner_cnt1.175 = phi i32 [ 0, %for.body ], [ %37, %for.body28 ]
  %iterator_wts_cnt0.174 = phi i32 [ 0, %for.body ], [ %50, %for.body28 ]
  %acc0.sroa.0.073 = phi <32 x float> [ %26, %for.body ], [ %64, %for.body28 ]
  %acc1.sroa.0.072 = phi <32 x float> [ %26, %for.body ], [ %68, %for.body28 ]
  %p_in.1 = addrspacecast ptr %p_in.1.in78 to ptr addrspace(5)
  %27 = load <32 x bfloat>, ptr addrspace(5) %p_in.1, align 64, !tbaa !4, !noalias !14
  %add.ptr = getelementptr inbounds nuw i8, ptr addrspace(5) %p_in.1, i20 64
  %28 = load <32 x bfloat>, ptr addrspace(5) %add.ptr, align 64, !tbaa !4, !noalias !21
  %add.ptr32 = getelementptr inbounds nuw i8, ptr addrspace(5) %p_in.1, i20 128
  %29 = load <32 x bfloat>, ptr addrspace(5) %add.ptr32, align 64, !tbaa !4, !noalias !28
  %30 = addrspacecast ptr addrspace(5) %add.ptr32 to ptr
  %31 = trunc nuw i32 %iterator_inner_cnt0.176 to i20
  %32 = trunc nuw i32 %iterator_inner_cnt1.175 to i20
  %33 = tail call { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr %30, i20 %3, i20 %4, i20 %5, i20 %6, i20 %31, i20 %7, i20 %32)
  %34 = extractvalue { ptr, i20, i20 } %33, 1
  %35 = zext i20 %34 to i32
  %36 = extractvalue { ptr, i20, i20 } %33, 2
  %37 = zext i20 %36 to i32
  %38 = extractvalue { ptr, i20, i20 } %33, 0
  %39 = tail call noundef <32 x bfloat> @llvm.aie2p.vshift.bf512.bf512(<32 x bfloat> %27, <32 x bfloat> %28, i32 0, i32 16)
  %40 = tail call noundef <32 x bfloat> @llvm.aie2p.vshift.bf512.bf512(<32 x bfloat> %27, <32 x bfloat> %28, i32 0, i32 32)
  %41 = tail call noundef <32 x bfloat> @llvm.aie2p.vshift.bf512.bf512(<32 x bfloat> %27, <32 x bfloat> %28, i32 0, i32 48)
  %42 = tail call noundef <32 x bfloat> @llvm.aie2p.vshift.bf512.bf512(<32 x bfloat> %28, <32 x bfloat> %29, i32 0, i32 16)
  %43 = tail call noundef <32 x bfloat> @llvm.aie2p.vshift.bf512.bf512(<32 x bfloat> %28, <32 x bfloat> %29, i32 0, i32 32)
  %44 = tail call noundef <32 x bfloat> @llvm.aie2p.vshift.bf512.bf512(<32 x bfloat> %28, <32 x bfloat> %29, i32 0, i32 48)
  %45 = load <16 x i32>, ptr addrspace(6) %p_weight.177, align 64, !tbaa !4, !noalias !35
  %46 = addrspacecast ptr addrspace(6) %p_weight.177 to ptr
  %47 = trunc nuw i32 %iterator_wts_cnt0.174 to i20
  %48 = tail call { ptr, i20 } @llvm.aie2p.add.2d(ptr %46, i20 %8, i20 %9, i20 %10, i20 %47)
  %49 = extractvalue { ptr, i20 } %48, 1
  %50 = zext i20 %49 to i32
  %51 = extractvalue { ptr, i20 } %48, 0
  %52 = addrspacecast ptr %51 to ptr addrspace(6)
  %53 = tail call noundef <16 x i32> @llvm.aie2p.vextract.broadcast128.I512(<16 x i32> %45, i32 1)
  %54 = bitcast <16 x i32> %53 to <32 x bfloat>
  %55 = tail call noundef <16 x i32> @llvm.aie2p.vextract.broadcast128.I512(<16 x i32> %45, i32 2)
  %56 = bitcast <16 x i32> %55 to <32 x bfloat>
  %57 = tail call noundef <16 x i32> @llvm.aie2p.vextract.broadcast128.I512(<16 x i32> %45, i32 3)
  %58 = bitcast <16 x i32> %57 to <32 x bfloat>
  %59 = tail call noundef <16 x i32> @llvm.aie2p.vextract.broadcast128.I512(<16 x i32> %45, i32 0)
  %60 = bitcast <16 x i32> %59 to <32 x bfloat>
  %61 = tail call noundef <32 x float> @llvm.aie2p.I512.I512.ACC1024.bf.mac.conf(<32 x bfloat> %27, <32 x bfloat> %60, <32 x float> %acc0.sroa.0.073, i32 60)
  %62 = tail call noundef <32 x float> @llvm.aie2p.I512.I512.ACC1024.bf.mac.conf(<32 x bfloat> %39, <32 x bfloat> %54, <32 x float> %61, i32 60)
  %63 = tail call noundef <32 x float> @llvm.aie2p.I512.I512.ACC1024.bf.mac.conf(<32 x bfloat> %40, <32 x bfloat> %56, <32 x float> %62, i32 60)
  %64 = tail call noundef <32 x float> @llvm.aie2p.I512.I512.ACC1024.bf.mac.conf(<32 x bfloat> %41, <32 x bfloat> %58, <32 x float> %63, i32 60)
  %65 = tail call noundef <32 x float> @llvm.aie2p.I512.I512.ACC1024.bf.mac.conf(<32 x bfloat> %28, <32 x bfloat> %60, <32 x float> %acc1.sroa.0.072, i32 60)
  %66 = tail call noundef <32 x float> @llvm.aie2p.I512.I512.ACC1024.bf.mac.conf(<32 x bfloat> %42, <32 x bfloat> %54, <32 x float> %65, i32 60)
  %67 = tail call noundef <32 x float> @llvm.aie2p.I512.I512.ACC1024.bf.mac.conf(<32 x bfloat> %43, <32 x bfloat> %56, <32 x float> %66, i32 60)
  %68 = tail call noundef <32 x float> @llvm.aie2p.I512.I512.ACC1024.bf.mac.conf(<32 x bfloat> %44, <32 x bfloat> %58, <32 x float> %67, i32 60)
  %lsr.iv.next = add i32 %lsr.iv, -1
  %exitcond.not = icmp eq i32 %lsr.iv.next, 0
  br i1 %exitcond.not, label %for.cond.cleanup27, label %for.body28, !llvm.loop !42

for.cond.cleanup27:                               ; preds = %for.body28
  %83 = tail call noundef <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float> %64)
  %84 = tail call noundef <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float> %68)
  %87 = bitcast <32 x bfloat> %83 to <16 x i32>
  %88 = bitcast <32 x bfloat> %84 to <16 x i32>
  %89 = tail call <16 x i32> @llvm.aie2p.vshuffle(<16 x i32> %87, <16 x i32> %88, i32 %19)
  %90 = bitcast <16 x i32> %89 to <32 x bfloat>
  %91 = tail call { <32 x bfloat>, i32 } @llvm.aie2p.vmax.ltbf16(<32 x bfloat> %90, <32 x bfloat> %splat.splat.i.i.i.i.i.i.i.i.i)
  %92 = extractvalue { <32 x bfloat>, i32 } %91, 0
  store <32 x bfloat> %92, ptr %output, align 64, !tbaa !4
  ret void
}

!4 = !{!5, !5, i64 0}
!5 = !{!"omnipotent char", !6, i64 0}
!6 = !{!"Simple C++ TBAA"}
!7 = !{!8, !10, !12}
!8 = distinct !{!8, !9, !"A: %agg.result"}
!9 = distinct !{!9, !"A"}
!10 = distinct !{!10, !11, !"B: %agg.result"}
!11 = distinct !{!11, !"B"}
!12 = distinct !{!12, !13, !"C: %agg.result"}
!13 = distinct !{!13, !"A"}
!14 = !{!15, !17, !19}
!15 = distinct !{!15, !16, !"B: %agg.result"}
!16 = distinct !{!16, !"B"}
!17 = distinct !{!17, !18, !"C: %agg.result"}
!18 = distinct !{!18, !"C"}
!19 = distinct !{!19, !20, !"D: %agg.result"}
!20 = distinct !{!20, !"D"}
!21 = !{!22, !24, !26}
!22 = distinct !{!22, !23, !"B: %agg.result"}
!23 = distinct !{!23, !"B"}
!24 = distinct !{!24, !25, !"C: %agg.result"}
!25 = distinct !{!25, !"C"}
!26 = distinct !{!26, !27, !"D: %agg.result"}
!27 = distinct !{!27, !"D"}
!28 = !{!29, !31, !33}
!29 = distinct !{!29, !30, !"B: %agg.result"}
!30 = distinct !{!30, !"B"}
!31 = distinct !{!31, !32, !"C: %agg.result"}
!32 = distinct !{!32, !"C"}
!33 = distinct !{!33, !34, !"D: %agg.result"}
!34 = distinct !{!34, !"D"}
!35 = !{!36, !38, !40}
!36 = distinct !{!36, !37, !"E: %agg.result"}
!37 = distinct !{!37, !"E"}
!38 = distinct !{!38, !39, !"F: %agg.result"}
!39 = distinct !{!39, !"F"}
!40 = distinct !{!40, !41, !"A: %agg.result"}
!41 = distinct !{!41, !"A"}
!42 = distinct !{!42, !43, !44}
!43 = !{!"llvm.loop.mustprogress"}
!44 = !{!"llvm.loop.itercount.range", i64 2}
!45 = distinct !{!45, !43, !44}
