; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie2p %s -o - | FileCheck %s

; Test that the use of llvm.loop.pipeline.initiationinterval can force pre-swp to accepted
; high stage counts.

@_ZN11gelu_lut_32ILj0ELj512EE7data_abE = external dso_local global [512 x i32], align 64
@_ZN11gelu_lut_32ILj0ELj512EE7data_cdE = external dso_local global [512 x i32], align 64

; Function Attrs: mustprogress noinline
define void @gelu_fn(ptr noalias %ifm, ptr noalias %ofm, ptr nonnull align 64 dereferenceable(64) %params) {
; CHECK-LABEL: gelu_fn:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml1, [p0], #64; nopx
; CHECK-NEXT:    movxm r0, #16544
; CHECK-NEXT:    vbcst.16 x6, r0
; CHECK-NEXT:    lda r1, [p2, #0]; movxm r0, #17280
; CHECK-NEXT:    mova r0, #60; vbcst.16 x2, r0
; CHECK-NEXT:    vadd.f dm3, dm1, dm0, r0
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml2, [p0], #64; vconv.fp32.bf16 cml0, x6
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    movxm r2, #15821
; CHECK-NEXT:    mova r2, #255; movx r4, #1; vbcst.16 x4, r2; vadd.f dm3, dm2, dm0, r0
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml1, [p0], #64; vconv.bf16.fp32 x8, cml3; lshl r2, r1, r4; vbcst.16 x0, r2
; CHECK-NEXT:    mova r2, #828; mov m0, r2
; CHECK-NEXT:    vmul.f dm2, x8, x2, r2
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vconv.bf16.fp32 x10, cml3; vadd.f dm3, dm1, dm0, r0
; CHECK-NEXT:    nop
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml2, [p0], #64; vmul.f dm1, x10, x2, r2
; CHECK-NEXT:    vconv.bf16.fp32 x8, cml2
; CHECK-NEXT:    nop
; CHECK-NEXT:    vmul.f dm4, x8, x4, r2
; CHECK-NEXT:    vconv.bf16.fp32 x1, cml3; vadd.f dm3, dm2, dm0, r0
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml1, [p0], #64
; CHECK-NEXT:    vconv.bf16.fp32 x10, cml1; vmul.f dm2, x1, x2, r2
; CHECK-NEXT:    nop
; CHECK-NEXT:    vmul.f dm4, x10, x4, r2
; CHECK-NEXT:    mova r3, #0; vconv.bf16.fp32 x8, cml4; vadd.f dm1, dm1, dm0, r0
; CHECK-NEXT:    vconv.bf16.fp32 x7, cml3; mov s0, r3
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml2, [p0], #64; vfloor.s32.bf16 x1, wl8, s0
; CHECK-NEXT:    vconv.bf16.fp32 x5, cml2; vmul.f dm3, x7, x2, r2
; CHECK-NEXT:    vfloor.s32.bf16 x3, wh8, s0; movxm ls, #.LBB0_1
; CHECK-NEXT:    mova r4, #-5; nopb ; vconv.bf16.fp32 x10, cml4; movxm le, #.L_LEnd0; vmul.f dm4, x5, x4, r2
; CHECK-NEXT:    vconv.bf16.fp32 x7, cml1; lshl r4, r1, r4; vadd.f dm2, dm2, dm0, r0
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml1, [p0], #64; movx r1, #2; vbcst.16 x6, r3
; CHECK-NEXT:    vfloor.s32.bf16 x9, wl10, s0; vshuffle x1, x1, x3, r1; vmul.f dm4, x7, x2, r2
; CHECK-NEXT:    vconv.bf16.fp32 x5, cml3; vmin_ge.16 x3, r16, x1, x0, vaddsign1
; CHECK-NEXT:    nopa ; nopb ; vfloor.s32.bf16 x3, wh10, s0; nopx ; add.nc lc, r4, #-7; nopv
; CHECK-NEXT:    padda [p1], m0; nopb ; vconv.bf16.fp32 x8, cml4; nopx ; vmax_lt.16 x11, r16, x3, x6, vaddsign1; vmul.f dm3, x5, x4, r2
; CHECK-NEXT:  .LBB0_1: // %for.body
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    nopa ; nopb ; vconv.bf16.fp32 x10, cml2; nopxm ; nopv
; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; vadd.f dm2, dm4, dm0, r0
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml1, [p0], #64; nopb ; vconv.bf16.fp32 x7, cml4; nopx ; vmov cml4, cml1; vmul.f dm4, x10, x2, r2
; CHECK-NEXT:    nopa ; nopb ; vst x11, [p1], #64; nopx ; vshuffle x1, x9, x3, r1; nopv
; CHECK-NEXT:    vfloor.s32.bf16 x3, wh8, s0; vmin_ge.16 x5, r16, x1, x0, vaddsign1
; CHECK-NEXT:    vfloor.s32.bf16 x9, wl8, s0; vmax_lt.16 x11, r16, x5, x6, vaddsign1
; CHECK-NEXT:  .L_LEnd0:
; CHECK-NEXT:    nopa ; nopb ; vconv.bf16.fp32 x8, cml3; nopxm ; vmul.f dm3, x7, x4, r2
; CHECK-NEXT:  // %bb.2:
; CHECK-NEXT:    nopa ; nopb ; nops ; nopx ; vshuffle x10, x9, x3, r1; nopv
; CHECK-NEXT:    vmin_ge.16 x10, r16, x10, x0, vaddsign1
; CHECK-NEXT:    vmax_lt.16 x10, r16, x10, x6, vaddsign1
; CHECK-NEXT:    vst x11, [p1], #64
; CHECK-NEXT:    vst x10, [p1], #64
; CHECK-NEXT:    vfloor.s32.bf16 x10, wl8, s0
; CHECK-NEXT:    vfloor.s32.bf16 x8, wh8, s0
; CHECK-NEXT:    nop
; CHECK-NEXT:    vshuffle x8, x10, x8, r1
; CHECK-NEXT:    vmin_ge.16 x8, r16, x8, x0, vaddsign1
; CHECK-NEXT:    vmax_lt.16 x8, r16, x8, x6, vaddsign1
; CHECK-NEXT:    vconv.bf16.fp32 x8, cml3
; CHECK-NEXT:    vst x8, [p1], #64
; CHECK-NEXT:    vfloor.s32.bf16 x10, wl8, s0
; CHECK-NEXT:    vfloor.s32.bf16 x8, wh8, s0
; CHECK-NEXT:    nop
; CHECK-NEXT:    vshuffle x8, x10, x8, r1
; CHECK-NEXT:    vmin_ge.16 x8, r16, x8, x0, vaddsign1
; CHECK-NEXT:    vmax_lt.16 x8, r16, x8, x6, vaddsign1
; CHECK-NEXT:    vconv.bf16.fp32 x8, cml4
; CHECK-NEXT:    vst x8, [p1], #64
; CHECK-NEXT:    vmul.f dm3, x8, x4, r2
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vconv.bf16.fp32 x8, cml3
; CHECK-NEXT:    nop
; CHECK-NEXT:    vfloor.s32.bf16 x10, wl8, s0
; CHECK-NEXT:    vfloor.s32.bf16 x8, wh8, s0
; CHECK-NEXT:    nop
; CHECK-NEXT:    vshuffle x8, x10, x8, r1
; CHECK-NEXT:    vmin_ge.16 x8, r16, x8, x0, vaddsign1
; CHECK-NEXT:    vmax_lt.16 x8, r16, x8, x6, vaddsign1
; CHECK-NEXT:    vconv.bf16.fp32 x8, cml2
; CHECK-NEXT:    vst x8, [p1], #64
; CHECK-NEXT:    vmul.f dm2, x8, x2, r2
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vconv.bf16.fp32 x8, cml2
; CHECK-NEXT:    nop
; CHECK-NEXT:    vmul.f dm2, x8, x4, r2
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vconv.bf16.fp32 x8, cml2
; CHECK-NEXT:    nop
; CHECK-NEXT:    vfloor.s32.bf16 x10, wl8, s0; vadd.f dm0, dm1, dm0, r0
; CHECK-NEXT:    vfloor.s32.bf16 x8, wh8, s0
; CHECK-NEXT:    nop
; CHECK-NEXT:    vshuffle x8, x10, x8, r1
; CHECK-NEXT:    vmin_ge.16 x8, r16, x8, x0, vaddsign1
; CHECK-NEXT:    vmax_lt.16 x8, r16, x8, x6, vaddsign1
; CHECK-NEXT:    vconv.bf16.fp32 x8, cml0
; CHECK-NEXT:    vst x8, [p1], #64
; CHECK-NEXT:    vmul.f dm0, x8, x2, r2
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vconv.bf16.fp32 x2, cml0
; CHECK-NEXT:    nop
; CHECK-NEXT:    vmul.f dm0, x2, x4, r2
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vconv.bf16.fp32 x2, cml0
; CHECK-NEXT:    nop
; CHECK-NEXT:    vfloor.s32.bf16 x4, wl2, s0
; CHECK-NEXT:    vfloor.s32.bf16 x2, wh2, s0
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr; vshuffle x2, x4, x2, r1
; CHECK-NEXT:    vmin_ge.16 x0, r16, x2, x0, vaddsign1 // Delay Slot 5
; CHECK-NEXT:    vmax_lt.16 x0, r16, x0, x6, vaddsign1 // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vst x0, [p1], #64 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
  entry:
    %0 = addrspacecast ptr %ifm to ptr addrspace(5)
    %1 = addrspacecast ptr %ofm to ptr addrspace(6)
    %2 = load i32, ptr %params, align 64, !tbaa !4
    %.fr = freeze i32 %2
    %idx.ext = trunc i32 %.fr to i20
    %add.ptr = getelementptr inbounds i16, ptr addrspace(6) %1, i20 %idx.ext
    %div17 = lshr i32 %.fr, 5
    call void @llvm.set.loop.iterations.i32(i32 %div17)
    br label %for.body

  for.cond.cleanup:                                 ; preds = %for.body
    %3 = addrspacecast ptr %ofm to ptr addrspace(5)
    %add.ptr9 = getelementptr inbounds i16, ptr addrspace(5) %3, i20 %idx.ext
    %div1318 = lshr i32 %.fr, 4
    %4 = zext i20 ptrtoint (ptr @_ZN11gelu_lut_32ILj0ELj512EE7data_abE to i20) to i32
    %splat.splatinsert.i.i.i.i.i.i.i = insertelement <16 x i32> poison, i32 %4, i64 0
    %splat.splat.i.i.i.i.i.i.i = shufflevector <16 x i32> %splat.splatinsert.i.i.i.i.i.i.i, <16 x i32> poison, <16 x i32> zeroinitializer
    %5 = zext i20 ptrtoint (ptr @_ZN11gelu_lut_32ILj0ELj512EE7data_cdE to i20) to i32
    %splat.splatinsert.i1.i.i.i.i.i.i = insertelement <16 x i32> poison, i32 %5, i64 0
    %splat.splat.i2.i.i.i.i.i.i = shufflevector <16 x i32> %splat.splatinsert.i1.i.i.i.i.i.i, <16 x i32> poison, <16 x i32> zeroinitializer
    %6 = icmp eq i32 %div1318, 1
    br i1 %6, label %for.cond.cleanup15.unr-lcssa, label %for.cond.cleanup.new

  for.cond.cleanup.new:                             ; preds = %for.cond.cleanup
    %unroll_iter = and i32 %div1318, 268435454
    br label %for.cond.cleanup15

  for.body:                                         ; preds = %for.body, %entry
    %pin1.073 = phi ptr addrspace(5) [ %0, %entry ], [ %add.ptr.ascast.i, %for.body ]
    %pout1.072 = phi ptr addrspace(6) [ %add.ptr, %entry ], [ %add.ptr.ascast.i23, %for.body ]
    %7 = load <32 x bfloat>, ptr addrspace(5) %pin1.073, align 64, !tbaa !11, !noalias !12
    %8 = addrspacecast ptr addrspace(5) %pin1.073 to ptr
    %add.ptr.i = getelementptr inbounds i8, ptr %8, i20 64
    %add.ptr.ascast.i = addrspacecast ptr %add.ptr.i to ptr addrspace(5)
    %9 = tail call noundef <32 x float> @llvm.aie2p.v32bf16.to.v32accfloat(<32 x bfloat> %7)
    %10 = bitcast <32 x float> %9 to <16 x i64>
    %11 = tail call noundef <32 x float> @llvm.aie2p.v32bf16.to.v32accfloat(<32 x bfloat> <bfloat 0xR40A0, bfloat 0xR40A0, bfloat 0xR40A0, bfloat 0xR40A0, bfloat 0xR40A0, bfloat 0xR40A0, bfloat 0xR40A0, bfloat 0xR40A0, bfloat 0xR40A0, bfloat 0xR40A0, bfloat 0xR40A0, bfloat 0xR40A0, bfloat 0xR40A0, bfloat 0xR40A0, bfloat 0xR40A0, bfloat 0xR40A0, bfloat 0xR40A0, bfloat 0xR40A0, bfloat 0xR40A0, bfloat 0xR40A0, bfloat 0xR40A0, bfloat 0xR40A0, bfloat 0xR40A0, bfloat 0xR40A0, bfloat 0xR40A0, bfloat 0xR40A0, bfloat 0xR40A0, bfloat 0xR40A0, bfloat 0xR40A0, bfloat 0xR40A0, bfloat 0xR40A0, bfloat 0xR40A0>)
    %12 = bitcast <32 x float> %11 to <16 x i64>
    %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i = shufflevector <16 x i64> %10, <16 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
    %shuffle.i.i.i.i.i.i5.i.i.i.i.i.i.i.i = shufflevector <16 x i64> %12, <16 x i64> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
    %13 = bitcast <32 x i64> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i to <64 x float>
    %14 = bitcast <32 x i64> %shuffle.i.i.i.i.i.i5.i.i.i.i.i.i.i.i to <64 x float>
    %15 = tail call noundef <64 x float> @llvm.aie2p.ACC2048.accfloat.add.conf(<64 x float> %13, <64 x float> %14, i32 60)
    %16 = bitcast <64 x float> %15 to <32 x i64>
    %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i = shufflevector <32 x i64> %16, <32 x i64> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
    %17 = bitcast <16 x i64> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i to <32 x float>
    %18 = tail call noundef <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float> %17)
    %19 = tail call noundef <32 x float> @llvm.aie2p.I512.I512.ACC1024.bf.mul.conf(<32 x bfloat> %18, <32 x bfloat> <bfloat 0xR4380, bfloat 0xR4380, bfloat 0xR4380, bfloat 0xR4380, bfloat 0xR4380, bfloat 0xR4380, bfloat 0xR4380, bfloat 0xR4380, bfloat 0xR4380, bfloat 0xR4380, bfloat 0xR4380, bfloat 0xR4380, bfloat 0xR4380, bfloat 0xR4380, bfloat 0xR4380, bfloat 0xR4380, bfloat 0xR4380, bfloat 0xR4380, bfloat 0xR4380, bfloat 0xR4380, bfloat 0xR4380, bfloat 0xR4380, bfloat 0xR4380, bfloat 0xR4380, bfloat 0xR4380, bfloat 0xR4380, bfloat 0xR4380, bfloat 0xR4380, bfloat 0xR4380, bfloat 0xR4380, bfloat 0xR4380, bfloat 0xR4380>, i32 828)
    %20 = tail call noundef <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float> %19)
    %21 = tail call noundef <32 x float> @llvm.aie2p.I512.I512.ACC1024.bf.mul.conf(<32 x bfloat> %20, <32 x bfloat> <bfloat 0xR3DCD, bfloat 0xR3DCD, bfloat 0xR3DCD, bfloat 0xR3DCD, bfloat 0xR3DCD, bfloat 0xR3DCD, bfloat 0xR3DCD, bfloat 0xR3DCD, bfloat 0xR3DCD, bfloat 0xR3DCD, bfloat 0xR3DCD, bfloat 0xR3DCD, bfloat 0xR3DCD, bfloat 0xR3DCD, bfloat 0xR3DCD, bfloat 0xR3DCD, bfloat 0xR3DCD, bfloat 0xR3DCD, bfloat 0xR3DCD, bfloat 0xR3DCD, bfloat 0xR3DCD, bfloat 0xR3DCD, bfloat 0xR3DCD, bfloat 0xR3DCD, bfloat 0xR3DCD, bfloat 0xR3DCD, bfloat 0xR3DCD, bfloat 0xR3DCD, bfloat 0xR3DCD, bfloat 0xR3DCD, bfloat 0xR3DCD, bfloat 0xR3DCD>, i32 828)
    %22 = tail call noundef <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float> %21)
    %23 = bitcast <32 x bfloat> %22 to <16 x i32>
    %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i21 = shufflevector <16 x i32> %23, <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
    %24 = bitcast <8 x i32> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i21 to <16 x bfloat>
    %25 = tail call noundef <16 x i32> @llvm.aie2p.v16bf16.to.v16i32(<16 x bfloat> %24, i32 0)
    %shuffle1.i.i.i.i.i.i.i2.i.i.i.i.i.i.i = shufflevector <16 x i32> %23, <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
    %26 = bitcast <8 x i32> %shuffle1.i.i.i.i.i.i.i2.i.i.i.i.i.i.i to <16 x bfloat>
    %27 = tail call noundef <16 x i32> @llvm.aie2p.v16bf16.to.v16i32(<16 x bfloat> %26, i32 0)
    %28 = tail call noundef <16 x i32> @llvm.aie2p.vshuffle(<16 x i32> %25, <16 x i32> %27, i32 2)
    %29 = bitcast <16 x i32> %28 to <32 x i16>
    %30 = tail call { <32 x i16>, i32 } @llvm.aie2p.vmin.ge16(<32 x i16> %29, <32 x i16> <i16 255, i16 255, i16 255, i16 255, i16 255, i16 255, i16 255, i16 255, i16 255, i16 255, i16 255, i16 255, i16 255, i16 255, i16 255, i16 255, i16 255, i16 255, i16 255, i16 255, i16 255, i16 255, i16 255, i16 255, i16 255, i16 255, i16 255, i16 255, i16 255, i16 255, i16 255, i16 255>, i32 1)
    %31 = extractvalue { <32 x i16>, i32 } %30, 0
    %32 = tail call { <32 x i16>, i32 } @llvm.aie2p.vmax.lt16(<32 x i16> %31, <32 x i16> zeroinitializer, i32 1)
    %33 = extractvalue { <32 x i16>, i32 } %32, 0
    store <32 x i16> %33, ptr addrspace(6) %pout1.072, align 64, !tbaa !11
    %34 = addrspacecast ptr addrspace(6) %pout1.072 to ptr
    %add.ptr.i22 = getelementptr inbounds i8, ptr %34, i20 64
    %add.ptr.ascast.i23 = addrspacecast ptr %add.ptr.i22 to ptr addrspace(6)
    %35 = call i1 @llvm.loop.decrement.i32(i32 1)
    br i1 %35, label %for.body, label %for.cond.cleanup, !llvm.loop !19

  for.cond.cleanup15.unr-lcssa:                     ; preds = %for.cond.cleanup
    br label %for.cond.cleanup15

  for.cond.cleanup15:                               ; preds = %for.cond.cleanup15.unr-lcssa, %for.cond.cleanup.new
    ret void
  }

  ; Function Attrs: nounwind memory(none)
  declare <32 x float> @llvm.aie2p.v32bf16.to.v32accfloat(<32 x bfloat>) #1

  ; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read)
  declare <64 x float> @llvm.aie2p.ACC2048.accfloat.add.conf(<64 x float>, <64 x float>, i32) #2

  ; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read)
  declare <32 x float> @llvm.aie2p.I512.I512.ACC1024.bf.mul.conf(<32 x bfloat>, <32 x bfloat>, i32) #2

  ; Function Attrs: nounwind memory(inaccessiblemem: read)
  declare <32 x bfloat> @llvm.aie2p.v32accfloat.to.v32bf16(<32 x float>) #3

  ; Function Attrs: nounwind memory(inaccessiblemem: read)
  declare <16 x i32> @llvm.aie2p.v16bf16.to.v16i32(<16 x bfloat>, i32) #3

  ; Function Attrs: nounwind memory(none)
  declare <16 x i32> @llvm.aie2p.vshuffle(<16 x i32>, <16 x i32>, i32) #1

  ; Function Attrs: nocallback noduplicate nofree nosync nounwind willreturn
  declare void @llvm.set.loop.iterations.i32(i32) #6

  ; Function Attrs: nocallback noduplicate nofree nosync nounwind willreturn
  declare i1 @llvm.loop.decrement.i32(i32) #6

  !llvm.linker.options = !{}
  !llvm.module.flags = !{!0, !1, !2}
  !llvm.ident = !{!3}

  !0 = !{i32 7, !"Dwarf Version", i32 4}
  !1 = !{i32 2, !"Debug Info Version", i32 3}
  !2 = !{i32 1, !"wchar_size", i32 4}
  !3 = !{!"clang version 19.0.0git"}
  !4 = !{!5, !6, i64 0}
  !5 = !{!"_ZTS26elementwise_unary_params_tI15gelu1d_params_tI8bfloat16EE", !6, i64 0, !7, i64 4, !7, i64 5, !7, i64 6, !7, i64 7, !9, i64 8, !9, i64 10, !6, i64 12, !6, i64 16, !6, i64 20, !6, i64 24, !6, i64 28, !10, i64 32}
  !6 = !{!"int", !7, i64 0}
  !7 = !{!"omnipotent char", !8, i64 0}
  !8 = !{!"Simple C++ TBAA"}
  !9 = !{!"short", !7, i64 0}
  !10 = !{!"_ZTS15gelu1d_params_tI8bfloat16E"}
  !11 = !{!7, !7, i64 0}
  !12 = !{!13, !15, !17}
  !13 = distinct !{!13, !14, !"_ZN3aie6detail18load_vector_helperIU3AS58bfloat16Lj32EL15aie_dm_resource0EE3runEPU3AS5KS2_: %agg.result"}
  !14 = distinct !{!14, !"_ZN3aie6detail18load_vector_helperIU3AS58bfloat16Lj32EL15aie_dm_resource0EE3runEPU3AS5KS2_"}
  !15 = distinct !{!15, !16, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS58bfloat16EEDaPKT1_: %agg.result"}
  !16 = distinct !{!16, !"_ZN3aie6detail11load_vectorILj32EL15aie_dm_resource0EU3AS58bfloat16EEDaPKT1_"}
  !17 = distinct !{!17, !18, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS58bfloat16EENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS6_: %agg.result"}
  !18 = distinct !{!18, !"_ZN3aie6load_vILj32EL15aie_dm_resource0ETkNS_21DecoratedElemBaseTypeEU3AS58bfloat16EENS_6vectorIN22aie_dm_resource_removeIT1_E4typeEXT_EEEPKS6_"}
  !19 = distinct !{!19, !20, !21, !22}
  !20 = !{!"llvm.loop.mustprogress"}
  !21 = !{!"llvm.loop.itercount.range", i64 8}
  !22 = !{!"llvm.loop.pipeline.initiationinterval", i32 6}
