; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie2p --aie-reg-rewrite-mode=latencyaware %s -o - | FileCheck %s

; Test postSWP capabilities related to gemm_bfp16.

; Function Attrs: nounwind memory(none)
declare <16 x i32> @llvm.aie2p.vshuffle(<16 x i32>, <16 x i32>, i32) #0

; Function Attrs: nounwind memory(none)
declare <32 x float> @llvm.aie2p.v32bf16.to.v32accfloat(<32 x bfloat>) #0

; Function Attrs: nounwind memory(none)
declare { ptr, i20 } @llvm.aie2p.add.2d(ptr, i20, i20, i20, i20) #0

; Function Attrs: nounwind memory(none)
declare { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr, i20, i20, i20, i20, i20, i20, i20) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read)
declare <64 x float> @llvm.aie2p.I1024.I1024.ACC2048.bf.mul.conf(<64 x bfloat>, <64 x bfloat>, i32) #1

; Function Attrs: nounwind memory(inaccessiblemem: read)
declare { <64 x i8>, <8 x i8> } @llvm.aie2p.v64accfloat.to.v64bfp16ebs8(<64 x float>) #2

; Function Attrs: nounwind memory(inaccessiblemem: read)
declare <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mac.conf(<64 x i8>, <8 x i8>, <64 x i8>, <8 x i8>, <64 x i32>, i32) #2

; Function Attrs: mustprogress
define dso_local void @gemm_bfp16(ptr %ofm_ptr, ptr %ifm_ptr, ptr %wts_ptr, ptr %param, i20 %0, i20 %1, i20 %2, i20 %3, i20 %4, i20 %5, i20 %6, i20 %7, i20 %idx.ext.i.i.i.i.i.i.i.i.i90.i) {
; CHECK-LABEL: gemm_bfp16:
; CHECK:       // %bb.0: // %newFuncRoot
; CHECK-NEXT:    mov r7, p5
; CHECK-NEXT:    paddxm [sp], #64
; CHECK-NEXT:    mova dc5, #0; st p6, [sp, #-64]; movxm r0, #16256 // 4-byte Folded Spill
; CHECK-NEXT:    mova m0, #-68; mov p6, sp
; CHECK-NEXT:    padda [p6], m0; mov r6, p4
; CHECK-NEXT:    lda dn2, [p6], #-4; movs m2, p4; movxm ls, #.LBB0_2
; CHECK-NEXT:    lda m0, [p6], #-4; movs dj2, p5; movxm le, #.L_LEnd0
; CHECK-NEXT:    mova dj6, #68; movs p5, p0; vbcst.16 x0, r0
; CHECK-NEXT:    lda dj0, [p6], #-4; movs dc1, dc5; movx r1, #53; mov dc2, dc5
; CHECK-NEXT:    lda dj4, [p6], #-4; movs dc3, dc5; movx r2, #60; mov dc4, dc5
; CHECK-NEXT:    lda dn0, [p6], #-4; movs dc0, dc5; movx r3, #780; mov dj3, r7
; CHECK-NEXT:    lda m4, [p6, #-4]; st p7, [sp, #-60]; movx r4, #0; vmov x1, x0 // 4-byte Folded Spill
; CHECK-NEXT:    lda dn4, [p6, #0]; movs p6, p1; movx r0, #52; mov dn3, dn2
; CHECK-NEXT:  .LBB0_1: // %for.body.i
; CHECK-NEXT:    // =>This Loop Header: Depth=1
; CHECK-NEXT:    // Child Loop BB0_2 Depth 2
; CHECK-NEXT:    mova m1, #80; mov p7, p3
; CHECK-NEXT:    padda [p7], m1
; CHECK-NEXT:    lda m3, [p7], #4
; CHECK-NEXT:    lda m5, [p7], #4
; CHECK-NEXT:    lda m6, [p7], #4
; CHECK-NEXT:    lda m7, [p7], #-20; mov m1, #104
; CHECK-NEXT:    lda r5, [p7], m1
; CHECK-NEXT:    lda m1, [p7], #-16
; CHECK-NEXT:    lda dn1, [p7], #4; mov p1, p5
; CHECK-NEXT:    lda dj1, [p7], #4; paddb [p1], m3
; CHECK-NEXT:    vlda bmll1, [p1, #0]
; CHECK-NEXT:    vlda bmlh1, [p1, #64]
; CHECK-NEXT:    vlda bmhl1, [p1, #128]
; CHECK-NEXT:    vlda bmhh1, [p1, #192]; mov p4, p5
; CHECK-NEXT:    lda dn5, [p7], #4; paddb [p4], m5
; CHECK-NEXT:    vlda bmll0, [p4, #0]
; CHECK-NEXT:    vlda bmlh0, [p4, #64]
; CHECK-NEXT:    lda dj5, [p7, #0]
; CHECK-NEXT:    lda m5, [p7, #8]
; CHECK-NEXT:    vlda bmhl0, [p4, #128]; movs p7, p2
; CHECK-NEXT:    vlda bmhh0, [p4, #192]; vldb.3d x9, [p2], d0; mov p1, p5
; CHECK-NEXT:    padda [p7], m4; vldb x8, [p7, #64]; padds [p1], m6
; CHECK-NEXT:    vlda bmll4, [p1, #0]; vldb x7, [p7, #0]
; CHECK-NEXT:    vlda bmlh4, [p1, #64]; vldb x5, [p7, #64]
; CHECK-NEXT:    vlda bmhl4, [p1, #128]; mov p4, p5
; CHECK-NEXT:    vlda bmhh4, [p1, #192]; paddb [p4], m7
; CHECK-NEXT:    vlda bmll3, [p4, #0]
; CHECK-NEXT:    vlda.conv.fp32.bf16 cmh2, [p6, #64]; movs p7, p2; mov p1, p6
; CHECK-NEXT:    vlda.3d.conv.fp32.bf16 cml2, [p6], d1; vldb.3d x9, [p2], d0; vshuffle x10, x9, x8, r0
; CHECK-NEXT:    padda [p7], m4; vldb x8, [p7, #64]; vshuffle x11, x9, x8, r1
; CHECK-NEXT:    vlda bmlh3, [p4, #64]; vldb x7, [p7, #0]; vshuffle x10, x7, x5, r0
; CHECK-NEXT:    vlda bmhl3, [p4, #128]; vldb x5, [p7, #64]; vshuffle x11, x7, x5, r1; vmul.f dm2, y5, y0, r2
; CHECK-NEXT:    vlda bmhh3, [p4, #192]; paddb [p1], m5
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml2, [p1, #0]; vmul.f dm2, y5, y0, r2
; CHECK-NEXT:    vlda.conv.fp32.bf16 cmh2, [p1, #64]; add.nc lc, r5, #-3
; CHECK-NEXT:    vlda.conv.fp32.bf16 cmh2, [p6, #64]; movs p7, p2; mov p1, p6
; CHECK-NEXT:    vlda.3d.conv.fp32.bf16 cml2, [p6], d1; vldb.3d x9, [p2], d0; vconv.bfp16ebs8.fp32 ex3, dm2; vshuffle x10, x9, x8, r0
; CHECK-NEXT:    padda [p7], m4; vldb x8, [p7, #64]; vshuffle x11, x9, x8, r1
; CHECK-NEXT:    padda.2d [p5], d2; vldb x7, [p7, #0]; vconv.bfp16ebs8.fp32 ex6, dm2; vshuffle x10, x7, x5, r0
; CHECK-NEXT:  .LBB0_2: // %for.body46.i
; CHECK-NEXT:    // Parent Loop BB0_1 Depth=1
; CHECK-NEXT:    // => This Inner Loop Header: Depth=2
; CHECK-NEXT:    nopa ; vldb x5, [p7, #64]; vconv.bfp16ebs8.fp32 ex4, dm2; nopx ; vshuffle x11, x7, x5, r1; vmul.f dm2, y5, y0, r2
; CHECK-NEXT:    nopa ; paddb [p1], m5; nopx
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml2, [p1, #0]; vconv.bfp16ebs8.fp32 ex2, dm2; vmul.f dm2, y5, y0, r2
; CHECK-NEXT:    vlda.conv.fp32.bf16 cmh2, [p1, #64]
; CHECK-NEXT:    vlda.conv.fp32.bf16 cmh2, [p6, #64]; movs p7, p2; mov p1, p6; vmac.f dm1, dm1, ex3, ex6, r3
; CHECK-NEXT:    vlda.3d.conv.fp32.bf16 cml2, [p6], d1; vldb.3d x9, [p2], d0; vconv.bfp16ebs8.fp32 ex3, dm2; nopx ; vshuffle x10, x9, x8, r0; vmac.f dm0, dm0, ex3, ex4, r3
; CHECK-NEXT:    padda [p7], m4; vldb x8, [p7, #64]; vshuffle x11, x9, x8, r1; vmac.f dm4, dm4, ex2, ex6, r3
; CHECK-NEXT:  .L_LEnd0:
; CHECK-NEXT:    nopa ; vldb x7, [p7, #0]; vconv.bfp16ebs8.fp32 ex6, dm2; nopx ; vshuffle x10, x7, x5, r0; vmac.f dm3, dm3, ex2, ex4, r3
; CHECK-NEXT:  // %bb.3: // %for.cond.cleanup45.i
; CHECK-NEXT:    // in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    nopa ; vldb x5, [p7, #64]; vconv.bfp16ebs8.fp32 ex4, dm2; add r4, r4, #1; vshuffle x11, x7, x5, r1; vmul.f dm2, y5, y0, r2
; CHECK-NEXT:    nopa ; paddb [p1], m5; nopx ; mov p4, p0
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml2, [p1, #0]; vconv.bfp16ebs8.fp32 ex2, dm2; vmul.f dm2, y5, y0, r2
; CHECK-NEXT:    vlda.conv.fp32.bf16 cmh2, [p1, #64]
; CHECK-NEXT:    vlda.conv.fp32.bf16 cmh2, [p6, #64]; mov p1, p6; vmac.f dm1, dm1, ex3, ex6, r3
; CHECK-NEXT:    vlda.3d.conv.fp32.bf16 cml2, [p6], d1; vconv.bfp16ebs8.fp32 ex3, dm2; vshuffle x10, x9, x8, r0; vmac.f dm0, dm0, ex3, ex4, r3
; CHECK-NEXT:    mova m1, #84; vshuffle x11, x9, x8, r1; vmac.f dm4, dm4, ex2, ex6, r3
; CHECK-NEXT:    vconv.bfp16ebs8.fp32 ex6, dm2; vshuffle x10, x7, x5, r0; vmac.f dm3, dm3, ex2, ex4, r3
; CHECK-NEXT:    vconv.bfp16ebs8.fp32 ex4, dm2; vshuffle x11, x7, x5, r1; vmul.f dm2, y5, y0, r2
; CHECK-NEXT:    paddb [p1], m5
; CHECK-NEXT:    vlda.conv.fp32.bf16 cml2, [p1, #0]; vconv.bfp16ebs8.fp32 ex2, dm2; vmul.f dm2, y5, y0, r2
; CHECK-NEXT:    vlda.conv.fp32.bf16 cmh2, [p1, #64]
; CHECK-NEXT:    mov p1, p0; vmac.f dm1, dm1, ex3, ex6, r3
; CHECK-NEXT:    padda [p1], m3; vconv.bfp16ebs8.fp32 ex3, dm2; mov m3, r6; vmac.f dm0, dm0, ex3, ex4, r3
; CHECK-NEXT:    vmac.f dm4, dm4, ex2, ex6, r3
; CHECK-NEXT:    vconv.bfp16ebs8.fp32 ex6, dm2; vmac.f dm3, dm3, ex2, ex4, r3
; CHECK-NEXT:    vconv.bfp16ebs8.fp32 ex4, dm2
; CHECK-NEXT:    nop
; CHECK-NEXT:    vconv.bfp16ebs8.fp32 ex2, dm2
; CHECK-NEXT:    nop
; CHECK-NEXT:    vmac.f dm1, dm1, ex3, ex6, r3
; CHECK-NEXT:    vmac.f dm0, dm0, ex3, ex4, r3
; CHECK-NEXT:    vmac.f dm4, dm4, ex2, ex6, r3
; CHECK-NEXT:    vmac.f dm3, dm3, ex2, ex4, r3
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst bmll1, [p1, #0]
; CHECK-NEXT:    vst bmlh1, [p1, #64]
; CHECK-NEXT:    vst bmhl1, [p1, #128]
; CHECK-NEXT:    vst bmhh1, [p1, #192]; mov p1, p3
; CHECK-NEXT:    padda [p1], m1
; CHECK-NEXT:    lda m1, [p1], #4
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    padda [p4], m1
; CHECK-NEXT:    vst bmll0, [p4, #0]
; CHECK-NEXT:    vst bmlh0, [p4, #64]
; CHECK-NEXT:    vst bmhl0, [p4, #128]
; CHECK-NEXT:    vst bmhh0, [p4, #192]; mov p4, p0
; CHECK-NEXT:    lda m1, [p1, #0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    padda [p4], m1
; CHECK-NEXT:    vst bmll4, [p4, #0]
; CHECK-NEXT:    vst bmlh4, [p4, #64]
; CHECK-NEXT:    vst bmhl4, [p4, #128]
; CHECK-NEXT:    vst bmhh4, [p4, #192]
; CHECK-NEXT:    lda m1, [p1, #4]; paddb.2d [p0], d3; mov p1, p0
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    padda [p1], m1
; CHECK-NEXT:    vst bmll3, [p1, #0]
; CHECK-NEXT:    vst bmlh3, [p1, #64]
; CHECK-NEXT:    vst bmhl3, [p1, #128]
; CHECK-NEXT:    vst bmhh3, [p1, #192]
; CHECK-NEXT:    lda r5, [p3, dj6]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    lt r5, r4, r5
; CHECK-NEXT:    jnz r5, #.LBB0_1
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
; CHECK-NEXT:  // %bb.4: // %exit.exitStub
; CHECK-NEXT:    lda p7, [sp, #-60] // 4-byte Folded Reload
; CHECK-NEXT:    lda p6, [sp, #-64] // 4-byte Folded Reload
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    paddxm [sp], #-64 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
newFuncRoot:
  br label %for.body.i

for.body.i:                                       ; preds = %newFuncRoot, %for.cond.cleanup45.i
  %ot.0168.i = phi i32 [ 0, %newFuncRoot ], [ %inc86.i, %for.cond.cleanup45.i ]
  %output_ptr.0167.i = phi ptr [ %ofm_ptr, %newFuncRoot ], [ %90, %for.cond.cleanup45.i ]
  %psum_ptr.0166.i = phi ptr [ %ofm_ptr, %newFuncRoot ], [ %82, %for.cond.cleanup45.i ]
  %tsA.sroa.10.0165.i = phi i32 [ 0, %newFuncRoot ], [ %37, %for.cond.cleanup45.i ]
  %tsA.sroa.7118.0164.i = phi i32 [ 0, %newFuncRoot ], [ %35, %for.cond.cleanup45.i ]
  %tsA.sroa.0.0163.i = phi ptr [ %ifm_ptr, %newFuncRoot ], [ %38, %for.cond.cleanup45.i ]
  %tsB.sroa.10.0162.i = phi i32 [ 0, %newFuncRoot ], [ %45, %for.cond.cleanup45.i ]
  %tsB.sroa.7116.0161.i = phi i32 [ 0, %newFuncRoot ], [ %43, %for.cond.cleanup45.i ]
  %tsB.sroa.0.0160.i = phi ptr [ %wts_ptr, %newFuncRoot ], [ %46, %for.cond.cleanup45.i ]
  %iterator_psum_cnt0.0159.i = phi i32 [ 0, %newFuncRoot ], [ %81, %for.cond.cleanup45.i ]
  %iterator_outer_cnt0.0158.i = phi i32 [ 0, %newFuncRoot ], [ %89, %for.cond.cleanup45.i ]
  %sunkaddr = getelementptr inbounds i8, ptr %param, i20 80
  %8 = load i32, ptr %sunkaddr, align 16, !tbaa !4, !noalias !19
  %idx.ext.i = trunc i32 %8 to i20
  %add.ptr.i = getelementptr inbounds i8, ptr %psum_ptr.0166.i, i20 %idx.ext.i
  %9 = load <64 x i32>, ptr %add.ptr.i, align 64, !tbaa !23, !noalias !19
  %sunkaddr69 = getelementptr inbounds i8, ptr %param, i20 84
  %10 = load i32, ptr %sunkaddr69, align 4, !tbaa !24, !noalias !19
  %idx.ext22.i = trunc i32 %10 to i20
  %add.ptr23.i = getelementptr inbounds i8, ptr %psum_ptr.0166.i, i20 %idx.ext22.i
  %11 = load <64 x i32>, ptr %add.ptr23.i, align 64, !tbaa !23, !noalias !19
  %sunkaddr70 = getelementptr inbounds i8, ptr %param, i20 88
  %12 = load i32, ptr %sunkaddr70, align 8, !tbaa !25, !noalias !19
  %idx.ext29.i = trunc i32 %12 to i20
  %add.ptr30.i = getelementptr inbounds i8, ptr %psum_ptr.0166.i, i20 %idx.ext29.i
  %13 = load <64 x i32>, ptr %add.ptr30.i, align 64, !tbaa !23, !noalias !19
  %sunkaddr71 = getelementptr inbounds i8, ptr %param, i20 92
  %14 = load i32, ptr %sunkaddr71, align 4, !tbaa !26, !noalias !19
  %idx.ext36.i = trunc i32 %14 to i20
  %add.ptr37.i = getelementptr inbounds i8, ptr %psum_ptr.0166.i, i20 %idx.ext36.i
  %15 = load <64 x i32>, ptr %add.ptr37.i, align 64, !tbaa !23, !noalias !19
  %16 = trunc nuw i32 %iterator_psum_cnt0.0159.i to i20
  %17 = tail call { ptr, i20 } @llvm.aie2p.add.2d(ptr %psum_ptr.0166.i, i20 %0, i20 %1, i20 %2, i20 %16)
  %18 = extractvalue { ptr, i20 } %17, 1
  %sunkaddr72 = getelementptr inbounds i8, ptr %param, i20 72
  %19 = load i32, ptr %sunkaddr72, align 8, !tbaa !27, !noalias !19
  %sunkaddr73 = getelementptr inbounds i8, ptr %param, i20 176
  %20 = load i32, ptr %sunkaddr73, align 16, !tbaa !28, !noalias !19
  %sunkaddr74 = getelementptr inbounds i8, ptr %param, i20 160
  %21 = load i32, ptr %sunkaddr74, align 32, !tbaa !29, !noalias !19
  %sunkaddr75 = getelementptr inbounds i8, ptr %param, i20 164
  %22 = load i32, ptr %sunkaddr75, align 4, !tbaa !30, !noalias !19
  %sunkaddr76 = getelementptr inbounds i8, ptr %param, i20 168
  %23 = load i32, ptr %sunkaddr76, align 8, !tbaa !31, !noalias !19
  %sunkaddr77 = getelementptr inbounds i8, ptr %param, i20 172
  %24 = load i32, ptr %sunkaddr77, align 4, !tbaa !32, !noalias !19
  %25 = trunc i32 %20 to i20
  %26 = trunc i32 %22 to i20
  %27 = trunc i32 %24 to i20
  %28 = trunc i32 %21 to i20
  %29 = trunc i32 %23 to i20
  %sunkaddr78 = getelementptr inbounds i8, ptr %param, i20 180
  %30 = load i32, ptr %sunkaddr78, align 4, !tbaa !33, !noalias !34
  %idx.ext.i.i.i.i.i.i.i.i.i.i = trunc i32 %30 to i20
  br label %for.body46.i

for.body46.i:                                     ; preds = %for.body46.i, %for.body.i
  %lsr.iv = phi i32 [ %lsr.iv.next, %for.body46.i ], [ %19, %for.body.i ]
  %tsA.sroa.10.1155.i = phi i32 [ %tsA.sroa.10.0165.i, %for.body.i ], [ %37, %for.body46.i ]
  %tsA.sroa.7118.1154.i = phi i32 [ %tsA.sroa.7118.0164.i, %for.body.i ], [ %35, %for.body46.i ]
  %tsA.sroa.0.1153.i = phi ptr [ %tsA.sroa.0.0163.i, %for.body.i ], [ %38, %for.body46.i ]
  %tsB.sroa.10.1152.i = phi i32 [ %tsB.sroa.10.0162.i, %for.body.i ], [ %45, %for.body46.i ]
  %tsB.sroa.7116.1151.i = phi i32 [ %tsB.sroa.7116.0161.i, %for.body.i ], [ %43, %for.body46.i ]
  %tsB.sroa.0.1150.i = phi ptr [ %tsB.sroa.0.0160.i, %for.body.i ], [ %46, %for.body46.i ]
  %C.sroa.26143.1149.i = phi <64 x i32> [ %15, %for.body.i ], [ %80, %for.body46.i ]
  %C.sroa.18140.1148.i = phi <64 x i32> [ %13, %for.body.i ], [ %79, %for.body46.i ]
  %C.sroa.10137.1147.i = phi <64 x i32> [ %11, %for.body.i ], [ %70, %for.body46.i ]
  %C.sroa.0.1146.i = phi <64 x i32> [ %9, %for.body.i ], [ %62, %for.body46.i ]
  %31 = trunc nuw i32 %tsA.sroa.7118.1154.i to i20
  %32 = trunc nuw i32 %tsA.sroa.10.1155.i to i20
  %33 = tail call { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr %tsA.sroa.0.1153.i, i20 %25, i20 %26, i20 %27, i20 %28, i20 %31, i20 %29, i20 %32)
  %34 = extractvalue { ptr, i20, i20 } %33, 1
  %35 = zext i20 %34 to i32
  %36 = extractvalue { ptr, i20, i20 } %33, 2
  %37 = zext i20 %36 to i32
  %38 = extractvalue { ptr, i20, i20 } %33, 0
  %39 = trunc nuw i32 %tsB.sroa.7116.1151.i to i20
  %40 = trunc nuw i32 %tsB.sroa.10.1152.i to i20
  %41 = tail call { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr %tsB.sroa.0.1150.i, i20 %3, i20 %4, i20 %5, i20 %6, i20 %39, i20 %7, i20 %40)
  %42 = extractvalue { ptr, i20, i20 } %41, 1
  %43 = zext i20 %42 to i32
  %44 = extractvalue { ptr, i20, i20 } %41, 2
  %45 = zext i20 %44 to i32
  %46 = extractvalue { ptr, i20, i20 } %41, 0
  %ref.tmp.sroa.0.i.i.i.i.i.i.sroa.0.0.copyload.i = load <32 x bfloat>, ptr %tsA.sroa.0.1153.i, align 64, !alias.scope !37, !noalias !38
  %ref.tmp.sroa.0.i.i.i.i.i.i.sroa.4.0.tsA_inner.sroa.0.0.119.sroa_idx.i = getelementptr inbounds nuw i8, ptr %tsA.sroa.0.1153.i, i20 64
  %ref.tmp.sroa.0.i.i.i.i.i.i.sroa.4.0.copyload.i = load <32 x bfloat>, ptr %ref.tmp.sroa.0.i.i.i.i.i.i.sroa.4.0.tsA_inner.sroa.0.0.119.sroa_idx.i, align 64, !alias.scope !37, !noalias !38
  %add.ptr.i1.i.i.i.i.i.i.i.i.i = getelementptr inbounds i8, ptr %tsA.sroa.0.1153.i, i20 %idx.ext.i.i.i.i.i.i.i.i.i.i
  %ref.tmp.sroa.0.i.i.i.i.i.i.i.sroa.0.0.copyload.i = load <32 x bfloat>, ptr %add.ptr.i1.i.i.i.i.i.i.i.i.i, align 64, !alias.scope !37, !noalias !38
  %ref.tmp.sroa.0.i.i.i.i.i.i.i.sroa.4.0.tsA_inner.sroa.0.0..sroa_idx.i = getelementptr inbounds nuw i8, ptr %add.ptr.i1.i.i.i.i.i.i.i.i.i, i20 64
  %ref.tmp.sroa.0.i.i.i.i.i.i.i.sroa.4.0.copyload.i = load <32 x bfloat>, ptr %ref.tmp.sroa.0.i.i.i.i.i.i.i.sroa.4.0.tsA_inner.sroa.0.0..sroa_idx.i, align 64, !alias.scope !37, !noalias !38
  %ref.tmp.sroa.0.i.i.i.i.i.i87.sroa.0.0.copyload.i = load <16 x i32>, ptr %tsB.sroa.0.1150.i, align 64, !alias.scope !38, !noalias !37
  %ref.tmp.sroa.0.i.i.i.i.i.i87.sroa.4.0.tsB_inner.sroa.0.0.123.sroa_idx.i = getelementptr inbounds nuw i8, ptr %tsB.sroa.0.1150.i, i20 64
  %ref.tmp.sroa.0.i.i.i.i.i.i87.sroa.4.0.copyload.i = load <16 x i32>, ptr %ref.tmp.sroa.0.i.i.i.i.i.i87.sroa.4.0.tsB_inner.sroa.0.0.123.sroa_idx.i, align 64, !alias.scope !38, !noalias !37
  %add.ptr.i1.i.i.i.i.i.i.i.i91.i = getelementptr inbounds i8, ptr %tsB.sroa.0.1150.i, i20 %idx.ext.i.i.i.i.i.i.i.i.i90.i
  %ref.tmp.sroa.0.i.i.i.i.i.i.i86.sroa.0.0.copyload.i = load <16 x i32>, ptr %add.ptr.i1.i.i.i.i.i.i.i.i91.i, align 64, !alias.scope !38, !noalias !37
  %ref.tmp.sroa.0.i.i.i.i.i.i.i86.sroa.4.0.tsB_inner.sroa.0.0..sroa_idx.i = getelementptr inbounds nuw i8, ptr %add.ptr.i1.i.i.i.i.i.i.i.i91.i, i20 64
  %ref.tmp.sroa.0.i.i.i.i.i.i.i86.sroa.4.0.copyload.i = load <16 x i32>, ptr %ref.tmp.sroa.0.i.i.i.i.i.i.i86.sroa.4.0.tsB_inner.sroa.0.0..sroa_idx.i, align 64, !alias.scope !38, !noalias !37
  %47 = tail call noundef <32 x float> @llvm.aie2p.v32bf16.to.v32accfloat(<32 x bfloat> %ref.tmp.sroa.0.i.i.i.i.i.i.sroa.0.0.copyload.i)
  %48 = bitcast <32 x float> %47 to <16 x i64>
  %49 = tail call noundef <32 x float> @llvm.aie2p.v32bf16.to.v32accfloat(<32 x bfloat> %ref.tmp.sroa.0.i.i.i.i.i.i.sroa.4.0.copyload.i)
  %50 = bitcast <32 x float> %49 to <16 x i64>
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i = shufflevector <16 x i64> %48, <16 x i64> %50, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %51 = tail call <16 x i32> @llvm.aie2p.vshuffle(<16 x i32> %ref.tmp.sroa.0.i.i.i.i.i.i87.sroa.0.0.copyload.i, <16 x i32> %ref.tmp.sroa.0.i.i.i.i.i.i87.sroa.4.0.copyload.i, i32 52)
  %52 = tail call <16 x i32> @llvm.aie2p.vshuffle(<16 x i32> %ref.tmp.sroa.0.i.i.i.i.i.i87.sroa.0.0.copyload.i, <16 x i32> %ref.tmp.sroa.0.i.i.i.i.i.i87.sroa.4.0.copyload.i, i32 53)
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i = shufflevector <16 x i32> %51, <16 x i32> %52, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %53 = bitcast <32 x i32> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i to <64 x bfloat>
  %54 = tail call noundef <64 x float> @llvm.aie2p.I1024.I1024.ACC2048.bf.mul.conf(<64 x bfloat> %53, <64 x bfloat> splat (bfloat 0xR3F80), i32 60)
  %55 = bitcast <32 x i64> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i to <64 x float>
  %56 = tail call { <64 x i8>, <8 x i8> } @llvm.aie2p.v64accfloat.to.v64bfp16ebs8(<64 x float> %55)
  %57 = extractvalue { <64 x i8>, <8 x i8> } %56, 0
  %58 = extractvalue { <64 x i8>, <8 x i8> } %56, 1
  %59 = tail call { <64 x i8>, <8 x i8> } @llvm.aie2p.v64accfloat.to.v64bfp16ebs8(<64 x float> %54)
  %60 = extractvalue { <64 x i8>, <8 x i8> } %59, 0
  %61 = extractvalue { <64 x i8>, <8 x i8> } %59, 1
  %62 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mac.conf(<64 x i8> %57, <8 x i8> %58, <64 x i8> %60, <8 x i8> %61, <64 x i32> %C.sroa.0.1146.i, i32 780)
  %63 = tail call <16 x i32> @llvm.aie2p.vshuffle(<16 x i32> %ref.tmp.sroa.0.i.i.i.i.i.i.i86.sroa.0.0.copyload.i, <16 x i32> %ref.tmp.sroa.0.i.i.i.i.i.i.i86.sroa.4.0.copyload.i, i32 52)
  %64 = tail call <16 x i32> @llvm.aie2p.vshuffle(<16 x i32> %ref.tmp.sroa.0.i.i.i.i.i.i.i86.sroa.0.0.copyload.i, <16 x i32> %ref.tmp.sroa.0.i.i.i.i.i.i.i86.sroa.4.0.copyload.i, i32 53)
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i = shufflevector <16 x i32> %63, <16 x i32> %64, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %65 = bitcast <32 x i32> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i to <64 x bfloat>
  %66 = tail call noundef <64 x float> @llvm.aie2p.I1024.I1024.ACC2048.bf.mul.conf(<64 x bfloat> %65, <64 x bfloat> splat (bfloat 0xR3F80), i32 60)
  %67 = tail call { <64 x i8>, <8 x i8> } @llvm.aie2p.v64accfloat.to.v64bfp16ebs8(<64 x float> %66)
  %68 = extractvalue { <64 x i8>, <8 x i8> } %67, 0
  %69 = extractvalue { <64 x i8>, <8 x i8> } %67, 1
  %70 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mac.conf(<64 x i8> %57, <8 x i8> %58, <64 x i8> %68, <8 x i8> %69, <64 x i32> %C.sroa.10137.1147.i, i32 780)
  %71 = tail call noundef <32 x float> @llvm.aie2p.v32bf16.to.v32accfloat(<32 x bfloat> %ref.tmp.sroa.0.i.i.i.i.i.i.i.sroa.0.0.copyload.i)
  %72 = bitcast <32 x float> %71 to <16 x i64>
  %73 = tail call noundef <32 x float> @llvm.aie2p.v32bf16.to.v32accfloat(<32 x bfloat> %ref.tmp.sroa.0.i.i.i.i.i.i.i.sroa.4.0.copyload.i)
  %74 = bitcast <32 x float> %73 to <16 x i64>
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i = shufflevector <16 x i64> %72, <16 x i64> %74, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %75 = bitcast <32 x i64> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i to <64 x float>
  %76 = tail call { <64 x i8>, <8 x i8> } @llvm.aie2p.v64accfloat.to.v64bfp16ebs8(<64 x float> %75)
  %77 = extractvalue { <64 x i8>, <8 x i8> } %76, 0
  %78 = extractvalue { <64 x i8>, <8 x i8> } %76, 1
  %79 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mac.conf(<64 x i8> %77, <8 x i8> %78, <64 x i8> %60, <8 x i8> %61, <64 x i32> %C.sroa.18140.1148.i, i32 780)
  %80 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mac.conf(<64 x i8> %77, <8 x i8> %78, <64 x i8> %68, <8 x i8> %69, <64 x i32> %C.sroa.26143.1149.i, i32 780)
  %lsr.iv.next = add nsw i32 %lsr.iv, -1
  %exitcond.not.i = icmp eq i32 %lsr.iv.next, 0
  br i1 %exitcond.not.i, label %for.cond.cleanup45.i, label %for.body46.i, !llvm.loop !39

for.cond.cleanup45.i:                             ; preds = %for.body46.i
  %81 = zext i20 %18 to i32
  %82 = extractvalue { ptr, i20 } %17, 0
  %add.ptr58.i = getelementptr inbounds i8, ptr %output_ptr.0167.i, i20 %idx.ext.i
  store <64 x i32> %62, ptr %add.ptr58.i, align 64, !tbaa !23, !noalias !19
  %sunkaddr79 = getelementptr inbounds i8, ptr %param, i20 84
  %83 = load i32, ptr %sunkaddr79, align 4, !tbaa !24, !noalias !19
  %idx.ext65.i = trunc i32 %83 to i20
  %add.ptr66.i = getelementptr inbounds i8, ptr %output_ptr.0167.i, i20 %idx.ext65.i
  store <64 x i32> %70, ptr %add.ptr66.i, align 64, !tbaa !23, !noalias !19
  %sunkaddr80 = getelementptr inbounds i8, ptr %param, i20 88
  %84 = load i32, ptr %sunkaddr80, align 8, !tbaa !25, !noalias !19
  %idx.ext73.i = trunc i32 %84 to i20
  %add.ptr74.i = getelementptr inbounds i8, ptr %output_ptr.0167.i, i20 %idx.ext73.i
  store <64 x i32> %79, ptr %add.ptr74.i, align 64, !tbaa !23, !noalias !19
  %sunkaddr81 = getelementptr inbounds i8, ptr %param, i20 92
  %85 = load i32, ptr %sunkaddr81, align 4, !tbaa !26, !noalias !19
  %idx.ext81.i = trunc i32 %85 to i20
  %add.ptr82.i = getelementptr inbounds i8, ptr %output_ptr.0167.i, i20 %idx.ext81.i
  store <64 x i32> %80, ptr %add.ptr82.i, align 64, !tbaa !23, !noalias !19
  %86 = trunc nuw i32 %iterator_outer_cnt0.0158.i to i20
  %87 = tail call { ptr, i20 } @llvm.aie2p.add.2d(ptr %output_ptr.0167.i, i20 %0, i20 %1, i20 %2, i20 %86)
  %88 = extractvalue { ptr, i20 } %87, 1
  %89 = zext i20 %88 to i32
  %90 = extractvalue { ptr, i20 } %87, 0
  %inc86.i = add nuw nsw i32 %ot.0168.i, 1
  %sunkaddr82 = getelementptr inbounds i8, ptr %param, i20 68
  %91 = load i32, ptr %sunkaddr82, align 4, !tbaa !43, !noalias !19
  %cmp16.i = icmp slt i32 %inc86.i, %91
  br i1 %cmp16.i, label %for.body.i, label %exit.exitStub, !llvm.loop !44

exit.exitStub: ; preds = %for.cond.cleanup45.i
  ret void
}

!4 = !{!5, !7, i64 16}
!5 = !{!"A", !6, i64 0, !11, i64 64, !11, i64 120, !11, i64 176, !18, i64 232}
!6 = !{!"B", !7, i64 0, !7, i64 4, !7, i64 8, !10, i64 12, !7, i64 16, !7, i64 20, !7, i64 24, !7, i64 28, !7, i64 32, !7, i64 36, !7, i64 40}
!7 = !{!"int", !8, i64 0}
!8 = !{!"omnipotent char", !9, i64 0}
!9 = !{!"Simple C++ TBAA"}
!10 = !{!"bool", !8, i64 0}
!11 = !{!"C", !12, i64 0, !13, i64 32}
!12 = !{!"D", !8, i64 0}
!13 = !{!"E", !14, i64 0}
!14 = !{!"F", !15, i64 0, !17, i64 20}
!15 = !{!"G", !16, i64 0}
!16 = !{!"H", !7, i64 0, !7, i64 4, !7, i64 8, !7, i64 12, !7, i64 16}
!17 = !{!"I", !7, i64 0}
!18 = !{!"J", !12, i64 0, !13, i64 32}
!19 = !{!20, !22}
!20 = distinct !{!20, !21, !"K: %matA"}
!21 = distinct !{!21, !"L"}
!22 = distinct !{!22, !21, !"M: %matB_bf16"}
!23 = !{!8, !8, i64 0}
!24 = !{!5, !7, i64 20}
!25 = !{!5, !7, i64 24}
!26 = !{!5, !7, i64 28}
!27 = !{!5, !7, i64 8}
!28 = !{!16, !7, i64 16}
!29 = !{!16, !7, i64 0}
!30 = !{!16, !7, i64 4}
!31 = !{!16, !7, i64 8}
!32 = !{!16, !7, i64 12}
!33 = !{!7, !7, i64 0}
!34 = !{!35, !20, !22}
!35 = distinct !{!35, !36, !"N: %agg.result"}
!36 = distinct !{!36, !"O"}
!37 = !{!20}
!38 = !{!22}
!39 = distinct !{!39, !40, !41, !42}
!40 = !{!"llvm.loop.mustprogress"}
!41 = !{!"llvm.loop.itercount.range", i64 4}
!42 = !{!"llvm.loop.unroll.disable"}
!43 = !{!5, !7, i64 4}
!44 = distinct !{!44, !40, !45, !42}
!45 = !{!"llvm.loop.itercount.range", i64 2}
