; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates

; RUN: llc -mtriple=aie2p -verify-machineinstrs %s -o - | FileCheck %s

define void @sigmoid_int8_1() {
; CHECK-LABEL: sigmoid_int8_1:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    movxm ls, #.LBB0_1
; CHECK-NEXT:    movxm le, #.L_LEnd0
; CHECK-NEXT:    mova p0, #0; mov crunpacksize, #1
; CHECK-NEXT:    mova r0, #0; vldb.unpack x5, unpacksign0, [p0, #0]; mov crsrsmode, #0
; CHECK-NEXT:    vbcst.32 x2, r0
; CHECK-NEXT:    nopa ; nopb ; nops ; nopx ; add.nc lc, r0, #-3; nopv
; CHECK-NEXT:    mova r1, #1; nopb ; nops ; nopx ; vbcst.16 x0, r0; nopv
; CHECK-NEXT:    nops ; vbcst.16 x4, r1
; CHECK-NEXT:    vldb.unpack x5, unpacksign0, [p0, #0]; vmov x7, x0
; CHECK-NEXT:    vmov x6, x0
; CHECK-NEXT:    vmin_ge.16 x9, r16, x5, x4, vaddsign0
; CHECK-NEXT:    vmax_lt.16 x8, r16, x9, x0, vaddsign0; vclr dm0
; CHECK-NEXT:    vmov x9, x8
; CHECK-NEXT:    vldb.unpack x5, unpacksign0, [p0, #0]; mov s0, r0
; CHECK-NEXT:    vmov x3, x2; vmac dm3, dm0, y4, y3,r0
; CHECK-NEXT:    vmin_ge.16 x9, r16, x5, x4, vaddsign0
; CHECK-NEXT:    vmax_lt.16 x8, r16, x9, x0, vaddsign0; vmsc dm4, dm3, y1, y4,r0
; CHECK-NEXT:    vmov x9, x8
; CHECK-NEXT:  .LBB0_1: // %for.body
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    nopa ; vldb.unpack x5, unpacksign0, [p0, #0]; nops ; nopxm ; nopv
; CHECK-NEXT:    vmac dm3, dm0, y4, y3,r0
; CHECK-NEXT:    vmin_ge.16 x9, r16, x5, x4, vaddsign0
; CHECK-NEXT:    vmax_lt.16 x8, r16, x9, x0, vaddsign0; vmsc dm4, dm3, y1, y4,r0
; CHECK-NEXT:  .L_LEnd0:
; CHECK-NEXT:    nopa ; nopb ; vsrs.4x wh11, cml4, s0, srssign0; nopx ; vmov x9, x8; nopv
; CHECK-NEXT:  // %bb.2: // %for.cond.cleanup
; CHECK-NEXT:    nopx
; CHECK-NEXT:    vmac dm3, dm0, y4, y3,r0
; CHECK-NEXT:    vmin_ge.16 x9, r16, x5, x4, vaddsign0
; CHECK-NEXT:    vmax_lt.16 x8, r16, x9, x0, vaddsign0; vmsc dm4, dm3, y1, y4,r0
; CHECK-NEXT:    vsrs.4x wh11, cml4, s0, srssign0; vmov x9, x8
; CHECK-NEXT:    nop
; CHECK-NEXT:    vmac dm3, dm0, y4, y3,r0
; CHECK-NEXT:    nop
; CHECK-NEXT:    vmsc dm4, dm3, y1, y4,r0
; CHECK-NEXT:    vsrs.4x wh11, cml4, s0, srssign0
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    vsrs.4x wh11, cml4, s0, srssign0 // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %for.body, %entry
  %j.058 = phi i32 [ 0, %entry ], [ %inc, %for.body ]
  %0 = load <32 x i8>, ptr addrspace(5) null, align 32
  %1 = tail call <32 x i16> @llvm.aie2p.unpack.I512.I16.I8(<32 x i8> %0, i32 0)
  %2 = tail call { <32 x i16>, i32 } @llvm.aie2p.vmin.ge16(<32 x i16> %1, <32 x i16> splat (i16 1), i32 0)
  %3 = extractvalue { <32 x i16>, i32 } %2, 0
  %4 = tail call { <32 x i16>, i32 } @llvm.aie2p.vmax.lt16(<32 x i16> %3, <32 x i16> zeroinitializer, i32 0)
  %5 = extractvalue { <32 x i16>, i32 } %4, 0
  %6 = bitcast <32 x i16> %5 to <16 x i32>
  %shuffle.i.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i = shufflevector <16 x i32> %6, <16 x i32> %6, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %7 = tail call <32 x i64> @llvm.aie2p.I1024.I1024.ACC2048.mac.conf(<32 x i32> %shuffle.i.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i, <64 x i16> zeroinitializer, <32 x i64> zeroinitializer, i32 0)
  %8 = bitcast <32 x i32> %shuffle.i.i.i.i.i.i13.i.i.i.i.i.i.i.i.i.i to <64 x i16>
  %9 = tail call <32 x i64> @llvm.aie2p.I1024.I1024.ACC2048.msc.conf(<32 x i32> zeroinitializer, <64 x i16> %8, <32 x i64> %7, i32 0)
  %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i43 = shufflevector <32 x i64> %9, <32 x i64> zeroinitializer, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %10 = bitcast <16 x i64> %shuffle.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i43 to <32 x i32>
  %11 = tail call <32 x i8> @llvm.aie2p.I256.v32.acc32.srs(<32 x i32> %10, i32 0, i32 0)
  %inc = add i32 %j.058, 1
  %exitcond.not = icmp eq i32 %inc, 0
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body, !llvm.loop !0
}

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <32 x i16> @llvm.aie2p.unpack.I512.I16.I8(<32 x i8>, i32) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare { <32 x i16>, i32 } @llvm.aie2p.vmin.ge16(<32 x i16>, <32 x i16>, i32) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare { <32 x i16>, i32 } @llvm.aie2p.vmax.lt16(<32 x i16>, <32 x i16>, i32) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <32 x i64> @llvm.aie2p.I1024.I1024.ACC2048.mac.conf(<32 x i32>, <64 x i16>, <32 x i64>, i32) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <32 x i64> @llvm.aie2p.I1024.I1024.ACC2048.msc.conf(<32 x i32>, <64 x i16>, <32 x i64>, i32) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read)
declare <32 x i8> @llvm.aie2p.I256.v32.acc32.srs(<32 x i32>, i32, i32) #1

attributes #0 = { nocallback nofree nosync nounwind willreturn memory(none) }
attributes #1 = { nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read) }

!0 = distinct !{!0, !1, !2}
!1 = !{!"llvm.loop.mustprogress"}
!2 = !{!"llvm.loop.itercount.range", i64 8}
