# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -verify-machineinstrs -run-pass=postmisched %s -o - | FileCheck %s

---
name:            crf2fmask_vst_conv
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $bml1, $p2

    ; CHECK-LABEL: name: crf2fmask_vst_conv
    ; CHECK: liveins: $bml1, $p2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $crf2fmask = MOVXM_lng_cg 0
    ; CHECK-NEXT: $crrnd = MOVXM_lng_cg 0
    ; CHECK-NEXT: VST_CONV_BF16_FP32_ag_idx_imm killed $p2, 0, killed $bml1, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $crf2fmask   = MOVXM_lng_cg 0
    $crrnd   = MOVXM_lng_cg 0
    VST_CONV_BF16_FP32_ag_idx_imm $p2, 0, $bml1, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
...

---
name:            crf2fmask_vst_conv_potinc
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $bml1, $p2

    ; CHECK-LABEL: name: crf2fmask_vst_conv_potinc
    ; CHECK: liveins: $bml1, $p2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $crf2fmask = MOVXM_lng_cg 0
    ; CHECK-NEXT: $crrnd = MOVXM_lng_cg 0
    ; CHECK-NEXT: $p2 = VST_CONV_BF16_FP32_ag_pstm_nrm_imm killed $p2, 0, killed $bml1, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $crf2fmask   = MOVXM_lng_cg 0
    $crrnd   = MOVXM_lng_cg 0
    $p2 = VST_CONV_BF16_FP32_ag_pstm_nrm_imm $p2, 0, $bml1, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
...

---
name:            crf2fmask_vst_conv_2d
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $bml1, $d0, $p2

    ; CHECK-LABEL: name: crf2fmask_vst_conv_2d
    ; CHECK: liveins: $bml1, $d0, $p2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $crf2fmask = MOVXM_lng_cg 0
    ; CHECK-NEXT: $crrnd = MOVXM_lng_cg 0
    ; CHECK-NEXT: $p2, $dc0 = VST_CONV_2D_BF16_FP32 killed $p2, killed $d0, killed $bml1, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $crf2fmask   = MOVXM_lng_cg 0
    $crrnd   = MOVXM_lng_cg 0
    $p2, $dc0 = VST_CONV_2D_BF16_FP32 $p2, $d0, $bml1, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
...

---
name:            crf2fmask_vst_conv_3d
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $bml1, $d0_3d, $p2

    ; CHECK-LABEL: name: crf2fmask_vst_conv_3d
    ; CHECK: liveins: $bml1, $d0_3d, $p2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $crf2fmask = MOVXM_lng_cg 0
    ; CHECK-NEXT: $crrnd = MOVXM_lng_cg 0
    ; CHECK-NEXT: $p2, $dc0, $dc4 = VST_CONV_3D_BF16_FP32 killed $p2, killed $d0_3d, killed $bml1, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $crf2fmask   = MOVXM_lng_cg 0
    $crrnd   = MOVXM_lng_cg 0
    $p2, $dc0, $dc4 = VST_CONV_3D_BF16_FP32 $p2, $d0_3d, $bml1, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
...
