# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 --issue-limit=1 -verify-machineinstrs \
# RUN:    -run-pass=postmisched %s -o - | FileCheck %s

---
name:            test_crfpmask
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x4, $x5, $r9, $p2, $d0, $amll0, $s0, $bml1

    ; CHECK-LABEL: name: test_crfpmask
    ; CHECK: liveins: $x4, $x5, $r9, $p2, $d0, $amll0, $s0, $bml1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $x4 = VFLOOR_S32_BF16_mFl2FxSrc_AM killed $amll0, killed $s0, implicit-def $srf2iflags, implicit $crf2imask
    ; CHECK-NEXT: $crfpmask = MOVXM_lng_cg 0
    ; CHECK-NEXT: $bml5 = VMUL_F_vmac_bm_core_dense killed $x4, killed $x5, killed $r9, implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: $crf2fmask = MOVXM_lng_cg 0
    ; CHECK-NEXT: $p2, $dc0 = VST_CONV_2D_BF16_FP32 killed $p2, killed $d0, killed $bml1, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $crf2fmask   = MOVXM_lng_cg 0
    $p2, $dc0 = VST_CONV_2D_BF16_FP32 $p2, $d0, $bml1, implicit-def $srf2fflags, implicit $crrnd, implicit $crf2fmask
    $crfpmask   = MOVXM_lng_cg 0
    $x4 = VFLOOR_S32_BF16_mFl2FxSrc_AM $amll0, $s0, implicit-def $srf2iflags, implicit $crf2imask
    $bml5 = VMUL_F_vmac_bm_core_dense $x4, $x5, $r9, implicit-def $srfpflags, implicit $crfpmask
...
