# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -verify-machineinstrs -run-pass=postmisched %s -o - | FileCheck %s

---
name:            test_reg
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $bml0

    ; CHECK-LABEL: name: test_reg
    ; CHECK: liveins: $bml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $crmcden = MOVXM_lng_cg 0
    ; CHECK-NEXT: VMOV_mv_mcd killed $bml0, implicit $crmcden
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $crmcden  = MOVXM_lng_cg 0
    VMOV_mv_mcd $bml0, implicit $crmcden
...
