# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -verify-machineinstrs -run-pass=postmisched %topdown-multi %s -o - | FileCheck %s

---
name:            test_srfpflags
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x4, $x5, $r9

    ; CHECK-LABEL: name: test_srfpflags
    ; CHECK: liveins: $x4, $x5, $r9
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $bml5 = VMUL_F_vmac_bm_core_dense killed $x4, killed $x5, killed $r9, implicit-def $srfpflags, implicit $crfpmask
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $crf2fmask = MOVXM_lng_cg $srfpflags
    $bml5 = VMUL_F_vmac_bm_core_dense $x4, $x5, $r9, implicit-def $srfpflags, implicit $crfpmask
    $crf2fmask   = MOVXM_lng_cg $srfpflags
...
