# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2ps -run-pass=aie-machine-alignment %s -verify-machineinstrs -o - | FileCheck %s

---
name:            zol_elongated_preheader_plus_1_LoopBundles_ge112bytes
alignment:       16
body:             |
  ; CHECK-LABEL: name: zol_elongated_preheader_plus_1_LoopBundles_ge112bytes
  ; CHECK: bb.0.entry (align 16):
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BUNDLE implicit-def $x6, implicit-def $wl6, implicit-def $wh6, implicit-def $p0, implicit killed $p0 {
  ; CHECK-NEXT:     renamable $x6, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 0 :: (load (<32 x s16>))
  ; CHECK-NEXT:     NOPX
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $r0, implicit-def dead $srcarry, implicit killed $r0 {
  ; CHECK-NEXT:     renamable $r0 = ADD_add_r_ri killed renamable $r0, -1, implicit-def dead $srcarry
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $lc, implicit $r0, implicit-def $lc, implicit-def $lci {
  ; CHECK-NEXT:     NOPB
  ; CHECK-NEXT:     $lc = ADD_NC_add_lc_ri $r0, -3, implicit-def $lc, implicit-def $lci
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x0, implicit-def $wl0, implicit-def $wh0, implicit-def $p0, implicit-def $r0, implicit-def dead $srcarry, implicit killed $p0, implicit killed $r0 {
  ; CHECK-NEXT:     renamable $x0, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 64 :: (load (<32 x s16>))
  ; CHECK-NEXT:     renamable $r0 = ADD_add_r_ri killed renamable $r0, -1, implicit-def dead $srcarry
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x2, implicit-def $wl2, implicit-def $wh2, implicit-def $p0, implicit-def $ls, implicit killed $p0 {
  ; CHECK-NEXT:     renamable $x2, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 64 :: (load (<32 x s16>))
  ; CHECK-NEXT:     MOVXM_lng_cg_ls_abs 0, implicit-def $ls
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x1, implicit-def $wl1, implicit-def $wh1, implicit-def $p0, implicit-def $le, implicit killed $p0 {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     renamable $x1, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 128 :: (load (<32 x s16>))
  ; CHECK-NEXT:     NOPS
  ; CHECK-NEXT:     MOVXM_lng_cg_le_abs <mcsymbol .L_1120>, implicit-def $le
  ; CHECK-NEXT:     NOPV
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x0, implicit-def $wl0, implicit-def $wh0, implicit-def $p0, implicit-def $r0, implicit-def dead $srcarry, implicit killed $p0, implicit killed $r0 {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     renamable $x0, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 64 :: (load (<32 x s16>))
  ; CHECK-NEXT:     NOPS
  ; CHECK-NEXT:     renamable $r0 = ADD_add_r_ri killed renamable $r0, -1, implicit-def dead $srcarry
  ; CHECK-NEXT:     NOPM
  ; CHECK-NEXT:     NOPV
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x2, implicit-def $wl2, implicit-def $wh2, implicit-def $p0, implicit killed $p0 {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     renamable $x2, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 64 :: (load (<32 x s16>))
  ; CHECK-NEXT:     NOPS
  ; CHECK-NEXT:     NOPXM
  ; CHECK-NEXT:     NOPV
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x1, implicit-def $wl1, implicit-def $wh1, implicit-def $p0, implicit killed $p0 {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     renamable $x1, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 128 :: (load (<32 x s16>))
  ; CHECK-NEXT:     NOPS
  ; CHECK-NEXT:     NOPXM
  ; CHECK-NEXT:     NOPV
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x0, implicit-def $wl0, implicit-def $wh0, implicit-def $p0, implicit-def $r0, implicit-def dead $srcarry, implicit killed $p0, implicit killed $r0 {
  ; CHECK-NEXT:     renamable $x0, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 64 :: (load (<32 x s16>))
  ; CHECK-NEXT:     renamable $r0 = ADD_add_r_ri killed renamable $r0, -1, implicit-def dead $srcarry
  ; CHECK-NEXT:     NOPM
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x2, implicit-def $wl2, implicit-def $wh2, implicit-def $p0, implicit-def $x4, implicit-def $wl4, implicit-def $wh4, implicit killed $p0, implicit $x6, implicit killed $x0, implicit $crbf8conf, implicit $crfp8conf {
  ; CHECK-NEXT:     renamable $x2, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 64 :: (load (<32 x s16>))
  ; CHECK-NEXT:     renamable $x4 = VADD_16 renamable $x6, killed renamable $x0, implicit $crbf8conf, implicit $crfp8conf
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x1, implicit-def $wl1, implicit-def $wh1, implicit-def $p0, implicit killed $p0 {
  ; CHECK-NEXT:     renamable $x1, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 128 :: (load (<32 x s16>))
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $r23, implicit-def $p0, implicit-def $r24, implicit-def $s0, implicit $p1 {
  ; CHECK-NEXT:     renamable $r23 = MOVA 0
  ; CHECK-NEXT:     $p1 = MOVS $p0
  ; CHECK-NEXT:     renamable $r0 = MOVX_alu_cg_or 64
  ; CHECK-NEXT:     $s0 = MOV_alu_mv_mv_mv_scl internal $r0
  ; CHECK-NEXT:   }
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1 (align 16):
  ; CHECK-NEXT:   successors: %bb.1(0x7c000000), %bb.2(0x04000000)
  ; CHECK-NEXT:   liveins: $p1, $r0, $s0, $r5, $x6
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BUNDLE implicit-def $x0, implicit-def $wl0, implicit-def $wh0, implicit-def $p1, implicit-def $r0, implicit-def dead $srcarry, implicit-def $x6, implicit-def $wl6, implicit-def $wh6, implicit killed $p1, implicit killed $r0, implicit killed $x4, implicit killed $x1, implicit $crbf8conf, implicit $crfp8conf {
  ; CHECK-NEXT:     renamable $x0, renamable $p1 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p1, 64 :: (load (<32 x s16>))
  ; CHECK-NEXT:     renamable $r0 = ADD_add_r_ri killed renamable $r0, -1, implicit-def dead $srcarry
  ; CHECK-NEXT:     renamable $x6 = VADD_16 killed renamable $x4, killed renamable $x1, implicit $crbf8conf, implicit $crfp8conf
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x2, implicit-def $wl2, implicit-def $wh2, implicit-def $p1, implicit-def $x4, implicit-def $wl4, implicit-def $wh4, implicit killed $p1, implicit $x6, implicit killed $x0, implicit $crbf8conf, implicit $crfp8conf {
  ; CHECK-NEXT:     renamable $x2, renamable $p1 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p1, 64 :: (load (<32 x s16>))
  ; CHECK-NEXT:     renamable $x4 = VADD_16 renamable $x6, killed renamable $x0, implicit $crbf8conf, implicit $crfp8conf
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x1, implicit-def $wl1, implicit-def $wh1, implicit-def $p1, implicit killed $p1 {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     renamable $x1, renamable $p1 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p1, 128 :: (load (<32 x s16>))
  ; CHECK-NEXT:     NOPS
  ; CHECK-NEXT:     NOPXM
  ; CHECK-NEXT:     NOPV
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.1, implicit $ls, implicit $le
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   BUNDLE implicit $lr {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     NOPB
  ; CHECK-NEXT:     NOPS
  ; CHECK-NEXT:     RET implicit $lr
  ; CHECK-NEXT:     NOPM
  ; CHECK-NEXT:     NOPV
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   DelayedSchedBarrier implicit killed $x0
  bb.0.entry (align 16):
    successors: %bb.1(0x80000000)
    liveins: $p0, $r0

    BUNDLE implicit-def $x6, implicit-def $wl6, implicit-def $wh6, implicit-def $p0, implicit killed $p0 {
      renamable $x6, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 0 :: (load (<32 x s16>))
    }
    BUNDLE implicit-def $r0, implicit-def dead $srcarry, implicit killed $r0 {
      renamable $r0 = ADD_add_r_ri killed renamable $r0, -1, implicit-def dead $srcarry
    }
    BUNDLE implicit-def $lc, implicit $r0, implicit-def $lc, implicit-def $lci {
      NOPB
      $lc = ADD_NC_add_lc_ri $r0, -3, implicit-def $lc, implicit-def $lci
    }
    BUNDLE implicit-def $x0, implicit-def $wl0, implicit-def $wh0, implicit-def $p0, implicit-def $r0, implicit-def dead $srcarry, implicit killed $p0, implicit killed $r0 {
      renamable $x0, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 64 :: (load (<32 x s16>))
      renamable $r0 = ADD_add_r_ri killed renamable $r0, -1, implicit-def dead $srcarry
    }
    BUNDLE implicit-def $x2, implicit-def $wl2, implicit-def $wh2, implicit-def $p0, implicit-def $ls, implicit killed $p0 {
      renamable $x2, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 64 :: (load (<32 x s16>))
      MOVXM_lng_cg_ls_abs 0, implicit-def $ls
    }
    BUNDLE implicit-def $x1, implicit-def $wl1, implicit-def $wh1, implicit-def $p0, implicit-def $le, implicit killed $p0 {
      renamable $x1, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 128 :: (load (<32 x s16>))
      MOVXM_lng_cg_le_abs <mcsymbol .L_1120>, implicit-def $le
    }
    BUNDLE implicit-def $x0, implicit-def $wl0, implicit-def $wh0, implicit-def $p0, implicit-def $r0, implicit-def dead $srcarry, implicit killed $p0, implicit killed $r0 {
      renamable $x0, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 64 :: (load (<32 x s16>))
      renamable $r0 = ADD_add_r_ri killed renamable $r0, -1, implicit-def dead $srcarry
    }
    BUNDLE implicit-def $x2, implicit-def $wl2, implicit-def $wh2, implicit-def $p0, implicit killed $p0 {
      renamable $x2, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 64 :: (load (<32 x s16>))
    }
    BUNDLE implicit-def $x1, implicit-def $wl1, implicit-def $wh1, implicit-def $p0, implicit killed $p0 {
      renamable $x1, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 128 :: (load (<32 x s16>))
    }
    BUNDLE implicit-def $x0, implicit-def $wl0, implicit-def $wh0, implicit-def $p0, implicit-def $r0, implicit-def dead $srcarry, implicit killed $p0, implicit killed $r0 {
      renamable $x0, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 64 :: (load (<32 x s16>))
      renamable $r0 = ADD_add_r_ri killed renamable $r0, -1, implicit-def dead $srcarry
    }
    BUNDLE implicit-def $x2, implicit-def $wl2, implicit-def $wh2, implicit-def $p0, implicit-def $x4, implicit-def $wl4, implicit-def $wh4, implicit killed $p0, implicit $x6, implicit killed $x0, implicit $crbf8conf, implicit $crfp8conf {
      renamable $x2, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 64 :: (load (<32 x s16>))
      renamable $x4 = VADD_16 renamable $x6, killed renamable $x0, implicit $crbf8conf, implicit $crfp8conf
    }
    BUNDLE implicit-def $x1, implicit-def $wl1, implicit-def $wh1, implicit-def $p0, implicit killed $p0 {
      renamable $x1, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 128 :: (load (<32 x s16>))
    }
    BUNDLE implicit-def $r23, implicit-def $p0, implicit-def $r24, implicit-def $s0, implicit $p1 {
      renamable $r23 = MOVA 0
      $p1 = MOVS $p0
      renamable $r0 = MOVX_alu_cg_or 64
      $s0 = MOV_alu_mv_mv_mv_scl internal $r0
    }

  bb.1 (align 16):
    successors: %bb.1(0x7c000000), %bb.2(0x04000000)
    liveins: $p1, $r0, $s0, $r5, $x6

    BUNDLE implicit-def $x0, implicit-def $wl0, implicit-def $wh0, implicit-def $p1, implicit-def $r0, implicit-def dead $srcarry, implicit-def $x6, implicit-def $wl6, implicit-def $wh6, implicit killed $p1, implicit killed $r0, implicit killed $x4, implicit killed $x1, implicit $crbf8conf, implicit $crfp8conf {
      renamable $x0, renamable $p1 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p1, 64 :: (load (<32 x s16>))
      renamable $r0 = ADD_add_r_ri killed renamable $r0, -1, implicit-def dead $srcarry
      renamable $x6 = VADD_16 killed renamable $x4, killed renamable $x1, implicit $crbf8conf, implicit $crfp8conf
    }
    BUNDLE implicit-def $x2, implicit-def $wl2, implicit-def $wh2, implicit-def $p1, implicit-def $x4, implicit-def $wl4, implicit-def $wh4, implicit killed $p1, implicit $x6, implicit killed $x0, implicit $crbf8conf, implicit $crfp8conf {
      renamable $x2, renamable $p1 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p1, 64 :: (load (<32 x s16>))
      renamable $x4 = VADD_16 renamable $x6, killed renamable $x0, implicit $crbf8conf, implicit $crfp8conf
    }
    BUNDLE implicit-def $x1, implicit-def $wl1, implicit-def $wh1, implicit-def $p1, implicit killed $p1 {
      renamable $x1, renamable $p1 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p1, 128 :: (load (<32 x s16>))
    }
    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.1, implicit $ls, implicit $le

  bb.2:
    BUNDLE implicit $lr {
      RET implicit $lr
    }
    DelayedSchedBarrier implicit killed $x0

...

# Same as before, but with an empty MBB after the ZOL body.

---
name:            empty_MBB_After_zol_elongated_preheader_plus_1_LoopBundles_ge112bytes
alignment:       16
body:             |
  ; CHECK-LABEL: name: empty_MBB_After_zol_elongated_preheader_plus_1_LoopBundles_ge112bytes
  ; CHECK: bb.0.entry (align 16):
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BUNDLE implicit-def $x6, implicit-def $wl6, implicit-def $wh6, implicit-def $p0, implicit killed $p0 {
  ; CHECK-NEXT:     renamable $x6, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 0 :: (load (<32 x s16>))
  ; CHECK-NEXT:     NOPX
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $r0, implicit-def dead $srcarry, implicit killed $r0 {
  ; CHECK-NEXT:     renamable $r0 = ADD_add_r_ri killed renamable $r0, -1, implicit-def dead $srcarry
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $lc, implicit $r0, implicit-def $lc, implicit-def $lci {
  ; CHECK-NEXT:     NOPB
  ; CHECK-NEXT:     $lc = ADD_NC_add_lc_ri $r0, -3, implicit-def $lc, implicit-def $lci
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x0, implicit-def $wl0, implicit-def $wh0, implicit-def $p0, implicit-def $r0, implicit-def dead $srcarry, implicit killed $p0, implicit killed $r0 {
  ; CHECK-NEXT:     renamable $x0, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 64 :: (load (<32 x s16>))
  ; CHECK-NEXT:     renamable $r0 = ADD_add_r_ri killed renamable $r0, -1, implicit-def dead $srcarry
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x2, implicit-def $wl2, implicit-def $wh2, implicit-def $p0, implicit-def $ls, implicit killed $p0 {
  ; CHECK-NEXT:     renamable $x2, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 64 :: (load (<32 x s16>))
  ; CHECK-NEXT:     MOVXM_lng_cg_ls_abs 0, implicit-def $ls
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x1, implicit-def $wl1, implicit-def $wh1, implicit-def $p0, implicit-def $le, implicit killed $p0 {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     renamable $x1, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 128 :: (load (<32 x s16>))
  ; CHECK-NEXT:     NOPS
  ; CHECK-NEXT:     MOVXM_lng_cg_le_abs <mcsymbol .L_1120>, implicit-def $le
  ; CHECK-NEXT:     NOPV
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x0, implicit-def $wl0, implicit-def $wh0, implicit-def $p0, implicit-def $r0, implicit-def dead $srcarry, implicit killed $p0, implicit killed $r0 {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     renamable $x0, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 64 :: (load (<32 x s16>))
  ; CHECK-NEXT:     NOPS
  ; CHECK-NEXT:     renamable $r0 = ADD_add_r_ri killed renamable $r0, -1, implicit-def dead $srcarry
  ; CHECK-NEXT:     NOPM
  ; CHECK-NEXT:     NOPV
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x2, implicit-def $wl2, implicit-def $wh2, implicit-def $p0, implicit killed $p0 {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     renamable $x2, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 64 :: (load (<32 x s16>))
  ; CHECK-NEXT:     NOPS
  ; CHECK-NEXT:     NOPXM
  ; CHECK-NEXT:     NOPV
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x1, implicit-def $wl1, implicit-def $wh1, implicit-def $p0, implicit killed $p0 {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     renamable $x1, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 128 :: (load (<32 x s16>))
  ; CHECK-NEXT:     NOPS
  ; CHECK-NEXT:     NOPXM
  ; CHECK-NEXT:     NOPV
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x0, implicit-def $wl0, implicit-def $wh0, implicit-def $p0, implicit-def $r0, implicit-def dead $srcarry, implicit killed $p0, implicit killed $r0 {
  ; CHECK-NEXT:     renamable $x0, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 64 :: (load (<32 x s16>))
  ; CHECK-NEXT:     renamable $r0 = ADD_add_r_ri killed renamable $r0, -1, implicit-def dead $srcarry
  ; CHECK-NEXT:     NOPM
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x2, implicit-def $wl2, implicit-def $wh2, implicit-def $p0, implicit-def $x4, implicit-def $wl4, implicit-def $wh4, implicit killed $p0, implicit $x6, implicit killed $x0, implicit $crbf8conf, implicit $crfp8conf {
  ; CHECK-NEXT:     renamable $x2, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 64 :: (load (<32 x s16>))
  ; CHECK-NEXT:     renamable $x4 = VADD_16 renamable $x6, killed renamable $x0, implicit $crbf8conf, implicit $crfp8conf
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x1, implicit-def $wl1, implicit-def $wh1, implicit-def $p0, implicit killed $p0 {
  ; CHECK-NEXT:     renamable $x1, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 128 :: (load (<32 x s16>))
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $r23, implicit-def $p0, implicit-def $r24, implicit-def $s0, implicit $p1 {
  ; CHECK-NEXT:     renamable $r23 = MOVA 0
  ; CHECK-NEXT:     $p1 = MOVS $p0
  ; CHECK-NEXT:     renamable $r0 = MOVX_alu_cg_or 64
  ; CHECK-NEXT:     $s0 = MOV_alu_mv_mv_mv_scl internal $r0
  ; CHECK-NEXT:   }
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1 (align 16):
  ; CHECK-NEXT:   successors: %bb.1(0x7c000000), %bb.2(0x04000000)
  ; CHECK-NEXT:   liveins: $p1, $r0, $s0, $r5, $x6
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BUNDLE implicit-def $x0, implicit-def $wl0, implicit-def $wh0, implicit-def $p1, implicit-def $r0, implicit-def dead $srcarry, implicit-def $x6, implicit-def $wl6, implicit-def $wh6, implicit killed $p1, implicit killed $r0, implicit killed $x4, implicit killed $x1, implicit $crbf8conf, implicit $crfp8conf {
  ; CHECK-NEXT:     renamable $x0, renamable $p1 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p1, 64 :: (load (<32 x s16>))
  ; CHECK-NEXT:     renamable $r0 = ADD_add_r_ri killed renamable $r0, -1, implicit-def dead $srcarry
  ; CHECK-NEXT:     renamable $x6 = VADD_16 killed renamable $x4, killed renamable $x1, implicit $crbf8conf, implicit $crfp8conf
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x2, implicit-def $wl2, implicit-def $wh2, implicit-def $p1, implicit-def $x4, implicit-def $wl4, implicit-def $wh4, implicit killed $p1, implicit $x6, implicit killed $x0, implicit $crbf8conf, implicit $crfp8conf {
  ; CHECK-NEXT:     renamable $x2, renamable $p1 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p1, 64 :: (load (<32 x s16>))
  ; CHECK-NEXT:     renamable $x4 = VADD_16 renamable $x6, killed renamable $x0, implicit $crbf8conf, implicit $crfp8conf
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x1, implicit-def $wl1, implicit-def $wh1, implicit-def $p1, implicit killed $p1 {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     renamable $x1, renamable $p1 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p1, 128 :: (load (<32 x s16>))
  ; CHECK-NEXT:     NOPS
  ; CHECK-NEXT:     NOPXM
  ; CHECK-NEXT:     NOPV
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.1, implicit $ls, implicit $le
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   BUNDLE implicit $lr {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     NOPB
  ; CHECK-NEXT:     NOPS
  ; CHECK-NEXT:     RET implicit $lr
  ; CHECK-NEXT:     NOPM
  ; CHECK-NEXT:     NOPV
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   DelayedSchedBarrier implicit killed $x0
  bb.0.entry (align 16):
    successors: %bb.1(0x80000000)
    liveins: $p0, $r0

    BUNDLE implicit-def $x6, implicit-def $wl6, implicit-def $wh6, implicit-def $p0, implicit killed $p0 {
      renamable $x6, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 0 :: (load (<32 x s16>))
    }
    BUNDLE implicit-def $r0, implicit-def dead $srcarry, implicit killed $r0 {
      renamable $r0 = ADD_add_r_ri killed renamable $r0, -1, implicit-def dead $srcarry
    }
    BUNDLE implicit-def $lc, implicit $r0, implicit-def $lc, implicit-def $lci {
      NOPB
      $lc = ADD_NC_add_lc_ri $r0, -3, implicit-def $lc, implicit-def $lci
    }
    BUNDLE implicit-def $x0, implicit-def $wl0, implicit-def $wh0, implicit-def $p0, implicit-def $r0, implicit-def dead $srcarry, implicit killed $p0, implicit killed $r0 {
      renamable $x0, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 64 :: (load (<32 x s16>))
      renamable $r0 = ADD_add_r_ri killed renamable $r0, -1, implicit-def dead $srcarry
    }
    BUNDLE implicit-def $x2, implicit-def $wl2, implicit-def $wh2, implicit-def $p0, implicit-def $ls, implicit killed $p0 {
      renamable $x2, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 64 :: (load (<32 x s16>))
      MOVXM_lng_cg_ls_abs 0, implicit-def $ls
    }
    BUNDLE implicit-def $x1, implicit-def $wl1, implicit-def $wh1, implicit-def $p0, implicit-def $le, implicit killed $p0 {
      renamable $x1, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 128 :: (load (<32 x s16>))
      MOVXM_lng_cg_le_abs <mcsymbol .L_1120>, implicit-def $le
    }
    BUNDLE implicit-def $x0, implicit-def $wl0, implicit-def $wh0, implicit-def $p0, implicit-def $r0, implicit-def dead $srcarry, implicit killed $p0, implicit killed $r0 {
      renamable $x0, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 64 :: (load (<32 x s16>))
      renamable $r0 = ADD_add_r_ri killed renamable $r0, -1, implicit-def dead $srcarry
    }
    BUNDLE implicit-def $x2, implicit-def $wl2, implicit-def $wh2, implicit-def $p0, implicit killed $p0 {
      renamable $x2, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 64 :: (load (<32 x s16>))
    }
    BUNDLE implicit-def $x1, implicit-def $wl1, implicit-def $wh1, implicit-def $p0, implicit killed $p0 {
      renamable $x1, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 128 :: (load (<32 x s16>))
    }
    BUNDLE implicit-def $x0, implicit-def $wl0, implicit-def $wh0, implicit-def $p0, implicit-def $r0, implicit-def dead $srcarry, implicit killed $p0, implicit killed $r0 {
      renamable $x0, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 64 :: (load (<32 x s16>))
      renamable $r0 = ADD_add_r_ri killed renamable $r0, -1, implicit-def dead $srcarry
    }
    BUNDLE implicit-def $x2, implicit-def $wl2, implicit-def $wh2, implicit-def $p0, implicit-def $x4, implicit-def $wl4, implicit-def $wh4, implicit killed $p0, implicit $x6, implicit killed $x0, implicit $crbf8conf, implicit $crfp8conf {
      renamable $x2, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 64 :: (load (<32 x s16>))
      renamable $x4 = VADD_16 renamable $x6, killed renamable $x0, implicit $crbf8conf, implicit $crfp8conf
    }
    BUNDLE implicit-def $x1, implicit-def $wl1, implicit-def $wh1, implicit-def $p0, implicit killed $p0 {
      renamable $x1, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 128 :: (load (<32 x s16>))
    }
    BUNDLE implicit-def $r23, implicit-def $p0, implicit-def $r24, implicit-def $s0, implicit $p1 {
      renamable $r23 = MOVA 0
      $p1 = MOVS $p0
      renamable $r0 = MOVX_alu_cg_or 64
      $s0 = MOV_alu_mv_mv_mv_scl internal $r0
    }

  bb.1 (align 16):
    successors: %bb.1(0x7c000000), %bb.2(0x04000000)
    liveins: $p1, $r0, $s0, $r5, $x6

    BUNDLE implicit-def $x0, implicit-def $wl0, implicit-def $wh0, implicit-def $p1, implicit-def $r0, implicit-def dead $srcarry, implicit-def $x6, implicit-def $wl6, implicit-def $wh6, implicit killed $p1, implicit killed $r0, implicit killed $x4, implicit killed $x1, implicit $crbf8conf, implicit $crfp8conf {
      renamable $x0, renamable $p1 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p1, 64 :: (load (<32 x s16>))
      renamable $r0 = ADD_add_r_ri killed renamable $r0, -1, implicit-def dead $srcarry
      renamable $x6 = VADD_16 killed renamable $x4, killed renamable $x1, implicit $crbf8conf, implicit $crfp8conf
    }
    BUNDLE implicit-def $x2, implicit-def $wl2, implicit-def $wh2, implicit-def $p1, implicit-def $x4, implicit-def $wl4, implicit-def $wh4, implicit killed $p1, implicit $x6, implicit killed $x0, implicit $crbf8conf, implicit $crfp8conf {
      renamable $x2, renamable $p1 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p1, 64 :: (load (<32 x s16>))
      renamable $x4 = VADD_16 renamable $x6, killed renamable $x0, implicit $crbf8conf, implicit $crfp8conf
    }
    BUNDLE implicit-def $x1, implicit-def $wl1, implicit-def $wh1, implicit-def $p1, implicit killed $p1 {
      renamable $x1, renamable $p1 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p1, 128 :: (load (<32 x s16>))
    }
    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.1, implicit $ls, implicit $le

  bb.2:

  bb.3:
    BUNDLE implicit $lr {
      RET implicit $lr
    }
    DelayedSchedBarrier implicit killed $x0

...
