# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py

# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024-2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2 -run-pass=aie-hardware-loops \
# RUN:   --enable-aie-hardware-loops --enable-aie-zero-overhead-loops %s \
# RUN:  -verify-machineinstrs -o - | FileCheck %s


# We pass an empty loop to aie-hardware-loops, expecting it to be expanded to
# fallthrough straight line code.
---
name:            emptyLoop
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: emptyLoop
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.0.entry:
    successors: %bb.1
    liveins: $r0
    LoopStart $r0, 0
  bb.1:
    successors: %bb.1, %bb.2
    PseudoLoopEnd <mcsymbol .L_1120>, %bb.1, implicit $ls, implicit $le
  bb.2:
    PseudoRET implicit $lr
...
