; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
;
; RUN: opt -mtriple=aie2p -passes=indvars -S < %s | FileCheck %s


; Test 1: Separate load/store pointers - AIE should keep them separate by default
define void @separate_load_store(ptr %arr, i32 %n) {
; CHECK-LABEL: @separate_load_store(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[UMAX:%.*]] = call i32 @llvm.umax.i32(i32 [[N:%.*]], i32 1)
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[I_NEXT:%.*]], [[LOOP]] ]
; CHECK-NEXT:    [[STORE_PTR:%.*]] = phi ptr [ [[ARR:%.*]], [[ENTRY]] ], [ [[STORE_PTR_NEXT:%.*]], [[LOOP]] ]
; CHECK-NEXT:    [[STORE_PTR1:%.*]] = phi ptr [ [[ARR]], [[ENTRY]] ], [ [[STORE_PTR_NEXT1:%.*]], [[LOOP]] ]
; CHECK-NEXT:    [[VAL:%.*]] = load i32, ptr [[STORE_PTR]], align 4
; CHECK-NEXT:    [[RESULT:%.*]] = add i32 [[VAL]], 1
; CHECK-NEXT:    store i32 [[RESULT]], ptr [[STORE_PTR1]], align 4
; CHECK-NEXT:    [[STORE_PTR_NEXT]] = getelementptr i32, ptr [[STORE_PTR]], i32 1
; CHECK-NEXT:    [[STORE_PTR_NEXT1]] = getelementptr i32, ptr [[STORE_PTR1]], i32 1
; CHECK-NEXT:    [[I_NEXT]] = add nuw i32 [[I]], 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp ne i32 [[I_NEXT]], [[UMAX]]
; CHECK-NEXT:    br i1 [[EXITCOND]], label [[LOOP]], label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %load_ptr = phi ptr [ %arr, %entry ], [ %load_ptr.next, %loop ]
  %store_ptr = phi ptr [ %arr, %entry ], [ %store_ptr.next, %loop ]

  %val = load i32, ptr %load_ptr, align 4
  %result = add i32 %val, 1
  store i32 %result, ptr %store_ptr, align 4

  %load_ptr.next = getelementptr i32, ptr %load_ptr, i32 1
  %store_ptr.next = getelementptr i32, ptr %store_ptr, i32 1
  %i.next = add i32 %i, 1
  %cond = icmp ult i32 %i.next, %n
  br i1 %cond, label %loop, label %exit

exit:
  ret void
}

; Test 2: Both IVs used for loads - should merge (no separation benefit)
define void @both_loads(ptr %arr, i32 %n) {
; CHECK-LABEL: @both_loads(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[PTR2:%.*]] = phi ptr [ [[ARR2:%.*]], [[ENTRY:%.*]] ], [ [[PTR2_NEXT:%.*]], [[LOOP]] ]
; CHECK-NEXT:    [[VAL1:%.*]] = load i32, ptr [[PTR2]], align 4
; CHECK-NEXT:    [[VAL2:%.*]] = load i32, ptr [[PTR2]], align 4
; CHECK-NEXT:    [[SUM:%.*]] = add i32 [[VAL1]], [[VAL2]]
; CHECK-NEXT:    [[PTR2_NEXT]] = getelementptr i32, ptr [[PTR2]], i32 1
; CHECK-NEXT:    br i1 false, label [[LOOP]], label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %ptr1 = phi ptr [ %arr, %entry ], [ %ptr1.next, %loop ]
  %ptr2 = phi ptr [ %arr, %entry ], [ %ptr2.next, %loop ]

  %val1 = load i32, ptr %ptr1, align 4
  %val2 = load i32, ptr %ptr2, align 4
  %sum = add i32 %val1, %val2

  %ptr1.next = getelementptr i32, ptr %ptr1, i32 1
  %ptr2.next = getelementptr i32, ptr %ptr2, i32 1
  %i.next = add i32 %i, 1
  %cond = icmp ult i32 %i.next, %n
  br i1 %cond, label %loop, label %exit

exit:
  ret void
}

; Test 3: Both IVs used for stores - should merge (no separation benefit)
define void @both_stores(ptr %arr, i32 %n, i32 %val) {
; CHECK-LABEL: @both_stores(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[UMAX:%.*]] = call i32 @llvm.umax.i32(i32 [[N:%.*]], i32 1)
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[I_NEXT:%.*]], [[LOOP]] ]
; CHECK-NEXT:    [[PTR2:%.*]] = phi ptr [ [[ARR2:%.*]], [[ENTRY]] ], [ [[PTR2_NEXT:%.*]], [[LOOP]] ]
; CHECK-NEXT:    store i32 [[VAL:%.*]], ptr [[PTR2]], align 4
; CHECK-NEXT:    store i32 [[VAL]], ptr [[PTR2]], align 4
; CHECK-NEXT:    [[PTR2_NEXT]] = getelementptr i32, ptr [[PTR2]], i32 1
; CHECK-NEXT:    [[I_NEXT]] = add nuw i32 [[I]], 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp ne i32 [[I_NEXT]], [[UMAX]]
; CHECK-NEXT:    br i1 [[EXITCOND]], label [[LOOP]], label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %ptr1 = phi ptr [ %arr, %entry ], [ %ptr1.next, %loop ]
  %ptr2 = phi ptr [ %arr, %entry ], [ %ptr2.next, %loop ]

  store i32 %val, ptr %ptr1, align 4
  store i32 %val, ptr %ptr2, align 4

  %ptr1.next = getelementptr i32, ptr %ptr1, i32 1
  %ptr2.next = getelementptr i32, ptr %ptr2, i32 1
  %i.next = add i32 %i, 1
  %cond = icmp ult i32 %i.next, %n
  br i1 %cond, label %loop, label %exit

exit:
  ret void
}

; Test 4: One IV has mixed usage - should merge (not cleanly separated)
define void @mixed_usage(ptr %arr, i32 %n) {
; CHECK-LABEL: @mixed_usage(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[UMAX:%.*]] = call i32 @llvm.umax.i32(i32 [[N:%.*]], i32 1)
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[I_NEXT:%.*]], [[LOOP]] ]
; CHECK-NEXT:    [[PTR1:%.*]] = phi ptr [ [[ARR:%.*]], [[ENTRY]] ], [ [[PTR1_NEXT:%.*]], [[LOOP]] ]
; CHECK-NEXT:    [[VAL:%.*]] = load i32, ptr [[PTR1]], align 4
; CHECK-NEXT:    store i32 [[VAL]], ptr [[PTR1]], align 4
; CHECK-NEXT:    [[PTR1_NEXT]] = getelementptr i32, ptr [[PTR1]], i32 1
; CHECK-NEXT:    [[I_NEXT]] = add nuw i32 [[I]], 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp ne i32 [[I_NEXT]], [[UMAX]]
; CHECK-NEXT:    br i1 [[EXITCOND]], label [[LOOP]], label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %ptr1 = phi ptr [ %arr, %entry ], [ %ptr1.next, %loop ]
  %ptr2 = phi ptr [ %arr, %entry ], [ %ptr2.next, %loop ]

  ; ptr1 used for both load and store (mixed)
  %val = load i32, ptr %ptr1, align 4
  store i32 %val, ptr %ptr1, align 4

  ; ptr2 used only for load
  %val2 = load i32, ptr %ptr2, align 4

  %ptr1.next = getelementptr i32, ptr %ptr1, i32 1
  %ptr2.next = getelementptr i32, ptr %ptr2, i32 1
  %i.next = add i32 %i, 1
  %cond = icmp ult i32 %i.next, %n
  br i1 %cond, label %loop, label %exit

exit:
  ret void
}

; Test 5: In-place operation (same pointer for load and store) - should merge
define void @inplace_operation(ptr %arr, i32 %n) {
; CHECK-LABEL: @inplace_operation(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[UMAX:%.*]] = call i32 @llvm.umax.i32(i32 [[N:%.*]], i32 1)
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[I_NEXT:%.*]], [[LOOP]] ]
; CHECK-NEXT:    [[PTR:%.*]] = phi ptr [ [[ARR:%.*]], [[ENTRY]] ], [ [[PTR_NEXT:%.*]], [[LOOP]] ]
; CHECK-NEXT:    [[VAL:%.*]] = load i32, ptr [[PTR]], align 4
; CHECK-NEXT:    [[RESULT:%.*]] = mul i32 [[VAL]], 2
; CHECK-NEXT:    store i32 [[RESULT]], ptr [[PTR]], align 4
; CHECK-NEXT:    [[PTR_NEXT]] = getelementptr i32, ptr [[PTR]], i32 1
; CHECK-NEXT:    [[I_NEXT]] = add nuw i32 [[I]], 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp ne i32 [[I_NEXT]], [[UMAX]]
; CHECK-NEXT:    br i1 [[EXITCOND]], label [[LOOP]], label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %ptr = phi ptr [ %arr, %entry ], [ %ptr.next, %loop ]

  %val = load i32, ptr %ptr, align 4
  %result = mul i32 %val, 2
  store i32 %result, ptr %ptr, align 4

  %ptr.next = getelementptr i32, ptr %ptr, i32 1
  %i.next = add i32 %i, 1
  %cond = icmp ult i32 %i.next, %n
  br i1 %cond, label %loop, label %exit

exit:
  ret void
}
