# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2p -run-pass=early-ifcvt -aie-if-conv-critical-path-limit=5 %s -verify-machineinstrs -o - | FileCheck %s

--- |
  define void @test1(ptr nocapture writeonly %params_ptr, i32 %conv, i16 %0) {
  entry:
    switch i32 %conv, label %cond.false66 [
      i32 16, label %cond.end72
      i32 0, label %cond.end72
    ]

  cond.false66:                                     ; preds = %entry
    br label %cond.end72

  cond.end72:                                       ; preds = %cond.false66, %entry, %entry
    %cond73 = phi i16 [ 0, %entry ], [ %0, %cond.false66 ], [ 0, %entry ]
    store i16 %cond73, ptr %params_ptr, align 4
    ret void
  }

  define void @test2(ptr nocapture writeonly %params_ptr, i32 %conv, i16 %0) local_unnamed_addr {
  entry:
    switch i32 %conv, label %cond.false66 [
      i32 16, label %cond.end72
      i32 0, label %cond.false67
    ]

  cond.false66:                                     ; preds = %entry
    br label %cond.end72

  cond.false67:                                     ; preds = %entry
    br label %cond.end72

  cond.end72:                                       ; preds = %cond.false67, %cond.false66, %entry
    %cond73 = phi i16 [ 0, %entry ], [ %0, %cond.false66 ], [ 2, %cond.false67 ]
    store i16 %cond73, ptr %params_ptr, align 4
    ret void
  }

  define void @test3(ptr nocapture writeonly %params_ptr, i32 %conv, i16 %0) local_unnamed_addr {
  entry:
    switch i32 %conv, label %cond.false66 [
      i32 16, label %cond.end72
      i32 0, label %cond.false67
    ]

  cond.false66:                                     ; preds = %entry
    br label %cond.end72

  cond.false67:                                     ; preds = %entry
    %1 = add i16 %0, 3
    br label %cond.end72

  cond.end72:                                       ; preds = %cond.false67, %cond.false66, %entry
    %cond73 = phi i16 [ 0, %entry ], [ %0, %cond.false66 ], [ %1, %cond.false67 ]
    store i16 %cond73, ptr %params_ptr, align 4
    ret void
  }

  define void @test4(ptr nocapture writeonly %params_ptr, i32 %conv, i16 %0, i16 %1) local_unnamed_addr {
  entry:
    switch i32 %conv, label %cond.false66 [
      i32 16, label %cond.end72
      i32 0, label %cond.false67
    ]

  cond.false66:                                     ; preds = %entry
    %2 = shl i16 %0, 7
    %3 = add i16 %2, %1
    br label %cond.end72

  cond.false67:                                     ; preds = %entry
    %4 = shl i16 %0, 4
    %5 = add i16 %4, 48
    br label %cond.end72

  cond.end72:                                       ; preds = %cond.false67, %cond.false66, %entry
    %cond73 = phi i16 [ 0, %entry ], [ %3, %cond.false66 ], [ %5, %cond.false67 ]
    store i16 %cond73, ptr %params_ptr, align 4
    ret void
  }

  define void @test5(ptr nocapture writeonly %params_ptr, i32 %conv, i16 %0, i16 %1) local_unnamed_addr {
  entry:
    switch i32 %conv, label %cond.false66 [
      i32 16, label %cond.end72
      i32 0, label %cond.false67
    ]

  cond.false66:                                     ; preds = %entry
    %2 = shl i16 %0, 7
    %3 = add i16 %2, %1
    %4 = mul i16 %3, 10
    br label %cond.end72

  cond.false67:                                     ; preds = %entry
    %5 = shl i16 %0, 4
    %6 = add i16 %5, 48
    %7 = mul i16 %6, %1
    br label %cond.end72

  cond.end72:                                       ; preds = %cond.false67, %cond.false66, %entry
    %cond73 = phi i16 [ 0, %entry ], [ %4, %cond.false66 ], [ %7, %cond.false67 ]
    store i16 %cond73, ptr %params_ptr, align 4
    ret void
  }

  define void @test6_reject(ptr nocapture writeonly %params_ptr, i32 %conv, i16 %0, i16 %1) local_unnamed_addr {
  entry:
    switch i32 %conv, label %cond.false66 [
      i32 16, label %cond.end72
      i32 0, label %cond.false67
    ]

  cond.false66:                                     ; preds = %entry
    %2 = shl i16 %0, 7
    %3 = add i16 %2, %1
    %4 = mul i16 %3, 10
    %5 = add i16 %1, 10
    %6 = add i16 %5, %4
    br label %cond.end72

  cond.false67:                                     ; preds = %entry
    %7 = shl i16 %0, 4
    %8 = add i16 %7, 48
    %9 = mul i16 %1, %0
    %10 = mul i16 %9, %8
    br label %cond.end72

  cond.end72:                                       ; preds = %cond.false67, %cond.false66, %entry
    %cond73 = phi i16 [ 0, %entry ], [ %6, %cond.false66 ], [ %10, %cond.false67 ]
    store i16 %cond73, ptr %params_ptr, align 4
    ret void
  }

...
---
name:            test1
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: ep, preferred-register: '' }
  - { id: 1, class: er, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: er, preferred-register: '' }
  - { id: 4, class: gprregbank, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: er, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: _, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: _, preferred-register: '' }
  - { id: 11, class: _, preferred-register: '' }
  - { id: 12, class: _, preferred-register: '' }
  - { id: 13, class: _, preferred-register: '' }
  - { id: 14, class: er, preferred-register: '' }
  - { id: 15, class: _, preferred-register: '' }
  - { id: 16, class: er, preferred-register: '' }
  - { id: 17, class: _, preferred-register: '' }
  - { id: 18, class: gprregbank, preferred-register: '' }
  - { id: 19, class: er, preferred-register: '' }
liveins:         []
calleeSavedRegisters: [ '$lr', '$r8', '$r9', '$r10', '$r11', '$r12', '$r13',
                        '$r14', '$r15', '$p6', '$p7' ]
body:             |
  ; CHECK-LABEL: name: test1
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   liveins: $p0, $r0, $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:ep = COPY $p0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:er = COPY $r0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:er = COPY $r1
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 16
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
  ; CHECK-NEXT:   [[EQ:%[0-9]+]]:er = EQ [[COPY1]], [[MOV_RLC_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:mr27_select = COPY [[EQ]]
  ; CHECK-NEXT:   [[SEL_NEZ:%[0-9]+]]:er = SEL_NEZ [[MOV_RLC_imm11_pseudo1]], [[COPY2]], [[COPY3]]
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:mr27_select = COPY [[COPY1]]
  ; CHECK-NEXT:   [[SEL_EQZ:%[0-9]+]]:er = SEL_EQZ [[MOV_RLC_imm11_pseudo1]], [[SEL_NEZ]], [[COPY4]]
  ; CHECK-NEXT:   ST_s16_idx_imm [[SEL_EQZ]], [[COPY]], 0, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16) into %ir.params_ptr, align 4)
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.1.entry:
    successors: %bb.3(0x2aaaaaab), %bb.4(0x55555555)
    liveins: $p0, $r0, $r1

    %0:ep = COPY $p0
    %1:er = COPY $r0
    %3:er = COPY $r1
    %6:er = MOV_RLC_imm11_pseudo 16
    %19:er = MOV_RLC_imm11_pseudo 0
    PseudoJZ %1, %bb.3
    PseudoJ_jump_imm %bb.4

  bb.4.entry:
    successors: %bb.3(0x40000001), %bb.2(0x3fffffff)

    %16:er = EQ %1, %6
    PseudoJNZ %16, %bb.3
    PseudoJ_jump_imm %bb.2

  bb.2.cond.false66:
    successors: %bb.3(0x80000000)

  bb.3.cond.end72:
    %14:er = PHI %19, %bb.1, %19, %bb.4, %3, %bb.2
    ST_s16_idx_imm %14, %0, 0, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16) into %ir.params_ptr, align 4)
    PseudoRET implicit $lr

...
---
name:            test2
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: ep, preferred-register: '' }
  - { id: 1, class: er, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: er, preferred-register: '' }
  - { id: 4, class: gprregbank, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: er, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: _, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: _, preferred-register: '' }
  - { id: 11, class: _, preferred-register: '' }
  - { id: 12, class: _, preferred-register: '' }
  - { id: 13, class: _, preferred-register: '' }
  - { id: 14, class: _, preferred-register: '' }
  - { id: 15, class: er, preferred-register: '' }
  - { id: 16, class: _, preferred-register: '' }
  - { id: 17, class: er, preferred-register: '' }
  - { id: 18, class: _, preferred-register: '' }
  - { id: 19, class: gprregbank, preferred-register: '' }
  - { id: 20, class: er, preferred-register: '' }
  - { id: 21, class: er, preferred-register: '' }
liveins:         []
calleeSavedRegisters: [ '$lr', '$r8', '$r9', '$r10', '$r11', '$r12', '$r13',
                        '$r14', '$r15', '$p6', '$p7' ]
body:             |
  ; CHECK-LABEL: name: test2
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   liveins: $p0, $r0, $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:ep = COPY $p0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:er = COPY $r0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:er = COPY $r1
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 16
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo2:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 2
  ; CHECK-NEXT:   [[EQ:%[0-9]+]]:er = EQ [[COPY1]], [[MOV_RLC_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:mr27_select = COPY [[EQ]]
  ; CHECK-NEXT:   [[SEL_NEZ:%[0-9]+]]:er = SEL_NEZ [[MOV_RLC_imm11_pseudo1]], [[COPY2]], [[COPY3]]
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:mr27_select = COPY [[COPY1]]
  ; CHECK-NEXT:   [[SEL_EQZ:%[0-9]+]]:er = SEL_EQZ [[MOV_RLC_imm11_pseudo2]], [[SEL_NEZ]], [[COPY4]]
  ; CHECK-NEXT:   ST_s16_idx_imm [[SEL_EQZ]], [[COPY]], 0, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16) into %ir.params_ptr, align 4)
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.1.entry:
    successors: %bb.3(0x2aaaaaab), %bb.5(0x55555555)
    liveins: $p0, $r0, $r1

    %0:ep = COPY $p0
    %1:er = COPY $r0
    %3:er = COPY $r1
    %6:er = MOV_RLC_imm11_pseudo 16
    %21:er = MOV_RLC_imm11_pseudo 0
    %20:er = MOV_RLC_imm11_pseudo 2
    PseudoJZ %1, %bb.3
    PseudoJ_jump_imm %bb.5

  bb.5.entry:
    successors: %bb.4(0x40000001), %bb.2(0x3fffffff)

    %17:er = EQ %1, %6
    PseudoJNZ %17, %bb.4
    PseudoJ_jump_imm %bb.2

  bb.2.cond.false66:
    successors: %bb.4(0x80000000)

    PseudoJ_jump_imm %bb.4

  bb.3.cond.false67:
    successors: %bb.4(0x80000000)

  bb.4.cond.end72:
    %15:er = PHI %21, %bb.5, %3, %bb.2, %20, %bb.3
    ST_s16_idx_imm %15, %0, 0, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16) into %ir.params_ptr, align 4)
    PseudoRET implicit $lr

...
---
name:            test3
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: ep, preferred-register: '' }
  - { id: 1, class: er, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: er, preferred-register: '' }
  - { id: 4, class: gprregbank, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: er, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: _, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: _, preferred-register: '' }
  - { id: 11, class: _, preferred-register: '' }
  - { id: 12, class: _, preferred-register: '' }
  - { id: 13, class: _, preferred-register: '' }
  - { id: 14, class: _, preferred-register: '' }
  - { id: 15, class: _, preferred-register: '' }
  - { id: 16, class: er, preferred-register: '' }
  - { id: 17, class: _, preferred-register: '' }
  - { id: 18, class: _, preferred-register: '' }
  - { id: 19, class: er, preferred-register: '' }
  - { id: 20, class: _, preferred-register: '' }
  - { id: 21, class: er, preferred-register: '' }
  - { id: 22, class: _, preferred-register: '' }
  - { id: 23, class: gprregbank, preferred-register: '' }
  - { id: 24, class: er, preferred-register: '' }
  - { id: 25, class: gprregbank, preferred-register: '' }
liveins:         []
calleeSavedRegisters: [ '$lr', '$r8', '$r9', '$r10', '$r11', '$r12', '$r13',
                        '$r14', '$r15', '$p6', '$p7' ]
body:             |
  ; CHECK-LABEL: name: test3
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   liveins: $p0, $r0, $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:ep = COPY $p0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:er = COPY $r0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:er = COPY $r1
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 16
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
  ; CHECK-NEXT:   [[ADD_add_r_ri:%[0-9]+]]:er = ADD_add_r_ri [[COPY2]], 3, implicit-def dead $srcarry
  ; CHECK-NEXT:   [[EQ:%[0-9]+]]:er = EQ [[COPY1]], [[MOV_RLC_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:mr27_select = COPY [[EQ]]
  ; CHECK-NEXT:   [[SEL_NEZ:%[0-9]+]]:er = SEL_NEZ [[MOV_RLC_imm11_pseudo1]], [[COPY2]], [[COPY3]]
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:mr27_select = COPY [[COPY1]]
  ; CHECK-NEXT:   [[SEL_EQZ:%[0-9]+]]:er = SEL_EQZ [[ADD_add_r_ri]], [[SEL_NEZ]], [[COPY4]]
  ; CHECK-NEXT:   ST_s16_idx_imm [[SEL_EQZ]], [[COPY]], 0, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16) into %ir.params_ptr, align 4)
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.1.entry:
    successors: %bb.3(0x2aaaaaab), %bb.5(0x55555555)
    liveins: $p0, $r0, $r1

    %0:ep = COPY $p0
    %1:er = COPY $r0
    %3:er = COPY $r1
    %6:er = MOV_RLC_imm11_pseudo 16
    %24:er = MOV_RLC_imm11_pseudo 0
    PseudoJZ %1, %bb.3
    PseudoJ_jump_imm %bb.5

  bb.5.entry:
    successors: %bb.4(0x40000001), %bb.2(0x3fffffff)

    %21:er = EQ %1, %6
    PseudoJNZ %21, %bb.4
    PseudoJ_jump_imm %bb.2

  bb.2.cond.false66:
    successors: %bb.4(0x80000000)

    PseudoJ_jump_imm %bb.4

  bb.3.cond.false67:
    successors: %bb.4(0x80000000)

    %19:er = ADD_add_r_ri %3, 3, implicit-def dead $srcarry

  bb.4.cond.end72:
    %16:er = PHI %24, %bb.5, %3, %bb.2, %19, %bb.3
    ST_s16_idx_imm %16, %0, 0, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16) into %ir.params_ptr, align 4)
    PseudoRET implicit $lr

...
---
name:            test4
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: ep, preferred-register: '' }
  - { id: 1, class: er, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: er, preferred-register: '' }
  - { id: 5, class: er, preferred-register: '' }
  - { id: 6, class: gprregbank, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: er, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: _, preferred-register: '' }
  - { id: 11, class: _, preferred-register: '' }
  - { id: 12, class: _, preferred-register: '' }
  - { id: 13, class: _, preferred-register: '' }
  - { id: 14, class: _, preferred-register: '' }
  - { id: 15, class: _, preferred-register: '' }
  - { id: 16, class: _, preferred-register: '' }
  - { id: 17, class: _, preferred-register: '' }
  - { id: 18, class: _, preferred-register: '' }
  - { id: 19, class: _, preferred-register: '' }
  - { id: 20, class: _, preferred-register: '' }
  - { id: 21, class: _, preferred-register: '' }
  - { id: 22, class: _, preferred-register: '' }
  - { id: 23, class: er, preferred-register: '' }
  - { id: 24, class: _, preferred-register: '' }
  - { id: 25, class: _, preferred-register: '' }
  - { id: 26, class: er, preferred-register: '' }
  - { id: 27, class: _, preferred-register: '' }
  - { id: 28, class: er, preferred-register: '' }
  - { id: 29, class: _, preferred-register: '' }
  - { id: 30, class: _, preferred-register: '' }
  - { id: 31, class: _, preferred-register: '' }
  - { id: 32, class: er, preferred-register: '' }
  - { id: 33, class: _, preferred-register: '' }
  - { id: 34, class: er, preferred-register: '' }
  - { id: 35, class: _, preferred-register: '' }
  - { id: 36, class: _, preferred-register: '' }
  - { id: 37, class: er, preferred-register: '' }
  - { id: 38, class: _, preferred-register: '' }
  - { id: 39, class: gprregbank, preferred-register: '' }
  - { id: 40, class: er, preferred-register: '' }
  - { id: 41, class: er, preferred-register: '' }
  - { id: 42, class: gprregbank, preferred-register: '' }
  - { id: 43, class: er, preferred-register: '' }
liveins:         []
calleeSavedRegisters: [ '$lr', '$r8', '$r9', '$r10', '$r11', '$r12', '$r13',
                        '$r14', '$r15', '$p6', '$p7' ]
body:             |
  ; CHECK-LABEL: name: test4
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   liveins: $p0, $r0, $r1, $r2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:ep = COPY $p0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:er = COPY $r0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:er = COPY $r1
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:er = COPY $r2
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 16
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 4
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo2:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 7
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo3:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
  ; CHECK-NEXT:   [[LSHL:%[0-9]+]]:er = LSHL [[COPY2]], [[MOV_RLC_imm11_pseudo1]]
  ; CHECK-NEXT:   [[ADD_add_r_ri:%[0-9]+]]:er = ADD_add_r_ri [[LSHL]], 48, implicit-def dead $srcarry
  ; CHECK-NEXT:   [[EQ:%[0-9]+]]:er = EQ [[COPY1]], [[MOV_RLC_imm11_pseudo]]
  ; CHECK-NEXT:   [[LSHL1:%[0-9]+]]:er = LSHL [[COPY2]], [[MOV_RLC_imm11_pseudo2]]
  ; CHECK-NEXT:   [[ADD_alu_r_rr:%[0-9]+]]:er = ADD_alu_r_rr [[LSHL1]], [[COPY3]], implicit-def dead $srcarry
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:mr27_select = COPY [[EQ]]
  ; CHECK-NEXT:   [[SEL_NEZ:%[0-9]+]]:er = SEL_NEZ [[MOV_RLC_imm11_pseudo3]], [[ADD_alu_r_rr]], [[COPY4]]
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:mr27_select = COPY [[COPY1]]
  ; CHECK-NEXT:   [[SEL_EQZ:%[0-9]+]]:er = SEL_EQZ [[ADD_add_r_ri]], [[SEL_NEZ]], [[COPY5]]
  ; CHECK-NEXT:   ST_s16_idx_imm [[SEL_EQZ]], [[COPY]], 0, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16) into %ir.params_ptr, align 4)
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.1.entry:
    successors: %bb.3(0x2aaaaaab), %bb.5(0x55555555)
    liveins: $p0, $r0, $r1, $r2

    %0:ep = COPY $p0
    %1:er = COPY $r0
    %4:er = COPY $r1
    %5:er = COPY $r2
    %8:er = MOV_RLC_imm11_pseudo 16
    %43:er = MOV_RLC_imm11_pseudo 4
    %41:er = MOV_RLC_imm11_pseudo 7
    %40:er = MOV_RLC_imm11_pseudo 0
    PseudoJZ %1, %bb.3
    PseudoJ_jump_imm %bb.5

  bb.5.entry:
    successors: %bb.4(0x40000001), %bb.2(0x3fffffff)

    %37:er = EQ %1, %8
    PseudoJNZ %37, %bb.4
    PseudoJ_jump_imm %bb.2

  bb.2.cond.false66:
    successors: %bb.4(0x80000000)

    %34:er = LSHL %4, %41
    %32:er = ADD_alu_r_rr %34, %5, implicit-def dead $srcarry
    PseudoJ_jump_imm %bb.4

  bb.3.cond.false67:
    successors: %bb.4(0x80000000)

    %28:er = LSHL %4, %43
    %26:er = ADD_add_r_ri %28, 48, implicit-def dead $srcarry

  bb.4.cond.end72:
    %23:er = PHI %40, %bb.5, %32, %bb.2, %26, %bb.3
    ST_s16_idx_imm %23, %0, 0, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16) into %ir.params_ptr, align 4)
    PseudoRET implicit $lr

...
---
name:            test5
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: ep, preferred-register: '' }
  - { id: 1, class: er, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: er, preferred-register: '' }
  - { id: 5, class: er, preferred-register: '' }
  - { id: 6, class: gprregbank, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: er, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: _, preferred-register: '' }
  - { id: 11, class: _, preferred-register: '' }
  - { id: 12, class: _, preferred-register: '' }
  - { id: 13, class: _, preferred-register: '' }
  - { id: 14, class: _, preferred-register: '' }
  - { id: 15, class: _, preferred-register: '' }
  - { id: 16, class: _, preferred-register: '' }
  - { id: 17, class: _, preferred-register: '' }
  - { id: 18, class: _, preferred-register: '' }
  - { id: 19, class: _, preferred-register: '' }
  - { id: 20, class: _, preferred-register: '' }
  - { id: 21, class: _, preferred-register: '' }
  - { id: 22, class: _, preferred-register: '' }
  - { id: 23, class: er, preferred-register: '' }
  - { id: 24, class: _, preferred-register: '' }
  - { id: 25, class: _, preferred-register: '' }
  - { id: 26, class: er, preferred-register: '' }
  - { id: 27, class: _, preferred-register: '' }
  - { id: 28, class: er, preferred-register: '' }
  - { id: 29, class: _, preferred-register: '' }
  - { id: 30, class: _, preferred-register: '' }
  - { id: 31, class: _, preferred-register: '' }
  - { id: 32, class: er, preferred-register: '' }
  - { id: 33, class: _, preferred-register: '' }
  - { id: 34, class: er, preferred-register: '' }
  - { id: 35, class: _, preferred-register: '' }
  - { id: 36, class: _, preferred-register: '' }
  - { id: 37, class: er, preferred-register: '' }
  - { id: 38, class: _, preferred-register: '' }
  - { id: 39, class: gprregbank, preferred-register: '' }
  - { id: 40, class: er, preferred-register: '' }
  - { id: 41, class: er, preferred-register: '' }
  - { id: 42, class: gprregbank, preferred-register: '' }
  - { id: 43, class: er, preferred-register: '' }
liveins:         []
calleeSavedRegisters: [ '$lr', '$r8', '$r9', '$r10', '$r11', '$r12', '$r13',
                        '$r14', '$r15', '$p6', '$p7' ]
body:             |
  ; CHECK-LABEL: name: test5
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   liveins: $p0, $r0, $r1, $r2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:ep = COPY $p0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:er = COPY $r0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:er = COPY $r1
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:er = COPY $r2
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 16
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 4
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo2:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 7
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo3:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
  ; CHECK-NEXT:   [[LSHL:%[0-9]+]]:er = LSHL [[COPY2]], [[MOV_RLC_imm11_pseudo1]]
  ; CHECK-NEXT:   [[ADD_add_r_ri:%[0-9]+]]:er = ADD_add_r_ri [[LSHL]], 48, implicit-def dead $srcarry
  ; CHECK-NEXT:   [[EQ:%[0-9]+]]:er = EQ [[COPY1]], [[MOV_RLC_imm11_pseudo]]
  ; CHECK-NEXT:   [[LSHL1:%[0-9]+]]:er = LSHL [[COPY2]], [[MOV_RLC_imm11_pseudo2]]
  ; CHECK-NEXT:   [[ADD_alu_r_rr:%[0-9]+]]:er = ADD_alu_r_rr [[LSHL1]], [[COPY3]], implicit-def dead $srcarry
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:mr27_select = COPY [[EQ]]
  ; CHECK-NEXT:   [[SEL_NEZ:%[0-9]+]]:er = SEL_NEZ [[MOV_RLC_imm11_pseudo3]], [[ADD_alu_r_rr]], [[COPY4]]
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:mr27_select = COPY [[COPY1]]
  ; CHECK-NEXT:   [[SEL_EQZ:%[0-9]+]]:er = SEL_EQZ [[ADD_add_r_ri]], [[SEL_NEZ]], [[COPY5]]
  ; CHECK-NEXT:   ST_s16_idx_imm [[SEL_EQZ]], [[COPY]], 0, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16) into %ir.params_ptr, align 4)
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.1.entry:
    successors: %bb.3(0x2aaaaaab), %bb.5(0x55555555)
    liveins: $p0, $r0, $r1, $r2

    %0:ep = COPY $p0
    %1:er = COPY $r0
    %4:er = COPY $r1
    %5:er = COPY $r2
    %8:er = MOV_RLC_imm11_pseudo 16
    %43:er = MOV_RLC_imm11_pseudo 4
    %41:er = MOV_RLC_imm11_pseudo 7
    %40:er = MOV_RLC_imm11_pseudo 0
    PseudoJZ %1, %bb.3
    PseudoJ_jump_imm %bb.5

  bb.5.entry:
    successors: %bb.4(0x40000001), %bb.2(0x3fffffff)

    %37:er = EQ %1, %8
    PseudoJNZ %37, %bb.4
    PseudoJ_jump_imm %bb.2

  bb.2.cond.false66:
    successors: %bb.4(0x80000000)

    %34:er = LSHL %4, %41
    %32:er = ADD_alu_r_rr %34, %5, implicit-def dead $srcarry
    PseudoJ_jump_imm %bb.4

  bb.3.cond.false67:
    successors: %bb.4(0x80000000)

    %28:er = LSHL %4, %43
    %26:er = ADD_add_r_ri %28, 48, implicit-def dead $srcarry

  bb.4.cond.end72:
    %23:er = PHI %40, %bb.5, %32, %bb.2, %26, %bb.3
    ST_s16_idx_imm %23, %0, 0, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16) into %ir.params_ptr, align 4)
    PseudoRET implicit $lr

...
---
name:            test6_reject
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: ep, preferred-register: '' }
  - { id: 1, class: er, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: er, preferred-register: '' }
  - { id: 5, class: er, preferred-register: '' }
  - { id: 6, class: gprregbank, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: er, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: _, preferred-register: '' }
  - { id: 11, class: _, preferred-register: '' }
  - { id: 12, class: _, preferred-register: '' }
  - { id: 13, class: _, preferred-register: '' }
  - { id: 14, class: _, preferred-register: '' }
  - { id: 15, class: _, preferred-register: '' }
  - { id: 16, class: _, preferred-register: '' }
  - { id: 17, class: _, preferred-register: '' }
  - { id: 18, class: _, preferred-register: '' }
  - { id: 19, class: _, preferred-register: '' }
  - { id: 20, class: _, preferred-register: '' }
  - { id: 21, class: _, preferred-register: '' }
  - { id: 22, class: _, preferred-register: '' }
  - { id: 23, class: _, preferred-register: '' }
  - { id: 24, class: _, preferred-register: '' }
  - { id: 25, class: _, preferred-register: '' }
  - { id: 26, class: _, preferred-register: '' }
  - { id: 27, class: _, preferred-register: '' }
  - { id: 28, class: _, preferred-register: '' }
  - { id: 29, class: _, preferred-register: '' }
  - { id: 30, class: er, preferred-register: '' }
  - { id: 31, class: _, preferred-register: '' }
  - { id: 32, class: _, preferred-register: '' }
  - { id: 33, class: er, preferred-register: '' }
  - { id: 34, class: _, preferred-register: '' }
  - { id: 35, class: _, preferred-register: '' }
  - { id: 36, class: er, preferred-register: '' }
  - { id: 37, class: _, preferred-register: '' }
  - { id: 38, class: _, preferred-register: '' }
  - { id: 39, class: er, preferred-register: '' }
  - { id: 40, class: er, preferred-register: '' }
  - { id: 41, class: _, preferred-register: '' }
  - { id: 42, class: _, preferred-register: '' }
  - { id: 43, class: _, preferred-register: '' }
  - { id: 44, class: er, preferred-register: '' }
  - { id: 45, class: _, preferred-register: '' }
  - { id: 46, class: _, preferred-register: '' }
  - { id: 47, class: er, preferred-register: '' }
  - { id: 48, class: _, preferred-register: '' }
  - { id: 49, class: er, preferred-register: '' }
  - { id: 50, class: _, preferred-register: '' }
  - { id: 51, class: er, preferred-register: '' }
  - { id: 52, class: _, preferred-register: '' }
  - { id: 53, class: er, preferred-register: '' }
  - { id: 54, class: _, preferred-register: '' }
  - { id: 55, class: _, preferred-register: '' }
  - { id: 56, class: er, preferred-register: '' }
  - { id: 57, class: _, preferred-register: '' }
  - { id: 58, class: gprregbank, preferred-register: '' }
  - { id: 59, class: er, preferred-register: '' }
  - { id: 60, class: er, preferred-register: '' }
  - { id: 61, class: er, preferred-register: '' }
  - { id: 62, class: gprregbank, preferred-register: '' }
  - { id: 63, class: er, preferred-register: '' }
liveins:         []
calleeSavedRegisters: [ '$lr', '$r8', '$r9', '$r10', '$r11', '$r12', '$r13',
                        '$r14', '$r15', '$p6', '$p7' ]
body:             |
  ; CHECK-LABEL: name: test6_reject
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.3(0x2aaaaaab), %bb.1(0x55555555)
  ; CHECK-NEXT:   liveins: $p0, $r0, $r1, $r2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:ep = COPY $p0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:er = COPY $r0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:er = COPY $r1
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:er = COPY $r2
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 16
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 4
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo2:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 7
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo3:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 10
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo4:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
  ; CHECK-NEXT:   PseudoJZ [[COPY1]], %bb.3
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.entry:
  ; CHECK-NEXT:   successors: %bb.4(0x40000001), %bb.2(0x3fffffff)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[EQ:%[0-9]+]]:er = EQ [[COPY1]], [[MOV_RLC_imm11_pseudo]]
  ; CHECK-NEXT:   PseudoJNZ [[EQ]], %bb.4
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.cond.false66:
  ; CHECK-NEXT:   successors: %bb.4(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LSHL:%[0-9]+]]:er = LSHL [[COPY2]], [[MOV_RLC_imm11_pseudo2]]
  ; CHECK-NEXT:   [[ADD_alu_r_rr:%[0-9]+]]:er = ADD_alu_r_rr [[LSHL]], [[COPY3]], implicit-def dead $srcarry
  ; CHECK-NEXT:   [[MUL:%[0-9]+]]:er = MUL [[ADD_alu_r_rr]], [[MOV_RLC_imm11_pseudo3]]
  ; CHECK-NEXT:   [[ADD_alu_r_rr1:%[0-9]+]]:er = ADD_alu_r_rr [[COPY3]], [[MUL]], implicit-def dead $srcarry
  ; CHECK-NEXT:   [[ADD_add_r_ri:%[0-9]+]]:er = ADD_add_r_ri [[ADD_alu_r_rr1]], 10, implicit-def dead $srcarry
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.cond.false67:
  ; CHECK-NEXT:   successors: %bb.4(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LSHL1:%[0-9]+]]:er = LSHL [[COPY2]], [[MOV_RLC_imm11_pseudo1]]
  ; CHECK-NEXT:   [[ADD_add_r_ri1:%[0-9]+]]:er = ADD_add_r_ri [[LSHL1]], 48, implicit-def dead $srcarry
  ; CHECK-NEXT:   [[MUL1:%[0-9]+]]:er = MUL [[COPY3]], [[COPY2]]
  ; CHECK-NEXT:   [[MUL2:%[0-9]+]]:er = MUL [[MUL1]], [[ADD_add_r_ri1]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4.cond.end72:
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:er = PHI [[MOV_RLC_imm11_pseudo4]], %bb.1, [[ADD_add_r_ri]], %bb.2, [[MUL2]], %bb.3
  ; CHECK-NEXT:   ST_s16_idx_imm [[PHI]], [[COPY]], 0, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16) into %ir.params_ptr, align 4)
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.1.entry:
    successors: %bb.3(0x2aaaaaab), %bb.5(0x55555555)
    liveins: $p0, $r0, $r1, $r2

    %0:ep = COPY $p0
    %1:er = COPY $r0
    %4:er = COPY $r1
    %5:er = COPY $r2
    %8:er = MOV_RLC_imm11_pseudo 16
    %63:er = MOV_RLC_imm11_pseudo 4
    %61:er = MOV_RLC_imm11_pseudo 7
    %60:er = MOV_RLC_imm11_pseudo 10
    %59:er = MOV_RLC_imm11_pseudo 0
    PseudoJZ %1, %bb.3
    PseudoJ_jump_imm %bb.5

  bb.5.entry:
    successors: %bb.4(0x40000001), %bb.2(0x3fffffff)

    %56:er = EQ %1, %8
    PseudoJNZ %56, %bb.4
    PseudoJ_jump_imm %bb.2

  bb.2.cond.false66:
    successors: %bb.4(0x80000000)

    %53:er = LSHL %4, %61
    %51:er = ADD_alu_r_rr %53, %5, implicit-def dead $srcarry
    %49:er = MUL %51, %60
    %47:er = ADD_alu_r_rr %5, %49, implicit-def dead $srcarry
    %44:er = ADD_add_r_ri %47, 10, implicit-def dead $srcarry
    PseudoJ_jump_imm %bb.4

  bb.3.cond.false67:
    successors: %bb.4(0x80000000)

    %40:er = LSHL %4, %63
    %39:er = ADD_add_r_ri %40, 48, implicit-def dead $srcarry
    %36:er = MUL %5, %4
    %33:er = MUL %36, %39

  bb.4.cond.end72:
    %30:er = PHI %59, %bb.5, %44, %bb.2, %33, %bb.3
    ST_s16_idx_imm %30, %0, 0, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16) into %ir.params_ptr, align 4)
    PseudoRET implicit $lr

...





