# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2ps -run-pass=early-ifcvt -aie-if-conv-critical-path-limit=5 %s -verify-machineinstrs -o - | FileCheck %s

--- |
  define void @test1(ptr nocapture writeonly %params_ptr, i32 %conv, i16 %0) {
  entry:
    switch i32 %conv, label %cond.false66 [
      i32 16, label %cond.end72
      i32 0, label %cond.end72
    ]

  cond.false66:                                     ; preds = %entry
    br label %cond.end72

  cond.end72:                                       ; preds = %cond.false66, %entry, %entry
    %cond73 = phi i16 [ 0, %entry ], [ %0, %cond.false66 ], [ 0, %entry ]
    store i16 %cond73, ptr %params_ptr, align 4
    ret void
  }

  define void @test2(ptr nocapture writeonly %params_ptr, i32 %conv, i16 %0) local_unnamed_addr {
  entry:
    switch i32 %conv, label %cond.false66 [
      i32 16, label %cond.end72
      i32 0, label %cond.false67
    ]

  cond.false66:                                     ; preds = %entry
    br label %cond.end72

  cond.false67:                                     ; preds = %entry
    br label %cond.end72

  cond.end72:                                       ; preds = %cond.false67, %cond.false66, %entry
    %cond73 = phi i16 [ 0, %entry ], [ %0, %cond.false66 ], [ 2, %cond.false67 ]
    store i16 %cond73, ptr %params_ptr, align 4
    ret void
  }

  define void @test3_reject(ptr nocapture writeonly %params_ptr, i32 %conv, i16 %0, i16 %1) local_unnamed_addr {
  entry:
    switch i32 %conv, label %cond.false66 [
      i32 16, label %cond.end72
      i32 0, label %cond.false67
    ]

  cond.false66:                                     ; preds = %entry
    %2 = shl i16 %0, 7
    %3 = add i16 %2, %1
    %4 = mul i16 %3, 10
    %5 = add i16 %1, 10
    %6 = add i16 %5, %4
    br label %cond.end72

  cond.false67:                                     ; preds = %entry
    %7 = shl i16 %0, 4
    %8 = add i16 %7, 48
    %9 = mul i16 %1, %0
    %10 = mul i16 %9, %8
    br label %cond.end72

  cond.end72:                                       ; preds = %cond.false67, %cond.false66, %entry
    %cond73 = phi i16 [ 0, %entry ], [ %6, %cond.false66 ], [ %10, %cond.false67 ]
    store i16 %cond73, ptr %params_ptr, align 4
    ret void
  }

...
---
name:            test1
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: test1
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   liveins: $p0, $r0, $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:ep = COPY $p0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:mrx = COPY $r0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:mrs = COPY $r1
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mry = MOV_RLC_imm11_pseudo 16
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:mrs = MOV_RLC_imm11_pseudo 0
  ; CHECK-NEXT:   [[EQ:%[0-9]+]]:mrx = EQ [[COPY1]], [[MOV_RLC_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:mr27_select = COPY [[EQ]]
  ; CHECK-NEXT:   [[SEL_NEZ:%[0-9]+]]:mrs = SEL_NEZ [[MOV_RLC_imm11_pseudo1]], [[COPY2]], [[COPY3]]
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:mr27_select = COPY [[COPY1]]
  ; CHECK-NEXT:   [[SEL_EQZ:%[0-9]+]]:mrs = SEL_EQZ [[MOV_RLC_imm11_pseudo1]], [[SEL_NEZ]], [[COPY4]]
  ; CHECK-NEXT:   ST_s16_idx_imm [[SEL_EQZ]], [[COPY]], 0, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16) into %ir.params_ptr, align 4)
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.1.entry:
    successors: %bb.3(0x2aaaaaab), %bb.4(0x55555555)
    liveins: $p0, $r0, $r1

    %0:ep = COPY $p0
    %1:mrx = COPY $r0
    %3:mrs = COPY $r1
    %6:mry = MOV_RLC_imm11_pseudo 16
    %19:mrs = MOV_RLC_imm11_pseudo 0
    PseudoJZ %1, %bb.3
    PseudoJ_jump_imm %bb.4

  bb.4.entry:
    successors: %bb.3(0x40000001), %bb.2(0x3fffffff)

    %16:mrx = EQ %1, %6
    PseudoJNZ %16, %bb.3
    PseudoJ_jump_imm %bb.2

  bb.2.cond.false66:
    successors: %bb.3(0x80000000)

  bb.3.cond.end72:
    %14:mrs = PHI %19, %bb.1, %19, %bb.4, %3, %bb.2
    ST_s16_idx_imm %14, %0, 0, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16) into %ir.params_ptr, align 4)
    PseudoRET implicit $lr

...
---
name:            test2
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
failsVerification: false
tracksDebugUserValues: false
body:             |
  ; CHECK-LABEL: name: test2
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   liveins: $p0, $r0, $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:ep = COPY $p0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:mrx = COPY $r0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:mrs = COPY $r1
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mry = MOV_RLC_imm11_pseudo 16
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:mrs = MOV_RLC_imm11_pseudo 0
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo2:%[0-9]+]]:mrs = MOV_RLC_imm11_pseudo 2
  ; CHECK-NEXT:   [[EQ:%[0-9]+]]:mrx = EQ [[COPY1]], [[MOV_RLC_imm11_pseudo]]
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:mr27_select = COPY [[EQ]]
  ; CHECK-NEXT:   [[SEL_NEZ:%[0-9]+]]:mrs = SEL_NEZ [[MOV_RLC_imm11_pseudo1]], [[COPY2]], [[COPY3]]
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:mr27_select = COPY [[COPY1]]
  ; CHECK-NEXT:   [[SEL_EQZ:%[0-9]+]]:mrs = SEL_EQZ [[MOV_RLC_imm11_pseudo2]], [[SEL_NEZ]], [[COPY4]]
  ; CHECK-NEXT:   ST_s16_idx_imm [[SEL_EQZ]], [[COPY]], 0, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16) into %ir.params_ptr, align 4)
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.1.entry:
    successors: %bb.3(0x2aaaaaab), %bb.5(0x55555555)
    liveins: $p0, $r0, $r1

    %0:ep = COPY $p0
    %1:mrx = COPY $r0
    %3:mrs = COPY $r1
    %6:mry = MOV_RLC_imm11_pseudo 16
    %21:mrs = MOV_RLC_imm11_pseudo 0
    %20:mrs = MOV_RLC_imm11_pseudo 2
    PseudoJZ %1, %bb.3
    PseudoJ_jump_imm %bb.5

  bb.5.entry:
    successors: %bb.4(0x40000001), %bb.2(0x3fffffff)

    %17:mrx = EQ %1, %6
    PseudoJNZ %17, %bb.4
    PseudoJ_jump_imm %bb.2

  bb.2.cond.false66:
    successors: %bb.4(0x80000000)

    PseudoJ_jump_imm %bb.4

  bb.3.cond.false67:
    successors: %bb.4(0x80000000)

  bb.4.cond.end72:
    %15:mrs = PHI %21, %bb.5, %3, %bb.2, %20, %bb.3
    ST_s16_idx_imm %15, %0, 0, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16) into %ir.params_ptr, align 4)
    PseudoRET implicit $lr

...
---
name:            test3_reject
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
failsVerification: false
tracksDebugUserValues: false
body:             |
  ; CHECK-LABEL: name: test3_reject
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.3(0x2aaaaaab), %bb.1(0x55555555)
  ; CHECK-NEXT:   liveins: $p0, $r0, $r1, $r2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:ep = COPY $p0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:mrx = COPY $r0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:mrx = COPY $r1
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:mry = COPY $r2
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo:%[0-9]+]]:mry = MOV_RLC_imm11_pseudo 16
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo1:%[0-9]+]]:mry = MOV_RLC_imm11_pseudo 4
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo2:%[0-9]+]]:mry = MOV_RLC_imm11_pseudo 7
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo3:%[0-9]+]]:mry = MOV_RLC_imm11_pseudo 10
  ; CHECK-NEXT:   [[MOV_RLC_imm11_pseudo4:%[0-9]+]]:mrs = MOV_RLC_imm11_pseudo 0
  ; CHECK-NEXT:   PseudoJZ [[COPY1]], %bb.3
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.entry:
  ; CHECK-NEXT:   successors: %bb.4(0x40000001), %bb.2(0x3fffffff)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[EQ:%[0-9]+]]:mrx = EQ [[COPY1]], [[MOV_RLC_imm11_pseudo]]
  ; CHECK-NEXT:   PseudoJNZ [[EQ]], %bb.4
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.cond.false66:
  ; CHECK-NEXT:   successors: %bb.4(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LSHL:%[0-9]+]]:mrx = LSHL [[COPY2]], [[MOV_RLC_imm11_pseudo2]]
  ; CHECK-NEXT:   [[ADD_alu_r_rr:%[0-9]+]]:mrx = ADD_alu_r_rr [[LSHL]], [[COPY3]], implicit-def dead $srcarry
  ; CHECK-NEXT:   [[MUL:%[0-9]+]]:mrx = MUL [[ADD_alu_r_rr]], [[MOV_RLC_imm11_pseudo3]]
  ; CHECK-NEXT:   [[ADD_alu_r_rr1:%[0-9]+]]:mrx = ADD_alu_r_rr [[COPY3]], [[MUL]], implicit-def dead $srcarry
  ; CHECK-NEXT:   [[ADD_add_r_ri:%[0-9]+]]:mrs = ADD_add_r_ri [[ADD_alu_r_rr1]], 10, implicit-def dead $srcarry
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.cond.false67:
  ; CHECK-NEXT:   successors: %bb.4(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LSHL1:%[0-9]+]]:mrx = LSHL [[COPY2]], [[MOV_RLC_imm11_pseudo1]]
  ; CHECK-NEXT:   [[ADD_add_r_ri1:%[0-9]+]]:mrx = ADD_add_r_ri [[LSHL1]], 48, implicit-def dead $srcarry
  ; CHECK-NEXT:   [[MUL1:%[0-9]+]]:mrx = MUL [[COPY3]], [[COPY2]]
  ; CHECK-NEXT:   [[MUL2:%[0-9]+]]:mrs = MUL [[MUL1]], [[ADD_add_r_ri1]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4.cond.end72:
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:mrs = PHI [[MOV_RLC_imm11_pseudo4]], %bb.1, [[ADD_add_r_ri]], %bb.2, [[MUL2]], %bb.3
  ; CHECK-NEXT:   ST_s16_idx_imm [[PHI]], [[COPY]], 0, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16) into %ir.params_ptr, align 4)
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.1.entry:
    successors: %bb.3(0x2aaaaaab), %bb.5(0x55555555)
    liveins: $p0, $r0, $r1, $r2

    %0:ep = COPY $p0
    %1:mrx = COPY $r0
    %4:mrx = COPY $r1
    %5:mry = COPY $r2
    %8:mry = MOV_RLC_imm11_pseudo 16
    %63:mry = MOV_RLC_imm11_pseudo 4
    %61:mry = MOV_RLC_imm11_pseudo 7
    %60:mry = MOV_RLC_imm11_pseudo 10
    %59:mrs = MOV_RLC_imm11_pseudo 0
    PseudoJZ %1, %bb.3
    PseudoJ_jump_imm %bb.5

  bb.5.entry:
    successors: %bb.4(0x40000001), %bb.2(0x3fffffff)

    %56:mrx = EQ %1, %8
    PseudoJNZ %56, %bb.4
    PseudoJ_jump_imm %bb.2

  bb.2.cond.false66:
    successors: %bb.4(0x80000000)

    %53:mrx = LSHL %4, %61
    %51:mrx = ADD_alu_r_rr %53, %5, implicit-def dead $srcarry
    %49:mrx = MUL %51, %60
    %47:mrx = ADD_alu_r_rr %5, %49, implicit-def dead $srcarry
    %44:mrs = ADD_add_r_ri %47, 10, implicit-def dead $srcarry
    PseudoJ_jump_imm %bb.4

  bb.3.cond.false67:
    successors: %bb.4(0x80000000)

    %40:mrx = LSHL %4, %63
    %39:mrx = ADD_add_r_ri %40, 48, implicit-def dead $srcarry
    %36:mrx = MUL %5, %4
    %33:mrs = MUL %36, %39

  bb.4.cond.end72:
    %30:mrs = PHI %59, %bb.5, %44, %bb.2, %33, %bb.3
    ST_s16_idx_imm %30, %0, 0, implicit-def $pe2_ads, implicit $pe2_ads :: (store (s16) into %ir.params_ptr, align 4)
    PseudoRET implicit $lr

...
