; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
;
; RUN: opt -S -passes=instcombine -mtriple=aie2p %s | FileCheck %s

; Baseline test for the upcoming InstCombine fold of
; @llvm.aie2p.vextract.broadcast128.I512 with a constant lane index. See the
; aie2ps companion test for the full description; the same fold (added in the
; next commit) applies here through the AIE2P TTI hook.

declare <16 x i32> @llvm.aie2p.vextract.broadcast128.I512(<16 x i32>, i32)

; Constant idx 0 -- should fold to shufflevector picking lanes 0..3 of %v.
define <4 x i32> @test_vextbcst128_const_idx0(<16 x i32> %v) {
; CHECK-LABEL: @test_vextbcst128_const_idx0(
; CHECK-NEXT:    [[BCST:%.*]] = call <16 x i32> @llvm.aie2p.vextract.broadcast128.I512(<16 x i32> [[V:%.*]], i32 0)
; CHECK-NEXT:    [[R:%.*]] = shufflevector <16 x i32> [[BCST]], <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; CHECK-NEXT:    ret <4 x i32> [[R]]
;
  %bcst = call <16 x i32> @llvm.aie2p.vextract.broadcast128.I512(<16 x i32> %v, i32 0)
  %r = shufflevector <16 x i32> %bcst, <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  ret <4 x i32> %r
}

; Constant idx 2 -- should fold to shufflevector picking lanes 8..11 of %v.
define <4 x i32> @test_vextbcst128_const_idx2(<16 x i32> %v) {
; CHECK-LABEL: @test_vextbcst128_const_idx2(
; CHECK-NEXT:    [[BCST:%.*]] = call <16 x i32> @llvm.aie2p.vextract.broadcast128.I512(<16 x i32> [[V:%.*]], i32 2)
; CHECK-NEXT:    [[R:%.*]] = shufflevector <16 x i32> [[BCST]], <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; CHECK-NEXT:    ret <4 x i32> [[R]]
;
  %bcst = call <16 x i32> @llvm.aie2p.vextract.broadcast128.I512(<16 x i32> %v, i32 2)
  %r = shufflevector <16 x i32> %bcst, <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  ret <4 x i32> %r
}

; Constant idx 3 -- should fold to shufflevector picking lanes 12..15 of %v.
define <4 x i32> @test_vextbcst128_const_idx3(<16 x i32> %v) {
; CHECK-LABEL: @test_vextbcst128_const_idx3(
; CHECK-NEXT:    [[BCST:%.*]] = call <16 x i32> @llvm.aie2p.vextract.broadcast128.I512(<16 x i32> [[V:%.*]], i32 3)
; CHECK-NEXT:    [[R:%.*]] = shufflevector <16 x i32> [[BCST]], <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; CHECK-NEXT:    ret <4 x i32> [[R]]
;
  %bcst = call <16 x i32> @llvm.aie2p.vextract.broadcast128.I512(<16 x i32> %v, i32 3)
  %r = shufflevector <16 x i32> %bcst, <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  ret <4 x i32> %r
}

; Runtime idx -- intrinsic must NOT fold (no constant lane known).
define <4 x i32> @test_vextbcst128_runtime_idx(<16 x i32> %v, i32 %idx) {
; CHECK-LABEL: @test_vextbcst128_runtime_idx(
; CHECK-NEXT:    [[BCST:%.*]] = call <16 x i32> @llvm.aie2p.vextract.broadcast128.I512(<16 x i32> [[V:%.*]], i32 [[IDX:%.*]])
; CHECK-NEXT:    [[R:%.*]] = shufflevector <16 x i32> [[BCST]], <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; CHECK-NEXT:    ret <4 x i32> [[R]]
;
  %bcst = call <16 x i32> @llvm.aie2p.vextract.broadcast128.I512(<16 x i32> %v, i32 %idx)
  %r = shufflevector <16 x i32> %bcst, <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  ret <4 x i32> %r
}
