; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
;
; RUN: opt -S -passes=instcombine -mtriple=aie2ps %s | FileCheck %s

; Baseline test for the upcoming InstCombine fold of
; @llvm.aie2ps.vextract.broadcast128.I512 with a constant lane index. The
; intrinsic has the semantics "extract the 128-bit lane at <idx> of a 512-bit
; vector and broadcast it to all four lanes of the 512-bit destination". When
; <idx> is a compile-time constant and only the low 128 bits of the broadcast
; result are consumed, the whole call is equivalent to a single constant-mask
; shufflevector.
;
; Today the intrinsic survives InstCombine, even with constant idx, because
; LLVM treats it as opaque. The follow-up commit adds the target-specific
; instCombineIntrinsic hook that rewrites it; this test's CHECK lines are
; regenerated in that commit to show the intrinsic disappearing for the
; constant-idx cases while staying intact for the runtime-idx case.

declare <16 x i32> @llvm.aie2ps.vextract.broadcast128.I512(<16 x i32>, i32)

; Constant idx 0 -- should fold to shufflevector picking lanes 0..3 of %v.
define <4 x i32> @test_vextbcst128_const_idx0(<16 x i32> %v) {
; CHECK-LABEL: @test_vextbcst128_const_idx0(
; CHECK-NEXT:    [[BCST:%.*]] = call <16 x i32> @llvm.aie2ps.vextract.broadcast128.I512(<16 x i32> [[V:%.*]], i32 0)
; CHECK-NEXT:    [[R:%.*]] = shufflevector <16 x i32> [[BCST]], <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; CHECK-NEXT:    ret <4 x i32> [[R]]
;
  %bcst = call <16 x i32> @llvm.aie2ps.vextract.broadcast128.I512(<16 x i32> %v, i32 0)
  %r = shufflevector <16 x i32> %bcst, <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  ret <4 x i32> %r
}

; Constant idx 2 -- should fold to shufflevector picking lanes 8..11 of %v.
define <4 x i32> @test_vextbcst128_const_idx2(<16 x i32> %v) {
; CHECK-LABEL: @test_vextbcst128_const_idx2(
; CHECK-NEXT:    [[BCST:%.*]] = call <16 x i32> @llvm.aie2ps.vextract.broadcast128.I512(<16 x i32> [[V:%.*]], i32 2)
; CHECK-NEXT:    [[R:%.*]] = shufflevector <16 x i32> [[BCST]], <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; CHECK-NEXT:    ret <4 x i32> [[R]]
;
  %bcst = call <16 x i32> @llvm.aie2ps.vextract.broadcast128.I512(<16 x i32> %v, i32 2)
  %r = shufflevector <16 x i32> %bcst, <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  ret <4 x i32> %r
}

; Constant idx 3 -- should fold to shufflevector picking lanes 12..15 of %v.
define <4 x i32> @test_vextbcst128_const_idx3(<16 x i32> %v) {
; CHECK-LABEL: @test_vextbcst128_const_idx3(
; CHECK-NEXT:    [[BCST:%.*]] = call <16 x i32> @llvm.aie2ps.vextract.broadcast128.I512(<16 x i32> [[V:%.*]], i32 3)
; CHECK-NEXT:    [[R:%.*]] = shufflevector <16 x i32> [[BCST]], <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; CHECK-NEXT:    ret <4 x i32> [[R]]
;
  %bcst = call <16 x i32> @llvm.aie2ps.vextract.broadcast128.I512(<16 x i32> %v, i32 3)
  %r = shufflevector <16 x i32> %bcst, <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  ret <4 x i32> %r
}

; Runtime idx -- intrinsic must NOT fold (no constant lane known).
define <4 x i32> @test_vextbcst128_runtime_idx(<16 x i32> %v, i32 %idx) {
; CHECK-LABEL: @test_vextbcst128_runtime_idx(
; CHECK-NEXT:    [[BCST:%.*]] = call <16 x i32> @llvm.aie2ps.vextract.broadcast128.I512(<16 x i32> [[V:%.*]], i32 [[IDX:%.*]])
; CHECK-NEXT:    [[R:%.*]] = shufflevector <16 x i32> [[BCST]], <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; CHECK-NEXT:    ret <4 x i32> [[R]]
;
  %bcst = call <16 x i32> @llvm.aie2ps.vextract.broadcast128.I512(<16 x i32> %v, i32 %idx)
  %r = shufflevector <16 x i32> %bcst, <16 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  ret <4 x i32> %r
}
