; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
;
; RUN: opt -S -passes=instcombine -mtriple=aie2ps %s | FileCheck %s

; Test the InstCombine optimizations for aie2ps_vsel16 and aie2ps_vsel32 intrinsics
; These optimizations are defined in AIE2PSTargetTransformInfo::instCombineIntrinsic
; The goal is to eliminate unnecessary 'and' operations that mask bits when only lower bits are needed

; ============================================================================
; aie2ps_vsel16 tests
; ============================================================================

; Test that vsel16 with upper part discarded eliminates the 'and' operation
; The 'and' masks to 16 bits, but vsel16 only needs 16 bits when upper part is discarded
define <16 x i16> @test_vsel16_eliminate_and(<32 x i16> %a, <32 x i16> %b, i32 %sel) {
; CHECK-LABEL: @test_vsel16_eliminate_and(
; CHECK-NEXT:    [[VSEL:%.*]] = call <32 x i16> @llvm.aie2ps.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[SEL:%.*]])
; CHECK-NEXT:    [[RESULT:%.*]] = shufflevector <32 x i16> [[VSEL]], <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    ret <16 x i16> [[RESULT]]
;
  %masked = and i32 %sel, 65535
  %vsel = call <32 x i16> @llvm.aie2ps.vsel16(<32 x i16> %a, <32 x i16> %b, i32 %masked)
  %result = shufflevector <32 x i16> %vsel, <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  ret <16 x i16> %result
}

; Test with bitcast in the chain
define <16 x i16> @test_vsel16_eliminate_and_bitcast(<32 x i16> %a, <32 x i16> %b, i32 %sel) {
; CHECK-LABEL: @test_vsel16_eliminate_and_bitcast(
; CHECK-NEXT:    [[VSEL:%.*]] = call <32 x i16> @llvm.aie2ps.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[SEL:%.*]])
; CHECK-NEXT:    [[RESULT:%.*]] = shufflevector <32 x i16> [[VSEL]], <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    ret <16 x i16> [[RESULT]]
;
  %masked = and i32 %sel, 65535
  %vsel = call <32 x i16> @llvm.aie2ps.vsel16(<32 x i16> %a, <32 x i16> %b, i32 %masked)
  %bc = bitcast <32 x i16> %vsel to <32 x i16>
  %result = shufflevector <32 x i16> %bc, <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  ret <16 x i16> %result
}

; Negative test: vsel16 without upper part discarded should keep the 'and'
define <32 x i16> @test_vsel16_keep_and(<32 x i16> %a, <32 x i16> %b, i32 %sel) {
; CHECK-LABEL: @test_vsel16_keep_and(
; CHECK-NEXT:    [[MASKED:%.*]] = and i32 [[SEL:%.*]], 65535
; CHECK-NEXT:    [[VSEL:%.*]] = call <32 x i16> @llvm.aie2ps.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[MASKED]])
; CHECK-NEXT:    ret <32 x i16> [[VSEL]]
;
  %masked = and i32 %sel, 65535
  %vsel = call <32 x i16> @llvm.aie2ps.vsel16(<32 x i16> %a, <32 x i16> %b, i32 %masked)
  ret <32 x i16> %vsel
}

; ============================================================================
; aie2ps_vsel32 tests
; ============================================================================

; Test that vsel32 always eliminates the 'and' operation (unconditional optimization)
define <16 x i32> @test_vsel32_eliminate_and(<16 x i32> %a, <16 x i32> %b, i32 %sel) {
; CHECK-LABEL: @test_vsel32_eliminate_and(
; CHECK-NEXT:    [[VSEL:%.*]] = call <16 x i32> @llvm.aie2ps.vsel32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[SEL:%.*]])
; CHECK-NEXT:    ret <16 x i32> [[VSEL]]
;
  %masked = and i32 %sel, 65535
  %vsel = call <16 x i32> @llvm.aie2ps.vsel32(<16 x i32> %a, <16 x i32> %b, i32 %masked)
  ret <16 x i32> %vsel
}

; Test that vsel32 eliminates 'and' even with full result usage
define <16 x i32> @test_vsel32_eliminate_and_full_usage(<16 x i32> %a, <16 x i32> %b, i32 %sel) {
; CHECK-LABEL: @test_vsel32_eliminate_and_full_usage(
; CHECK-NEXT:    [[VSEL:%.*]] = call <16 x i32> @llvm.aie2ps.vsel32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[SEL:%.*]])
; CHECK-NEXT:    [[RESULT:%.*]] = shl <16 x i32> [[VSEL]], splat (i32 1)
; CHECK-NEXT:    ret <16 x i32> [[RESULT]]
;
  %masked = and i32 %sel, 65535
  %vsel = call <16 x i32> @llvm.aie2ps.vsel32(<16 x i32> %a, <16 x i32> %b, i32 %masked)
  %result = add <16 x i32> %vsel, %vsel
  ret <16 x i32> %result
}

; Test that vsel32 eliminates 'and' even when result is shuffled
define <8 x i32> @test_vsel32_eliminate_and_with_shuffle(<16 x i32> %a, <16 x i32> %b, i32 %sel) {
; CHECK-LABEL: @test_vsel32_eliminate_and_with_shuffle(
; CHECK-NEXT:    [[VSEL:%.*]] = call <16 x i32> @llvm.aie2ps.vsel32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[SEL:%.*]])
; CHECK-NEXT:    [[RESULT:%.*]] = shufflevector <16 x i32> [[VSEL]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    ret <8 x i32> [[RESULT]]
;
  %masked = and i32 %sel, 65535
  %vsel = call <16 x i32> @llvm.aie2ps.vsel32(<16 x i32> %a, <16 x i32> %b, i32 %masked)
  %result = shufflevector <16 x i32> %vsel, <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  ret <8 x i32> %result
}

; Test with zext + and pattern (common in real code)
define <16 x i32> @test_vsel32_eliminate_zext_and(<16 x i32> %a, <16 x i32> %b, i16 %sel_i16) {
; CHECK-LABEL: @test_vsel32_eliminate_zext_and(
; CHECK-NEXT:    [[SEL_I16:%.*]] = zext i16 [[SEL_I17:%.*]] to i32
; CHECK-NEXT:    [[VSEL:%.*]] = call <16 x i32> @llvm.aie2ps.vsel32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[SEL_I16]])
; CHECK-NEXT:    ret <16 x i32> [[VSEL]]
;
  %sel = zext i16 %sel_i16 to i32
  %masked = and i32 %sel, 65535
  %vsel = call <16 x i32> @llvm.aie2ps.vsel32(<16 x i32> %a, <16 x i32> %b, i32 %masked)
  ret <16 x i32> %vsel
}

; ============================================================================
; Negative tests: Smaller masks should be preserved
; ============================================================================

; Test that 8-bit mask (255) is preserved for vsel16 when upper part discarded
define <16 x i16> @test_vsel16_keep_8bit_mask(<32 x i16> %a, <32 x i16> %b, i32 %sel) {
; CHECK-LABEL: @test_vsel16_keep_8bit_mask(
; CHECK-NEXT:    [[MASKED:%.*]] = and i32 [[SEL:%.*]], 255
; CHECK-NEXT:    [[VSEL:%.*]] = call <32 x i16> @llvm.aie2ps.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[MASKED]])
; CHECK-NEXT:    [[RESULT:%.*]] = shufflevector <32 x i16> [[VSEL]], <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    ret <16 x i16> [[RESULT]]
;
  %masked = and i32 %sel, 255
  %vsel = call <32 x i16> @llvm.aie2ps.vsel16(<32 x i16> %a, <32 x i16> %b, i32 %masked)
  %result = shufflevector <32 x i16> %vsel, <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  ret <16 x i16> %result
}

; Test that 4-bit mask (15) is preserved for vsel16 when upper part discarded
define <16 x i16> @test_vsel16_keep_4bit_mask(<32 x i16> %a, <32 x i16> %b, i32 %sel) {
; CHECK-LABEL: @test_vsel16_keep_4bit_mask(
; CHECK-NEXT:    [[MASKED:%.*]] = and i32 [[SEL:%.*]], 15
; CHECK-NEXT:    [[VSEL:%.*]] = call <32 x i16> @llvm.aie2ps.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[MASKED]])
; CHECK-NEXT:    [[RESULT:%.*]] = shufflevector <32 x i16> [[VSEL]], <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    ret <16 x i16> [[RESULT]]
;
  %masked = and i32 %sel, 15
  %vsel = call <32 x i16> @llvm.aie2ps.vsel16(<32 x i16> %a, <32 x i16> %b, i32 %masked)
  %result = shufflevector <32 x i16> %vsel, <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  ret <16 x i16> %result
}

; Test that 15-bit mask (32767) is preserved for vsel16 when upper part discarded
define <16 x i16> @test_vsel16_keep_15bit_mask(<32 x i16> %a, <32 x i16> %b, i32 %sel) {
; CHECK-LABEL: @test_vsel16_keep_15bit_mask(
; CHECK-NEXT:    [[MASKED:%.*]] = and i32 [[SEL:%.*]], 32767
; CHECK-NEXT:    [[VSEL:%.*]] = call <32 x i16> @llvm.aie2ps.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[MASKED]])
; CHECK-NEXT:    [[RESULT:%.*]] = shufflevector <32 x i16> [[VSEL]], <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    ret <16 x i16> [[RESULT]]
;
  %masked = and i32 %sel, 32767
  %vsel = call <32 x i16> @llvm.aie2ps.vsel16(<32 x i16> %a, <32 x i16> %b, i32 %masked)
  %result = shufflevector <32 x i16> %vsel, <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  ret <16 x i16> %result
}

; Test that 8-bit mask (255) is preserved for vsel32
define <16 x i32> @test_vsel32_keep_8bit_mask(<16 x i32> %a, <16 x i32> %b, i32 %sel) {
; CHECK-LABEL: @test_vsel32_keep_8bit_mask(
; CHECK-NEXT:    [[MASKED:%.*]] = and i32 [[SEL:%.*]], 255
; CHECK-NEXT:    [[VSEL:%.*]] = call <16 x i32> @llvm.aie2ps.vsel32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[MASKED]])
; CHECK-NEXT:    ret <16 x i32> [[VSEL]]
;
  %masked = and i32 %sel, 255
  %vsel = call <16 x i32> @llvm.aie2ps.vsel32(<16 x i32> %a, <16 x i32> %b, i32 %masked)
  ret <16 x i32> %vsel
}

; Test that 4-bit mask (15) is preserved for vsel32
define <16 x i32> @test_vsel32_keep_4bit_mask(<16 x i32> %a, <16 x i32> %b, i32 %sel) {
; CHECK-LABEL: @test_vsel32_keep_4bit_mask(
; CHECK-NEXT:    [[MASKED:%.*]] = and i32 [[SEL:%.*]], 15
; CHECK-NEXT:    [[VSEL:%.*]] = call <16 x i32> @llvm.aie2ps.vsel32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[MASKED]])
; CHECK-NEXT:    ret <16 x i32> [[VSEL]]
;
  %masked = and i32 %sel, 15
  %vsel = call <16 x i32> @llvm.aie2ps.vsel32(<16 x i32> %a, <16 x i32> %b, i32 %masked)
  ret <16 x i32> %vsel
}

; Test that 15-bit mask (32767) is preserved for vsel32
define <16 x i32> @test_vsel32_keep_15bit_mask(<16 x i32> %a, <16 x i32> %b, i32 %sel) {
; CHECK-LABEL: @test_vsel32_keep_15bit_mask(
; CHECK-NEXT:    [[MASKED:%.*]] = and i32 [[SEL:%.*]], 32767
; CHECK-NEXT:    [[VSEL:%.*]] = call <16 x i32> @llvm.aie2ps.vsel32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[MASKED]])
; CHECK-NEXT:    ret <16 x i32> [[VSEL]]
;
  %masked = and i32 %sel, 32767
  %vsel = call <16 x i32> @llvm.aie2ps.vsel32(<16 x i32> %a, <16 x i32> %b, i32 %masked)
  ret <16 x i32> %vsel
}

; ============================================================================
; Intrinsic declarations
; ============================================================================

declare <32 x i16> @llvm.aie2ps.vsel16(<32 x i16>, <32 x i16>, i32)
declare <16 x i32> @llvm.aie2ps.vsel32(<16 x i32>, <16 x i32>, i32)
