; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
;
; RUN: opt -S -passes=instcombine -mtriple=aie2p %s | FileCheck %s

; Test the InstCombine optimizations for aie2p_vsel16 and aie2p_vsel32 intrinsics
; These optimizations are defined in AIE2PTargetTransformInfo::instCombineIntrinsic
; The goal is to eliminate unnecessary 'and' operations that mask bits when only lower bits are needed

; ============================================================================
; aie2p_vsel16 tests
; ============================================================================

; Test that vsel16 with upper part discarded eliminates the 'and' operation
; The 'and' masks to 16 bits, but vsel16 only needs 16 bits when upper part is discarded
define <16 x i16> @test_vsel16_eliminate_and(<32 x i16> %a, <32 x i16> %b, i32 %sel) {
; CHECK-LABEL: @test_vsel16_eliminate_and(
; CHECK-NEXT:    [[VSEL:%.*]] = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[SEL:%.*]])
; CHECK-NEXT:    [[RESULT:%.*]] = shufflevector <32 x i16> [[VSEL]], <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    ret <16 x i16> [[RESULT]]
;
  %masked = and i32 %sel, 65535
  %vsel = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> %a, <32 x i16> %b, i32 %masked)
  %result = shufflevector <32 x i16> %vsel, <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  ret <16 x i16> %result
}

; Test with bitcast in the chain
define <16 x i16> @test_vsel16_eliminate_and_bitcast(<32 x i16> %a, <32 x i16> %b, i32 %sel) {
; CHECK-LABEL: @test_vsel16_eliminate_and_bitcast(
; CHECK-NEXT:    [[VSEL:%.*]] = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[SEL:%.*]])
; CHECK-NEXT:    [[RESULT:%.*]] = shufflevector <32 x i16> [[VSEL]], <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    ret <16 x i16> [[RESULT]]
;
  %masked = and i32 %sel, 65535
  %vsel = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> %a, <32 x i16> %b, i32 %masked)
  %bc = bitcast <32 x i16> %vsel to <32 x i16>
  %result = shufflevector <32 x i16> %bc, <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  ret <16 x i16> %result
}

; Negative test: vsel16 without upper part discarded should keep the 'and'
define <32 x i16> @test_vsel16_keep_and(<32 x i16> %a, <32 x i16> %b, i32 %sel) {
; CHECK-LABEL: @test_vsel16_keep_and(
; CHECK-NEXT:    [[MASKED:%.*]] = and i32 [[SEL:%.*]], 65535
; CHECK-NEXT:    [[VSEL:%.*]] = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[MASKED]])
; CHECK-NEXT:    ret <32 x i16> [[VSEL]]
;
  %masked = and i32 %sel, 65535
  %vsel = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> %a, <32 x i16> %b, i32 %masked)
  ret <32 x i16> %vsel
}

; ============================================================================
; aie2p_vsel32 tests
; ============================================================================

; Test that vsel32 always eliminates the 'and' operation (unconditional optimization)
define <16 x i32> @test_vsel32_eliminate_and(<16 x i32> %a, <16 x i32> %b, i32 %sel) {
; CHECK-LABEL: @test_vsel32_eliminate_and(
; CHECK-NEXT:    [[VSEL:%.*]] = call <16 x i32> @llvm.aie2p.vsel32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[SEL:%.*]])
; CHECK-NEXT:    ret <16 x i32> [[VSEL]]
;
  %masked = and i32 %sel, 65535
  %vsel = call <16 x i32> @llvm.aie2p.vsel32(<16 x i32> %a, <16 x i32> %b, i32 %masked)
  ret <16 x i32> %vsel
}

; Test that vsel32 eliminates 'and' even with full result usage
define <16 x i32> @test_vsel32_eliminate_and_full_usage(<16 x i32> %a, <16 x i32> %b, i32 %sel) {
; CHECK-LABEL: @test_vsel32_eliminate_and_full_usage(
; CHECK-NEXT:    [[VSEL:%.*]] = call <16 x i32> @llvm.aie2p.vsel32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[SEL:%.*]])
; CHECK-NEXT:    [[RESULT:%.*]] = shl <16 x i32> [[VSEL]], splat (i32 1)
; CHECK-NEXT:    ret <16 x i32> [[RESULT]]
;
  %masked = and i32 %sel, 65535
  %vsel = call <16 x i32> @llvm.aie2p.vsel32(<16 x i32> %a, <16 x i32> %b, i32 %masked)
  %result = add <16 x i32> %vsel, %vsel
  ret <16 x i32> %result
}

; Test that vsel32 eliminates 'and' even when result is shuffled
define <8 x i32> @test_vsel32_eliminate_and_with_shuffle(<16 x i32> %a, <16 x i32> %b, i32 %sel) {
; CHECK-LABEL: @test_vsel32_eliminate_and_with_shuffle(
; CHECK-NEXT:    [[VSEL:%.*]] = call <16 x i32> @llvm.aie2p.vsel32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[SEL:%.*]])
; CHECK-NEXT:    [[RESULT:%.*]] = shufflevector <16 x i32> [[VSEL]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    ret <8 x i32> [[RESULT]]
;
  %masked = and i32 %sel, 65535
  %vsel = call <16 x i32> @llvm.aie2p.vsel32(<16 x i32> %a, <16 x i32> %b, i32 %masked)
  %result = shufflevector <16 x i32> %vsel, <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  ret <8 x i32> %result
}

; Test with zext + and pattern (common in real code)
define <16 x i32> @test_vsel32_eliminate_zext_and(<16 x i32> %a, <16 x i32> %b, i16 %sel_i16) {
; CHECK-LABEL: @test_vsel32_eliminate_zext_and(
; CHECK-NEXT:    [[SEL_I16:%.*]] = zext i16 [[SEL_I17:%.*]] to i32
; CHECK-NEXT:    [[VSEL:%.*]] = call <16 x i32> @llvm.aie2p.vsel32(<16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[SEL_I16]])
; CHECK-NEXT:    ret <16 x i32> [[VSEL]]
;
  %sel = zext i16 %sel_i16 to i32
  %masked = and i32 %sel, 65535
  %vsel = call <16 x i32> @llvm.aie2p.vsel32(<16 x i32> %a, <16 x i32> %b, i32 %masked)
  ret <16 x i32> %vsel
}

; ============================================================================
; Multi-user tests for vsel16
; ============================================================================

; Test: Multiple shuffle users, all discard upper part - should optimize
define void @test_vsel16_multiple_shuffles_all_discard(<32 x i16> %a, <32 x i16> %b, i32 %sel, ptr %out1, ptr %out2) {
; CHECK-LABEL: @test_vsel16_multiple_shuffles_all_discard(
; CHECK-NEXT:    [[VSEL:%.*]] = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[SEL:%.*]])
; CHECK-NEXT:    [[RESULT1:%.*]] = shufflevector <32 x i16> [[VSEL]], <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[RESULT2:%.*]] = shufflevector <32 x i16> [[VSEL]], <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    store <16 x i16> [[RESULT1]], ptr [[OUT1:%.*]], align 32
; CHECK-NEXT:    store <16 x i16> [[RESULT2]], ptr [[OUT2:%.*]], align 32
; CHECK-NEXT:    ret void
;
  %masked = and i32 %sel, 65535
  %vsel = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> %a, <32 x i16> %b, i32 %masked)
  %result1 = shufflevector <32 x i16> %vsel, <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %result2 = shufflevector <32 x i16> %vsel, <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  store <16 x i16> %result1, ptr %out1
  store <16 x i16> %result2, ptr %out2
  ret void
}

; Test: Multiple users with bitcasts, all discard upper part - should optimize
define void @test_vsel16_multiple_bitcast_shuffles_all_discard(<32 x i16> %a, <32 x i16> %b, i32 %sel, ptr %out1, ptr %out2) {
; CHECK-LABEL: @test_vsel16_multiple_bitcast_shuffles_all_discard(
; CHECK-NEXT:    [[VSEL:%.*]] = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[SEL:%.*]])
; CHECK-NEXT:    [[RESULT1:%.*]] = shufflevector <32 x i16> [[VSEL]], <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[RESULT2:%.*]] = shufflevector <32 x i16> [[VSEL]], <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    store <16 x i16> [[RESULT1]], ptr [[OUT1:%.*]], align 32
; CHECK-NEXT:    store <16 x i16> [[RESULT2]], ptr [[OUT2:%.*]], align 32
; CHECK-NEXT:    ret void
;
  %masked = and i32 %sel, 65535
  %vsel = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> %a, <32 x i16> %b, i32 %masked)
  %bc1 = bitcast <32 x i16> %vsel to <32 x i16>
  %result1 = shufflevector <32 x i16> %bc1, <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %bc2 = bitcast <32 x i16> %vsel to <32 x i16>
  %result2 = shufflevector <32 x i16> %bc2, <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  store <16 x i16> %result1, ptr %out1
  store <16 x i16> %result2, ptr %out2
  ret void
}

; Test: Mixed direct shuffle and bitcast users, all discard upper part - should optimize
define void @test_vsel16_mixed_users_all_discard(<32 x i16> %a, <32 x i16> %b, i32 %sel, ptr %out1, ptr %out2) {
; CHECK-LABEL: @test_vsel16_mixed_users_all_discard(
; CHECK-NEXT:    [[VSEL:%.*]] = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[SEL:%.*]])
; CHECK-NEXT:    [[RESULT1:%.*]] = shufflevector <32 x i16> [[VSEL]], <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[RESULT2:%.*]] = shufflevector <32 x i16> [[VSEL]], <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    store <16 x i16> [[RESULT1]], ptr [[OUT1:%.*]], align 32
; CHECK-NEXT:    store <16 x i16> [[RESULT2]], ptr [[OUT2:%.*]], align 32
; CHECK-NEXT:    ret void
;
  %masked = and i32 %sel, 65535
  %vsel = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> %a, <32 x i16> %b, i32 %masked)
  %result1 = shufflevector <32 x i16> %vsel, <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %bc = bitcast <32 x i16> %vsel to <32 x i16>
  %result2 = shufflevector <32 x i16> %bc, <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  store <16 x i16> %result1, ptr %out1
  store <16 x i16> %result2, ptr %out2
  ret void
}

; Test: Multiple bitcast levels, all discard upper part - should optimize
define <16 x i16> @test_vsel16_multiple_bitcast_levels(<32 x i16> %a, <32 x i16> %b, i32 %sel) {
; CHECK-LABEL: @test_vsel16_multiple_bitcast_levels(
; CHECK-NEXT:    [[VSEL:%.*]] = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[SEL:%.*]])
; CHECK-NEXT:    [[RESULT:%.*]] = shufflevector <32 x i16> [[VSEL]], <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    ret <16 x i16> [[RESULT]]
;
  %masked = and i32 %sel, 65535
  %vsel = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> %a, <32 x i16> %b, i32 %masked)
  %bc1 = bitcast <32 x i16> %vsel to <32 x i16>
  %bc2 = bitcast <32 x i16> %bc1 to <32 x i16>
  %result = shufflevector <32 x i16> %bc2, <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  ret <16 x i16> %result
}

; Negative test: Multiple users where one keeps upper part - should NOT optimize
define void @test_vsel16_multiple_users_one_keeps_upper(<32 x i16> %a, <32 x i16> %b, i32 %sel, ptr %out1, ptr %out2) {
; CHECK-LABEL: @test_vsel16_multiple_users_one_keeps_upper(
; CHECK-NEXT:    [[MASKED:%.*]] = and i32 [[SEL:%.*]], 65535
; CHECK-NEXT:    [[VSEL:%.*]] = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[MASKED]])
; CHECK-NEXT:    [[RESULT1:%.*]] = shufflevector <32 x i16> [[VSEL]], <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    store <16 x i16> [[RESULT1]], ptr [[OUT1:%.*]], align 32
; CHECK-NEXT:    store <32 x i16> [[VSEL]], ptr [[OUT2:%.*]], align 64
; CHECK-NEXT:    ret void
;
  %masked = and i32 %sel, 65535
  %vsel = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> %a, <32 x i16> %b, i32 %masked)
  %result1 = shufflevector <32 x i16> %vsel, <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  store <16 x i16> %result1, ptr %out1
  store <32 x i16> %vsel, ptr %out2
  ret void
}

; Negative test: Multiple users with non-shuffle/non-bitcast - should NOT optimize
define void @test_vsel16_multiple_users_with_non_shuffle(<32 x i16> %a, <32 x i16> %b, i32 %sel, ptr %out1, ptr %out2) {
; CHECK-LABEL: @test_vsel16_multiple_users_with_non_shuffle(
; CHECK-NEXT:    [[MASKED:%.*]] = and i32 [[SEL:%.*]], 65535
; CHECK-NEXT:    [[VSEL:%.*]] = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[MASKED]])
; CHECK-NEXT:    [[RESULT1:%.*]] = shufflevector <32 x i16> [[VSEL]], <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[RESULT2:%.*]] = shl <32 x i16> [[VSEL]], splat (i16 1)
; CHECK-NEXT:    store <16 x i16> [[RESULT1]], ptr [[OUT1:%.*]], align 32
; CHECK-NEXT:    store <32 x i16> [[RESULT2]], ptr [[OUT2:%.*]], align 64
; CHECK-NEXT:    ret void
;
  %masked = and i32 %sel, 65535
  %vsel = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> %a, <32 x i16> %b, i32 %masked)
  %result1 = shufflevector <32 x i16> %vsel, <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %result2 = add <32 x i16> %vsel, %vsel
  store <16 x i16> %result1, ptr %out1
  store <32 x i16> %result2, ptr %out2
  ret void
}

; Negative test: Bitcast chain ending in non-shuffle - should NOT optimize
define void @test_vsel16_bitcast_to_non_shuffle(<32 x i16> %a, <32 x i16> %b, i32 %sel, ptr %out) {
; CHECK-LABEL: @test_vsel16_bitcast_to_non_shuffle(
; CHECK-NEXT:    [[MASKED:%.*]] = and i32 [[SEL:%.*]], 65535
; CHECK-NEXT:    [[VSEL:%.*]] = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[MASKED]])
; CHECK-NEXT:    [[RESULT:%.*]] = shl <32 x i16> [[VSEL]], splat (i16 1)
; CHECK-NEXT:    store <32 x i16> [[RESULT]], ptr [[OUT:%.*]], align 64
; CHECK-NEXT:    ret void
;
  %masked = and i32 %sel, 65535
  %vsel = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> %a, <32 x i16> %b, i32 %masked)
  %bc = bitcast <32 x i16> %vsel to <32 x i16>
  %result = add <32 x i16> %bc, %bc
  store <32 x i16> %result, ptr %out
  ret void
}

; Negative test: Shuffle with wrong mask (not lower half) - should NOT optimize
define <16 x i16> @test_vsel16_shuffle_wrong_mask(<32 x i16> %a, <32 x i16> %b, i32 %sel) {
; CHECK-LABEL: @test_vsel16_shuffle_wrong_mask(
; CHECK-NEXT:    [[MASKED:%.*]] = and i32 [[SEL:%.*]], 65535
; CHECK-NEXT:    [[VSEL:%.*]] = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[MASKED]])
; CHECK-NEXT:    [[RESULT:%.*]] = shufflevector <32 x i16> [[VSEL]], <32 x i16> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
; CHECK-NEXT:    ret <16 x i16> [[RESULT]]
;
  %masked = and i32 %sel, 65535
  %vsel = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> %a, <32 x i16> %b, i32 %masked)
  %result = shufflevector <32 x i16> %vsel, <32 x i16> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  ret <16 x i16> %result
}

; ============================================================================
; Tests for HighestLane checking (non-sequential mask patterns)
; ============================================================================

; Test: Reversed lower half - should optimize (all lanes <= 15)
define <16 x i16> @test_vsel16_reversed_lower_half(<32 x i16> %a, <32 x i16> %b, i32 %sel) {
; CHECK-LABEL: @test_vsel16_reversed_lower_half(
; CHECK-NEXT:    [[VSEL:%.*]] = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[SEL:%.*]])
; CHECK-NEXT:    [[RESULT:%.*]] = shufflevector <32 x i16> [[VSEL]], <32 x i16> poison, <16 x i32> <i32 15, i32 14, i32 13, i32 12, i32 11, i32 10, i32 9, i32 8, i32 7, i32 6, i32 5, i32 4, i32 3, i32 2, i32 1, i32 0>
; CHECK-NEXT:    ret <16 x i16> [[RESULT]]
;
  %masked = and i32 %sel, 65535
  %vsel = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> %a, <32 x i16> %b, i32 %masked)
  %result = shufflevector <32 x i16> %vsel, <32 x i16> poison, <16 x i32> <i32 15, i32 14, i32 13, i32 12, i32 11, i32 10, i32 9, i32 8, i32 7, i32 6, i32 5, i32 4, i32 3, i32 2, i32 1, i32 0>
  ret <16 x i16> %result
}

; Test: Even lanes only from lower half - should optimize (all lanes <= 15)
define <8 x i16> @test_vsel16_even_lanes_lower(<32 x i16> %a, <32 x i16> %b, i32 %sel) {
; CHECK-LABEL: @test_vsel16_even_lanes_lower(
; CHECK-NEXT:    [[VSEL:%.*]] = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[SEL:%.*]])
; CHECK-NEXT:    [[RESULT:%.*]] = shufflevector <32 x i16> [[VSEL]], <32 x i16> poison, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>
; CHECK-NEXT:    ret <8 x i16> [[RESULT]]
;
  %masked = and i32 %sel, 65535
  %vsel = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> %a, <32 x i16> %b, i32 %masked)
  %result = shufflevector <32 x i16> %vsel, <32 x i16> poison, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>
  ret <8 x i16> %result
}

; Test: Odd lanes only from lower half - should optimize (all lanes <= 15)
define <8 x i16> @test_vsel16_odd_lanes_lower(<32 x i16> %a, <32 x i16> %b, i32 %sel) {
; CHECK-LABEL: @test_vsel16_odd_lanes_lower(
; CHECK-NEXT:    [[VSEL:%.*]] = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[SEL:%.*]])
; CHECK-NEXT:    [[RESULT:%.*]] = shufflevector <32 x i16> [[VSEL]], <32 x i16> poison, <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
; CHECK-NEXT:    ret <8 x i16> [[RESULT]]
;
  %masked = and i32 %sel, 65535
  %vsel = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> %a, <32 x i16> %b, i32 %masked)
  %result = shufflevector <32 x i16> %vsel, <32 x i16> poison, <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
  ret <8 x i16> %result
}

; Test: Partial extraction (first 8 elements) - should optimize (all lanes <= 15)
define <8 x i16> @test_vsel16_partial_first_8(<32 x i16> %a, <32 x i16> %b, i32 %sel) {
; CHECK-LABEL: @test_vsel16_partial_first_8(
; CHECK-NEXT:    [[VSEL:%.*]] = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[SEL:%.*]])
; CHECK-NEXT:    [[RESULT:%.*]] = shufflevector <32 x i16> [[VSEL]], <32 x i16> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    ret <8 x i16> [[RESULT]]
;
  %masked = and i32 %sel, 65535
  %vsel = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> %a, <32 x i16> %b, i32 %masked)
  %result = shufflevector <32 x i16> %vsel, <32 x i16> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  ret <8 x i16> %result
}

; Test: Partial extraction (last 8 of lower half) - should optimize (all lanes <= 15)
define <8 x i16> @test_vsel16_partial_last_8_of_lower(<32 x i16> %a, <32 x i16> %b, i32 %sel) {
; CHECK-LABEL: @test_vsel16_partial_last_8_of_lower(
; CHECK-NEXT:    [[VSEL:%.*]] = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[SEL:%.*]])
; CHECK-NEXT:    [[RESULT:%.*]] = shufflevector <32 x i16> [[VSEL]], <32 x i16> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    ret <8 x i16> [[RESULT]]
;
  %masked = and i32 %sel, 65535
  %vsel = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> %a, <32 x i16> %b, i32 %masked)
  %result = shufflevector <32 x i16> %vsel, <32 x i16> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  ret <8 x i16> %result
}

; Test: Broadcast lane 0 - should optimize (all lanes <= 15)
define <16 x i16> @test_vsel16_broadcast_lane0(<32 x i16> %a, <32 x i16> %b, i32 %sel) {
; CHECK-LABEL: @test_vsel16_broadcast_lane0(
; CHECK-NEXT:    [[VSEL:%.*]] = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[SEL:%.*]])
; CHECK-NEXT:    [[RESULT:%.*]] = shufflevector <32 x i16> [[VSEL]], <32 x i16> poison, <16 x i32> zeroinitializer
; CHECK-NEXT:    ret <16 x i16> [[RESULT]]
;
  %masked = and i32 %sel, 65535
  %vsel = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> %a, <32 x i16> %b, i32 %masked)
  %result = shufflevector <32 x i16> %vsel, <32 x i16> poison, <16 x i32> <i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>
  ret <16 x i16> %result
}

; Test: Repeat pattern from lower half - should optimize (all lanes <= 15)
define <16 x i16> @test_vsel16_repeat_pattern(<32 x i16> %a, <32 x i16> %b, i32 %sel) {
; CHECK-LABEL: @test_vsel16_repeat_pattern(
; CHECK-NEXT:    [[VSEL:%.*]] = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[SEL:%.*]])
; CHECK-NEXT:    [[RESULT:%.*]] = shufflevector <32 x i16> [[VSEL]], <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1>
; CHECK-NEXT:    ret <16 x i16> [[RESULT]]
;
  %masked = and i32 %sel, 65535
  %vsel = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> %a, <32 x i16> %b, i32 %masked)
  %result = shufflevector <32 x i16> %vsel, <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1>
  ret <16 x i16> %result
}

; Test: Exactly at boundary (lane 15) - should optimize (lane 15 <= 15)
define <4 x i16> @test_vsel16_boundary_lane15(<32 x i16> %a, <32 x i16> %b, i32 %sel) {
; CHECK-LABEL: @test_vsel16_boundary_lane15(
; CHECK-NEXT:    [[VSEL:%.*]] = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[SEL:%.*]])
; CHECK-NEXT:    [[RESULT:%.*]] = shufflevector <32 x i16> [[VSEL]], <32 x i16> poison, <4 x i32> <i32 15, i32 15, i32 15, i32 15>
; CHECK-NEXT:    ret <4 x i16> [[RESULT]]
;
  %masked = and i32 %sel, 65535
  %vsel = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> %a, <32 x i16> %b, i32 %masked)
  %result = shufflevector <32 x i16> %vsel, <32 x i16> poison, <4 x i32> <i32 15, i32 15, i32 15, i32 15>
  ret <4 x i16> %result
}

; Negative test: Mix of lower and upper (lane 16) - should NOT optimize (lane 16 > 15)
define <16 x i16> @test_vsel16_mix_lower_upper_lane16(<32 x i16> %a, <32 x i16> %b, i32 %sel) {
; CHECK-LABEL: @test_vsel16_mix_lower_upper_lane16(
; CHECK-NEXT:    [[MASKED:%.*]] = and i32 [[SEL:%.*]], 65535
; CHECK-NEXT:    [[VSEL:%.*]] = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[MASKED]])
; CHECK-NEXT:    [[RESULT:%.*]] = shufflevector <32 x i16> [[VSEL]], <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 16>
; CHECK-NEXT:    ret <16 x i16> [[RESULT]]
;
  %masked = and i32 %sel, 65535
  %vsel = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> %a, <32 x i16> %b, i32 %masked)
  %result = shufflevector <32 x i16> %vsel, <32 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 16>
  ret <16 x i16> %result
}

; Negative test: Single upper lane (lane 20) - should NOT optimize (lane 20 > 15)
define <8 x i16> @test_vsel16_single_upper_lane20(<32 x i16> %a, <32 x i16> %b, i32 %sel) {
; CHECK-LABEL: @test_vsel16_single_upper_lane20(
; CHECK-NEXT:    [[MASKED:%.*]] = and i32 [[SEL:%.*]], 65535
; CHECK-NEXT:    [[VSEL:%.*]] = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[MASKED]])
; CHECK-NEXT:    [[RESULT:%.*]] = shufflevector <32 x i16> [[VSEL]], <32 x i16> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 20, i32 5, i32 6, i32 7>
; CHECK-NEXT:    ret <8 x i16> [[RESULT]]
;
  %masked = and i32 %sel, 65535
  %vsel = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> %a, <32 x i16> %b, i32 %masked)
  %result = shufflevector <32 x i16> %vsel, <32 x i16> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 20, i32 5, i32 6, i32 7>
  ret <8 x i16> %result
}

; Negative test: Only upper half lanes - should NOT optimize (all lanes > 15)
define <16 x i16> @test_vsel16_only_upper_half(<32 x i16> %a, <32 x i16> %b, i32 %sel) {
; CHECK-LABEL: @test_vsel16_only_upper_half(
; CHECK-NEXT:    [[MASKED:%.*]] = and i32 [[SEL:%.*]], 65535
; CHECK-NEXT:    [[VSEL:%.*]] = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[MASKED]])
; CHECK-NEXT:    [[RESULT:%.*]] = shufflevector <32 x i16> [[VSEL]], <32 x i16> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
; CHECK-NEXT:    ret <16 x i16> [[RESULT]]
;
  %masked = and i32 %sel, 65535
  %vsel = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> %a, <32 x i16> %b, i32 %masked)
  %result = shufflevector <32 x i16> %vsel, <32 x i16> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  ret <16 x i16> %result
}

; Negative test: Interleaved lower and upper lanes - should NOT optimize
define <8 x i16> @test_vsel16_interleaved_lower_upper(<32 x i16> %a, <32 x i16> %b, i32 %sel) {
; CHECK-LABEL: @test_vsel16_interleaved_lower_upper(
; CHECK-NEXT:    [[MASKED:%.*]] = and i32 [[SEL:%.*]], 65535
; CHECK-NEXT:    [[VSEL:%.*]] = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[MASKED]])
; CHECK-NEXT:    [[RESULT:%.*]] = shufflevector <32 x i16> [[VSEL]], <32 x i16> poison, <8 x i32> <i32 0, i32 16, i32 2, i32 18, i32 4, i32 20, i32 6, i32 22>
; CHECK-NEXT:    ret <8 x i16> [[RESULT]]
;
  %masked = and i32 %sel, 65535
  %vsel = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> %a, <32 x i16> %b, i32 %masked)
  %result = shufflevector <32 x i16> %vsel, <32 x i16> poison, <8 x i32> <i32 0, i32 16, i32 2, i32 18, i32 4, i32 20, i32 6, i32 22>
  ret <8 x i16> %result
}

; Test: Non-sequential but all in lower half with bitcast - should optimize
define <8 x i16> @test_vsel16_nonseq_lower_with_bitcast(<32 x i16> %a, <32 x i16> %b, i32 %sel) {
; CHECK-LABEL: @test_vsel16_nonseq_lower_with_bitcast(
; CHECK-NEXT:    [[VSEL:%.*]] = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> [[A:%.*]], <32 x i16> [[B:%.*]], i32 [[SEL:%.*]])
; CHECK-NEXT:    [[RESULT:%.*]] = shufflevector <32 x i16> [[VSEL]], <32 x i16> poison, <8 x i32> <i32 15, i32 10, i32 5, i32 0, i32 3, i32 7, i32 12, i32 1>
; CHECK-NEXT:    ret <8 x i16> [[RESULT]]
;
  %masked = and i32 %sel, 65535
  %vsel = call <32 x i16> @llvm.aie2p.vsel16(<32 x i16> %a, <32 x i16> %b, i32 %masked)
  %bc = bitcast <32 x i16> %vsel to <32 x i16>
  %result = shufflevector <32 x i16> %bc, <32 x i16> poison, <8 x i32> <i32 15, i32 10, i32 5, i32 0, i32 3, i32 7, i32 12, i32 1>
  ret <8 x i16> %result
}

; ============================================================================
; Intrinsic declarations
; ============================================================================

declare <32 x i16> @llvm.aie2p.vsel16(<32 x i16>, <32 x i16>, i32)
declare <16 x i32> @llvm.aie2p.vsel32(<16 x i32>, <16 x i32>, i32)
