; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates

; RUN: opt --passes=licm -o - -S  %s | FileCheck %s
; REQUIRES: aie-registered-target


; promote store %inc to exit block
define void @promote_store(ptr noalias %param) {
; CHECK-LABEL: define void @promote_store(
; CHECK-SAME: ptr noalias [[PARAM:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[COUNT2_I_I_I:%.*]] = getelementptr i8, ptr [[PARAM]], i20 140
; CHECK-NEXT:    br label %[[FOR_BODY_I31_I:.*]]
; CHECK:       [[FOR_BODY_I31_I]]:
; CHECK-NEXT:    [[LOOP_COUNTER:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[INC:%.*]], %[[FOR_BODY_I31_I]] ]
; CHECK-NEXT:    [[INC]] = add i32 [[LOOP_COUNTER]], 1
; CHECK-NEXT:    br i1 false, label %[[EXIT:.*]], label %[[FOR_BODY_I31_I]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[INC_LCSSA:%.*]] = phi i32 [ [[INC]], %[[FOR_BODY_I31_I]] ]
; CHECK-NEXT:    store i32 [[INC_LCSSA]], ptr [[COUNT2_I_I_I]], align 4, !alias.scope [[META0:![0-9]+]]
; CHECK-NEXT:    ret void
;
entry:
  %count2.i.i.i = getelementptr i8, ptr %param, i20 140
  br label %for.body.i31.i

for.body.i31.i:                                   ; preds = %for.body.i31.i, %entry
  %loop.counter = phi i32 [ 0, %entry ], [ %inc, %for.body.i31.i ]
  %inc = add i32 %loop.counter, 1
  store i32 %inc, ptr %count2.i.i.i, align 4, !alias.scope !0
  br i1 false, label %exit, label %for.body.i31.i

exit:                                   ; preds = %for.body.i31.i
  ret void
}

; aie2
; promote store %inc to exit block
define void @promote_store_aie2_intrinsics(ptr noalias %param, ptr addrspace(5) %in) {
; CHECK-LABEL: define void @promote_store_aie2_intrinsics(
; CHECK-SAME: ptr noalias [[PARAM:%.*]], ptr addrspace(5) [[IN:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[COUNT2_I_I_I:%.*]] = getelementptr i8, ptr [[PARAM]], i20 140
; CHECK-NEXT:    br label %[[FOR_BODY_I31_I:.*]]
; CHECK:       [[FOR_BODY_I31_I]]:
; CHECK-NEXT:    [[PTR_LOOP:%.*]] = phi ptr addrspace(5) [ [[IN]], %[[ENTRY]] ], [ [[PTR_INC:%.*]], %[[FOR_BODY_I31_I]] ]
; CHECK-NEXT:    [[LOOP_CTR:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[INC:%.*]], %[[FOR_BODY_I31_I]] ]
; CHECK-NEXT:    [[PTR_INC]] = getelementptr <16 x i32>, ptr addrspace(5) [[PTR_LOOP]], i20 512
; CHECK-NEXT:    [[TMP1:%.*]] = load <16 x i32>, ptr addrspace(5) [[PTR_INC]], align 64
; CHECK-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2.vshuffle(<16 x i32> [[TMP1]], <16 x i32> zeroinitializer, i32 0)
; CHECK-NEXT:    store <16 x i32> [[TMP2]], ptr addrspace(5) [[PTR_INC]], align 64
; CHECK-NEXT:    [[INC]] = add i32 [[LOOP_CTR]], 1
; CHECK-NEXT:    br i1 false, label %[[EXIT:.*]], label %[[FOR_BODY_I31_I]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[INC_LCSSA:%.*]] = phi i32 [ [[INC]], %[[FOR_BODY_I31_I]] ]
; CHECK-NEXT:    store i32 [[INC_LCSSA]], ptr [[COUNT2_I_I_I]], align 4, !alias.scope [[META3:![0-9]+]]
; CHECK-NEXT:    ret void
;
entry:
  %count2.i.i.i = getelementptr i8, ptr %param, i20 140
  br label %for.body.i31.i

for.body.i31.i:                                   ; preds = %for.body.i31.i, %entry
  %ptr.loop = phi ptr addrspace(5) [ %in, %entry ], [ %ptr.inc, %for.body.i31.i ]
  %loop.ctr = phi i32 [ 0, %entry ], [ %inc, %for.body.i31.i ]
  %ptr.inc = getelementptr <16 x i32>, ptr addrspace(5) %ptr.loop, i20 512
  %31 = load <16 x i32>, ptr addrspace(5) %ptr.inc, align 64
  %34 = tail call <16 x i32> @llvm.aie2.vshuffle(<16 x i32> %31, <16 x i32> zeroinitializer, i32 0)
  store <16 x i32> %34, ptr addrspace(5) %ptr.inc, align 64
  %inc = add i32 %loop.ctr, 1
  store i32 %inc, ptr %count2.i.i.i, align 4, !alias.scope !6
  br i1 false, label %exit, label %for.body.i31.i

exit:                                   ; preds = %for.body.i31.i
  ret void
}

; aie2p
; promote store %inc to exit block
define void @promote_store_aie2p_intrinsics(ptr noalias %param, ptr addrspace(5) %in) {
; CHECK-LABEL: define void @promote_store_aie2p_intrinsics(
; CHECK-SAME: ptr noalias [[PARAM:%.*]], ptr addrspace(5) [[IN:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[COUNT2_I_I_I:%.*]] = getelementptr i8, ptr [[PARAM]], i20 140
; CHECK-NEXT:    br label %[[FOR_BODY_I31_I:.*]]
; CHECK:       [[FOR_BODY_I31_I]]:
; CHECK-NEXT:    [[PTR_LOOP:%.*]] = phi ptr addrspace(5) [ [[IN]], %[[ENTRY]] ], [ [[PTR_INC:%.*]], %[[FOR_BODY_I31_I]] ]
; CHECK-NEXT:    [[LOOP_CTR:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[INC:%.*]], %[[FOR_BODY_I31_I]] ]
; CHECK-NEXT:    [[PTR_INC]] = getelementptr <16 x i32>, ptr addrspace(5) [[PTR_LOOP]], i20 512
; CHECK-NEXT:    [[TMP1:%.*]] = load <16 x i32>, ptr addrspace(5) [[PTR_INC]], align 64
; CHECK-NEXT:    [[TMP2:%.*]] = tail call <16 x i32> @llvm.aie2p.vshuffle(<16 x i32> [[TMP1]], <16 x i32> zeroinitializer, i32 0)
; CHECK-NEXT:    store <16 x i32> [[TMP2]], ptr addrspace(5) [[PTR_INC]], align 64
; CHECK-NEXT:    [[INC]] = add i32 [[LOOP_CTR]], 1
; CHECK-NEXT:    br i1 false, label %[[EXIT:.*]], label %[[FOR_BODY_I31_I]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[INC_LCSSA:%.*]] = phi i32 [ [[INC]], %[[FOR_BODY_I31_I]] ]
; CHECK-NEXT:    store i32 [[INC_LCSSA]], ptr [[COUNT2_I_I_I]], align 4, !alias.scope [[META6:![0-9]+]]
; CHECK-NEXT:    ret void
;
entry:
  %count2.i.i.i = getelementptr i8, ptr %param, i20 140
  br label %for.body.i31.i

for.body.i31.i:                                   ; preds = %for.body.i31.i, %entry
  %ptr.loop = phi ptr addrspace(5) [ %in, %entry ], [ %ptr.inc, %for.body.i31.i ]
  %loop.ctr = phi i32 [ 0, %entry ], [ %inc, %for.body.i31.i ]
  %ptr.inc = getelementptr <16 x i32>, ptr addrspace(5) %ptr.loop, i20 512
  %31 = load <16 x i32>, ptr addrspace(5) %ptr.inc, align 64
  %34 = tail call <16 x i32> @llvm.aie2p.vshuffle(<16 x i32> %31, <16 x i32> zeroinitializer, i32 0)
  store <16 x i32> %34, ptr addrspace(5) %ptr.inc, align 64
  %inc = add i32 %loop.ctr, 1
  store i32 %inc, ptr %count2.i.i.i, align 4, !alias.scope !3
  br i1 false, label %exit, label %for.body.i31.i

exit:                                   ; preds = %for.body.i31.i
  ret void
}

; Function Attrs: nounwind memory(none)
declare <16 x i32> @llvm.aie2.vshuffle(<16 x i32>, <16 x i32>, i32) #0
; Function Attrs: nounwind memory(none)
declare <16 x i32> @llvm.aie2p.vshuffle(<16 x i32>, <16 x i32>, i32) #0

attributes #0 = { nounwind memory(none) }

!0 = !{!1}
!1 = distinct !{!1, !2, !"promote_store: %param"}
!2 = distinct !{!2, !"promote_store"}
!3 = !{!4}
!4 = distinct !{!4, !5, !"promote_store_aie2p_intrinsics: %param"}
!5 = distinct !{!5, !"promote_store_aie2p_intrinsics"}
!6 = !{!7}
!7 = distinct !{!7, !8, !"promote_store_aie2_intrinsics: %param"}
!8 = distinct !{!8, !"promote_store_aie2_intrinsics"}

;.
; CHECK: [[META0]] = !{[[META1:![0-9]+]]}
; CHECK: [[META1]] = distinct !{[[META1]], [[META2:![0-9]+]], !"promote_store: %param"}
; CHECK: [[META2]] = distinct !{[[META2]], !"promote_store"}
; CHECK: [[META3]] = !{[[META4:![0-9]+]]}
; CHECK: [[META4]] = distinct !{[[META4]], [[META5:![0-9]+]], !"promote_store_aie2_intrinsics: %param"}
; CHECK: [[META5]] = distinct !{[[META5]], !"promote_store_aie2_intrinsics"}
; CHECK: [[META6]] = !{[[META7:![0-9]+]]}
; CHECK: [[META7]] = distinct !{[[META7]], [[META8:![0-9]+]], !"promote_store_aie2p_intrinsics: %param"}
; CHECK: [[META8]] = distinct !{[[META8]], !"promote_store_aie2p_intrinsics"}
;.
