; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie2 < %s | FileCheck --check-prefix=AIE2 %s
; RUN: llc -mtriple=aie2p < %s | FileCheck --check-prefix=AIE2P %s
; RUN: llc -mtriple=aie2ps < %s | FileCheck --check-prefix=AIE2PS %s

; Function Attrs: mustprogress noinline
define weak_odr dso_local void @setup(ptr noalias nonnull align 64 dereferenceable(57) %params, ptr noalias %rtps_void) {
; AIE2-LABEL: setup:
; AIE2:       // %bb.0: // %entry
; AIE2-NEXT:    nopb ; lda r6, [p1, #12]; nops ; nopxm ; nopv
; AIE2-NEXT:    lda r0, [p1], #4; nopx
; AIE2-NEXT:    lda r3, [p1], #4
; AIE2-NEXT:    lda r2, [p1], #8
; AIE2-NEXT:    nop
; AIE2-NEXT:    lda r5, [p1], #4
; AIE2-NEXT:    lda r4, [p1, #0]
; AIE2-NEXT:    lda r7, [p1, #4]; mov p1, p0
; AIE2-NEXT:    st r0, [p1], #4
; AIE2-NEXT:    st r3, [p1], #4
; AIE2-NEXT:    st r2, [p1], #4
; AIE2-NEXT:    st r6, [p1], #4
; AIE2-NEXT:    st r5, [p1], #4
; AIE2-NEXT:    mova m0, #6; st r4, [p1], #4
; AIE2-NEXT:    st r7, [p1], m0
; AIE2-NEXT:    st.s16 r1, [p1], #4
; AIE2-NEXT:    nop
; AIE2-NEXT:    mul r1, r4, r5
; AIE2-NEXT:    nop
; AIE2-NEXT:    mul r1, r1, r7
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    st.s16 r1, [p1, #0]
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    mova r1, #0
; AIE2-NEXT:    nop
; AIE2-NEXT:    mova r1, #4
; AIE2-NEXT:    eq r8, r6, r1
; AIE2-NEXT:    jnz r8, #.LBB0_5
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    nop // Delay Slot 2
; AIE2-NEXT:    mova r1, #32 // Delay Slot 1
; AIE2-NEXT:  // %bb.1: // %entry
; AIE2-NEXT:    mova r5, #2
; AIE2-NEXT:    eq r8, r6, r5
; AIE2-NEXT:    jnz r8, #.LBB0_4
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    nop // Delay Slot 2
; AIE2-NEXT:    movxm r5, #65535 // Delay Slot 1
; AIE2-NEXT:  // %bb.2: // %entry
; AIE2-NEXT:    mova r7, #1
; AIE2-NEXT:    ne r6, r6, r7
; AIE2-NEXT:    jnz r6, #.LBB0_6
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    nop // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
; AIE2-NEXT:  // %bb.3: // %sw.bb
; AIE2-NEXT:    add r6, r3, r5
; AIE2-NEXT:    add r5, r0, r5
; AIE2-NEXT:    mul r3, r2, r3
; AIE2-NEXT:    mova r7, #-5
; AIE2-NEXT:    lshl r8, r2, r7
; AIE2-NEXT:    mul r6, r2, r6
; AIE2-NEXT:    mul r2, r2, r0
; AIE2-NEXT:    nop
; AIE2-NEXT:    add r8, r8, #-1
; AIE2-NEXT:    mul r5, r3, r5
; AIE2-NEXT:    mova m0, #38; movxm r10, #2097152
; AIE2-NEXT:    mova r9, #16; paddb [p0], m0; extend.u16 r8, r8
; AIE2-NEXT:    st.s16 r1, [p0], #2; lshl r6, r6, r9
; AIE2-NEXT:    add r6, r6, r10
; AIE2-NEXT:    sub r5, r1, r5
; AIE2-NEXT:    or r6, r8, r6
; AIE2-NEXT:    add r8, r0, #-1
; AIE2-NEXT:    lshl r5, r5, r9
; AIE2-NEXT:    extend.u16 r8, r8
; AIE2-NEXT:    st r6, [p0], #4; or r5, r8, r5
; AIE2-NEXT:    st r5, [p0], #4
; AIE2-NEXT:    st r2, [p0], #-16
; AIE2-NEXT:    st.s16 r4, [p0], #-4
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    st.s16 r0, [p0, #0]
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    mul r0, r3, r0
; AIE2-NEXT:    nop
; AIE2-NEXT:    lshl r0, r0, r7
; AIE2-NEXT:    mova dj0, #26
; AIE2-NEXT:    st.s16 r0, [p0, dj0]
; AIE2-NEXT:    nop
; AIE2-NEXT:    ret lr
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    sub r0, r1, r2 // Delay Slot 3
; AIE2-NEXT:    nop // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
; AIE2-NEXT:  .LBB0_4: // %sw.bb51
; AIE2-NEXT:    nopa ; paddb [p0], #28; nopx
; AIE2-NEXT:    st.s16 r4, [p0], #4
; AIE2-NEXT:    mul r4, r2, r3
; AIE2-NEXT:    nop
; AIE2-NEXT:    mul r4, r4, r0
; AIE2-NEXT:    mova r6, #-5
; AIE2-NEXT:    lshl r4, r4, r6
; AIE2-NEXT:    mova m0, #16
; AIE2-NEXT:    st.s16 r7, [p0], m0
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    add r6, r0, r5
; AIE2-NEXT:    mul r6, r3, r6
; AIE2-NEXT:    mul r4, r3, r0
; AIE2-NEXT:    mova m0, #-10
; AIE2-NEXT:    st r4, [p0], m0; add r6, r3, r6
; AIE2-NEXT:    st.s16 r2, [p0], #2; add r5, r6, r5
; AIE2-NEXT:    add r3, r3, #-1
; AIE2-NEXT:    add r0, r0, #-1
; AIE2-NEXT:    mul r5, r5, r2
; AIE2-NEXT:    nop
; AIE2-NEXT:    mova r6, #16; extend.u16 r3, r3
; AIE2-NEXT:    lshl r2, r2, r6
; AIE2-NEXT:    or r2, r3, r2
; AIE2-NEXT:    mova dj0, #10; st r2, [p0], #4; extend.u16 r0, r0
; AIE2-NEXT:    st.s16 r2, [p0, dj0]; movx r7, #5
; AIE2-NEXT:    lshl r2, r4, r7
; AIE2-NEXT:    sub r2, r1, r2
; AIE2-NEXT:    ret lr
; AIE2-NEXT:    sub r1, r1, r5 // Delay Slot 5
; AIE2-NEXT:    lshl r1, r1, r6 // Delay Slot 4
; AIE2-NEXT:    or r0, r0, r1 // Delay Slot 3
; AIE2-NEXT:    st r0, [p0, #0] // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
; AIE2-NEXT:  .LBB0_5: // %sw.bb109
; AIE2-NEXT:    mova m0, #38; nopb ; nopxm
; AIE2-NEXT:    mova r4, #-5; paddb [p0], m0; add r8, r3, #-1
; AIE2-NEXT:    st.s16 r1, [p0], #2; lshl r6, r2, r4
; AIE2-NEXT:    extend.u16 r8, r8
; AIE2-NEXT:    mul r2, r2, r3
; AIE2-NEXT:    movxm r7, #2097152
; AIE2-NEXT:    add r6, r6, #-1
; AIE2-NEXT:    extend.u16 r6, r6
; AIE2-NEXT:    or r6, r6, r7
; AIE2-NEXT:    st r6, [p0], #4; or r7, r8, r7
; AIE2-NEXT:    st r7, [p0], #4
; AIE2-NEXT:    st r2, [p0], #-16
; AIE2-NEXT:    st.s16 r5, [p0], #-4
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    st.s16 r0, [p0, #0]
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    mul r0, r2, r0
; AIE2-NEXT:    nop
; AIE2-NEXT:    lshl r0, r0, r4
; AIE2-NEXT:    mova dj0, #26
; AIE2-NEXT:    st.s16 r0, [p0, dj0]
; AIE2-NEXT:    sub r0, r1, r2
; AIE2-NEXT:  .LBB0_6: // %sw.epilog
; AIE2-NEXT:    nopa ; ret lr
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    nop // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: setup:
; AIE2P:       // %bb.0: // %entry
; AIE2P-NEXT:    lda r6, [p1, #12]; nopxm
; AIE2P-NEXT:    lda r1, [p1], #4
; AIE2P-NEXT:    lda r2, [p1], #4
; AIE2P-NEXT:    lda r0, [p1], #8
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    lda r4, [p1], #4
; AIE2P-NEXT:    lda r5, [p1, #0]
; AIE2P-NEXT:    lda r7, [p1, #4]; mov p1, p0
; AIE2P-NEXT:    st r1, [p1], #4
; AIE2P-NEXT:    st r2, [p1], #4
; AIE2P-NEXT:    st r0, [p1], #4
; AIE2P-NEXT:    st r6, [p1], #4
; AIE2P-NEXT:    st r4, [p1], #4
; AIE2P-NEXT:    mova m0, #6; st r5, [p1], #4
; AIE2P-NEXT:    st r7, [p1], m0
; AIE2P-NEXT:    st.s16 r3, [p1, #0]
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    mul r3, r5, r4
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    mul r3, r3, r7
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    st.s16 r3, [p1, #4]
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    mova r3, #0
; AIE2P-NEXT:    mova r3, #4
; AIE2P-NEXT:    eq r16, r6, r3
; AIE2P-NEXT:    jnz r16, #.LBB0_5
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    nop // Delay Slot 2
; AIE2P-NEXT:    mova r3, #32 // Delay Slot 1
; AIE2P-NEXT:  // %bb.1: // %entry
; AIE2P-NEXT:    mova r4, #2
; AIE2P-NEXT:    eq r16, r6, r4
; AIE2P-NEXT:    jnz r16, #.LBB0_4
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    nop // Delay Slot 2
; AIE2P-NEXT:    movxm r4, #65535 // Delay Slot 1
; AIE2P-NEXT:  // %bb.2: // %entry
; AIE2P-NEXT:    mova r7, #1
; AIE2P-NEXT:    ne r6, r6, r7
; AIE2P-NEXT:    jnz r6, #.LBB0_6
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    nop // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
; AIE2P-NEXT:  // %bb.3: // %sw.bb
; AIE2P-NEXT:    add r16, r2, r4
; AIE2P-NEXT:    add r4, r1, r4
; AIE2P-NEXT:    movxm r18, #2097152
; AIE2P-NEXT:    mova r6, #-5; mul r2, r0, r2
; AIE2P-NEXT:    lshl r7, r0, r6
; AIE2P-NEXT:    mul r16, r0, r16
; AIE2P-NEXT:    add r7, r7, #-1
; AIE2P-NEXT:    mova m0, #38; extend.u16 r7, r7; mov r17, #16
; AIE2P-NEXT:    padda [p0], m0; lshl r16, r16, r17
; AIE2P-NEXT:    st.s16 r3, [p0], #2; add r16, r16, r18
; AIE2P-NEXT:    mova r18, #32; msc r18, r18, r2, r4
; AIE2P-NEXT:    or r7, r7, r16
; AIE2P-NEXT:    add r16, r1, #-1
; AIE2P-NEXT:    extend.u16 r4, r16
; AIE2P-NEXT:    lshl r16, r18, r17
; AIE2P-NEXT:    mul r7, r0, r1
; AIE2P-NEXT:    st r7, [p0], #4; or r4, r4, r16
; AIE2P-NEXT:    st r4, [p0], #4
; AIE2P-NEXT:    st r7, [p0], #-16
; AIE2P-NEXT:    st.s16 r5, [p0], #-4
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    st.s16 r2, [p0, #0]
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    mul r2, r2, r1
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    lshl r2, r2, r6
; AIE2P-NEXT:    mova dj0, #26
; AIE2P-NEXT:    st.s16 r3, [p0, dj0]
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    ret lr
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    msc r3, r3, r0, r1 // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    nop // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
; AIE2P-NEXT:  .LBB0_4: // %sw.bb51
; AIE2P-NEXT:    mova m0, #28
; AIE2P-NEXT:    padda [p0], m0
; AIE2P-NEXT:    st.s16 r5, [p0], #4
; AIE2P-NEXT:    mul r5, r0, r2
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    mul r5, r5, r1
; AIE2P-NEXT:    movx r6, #-5
; AIE2P-NEXT:    lshl r5, r5, r6
; AIE2P-NEXT:    mova m0, #16
; AIE2P-NEXT:    st.s16 r7, [p0], m0
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    mul r5, r2, r1
; AIE2P-NEXT:    mova m0, #-10
; AIE2P-NEXT:    st r5, [p0], m0
; AIE2P-NEXT:    st.s16 r0, [p0], #2
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    add r6, r2, #-1
; AIE2P-NEXT:    mova r7, #16; extend.u16 r6, r6
; AIE2P-NEXT:    lshl r16, r0, r7
; AIE2P-NEXT:    or r6, r6, r16
; AIE2P-NEXT:    mova r17, #5; st r6, [p0], #4
; AIE2P-NEXT:    st.s16 r3, [p0, #10]; lshl r5, r5, r17
; AIE2P-NEXT:    sub r3, r3, r5
; AIE2P-NEXT:    add r16, r1, r4
; AIE2P-NEXT:    mac r2, r2, r2, r16
; AIE2P-NEXT:    add r1, r1, #-1
; AIE2P-NEXT:    add r2, r2, r4
; AIE2P-NEXT:    mova r3, #32; msc r3, r3, r2, r0
; AIE2P-NEXT:    ret lr
; AIE2P-NEXT:    extend.u16 r0, r1 // Delay Slot 5
; AIE2P-NEXT:    lshl r1, r3, r7 // Delay Slot 4
; AIE2P-NEXT:    or r0, r0, r1 // Delay Slot 3
; AIE2P-NEXT:    st r0, [p0, #0] // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
; AIE2P-NEXT:  .LBB0_5: // %sw.bb109
; AIE2P-NEXT:    mova m0, #38; nopb ; add r7, r2, #-1; nopm
; AIE2P-NEXT:    padda [p0], m0; movx r5, #-5
; AIE2P-NEXT:    st.s16 r3, [p0], #2; movxm r16, #2097152
; AIE2P-NEXT:    lshl r6, r0, r5
; AIE2P-NEXT:    extend.u16 r7, r7
; AIE2P-NEXT:    add r6, r6, #-1
; AIE2P-NEXT:    or r7, r7, r16
; AIE2P-NEXT:    extend.u16 r6, r6
; AIE2P-NEXT:    or r6, r6, r16
; AIE2P-NEXT:    st r6, [p0], #4; mul r6, r0, r2
; AIE2P-NEXT:    st r7, [p0], #4
; AIE2P-NEXT:    st r6, [p0], #-16
; AIE2P-NEXT:    st.s16 r4, [p0], #-4
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    st.s16 r1, [p0, #0]
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    mul r1, r6, r1
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    lshl r1, r1, r5
; AIE2P-NEXT:    mova dj0, #26
; AIE2P-NEXT:    st.s16 r3, [p0, dj0]
; AIE2P-NEXT:    msc r3, r3, r0, r2
; AIE2P-NEXT:  .LBB0_6: // %sw.epilog
; AIE2P-NEXT:    nopa ; ret lr
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    nop // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
;
; AIE2PS-LABEL: setup:
; AIE2PS:       // %bb.0: // %entry
; AIE2PS-NEXT:    lda r18, [p1, #12]
; AIE2PS-NEXT:    lda r2, [p1], #4
; AIE2PS-NEXT:    lda r4, [p1], #4
; AIE2PS-NEXT:    lda r0, [p1], #8
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    lda r16, [p1], #4
; AIE2PS-NEXT:    lda r6, [p1, #0]
; AIE2PS-NEXT:    lda r20, [p1, #4]; mov p1, p0
; AIE2PS-NEXT:    st r2, [p1], #4
; AIE2PS-NEXT:    st r4, [p1], #4
; AIE2PS-NEXT:    st r0, [p1], #4
; AIE2PS-NEXT:    st r18, [p1], #4
; AIE2PS-NEXT:    st r16, [p1], #4
; AIE2PS-NEXT:    mova m0, #6; st r6, [p1], #4
; AIE2PS-NEXT:    st r20, [p1], m0
; AIE2PS-NEXT:    st.s16 r22, [p1, #0]
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    mul r22, r6, r16
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    mul r22, r22, r20
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    st.s16 r22, [p1, #4]
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    mova r22, #0
; AIE2PS-NEXT:    mova r22, #4
; AIE2PS-NEXT:    eq r22, r18, r22
; AIE2PS-NEXT:    jnz r22, #.LBB0_5
; AIE2PS-NEXT:    nop // Delay Slot 5
; AIE2PS-NEXT:    nop // Delay Slot 4
; AIE2PS-NEXT:    nop // Delay Slot 3
; AIE2PS-NEXT:    nop // Delay Slot 2
; AIE2PS-NEXT:    nop // Delay Slot 1
; AIE2PS-NEXT:  // %bb.1: // %entry
; AIE2PS-NEXT:    mova r16, #2
; AIE2PS-NEXT:    eq r16, r18, r16
; AIE2PS-NEXT:    jnz r16, #.LBB0_4
; AIE2PS-NEXT:    nop // Delay Slot 5
; AIE2PS-NEXT:    nop // Delay Slot 4
; AIE2PS-NEXT:    nop // Delay Slot 3
; AIE2PS-NEXT:    nop // Delay Slot 2
; AIE2PS-NEXT:    nop // Delay Slot 1
; AIE2PS-NEXT:  // %bb.2: // %entry
; AIE2PS-NEXT:    mova r16, #1
; AIE2PS-NEXT:    ne r16, r18, r16
; AIE2PS-NEXT:    jnz r16, #.LBB0_6
; AIE2PS-NEXT:    nop // Delay Slot 5
; AIE2PS-NEXT:    nop // Delay Slot 4
; AIE2PS-NEXT:    nop // Delay Slot 3
; AIE2PS-NEXT:    nop // Delay Slot 2
; AIE2PS-NEXT:    nop // Delay Slot 1
; AIE2PS-NEXT:  // %bb.3: // %sw.bb
; AIE2PS-NEXT:    movxm r20, #65535
; AIE2PS-NEXT:    mova r16, #-5; movxm r26, #2097152
; AIE2PS-NEXT:    lshl r18, r0, r16
; AIE2PS-NEXT:    add r22, r4, r20
; AIE2PS-NEXT:    add r20, r2, r20
; AIE2PS-NEXT:    mul r4, r0, r4
; AIE2PS-NEXT:    add r18, r18, #-1
; AIE2PS-NEXT:    mul r22, r0, r22
; AIE2PS-NEXT:    mova m0, #38; msc r28, r28, r4, r20; mov r28, #32
; AIE2PS-NEXT:    padda [p0], m0; extend.u16 r18, r18; mov r24, #16
; AIE2PS-NEXT:    st.s16 r22, [p0], #2; lshl r22, r22, r24
; AIE2PS-NEXT:    add r22, r22, r26
; AIE2PS-NEXT:    add r26, r2, #-1
; AIE2PS-NEXT:    lshl r24, r28, r24
; AIE2PS-NEXT:    or r18, r18, r22
; AIE2PS-NEXT:    mova r22, #32; extend.u16 r20, r26
; AIE2PS-NEXT:    or r20, r20, r24
; AIE2PS-NEXT:    st r18, [p0], #4; mul r18, r0, r2
; AIE2PS-NEXT:    st r20, [p0], #4
; AIE2PS-NEXT:    st r18, [p0], #-16
; AIE2PS-NEXT:    st.s16 r6, [p0], #-4
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    st.s16 r4, [p0, #0]
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    mul r4, r4, r2
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    lshl r4, r4, r16
; AIE2PS-NEXT:    mova dj0, #26
; AIE2PS-NEXT:    st.s16 r22, [p0, dj0]
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    ret lr
; AIE2PS-NEXT:    nop // Delay Slot 5
; AIE2PS-NEXT:    msc r22, r22, r0, r2 // Delay Slot 4
; AIE2PS-NEXT:    nop // Delay Slot 3
; AIE2PS-NEXT:    nop // Delay Slot 2
; AIE2PS-NEXT:    nop // Delay Slot 1
; AIE2PS-NEXT:  .LBB0_4: // %sw.bb51
; AIE2PS-NEXT:    mova m0, #28; nopb ; nopxm
; AIE2PS-NEXT:    padda [p0], m0
; AIE2PS-NEXT:    st.s16 r6, [p0], #4
; AIE2PS-NEXT:    mul r6, r0, r4
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    mul r6, r6, r2
; AIE2PS-NEXT:    movx r16, #-5
; AIE2PS-NEXT:    lshl r6, r6, r16
; AIE2PS-NEXT:    mova m0, #16
; AIE2PS-NEXT:    st.s16 r20, [p0], m0
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    mul r6, r4, r2
; AIE2PS-NEXT:    mova m0, #-10
; AIE2PS-NEXT:    st r6, [p0], m0
; AIE2PS-NEXT:    st.s16 r0, [p0], #2; movxm r18, #65535
; AIE2PS-NEXT:    add r16, r4, #-1
; AIE2PS-NEXT:    extend.u16 r16, r16
; AIE2PS-NEXT:    add r20, r2, r18
; AIE2PS-NEXT:    mova r22, #16; mac r4, r4, r4, r20
; AIE2PS-NEXT:    lshl r20, r0, r22
; AIE2PS-NEXT:    or r16, r16, r20
; AIE2PS-NEXT:    st r16, [p0], #4
; AIE2PS-NEXT:    st.s16 r6, [p0, #10]
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    mova r20, #5; add r2, r2, #-1
; AIE2PS-NEXT:    lshl r6, r6, r20
; AIE2PS-NEXT:    mova r16, #32; add r4, r4, r18
; AIE2PS-NEXT:    sub r6, r16, r6
; AIE2PS-NEXT:    mova r6, #32; msc r6, r6, r4, r0
; AIE2PS-NEXT:    ret lr
; AIE2PS-NEXT:    extend.u16 r0, r2 // Delay Slot 5
; AIE2PS-NEXT:    lshl r2, r6, r22 // Delay Slot 4
; AIE2PS-NEXT:    or r0, r0, r2 // Delay Slot 3
; AIE2PS-NEXT:    st r0, [p0, #0] // Delay Slot 2
; AIE2PS-NEXT:    nop // Delay Slot 1
; AIE2PS-NEXT:  .LBB0_5: // %sw.bb109
; AIE2PS-NEXT:    mova m0, #38; add r22, r4, #-1; nopm
; AIE2PS-NEXT:    padda [p0], m0; movx r6, #-5
; AIE2PS-NEXT:    st.s16 r20, [p0], #2; movxm r24, #2097152
; AIE2PS-NEXT:    lshl r18, r0, r6
; AIE2PS-NEXT:    extend.u16 r22, r22
; AIE2PS-NEXT:    add r18, r18, #-1
; AIE2PS-NEXT:    or r22, r22, r24
; AIE2PS-NEXT:    mova r20, #32; extend.u16 r18, r18
; AIE2PS-NEXT:    or r18, r18, r24
; AIE2PS-NEXT:    st r18, [p0], #4; mul r18, r0, r4
; AIE2PS-NEXT:    st r22, [p0], #4
; AIE2PS-NEXT:    st r18, [p0], #-16
; AIE2PS-NEXT:    st.s16 r16, [p0], #-4
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    st.s16 r2, [p0, #0]
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    mul r2, r18, r2
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    lshl r2, r2, r6
; AIE2PS-NEXT:    mova dj0, #26
; AIE2PS-NEXT:    st.s16 r20, [p0, dj0]
; AIE2PS-NEXT:    msc r20, r20, r0, r4
; AIE2PS-NEXT:  .LBB0_6: // %sw.epilog
; AIE2PS-NEXT:    nopa ; ret lr
; AIE2PS-NEXT:    nop // Delay Slot 5
; AIE2PS-NEXT:    nop // Delay Slot 4
; AIE2PS-NEXT:    nop // Delay Slot 3
; AIE2PS-NEXT:    nop // Delay Slot 2
; AIE2PS-NEXT:    nop // Delay Slot 1
entry:
  %0 = load i32, ptr %rtps_void, align 4, !tbaa !4
  store i32 %0, ptr %params, align 64, !tbaa !8
  %arrayidx1 = getelementptr inbounds nuw i8, ptr %rtps_void, i20 4
  %1 = load i32, ptr %arrayidx1, align 4, !tbaa !4
  %sv_channel = getelementptr inbounds nuw i8, ptr %params, i20 4
  store i32 %1, ptr %sv_channel, align 4, !tbaa !12
  %arrayidx2 = getelementptr inbounds nuw i8, ptr %rtps_void, i20 8
  %2 = load i32, ptr %arrayidx2, align 4, !tbaa !4
  %sv_width = getelementptr inbounds nuw i8, ptr %params, i20 8
  store i32 %2, ptr %sv_width, align 8, !tbaa !13
  %arrayidx3 = getelementptr inbounds nuw i8, ptr %rtps_void, i20 12
  %3 = load i32, ptr %arrayidx3, align 4, !tbaa !4
  %reduce_axis = getelementptr inbounds nuw i8, ptr %params, i20 12
  store i32 %3, ptr %reduce_axis, align 4, !tbaa !14
  %arrayidx4 = getelementptr inbounds nuw i8, ptr %rtps_void, i20 16
  %4 = load i32, ptr %arrayidx4, align 4, !tbaa !4
  %loop_num_height = getelementptr inbounds nuw i8, ptr %params, i20 16
  store i32 %4, ptr %loop_num_height, align 16, !tbaa !15
  %arrayidx5 = getelementptr inbounds nuw i8, ptr %rtps_void, i20 20
  %5 = load i32, ptr %arrayidx5, align 4, !tbaa !4
  %loop_num_channel = getelementptr inbounds nuw i8, ptr %params, i20 20
  store i32 %5, ptr %loop_num_channel, align 4, !tbaa !16
  %arrayidx6 = getelementptr inbounds nuw i8, ptr %rtps_void, i20 24
  %6 = load i32, ptr %arrayidx6, align 4, !tbaa !4
  %loop_num_width = getelementptr inbounds nuw i8, ptr %params, i20 24
  store i32 %6, ptr %loop_num_width, align 8, !tbaa !17
  %mul = mul i32 %5, %4
  %mul10 = mul i32 %mul, %6
  %conv = trunc i32 %mul10 to i16
  %all_loop_num = getelementptr inbounds nuw i8, ptr %params, i20 30
  store i16 %conv, ptr %all_loop_num, align 2, !tbaa !18
  %curr_depth_iter = getelementptr inbounds nuw i8, ptr %params, i20 34
  store i16 0, ptr %curr_depth_iter, align 2, !tbaa !19
  switch i32 %3, label %sw.epilog [
  i32 1, label %sw.bb
  i32 2, label %sw.bb51
  i32 4, label %sw.bb109
  ]

sw.bb:                                            ; preds = %entry
  %i_ptr_inc1 = getelementptr inbounds nuw i8, ptr %params, i20 38
  store i16 32, ptr %i_ptr_inc1, align 2, !tbaa !20
  %div103 = lshr i32 %2, 5
  %7 = trunc i32 %div103 to i16
  %conv13 = add i16 %7, -1
  %i_ptr_size1 = getelementptr inbounds nuw i8, ptr %params, i20 40
  store i16 %conv13, ptr %i_ptr_size1, align 8, !tbaa !21
  %mul18104 = add i32 %1, 65535
  %reass.sub = mul i32 %2, %mul18104
  %8 = trunc i32 %reass.sub to i16
  %conv19 = add i16 %8, 32
  %i_ptr_inc2 = getelementptr inbounds nuw i8, ptr %params, i20 42
  store i16 %conv19, ptr %i_ptr_inc2, align 2, !tbaa !22
  %9 = trunc i32 %0 to i16
  %conv22 = add i16 %9, -1
  %i_ptr_size2 = getelementptr inbounds nuw i8, ptr %params, i20 44
  store i16 %conv22, ptr %i_ptr_size2, align 4, !tbaa !23
  %sub24 = add i32 %0, 65535
  %mul26 = mul i32 %2, %1
  %mul28 = mul i32 %mul26, %sub24
  %10 = trunc i32 %mul28 to i16
  %conv30 = sub i16 32, %10
  %i_ptr_offset = getelementptr inbounds nuw i8, ptr %params, i20 46
  store i16 %conv30, ptr %i_ptr_offset, align 2, !tbaa !24
  %mul33 = mul i32 %2, %0
  %output_size = getelementptr inbounds nuw i8, ptr %params, i20 48
  store i32 %mul33, ptr %output_size, align 16, !tbaa !25
  %conv35 = trunc i32 %5 to i16
  %loop_width = getelementptr inbounds nuw i8, ptr %params, i20 32
  store i16 %conv35, ptr %loop_width, align 32, !tbaa !26
  %mul40 = mul i32 %mul26, %0
  %div41105 = lshr i32 %mul40, 5
  %conv42 = trunc i32 %div41105 to i16
  %num_iter = getelementptr inbounds nuw i8, ptr %params, i20 28
  store i16 %conv42, ptr %num_iter, align 4, !tbaa !27
  %11 = trunc i32 %mul33 to i16
  %conv45 = sub i16 32, %11
  %p_out_offset = getelementptr inbounds nuw i8, ptr %params, i20 54
  store i16 %conv45, ptr %p_out_offset, align 2, !tbaa !28
  %div47106 = lshr i32 %mul33, 5
  %12 = trunc i32 %div47106 to i16
  br label %sw.epilog

sw.bb51:                                          ; preds = %entry
  %mul54 = mul i32 %2, %1
  %mul56 = mul i32 %mul54, %0
  %div57102 = lshr i32 %mul56, 5
  %conv58 = trunc i32 %div57102 to i16
  %num_iter59 = getelementptr inbounds nuw i8, ptr %params, i20 28
  store i16 %conv58, ptr %num_iter59, align 4, !tbaa !27
  %conv61 = trunc i32 %6 to i16
  %loop_width62 = getelementptr inbounds nuw i8, ptr %params, i20 32
  store i16 %conv61, ptr %loop_width62, align 32, !tbaa !26
  %mul65 = mul i32 %1, %0
  %output_size66 = getelementptr inbounds nuw i8, ptr %params, i20 48
  store i32 %mul65, ptr %output_size66, align 16, !tbaa !25
  %conv68 = trunc i32 %2 to i16
  %i_ptr_inc169 = getelementptr inbounds nuw i8, ptr %params, i20 38
  store i16 %conv68, ptr %i_ptr_inc169, align 2, !tbaa !20
  %13 = trunc i32 %1 to i16
  %conv72 = add i16 %13, -1
  %i_ptr_size173 = getelementptr inbounds nuw i8, ptr %params, i20 40
  store i16 %conv72, ptr %i_ptr_size173, align 8, !tbaa !21
  %i_ptr_inc276 = getelementptr inbounds nuw i8, ptr %params, i20 42
  store i16 %conv68, ptr %i_ptr_inc276, align 2, !tbaa !22
  %14 = trunc i32 %0 to i16
  %conv79 = add i16 %14, -1
  %i_ptr_size280 = getelementptr inbounds nuw i8, ptr %params, i20 44
  store i16 %conv79, ptr %i_ptr_size280, align 4, !tbaa !23
  %sub82 = add i32 %0, 65535
  %mul86 = mul i32 %1, %sub82
  %sub89 = add i32 %1, 65535
  %reass.add = add i32 %sub89, %mul86
  %reass.mul = mul i32 %reass.add, %2
  %15 = trunc i32 %reass.mul to i16
  %conv93 = sub i16 32, %15
  %i_ptr_offset94 = getelementptr inbounds nuw i8, ptr %params, i20 46
  store i16 %conv93, ptr %i_ptr_offset94, align 2, !tbaa !24
  %mul97.tr = trunc i32 %mul65 to i16
  %16 = shl i16 %mul97.tr, 5
  %conv100 = sub i16 32, %16
  %p_out_offset101 = getelementptr inbounds nuw i8, ptr %params, i20 54
  store i16 %conv100, ptr %p_out_offset101, align 2, !tbaa !28
  br label %sw.epilog

sw.bb109:                                         ; preds = %entry
  %i_ptr_inc1110 = getelementptr inbounds nuw i8, ptr %params, i20 38
  store i16 32, ptr %i_ptr_inc1110, align 2, !tbaa !20
  %div11299 = lshr i32 %2, 5
  %17 = trunc i32 %div11299 to i16
  %conv114 = add i16 %17, -1
  %i_ptr_size1115 = getelementptr inbounds nuw i8, ptr %params, i20 40
  store i16 %conv114, ptr %i_ptr_size1115, align 8, !tbaa !21
  %i_ptr_inc2116 = getelementptr inbounds nuw i8, ptr %params, i20 42
  store i16 32, ptr %i_ptr_inc2116, align 2, !tbaa !22
  %18 = trunc i32 %1 to i16
  %conv119 = add i16 %18, -1
  %i_ptr_size2120 = getelementptr inbounds nuw i8, ptr %params, i20 44
  store i16 %conv119, ptr %i_ptr_size2120, align 4, !tbaa !23
  %i_ptr_offset121 = getelementptr inbounds nuw i8, ptr %params, i20 46
  store i16 32, ptr %i_ptr_offset121, align 2, !tbaa !24
  %mul124 = mul i32 %2, %1
  %output_size125 = getelementptr inbounds nuw i8, ptr %params, i20 48
  store i32 %mul124, ptr %output_size125, align 16, !tbaa !25
  %conv127 = trunc i32 %4 to i16
  %loop_width128 = getelementptr inbounds nuw i8, ptr %params, i20 32
  store i16 %conv127, ptr %loop_width128, align 32, !tbaa !26
  %mul133 = mul i32 %mul124, %0
  %div134100 = lshr i32 %mul133, 5
  %conv135 = trunc i32 %div134100 to i16
  %num_iter136 = getelementptr inbounds nuw i8, ptr %params, i20 28
  store i16 %conv135, ptr %num_iter136, align 4, !tbaa !27
  %19 = trunc i32 %mul124 to i16
  %conv139 = sub i16 32, %19
  %p_out_offset140 = getelementptr inbounds nuw i8, ptr %params, i20 54
  store i16 %conv139, ptr %p_out_offset140, align 2, !tbaa !28
  br label %sw.epilog

sw.epilog:                                        ; preds = sw.bb109, %entry
  ret void
}

!4 = !{!5, !5, i64 0}
!5 = !{!"int", !6, i64 0}
!6 = !{!"omnipotent char", !7, i64 0}
!7 = !{!"Simple C++ TBAA"}
!8 = !{!9, !5, i64 0}
!9 = !{!"_ZTS15reduce_params_tI18reducemax_params_tI8bfloat16EE", !5, i64 0, !5, i64 4, !5, i64 8, !5, i64 12, !5, i64 16, !5, i64 20, !5, i64 24, !10, i64 28, !10, i64 30, !10, i64 32, !10, i64 34, !10, i64 36, !10, i64 38, !10, i64 40, !10, i64 42, !10, i64 44, !10, i64 46, !5, i64 48, !10, i64 52, !10, i64 54, !11, i64 56}
!10 = !{!"short", !6, i64 0}
!11 = !{!"_ZTS18reducemax_params_tI8bfloat16E"}
!12 = !{!9, !5, i64 4}
!13 = !{!9, !5, i64 8}
!14 = !{!9, !5, i64 12}
!15 = !{!9, !5, i64 16}
!16 = !{!9, !5, i64 20}
!17 = !{!9, !5, i64 24}
!18 = !{!9, !10, i64 30}
!19 = !{!9, !10, i64 34}
!20 = !{!9, !10, i64 38}
!21 = !{!9, !10, i64 40}
!22 = !{!9, !10, i64 42}
!23 = !{!9, !10, i64 44}
!24 = !{!9, !10, i64 46}
!25 = !{!9, !5, i64 48}
!26 = !{!9, !10, i64 32}
!27 = !{!9, !10, i64 28}
!28 = !{!9, !10, i64 54}
!29 = !{!9, !10, i64 52}
