; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
; RUN: opt -S -mtriple=aie2p -passes=loop-unroll %s -o - | FileCheck %s

; Verify that we can unroll scalar loops (TTI filter test).

%"struct1" = type { %"struct2", %"struct4" }
%"struct2" = type { [4 x %"struct3"] }
%"struct3" = type { i32, i32 }
%"struct4" = type { %"struct5" }
%"struct5" = type { %"struct6", %"struct9" }
%"struct6" = type { %"struct7" }
%"struct7" = type { i32, i32, i32, i32, i32 }
%"struct9" = type { i32 }

define void @_Z4testv(ptr dead_on_unwind noalias nocapture writable sret(%"struct1") align 4 %agg.result) {
; CHECK-LABEL: define void @_Z4testv(
; CHECK-SAME: ptr dead_on_unwind noalias writable sret([[STRUCT1:%.*]]) align 4 captures(none) [[AGG_RESULT:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[REF_TMP_I:%.*]] = alloca [[STRUCT2:%.*]], align 4
; CHECK-NEXT:    store i64 429496729601, ptr [[REF_TMP_I]], align 4
; CHECK-NEXT:    [[ARRAYINIT_ELEMENT_I:%.*]] = getelementptr inbounds i8, ptr [[REF_TMP_I]], i20 8
; CHECK-NEXT:    store i64 1, ptr [[ARRAYINIT_ELEMENT_I]], align 4
; CHECK-NEXT:    [[ARRAYINIT_ELEMENT7_I:%.*]] = getelementptr inbounds i8, ptr [[REF_TMP_I]], i20 16
; CHECK-NEXT:    store i64 429496729700, ptr [[ARRAYINIT_ELEMENT7_I]], align 4
; CHECK-NEXT:    [[ARRAYINIT_ELEMENT8_I:%.*]] = getelementptr inbounds i8, ptr [[REF_TMP_I]], i20 24
; CHECK-NEXT:    store i64 4294967396, ptr [[ARRAYINIT_ELEMENT8_I]], align 4
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [4 x %struct3], ptr [[REF_TMP_I]], i20 0, i20 3
; CHECK-NEXT:    [[STEP:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX]], i20 4
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[STEP]], align 4
; CHECK-NEXT:    [[MUL:%.*]] = shl i32 [[TMP0]], 6
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[SUB1:%.*]] = add i32 [[TMP1]], -1
; CHECK-NEXT:    [[MUL3:%.*]] = mul i32 [[SUB1]], [[MUL]]
; CHECK-NEXT:    [[ARRAY:%.*]] = getelementptr inbounds [4 x %struct3], ptr [[AGG_RESULT]], i20 0, i20 3
; CHECK-NEXT:    [[EXT:%.*]] = zext i32 [[MUL]] to i64
; CHECK-NEXT:    [[SHIFT:%.*]] = shl nuw i64 [[EXT]], 32
; CHECK-NEXT:    [[ZEXT1:%.*]] = zext i32 [[SUB1]] to i64
; CHECK-NEXT:    [[OR1:%.*]] = or disjoint i64 [[SHIFT]], [[ZEXT1]]
; CHECK-NEXT:    store i64 [[OR1]], ptr [[ARRAY]], align 4
; CHECK-NEXT:    [[ARRAYIDX_1:%.*]] = getelementptr inbounds [4 x %struct3], ptr [[REF_TMP_I]], i20 0, i20 2
; CHECK-NEXT:    [[STEP_1:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX_1]], i20 4
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[STEP_1]], align 4
; CHECK-NEXT:    [[MUL_1:%.*]] = shl i32 [[TMP2]], 6
; CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[ARRAYIDX_1]], align 4
; CHECK-NEXT:    [[SUB1_1:%.*]] = add i32 [[TMP3]], -1
; CHECK-NEXT:    [[MUL3_1:%.*]] = mul i32 [[SUB1_1]], [[MUL_1]]
; CHECK-NEXT:    [[SUB2_1:%.*]] = sub nsw i32 [[MUL_1]], [[MUL3]]
; CHECK-NEXT:    [[ARRAY_1:%.*]] = getelementptr inbounds [4 x %struct3], ptr [[AGG_RESULT]], i20 0, i20 2
; CHECK-NEXT:    [[EXT_1:%.*]] = zext i32 [[SUB2_1]] to i64
; CHECK-NEXT:    [[SHIFT_1:%.*]] = shl nuw i64 [[EXT_1]], 32
; CHECK-NEXT:    [[ZEXT1_1:%.*]] = zext i32 [[SUB1_1]] to i64
; CHECK-NEXT:    [[OR1_1:%.*]] = or disjoint i64 [[SHIFT_1]], [[ZEXT1_1]]
; CHECK-NEXT:    store i64 [[OR1_1]], ptr [[ARRAY_1]], align 4
; CHECK-NEXT:    [[ADD1_1:%.*]] = add nsw i32 [[MUL3_1]], [[MUL3]]
; CHECK-NEXT:    [[ARRAYIDX_2:%.*]] = getelementptr inbounds [4 x %struct3], ptr [[REF_TMP_I]], i20 0, i20 1
; CHECK-NEXT:    [[STEP_2:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX_2]], i20 4
; CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[STEP_2]], align 4
; CHECK-NEXT:    [[MUL_2:%.*]] = shl i32 [[TMP4]], 6
; CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[ARRAYIDX_2]], align 4
; CHECK-NEXT:    [[SUB1_2:%.*]] = add i32 [[TMP5]], -1
; CHECK-NEXT:    [[MUL3_2:%.*]] = mul i32 [[SUB1_2]], [[MUL_2]]
; CHECK-NEXT:    [[SUB2_2:%.*]] = sub nsw i32 [[MUL_2]], [[ADD1_1]]
; CHECK-NEXT:    [[ARRAY_2:%.*]] = getelementptr inbounds [4 x %struct3], ptr [[AGG_RESULT]], i20 0, i20 1
; CHECK-NEXT:    [[EXT_2:%.*]] = zext i32 [[SUB2_2]] to i64
; CHECK-NEXT:    [[SHIFT_2:%.*]] = shl nuw i64 [[EXT_2]], 32
; CHECK-NEXT:    [[ZEXT1_2:%.*]] = zext i32 [[SUB1_2]] to i64
; CHECK-NEXT:    [[OR1_2:%.*]] = or disjoint i64 [[SHIFT_2]], [[ZEXT1_2]]
; CHECK-NEXT:    store i64 [[OR1_2]], ptr [[ARRAY_2]], align 4
; CHECK-NEXT:    [[ADD1_2:%.*]] = add nsw i32 [[MUL3_2]], [[ADD1_1]]
; CHECK-NEXT:    [[STEP_3:%.*]] = getelementptr inbounds i8, ptr [[REF_TMP_I]], i20 4
; CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr [[STEP_3]], align 4
; CHECK-NEXT:    [[MUL_3:%.*]] = shl i32 [[TMP6]], 6
; CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[REF_TMP_I]], align 4
; CHECK-NEXT:    [[SUB1_3:%.*]] = add i32 [[TMP7]], -1
; CHECK-NEXT:    [[SUB2_3:%.*]] = sub nsw i32 [[MUL_3]], [[ADD1_2]]
; CHECK-NEXT:    [[EXT_3:%.*]] = zext i32 [[SUB2_3]] to i64
; CHECK-NEXT:    [[SHIFT_3:%.*]] = shl nuw i64 [[EXT_3]], 32
; CHECK-NEXT:    [[ZEXT1_3:%.*]] = zext i32 [[SUB1_3]] to i64
; CHECK-NEXT:    [[OR1_3:%.*]] = or disjoint i64 [[SHIFT_3]], [[ZEXT1_3]]
; CHECK-NEXT:    store i64 [[OR1_3]], ptr [[AGG_RESULT]], align 4
; CHECK-NEXT:    [[DESC:%.*]] = getelementptr inbounds i8, ptr [[AGG_RESULT]], i20 32
; CHECK-NEXT:    [[ARRAYIDX3:%.*]] = getelementptr inbounds i8, ptr [[AGG_RESULT]], i20 24
; CHECK-NEXT:    [[STEP4:%.*]] = getelementptr inbounds i8, ptr [[AGG_RESULT]], i20 28
; CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[STEP4]], align 4
; CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[ARRAYIDX3]], align 4
; CHECK-NEXT:    [[MUL4:%.*]] = mul i32 [[TMP9]], [[TMP8]]
; CHECK-NEXT:    [[ARRAYIDX_I29_I_I_I:%.*]] = getelementptr inbounds i8, ptr [[AGG_RESULT]], i20 16
; CHECK-NEXT:    [[TMP10:%.*]] = load i32, ptr [[ARRAYIDX_I29_I_I_I]], align 4
; CHECK-NEXT:    [[STEP7:%.*]] = getelementptr inbounds i8, ptr [[AGG_RESULT]], i20 20
; CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr [[STEP7]], align 4
; CHECK-NEXT:    [[ADD8:%.*]] = add nsw i32 [[TMP11]], [[MUL4]]
; CHECK-NEXT:    [[ARRAYIDX31:%.*]] = getelementptr inbounds i8, ptr [[AGG_RESULT]], i20 8
; CHECK-NEXT:    [[TMP12:%.*]] = load i32, ptr [[ARRAYIDX31]], align 4
; CHECK-NEXT:    [[STEP12:%.*]] = getelementptr inbounds i8, ptr [[AGG_RESULT]], i20 12
; CHECK-NEXT:    [[TMP13:%.*]] = load i32, ptr [[STEP12]], align 4
; CHECK-NEXT:    [[ADD13:%.*]] = add nsw i32 [[TMP13]], [[MUL4]]
; CHECK-NEXT:    [[ADD131:%.*]] = getelementptr inbounds i8, ptr [[AGG_RESULT]], i20 4
; CHECK-NEXT:    [[TMP14:%.*]] = load i32, ptr [[ADD131]], align 4
; CHECK-NEXT:    [[ADD16:%.*]] = add nsw i32 [[TMP14]], [[MUL4]]
; CHECK-NEXT:    store i32 [[TMP10]], ptr [[DESC]], align 4
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr inbounds i8, ptr [[AGG_RESULT]], i20 36
; CHECK-NEXT:    store i32 [[ADD8]], ptr [[GEP1]], align 4
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr inbounds i8, ptr [[AGG_RESULT]], i20 40
; CHECK-NEXT:    store i32 [[TMP12]], ptr [[GEP2]], align 4
; CHECK-NEXT:    [[RGEP3:%.*]] = getelementptr inbounds i8, ptr [[AGG_RESULT]], i20 44
; CHECK-NEXT:    store i32 [[ADD13]], ptr [[RGEP3]], align 4
; CHECK-NEXT:    [[GEP4:%.*]] = getelementptr inbounds i8, ptr [[AGG_RESULT]], i20 48
; CHECK-NEXT:    store i32 [[ADD16]], ptr [[GEP4]], align 4
; CHECK-NEXT:    [[TMP15:%.*]] = getelementptr inbounds i8, ptr [[AGG_RESULT]], i20 52
; CHECK-NEXT:    store i32 [[TMP8]], ptr [[TMP15]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %ref.tmp.i = alloca %"struct2", align 4
  store i64 429496729601, ptr %ref.tmp.i, align 4
  %arrayinit.element.i = getelementptr inbounds i8, ptr %ref.tmp.i, i20 8
  store i64 1, ptr %arrayinit.element.i, align 4
  %arrayinit.element7.i = getelementptr inbounds i8, ptr %ref.tmp.i, i20 16
  store i64 429496729700, ptr %arrayinit.element7.i, align 4
  %arrayinit.element8.i = getelementptr inbounds i8, ptr %ref.tmp.i, i20 24
  store i64 4294967396, ptr %arrayinit.element8.i, align 4
  br label %for.body

for.body:                                   ; preds = %for.body, %entry
  %rollback = phi i32 [ 0, %entry ], [ %add1, %for.body ]
  %i = phi i32 [ 3, %entry ], [ %dec, %for.body ]
  %0 = trunc i32 %i to i20
  %arrayidx = getelementptr inbounds [4 x %"struct3"], ptr %ref.tmp.i, i20 0, i20 %0
  %step = getelementptr inbounds i8, ptr %arrayidx, i20 4
  %1 = load i32, ptr %step, align 4
  %mul = shl i32 %1, 6
  %2 = load i32, ptr %arrayidx, align 4
  %sub1 = add i32 %2, -1
  %mul3 = mul i32 %sub1, %mul
  %sub2 = sub nsw i32 %mul, %rollback
  %array = getelementptr inbounds [4 x %"struct3"], ptr %agg.result, i20 0, i20 %0
  %ext = zext i32 %sub2 to i64
  %shift = shl nuw i64 %ext, 32
  %zext1 = zext i32 %sub1 to i64
  %or1 = or disjoint i64 %shift, %zext1
  store i64 %or1, ptr %array, align 4
  %add1 = add nsw i32 %mul3, %rollback
  %dec = add nsw i32 %i, -1
  %cmp = icmp eq i32 %dec, -1
  br i1 %cmp, label %exit, label %for.body

exit: ; preds = %for.body
  %desc = getelementptr inbounds i8, ptr %agg.result, i20 32
  %arrayidx3 = getelementptr inbounds i8, ptr %agg.result, i20 24
  %step4 = getelementptr inbounds i8, ptr %agg.result, i20 28
  %3 = load i32, ptr %step4, align 4
  %4 = load i32, ptr %arrayidx3, align 4
  %mul4 = mul i32 %4, %3
  %arrayidx.i29.i.i.i = getelementptr inbounds i8, ptr %agg.result, i20 16
  %5 = load i32, ptr %arrayidx.i29.i.i.i, align 4
  %step7 = getelementptr inbounds i8, ptr %agg.result, i20 20
  %6 = load i32, ptr %step7, align 4
  %add8 = add nsw i32 %6, %mul4
  %arrayidx31 = getelementptr inbounds i8, ptr %agg.result, i20 8
  %7 = load i32, ptr %arrayidx31, align 4
  %step12 = getelementptr inbounds i8, ptr %agg.result, i20 12
  %8 = load i32, ptr %step12, align 4
  %add13 = add nsw i32 %8, %mul4
  %add131 = getelementptr inbounds i8, ptr %agg.result, i20 4
  %9 = load i32, ptr %add131, align 4
  %add16 = add nsw i32 %9, %mul4
  store i32 %5, ptr %desc, align 4
  %gep1 = getelementptr inbounds i8, ptr %agg.result, i20 36
  store i32 %add8, ptr %gep1, align 4
  %gep2 = getelementptr inbounds i8, ptr %agg.result, i20 40
  store i32 %7, ptr %gep2, align 4
  %rgep3 = getelementptr inbounds i8, ptr %agg.result, i20 44
  store i32 %add13, ptr %rgep3, align 4
  %gep4 = getelementptr inbounds i8, ptr %agg.result, i20 48
  store i32 %add16, ptr %gep4, align 4
  %10 = getelementptr inbounds i8, ptr %agg.result, i20 52
  store i32 %3, ptr %10, align 4
  ret void
}

!llvm.linker.options = !{}
!llvm.module.flags = !{!0}
!llvm.ident = !{!1}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{!"clang version 19.0.0git"}
