; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
; RUN: opt -mtriple=aie2p -passes=load-store-vectorizer -S < %s | FileCheck %s

  define dso_local void @_Z16four_byte_storesP2B4(ptr nocapture writeonly initializes((0, 4)) %B) {
; CHECK-LABEL: @_Z16four_byte_storesP2B4(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    store <4 x i8> <i8 1, i8 2, i8 3, i8 4>, ptr [[B:%.*]], align 32, !tbaa [[TBAA2:![0-9]+]]
; CHECK-NEXT:    ret void
;
  entry:
  store i8 1, ptr %B, align 32, !tbaa !2
  %arrayidx2 = getelementptr inbounds nuw i8, ptr %B, i20 1
  store i8 2, ptr %arrayidx2, align 1, !tbaa !2
  %arrayidx4 = getelementptr inbounds nuw i8, ptr %B, i20 2
  store i8 3, ptr %arrayidx4, align 2, !tbaa !2
  %arrayidx6 = getelementptr inbounds nuw i8, ptr %B, i20 3
  store i8 4, ptr %arrayidx6, align 1, !tbaa !2
  ret void
  }

  define dso_local void @_Z16five_byte_storesP2B5(ptr nocapture writeonly initializes((0, 5)) %B) {
; CHECK-LABEL: @_Z16five_byte_storesP2B5(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    store <4 x i8> <i8 1, i8 2, i8 3, i8 4>, ptr [[B:%.*]], align 32, !tbaa [[TBAA2]]
; CHECK-NEXT:    [[ARRAYIDX8:%.*]] = getelementptr inbounds nuw i8, ptr [[B]], i20 4
; CHECK-NEXT:    store i8 5, ptr [[ARRAYIDX8]], align 4, !tbaa [[TBAA2]]
; CHECK-NEXT:    ret void
;
  entry:
  store i8 1, ptr %B, align 32, !tbaa !2
  %arrayidx2 = getelementptr inbounds nuw i8, ptr %B, i20 1
  store i8 2, ptr %arrayidx2, align 1, !tbaa !2
  %arrayidx4 = getelementptr inbounds nuw i8, ptr %B, i20 2
  store i8 3, ptr %arrayidx4, align 2, !tbaa !2
  %arrayidx6 = getelementptr inbounds nuw i8, ptr %B, i20 3
  store i8 4, ptr %arrayidx6, align 1, !tbaa !2
  %arrayidx8 = getelementptr inbounds nuw i8, ptr %B, i20 4
  store i8 5, ptr %arrayidx8, align 4, !tbaa !2
  ret void
  }

  ; This should be vectorized to two <2 x i16> stores.

  define dso_local void @_Z17four_short_storesP2S4(ptr nocapture writeonly initializes((0, 8)) %B) {
; CHECK-LABEL: @_Z17four_short_storesP2S4(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    store <2 x i16> <i16 1, i16 2>, ptr [[B:%.*]], align 32, !tbaa [[TBAA5:![0-9]+]]
; CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds nuw i8, ptr [[B]], i20 4
; CHECK-NEXT:    store <2 x i16> <i16 3, i16 4>, ptr [[ARRAYIDX4]], align 4, !tbaa [[TBAA5]]
; CHECK-NEXT:    ret void
;
  entry:
  store i16 1, ptr %B, align 32, !tbaa !5
  %arrayidx2 = getelementptr inbounds nuw i8, ptr %B, i20 2
  store i16 2, ptr %arrayidx2, align 2, !tbaa !5
  %arrayidx4 = getelementptr inbounds nuw i8, ptr %B, i20 4
  store i16 3, ptr %arrayidx4, align 4, !tbaa !5
  %arrayidx6 = getelementptr inbounds nuw i8, ptr %B, i20 6
  store i16 4, ptr %arrayidx6, align 2, !tbaa !5
  ret void
  }

  ; Negative test: alignment does not fit.

  define dso_local void @_Z25four_byte_stores_negativeP9B4NoAlign(ptr nocapture writeonly initializes((0, 4)) %B) {
; CHECK-LABEL: @_Z25four_byte_stores_negativeP9B4NoAlign(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    store i8 1, ptr [[B:%.*]], align 1, !tbaa [[TBAA2]]
; CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds nuw i8, ptr [[B]], i20 1
; CHECK-NEXT:    store i8 2, ptr [[ARRAYIDX2]], align 1, !tbaa [[TBAA2]]
; CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds nuw i8, ptr [[B]], i20 2
; CHECK-NEXT:    store i8 3, ptr [[ARRAYIDX4]], align 1, !tbaa [[TBAA2]]
; CHECK-NEXT:    [[ARRAYIDX6:%.*]] = getelementptr inbounds nuw i8, ptr [[B]], i20 3
; CHECK-NEXT:    store i8 4, ptr [[ARRAYIDX6]], align 1, !tbaa [[TBAA2]]
; CHECK-NEXT:    ret void
;
  entry:
  store i8 1, ptr %B, align 1, !tbaa !2
  %arrayidx2 = getelementptr inbounds nuw i8, ptr %B, i20 1
  store i8 2, ptr %arrayidx2, align 1, !tbaa !2
  %arrayidx4 = getelementptr inbounds nuw i8, ptr %B, i20 2
  store i8 3, ptr %arrayidx4, align 1, !tbaa !2
  %arrayidx6 = getelementptr inbounds nuw i8, ptr %B, i20 3
  store i8 4, ptr %arrayidx6, align 1, !tbaa !2
  ret void
  }

  !llvm.module.flags = !{!0}
  !llvm.ident = !{!1}

  !0 = !{i32 1, !"wchar_size", i32 4}
  !1 = !{!"clang version 20"}
  !2 = !{!3, !3, i64 0}
  !3 = !{!"omnipotent char", !4, i64 0}
  !4 = !{!"Simple C++ TBAA"}
  !5 = !{!6, !6, i64 0}
  !6 = !{!"short", !3, i64 0}
