; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
;
; RUN: opt -mtriple=aie2 -passes=vector-combine -S < %s | FileCheck %s --check-prefixes=CHECK
; RUN: opt -mtriple=aie2p -passes=vector-combine -S < %s | FileCheck %s --check-prefixes=CHECK
; RUN: opt -mtriple=aie2ps -passes=vector-combine -S < %s | FileCheck %s --check-prefixes=CHECK

; Test the widenSubvectorLoad transformation
; This is what actually creates vector loads in real compilation!
; Pattern: load scalar -> insertelement -> shufflevector (identity with padding)
;       -> VectorCombine widens the load

; Test case based on actual pattern seen in compilation
; The scalar load gets widened when used in a shuffle that broadcasts
; Without cost model, this is vectorized.
define <32 x i16> @test_widen_i16_to_v32i16_via_shuffle(ptr align 2 dereferenceable(64) %p) {
; CHECK-LABEL: @test_widen_i16_to_v32i16_via_shuffle(
; CHECK-NEXT:    [[SCALAR:%.*]] = load i16, ptr [[P:%.*]], align 2
; CHECK-NEXT:    [[INSERT:%.*]] = insertelement <32 x i16> poison, i16 [[SCALAR]], i64 0
; CHECK-NEXT:    [[SPLAT:%.*]] = shufflevector <32 x i16> [[INSERT]], <32 x i16> poison, <32 x i32> zeroinitializer
; CHECK-NEXT:    ret <32 x i16> [[SPLAT]]
;
  %scalar = load i16, ptr %p, align 2
  %insert = insertelement <32 x i16> poison, i16 %scalar, i64 0
  %splat = shufflevector <32 x i16> %insert, <32 x i16> poison, <32 x i32> zeroinitializer
  ret <32 x i16> %splat
}

define <16 x i16> @test_broadcast_i16_to_v16i16(ptr align 2 dereferenceable(32) %p) {
; CHECK-LABEL: @test_broadcast_i16_to_v16i16(
; CHECK-NEXT:    [[SCALAR:%.*]] = load i16, ptr [[P:%.*]], align 2
; CHECK-NEXT:    [[INSERT:%.*]] = insertelement <16 x i16> poison, i16 [[SCALAR]], i64 0
; CHECK-NEXT:    [[SPLAT:%.*]] = shufflevector <16 x i16> [[INSERT]], <16 x i16> poison, <16 x i32> zeroinitializer
; CHECK-NEXT:    ret <16 x i16> [[SPLAT]]
;
  %scalar = load i16, ptr %p, align 2
  %insert = insertelement <16 x i16> poison, i16 %scalar, i64 0
  %splat = shufflevector <16 x i16> %insert, <16 x i16> poison, <16 x i32> zeroinitializer
  ret <16 x i16> %splat
}

define <32 x i8> @test_broadcast_i8_to_v32i8(ptr align 1 dereferenceable(32) %p) {
; CHECK-LABEL: @test_broadcast_i8_to_v32i8(
; CHECK-NEXT:    [[SCALAR:%.*]] = load i8, ptr [[P:%.*]], align 1
; CHECK-NEXT:    [[INSERT:%.*]] = insertelement <32 x i8> poison, i8 [[SCALAR]], i64 0
; CHECK-NEXT:    [[SPLAT:%.*]] = shufflevector <32 x i8> [[INSERT]], <32 x i8> poison, <32 x i32> zeroinitializer
; CHECK-NEXT:    ret <32 x i8> [[SPLAT]]
;
  %scalar = load i8, ptr %p, align 1
  %insert = insertelement <32 x i8> poison, i8 %scalar, i64 0
  %splat = shufflevector <32 x i8> %insert, <32 x i8> poison, <32 x i32> zeroinitializer
  ret <32 x i8> %splat
}

define <8 x i32> @test_broadcast_i32_to_v8i32(ptr align 4 dereferenceable(32) %p) {
; CHECK-LABEL: @test_broadcast_i32_to_v8i32(
; CHECK-NEXT:    [[SCALAR:%.*]] = load i32, ptr [[P:%.*]], align 4
; CHECK-NEXT:    [[INSERT:%.*]] = insertelement <8 x i32> poison, i32 [[SCALAR]], i64 0
; CHECK-NEXT:    [[SPLAT:%.*]] = shufflevector <8 x i32> [[INSERT]], <8 x i32> poison, <8 x i32> zeroinitializer
; CHECK-NEXT:    ret <8 x i32> [[SPLAT]]
;
  %scalar = load i32, ptr %p, align 4
  %insert = insertelement <8 x i32> poison, i32 %scalar, i64 0
  %splat = shufflevector <8 x i32> %insert, <8 x i32> poison, <8 x i32> zeroinitializer
  ret <8 x i32> %splat
}

define <32 x i16> @test_unaligned_v32i16_load(ptr align 1 dereferenceable(64) %p) {
; CHECK-LABEL: @test_unaligned_v32i16_load(
; CHECK-NEXT:    [[SCALAR:%.*]] = load i16, ptr [[P:%.*]], align 1
; CHECK-NEXT:    [[INSERT:%.*]] = insertelement <32 x i16> poison, i16 [[SCALAR]], i64 0
; CHECK-NEXT:    [[SPLAT:%.*]] = shufflevector <32 x i16> [[INSERT]], <32 x i16> poison, <32 x i32> zeroinitializer
; CHECK-NEXT:    ret <32 x i16> [[SPLAT]]
;
  %scalar = load i16, ptr %p, align 1
  %insert = insertelement <32 x i16> poison, i16 %scalar, i64 0
  %splat = shufflevector <32 x i16> %insert, <32 x i16> poison, <32 x i32> zeroinitializer
  ret <32 x i16> %splat
}

; For this case, vectorization should be feasible..
define <32 x i16> @test_aligned_v32i16_load(ptr align 64 dereferenceable(64) %p) {
; CHECK-LABEL: @test_aligned_v32i16_load(
; CHECK-NEXT:    [[INSERT:%.*]] = load <32 x i16>, ptr [[P:%.*]], align 64
; CHECK-NEXT:    [[SPLAT:%.*]] = shufflevector <32 x i16> [[INSERT]], <32 x i16> poison, <32 x i32> zeroinitializer
; CHECK-NEXT:    ret <32 x i16> [[SPLAT]]
;
  %scalar = load i16, ptr %p, align 64
  %insert = insertelement <32 x i16> poison, i16 %scalar, i64 0
  %splat = shufflevector <32 x i16> %insert, <32 x i16> poison, <32 x i32> zeroinitializer
  ret <32 x i16> %splat
}

; The cases above exercise widenSubvectorLoad (shufflevector input). The
; cases below exercise vectorizeLoadInsert (insertelement directly returned,
; no shufflevector in source). vectorizeLoadInsert reads
; getMinVectorRegisterBitWidth() to choose the load width directly, so it
; is the path most affected by the AIE 512-bit override (llvm-aie#480).
;
; With the override, scalar loads here widen to a 512-bit vector load
; followed by a shuffle that picks element 0 and leaves the rest poison.
; The wider IR-level load lowers to the natural width: for a 256-bit output
; type, llc emits a single 256-bit `vldb wl0, [p0, #0]` -- the backend
; narrows the load when the shuffle's poison mask makes the upper half
; dead. Codegen is identical to a plain 256-bit IR load.

define <32 x i16> @test_loadinsert_i16_to_v32i16(ptr align 64 dereferenceable(64) %p) {
; CHECK-LABEL: @test_loadinsert_i16_to_v32i16(
; CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i16>, ptr [[P:%.*]], align 64
; CHECK-NEXT:    [[INSERT:%.*]] = shufflevector <32 x i16> [[TMP1]], <32 x i16> poison, <32 x i32> <i32 0, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    ret <32 x i16> [[INSERT]]
;
  %scalar = load i16, ptr %p, align 64
  %insert = insertelement <32 x i16> poison, i16 %scalar, i64 0
  ret <32 x i16> %insert
}

define <16 x i16> @test_loadinsert_i16_to_v16i16(ptr align 64 dereferenceable(64) %p) {
; CHECK-LABEL: @test_loadinsert_i16_to_v16i16(
; CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i16>, ptr [[P:%.*]], align 64
; CHECK-NEXT:    [[INSERT:%.*]] = shufflevector <32 x i16> [[TMP1]], <32 x i16> poison, <16 x i32> <i32 0, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    ret <16 x i16> [[INSERT]]
;
  %scalar = load i16, ptr %p, align 64
  %insert = insertelement <16 x i16> poison, i16 %scalar, i64 0
  ret <16 x i16> %insert
}

define <8 x i32> @test_loadinsert_i32_to_v8i32(ptr align 64 dereferenceable(64) %p) {
; CHECK-LABEL: @test_loadinsert_i32_to_v8i32(
; CHECK-NEXT:    [[TMP1:%.*]] = load <16 x i32>, ptr [[P:%.*]], align 64
; CHECK-NEXT:    [[INSERT:%.*]] = shufflevector <16 x i32> [[TMP1]], <16 x i32> poison, <8 x i32> <i32 0, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    ret <8 x i32> [[INSERT]]
;
  %scalar = load i32, ptr %p, align 64
  %insert = insertelement <8 x i32> poison, i32 %scalar, i64 0
  ret <8 x i32> %insert
}

define <32 x i8> @test_loadinsert_i8_to_v32i8(ptr align 64 dereferenceable(64) %p) {
; CHECK-LABEL: @test_loadinsert_i8_to_v32i8(
; CHECK-NEXT:    [[TMP1:%.*]] = load <64 x i8>, ptr [[P:%.*]], align 64
; CHECK-NEXT:    [[INSERT:%.*]] = shufflevector <64 x i8> [[TMP1]], <64 x i8> poison, <32 x i32> <i32 0, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    ret <32 x i8> [[INSERT]]
;
  %scalar = load i8, ptr %p, align 64
  %insert = insertelement <32 x i8> poison, i8 %scalar, i64 0
  ret <32 x i8> %insert
}

; Insufficient dereferenceable bytes for a 512-bit load: the gating in
; vectorizeLoadInsert bails, leaving the scalar load and insertelement
; intact. This guards the deref check.
define <16 x i16> @test_loadinsert_i16_short_deref(ptr align 32 dereferenceable(32) %p) {
; CHECK-LABEL: @test_loadinsert_i16_short_deref(
; CHECK-NEXT:    [[SCALAR:%.*]] = load i16, ptr [[P:%.*]], align 32
; CHECK-NEXT:    [[INSERT:%.*]] = insertelement <16 x i16> poison, i16 [[SCALAR]], i64 0
; CHECK-NEXT:    ret <16 x i16> [[INSERT]]
;
  %scalar = load i16, ptr %p, align 32
  %insert = insertelement <16 x i16> poison, i16 %scalar, i64 0
  ret <16 x i16> %insert
}
