# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2p --verify-machineinstrs -run-pass=greedy -run-pass=virtregrewriter %s -o - | FileCheck %s

# There is only one eD (dimension) register available, it will then be used for the %0
# virtual register. Here we test that it is properly spilled and then reloaded.

---
  name:            test
  alignment:       16
  legalized:       true
  regBankSelected: true
  selected:        true
  tracksRegLiveness: true
  body:             |
    bb.1.entry:
      liveins: $p0, $d1, $d2, $d3, $d4, $d5, $d6, $d7

    ; CHECK-LABEL: name: test
    ; CHECK: liveins: $d1, $d2, $d3, $d4, $d5, $d6, $d7, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $r0 = MOVA 32
    ; CHECK-NEXT: renamable $m0 = COPY renamable $r0
    ; CHECK-NEXT: renamable $dn0 = COPY renamable $r0
    ; CHECK-NEXT: renamable $dj0 = COPY renamable $r0
    ; CHECK-NEXT: renamable $dc0 = COPY killed renamable $r0
    ; CHECK-NEXT: ST_D_SPILL killed renamable $d0, %stack.0, implicit $sp :: (store (s128) into %stack.0, align 4)
    ; CHECK-NEXT: $d0 = COPY $d1
    ; CHECK-NEXT: $p0, $dc0 = PADDA_2D $p0, $d0, implicit $d1, implicit $d2, implicit $d3, implicit $d4, implicit $d5, implicit $d6, implicit $d7
    ; CHECK-NEXT: renamable $d0 = LDA_D_SPILL %stack.0, implicit $sp :: (load (s128) from %stack.0, align 4)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $d0
      %10:er = MOVA 32
      undef %0.sub_mod:ed = COPY %10 ; -> only $d0 is available for %0
      %0.sub_dim_size:ed = COPY %10
      %0.sub_dim_stride:ed = COPY %10
      %0.sub_dim_count:ed = COPY %10

      $d0 = COPY $d1
      $p0, $dc0 = PADDA_2D $p0, $d0, implicit $d1, implicit $d2, implicit $d3, implicit $d4, implicit $d5, implicit $d6, implicit $d7

      PseudoRET implicit $lr, implicit %0
...
