# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2p --verify-machineinstrs -run-pass=greedy -run-pass=virtregrewriter %s -o - | FileCheck %s

---
name:            test_1024_fifo_scarce_regs
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $cml0, $r0, $p0, $lf1

    ; CHECK-LABEL: name: test_1024_fifo_scarce_regs
    ; CHECK: liveins: $cml0, $lf1, $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $lf0 = COPY $cml0
    ; CHECK-NEXT: VST_FIFO_SPILL killed renamable $lf0, %stack.0, implicit $sp :: (store (s1024) into %stack.0, align 64)
    ; CHECK-NEXT: $lf0 = COPY $lf1
    ; CHECK-NEXT: ST_dms_sts_idx_imm $r0, $p0, 0, implicit $lf0, implicit $lf1
    ; CHECK-NEXT: renamable $lf0 = VLDA_FIFO_SPILL %stack.0, implicit $sp :: (load (s1024) from %stack.0, align 64)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $lf0
    %0:eldfiforeg = COPY $cml0 ; -> only $lf0 is available

    $lf0 = COPY $lf1
    ST_dms_sts_idx_imm $r0, $p0, 0, implicit $lf0, implicit $lf1
    PseudoRET implicit $lr, implicit %0
...

---
name:            test_1024_fifo_caller_saved
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $lf0

    ; CHECK-LABEL: name: test_1024_fifo_caller_saved
    ; CHECK: liveins: $lf0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: VST_FIFO_SPILL $lf0, %stack.0, implicit $sp :: (store (s1024) into %stack.0, align 64)
    ; CHECK-NEXT: PseudoJL 32, csr_aie2p, implicit-def $lr
    ; CHECK-NEXT: renamable $lf0 = VLDA_FIFO_SPILL %stack.0, implicit $sp :: (load (s1024) from %stack.0, align 64)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $lf0
    %0:eldfiforeg = COPY $lf0
    PseudoJL 32, csr_aie2p, implicit-def $lr
    PseudoRET implicit $lr, implicit %0
...



---
name:            test_1024_fifo_sf_scarce_regs
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $cml0, $r0, $p0, $y1

    ; CHECK-LABEL: name: test_1024_fifo_sf_scarce_regs
    ; CHECK: liveins: $cml0, $p0, $r0, $y1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $sf = COPY $cml0
    ; CHECK-NEXT: VST_FIFO_SPILL killed renamable $sf, %stack.0, implicit $sp :: (store (s1024) into %stack.0, align 64)
    ; CHECK-NEXT: $sf = COPY $y1
    ; CHECK-NEXT: ST_dms_sts_idx_imm $r0, $p0, 0, implicit $sf
    ; CHECK-NEXT: renamable $sf = VLDA_FIFO_SPILL %stack.0, implicit $sp :: (load (s1024) from %stack.0, align 64)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $sf
    %0:mstfifo = COPY $cml0 ; -> only $sf is available

    $sf = COPY $y1
    ST_dms_sts_idx_imm $r0, $p0, 0, implicit $sf
    PseudoRET implicit $lr, implicit %0
...

---
name:            test_1024_fifo_sf_caller_saved
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $sf

    ; CHECK-LABEL: name: test_1024_fifo_sf_caller_saved
    ; CHECK: liveins: $sf
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: VST_FIFO_SPILL $sf, %stack.0, implicit $sp :: (store (s1024) into %stack.0, align 64)
    ; CHECK-NEXT: PseudoJL 32, csr_aie2p, implicit-def $lr
    ; CHECK-NEXT: renamable $sf = VLDA_FIFO_SPILL %stack.0, implicit $sp :: (load (s1024) from %stack.0, align 64)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $sf
    %0:mstfifo = COPY $sf
    PseudoJL 32, csr_aie2p, implicit-def $lr
    PseudoRET implicit $lr, implicit %0
...


---
name:            test_512_fifo_caller_saved
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $lf0

    ; CHECK-LABEL: name: test_512_fifo_caller_saved
    ; CHECK: liveins: $lf0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $lfh0 = COPY $lfl0
    ; CHECK-NEXT: VST_dmx_sts_fifohl_spill killed renamable $lfh0, %stack.0, implicit $sp :: (store (s512) into %stack.0)
    ; CHECK-NEXT: PseudoJL 32, csr_aie2p, implicit-def $lr
    ; CHECK-NEXT: renamable $lfh0 = VLDA_dmx_lda_fifohl_spill %stack.0, implicit $sp :: (load (s512) from %stack.0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $lfh0
    %0:eldfifohreg = COPY $lfl0
    PseudoJL 32, csr_aie2p, implicit-def $lr
    PseudoRET implicit $lr, implicit %0
...

---
name:            test_512_fifo_scarce_regs
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $r0, $p0, $lf1

    ; CHECK-LABEL: name: test_512_fifo_scarce_regs
    ; CHECK: liveins: $bmll0, $lf1, $p0, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $lfl0 = COPY $bmll0
    ; CHECK-NEXT: VST_dmx_sts_fifohl_spill killed renamable $lfl0, %stack.0, implicit $sp :: (store (s512) into %stack.0)
    ; CHECK-NEXT: $lfl0 = COPY $lfl1
    ; CHECK-NEXT: ST_dms_sts_idx_imm $r0, $p0, 0, implicit $lf0, implicit $lf1
    ; CHECK-NEXT: renamable $lfl0 = VLDA_dmx_lda_fifohl_spill %stack.0, implicit $sp :: (load (s512) from %stack.0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $lfl0
    %0:eldfifolreg = COPY $bmll0 ; -> only $lfl0 is available

    $lfl0 = COPY $lfl1
    ST_dms_sts_idx_imm $r0, $p0, 0, implicit $lf0, implicit $lf1
    PseudoRET implicit $lr, implicit %0
...


---
name:            test_plfr_fifo_caller_saved
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $plfr0

    ; CHECK-LABEL: name: test_plfr_fifo_caller_saved
    ; CHECK: liveins: $plfr0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: VST_PLFR_SPILL $plfr0, %stack.0, implicit $sp :: (store (s1088) into %stack.0, align 64)
    ; CHECK-NEXT: PseudoJL 32, csr_aie2p, implicit-def $lr
    ; CHECK-NEXT: renamable $plfr0 = VLDA_PLFR_SPILL %stack.0, implicit $sp :: (load (s1088) from %stack.0, align 64)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $plfr0
    %0:epsrfldf = COPY $plfr0
    PseudoJL 32, csr_aie2p, implicit-def $lr
    PseudoRET implicit $lr, implicit %0
...

---
name:            test_plfr_fifo_scarce_regs
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $bmll0, $r0, $p0, $plfr1

    ; CHECK-LABEL: name: test_plfr_fifo_scarce_regs
    ; CHECK: liveins: $bmll0, $p0, $plfr1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $plfr0 = COPY $bmll0
    ; CHECK-NEXT: VST_PLFR_SPILL killed renamable $plfr0, %stack.0, implicit $sp :: (store (s1088) into %stack.0, align 64)
    ; CHECK-NEXT: $plfr0 = COPY $plfr1
    ; CHECK-NEXT: ST_dms_sts_idx_imm $r0, $p0, 0, implicit $plfr0, implicit $plfr1
    ; CHECK-NEXT: renamable $plfr0 = VLDA_PLFR_SPILL %stack.0, implicit $sp :: (load (s1088) from %stack.0, align 64)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $plfr0
    %0:epsrfldf = COPY $bmll0 ; -> only $plfr0 is available

    $plfr0 = COPY $plfr1
    ST_dms_sts_idx_imm $r0, $p0, 0, implicit $plfr0, implicit $plfr1
    PseudoRET implicit $lr, implicit %0
...

