# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2p --verify-machineinstrs -run-pass=greedy -run-pass=virtregrewriter %s -o - | FileCheck %s


# There is only one BM register available, it will then be used for the %0
# virtual register. Here we test that it is properly spilled and then reloaded.
---
name:            test_512_scarce_regs
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $x0, $r0, $p0, $bmll1, $bmll2, $bmll3, $bmll4, $bmlh0, $bmlh1, $bmlh2, $bmlh3, $bmlh4, $bmhh0, $bmhh1, $bmhh2, $bmhh3, $bmhh4, $bmhl0, $bmhl1, $bmhl2, $bmhl3, $bmhl4

    ; CHECK-LABEL: name: test_512_scarce_regs
    ; CHECK: liveins: $bmhh0, $bmhh1, $bmhh2, $bmhh3, $bmhh4, $bmhl0, $bmhl1, $bmhl2, $bmhl3, $bmhl4, $bmlh0, $bmlh1, $bmlh2, $bmlh3, $bmlh4, $bmll1, $bmll2, $bmll3, $bmll4, $p0, $r0, $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $bmll0 = COPY $x0
    ; CHECK-NEXT: VST_dmx_sts_bm_spill killed renamable $bmll0, %stack.0, implicit $sp :: (store (s512) into %stack.0)
    ; CHECK-NEXT: $bmll0 = COPY $bmll1
    ; CHECK-NEXT: ST_dms_sts_idx_imm $r0, $p0, 0, implicit $bmll0, implicit $bmll1, implicit $bmll2, implicit $bmll3, implicit $bmll4, implicit $bmlh0, implicit $bmlh1, implicit $bmlh2, implicit $bmlh3, implicit $bmlh4, implicit $bmhh0, implicit $bmhh1, implicit $bmhh2, implicit $bmhh3, implicit $bmhh4, implicit $bmhl0, implicit $bmhl1, implicit $bmhl2, implicit $bmhl3, implicit $bmhl4
    ; CHECK-NEXT: renamable $bmll0 = VLDA_dmx_lda_bm_spill %stack.0, implicit $sp :: (load (s512) from %stack.0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $bmll0
    %0:acc512 = COPY $x0 ; -> only $bmll0 is available

    $bmll0 = COPY $bmll1
    ST_dms_sts_idx_imm $r0, $p0, 0, implicit $bmll0, implicit $bmll1, implicit $bmll2, implicit $bmll3, implicit $bmll4, implicit $bmlh0, implicit $bmlh1, implicit $bmlh2, implicit $bmlh3, implicit $bmlh4, implicit $bmhh0, implicit $bmhh1, implicit $bmhh2, implicit $bmhh3, implicit $bmhh4, implicit $bmhl0, implicit $bmhl1, implicit $bmhl2, implicit $bmhl3, implicit $bmhl4

    PseudoRET implicit $lr, implicit %0
...

---
name:            test_512_caller_saved
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $bmll0

    ; CHECK-LABEL: name: test_512_caller_saved
    ; CHECK: liveins: $bmll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: VST_dmx_sts_bm_spill $bmll0, %stack.0, implicit $sp :: (store (s512) into %stack.0)
    ; CHECK-NEXT: PseudoJL 32, csr_aie2p, implicit-def $lr
    ; CHECK-NEXT: renamable $bmll0 = VLDA_dmx_lda_bm_spill %stack.0, implicit $sp :: (load (s512) from %stack.0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $bmll0
    %0:acc512 = COPY $bmll0
    PseudoJL 32, csr_aie2p, implicit-def $lr
    PseudoRET implicit $lr, implicit %0
...


# There is only one CM register available, it will then be used for the %0
# virtual register. Here we test that it is properly spilled and then reloaded.
---
name:            test_1024_scarce_regs
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $y2, $r0, $p0, $cml1, $cml2, $cml3, $cml4, $cmh0, $cmh1, $cmh2, $cmh3, $cmh4

    ; CHECK-LABEL: name: test_1024_scarce_regs
    ; CHECK: liveins: $cmh0, $cmh1, $cmh2, $cmh3, $cmh4, $cml1, $cml2, $cml3, $cml4, $p0, $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $cml0 = COPY $y2
    ; CHECK-NEXT: VST_CM_SPILL killed renamable $cml0, %stack.0, implicit $sp :: (store (s1024) into %stack.0, align 64)
    ; CHECK-NEXT: $cml0 = COPY $cml1
    ; CHECK-NEXT: ST_dms_sts_idx_imm $r0, $p0, 0, implicit $cml0, implicit $cml1, implicit $cml2, implicit $cml3, implicit $cml4, implicit $cmh0, implicit $cmh1, implicit $cmh2, implicit $cmh3, implicit $cmh4
    ; CHECK-NEXT: renamable $cml0 = VLDA_CM_SPILL %stack.0, implicit $sp :: (load (s1024) from %stack.0, align 64)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $cml0
    %0:acc1024 = COPY $y2 ; -> only $cml0 is available

    $cml0 = COPY $cml1
    ST_dms_sts_idx_imm $r0, $p0, 0, implicit $cml0, implicit $cml1, implicit $cml2, implicit $cml3, implicit $cml4, implicit $cmh0, implicit $cmh1, implicit $cmh2, implicit $cmh3, implicit $cmh4

    PseudoRET implicit $lr, implicit %0
...

---
name:            test_1024_caller_saved
alignment:       16
legalized:       true
regBankSelected: true
selected:        true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $cml0

    ; CHECK-LABEL: name: test_1024_caller_saved
    ; CHECK: liveins: $cml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: VST_CM_SPILL $cml0, %stack.0, implicit $sp :: (store (s1024) into %stack.0, align 64)
    ; CHECK-NEXT: PseudoJL 32, csr_aie2p, implicit-def $lr
    ; CHECK-NEXT: renamable $cml0 = VLDA_CM_SPILL %stack.0, implicit $sp :: (load (s1024) from %stack.0, align 64)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $cml0
    %0:acc1024 = COPY $cml0
    PseudoJL 32, csr_aie2p, implicit-def $lr
    PseudoRET implicit $lr, implicit %0
...
