# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2p --verify-machineinstrs -run-pass=greedy -run-pass=virtregrewriter %s -o - | FileCheck %s

# There is only one eM (MOD) register available, it will then be used for the %0
# virtual register. Here we test that it is properly spilled and then reloaded.

# %0 isn't used by "real" instructions directly, greedy assumes the reg class
# would not benefit from enlarging, and prefers spilling.
---
  name:            spill_to_mem
  alignment:       16
  legalized:       true
  regBankSelected: true
  selected:        true
  tracksRegLiveness: true
  body:             |
    bb.1.entry:
      liveins: $p0, $m0, $m1, $m2, $m3, $m4, $m5, $m6, $m7

    ; CHECK-LABEL: name: spill_to_mem
    ; CHECK: liveins: $m0, $m1, $m2, $m3, $m4, $m5, $m6, $m7, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: ST_R_SPILL $m0, %stack.0, implicit $sp :: (store (s32) into %stack.0)
    ; CHECK-NEXT: $m0 = COPY $m1
    ; CHECK-NEXT: ST_dms_sts_idx_imm $m0, $p0, 0, implicit $m1, implicit $m2, implicit $m3, implicit $m4, implicit $m5, implicit $m6, implicit $m7
    ; CHECK-NEXT: renamable $m0 = LDA_R_SPILL %stack.0, implicit $sp :: (load (s32) from %stack.0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $m0
      %0:em = COPY $m0 ; -> only $m0 is available

      $m0 = COPY $m1
      ST_dms_sts_idx_imm $m0, $p0, 0, implicit $m1, implicit $m2, implicit $m3, implicit $m4, implicit $m5, implicit $m6, implicit $m7

      PseudoRET implicit $lr, implicit %0
...

# %0 is used by "real" instructions, but those impose no strict constraints
# on the current reg class. Greedy prefers spilling, because splitting is
# "similar to spilling", only without the extra COPY instructions.
---
  name:            spill_to_mem2
  alignment:       16
  legalized:       true
  regBankSelected: true
  selected:        true
  tracksRegLiveness: true
  body:             |
    bb.1.entry:
      liveins: $p0, $m1, $m2, $m3, $m4, $m5, $m6, $m7

    ; CHECK-LABEL: name: spill_to_mem2
    ; CHECK: liveins: $m1, $m2, $m3, $m4, $m5, $m6, $m7, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $m0 = LDA_dms_lda_idx_imm $p0, 0
    ; CHECK-NEXT: ST_R_SPILL killed renamable $m0, %stack.0, implicit $sp :: (store (s32) into %stack.0)
    ; CHECK-NEXT: $m0 = COPY $m1
    ; CHECK-NEXT: ST_dms_sts_idx_imm $m0, $p0, 0, implicit $m1, implicit $m2, implicit $m3, implicit $m4, implicit $m5, implicit $m6, implicit $m7
    ; CHECK-NEXT: renamable $m0 = LDA_R_SPILL %stack.0, implicit $sp :: (load (s32) from %stack.0)
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed renamable $m0, $p0, 4
      %0:em_as_32bit = LDA_dms_lda_idx_imm $p0, 0 ; -> only $m0 is available

      $m0 = COPY $m1
      ST_dms_sts_idx_imm $m0, $p0, 0, implicit $m1, implicit $m2, implicit $m3, implicit $m4, implicit $m5, implicit $m6, implicit $m7

      ST_dms_sts_idx_imm %0, $p0, 4
...

# %0 is used by a real/non-COPY instruction that has a constrained class
# compared to spill_eM_to_eR. Here, greedy favors splitting over spilling.
---
  name:            spill_to_reg
  alignment:       16
  legalized:       true
  regBankSelected: true
  selected:        true
  tracksRegLiveness: true
  body:             |
    bb.1.entry:
      liveins: $p0, $m0, $m1, $m2, $m3, $m4, $m5, $m6, $m7

    ; CHECK-LABEL: name: spill_to_reg
    ; CHECK: liveins: $m0, $m1, $m2, $m3, $m4, $m5, $m6, $m7, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $r0 = COPY $m0
    ; CHECK-NEXT: $m0 = COPY $m1
    ; CHECK-NEXT: ST_dms_sts_idx_imm $m0, $p0, 0, implicit $m1, implicit $m2, implicit $m3, implicit $m4, implicit $m5, implicit $m6, implicit $m7
    ; CHECK-NEXT: renamable $m0 = COPY killed renamable $r0
    ; CHECK-NEXT: $p0 = PADDA_pstm_nrm $p0, killed renamable $m0
      %0:em = COPY $m0 ; -> only $m0 is available

      $m0 = COPY $m1
      ST_dms_sts_idx_imm $m0, $p0, 0, implicit $m1, implicit $m2, implicit $m3, implicit $m4, implicit $m5, implicit $m6, implicit $m7

      $p0 = PADDA_pstm_nrm $p0, %0
...
