# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc --mtriple=aie2p -verify-machineinstrs \
# RUN:  --start-before=aie-postlegalizer-generic-combiner \
# RUN:  --stop-after=aie-postlegalizer-custom-combiner \
# RUN: --aie-global-ptr-mod-opt=true \
# RUN:  -o - %s  | FileCheck %s

# Verify that Gemm has the correct assignment


---
name:            gemm-kernel
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: gemm-kernel
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $p1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 -1
  ; CHECK-NEXT:   [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
  ; CHECK-NEXT:   %configZero:_(s20) = G_LOAD [[COPY]](p0) :: (load (s20), align 4)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:_(s32) = G_PHI [[C3]](s32), %bb.0, %7(s32), %bb.1
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:_(p0) = G_PHI [[COPY]](p0), %bb.0, %9(p0), %bb.1
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:_(s32) = G_ADD [[PHI]], [[C2]]
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(sgt), [[ADD]](s32), [[C]]
  ; CHECK-NEXT:   [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
  ; CHECK-NEXT:   [[AIE_OFFSET_LOAD:%[0-9]+]]:_(<32 x s16>) = G_AIE_OFFSET_LOAD [[PHI1]](p0), [[C4]](s20) :: (load (<32 x s16>))
  ; CHECK-NEXT:   [[AIE_POSTINC_3D_LOAD:%[0-9]+]]:_(<32 x s16>), [[AIE_POSTINC_3D_LOAD1:%[0-9]+]]:_(p0), [[AIE_POSTINC_3D_LOAD2:%[0-9]+]]:_(s20), [[AIE_POSTINC_3D_LOAD3:%[0-9]+]]:_ = G_AIE_POSTINC_3D_LOAD [[PHI1]], [[C1]], [[C1]], [[C1]], [[C1]], [[C1]], [[C1]], [[C1]] :: (load (<32 x s16>))
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[PHI1]], %configZero(s20)
  ; CHECK-NEXT:   [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 0
  ; CHECK-NEXT:   [[AIE_OFFSET_LOAD1:%[0-9]+]]:_(<32 x s16>) = G_AIE_OFFSET_LOAD [[PTR_ADD]](p0), [[C5]](s20) :: (load (<32 x s16>))
  ; CHECK-NEXT:   [[AIE_OFFSET_LOAD2:%[0-9]+]]:_(<32 x s16>) = G_AIE_OFFSET_LOAD [[PTR_ADD]](p0), [[C4]](s20) :: (load (<32 x s16>))
  ; CHECK-NEXT:   G_BRCOND [[ICMP]](s32), %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit [[AIE_POSTINC_3D_LOAD]](<32 x s16>), implicit [[AIE_OFFSET_LOAD]](<32 x s16>), implicit [[AIE_OFFSET_LOAD1]](<32 x s16>), implicit [[AIE_OFFSET_LOAD2]](<32 x s16>)
  bb.0:
    liveins: $p0, $p1
    %0:_(p0) = COPY $p0
    %1:_(s32) = G_CONSTANT i32 0
    %2:_(s20) = G_CONSTANT i20 64
    %3:_(s32) = G_CONSTANT i32 -1
    %4:_(s32) = G_CONSTANT i32 4
    %configZero:_(s20) = G_LOAD %0(p0) :: (load (s20))
  bb.1:
    %5:_(s32) = G_PHI %4, %bb.0, %7, %bb.1
    %6:_(p0) = G_PHI %0, %bb.0, %9, %bb.1
    %7:_(s32) = G_ADD %3, %5
    %8:_(s32) = G_ICMP intpred(sgt), %7(s32), %1
    %9:_(p0), %10:_(s20), %11:_(s20) = G_INTRINSIC intrinsic(@llvm.aie2p.add.3d), %6:_(p0), %2:_(s20), %2:_(s20), %2:_(s20), %2:_(s20), %2:_(s20), %2:_(s20), %2:_(s20)
    %12:_(<32 x s16>) = G_LOAD %6(p0) :: (load (<32 x s16>))
    %13:_(s20) = G_CONSTANT i20 64
    %14:_(p0) = nuw G_PTR_ADD %6, %13(s20)
    %15:_(<32 x s16>) = G_LOAD %14(p0) :: (load (<32 x s16>))
    %16:_(p0) = G_PTR_ADD %6, %configZero
    %17:_(<32 x s16>) = G_LOAD %16(p0) :: (load (<32 x s16>))
    %18:_(p0) = nuw G_PTR_ADD %16, %13(s20)
    %19:_(<32 x s16>) = G_LOAD %18(p0) :: (load (<32 x s16>))
    G_BRCOND %8(s32), %bb.1
  bb.2:
    PseudoRET implicit $lr, implicit %12, implicit %15, implicit %17, implicit %19
...
...



