# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2p --start-before=aie-postlegalizer-generic-combiner --stop-after=aie-postlegalizer-custom-combiner -verify-machineinstrs -o - %s | FileCheck %s

# Coverage for combine_lag_ptr_add. The rule rewrites G_PTR_ADD of a
# pre-increment pointer-register value in terms of the corresponding
# POSTINC's post-increment def. matchLagPtrAdd uses
# CombinerHelper::dominates so it works both same-BB and cross-BB; it
# also bails out when the root's def feeds a real (non-side-effecting)
# load/store so the PointerModifierCombiner cache stays consistent.

# ---------------------------------------------------------------------
# Cross-BB, pointer path.
#
# At loop exit, %pre and %post satisfy %post = %pre + step, so
# G_PTR_ADD %pre, C  ==  COPY %post              when C == step
# G_PTR_ADD %pre, C  ==  G_PTR_ADD %post, C-step when C != step
# ---------------------------------------------------------------------

# 1D POSTINC_LOAD, C == step (32 == 32) -> rewrite to COPY %post.
---
name:            ptr-postinc-load-1d-c-eq-step
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: ptr-postinc-load-1d-c-eq-step
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 -1
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %pre:_(p0) = G_PHI [[COPY]](p0), %bb.0, %post(p0), %bb.1
  ; CHECK-NEXT:   %i:_(s32) = G_PHI [[COPY1]](s32), %bb.0, %inext(s32), %bb.1
  ; CHECK-NEXT:   %val:_(s32), %post:_(p0) = G_AIE_POSTINC_LOAD %pre, [[C2]](s20) :: (load (s32))
  ; CHECK-NEXT:   %inext:_(s32) = G_ADD %i, [[C1]]
  ; CHECK-NEXT:   %cond:_(s32) = G_ICMP intpred(sgt), %inext(s32), [[C]]
  ; CHECK-NEXT:   G_BRCOND %cond(s32), %bb.1
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   %adjusted:_(p0) = COPY %post(p0)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit %adjusted(p0)
  bb.0:
    liveins: $p0, $r0
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r0
    %2:_(s32) = G_CONSTANT i32 0
    %3:_(s32) = G_CONSTANT i32 -1
    %4:_(s20) = G_CONSTANT i20 32

  bb.1:
    %pre:_(p0) = G_PHI %0(p0), %bb.0, %post(p0), %bb.1
    %i:_(s32) = G_PHI %1(s32), %bb.0, %inext(s32), %bb.1
    %val:_(s32), %post:_(p0) = G_AIE_POSTINC_LOAD %pre(p0), %4(s20) :: (load (s32))
    %inext:_(s32) = G_ADD %i, %3
    %cond:_(s32) = G_ICMP intpred(sgt), %inext(s32), %2
    G_BRCOND %cond(s32), %bb.1
    G_BR %bb.2

  bb.2:
    %step:_(s20) = G_CONSTANT i20 32
    %adjusted:_(p0) = G_PTR_ADD %pre, %step(s20)
    PseudoRET implicit $lr, implicit %adjusted(p0)
...

# 1D POSTINC_LOAD, C > step (96 > 32) -> rewrite to G_PTR_ADD %post, 64.
---
name:            ptr-postinc-load-1d-c-gt-step
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: ptr-postinc-load-1d-c-gt-step
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 -1
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %pre:_(p0) = G_PHI [[COPY]](p0), %bb.0, %post(p0), %bb.1
  ; CHECK-NEXT:   %i:_(s32) = G_PHI [[COPY1]](s32), %bb.0, %inext(s32), %bb.1
  ; CHECK-NEXT:   %val:_(s32), %post:_(p0) = G_AIE_POSTINC_LOAD %pre, [[C2]](s20) :: (load (s32))
  ; CHECK-NEXT:   %inext:_(s32) = G_ADD %i, [[C1]]
  ; CHECK-NEXT:   %cond:_(s32) = G_ICMP intpred(sgt), %inext(s32), [[C]]
  ; CHECK-NEXT:   G_BRCOND %cond(s32), %bb.1
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
  ; CHECK-NEXT:   %adjusted:_(p0) = G_PTR_ADD %post, [[C3]](s20)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit %adjusted(p0)
  bb.0:
    liveins: $p0, $r0
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r0
    %2:_(s32) = G_CONSTANT i32 0
    %3:_(s32) = G_CONSTANT i32 -1
    %4:_(s20) = G_CONSTANT i20 32

  bb.1:
    %pre:_(p0) = G_PHI %0(p0), %bb.0, %post(p0), %bb.1
    %i:_(s32) = G_PHI %1(s32), %bb.0, %inext(s32), %bb.1
    %val:_(s32), %post:_(p0) = G_AIE_POSTINC_LOAD %pre(p0), %4(s20) :: (load (s32))
    %inext:_(s32) = G_ADD %i, %3
    %cond:_(s32) = G_ICMP intpred(sgt), %inext(s32), %2
    G_BRCOND %cond(s32), %bb.1
    G_BR %bb.2

  bb.2:
    %offset:_(s20) = G_CONSTANT i20 96
    %adjusted:_(p0) = G_PTR_ADD %pre, %offset(s20)
    PseudoRET implicit $lr, implicit %adjusted(p0)
...

# 1D POSTINC_STORE (post-ptr at op 0): C == step -> COPY %post.
---
name:            ptr-postinc-store-1d-c-eq-step
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: ptr-postinc-store-1d-c-eq-step
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 -1
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %pre:_(p0) = G_PHI [[COPY]](p0), %bb.0, %post(p0), %bb.1
  ; CHECK-NEXT:   %i:_(s32) = G_PHI [[COPY1]](s32), %bb.0, %inext(s32), %bb.1
  ; CHECK-NEXT:   %post:_(p0) = G_AIE_POSTINC_STORE [[COPY1]](s32), %pre, [[C2]](s20) :: (store (s32))
  ; CHECK-NEXT:   %inext:_(s32) = G_ADD %i, [[C1]]
  ; CHECK-NEXT:   %cond:_(s32) = G_ICMP intpred(sgt), %inext(s32), [[C]]
  ; CHECK-NEXT:   G_BRCOND %cond(s32), %bb.1
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   %adjusted:_(p0) = COPY %post(p0)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit %adjusted(p0)
  bb.0:
    liveins: $p0, $r0
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r0
    %2:_(s32) = G_CONSTANT i32 0
    %3:_(s32) = G_CONSTANT i32 -1
    %4:_(s20) = G_CONSTANT i20 32

  bb.1:
    %pre:_(p0) = G_PHI %0(p0), %bb.0, %post(p0), %bb.1
    %i:_(s32) = G_PHI %1(s32), %bb.0, %inext(s32), %bb.1
    %post:_(p0) = G_AIE_POSTINC_STORE %1(s32), %pre(p0), %4(s20) :: (store (s32))
    %inext:_(s32) = G_ADD %i, %3
    %cond:_(s32) = G_ICMP intpred(sgt), %inext(s32), %2
    G_BRCOND %cond(s32), %bb.1
    G_BR %bb.2

  bb.2:
    %step:_(s20) = G_CONSTANT i20 32
    %adjusted:_(p0) = G_PTR_ADD %pre, %step(s20)
    PseudoRET implicit $lr, implicit %adjusted(p0)
...

# 2D POSTINC_LOAD (PostPtrDef=1, PrePtrUse=3, ModifierUse=4),
# C == step (16 == 16) -> COPY %post.
---
name:            ptr-postinc-load-2d-c-eq-step
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: ptr-postinc-load-2d-c-eq-step
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 -1
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %pre:_(p0) = G_PHI [[COPY]](p0), %bb.0, %post(p0), %bb.1
  ; CHECK-NEXT:   %ctr:_(s20) = G_PHI [[C2]](s20), %bb.0, %ctrn(s20), %bb.1
  ; CHECK-NEXT:   %i:_(s32) = G_PHI [[COPY1]](s32), %bb.0, %inext(s32), %bb.1
  ; CHECK-NEXT:   %val:_(s32), %post:_(p0), %ctrn:_(s20) = G_AIE_POSTINC_2D_LOAD %pre, [[C2]], [[C2]], [[C2]], %ctr :: (load (s32))
  ; CHECK-NEXT:   %inext:_(s32) = G_ADD %i, [[C1]]
  ; CHECK-NEXT:   %cond:_(s32) = G_ICMP intpred(sgt), %inext(s32), [[C]]
  ; CHECK-NEXT:   G_BRCOND %cond(s32), %bb.1
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   %adjusted:_(p0) = COPY %post(p0)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit %adjusted(p0)
  bb.0:
    liveins: $p0, $r0
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r0
    %2:_(s32) = G_CONSTANT i32 0
    %3:_(s32) = G_CONSTANT i32 -1
    %4:_(s20) = G_CONSTANT i20 16

  bb.1:
    %pre:_(p0) = G_PHI %0(p0), %bb.0, %post(p0), %bb.1
    %ctr:_(s20) = G_PHI %4(s20), %bb.0, %ctrn(s20), %bb.1
    %i:_(s32) = G_PHI %1(s32), %bb.0, %inext(s32), %bb.1
    %val:_(s32), %post:_(p0), %ctrn:_(s20) = G_AIE_POSTINC_2D_LOAD %pre(p0), %4(s20), %4(s20), %4(s20), %ctr(s20) :: (load (s32))
    %inext:_(s32) = G_ADD %i, %3
    %cond:_(s32) = G_ICMP intpred(sgt), %inext(s32), %2
    G_BRCOND %cond(s32), %bb.1
    G_BR %bb.2

  bb.2:
    %step:_(s20) = G_CONSTANT i20 16
    %adjusted:_(p0) = G_PTR_ADD %pre, %step(s20)
    PseudoRET implicit $lr, implicit %adjusted(p0)
...

# 2D POSTINC_STORE (PostPtrDef=0, PrePtrUse=3, ModifierUse=4),
# C == step (16 == 16) -> COPY %post.
---
name:            ptr-postinc-store-2d-c-eq-step
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: ptr-postinc-store-2d-c-eq-step
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 -1
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %pre:_(p0) = G_PHI [[COPY]](p0), %bb.0, %post(p0), %bb.1
  ; CHECK-NEXT:   %ctr:_(s20) = G_PHI [[C2]](s20), %bb.0, %ctrn(s20), %bb.1
  ; CHECK-NEXT:   %i:_(s32) = G_PHI [[COPY1]](s32), %bb.0, %inext(s32), %bb.1
  ; CHECK-NEXT:   %post:_(p0), %ctrn:_(s20) = G_AIE_POSTINC_2D_STORE [[COPY1]](s32), %pre, [[C2]], [[C2]], [[C2]], %ctr :: (store (s32))
  ; CHECK-NEXT:   %inext:_(s32) = G_ADD %i, [[C1]]
  ; CHECK-NEXT:   %cond:_(s32) = G_ICMP intpred(sgt), %inext(s32), [[C]]
  ; CHECK-NEXT:   G_BRCOND %cond(s32), %bb.1
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   %adjusted:_(p0) = COPY %post(p0)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit %adjusted(p0)
  bb.0:
    liveins: $p0, $r0
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r0
    %2:_(s32) = G_CONSTANT i32 0
    %3:_(s32) = G_CONSTANT i32 -1
    %4:_(s20) = G_CONSTANT i20 16

  bb.1:
    %pre:_(p0) = G_PHI %0(p0), %bb.0, %post(p0), %bb.1
    %ctr:_(s20) = G_PHI %4(s20), %bb.0, %ctrn(s20), %bb.1
    %i:_(s32) = G_PHI %1(s32), %bb.0, %inext(s32), %bb.1
    %post:_(p0), %ctrn:_(s20) = G_AIE_POSTINC_2D_STORE %1(s32), %pre(p0), %4(s20), %4(s20), %4(s20), %ctr(s20) :: (store (s32))
    %inext:_(s32) = G_ADD %i, %3
    %cond:_(s32) = G_ICMP intpred(sgt), %inext(s32), %2
    G_BRCOND %cond(s32), %bb.1
    G_BR %bb.2

  bb.2:
    %step:_(s20) = G_CONSTANT i20 16
    %adjusted:_(p0) = G_PTR_ADD %pre, %step(s20)
    PseudoRET implicit $lr, implicit %adjusted(p0)
...

# 3D POSTINC_LOAD (PostPtrDef=1, PrePtrUse=4, ModifierUse=5),
# C == step (16 == 16) -> COPY %post.
---
name:            ptr-postinc-load-3d-c-eq-step
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: ptr-postinc-load-3d-c-eq-step
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 -1
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %pre:_(p0) = G_PHI [[COPY]](p0), %bb.0, %post(p0), %bb.1
  ; CHECK-NEXT:   %ctr1:_(s20) = G_PHI [[C2]](s20), %bb.0, %ctr1n(s20), %bb.1
  ; CHECK-NEXT:   %ctr2:_(s20) = G_PHI [[C2]](s20), %bb.0, %ctr2n(s20), %bb.1
  ; CHECK-NEXT:   %i:_(s32) = G_PHI [[COPY1]](s32), %bb.0, %inext(s32), %bb.1
  ; CHECK-NEXT:   %val:_(s32), %post:_(p0), %ctr1n:_(s20), %ctr2n:_ = G_AIE_POSTINC_3D_LOAD %pre, [[C2]], [[C2]], [[C2]], %ctr1, [[C2]], [[C2]], %ctr2 :: (load (s32))
  ; CHECK-NEXT:   %inext:_(s32) = G_ADD %i, [[C1]]
  ; CHECK-NEXT:   %cond:_(s32) = G_ICMP intpred(sgt), %inext(s32), [[C]]
  ; CHECK-NEXT:   G_BRCOND %cond(s32), %bb.1
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   %adjusted:_(p0) = COPY %post(p0)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit %adjusted(p0)
  bb.0:
    liveins: $p0, $r0
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r0
    %2:_(s32) = G_CONSTANT i32 0
    %3:_(s32) = G_CONSTANT i32 -1
    %4:_(s20) = G_CONSTANT i20 16

  bb.1:
    %pre:_(p0) = G_PHI %0(p0), %bb.0, %post(p0), %bb.1
    %ctr1:_(s20) = G_PHI %4(s20), %bb.0, %ctr1n(s20), %bb.1
    %ctr2:_(s20) = G_PHI %4(s20), %bb.0, %ctr2n(s20), %bb.1
    %i:_(s32) = G_PHI %1(s32), %bb.0, %inext(s32), %bb.1
    %val:_(s32), %post:_(p0), %ctr1n:_(s20), %ctr2n:_(s20) = G_AIE_POSTINC_3D_LOAD %pre(p0), %4(s20), %4(s20), %4(s20), %ctr1(s20), %4(s20), %4(s20), %ctr2(s20) :: (load (s32))
    %inext:_(s32) = G_ADD %i, %3
    %cond:_(s32) = G_ICMP intpred(sgt), %inext(s32), %2
    G_BRCOND %cond(s32), %bb.1
    G_BR %bb.2

  bb.2:
    %step:_(s20) = G_CONSTANT i20 16
    %adjusted:_(p0) = G_PTR_ADD %pre, %step(s20)
    PseudoRET implicit $lr, implicit %adjusted(p0)
...

# No-fire: the G_PTR_ADD's result feeds a G_LOAD — bail out so the
# PointerModifier combiner can handle it instead.
---
name:            ptr-postinc-load-no-fire-feeds-load
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: ptr-postinc-load-no-fire-feeds-load
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 -1
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %pre:_(p0) = G_PHI [[COPY]](p0), %bb.0, %post(p0), %bb.1
  ; CHECK-NEXT:   %i:_(s32) = G_PHI [[COPY1]](s32), %bb.0, %inext(s32), %bb.1
  ; CHECK-NEXT:   %val:_(s32), %post:_(p0) = G_AIE_POSTINC_LOAD %pre, [[C2]](s20) :: (load (s32))
  ; CHECK-NEXT:   %inext:_(s32) = G_ADD %i, [[C1]]
  ; CHECK-NEXT:   %cond:_(s32) = G_ICMP intpred(sgt), %inext(s32), [[C]]
  ; CHECK-NEXT:   G_BRCOND %cond(s32), %bb.1
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   %step:_(s20) = G_CONSTANT i20 32
  ; CHECK-NEXT:   %loaded:_(s32) = G_AIE_OFFSET_LOAD %pre(p0), %step(s20) :: (load (s32))
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit %loaded(s32)
  bb.0:
    liveins: $p0, $r0
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r0
    %2:_(s32) = G_CONSTANT i32 0
    %3:_(s32) = G_CONSTANT i32 -1
    %4:_(s20) = G_CONSTANT i20 32

  bb.1:
    %pre:_(p0) = G_PHI %0(p0), %bb.0, %post(p0), %bb.1
    %i:_(s32) = G_PHI %1(s32), %bb.0, %inext(s32), %bb.1
    %val:_(s32), %post:_(p0) = G_AIE_POSTINC_LOAD %pre(p0), %4(s20) :: (load (s32))
    %inext:_(s32) = G_ADD %i, %3
    %cond:_(s32) = G_ICMP intpred(sgt), %inext(s32), %2
    G_BRCOND %cond(s32), %bb.1
    G_BR %bb.2

  bb.2:
    %step:_(s20) = G_CONSTANT i20 32
    %adjusted:_(p0) = G_PTR_ADD %pre, %step(s20)
    %loaded:_(s32) = G_LOAD %adjusted(p0) :: (load (s32))
    PseudoRET implicit $lr, implicit %loaded(s32)
...
