# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc --mtriple=aie2p \
# RUN:  --start-before=aie-postlegalizer-generic-combiner \
# RUN:  --stop-after=aie-postlegalizer-custom-combiner \
# RUN:  --aie-global-ptr-mod-opt=true \
# RUN:  -o - %s | FileCheck %s --check-prefix=CHECK-COMBINER
# RUN: llc --mtriple=aie2p -verify-machineinstrs \
# RUN:  --start-before=aie-postlegalizer-generic-combiner \
# RUN:  --stop-after=register-coalescer \
# RUN:  --aie-global-ptr-mod-opt=true \
# RUN:  -o - %s | FileCheck %s --check-prefix=CHECK-COALESCER
# RUN: llc --mtriple=aie2p -verify-machineinstrs \
# RUN:  --start-before=aie-postlegalizer-generic-combiner \
# RUN:  --stop-after=virtregrewriter \
# RUN:  --aie-global-ptr-mod-opt=true \
# RUN:  -o - %s | FileCheck %s

# Downstream-effect coverage for combine_lag_ptr_add.
#
# lag-ptr-add.mir pins the IR-level rewrite (G_PTR_ADD %pre, C => COPY %post
# when C == step). This file pins the resulting consequence: with the rewrite
# in place, the lag-PHI %pre and the in-loop POSTINC's %post become the same
# value, so register coalescing assigns them the same physical register and
# the back-edge COPY between two p-class regs disappears.
---
name:            ptr-postinc-coalesce
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-COMBINER-LABEL: name: ptr-postinc-coalesce
  ; CHECK-COMBINER: bb.0:
  ; CHECK-COMBINER-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-COMBINER-NEXT:   liveins: $p0, $r0
  ; CHECK-COMBINER-NEXT: {{  $}}
  ; CHECK-COMBINER-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-COMBINER-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
  ; CHECK-COMBINER-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-COMBINER-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 -1
  ; CHECK-COMBINER-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
  ; CHECK-COMBINER-NEXT: {{  $}}
  ; CHECK-COMBINER-NEXT: bb.1:
  ; CHECK-COMBINER-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-COMBINER-NEXT: {{  $}}
  ; CHECK-COMBINER-NEXT:   %pre:_(p0) = G_PHI [[COPY]](p0), %bb.0, %post(p0), %bb.1
  ; CHECK-COMBINER-NEXT:   %i:_(s32) = G_PHI [[COPY1]](s32), %bb.0, %inext(s32), %bb.1
  ; CHECK-COMBINER-NEXT:   %val:_(s32), %post:_(p0) = G_AIE_POSTINC_LOAD %pre, [[C2]](s20) :: (load (s32))
  ; CHECK-COMBINER-NEXT:   %inext:_(s32) = G_ADD %i, [[C1]]
  ; CHECK-COMBINER-NEXT:   %cond:_(s32) = G_ICMP intpred(sgt), %inext(s32), [[C]]
  ; CHECK-COMBINER-NEXT:   G_BRCOND %cond(s32), %bb.1
  ; CHECK-COMBINER-NEXT:   G_BR %bb.2
  ; CHECK-COMBINER-NEXT: {{  $}}
  ; CHECK-COMBINER-NEXT: bb.2:
  ; CHECK-COMBINER-NEXT:   %adjusted:_(p0) = COPY %post(p0)
  ; CHECK-COMBINER-NEXT:   PseudoRET implicit $lr, implicit %adjusted(p0)
  ;
  ; CHECK-COALESCER-LABEL: name: ptr-postinc-coalesce
  ; CHECK-COALESCER: bb.0:
  ; CHECK-COALESCER-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-COALESCER-NEXT:   liveins: $p0, $r0
  ; CHECK-COALESCER-NEXT: {{  $}}
  ; CHECK-COALESCER-NEXT:   [[COPY:%[0-9]+]]:ep_as_32bit = COPY $p0
  ; CHECK-COALESCER-NEXT:   [[COPY1:%[0-9]+]]:er = COPY $r0
  ; CHECK-COALESCER-NEXT:   [[MOV_RLC_imm11_pseudo:%[0-9]+]]:er = MOV_RLC_imm11_pseudo 0
  ; CHECK-COALESCER-NEXT:   [[MOV_PD_imm11_pseudo:%[0-9]+]]:em = MOV_PD_imm11_pseudo 32
  ; CHECK-COALESCER-NEXT: {{  $}}
  ; CHECK-COALESCER-NEXT: bb.1:
  ; CHECK-COALESCER-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-COALESCER-NEXT: {{  $}}
  ; CHECK-COALESCER-NEXT:   dead %val:er, [[COPY]]:ep_as_32bit = LDA_dms_lda_pstm_nrm [[COPY]], [[MOV_PD_imm11_pseudo]] :: (load (s32))
  ; CHECK-COALESCER-NEXT:   [[COPY1:%[0-9]+]]:er = ADD_add_r_ri [[COPY1]], -1, implicit-def dead $srcarry
  ; CHECK-COALESCER-NEXT:   %cond:er = LT [[MOV_RLC_imm11_pseudo]], [[COPY1]]
  ; CHECK-COALESCER-NEXT:   PseudoJNZ %cond, %bb.1
  ; CHECK-COALESCER-NEXT:   PseudoJ_jump_imm %bb.2
  ; CHECK-COALESCER-NEXT: {{  $}}
  ; CHECK-COALESCER-NEXT: bb.2:
  ; CHECK-COALESCER-NEXT:   PseudoRET implicit $lr, implicit [[COPY]]
  ;
  ; CHECK-LABEL: name: ptr-postinc-coalesce
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $r1 = MOV_RLC_imm11_pseudo 0
  ; CHECK-NEXT:   renamable $m0 = MOV_PD_imm11_pseudo 32
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $m0, $p0, $r0, $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   dead renamable $r2, renamable $p0 = LDA_dms_lda_pstm_nrm killed renamable $p0, renamable $m0 :: (load (s32))
  ; CHECK-NEXT:   renamable $r0 = ADD_add_r_ri killed renamable $r0, -1, implicit-def dead $srcarry
  ; CHECK-NEXT:   renamable $r2 = LT renamable $r1, renamable $r0
  ; CHECK-NEXT:   PseudoJNZ killed renamable $r2, %bb.1
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   liveins: $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit killed renamable $p0
  bb.0:
    liveins: $p0, $r0
    %0:_(p0) = COPY $p0
    %1:_(s32) = COPY $r0
    %2:_(s32) = G_CONSTANT i32 0
    %3:_(s32) = G_CONSTANT i32 -1
    %4:_(s20) = G_CONSTANT i20 32

  bb.1:
    %pre:_(p0) = G_PHI %0(p0), %bb.0, %post(p0), %bb.1
    %i:_(s32) = G_PHI %1(s32), %bb.0, %inext(s32), %bb.1
    %val:_(s32), %post:_(p0) = G_AIE_POSTINC_LOAD %pre(p0), %4(s20) :: (load (s32))
    %inext:_(s32) = G_ADD %i, %3
    %cond:_(s32) = G_ICMP intpred(sgt), %inext(s32), %2
    G_BRCOND %cond(s32), %bb.1
    G_BR %bb.2

  bb.2:
    %step:_(s20) = G_CONSTANT i20 32
    %adjusted:_(p0) = G_PTR_ADD %pre, %step(s20)
    PseudoRET implicit $lr, implicit %adjusted(p0)
...
