# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc --mtriple=aie2p -verify-machineinstrs \
# RUN:  --start-before=aie-postlegalizer-generic-combiner \
# RUN:  --stop-after=aie-postlegalizer-custom-combiner \
# RUN: --aie-global-ptr-mod-opt=true \
# RUN:  -o - %s  | FileCheck %s

# Consider MBB Crossing in Selection Decision

# Check out of block use of %0(p0) in BB.1
---
name:            MBB-crossing
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: MBB-crossing
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 192
  ; CHECK-NEXT:   G_STORE [[C1]](s32), [[COPY]](p0) :: (store (s32))
  ; CHECK-NEXT:   G_AIE_OFFSET_STORE [[C1]](s32), [[COPY]](p0), [[C]](s20) :: (store (s32))
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   G_STORE [[C1]](s32), [[COPY]](p0) :: (store (s32))
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.0:
    liveins: $p0
    %0:_(p0) = COPY $p0
    %1:_(s20) = G_CONSTANT i20 64
    %2:_(s32) = G_CONSTANT i32 192
    %3:_(p0) = G_PTR_ADD %0, %1(s20)
    G_STORE %2(s32), %0(p0) :: (store (s32))
    G_STORE %2(s32), %3(p0) :: (store (s32))
  bb.1:
    G_STORE %2, %0(p0) :: (store (s32))
    PseudoRET implicit $lr
...

#  %3(p0) is defined (bb.0) outside of the use in MBB bb.1
---
name:            def-outside-loop-dominance
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: def-outside-loop-dominance
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:_(s32) = G_PHI %6(s32), %bb.1, [[C2]](s32), %bb.0
  ; CHECK-NEXT:   [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:_(s32) = nsw G_ADD [[PHI]], [[C3]]
  ; CHECK-NEXT:   G_STORE [[ADD]](s32), [[COPY]](p0) :: (store (s32))
  ; CHECK-NEXT:   G_AIE_OFFSET_STORE [[ADD]](s32), [[COPY]](p0), [[C]](s20) :: (store (s32))
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(sgt), [[ADD]](s32), [[C1]]
  ; CHECK-NEXT:   G_BRCOND [[ICMP]](s32), %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.0:
    liveins: $p0
    %0:_(p0) = COPY $p0
    %1:_(s20) = G_CONSTANT i20 64
    %2:_(s32) = G_CONSTANT i32 0
    %3:_(p0) = G_PTR_ADD %0, %1(s20)
    %4:_(s32) = G_CONSTANT i32 4
  bb.1:
    %5:_(s32) = G_PHI %7(s32), %bb.1, %4(s32), %bb.0
    %6:_(s32) = G_CONSTANT i32 1
    %7:_(s32) = nsw G_ADD %5, %6
    G_STORE %7(s32), %0(p0) :: (store (s32))
    G_STORE %7(s32), %3(p0) :: (store (s32))
    %8:_(s32) = G_ICMP intpred(sgt), %7(s32), %2
    G_BRCOND %8(s32), %bb.1
  bb.2:
    PseudoRET implicit $lr
...

# %0 is used to define a G_PTR_ADD (%10) in a different block (bb.2) than where
# %0 is otherwise used (bb.1)
---
name:            ptr-add-after-loop
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: ptr-add-after-loop
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
  ; CHECK-NEXT:   [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:_(s32) = G_PHI %6(s32), %bb.1, [[C3]](s32), %bb.0
  ; CHECK-NEXT:   [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:_(s32) = nsw G_ADD [[PHI]], [[C4]]
  ; CHECK-NEXT:   G_STORE [[ADD]](s32), [[COPY]](p0) :: (store (s32))
  ; CHECK-NEXT:   G_AIE_OFFSET_STORE [[ADD]](s32), [[COPY]](p0), [[C2]](s20) :: (store (s32))
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(sgt), [[ADD]](s32), [[C1]]
  ; CHECK-NEXT:   G_BRCOND [[ICMP]](s32), %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   G_AIE_OFFSET_STORE [[ADD]](s32), [[COPY]](p0), [[C]](s20) :: (store (s32))
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.0:
    liveins: $p0
    %0:_(p0) = COPY $p0
    %1:_(s20) = G_CONSTANT i20 32
    %2:_(s32) = G_CONSTANT i32 0
    %3:_(s20) = G_CONSTANT i20 16
    %4:_(s32) = G_CONSTANT i32 4
  bb.1:
    %5:_(s32) = G_PHI %7(s32), %bb.1, %4(s32), %bb.0
    %6:_(s32) = G_CONSTANT i32 1
    %7:_(s32) = nsw G_ADD %5, %6
    G_STORE %7(s32), %0(p0) :: (store (s32))
    %8:_(p0) = G_PTR_ADD %0, %3(s20)
    G_STORE %7(s32), %8(p0) :: (store (s32))
    %9:_(s32) = G_ICMP intpred(sgt), %7(s32), %2
    G_BRCOND %9(s32), %bb.1
  bb.2:
    %10:_(p0) = G_PTR_ADD %0, %1(s20)
    G_STORE %7(s32), %10(p0) :: (store (s32))
    PseudoRET implicit $lr
...

# The result of G_PTR_ADD (%l1) is used in a phi of the same MBB.
---
name:            phi-ptr-add
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: phi-ptr-add
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:_(s32) = G_PHI %6(s32), %bb.1, [[C2]](s32), %bb.0
  ; CHECK-NEXT:   %l0:_(p0) = G_PHI %l1(p0), %bb.1, [[PTR_ADD]](p0), %bb.0
  ; CHECK-NEXT:   [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:_(s32) = nsw G_ADD [[PHI]], [[C3]]
  ; CHECK-NEXT:   G_STORE [[ADD]](s32), [[COPY]](p0) :: (store (s32))
  ; CHECK-NEXT:   [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 1
  ; CHECK-NEXT:   %l1:_(p0) = G_AIE_POSTINC_STORE [[ADD]](s32), %l0, [[C4]](s20) :: (store (s32))
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(sgt), [[ADD]](s32), [[C1]]
  ; CHECK-NEXT:   G_BRCOND [[ICMP]](s32), %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.0:
    liveins: $p0
    %0:_(p0) = COPY $p0
    %1:_(s20) = G_CONSTANT i20 64
    %2:_(s32) = G_CONSTANT i32 0
    %3:_(p0) = G_PTR_ADD %0, %1(s20)
    %4:_(s32) = G_CONSTANT i32 4
  bb.1:
    %5:_(s32) = G_PHI %7(s32), %bb.1, %4(s32), %bb.0
    %l0:_(p0) = G_PHI %l1(p0), %bb.1, %3(p0), %bb.0
    %6:_(s32) = G_CONSTANT i32 1
    %7:_(s32) = nsw G_ADD %5, %6
    G_STORE %7(s32), %0(p0) :: (store (s32))
    G_STORE %7(s32), %l0(p0) :: (store (s32))
    %8:_(s20) = G_CONSTANT i20 1
    %l1:_(p0) = G_PTR_ADD %l0, %8
    %9:_(s32) = G_ICMP intpred(sgt), %7(s32), %2
    G_BRCOND %9(s32), %bb.1
  bb.2:
    PseudoRET implicit $lr
...
