# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc --mtriple=aie2p -verify-machineinstrs \
# RUN:  --start-before=aie2p-postlegalizer-generic-combiner \
# RUN:  --stop-after=aie2p-postlegalizer-custom-combiner \
# RUN: --aie-address-chaining=true \
# RUN:  --aie-global-ptr-mod-opt=true \
# RUN:  -o - %s  | FileCheck %s

# store hinders addr-chaining and thus leads to suboptimal assignments.
# The store should have been a postinc, so that the second load could be a
# Offset Load within Imm range


---
name:            select-offset-and-postinc
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0, $p1
    ; CHECK-LABEL: name: select-offset-and-postinc
    ; CHECK: liveins: $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; CHECK-NEXT: [[AIE_OFFSET_LOAD:%[0-9]+]]:_(s32) = G_AIE_OFFSET_LOAD [[COPY]](p0), [[C]](s20) :: (load (s32))
    ; CHECK-NEXT: G_AIE_OFFSET_STORE [[AIE_OFFSET_LOAD]](s32), [[COPY]](p0), [[C]](s20) :: (store (s32))
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; CHECK-NEXT: [[AIE_OFFSET_LOAD1:%[0-9]+]]:_(s32) = G_AIE_OFFSET_LOAD [[COPY]](p0), [[C1]](s20) :: (load (s32))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_OFFSET_LOAD]](s32), implicit [[AIE_OFFSET_LOAD1]](s32)
    %0:_(p0) = COPY $p0
    %1:_(p0) = COPY $p1
    %2:_(s20) = G_CONSTANT i20 16
    %3:_(p0) = nuw G_PTR_ADD %0, %2
    %4:_(s32) = G_LOAD %3(p0) :: (load (s32))
    G_STORE %4, %3(p0) :: (store (s32))
    %5:_(s20) = G_CONSTANT i20 16
    %6:_(p0) = nuw G_PTR_ADD %3, %5
    %7:_(s32) = G_LOAD %6(p0) :: (load (s32))
    PseudoRET implicit $lr, implicit %4, implicit %7
...
