# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc --mtriple=aie2p -verify-machineinstrs \
# RUN:  --start-before=aie-postlegalizer-generic-combiner \
# RUN:  --stop-after=aie-postlegalizer-custom-combiner \
# RUN:  -o - %s  | FileCheck %s

# Check Movability

# Check that PTR_ADD which has a lower DAG depth than the CombineRoot (load),
# can be combined
---
name:            move-up-check
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: move-up-check
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $p1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
  ; CHECK-NEXT:   [[AIE_POSTINC_LOAD:%[0-9]+]]:_(s32), [[AIE_POSTINC_LOAD1:%[0-9]+]]:_(p0) = G_AIE_POSTINC_LOAD [[COPY]], [[C]](s20) :: (load (s32))
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit [[AIE_POSTINC_LOAD]](s32), implicit [[AIE_POSTINC_LOAD1]](p0)
  bb.0:
    liveins: $p0, $p1
    %0:_(p0) = COPY $p0
    %1:_(s32) = G_CONSTANT i32 0
    %2:_(s20) = G_CONSTANT i20 64
    %3:_(s32) = G_CONSTANT i32 -1
  bb.1:
    %5:_(s32) = G_LOAD %0(p0) :: (load (s32))
    %6:_(s20) = G_CONSTANT i20 4
    %7:_(p0) = G_PTR_ADD %0(p0), %6(s20)
    PseudoRET implicit $lr, implicit %5, implicit %7
...

---
name:            move-multiple-preds
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: move-multiple-preds
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $p1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
  ; CHECK-NEXT:   %Res:_(s32), %7:_(p0) = G_AIE_POSTINC_LOAD [[COPY]], [[C]](s20) :: (load (s32))
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit %Res(s32), implicit %7(p0)
  bb.0:
    liveins: $p0, $p1
    %0:_(p0) = COPY $p0
    %1:_(s32) = G_CONSTANT i32 0
    %2:_(s20) = G_CONSTANT i20 64
    %3:_(s32) = G_CONSTANT i32 -1
  bb.1:
    %Res:_(s32) = G_LOAD %0(p0) :: (load (s32))
    %4:_(s32) = G_CONSTANT i32 8
    %5:_(s20) = G_TRUNC %4
    %7:_(p0) = G_PTR_ADD %0(p0), %5(s20)
    PseudoRET implicit $lr, implicit %Res, implicit %7
...


---
name:            detect-no-movability
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: detect-no-movability
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $p1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 128
  ; CHECK-NEXT:   G_STORE [[C]](s20), [[COPY]](p0) :: (store (s20), align 4)
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(s20) = G_LOAD [[COPY]](p0) :: (load (s20), align 4)
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[LOAD]](s20)
  ; CHECK-NEXT:   PseudoRET implicit $lr, implicit [[PTR_ADD]](p0)
  bb.0:
    liveins: $p0, $p1
    %0:_(p0) = COPY $p0
    %1:_(s32) = G_CONSTANT i32 0
    %2:_(s20) = G_CONSTANT i20 64
    %3:_(s32) = G_CONSTANT i32 -1
  bb.1:
    %4:_(s20) = G_ADD %2, %2
    G_STORE %4(s20), %0(p0) :: (store (s20))
    %5:_(s20) = G_LOAD %0(p0) :: (load (s20))
    %7:_(p0) = G_PTR_ADD %0(p0), %5(s20)
    PseudoRET implicit $lr, implicit %7
...



