# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc --mtriple=aie2p -verify-machineinstrs \
# RUN:  --start-before=aie-postlegalizer-generic-combiner \
# RUN:  --stop-after=aie-postlegalizer-custom-combiner \
# RUN:  --aie-address-chaining=false \
# RUN: --aie-global-ptr-mod-opt=true \
# RUN:  -o - %s  | FileCheck %s

# Check that there is no conflict between pointer independent post-increments
# and a following pre-increment

---
name:            check-non-overlap-gain
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: check-non-overlap-gain
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 192
    ; CHECK-NEXT: [[AIE_POSTINC_3D_STORE:%[0-9]+]]:_(p0), [[AIE_POSTINC_3D_STORE1:%[0-9]+]]:_(s20), [[AIE_POSTINC_3D_STORE2:%[0-9]+]]:_ = G_AIE_POSTINC_3D_STORE [[C1]](s32), [[COPY]], [[C]], [[C]], [[C]], [[C]], [[C]], [[C]], [[C]] :: (store (s32))
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: G_AIE_OFFSET_STORE [[C1]](s32), [[AIE_POSTINC_3D_STORE]](p0), [[C2]](s20) :: (store (s32))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(s20) = G_CONSTANT i20 64
    %2:_(s32) = G_CONSTANT i32 192
    G_STORE %2(s32), %0(p0) :: (store (s32))
    %3:_(p0), %4:_(s20), %5:_(s20) = G_INTRINSIC intrinsic(@llvm.aie2p.add.3d), %0:_(p0), %1:_(s20), %1:_(s20), %1:_(s20), %1:_(s20), %1:_(s20), %1:_(s20), %1:_(s20)
    %6:_(s20) = G_CONSTANT i20 8
    %7:_(p0) = G_PTR_ADD %3, %6(s20)
    G_STORE %2, %7(p0) :: (store (s32))
    PseudoRET implicit $lr
...


# Assign 3d post-increment to later store, so that the pointer does not have to
# be saved
---
name:            overlap-penalty
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: overlap-penalty
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 192
    ; CHECK-NEXT: [[AIE_POSTINC_3D_STORE:%[0-9]+]]:_(p0), [[AIE_POSTINC_3D_STORE1:%[0-9]+]]:_(s20), [[AIE_POSTINC_3D_STORE2:%[0-9]+]]:_ = G_AIE_POSTINC_3D_STORE [[C1]](s32), [[COPY]], [[C]], [[C]], [[C]], [[C]], [[C]], [[C]], [[C]] :: (store (s32))
    ; CHECK-NEXT: G_STORE [[C1]](s32), [[COPY]](p0) :: (store (s32))
    ; CHECK-NEXT: G_STORE [[C1]](s32), [[AIE_POSTINC_3D_STORE]](p0) :: (store (s32))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(s20) = G_CONSTANT i20 64
    %2:_(s32) = G_CONSTANT i32 192
    %3:_(p0), %4:_(s20), %5:_(s20) = G_INTRINSIC intrinsic(@llvm.aie2p.add.3d), %0:_(p0), %1:_(s20), %1:_(s20), %1:_(s20), %1:_(s20), %1:_(s20), %1:_(s20), %1:_(s20)
    G_STORE %2(s32), %0(p0) :: (store (s32))
    G_STORE %2, %0(p0) :: (store (s32))
    G_STORE %2, %3(p0) :: (store (s32))
    PseudoRET implicit $lr
...


