# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc --mtriple=aie2p -verify-machineinstrs \
# RUN:  --start-before=aie2p-postlegalizer-generic-combiner \
# RUN:  --stop-after=aie2p-postlegalizer-custom-combiner \
# RUN:  --aie-address-chaining=false \
# RUN: --aie-global-ptr-mod-opt=true \
# RUN:  -o - %s  | FileCheck %s

# The post-increment with the first memory instruction causes a pointer copy,
# increasing register pressure.
# FIXME: reorder instructions

---
name:            post-inc-reg-pressure-store
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: post-inc-reg-pressure-store
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 192
    ; CHECK-NEXT: [[AIE_POSTINC_3D_STORE:%[0-9]+]]:_(p0), [[AIE_POSTINC_3D_STORE1:%[0-9]+]]:_(s20), [[AIE_POSTINC_3D_STORE2:%[0-9]+]]:_ = G_AIE_POSTINC_3D_STORE [[C1]](s32), [[COPY]], [[C]], [[C]], [[C]], [[C]], [[C]], [[C]], [[C]] :: (store (s32))
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: G_AIE_OFFSET_STORE [[C1]](s32), [[COPY]](p0), [[C2]](s20) :: (store (s32))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_POSTINC_3D_STORE]](p0)
    %0:_(p0) = COPY $p0
    %1:_(s20) = G_CONSTANT i20 64
    %2:_(s32) = G_CONSTANT i32 192
    G_STORE %2(s32), %0(p0) :: (store (s32))
    %6:_(s20) = G_CONSTANT i20 8
    %7:_(p0) = G_PTR_ADD %0, %6(s20)
    G_STORE %2(s32), %7(p0) :: (store (s32))
    %3:_(p0), %4:_(s20), %5:_(s20) = G_INTRINSIC intrinsic(@llvm.aie2p.add.3d), %0:_(p0), %1:_(s20), %1:_(s20), %1:_(s20), %1:_(s20), %1:_(s20), %1:_(s20), %1:_(s20)
    PseudoRET implicit $lr, implicit %3
...

# similar example as above, but with load instructions
---
name:            post-inc-reg-pressure-load
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: post-inc-reg-pressure-load
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; CHECK-NEXT: %lZero:_(s32), %7:_(p0), %8:_(s20), %9:_ = G_AIE_POSTINC_3D_LOAD [[COPY]], [[C]], [[C]], [[C]], [[C]], [[C]], [[C]], [[C]] :: (load (s32))
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: %lOne:_(s32) = G_AIE_OFFSET_LOAD [[COPY]](p0), [[C1]](s20) :: (load (s32))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit %7(p0), implicit %lZero(s32), implicit %lOne(s32)
    %0:_(p0) = COPY $p0
    %1:_(s20) = G_CONSTANT i20 64
    %2:_(s32) = G_CONSTANT i32 192
    %lZero:_(s32) = G_LOAD %0(p0) :: (load (s32))
    %6:_(s20) = G_CONSTANT i20 8
    %7:_(p0) = G_PTR_ADD %0, %6(s20)
    %lOne:_(s32) = G_LOAD %7(p0) :: (load (s32))
    %3:_(p0), %4:_(s20), %5:_(s20) = G_INTRINSIC intrinsic(@llvm.aie2p.add.3d), %0:_(p0), %1:_(s20), %1:_(s20), %1:_(s20), %1:_(s20), %1:_(s20), %1:_(s20), %1:_(s20)
    PseudoRET implicit $lr, implicit %3, implicit %lZero, implicit %lOne
...
