# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc --mtriple=aie2p -verify-machineinstrs \
# RUN:  --start-before=aie-postlegalizer-generic-combiner \
# RUN:  --stop-after=aie-postlegalizer-custom-combiner \
# RUN:  --aie-address-chaining=false \
# RUN: --aie-global-ptr-mod-opt=true \
# RUN:  -o - %s  | FileCheck %s

# Reorder Loads, so that the pointer does not have to be restored for the
# second Load Instr
---
name:            reorder-loads
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: reorder-loads
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; CHECK-NEXT: %sOne:_(s32) = G_AIE_OFFSET_LOAD [[COPY]](p0), [[C]](s20) :: (load (s32))
    ; CHECK-NEXT: %sZero:_(s32), %6:_(p0), %7:_(s20), %8:_ = G_AIE_POSTINC_3D_LOAD [[COPY]], [[C]], [[C]], [[C]], [[C]], [[C]], [[C]], [[C]] :: (load (s32))
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s32) = nsw G_ADD %sZero, %sOne
    ; CHECK-NEXT: G_STORE [[ADD]](s32), %6(p0) :: (store (s32))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:_(p0) = COPY $p0
    %1:_(s20) = G_CONSTANT i20 64
    %2:_(s32) = G_CONSTANT i32 192
    %sZero:_(s32) = G_LOAD %0(p0) :: (load (s32))
    %3:_(p0) = G_PTR_ADD %0, %1(s20)
    %sOne:_(s32) = G_LOAD %3(p0) :: (load (s32))
    %4:_(p0), %5:_(s20), %6:_(s20) = G_INTRINSIC intrinsic(@llvm.aie2p.add.3d), %0:_(p0), %1:_(s20), %1:_(s20), %1:_(s20), %1:_(s20), %1:_(s20), %1:_(s20), %1:_(s20)
    %7:_(s32) = nsw G_ADD %sZero(s32), %sOne(s32)
    G_STORE %7, %4(p0) :: (store (s32))
    PseudoRET implicit $lr
...
