# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc --mtriple=aie2p -verify-machineinstrs \
# RUN:  --start-before=aie-postlegalizer-generic-combiner \
# RUN:  --stop-after=aie-postlegalizer-custom-combiner \
# RUN:  --aie-address-chaining=false \
# RUN:  --aie-global-ptr-mod-opt=true \
# RUN:  -o - %s  | FileCheck %s

# OffsetCombiner must not hoist a load past a side-effecting instruction
# (e.g. a lock acquire/release). The acquire establishes a memory ordering
# constraint: loads after it must observe stores that completed before
# the corresponding release on another tile. Hoisting a load above the
# acquire breaks this contract.

# Single acquire between post-inc load and offset load.
---
name:            no_reorder_across_acquire
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: no_reorder_across_acquire
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: %lockid:_(s32) = G_CONSTANT i32 50
    ; CHECK-NEXT: %lockval:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: %off:_(s20) = G_CONSTANT i20 12
    ; CHECK-NEXT: %first:_(s32), %ptr1:_(p0), %d0:_(s20), %d1:_ = G_AIE_POSTINC_3D_LOAD [[COPY]], %off, %off, %off, %off, %off, %off, %off :: (load (s32))
    ; CHECK-NEXT: G_STORE %first(s32), [[COPY]](p0) :: (store (s32))
    ; CHECK-NEXT: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acquire), %lockid(s32), %lockval(s32)
    ; CHECK-NEXT: %second:_(s32) = G_AIE_OFFSET_LOAD [[COPY]](p0), %off(s20) :: (load (s32))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit %first(s32), implicit %second(s32), implicit %ptr1(p0)
    %0:_(p0) = COPY $p0
    %lockid:_(s32) = G_CONSTANT i32 50
    %lockval:_(s32) = G_CONSTANT i32 1
    %off:_(s20) = G_CONSTANT i20 12

    %first:_(s32) = G_LOAD %0(p0) :: (load (s32))
    G_STORE %first(s32), %0(p0) :: (store (s32))
    %ptr1:_(p0), %d0:_(s20), %d1:_(s20) = G_INTRINSIC intrinsic(@llvm.aie2p.add.3d), %0:_(p0), %off:_(s20), %off:_(s20), %off:_(s20), %off:_(s20), %off:_(s20), %off:_(s20), %off:_(s20)

    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acquire), %lockid(s32), %lockval(s32)

    %addr:_(p0) = nuw G_PTR_ADD %0, %off(s20)
    %second:_(s32) = G_LOAD %addr(p0) :: (load (s32))

    PseudoRET implicit $lr, implicit %first, implicit %second, implicit %ptr1
...

# Release + acquire (lock window) between positions. Both are barriers.
---
name:            no_reorder_across_release_and_acquire
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: no_reorder_across_release_and_acquire
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: %lock1:_(s32) = G_CONSTANT i32 40
    ; CHECK-NEXT: %lock2:_(s32) = G_CONSTANT i32 50
    ; CHECK-NEXT: %lockval:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: %off:_(s20) = G_CONSTANT i20 16
    ; CHECK-NEXT: %first:_(s32), %ptr1:_(p0), %d0:_(s20), %d1:_ = G_AIE_POSTINC_3D_LOAD [[COPY]], %off, %off, %off, %off, %off, %off, %off :: (load (s32))
    ; CHECK-NEXT: G_STORE %first(s32), [[COPY]](p0) :: (store (s32))
    ; CHECK-NEXT: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.release), %lock1(s32), %lockval(s32)
    ; CHECK-NEXT: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acquire), %lock2(s32), %lockval(s32)
    ; CHECK-NEXT: %second:_(s32) = G_AIE_OFFSET_LOAD [[COPY]](p0), %off(s20) :: (load (s32))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit %first(s32), implicit %second(s32), implicit %ptr1(p0)
    %0:_(p0) = COPY $p0
    %lock1:_(s32) = G_CONSTANT i32 40
    %lock2:_(s32) = G_CONSTANT i32 50
    %lockval:_(s32) = G_CONSTANT i32 1
    %off:_(s20) = G_CONSTANT i20 16

    %first:_(s32) = G_LOAD %0(p0) :: (load (s32))
    G_STORE %first(s32), %0(p0) :: (store (s32))
    %ptr1:_(p0), %d0:_(s20), %d1:_(s20) = G_INTRINSIC intrinsic(@llvm.aie2p.add.3d), %0:_(p0), %off:_(s20), %off:_(s20), %off:_(s20), %off:_(s20), %off:_(s20), %off:_(s20), %off:_(s20)

    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.release), %lock1(s32), %lockval(s32)
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acquire), %lock2(s32), %lockval(s32)

    %addr:_(p0) = nuw G_PTR_ADD %0, %off(s20)
    %second:_(s32) = G_LOAD %addr(p0) :: (load (s32))

    PseudoRET implicit $lr, implicit %first, implicit %second, implicit %ptr1
...

# Two offset loads from same base, both after the acquire.
# Neither should be hoisted above the barrier.
---
name:            no_reorder_across_acquire_two_offsets
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: no_reorder_across_acquire_two_offsets
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: %lockid:_(s32) = G_CONSTANT i32 50
    ; CHECK-NEXT: %lockval:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: %off1:_(s20) = G_CONSTANT i20 12
    ; CHECK-NEXT: %off2:_(s20) = G_CONSTANT i20 24
    ; CHECK-NEXT: %first:_(s32), %ptr1:_(p0), %d0:_(s20), %d1:_ = G_AIE_POSTINC_3D_LOAD [[COPY]], %off1, %off1, %off1, %off1, %off1, %off1, %off1 :: (load (s32))
    ; CHECK-NEXT: G_STORE %first(s32), [[COPY]](p0) :: (store (s32))
    ; CHECK-NEXT: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acquire), %lockid(s32), %lockval(s32)
    ; CHECK-NEXT: %second:_(s32) = G_AIE_OFFSET_LOAD [[COPY]](p0), %off1(s20) :: (load (s32))
    ; CHECK-NEXT: %third:_(s32) = G_AIE_OFFSET_LOAD [[COPY]](p0), %off2(s20) :: (load (s32))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit %first(s32), implicit %second(s32), implicit %third(s32), implicit %ptr1(p0)
    %0:_(p0) = COPY $p0
    %lockid:_(s32) = G_CONSTANT i32 50
    %lockval:_(s32) = G_CONSTANT i32 1
    %off1:_(s20) = G_CONSTANT i20 12
    %off2:_(s20) = G_CONSTANT i20 24

    %first:_(s32) = G_LOAD %0(p0) :: (load (s32))
    G_STORE %first(s32), %0(p0) :: (store (s32))
    %ptr1:_(p0), %d0:_(s20), %d1:_(s20) = G_INTRINSIC intrinsic(@llvm.aie2p.add.3d), %0:_(p0), %off1:_(s20), %off1:_(s20), %off1:_(s20), %off1:_(s20), %off1:_(s20), %off1:_(s20), %off1:_(s20)

    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acquire), %lockid(s32), %lockval(s32)

    %addr1:_(p0) = nuw G_PTR_ADD %0, %off1(s20)
    %second:_(s32) = G_LOAD %addr1(p0) :: (load (s32))
    %addr2:_(p0) = nuw G_PTR_ADD %0, %off2(s20)
    %third:_(s32) = G_LOAD %addr2(p0) :: (load (s32))

    PseudoRET implicit $lr, implicit %first, implicit %second, implicit %third, implicit %ptr1
...

# Barrier is AFTER both loads -- reorder is safe and should proceed.
---
name:            reorder_allowed_barrier_after_both
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: reorder_allowed_barrier_after_both
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: %lockid:_(s32) = G_CONSTANT i32 50
    ; CHECK-NEXT: %lockval:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: %off:_(s20) = G_CONSTANT i20 12
    ; CHECK-NEXT: %second:_(s32) = G_AIE_OFFSET_LOAD [[COPY]](p0), %off(s20) :: (load (s32))
    ; CHECK-NEXT: %first:_(s32), %ptr1:_(p0), %d0:_(s20), %d1:_ = G_AIE_POSTINC_3D_LOAD [[COPY]], %off, %off, %off, %off, %off, %off, %off :: (load (s32))
    ; CHECK-NEXT: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acquire), %lockid(s32), %lockval(s32)
    ; CHECK-NEXT: G_STORE %first(s32), %ptr1(p0) :: (store (s32))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit %first(s32), implicit %second(s32), implicit %ptr1(p0)
    %0:_(p0) = COPY $p0
    %lockid:_(s32) = G_CONSTANT i32 50
    %lockval:_(s32) = G_CONSTANT i32 1
    %off:_(s20) = G_CONSTANT i20 12

    %first:_(s32) = G_LOAD %0(p0) :: (load (s32))
    %addr:_(p0) = nuw G_PTR_ADD %0, %off(s20)
    %second:_(s32) = G_LOAD %addr(p0) :: (load (s32))
    %ptr1:_(p0), %d0:_(s20), %d1:_(s20) = G_INTRINSIC intrinsic(@llvm.aie2p.add.3d), %0:_(p0), %off:_(s20), %off:_(s20), %off:_(s20), %off:_(s20), %off:_(s20), %off:_(s20), %off:_(s20)

    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acquire), %lockid(s32), %lockval(s32)

    G_STORE %first(s32), %ptr1(p0) :: (store (s32))
    PseudoRET implicit $lr, implicit %first, implicit %second, implicit %ptr1
...

# Barrier is BEFORE both loads -- reorder is safe and should proceed.
---
name:            reorder_allowed_barrier_before_both
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: reorder_allowed_barrier_before_both
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: %lockid:_(s32) = G_CONSTANT i32 50
    ; CHECK-NEXT: %lockval:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: %off:_(s20) = G_CONSTANT i20 12
    ; CHECK-NEXT: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acquire), %lockid(s32), %lockval(s32)
    ; CHECK-NEXT: %second:_(s32) = G_AIE_OFFSET_LOAD [[COPY]](p0), %off(s20) :: (load (s32))
    ; CHECK-NEXT: %first:_(s32), %ptr1:_(p0), %d0:_(s20), %d1:_ = G_AIE_POSTINC_3D_LOAD [[COPY]], %off, %off, %off, %off, %off, %off, %off :: (load (s32))
    ; CHECK-NEXT: G_STORE %first(s32), [[COPY]](p0) :: (store (s32))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit %first(s32), implicit %second(s32), implicit %ptr1(p0)
    %0:_(p0) = COPY $p0
    %lockid:_(s32) = G_CONSTANT i32 50
    %lockval:_(s32) = G_CONSTANT i32 1
    %off:_(s20) = G_CONSTANT i20 12

    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acquire), %lockid(s32), %lockval(s32)

    %first:_(s32) = G_LOAD %0(p0) :: (load (s32))
    G_STORE %first(s32), %0(p0) :: (store (s32))
    %addr:_(p0) = nuw G_PTR_ADD %0, %off(s20)
    %second:_(s32) = G_LOAD %addr(p0) :: (load (s32))
    %ptr1:_(p0), %d0:_(s20), %d1:_(s20) = G_INTRINSIC intrinsic(@llvm.aie2p.add.3d), %0:_(p0), %off:_(s20), %off:_(s20), %off:_(s20), %off:_(s20), %off:_(s20), %off:_(s20), %off:_(s20)

    PseudoRET implicit $lr, implicit %first, implicit %second, implicit %ptr1
...

# Both combiner positions sit between two barriers (acquire before,
# release after). The load does not cross either barrier, so
# combination should proceed.
---
name:            reorder_allowed_barrier_around_both
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: reorder_allowed_barrier_around_both
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: %lock1:_(s32) = G_CONSTANT i32 40
    ; CHECK-NEXT: %lock2:_(s32) = G_CONSTANT i32 50
    ; CHECK-NEXT: %lockval:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: %off:_(s20) = G_CONSTANT i20 12
    ; CHECK-NEXT: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acquire), %lock1(s32), %lockval(s32)
    ; CHECK-NEXT: %second:_(s32) = G_AIE_OFFSET_LOAD [[COPY]](p0), %off(s20) :: (load (s32))
    ; CHECK-NEXT: %first:_(s32), %ptr1:_(p0), %d0:_(s20), %d1:_ = G_AIE_POSTINC_3D_LOAD [[COPY]], %off, %off, %off, %off, %off, %off, %off :: (load (s32))
    ; CHECK-NEXT: G_STORE %first(s32), [[COPY]](p0) :: (store (s32))
    ; CHECK-NEXT: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.release), %lock2(s32), %lockval(s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit %first(s32), implicit %second(s32), implicit %ptr1(p0)
    %0:_(p0) = COPY $p0
    %lock1:_(s32) = G_CONSTANT i32 40
    %lock2:_(s32) = G_CONSTANT i32 50
    %lockval:_(s32) = G_CONSTANT i32 1
    %off:_(s20) = G_CONSTANT i20 12

    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.acquire), %lock1(s32), %lockval(s32)

    %first:_(s32) = G_LOAD %0(p0) :: (load (s32))
    G_STORE %first(s32), %0(p0) :: (store (s32))
    %addr:_(p0) = nuw G_PTR_ADD %0, %off(s20)
    %second:_(s32) = G_LOAD %addr(p0) :: (load (s32))
    %ptr1:_(p0), %d0:_(s20), %d1:_(s20) = G_INTRINSIC intrinsic(@llvm.aie2p.add.3d), %0:_(p0), %off:_(s20), %off:_(s20), %off:_(s20), %off:_(s20), %off:_(s20), %off:_(s20), %off:_(s20)

    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2p.release), %lock2(s32), %lockval(s32)

    PseudoRET implicit $lr, implicit %first, implicit %second, implicit %ptr1
...
