# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc --mtriple=aie2p -verify-machineinstrs \
# RUN:  --start-before=aie-postlegalizer-generic-combiner \
# RUN:  --stop-after=aie-postlegalizer-custom-combiner \
# RUN: --aie-global-ptr-mod-opt=true \
# RUN:  --aie-address-chaining=true -o - %s  | FileCheck %s

# overlay gain: Do not penalize Immediates that can be reused, if the Immediates
# have to be copied to registers because they do not fit the bit encoding length.
# Thus select Post-Increments, since they only have a single copy penalty.

---
name:            shared-postinc-constants
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0, $p1, $p2
    ; CHECK-LABEL: name: shared-postinc-constants
    ; CHECK: liveins: $p0, $p1, $p2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; CHECK-NEXT: [[AIE_POSTINC_ZEXTLOAD:%[0-9]+]]:_(s32), [[AIE_POSTINC_ZEXTLOAD1:%[0-9]+]]:_(p0) = G_AIE_POSTINC_ZEXTLOAD [[COPY]], [[C]](s20) :: (load (s8))
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; CHECK-NEXT: [[AIE_POSTINC_ZEXTLOAD2:%[0-9]+]]:_(s32), [[AIE_POSTINC_ZEXTLOAD3:%[0-9]+]]:_(p0) = G_AIE_POSTINC_ZEXTLOAD [[AIE_POSTINC_ZEXTLOAD1]], [[C1]](s20) :: (load (s8))
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; CHECK-NEXT: [[AIE_POSTINC_ZEXTLOAD4:%[0-9]+]]:_(s32), [[AIE_POSTINC_ZEXTLOAD5:%[0-9]+]]:_(p0) = G_AIE_POSTINC_ZEXTLOAD [[AIE_POSTINC_ZEXTLOAD3]], [[C2]](s20) :: (load (s8))
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 16
    ; CHECK-NEXT: [[AIE_POSTINC_ZEXTLOAD6:%[0-9]+]]:_(s32), [[AIE_POSTINC_ZEXTLOAD7:%[0-9]+]]:_(p0) = G_AIE_POSTINC_ZEXTLOAD [[AIE_POSTINC_ZEXTLOAD5]], [[C3]](s20) :: (load (s8))
    ; CHECK-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[AIE_POSTINC_ZEXTLOAD7]](p0) :: (load (s8))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_POSTINC_ZEXTLOAD]](s32), implicit [[AIE_POSTINC_ZEXTLOAD2]](s32), implicit [[AIE_POSTINC_ZEXTLOAD4]](s32), implicit [[AIE_POSTINC_ZEXTLOAD6]](s32), implicit [[ZEXTLOAD]](s32)
    %0:_(p0) = COPY $p0
    %2:_(p0) = COPY $p2
    %3:_(s20) = G_CONSTANT i20 16
    %4:_(p0) = nuw G_PTR_ADD %0, %3(s20)
    %5:_(s32) = G_ZEXTLOAD %0(p0) :: (load (s8))
    %6:_(s32) = G_ZEXTLOAD %4(p0) :: (load (s8))
    %7:_(s20) = G_CONSTANT i20 44
    %22:_(s20) = G_CONSTANT i20 16
    %10:_(p0) = nuw G_PTR_ADD %4, %22(s20)
    %23:_(s20) = G_CONSTANT i20 16
    %12:_(p0) = nuw G_PTR_ADD %10, %23(s20)
    %13:_(s32) = G_ZEXTLOAD %10(p0) :: (load (s8))
    %14:_(s32) = G_ZEXTLOAD %12(p0) :: (load (s8))
    %24:_(s20) = G_CONSTANT i20 16
    %16:_(p0) = nuw G_PTR_ADD %12, %24(s20)
    %17:_(s32) = G_ZEXTLOAD %16(p0) :: (load (s8))
    PseudoRET implicit $lr, implicit %5, implicit %6, implicit %13, implicit %14, implicit %17
...

