# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc --mtriple=aie2p -verify-machineinstrs \
# RUN:  --start-before=aie-postlegalizer-generic-combiner \
# RUN:  --stop-after=aie-postlegalizer-custom-combiner \
# RUN:  --aie-address-chaining=false \
# RUN: --aie-global-ptr-mod-opt=true \
# RUN:  -o - %s  | FileCheck %s

# properly assign user intrinsics

---
name:            assign-user-intrinsics
legalized:       true
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0, $p1
    ; CHECK-LABEL: name: assign-user-intrinsics
    ; CHECK: liveins: $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $p1
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 8
    ; CHECK-NEXT: [[AIE_OFFSET_LOAD:%[0-9]+]]:_(s32) = G_AIE_OFFSET_LOAD [[COPY]](p0), [[C]](s20) :: (load (s32))
    ; CHECK-NEXT: [[AIE_POSTINC_3D_LOAD:%[0-9]+]]:_(s32), [[AIE_POSTINC_3D_LOAD1:%[0-9]+]]:_(p0), [[AIE_POSTINC_3D_LOAD2:%[0-9]+]]:_(s20), [[AIE_POSTINC_3D_LOAD3:%[0-9]+]]:_ = G_AIE_POSTINC_3D_LOAD [[COPY]], [[C]], [[C]], [[C]], [[C]], [[C]], [[C]], [[C]] :: (load (s32))
    ; CHECK-NEXT: [[AIE_OFFSET_LOAD1:%[0-9]+]]:_(s32) = G_AIE_OFFSET_LOAD [[COPY1]](p0), [[C]](s20) :: (load (s32))
    ; CHECK-NEXT: [[AIE_POSTINC_3D_LOAD4:%[0-9]+]]:_(s32), [[AIE_POSTINC_3D_LOAD5:%[0-9]+]]:_(p0), [[AIE_POSTINC_3D_LOAD6:%[0-9]+]]:_(s20), [[AIE_POSTINC_3D_LOAD7:%[0-9]+]]:_ = G_AIE_POSTINC_3D_LOAD [[COPY1]], [[C]], [[C]], [[C]], [[C]], [[C]], [[C]], [[C]] :: (load (s32))
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_POSTINC_3D_LOAD]](s32), implicit [[AIE_OFFSET_LOAD]](s32), implicit [[AIE_POSTINC_3D_LOAD4]](s32), implicit [[AIE_OFFSET_LOAD1]](s32), implicit [[AIE_POSTINC_3D_LOAD1]](p0), implicit [[AIE_POSTINC_3D_LOAD5]](p0)
    %0:_(p0) = COPY $p0
    %1:_(p0) = COPY $p1
    %2:_(s20) = G_CONSTANT i20 8
    %3:_(s32) = G_LOAD %0(p0) :: (load (s32))
    %4:_(p0) = nuw G_PTR_ADD %0, %2
    %5:_(s32) = G_LOAD %4(p0) :: (load (s32))
    %6:_(s32) = G_LOAD %1(p0) :: (load (s32))
    %7:_(p0) = nuw G_PTR_ADD %1, %2
    %8:_(s32) = G_LOAD %7(p0) :: (load (s32))
    %9:_(p0), %10:_(s20), %11:_(s20) = G_INTRINSIC intrinsic(@llvm.aie2p.add.3d), %0:_(p0), %2:_(s20), %2:_(s20), %2:_(s20), %2:_(s20), %2:_(s20), %2:_(s20), %2:_(s20)
    %12:_(p0), %13:_(s20), %14:_(s20) = G_INTRINSIC intrinsic(@llvm.aie2p.add.3d), %1:_(p0), %2:_(s20), %2:_(s20), %2:_(s20), %2:_(s20), %2:_(s20), %2:_(s20), %2:_(s20)
    PseudoRET implicit $lr, implicit %3, implicit %5, implicit %6, implicit %8, implicit %9, implicit %12
...



