# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc --mtriple=aie2 --issue-limit=6 --run-pass=postmisched \
# RUN:     --aie-interblock-scoreboard=false --aie-interblock-latency=false \
# RUN:     %s -o - | FileCheck %s

# Check that the safety margin is respected if we switch off interblock latency
# We disable the interblock scoreboard from the commandline to make the
# test more sensitive

---
name:            oneSucc
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: oneSucc
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $wl0 = VLDA_dmw_lda_w_ag_idx_imm killed $p0, 0
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT:   liveins: $r1, $r2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $r1 = OR killed $r1, $r2
  ; CHECK-NEXT:   $r1 = AND killed $r1, $r2
  ; CHECK-NEXT:   $r1 = OR killed $r1, $r2
  ; CHECK-NEXT:   $r1 = AND killed $r1, $r2
  ; CHECK-NEXT:   $r1 = OR killed $r1, $r2
  ; CHECK-NEXT:   $r1 = AND killed $r1, $r2
  ; CHECK-NEXT:   $r1 = OR killed $r1, killed $r2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   liveins: $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   RET implicit $lr
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   DelayedSchedBarrier implicit killed $r1

  bb.0:
    successors: %bb.1
    liveins: $p0
    $wl0 = VLDA_dmw_lda_w_ag_idx_imm $p0, 0
  bb.1:
    successors: %bb.2
    liveins: $r1, $r2
    $r1 = OR $r1, $r2
    $r1 = AND $r1, $r2
    $r1 = OR $r1, $r2
    $r1 = AND $r1, $r2
    $r1 = OR $r1, $r2
    $r1 = AND $r1, $r2
    $r1 = OR $r1, $r2
  bb.2:
    successors:
    liveins: $r1
    RET implicit $lr
    DelayedSchedBarrier implicit $r1
...
