# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 -run-pass=postmisched %s -o - \
# RUN:   | FileCheck %s

# An REL followed by a store must keep the store outside the lock's core-resume
# window, just like a load. Several stores are issued so that one cannot sink
# into the RET delay slots and instead sits at the top of the successor block,
# on the lock's exit edge, where the resume window binds.

#
# The *_rev_* functions cover the reverse direction: a memory op in the
# predecessor and the REL alone in the successor (isolated so it anchors at
# the successor's first cycle). The backward stall window is carried across
# the border, so the memory op is held back from the lock.
---
name:            rel_store_same_mbb
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0, $r0, $r1
    ; CHECK-LABEL: name: rel_store_same_mbb
    ; CHECK: liveins: $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: REL_mLockId_imm 0, killed $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: BUNDLE implicit $r1, implicit $p0, implicit $lr {
    ; CHECK-NEXT:   ST_dms_sts_idx_imm $r1, $p0, 0
    ; CHECK-NEXT:   RET implicit $lr
    ; CHECK-NEXT: }
    ; CHECK-NEXT: ST_dms_sts_idx_imm $r1, $p0, 4
    ; CHECK-NEXT: ST_dms_sts_idx_imm $r1, $p0, 8
    ; CHECK-NEXT: ST_dms_sts_idx_imm $r1, $p0, 12
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed $r1, killed $p0, 16
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: DelayedSchedBarrier
    REL_mLockId_imm 0, $r0
    ST_dms_sts_idx_imm $r1, $p0, 0
    ST_dms_sts_idx_imm $r1, $p0, 4
    ST_dms_sts_idx_imm $r1, $p0, 8
    ST_dms_sts_idx_imm $r1, $p0, 12
    ST_dms_sts_idx_imm $r1, $p0, 16
    RET implicit $lr
    DelayedSchedBarrier
...

---
name:            rel_store_mbb_border
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: rel_store_mbb_border
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $r0, $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   REL_mLockId_imm 0, killed $r0
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   DelayedSchedBarrier
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   liveins: $p0, $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BUNDLE implicit $r1, implicit $p0, implicit $lr {
  ; CHECK-NEXT:     ST_dms_sts_idx_imm $r1, $p0, 0
  ; CHECK-NEXT:     RET implicit $lr
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   ST_dms_sts_idx_imm $r1, $p0, 4
  ; CHECK-NEXT:   ST_dms_sts_idx_imm $r1, $p0, 8
  ; CHECK-NEXT:   ST_dms_sts_idx_imm $r1, $p0, 12
  ; CHECK-NEXT:   ST_dms_sts_idx_imm killed $r1, killed $p0, 16
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   DelayedSchedBarrier
  bb.0:
    successors: %bb.1
    liveins: $p0, $r0, $r1
    REL_mLockId_imm 0, $r0
    DelayedSchedBarrier

  bb.1:
    liveins: $p0, $r1
    ST_dms_sts_idx_imm $r1, $p0, 0
    ST_dms_sts_idx_imm $r1, $p0, 4
    ST_dms_sts_idx_imm $r1, $p0, 8
    ST_dms_sts_idx_imm $r1, $p0, 12
    ST_dms_sts_idx_imm $r1, $p0, 16
    RET implicit $lr
    DelayedSchedBarrier
...

---
name:            store_rel_rev_same_mbb
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0, $r0, $r1
    ; CHECK-LABEL: name: store_rel_rev_same_mbb
    ; CHECK: liveins: $p0, $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: ST_dms_sts_idx_imm $r1, $p0, 0
    ; CHECK-NEXT: ST_dms_sts_idx_imm $r1, $p0, 4
    ; CHECK-NEXT: ST_dms_sts_idx_imm $r1, $p0, 8
    ; CHECK-NEXT: ST_dms_sts_idx_imm $r1, $p0, 12
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed $r1, killed $p0, 16
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: RET implicit $lr
    ; CHECK-NEXT: REL_mLockId_imm 0, killed $r0
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: DelayedSchedBarrier
    ST_dms_sts_idx_imm $r1, $p0, 0
    ST_dms_sts_idx_imm $r1, $p0, 4
    ST_dms_sts_idx_imm $r1, $p0, 8
    ST_dms_sts_idx_imm $r1, $p0, 12
    ST_dms_sts_idx_imm $r1, $p0, 16
    REL_mLockId_imm 0, $r0
    RET implicit $lr
    DelayedSchedBarrier
...

---
name:            store_rel_rev_mbb_border
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: store_rel_rev_mbb_border
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $r0, $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   ST_dms_sts_idx_imm $r1, $p0, 0
  ; CHECK-NEXT:   ST_dms_sts_idx_imm $r1, $p0, 4
  ; CHECK-NEXT:   ST_dms_sts_idx_imm $r1, $p0, 8
  ; CHECK-NEXT:   ST_dms_sts_idx_imm $r1, $p0, 12
  ; CHECK-NEXT:   ST_dms_sts_idx_imm killed $r1, killed $p0, 16
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   DelayedSchedBarrier
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   REL_mLockId_imm 0, killed $r0
  ; CHECK-NEXT:   DelayedSchedBarrier
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   RET implicit $lr
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   DelayedSchedBarrier
  bb.0:
    successors: %bb.1
    liveins: $p0, $r0, $r1
    ST_dms_sts_idx_imm $r1, $p0, 0
    ST_dms_sts_idx_imm $r1, $p0, 4
    ST_dms_sts_idx_imm $r1, $p0, 8
    ST_dms_sts_idx_imm $r1, $p0, 12
    ST_dms_sts_idx_imm $r1, $p0, 16
    DelayedSchedBarrier

  bb.1:
    successors: %bb.2
    liveins: $r0
    REL_mLockId_imm 0, $r0
    DelayedSchedBarrier

  bb.2:
    RET implicit $lr
    DelayedSchedBarrier
...
