# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2 %topdown-multi -run-pass=postmisched %s -o - \
# RUN:   | FileCheck %s

# The lock's core-resume window only governs memory ops. Each function follows
# the REL with five non-memory scalar ops: these pack tightly against the REL
# (and into the RET delay slots) with no spacing, confirming the lock does not
# interfere with non-memory instructions.

#
# The *_rev_* functions cover the reverse direction: a non-memory op in the
# predecessor and the REL alone in the successor. No memory op means no
# backward stall window, so the lock packs against the predecessor with no
# spacing across the border.
---
name:            rel_nomemory_same_mbb
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r0, $r1
    ; CHECK-LABEL: name: rel_nomemory_same_mbb
    ; CHECK: liveins: $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $r6 = ADD_add_r_ri $r1, 1, implicit-def $srcarry
    ; CHECK-NEXT: RET implicit $lr
    ; CHECK-NEXT: REL_mLockId_imm 0, killed $r0
    ; CHECK-NEXT: $r7 = ADD_add_r_ri $r1, 2, implicit-def $srcarry
    ; CHECK-NEXT: $r8 = ADD_add_r_ri $r1, 3, implicit-def $srcarry
    ; CHECK-NEXT: $r9 = ADD_add_r_ri $r1, 4, implicit-def $srcarry
    ; CHECK-NEXT: $r10 = ADD_add_r_ri killed $r1, 5, implicit-def $srcarry
    ; CHECK-NEXT: DelayedSchedBarrier
    REL_mLockId_imm 0, $r0
    $r6 = ADD_add_r_ri $r1, 1, implicit-def $srcarry
    $r7 = ADD_add_r_ri $r1, 2, implicit-def $srcarry
    $r8 = ADD_add_r_ri $r1, 3, implicit-def $srcarry
    $r9 = ADD_add_r_ri $r1, 4, implicit-def $srcarry
    $r10 = ADD_add_r_ri $r1, 5, implicit-def $srcarry
    RET implicit $lr
    DelayedSchedBarrier
...

---
name:            rel_nomemory_mbb_border
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: rel_nomemory_mbb_border
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $r0, $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   REL_mLockId_imm 0, killed $r0
  ; CHECK-NEXT:   DelayedSchedBarrier
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   liveins: $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   RET implicit $lr
  ; CHECK-NEXT:   $r6 = ADD_add_r_ri $r1, 1, implicit-def $srcarry
  ; CHECK-NEXT:   $r7 = ADD_add_r_ri $r1, 2, implicit-def $srcarry
  ; CHECK-NEXT:   $r8 = ADD_add_r_ri $r1, 3, implicit-def $srcarry
  ; CHECK-NEXT:   $r9 = ADD_add_r_ri $r1, 4, implicit-def $srcarry
  ; CHECK-NEXT:   $r10 = ADD_add_r_ri killed $r1, 5, implicit-def $srcarry
  ; CHECK-NEXT:   DelayedSchedBarrier
  bb.0:
    successors: %bb.1
    liveins: $r0, $r1
    REL_mLockId_imm 0, $r0
    DelayedSchedBarrier

  bb.1:
    liveins: $r1
    $r6 = ADD_add_r_ri $r1, 1, implicit-def $srcarry
    $r7 = ADD_add_r_ri $r1, 2, implicit-def $srcarry
    $r8 = ADD_add_r_ri $r1, 3, implicit-def $srcarry
    $r9 = ADD_add_r_ri $r1, 4, implicit-def $srcarry
    $r10 = ADD_add_r_ri $r1, 5, implicit-def $srcarry
    RET implicit $lr
    DelayedSchedBarrier
...

---
name:            nomemory_rel_rev_same_mbb
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r0, $r1
    ; CHECK-LABEL: name: nomemory_rel_rev_same_mbb
    ; CHECK: liveins: $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $r6 = ADD_add_r_ri $r1, 1, implicit-def $srcarry
    ; CHECK-NEXT: RET implicit $lr
    ; CHECK-NEXT: REL_mLockId_imm 0, killed $r0
    ; CHECK-NEXT: $r7 = ADD_add_r_ri $r1, 2, implicit-def $srcarry
    ; CHECK-NEXT: $r8 = ADD_add_r_ri $r1, 3, implicit-def $srcarry
    ; CHECK-NEXT: $r9 = ADD_add_r_ri $r1, 4, implicit-def $srcarry
    ; CHECK-NEXT: $r10 = ADD_add_r_ri killed $r1, 5, implicit-def $srcarry
    ; CHECK-NEXT: DelayedSchedBarrier
    $r6 = ADD_add_r_ri $r1, 1, implicit-def $srcarry
    $r7 = ADD_add_r_ri $r1, 2, implicit-def $srcarry
    $r8 = ADD_add_r_ri $r1, 3, implicit-def $srcarry
    $r9 = ADD_add_r_ri $r1, 4, implicit-def $srcarry
    $r10 = ADD_add_r_ri $r1, 5, implicit-def $srcarry
    REL_mLockId_imm 0, $r0
    RET implicit $lr
    DelayedSchedBarrier
...

---
name:            nomemory_rel_rev_mbb_border
alignment:       16
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: nomemory_rel_rev_mbb_border
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $r0, $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $r6 = ADD_add_r_ri $r1, 1, implicit-def $srcarry
  ; CHECK-NEXT:   $r7 = ADD_add_r_ri $r1, 2, implicit-def $srcarry
  ; CHECK-NEXT:   $r8 = ADD_add_r_ri $r1, 3, implicit-def $srcarry
  ; CHECK-NEXT:   $r9 = ADD_add_r_ri $r1, 4, implicit-def $srcarry
  ; CHECK-NEXT:   $r10 = ADD_add_r_ri killed $r1, 5, implicit-def $srcarry
  ; CHECK-NEXT:   DelayedSchedBarrier
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   REL_mLockId_imm 0, killed $r0
  ; CHECK-NEXT:   DelayedSchedBarrier
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   RET implicit $lr
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   DelayedSchedBarrier
  bb.0:
    successors: %bb.1
    liveins: $r0, $r1
    $r6 = ADD_add_r_ri $r1, 1, implicit-def $srcarry
    $r7 = ADD_add_r_ri $r1, 2, implicit-def $srcarry
    $r8 = ADD_add_r_ri $r1, 3, implicit-def $srcarry
    $r9 = ADD_add_r_ri $r1, 4, implicit-def $srcarry
    $r10 = ADD_add_r_ri $r1, 5, implicit-def $srcarry
    DelayedSchedBarrier

  bb.1:
    successors: %bb.2
    liveins: $r0
    REL_mLockId_imm 0, $r0
    DelayedSchedBarrier

  bb.2:
    RET implicit $lr
    DelayedSchedBarrier
...
