# NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc --mtriple=aie2p --start-before=postmisched %s -o - | FileCheck %s

--- |
  target datalayout = "e-m:e-p:20:32-i1:8:32-i8:8:32-i16:16:32-i32:32:32-f32:32:32-i64:32-f64:32-a:0:32-n32"
  target triple = "aie2p-none-unknown-elf"

  define dso_local void @_Z1fPii(ptr %p, i32 noundef %n) local_unnamed_addr #0 {
  ; CHECK-LABEL: _Z1fPii:
  ; CHECK:         .p2align 4
  ; CHECK-NEXT:  // %bb.0: // %entry
  ; CHECK-NEXT:    mova m0, #4; nopb ; nopxm ; nops
  ; CHECK-NEXT:    mova dn0, #16; mov m1, m0
  ; CHECK-NEXT:    mova dc1, #0; movs p1, p0; mov dn1, dn0
  ; CHECK-NEXT:    movs dj1, m0; mov dc0, dc1
  ; CHECK-NEXT:    lda.2d r1, [p1], d1
  ; CHECK-NEXT:    nop
  ; CHECK-NEXT:    mova r1, #4; movxm ls, #.LBB0_1
  ; CHECK-NEXT:    lda.2d r1, [p1], d1; movxm le, #.L_LEnd0
  ; CHECK-NEXT:    nopa ; nopb ; nops ; nopx ; add.nc lc, r1, #-3; nopv
  ; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; nopv
  ; CHECK-NEXT:    lda.2d r1, [p1], d1; nopb ; nops ; movx r0, #10; nopm ; nopv
  ; CHECK-NEXT:    nopa ; nopb ; nops ; mul r1, r1, r0; nopm ; nopv
  ; CHECK-NEXT:    nopa ; nopb ; nops ; nopx ; mov dj0, m0; nopv
  ; CHECK-NEXT:    .p2align 4
  ; CHECK-NEXT:  .LBB0_1: // %for.body
  ; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
  ; CHECK-NEXT:    lda.2d r1, [p1], d1; nopb ; st.2d r1, [p0], d0; nopxm ; nopv
  ; CHECK-NEXT:    nopa ; nopb ; nops ; mul r1, r1, r0; nopm ; nopv
  ; CHECK-NEXT:  .L_LEnd0:
  ; CHECK-NEXT:    nopa ; nopb ; nops ; nopxm ; nopv
  ; CHECK-NEXT:  // %bb.2: // %for.cond.cleanup
  ; CHECK-NEXT:    st.2d r1, [p0], d0; nopb ; nopx
  ; CHECK-NEXT:    mul r1, r1, r0
  ; CHECK-NEXT:    ret lr
  ; CHECK-NEXT:    st.2d r1, [p0], d0 // Delay Slot 5
  ; CHECK-NEXT:    mul r1, r1, r0 // Delay Slot 4
  ; CHECK-NEXT:    nop // Delay Slot 3
  ; CHECK-NEXT:    st.2d r1, [p0], d0 // Delay Slot 2
  ; CHECK-NEXT:    nop // Delay Slot 1
  entry:
    call void @llvm.set.loop.iterations.i32(i32 4)
    br label %for.body

  for.cond.cleanup:                                 ; preds = %for.body
    ret void

  for.body:                                         ; preds = %for.body, %entry
    %put.09 = phi ptr [ %p, %entry ], [ %5, %for.body ]
    %get.08 = phi ptr [ %p, %entry ], [ %10, %for.body ]
    %count2.07 = phi i32 [ 0, %entry ], [ %9, %for.body ]
    %count1.06 = phi i32 [ 0, %entry ], [ %4, %for.body ]
    %0 = load i32, ptr %get.08, align 4, !tbaa !2
    %mul = mul nsw i32 %0, 10
    store i32 %mul, ptr %put.09, align 4, !tbaa !2
    %1 = trunc nuw i32 %count1.06 to i20
    %2 = tail call { ptr, i20 } @llvm.aie2p.add.2d(ptr nonnull %put.09, i20 4, i20 4, i20 16, i20 %1)
    %3 = extractvalue { ptr, i20 } %2, 1
    %4 = zext i20 %3 to i32
    %5 = extractvalue { ptr, i20 } %2, 0
    %6 = trunc nuw i32 %count2.07 to i20
    %7 = tail call { ptr, i20 } @llvm.aie2p.add.2d(ptr nonnull %get.08, i20 4, i20 4, i20 16, i20 %6)
    %8 = extractvalue { ptr, i20 } %7, 1
    %9 = zext i20 %8 to i32
    %10 = extractvalue { ptr, i20 } %7, 0
    %11 = call i1 @llvm.loop.decrement.i32(i32 1)
    br i1 %11, label %for.body, label %for.cond.cleanup, !llvm.loop !6
  }

  declare { ptr, i20 } @llvm.aie2p.add.2d(ptr, i20, i20, i20, i20) #1
  declare void @llvm.set.loop.iterations.i32(i32) #2
  declare i1 @llvm.loop.decrement.i32(i32) #2
  attributes #0 = { mustprogress nofree nosync nounwind memory(readwrite, inaccessiblemem: none) "no-trapping-math"="true" "stack-protector-buffer-size"="8" }
  attributes #1 = { nounwind memory(none) }
  attributes #2 = { nocallback noduplicate nofree nosync nounwind willreturn }

  !llvm.module.flags = !{!0}
  !llvm.ident = !{!1}

  !0 = !{i32 1, !"wchar_size", i32 4}
  !1 = !{!"clang version 19.0.0git (git@github.com:Xilinx/llvm-aie.git 17b26e29fd35377804d813a51f42ac19ecf97150)"}
  !2 = !{!3, !3, i64 0}
  !3 = !{!"int", !4, i64 0}
  !4 = !{!"omnipotent char", !5, i64 0}
  !5 = !{!"Simple C++ TBAA"}
  !6 = distinct !{!6, !7, !8, !9}
  !7 = !{!"llvm.loop.mustprogress"}
  !8 = !{!"llvm.loop.unroll.disable"}
  !9 = !{!"llvm.loop.itercount.range", i64 4}

...
---
name:            _Z1fPii
alignment:       16
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
isOutlined:      false
debugInstrRef:   false
failsVerification: false
tracksDebugUserValues: true
registers:       []
liveins:         []
calleeSavedRegisters: [ '$lr', '$r8', '$r9', '$r10', '$r11', '$r12', '$r13',
                        '$r14', '$r15', '$p6', '$p7' ]
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 0
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
entry_values:    []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo:
  varArgsFrameIndex: 0
body:             |
  bb.0.entry (align 16):
    successors: %bb.1(0x80000000)
    liveins: $p0, $r0

    renamable $m0 = MOV_PD_imm11_pseudo 4
    $m1 = MOV_alu_mv_mv_mv_scl $m0
    renamable $dn0 = MOV_PD_imm11_pseudo 16
    renamable $r1 = MOV_RLC_imm11_pseudo 4
    $dn1 = MOV_alu_mv_mv_mv_scl $dn0
    renamable $dc1 = MOV_PD_imm11_pseudo 0
    renamable $r0 = MOV_RLC_imm11_pseudo 10
    $lc = ADD_NC_mv_add_ri $r1, 0
    $ls = MOVXM %bb.1
    $le = MOVXM <mcsymbol .L_LEnd0>
    $dj1 = MOV_scalar_pseudo $m0
    $p1 = MOV_scalar_pseudo $p0
    $dc0 = MOV_scalar_pseudo $dc1
    $dj0 = MOV_scalar_pseudo $m0

  bb.1.for.body (align 16):
    successors: %bb.1(0x7c000000), %bb.2(0x04000000)
    liveins: $d0:0x0000000000200600, $d1:0x0000000000200E00, $dc0, $dc1, $dj1, $dn0, $dn1, $m0, $m1, $p0, $p1, $r0, $dj0

    $r1, $p1, $dc1 = LDA_2D_dms_lda killed $p1, $d1 :: (load (s32) from %ir.get.08, !tbaa !2)
    renamable $r1 = nsw MUL killed renamable $r1, renamable $r0
    $p0, $dc0 = ST_2D_dms_sts killed $r1, killed $p0, $d0 :: (store (s32) into %ir.put.09, !tbaa !2)
    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.1, implicit $ls, implicit $le

  bb.2.for.cond.cleanup:
    RET implicit $lr
    DelayedSchedBarrier

...
