# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple=aie2p %s --run-pass=aie-machine-alignment -o - | FileCheck %s

# bb.2 is the layout successor of bb.1, but also part of a jump table.
# bb.1 ends in an unconditional indirect branch, that happens to jump to bb.2
# However, bb.2 still needs to be aligned, and cannot be merged with bb.1 for
# alignment purposes.

---
name:            align_jt
alignment:       16
jumpTable:
  kind:            block-address
  entries:
    - id:              0
      blocks:          [ '%bb.4', '%bb.2' ]
body:             |
  ; CHECK-LABEL: name: align_jt
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $p1, $p2, $p3, $r0, $r1, $r2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BUNDLE implicit-def $r3, implicit killed $p2 {
  ; CHECK-NEXT:     renamable $r3 = LDA_s8_idx_imm killed renamable $p2, 0 :: (dereferenceable load (s8))
  ; CHECK-NEXT:     NOPB
  ; CHECK-NEXT:     NOPS
  ; CHECK-NEXT:     NOPXM
  ; CHECK-NEXT:     NOPV
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x0, implicit-def $wl0, implicit-def $wh0, implicit killed $r3 {
  ; CHECK-NEXT:     NOPX
  ; CHECK-NEXT:     renamable $x0 = VBCST_8 killed renamable $r3
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $r1 {
  ; CHECK-NEXT:     renamable $r1 = MOVA 64
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   DelayedSchedBarrier
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.5(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $p0, $p1, $p3, $r0, $r1, $r2, $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BUNDLE implicit-def $r3, implicit-def $p2 {
  ; CHECK-NEXT:     renamable $r3 = MOVA 2
  ; CHECK-NEXT:     renamable $p2 = MOVXM target-flags(aie2p-global) %jump-table.0
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $r2, implicit killed $r2, implicit killed $r3 {
  ; CHECK-NEXT:     renamable $r2 = LSHL killed renamable $r2, killed renamable $r3
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $dj0, implicit killed $r2 {
  ; CHECK-NEXT:     $dj0 = MOV_alu_mv_mv_mv_scl killed $r2
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $p2, implicit killed $p2, implicit killed $dj0 {
  ; CHECK-NEXT:     renamable $p2 = LDA_dms_lda_idx killed renamable $p2, killed renamable $dj0 :: (load (p0), align 4)
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit killed $p2 {
  ; CHECK-NEXT:     J_alumv_or killed renamable $p2
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $r2, implicit killed $p3 {
  ; CHECK-NEXT:     renamable $r2 = LDA_s8_idx_imm killed renamable $p3, 0 :: (dereferenceable load (s8))
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $r3 {
  ; CHECK-NEXT:     renamable $r3 = MOVA 0
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x2, implicit-def $wl2, implicit-def $wh2, implicit killed $r3 {
  ; CHECK-NEXT:     renamable $x2 = VBCST_8 killed renamable $r3
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   DelayedSchedBarrier
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $p1, $r0, $r1, $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BUNDLE implicit-def $r27, implicit $r1, implicit $r0 {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     NOPB
  ; CHECK-NEXT:     NOPS
  ; CHECK-NEXT:     renamable $r27 = LTU renamable $r1, renamable $r0
  ; CHECK-NEXT:     NOPM
  ; CHECK-NEXT:     NOPV
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $ls {
  ; CHECK-NEXT:     $ls = MOVXM %bb.3
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $le {
  ; CHECK-NEXT:     $le = MOVXM <mcsymbol .L_LEnd3>
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $r0, implicit killed $r0, implicit killed $r1, implicit killed $r27 {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     renamable $r0 = SEL_NEZ killed renamable $r0, killed renamable $r1, killed renamable $r27
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $r1, implicit-def $r0, implicit-def dead $srcarry, implicit killed $r0 {
  ; CHECK-NEXT:     renamable $r1 = MOVA -6
  ; CHECK-NEXT:     renamable $r0 = ADD_add_r_ri killed renamable $r0, -1, implicit-def dead $srcarry
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $r0, implicit killed $r0, implicit killed $r1 {
  ; CHECK-NEXT:     renamable $r0 = LSHL killed renamable $r0, killed renamable $r1
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $r0, implicit-def dead $srcarry, implicit killed $r0 {
  ; CHECK-NEXT:     renamable $r0 = nuw nsw ADD_add_r_ri killed renamable $r0, 1, implicit-def dead $srcarry
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $lc, implicit killed $r0 {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     NOPB
  ; CHECK-NEXT:     NOPS
  ; CHECK-NEXT:     NOPX
  ; CHECK-NEXT:     $lc = ADD_NC_mv_add_ri killed $r0, 0
  ; CHECK-NEXT:     NOPV
  ; CHECK-NEXT:   }
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.3(0x7c000000), %bb.4(0x04000000)
  ; CHECK-NEXT:   liveins: $p0, $p1, $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BUNDLE implicit-def $x2, implicit-def $wl2, implicit-def $wh2, implicit-def $p0, implicit killed $p0 {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     renamable $x2, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 64 :: (load (<64 x s8>))
  ; CHECK-NEXT:     NOPS
  ; CHECK-NEXT:     NOPXM
  ; CHECK-NEXT:     NOPV
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     NOPB
  ; CHECK-NEXT:     NOPS
  ; CHECK-NEXT:     NOPXM
  ; CHECK-NEXT:     NOPV
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     NOPB
  ; CHECK-NEXT:     NOPS
  ; CHECK-NEXT:     NOPXM
  ; CHECK-NEXT:     NOPV
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     NOPB
  ; CHECK-NEXT:     NOPS
  ; CHECK-NEXT:     NOPXM
  ; CHECK-NEXT:     NOPV
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     NOPB
  ; CHECK-NEXT:     NOPS
  ; CHECK-NEXT:     NOPXM
  ; CHECK-NEXT:     NOPV
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     NOPB
  ; CHECK-NEXT:     NOPX
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x4, implicit-def $wl4, implicit-def $wh4, implicit-def dead $l8, implicit $x0, implicit killed $x2, implicit $vaddsign0 {
  ; CHECK-NEXT:     renamable $x4, dead renamable $l8 = VMIN_GE_8_vaddSign0 renamable $x0, killed renamable $x2, implicit $vaddsign0
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $p1, implicit killed $x4, implicit killed $p1 {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     NOPB
  ; CHECK-NEXT:     renamable $p1 = VST_dmx_sts_x_pstm_nrm_imm killed renamable $x4, killed renamable $p1, 64 :: (store (<64 x s8>))
  ; CHECK-NEXT:     NOPXM
  ; CHECK-NEXT:     NOPV
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   PseudoLoopEnd <mcsymbol .L_LEnd3>, %bb.3, implicit $ls, implicit $le
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   successors: %bb.8(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     J_lng %bb.8
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   DelayedSchedBarrier
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5:
  ; CHECK-NEXT:   successors: %bb.6(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $p1, $r0, $r1, $r2, $x0, $x2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BUNDLE implicit-def $r27, implicit $r1, implicit $r0 {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     NOPB
  ; CHECK-NEXT:     NOPS
  ; CHECK-NEXT:     renamable $r27 = LTU renamable $r1, renamable $r0
  ; CHECK-NEXT:     NOPM
  ; CHECK-NEXT:     NOPV
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $ls {
  ; CHECK-NEXT:     $ls = MOVXM %bb.6
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $le {
  ; CHECK-NEXT:     $le = MOVXM <mcsymbol .L_LEnd1>
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $r0, implicit killed $r0, implicit killed $r1, implicit killed $r27 {
  ; CHECK-NEXT:     renamable $r0 = SEL_NEZ killed renamable $r0, killed renamable $r1, killed renamable $r27
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $r1, implicit-def $r0, implicit-def dead $srcarry, implicit killed $r0 {
  ; CHECK-NEXT:     renamable $r1 = MOVA -6
  ; CHECK-NEXT:     renamable $r0 = ADD_add_r_ri killed renamable $r0, -1, implicit-def dead $srcarry
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $r0, implicit killed $r0, implicit killed $r1 {
  ; CHECK-NEXT:     renamable $r0 = LSHL killed renamable $r0, killed renamable $r1
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $r0, implicit-def dead $srcarry, implicit-def $x4, implicit-def $wl4, implicit-def $wh4, implicit killed $r0, implicit killed $r2 {
  ; CHECK-NEXT:     renamable $r0 = nuw nsw ADD_add_r_ri killed renamable $r0, 1, implicit-def dead $srcarry
  ; CHECK-NEXT:     renamable $x4 = VBCST_8 killed renamable $r2
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $lc, implicit killed $r0 {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     NOPB
  ; CHECK-NEXT:     NOPS
  ; CHECK-NEXT:     NOPX
  ; CHECK-NEXT:     $lc = ADD_NC_mv_add_ri killed $r0, 0
  ; CHECK-NEXT:     NOPV
  ; CHECK-NEXT:   }
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6:
  ; CHECK-NEXT:   successors: %bb.6(0x7c000000), %bb.7(0x04000000)
  ; CHECK-NEXT:   liveins: $p0, $p1, $x0, $x2, $x4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BUNDLE implicit-def $x6, implicit-def $wl6, implicit-def $wh6, implicit-def $p0, implicit killed $p0 {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     renamable $x6, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 64 :: (load (<64 x s8>))
  ; CHECK-NEXT:     NOPS
  ; CHECK-NEXT:     NOPXM
  ; CHECK-NEXT:     NOPV
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     NOPB
  ; CHECK-NEXT:     NOPS
  ; CHECK-NEXT:     NOPXM
  ; CHECK-NEXT:     NOPV
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     NOPB
  ; CHECK-NEXT:     NOPS
  ; CHECK-NEXT:     NOPXM
  ; CHECK-NEXT:     NOPV
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     NOPB
  ; CHECK-NEXT:     NOPS
  ; CHECK-NEXT:     NOPXM
  ; CHECK-NEXT:     NOPV
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     NOPB
  ; CHECK-NEXT:     NOPS
  ; CHECK-NEXT:     NOPXM
  ; CHECK-NEXT:     NOPV
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $l0, implicit-def $r0, implicit-def $r1, implicit $x0, implicit killed $x6, implicit $vaddsign0 {
  ; CHECK-NEXT:     renamable $l0 = VLT_8_vaddSign0 renamable $x0, killed renamable $x6, implicit $vaddsign0
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $x8, implicit-def $wl8, implicit-def $wh8, implicit $x2, implicit $x4, implicit killed $l0 {
  ; CHECK-NEXT:     renamable $x8 = VSEL_8 renamable $x2, renamable $x4, killed renamable $l0
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $p1, implicit killed $x8, implicit killed $p1 {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     NOPB
  ; CHECK-NEXT:     renamable $p1 = VST_dmx_sts_x_pstm_nrm_imm killed renamable $x8, killed renamable $p1, 64 :: (store (<64 x s8>))
  ; CHECK-NEXT:     NOPXM
  ; CHECK-NEXT:     NOPV
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   PseudoLoopEnd <mcsymbol .L_LEnd1>, %bb.6, implicit $ls, implicit $le
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.7:
  ; CHECK-NEXT:   successors: %bb.8(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     J_lng %bb.8
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   DelayedSchedBarrier
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.8:
  ; CHECK-NEXT:   BUNDLE implicit $lr {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     RET implicit $lr
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   DelayedSchedBarrier
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $p0, $p1, $p2, $p3, $r0, $r1, $r2

    BUNDLE implicit-def $r3, implicit killed $p2 {
      renamable $r3 = LDA_s8_idx_imm killed renamable $p2, 0 :: (dereferenceable load (s8))
    }
    BUNDLE implicit-def $x0, implicit-def $wl0, implicit-def $wh0, implicit killed $r3 {
      renamable $x0 = VBCST_8 killed renamable $r3
    }
    BUNDLE implicit-def $r1 {
      renamable $r1 = MOVA 64
    }
    DelayedSchedBarrier

  bb.1:
    successors: %bb.4(0x40000000), %bb.2(0x40000000)
    liveins: $p0, $p1, $p3, $r0, $r1, $r2, $x0

    BUNDLE implicit-def $r3, implicit-def $p2 {
      renamable $r3 = MOVA 2
      renamable $p2 = MOVXM target-flags(aie2p-global) %jump-table.0
    }
    BUNDLE implicit-def $r2, implicit killed $r2, implicit killed $r3 {
      renamable $r2 = LSHL killed renamable $r2, killed renamable $r3
    }
    BUNDLE implicit-def $dj0, implicit killed $r2 {
      $dj0 = MOV_alu_mv_mv_mv_scl killed $r2
    }
    BUNDLE implicit-def $p2, implicit killed $p2, implicit killed $dj0 {
      renamable $p2 = LDA_dms_lda_idx killed renamable $p2, killed renamable $dj0 :: (load (p0), align 4)
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE implicit killed $p2 {
      J_alumv_or killed renamable $p2
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE implicit-def $r2, implicit killed $p3 {
      renamable $r2 = LDA_s8_idx_imm killed renamable $p3, 0 :: (dereferenceable load (s8))
    }
    BUNDLE implicit-def $r3 {
      renamable $r3 = MOVA 0
    }
    BUNDLE implicit-def $x2, implicit-def $wl2, implicit-def $wh2, implicit killed $r3 {
      renamable $x2 = VBCST_8 killed renamable $r3
    }
    DelayedSchedBarrier

  bb.2:
    successors: %bb.3(0x80000000)
    liveins: $p0, $p1, $r0, $r1, $x0

    BUNDLE implicit-def $r27, implicit $r1, implicit $r0 {
      renamable $r27 = LTU renamable $r1, renamable $r0
    }
    BUNDLE implicit-def $ls {
      $ls = MOVXM %bb.3
    }
    BUNDLE implicit-def $le {
      $le = MOVXM <mcsymbol .L_LEnd3>
    }
    BUNDLE implicit-def $r0, implicit killed $r0, implicit killed $r1, implicit killed $r27 {
      renamable $r0 = SEL_NEZ killed renamable $r0, killed renamable $r1, killed renamable $r27
    }
    BUNDLE implicit-def $r1, implicit-def $r0, implicit-def dead $srcarry, implicit killed $r0 {
      renamable $r1 = MOVA -6
      renamable $r0 = ADD_add_r_ri killed renamable $r0, -1, implicit-def dead $srcarry
    }
    BUNDLE implicit-def $r0, implicit killed $r0, implicit killed $r1 {
      renamable $r0 = LSHL killed renamable $r0, killed renamable $r1
    }
    BUNDLE implicit-def $r0, implicit-def dead $srcarry, implicit killed $r0 {
      renamable $r0 = nuw nsw ADD_add_r_ri killed renamable $r0, 1, implicit-def dead $srcarry
    }
    BUNDLE implicit-def $lc, implicit killed $r0 {
      $lc = ADD_NC_mv_add_ri killed $r0, 0
    }

  bb.3:
    successors: %bb.3(0x7c000000), %bb.17(0x04000000)
    liveins: $p0, $p1, $x0

    BUNDLE implicit-def $x2, implicit-def $wl2, implicit-def $wh2, implicit-def $p0, implicit killed $p0 {
      renamable $x2, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 64 :: (load (<64 x s8>))
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE implicit-def $x4, implicit-def $wl4, implicit-def $wh4, implicit-def dead $l8, implicit $x0, implicit killed $x2, implicit $vaddsign0 {
      renamable $x4, dead renamable $l8 = VMIN_GE_8_vaddSign0 renamable $x0, killed renamable $x2, implicit $vaddsign0
    }
    BUNDLE {
      NOP
    }
    BUNDLE implicit-def $p1, implicit killed $x4, implicit killed $p1 {
      renamable $p1 = VST_dmx_sts_x_pstm_nrm_imm killed renamable $x4, killed renamable $p1, 64 :: (store (<64 x s8>))
    }
    PseudoLoopEnd <mcsymbol .L_LEnd3>, %bb.3, implicit $ls, implicit $le

  bb.17:
    successors: %bb.14(0x80000000)

    BUNDLE {
      J_lng %bb.14
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    DelayedSchedBarrier

  bb.4:
    successors: %bb.5(0x80000000)
    liveins: $p0, $p1, $r0, $r1, $r2, $x0, $x2

    BUNDLE implicit-def $r27, implicit $r1, implicit $r0 {
      renamable $r27 = LTU renamable $r1, renamable $r0
    }
    BUNDLE implicit-def $ls {
      $ls = MOVXM %bb.5
    }
    BUNDLE implicit-def $le {
      $le = MOVXM <mcsymbol .L_LEnd1>
    }
    BUNDLE implicit-def $r0, implicit killed $r0, implicit killed $r1, implicit killed $r27 {
      renamable $r0 = SEL_NEZ killed renamable $r0, killed renamable $r1, killed renamable $r27
    }
    BUNDLE implicit-def $r1, implicit-def $r0, implicit-def dead $srcarry, implicit killed $r0 {
      renamable $r1 = MOVA -6
      renamable $r0 = ADD_add_r_ri killed renamable $r0, -1, implicit-def dead $srcarry
    }
    BUNDLE implicit-def $r0, implicit killed $r0, implicit killed $r1 {
      renamable $r0 = LSHL killed renamable $r0, killed renamable $r1
    }
    BUNDLE implicit-def $r0, implicit-def dead $srcarry, implicit-def $x4, implicit-def $wl4, implicit-def $wh4, implicit killed $r0, implicit killed $r2 {
      renamable $r0 = nuw nsw ADD_add_r_ri killed renamable $r0, 1, implicit-def dead $srcarry
      renamable $x4 = VBCST_8 killed renamable $r2
    }
    BUNDLE implicit-def $lc, implicit killed $r0 {
      $lc = ADD_NC_mv_add_ri killed $r0, 0
    }

  bb.5:
    successors: %bb.5(0x7c000000), %bb.15(0x04000000)
    liveins: $p0, $p1, $x0, $x2, $x4

    BUNDLE implicit-def $x6, implicit-def $wl6, implicit-def $wh6, implicit-def $p0, implicit killed $p0 {
      renamable $x6, renamable $p0 = VLDB_dmx_ldb_x_pstm_nrm_imm killed renamable $p0, 64 :: (load (<64 x s8>))
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE implicit-def $l0, implicit-def $r0, implicit-def $r1, implicit $x0, implicit killed $x6, implicit $vaddsign0 {
      renamable $l0 = VLT_8_vaddSign0 renamable $x0, killed renamable $x6, implicit $vaddsign0
    }
    BUNDLE {
      NOP
    }
    BUNDLE implicit-def $x8, implicit-def $wl8, implicit-def $wh8, implicit $x2, implicit $x4, implicit killed $l0 {
      renamable $x8 = VSEL_8 renamable $x2, renamable $x4, killed renamable $l0
    }
    BUNDLE {
      NOP
    }
    BUNDLE implicit-def $p1, implicit killed $x8, implicit killed $p1 {
      renamable $p1 = VST_dmx_sts_x_pstm_nrm_imm killed renamable $x8, killed renamable $p1, 64 :: (store (<64 x s8>))
    }
    PseudoLoopEnd <mcsymbol .L_LEnd1>, %bb.5, implicit $ls, implicit $le

  bb.15:
    successors: %bb.14(0x80000000)

    BUNDLE {
      J_lng %bb.14
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    DelayedSchedBarrier

  bb.14:
    BUNDLE implicit $lr {
      RET implicit $lr
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    DelayedSchedBarrier

...
