# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple=aie2p %s --run-pass=aie-machine-alignment -o - | FileCheck %s

---
name:            fallThroughBlock
alignment:       16
body:             |
  ; CHECK-LABEL: name: fallThroughBlock
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BUNDLE implicit-def $r0 {
  ; CHECK-NEXT:     renamable $r0 = MOVA 1
  ; CHECK-NEXT:     NOPB
  ; CHECK-NEXT:     NOPXM
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $r0, implicit killed $r0, implicit $r1 {
  ; CHECK-NEXT:     renamable $r0 = GE killed renamable $r0, renamable $r1
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit killed $r0 {
  ; CHECK-NEXT:     JNZ killed renamable $r0, %bb.2
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   DelayedSchedBarrier
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors:
  ; CHECK-NEXT:   liveins: $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BUNDLE implicit $lr {
  ; CHECK-NEXT:     RET implicit $lr
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $r0, implicit-def dead $srcarry, implicit killed $r1 {
  ; CHECK-NEXT:     renamable $r0 = ADD_add_r_ri killed renamable $r1, 5, implicit-def dead $srcarry
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   DelayedSchedBarrier implicit killed $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   liveins: $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BUNDLE implicit $lr {
  ; CHECK-NEXT:     RET implicit $lr
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $r0, implicit-def dead $srcarry, implicit killed $r1 {
  ; CHECK-NEXT:     renamable $r0 = ADD_add_r_ri killed renamable $r1, 10, implicit-def dead $srcarry
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   DelayedSchedBarrier implicit killed $r0
  bb.0:
    successors: %bb.1(0x40000000), %bb.2(0x40000000)
    liveins: $r1

    BUNDLE implicit-def $r0 {
      renamable $r0 = MOVA 1
    }
    BUNDLE implicit-def $r0, implicit killed $r0, implicit $r1 {
      renamable $r0 = GE killed renamable $r0, renamable $r1
    }
    BUNDLE implicit killed $r0 {
      JNZ killed renamable $r0, %bb.2
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    DelayedSchedBarrier

  bb.1:
    successors:
    liveins: $r1

    BUNDLE implicit $lr {
      RET implicit $lr
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE implicit-def $r0, implicit-def dead $srcarry, implicit killed $r1 {
      renamable $r0 = ADD_add_r_ri killed renamable $r1, 5, implicit-def dead $srcarry
    }
    DelayedSchedBarrier implicit killed $r0

  bb.2:
    liveins: $r1

    BUNDLE implicit $lr {
      RET implicit $lr
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE implicit-def $r0, implicit-def dead $srcarry, implicit killed $r1 {
      renamable $r0 = ADD_add_r_ri killed renamable $r1, 10, implicit-def dead $srcarry
    }
    DelayedSchedBarrier implicit killed $r0

...
