# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple=aie2p %s --run-pass=aie-machine-alignment -o - -verify-machineinstrs | FileCheck %s

# Alignment not possible in the MBB right before the jump target.
# bb.2 needs alignment, but bb.1 cannot be elongated enough to fulfill the
# alignment requirements. So bb.0 has to be elongated to satisfy the alignment
# requirements from bb.2.
---
name:            MultiStepAlignment
alignment:       16
fixedStack:      []
stack:
  - { id: 0, name: '', type: spill-slot, offset: 12, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '$lr', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 1, name: '', type: spill-slot, offset: 8, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '$r8', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 2, name: '', type: spill-slot, offset: 4, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '$p6', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 3, name: '', type: spill-slot, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '$p7', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
body:             |
  ; CHECK-LABEL: name: MultiStepAlignment
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x50000000), %bb.3(0x30000000)
  ; CHECK-NEXT:   liveins: $p0, $p1, $r0, $r8, $p6, $p7
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   frame-setup BUNDLE implicit-def $r1, implicit-def $sp, implicit $sp {
  ; CHECK-NEXT:     renamable $r1 = MOVA 0
  ; CHECK-NEXT:     NOPB
  ; CHECK-NEXT:     NOPS
  ; CHECK-NEXT:     frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:     NOPV
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit-def $r0, implicit-def $r8, implicit killed $r8, implicit $sp, implicit killed $r1, implicit killed $r0 {
  ; CHECK-NEXT:     ST_dms_sts_spill killed $r8, -56, implicit $sp :: (store (s32) into %stack.1)
  ; CHECK-NEXT:     renamable $r0 = GE killed renamable $r1, killed $r0
  ; CHECK-NEXT:     $r8 = MOV_alu_mv_mv_mv_scl internal $r0
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit killed $r0 {
  ; CHECK-NEXT:     JNZ killed renamable $r0, %bb.3
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit $lr, implicit $sp {
  ; CHECK-NEXT:     ST_dms_sts_spill $lr, -52, implicit $sp :: (store (s32) into %stack.0)
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit killed $p6, implicit $sp {
  ; CHECK-NEXT:     ST_dms_sts_spill killed $p6, -60, implicit $sp :: (store (s32) into %stack.2)
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE implicit killed $p7, implicit $sp {
  ; CHECK-NEXT:     ST_dms_sts_spill killed $p7, -64, implicit $sp :: (store (s32) into %stack.3)
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   DelayedSchedBarrier
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $p1, $r8
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BUNDLE implicit-def $p6, implicit-def $p7, implicit killed $p0, implicit killed $p1 {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     NOPB
  ; CHECK-NEXT:     $p6 = MOVS killed $p0
  ; CHECK-NEXT:     NOPX
  ; CHECK-NEXT:     $p7 = MOV_alu_mv_mv_mv_scl killed $p1
  ; CHECK-NEXT:     NOPV
  ; CHECK-NEXT:   }
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x04000000), %bb.2(0x7c000000)
  ; CHECK-NEXT:   liveins: $r8
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BUNDLE implicit $r8 {
  ; CHECK-NEXT:     JNZ renamable $r8, %bb.2
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   DelayedSchedBarrier
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   BUNDLE implicit $lr {
  ; CHECK-NEXT:     NOPA
  ; CHECK-NEXT:     RET implicit $lr
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   BUNDLE {
  ; CHECK-NEXT:     NOP
  ; CHECK-NEXT:   }
  ; CHECK-NEXT:   DelayedSchedBarrier
  bb.0:
    successors: %bb.1(0x50000000), %bb.3(0x30000000)
    liveins: $p0, $p1, $r0, $r8, $p6, $p7


    frame-setup BUNDLE implicit-def $r1, implicit-def $sp, implicit $sp {
      renamable $r1 = MOVA 0
      frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    }
    BUNDLE implicit-def $r0, implicit-def $r8, implicit killed $r8, implicit $sp, implicit killed $r1, implicit killed $r0 {
      ST_dms_sts_spill killed $r8, -56, implicit $sp :: (store (s32) into %stack.1)
      renamable $r0 = GE killed renamable $r1, killed $r0
      $r8 = MOV_alu_mv_mv_mv_scl internal $r0
    }
    BUNDLE implicit killed $r0 {
      JNZ killed renamable $r0, %bb.3
    }
    BUNDLE {
      NOP
    }
    BUNDLE implicit $lr, implicit $sp {
      ST_dms_sts_spill $lr, -52, implicit $sp :: (store (s32) into %stack.0)
    }
    BUNDLE implicit killed $p6, implicit $sp {
      ST_dms_sts_spill killed $p6, -60, implicit $sp :: (store (s32) into %stack.2)
    }
    BUNDLE implicit killed $p7, implicit $sp {
      ST_dms_sts_spill killed $p7, -64, implicit $sp :: (store (s32) into %stack.3)
    }
    BUNDLE {
      NOP
    }
    DelayedSchedBarrier

  bb.1:
    successors: %bb.2(0x80000000)
    liveins: $p0, $p1, $r8

    BUNDLE implicit-def $p6, implicit-def $p7, implicit killed $p0, implicit killed $p1 {
      $p6 = MOVS killed $p0
      $p7 = MOV_alu_mv_mv_mv_scl killed $p1
    }

  bb.2:
    successors: %bb.3(0x04000000), %bb.2(0x7c000000)
    liveins: $r8

    BUNDLE implicit $r8 {
      JNZ renamable $r8, %bb.2
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    DelayedSchedBarrier

  bb.3:
    BUNDLE implicit $lr {
      RET implicit $lr
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    BUNDLE {
      NOP
    }
    DelayedSchedBarrier

...
