; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -O2 -mtriple=aie2p -verify-machineinstrs --issue-limit=1 %s -o - | FileCheck %s

define void @test_single_diff_lane_buildvector() {
; CHECK-LABEL: test_single_diff_lane_buildvector:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mova r0, #111; nopx
; CHECK-NEXT:    mova r1, #777
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    vbcst.32 x0, r1 // Delay Slot 5
; CHECK-NEXT:    vinsert.32 x0, x0, #0, r0 // Delay Slot 4
; CHECK-NEXT:    mova p0, #0 // Delay Slot 3
; CHECK-NEXT:    vst wl0, [p0, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  store <8 x i32> <i32 111, i32 777, i32 777, i32 777, i32 777, i32 777, i32 777, i32 777>, ptr addrspace(6) null, align 32
  ret void
}

define void @test_splat_buildvector() {
; CHECK-LABEL: test_splat_buildvector:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; ret lr; nopm ; nops
; CHECK-NEXT:    mova r0, #888 // Delay Slot 5
; CHECK-NEXT:    vbcst.32 x0, r0 // Delay Slot 4
; CHECK-NEXT:    mova p0, #0 // Delay Slot 3
; CHECK-NEXT:    vst wl0, [p0, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  store <8 x i32> <i32 888, i32 888, i32 888, i32 888, i32 888, i32 888, i32 888, i32 888>, ptr addrspace(6) null, align 32
  ret void
}

define void @test_symmetric_buildvector() {
; CHECK-LABEL: test_symmetric_buildvector:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mova r0, #111; nopb ; nopxm ; nops
; CHECK-NEXT:    mova r1, #222
; CHECK-NEXT:    mova p0, #0
; CHECK-NEXT:    vbcst.32 x0, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    vbcst.32 x2, r1 // Delay Slot 5
; CHECK-NEXT:    vst wl0, [p0, #0] // Delay Slot 4
; CHECK-NEXT:    mova p0, #32 // Delay Slot 3
; CHECK-NEXT:    vst wl2, [p0, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  store <16 x i32> <i32 111, i32 111, i32 111, i32 111, i32 111, i32 111, i32 111, i32 111, i32 222, i32 222, i32 222, i32 222, i32 222, i32 222, i32 222, i32 222>, ptr addrspace(6) null, align 32
  ret void
}

define void @test_multi_diff_lane_buildvector() {
; CHECK-LABEL: test_multi_diff_lane_buildvector:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mova r0, #111; nopxm
; CHECK-NEXT:    mova r1, #222
; CHECK-NEXT:    mova r2, #777
; CHECK-NEXT:    vpush.hi.32 x0, x0, r0
; CHECK-NEXT:    vpush.hi.32 x0, x0, r1
; CHECK-NEXT:    vpush.hi.32 x0, x0, r2
; CHECK-NEXT:    vpush.hi.32 x0, x0, r2
; CHECK-NEXT:    vpush.hi.32 x0, x0, r2
; CHECK-NEXT:    vpush.hi.32 x0, x0, r2
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    vpush.hi.32 x0, x0, r2 // Delay Slot 5
; CHECK-NEXT:    vpush.hi.32 x0, x0, r0 // Delay Slot 4
; CHECK-NEXT:    mova p0, #0 // Delay Slot 3
; CHECK-NEXT:    vst wh0, [p0, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  store <8 x i32> <i32 111, i32 222, i32 777, i32 777, i32 777, i32 777, i32 777, i32 111>, ptr addrspace(6) null, align 32
  ret void
}

