; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
;
; Test for the inter-block scheduler handling of a Conv2D kernel with a nested
; loop: inner loop %for.body55.i82 and outer loop body %for.body.i68.
;
; RUN: llc -mtriple=aie2ps -verify-machineinstrs < %s | FileCheck %s

source_filename = "Work/aie/0_0/src/0_0.cc"
target datalayout = "e-m:e-p:20:32-i1:8:32-i8:8:32-i16:16:32-i32:32:32-f32:32:32-i64:32-f64:32-a:0:32-n32"
target triple = "aie2ps-none-unknown-elf"
$_Z6conv2dILh1EL5act_t0EaaaLb0ELb1EEvPT1_PT2_PT3_R13conv2d_paramsS6_S6_ = comdat any

; Function Attrs: mustprogress
define weak_odr dso_local void @_Z6conv2dILh1EL5act_t0EaaaLb0ELb1EEvPT1_PT2_PT3_R13conv2d_paramsS6_S6_(ptr noalias %ifm, ptr noalias %wts, ptr noalias %ofm, ptr nonnull align 64 dereferenceable(384) %conv2d_params, ptr noalias %psum_0_tdm, ptr noalias %psum_1_tdm) local_unnamed_addr #0 comdat {
; CHECK-LABEL: _Z6conv2dILh1EL5act_t0EaaaLb0ELb1EEvPT1_PT2_PT3_R13conv2d_paramsS6_S6_:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mova dj0, #92; nopxm
; CHECK-NEXT:    lda r4, [p3, dj0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    mova dj1, #18
; CHECK-NEXT:    lda.u8 r6, [p3, dj1]
; CHECK-NEXT:    nop
; CHECK-NEXT:    movxm r0, #16777216
; CHECK-NEXT:    movxm r2, #33554431
; CHECK-NEXT:    mova r0, #-24; add r26, r4, r0
; CHECK-NEXT:    lshl r20, r26, r0
; CHECK-NEXT:    ltu r2, r2, r26
; CHECK-NEXT:    ltu r16, r20, r6
; CHECK-NEXT:    eq r24, r20, r6
; CHECK-NEXT:    mova r0, #0; and r27, r2, r16; mov r22, #3
; CHECK-NEXT:    lda.u8 r2, [p3, #7]; sel.nez r2, r22, r0, r27; mov r16, #1
; CHECK-NEXT:    eq r18, r20, r16
; CHECK-NEXT:    paddxm [sp], #64; lshl r28, r24, r16
; CHECK-NEXT:    st p6, [sp, #-64]; ltu r27, r16, r6 // 4-byte Folded Spill
; CHECK-NEXT:    mova dj1, #96; st r26, [p3, dj0]; or r18, r28, r18
; CHECK-NEXT:    st.s8 r18, [p3, dj1]; add r2, r18, r2
; CHECK-NEXT:    sel.nez r18, r2, r0, r27
; CHECK-NEXT:    ne r26, r2, r16
; CHECK-NEXT:    jnz r26, #.LBB0_2
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mova dj0, #76; ltu r28, r16, r18 // Delay Slot 3
; CHECK-NEXT:    st r28, [p3, dj0]; mov r7, r8 // Delay Slot 2
; CHECK-NEXT:    mova r2, #5; st p7, [sp, #-60]; or r17, r10, r10; mov r19, r12 // 4-byte Folded Spill Delay Slot 1
; CHECK-NEXT:  // %bb.1: // %entry
; CHECK-NEXT:    jnz r24, #.LBB0_3
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    mova r26, #3; movx r28, #1 // Delay Slot 1
; CHECK-NEXT:  .LBB0_2: // %if.else.i
; CHECK-NEXT:    mova dj0, #28; nopx
; CHECK-NEXT:    lda.s8 r24, [p3, dj0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    add r26, r24, #-4
; CHECK-NEXT:    extend.u8 r30, r24
; CHECK-NEXT:    mova r28, #254; extend.u8 r26, r26
; CHECK-NEXT:    mova r28, #8; ltu r26, r26, r28
; CHECK-NEXT:    ne r28, r30, r28
; CHECK-NEXT:    ne r30, r30, r2
; CHECK-NEXT:    mova r28, #4; and r26, r28, r26
; CHECK-NEXT:    lshl r24, r24, r28
; CHECK-NEXT:    and r27, r30, r26
; CHECK-NEXT:    and r26, r18, r2
; CHECK-NEXT:    sel.nez r24, r24, r0, r27
; CHECK-NEXT:    nez r28, r26
; CHECK-NEXT:    or r26, r24, r18
; CHECK-NEXT:  .LBB0_3: // %if.end.i
; CHECK-NEXT:    mova m0, #80; nopb ; nops ; nopx ; mov p2, p3; nopv
; CHECK-NEXT:    padda [p2], m0
; CHECK-NEXT:    st r28, [p2], #24
; CHECK-NEXT:    st.s8 r26, [p2, #0]; ne r6, r20, r6
; CHECK-NEXT:    jnz r6, #.LBB0_5
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
; CHECK-NEXT:  // %bb.4: // %if.then87.i
; CHECK-NEXT:    movxm r6, #16777215
; CHECK-NEXT:    mova dj0, #92; and r4, r4, r6
; CHECK-NEXT:    st r4, [p3, dj0]
; CHECK-NEXT:    nop
; CHECK-NEXT:  .LBB0_5: // %_Z24setup_conv2d_iter_paramsR13conv2d_params.exit
; CHECK-NEXT:    mova dj0, #84; nopb ; nopxm
; CHECK-NEXT:    lda r20, [p3, dj0]; extend.u8 r4, r26
; CHECK-NEXT:    mova dj0, #120; eq r6, r4, r22
; CHECK-NEXT:    lda r24, [p3, dj0]; jnz r6, #.LBB0_7
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
; CHECK-NEXT:  // %bb.6: // %_Z24setup_conv2d_iter_paramsR13conv2d_params.exit
; CHECK-NEXT:    ne r4, r4, r16
; CHECK-NEXT:    jnz r4, #.LBB0_11
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
; CHECK-NEXT:  .LBB0_7: // %sw.bb14
; CHECK-NEXT:    mova m0, #112; nopxm
; CHECK-NEXT:    mova m0, #-104; paddb [p3], m0
; CHECK-NEXT:    lda r4, [p3], m0
; CHECK-NEXT:    lda.u8 r28, [p3], #1; mov m0, #131
; CHECK-NEXT:    lda.s8 r22, [p3], m0
; CHECK-NEXT:    lda m0, [p3], #-8
; CHECK-NEXT:    lda dn0, [p3], #-8
; CHECK-NEXT:    lda dj0, [p3], #12
; CHECK-NEXT:    lda dn4, [p3], #-8; mov m1, #188
; CHECK-NEXT:    lda dj4, [p3], m1
; CHECK-NEXT:    mova m1, #-284
; CHECK-NEXT:    lda r6, [p3], m1
; CHECK-NEXT:    mova m1, #76
; CHECK-NEXT:    lda r30, [p3], m1
; CHECK-NEXT:    mova m1, #52
; CHECK-NEXT:    lda r26, [p3], m1
; CHECK-NEXT:    lda m1, [p3], #-8
; CHECK-NEXT:    lda dn1, [p3], #-8; movx crupsmode, #0
; CHECK-NEXT:    lda dj1, [p3], #12; movx crsrsmode, #0; mov r1, #2
; CHECK-NEXT:    lda dn5, [p3], #-8; lshl r5, r20, r1; mov m2, #32
; CHECK-NEXT:    lda dj5, [p3], m2; lshl r24, r24, r1
; CHECK-NEXT:    lda m2, [p3], #-8; add r24, r5, r24
; CHECK-NEXT:    lda dn2, [p3], #-8; geu r5, r16, r18
; CHECK-NEXT:    lda dj2, [p3], #12; movx r16, #0; mov dj3, #-158
; CHECK-NEXT:    lda dn6, [p3], #-8; sub r16, r16, r20; mov dc3, #0
; CHECK-NEXT:    lda.s8 r3, [p3, dj3]; lshl r16, r16, r1; mov p6, p5
; CHECK-NEXT:    mova r18, #9; movs dc6, dc3; lshl r20, r5, r28; mov m3, r24
; CHECK-NEXT:    mova r24, #256; movs dc2, dc3; lshl r18, r30, r18; mov dc5, dc3
; CHECK-NEXT:    mova r16, #7; paddb [p1], m3; or r8, r18, r24; vbcst.32 x0, r20; movs m3, r16
; CHECK-NEXT:    mova r10, #264; movs dc1, dc3; lshl r28, r26, r16; mov s0, r22
; CHECK-NEXT:    mova r16, #16; movs p2, p1; add r18, r26, #-1; mov r30, #63
; CHECK-NEXT:    padda [p2], m3; movs dc0, dc3; or r24, r0, r0; mov m3, r28
; CHECK-NEXT:    lda dj6, [p3, #0]; movs p3, p4; or r12, r8, r5; mov s1, r3
; CHECK-NEXT:  .LBB0_8: // %for.body.i68
; CHECK-NEXT:    // =>This Loop Header: Depth=1
; CHECK-NEXT:    // Child Loop BB0_9 Depth 2
; CHECK-NEXT:    nopa ; vldb x1, [p1, #64]; nopx ; mov r0, dc6; nops
; CHECK-NEXT:    vlda.ups.2x cml1, s0, upssign1, [p4, #0]; vldb.popx x4, [p0, lf0, r24]; lshl r0, r0, r2; mov dc4, dc3
; CHECK-NEXT:    vlda.pop.3d x6, [p0, lf0, r24, d0]; or r20, r0, r16; mov dj3, r0
; CHECK-NEXT:    vldb.128 wl2, [p2, dj3]; mov dj3, r20
; CHECK-NEXT:    vldb.128 wl8, [p2, dj3]
; CHECK-NEXT:    vlda.ups.2x cml0, s0, upssign1, [p6, #0]; vldb x10, [p1, #0]
; CHECK-NEXT:    vlda.ups.2x cmh1, s0, upssign1, [p4, #64]
; CHECK-NEXT:    vlda.ups.2x cmh0, s0, upssign1, [p6, #64]; vldb.popx x10, [p0, lf0, r24]
; CHECK-NEXT:    vldb.pop.3d x8, [p0, lf0, r24, d0]
; CHECK-NEXT:    vldb.popx x10, [p0, lf0, r24]; mov p7, p1
; CHECK-NEXT:    vlda x6, [p7, #128]; vldb.pop.3d x8, [p0, lf0, r24, d0]; vshuffle x2, x4, x6, r6; vmul dm2, x0, x2, r10
; CHECK-NEXT:    vlda x4, [p7, #192]; vldb.popx x10, [p0, lf0, r24]; add.nc lc, r18, #-6; padds [p7], #128; vmul dm3, x0, x8, r10
; CHECK-NEXT:    vlda x6, [p7, #128]; vldb.pop.3d x8, [p0, lf0, r24, d0]; movxm ls, #.LBB0_9; vaddmac dm1, dm1, dm2, x2, x10, r12
; CHECK-NEXT:    vlda x4, [p7, #192]; vldb.popx x10, [p0, lf0, r24]; padds [p7], #128; movxm le, #.L_LEnd0; vaddmac dm0, dm0, dm3, x2, x1, r12
; CHECK-NEXT:    vlda x6, [p7, #128]; vldb.pop.3d x8, [p0, lf0, r24, d0]; nops ; nopxm ; nopv
; CHECK-NEXT:    vlda x4, [p7, #192]; vldb.popx x10, [p0, lf0, r24]; padds [p7], #128; nopxm ; nopv
; CHECK-NEXT:    vlda x6, [p7, #128]; vldb.pop.3d x8, [p0, lf0, r24, d0]; nops ; nopx ; vshuffle x2, x10, x8, r6; nopv
; CHECK-NEXT:    vlda x4, [p7, #192]; vldb.popx x10, [p0, lf0, r24]; padds [p7], #128; nopxm ; nopv
; CHECK-NEXT:    vlda x6, [p7, #128]; vldb.pop.3d x8, [p0, lf0, r24, d0]; nops ; nopx ; vshuffle x2, x10, x8, r6; vmac dm1, dm1, x2, x6, r8
; CHECK-NEXT:  .LBB0_9: // %for.body55.i82
; CHECK-NEXT:    // Parent Loop BB0_8 Depth=1
; CHECK-NEXT:    // => This Inner Loop Header: Depth=2
; CHECK-NEXT:    vlda x4, [p7, #192]; vldb.popx x10, [p0, lf0, r24]; padds [p7], #128; nopxm ; vmac dm0, dm0, x2, x4, r8
; CHECK-NEXT:  .L_LEnd0:
; CHECK-NEXT:    vlda x6, [p7, #128]; vldb.pop.3d x8, [p0, lf0, r24, d0]; nops ; nopx ; vshuffle x2, x10, x8, r6; vmac dm1, dm1, x2, x6, r8
; CHECK-NEXT:  // %bb.10: // %for.cond.cleanup54.i89
; CHECK-NEXT:    // in Loop: Header=BB0_8 Depth=1
; CHECK-NEXT:    vlda x4, [p7, #192]; paddb [p1], m3; padds [p7], #128; add r4, r4, #-1; nopm ; vmac dm0, dm0, x2, x4, r8
; CHECK-NEXT:    vlda x6, [p7, #128]; paddb [p4], #128; padds [p6], #128; nopx ; vshuffle x2, x10, x8, r6; vmac dm1, dm1, x2, x6, r8
; CHECK-NEXT:    vlda x4, [p7, #192]; paddb.3d [p0], d1; nopx ; padds [p7], #128; vmac dm0, dm0, x2, x4, r8
; CHECK-NEXT:    paddb.3d [p1], d2; vshuffle x2, x10, x8, r6; vmac dm1, dm1, x2, x6, r8
; CHECK-NEXT:    vmac dm0, dm0, x2, x4, r8
; CHECK-NEXT:    vshuffle x2, x10, x8, r6; vmac dm1, dm1, x2, x6, r8
; CHECK-NEXT:    vmac dm0, dm0, x2, x4, r8
; CHECK-NEXT:    vshuffle x2, x10, x8, r6; vmac dm1, dm1, x2, x6, r8
; CHECK-NEXT:    vmac dm0, dm0, x2, x4, r8
; CHECK-NEXT:    vmac dm1, dm1, x2, x6, r8
; CHECK-NEXT:    vmac dm0, dm0, x2, x4, r8
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst.srs.2x cml1, s1, srssign1, [p3], #64
; CHECK-NEXT:    vst.srs.2x cmh1, s1, srssign1, [p3], #64; jnz r4, #.LBB0_8
; CHECK-NEXT:    vst.srs.2x cml0, s1, srssign1, [p5], #64 // Delay Slot 5
; CHECK-NEXT:    vst.srs.2x cmh0, s1, srssign1, [p5], #64 // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
; CHECK-NEXT:  .LBB0_11: // %sw.epilog
; CHECK-NEXT:    lda p7, [sp, #-60] // 4-byte Folded Reload
; CHECK-NEXT:    lda p6, [sp, #-64] // 4-byte Folded Reload
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    mov r12, r19 // Delay Slot 2
; CHECK-NEXT:    paddxm [sp], #-64; or r10, r17, r17; mov r8, r7 // Delay Slot 1
entry:
  %0 = getelementptr inbounds i8, ptr %conv2d_params, i20 92
  %1 = load i32, ptr %0, align 4, !tbaa !4
  %add.i = add i32 %1, 16777216
  store i32 %add.i, ptr %0, align 4, !tbaa !4
  %shr.i = lshr i32 %add.i, 24
  %num_ifm_depth_iter.i = getelementptr inbounds i8, ptr %conv2d_params, i20 18
  %2 = load i8, ptr %num_ifm_depth_iter.i, align 2, !tbaa !7
  %conv2.i = zext i8 %2 to i32
  %cmp.i = icmp ugt i8 %2, 1
  %cmp5.i = icmp eq i32 %shr.i, 1
  %conv6.i = zext i1 %cmp5.i to i8
  %cmp10.i = icmp eq i32 %shr.i, %conv2.i
  %mul.i = select i1 %cmp10.i, i8 2, i8 0
  %add12.i = or disjoint i8 %mul.i, %conv6.i
  %cmp14.i = icmp ugt i32 %add.i, 33554431
  %cmp18.i = icmp samesign ult i32 %shr.i, %conv2.i
  %3 = select i1 %cmp14.i, i1 %cmp18.i, i1 false
  %conv19.i = select i1 %3, i8 3, i8 0
  %add21.i = add nsw i8 %add12.i, %conv19.i
  %conv23.i = select i1 %cmp.i, i8 %add21.i, i8 0
  %io_mode.i = getelementptr inbounds i8, ptr %conv2d_params, i20 96
  store i8 %conv23.i, ptr %io_mode.i, align 32, !tbaa !12
  %narrow.i = icmp samesign ugt i8 %conv23.i, 1
  %not..i = zext i1 %narrow.i to i32
  %psum_in.i = getelementptr inbounds i8, ptr %conv2d_params, i20 76
  store i32 %not..i, ptr %psum_in.i, align 4, !tbaa !13
  %out_mode.i = getelementptr inbounds i8, ptr %conv2d_params, i20 7
  %4 = load i8, ptr %out_mode.i, align 1, !tbaa !14
  %cmp53.i = icmp eq i8 %4, 1
  %or.cond.i = select i1 %cmp53.i, i1 %cmp10.i, i1 false
  br i1 %or.cond.i, label %if.end.i, label %if.else.i

if.else.i:                                        ; preds = %entry
  %conv_type.i = getelementptr inbounds i8, ptr %conv2d_params, i20 28
  %5 = load i8, ptr %conv_type.i, align 4, !tbaa !15
  %6 = add i8 %5, -4
  %7 = icmp ult i8 %6, -2
  %cmp39.i = icmp ne i8 %5, 8
  %mulbool119.i = and i1 %cmp39.i, %7
  %cmp49.i = icmp ne i8 %5, 5
  %mulbool.i = and i1 %cmp49.i, %mulbool119.i
  %8 = and i8 %conv23.i, 5
  %narrow121.i = icmp ne i8 %8, 0
  %not.120.i = zext i1 %narrow121.i to i32
  %shl.i = shl i8 %5, 4
  %mul75.i = select i1 %mulbool.i, i8 %shl.i, i8 0
  %add79.i = or disjoint i8 %mul75.i, %conv23.i
  br label %if.end.i

if.end.i:                                         ; preds = %if.else.i, %entry
  %not.120.sink.i = phi i32 [ %not.120.i, %if.else.i ], [ 1, %entry ]
  %add79.sink.i = phi i8 [ %add79.i, %if.else.i ], [ 3, %entry ]
  %9 = icmp eq i32 %shr.i, %conv2.i
  %10 = getelementptr inbounds i8, ptr %conv2d_params, i20 80
  store i32 %not.120.sink.i, ptr %10, align 16, !tbaa !16
  %11 = getelementptr inbounds i8, ptr %conv2d_params, i20 104
  store i8 %add79.sink.i, ptr %11, align 8, !tbaa !17
  br i1 %9, label %if.then87.i, label %_Z24setup_conv2d_iter_paramsR13conv2d_params.exit

if.then87.i:                                      ; preds = %if.end.i
  %and.i = and i32 %1, 16777215
  %sunkaddr = getelementptr inbounds i8, ptr %conv2d_params, i20 92
  store i32 %and.i, ptr %sunkaddr, align 4, !tbaa !4
  br label %_Z24setup_conv2d_iter_paramsR13conv2d_params.exit

_Z24setup_conv2d_iter_paramsR13conv2d_params.exit: ; preds = %if.then87.i, %if.end.i
  %hdr_len = getelementptr inbounds i8, ptr %conv2d_params, i20 84
  %12 = load i32, ptr %hdr_len, align 4, !tbaa !18
  %idx.ext = trunc i32 %12 to i20
  %add.ptr = getelementptr inbounds i32, ptr %wts, i20 %idx.ext
  %wts_offset = getelementptr inbounds i8, ptr %conv2d_params, i20 120
  %13 = load i32, ptr %wts_offset, align 8, !tbaa !19
  %idx.ext2 = trunc i32 %13 to i20
  %add.ptr3 = getelementptr inbounds i32, ptr %add.ptr, i20 %idx.ext2
  %14 = zext i8 %add79.sink.i to i32
  switch i32 %14, label %sw.epilog [
    i32 1, label %sw.bb14
    i32 3, label %sw.bb14
  ]

sw.bb14:                                          ; preds = %_Z24setup_conv2d_iter_paramsR13conv2d_params.exit, %_Z24setup_conv2d_iter_paramsR13conv2d_params.exit
  %151 = icmp ugt i8 %conv23.i, 1
  tail call void @llvm.experimental.noalias.scope.decl(metadata !69)
  tail call void @llvm.experimental.noalias.scope.decl(metadata !72)
  tail call void @llvm.experimental.noalias.scope.decl(metadata !74)
  tail call void @llvm.experimental.noalias.scope.decl(metadata !76)
  %idx.neg.i36 = sub i20 0, %idx.ext
  %add.ptr.i37 = getelementptr inbounds i32, ptr %add.ptr3, i20 %idx.neg.i36
  %152 = addrspacecast ptr %psum_0_tdm to ptr addrspace(6)
  %153 = addrspacecast ptr %psum_1_tdm to ptr addrspace(7)
  %outer_g.i38 = getelementptr inbounds i8, ptr %conv2d_params, i20 112
  %154 = load i32, ptr %outer_g.i38, align 16, !tbaa !35, !noalias !78
  %not.narrow.i = xor i1 %151, true
  %sub.i40 = zext i1 %not.narrow.i to i32
  %shift_bias_init.i41 = getelementptr inbounds i8, ptr %conv2d_params, i20 8
  %155 = load i8, ptr %shift_bias_init.i41, align 8, !tbaa !36, !noalias !78
  %conv200.i = zext nneg i8 %155 to i32
  %shl.i42 = shl i32 %sub.i40, %conv200.i
  %splat.splatinsert.i.i43 = insertelement <16 x i32> poison, i32 %shl.i42, i64 0
  %splat.splat.i.i44 = shufflevector <16 x i32> %splat.splatinsert.i.i43, <16 x i32> poison, <16 x i32> zeroinitializer
  %156 = bitcast <16 x i32> %splat.splat.i.i44 to <64 x i8>
  %shift_psum_in.i45 = getelementptr inbounds i8, ptr %conv2d_params, i20 9
  %157 = load i8, ptr %shift_psum_in.i45, align 1, !tbaa !37, !noalias !78
  %conv10.i46 = sext i8 %157 to i32
  %iterator_inner_incr2.i47 = getelementptr inbounds i8, ptr %conv2d_params, i20 140
  %158 = load i32, ptr %iterator_inner_incr2.i47, align 4, !tbaa !38, !noalias !78
  %iterator_inner_wrap0.i48 = getelementptr inbounds i8, ptr %conv2d_params, i20 132
  %159 = load i32, ptr %iterator_inner_wrap0.i48, align 4, !tbaa !39, !noalias !78
  %iterator_inner_incr0.i49 = getelementptr inbounds i8, ptr %conv2d_params, i20 124
  %160 = load i32, ptr %iterator_inner_incr0.i49, align 4, !tbaa !40, !noalias !78
  %iterator_inner_wrap1.i50 = getelementptr inbounds i8, ptr %conv2d_params, i20 136
  %161 = load i32, ptr %iterator_inner_wrap1.i50, align 8, !tbaa !41, !noalias !78
  %iterator_inner_incr1.i51 = getelementptr inbounds i8, ptr %conv2d_params, i20 128
  %162 = load i32, ptr %iterator_inner_incr1.i51, align 64, !tbaa !42, !noalias !78
  %163 = trunc i32 %158 to i20
  %164 = trunc i32 %159 to i20
  %165 = trunc i32 %160 to i20
  %166 = trunc i32 %161 to i20
  %167 = trunc i32 %162 to i20
  %shfl_1.i52 = getelementptr inbounds i8, ptr %conv2d_params, i20 316
  %168 = load i32, ptr %shfl_1.i52, align 4, !tbaa !43, !noalias !78
  %ifm_sign.i53 = getelementptr inbounds i8, ptr %conv2d_params, i20 32
  %169 = load i32, ptr %ifm_sign.i53, align 32, !tbaa !44, !noalias !78
  %shl20.i.i.i54 = shl i32 %169, 9
  %or22.i.i.i55 = or disjoint i32 %shl20.i.i.i54, 256
  %or25.i.i.i56 = or disjoint i32 %or22.i.i.i55, %sub.i40
  %inner_g.i57 = getelementptr inbounds i8, ptr %conv2d_params, i20 108
  %170 = load i32, ptr %inner_g.i57, align 4, !tbaa !45, !noalias !78
  %iterator_outer_incr2.i58 = getelementptr inbounds i8, ptr %conv2d_params, i20 160
  %171 = load i32, ptr %iterator_outer_incr2.i58, align 32, !tbaa !46, !noalias !78
  %iterator_outer_wrap0.i59 = getelementptr inbounds i8, ptr %conv2d_params, i20 152
  %172 = load i32, ptr %iterator_outer_wrap0.i59, align 8, !tbaa !47, !noalias !78
  %iterator_outer_incr0.i60 = getelementptr inbounds i8, ptr %conv2d_params, i20 144
  %173 = load i32, ptr %iterator_outer_incr0.i60, align 16, !tbaa !48, !noalias !78
  %iterator_outer_wrap1.i61 = getelementptr inbounds i8, ptr %conv2d_params, i20 156
  %174 = load i32, ptr %iterator_outer_wrap1.i61, align 4, !tbaa !49, !noalias !78
  %iterator_outer_incr1.i62 = getelementptr inbounds i8, ptr %conv2d_params, i20 148
  %175 = load i32, ptr %iterator_outer_incr1.i62, align 4, !tbaa !50, !noalias !78
  %176 = trunc i32 %171 to i20
  %177 = trunc i32 %173 to i20
  %178 = trunc i32 %175 to i20
  %179 = trunc i32 %172 to i20
  %180 = trunc i32 %174 to i20
  %iterator_weights_incr2.i63 = getelementptr inbounds i8, ptr %conv2d_params, i20 180
  %181 = load i32, ptr %iterator_weights_incr2.i63, align 4, !tbaa !51, !noalias !78
  %iterator_weights_wrap0.i64 = getelementptr inbounds i8, ptr %conv2d_params, i20 172
  %182 = load i32, ptr %iterator_weights_wrap0.i64, align 4, !tbaa !52, !noalias !78
  %iterator_weights_incr0.i65 = getelementptr inbounds i8, ptr %conv2d_params, i20 164
  %183 = load i32, ptr %iterator_weights_incr0.i65, align 4, !tbaa !53, !noalias !78
  %iterator_weights_wrap1.i66 = getelementptr inbounds i8, ptr %conv2d_params, i20 176
  %184 = load i32, ptr %iterator_weights_wrap1.i66, align 16, !tbaa !54, !noalias !78
  %iterator_weights_incr1.i67 = getelementptr inbounds i8, ptr %conv2d_params, i20 168
  %185 = load i32, ptr %iterator_weights_incr1.i67, align 8, !tbaa !55, !noalias !78
  %186 = trunc i32 %181 to i20
  %187 = trunc i32 %183 to i20
  %188 = trunc i32 %185 to i20
  %189 = trunc i32 %182 to i20
  %190 = trunc i32 %184 to i20
  %shift_psum_out.i = getelementptr inbounds i8, ptr %conv2d_params, i20 10
  %191 = load i8, ptr %shift_psum_out.i, align 2, !tbaa !79, !noalias !78
  %conv90.i = sext i8 %191 to i32
  %192 = trunc i32 %170 to i20
  %193 = shl i20 %192, 7
  %194 = add i32 %170, -1
  br label %for.body.i68

for.body.i68:                                     ; preds = %for.cond.cleanup54.i89, %sw.bb14
  %lsr.iv132 = phi i32 [ %lsr.iv.next133, %for.cond.cleanup54.i89 ], [ %154, %sw.bb14 ]
  %p_w.0.in300.i = phi ptr [ %add.ptr3, %sw.bb14 ], [ %255, %for.cond.cleanup54.i89 ]
  %p_psum_out_1.0298.i = phi ptr addrspace(7) [ %153, %sw.bb14 ], [ %add.ptr.ascast.i240.i, %for.cond.cleanup54.i89 ]
  %p_psum_in_0.0297.i = phi ptr addrspace(6) [ %152, %sw.bb14 ], [ %add.ptr.ascast.i207.i, %for.cond.cleanup54.i89 ]
  %p_psum_out_0.0296.i = phi ptr addrspace(6) [ %152, %sw.bb14 ], [ %add.ptr.ascast.i234.i, %for.cond.cleanup54.i89 ]
  %p_psum_in_1.0295.i = phi ptr addrspace(7) [ %153, %sw.bb14 ], [ %add.ptr.ascast.i220.i, %for.cond.cleanup54.i89 ]
  %p_in_fifo.sroa.0.0294.i = phi <32 x i32> [ poison, %sw.bb14 ], [ %p_in_fifo.sroa.0.1.i85, %for.cond.cleanup54.i89 ]
  %p_in_fifo.sroa.10.0293.i = phi i32 [ 0, %sw.bb14 ], [ %p_in_fifo.sroa.10.1.i86, %for.cond.cleanup54.i89 ]
  %p_in_fifo.sroa.19258.0292.i = phi <16 x i32> [ poison, %sw.bb14 ], [ %p_in_fifo.sroa.19258.1.i, %for.cond.cleanup54.i89 ]
  %iterator_weights_cnt1.0291.i = phi i32 [ 0, %sw.bb14 ], [ %254, %for.cond.cleanup54.i89 ]
  %iterator_weights_cnt0.0290.i = phi i32 [ 0, %sw.bb14 ], [ %252, %for.cond.cleanup54.i89 ]
  %iterator_outer_cnt1.0289.i = phi i32 [ 0, %sw.bb14 ], [ %246, %for.cond.cleanup54.i89 ]
  %iterator_outer_cnt0.0288.i = phi i32 [ 0, %sw.bb14 ], [ %244, %for.cond.cleanup54.i89 ]
  %iterator_inner_cnt0.0287.i = phi i32 [ 0, %sw.bb14 ], [ %278, %for.cond.cleanup54.i89 ]
  %p_in.0.in286.i = phi ptr [ %ifm, %sw.bb14 ], [ %247, %for.cond.cleanup54.i89 ]
  %p_w.0.i69 = addrspacecast ptr %p_w.0.in300.i to ptr addrspace(6)
  %p_in.0.i70 = addrspacecast ptr %p_in.0.in286.i to ptr addrspace(5)
  %mul.i71 = shl nsw i32 %iterator_weights_cnt1.0291.i, 5
  %idx.ext.i.i72 = trunc i32 %mul.i71 to i20
  %add.ptr.i.i73 = getelementptr inbounds i8, ptr %add.ptr.i37, i20 %idx.ext.i.i72
  %add.ptr.ascast.i.i74 = addrspacecast ptr %add.ptr.i.i73 to ptr addrspace(6)
  %195 = load <4 x i32>, ptr addrspace(6) %add.ptr.ascast.i.i74, align 16, !tbaa !4, !alias.scope !72, !noalias !80
  %shuffle.i.i.i75 = shufflevector <4 x i32> %195, <4 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %shuffle1.i.i.i76 = shufflevector <8 x i32> %shuffle.i.i.i75, <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %196 = bitcast <16 x i32> %shuffle1.i.i.i76 to <64 x i8>
  %197 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mul.conf(<64 x i8> %156, <64 x i8> %196, i32 264)
  %198 = load <32 x i16>, ptr addrspace(6) %p_psum_in_0.0297.i, align 64, !tbaa !4, !alias.scope !74, !noalias !81
  %199 = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16> %198, i32 range(i32 -128, 128) %conv10.i46, i32 1)
  %200 = bitcast <32 x i32> %199 to <16 x i64>
  %201 = addrspacecast ptr addrspace(6) %p_psum_in_0.0297.i to ptr
  %add.ptr.i203.i = getelementptr inbounds i8, ptr %201, i20 64
  %add.ptr.ascast.i204.i = addrspacecast ptr %add.ptr.i203.i to ptr addrspace(6)
  %202 = load <32 x i16>, ptr addrspace(6) %add.ptr.ascast.i204.i, align 64, !tbaa !4, !alias.scope !74, !noalias !81
  %203 = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16> %202, i32 range(i32 -128, 128) %conv10.i46, i32 1)
  %204 = bitcast <32 x i32> %203 to <16 x i64>
  %shuffle2.i.i.i77 = shufflevector <16 x i64> %200, <16 x i64> %204, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %205 = bitcast <32 x i64> %shuffle2.i.i.i77 to <64 x i32>
  %add.i79 = or disjoint i32 %mul.i71, 16
  %idx.ext.i208.i = trunc i32 %add.i79 to i20
  %add.ptr.i209.i80 = getelementptr inbounds i8, ptr %add.ptr.i37, i20 %idx.ext.i208.i
  %add.ptr.ascast.i210.i81 = addrspacecast ptr %add.ptr.i209.i80 to ptr addrspace(6)
  %206 = load <4 x i32>, ptr addrspace(6) %add.ptr.ascast.i210.i81, align 16, !tbaa !4, !alias.scope !72, !noalias !80
  %shuffle.i.i211.i = shufflevector <4 x i32> %206, <4 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %shuffle1.i.i212.i = shufflevector <8 x i32> %shuffle.i.i211.i, <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %207 = bitcast <16 x i32> %shuffle1.i.i212.i to <64 x i8>
  %208 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mul.conf(<64 x i8> %156, <64 x i8> %207, i32 264)
  %209 = load <32 x i16>, ptr addrspace(7) %p_psum_in_1.0295.i, align 64, !tbaa !4, !alias.scope !76, !noalias !82
  %210 = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16> %209, i32 range(i32 -128, 128) %conv10.i46, i32 1)
  %211 = bitcast <32 x i32> %210 to <16 x i64>
  %212 = addrspacecast ptr addrspace(7) %p_psum_in_1.0295.i to ptr
  %add.ptr.i215.i = getelementptr inbounds i8, ptr %212, i20 64
  %add.ptr.ascast.i216.i = addrspacecast ptr %add.ptr.i215.i to ptr addrspace(7)
  %213 = load <32 x i16>, ptr addrspace(7) %add.ptr.ascast.i216.i, align 64, !tbaa !4, !alias.scope !76, !noalias !82
  %214 = tail call noundef <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16> %213, i32 range(i32 -128, 128) %conv10.i46, i32 1)
  %215 = bitcast <32 x i32> %214 to <16 x i64>
  %shuffle2.i.i218.i = shufflevector <16 x i64> %211, <16 x i64> %215, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %216 = bitcast <32 x i64> %shuffle2.i.i218.i to <64 x i32>
  %217 = tail call { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.popx.p5.p5(ptr addrspace(5) %p_in.0.i70, <32 x i32> %p_in_fifo.sroa.0.0294.i, i32 %p_in_fifo.sroa.10.0293.i, <16 x i32> %p_in_fifo.sroa.19258.0292.i, i32 63), !alias.scope !69, !noalias !83
  %218 = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, <16 x i32> } %217, 0
  %219 = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, <16 x i32> } %217, 1
  %220 = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, <16 x i32> } %217, 2
  %221 = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, <16 x i32> } %217, 3
  %222 = trunc i32 %iterator_inner_cnt0.0287.i to i20
  %223 = tail call { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.ld.pop.3d.unaligned.p5.p5(ptr addrspace(5) %219, <32 x i32> %220, i32 %221, i20 %163, i20 %164, i20 %222, i20 %165, i20 %166, i20 0, i20 %167), !alias.scope !69, !noalias !83
  %224 = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } %223, 0
  %225 = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } %223, 4
  %226 = zext i20 %225 to i32
  %227 = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } %223, 5
  %228 = zext i20 %227 to i32
  %229 = bitcast <64 x i8> %218 to <16 x i32>
  %230 = bitcast <64 x i8> %224 to <16 x i32>
  %231 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %229, <16 x i32> %230, i32 %168)
  %232 = load <32 x i16>, ptr addrspace(6) %p_w.0.i69, align 64, !tbaa !4, !alias.scope !72, !noalias !80
  %add.ptr.i222.i = getelementptr inbounds i8, ptr %p_w.0.in300.i, i20 64
  %add.ptr.ascast.i223.i = addrspacecast ptr %add.ptr.i222.i to ptr addrspace(6)
  %233 = load <32 x i16>, ptr addrspace(6) %add.ptr.ascast.i223.i, align 64, !tbaa !4, !alias.scope !72, !noalias !80
  %234 = bitcast <16 x i32> %231 to <32 x i16>
  %235 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.addmac.conf(<32 x i16> %234, <32 x i16> %232, <64 x i32> %205, <64 x i32> %197, i32 %or25.i.i.i56)
  %236 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.addmac.conf(<32 x i16> %234, <32 x i16> %233, <64 x i32> %216, <64 x i32> %208, i32 %or25.i.i.i56)
  %p_in_fifo.sroa.0.1271.i = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } %223, 2
  %p_in_fifo.sroa.10.1272.i = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } %223, 3
  %p_in_fifo.sroa.19258.1273.i = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, <16 x i32> } %217, 4
  %p_in.1274.i = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } %223, 1
  call void @llvm.set.loop.iterations.i32(i32 %194)
  br label %for.body55.i82

for.cond.cleanup54.i89:                           ; preds = %for.body55.i82
  %237 = addrspacecast ptr addrspace(7) %p_psum_in_1.0295.i to ptr
  %238 = addrspacecast ptr addrspace(6) %p_psum_in_0.0297.i to ptr
  %add.ptr.i206.i78 = getelementptr inbounds i8, ptr %238, i20 128
  %add.ptr.i219.i = getelementptr inbounds i8, ptr %237, i20 128
  %add.ptr.ascast.i207.i = addrspacecast ptr %add.ptr.i206.i78 to ptr addrspace(6)
  %add.ptr.ascast.i220.i = addrspacecast ptr %add.ptr.i219.i to ptr addrspace(7)
  %scevgep.i90 = getelementptr i8, ptr %p_w.0.in300.i, i20 %193
  %239 = addrspacecast ptr addrspace(5) %p_in.1.i87 to ptr
  %240 = trunc i32 %iterator_outer_cnt0.0288.i to i20
  %241 = trunc i32 %iterator_outer_cnt1.0289.i to i20
  %242 = tail call { ptr, i20, i20 } @llvm.aie2ps.add.3d(ptr %239, i20 %176, i20 %177, i20 %178, i20 %179, i20 %240, i20 %180, i20 %241)
  %243 = extractvalue { ptr, i20, i20 } %242, 1
  %244 = zext i20 %243 to i32
  %245 = extractvalue { ptr, i20, i20 } %242, 2
  %246 = zext i20 %245 to i32
  %247 = extractvalue { ptr, i20, i20 } %242, 0
  %248 = trunc i32 %iterator_weights_cnt0.0290.i to i20
  %249 = trunc i32 %iterator_weights_cnt1.0291.i to i20
  %250 = tail call { ptr, i20, i20 } @llvm.aie2ps.add.3d(ptr nonnull %scevgep.i90, i20 %186, i20 %187, i20 %188, i20 %189, i20 %248, i20 %190, i20 %249)
  %251 = extractvalue { ptr, i20, i20 } %250, 1
  %252 = zext i20 %251 to i32
  %253 = extractvalue { ptr, i20, i20 } %250, 2
  %254 = zext i20 %253 to i32
  %255 = extractvalue { ptr, i20, i20 } %250, 0
  %256 = bitcast <64 x i32> %287 to <32 x i64>
  %shuffle.i.i229.i = shufflevector <32 x i64> %256, <32 x i64> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %257 = bitcast <16 x i64> %shuffle.i.i229.i to <32 x i32>
  %258 = tail call noundef <32 x i16> @llvm.aie2ps.I512.v32.acc32.srs(<32 x i32> %257, i32 range(i32 -128, 128) %conv90.i, i32 1)
  store <32 x i16> %258, ptr addrspace(6) %p_psum_out_0.0296.i, align 64, !tbaa !4, !alias.scope !74, !noalias !81
  %259 = addrspacecast ptr addrspace(6) %p_psum_out_0.0296.i to ptr
  %add.ptr.i230.i = getelementptr inbounds i8, ptr %259, i20 64
  %add.ptr.ascast.i231.i = addrspacecast ptr %add.ptr.i230.i to ptr addrspace(6)
  %shuffle1.i.i232.i = shufflevector <32 x i64> %256, <32 x i64> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %260 = bitcast <16 x i64> %shuffle1.i.i232.i to <32 x i32>
  %261 = tail call noundef <32 x i16> @llvm.aie2ps.I512.v32.acc32.srs(<32 x i32> %260, i32 range(i32 -128, 128) %conv90.i, i32 1)
  store <32 x i16> %261, ptr addrspace(6) %add.ptr.ascast.i231.i, align 64, !tbaa !4, !alias.scope !74, !noalias !81
  %add.ptr.i233.i = getelementptr inbounds i8, ptr %259, i20 128
  %add.ptr.ascast.i234.i = addrspacecast ptr %add.ptr.i233.i to ptr addrspace(6)
  %262 = bitcast <64 x i32> %288 to <32 x i64>
  %shuffle.i.i235.i = shufflevector <32 x i64> %262, <32 x i64> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %263 = bitcast <16 x i64> %shuffle.i.i235.i to <32 x i32>
  %264 = tail call noundef <32 x i16> @llvm.aie2ps.I512.v32.acc32.srs(<32 x i32> %263, i32 range(i32 -128, 128) %conv90.i, i32 1)
  store <32 x i16> %264, ptr addrspace(7) %p_psum_out_1.0298.i, align 64, !tbaa !4, !alias.scope !76, !noalias !82
  %265 = addrspacecast ptr addrspace(7) %p_psum_out_1.0298.i to ptr
  %add.ptr.i236.i = getelementptr inbounds i8, ptr %265, i20 64
  %add.ptr.ascast.i237.i = addrspacecast ptr %add.ptr.i236.i to ptr addrspace(7)
  %shuffle1.i.i238.i = shufflevector <32 x i64> %262, <32 x i64> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %266 = bitcast <16 x i64> %shuffle1.i.i238.i to <32 x i32>
  %267 = tail call noundef <32 x i16> @llvm.aie2ps.I512.v32.acc32.srs(<32 x i32> %266, i32 range(i32 -128, 128) %conv90.i, i32 1)
  store <32 x i16> %267, ptr addrspace(7) %add.ptr.ascast.i237.i, align 64, !tbaa !4, !alias.scope !76, !noalias !82
  %add.ptr.i239.i = getelementptr inbounds i8, ptr %265, i20 128
  %add.ptr.ascast.i240.i = addrspacecast ptr %add.ptr.i239.i to ptr addrspace(7)
  %lsr.iv.next133 = add i32 %lsr.iv132, -1
  %exitcond303.not.i = icmp eq i32 %lsr.iv.next133, 0
  br i1 %exitcond303.not.i, label %sw.epilog, label %for.body.i68, !llvm.loop !84

for.body55.i82:                                   ; preds = %for.body55.i82, %for.body.i68
  %p_in.1285.i = phi ptr addrspace(5) [ %p_in.1274.i, %for.body.i68 ], [ %p_in.1.i87, %for.body55.i82 ]
  %p_in_fifo.sroa.19258.1284.i = phi <16 x i32> [ %p_in_fifo.sroa.19258.1273.i, %for.body.i68 ], [ %p_in_fifo.sroa.19258.1.i, %for.body55.i82 ]
  %p_in_fifo.sroa.10.1283.i = phi i32 [ %p_in_fifo.sroa.10.1272.i, %for.body.i68 ], [ %p_in_fifo.sroa.10.1.i86, %for.body55.i82 ]
  %p_in_fifo.sroa.0.1282.i = phi <32 x i32> [ %p_in_fifo.sroa.0.1271.i, %for.body.i68 ], [ %p_in_fifo.sroa.0.1.i85, %for.body55.i82 ]
  %p_w.0.in.pn280.i = phi ptr [ %p_w.0.in300.i, %for.body.i68 ], [ %p_w.1.in281.i, %for.body55.i82 ]
  %acc_1.0278.i = phi <64 x i32> [ %236, %for.body.i68 ], [ %288, %for.body55.i82 ]
  %acc_0.0277.i = phi <64 x i32> [ %235, %for.body.i68 ], [ %287, %for.body55.i82 ]
  %iterator_inner_cnt1.1276.i = phi i32 [ %228, %for.body.i68 ], [ %280, %for.body55.i82 ]
  %iterator_inner_cnt0.1275.i = phi i32 [ %226, %for.body.i68 ], [ %278, %for.body55.i82 ]
  %p_w.1.in281.i = getelementptr inbounds i8, ptr %p_w.0.in.pn280.i, i20 128
  %p_w.1.i83 = addrspacecast ptr %p_w.1.in281.i to ptr addrspace(6)
  %268 = tail call { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.popx.p5.p5(ptr addrspace(5) %p_in.1285.i, <32 x i32> %p_in_fifo.sroa.0.1282.i, i32 %p_in_fifo.sroa.10.1283.i, <16 x i32> %p_in_fifo.sroa.19258.1284.i, i32 63), !alias.scope !69, !noalias !83
  %269 = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, <16 x i32> } %268, 0
  %270 = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, <16 x i32> } %268, 1
  %271 = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, <16 x i32> } %268, 2
  %272 = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, <16 x i32> } %268, 3
  %273 = trunc i32 %iterator_inner_cnt0.1275.i to i20
  %274 = trunc i32 %iterator_inner_cnt1.1276.i to i20
  %275 = tail call { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.ld.pop.3d.unaligned.p5.p5(ptr addrspace(5) %270, <32 x i32> %271, i32 %272, i20 %163, i20 %164, i20 %273, i20 %165, i20 %166, i20 %274, i20 %167), !alias.scope !69, !noalias !83
  %276 = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } %275, 0
  %277 = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } %275, 4
  %278 = zext i20 %277 to i32
  %279 = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } %275, 5
  %280 = zext i20 %279 to i32
  %281 = bitcast <64 x i8> %269 to <16 x i32>
  %282 = bitcast <64 x i8> %276 to <16 x i32>
  %283 = tail call <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32> %281, <16 x i32> %282, i32 %168)
  %284 = load <32 x i16>, ptr addrspace(6) %p_w.1.i83, align 64, !tbaa !4, !alias.scope !72, !noalias !80
  %add.ptr.i244.i = getelementptr inbounds i8, ptr %p_w.0.in.pn280.i, i20 192
  %add.ptr.ascast.i245.i = addrspacecast ptr %add.ptr.i244.i to ptr addrspace(6)
  %285 = load <32 x i16>, ptr addrspace(6) %add.ptr.ascast.i245.i, align 64, !tbaa !4, !alias.scope !72, !noalias !80
  %286 = bitcast <16 x i32> %283 to <32 x i16>
  %287 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16> %286, <32 x i16> %284, <64 x i32> %acc_0.0277.i, i32 %or22.i.i.i55)
  %288 = tail call noundef <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16> %286, <32 x i16> %285, <64 x i32> %acc_1.0278.i, i32 %or22.i.i.i55)
  %p_in_fifo.sroa.0.1.i85 = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } %275, 2
  %p_in_fifo.sroa.10.1.i86 = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } %275, 3
  %p_in_fifo.sroa.19258.1.i = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, <16 x i32> } %268, 4
  %p_in.1.i87 = extractvalue { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } %275, 1
  %289 = call i1 @llvm.loop.decrement.i32(i32 1)
  br i1 %289, label %for.body55.i82, label %for.cond.cleanup54.i89, !llvm.loop !85

sw.epilog:                                        ; preds = %for.cond.cleanup54.i89, %for.cond.cleanup54.i, %_Z24setup_conv2d_iter_paramsR13conv2d_params.exit
  ret void
}

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mul.conf(<64 x i8>, <64 x i8>, i32) #1

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read)
declare <32 x i32> @llvm.aie2ps.acc32.v32.I512.ups(<32 x i16>, i32, i32) #2

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: read)
declare { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, <16 x i32> } @llvm.aie2ps.fifo.ld.popx.p5.p5(ptr addrspace(5), <32 x i32>, i32, <16 x i32>, i32) #3

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: read)
declare { <64 x i8>, ptr addrspace(5), <32 x i32>, i32, i20, i20 } @llvm.aie2ps.fifo.ld.pop.3d.unaligned.p5.p5(ptr addrspace(5), <32 x i32>, i32, i20, i20, i20, i20, i20, i20, i20) #3

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <16 x i32> @llvm.aie2ps.vshuffle(<16 x i32>, <16 x i32>, i32) #1

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.addmac.conf(<32 x i16>, <32 x i16>, <64 x i32>, <64 x i32>, i32) #1

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <64 x i32> @llvm.aie2ps.I512.I512.ACC2048.mac.conf(<32 x i16>, <32 x i16>, <64 x i32>, i32) #1

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare { ptr, i20, i20 } @llvm.aie2ps.add.3d(ptr, i20, i20, i20, i20, i20, i20, i20) #1

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read)
declare <64 x i8> @llvm.aie2ps.I512.v64.acc32.srs(<64 x i32>, i32, i32) #2

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare { ptr, i20 } @llvm.aie2ps.add.2d(ptr, i20, i20, i20, i20) #1

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read)
declare <32 x i16> @llvm.aie2ps.I512.v32.acc32.srs(<32 x i32>, i32, i32) #2

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: readwrite)
declare void @llvm.experimental.noalias.scope.decl(metadata) #4

; Function Attrs: nocallback noduplicate nofree nosync nounwind willreturn
declare void @llvm.set.loop.iterations.i32(i32) #5

; Function Attrs: nocallback noduplicate nofree nosync nounwind willreturn
declare i1 @llvm.loop.decrement.i32(i32) #5

attributes #0 = { mustprogress "no-builtin-memcpy" "no-builtin-memmove" "no-builtin-memset" "no-jump-tables"="true" "no-trapping-math"="true" "stack-protector-buffer-size"="8" }
attributes #1 = { nocallback nofree nosync nounwind willreturn memory(none) }
attributes #2 = { nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read) }
attributes #3 = { nocallback nofree nosync nounwind willreturn memory(argmem: read) }
attributes #4 = { nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: readwrite) }
attributes #5 = { nocallback noduplicate nofree nosync nounwind willreturn }

!llvm.linker.options = !{}
!llvm.module.flags = !{!0, !1, !2}
!llvm.ident = !{!3}

!0 = !{i32 7, !"Dwarf Version", i32 4}
!1 = !{i32 2, !"Debug Info Version", i32 3}
!2 = !{i32 1, !"wchar_size", i32 4}
!3 = !{!"clang version 21.0.0git (https://gitenterprise.xilinx.com/FaaSApps/llvm-aie 1cc67d44128e8423c534ad17733c7c720c2a7dc4)"}
!4 = !{!5, !5, i64 0}
!5 = !{!"omnipotent char", !6, i64 0}
!6 = !{!"Simple C++ TBAA"}
!7 = !{!8, !5, i64 18}
!8 = !{!"_ZTS13conv2d_params", !5, i64 0, !5, i64 1, !5, i64 2, !5, i64 3, !5, i64 4, !5, i64 5, !5, i64 6, !5, i64 7, !5, i64 8, !5, i64 9, !5, i64 10, !5, i64 11, !9, i64 12, !5, i64 14, !5, i64 15, !5, i64 16, !5, i64 17, !5, i64 18, !5, i64 19, !9, i64 20, !5, i64 22, !5, i64 23, !9, i64 24, !5, i64 26, !5, i64 27, !5, i64 28, !5, i64 29, !5, i64 30, !5, i64 31, !10, i64 32, !5, i64 36, !5, i64 37, !11, i64 64}
!9 = !{!"short", !5, i64 0}
!10 = !{!"int", !5, i64 0}
!11 = !{!"_ZTS22conv2d_internal_params", !10, i64 0, !10, i64 4, !5, i64 8, !10, i64 12, !10, i64 16, !10, i64 20, !5, i64 24, !5, i64 28, !5, i64 32, !10, i64 36, !5, i64 40, !10, i64 44, !10, i64 48, !10, i64 52, !10, i64 56, !10, i64 60, !10, i64 64, !10, i64 68, !10, i64 72, !10, i64 76, !10, i64 80, !10, i64 84, !10, i64 88, !10, i64 92, !10, i64 96, !10, i64 100, !10, i64 104, !10, i64 108, !10, i64 112, !10, i64 116, !10, i64 120, !10, i64 124, !10, i64 128, !10, i64 132, !10, i64 136, !10, i64 140, !10, i64 144, !10, i64 148, !10, i64 152, !10, i64 156, !10, i64 160, !10, i64 164, !10, i64 168, !10, i64 172, !10, i64 176, !10, i64 180, !10, i64 184, !10, i64 188, !10, i64 192, !10, i64 196, !10, i64 200, !10, i64 204, !10, i64 208, !10, i64 212, !10, i64 216, !10, i64 220, !10, i64 224, !10, i64 228, !10, i64 232, !10, i64 236, !10, i64 240, !10, i64 244, !10, i64 248, !10, i64 252, !10, i64 256, !9, i64 260, !9, i64 262, !5, i64 264, !10, i64 268, !10, i64 272, !5, i64 276, !5, i64 277}
!12 = !{!8, !5, i64 96}
!13 = !{!8, !10, i64 76}
!14 = !{!8, !5, i64 7}
!15 = !{!8, !5, i64 28}
!16 = !{!8, !10, i64 80}
!17 = !{!8, !5, i64 104}
!18 = !{!8, !10, i64 84}
!19 = !{!8, !10, i64 120}
!20 = !{!21}
!21 = distinct !{!21, !22, !"_Z18conv2d_generic_optILh1EL5act_t0EL10out_mode_t0EaaaEvPiS2_S2_S2_S2_R13conv2d_params: %input"}
!22 = distinct !{!22, !"_Z18conv2d_generic_optILh1EL5act_t0EL10out_mode_t0EaaaEvPiS2_S2_S2_S2_R13conv2d_params"}
!23 = !{!24}
!24 = distinct !{!24, !22, !"_Z18conv2d_generic_optILh1EL5act_t0EL10out_mode_t0EaaaEvPiS2_S2_S2_S2_R13conv2d_params: %weights"}
!25 = !{!26}
!26 = distinct !{!26, !22, !"_Z18conv2d_generic_optILh1EL5act_t0EL10out_mode_t0EaaaEvPiS2_S2_S2_S2_R13conv2d_params: %psum_0"}
!27 = !{!28}
!28 = distinct !{!28, !22, !"_Z18conv2d_generic_optILh1EL5act_t0EL10out_mode_t0EaaaEvPiS2_S2_S2_S2_R13conv2d_params: %psum_1"}
!29 = !{!30}
!30 = distinct !{!30, !22, !"_Z18conv2d_generic_optILh1EL5act_t0EL10out_mode_t0EaaaEvPiS2_S2_S2_S2_R13conv2d_params: %output"}
!31 = !{!8, !10, i64 220}
!32 = !{!21, !24, !26, !28, !30}
!33 = !{!8, !10, i64 336}
!34 = !{!8, !10, i64 216}
!35 = !{!8, !10, i64 112}
!36 = !{!8, !5, i64 8}
!37 = !{!8, !5, i64 9}
!38 = !{!8, !10, i64 140}
!39 = !{!8, !10, i64 132}
!40 = !{!8, !10, i64 124}
!41 = !{!8, !10, i64 136}
!42 = !{!8, !10, i64 128}
!43 = !{!8, !10, i64 316}
!44 = !{!8, !10, i64 32}
!45 = !{!8, !10, i64 108}
!46 = !{!8, !10, i64 160}
!47 = !{!8, !10, i64 152}
!48 = !{!8, !10, i64 144}
!49 = !{!8, !10, i64 156}
!50 = !{!8, !10, i64 148}
!51 = !{!8, !10, i64 180}
!52 = !{!8, !10, i64 172}
!53 = !{!8, !10, i64 164}
!54 = !{!8, !10, i64 176}
!55 = !{!8, !10, i64 168}
!56 = !{!8, !10, i64 64}
!57 = !{!8, !5, i64 6}
!58 = !{!8, !10, i64 232}
!59 = !{!21, !26, !28, !30}
!60 = !{!21, !24, !28, !30}
!61 = !{!21, !24, !26, !30}
!62 = !{!24, !26, !28, !30}
!63 = !{!21, !24, !26, !28}
!64 = distinct !{!64, !65, !66}
!65 = !{!"llvm.loop.mustprogress"}
!66 = !{!"llvm.loop.itercount.range", i64 2}
!67 = distinct !{!67, !65, !68}
!68 = !{!"llvm.loop.itercount.range", i64 7}
!69 = !{!70}
!70 = distinct !{!70, !71, !"_Z18conv2d_generic_optILh1EL5act_t0EL10out_mode_t1EaaaEvPiS2_S2_S2_S2_R13conv2d_params: %input"}
!71 = distinct !{!71, !"_Z18conv2d_generic_optILh1EL5act_t0EL10out_mode_t1EaaaEvPiS2_S2_S2_S2_R13conv2d_params"}
!72 = !{!73}
!73 = distinct !{!73, !71, !"_Z18conv2d_generic_optILh1EL5act_t0EL10out_mode_t1EaaaEvPiS2_S2_S2_S2_R13conv2d_params: %weights"}
!74 = !{!75}
!75 = distinct !{!75, !71, !"_Z18conv2d_generic_optILh1EL5act_t0EL10out_mode_t1EaaaEvPiS2_S2_S2_S2_R13conv2d_params: %psum_0"}
!76 = !{!77}
!77 = distinct !{!77, !71, !"_Z18conv2d_generic_optILh1EL5act_t0EL10out_mode_t1EaaaEvPiS2_S2_S2_S2_R13conv2d_params: %psum_1"}
!78 = !{!70, !73, !75, !77}
!79 = !{!8, !5, i64 10}
!80 = !{!70, !75, !77}
!81 = !{!70, !73, !77}
!82 = !{!70, !73, !75}
!83 = !{!73, !75, !77}
!84 = distinct !{!84, !65, !66}
!85 = distinct !{!85, !65, !68}
