# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple=aie2p -run-pass detect-dead-lanes -o - %s | FileCheck %s

---
name: vec512
body: |
  bb.0:
    liveins: $wl0, $wh0
    ; CHECK-LABEL: name: vec512
    ; CHECK: liveins: $wl0, $wh0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec256 = COPY $wh0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec512 = REG_SEQUENCE [[COPY]], %subreg.sub_256_lo, [[COPY1]], %subreg.sub_256_hi
    ; CHECK-NEXT: $x0 = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vec256 = COPY $wl0
    %2:vec256 = COPY $wh0
    %3:vec512 = REG_SEQUENCE %1, %subreg.sub_256_lo, %2, %subreg.sub_256_hi
    $x0 = COPY %3
    PseudoRET implicit $lr, implicit $x0
...

---
name: vec1024
body: |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: vec1024
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x1
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec1024 = REG_SEQUENCE [[COPY]], %subreg.sub_512_lo, [[COPY1]], %subreg.sub_512_hi
    ; CHECK-NEXT: $y2 = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y2
    %1:vec512 = COPY $x0
    %2:vec512 = COPY $x1
    %3:vec1024 = REG_SEQUENCE %1, %subreg.sub_512_lo, %2, %subreg.sub_512_hi
    $y2 = COPY %3
    PseudoRET implicit $lr, implicit $y2
...

---
name: acc1024
body: |
  bb.0:
    liveins: $bmll1, $bmll2

    ; CHECK-LABEL: name: acc1024
    ; CHECK: liveins: $bmll1, $bmll2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:mwbfsrs = COPY $bmll1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mwbfsrs = COPY $bmll2
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc1024 = REG_SEQUENCE [[COPY]], %subreg.sub_512_acc_lo, [[COPY1]], %subreg.sub_512_acc_hi
    ; CHECK-NEXT: $cml0 = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cml0
    %1:mwbfsrs = COPY $bmll1
    %2:mwbfsrs = COPY $bmll2
    %3:acc1024 = REG_SEQUENCE %1, %subreg.sub_512_acc_lo, %2, %subreg.sub_512_acc_hi
    $cml0 = COPY %3
    PseudoRET implicit $lr, implicit $cml0
...

---
name: acc2048
body: |
  bb.0:
    liveins: $cml1, $cml2
    ; CHECK-LABEL: name: acc2048
    ; CHECK: liveins: $cml1, $cml2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ecml = COPY $cml1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ecmh = COPY $cml2
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc2048 = REG_SEQUENCE [[COPY]], %subreg.sub_1024_acc_lo, [[COPY1]], %subreg.sub_1024_acc_hi
    ; CHECK-NEXT: $dm0 = COPY [[REG_SEQUENCE]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $dm0
    %1:ecml = COPY $cml1
    %2:ecmh = COPY $cml2
    %3:acc2048 = REG_SEQUENCE %1, %subreg.sub_1024_acc_lo, %2, %subreg.sub_1024_acc_hi
    $dm0 = COPY %3
    PseudoRET implicit $lr, implicit $dm0
...
