# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024-2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -verify-machineinstrs --march=aie2p -run-pass=prologepilog %s -o - | FileCheck %s

# Note that the "offset" mentionned in the stack objects in irrelevant. It is
# re-computed by the prologepilog pass in AdjustStackOffset().

---
name:            test_scl
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 4, alignment: 4 }
  - { id: 1, name: '', type: spill-slot, offset: 0, size: 4, alignment: 4 }
body:             |
  bb.0 (align 16):
    ; CHECK-LABEL: name: test_scl
    ; CHECK: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r2 = LDA_dms_lda_spill -60, implicit $sp
    ; CHECK-NEXT: ST_dms_sts_spill $r2, -60, implicit $sp
    $r2 = LDA_R_SPILL %stack.1, implicit $sp
    ST_R_SPILL $r2, %stack.1, implicit $sp
...

---
name:            test_scl_explicit_lda_st_spill
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 4, alignment: 4 }
  - { id: 1, name: '', type: spill-slot, offset: 0, size: 4, alignment: 4 }
body:             |
  bb.0 (align 16):
    ; CHECK-LABEL: name: test_scl_explicit_lda_st_spill
    ; CHECK: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r2 = LDA_dms_lda_spill -60, implicit $sp
    ; CHECK-NEXT: ST_dms_sts_spill $r2, -60, implicit $sp
    $r2 = LDA_dms_lda_spill %stack.1, implicit $sp
    ST_dms_sts_spill $r2, %stack.1, implicit $sp
...

---
name:            test_vec256
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 4, alignment: 4 }
  - { id: 1, name: '', type: spill-slot, offset: 0, size: 32, alignment: 32 }
body:             |
  bb.0 (align 16):
    ; CHECK-LABEL: name: test_vec256
    ; CHECK: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $wl1 = VLDA_dmw_lda_w_spill -64, implicit $sp
    ; CHECK-NEXT: VST_dmw_sts_w_spill $wl1, -64, implicit $sp
    $wl1 = VLDA_dmw_lda_w_spill %stack.1, implicit $sp
    VST_dmw_sts_w_spill $wl1, %stack.1, implicit $sp
...

---
name:            test_vec512
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 4, alignment: 4 }
  - { id: 1, name: '', type: spill-slot, offset: 0, size: 32, alignment: 32 }
body:             |
  bb.0 (align 16):
    ; CHECK-LABEL: name: test_vec512
    ; CHECK: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $wl1 = VLDA_dmw_lda_w_spill -64, implicit $sp
    ; CHECK-NEXT: VST_dmw_sts_w_spill $wl1, -64, implicit $sp
    $wl1 = VLDA_dmw_lda_w_spill %stack.1, implicit $sp
    VST_dmw_sts_w_spill $wl1, %stack.1, implicit $sp
...

---
name:            test_fifo_vec
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 4, alignment: 4 }
  - { id: 1, name: '', type: spill-slot, offset: 0, size: 32, alignment: 32 }
body:             |
  bb.0 (align 16):
    ; CHECK-LABEL: name: test_fifo_vec
    ; CHECK: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $lfh0 = VLDA_dmx_lda_fifohl_spill -64, implicit $sp
    ; CHECK-NEXT: VST_dmx_sts_fifohl_spill $lfh0, -64, implicit $sp
    $lfh0 = VLDA_dmx_lda_fifohl_spill %stack.1, implicit $sp
    VST_dmx_sts_fifohl_spill  $lfh0, %stack.1, implicit $sp
...

---
name:            test_acc512
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 4, alignment: 4 }
  - { id: 1, name: '', type: spill-slot, offset: 0, size: 32, alignment: 32 }
body:             |
  bb.0 (align 16):
    ; CHECK-LABEL: name: test_acc512
    ; CHECK: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $bmll1 = VLDA_dmx_lda_bm_spill -64, implicit $sp
    ; CHECK-NEXT: VST_dmx_sts_bm_spill $bmll1, -64, implicit $sp
    $bmll1 = VLDA_dmx_lda_bm_spill %stack.1, implicit $sp
    VST_dmx_sts_bm_spill $bmll1, %stack.1, implicit $sp
...

---
name:            test_vec1024
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 128, alignment: 32 }
body:             |
  bb.0 (align 16):

    ; CHECK-LABEL: name: test_vec1024
    ; CHECK: frame-setup PADDXM_pstm_sp_imm 128, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: VST_dmx_sts_x_spill $x6, -128, implicit $sp :: (store (s512) into %stack.0)
    ; CHECK-NEXT: VST_dmx_sts_x_spill $x7, -64, implicit $sp :: (store (s512) into %stack.0 + 64)
    ; CHECK-NEXT: $x6 = VLDA_dmx_lda_x_spill -128, implicit $sp :: (load (s512) from %stack.0)
    ; CHECK-NEXT: $x7 = VLDA_dmx_lda_x_spill -64, implicit $sp :: (load (s512) from %stack.0 + 64)
    VST_Y_SPILL $y3, %stack.0, implicit $sp :: (store (s1024) into %stack.0, align 64)
    $y3 = VLDA_Y_SPILL %stack.0, implicit $sp :: (load (s1024) from %stack.0, align 64)
...

---
name:            test_acc1024
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 128, alignment: 32 }
body:             |
  bb.0 (align 16):

    ; CHECK-LABEL: name: test_acc1024
    ; CHECK: frame-setup PADDXM_pstm_sp_imm 128, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: VST_dmx_sts_bm_spill $bmll3, -128, implicit $sp :: (store (s512) into %stack.0)
    ; CHECK-NEXT: VST_dmx_sts_bm_spill $bmlh3, -64, implicit $sp :: (store (s512) into %stack.0 + 64)
    ; CHECK-NEXT: $bmll3 = VLDA_dmx_lda_bm_spill -128, implicit $sp :: (load (s512) from %stack.0)
    ; CHECK-NEXT: $bmlh3 = VLDA_dmx_lda_bm_spill -64, implicit $sp :: (load (s512) from %stack.0 + 64)
    VST_CM_SPILL $cml3, %stack.0, implicit $sp :: (store (s1024) into %stack.0, align 64)
    $cml3 = VLDA_CM_SPILL %stack.0, implicit $sp :: (load (s1024) from %stack.0, align 64)
...


---
name:            test_acc2048
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 128, alignment: 32 }
body:             |
  bb.0 (align 16):

    ; CHECK-LABEL: name: test_acc2048
    ; CHECK: frame-setup PADDXM_pstm_sp_imm 128, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: VST_dmx_sts_bm_spill $bmll3, -128, implicit $sp :: (store (s512) into %stack.0)
    ; CHECK-NEXT: VST_dmx_sts_bm_spill $bmlh3, -64, implicit $sp :: (store (s512) into %stack.0 + 64)
    ; CHECK-NEXT: VST_dmx_sts_bm_spill $bmhl3, 0, implicit $sp :: (store (s512) into %stack.0 + 128)
    ; CHECK-NEXT: VST_dmx_sts_bm_spill $bmhh3, 64, implicit $sp :: (store (s512) into %stack.0 + 192)
    ; CHECK-NEXT: $bmll3 = VLDA_dmx_lda_bm_spill -128, implicit $sp :: (load (s512) from %stack.0)
    ; CHECK-NEXT: $bmlh3 = VLDA_dmx_lda_bm_spill -64, implicit $sp :: (load (s512) from %stack.0 + 64)
    ; CHECK-NEXT: $bmhl3 = VLDA_dmx_lda_bm_spill 0, implicit $sp :: (load (s512) from %stack.0 + 128)
    ; CHECK-NEXT: $bmhh3 = VLDA_dmx_lda_bm_spill 64, implicit $sp :: (load (s512) from %stack.0 + 192)
    VST_DM_SPILL $dm3, %stack.0, implicit $sp :: (store (s1024) into %stack.0, align 64)
    $dm3 = VLDA_DM_SPILL %stack.0, implicit $sp :: (load (s2048) from %stack.0, align 64)
...


---
name:            test_vec128
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 4, alignment: 4 }
  - { id: 1, name: '', type: spill-slot, offset: 0, size: 16, alignment: 16 }
body:             |
  bb.0 (align 16):
    ; CHECK-LABEL: name: test_vec128
    ; CHECK: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $wh0 = VLDA_128_dmv_lda_w_spill -64, implicit $sp
    ; CHECK-NEXT: VST_128_dmv_sts_w_spill $wh0, -64, implicit $sp
    $wh0 = VLDA_128_dmv_lda_w_spill %stack.1, implicit $sp
    VST_128_dmv_sts_w_spill $wh0, %stack.1, implicit $sp
...


---
name:            test_vec64
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 4, alignment: 4 }
  - { id: 1, name: '', type: spill-slot, offset: 0, size: 8, alignment: 8 }
body:             |
  bb.0 (align 16):
    ; CHECK-LABEL: name: test_vec64
    ; CHECK: liveins: $r14, $r15
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r0 = PseudoMove killed $r14
    ; CHECK-NEXT: $r1 = PseudoMove killed $r15
    ; CHECK-NEXT: $r14 = LDA_dms_lda_spill -64, implicit $sp
    ; CHECK-NEXT: $r15 = LDA_dms_lda_spill -60, implicit $sp
    ; CHECK-NEXT: ST_dms_sts_spill $r14, -64, implicit $sp
    ; CHECK-NEXT: ST_dms_sts_spill $r15, -60, implicit $sp
    $l7 = VLDA_L_SPILL %stack.1, implicit $sp
    VST_L_SPILL $l7, %stack.1, implicit $sp
...

---
name:            test_vec64_exp
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 8, alignment: 4 }
body:             |
  bb.0 (align 16):
    ; CHECK-LABEL: name: test_vec64_exp
    ; CHECK: frame-setup PADDXM_pstm_sp_imm 64, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $el0 = LDA_dms_lda_spill -64, implicit $sp
    ; CHECK-NEXT: $eh0 = LDA_dms_lda_spill -60, implicit $sp
    ; CHECK-NEXT: ST_dms_sts_spill $el0, -64, implicit $sp
    ; CHECK-NEXT: ST_dms_sts_spill $eh0, -60, implicit $sp
    $e0 = VLDA_E_SPILL %stack.0, implicit $sp
    VST_E_SPILL $e0, %stack.0, implicit $sp
...


---
name:            test_vec576
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 72, alignment: 4 }
body:             |
  bb.0 (align 16):
    ; CHECK-LABEL: name: test_vec576
    ; CHECK: frame-setup PADDXM_pstm_sp_imm 128, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $x0 = VLDA_dmx_lda_x_spill -128, implicit $sp
    ; CHECK-NEXT: $el0 = LDA_dms_lda_spill -64, implicit $sp
    ; CHECK-NEXT: $eh0 = LDA_dms_lda_spill -60, implicit $sp
    ; CHECK-NEXT: VST_dmx_sts_x_spill $x0, -128, implicit $sp
    ; CHECK-NEXT: ST_dms_sts_spill $el0, -64, implicit $sp
    ; CHECK-NEXT: ST_dms_sts_spill $eh0, -60, implicit $sp
    $ex0 = VLDA_EX_SPILL %stack.0, implicit $sp
    VST_EX_SPILL $ex0, %stack.0, implicit $sp
...


---
name:            test_fifo_lf
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 128, alignment: 32 }
body:             |
  bb.0 (align 16):

    ; CHECK-LABEL: name: test_fifo_lf
    ; CHECK: frame-setup PADDXM_pstm_sp_imm 128, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $lfl0 = VLDA_dmx_lda_fifohl_spill -128, implicit $sp
    ; CHECK-NEXT: $lfh0 = VLDA_dmx_lda_fifohl_spill -64, implicit $sp
    ; CHECK-NEXT: VST_dmx_sts_fifohl_spill $lfl0, -128, implicit $sp
    ; CHECK-NEXT: VST_dmx_sts_fifohl_spill $lfh0, -64, implicit $sp
    $lf0 = VLDA_FIFO_SPILL %stack.0, implicit $sp
    VST_FIFO_SPILL $lf0, %stack.0, implicit $sp
...

---
name:            test_fifo_sf
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 128, alignment: 32 }
body:             |
  bb.0 (align 16):

    ; CHECK-LABEL: name: test_fifo_sf
    ; CHECK: frame-setup PADDXM_pstm_sp_imm 128, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $sfl = VLDA_dmx_lda_fifohl_spill -128, implicit $sp
    ; CHECK-NEXT: $sfh = VLDA_dmx_lda_fifohl_spill -64, implicit $sp
    ; CHECK-NEXT: VST_dmx_sts_fifohl_spill $sfl, -128, implicit $sp
    ; CHECK-NEXT: VST_dmx_sts_fifohl_spill $sfh, -64, implicit $sp
    $sf = VLDA_FIFO_SPILL %stack.0, implicit $sp
    VST_FIFO_SPILL $sf, %stack.0, implicit $sp
...


---
name:            test_fifo_plfr
alignment:       16
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 136, alignment: 32 }
body:             |
  bb.0 (align 16):

    ; CHECK-LABEL: name: test_fifo_plfr
    ; CHECK: frame-setup PADDXM_pstm_sp_imm 192, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $lfl0 = VLDA_dmx_lda_fifohl_spill -192, implicit $sp
    ; CHECK-NEXT: $lfh0 = VLDA_dmx_lda_fifohl_spill -128, implicit $sp
    ; CHECK-NEXT: $r24 = LDA_dms_lda_spill -64, implicit $sp
    ; CHECK-NEXT: $p0 = LDA_dms_lda_spill -60, implicit $sp
    ; CHECK-NEXT: VST_dmx_sts_fifohl_spill $lfl0, -192, implicit $sp
    ; CHECK-NEXT: VST_dmx_sts_fifohl_spill $lfh0, -128, implicit $sp
    ; CHECK-NEXT: ST_dms_sts_spill $r24, -64, implicit $sp
    ; CHECK-NEXT: ST_dms_sts_spill $p0, -60, implicit $sp
    $plfr0 = VLDA_PLFR_SPILL %stack.0, implicit $sp
    VST_PLFR_SPILL $plfr0, %stack.0, implicit $sp
...

---
name:            test_scl_big_offset
alignment:       16
frameInfo:
  adjustsStack:    true
stack:
  - { id: 0, name: '', type: default, offset: 0, size: 2200, alignment: 16,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true }
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_scl_big_offset
    ; CHECK: frame-setup PADDXM_pstm_sp_imm 2240, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: ST_dms_sts_spill killed $lr, -40, implicit $sp :: (store (s32) into %stack.1)
    ; CHECK-NEXT: $p0 = MOV_alu_mv_mv_mv_scl $sp
    ; CHECK-NEXT: $m0 = MOVXM -2240
    ; CHECK-NEXT: $p0 = PADD_mod_pseudo $p0, killed $m0
    ; CHECK-NEXT: PseudoJL 10, csr_aie2p, implicit-def $lr, implicit $p0
    ; CHECK-NEXT: $lr = LDA_dms_lda_spill -40, implicit $sp :: (load (s32) from %stack.1)
    ; CHECK-NEXT: frame-destroy PADDXM_pstm_sp_imm -2240, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: PseudoRET implicit $lr
    renamable $p0 = PseudoFI %stack.0, implicit $sp
    ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    PseudoJL 10, csr_aie2p, implicit-def $lr, implicit $p0
    ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    PseudoRET implicit $lr
...
---
name:            test_vec64_big_offset
alignment:       16
frameInfo:
  adjustsStack:    true
stack:
  - { id: 0, name: '', type: default, offset: 0, size: 2200, alignment: 16 }
  - { id: 1, name: '', type: spill-slot, offset: 0, size: 8, alignment: 8 }
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_vec64_big_offset
    ; CHECK: frame-setup PADDXM_pstm_sp_imm 2240, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $p0 = MOV_alu_mv_mv_mv_scl $sp
    ; CHECK-NEXT: $m0 = MOVXM -2240
    ; CHECK-NEXT: $p0 = PADD_mod_pseudo $p0, killed $m0
    ; CHECK-NEXT: $p0 = MOV_alu_mv_mv_mv_scl $sp
    ; CHECK-NEXT: $dj0 = MOVXM -2240
    ; CHECK-NEXT: $r2 = LDA_dms_lda_idx $p0, killed $dj0
    ; CHECK-NEXT: $dj0 = MOVXM -2236
    ; CHECK-NEXT: $r3 = LDA_dms_lda_idx killed $p0, killed $dj0
    ; CHECK-NEXT: $p0 = MOV_alu_mv_mv_mv_scl $sp
    ; CHECK-NEXT: $dj0 = MOVXM -2240
    ; CHECK-NEXT: ST_dms_sts_idx $r2, $p0, killed $dj0
    ; CHECK-NEXT: $dj0 = MOVXM -2236
    ; CHECK-NEXT: ST_dms_sts_idx $r3, killed $p0, killed $dj0
    ; CHECK-NEXT: frame-destroy PADDXM_pstm_sp_imm -2240, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: PseudoRET implicit $lr
    renamable $p0 = PseudoFI %stack.0, implicit $sp
    ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    $l1 = VLDA_L_SPILL %stack.0, implicit $sp
    VST_L_SPILL $l1, %stack.0, implicit $sp
    ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    PseudoRET implicit $lr
...
---
name:            test_D_big_offset
alignment:       16
frameInfo:
  adjustsStack:    true
stack:
  - { id: 0, name: '', type: default, offset: 0, size: 2200, alignment: 16 }
  - { id: 1, name: '', type: spill-slot, offset: 0, size: 8, alignment: 8 }
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_D_big_offset
    ; CHECK: frame-setup PADDXM_pstm_sp_imm 2240, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $p0 = MOV_alu_mv_mv_mv_scl $sp
    ; CHECK-NEXT: $m0 = MOVXM -2240
    ; CHECK-NEXT: $p0 = PADD_mod_pseudo $p0, killed $m0
    ; CHECK-NEXT: $p0 = MOV_alu_mv_mv_mv_scl $sp
    ; CHECK-NEXT: $dj0 = MOVXM -2240
    ; CHECK-NEXT: $m0 = LDA_dms_lda_idx $p0, killed $dj0
    ; CHECK-NEXT: $dj0 = MOVXM -2236
    ; CHECK-NEXT: $dn0 = LDA_dms_lda_idx $p0, killed $dj0
    ; CHECK-NEXT: $dj0 = MOVXM -2232
    ; CHECK-NEXT: $dj0 = LDA_dms_lda_idx $p0, killed $dj0
    ; CHECK-NEXT: $dj1 = MOVXM -2228
    ; CHECK-NEXT: $dc0 = LDA_dms_lda_idx killed $p0, killed $dj1
    ; CHECK-NEXT: $p0 = MOV_alu_mv_mv_mv_scl $sp
    ; CHECK-NEXT: $dj1 = MOVXM -2240
    ; CHECK-NEXT: ST_dms_sts_idx $m0, $p0, killed $dj1
    ; CHECK-NEXT: $dj1 = MOVXM -2236
    ; CHECK-NEXT: ST_dms_sts_idx $dn0, $p0, killed $dj1
    ; CHECK-NEXT: $dj1 = MOVXM -2232
    ; CHECK-NEXT: ST_dms_sts_idx $dj0, $p0, killed $dj1
    ; CHECK-NEXT: $dj0 = MOVXM -2228
    ; CHECK-NEXT: ST_dms_sts_idx $dc0, killed $p0, killed $dj0
    ; CHECK-NEXT: frame-destroy PADDXM_pstm_sp_imm -2240, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: PseudoRET implicit $lr
    renamable $p0 = PseudoFI %stack.0, implicit $sp
    ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    $d0 = LDA_D_SPILL %stack.0, implicit $sp
    ST_D_SPILL $d0, %stack.0, implicit $sp
    ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    PseudoRET implicit $lr
...
---
name:            test_DS_big_offset
alignment:       16
frameInfo:
  adjustsStack:    true
stack:
  - { id: 0, name: '', type: default, offset: 0, size: 2200, alignment: 16 }
  - { id: 1, name: '', type: spill-slot, offset: 0, size: 8, alignment: 8 }
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_DS_big_offset
    ; CHECK: frame-setup PADDXM_pstm_sp_imm 2240, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $p0 = MOV_alu_mv_mv_mv_scl $sp
    ; CHECK-NEXT: $m0 = MOVXM -2240
    ; CHECK-NEXT: $p0 = PADD_mod_pseudo $p0, killed $m0
    ; CHECK-NEXT: $p0 = MOV_alu_mv_mv_mv_scl $sp
    ; CHECK-NEXT: $dj0 = MOVXM -2240
    ; CHECK-NEXT: $m0 = LDA_dms_lda_idx $p0, killed $dj0
    ; CHECK-NEXT: $dj0 = MOVXM -2236
    ; CHECK-NEXT: $dn0 = LDA_dms_lda_idx $p0, killed $dj0
    ; CHECK-NEXT: $dj0 = MOVXM -2232
    ; CHECK-NEXT: $dj0 = LDA_dms_lda_idx $p0, killed $dj0
    ; CHECK-NEXT: $dj1 = MOVXM -2228
    ; CHECK-NEXT: $dc0 = LDA_dms_lda_idx $p0, killed $dj1
    ; CHECK-NEXT: $dj1 = MOVXM -2224
    ; CHECK-NEXT: $m4 = LDA_dms_lda_idx $p0, killed $dj1
    ; CHECK-NEXT: $dj1 = MOVXM -2220
    ; CHECK-NEXT: $dn4 = LDA_dms_lda_idx $p0, killed $dj1
    ; CHECK-NEXT: $dj1 = MOVXM -2216
    ; CHECK-NEXT: $dj4 = LDA_dms_lda_idx $p0, killed $dj1
    ; CHECK-NEXT: $dj1 = MOVXM -2212
    ; CHECK-NEXT: $dc4 = LDA_dms_lda_idx killed $p0, killed $dj1
    ; CHECK-NEXT: $p0 = MOV_alu_mv_mv_mv_scl $sp
    ; CHECK-NEXT: $dj1 = MOVXM -2240
    ; CHECK-NEXT: ST_dms_sts_idx $m0, $p0, killed $dj1
    ; CHECK-NEXT: $dj1 = MOVXM -2236
    ; CHECK-NEXT: ST_dms_sts_idx $dn0, $p0, killed $dj1
    ; CHECK-NEXT: $dj1 = MOVXM -2232
    ; CHECK-NEXT: ST_dms_sts_idx $dj0, $p0, killed $dj1
    ; CHECK-NEXT: $dj0 = MOVXM -2228
    ; CHECK-NEXT: ST_dms_sts_idx $dc0, $p0, killed $dj0
    ; CHECK-NEXT: $dj0 = MOVXM -2224
    ; CHECK-NEXT: ST_dms_sts_idx $m4, $p0, killed $dj0
    ; CHECK-NEXT: $dj0 = MOVXM -2220
    ; CHECK-NEXT: ST_dms_sts_idx $dn4, $p0, killed $dj0
    ; CHECK-NEXT: $dj0 = MOVXM -2216
    ; CHECK-NEXT: ST_dms_sts_idx $dj4, $p0, killed $dj0
    ; CHECK-NEXT: $dj0 = MOVXM -2212
    ; CHECK-NEXT: ST_dms_sts_idx $dc4, killed $p0, killed $dj0
    ; CHECK-NEXT: frame-destroy PADDXM_pstm_sp_imm -2240, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: PseudoRET implicit $lr
    renamable $p0 = PseudoFI %stack.0, implicit $sp
    ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    $d0_3d = LDA_DS_SPILL %stack.0, implicit $sp
    ST_DS_SPILL $d0_3d, %stack.0, implicit $sp
    ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    PseudoRET implicit $lr
...
---
name:            test_fifo_plfr_bigstack
alignment:       16
frameInfo:
  adjustsStack:    true
stack:
  - { id: 0, name: '', type: default, offset: 0, size: 2200, alignment: 16 }
  - { id: 1, name: '', type: spill-slot, offset: 0, size: 8, alignment: 8 }
body:             |
  bb.0 (align 16):
    ; CHECK-LABEL: name: test_fifo_plfr_bigstack
    ; CHECK: frame-setup PADDXM_pstm_sp_imm 2240, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $p0 = MOV_alu_mv_mv_mv_scl $sp
    ; CHECK-NEXT: $m0 = MOVXM -2240
    ; CHECK-NEXT: $p0 = PADD_mod_pseudo $p0, killed $m0
    ; CHECK-NEXT: $p0 = MOV_alu_mv_mv_mv_scl $sp
    ; CHECK-NEXT: $dj0 = MOVXM -2240
    ; CHECK-NEXT: $lfl0 = VLDA_dmx_lda_fifohl_idx $p0, killed $dj0
    ; CHECK-NEXT: $dj0 = MOVXM -2176
    ; CHECK-NEXT: $lfh0 = VLDA_dmx_lda_fifohl_idx $p0, killed $dj0
    ; CHECK-NEXT: $dj0 = MOVXM -2112
    ; CHECK-NEXT: $r24 = LDA_dms_lda_idx $p0, killed $dj0
    ; CHECK-NEXT: $dj0 = MOVXM -2108
    ; CHECK-NEXT: $p0 = LDA_dms_lda_idx killed $p0, killed $dj0
    ; CHECK-NEXT: $p1 = MOV_alu_mv_mv_mv_scl $sp
    ; CHECK-NEXT: $dj0 = MOVXM -2240
    ; CHECK-NEXT: VST_dmx_sts_fifohl_idx $lfl0, $p1, killed $dj0
    ; CHECK-NEXT: $dj0 = MOVXM -2176
    ; CHECK-NEXT: VST_dmx_sts_fifohl_idx $lfh0, $p1, killed $dj0
    ; CHECK-NEXT: $dj0 = MOVXM -2112
    ; CHECK-NEXT: ST_dms_sts_idx $r24, $p1, killed $dj0
    ; CHECK-NEXT: $dj0 = MOVXM -2108
    ; CHECK-NEXT: ST_dms_sts_idx $p0, killed $p1, killed $dj0
    renamable $p0 = PseudoFI %stack.0, implicit $sp
    ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    $plfr0 = VLDA_PLFR_SPILL %stack.0, implicit $sp
    VST_PLFR_SPILL $plfr0, %stack.0, implicit $sp
    ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
...


---
name:            test_ex_bigstack
alignment:       16
frameInfo:
  adjustsStack:    true
stack:
  - { id: 0, name: '', type: default, offset: 0, size: 2200, alignment: 16 }
  - { id: 1, name: '', type: spill-slot, offset: 0, size: 8, alignment: 8 }
body:             |
  bb.0 (align 16):
    ; CHECK-LABEL: name: test_ex_bigstack
    ; CHECK: frame-setup PADDXM_pstm_sp_imm 2240, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $p0 = MOV_alu_mv_mv_mv_scl $sp
    ; CHECK-NEXT: $m0 = MOVXM -2240
    ; CHECK-NEXT: $p0 = PADD_mod_pseudo $p0, killed $m0
    ; CHECK-NEXT: $p0 = MOV_alu_mv_mv_mv_scl $sp
    ; CHECK-NEXT: $dj0 = MOVXM -2240
    ; CHECK-NEXT: $x0 = VLDA_dmx_lda_x_idx $p0, killed $dj0
    ; CHECK-NEXT: $dj0 = MOVXM -2176
    ; CHECK-NEXT: $el0 = LDA_dms_lda_idx $p0, killed $dj0
    ; CHECK-NEXT: $dj0 = MOVXM -2172
    ; CHECK-NEXT: $eh0 = LDA_dms_lda_idx killed $p0, killed $dj0
    ; CHECK-NEXT: $p0 = MOV_alu_mv_mv_mv_scl $sp
    ; CHECK-NEXT: $dj0 = MOVXM -2240
    ; CHECK-NEXT: VST_dmx_sts_x_idx $x0, $p0, killed $dj0
    ; CHECK-NEXT: $dj0 = MOVXM -2176
    ; CHECK-NEXT: ST_dms_sts_idx $el0, $p0, killed $dj0
    ; CHECK-NEXT: $dj0 = MOVXM -2172
    ; CHECK-NEXT: ST_dms_sts_idx $eh0, killed $p0, killed $dj0
    renamable $p0 = PseudoFI %stack.0, implicit $sp
    ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    $ex0 = VLDA_EX_SPILL %stack.0, implicit $sp
    VST_EX_SPILL $ex0, %stack.0, implicit $sp
    ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
...

---
name:            test_exponent_bigstack
alignment:       16
frameInfo:
  adjustsStack:    true
stack:
  - { id: 0, name: '', type: default, offset: 0, size: 2200, alignment: 16 }
  - { id: 1, name: '', type: spill-slot, offset: 0, size: 8, alignment: 8 }
body:             |
  bb.0 (align 16):
    ; CHECK-LABEL: name: test_exponent_bigstack
    ; CHECK: frame-setup PADDXM_pstm_sp_imm 2240, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $p0 = MOV_alu_mv_mv_mv_scl $sp
    ; CHECK-NEXT: $m0 = MOVXM -2240
    ; CHECK-NEXT: $p0 = PADD_mod_pseudo $p0, killed $m0
    ; CHECK-NEXT: $p0 = MOV_alu_mv_mv_mv_scl $sp
    ; CHECK-NEXT: $dj0 = MOVXM -2240
    ; CHECK-NEXT: $el0 = LDA_dms_lda_idx $p0, killed $dj0
    ; CHECK-NEXT: $dj0 = MOVXM -2236
    ; CHECK-NEXT: $eh0 = LDA_dms_lda_idx killed $p0, killed $dj0
    ; CHECK-NEXT: $p0 = MOV_alu_mv_mv_mv_scl $sp
    ; CHECK-NEXT: $dj0 = MOVXM -2240
    ; CHECK-NEXT: ST_dms_sts_idx $el0, $p0, killed $dj0
    ; CHECK-NEXT: $dj0 = MOVXM -2236
    ; CHECK-NEXT: ST_dms_sts_idx $eh0, killed $p0, killed $dj0
    renamable $p0 = PseudoFI %stack.0, implicit $sp
    ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    $e0 = VLDA_E_SPILL %stack.0, implicit $sp
    VST_E_SPILL $e0, %stack.0, implicit $sp
    ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
...
