; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -O2 -mtriple=aie2p --issue-limit=1 %s -o - | FileCheck %s --check-prefix=AIE2P

; 256-bit vectors
define i64 @extract_v4i64(<4 x i64> inreg %v) nounwind {
; AIE2P-LABEL: extract_v4i64:
; AIE2P:       // %bb.0:
; AIE2P-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; AIE2P-NEXT:    nopx // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    vmov x0, bmll0 // Delay Slot 3
; AIE2P-NEXT:    vextract.64 r1:r0, x0, #3, vaddsign1 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
  %1 = extractelement <4 x i64> %v, i32 3
  ret i64 %1
}

define i64 @extract_v4i64_dyn(<4 x i64> inreg %v, i32 %idx) nounwind {
; AIE2P-LABEL: extract_v4i64_dyn:
; AIE2P:       // %bb.0:
; AIE2P-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; AIE2P-NEXT:    nopx // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    vmov x0, bmll0 // Delay Slot 3
; AIE2P-NEXT:    vextract.64 r1:r0, x0, r2, vaddsign1 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
  %1 = extractelement <4 x i64> %v, i32 %idx
  ret i64 %1
}

; 512-bit vectors
define i64 @extract_v8i64(<8 x i64> inreg %v) nounwind {
; AIE2P-LABEL: extract_v8i64:
; AIE2P:       // %bb.0:
; AIE2P-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; AIE2P-NEXT:    nopx // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    vmov x0, bmll0 // Delay Slot 3
; AIE2P-NEXT:    vextract.64 r1:r0, x0, #7, vaddsign1 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
  %1 = extractelement <8 x i64> %v, i32 7
  ret i64 %1
}

define i64 @extract_v8i64_dyn(<8 x i64> inreg %v, i32 %idx) nounwind {
; AIE2P-LABEL: extract_v8i64_dyn:
; AIE2P:       // %bb.0:
; AIE2P-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; AIE2P-NEXT:    nopx // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    vmov x0, bmll0 // Delay Slot 3
; AIE2P-NEXT:    vextract.64 r1:r0, x0, r2, vaddsign1 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
  %1 = extractelement <8 x i64> %v, i32 %idx
  ret i64 %1
}

; 1024-bit vectors
define i64 @extract_v16i64(<16 x i64> inreg %v) nounwind {
; AIE2P-LABEL: extract_v16i64:
; AIE2P:       // %bb.0:
; AIE2P-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; AIE2P-NEXT:    nopx // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    vmov x0, bmll0 // Delay Slot 3
; AIE2P-NEXT:    vextract.64 r1:r0, x0, #7, vaddsign1 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
  %1 = extractelement <16 x i64> %v, i32 7
  ret i64 %1
}

define i64 @extract_v16i64_dyn(<16 x i64> inreg %v, i32 %idx) nounwind {
; AIE2P-LABEL: extract_v16i64_dyn:
; AIE2P:       // %bb.0:
; AIE2P-NEXT:    mova r0, #8; movx r1, #0; nopm
; AIE2P-NEXT:    vmov x0, bmlh0
; AIE2P-NEXT:    vmov x2, bmll0
; AIE2P-NEXT:    lt r27, r2, r0
; AIE2P-NEXT:    add r16, r27, #-1
; AIE2P-NEXT:    ret lr
; AIE2P-NEXT:    sel.nez r0, r1, r0, r27 // Delay Slot 5
; AIE2P-NEXT:    sub r0, r2, r0 // Delay Slot 4
; AIE2P-NEXT:    vsel.32 x0, x2, x0, r16 // Delay Slot 3
; AIE2P-NEXT:    vextract.64 r1:r0, x0, r0, vaddsign1 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
  %1 = extractelement <16 x i64> %v, i32 %idx
  ret i64 %1
}

; 2048-bit vectors
define i32 @extract_v64i32(<64 x i32> inreg %v) nounwind {
; AIE2P-LABEL: extract_v64i32:
; AIE2P:       // %bb.0:
; AIE2P-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; AIE2P-NEXT:    nopx // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    vmov x0, bmll0 // Delay Slot 3
; AIE2P-NEXT:    vextract.32 r0, x0, #7, vaddsign1 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
  %1 = extractelement <64 x i32> %v, i32 7
  ret i32 %1
}

define i32 @extract_v64i32_dyn(<64 x i32> inreg %v, i32 %idx) nounwind {
; AIE2P-LABEL: extract_v64i32_dyn:
; AIE2P:       // %bb.0:
; AIE2P-NEXT:    mova r0, #48; nopb ; movx r2, #32; nopm
; AIE2P-NEXT:    vmov x0, bmhh0
; AIE2P-NEXT:    vmov x2, bmlh0
; AIE2P-NEXT:    vmov x4, bmll0
; AIE2P-NEXT:    vmov x6, bmhl0
; AIE2P-NEXT:    lt r27, r1, r0
; AIE2P-NEXT:    add r16, r27, #-1
; AIE2P-NEXT:    sel.nez r0, r2, r0, r27
; AIE2P-NEXT:    lt r27, r1, r2
; AIE2P-NEXT:    mova r3, #0; movx r2, #16
; AIE2P-NEXT:    add r17, r27, #-1
; AIE2P-NEXT:    sel.nez r0, r2, r0, r27
; AIE2P-NEXT:    lt r27, r1, r2
; AIE2P-NEXT:    vsel.32 x0, x6, x0, r16
; AIE2P-NEXT:    add r18, r27, #-1
; AIE2P-NEXT:    sel.nez r0, r3, r0, r27
; AIE2P-NEXT:    ret lr
; AIE2P-NEXT:    vsel.32 x0, x2, x0, r17 // Delay Slot 5
; AIE2P-NEXT:    sub r0, r1, r0 // Delay Slot 4
; AIE2P-NEXT:    vsel.32 x0, x4, x0, r18 // Delay Slot 3
; AIE2P-NEXT:    vextract.32 r0, x0, r0, vaddsign1 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
  %1 = extractelement <64 x i32> %v, i32 %idx
  ret i32 %1
}

define i64 @extract_v32i64(<32 x i64> inreg %v) nounwind {
; AIE2P-LABEL: extract_v32i64:
; AIE2P:       // %bb.0:
; AIE2P-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; AIE2P-NEXT:    nopx // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    vmov x0, bmll0 // Delay Slot 3
; AIE2P-NEXT:    vextract.64 r1:r0, x0, #7, vaddsign1 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
  %1 = extractelement <32 x i64> %v, i32 7
  ret i64 %1
}

define i64 @extract_v32i64_dyn(<32 x i64> inreg %v, i32 %idx) nounwind {
; AIE2P-LABEL: extract_v32i64_dyn:
; AIE2P:       // %bb.0:
; AIE2P-NEXT:    mova r0, #24; nopb ; movx r1, #16; nopm
; AIE2P-NEXT:    vmov x0, bmhh0
; AIE2P-NEXT:    vmov x2, bmlh0
; AIE2P-NEXT:    vmov x4, bmll0
; AIE2P-NEXT:    vmov x6, bmhl0
; AIE2P-NEXT:    lt r27, r2, r0
; AIE2P-NEXT:    add r16, r27, #-1
; AIE2P-NEXT:    sel.nez r0, r1, r0, r27
; AIE2P-NEXT:    lt r27, r2, r1
; AIE2P-NEXT:    mova r3, #0; movx r1, #8
; AIE2P-NEXT:    add r17, r27, #-1
; AIE2P-NEXT:    sel.nez r0, r1, r0, r27
; AIE2P-NEXT:    lt r27, r2, r1
; AIE2P-NEXT:    vsel.32 x0, x6, x0, r16
; AIE2P-NEXT:    add r18, r27, #-1
; AIE2P-NEXT:    sel.nez r0, r3, r0, r27
; AIE2P-NEXT:    ret lr
; AIE2P-NEXT:    vsel.32 x0, x2, x0, r17 // Delay Slot 5
; AIE2P-NEXT:    sub r0, r2, r0 // Delay Slot 4
; AIE2P-NEXT:    vsel.32 x0, x4, x0, r18 // Delay Slot 3
; AIE2P-NEXT:    vextract.64 r1:r0, x0, r0, vaddsign1 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
  %1 = extractelement <32 x i64> %v, i32 %idx
  ret i64 %1
}
