; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc < %s -verify-machineinstrs -mtriple=aie2p | FileCheck %s

%struct.v64bfp16ebs8 = type <{ <64 x i8>, <8 x i8> }>
%struct.v64bfp16ebs16 = type <{ <64 x i8>, <8 x i8> }>
%struct.v128bfp16ebs8 = type <{ <64 x i8>, <64 x i8>, <8 x i8>, <8 x i8> }>
%struct.v128bfp16ebs16 = type <{ <64 x i8>, <64 x i8>, <8 x i8>, <8 x i8> }>


define dso_local void @_Z17test_fifo_ld_fillRPDv64_DB8_R12fifo_state_t(ptr nocapture nonnull align 4 dereferenceable(4) %p, ptr nocapture nonnull align 64 dereferenceable(256) %s) local_unnamed_addr #2 {
; CHECK-LABEL: _Z17test_fifo_ld_fillRPDv64_DB8_R12fifo_state_t:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    lda p0, [p0, #0]; mov dj0, #128
; CHECK-NEXT:    lda r24, [p1, dj0]; nopx
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vlda lfh0, [p1, #64]; movs p2, p0
; CHECK-NEXT:    vlda lfl0, [p1, #0]
; CHECK-NEXT:    vldb.fill.512 [p0, lf0, r24]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    st r24, [p1, dj0] // Delay Slot 5
; CHECK-NEXT:    vst lfh0, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst lfl0, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p0, [p2, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %pos1.i = getelementptr inbounds i8, ptr %s, i20 128
  %0 = load ptr, ptr %p, align 4, !tbaa !2
  %1 = load <32 x i32>, ptr %s, align 64, !tbaa !6
  %2 = load i32, ptr %pos1.i, align 64, !tbaa !7
  %3 = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill(ptr %0, <32 x i32> %1, i32 %2)
  %4 = extractvalue { ptr, <32 x i32>, i32 } %3, 0
  %5 = extractvalue { ptr, <32 x i32>, i32 } %3, 1
  %6 = extractvalue { ptr, <32 x i32>, i32 } %3, 2
  store <32 x i32> %5, ptr %s, align 128
  store i32 %6, ptr %pos1.i, align 64
  store ptr %4, ptr %p, align 4
  ret void
}

define dso_local noundef <64 x i8> @_Z16test_fifo_ld_popRPDv64_DB8_R12fifo_state_t(ptr nocapture nonnull align 4 dereferenceable(4) %p, ptr nocapture nonnull align 64 dereferenceable(256) %s) local_unnamed_addr #2 {
; CHECK-LABEL: _Z16test_fifo_ld_popRPDv64_DB8_R12fifo_state_t:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    lda p0, [p0, #0]; mov dj0, #128
; CHECK-NEXT:    lda r24, [p1, dj0]; nopx
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vlda lfh0, [p1, #64]; movs p2, p0
; CHECK-NEXT:    vlda lfl0, [p1, #0]
; CHECK-NEXT:    vldb.pop.512 x0, [p0, lf0, r24]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    st r24, [p1, dj0] // Delay Slot 5
; CHECK-NEXT:    vst lfh0, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst lfl0, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p0, [p2, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %pos1.i = getelementptr inbounds i8, ptr %s, i20 128
  %0 = load ptr, ptr %p, align 4, !tbaa !2
  %1 = load <32 x i32>, ptr %s, align 64, !tbaa !6
  %2 = load i32, ptr %pos1.i, align 64, !tbaa !7
  %3 = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.unaligned(ptr %0, <32 x i32> %1, i32 %2)
  %4 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } %3, 1
  %5 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } %3, 2
  %6 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } %3, 3
  store <32 x i32> %5, ptr %s, align 128
  store i32 %6, ptr %pos1.i, align 64
  store ptr %4, ptr %p, align 4
  %7 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } %3, 0
  ret <64 x i8> %7
}

define dso_local noundef <64 x i8> @_Z24test_fifo_ld_pop_1d_byteRPDv64_DB8_R12fifo_state_ti(ptr nocapture nonnull align 4 dereferenceable(4) %p, ptr nocapture nonnull align 64 dereferenceable(256) %s, i32 noundef %off) local_unnamed_addr #2 {
; CHECK-LABEL: _Z24test_fifo_ld_pop_1d_byteRPDv64_DB8_R12fifo_state_ti:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    lda p0, [p0, #0]; mov dj0, #128
; CHECK-NEXT:    lda r24, [p1, dj0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vlda lfh0, [p1, #64]; movs p2, p0
; CHECK-NEXT:    vlda lfl0, [p1, #0]; mov m0, r0
; CHECK-NEXT:    vldb.pop.512 x0, [p0, lf0, r24, m0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    st r24, [p1, dj0] // Delay Slot 5
; CHECK-NEXT:    vst lfh0, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst lfl0, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p0, [p2, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %pos1.i = getelementptr inbounds i8, ptr %s, i20 128
  %0 = load ptr, ptr %p, align 4, !tbaa !2
  %1 = load <32 x i32>, ptr %s, align 64, !tbaa !6
  %2 = load i32, ptr %pos1.i, align 64, !tbaa !7
  %3 = trunc i32 %off to i20
  %4 = tail call { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.1d.unaligned(ptr %0, <32 x i32> %1, i32 %2, i20 %3)
  %5 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } %4, 1
  %6 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } %4, 2
  %7 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } %4, 3
  store <32 x i32> %6, ptr %s, align 128
  store i32 %7, ptr %pos1.i, align 64
  store ptr %5, ptr %p, align 4
  %8 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32 } %4, 0
  ret <64 x i8> %8
}

define dso_local noundef <64 x i8> @_Z24test_fifo_ld_pop_2d_byteRPDv64_DB8_R12fifo_state_tiiRii(ptr nocapture nonnull align 4 dereferenceable(4) %p, ptr nocapture nonnull align 64 dereferenceable(256) %s, i32 noundef %off, i32 noundef %size1, ptr nocapture nonnull align 4 dereferenceable(4) %count1, i32 noundef %inc1) local_unnamed_addr #2 {
; CHECK-LABEL: _Z24test_fifo_ld_pop_2d_byteRPDv64_DB8_R12fifo_state_tiiRii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    lda p0, [p0, #0]; nopb ; nopx
; CHECK-NEXT:    lda dc0, [p2, #0]; mov dj1, #128
; CHECK-NEXT:    lda r24, [p1, dj1]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    movs p3, p0
; CHECK-NEXT:    vlda lfh0, [p1, #64]; mov m0, r0
; CHECK-NEXT:    vlda lfl0, [p1, #0]; movs dn0, r1; mov dj0, r2
; CHECK-NEXT:    vldb.pop.512.2d x0, [p0, lf0, r24, d0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    st dc0, [p2, #0]; ret lr
; CHECK-NEXT:    st r24, [p1, dj1] // Delay Slot 5
; CHECK-NEXT:    vst lfh0, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst lfl0, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p0, [p3, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %pos1.i = getelementptr inbounds i8, ptr %s, i20 128
  %0 = load ptr, ptr %p, align 4, !tbaa !2
  %1 = load <32 x i32>, ptr %s, align 64, !tbaa !6
  %2 = load i32, ptr %pos1.i, align 64, !tbaa !7
  %3 = trunc i32 %off to i20
  %4 = trunc i32 %size1 to i20
  %5 = load i32, ptr %count1, align 4, !tbaa !7
  %6 = trunc i32 %5 to i20
  %7 = trunc i32 %inc1 to i20
  %8 = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.ld.pop.2d.unaligned(ptr %0, <32 x i32> %1, i32 %2, i20 %3, i20 %4, i20 %6, i20 %7)
  %9 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } %8, 1
  %10 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } %8, 2
  %11 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } %8, 3
  %12 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } %8, 4
  %13 = zext i20 %12 to i32
  store i32 %13, ptr %count1, align 4
  store <32 x i32> %10, ptr %s, align 128
  store i32 %11, ptr %pos1.i, align 64
  store ptr %9, ptr %p, align 4
  %14 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20 } %8, 0
  ret <64 x i8> %14
}

define dso_local noundef <64 x i8> @_Z24test_fifo_ld_pop_3d_byteRPDv64_DB8_R12fifo_state_tiiRiiiS5_i(ptr nocapture nonnull align 4 dereferenceable(4) %p, ptr nocapture nonnull align 64 dereferenceable(256) %s, i32 noundef %off, i32 noundef %size1, ptr nocapture nonnull align 4 dereferenceable(4) %count1, i32 noundef %inc1, i32 noundef %size2, ptr nocapture nonnull align 4 dereferenceable(4) %count2, i32 noundef %inc2) local_unnamed_addr #2 {
; CHECK-LABEL: _Z24test_fifo_ld_pop_3d_byteRPDv64_DB8_R12fifo_state_tiiRiiiS5_i:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    lda p0, [p0, #0]; nopb ; nopxm
; CHECK-NEXT:    lda dc0, [p2, #0]
; CHECK-NEXT:    lda dc4, [p3, #0]; mov dj1, #128
; CHECK-NEXT:    lda r24, [p1, dj1]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    movs p4, p0
; CHECK-NEXT:    mov m0, r0
; CHECK-NEXT:    vlda lfh0, [p1, #64]; movs dn0, r1; mov dj0, r2
; CHECK-NEXT:    vlda lfl0, [p1, #0]; movs dn4, r3; mov dj4, r4
; CHECK-NEXT:    vldb.pop.512.3d x0, [p0, lf0, r24, d0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    st dc0, [p2, #0]
; CHECK-NEXT:    st dc4, [p3, #0]; ret lr
; CHECK-NEXT:    st r24, [p1, dj1] // Delay Slot 5
; CHECK-NEXT:    vst lfh0, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst lfl0, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p0, [p4, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %pos1.i = getelementptr inbounds i8, ptr %s, i20 128
  %0 = load ptr, ptr %p, align 4, !tbaa !2
  %1 = load <32 x i32>, ptr %s, align 64, !tbaa !6
  %2 = load i32, ptr %pos1.i, align 64, !tbaa !7
  %3 = trunc i32 %off to i20
  %4 = trunc i32 %size1 to i20
  %5 = load i32, ptr %count1, align 4, !tbaa !7
  %6 = trunc i32 %5 to i20
  %7 = trunc i32 %inc1 to i20
  %8 = trunc i32 %size2 to i20
  %9 = load i32, ptr %count2, align 4, !tbaa !7
  %10 = trunc i32 %9 to i20
  %11 = trunc i32 %inc2 to i20
  %12 = tail call { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.ld.pop.3d.unaligned(ptr %0, <32 x i32> %1, i32 %2, i20 %3, i20 %4, i20 %6, i20 %7, i20 %8, i20 %10, i20 %11)
  %13 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } %12, 1
  %14 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } %12, 2
  %15 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } %12, 3
  %16 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } %12, 4
  %17 = zext i20 %16 to i32
  %18 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } %12, 5
  %19 = zext i20 %18 to i32
  store i32 %17, ptr %count1, align 4
  store i32 %19, ptr %count2, align 4
  store <32 x i32> %14, ptr %s, align 128
  store i32 %15, ptr %pos1.i, align 64
  store ptr %13, ptr %p, align 4
  %20 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } %12, 0
  ret <64 x i8> %20
}


define dso_local %struct.v64bfp16ebs8 @_Z16test_fifo_ld_popRP22v64bfp16ebs8_unalignedR12fifo_state_t(ptr nocapture nonnull align 4 dereferenceable(4) %p, ptr nocapture nonnull align 64 dereferenceable(256) %s) local_unnamed_addr #2 {
; CHECK-LABEL: _Z16test_fifo_ld_popRP22v64bfp16ebs8_unalignedR12fifo_state_t:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    lda p0, [p0, #0]; mov dj0, #128
; CHECK-NEXT:    lda r24, [p1, dj0]; nopx
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vlda lfh0, [p1, #64]; movs p2, p0
; CHECK-NEXT:    vlda lfl0, [p1, #0]
; CHECK-NEXT:    vldb.pop.576 ex0, [p0, lf0, r24]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    st r24, [p1, dj0] // Delay Slot 5
; CHECK-NEXT:    vst lfh0, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst lfl0, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p0, [p2, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %pos1.i = getelementptr inbounds i8, ptr %s, i20 128
  %0 = load ptr, ptr %p, align 4, !tbaa !2
  %1 = load <32 x i32>, ptr %s, align 64, !tbaa !6
  %2 = load i32, ptr %pos1.i, align 64, !tbaa !7
  %3 = tail call { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.bfp16(ptr %0, <32 x i32> %1, i32 %2)
  %4 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %3, 0
  %5 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %3, 1
  %6 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %3, 2
  %7 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %3, 3
  %8 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %3, 4
  store <32 x i32> %5, ptr %s, align 128
  store i32 %6, ptr %pos1.i, align 64
  store ptr %4, ptr %p, align 4
  %.fca.0.insert.i = insertvalue %struct.v64bfp16ebs8 poison, <64 x i8> %7, 0
  %.fca.1.insert.i = insertvalue %struct.v64bfp16ebs8 %.fca.0.insert.i, <8 x i8> %8, 1
  ret %struct.v64bfp16ebs8 %.fca.1.insert.i
}

define dso_local %struct.v64bfp16ebs8 @_Z24test_fifo_ld_pop_1d_byteRP22v64bfp16ebs8_unalignedR12fifo_state_ti(ptr nocapture nonnull align 4 dereferenceable(4) %p, ptr nocapture nonnull align 64 dereferenceable(256) %s, i32 noundef %off) local_unnamed_addr #2 {
; CHECK-LABEL: _Z24test_fifo_ld_pop_1d_byteRP22v64bfp16ebs8_unalignedR12fifo_state_ti:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    lda p0, [p0, #0]; mov dj0, #128
; CHECK-NEXT:    lda r24, [p1, dj0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vlda lfh0, [p1, #64]; movs p2, p0
; CHECK-NEXT:    vlda lfl0, [p1, #0]; mov m0, r0
; CHECK-NEXT:    vldb.pop.576 ex0, [p0, lf0, r24, m0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    st r24, [p1, dj0] // Delay Slot 5
; CHECK-NEXT:    vst lfh0, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst lfl0, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p0, [p2, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %pos1.i = getelementptr inbounds i8, ptr %s, i20 128
  %0 = load ptr, ptr %p, align 4, !tbaa !2
  %1 = load <32 x i32>, ptr %s, align 64, !tbaa !6
  %2 = load i32, ptr %pos1.i, align 64, !tbaa !7
  %3 = trunc i32 %off to i20
  %4 = tail call { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.1d.bfp16(ptr %0, <32 x i32> %1, i32 %2, i20 %3)
  %5 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %4, 0
  %6 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %4, 1
  %7 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %4, 2
  %8 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %4, 3
  %9 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %4, 4
  store <32 x i32> %6, ptr %s, align 128
  store i32 %7, ptr %pos1.i, align 64
  store ptr %5, ptr %p, align 4
  %.fca.0.insert.i = insertvalue %struct.v64bfp16ebs8 poison, <64 x i8> %8, 0
  %.fca.1.insert.i = insertvalue %struct.v64bfp16ebs8 %.fca.0.insert.i, <8 x i8> %9, 1
  ret %struct.v64bfp16ebs8 %.fca.1.insert.i
}

define dso_local %struct.v64bfp16ebs8 @_Z24test_fifo_ld_pop_2d_byteRP22v64bfp16ebs8_unalignedR12fifo_state_tiiRii(ptr nocapture nonnull align 4 dereferenceable(4) %p, ptr nocapture nonnull align 64 dereferenceable(256) %s, i32 noundef %off, i32 noundef %size1, ptr nocapture nonnull align 4 dereferenceable(4) %count1, i32 noundef %inc1) local_unnamed_addr #2 {
; CHECK-LABEL: _Z24test_fifo_ld_pop_2d_byteRP22v64bfp16ebs8_unalignedR12fifo_state_tiiRii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    lda p0, [p0, #0]; nopb ; nopx
; CHECK-NEXT:    lda dc0, [p2, #0]; mov dj1, #128
; CHECK-NEXT:    lda r24, [p1, dj1]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    movs p3, p0
; CHECK-NEXT:    vlda lfh0, [p1, #64]; mov m0, r0
; CHECK-NEXT:    vlda lfl0, [p1, #0]; movs dn0, r1; mov dj0, r2
; CHECK-NEXT:    vldb.pop.576.2d ex0, [p0, lf0, r24, d0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    st dc0, [p2, #0]; ret lr
; CHECK-NEXT:    st r24, [p1, dj1] // Delay Slot 5
; CHECK-NEXT:    vst lfh0, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst lfl0, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p0, [p3, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %pos1.i = getelementptr inbounds i8, ptr %s, i20 128
  %0 = load ptr, ptr %p, align 4, !tbaa !2
  %1 = load <32 x i32>, ptr %s, align 64, !tbaa !6
  %2 = load i32, ptr %pos1.i, align 64, !tbaa !7
  %3 = trunc i32 %off to i20
  %4 = trunc i32 %size1 to i20
  %5 = load i32, ptr %count1, align 4, !tbaa !7
  %6 = trunc i32 %5 to i20
  %7 = trunc i32 %inc1 to i20
  %8 = tail call { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.2d.bfp16(ptr %0, <32 x i32> %1, i32 %2, i20 %3, i20 %4, i20 %6, i20 %7)
  %9 = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } %8, 0
  %10 = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } %8, 1
  %11 = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } %8, 2
  %12 = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } %8, 4
  %13 = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } %8, 5
  %14 = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } %8, 3
  %15 = zext i20 %14 to i32
  store i32 %15, ptr %count1, align 4
  store <32 x i32> %10, ptr %s, align 128
  store i32 %11, ptr %pos1.i, align 64
  store ptr %9, ptr %p, align 4
  %.fca.0.insert.i = insertvalue %struct.v64bfp16ebs8 poison, <64 x i8> %12, 0
  %.fca.1.insert.i = insertvalue %struct.v64bfp16ebs8 %.fca.0.insert.i, <8 x i8> %13, 1
  ret %struct.v64bfp16ebs8 %.fca.1.insert.i
}

define dso_local %struct.v64bfp16ebs8 @_Z24test_fifo_ld_pop_3d_byteRP22v64bfp16ebs8_unalignedR12fifo_state_tiiRiiiS4_i(ptr nocapture nonnull align 4 dereferenceable(4) %p, ptr nocapture nonnull align 64 dereferenceable(256) %s, i32 noundef %off, i32 noundef %size1, ptr nocapture nonnull align 4 dereferenceable(4) %count1, i32 noundef %inc1, i32 noundef %size2, ptr nocapture nonnull align 4 dereferenceable(4) %count2, i32 noundef %inc2) local_unnamed_addr #2 {
; CHECK-LABEL: _Z24test_fifo_ld_pop_3d_byteRP22v64bfp16ebs8_unalignedR12fifo_state_tiiRiiiS4_i:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    lda p0, [p0, #0]; nopb ; nopxm
; CHECK-NEXT:    lda dc0, [p2, #0]
; CHECK-NEXT:    lda dc4, [p3, #0]; mov dj1, #128
; CHECK-NEXT:    lda r24, [p1, dj1]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    movs p4, p0
; CHECK-NEXT:    mov m0, r0
; CHECK-NEXT:    vlda lfh0, [p1, #64]; movs dn0, r1; mov dj0, r2
; CHECK-NEXT:    vlda lfl0, [p1, #0]; movs dn4, r3; mov dj4, r4
; CHECK-NEXT:    vldb.pop.576.3d ex0, [p0, lf0, r24, d0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    st dc0, [p2, #0]
; CHECK-NEXT:    st dc4, [p3, #0]; ret lr
; CHECK-NEXT:    st r24, [p1, dj1] // Delay Slot 5
; CHECK-NEXT:    vst lfh0, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst lfl0, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p0, [p4, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %pos1.i = getelementptr inbounds i8, ptr %s, i20 128
  %0 = load ptr, ptr %p, align 4, !tbaa !2
  %1 = load <32 x i32>, ptr %s, align 64, !tbaa !6
  %2 = load i32, ptr %pos1.i, align 64, !tbaa !7
  %3 = trunc i32 %off to i20
  %4 = trunc i32 %size1 to i20
  %5 = load i32, ptr %count1, align 4, !tbaa !7
  %6 = trunc i32 %5 to i20
  %7 = trunc i32 %inc1 to i20
  %8 = trunc i32 %size2 to i20
  %9 = load i32, ptr %count2, align 4, !tbaa !7
  %10 = trunc i32 %9 to i20
  %11 = trunc i32 %inc2 to i20
  %12 = tail call { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.3d.bfp16(ptr %0, <32 x i32> %1, i32 %2, i20 %3, i20 %4, i20 %6, i20 %7, i20 %8, i20 %10, i20 %11)
  %13 = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %12, 0
  %14 = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %12, 1
  %15 = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %12, 2
  %16 = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %12, 5
  %17 = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %12, 6
  %18 = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %12, 3
  %19 = zext i20 %18 to i32
  %20 = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %12, 4
  %21 = zext i20 %20 to i32
  store i32 %19, ptr %count1, align 4
  store i32 %21, ptr %count2, align 4
  store <32 x i32> %14, ptr %s, align 128
  store i32 %15, ptr %pos1.i, align 64
  store ptr %13, ptr %p, align 4
  %.fca.0.insert.i = insertvalue %struct.v64bfp16ebs8 poison, <64 x i8> %16, 0
  %.fca.1.insert.i = insertvalue %struct.v64bfp16ebs8 %.fca.0.insert.i, <8 x i8> %17, 1
  ret %struct.v64bfp16ebs8 %.fca.1.insert.i
}


define dso_local %struct.v64bfp16ebs16 @_Z16test_fifo_ld_popRP23v64bfp16ebs16_unalignedR12fifo_state_t(ptr nocapture nonnull align 4 dereferenceable(4) %p, ptr nocapture nonnull align 64 dereferenceable(256) %s) local_unnamed_addr #2 {
; CHECK-LABEL: _Z16test_fifo_ld_popRP23v64bfp16ebs16_unalignedR12fifo_state_t:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    lda p0, [p0, #0]; mov dj0, #128
; CHECK-NEXT:    lda r24, [p1, dj0]; nopx
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vlda lfh0, [p1, #64]; movs p2, p0
; CHECK-NEXT:    vlda lfl0, [p1, #0]
; CHECK-NEXT:    vldb.pop.544 ex0, [p0, lf0, r24]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    st r24, [p1, dj0] // Delay Slot 5
; CHECK-NEXT:    vst lfh0, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst lfl0, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p0, [p2, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %pos1.i = getelementptr inbounds i8, ptr %s, i20 128
  %0 = load ptr, ptr %p, align 4, !tbaa !2
  %1 = load <32 x i32>, ptr %s, align 64, !tbaa !6
  %2 = load i32, ptr %pos1.i, align 64, !tbaa !7
  %3 = tail call { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.544.bfp16(ptr %0, <32 x i32> %1, i32 %2)
  %4 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %3, 0
  %5 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %3, 1
  %6 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %3, 2
  %7 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %3, 3
  %8 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %3, 4
  store <32 x i32> %5, ptr %s, align 128
  store i32 %6, ptr %pos1.i, align 64
  store ptr %4, ptr %p, align 4
  %.fca.0.insert.i = insertvalue %struct.v64bfp16ebs16 poison, <64 x i8> %7, 0
  %.fca.1.insert.i = insertvalue %struct.v64bfp16ebs16 %.fca.0.insert.i, <8 x i8> %8, 1
  ret %struct.v64bfp16ebs16 %.fca.1.insert.i
}

define dso_local %struct.v64bfp16ebs16 @_Z24test_fifo_ld_pop_1d_byteRP23v64bfp16ebs16_unalignedR12fifo_state_ti(ptr nocapture nonnull align 4 dereferenceable(4) %p, ptr nocapture nonnull align 64 dereferenceable(256) %s, i32 noundef %off) local_unnamed_addr #2 {
; CHECK-LABEL: _Z24test_fifo_ld_pop_1d_byteRP23v64bfp16ebs16_unalignedR12fifo_state_ti:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    lda p0, [p0, #0]; mov dj0, #128
; CHECK-NEXT:    lda r24, [p1, dj0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vlda lfh0, [p1, #64]; movs p2, p0
; CHECK-NEXT:    vlda lfl0, [p1, #0]; mov m0, r0
; CHECK-NEXT:    vldb.pop.544 ex0, [p0, lf0, r24, m0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    st r24, [p1, dj0] // Delay Slot 5
; CHECK-NEXT:    vst lfh0, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst lfl0, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p0, [p2, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %pos1.i = getelementptr inbounds i8, ptr %s, i20 128
  %0 = load ptr, ptr %p, align 4, !tbaa !2
  %1 = load <32 x i32>, ptr %s, align 64, !tbaa !6
  %2 = load i32, ptr %pos1.i, align 64, !tbaa !7
  %3 = trunc i32 %off to i20
  %4 = tail call { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.544.1d.bfp16(ptr %0, <32 x i32> %1, i32 %2, i20 %3)
  %5 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %4, 0
  %6 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %4, 1
  %7 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %4, 2
  %8 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %4, 3
  %9 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %4, 4
  store <32 x i32> %6, ptr %s, align 128
  store i32 %7, ptr %pos1.i, align 64
  store ptr %5, ptr %p, align 4
  %.fca.0.insert.i = insertvalue %struct.v64bfp16ebs16 poison, <64 x i8> %8, 0
  %.fca.1.insert.i = insertvalue %struct.v64bfp16ebs16 %.fca.0.insert.i, <8 x i8> %9, 1
  ret %struct.v64bfp16ebs16 %.fca.1.insert.i
}

define dso_local %struct.v64bfp16ebs16 @_Z24test_fifo_ld_pop_2d_byteRP23v64bfp16ebs16_unalignedR12fifo_state_tiiRii(ptr nocapture nonnull align 4 dereferenceable(4) %p, ptr nocapture nonnull align 64 dereferenceable(256) %s, i32 noundef %off, i32 noundef %size1, ptr nocapture nonnull align 4 dereferenceable(4) %count1, i32 noundef %inc1) local_unnamed_addr #2 {
; CHECK-LABEL: _Z24test_fifo_ld_pop_2d_byteRP23v64bfp16ebs16_unalignedR12fifo_state_tiiRii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    lda p0, [p0, #0]; nopb ; nopx
; CHECK-NEXT:    lda dc0, [p2, #0]; mov dj1, #128
; CHECK-NEXT:    lda r24, [p1, dj1]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    movs p3, p0
; CHECK-NEXT:    vlda lfh0, [p1, #64]; mov m0, r0
; CHECK-NEXT:    vlda lfl0, [p1, #0]; movs dn0, r1; mov dj0, r2
; CHECK-NEXT:    vldb.pop.544.2d ex0, [p0, lf0, r24, d0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    st dc0, [p2, #0]; ret lr
; CHECK-NEXT:    st r24, [p1, dj1] // Delay Slot 5
; CHECK-NEXT:    vst lfh0, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst lfl0, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p0, [p3, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %pos1.i = getelementptr inbounds i8, ptr %s, i20 128
  %0 = load ptr, ptr %p, align 4, !tbaa !2
  %1 = load <32 x i32>, ptr %s, align 64, !tbaa !6
  %2 = load i32, ptr %pos1.i, align 64, !tbaa !7
  %3 = trunc i32 %off to i20
  %4 = trunc i32 %size1 to i20
  %5 = load i32, ptr %count1, align 4, !tbaa !7
  %6 = trunc i32 %5 to i20
  %7 = trunc i32 %inc1 to i20
  %8 = tail call { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.544.2d.bfp16(ptr %0, <32 x i32> %1, i32 %2, i20 %3, i20 %4, i20 %6, i20 %7)
  %9 = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } %8, 0
  %10 = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } %8, 1
  %11 = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } %8, 2
  %12 = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } %8, 4
  %13 = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } %8, 5
  %14 = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } %8, 3
  %15 = zext i20 %14 to i32
  store i32 %15, ptr %count1, align 4
  store <32 x i32> %10, ptr %s, align 128
  store i32 %11, ptr %pos1.i, align 64
  store ptr %9, ptr %p, align 4
  %.fca.0.insert.i = insertvalue %struct.v64bfp16ebs16 poison, <64 x i8> %12, 0
  %.fca.1.insert.i = insertvalue %struct.v64bfp16ebs16 %.fca.0.insert.i, <8 x i8> %13, 1
  ret %struct.v64bfp16ebs16 %.fca.1.insert.i
}

define dso_local %struct.v64bfp16ebs16 @_Z24test_fifo_ld_pop_3d_byteRP23v64bfp16ebs16_unalignedR12fifo_state_tiiRiiiS4_i(ptr nocapture nonnull align 4 dereferenceable(4) %p, ptr nocapture nonnull align 64 dereferenceable(256) %s, i32 noundef %off, i32 noundef %size1, ptr nocapture nonnull align 4 dereferenceable(4) %count1, i32 noundef %inc1, i32 noundef %size2, ptr nocapture nonnull align 4 dereferenceable(4) %count2, i32 noundef %inc2) local_unnamed_addr #2 {
; CHECK-LABEL: _Z24test_fifo_ld_pop_3d_byteRP23v64bfp16ebs16_unalignedR12fifo_state_tiiRiiiS4_i:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    lda p0, [p0, #0]; nopb ; nopxm
; CHECK-NEXT:    lda dc0, [p2, #0]
; CHECK-NEXT:    lda dc4, [p3, #0]; mov dj1, #128
; CHECK-NEXT:    lda r24, [p1, dj1]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    movs p4, p0
; CHECK-NEXT:    mov m0, r0
; CHECK-NEXT:    vlda lfh0, [p1, #64]; movs dn0, r1; mov dj0, r2
; CHECK-NEXT:    vlda lfl0, [p1, #0]; movs dn4, r3; mov dj4, r4
; CHECK-NEXT:    vldb.pop.544.3d ex0, [p0, lf0, r24, d0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    st dc0, [p2, #0]
; CHECK-NEXT:    st dc4, [p3, #0]; ret lr
; CHECK-NEXT:    st r24, [p1, dj1] // Delay Slot 5
; CHECK-NEXT:    vst lfh0, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst lfl0, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p0, [p4, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %pos1.i = getelementptr inbounds i8, ptr %s, i20 128
  %0 = load ptr, ptr %p, align 4, !tbaa !2
  %1 = load <32 x i32>, ptr %s, align 64, !tbaa !6
  %2 = load i32, ptr %pos1.i, align 64, !tbaa !7
  %3 = trunc i32 %off to i20
  %4 = trunc i32 %size1 to i20
  %5 = load i32, ptr %count1, align 4, !tbaa !7
  %6 = trunc i32 %5 to i20
  %7 = trunc i32 %inc1 to i20
  %8 = trunc i32 %size2 to i20
  %9 = load i32, ptr %count2, align 4, !tbaa !7
  %10 = trunc i32 %9 to i20
  %11 = trunc i32 %inc2 to i20
  %12 = tail call { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.544.3d.bfp16(ptr %0, <32 x i32> %1, i32 %2, i20 %3, i20 %4, i20 %6, i20 %7, i20 %8, i20 %10, i20 %11)
  %13 = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %12, 0
  %14 = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %12, 1
  %15 = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %12, 2
  %16 = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %12, 5
  %17 = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %12, 6
  %18 = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %12, 3
  %19 = zext i20 %18 to i32
  %20 = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %12, 4
  %21 = zext i20 %20 to i32
  store i32 %19, ptr %count1, align 4
  store i32 %21, ptr %count2, align 4
  store <32 x i32> %14, ptr %s, align 128
  store i32 %15, ptr %pos1.i, align 64
  store ptr %13, ptr %p, align 4
  %.fca.0.insert.i = insertvalue %struct.v64bfp16ebs16 poison, <64 x i8> %16, 0
  %.fca.1.insert.i = insertvalue %struct.v64bfp16ebs16 %.fca.0.insert.i, <8 x i8> %17, 1
  ret %struct.v64bfp16ebs16 %.fca.1.insert.i
}

define dso_local noundef <64 x i8> @_Z17test_fifo_ld_popxRPDv64_hR12fifo_state_t(ptr nocapture nonnull align 4 dereferenceable(4) %p, ptr nocapture nonnull align 64 dereferenceable(256) %s) local_unnamed_addr #0 {
; CHECK-LABEL: _Z17test_fifo_ld_popxRPDv64_hR12fifo_state_t:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    lda p0, [p0, #0]; nopb ; nopx ; mov dj0, #128
; CHECK-NEXT:    lda r24, [p1, dj0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vlda lfh0, [p1, #64]
; CHECK-NEXT:    vlda lfl0, [p1, #0]; movs p2, p0
; CHECK-NEXT:    vlda lfe, [p1, #192]; movxm r30, #2015
; CHECK-NEXT:    vldb.popx.512 x0, [p0, lf0, r24]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    st r24, [p1, dj0]; ret lr
; CHECK-NEXT:    vst lfe, [p1, #192] // Delay Slot 5
; CHECK-NEXT:    vst lfh0, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst lfl0, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p0, [p2, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %pos1.i.i = getelementptr inbounds i8, ptr %s, i20 128
  %extra3.i.i = getelementptr inbounds i8, ptr %s, i20 192
  %0 = load ptr, ptr %p, align 4, !tbaa !2
  %1 = load <32 x i32>, ptr %s, align 64, !tbaa !6
  %2 = load i32, ptr %pos1.i.i, align 64, !tbaa !7
  %3 = load <16 x i32>, ptr %extra3.i.i, align 64, !tbaa !6
  %4 = tail call { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx(ptr %0, <32 x i32> %1, i32 %2, <16 x i32> %3, i32 2015)
  %5 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } %4, 0
  %6 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } %4, 1
  %7 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } %4, 2
  %8 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } %4, 3
  %9 = extractvalue { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } %4, 4
  store <16 x i32> %9, ptr %extra3.i.i, align 64
  store <32 x i32> %7, ptr %s, align 128
  store i32 %8, ptr %pos1.i.i, align 64
  store ptr %6, ptr %p, align 4
  ret <64 x i8> %5
}

define dso_local void @_Z18test_fifo_ld_fillxRP22v64bfp16ebs8_unalignedR12fifo_state_tii(ptr nocapture nonnull align 4 dereferenceable(4) %p, ptr nocapture nonnull align 64 dereferenceable(256) %s, i32 noundef %step, i32 noundef %mask) local_unnamed_addr #0 {
; CHECK-LABEL: _Z18test_fifo_ld_fillxRP22v64bfp16ebs8_unalignedR12fifo_state_tii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    lda p0, [p0, #0]; nopx ; mov dj0, #128
; CHECK-NEXT:    lda r24, [p1, dj0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vlda lfh0, [p1, #64]
; CHECK-NEXT:    mova r2, #6
; CHECK-NEXT:    vlda lfl0, [p1, #0]; movs p2, p0; lshl r0, r0, r2
; CHECK-NEXT:    vlda lfe, [p1, #192]; or r30, r0, r1
; CHECK-NEXT:    vldb.fillx.512 [p0, lf0, r24]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    st r24, [p1, dj0]; ret lr
; CHECK-NEXT:    vst lfe, [p1, #192] // Delay Slot 5
; CHECK-NEXT:    vst lfh0, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst lfl0, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p0, [p2, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %pos1.i = getelementptr inbounds i8, ptr %s, i20 128
  %extra3.i = getelementptr inbounds i8, ptr %s, i20 192
  %shl.i = shl i32 %step, 6
  %or.i = or i32 %shl.i, %mask
  %0 = load ptr, ptr %p, align 4, !tbaa !2
  %1 = load <32 x i32>, ptr %s, align 64, !tbaa !6
  %2 = load i32, ptr %pos1.i, align 64, !tbaa !7
  %3 = load <16 x i32>, ptr %extra3.i, align 64, !tbaa !6
  %4 = tail call { ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.fillx(ptr %0, <32 x i32> %1, i32 %2, <16 x i32> %3, i32 %or.i)
  %5 = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } %4, 0
  %6 = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } %4, 1
  %7 = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } %4, 2
  %8 = extractvalue { ptr, <32 x i32>, i32, <16 x i32> } %4, 3
  store <16 x i32> %8, ptr %extra3.i, align 64
  store <32 x i32> %6, ptr %s, align 128
  store i32 %7, ptr %pos1.i, align 64
  store ptr %5, ptr %p, align 4
  ret void
}


define dso_local void @_Z18test_fifo_ld_resetRrP23v128bfp16ebs8_unalignedR12fifo_state_t(ptr nocapture nonnull align 4 dereferenceable(4) %p, ptr nocapture nonnull align 64 dereferenceable(256) %s) local_unnamed_addr #0 {
; CHECK-LABEL: _Z18test_fifo_ld_resetRrP23v128bfp16ebs8_unalignedR12fifo_state_t:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    lda p0, [p0, #0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vlda lfh0, [p1, #64]
; CHECK-NEXT:    vlda lfl0, [p1, #0]; movs p2, p0; movx r24, #0; mov dj0, #128
; CHECK-NEXT:    st r24, [p1, dj0]
; CHECK-NEXT:    vldb.fill.512 [p0, lf0, r24]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    st r24, [p1, dj0] // Delay Slot 5
; CHECK-NEXT:    vst lfh0, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst lfl0, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p0, [p2, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %pos.i.i = getelementptr inbounds i8, ptr %s, i20 128
  store i32 0, ptr %pos.i.i, align 64, !tbaa !2
  %0 = load ptr, ptr %p, align 4, !tbaa !7
  %1 = load <32 x i32>, ptr %s, align 64
  %2 = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr %0, <32 x i32> %1, i32 0)
  %3 = extractvalue { ptr, <32 x i32>, i32 } %2, 0
  %4 = extractvalue { ptr, <32 x i32>, i32 } %2, 1
  %5 = extractvalue { ptr, <32 x i32>, i32 } %2, 2
  store <32 x i32> %4, ptr %s, align 128
  store i32 %5, ptr %pos.i.i, align 64
  store ptr %3, ptr %p, align 4
  ret void
}

define dso_local void @_Z17test_fifo_ld_fillRrP23v128bfp16ebs8_unalignedR12fifo_state_t(ptr nocapture nonnull align 4 dereferenceable(4) %p, ptr nocapture nonnull align 64 dereferenceable(256) %s) local_unnamed_addr #0 {
; CHECK-LABEL: _Z17test_fifo_ld_fillRrP23v128bfp16ebs8_unalignedR12fifo_state_t:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    lda p0, [p0, #0]; mov dj0, #128
; CHECK-NEXT:    lda r24, [p1, dj0]; nopx
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vlda lfh0, [p1, #64]; movs p2, p0
; CHECK-NEXT:    vlda lfl0, [p1, #0]
; CHECK-NEXT:    vldb.fill.512 [p0, lf0, r24]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    st r24, [p1, dj0] // Delay Slot 5
; CHECK-NEXT:    vst lfh0, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst lfl0, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p0, [p2, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %pos1.i.i = getelementptr inbounds i8, ptr %s, i20 128
  %0 = load ptr, ptr %p, align 4, !tbaa !7
  %1 = load <32 x i32>, ptr %s, align 64
  %2 = load i32, ptr %pos1.i.i, align 64
  %3 = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill.p0.p0(ptr %0, <32 x i32> %1, i32 %2)
  %4 = extractvalue { ptr, <32 x i32>, i32 } %3, 0
  %5 = extractvalue { ptr, <32 x i32>, i32 } %3, 1
  %6 = extractvalue { ptr, <32 x i32>, i32 } %3, 2
  store <32 x i32> %5, ptr %s, align 128
  store i32 %6, ptr %pos1.i.i, align 64
  store ptr %4, ptr %p, align 4
  ret void
}

define dso_local %struct.v128bfp16ebs8 @_Z16test_fifo_ld_popRrP23v128bfp16ebs8_unalignedR12fifo_state_t(ptr nocapture nonnull align 4 dereferenceable(4) %p, ptr nocapture nonnull align 64 dereferenceable(256) %s) local_unnamed_addr #0 {
; CHECK-LABEL: _Z16test_fifo_ld_popRrP23v128bfp16ebs8_unalignedR12fifo_state_t:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    lda p0, [p0, #0]; mov dj0, #128
; CHECK-NEXT:    lda r24, [p1, dj0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vlda lfh0, [p1, #64]; movs p2, p0
; CHECK-NEXT:    vlda lfl0, [p1, #0]
; CHECK-NEXT:    vldb.pop.576 ex0, [p0, lf0, r24]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    st r24, [p1, dj0]
; CHECK-NEXT:    vst lfh0, [p1, #64]
; CHECK-NEXT:    vst lfl0, [p1, #0]
; CHECK-NEXT:    st p0, [p2, #0]
; CHECK-NEXT:    lda r24, [p1, dj0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vlda lfh0, [p1, #64]
; CHECK-NEXT:    vlda lfl0, [p1, #0]
; CHECK-NEXT:    vldb.pop.576 ex1, [p0, lf0, r24]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    st r24, [p1, dj0] // Delay Slot 5
; CHECK-NEXT:    vst lfh0, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst lfl0, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p0, [p2, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %pos1.i.i = getelementptr inbounds i8, ptr %s, i20 128
  %0 = load ptr, ptr %p, align 4, !tbaa !7
  %1 = load <32 x i32>, ptr %s, align 64
  %2 = load i32, ptr %pos1.i.i, align 64
  %3 = tail call { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.bfp16.p0.p0(ptr %0, <32 x i32> %1, i32 %2)
  %4 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %3, 0
  %5 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %3, 1
  %6 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %3, 2
  %7 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %3, 3
  %8 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %3, 4
  store <32 x i32> %5, ptr %s, align 128
  store i32 %6, ptr %pos1.i.i, align 64
  store ptr %4, ptr %p, align 4
  %.fca.0.insert.i23.i = insertvalue %struct.v128bfp16ebs8 poison, <64 x i8> %7, 0
  %9 = load <32 x i32>, ptr %s, align 64
  %10 = load i32, ptr %pos1.i.i, align 64
  %11 = tail call { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.bfp16.p0.p0(ptr %4, <32 x i32> %9, i32 %10)
  %12 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %11, 0
  %13 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %11, 1
  %14 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %11, 2
  %15 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %11, 3
  %16 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %11, 4
  store <32 x i32> %13, ptr %s, align 128
  store i32 %14, ptr %pos1.i.i, align 64
  store ptr %12, ptr %p, align 4
  %.fca.1.insert.i28.i = insertvalue %struct.v128bfp16ebs8 %.fca.0.insert.i23.i, <64 x i8> %15, 1
  %.fca.2.insert.i29.i = insertvalue %struct.v128bfp16ebs8 %.fca.1.insert.i28.i, <8 x i8> %8, 2
  %.fca.3.insert.i30.i = insertvalue %struct.v128bfp16ebs8 %.fca.2.insert.i29.i, <8 x i8> %16, 3
  ret %struct.v128bfp16ebs8 %.fca.3.insert.i30.i
}

define dso_local %struct.v128bfp16ebs8 @_Z24test_fifo_ld_pop_1d_byteRrP23v128bfp16ebs8_unalignedR12fifo_state_ti(ptr nocapture nonnull align 4 dereferenceable(4) %p, ptr nocapture nonnull align 64 dereferenceable(256) %s, i32 noundef %off) local_unnamed_addr #0 {
; CHECK-LABEL: _Z24test_fifo_ld_pop_1d_byteRrP23v128bfp16ebs8_unalignedR12fifo_state_ti:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    lda p0, [p0, #0]; nopb ; nops ; nopx ; mov dj0, #128; nopv
; CHECK-NEXT:    lda r24, [p1, dj0]; nopb ; nopx
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vlda lfh0, [p1, #64]; movs p2, p0
; CHECK-NEXT:    vlda lfl0, [p1, #0]
; CHECK-NEXT:    vldb.pop.576 ex0, [p0, lf0, r24]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    st r24, [p1, dj0]
; CHECK-NEXT:    vst lfh0, [p1, #64]
; CHECK-NEXT:    vst lfl0, [p1, #0]
; CHECK-NEXT:    st p0, [p2, #0]
; CHECK-NEXT:    lda r24, [p1, dj0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vlda lfh0, [p1, #64]
; CHECK-NEXT:    vlda lfl0, [p1, #0]; mov m0, r0
; CHECK-NEXT:    vldb.pop.576 ex1, [p0, lf0, r24, m0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    st r24, [p1, dj0] // Delay Slot 5
; CHECK-NEXT:    vst lfh0, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst lfl0, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p0, [p2, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %pos1.i.i = getelementptr inbounds i8, ptr %s, i20 128
  %0 = load ptr, ptr %p, align 4, !tbaa !7
  %1 = load <32 x i32>, ptr %s, align 64
  %2 = load i32, ptr %pos1.i.i, align 64
  %3 = tail call { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.bfp16.p0.p0(ptr %0, <32 x i32> %1, i32 %2)
  %4 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %3, 0
  %5 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %3, 1
  %6 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %3, 2
  %7 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %3, 3
  %8 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %3, 4
  store <32 x i32> %5, ptr %s, align 128
  store i32 %6, ptr %pos1.i.i, align 64
  store ptr %4, ptr %p, align 4
  %.fca.0.insert.i23.i = insertvalue %struct.v128bfp16ebs8 poison, <64 x i8> %7, 0
  %9 = load <32 x i32>, ptr %s, align 64
  %10 = load i32, ptr %pos1.i.i, align 64
  %11 = trunc i32 %off to i20
  %12 = tail call { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.1d.bfp16.p0.p0(ptr %4, <32 x i32> %9, i32 %10, i20 %11)
  %13 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %12, 0
  %14 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %12, 1
  %15 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %12, 2
  %16 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %12, 3
  %17 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %12, 4
  store <32 x i32> %14, ptr %s, align 128
  store i32 %15, ptr %pos1.i.i, align 64
  store ptr %13, ptr %p, align 4
  %.fca.1.insert.i28.i = insertvalue %struct.v128bfp16ebs8 %.fca.0.insert.i23.i, <64 x i8> %16, 1
  %.fca.2.insert.i29.i = insertvalue %struct.v128bfp16ebs8 %.fca.1.insert.i28.i, <8 x i8> %8, 2
  %.fca.3.insert.i30.i = insertvalue %struct.v128bfp16ebs8 %.fca.2.insert.i29.i, <8 x i8> %17, 3
  ret %struct.v128bfp16ebs8 %.fca.3.insert.i30.i
}

define dso_local %struct.v128bfp16ebs8 @_Z24test_fifo_ld_pop_2d_byteRrP23v128bfp16ebs8_unalignedR12fifo_state_tiiRii(ptr nocapture nonnull align 4 dereferenceable(4) %p, ptr nocapture nonnull align 64 dereferenceable(256) %s, i32 noundef %off, i32 noundef %size1, ptr nocapture nonnull align 4 dereferenceable(4) %count1, i32 noundef %inc1) local_unnamed_addr #0 {
; CHECK-LABEL: _Z24test_fifo_ld_pop_2d_byteRrP23v128bfp16ebs8_unalignedR12fifo_state_tiiRii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    lda p0, [p0, #0]; mov dj1, #128
; CHECK-NEXT:    lda r24, [p1, dj1]; nopx
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vlda lfh0, [p1, #64]; movs p3, p0
; CHECK-NEXT:    vlda lfl0, [p1, #0]
; CHECK-NEXT:    vldb.pop.576 ex0, [p0, lf0, r24]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    st r24, [p1, dj1]
; CHECK-NEXT:    vst lfh0, [p1, #64]
; CHECK-NEXT:    vst lfl0, [p1, #0]
; CHECK-NEXT:    st p0, [p3, #0]
; CHECK-NEXT:    lda r24, [p1, dj1]
; CHECK-NEXT:    lda dc0, [p2, #0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vlda lfh0, [p1, #64]; mov m0, r0
; CHECK-NEXT:    vlda lfl0, [p1, #0]; movs dn0, r1; mov dj0, r2
; CHECK-NEXT:    vldb.pop.576.2d ex1, [p0, lf0, r24, d0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    st dc0, [p2, #0]; ret lr
; CHECK-NEXT:    st r24, [p1, dj1] // Delay Slot 5
; CHECK-NEXT:    vst lfh0, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst lfl0, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p0, [p3, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %pos1.i.i = getelementptr inbounds i8, ptr %s, i20 128
  %0 = load ptr, ptr %p, align 4, !tbaa !7
  %1 = load <32 x i32>, ptr %s, align 64
  %2 = load i32, ptr %pos1.i.i, align 64
  %3 = tail call { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.bfp16.p0.p0(ptr %0, <32 x i32> %1, i32 %2)
  %4 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %3, 0
  %5 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %3, 1
  %6 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %3, 2
  %7 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %3, 3
  %8 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %3, 4
  store <32 x i32> %5, ptr %s, align 128
  store i32 %6, ptr %pos1.i.i, align 64
  store ptr %4, ptr %p, align 4
  %.fca.0.insert.i23.i = insertvalue %struct.v128bfp16ebs8 poison, <64 x i8> %7, 0
  %9 = load <32 x i32>, ptr %s, align 64
  %10 = load i32, ptr %pos1.i.i, align 64
  %11 = trunc i32 %off to i20
  %12 = trunc i32 %size1 to i20
  %13 = load i32, ptr %count1, align 4
  %14 = trunc i32 %13 to i20
  %15 = trunc i32 %inc1 to i20
  %16 = tail call { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.2d.bfp16.p0.p0(ptr %4, <32 x i32> %9, i32 %10, i20 %11, i20 %12, i20 %14, i20 %15)
  %17 = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } %16, 0
  %18 = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } %16, 1
  %19 = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } %16, 2
  %20 = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } %16, 4
  %21 = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } %16, 5
  %22 = extractvalue { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } %16, 3
  %23 = zext i20 %22 to i32
  store i32 %23, ptr %count1, align 4
  store <32 x i32> %18, ptr %s, align 128
  store i32 %19, ptr %pos1.i.i, align 64
  store ptr %17, ptr %p, align 4
  %.fca.1.insert.i28.i = insertvalue %struct.v128bfp16ebs8 %.fca.0.insert.i23.i, <64 x i8> %20, 1
  %.fca.2.insert.i29.i = insertvalue %struct.v128bfp16ebs8 %.fca.1.insert.i28.i, <8 x i8> %8, 2
  %.fca.3.insert.i30.i = insertvalue %struct.v128bfp16ebs8 %.fca.2.insert.i29.i, <8 x i8> %21, 3
  ret %struct.v128bfp16ebs8 %.fca.3.insert.i30.i
}

define dso_local %struct.v128bfp16ebs8 @_Z24test_fifo_ld_pop_3d_byteRrP23v128bfp16ebs8_unalignedR12fifo_state_tiiRiiiS5_i(ptr nocapture nonnull align 4 dereferenceable(4) %p, ptr nocapture nonnull align 64 dereferenceable(256) %s, i32 noundef %off, i32 noundef %size1, ptr nocapture nonnull align 4 dereferenceable(4) %count1, i32 noundef %inc1, i32 noundef %size2, ptr nocapture nonnull align 4 dereferenceable(4) %count2, i32 noundef %inc2) local_unnamed_addr #0 {
; CHECK-LABEL: _Z24test_fifo_ld_pop_3d_byteRrP23v128bfp16ebs8_unalignedR12fifo_state_tiiRiiiS5_i:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    lda p0, [p0, #0]; nopb ; nopx ; mov dj1, #128
; CHECK-NEXT:    lda r24, [p1, dj1]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vlda lfh0, [p1, #64]; movs p4, p0
; CHECK-NEXT:    vlda lfl0, [p1, #0]
; CHECK-NEXT:    vldb.pop.576 ex0, [p0, lf0, r24]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    st r24, [p1, dj1]
; CHECK-NEXT:    vst lfh0, [p1, #64]
; CHECK-NEXT:    vst lfl0, [p1, #0]
; CHECK-NEXT:    st p0, [p4, #0]
; CHECK-NEXT:    lda r24, [p1, dj1]
; CHECK-NEXT:    lda dc0, [p2, #0]
; CHECK-NEXT:    lda dc4, [p3, #0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    mov m0, r0
; CHECK-NEXT:    vlda lfh0, [p1, #64]; movs dn0, r1; mov dj0, r2
; CHECK-NEXT:    vlda lfl0, [p1, #0]; movs dn4, r3; mov dj4, r4
; CHECK-NEXT:    vldb.pop.576.3d ex1, [p0, lf0, r24, d0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    st dc0, [p2, #0]
; CHECK-NEXT:    st dc4, [p3, #0]; ret lr
; CHECK-NEXT:    st r24, [p1, dj1] // Delay Slot 5
; CHECK-NEXT:    vst lfh0, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst lfl0, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p0, [p4, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %pos1.i.i = getelementptr inbounds i8, ptr %s, i20 128
  %0 = load ptr, ptr %p, align 4, !tbaa !7
  %1 = load <32 x i32>, ptr %s, align 64
  %2 = load i32, ptr %pos1.i.i, align 64
  %3 = tail call { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.bfp16.p0.p0(ptr %0, <32 x i32> %1, i32 %2)
  %4 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %3, 0
  %5 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %3, 1
  %6 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %3, 2
  %7 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %3, 3
  %8 = extractvalue { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } %3, 4
  store <32 x i32> %5, ptr %s, align 128
  store i32 %6, ptr %pos1.i.i, align 64
  store ptr %4, ptr %p, align 4
  %.fca.0.insert.i23.i = insertvalue %struct.v128bfp16ebs8 poison, <64 x i8> %7, 0
  %9 = load <32 x i32>, ptr %s, align 64
  %10 = load i32, ptr %pos1.i.i, align 64
  %11 = trunc i32 %off to i20
  %12 = trunc i32 %size1 to i20
  %13 = load i32, ptr %count1, align 4
  %14 = trunc i32 %13 to i20
  %15 = trunc i32 %inc1 to i20
  %16 = trunc i32 %size2 to i20
  %17 = load i32, ptr %count2, align 4
  %18 = trunc i32 %17 to i20
  %19 = trunc i32 %inc2 to i20
  %20 = tail call { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.3d.bfp16.p0.p0(ptr %4, <32 x i32> %9, i32 %10, i20 %11, i20 %12, i20 %14, i20 %15, i20 %16, i20 %18, i20 %19)
  %21 = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %20, 0
  %22 = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %20, 1
  %23 = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %20, 2
  %24 = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %20, 5
  %25 = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %20, 6
  %26 = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %20, 3
  %27 = zext i20 %26 to i32
  %28 = extractvalue { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %20, 4
  %29 = zext i20 %28 to i32
  store i32 %27, ptr %count1, align 4
  store i32 %29, ptr %count2, align 4
  store <32 x i32> %22, ptr %s, align 128
  store i32 %23, ptr %pos1.i.i, align 64
  store ptr %21, ptr %p, align 4
  %.fca.1.insert.i28.i = insertvalue %struct.v128bfp16ebs8 %.fca.0.insert.i23.i, <64 x i8> %24, 1
  %.fca.2.insert.i29.i = insertvalue %struct.v128bfp16ebs8 %.fca.1.insert.i28.i, <8 x i8> %8, 2
  %.fca.3.insert.i30.i = insertvalue %struct.v128bfp16ebs8 %.fca.2.insert.i29.i, <8 x i8> %25, 3
  ret %struct.v128bfp16ebs8 %.fca.3.insert.i30.i
}





declare { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.fill(ptr, <32 x i32>, i32) #5
declare { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.unaligned(ptr, <32 x i32>, i32) #5
declare { <64 x i8>, ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.ld.pop.1d.unaligned(ptr, <32 x i32>, i32, i20) #5
declare { <64 x i8>, ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.ld.pop.2d.unaligned(ptr, <32 x i32>, i32, i20, i20, i20, i20) #5
declare { <64 x i8>, ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.ld.pop.3d.unaligned(ptr, <32 x i32>, i32, i20, i20, i20, i20, i20, i20, i20) #5
declare { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.bfp16(ptr, <32 x i32>, i32) #5
declare { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.1d.bfp16(ptr, <32 x i32>, i32, i20) #5
declare { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.2d.bfp16(ptr, <32 x i32>, i32, i20, i20, i20, i20) #5
declare { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.3d.bfp16(ptr, <32 x i32>, i32, i20, i20, i20, i20, i20, i20, i20) #5
declare { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.544.bfp16(ptr, <32 x i32>, i32) #5
declare { ptr, <32 x i32>, i32, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.544.1d.bfp16(ptr, <32 x i32>, i32, i20) #5
declare { ptr, <32 x i32>, i32, i20, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.544.2d.bfp16(ptr, <32 x i32>, i32, i20, i20, i20, i20) #5
declare { ptr, <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.544.3d.bfp16(ptr, <32 x i32>, i32, i20, i20, i20, i20, i20, i20, i20) #5
declare { <64 x i8>, ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.popx(ptr, <32 x i32>, i32, <16 x i32>, i32) #1
declare { ptr, <32 x i32>, i32, <16 x i32> } @llvm.aie2p.fifo.ld.fillx(ptr, <32 x i32>, i32, <16 x i32>, i32) #1

!2 = !{!3, !3, i64 0}
!3 = !{!"any pointer", !4, i64 0}
!4 = !{!"omnipotent char", !5, i64 0}
!5 = !{!"Simple C++ TBAA"}
!6 = !{!4, !4, i64 0}
!7 = !{!8, !8, i64 0}
!8 = !{!"int", !4, i64 0}
