; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2024-25 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie2p -verify-machineinstrs -o - < %s | FileCheck %s

target datalayout = "e-m:e-p:20:32-i1:8:32-i8:8:32-i16:16:32-i32:32:32-f32:32:32-i64:32-f64:32-a:0:32-n32"
target triple = "aie2p-none-unknown-elf"

define void @issue_3(i1 %exitcond.not.i) {
; CHECK-LABEL: issue_3:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova p3, #0; nopb ; nops ; paddxm [sp], #192; nopv
; CHECK-NEXT:    mova r1, #0; nopb ; jl p3; nopm ; nops
; CHECK-NEXT:    st r8, [sp, #-192]; vbcst.32 x0, r1 // 4-byte Folded Spill Delay Slot 5
; CHECK-NEXT:    st lr, [sp, #-188]; vmov x1, x0 // 4-byte Folded Spill Delay Slot 4
; CHECK-NEXT:    mova p0, #0; vst x0, [sp, #-128] // 64-byte Folded Spill Delay Slot 3
; CHECK-NEXT:    mova p1, #0; vst x1, [sp, #-64] // 64-byte Folded Spill Delay Slot 2
; CHECK-NEXT:    mova p2, #0; mov r8, r0 // Delay Slot 1
; CHECK-NEXT:    mova m4, #0; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    mov dn0, m4
; CHECK-NEXT:    mov dn4, m4
; CHECK-NEXT:    mov dn1, m4
; CHECK-NEXT:    mov dn5, m4
; CHECK-NEXT:    mov dn2, m4
; CHECK-NEXT:    movs dc5, m4; mov dc1, m4
; CHECK-NEXT:    vlda x2, [sp, #-128]; movs dc2, m4; mov r1, m4 // 64-byte Folded Reload
; CHECK-NEXT:    vlda x3, [sp, #-64]; movs dc3, m4; movx r0, #1; mov r2, m4 // 64-byte Folded Reload
; CHECK-NEXT:    movs dc0, m4; and r3, r8, r0; mov r0, m4
; CHECK-NEXT:    movs m1, m4; mov dj7, m4
; CHECK-NEXT:    movs m3, m4; mov dj1, r1
; CHECK-NEXT:    movs m2, m4; mov dj5, r1
; CHECK-NEXT:    movs dn7, m4; mov dj2, r1
; CHECK-NEXT:    movs dj6, r1; vmov lfl0, x2
; CHECK-NEXT:    mova dc4, #0; movs dj3, r1; movx r4, #0; vmov lfh0, x3
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB0_1: // %for.body.i
; CHECK-NEXT:    // =>This Loop Header: Depth=1
; CHECK-NEXT:    // Child Loop BB0_2 Depth 2
; CHECK-NEXT:    nopx ; vmov lfl1, lfl0
; CHECK-NEXT:    mova p1, #0; mov r25, r4
; CHECK-NEXT:    vldb.pop.576.3d ex0, [p1, lf1, r25, d1]; mov dj4, r1
; CHECK-NEXT:    mova p0, #0; movs m0, m4; mov dj0, r1
; CHECK-NEXT:    movs dn6, dn0; paddb.3d [p0], d0; vmov lfh1, lfh0
; CHECK-NEXT:    mova p0, #0; movs dn3, dn4; mov dc6, dc4
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB0_2: // %for.body103.i
; CHECK-NEXT:    // Parent Loop BB0_1 Depth=1
; CHECK-NEXT:    // => This Inner Loop Header: Depth=2
; CHECK-NEXT:    nopa ; nopb ; nops ; nopx ; mov m0, m4; nopv
; CHECK-NEXT:    movs dn0, r0; jz r3, #.LBB0_2
; CHECK-NEXT:    movs dj0, r1; mov dc0, m4 // Delay Slot 5
; CHECK-NEXT:    movs dn4, r2; mov dc4, m4 // Delay Slot 4
; CHECK-NEXT:    movs dj4, r1; mov r25, r4 // Delay Slot 3
; CHECK-NEXT:    movs p1, p0; vmov lfl1, x2 // Delay Slot 2
; CHECK-NEXT:    vldb.pop.576.3d ex0, [p1, lf1, r25, d0]; vmov lfh1, x3 // Delay Slot 1
; CHECK-NEXT:  // %bb.3: // %for.cond.cleanup102.i
; CHECK-NEXT:    // in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    nopa ; nopb ; nopxm
; CHECK-NEXT:    movs dc5, dc4; j #.LBB0_1
; CHECK-NEXT:    movs dn0, dn6; mov dc4, dc6 // Delay Slot 5
; CHECK-NEXT:    mova p0, #0; movs dn6, m4; mov dc6, m4 // Delay Slot 4
; CHECK-NEXT:    paddb.3d [p0], d2; mov dn4, dn3 // Delay Slot 3
; CHECK-NEXT:    mova p0, #0; movs dc7, m4; mov dn3, m4 // Delay Slot 2
; CHECK-NEXT:    mova dc0, #1; paddb.3d [p0], d3; movs dc1, dc0 // Delay Slot 1
entry:
  tail call void null(ptr null, ptr null, ptr null)
  br label %for.body.i

for.body.i:                                       ; preds = %for.cond.cleanup102.i, %entry
  %dimsAI.sroa.17.0665.i = phi i32 [ 0, %entry ], [ %20, %for.cond.cleanup102.i ]
  %dimsAI.sroa.13.0664.i = phi i32 [ 0, %entry ], [ %18, %for.cond.cleanup102.i ]
  %dimsAO.sroa.8.0662.i = phi i32 [ 0, %entry ], [ %11, %for.cond.cleanup102.i ]
  %dimsW.sroa.8.0660.i = phi i32 [ 0, %entry ], [ %15, %for.cond.cleanup102.i ]
  %iterator_psum_cnt0.0659.i = phi i32 [ 0, %entry ], [ 1, %for.cond.cleanup102.i ]
  %iterator_psum_cnt1.0658.i = phi i32 [ 0, %entry ], [ %7, %for.cond.cleanup102.i ]
  %0 = trunc i32 %iterator_psum_cnt0.0659.i to i20
  %1 = trunc i32 %iterator_psum_cnt1.0658.i to i20
  %2 = tail call { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr null, i20 0, i20 0, i20 0, i20 0, i20 %0, i20 0, i20 %1)
  %3 = extractvalue { ptr, i20, i20 } %2, 2
  %4 = trunc i32 %dimsAI.sroa.13.0664.i to i20
  %5 = trunc i32 %dimsAI.sroa.17.0665.i to i20
  %6 = tail call { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.3d.bfp16.p5.p5(ptr addrspace(5) null, <32 x i32> zeroinitializer, i32 0, i20 0, i20 0, i20 %4, i20 0, i20 0, i20 %5, i20 0)
  br label %for.body103.i

for.cond.cleanup102.i:                            ; preds = %for.body103.i
  %7 = zext i20 %3 to i32
  %8 = trunc i32 %dimsAO.sroa.8.0662.i to i20
  %9 = tail call { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr null, i20 0, i20 0, i20 0, i20 0, i20 %8, i20 0, i20 0)
  %10 = extractvalue { ptr, i20, i20 } %9, 1
  %11 = zext i20 %10 to i32
  %12 = trunc i32 %dimsW.sroa.8.0660.i to i20
  %13 = tail call { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr null, i20 0, i20 0, i20 0, i20 0, i20 %12, i20 0, i20 0)
  %14 = extractvalue { ptr, i20, i20 } %13, 1
  %15 = zext i20 %14 to i32
  br label %for.body.i

for.body103.i:                                    ; preds = %for.body103.i, %for.body.i
  %16 = tail call { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.3d.bfp16.p5.p5(ptr addrspace(5) null, <32 x i32> zeroinitializer, i32 0, i20 0, i20 0, i20 0, i20 0, i20 0, i20 0, i20 0)
  %17 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %16, 3
  %18 = zext i20 %17 to i32
  %19 = extractvalue { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } %16, 4
  %20 = zext i20 %19 to i32
  br i1 %exitcond.not.i, label %for.cond.cleanup102.i, label %for.body103.i
}

; Function Attrs: nounwind memory(none)
declare { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr, i20, i20, i20, i20, i20, i20, i20) #0

; Function Attrs: nounwind memory(argmem: read)
declare { ptr addrspace(5), <32 x i32>, i32, i20, i20, <64 x i8>, <8 x i8> } @llvm.aie2p.fifo.ld.pop.576.3d.bfp16.p5.p5(ptr addrspace(5), <32 x i32>, i32, i20, i20, i20, i20, i20, i20, i20) #1

; uselistorder directives
uselistorder ptr @llvm.aie2p.add.3d, { 2, 1, 0 }
uselistorder ptr @llvm.aie2p.fifo.ld.pop.576.3d.bfp16.p5.p5, { 1, 0 }

attributes #0 = { nounwind memory(none) }
attributes #1 = { nounwind memory(argmem: read) }
