; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2024-25 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie2p -verify-machineinstrs -o - < %s | FileCheck %s


target datalayout = "e-m:e-p:20:32-i1:8:32-i8:8:32-i16:16:32-i32:32:32-f32:32:32-i64:32-f64:32-a:0:32-n32"
target triple = "aie2p-none-unknown-elf"

define void @issue_1(i1 %exitcond.not.i) {
; CHECK-LABEL: issue_1:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova dn3, #0; nopb ; movx r1, #1; mov crupsmode, #0
; CHECK-NEXT:    and r7, r0, r1; mov r0, dn3
; CHECK-NEXT:    mova r2, #0; mov r1, dn3
; CHECK-NEXT:    movs dn7, dn3; vbcst.16 x0, r2
; CHECK-NEXT:    movs dc3, dn3; mov s0, r2
; CHECK-NEXT:    movs dc7, dn3; mov r2, dn3
; CHECK-NEXT:    movs dn0, dn3; mov r3, dn3
; CHECK-NEXT:    movs dc0, dn3; mov r4, dn3
; CHECK-NEXT:    movs dc5, dn3; mov r5, dn3
; CHECK-NEXT:    movs dj3, dn3; mov r6, dn3
; CHECK-NEXT:    movs m2, dn3; mov dj6, dn3
; CHECK-NEXT:    movs m1, dn3; mov dj2, dn3
; CHECK-NEXT:    movs dn1, dn3; mov dj1, dn3
; CHECK-NEXT:    movs dn5, dn3; mov dj5, dn3
; CHECK-NEXT:    movs dn4, dn3; mov dj0, dn3
; CHECK-NEXT:    movs m0, dn3; mov dj4, dn3
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB0_1: // %for.body.i
; CHECK-NEXT:    // =>This Loop Header: Depth=1
; CHECK-NEXT:    // Child Loop BB0_2 Depth 2
; CHECK-NEXT:    nopa ; nopb ; movs dc4, dn3; nopx ; vups.2x cml0, x0, s0, upssign0; nopv
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB0_2: // %for.body58.i
; CHECK-NEXT:    // Parent Loop BB0_1 Depth=1
; CHECK-NEXT:    // => This Inner Loop Header: Depth=2
; CHECK-NEXT:    nopa ; nopb ; nopx ; mov dn2, dn7; movs dc2, dc3
; CHECK-NEXT:    mova p0, #0; movs dc6, dc7; mov dn6, r0
; CHECK-NEXT:    movs dn2, r1; paddb.3d [p0], d2; jz r7, #.LBB0_2
; CHECK-NEXT:    mov dn6, r2 // Delay Slot 5
; CHECK-NEXT:    movs dc2, dc4; mov dc6, r3 // Delay Slot 4
; CHECK-NEXT:    paddb.3d [p0], d2 // Delay Slot 3
; CHECK-NEXT:    mova p0, #0; mov dc1, r5 // Delay Slot 2
; CHECK-NEXT:    paddb.3d [p0], d1; mov dc4, dc2 // Delay Slot 1
; CHECK-NEXT:  // %bb.3: // %for.cond.cleanup57.i
; CHECK-NEXT:    // in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    nopa ; nopb ; nops ; j #.LBB0_1; nopv
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    mova p0, #0; mov dc4, dn3 // Delay Slot 2
; CHECK-NEXT:    paddb.3d [p0], d0 // Delay Slot 1
entry:
  br label %for.body.i

for.body.i:                                       ; preds = %for.cond.cleanup57.i, %entry
  %iterator_pout_cnt0.0489.i = phi i32 [ 0, %entry ], [ %4, %for.cond.cleanup57.i ]
  %Ky_cnt.0485.i = phi i32 [ 0, %entry ], [ %14, %for.cond.cleanup57.i ]
  %0 = tail call <32 x i32> @llvm.aie2p.acc32.v32.I512.ups(<32 x i16> zeroinitializer, i32 0, i32 0)
  br label %for.body58.i

for.cond.cleanup57.i:                             ; preds = %for.body58.i
  %1 = trunc i32 %iterator_pout_cnt0.0489.i to i20
  %2 = tail call { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr null, i20 0, i20 0, i20 0, i20 0, i20 %1, i20 0, i20 0)
  %3 = extractvalue { ptr, i20, i20 } %2, 1
  %4 = zext i20 %3 to i32
  br label %for.body.i

for.body58.i:                                     ; preds = %for.body58.i, %for.body.i
  %iterator_inner1_cnt0.1478.i = phi i32 [ 0, %for.body.i ], [ %10, %for.body58.i ]
  %Ky_cnt.1476.i = phi i32 [ %Ky_cnt.0485.i, %for.body.i ], [ %14, %for.body58.i ]
  %5 = tail call { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr null, i20 0, i20 0, i20 0, i20 0, i20 0, i20 0, i20 0)
  %6 = extractvalue { ptr, i20, i20 } %5, 0
  %7 = trunc i32 %iterator_inner1_cnt0.1478.i to i20
  %8 = tail call { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr %6, i20 0, i20 0, i20 0, i20 0, i20 %7, i20 0, i20 0)
  %9 = extractvalue { ptr, i20, i20 } %8, 1
  %10 = zext i20 %9 to i32
  %11 = trunc i32 %Ky_cnt.1476.i to i20
  %12 = tail call { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr null, i20 0, i20 0, i20 0, i20 0, i20 0, i20 0, i20 %11)
  %13 = extractvalue { ptr, i20, i20 } %12, 2
  %14 = zext i20 %13 to i32
  br i1 %exitcond.not.i, label %for.cond.cleanup57.i, label %for.body58.i

; uselistorder directives
  uselistorder i32 %14, { 1, 0 }
}

; Function Attrs: nounwind memory(inaccessiblemem: read)
declare <32 x i32> @llvm.aie2p.acc32.v32.I512.ups(<32 x i16>, i32, i32) #0

; Function Attrs: nounwind memory(none)
declare { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr, i20, i20, i20, i20, i20, i20, i20) #1

; uselistorder directives
uselistorder ptr @llvm.aie2p.add.3d, { 3, 2, 1, 0 }

attributes #0 = { nounwind memory(inaccessiblemem: read) }
attributes #1 = { nounwind memory(none) }
