; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2024-25 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie2p -verify-machineinstrs -o - < %s | FileCheck %s


target datalayout = "e-m:e-p:20:32-i1:8:32-i8:8:32-i16:16:32-i32:32:32-f32:32:32-i64:32-f64:32-a:0:32-n32"
target triple = "aie2p-none-unknown-elf"

define void @issue_2(i32 %0, i1 %exitcond.not.i) {
; CHECK-LABEL: issue_2:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova m0, #0; nopb ; nopx
; CHECK-NEXT:    movs dc5, m0; mov dj0, m0
; CHECK-NEXT:    movs dj4, m0; mov dn0, m0
; CHECK-NEXT:    movs dj2, m0; mov dn4, m0
; CHECK-NEXT:    movs dj6, m0; mov dn2, m0
; CHECK-NEXT:    movs dj3, m0; mov dn6, m0
; CHECK-NEXT:    movs dj7, m0; mov dn3, m0
; CHECK-NEXT:    mova r2, #1; movs dn7, m0; mov dc0, m0
; CHECK-NEXT:    movs dc4, m0; and r5, r1, r2; mov r2, m0
; CHECK-NEXT:    movs dc3, m0; mov r1, m0
; CHECK-NEXT:    movs dc2, m0; mov m2, m0
; CHECK-NEXT:    mova dn5, #1; movs dj5, m0; mov m3, m0
; CHECK-NEXT:    mova r3, #0; movs dn1, m0; mov m1, m0
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB0_1: // %for.body58.i
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    jz r5, #.LBB0_1
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    mova p0, #0 // Delay Slot 4
; CHECK-NEXT:    paddb.3d [p0], d0 // Delay Slot 3
; CHECK-NEXT:    mova p0, #0; mov dc6, r3 // Delay Slot 2
; CHECK-NEXT:    paddb.3d [p0], d2; or r3, r0, r0; mov dc0, dn5 // Delay Slot 1
; CHECK-NEXT:  // %bb.2: // %for.cond.cleanup57.i
; CHECK-NEXT:    // in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    nopa ; nopb ; movs dc7, dn5; nopx ; mov dc0, dc5; nopv
; CHECK-NEXT:    nopa ; nopb ; nopx ; mov r3, dn5; movs dc1, r2
; CHECK-NEXT:    movs dj1, r1; mov dn5, m0
; CHECK-NEXT:    mova p0, #0; movs dc5, m0; j #.LBB0_1
; CHECK-NEXT:    paddb.3d [p0], d1 // Delay Slot 5
; CHECK-NEXT:    mova p0, #0; movs dc2, m0; mov dn5, r3 // Delay Slot 4
; CHECK-NEXT:    movs dj1, m0; paddb.3d [p0], d3; mov r2, dc1 // Delay Slot 3
; CHECK-NEXT:    mova p0, #0; movs dc5, dc0; mov dc1, m0 // Delay Slot 2
; CHECK-NEXT:    mova r3, #0; paddb.3d [p0], d1; movs dc4, m0; mov dc0, m0 // Delay Slot 1
entry:
  br label %for.body.i

for.body.i:                                       ; preds = %for.cond.cleanup57.i, %entry
  %iterator_outer0_cnt0.0496.i = phi i32 [ 0, %entry ], [ %4, %for.cond.cleanup57.i ]
  %iterator_weights_cnt0.0493.i = phi i32 [ 0, %entry ], [ %8, %for.cond.cleanup57.i ]
  %y_cnt.0487.i = phi i32 [ 0, %entry ], [ %12, %for.cond.cleanup57.i ]
  br label %for.body58.i

for.cond.cleanup57.i:                             ; preds = %for.body58.i
  %1 = trunc i32 %iterator_outer0_cnt0.0496.i to i20
  %2 = tail call { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr null, i20 0, i20 0, i20 0, i20 0, i20 %1, i20 0, i20 1)
  %3 = extractvalue { ptr, i20, i20 } %2, 1
  %4 = zext i20 %3 to i32
  %5 = trunc i32 %iterator_weights_cnt0.0493.i to i20
  %6 = tail call { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr null, i20 0, i20 0, i20 0, i20 0, i20 %5, i20 0, i20 0)
  %7 = extractvalue { ptr, i20, i20 } %6, 1
  %8 = zext i20 %7 to i32
  %9 = trunc i32 %y_cnt.0487.i to i20
  %10 = tail call { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr null, i20 0, i20 0, i20 0, i20 0, i20 0, i20 1, i20 %9)
  %11 = extractvalue { ptr, i20, i20 } %10, 2
  %12 = zext i20 %11 to i32
  br label %for.body.i

for.body58.i:                                     ; preds = %for.body58.i, %for.body.i
  %iterator_inner0_cnt0.1480.i = phi i32 [ 0, %for.body.i ], [ 1, %for.body58.i ]
  %iterator_inner0_cnt1.1479.i = phi i32 [ 0, %for.body.i ], [ %17, %for.body58.i ]
  %iterator_inner1_cnt0.1478.i = phi i32 [ 0, %for.body.i ], [ %22, %for.body58.i ]
  %iterator_inner1_cnt1.1477.i = phi i32 [ 0, %for.body.i ], [ %0, %for.body58.i ]
  %13 = trunc i32 %iterator_inner0_cnt0.1480.i to i20
  %14 = trunc i32 %iterator_inner0_cnt1.1479.i to i20
  %15 = tail call { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr null, i20 0, i20 0, i20 0, i20 0, i20 %13, i20 0, i20 %14)
  %16 = extractvalue { ptr, i20, i20 } %15, 2
  %17 = zext i20 %16 to i32
  %18 = trunc i32 %iterator_inner1_cnt0.1478.i to i20
  %19 = trunc i32 %iterator_inner1_cnt1.1477.i to i20
  %20 = tail call { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr null, i20 0, i20 0, i20 0, i20 0, i20 %18, i20 0, i20 %19)
  %21 = extractvalue { ptr, i20, i20 } %20, 1
  %22 = zext i20 %21 to i32
  br i1 %exitcond.not.i, label %for.cond.cleanup57.i, label %for.body58.i
}

; Function Attrs: nounwind memory(none)
declare { ptr, i20, i20 } @llvm.aie2p.add.3d(ptr, i20, i20, i20, i20, i20, i20, i20) #0

; uselistorder directives
uselistorder ptr @llvm.aie2p.add.3d, { 4, 3, 2, 1, 0 }

attributes #0 = { nounwind memory(none) }
