; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc < %s -verify-machineinstrs -mtriple=aie2p | FileCheck %s

%struct.v64bfp16ebs8 = type <{ <64 x i8>, <8 x i8> }>
%struct.v64bfp16ebs16 = type <{ <64 x i8>, <8 x i8> }>
%struct.v128bfp16ebs8 = type <{ <64 x i8>, <64 x i8>, <8 x i8>, <8 x i8> }>
%struct.v128bfp16ebs16 = type <{ <64 x i8>, <64 x i8>, <8 x i8>, <8 x i8> }>

; Function Attrs: mustprogress nounwind memory(write, argmem: readwrite, inaccessiblemem: none)
define dso_local void @_Z18test_fifo_st_resetRPDv64_DB8_S0_R12fifo_state_t(ptr nocapture nonnull align 4 dereferenceable(4) %p, <64 x i8> noundef %v, ptr nocapture nonnull align 64 dereferenceable(256) %s) local_unnamed_addr #2 {
; CHECK-LABEL: _Z18test_fifo_st_resetRPDv64_DB8_S0_R12fifo_state_t:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    vlda sfh, [p1, #64]; nopx
; CHECK-NEXT:    lda p2, [p0, #0]
; CHECK-NEXT:    vlda sfl, [p1, #0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    mova r26, #0
; CHECK-NEXT:    vst.push.512 x0, [p2, sf, r26]; ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    vst sfh, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst sfl, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p2, [p0, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = load ptr, ptr %p, align 4, !tbaa !2
  %1 = bitcast <64 x i8> %v to <16 x i32>
  %2 = load <32 x i32>, ptr %s, align 64, !tbaa !6
  %3 = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16(ptr %0, <16 x i32> %1, <32 x i32> %2, i32 0)
  %4 = extractvalue { ptr, <32 x i32>, i32 } %3, 0
  %5 = extractvalue { ptr, <32 x i32>, i32 } %3, 1
  store <32 x i32> %5, ptr %s, align 128
  store ptr %4, ptr %p, align 4
  ret void
}

; Function Attrs: mustprogress nounwind memory(write, argmem: readwrite, inaccessiblemem: none)
define dso_local void @_Z17test_fifo_st_pushRPDv64_DB8_S0_R12fifo_state_t(ptr nocapture nonnull align 4 dereferenceable(4) %p, <64 x i8> noundef %v, ptr nocapture nonnull align 64 dereferenceable(256) %s) local_unnamed_addr #2 {
; CHECK-LABEL: _Z17test_fifo_st_pushRPDv64_DB8_S0_R12fifo_state_t:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    vlda sfh, [p1, #64]; nopb ; nopxm ; nops
; CHECK-NEXT:    lda p2, [p0, #0]; mov dj0, #128
; CHECK-NEXT:    lda r26, [p1, dj0]
; CHECK-NEXT:    vlda sfl, [p1, #0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst.push.512 x0, [p2, sf, r26]
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    st r26, [p1, dj0] // Delay Slot 5
; CHECK-NEXT:    vst sfh, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst sfl, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p2, [p0, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %pos1.i = getelementptr inbounds i8, ptr %s, i20 128
  %0 = load ptr, ptr %p, align 4, !tbaa !2
  %1 = bitcast <64 x i8> %v to <16 x i32>
  %2 = load <32 x i32>, ptr %s, align 64, !tbaa !6
  %3 = load i32, ptr %pos1.i, align 64, !tbaa !7
  %4 = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16(ptr %0, <16 x i32> %1, <32 x i32> %2, i32 %3)
  %5 = extractvalue { ptr, <32 x i32>, i32 } %4, 0
  %6 = extractvalue { ptr, <32 x i32>, i32 } %4, 1
  %7 = extractvalue { ptr, <32 x i32>, i32 } %4, 2
  store <32 x i32> %6, ptr %s, align 128
  store i32 %7, ptr %pos1.i, align 64
  store ptr %5, ptr %p, align 4
  ret void
}

; Function Attrs: mustprogress nounwind memory(write, argmem: readwrite, inaccessiblemem: none)
define dso_local void @_Z18test_fifo_st_flushRPDv64_DB8_R12fifo_state_t(ptr nocapture nonnull align 4 dereferenceable(4) %p, ptr nocapture nonnull align 64 dereferenceable(256) %s) local_unnamed_addr #2 {
; CHECK-LABEL: _Z18test_fifo_st_flushRPDv64_DB8_R12fifo_state_t:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    vlda sfh, [p1, #64]; nopb ; nopxm ; nops
; CHECK-NEXT:    lda p2, [p0, #0]; mov dj0, #128
; CHECK-NEXT:    lda r26, [p1, dj0]
; CHECK-NEXT:    vlda sfl, [p1, #0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst.flush.512 [p2, sf, r26]
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    st r26, [p1, dj0] // Delay Slot 5
; CHECK-NEXT:    vst sfh, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst sfl, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p2, [p0, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %pos1.i = getelementptr inbounds i8, ptr %s, i20 128
  %0 = load ptr, ptr %p, align 4, !tbaa !2
  %1 = load <32 x i32>, ptr %s, align 64, !tbaa !6
  %2 = load i32, ptr %pos1.i, align 64, !tbaa !7
  %3 = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush(ptr %0, <32 x i32> %1, i32 %2)
  %4 = extractvalue { ptr, <32 x i32>, i32 } %3, 0
  %5 = extractvalue { ptr, <32 x i32>, i32 } %3, 1
  %6 = extractvalue { ptr, <32 x i32>, i32 } %3, 2
  store <32 x i32> %5, ptr %s, align 128
  store i32 %6, ptr %pos1.i, align 64
  store ptr %4, ptr %p, align 4
  ret void
}

; Function Attrs: mustprogress nounwind memory(write, argmem: readwrite, inaccessiblemem: none)
define dso_local void @_Z26test_fifo_st_flush_1d_byteRPDv64_DB8_R12fifo_state_ti(ptr nocapture nonnull align 4 dereferenceable(4) %p, ptr nocapture nonnull align 64 dereferenceable(256) %s, i32 noundef %off) local_unnamed_addr #2 {
; CHECK-LABEL: _Z26test_fifo_st_flush_1d_byteRPDv64_DB8_R12fifo_state_ti:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    vlda sfh, [p1, #64]; nopb ; nopxm
; CHECK-NEXT:    lda p2, [p0, #0]; mov dj0, #128
; CHECK-NEXT:    lda r26, [p1, dj0]
; CHECK-NEXT:    vlda sfl, [p1, #0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    mov m0, r0
; CHECK-NEXT:    vst.flush.512 [p2, sf, r26, m0]
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    st r26, [p1, dj0] // Delay Slot 5
; CHECK-NEXT:    vst sfh, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst sfl, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p2, [p0, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %pos1.i = getelementptr inbounds i8, ptr %s, i20 128
  %0 = load ptr, ptr %p, align 4, !tbaa !2
  %1 = load <32 x i32>, ptr %s, align 64, !tbaa !6
  %2 = load i32, ptr %pos1.i, align 64, !tbaa !7
  %3 = trunc i32 %off to i20
  %4 = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d(ptr %0, <32 x i32> %1, i32 %2, i20 %3)
  %5 = extractvalue { ptr, <32 x i32>, i32 } %4, 0
  %6 = extractvalue { ptr, <32 x i32>, i32 } %4, 1
  %7 = extractvalue { ptr, <32 x i32>, i32 } %4, 2
  store <32 x i32> %6, ptr %s, align 128
  store i32 %7, ptr %pos1.i, align 64
  store ptr %5, ptr %p, align 4
  ret void
}

; Function Attrs: mustprogress nounwind memory(write, argmem: readwrite, inaccessiblemem: none)
define dso_local void @_Z26test_fifo_st_flush_2d_byteRPDv64_DB8_R12fifo_state_tiiRii(ptr nocapture nonnull align 4 dereferenceable(4) %p, ptr nocapture nonnull align 64 dereferenceable(256) %s, i32 noundef %off, i32 noundef %size1, ptr nocapture nonnull align 4 dereferenceable(4) %count1, i32 noundef %inc1) local_unnamed_addr #2 {
; CHECK-LABEL: _Z26test_fifo_st_flush_2d_byteRPDv64_DB8_R12fifo_state_tiiRii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    lda p4, [p0, #0]; nopx
; CHECK-NEXT:    lda dc0, [p2, #0]; mov dj1, #128
; CHECK-NEXT:    lda r26, [p1, dj1]
; CHECK-NEXT:    nop
; CHECK-NEXT:    vlda sfh, [p1, #64]
; CHECK-NEXT:    vlda sfl, [p1, #0]
; CHECK-NEXT:    movs p3, p2
; CHECK-NEXT:    movs m0, r0; mov dn0, r1
; CHECK-NEXT:    movs dj0, r2; mov p2, p4
; CHECK-NEXT:    vst.flush.512.conv.2d [p2, sf, r26, d0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    st dc0, [p3, #0]; ret lr
; CHECK-NEXT:    st r26, [p1, dj1] // Delay Slot 5
; CHECK-NEXT:    vst sfh, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst sfl, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p2, [p0, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %pos1.i = getelementptr inbounds i8, ptr %s, i20 128
  %0 = load ptr, ptr %p, align 4, !tbaa !2
  %1 = load <32 x i32>, ptr %s, align 64, !tbaa !6
  %2 = load i32, ptr %pos1.i, align 64, !tbaa !7
  %3 = trunc i32 %off to i20
  %4 = trunc i32 %size1 to i20
  %5 = load i32, ptr %count1, align 4, !tbaa !7
  %6 = trunc i32 %5 to i20
  %7 = trunc i32 %inc1 to i20
  %8 = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv(ptr %0, <32 x i32> %1, i32 %2, i20 %3, i20 %4, i20 %6, i20 %7)
  %9 = extractvalue { ptr, <32 x i32>, i32, i20 } %8, 0
  %10 = extractvalue { ptr, <32 x i32>, i32, i20 } %8, 1
  %11 = extractvalue { ptr, <32 x i32>, i32, i20 } %8, 2
  %12 = extractvalue { ptr, <32 x i32>, i32, i20 } %8, 3
  %13 = zext i20 %12 to i32
  store i32 %13, ptr %count1, align 4
  store <32 x i32> %10, ptr %s, align 128
  store i32 %11, ptr %pos1.i, align 64
  store ptr %9, ptr %p, align 4
  ret void
}

; Function Attrs: mustprogress nounwind memory(write, argmem: readwrite, inaccessiblemem: none)
define dso_local void @_Z26test_fifo_st_flush_3d_byteRPDv64_DB8_R12fifo_state_tiiRiiiS5_i(ptr nocapture nonnull align 4 dereferenceable(4) %p, ptr nocapture nonnull align 64 dereferenceable(256) %s, i32 noundef %off, i32 noundef %size1, ptr nocapture nonnull align 4 dereferenceable(4) %count1, i32 noundef %inc1, i32 noundef %size2, ptr nocapture nonnull align 4 dereferenceable(4) %count2, i32 noundef %inc2) local_unnamed_addr #2 {
; CHECK-LABEL: _Z26test_fifo_st_flush_3d_byteRPDv64_DB8_R12fifo_state_tiiRiiiS5_i:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    vlda sfh, [p1, #64]; nopxm
; CHECK-NEXT:    lda p5, [p0, #0]
; CHECK-NEXT:    lda dc0, [p2, #0]
; CHECK-NEXT:    lda dc4, [p3, #0]; mov dj1, #128
; CHECK-NEXT:    lda r26, [p1, dj1]
; CHECK-NEXT:    vlda sfl, [p1, #0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    movs p4, p2
; CHECK-NEXT:    movs m0, r0; mov dn0, r1
; CHECK-NEXT:    movs dj0, r2; mov dn4, r3
; CHECK-NEXT:    movs dj4, r4; mov p2, p5
; CHECK-NEXT:    vst.flush.512.3d [p2, sf, r26, d0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    st dc0, [p4, #0]
; CHECK-NEXT:    st dc4, [p3, #0]; ret lr
; CHECK-NEXT:    st r26, [p1, dj1] // Delay Slot 5
; CHECK-NEXT:    vst sfh, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst sfl, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p2, [p0, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %pos1.i = getelementptr inbounds i8, ptr %s, i20 128
  %0 = load ptr, ptr %p, align 4, !tbaa !2
  %1 = load <32 x i32>, ptr %s, align 64, !tbaa !6
  %2 = load i32, ptr %pos1.i, align 64, !tbaa !7
  %3 = trunc i32 %off to i20
  %4 = trunc i32 %size1 to i20
  %5 = load i32, ptr %count1, align 4, !tbaa !7
  %6 = trunc i32 %5 to i20
  %7 = trunc i32 %inc1 to i20
  %8 = trunc i32 %size2 to i20
  %9 = load i32, ptr %count2, align 4, !tbaa !7
  %10 = trunc i32 %9 to i20
  %11 = trunc i32 %inc2 to i20
  %12 = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d(ptr %0, <32 x i32> %1, i32 %2, i20 %3, i20 %4, i20 %6, i20 %7, i20 %8, i20 %10, i20 %11)
  %13 = extractvalue { ptr, <32 x i32>, i32, i20, i20 } %12, 0
  %14 = extractvalue { ptr, <32 x i32>, i32, i20, i20 } %12, 1
  %15 = extractvalue { ptr, <32 x i32>, i32, i20, i20 } %12, 2
  %16 = extractvalue { ptr, <32 x i32>, i32, i20, i20 } %12, 3
  %17 = zext i20 %16 to i32
  %18 = extractvalue { ptr, <32 x i32>, i32, i20, i20 } %12, 4
  %19 = zext i20 %18 to i32
  store i32 %17, ptr %count1, align 4
  store i32 %19, ptr %count2, align 4
  store <32 x i32> %14, ptr %s, align 128
  store i32 %15, ptr %pos1.i, align 64
  store ptr %13, ptr %p, align 4
  ret void
}

; Function Attrs: mustprogress nounwind memory(write, argmem: readwrite, inaccessiblemem: none)
define dso_local void @_Z23test_fifo_st_flush_convRPDv64_DB8_R12fifo_state_t(ptr nocapture nonnull align 4 dereferenceable(4) %p, ptr nocapture nonnull align 64 dereferenceable(256) %s) local_unnamed_addr #2 {
; CHECK-LABEL: _Z23test_fifo_st_flush_convRPDv64_DB8_R12fifo_state_t:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    lda p2, [p0, #0]; nopb ; nopx ; mov dj0, #128; nops
; CHECK-NEXT:    lda r26, [p1, dj0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    vlda sfh, [p1, #64]
; CHECK-NEXT:    vlda sfl, [p1, #0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst.flush.512.conv [p2, sf, r26]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    st r26, [p1, dj0] // Delay Slot 5
; CHECK-NEXT:    vst sfh, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst sfl, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p2, [p0, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %pos1.i = getelementptr inbounds i8, ptr %s, i20 128
  %0 = load ptr, ptr %p, align 4, !tbaa !2
  %1 = load <32 x i32>, ptr %s, align 64, !tbaa !6
  %2 = load i32, ptr %pos1.i, align 64, !tbaa !7
  %3 = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.conv(ptr %0, <32 x i32> %1, i32 %2)
  %4 = extractvalue { ptr, <32 x i32>, i32 } %3, 0
  %5 = extractvalue { ptr, <32 x i32>, i32 } %3, 1
  %6 = extractvalue { ptr, <32 x i32>, i32 } %3, 2
  store <32 x i32> %5, ptr %s, align 128
  store i32 %6, ptr %pos1.i, align 64
  store ptr %4, ptr %p, align 4
  ret void
}

; Function Attrs: mustprogress nounwind memory(write, argmem: readwrite, inaccessiblemem: none)
define dso_local void @_Z31test_fifo_st_flush_conv_1d_byteRPDv64_DB8_R12fifo_state_ti(ptr nocapture nonnull align 4 dereferenceable(4) %p, ptr nocapture nonnull align 64 dereferenceable(256) %s, i32 noundef %off) local_unnamed_addr #2 {
; CHECK-LABEL: _Z31test_fifo_st_flush_conv_1d_byteRPDv64_DB8_R12fifo_state_ti:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    lda p2, [p0, #0]; nopb ; nopx ; mov dj0, #128
; CHECK-NEXT:    lda r26, [p1, dj0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    vlda sfh, [p1, #64]
; CHECK-NEXT:    vlda sfl, [p1, #0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    mov m0, r0
; CHECK-NEXT:    vst.flush.512.conv [p2, sf, r26, m0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    st r26, [p1, dj0] // Delay Slot 5
; CHECK-NEXT:    vst sfh, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst sfl, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p2, [p0, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %pos1.i = getelementptr inbounds i8, ptr %s, i20 128
  %0 = load ptr, ptr %p, align 4, !tbaa !2
  %1 = load <32 x i32>, ptr %s, align 64, !tbaa !6
  %2 = load i32, ptr %pos1.i, align 64, !tbaa !7
  %3 = trunc i32 %off to i20
  %4 = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.conv(ptr %0, <32 x i32> %1, i32 %2, i20 %3)
  %5 = extractvalue { ptr, <32 x i32>, i32 } %4, 0
  %6 = extractvalue { ptr, <32 x i32>, i32 } %4, 1
  %7 = extractvalue { ptr, <32 x i32>, i32 } %4, 2
  store <32 x i32> %6, ptr %s, align 128
  store i32 %7, ptr %pos1.i, align 64
  store ptr %5, ptr %p, align 4
  ret void
}

; Function Attrs: mustprogress nounwind memory(write, argmem: readwrite, inaccessiblemem: none)
define dso_local void @_Z31test_fifo_st_flush_conv_2d_byteRPDv64_DB8_R12fifo_state_tiiRii(ptr nocapture nonnull align 4 dereferenceable(4) %p, ptr nocapture nonnull align 64 dereferenceable(256) %s, i32 noundef %off, i32 noundef %size1, ptr nocapture nonnull align 4 dereferenceable(4) %count1, i32 noundef %inc1) local_unnamed_addr #2 {
; CHECK-LABEL: _Z31test_fifo_st_flush_conv_2d_byteRPDv64_DB8_R12fifo_state_tiiRii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    vlda sfh, [p1, #64]; nopb ; nopx
; CHECK-NEXT:    lda p4, [p0, #0]
; CHECK-NEXT:    lda dc0, [p2, #0]; mov dj1, #128
; CHECK-NEXT:    lda r26, [p1, dj1]
; CHECK-NEXT:    vlda sfl, [p1, #0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    movs p3, p2
; CHECK-NEXT:    movs m0, r0; mov dn0, r1
; CHECK-NEXT:    movs dj0, r2; mov p2, p4
; CHECK-NEXT:    vst.flush.512.2d [p2, sf, r26, d0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    st dc0, [p3, #0]; ret lr
; CHECK-NEXT:    st r26, [p1, dj1] // Delay Slot 5
; CHECK-NEXT:    vst sfh, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst sfl, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p2, [p0, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %pos1.i = getelementptr inbounds i8, ptr %s, i20 128
  %0 = load ptr, ptr %p, align 4, !tbaa !2
  %1 = load <32 x i32>, ptr %s, align 64, !tbaa !6
  %2 = load i32, ptr %pos1.i, align 64, !tbaa !7
  %3 = trunc i32 %off to i20
  %4 = trunc i32 %size1 to i20
  %5 = load i32, ptr %count1, align 4, !tbaa !7
  %6 = trunc i32 %5 to i20
  %7 = trunc i32 %inc1 to i20
  %8 = tail call { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d(ptr %0, <32 x i32> %1, i32 %2, i20 %3, i20 %4, i20 %6, i20 %7)
  %9 = extractvalue { ptr, <32 x i32>, i32, i20 } %8, 0
  %10 = extractvalue { ptr, <32 x i32>, i32, i20 } %8, 1
  %11 = extractvalue { ptr, <32 x i32>, i32, i20 } %8, 2
  %12 = extractvalue { ptr, <32 x i32>, i32, i20 } %8, 3
  %13 = zext i20 %12 to i32
  store i32 %13, ptr %count1, align 4
  store <32 x i32> %10, ptr %s, align 128
  store i32 %11, ptr %pos1.i, align 64
  store ptr %9, ptr %p, align 4
  ret void
}

; Function Attrs: mustprogress nounwind memory(write, argmem: readwrite, inaccessiblemem: none)
define dso_local void @_Z31test_fifo_st_flush_conv_3d_byteRPDv64_DB8_R12fifo_state_tiiRiiiS5_i(ptr nocapture nonnull align 4 dereferenceable(4) %p, ptr nocapture nonnull align 64 dereferenceable(256) %s, i32 noundef %off, i32 noundef %size1, ptr nocapture nonnull align 4 dereferenceable(4) %count1, i32 noundef %inc1, i32 noundef %size2, ptr nocapture nonnull align 4 dereferenceable(4) %count2, i32 noundef %inc2) local_unnamed_addr #2 {
; CHECK-LABEL: _Z31test_fifo_st_flush_conv_3d_byteRPDv64_DB8_R12fifo_state_tiiRiiiS5_i:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    lda p5, [p0, #0]; nopb ; nopx
; CHECK-NEXT:    lda dc0, [p2, #0]
; CHECK-NEXT:    lda dc4, [p3, #0]; mov dj1, #128
; CHECK-NEXT:    lda r26, [p1, dj1]
; CHECK-NEXT:    nop
; CHECK-NEXT:    vlda sfh, [p1, #64]
; CHECK-NEXT:    vlda sfl, [p1, #0]; movs p4, p2
; CHECK-NEXT:    movs m0, r0; mov dn0, r1
; CHECK-NEXT:    movs dj0, r2; mov dn4, r3
; CHECK-NEXT:    movs dj4, r4; mov p2, p5
; CHECK-NEXT:    vst.flush.512.conv.3d [p2, sf, r26, d0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    st dc0, [p4, #0]
; CHECK-NEXT:    st dc4, [p3, #0]; ret lr
; CHECK-NEXT:    st r26, [p1, dj1] // Delay Slot 5
; CHECK-NEXT:    vst sfh, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst sfl, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p2, [p0, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %pos1.i = getelementptr inbounds i8, ptr %s, i20 128
  %0 = load ptr, ptr %p, align 4, !tbaa !2
  %1 = load <32 x i32>, ptr %s, align 64, !tbaa !6
  %2 = load i32, ptr %pos1.i, align 64, !tbaa !7
  %3 = trunc i32 %off to i20
  %4 = trunc i32 %size1 to i20
  %5 = load i32, ptr %count1, align 4, !tbaa !7
  %6 = trunc i32 %5 to i20
  %7 = trunc i32 %inc1 to i20
  %8 = trunc i32 %size2 to i20
  %9 = load i32, ptr %count2, align 4, !tbaa !7
  %10 = trunc i32 %9 to i20
  %11 = trunc i32 %inc2 to i20
  %12 = tail call { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.conv(ptr %0, <32 x i32> %1, i32 %2, i20 %3, i20 %4, i20 %6, i20 %7, i20 %8, i20 %10, i20 %11)
  %13 = extractvalue { ptr, <32 x i32>, i32, i20, i20 } %12, 0
  %14 = extractvalue { ptr, <32 x i32>, i32, i20, i20 } %12, 1
  %15 = extractvalue { ptr, <32 x i32>, i32, i20, i20 } %12, 2
  %16 = extractvalue { ptr, <32 x i32>, i32, i20, i20 } %12, 3
  %17 = zext i20 %16 to i32
  %18 = extractvalue { ptr, <32 x i32>, i32, i20, i20 } %12, 4
  %19 = zext i20 %18 to i32
  store i32 %17, ptr %count1, align 4
  store i32 %19, ptr %count2, align 4
  store <32 x i32> %14, ptr %s, align 128
  store i32 %15, ptr %pos1.i, align 64
  store ptr %13, ptr %p, align 4
  ret void
}


; Function Attrs: mustprogress nounwind memory(write, argmem: readwrite, inaccessiblemem: none)
define dso_local void @test_fifo_st_reset_v64bfp16ebs16(ptr nocapture nonnull align 4 dereferenceable(4) %p, %struct.v64bfp16ebs16 %v.coerce, ptr nocapture nonnull align 64 dereferenceable(256) %s) local_unnamed_addr #2 {
; CHECK-LABEL: test_fifo_st_reset_v64bfp16ebs16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    vlda sfh, [p1, #64]; nopx
; CHECK-NEXT:    lda p2, [p0, #0]
; CHECK-NEXT:    vlda sfl, [p1, #0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    mova r26, #0
; CHECK-NEXT:    vst.push.544 ex0, [p2, sf, r26]; ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    vst sfh, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst sfl, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p2, [p0, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %v.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs16 %v.coerce, 0
  %v.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs16 %v.coerce, 1
  %0 = load ptr, ptr %p, align 4, !tbaa !2
  %1 = load <32 x i32>, ptr %s, align 64, !tbaa !6
  %2 = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.544.bfp16(ptr %0, <64 x i8> %v.coerce.fca.0.extract.i, <8 x i8> %v.coerce.fca.1.extract.i, <32 x i32> %1, i32 0)
  %3 = extractvalue { ptr, <32 x i32>, i32 } %2, 0
  %4 = extractvalue { ptr, <32 x i32>, i32 } %2, 1
  store <32 x i32> %4, ptr %s, align 128
  store ptr %3, ptr %p, align 4
  ret void
}

; Function Attrs: mustprogress nounwind memory(write, argmem: readwrite, inaccessiblemem: none)
define dso_local void @test_fifo_st_push_v64bfp16ebs16(ptr nocapture nonnull align 4 dereferenceable(4) %p, %struct.v64bfp16ebs16 %v.coerce, ptr nocapture nonnull align 64 dereferenceable(256) %s) local_unnamed_addr #2 {
; CHECK-LABEL: test_fifo_st_push_v64bfp16ebs16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    vlda sfh, [p1, #64]; nopb ; nopxm ; nops
; CHECK-NEXT:    lda p2, [p0, #0]; mov dj0, #128
; CHECK-NEXT:    lda r26, [p1, dj0]
; CHECK-NEXT:    vlda sfl, [p1, #0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst.push.544 ex0, [p2, sf, r26]
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    st r26, [p1, dj0] // Delay Slot 5
; CHECK-NEXT:    vst sfh, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst sfl, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p2, [p0, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %v.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs16 %v.coerce, 0
  %v.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs16 %v.coerce, 1
  %pos1.i = getelementptr inbounds i8, ptr %s, i20 128
  %0 = load ptr, ptr %p, align 4, !tbaa !2
  %1 = load <32 x i32>, ptr %s, align 64, !tbaa !6
  %2 = load i32, ptr %pos1.i, align 64, !tbaa !7
  %3 = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.544.bfp16(ptr %0, <64 x i8> %v.coerce.fca.0.extract.i, <8 x i8> %v.coerce.fca.1.extract.i, <32 x i32> %1, i32 %2)
  %4 = extractvalue { ptr, <32 x i32>, i32 } %3, 0
  %5 = extractvalue { ptr, <32 x i32>, i32 } %3, 1
  %6 = extractvalue { ptr, <32 x i32>, i32 } %3, 2
  store <32 x i32> %5, ptr %s, align 128
  store i32 %6, ptr %pos1.i, align 64
  store ptr %4, ptr %p, align 4
  ret void
}

; Function Attrs: mustprogress nounwind memory(write, argmem: readwrite, inaccessiblemem: none)
define dso_local void @test_fifo_st_reset_v64bfp16ebs8(ptr nocapture nonnull align 4 dereferenceable(4) %p, %struct.v64bfp16ebs8 %v.coerce, ptr nocapture nonnull align 64 dereferenceable(256) %s) local_unnamed_addr #2 {
; CHECK-LABEL: test_fifo_st_reset_v64bfp16ebs8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    vlda sfh, [p1, #64]; nopx
; CHECK-NEXT:    lda p2, [p0, #0]
; CHECK-NEXT:    vlda sfl, [p1, #0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    mova r26, #0
; CHECK-NEXT:    vst.push.576 ex0, [p2, sf, r26]; ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    vst sfh, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst sfl, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p2, [p0, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %v.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %v.coerce, 0
  %v.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %v.coerce, 1
  %0 = load ptr, ptr %p, align 4, !tbaa !2
  %1 = load <32 x i32>, ptr %s, align 64, !tbaa !6
  %2 = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.576.bfp16(ptr %0, <64 x i8> %v.coerce.fca.0.extract.i, <8 x i8> %v.coerce.fca.1.extract.i, <32 x i32> %1, i32 0)
  %3 = extractvalue { ptr, <32 x i32>, i32 } %2, 0
  %4 = extractvalue { ptr, <32 x i32>, i32 } %2, 1
  store <32 x i32> %4, ptr %s, align 128
  store ptr %3, ptr %p, align 4
  ret void
}

; Function Attrs: mustprogress nounwind memory(write, argmem: readwrite, inaccessiblemem: none)
define dso_local void @test_fifo_st_push_v64bfp16ebs8(ptr nocapture nonnull align 4 dereferenceable(4) %p, %struct.v64bfp16ebs8 %v.coerce, ptr nocapture nonnull align 64 dereferenceable(256) %s) local_unnamed_addr #2 {
; CHECK-LABEL: test_fifo_st_push_v64bfp16ebs8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    vlda sfh, [p1, #64]; nopb ; nopxm ; nops
; CHECK-NEXT:    lda p2, [p0, #0]; mov dj0, #128
; CHECK-NEXT:    lda r26, [p1, dj0]
; CHECK-NEXT:    vlda sfl, [p1, #0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst.push.576 ex0, [p2, sf, r26]
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    st r26, [p1, dj0] // Delay Slot 5
; CHECK-NEXT:    vst sfh, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst sfl, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p2, [p0, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %v.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %v.coerce, 0
  %v.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %v.coerce, 1
  %pos1.i = getelementptr inbounds i8, ptr %s, i20 128
  %0 = load ptr, ptr %p, align 4, !tbaa !2
  %1 = load <32 x i32>, ptr %s, align 64, !tbaa !6
  %2 = load i32, ptr %pos1.i, align 64, !tbaa !7
  %3 = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.576.bfp16(ptr %0, <64 x i8> %v.coerce.fca.0.extract.i, <8 x i8> %v.coerce.fca.1.extract.i, <32 x i32> %1, i32 %2)
  %4 = extractvalue { ptr, <32 x i32>, i32 } %3, 0
  %5 = extractvalue { ptr, <32 x i32>, i32 } %3, 1
  %6 = extractvalue { ptr, <32 x i32>, i32 } %3, 2
  store <32 x i32> %5, ptr %s, align 128
  store i32 %6, ptr %pos1.i, align 64
  store ptr %4, ptr %p, align 4
  ret void
}


define dso_local void @_Z17test_fifo_st_pushRrP23v128bfp16ebs8_unaligned13v128bfp16ebs8R12fifo_state_t(ptr nocapture nonnull align 4 dereferenceable(4) %p, %struct.v128bfp16ebs8 %v.coerce, ptr nocapture nonnull align 64 dereferenceable(256) %s) local_unnamed_addr #1 {
; CHECK-LABEL: _Z17test_fifo_st_pushRrP23v128bfp16ebs8_unaligned13v128bfp16ebs8R12fifo_state_t:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    vlda sfh, [p1, #64]; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    lda p2, [p0, #0]; mov dj0, #128
; CHECK-NEXT:    lda r26, [p1, dj0]; nopx
; CHECK-NEXT:    vlda sfl, [p1, #0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst.push.576 ex0, [p2, sf, r26]
; CHECK-NEXT:    nop
; CHECK-NEXT:    st r26, [p1, dj0]
; CHECK-NEXT:    vst sfh, [p1, #64]
; CHECK-NEXT:    vst sfl, [p1, #0]
; CHECK-NEXT:    st p2, [p0, #0]
; CHECK-NEXT:    vlda sfh, [p1, #64]
; CHECK-NEXT:    lda r26, [p1, dj0]
; CHECK-NEXT:    vlda sfl, [p1, #0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst.push.576 ex1, [p2, sf, r26]
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    st r26, [p1, dj0] // Delay Slot 5
; CHECK-NEXT:    vst sfh, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst sfl, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p2, [p0, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %m.coerce.fca.2.extract.i.i = extractvalue %struct.v128bfp16ebs8 %v.coerce, 2
  %m.coerce.fca.0.extract.i.i = extractvalue %struct.v128bfp16ebs8 %v.coerce, 0
  %pos1.i.i = getelementptr inbounds i8, ptr %s, i20 128
  %0 = load ptr, ptr %p, align 4, !tbaa !7
  %1 = load <32 x i32>, ptr %s, align 64
  %2 = load i32, ptr %pos1.i.i, align 64
  %3 = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.576.bfp16.p0.p0(ptr %0, <64 x i8> %m.coerce.fca.0.extract.i.i, <8 x i8> %m.coerce.fca.2.extract.i.i, <32 x i32> %1, i32 %2)
  %4 = extractvalue { ptr, <32 x i32>, i32 } %3, 0
  %5 = extractvalue { ptr, <32 x i32>, i32 } %3, 1
  %6 = extractvalue { ptr, <32 x i32>, i32 } %3, 2
  store <32 x i32> %5, ptr %s, align 128
  store i32 %6, ptr %pos1.i.i, align 64
  store ptr %4, ptr %p, align 4
  %m.coerce.fca.3.extract.i25.i = extractvalue %struct.v128bfp16ebs8 %v.coerce, 3
  %m.coerce.fca.1.extract.i26.i = extractvalue %struct.v128bfp16ebs8 %v.coerce, 1
  %7 = load <32 x i32>, ptr %s, align 64
  %8 = load i32, ptr %pos1.i.i, align 64
  %9 = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.576.bfp16.p0.p0(ptr %4, <64 x i8> %m.coerce.fca.1.extract.i26.i, <8 x i8> %m.coerce.fca.3.extract.i25.i, <32 x i32> %7, i32 %8)
  %10 = extractvalue { ptr, <32 x i32>, i32 } %9, 0
  %11 = extractvalue { ptr, <32 x i32>, i32 } %9, 1
  %12 = extractvalue { ptr, <32 x i32>, i32 } %9, 2
  store <32 x i32> %11, ptr %s, align 128
  store i32 %12, ptr %pos1.i.i, align 64
  store ptr %10, ptr %p, align 4
  ret void
}

define dso_local void @_Z18test_fifo_st_flushRrP23v128bfp16ebs8_unalignedR12fifo_state_t(ptr nocapture nonnull align 4 dereferenceable(4) %p, ptr nocapture nonnull align 64 dereferenceable(256) %s) local_unnamed_addr #1 {
; CHECK-LABEL: _Z18test_fifo_st_flushRrP23v128bfp16ebs8_unalignedR12fifo_state_t:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    vlda sfh, [p1, #64]; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    lda p2, [p0, #0]; mov dj0, #128
; CHECK-NEXT:    lda r26, [p1, dj0]; nopx
; CHECK-NEXT:    vlda sfl, [p1, #0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst.flush.512 [p2, sf, r26]
; CHECK-NEXT:    nop
; CHECK-NEXT:    st r26, [p1, dj0]
; CHECK-NEXT:    vst sfh, [p1, #64]
; CHECK-NEXT:    vst sfl, [p1, #0]
; CHECK-NEXT:    st p2, [p0, #0]
; CHECK-NEXT:    vlda sfh, [p1, #64]
; CHECK-NEXT:    lda r26, [p1, dj0]
; CHECK-NEXT:    vlda sfl, [p1, #0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst.flush.512 [p2, sf, r26]
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    st r26, [p1, dj0] // Delay Slot 5
; CHECK-NEXT:    vst sfh, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst sfl, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p2, [p0, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %pos1.i.i = getelementptr inbounds i8, ptr %s, i20 128
  %0 = load ptr, ptr %p, align 4, !tbaa !7
  %1 = load <32 x i32>, ptr %s, align 64
  %2 = load i32, ptr %pos1.i.i, align 64
  %3 = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr %0, <32 x i32> %1, i32 %2)
  %4 = extractvalue { ptr, <32 x i32>, i32 } %3, 0
  %5 = extractvalue { ptr, <32 x i32>, i32 } %3, 1
  %6 = extractvalue { ptr, <32 x i32>, i32 } %3, 2
  store <32 x i32> %5, ptr %s, align 128
  store i32 %6, ptr %pos1.i.i, align 64
  store ptr %4, ptr %p, align 4
  %7 = load <32 x i32>, ptr %s, align 64
  %8 = load i32, ptr %pos1.i.i, align 64
  %9 = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr %4, <32 x i32> %7, i32 %8)
  %10 = extractvalue { ptr, <32 x i32>, i32 } %9, 0
  %11 = extractvalue { ptr, <32 x i32>, i32 } %9, 1
  %12 = extractvalue { ptr, <32 x i32>, i32 } %9, 2
  store <32 x i32> %11, ptr %s, align 128
  store i32 %12, ptr %pos1.i.i, align 64
  store ptr %10, ptr %p, align 4
  ret void
}

define dso_local void @_Z26test_fifo_st_flush_1d_byteRrP23v128bfp16ebs8_unalignedR12fifo_state_ti(ptr nocapture nonnull align 4 dereferenceable(4) %p, ptr nocapture nonnull align 64 dereferenceable(256) %s, i32 noundef %off) local_unnamed_addr #1 {
; CHECK-LABEL: _Z26test_fifo_st_flush_1d_byteRrP23v128bfp16ebs8_unalignedR12fifo_state_ti:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    vlda sfh, [p1, #64]; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    lda p2, [p0, #0]; mov dj0, #128
; CHECK-NEXT:    lda r26, [p1, dj0]
; CHECK-NEXT:    vlda sfl, [p1, #0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vst.flush.512 [p2, sf, r26]
; CHECK-NEXT:    nop
; CHECK-NEXT:    st r26, [p1, dj0]
; CHECK-NEXT:    vst sfh, [p1, #64]
; CHECK-NEXT:    vst sfl, [p1, #0]
; CHECK-NEXT:    st p2, [p0, #0]
; CHECK-NEXT:    vlda sfh, [p1, #64]
; CHECK-NEXT:    lda r26, [p1, dj0]
; CHECK-NEXT:    vlda sfl, [p1, #0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    mov m0, r0
; CHECK-NEXT:    vst.flush.512 [p2, sf, r26, m0]
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    st r26, [p1, dj0] // Delay Slot 5
; CHECK-NEXT:    vst sfh, [p1, #64] // Delay Slot 4
; CHECK-NEXT:    vst sfl, [p1, #0] // Delay Slot 3
; CHECK-NEXT:    st p2, [p0, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %pos1.i.i = getelementptr inbounds i8, ptr %s, i20 128
  %0 = load ptr, ptr %p, align 4, !tbaa !7
  %1 = load <32 x i32>, ptr %s, align 64
  %2 = load i32, ptr %pos1.i.i, align 64
  %3 = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.p0.p0(ptr %0, <32 x i32> %1, i32 %2)
  %4 = extractvalue { ptr, <32 x i32>, i32 } %3, 0
  %5 = extractvalue { ptr, <32 x i32>, i32 } %3, 1
  %6 = extractvalue { ptr, <32 x i32>, i32 } %3, 2
  store <32 x i32> %5, ptr %s, align 128
  store i32 %6, ptr %pos1.i.i, align 64
  store ptr %4, ptr %p, align 4
  %7 = load <32 x i32>, ptr %s, align 64
  %8 = load i32, ptr %pos1.i.i, align 64
  %9 = trunc i32 %off to i20
  %10 = tail call { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.p0.p0(ptr %4, <32 x i32> %7, i32 %8, i20 %9)
  %11 = extractvalue { ptr, <32 x i32>, i32 } %10, 0
  %12 = extractvalue { ptr, <32 x i32>, i32 } %10, 1
  %13 = extractvalue { ptr, <32 x i32>, i32 } %10, 2
  store <32 x i32> %12, ptr %s, align 128
  store i32 %13, ptr %pos1.i.i, align 64
  store ptr %11, ptr %p, align 4
  ret void
}

; Function Attrs: nofree nounwind memory(inaccessiblemem: read)
declare <32 x i8> @llvm.aie2p.pack.I512.I8.I16(<32 x i16>, i32) #3

; Function Attrs: nofree nosync nounwind memory(none)
declare <32 x i16> @llvm.aie2p.unpack.I512.I16.I8(<32 x i8>, i32) #4

; Function Attrs: nofree nounwind memory(inaccessiblemem: read)
declare <32 x i8> @llvm.aie2p.pack.I512.I4.I8(<64 x i8>, i32) #3

; Function Attrs: nofree nosync nounwind memory(none)
declare <64 x i8> @llvm.aie2p.unpack.I512.I8.I4(<32 x i8>, i32) #4

; Function Attrs: nofree nounwind memory(inaccessiblemem: read)
declare <64 x i8> @llvm.aie2p.pack.I1024.I8.I16(<64 x i16>, i32) #3

; Function Attrs: nofree nosync nounwind memory(none)
declare <64 x i16> @llvm.aie2p.unpack.I1024.I16.I8(<64 x i8>, i32) #4

; Function Attrs: nofree nounwind memory(inaccessiblemem: read)
declare <64 x i8> @llvm.aie2p.pack.I1024.I4.I8(<128 x i8>, i32) #3

; Function Attrs: nofree nosync nounwind memory(none)
declare <128 x i8> @llvm.aie2p.unpack.I1024.I8.I4(<64 x i8>, i32) #4

; Function Attrs: nounwind memory(argmem: write)
declare { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.512.bfp16(ptr, <16 x i32>, <32 x i32>, i32) #5

; Function Attrs: nounwind memory(argmem: write)
declare { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush(ptr, <32 x i32>, i32) #5

; Function Attrs: nounwind memory(argmem: write)
declare { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d(ptr, <32 x i32>, i32, i20) #5

; Function Attrs: nounwind memory(argmem: write)
declare { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d.conv(ptr, <32 x i32>, i32, i20, i20, i20, i20) #5

; Function Attrs: nounwind memory(argmem: write)
declare { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d(ptr, <32 x i32>, i32, i20, i20, i20, i20, i20, i20, i20) #5

; Function Attrs: nounwind memory(argmem: write)
declare { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.conv(ptr, <32 x i32>, i32) #5

; Function Attrs: nounwind memory(argmem: write)
declare { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.flush.1d.conv(ptr, <32 x i32>, i32, i20) #5

; Function Attrs: nounwind memory(argmem: write)
declare { ptr, <32 x i32>, i32, i20 } @llvm.aie2p.fifo.st.flush.2d(ptr, <32 x i32>, i32, i20, i20, i20, i20) #5

; Function Attrs: nounwind memory(argmem: write)
declare { ptr, <32 x i32>, i32, i20, i20 } @llvm.aie2p.fifo.st.flush.3d.conv(ptr, <32 x i32>, i32, i20, i20, i20, i20, i20, i20, i20) #5

; Function Attrs: nounwind memory(argmem: write)
declare { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.576.bfp16(ptr, <64 x i8>, <8 x i8>, <32 x i32>, i32) #5

; Function Attrs: nounwind memory(argmem: write)
declare { ptr, <32 x i32>, i32 } @llvm.aie2p.fifo.st.push.544.bfp16(ptr, <64 x i8>, <8 x i8>, <32 x i32>, i32) #5



!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{!"clang version 19.0.0git (git@gitenterprise.xilinx.com:XRLabs/llvm-aie.git 7712cc9eca3c28aba4de6f89a2124b1130c2ec6d)"}
!2 = !{!3, !3, i64 0}
!3 = !{!"any pointer", !4, i64 0}
!4 = !{!"omnipotent char", !5, i64 0}
!5 = !{!"Simple C++ TBAA"}
!6 = !{!4, !4, i64 0}
!7 = !{!8, !8, i64 0}
!8 = !{!"int", !4, i64 0}
