; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie2p --issue-limit=1 < %s | FileCheck %s

target triple = "aie2p"

; TODO: Add similar 1024-/2048-bit types load/store end-to-end test when we have ISel support

; Function Attrs: mustprogress noinline nounwind optnone
define dso_local void @test_load_store_aligned(<8 x i16> noundef %a, <4 x i32> noundef %b, <16 x i8> noundef %c, <16 x i16> noundef %d, <8 x i32> noundef %e, <4 x i64> inreg noundef %f, <8 x i64> inreg noundef %g, <16 x i32> noundef %h) #0 {
; CHECK-LABEL: test_load_store_aligned:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopx ; vmov q0, wl0
; CHECK-NEXT:    paddxm [sp], #768
; CHECK-NEXT:    vmov x1, bmll0
; CHECK-NEXT:    vst wl6, [sp, #-704]
; CHECK-NEXT:    vst wl8, [sp, #-640]
; CHECK-NEXT:    vst bmll1, [sp, #-512]
; CHECK-NEXT:    vst x10, [sp, #-448]
; CHECK-NEXT:    vmov wh0, q0
; CHECK-NEXT:    vst wl1, [sp, #-576]
; CHECK-NEXT:    vmov q0, wl2
; CHECK-NEXT:    vlda bmll0, [sp, #-512]
; CHECK-NEXT:    vmov wh2, q0
; CHECK-NEXT:    vmov q0, wl4
; CHECK-NEXT:    vst.128 wh0, [sp, #-768]
; CHECK-NEXT:    vlda.128 wh0, [sp, #-768]
; CHECK-NEXT:    vmov wh4, q0
; CHECK-NEXT:    vst.128 wh2, [sp, #-752]
; CHECK-NEXT:    vst.128 wh4, [sp, #-736]
; CHECK-NEXT:    vst bmll0, [sp, #-128]
; CHECK-NEXT:    vlda.128 wh0, [sp, #-752]
; CHECK-NEXT:    vlda.128 wh0, [sp, #-736]
; CHECK-NEXT:    vlda wh0, [sp, #-704]
; CHECK-NEXT:    vst.128 wh0, [sp, #-384]
; CHECK-NEXT:    vlda wh0, [sp, #-640]
; CHECK-NEXT:    vlda wh0, [sp, #-576]
; CHECK-NEXT:    vlda x0, [sp, #-448]
; CHECK-NEXT:    vst.128 wh0, [sp, #-368]
; CHECK-NEXT:    vst.128 wh0, [sp, #-352]
; CHECK-NEXT:    vst wh0, [sp, #-320]
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    vst wh0, [sp, #-256] // Delay Slot 5
; CHECK-NEXT:    vst wh0, [sp, #-192] // Delay Slot 4
; CHECK-NEXT:    vst x0, [sp, #-64] // Delay Slot 3
; CHECK-NEXT:    paddxm [sp], #-768 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.addr = alloca <8 x i16>, align 16
  %b.addr = alloca <4 x i32>, align 16
  %c.addr = alloca <16 x i8>, align 16
  %d.addr = alloca <16 x i16>, align 64
  %e.addr = alloca <8 x i32>, align 64
  %f.addr = alloca <4 x i64>, align 64
  %g.addr = alloca <8 x i64>, align 64
  %h.addr = alloca <16 x i32>, align 64
  %aa = alloca <8 x i16>, align 16
  %bb = alloca <4 x i32>, align 16
  %cc = alloca <16 x i8>, align 16
  %dd = alloca <16 x i16>, align 64
  %ee = alloca <8 x i32>, align 64
  %ff = alloca <4 x i64>, align 64
  %gg = alloca <8 x i64>, align 64
  %hh = alloca <16 x i32>, align 64
  store <8 x i16> %a, ptr %a.addr, align 16
  store <4 x i32> %b, ptr %b.addr, align 16
  store <16 x i8> %c, ptr %c.addr, align 16
  store <16 x i16> %d, ptr %d.addr, align 64
  store <8 x i32> %e, ptr %e.addr, align 64
  store <4 x i64> %f, ptr %f.addr, align 64
  store <8 x i64> %g, ptr %g.addr, align 64
  store <16 x i32> %h, ptr %h.addr, align 64
  %0 = load <8 x i16>, ptr %a.addr, align 16
  store <8 x i16> %0, ptr %aa, align 16
  %1 = load <4 x i32>, ptr %b.addr, align 16
  store <4 x i32> %1, ptr %bb, align 16
  %2 = load <16 x i8>, ptr %c.addr, align 16
  store <16 x i8> %2, ptr %cc, align 16
  %3 = load <16 x i16>, ptr %d.addr, align 64
  store <16 x i16> %3, ptr %dd, align 64
  %4 = load <8 x i32>, ptr %e.addr, align 64
  store <8 x i32> %4, ptr %ee, align 64
  %5 = load <4 x i64>, ptr %f.addr, align 64
  store <4 x i64> %5, ptr %ff, align 64
  %6 = load <8 x i64>, ptr %g.addr, align 64
  store <8 x i64> %6, ptr %gg, align 64
  %7 = load <16 x i32>, ptr %h.addr, align 64
  store <16 x i32> %7, ptr %hh, align 64
  ret void
}

attributes #0 = { mustprogress noinline nounwind optnone "no-trapping-math"="true" "stack-protector-buffer-size"="8" }

