; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie2p -verify-machineinstrs -o - < %s | FileCheck %s

define dso_local noundef float @_Z11test__sqrtff(float noundef %a)  {
; CHECK-LABEL: _Z11test__sqrtff:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    sqrt r0, r1 // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call noundef float @llvm.aie2p.sqrtf(float %a)
  ret float %0
}

define dso_local noundef float @_Z8test_invf(float noundef %a)  {
; CHECK-LABEL: _Z8test_invf:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    inv r0, r1 // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call noundef float @llvm.aie2p.inv(float %a)
  ret float %0
}

define dso_local noundef float @_Z12test_invsqrtf(float noundef %a)  {
; CHECK-LABEL: _Z12test_invsqrtf:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    invsqrt r0, r1 // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call noundef float @llvm.aie2p.invsqrt(float %a)
  ret float %0
}

define dso_local noundef <16 x bfloat> @_Z9test_exp2Dv16_u10__accfloat(<16 x float> inreg noundef %a)  {
; CHECK-LABEL: _Z9test_exp2Dv16_u10__accfloat:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vexp2 wl0, bmll0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call noundef <16 x bfloat> @llvm.aie2p.exp2(<16 x float> %a)
  ret <16 x bfloat> %0
}

define dso_local noundef <16 x bfloat> @_Z9test_exp2Dv16_f(<16 x float> noundef %a)  {
; CHECK-LABEL: _Z9test_exp2Dv16_f:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    vmov bmll0, x2 // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vexp2 wl0, bmll0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call noundef <16 x bfloat> @llvm.aie2p.exp2(<16 x float> %a)
  ret <16 x bfloat> %0
}

define dso_local noundef <16 x bfloat> @_Z9test_tanhDv16_u10__accfloat(<16 x float> inreg noundef %a)  {
; CHECK-LABEL: _Z9test_tanhDv16_u10__accfloat:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vtanh wl0, bmll0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call noundef <16 x bfloat> @llvm.aie2p.tanh(<16 x float> %a)
  ret <16 x bfloat> %0
}

define dso_local noundef <16 x bfloat> @_Z9test_tanhDv16_f(<16 x float> noundef %a)  {
; CHECK-LABEL: _Z9test_tanhDv16_f:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    vmov bmll0, x2 // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vtanh wl0, bmll0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call noundef <16 x bfloat> @llvm.aie2p.tanh(<16 x float> %a)
  ret <16 x bfloat> %0
}

declare float @llvm.aie2p.sqrtf(float)
declare float @llvm.aie2p.inv(float)
declare float @llvm.aie2p.invsqrt(float)
declare <16 x bfloat> @llvm.aie2p.exp2(<16 x float>)
declare <16 x bfloat> @llvm.aie2p.tanh(<16 x float>)
