; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -O2 -mtriple=aie2p %s -o - | FileCheck %s

define void @preserve_read_tm(i32 %channel) {
; CHECK-LABEL: preserve_read_tm:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    movxm r1, #524288
; CHECK-NEXT:    nopa ; xor r0, r0, r1
; CHECK-NEXT:    mov p0, r0
; CHECK-NEXT:  .LBB0_1: // %while.cond
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    lda.tm r0, [p0, #0]; nopx
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    jnz r0, #.LBB0_1
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
; CHECK-NEXT:  // %bb.2: // %while.end
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = xor i32 %channel, 524288
  %conv.i = trunc i32 %0 to i20
  %1 = inttoptr i20 %conv.i to ptr
  br label %while.cond

while.cond:
  %2 = tail call noundef i32 @llvm.aie2p.read.tm(ptr %1)
  %cmp.not = icmp eq i32 %2, 0
  br i1 %cmp.not, label %while.end, label %while.cond

while.end:
  ret void
}

declare i32 @llvm.aie2p.read.tm(ptr)
