# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2p -run-pass=reserved-reg-licm %s -verify-machineinstrs -o - \
# RUN:    | FileCheck %s


---
name:            pack_dyn_sign_loop
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: pack_dyn_sign_loop
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $r0, $r1, $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:er = COPY $r0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:ep = COPY $p0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:er = COPY $r1
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:mxs = COPY $x0
  ; CHECK-NEXT:   $packsign0 = COPY [[COPY2]]
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   $packsign0 = MOV_scalar_imm11_pseudo 0
  ; CHECK-NEXT:   PseudoRET implicit $lr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.2(0x7c000000), %bb.1(0x04000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   VST_PACK_dmw_sts_pack_idx_imm_packSign0 [[COPY3]], [[COPY1]], 0, implicit $crpacksize, implicit $crsat, implicit $packsign0
  ; CHECK-NEXT:   PseudoJNZ [[COPY]], %bb.2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  bb.0:
    successors: %bb.2(0x80000000)
    liveins: $p0, $r0, $r1, $x0
    %0:er = COPY $r0
    %1:ep = COPY $p0
    %2:er = COPY $r1
    %3:mxs = COPY $x0
    PseudoJ_jump_imm %bb.2

  bb.1:
    PseudoRET implicit $lr

  bb.2:
    successors: %bb.2(0x7c000000), %bb.1(0x04000000)
    $packsign0 = COPY %2
    VST_PACK_dmw_sts_pack_idx_imm_packSign0 %3, %1, 0, implicit $crpacksize, implicit $crsat, implicit $packsign0
    $packsign0 = MOV_scalar_imm11_pseudo 0
    PseudoJNZ %0, %bb.2
    PseudoJ_jump_imm %bb.1
...

# Similar to above, but the loop has no dedicated exit.
# A dedicated exit block should be created.
---
name:            pack_dyn_sign_loop_no_dedicated_exit
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: pack_dyn_sign_loop_no_dedicated_exit
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; CHECK-NEXT:   liveins: $p0, $r0, $r1, $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:er = COPY $r0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:ep = COPY $p0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:er = COPY $r1
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:mxs = COPY $x0
  ; CHECK-NEXT:   PseudoJNZ [[COPY]], %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   PseudoRET implicit $lr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $packsign0 = COPY [[COPY2]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.3(0x40000000), %bb.4(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   VST_PACK_dmw_sts_pack_idx_imm_packSign0 [[COPY3]], [[COPY1]], 0, implicit $crpacksize, implicit $crsat, implicit $packsign0
  ; CHECK-NEXT:   PseudoJNZ [[COPY]], %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $packsign0 = MOV_scalar_imm11_pseudo 0
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  bb.0:
    successors: %bb.3, %bb.1
    liveins: $p0, $r0, $r1, $x0
    %0:er = COPY $r0
    %1:ep = COPY $p0
    %2:er = COPY $r1
    %3:mxs = COPY $x0
    PseudoJNZ %0, %bb.3

  bb.1:
    PseudoRET implicit $lr

  bb.3:
    successors: %bb.2

  bb.2:
    successors: %bb.2, %bb.1
    $packsign0 = COPY %2
    VST_PACK_dmw_sts_pack_idx_imm_packSign0 %3, %1, 0, implicit $crpacksize, implicit $crsat, implicit $packsign0
    $packsign0 = MOV_scalar_imm11_pseudo 0
    PseudoJNZ %0, %bb.2
    PseudoJ_jump_imm %bb.1
...

---
name:            pack_dyn_sign_nested_loop
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: pack_dyn_sign_nested_loop
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $r0, $r1, $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:er = COPY $r0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:ep = COPY $p0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:er = COPY $r1
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:mxs = COPY $x0
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $packsign0 = COPY [[COPY2]]
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   VST_PACK_dmw_sts_pack_idx_imm_packSign0 [[COPY3]], [[COPY1]], 0, implicit $crpacksize, implicit $crsat, implicit $packsign0
  ; CHECK-NEXT:   PseudoJNZ [[COPY]], %bb.2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.4(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $packsign0 = MOV_scalar_imm11_pseudo 0
  ; CHECK-NEXT:   PseudoJNZ [[COPY]], %bb.1
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.0:
    liveins: $p0, $r0, $r1, $x0
    %0:er = COPY $r0
    %1:ep = COPY $p0
    %2:er = COPY $r1
    %3:mxs = COPY $x0
    PseudoJ_jump_imm %bb.1

  bb.1:
    PseudoJ_jump_imm %bb.2

  bb.2:
    $packsign0 = COPY %2
    VST_PACK_dmw_sts_pack_idx_imm_packSign0 %3, %1, 0, implicit $crpacksize, implicit $crsat, implicit $packsign0
    $packsign0 = MOV_scalar_imm11_pseudo 0
    PseudoJNZ %0, %bb.2
    PseudoJ_jump_imm %bb.3

  bb.3:
    PseudoJNZ %0, %bb.1
    PseudoJ_jump_imm %bb.4

  bb.4:
    PseudoRET implicit $lr

...

# $packsign0 has different live values within the loop, no hoisting
---
name:            pack_dyn_sign_different_assign
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: pack_dyn_sign_different_assign
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $r0, $r1, $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:er = COPY $r0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:ep = COPY $p0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:er = COPY $r1
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:mxs = COPY $x0
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   PseudoRET implicit $lr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.2(0x7c000000), %bb.1(0x04000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $packsign0 = COPY [[COPY2]]
  ; CHECK-NEXT:   VST_PACK_dmw_sts_pack_idx_imm_packSign0 [[COPY3]], [[COPY1]], 0, implicit $crpacksize, implicit $crsat, implicit $packsign0
  ; CHECK-NEXT:   $packsign0 = MOV_scalar_imm11_pseudo 0
  ; CHECK-NEXT:   VST_PACK_dmw_sts_pack_idx_imm_packSign0 [[COPY3]], [[COPY1]], 0, implicit $crpacksize, implicit $crsat, implicit $packsign0
  ; CHECK-NEXT:   PseudoJNZ [[COPY]], %bb.2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  bb.0:
    successors: %bb.2(0x80000000)
    liveins: $p0, $r0, $r1, $x0
    %0:er = COPY $r0
    %1:ep = COPY $p0
    %2:er = COPY $r1
    %3:mxs = COPY $x0
    PseudoJ_jump_imm %bb.2

  bb.1:
    PseudoRET implicit $lr

  bb.2:
    successors: %bb.2(0x7c000000), %bb.1(0x04000000)
    $packsign0 = COPY %2
    VST_PACK_dmw_sts_pack_idx_imm_packSign0 %3, %1, 0, implicit $crpacksize, implicit $crsat, implicit $packsign0
    $packsign0 = MOV_scalar_imm11_pseudo 0
    VST_PACK_dmw_sts_pack_idx_imm_packSign0 %3, %1, 0, implicit $crpacksize, implicit $crsat, implicit $packsign0
    PseudoJNZ %0, %bb.2
    PseudoJ_jump_imm %bb.1
...

# Verify that non-reserved physical registers aren't considered for LICM
---
name:            test_is_simplifiable_reserved_reg
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: test_is_simplifiable_reserved_reg
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT:   liveins: $r0, $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:er = COPY $r0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:mxs = COPY $x0
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   PseudoRET implicit $lr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.2(0x7c000000), %bb.1(0x04000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $x0 = COPY [[COPY1]]
  ; CHECK-NEXT:   PseudoJNZ [[COPY]], %bb.2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  bb.0:
    successors: %bb.2(0x80000000)
    liveins: $r0, $x0
    %0:er = COPY $r0
    %1:mxs = COPY $x0
    PseudoJ_jump_imm %bb.2

  bb.1:
    PseudoRET implicit $lr

  bb.2:
    successors: %bb.2(0x7c000000), %bb.1(0x04000000)
    $x0 = COPY %1
    PseudoJNZ %0, %bb.2
    PseudoJ_jump_imm %bb.1
...
