# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024-2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2p -run-pass postrapseudos -verify-machineinstrs -o - %s | FileCheck %s

# Verify AIE2PInstrInfo.cpp: copyPhysReg()

---
name:     test_copy_d
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_d
    ; CHECK: $m1 = MOV_scalar_pseudo $m2
    ; CHECK-NEXT: $dn1 = MOV_scalar_pseudo $dn2
    ; CHECK-NEXT: $dj1 = MOV_scalar_pseudo $dj2
    ; CHECK-NEXT: $dc1 = MOV_scalar_pseudo $dc2
  $d1 = COPY $d2
...

---
name:     test_copy_ds
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_ds
    ; CHECK: $m1 = MOV_scalar_pseudo $m2
    ; CHECK-NEXT: $dn1 = MOV_scalar_pseudo $dn2
    ; CHECK-NEXT: $dj1 = MOV_scalar_pseudo $dj2
    ; CHECK-NEXT: $dc1 = MOV_scalar_pseudo $dc2
    ; CHECK-NEXT: $m5 = MOV_scalar_pseudo $m6
    ; CHECK-NEXT: $dn5 = MOV_scalar_pseudo $dn6
    ; CHECK-NEXT: $dj5 = MOV_scalar_pseudo $dj6
    ; CHECK-NEXT: $dc5 = MOV_scalar_pseudo $dc6
  $d1_3d = COPY $d2_3d
...

---
name:     test_copy_w
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_w
    ; CHECK: $wh0 = VMOV_alu_mv_mv_w $wh1
    ; CHECK-NEXT: $wl1 = VMOV_alu_mv_mv_w $wh2
    ; CHECK-NEXT: $wh11 = VMOV_alu_mv_mv_w $wl10
  $wh0 = COPY $wh1
  $wl1 = COPY $wh2
  $wh11 = COPY $wl10
...

---
name:             test_copy_x
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_x
    ; CHECK: $x1 = VMOV_alu_mv_mv_x $x4
    ; CHECK-NEXT: $x2 = VMOV_alu_mv_mv_x $x3
    ; CHECK-NEXT: $x10 = VMOV_alu_mv_mv_x $x8
    ; CHECK-NEXT: $x3 = VMOV_alu_mv_mv_x $bmll0
    ; CHECK-NEXT: $x4 = VMOV_alu_mv_mv_x $bmhh3
    ; CHECK-NEXT: $bmhh2 = VMOV_alu_mv_mv_x $x1
    ; CHECK-NEXT: $bmll1 = VMOV_alu_mv_mv_x $x2
    ; CHECK-NEXT: $bmll3 = VMOV_alu_mv_mv_x $bmll0
    ; CHECK-NEXT: $bmhh4 = VMOV_alu_mv_mv_x $bmhh3
  $x1 = COPY $x4
  $x2 = COPY $x3
  $x10 = COPY $x8
  $x3 = COPY $bmll0
  $x4 = COPY $bmhh3
  $bmhh2 = COPY $x1
  $bmll1 = COPY $x2
  $bmll3 = COPY $bmll0
  $bmhh4 = COPY $bmhh3
...

---
name:             test_copy_cml
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_cml
    ; CHECK: $cml1 = VMOV_alu_mv_mv_cm $cml4
    ; CHECK-NEXT: $cml2 = VMOV_alu_mv_mv_cm $cml3
  $cml1 = COPY $cml4
  $cml2 = COPY $cml3
...

---
name:             test_copy_dm
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_dm
    ; CHECK: $dm1 = VMOV_D $dm2
    ; CHECK-NEXT: $dm2 = VMOV_D $dm3
  $dm1 = COPY $dm2
  $dm2 = COPY $dm3
...

---
name:            test_copy_y
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_y
    ; CHECK: $x4 = VMOV_alu_mv_mv_x $x8
    ; CHECK-NEXT: $x5 = VMOV_alu_mv_mv_x $x9
    ; CHECK-NEXT: $x6 = VMOV_alu_mv_mv_x $x10
    ; CHECK-NEXT: $x7 = VMOV_alu_mv_mv_x $x11
  $y2 = COPY $y4
  $y3 = COPY $y5
...

---
name:             test_copy_lf0
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_lf0
    ; CHECK: $lfl1 = VMOV_alu_mv_mv_x $x4
    ; CHECK-NEXT: $lfh0 = VMOV_alu_mv_mv_x $lfl1
    ; CHECK-NEXT: $x10 = VMOV_alu_mv_mv_x $lfh1
    ; CHECK-NEXT: $bmhh2 = VMOV_alu_mv_mv_x $lfl0
    ; CHECK-NEXT: $lfl0 = VMOV_alu_mv_mv_x $bmhh2
    ; CHECK-NEXT: $x10 = VMOV_alu_mv_mv_x $lfe
    ; CHECK-NEXT: $bmhh2 = VMOV_alu_mv_mv_x $lfe
    ; CHECK-NEXT: $lfe = VMOV_alu_mv_mv_x $bmhh2
    ; CHECK-NEXT: $lfe = VMOV_alu_mv_mv_x $lfl1
  $lfl1 = COPY $x4
  $lfh0 = COPY $lfl1
  $x10 = COPY $lfh1
  $bmhh2 = COPY $lfl0
  $lfl0 = COPY $bmhh2
  $x10 = COPY $lfe
  $bmhh2 = COPY $lfe
  $lfe = COPY $bmhh2
  $lfe = COPY $lfl1
...

---
name:            test_copy_lf
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_lf
    ; CHECK: $bmll1 = VMOV_alu_mv_mv_x $lfl0
    ; CHECK-NEXT: $bmlh1 = VMOV_alu_mv_mv_x $lfh0
    ; CHECK-NEXT: $lfl0 = VMOV_alu_mv_mv_x $bmll1
    ; CHECK-NEXT: $lfh0 = VMOV_alu_mv_mv_x $bmlh1
    ; CHECK-NEXT: $lfl1 = VMOV_alu_mv_mv_x $lfl0
    ; CHECK-NEXT: $lfh1 = VMOV_alu_mv_mv_x $lfh0
    ; CHECK-NEXT: $lfl0 = VMOV_alu_mv_mv_x $x6
    ; CHECK-NEXT: $lfh0 = VMOV_alu_mv_mv_x $x7
    ; CHECK-NEXT: $x6 = VMOV_alu_mv_mv_x $lfl0
    ; CHECK-NEXT: $x7 = VMOV_alu_mv_mv_x $lfh0
  $cml1 = COPY $lf0
  $lf0 = COPY $cml1
  $lf1 = COPY $lf0
  $lf0 = COPY $y3
  $y3 = COPY $lf0
...

---
name:            test_copy_plfr
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_plfr
    ; CHECK: $p1 = MOV_scalar_pseudo $p0
    ; CHECK-NEXT: $lfl1 = VMOV_alu_mv_mv_x $lfl0
    ; CHECK-NEXT: $lfh1 = VMOV_alu_mv_mv_x $lfh0
    ; CHECK-NEXT: $r25 = MOV_OR_pseudo $r24
    ; CHECK-NEXT: $p0 = MOV_scalar_pseudo $p1
    ; CHECK-NEXT: $lfl0 = VMOV_alu_mv_mv_x $lfl1
    ; CHECK-NEXT: $lfh0 = VMOV_alu_mv_mv_x $lfh1
    ; CHECK-NEXT: $r24 = MOV_OR_pseudo $r25
  $plfr1 = COPY $plfr0
  $plfr0 = COPY $plfr1
...

---
name:            test_copy_y_cml
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_y_cml
    ; CHECK: $x4 = VMOV_alu_mv_mv_x $bmll0
    ; CHECK-NEXT: $x5 = VMOV_alu_mv_mv_x $bmlh0
    ; CHECK-NEXT: $bmll1 = VMOV_alu_mv_mv_x $x10
    ; CHECK-NEXT: $bmlh1 = VMOV_alu_mv_mv_x $x11
  $y2  = COPY $cml0
  $cml1 = COPY $y5
...

---
name:            test_copy_l
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_l
    ; CHECK: $r2 = MOV_alu_mv_mv_mv_scl $r4
    ; CHECK-NEXT: $r3 = MOV_alu_mv_mv_mv_scl $r5
  $l1 = COPY $l2
...

---
name:            test_copy_q_w
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_q_w
    ; CHECK: $q0 = VMOV_alu_mv_mv_w_to_q $wh0
    ; CHECK-NEXT: $wl0 = VMOV_alu_mv_mv_q_to_w $q0
  $q0 = COPY $wh0
  $wl0 = COPY $q0
...

---
name:            test_copy_qx
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_qx
    ; CHECK: $qx0 = VMOV_alu_mv_mv_qx $qx1
    ; CHECK-NEXT: $qx2 = VMOV_alu_mv_mv_qx $qx3
  $qx0 = COPY $qx1
  $qx2 = COPY $qx3
...

---
name:            test_copy_ex
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_ex
    ; CHECK: $ex0 = VMOV_alu_mv_mv_ex $ex1
    ; CHECK-NEXT: $ex2 = VMOV_alu_mv_mv_ex $ex3
  $ex0 = COPY $ex1
  $ex2 = COPY $ex3
...

---
name:            test_copy_ey
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_ey
    ; CHECK: $ex0 = VMOV_alu_mv_mv_ex $ex2
    ; CHECK-NEXT: $ex1 = VMOV_alu_mv_mv_ex $ex3
  $ey0 = COPY $ey1
...

---
name:            test_copy_qex
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_qex
    ; CHECK: $qex0 = VMOV_alu_mv_mv_qex $qex1
    ; CHECK-NEXT: $qex2 = VMOV_alu_mv_mv_qex $qex3
  $qex0 = COPY $qex1
  $qex2 = COPY $qex3
...

---
name:            test_copy_qey
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_qey
    ; CHECK: $qex0 = VMOV_alu_mv_mv_qex $qex2
    ; CHECK-NEXT: $qex1 = VMOV_alu_mv_mv_qex $qex3
  $qey0 = COPY $qey1
...


---
name:            test_copy_l_to_e
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_l_to_e
    ; CHECK: $el0 = MOV_alu_mv_mv_mv_e_mv_r_to_el $r2
    ; CHECK-NEXT: $eh0 = MOV_alu_mv_mv_mv_e_mv_r_to_eh $r3
  $e0 = COPY $l1
...

---
name:            test_copy_e_to_l
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_e_to_l
    ; CHECK: $r0 = MOV_alu_mv_mv_mv_e_mv_el_to_r $el1
    ; CHECK-NEXT: $r1 = MOV_alu_mv_mv_mv_e_mv_eh_to_r $eh1
  $l0 = COPY $e1
...

---
name:            test_copy_exp_to_exp
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_exp_to_exp
    ; CHECK: $el0 = MOV_alu_mv_mv_mv_e_mv_el_to_el $el1
    ; CHECK-NEXT: $eh0 = MOV_alu_mv_mv_mv_e_mv_eh_to_eh $eh1
    ; CHECK-NEXT: $el5 = MOV_alu_mv_mv_mv_e_mv_el_to_el $el4
    ; CHECK-NEXT: $eh5 = MOV_alu_mv_mv_mv_e_mv_eh_to_eh $eh4
  $e0 = COPY $e1
  $e5 = COPY $e4
...


---
name:            test_copy_sf_to_lf
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_sf_to_lf
    ; CHECK: $lfl0 = VMOV_alu_mv_mv_x $sfl
    ; CHECK-NEXT: $lfh0 = VMOV_alu_mv_mv_x $sfh
  $lf0 = COPY $sf
...

---
name:            test_copy_vec_to_fifo
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_vec_to_fifo
    ; CHECK: $lfl0 = VMOV_alu_mv_mv_x $x0
    ; CHECK-NEXT: $lfh0 = VMOV_alu_mv_mv_x $x1
  $lf0 = COPY $y0
...

---
name:            test_copy_fifo_to_vec
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_fifo_to_vec
    ; CHECK: $x0 = VMOV_alu_mv_mv_x $lfl0
    ; CHECK-NEXT: $x1 = VMOV_alu_mv_mv_x $lfh0
  $y0 = COPY $lf0
...

---
name:            test_copy_acc_to_fifo
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_acc_to_fifo
    ; CHECK: $lfl0 = VMOV_alu_mv_mv_x $bmll0
    ; CHECK-NEXT: $lfh0 = VMOV_alu_mv_mv_x $bmlh0
  $lf0 = COPY $cml0
...

---
name:            test_copy_fifo_to_acc
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_fifo_to_acc
    ; CHECK: $bmll0 = VMOV_alu_mv_mv_x $lfl0
    ; CHECK-NEXT: $bmlh0 = VMOV_alu_mv_mv_x $lfh0
  $cml0 = COPY $lf0
...

---
name:            test_copy_eh_to_eh
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_eh_to_eh
    ; CHECK: $eh0 = MOV_alu_mv_mv_mv_e_mv_eh_to_eh $eh1
  $eh0 = COPY $eh1
...

---
name:            test_copy_el_to_el
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_el_to_el
    ; CHECK: $el0 = MOV_alu_mv_mv_mv_e_mv_el_to_el $el1
  $el0 = COPY $el1
...

---
name:            test_copy_eh_to_el
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_eh_to_el
    ; CHECK: $el0 = MOV_alu_mv_mv_mv_e_mv_eh_to_el $eh1
  $el0 = COPY $eh1
...

---
name:            test_copy_el_to_eh
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_el_to_eh
    ; CHECK: $eh0 = MOV_alu_mv_mv_mv_e_mv_el_to_eh $el1
  $eh0 = COPY $el1
...

---
name:            test_copy_eh_to_r
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_eh_to_r
    ; CHECK: $r0 = MOV_alu_mv_mv_mv_e_mv_eh_to_r $eh1
  $r0 = COPY $eh1
...

---
name:            test_copy_r_to_eh
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_r_to_eh
    ; CHECK: $eh0 = MOV_alu_mv_mv_mv_e_mv_r_to_eh $r1
  $eh0 = COPY $r1
...

---
name:            test_copy_el_to_r
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_el_to_r
    ; CHECK: $r0 = MOV_alu_mv_mv_mv_e_mv_el_to_r $el1
  $r0 = COPY $el1
...

---
name:            test_copy_r_to_el
body: |
  bb.0:
    ; CHECK-LABEL: name: test_copy_r_to_el
    ; CHECK: $el0 = MOV_alu_mv_mv_mv_e_mv_r_to_el $r1
  $el0 = COPY $r1
...
