; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -O2 -mtriple=aie2p -verify-machineinstrs --issue-limit=1 %s -o - | FileCheck %s

define <8 x i32> @test_shuffle_vector_to_concat_vector_8x32_v4x32(<4 x i32> noundef %a, <4 x i32> noundef %b) {
; CHECK-LABEL: test_shuffle_vector_to_concat_vector_8x32_v4x32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; ret lr; nopm ; nops
; CHECK-NEXT:    mova r0, #48 // Delay Slot 5
; CHECK-NEXT:    mova r16, #15 // Delay Slot 4
; CHECK-NEXT:    vshift x0, x0, x4, r0 // Delay Slot 3
; CHECK-NEXT:    vsel.32 x0, x0, x2, r16 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <4 x i32> %a, <4 x i32> %b, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  ret <8 x i32> %shuffle
}

define <16 x i16> @test_shuffle_vector_to_concat_vector_16x16_v8x16(<8 x i16> noundef %a, <8 x i16> noundef %b) {
; CHECK-LABEL: test_shuffle_vector_to_concat_vector_16x16_v8x16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; ret lr; nopm ; nops
; CHECK-NEXT:    mova r0, #48 // Delay Slot 5
; CHECK-NEXT:    mova r16, #15 // Delay Slot 4
; CHECK-NEXT:    vshift x0, x0, x4, r0 // Delay Slot 3
; CHECK-NEXT:    vsel.32 x0, x0, x2, r16 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <8 x i16> %a, <8 x i16> %b, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  ret <16 x i16> %shuffle
}

define <16 x i32> @test_shuffle_vector_to_concat_vector(<8 x i32> noundef %a, <8 x i32> noundef %b) {
; CHECK-LABEL: test_shuffle_vector_to_concat_vector:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    vmov wl0, wl2 // Delay Slot 3
; CHECK-NEXT:    vmov wh0, wl4 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <8 x i32> %a, <8 x i32> %b, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  ret <16 x i32> %shuffle
}

define <16 x i32> @test_shuffle_vector_2x32Src(<2 x i32> noundef %a, <2 x i32> noundef %b) {
; CHECK-LABEL: test_shuffle_vector_2x32Src:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vbcst.64 x0, r1:r0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <2 x i32> %a, <2 x i32> %b, <16 x i32> <i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1>
  ret <16 x i32> %shuffle
}

define <16 x i16> @test_shuffle_vector_4x16Src(<4 x i16> noundef %a, <4 x i16> noundef %b) {
; CHECK-LABEL: test_shuffle_vector_4x16Src:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vbcst.64 x0, r1:r0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <4 x i16> %a, <4 x i16> %b, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 0, i32 1, i32 2, i32 3, i32 0, i32 1, i32 2, i32 3, i32 0, i32 1, i32 2, i32 3>
  ret <16 x i16> %shuffle
}

define <32 x i8> @test_shuffle_vector_8x8Src(<8 x i8> noundef %a, <8 x i8> noundef %b) {
; CHECK-LABEL: test_shuffle_vector_8x8Src:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vbcst.64 x0, r1:r0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <8 x i8> %a, <8 x i8> %b, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  ret <32 x i8> %shuffle
}

define <16 x i16> @test_shuffle_vector_2x16Src(<2 x i16> noundef %a, <2 x i16> noundef %b) {
; CHECK-LABEL: test_shuffle_vector_2x16Src:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vbcst.32 x0, r0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <2 x i16> %a, <2 x i16> %b, <16 x i32> <i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1>
  ret <16 x i16> %shuffle
}

define <32 x i8> @test_shuffle_vector_4x8Src(<4 x i8> noundef %a, <4 x i8> noundef %b) {
; CHECK-LABEL: test_shuffle_vector_4x8Src:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vbcst.32 x0, r0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <4 x i8> %a, <4 x i8> %b, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 0, i32 1, i32 2, i32 3, i32 0, i32 1, i32 2, i32 3, i32 0, i32 1, i32 2, i32 3, i32 0, i32 1, i32 2, i32 3, i32 0, i32 1, i32 2, i32 3, i32 0, i32 1, i32 2, i32 3, i32 0, i32 1, i32 2, i32 3>
  ret <32 x i8> %shuffle
}

define <16 x i32> @test_shuffle_vector_all_undef(<16 x i32> noundef %a, <16 x i32> noundef %b) {
; CHECK-LABEL: test_shuffle_vector_all_undef:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <16 x i32> %a, <16 x i32> %b, <16 x i32> <i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>
  ret <16 x i32> %shuffle
}

define <16 x i32> @test_shuffle_vector_vsel_valid_mask_16_s32(<16 x i32> noundef %a, <16 x i32> noundef %b) {
; CHECK-LABEL: test_shuffle_vector_vsel_valid_mask_16_s32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    movxm r16, #65520 // Delay Slot 3
; CHECK-NEXT:    vsel.32 x0, x2, x4, r16 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <16 x i32> %a, <16 x i32> %b, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  ret <16 x i32> %shuffle
}

define <32 x i16> @test_shuffle_vector_vsel_valid_mask_32_s16(<32 x i16> noundef %a, <32 x i16> noundef %b) {
; CHECK-LABEL: test_shuffle_vector_vsel_valid_mask_32_s16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mova r16, #10 // Delay Slot 3
; CHECK-NEXT:    vsel.16 x0, x2, x4, r16 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <32 x i16> %a, <32 x i16> %b, <32 x i32> <i32 0, i32 33, i32 2, i32 35, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  ret <32 x i16> %shuffle
}

define <64 x i8> @test_shuffle_vector_vsel_valid_mask_64_s8(<64 x i8> noundef %a, <64 x i8> noundef %b) {
; CHECK-LABEL: test_shuffle_vector_vsel_valid_mask_64_s8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    mova r0, #5 // Delay Slot 4
; CHECK-NEXT:    mova r1, #0 // Delay Slot 3
; CHECK-NEXT:    vsel.8 x0, x2, x4, r1:r0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <64 x i8> %a, <64 x i8> %b, <64 x i32> <i32 64, i32 1, i32 66, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
  ret <64 x i8> %shuffle
}

define <16 x i32> @test_shuffle_vector_vsel_valid_mask_ordered_indices_with_undef(<16 x i32> noundef %a, <16 x i32> noundef %b) {
; CHECK-LABEL: test_shuffle_vector_vsel_valid_mask_ordered_indices_with_undef:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    movxm r16, #65520 // Delay Slot 3
; CHECK-NEXT:    vsel.32 x0, x2, x4, r16 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <16 x i32> %a, <16 x i32> %b, <16 x i32> <i32 undef, i32 undef, i32 undef, i32 undef, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  ret <16 x i32> %shuffle
}

define <16 x i32> @test_shuffle_vector_vsel_valid_mask_with_undef(<16 x i32> noundef %a, <16 x i32> noundef %b) {
; CHECK-LABEL: test_shuffle_vector_vsel_valid_mask_with_undef:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    movxm r16, #64992 // Delay Slot 3
; CHECK-NEXT:    vsel.32 x0, x2, x4, r16 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <16 x i32> %a, <16 x i32> %b, <16 x i32> <i32 0, i32 1, i32 2, i32 undef, i32 undef, i32 21, i32 22, i32 23, i32 24, i32 undef, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  ret <16 x i32> %shuffle
}

define <16 x i32> @test_shuffle_vector_vsel_valid_mask_mixed_indices(<16 x i32> noundef %a, <16 x i32> noundef %b) {
; CHECK-LABEL: test_shuffle_vector_vsel_valid_mask_mixed_indices:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    movxm r16, #65521 // Delay Slot 3
; CHECK-NEXT:    vsel.32 x0, x2, x4, r16 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <16 x i32> %a, <16 x i32> %b, <16 x i32> <i32 16, i32 1, i32 2, i32 3, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  ret <16 x i32> %shuffle
}

define <16 x i32> @test_shuffle_vector_vsel_valid_mask_mixed_indices_with_undef(<16 x i32> noundef %a, <16 x i32> noundef %b) {
; CHECK-LABEL: test_shuffle_vector_vsel_valid_mask_mixed_indices_with_undef:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    movxm r16, #64465 // Delay Slot 3
; CHECK-NEXT:    vsel.32 x0, x2, x4, r16 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <16 x i32> %a, <16 x i32> %b, <16 x i32> <i32 16, i32 1, i32 undef, i32 3, i32 20, i32 undef, i32 22, i32 23, i32 24, i32 25, i32 undef, i32 27, i32 28, i32 29, i32 30, i32 31>
  ret <16 x i32> %shuffle
}

define <16 x i32> @test_shuffle_vector_vsel_invalid_mask(<16 x i32> noundef %a, <16 x i32> noundef %b) {
; CHECK-LABEL: test_shuffle_vector_vsel_invalid_mask:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    vextract.64 r1:r0, x2, #0, vaddsign1 // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    vbcst.32 x0, r1 // Delay Slot 3
; CHECK-NEXT:    vinsert.32 x0, x0, #0, r0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <16 x i32> %a, <16 x i32> %b, <16 x i32> <i32 0, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1>
  ret <16 x i32> %shuffle
}

define <8 x i32> @test_shuffle_vector_to_extract_broadcast_vecElem(<8 x i32> noundef %a, <8 x i32> noundef %b) {
; CHECK-LABEL: test_shuffle_vector_to_extract_broadcast_vecElem:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vextbcst.32 x0, x2, #2 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <8 x i32> %a, <8 x i32> %b, <8 x i32> <i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2>
  ret <8 x i32> %shuffle
}

define <16 x i16> @test_shuffle_vector_to_extract_broadcast_s16(<16 x i16> noundef %a, <16 x i16> noundef %b) {
; CHECK-LABEL: test_shuffle_vector_to_extract_broadcast_s16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vextbcst.16 x0, x2, #2 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <16 x i16> %a, <16 x i16> %b, <16 x i32> <i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2>
  ret <16 x i16> %shuffle
}

; Tests for combining shuffle_vector to extract_subvector
; Test destination vector types with native source vector type (512 bits)

define <4 x i8> @test_shuffle_vector_to_extract_subvec_4xs8Dst(<64 x i8> noundef %a, <64 x i8> noundef %b) {
; CHECK-LABEL: test_shuffle_vector_to_extract_subvec_4xs8Dst:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vextract.32 r0, x0, #1, vaddsign1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <64 x i8> %a, <64 x i8> %b, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
  ret <4 x i8> %shuffle
}

define <2 x i16> @test_shuffle_vector_to_extract_subvec_2xs16Dst(<32 x i16> noundef %a, <32 x i16> noundef %b) {
; CHECK-LABEL: test_shuffle_vector_to_extract_subvec_2xs16Dst:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vextract.32 r0, x0, #0, vaddsign1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <32 x i16> %a, <32 x i16> %b, <2 x i32> <i32 0, i32 1>
  ret <2 x i16> %shuffle
}

define <8 x i8> @test_shuffle_vector_to_extract_subvec_8xs8Dst(<64 x i8> noundef %a, <64 x i8> noundef %b) {
; CHECK-LABEL: test_shuffle_vector_to_extract_subvec_8xs8Dst:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vextract.64 r1:r0, x0, #0, vaddsign1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <64 x i8> %a, <64 x i8> %b, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  ret <8 x i8> %shuffle
}

define <4 x i16> @test_shuffle_vector_to_extract_subvec_4xs16Dst(<32 x i16> noundef %a, <32 x i16> noundef %b) {
; CHECK-LABEL: test_shuffle_vector_to_extract_subvec_4xs16Dst:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vextract.64 r1:r0, x0, #1, vaddsign1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <32 x i16> %a, <32 x i16> %b, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
  ret <4 x i16> %shuffle
}

define <2 x i32> @test_shuffle_vector_to_extract_subvec_2xs32Dst(<16 x i32> noundef %a, <16 x i32> noundef %b) {
; CHECK-LABEL: test_shuffle_vector_to_extract_subvec_2xs32Dst:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vextract.64 r1:r0, x0, #0, vaddsign1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <16 x i32> %a, <16 x i32> %b, <2 x i32> <i32 0, i32 1>
  ret <2 x i32> %shuffle
}

; Test not native source vector types

define <2 x i32> @test_shuffle_vector_to_extract_subvec_256BitSrc(<8 x i32> noundef %a, <8 x i32> noundef %b) {
; CHECK-LABEL: test_shuffle_vector_to_extract_subvec_256BitSrc:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vextract.64 r1:r0, x0, #3, vaddsign1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <8 x i32> %a, <8 x i32> %b, <2 x i32> <i32 6, i32 7>
  ret <2 x i32> %shuffle
}

define <2 x i32> @test_shuffle_vector_to_extract_subvec_1024BitSrc(<32 x i32> noundef %a, <32 x i32> noundef %b) {
; CHECK-LABEL: test_shuffle_vector_to_extract_subvec_1024BitSrc:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vextract.64 r1:r0, x5, #0, vaddsign1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <32 x i32> %a, <32 x i32> %b, <2 x i32> <i32 16, i32 17>
  ret <2 x i32> %shuffle
}

define <2 x i32> @test_shuffle_vector_to_extract_subvec_2048BitSrc(<64 x i32> noundef %a, <64 x i32> noundef %b) {
; CHECK-LABEL: test_shuffle_vector_to_extract_subvec_2048BitSrc:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; nopx ; mov p0, sp; nopv
; CHECK-NEXT:    padda [p0], #-256
; CHECK-NEXT:    vlda bmll0, [p0, #0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    vmov x0, bmll0 // Delay Slot 3
; CHECK-NEXT:    vextract.64 r1:r0, x0, #0, vaddsign1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <64 x i32> %a, <64 x i32> %b, <2 x i32> <i32 0, i32 1>
  ret <2 x i32> %shuffle
}

; Test extract and broadcast a subvector

define <64 x i8> @test_shuffle_vector_to_extract_broadcast_subvec_32(<64 x i8> noundef %a, <64 x i8> noundef %b) {
; CHECK-LABEL: test_shuffle_vector_to_extract_broadcast_subvec_32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vextbcst.32 x0, x2, #1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <64 x i8> %a, <64 x i8> %b, <64 x i32> <i32 4, i32 5, i32 6, i32 7, i32 4, i32 5, i32 6, i32 7, i32 4, i32 5, i32 6, i32 7, i32 4, i32 5, i32 6, i32 7, i32 4, i32 5, i32 6, i32 7, i32 4, i32 5, i32 6, i32 7, i32 4, i32 5, i32 6, i32 7, i32 4, i32 5, i32 6, i32 7, i32 4, i32 5, i32 6, i32 7, i32 4, i32 5, i32 6, i32 7, i32 4, i32 5, i32 6, i32 7, i32 4, i32 5, i32 6, i32 7, i32 4, i32 5, i32 6, i32 7, i32 4, i32 5, i32 6, i32 7, i32 4, i32 5, i32 6, i32 7, i32 4, i32 5, i32 6, i32 7>
  ret <64 x i8> %shuffle
}

define <16 x i16> @test_shuffle_vector_to_extract_broadcast_subvec_64(<16 x i16> noundef %a, <16 x i16> noundef %b) {
; CHECK-LABEL: test_shuffle_vector_to_extract_broadcast_subvec_64:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vextbcst.64 x0, x2, #1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <16 x i16> %a, <16 x i16> %b, <16 x i32> <i32 4, i32 5, i32 6, i32 7, i32 4, i32 5, i32 6, i32 7, i32 4, i32 5, i32 6, i32 7, i32 4, i32 5, i32 6, i32 7>
  ret <16 x i16> %shuffle
}

; Test G_SHUFFLE_VECTOR to UNMERGE

define <8 x i32> @test_shuffle_vector_vector_unmerge_lo(<16 x i32> noundef %a, <16 x i32> noundef %b) {
; CHECK-LABEL: test_shuffle_vector_vector_unmerge_lo:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vmov x0, x2 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <16 x i32> %a, <16 x i32> %b, <8 x i32> <i32 0, i32  1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  ret <8 x i32> %shuffle
}

define <8 x i32> @test_shuffle_vector_vector_unmerge_lo_4_unmerge_outputs(<32 x i32> noundef %a, <32 x i32> noundef %b) {
; CHECK-LABEL: test_shuffle_vector_vector_unmerge_lo_4_unmerge_outputs:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vmov x0, x4 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <32 x i32> %a, <32 x i32> %b, <8 x i32> <i32 0, i32  1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  ret <8 x i32> %shuffle
}

define <4 x i32> @test_shuffle_vector_vector_unmerge_hi_128(<8 x i32> noundef %a, <8 x i32> noundef %b) {
; CHECK-LABEL: test_shuffle_vector_vector_unmerge_hi_128:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mova r0, #16 // Delay Slot 3
; CHECK-NEXT:    vshift x0, x2, x0, r0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <8 x i32> %a, <8 x i32> %b, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
  ret <4 x i32> %shuffle
}

define <8 x i32> @test_shuffle_vector_vector_unmerge_hi_256(<16 x i32> noundef %a, <16 x i32> noundef %b) {
; CHECK-LABEL: test_shuffle_vector_vector_unmerge_hi_256:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vmov wl0, wh2 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <16 x i32> %a, <16 x i32> %b, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  ret <8 x i32> %shuffle
}

define <16 x i32> @test_shuffle_vector_vector_unmerge_hi_512(<32 x i32> noundef %a, <32 x i32> noundef %b) {
; CHECK-LABEL: test_shuffle_vector_vector_unmerge_hi_512:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vmov x0, x5 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <32 x i32> %a, <32 x i32> %b, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  ret <16 x i32> %shuffle
}

define <32 x i32> @test_shuffle_vector_vector_unmerge_lo_1024(<64 x i32> noundef %a, <64 x i32> noundef %b) {
; CHECK-LABEL: test_shuffle_vector_vector_unmerge_lo_1024:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nopx ; mov p0, sp; nops
; CHECK-NEXT:    padda [p0], #-256
; CHECK-NEXT:    vlda bmll0, [p0, #0]
; CHECK-NEXT:    vlda bmlh0, [p0, #64]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    vmov x4, bmll0 // Delay Slot 3
; CHECK-NEXT:    vmov x5, bmlh0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <64 x i32> %a, <64 x i32> %b, <32 x i32> <i32 0, i32  1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  ret <32 x i32> %shuffle
}

; Combine G_SHUFFLE_VECTOR into COPY. Note: shufflevector doesn't accept scalar arguments.
define <16 x i32> @shuffle_vector_to_copy_vec(<16 x i32> noundef %a, <16 x i32> noundef %b) {
; CHECK-LABEL: shuffle_vector_to_copy_vec:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vmov x0, x2 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <16 x i32> %a, <16 x i32> %b, <16 x i32> <i32 0, i32  1, i32 2, i32 undef, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  ret <16 x i32> %shuffle
}

define <8 x i32> @shuffle_vector_to_copy_no_combine(<8 x i32> noundef %a, <8 x i32> noundef %b) {
; CHECK-LABEL: shuffle_vector_to_copy_no_combine:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopx ; vextract.32 r1, x2, #5, vaddsign1
; CHECK-NEXT:    vextract.32 r2, x2, #6, vaddsign1
; CHECK-NEXT:    vextract.32 r3, x2, #7, vaddsign1
; CHECK-NEXT:    vextract.32 r4, x4, #0, vaddsign1
; CHECK-NEXT:    vextract.32 r5, x4, #1, vaddsign1
; CHECK-NEXT:    vextract.32 r6, x4, #2, vaddsign1
; CHECK-NEXT:    vextract.32 r0, x2, #4, vaddsign1
; CHECK-NEXT:    vextract.32 r7, x4, #3, vaddsign1
; CHECK-NEXT:    vpush.hi.32 x0, x0, r0
; CHECK-NEXT:    vpush.hi.32 x0, x0, r1
; CHECK-NEXT:    vpush.hi.32 x0, x0, r2
; CHECK-NEXT:    vpush.hi.32 x0, x0, r3
; CHECK-NEXT:    vpush.hi.32 x0, x0, r4
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    vpush.hi.32 x0, x0, r5 // Delay Slot 5
; CHECK-NEXT:    vpush.hi.32 x0, x0, r6 // Delay Slot 4
; CHECK-NEXT:    vpush.hi.32 x0, x0, r7 // Delay Slot 3
; CHECK-NEXT:    vmov wl0, wh0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <8 x i32> %a, <8 x i32> %b, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11>
  ret <8 x i32> %shuffle
}

define <16 x i32> @shuffle_vector_to_unmerge_concat_lo(<16 x i32> noundef %a, <16 x i32> noundef %b) {
; CHECK-LABEL: shuffle_vector_to_unmerge_concat_lo:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    vmov x0, x2 // Delay Slot 3
; CHECK-NEXT:    vmov wh0, wl0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <16 x i32> %a, <16 x i32> %b, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  ret <16 x i32> %shuffle
}

define <16 x i32> @shuffle_vector_to_unmerge_concat_hi(<16 x i32> noundef %a, <16 x i32> noundef %b) {
; CHECK-LABEL: shuffle_vector_to_unmerge_concat_hi:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    vmov x0, x2 // Delay Slot 3
; CHECK-NEXT:    vmov wl0, wh0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <16 x i32> %a, <16 x i32> %b, <16 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  ret <16 x i32> %shuffle
}


; TODO: We should be able to handle this swap pattern with an unmerge and concat
define <16 x i32> @shuffle_vector_to_unmerge_concat_lo_hi(<16 x i32> noundef %a, <16 x i32> noundef %b) {
; CHECK-LABEL: shuffle_vector_to_unmerge_concat_lo_hi:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    vmov wl0, wh2 // Delay Slot 3
; CHECK-NEXT:    vmov wh0, wl2 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <16 x i32> %a, <16 x i32> %b, <16 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  ret <16 x i32> %shuffle
}

define fastcc void @shuffle_match_extracted_load_idx0() {
; CHECK-LABEL: shuffle_match_extracted_load_idx0:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mova p0, #0; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    lda.s16 r0, [p0, #0]; nopx
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    vbcst.16 x0, r0 // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vst x0, [p0, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = load <8 x bfloat>, ptr null, align 4
  %1 = shufflevector <8 x bfloat> %0, <8 x bfloat> zeroinitializer, <32 x i32> zeroinitializer
  store <32 x bfloat> %1, ptr addrspace(6) null, align 64
  ret void
}


define fastcc void @shuffle_match_extracted_load_idx_non_zero() {
; CHECK-LABEL: shuffle_match_extracted_load_idx_non_zero:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mova p0, #6; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    lda.s16 r0, [p0, #0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    vbcst.16 x0, r0 // Delay Slot 4
; CHECK-NEXT:    mova p0, #0 // Delay Slot 3
; CHECK-NEXT:    vst x0, [p0, #0] // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = load <8 x bfloat>, ptr null, align 4
  %1 = shufflevector <8 x bfloat> %0, <8 x bfloat> zeroinitializer, <32 x i32> <i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3>
  store <32 x bfloat> %1, ptr addrspace(6) null, align 64
  ret void
}



define <32 x i16> @shuffle_vector_to_extract_insert_elt_one_exception_second_input(<32 x i16> noundef %a, <32 x i16> noundef %b) {
; CHECK-LABEL: shuffle_vector_to_extract_insert_elt_one_exception_second_input:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    vextract.16 r0, x4, #0, vaddsign1 // Delay Slot 4
; CHECK-NEXT:    mova r29, #8 // Delay Slot 3
; CHECK-NEXT:    vinsert.16 x0, x2, r29, r0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <32 x i16> %a, <32 x i16> %b, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 32, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 undef, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 undef, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  ret <32 x i16> %shuffle
}

define <32 x i16> @shuffle_vector_to_extract_insert_elt_3_exceptions_second_input_reuse_extract_result(<32 x i16> noundef %a, <32 x i16> noundef %b) {
; CHECK-LABEL: shuffle_vector_to_extract_insert_elt_3_exceptions_second_input_reuse_extract_result:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mova r29, #7; nopx
; CHECK-NEXT:    vextract.16 r0, x4, #0, vaddsign1
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    vinsert.16 x0, x2, #0, r0 // Delay Slot 5
; CHECK-NEXT:    vinsert.16 x0, x0, r29, r0 // Delay Slot 4
; CHECK-NEXT:    mova r29, #8 // Delay Slot 3
; CHECK-NEXT:    vinsert.16 x0, x0, r29, r0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <32 x i16> %a, <32 x i16> %b, <32 x i32> <i32 32, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 32, i32 32, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 undef, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 undef, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  ret <32 x i16> %shuffle
}


define <32 x i16> @shuffle_vector_to_extract_insert_elt_one_exception_first_input(<32 x i16> noundef %a, <32 x i16> noundef %b) {
; CHECK-LABEL: shuffle_vector_to_extract_insert_elt_one_exception_first_input:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    vextract.16 r0, x2, #15, vaddsign1 // Delay Slot 4
; CHECK-NEXT:    mova r29, #8 // Delay Slot 3
; CHECK-NEXT:    vinsert.16 x0, x2, r29, r0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <32 x i16> %a, <32 x i16> %b, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 15, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 undef, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 undef, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  ret <32 x i16> %shuffle
}

define <32 x i16> @shuffle_vector_to_extract_insert_elt_two_exceptions_diff_input(<32 x i16> noundef %a, <32 x i16> noundef %b) {
; CHECK-LABEL: shuffle_vector_to_extract_insert_elt_two_exceptions_diff_input:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mova r29, #8; nopx
; CHECK-NEXT:    vextract.16 r0, x2, #15, vaddsign1
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    vinsert.16 x0, x2, r29, r0 // Delay Slot 5
; CHECK-NEXT:    vextract.16 r0, x4, #29, vaddsign1 // Delay Slot 4
; CHECK-NEXT:    mova r29, #11 // Delay Slot 3
; CHECK-NEXT:    vinsert.16 x0, x0, r29, r0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <32 x i16> %a, <32 x i16> %b, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 15, i32 9, i32 10, i32 61, i32 12, i32 13, i32 14, i32 15, i32 undef, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 undef, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  ret <32 x i16> %shuffle
}

define <16 x i32> @shuffle_vector_to_extract_insert_elt_beyond_max_exceptions_no_combine(<16 x i32> noundef %a, <16 x i32> noundef %b) {
; CHECK-LABEL: shuffle_vector_to_extract_insert_elt_beyond_max_exceptions_no_combine:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nopx ; vextract.32 r1, x2, #1, vaddsign1; nops
; CHECK-NEXT:    vextract.32 r2, x2, #2, vaddsign1
; CHECK-NEXT:    vextract.32 r3, x2, #3, vaddsign1
; CHECK-NEXT:    vextract.32 r4, x2, #4, vaddsign1
; CHECK-NEXT:    vextract.32 r5, x2, #5, vaddsign1
; CHECK-NEXT:    vextract.32 r6, x2, #6, vaddsign1
; CHECK-NEXT:    vextract.32 r0, x2, #0, vaddsign1
; CHECK-NEXT:    vextract.32 r7, x2, #7, vaddsign1
; CHECK-NEXT:    vpush.hi.32 x0, x0, r0
; CHECK-NEXT:    vpush.hi.32 x0, x0, r1
; CHECK-NEXT:    vpush.hi.32 x0, x0, r2
; CHECK-NEXT:    vpush.hi.32 x0, x0, r3
; CHECK-NEXT:    vpush.hi.32 x0, x0, r4
; CHECK-NEXT:    vpush.hi.32 x0, x0, r5
; CHECK-NEXT:    vpush.hi.32 x0, x0, r6
; CHECK-NEXT:    vpush.hi.32 x0, x0, r7
; CHECK-NEXT:    vpush.hi.32 x0, x0, r7
; CHECK-NEXT:    vpush.hi.32 x0, x0, r6
; CHECK-NEXT:    vpush.hi.32 x0, x0, r5
; CHECK-NEXT:    vpush.hi.32 x0, x0, r4
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    vpush.hi.32 x0, x0, r3 // Delay Slot 5
; CHECK-NEXT:    vpush.hi.32 x0, x0, r2 // Delay Slot 4
; CHECK-NEXT:    vpush.hi.32 x0, x0, r1 // Delay Slot 3
; CHECK-NEXT:    vpush.hi.32 x0, x0, r0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <16 x i32> %a, <16 x i32> %b, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 7, i32 6, i32 5, i32 4, i32 3, i32 2, i32 1, i32 0>
  ret <16 x i32> %shuffle
}


define <16 x i32> @shuffle_vector_to_extract_insert_elt_max_exceptions_combine(<16 x i32> noundef %a, <16 x i32> noundef %b) {
; CHECK-LABEL: shuffle_vector_to_extract_insert_elt_max_exceptions_combine:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopx ; vextract.32 r0, x2, #6, vaddsign1
; CHECK-NEXT:    mova r29, #9
; CHECK-NEXT:    vinsert.32 x0, x2, r29, r0
; CHECK-NEXT:    vextract.64 r1:r0, x2, #2, vaddsign1
; CHECK-NEXT:    mova r29, #10
; CHECK-NEXT:    vinsert.32 x0, x0, r29, r1
; CHECK-NEXT:    mova r29, #11
; CHECK-NEXT:    vinsert.32 x0, x0, r29, r0
; CHECK-NEXT:    vextract.64 r1:r0, x2, #1, vaddsign1
; CHECK-NEXT:    mova r29, #12
; CHECK-NEXT:    vinsert.32 x0, x0, r29, r1
; CHECK-NEXT:    mova r29, #13
; CHECK-NEXT:    vinsert.32 x0, x0, r29, r0
; CHECK-NEXT:    vextract.64 r1:r0, x2, #0, vaddsign1
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    mova r29, #14 // Delay Slot 5
; CHECK-NEXT:    vinsert.32 x0, x0, r29, r1 // Delay Slot 4
; CHECK-NEXT:    mova r29, #15 // Delay Slot 3
; CHECK-NEXT:    vinsert.32 x0, x0, r29, r0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %shuffle = shufflevector <16 x i32> %a, <16 x i32> %b, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 6, i32 5, i32 4, i32 3, i32 2, i32 1, i32 0>
  ret <16 x i32> %shuffle
}

define <16 x i32> @shuffle_concat_extracted_subvectors_vecToExtract_sameSize1(<16 x i32> %a, <16 x i32> %b) {
; CHECK-LABEL: shuffle_concat_extracted_subvectors_vecToExtract_sameSize1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    vmov x0, x4 // Delay Slot 3
; CHECK-NEXT:    vmov wh0, wl2 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
  %shuffle = shufflevector <16 x i32> %a, <16 x i32> %b, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 0, i32 1, i32 2, i32 3, i32 undef, i32 undef, i32 undef, i32 undef>
  ret <16 x i32> %shuffle
}

define <16 x i32> @shuffle_concat_extracted_subvectors_vecToExtract_sameSize2(<16 x i32> %a, <16 x i32> %b) {
; CHECK-LABEL: shuffle_concat_extracted_subvectors_vecToExtract_sameSize2:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mova r0, #48; nopxm
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    mova r16, #15 // Delay Slot 5
; CHECK-NEXT:    vshift x0, x0, x2, r0 // Delay Slot 4
; CHECK-NEXT:    vsel.32 x0, x0, x2, r16 // Delay Slot 3
; CHECK-NEXT:    vmov wh0, wl0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
  %shuffle = shufflevector <16 x i32> %a, <16 x i32> %b, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 0, i32 1, i32 2, i32 3, i32 undef, i32 1, i32 2, i32 3, i32 0, i32 1, i32 2, i32 3>
  ret <16 x i32> %shuffle
}

define <16 x i32> @shuffle_concat_extracted_subvectors_vecToExtract_DiffSize1(<16 x i32> %a, <16 x i32> %b) {
; CHECK-LABEL: shuffle_concat_extracted_subvectors_vecToExtract_DiffSize1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    nopa ; nopb ; nops ; nopx ; vmov wl4, wh4; nopv
; CHECK-NEXT:    mova r0, #16; nopx
; CHECK-NEXT:    mova r16, #15
; CHECK-NEXT:    vshift x0, x2, x0, r0
; CHECK-NEXT:    mova r0, #48
; CHECK-NEXT:    vshift x6, x0, x2, r0
; CHECK-NEXT:    vmov wl2, wh2
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    vshift x2, x0, x2, r0 // Delay Slot 5
; CHECK-NEXT:    vsel.32 x4, x6, x4, r16 // Delay Slot 4
; CHECK-NEXT:    vsel.32 x0, x2, x0, r16 // Delay Slot 3
; CHECK-NEXT:    vmov wh0, wl4 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
  %shuffle = shufflevector <16 x i32> %a, <16 x i32> %b, <16 x i32> <i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 24, i32 25, i32 26, i32 27, i32 0, i32 1, i32 2, i32 3>
  ret <16 x i32> %shuffle
}

define <16 x i32> @shuffle_concat_extracted_subvectors_vecToExtract_DiffSize2(<16 x i32> %a, <16 x i32> %b) {
; CHECK-LABEL: shuffle_concat_extracted_subvectors_vecToExtract_DiffSize2:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mova r0, #48; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    mova r16, #15; nopx
; CHECK-NEXT:    vsel.32 x0, x4, x4, r16
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    vmov wl4, wh4 // Delay Slot 5
; CHECK-NEXT:    vshift x2, x0, x2, r0 // Delay Slot 4
; CHECK-NEXT:    vsel.32 x2, x2, x4, r16 // Delay Slot 3
; CHECK-NEXT:    vmov wh0, wl2 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
  %shuffle = shufflevector <16 x i32> %a, <16 x i32> %b, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 0, i32 1, i32 2, i32 3>
  ret <16 x i32> %shuffle
}

define <16 x i32> @shuffle_concat_extracted_subvectors_no_undef_at_extractidx(<16 x i32> %a, <16 x i32> %b) {
; CHECK-LABEL: shuffle_concat_extracted_subvectors_no_undef_at_extractidx:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mova r0, #16; nopb ; nopxm ; nops
; CHECK-NEXT:    mova r16, #15
; CHECK-NEXT:    vshift x0, x2, x0, r0
; CHECK-NEXT:    mova r0, #48
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    vshift x4, x0, x2, r0 // Delay Slot 5
; CHECK-NEXT:    vsel.32 x6, x4, x0, r16 // Delay Slot 4
; CHECK-NEXT:    vsel.32 x0, x4, x2, r16 // Delay Slot 3
; CHECK-NEXT:    vmov wh0, wl6 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
  %shuffle = shufflevector <16 x i32> %a, <16 x i32> %b, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
  ret <16 x i32> %shuffle
}


define <16 x i32> @shuffle_concat_extracted_subvectors_undef_at_extractidx(<16 x i32> %a, <16 x i32> %b) {
; CHECK-LABEL: shuffle_concat_extracted_subvectors_undef_at_extractidx:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mova r0, #16; nopb ; nopxm ; nops
; CHECK-NEXT:    mova r16, #15
; CHECK-NEXT:    vshift x0, x2, x0, r0
; CHECK-NEXT:    mova r0, #48
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    vshift x4, x0, x2, r0 // Delay Slot 5
; CHECK-NEXT:    vsel.32 x6, x4, x0, r16 // Delay Slot 4
; CHECK-NEXT:    vsel.32 x0, x4, x2, r16 // Delay Slot 3
; CHECK-NEXT:    vmov wh0, wl6 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
  %shuffle = shufflevector <16 x i32> %a, <16 x i32> %b, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 undef, i32 undef, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3>
  ret <16 x i32> %shuffle
}

; Exeptions submask is all exceptions
define <16 x i32> @shuffle_concat_extracted_subvectors_nothing_but_exceptions(<16 x i32> %a, <16 x i32> %b) {
; CHECK-LABEL: shuffle_concat_extracted_subvectors_nothing_but_exceptions:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mova r29, #1; nopxm
; CHECK-NEXT:    vextract.64 r1:r0, x2, #2, vaddsign1
; CHECK-NEXT:    vextract.64 r3:r2, x2, #0, vaddsign1
; CHECK-NEXT:    vbcst.32 x0, r1
; CHECK-NEXT:    vinsert.32 x0, x0, #0, r2
; CHECK-NEXT:    vinsert.32 x0, x0, r29, r3
; CHECK-NEXT:    vextract.64 r3:r2, x2, #1, vaddsign1
; CHECK-NEXT:    mova r29, #2
; CHECK-NEXT:    vinsert.32 x0, x0, r29, r2
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    mova r29, #3 // Delay Slot 5
; CHECK-NEXT:    vinsert.32 x0, x0, r29, r3 // Delay Slot 4
; CHECK-NEXT:    mova r29, #4 // Delay Slot 3
; CHECK-NEXT:    vinsert.32 x0, x0, r29, r0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
  %shuffle = shufflevector <16 x i32> %a, <16 x i32> %b, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 5, i32 5, i32 5, i32 5, i32 5, i32 5, i32 5, i32 5, i32 5, i32 5>
  ret <16 x i32> %shuffle
}

define <8 x i32> @shuffle_concat_extracted_subvectors_height_not_power2_no_combine(<8 x i32> %a, <8 x i32> %b) {
; CHECK-LABEL: shuffle_concat_extracted_subvectors_height_not_power2_no_combine:
; CHECK:       // %bb.0:
; CHECK-NEXT:    nopa ; nopx ; vextract.32 r1, x2, #2, vaddsign1
; CHECK-NEXT:    vextract.32 r2, x2, #3, vaddsign1
; CHECK-NEXT:    vextract.32 r0, x2, #1, vaddsign1
; CHECK-NEXT:    vextract.32 r3, x2, #4, vaddsign1
; CHECK-NEXT:    vpush.hi.32 x0, x0, r0
; CHECK-NEXT:    vpush.hi.32 x0, x0, r1
; CHECK-NEXT:    vpush.hi.32 x0, x0, r2
; CHECK-NEXT:    vpush.hi.32 x0, x0, r3
; CHECK-NEXT:    vpush.hi.32 x0, x0, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    vpush.hi.32 x0, x0, r1 // Delay Slot 5
; CHECK-NEXT:    vpush.hi.32 x0, x0, r2 // Delay Slot 4
; CHECK-NEXT:    vpush.hi.32 x0, x0, r3 // Delay Slot 3
; CHECK-NEXT:    vmov wl0, wh0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
  %shuffle = shufflevector <8 x i32> %a, <8 x i32> %b, <8 x i32> <i32 1, i32 2, i32 3, i32 4, i32 1, i32 2, i32 3, i32 4>
  ret <8 x i32> %shuffle
}

define <16 x i32> @shuffle_concat_extracted_subvectors_numSubvecs_not_powerOf2_no_combine(<16 x i32> %a, <16 x i32> %b) {
; CHECK-LABEL: shuffle_concat_extracted_subvectors_numSubvecs_not_powerOf2_no_combine:
; CHECK:       // %bb.0:
; CHECK-NEXT:    nopa ; nopx ; vextract.32 r1, x2, #1, vaddsign1
; CHECK-NEXT:    vextract.32 r2, x2, #2, vaddsign1
; CHECK-NEXT:    vextract.32 r3, x2, #3, vaddsign1
; CHECK-NEXT:    vextract.32 r0, x2, #0, vaddsign1
; CHECK-NEXT:    vextract.32 r4, x2, #4, vaddsign1
; CHECK-NEXT:    vpush.hi.32 x0, x0, r0
; CHECK-NEXT:    vpush.hi.32 x0, x0, r1
; CHECK-NEXT:    vpush.hi.32 x0, x0, r2
; CHECK-NEXT:    vpush.hi.32 x0, x0, r3
; CHECK-NEXT:    vpush.hi.32 x0, x0, r0
; CHECK-NEXT:    vpush.hi.32 x0, x0, r1
; CHECK-NEXT:    vpush.hi.32 x0, x0, r2
; CHECK-NEXT:    vpush.hi.32 x0, x0, r3
; CHECK-NEXT:    vpush.hi.32 x0, x0, r4
; CHECK-NEXT:    vpush.hi.32 x0, x0, r1
; CHECK-NEXT:    vpush.hi.32 x0, x0, r2
; CHECK-NEXT:    vpush.hi.32 x0, x0, r3
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    vpush.hi.32 x0, x0, r0 // Delay Slot 5
; CHECK-NEXT:    vpush.hi.32 x0, x0, r1 // Delay Slot 4
; CHECK-NEXT:    vpush.hi.32 x0, x0, r2 // Delay Slot 3
; CHECK-NEXT:    vpush.hi.32 x0, x0, r3 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
  %shuffle = shufflevector <16 x i32> %a, <16 x i32> %b, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 0, i32 1, i32 2, i32 3, i32 4, i32 1, i32 2, i32 3, i32 0, i32 1, i32 2, i32 3>
  ret <16 x i32> %shuffle
}

define <64 x i8> @shuffle_concat_extracted_subvectors_exceptions_not_contiguous_no_combine(<8 x i64> %a, <8 x i64> %b) {
; CHECK-LABEL: shuffle_concat_extracted_subvectors_exceptions_not_contiguous_no_combine:
; CHECK:       // %bb.0:
; CHECK-NEXT:    vlda bmll0, [sp, #-64]; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    mov p0, sp
; CHECK-NEXT:    padda [p0], #-64
; CHECK-NEXT:    vlda bmll1, [p0, #-64]
; CHECK-NEXT:    vmov x0, bmll0
; CHECK-NEXT:    vextract.64 r1:r0, x0, #0, vaddsign1
; CHECK-NEXT:    vextract.64 r17:r16, x0, #1, vaddsign1
; CHECK-NEXT:    vextract.64 r19:r18, x0, #2, vaddsign1
; CHECK-NEXT:    vextract.64 r21:r20, x0, #3, vaddsign1
; CHECK-NEXT:    vextract.64 r23:r22, x0, #4, vaddsign1
; CHECK-NEXT:    vmov x2, bmll1
; CHECK-NEXT:    vpush.hi.64 x0, x0, r1:r0
; CHECK-NEXT:    vextract.64 r5:r4, x2, #2, vaddsign1
; CHECK-NEXT:    vextract.64 r3:r2, x2, #1, vaddsign1
; CHECK-NEXT:    vextract.64 r7:r6, x2, #3, vaddsign1
; CHECK-NEXT:    vpush.hi.64 x0, x0, r3:r2
; CHECK-NEXT:    vpush.hi.64 x0, x0, r5:r4
; CHECK-NEXT:    vpush.hi.64 x0, x0, r7:r6
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    vpush.hi.64 x0, x0, r17:r16 // Delay Slot 5
; CHECK-NEXT:    vpush.hi.64 x0, x0, r19:r18 // Delay Slot 4
; CHECK-NEXT:    vpush.hi.64 x0, x0, r21:r20 // Delay Slot 3
; CHECK-NEXT:    vpush.hi.64 x0, x0, r23:r22 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
  %shuffle = shufflevector <8 x i64> %b, <8 x i64> %a, <8 x i32> <i32 8, i32 1, i32 2, i32 3, i32 9, i32 10, i32 11, i32 12>
  %ret = bitcast <8 x i64> %shuffle to <64 x i8>
  ret <64 x i8> %ret
}
