# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
#
# RUN: llc -mtriple=aie2p -run-pass=prologepilog %s -o - | FileCheck %s --check-prefix=CHECK-OFFSETS
#
# Do not fill gap if the immediate offset for the spill instructions are not legal and require a pointer update to reach.
# This increases Program Memory Size which is not desirable.
#

---
name:            stack_slot_ordering_gemm
tracksRegLiveness: true
stack:
  - { id: 8, name: '', type: spill-slot, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 9, name: '', type: spill-slot, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 10, name: '', type: spill-slot, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 11, name: '', type: spill-slot, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 12, name: '', type: spill-slot, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 13, name: '', type: spill-slot, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 14, name: '', type: spill-slot, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 16, name: '', type: spill-slot, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 37, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 38, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 39, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 40, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 41, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 42, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 43, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 44, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 45, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 46, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 47, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 48, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 49, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 50, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 51, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 52, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 53, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 54, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 55, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 56, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 57, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 58, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 59, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 60, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 61, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 62, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 63, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 64, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 65, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 66, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 67, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 68, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 69, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 70, name: '', type: spill-slot, offset: 0, size: 64, alignment: 64,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
machineFunctionInfo:
  varArgsFrameIndex: 0
body:             |
  bb.0.entry:
    liveins: $p0, $p1, $p2, $p3, $p4, $p5


    ; CHECK-OFFSETS-LABEL: name: stack_slot_ordering_gemm
    ; CHECK-OFFSETS: liveins: $p0, $p1, $p2, $p3, $p4, $p5, $r8, $r9, $r10, $r11, $r12, $r13, $p6, $p7
    ; CHECK-OFFSETS-NEXT: {{  $}}
    ; CHECK-OFFSETS-NEXT: frame-setup PADDXM_pstm_sp_imm 2240, implicit-def $sp, implicit $sp
    ; CHECK-OFFSETS-NEXT: $r16 = PseudoMove killed $r8
    ; CHECK-OFFSETS-NEXT: $r17 = PseudoMove killed $r9
    ; CHECK-OFFSETS-NEXT: $r18 = PseudoMove killed $r10
    ; CHECK-OFFSETS-NEXT: $r19 = PseudoMove killed $r11
    ; CHECK-OFFSETS-NEXT: $r20 = PseudoMove killed $r12
    ; CHECK-OFFSETS-NEXT: $r21 = PseudoMove killed $r13
    ; CHECK-OFFSETS-NEXT: ST_dms_sts_spill killed $p6, -32, implicit $sp :: (store (s32) into %stack.42)
    ; CHECK-OFFSETS-NEXT: ST_dms_sts_spill killed $p7, -28, implicit $sp :: (store (s32) into %stack.43)
    ; CHECK-OFFSETS-NEXT: $p6 = IMPLICIT_DEF
    ; CHECK-OFFSETS-NEXT: $p7 = IMPLICIT_DEF
    ; CHECK-OFFSETS-NEXT: $r0 = LDA_dms_lda_spill -64, implicit $sp
    ; CHECK-OFFSETS-NEXT: $r1 = LDA_dms_lda_spill -60, implicit $sp
    ; CHECK-OFFSETS-NEXT: $r2 = LDA_dms_lda_spill -56, implicit $sp
    ; CHECK-OFFSETS-NEXT: $r3 = LDA_dms_lda_spill -52, implicit $sp
    ; CHECK-OFFSETS-NEXT: $r4 = LDA_dms_lda_spill -48, implicit $sp
    ; CHECK-OFFSETS-NEXT: $r5 = LDA_dms_lda_spill -44, implicit $sp
    ; CHECK-OFFSETS-NEXT: $r6 = LDA_dms_lda_spill -40, implicit $sp
    ; CHECK-OFFSETS-NEXT: $r7 = LDA_dms_lda_spill -36, implicit $sp
    ; CHECK-OFFSETS-NEXT: $r8 = LDA_dms_lda_idx_imm $p0, 0
    ; CHECK-OFFSETS-NEXT: $r9 = LDA_dms_lda_idx_imm $p1, 0
    ; CHECK-OFFSETS-NEXT: $r10 = LDA_dms_lda_idx_imm $p2, 0
    ; CHECK-OFFSETS-NEXT: $r11 = LDA_dms_lda_idx_imm $p3, 0
    ; CHECK-OFFSETS-NEXT: $r12 = LDA_dms_lda_idx_imm $p4, 0
    ; CHECK-OFFSETS-NEXT: $r13 = LDA_dms_lda_idx_imm $p5, 0
    ; CHECK-OFFSETS-NEXT: RET implicit $lr
    $p6 = IMPLICIT_DEF
    $p7 = IMPLICIT_DEF
    $r0 = LDA_dms_lda_spill %stack.8, implicit $sp
    $r1 = LDA_dms_lda_spill %stack.9, implicit $sp
    $r2 = LDA_dms_lda_spill %stack.10, implicit $sp
    $r3 = LDA_dms_lda_spill %stack.11, implicit $sp
    $r4 = LDA_dms_lda_spill %stack.12, implicit $sp
    $r5 = LDA_dms_lda_spill %stack.13, implicit $sp
    $r6 = LDA_dms_lda_spill %stack.14, implicit $sp
    $r7 = LDA_dms_lda_spill %stack.16, implicit $sp
    $r8 = LDA_dms_lda_idx_imm $p0, 0
    $r9 = LDA_dms_lda_idx_imm $p1, 0
    $r10 = LDA_dms_lda_idx_imm $p2, 0
    $r11 = LDA_dms_lda_idx_imm $p3, 0
    $r12 = LDA_dms_lda_idx_imm $p4, 0
    $r13 = LDA_dms_lda_idx_imm $p5, 0
    RET implicit $lr
...
