; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc < %s -verify-machineinstrs -mtriple=aie2p | FileCheck %s

define dso_local void @_Z12test_put_mcdDv64_DB8_i(<64 x i8> noundef %a, i32 noundef %en)  {
; CHECK-LABEL: _Z12test_put_mcdDv64_DB8_i:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; ret lr; nopm ; nops
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mov crmcden, r0 // Delay Slot 3
; CHECK-NEXT:    vmov mcd, x0; mov crmcden, #1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <64 x i8> %a to <16 x i32>
  tail call void @llvm.aie2p.mcd.write.vec(<16 x i32> %0, i32 %en)
  ret void
}


define dso_local void @_Z12test_put_mcdDv8_u7__acc64i(<8 x i64> inreg noundef %a, i32 noundef %en)  {
; CHECK-LABEL: _Z12test_put_mcdDv8_u7__acc64i:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; ret lr; nopm ; nops
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mov crmcden, r0 // Delay Slot 3
; CHECK-NEXT:    vmov mcd, bmll0; mov crmcden, #1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  tail call void @llvm.aie2p.mcd.write.acc32(<8 x i64> %a, i32 %en)
  ret void
}


define dso_local noundef i32 @_Z11test_get_ssv()  {
; CHECK-LABEL: _Z11test_get_ssv:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mov r0, ss; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call { i32, i32 } @llvm.aie2p.get.ss()
  %1 = extractvalue { i32, i32 } %0, 0
  ret i32 %1
}


define dso_local noundef i32 @_Z14test_get_ss_nbRbS_(ptr nocapture nonnull writeonly align 1 dereferenceable(1) %success, ptr nocapture nonnull writeonly align 1 dereferenceable(1) %tlast)  {
; CHECK-LABEL: _Z14test_get_ss_nbRbS_:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mov.nb r0, ss; nopb ; nopx
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    st.s8 r3, [p1, #0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    mova r2, #1; mov r1, srss0
; CHECK-NEXT:    and r3, r1, r2
; CHECK-NEXT:    nop
; CHECK-NEXT:    st.s8 r1, [p0, #0]
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    mova r3, #-1; extend.u8 r1, r1 // Delay Slot 5
; CHECK-NEXT:    lshl r1, r1, r3 // Delay Slot 4
; CHECK-NEXT:    and r1, r1, r2 // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call { i32, i32 } @llvm.aie2p.get.ss.nb()
  %1 = extractvalue { i32, i32 } %0, 1
  %2 = extractvalue { i32, i32 } %0, 0
  %3 = trunc i32 %1 to i8
  %frombool.i = and i8 %3, 1
  store i8 %frombool.i, ptr %tlast, align 1
  %4 = lshr i8 %3, 1
  %frombool3.i = and i8 %4, 1
  store i8 %frombool3.i, ptr %success, align 1
  ret i32 %2
}


define dso_local void @_Z11test_put_msii(i32 noundef %a, i32 noundef %tlast)  {
; CHECK-LABEL: _Z11test_put_msii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    mov r28, r1 // Delay Slot 4
; CHECK-NEXT:    mov ms, r0, r28 // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  tail call void @llvm.aie2p.put.ms(i32 %a, i32 %tlast)
  ret void
}


define dso_local void @_Z14test_put_ms_nbDv2_u6__bf16Rb(<2 x bfloat> noundef %val, ptr nocapture nonnull writeonly align 1 dereferenceable(1) %success)  {
; CHECK-LABEL: _Z14test_put_ms_nbDv2_u6__bf16Rb:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    st.s8 r0, [p0, #0]; nopb ; nopx ; mov.nb ms, r0
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    mov r0, srms0 // Delay Slot 4
; CHECK-NEXT:    nez r0, r0 // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <2 x bfloat> %val to i32
  %1 = tail call i32 @llvm.aie2p.put.ms.nb(i32 %0, i32 0)
  %tobool.i = icmp ne i32 %1, 0
  %frombool.i = zext i1 %tobool.i to i8
  store i8 %frombool.i, ptr %success, align 1
  ret void
}


define dso_local void @_Z19test_put_ms_v64bf16Dv64_u6__bf16ii(<64 x bfloat> noundef %a, i32 noundef %en, i32 noundef %tlast)  {
; CHECK-LABEL: _Z19test_put_ms_v64bf16Dv64_u6__bf16ii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nops ; vextract.64 r3:r2, x4, #0, vaddsign1
; CHECK-NEXT:    nop
; CHECK-NEXT:    mov ms, r2; vextract.64 r5:r4, x4, #1, vaddsign1
; CHECK-NEXT:    mov ms, r3
; CHECK-NEXT:    mov ms, r4; vextract.64 r3:r2, x4, #2, vaddsign1
; CHECK-NEXT:    mov ms, r5
; CHECK-NEXT:    mov ms, r2; vextract.64 r5:r4, x4, #3, vaddsign1
; CHECK-NEXT:    mov ms, r3
; CHECK-NEXT:    mov ms, r4; vextract.64 r3:r2, x4, #4, vaddsign1
; CHECK-NEXT:    mov ms, r5
; CHECK-NEXT:    mov ms, r2; vextract.64 r5:r4, x4, #5, vaddsign1
; CHECK-NEXT:    mov ms, r3
; CHECK-NEXT:    mov ms, r4; vextract.64 r3:r2, x4, #6, vaddsign1
; CHECK-NEXT:    mov ms, r5
; CHECK-NEXT:    mov ms, r2; vextract.64 r5:r4, x4, #7, vaddsign1
; CHECK-NEXT:    mov ms, r3
; CHECK-NEXT:    mov ms, r4; vextract.64 r3:r2, x5, #0, vaddsign1
; CHECK-NEXT:    mov ms, r5
; CHECK-NEXT:    mov ms, r2; vextract.64 r5:r4, x5, #1, vaddsign1
; CHECK-NEXT:    mov ms, r3
; CHECK-NEXT:    mov ms, r4; vextract.64 r3:r2, x5, #2, vaddsign1
; CHECK-NEXT:    mov ms, r5
; CHECK-NEXT:    mov ms, r2; vextract.64 r5:r4, x5, #3, vaddsign1
; CHECK-NEXT:    mov ms, r3
; CHECK-NEXT:    mov ms, r4; vextract.64 r3:r2, x5, #4, vaddsign1
; CHECK-NEXT:    mov ms, r5
; CHECK-NEXT:    mov ms, r2; vextract.64 r5:r4, x5, #5, vaddsign1
; CHECK-NEXT:    mov ms, r3
; CHECK-NEXT:    mov ms, r4; vextract.64 r3:r2, x5, #6, vaddsign1
; CHECK-NEXT:    mov ms, r5
; CHECK-NEXT:    mov ms, r2; ret lr; vextract.64 r5:r4, x5, #7, vaddsign1
; CHECK-NEXT:    mov ms, r3 // Delay Slot 5
; CHECK-NEXT:    mov ms, r4; mov r28, r1 // Delay Slot 4
; CHECK-NEXT:    mov ms, r5, r28 // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <64 x bfloat> %a to <32 x i32>
  %vecext.i.i.i5.i.i.i = extractelement <32 x i32> %0, i64 0
  tail call void @llvm.aie2p.put.ms(i32 %vecext.i.i.i5.i.i.i, i32 0)
  %vecext.i.i.i5.1.i.i.i = extractelement <32 x i32> %0, i64 1
  tail call void @llvm.aie2p.put.ms(i32 %vecext.i.i.i5.1.i.i.i, i32 0)
  %vecext.i.i.i5.2.i.i.i = extractelement <32 x i32> %0, i64 2
  tail call void @llvm.aie2p.put.ms(i32 %vecext.i.i.i5.2.i.i.i, i32 0)
  %vecext.i.i.i5.3.i.i.i = extractelement <32 x i32> %0, i64 3
  tail call void @llvm.aie2p.put.ms(i32 %vecext.i.i.i5.3.i.i.i, i32 0)
  %vecext.i.i.i5.4.i.i.i = extractelement <32 x i32> %0, i64 4
  tail call void @llvm.aie2p.put.ms(i32 %vecext.i.i.i5.4.i.i.i, i32 0)
  %vecext.i.i.i5.5.i.i.i = extractelement <32 x i32> %0, i64 5
  tail call void @llvm.aie2p.put.ms(i32 %vecext.i.i.i5.5.i.i.i, i32 0)
  %vecext.i.i.i5.6.i.i.i = extractelement <32 x i32> %0, i64 6
  tail call void @llvm.aie2p.put.ms(i32 %vecext.i.i.i5.6.i.i.i, i32 0)
  %vecext.i.i.i5.7.i.i.i = extractelement <32 x i32> %0, i64 7
  tail call void @llvm.aie2p.put.ms(i32 %vecext.i.i.i5.7.i.i.i, i32 0)
  %vecext.i.i.i5.8.i.i.i = extractelement <32 x i32> %0, i64 8
  tail call void @llvm.aie2p.put.ms(i32 %vecext.i.i.i5.8.i.i.i, i32 0)
  %vecext.i.i.i5.9.i.i.i = extractelement <32 x i32> %0, i64 9
  tail call void @llvm.aie2p.put.ms(i32 %vecext.i.i.i5.9.i.i.i, i32 0)
  %vecext.i.i.i5.10.i.i.i = extractelement <32 x i32> %0, i64 10
  tail call void @llvm.aie2p.put.ms(i32 %vecext.i.i.i5.10.i.i.i, i32 0)
  %vecext.i.i.i5.11.i.i.i = extractelement <32 x i32> %0, i64 11
  tail call void @llvm.aie2p.put.ms(i32 %vecext.i.i.i5.11.i.i.i, i32 0)
  %vecext.i.i.i5.12.i.i.i = extractelement <32 x i32> %0, i64 12
  tail call void @llvm.aie2p.put.ms(i32 %vecext.i.i.i5.12.i.i.i, i32 0)
  %vecext.i.i.i5.13.i.i.i = extractelement <32 x i32> %0, i64 13
  tail call void @llvm.aie2p.put.ms(i32 %vecext.i.i.i5.13.i.i.i, i32 0)
  %vecext.i.i.i5.14.i.i.i = extractelement <32 x i32> %0, i64 14
  tail call void @llvm.aie2p.put.ms(i32 %vecext.i.i.i5.14.i.i.i, i32 0)
  %vecext.i.i.i.i.i.i = extractelement <32 x i32> %0, i64 15
  tail call void @llvm.aie2p.put.ms(i32 %vecext.i.i.i.i.i.i, i32 0)
  %vecext.i.i.i5.i.i4.i = extractelement <32 x i32> %0, i64 16
  tail call void @llvm.aie2p.put.ms(i32 %vecext.i.i.i5.i.i4.i, i32 0)
  %vecext.i.i.i5.1.i.i5.i = extractelement <32 x i32> %0, i64 17
  tail call void @llvm.aie2p.put.ms(i32 %vecext.i.i.i5.1.i.i5.i, i32 0)
  %vecext.i.i.i5.2.i.i6.i = extractelement <32 x i32> %0, i64 18
  tail call void @llvm.aie2p.put.ms(i32 %vecext.i.i.i5.2.i.i6.i, i32 0)
  %vecext.i.i.i5.3.i.i7.i = extractelement <32 x i32> %0, i64 19
  tail call void @llvm.aie2p.put.ms(i32 %vecext.i.i.i5.3.i.i7.i, i32 0)
  %vecext.i.i.i5.4.i.i8.i = extractelement <32 x i32> %0, i64 20
  tail call void @llvm.aie2p.put.ms(i32 %vecext.i.i.i5.4.i.i8.i, i32 0)
  %vecext.i.i.i5.5.i.i9.i = extractelement <32 x i32> %0, i64 21
  tail call void @llvm.aie2p.put.ms(i32 %vecext.i.i.i5.5.i.i9.i, i32 0)
  %vecext.i.i.i5.6.i.i10.i = extractelement <32 x i32> %0, i64 22
  tail call void @llvm.aie2p.put.ms(i32 %vecext.i.i.i5.6.i.i10.i, i32 0)
  %vecext.i.i.i5.7.i.i11.i = extractelement <32 x i32> %0, i64 23
  tail call void @llvm.aie2p.put.ms(i32 %vecext.i.i.i5.7.i.i11.i, i32 0)
  %vecext.i.i.i5.8.i.i12.i = extractelement <32 x i32> %0, i64 24
  tail call void @llvm.aie2p.put.ms(i32 %vecext.i.i.i5.8.i.i12.i, i32 0)
  %vecext.i.i.i5.9.i.i13.i = extractelement <32 x i32> %0, i64 25
  tail call void @llvm.aie2p.put.ms(i32 %vecext.i.i.i5.9.i.i13.i, i32 0)
  %vecext.i.i.i5.10.i.i14.i = extractelement <32 x i32> %0, i64 26
  tail call void @llvm.aie2p.put.ms(i32 %vecext.i.i.i5.10.i.i14.i, i32 0)
  %vecext.i.i.i5.11.i.i15.i = extractelement <32 x i32> %0, i64 27
  tail call void @llvm.aie2p.put.ms(i32 %vecext.i.i.i5.11.i.i15.i, i32 0)
  %vecext.i.i.i5.12.i.i16.i = extractelement <32 x i32> %0, i64 28
  tail call void @llvm.aie2p.put.ms(i32 %vecext.i.i.i5.12.i.i16.i, i32 0)
  %vecext.i.i.i5.13.i.i17.i = extractelement <32 x i32> %0, i64 29
  tail call void @llvm.aie2p.put.ms(i32 %vecext.i.i.i5.13.i.i17.i, i32 0)
  %vecext.i.i.i5.14.i.i18.i = extractelement <32 x i32> %0, i64 30
  tail call void @llvm.aie2p.put.ms(i32 %vecext.i.i.i5.14.i.i18.i, i32 0)
  %vecext.i.i.i.i.i19.i = extractelement <32 x i32> %0, i64 31
  tail call void @llvm.aie2p.put.ms(i32 %vecext.i.i.i.i.i19.i, i32 %tlast)
  ret void
}

declare void @llvm.aie2p.mcd.write.vec(<16 x i32>, i32)
declare void @llvm.aie2p.mcd.write.acc32(<8 x i64>, i32)
declare { i32, i32 } @llvm.aie2p.get.ss()
declare { i32, i32 } @llvm.aie2p.get.ss.nb()
declare void @llvm.aie2p.put.ms(i32, i32)
declare i32 @llvm.aie2p.put.ms.nb(i32, i32)
