; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
; Attaching min iteration count to metadata
; RUN: opt -mtriple=aie2p -passes=hardware-loops %s -S -o - | FileCheck %s


@a = dso_local local_unnamed_addr global [6 x i32] [i32 1, i32 2, i32 3, i32 4, i32 5, i32 6], align 4
@b = dso_local local_unnamed_addr global [7 x i32] [i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 -12], align 4

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(read, argmem: none, inaccessiblemem: none)
define dso_local noundef i32 @attachMetadata() local_unnamed_addr #1 {
; CHECK-LABEL: define dso_local noundef i32 @attachMetadata(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.set.loop.iterations.i32(i32 6)
; CHECK-NEXT:    br label [[FOR_BODY_I:%.*]]
; CHECK:       for.body.i:
; CHECK-NEXT:    [[I_06_I:%.*]] = phi i32 [ [[INC_I:%.*]], [[FOR_BODY_I]] ], [ 0, [[ENTRY:%.*]] ]
; CHECK-NEXT:    [[SUM_05_I:%.*]] = phi i32 [ [[ADD_I:%.*]], [[FOR_BODY_I]] ], [ 0, [[ENTRY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = trunc i32 [[I_06_I]] to i20
; CHECK-NEXT:    [[ARRAYIDX_I:%.*]] = getelementptr inbounds i32, ptr @a, i20 [[TMP0]]
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX_I]], align 4, !tbaa [[TBAA2:![0-9]+]]
; CHECK-NEXT:    [[ADD_I]] = add nsw i32 [[TMP1]], [[SUM_05_I]]
; CHECK-NEXT:    [[INC_I]] = add nuw nsw i32 [[I_06_I]], 1
; CHECK-NEXT:    [[TMP2:%.*]] = call i1 @llvm.loop.decrement.i32(i32 1)
; CHECK-NEXT:    br i1 [[TMP2]], label [[FOR_BODY_I]], label [[FOR_BODY_I2_PREHEADER:%.*]], !llvm.loop [[LOOP6:![0-9]+]]
; CHECK:       for.body.i2.preheader:
; CHECK-NEXT:    [[I_06_I3_PH:%.*]] = phi i32 [ 0, [[FOR_BODY_I]] ]
; CHECK-NEXT:    [[SUM_05_I4_PH:%.*]] = phi i32 [ 0, [[FOR_BODY_I]] ]
; CHECK-NEXT:    call void @llvm.set.loop.iterations.i32(i32 7)
; CHECK-NEXT:    br label [[FOR_BODY_I2:%.*]]
; CHECK:       for.body.i2:
; CHECK-NEXT:    [[I_06_I3:%.*]] = phi i32 [ [[INC_I7:%.*]], [[FOR_BODY_I2]] ], [ [[I_06_I3_PH]], [[FOR_BODY_I2_PREHEADER]] ]
; CHECK-NEXT:    [[SUM_05_I4:%.*]] = phi i32 [ [[ADD_I6:%.*]], [[FOR_BODY_I2]] ], [ [[SUM_05_I4_PH]], [[FOR_BODY_I2_PREHEADER]] ]
; CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[I_06_I3]] to i20
; CHECK-NEXT:    [[ARRAYIDX_I5:%.*]] = getelementptr inbounds i32, ptr @b, i20 [[TMP3]]
; CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[ARRAYIDX_I5]], align 4, !tbaa [[TBAA2]]
; CHECK-NEXT:    [[ADD_I6]] = add nsw i32 [[TMP4]], [[SUM_05_I4]]
; CHECK-NEXT:    [[INC_I7]] = add nuw nsw i32 [[I_06_I3]], 1
; CHECK-NEXT:    [[TMP5:%.*]] = call i1 @llvm.loop.decrement.i32(i32 1)
; CHECK-NEXT:    br i1 [[TMP5]], label [[FOR_BODY_I2]], label [[_Z3SUMIPI_EXIT9:%.*]], !llvm.loop [[LOOP10:![0-9]+]]
; CHECK:       _Z3sumiPi.exit9:
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[ADD_I6]], [[ADD_I]]
; CHECK-NEXT:    ret i32 [[ADD]]
;
entry:
  br label %for.body.i

for.body.i:                                       ; preds = %for.body.i, %entry
  %i.06.i = phi i32 [ %inc.i, %for.body.i ], [ 0, %entry ]
  %sum.05.i = phi i32 [ %add.i, %for.body.i ], [ 0, %entry ]
  %0 = trunc i32 %i.06.i to i20
  %arrayidx.i = getelementptr inbounds i32, ptr @a, i20 %0
  %1 = load i32, ptr %arrayidx.i, align 4, !tbaa !2
  %add.i = add nsw i32 %1, %sum.05.i
  %inc.i = add nuw nsw i32 %i.06.i, 1
  %exitcond.not.i = icmp eq i32 %inc.i, 6
  br i1 %exitcond.not.i, label %for.body.i2, label %for.body.i, !llvm.loop !6

for.body.i2:                                      ; preds = %for.body.i, %for.body.i2
  %i.06.i3 = phi i32 [ %inc.i7, %for.body.i2 ], [ 0, %for.body.i ]
  %sum.05.i4 = phi i32 [ %add.i6, %for.body.i2 ], [ 0, %for.body.i ]
  %2 = trunc i32 %i.06.i3 to i20
  %arrayidx.i5 = getelementptr inbounds i32, ptr @b, i20 %2
  %3 = load i32, ptr %arrayidx.i5, align 4, !tbaa !2
  %add.i6 = add nsw i32 %3, %sum.05.i4
  %inc.i7 = add nuw nsw i32 %i.06.i3, 1
  %exitcond.not.i8 = icmp eq i32 %inc.i7, 7
  br i1 %exitcond.not.i8, label %_Z3sumiPi.exit9, label %for.body.i2, !llvm.loop !6

_Z3sumiPi.exit9:                                  ; preds = %for.body.i2
  %add = add nsw i32 %add.i6, %add.i
  ret i32 %add
}

attributes #0 = { mustprogress nofree norecurse nosync nounwind willreturn memory(argmem: read) "no-trapping-math"="true" "stack-protector-buffer-size"="8" }
attributes #1 = { mustprogress nofree norecurse nosync nounwind willreturn memory(read, argmem: none, inaccessiblemem: none) "no-trapping-math"="true" "stack-protector-buffer-size"="8" }

!llvm.module.flags = !{!0}
!llvm.ident = !{!1}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{!"clang version 19.0.0git"}
!2 = !{!3, !3, i64 0}
!3 = !{!"int", !4, i64 0}
!4 = !{!"omnipotent char", !5, i64 0}
!5 = !{!"Simple C++ TBAA"}
!6 = distinct !{!6, !7, !8}
!7 = !{!"llvm.loop.mustprogress"}
!8 = !{!"llvm.loop.unroll.disable"}


; In this test, no metadata is present in the loop
; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(read, inaccessiblemem: none)
define dso_local noundef i32 @noMetadata() local_unnamed_addr {
; CHECK-LABEL: define dso_local noundef i32 @noMetadata() local_unnamed_addr {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.set.loop.iterations.i32(i32 6)
; CHECK-NEXT:    br label [[FOR_BODY_I:%.*]]
; CHECK:       for.body.i:
; CHECK-NEXT:    [[SUM_06_I:%.*]] = phi i32 [ [[ADD_I:%.*]], [[FOR_BODY_I]] ], [ 0, [[ENTRY:%.*]] ]
; CHECK-NEXT:    [[VALUE_ADDR_05_I:%.*]] = phi ptr [ [[INCDEC_PTR_I:%.*]], [[FOR_BODY_I]] ], [ @a, [[ENTRY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[VALUE_ADDR_05_I]], align 4
; CHECK-NEXT:    [[ADD_I]] = add nsw i32 [[TMP0]], [[SUM_06_I]]
; CHECK-NEXT:    [[INCDEC_PTR_I]] = getelementptr inbounds i8, ptr [[VALUE_ADDR_05_I]], i20 4
; CHECK-NEXT:    [[TMP1:%.*]] = call i1 @llvm.loop.decrement.i32(i32 1)
; CHECK-NEXT:    br i1 [[TMP1]], label [[FOR_BODY_I]], label [[_Z3SUMIPI_EXIT:%.*]], !llvm.loop [[LOOP12:![0-9]+]]
; CHECK:       _Z3sumiPi.exit:
; CHECK-NEXT:    ret i32 [[ADD_I]]
;
entry:
  br label %for.body.i

for.body.i:                                       ; preds = %for.body.i, %entry
  %i.07.i = phi i32 [ %inc.i, %for.body.i ], [ 0, %entry ]
  %sum.06.i = phi i32 [ %add.i, %for.body.i ], [ 0, %entry ]
  %value.addr.05.i = phi ptr [ %incdec.ptr.i, %for.body.i ], [ @a, %entry ]
  %0 = load i32, ptr %value.addr.05.i, align 4
  %add.i = add nsw i32 %0, %sum.06.i
  %incdec.ptr.i = getelementptr inbounds i8, ptr %value.addr.05.i, i20 4
  %inc.i = add nuw nsw i32 %i.07.i, 1
  %exitcond.not.i = icmp eq i32 %inc.i, 6
  br i1 %exitcond.not.i, label %_Z3sumiPi.exit, label %for.body.i

_Z3sumiPi.exit:                                   ; preds = %for.body.i
  ret i32 %add.i
}
;.
; CHECK: [[TBAA2]] = !{[[META3:![0-9]+]], [[META3]], i64 0}
; CHECK: [[META3]] = !{!"int", [[META4:![0-9]+]], i64 0}
; CHECK: [[META4]] = !{!"omnipotent char", [[META5:![0-9]+]], i64 0}
; CHECK: [[META5]] = !{!"Simple C++ TBAA"}
; CHECK: [[LOOP6]] = distinct !{[[LOOP6]], [[META7:![0-9]+]], [[META8:![0-9]+]], [[META9:![0-9]+]]}
; CHECK: [[META7]] = !{!"llvm.loop.mustprogress"}
; CHECK: [[META8]] = !{!"llvm.loop.unroll.disable"}
; CHECK: [[META9]] = !{!"llvm.loop.itercount.range", i32 6}
; CHECK: [[LOOP10]] = distinct !{[[LOOP10]], [[META7]], [[META8]], [[META11:![0-9]+]]}
; CHECK: [[META11]] = !{!"llvm.loop.itercount.range", i32 7}
; CHECK: [[LOOP12]] = distinct !{[[LOOP12]], [[META9]]}
;.
