; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc < %s -verify-machineinstrs -mtriple=aie2p | FileCheck %s

define dso_local noundef <64 x i8> @_Z17unpack_I512_I8_I4Dv32_DB8_b(<32 x i8> noundef %v, i1 noundef zeroext %sign)  {
; CHECK-LABEL: _Z17unpack_I512_I8_I4Dv32_DB8_b:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    vunpack x0, wl2, unpacksign0; nopxm
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    mov unpacksign0, r0 // Delay Slot 4
; CHECK-NEXT:    mov crunpacksize, #0 // Delay Slot 3
; CHECK-NEXT:    mov unpacksign0, #0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %conv.i = zext i1 %sign to i32
  %0 = tail call noundef <64 x i8> @llvm.aie2p.unpack.I512.I8.I4(<32 x i8> %v, i32 %conv.i)
  ret <64 x i8> %0
}

define dso_local noundef <32 x i16> @_Z18unpack_I512_I16_I8Dv32_hb(<32 x i8> noundef %v, i1 noundef zeroext %sign)  {
; CHECK-LABEL: _Z18unpack_I512_I16_I8Dv32_hb:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    vunpack x0, wl2, unpacksign0; nopxm
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    mov unpacksign0, r0 // Delay Slot 4
; CHECK-NEXT:    mov crunpacksize, #1 // Delay Slot 3
; CHECK-NEXT:    mov unpacksign0, #0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %conv.i = zext i1 %sign to i32
  %0 = tail call noundef <32 x i16> @llvm.aie2p.unpack.I512.I16.I8(<32 x i8> %v, i32 %conv.i)
  ret <32 x i16> %0
}

define dso_local noundef <128 x i8> @_Z18unpack_I1024_I8_I4Dv64_DB8_b(<64 x i8> noundef %v, i1 noundef zeroext %sign)  {
; CHECK-LABEL: _Z18unpack_I1024_I8_I4Dv64_DB8_b:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    vunpack y2, x0, unpacksign0; nopxm
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    mov unpacksign0, r0 // Delay Slot 4
; CHECK-NEXT:    mov crunpacksize, #0 // Delay Slot 3
; CHECK-NEXT:    mov unpacksign0, #0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %conv.i = zext i1 %sign to i32
  %0 = tail call noundef <128 x i8> @llvm.aie2p.unpack.I1024.I8.I4(<64 x i8> %v, i32 %conv.i)
  ret <128 x i8> %0
}

define dso_local noundef <64 x i16> @_Z19unpack_I1024_I16_I8Dv64_ab(<64 x i8> noundef %v, i1 noundef zeroext %sign)  {
; CHECK-LABEL: _Z19unpack_I1024_I16_I8Dv64_ab:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    vunpack y2, x0, unpacksign0; nopxm
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    mov unpacksign0, r0 // Delay Slot 4
; CHECK-NEXT:    mov crunpacksize, #1 // Delay Slot 3
; CHECK-NEXT:    mov unpacksign0, #0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %conv.i = zext i1 %sign to i32
  %0 = tail call noundef <64 x i16> @llvm.aie2p.unpack.I1024.I16.I8(<64 x i8> %v, i32 %conv.i)
  ret <64 x i16> %0
}

declare <64 x i8> @llvm.aie2p.unpack.I512.I8.I4(<32 x i8>, i32)
declare <32 x i16> @llvm.aie2p.unpack.I512.I16.I8(<32 x i8>, i32)
declare <128 x i8> @llvm.aie2p.unpack.I1024.I8.I4(<64 x i8>, i32)
declare <64 x i16> @llvm.aie2p.unpack.I1024.I16.I8(<64 x i8>, i32)
