; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc < %s -verify-machineinstrs -mtriple=aie2p | FileCheck %s

%struct.v64bfp16ebs16 = type <{ <64 x i8>, <8 x i8> }>
%struct.v64bfp16ebs8 = type <{ <64 x i8>, <8 x i8> }>
%struct.v128bfp16ebs8 = type <{ <64 x i8>, <64 x i8>, <8 x i8>, <8 x i8> }>
%struct.v128bfp16ebs16 = type <{ <64 x i8>, <64 x i8>, <8 x i8>, <8 x i8> }>

define dso_local %struct.v64bfp16ebs16 @_Z11test_insert13v64bfp16ebs16Dv64_a(%struct.v64bfp16ebs16 %v.coerce, <64 x i8> noundef %m) local_unnamed_addr #0 {
; CHECK-LABEL: _Z11test_insert13v64bfp16ebs16Dv64_a:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    mov el0, el2 // Delay Slot 4
; CHECK-NEXT:    mov eh0, eh2 // Delay Slot 3
; CHECK-NEXT:    vmov x0, x4 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %v.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs16 %v.coerce, 1
  %.fca.0.insert.i = insertvalue %struct.v64bfp16ebs16 poison, <64 x i8> %m, 0
  %.fca.1.insert.i = insertvalue %struct.v64bfp16ebs16 %.fca.0.insert.i, <8 x i8> %v.coerce.fca.1.extract.i, 1
  ret %struct.v64bfp16ebs16 %.fca.1.insert.i
}

define dso_local noundef <64 x i8> @_Z20test_extract_v64int813v64bfp16ebs16(%struct.v64bfp16ebs16 %v.coerce) local_unnamed_addr #0 {
; CHECK-LABEL: _Z20test_extract_v64int813v64bfp16ebs16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vmov x0, x2 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %v.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs16 %v.coerce, 0
  ret <64 x i8> %v.coerce.fca.0.extract.i
}

define dso_local noundef <64 x i8> @_Z17test_extract_data13v64bfp16ebs16(%struct.v64bfp16ebs16 %v.coerce) local_unnamed_addr #0 {
; CHECK-LABEL: _Z17test_extract_data13v64bfp16ebs16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vmov x0, x2 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %v.coerce.fca.0.extract.i.i = extractvalue %struct.v64bfp16ebs16 %v.coerce, 0
  ret <64 x i8> %v.coerce.fca.0.extract.i.i
}

define dso_local %struct.v64bfp16ebs16 @_Z11test_insert13v64bfp16ebs16ii(%struct.v64bfp16ebs16 %v.coerce, i32 noundef %idx, i32 noundef %exp) local_unnamed_addr #0 {
; CHECK-LABEL: _Z11test_insert13v64bfp16ebs16ii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    or r27, r0, r0; mov r3, eh2
; CHECK-NEXT:    ret lr; mov r2, el2
; CHECK-NEXT:    sel.eqz r3, r3, r1, r27 // Delay Slot 5
; CHECK-NEXT:    sel.eqz r2, r1, r2, r27; vmov x0, x2 // Delay Slot 4
; CHECK-NEXT:    mov el0, r2 // Delay Slot 3
; CHECK-NEXT:    mov eh0, r3 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %cmp.i = icmp eq i32 %idx, 0
  %v.coerce.fca.1.extract.i13.i = extractvalue %struct.v64bfp16ebs16 %v.coerce, 1
  %shuffle.bc.i14.i = bitcast <8 x i8> %v.coerce.fca.1.extract.i13.i to <2 x i32>
  %shuffle.extract.i15.i = extractelement <2 x i32> %shuffle.bc.i14.i, i64 0
  %shuffle1.extract.i.i = extractelement <2 x i32> %shuffle.bc.i14.i, i64 1
  %exp32.sink.i = select i1 %cmp.i, i32 %shuffle1.extract.i.i, i32 %exp
  %.sink.v.i = select i1 %cmp.i, i32 %exp, i32 %shuffle.extract.i15.i
  %.sink.i = bitcast i32 %.sink.v.i to <4 x i8>
  %1 = bitcast i32 %exp32.sink.i to <4 x i8>
  %shuffle3.i = shufflevector <4 x i8> %.sink.i, <4 x i8> %1, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %.fca.1.insert12.i = insertvalue %struct.v64bfp16ebs16 %v.coerce, <8 x i8> %shuffle3.i, 1
  ret %struct.v64bfp16ebs16 %.fca.1.insert12.i
}

define dso_local noundef i32 @_Z21test_extract_exponent13v64bfp16ebs16i(%struct.v64bfp16ebs16 %v.coerce, i32 noundef %idx) local_unnamed_addr #0 {
; CHECK-LABEL: _Z21test_extract_exponent13v64bfp16ebs16i:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; ret lr; nopm ; nops
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    mov r2, el0 // Delay Slot 4
; CHECK-NEXT:    mov r3, eh0 // Delay Slot 3
; CHECK-NEXT:    or r27, r1, r1 // Delay Slot 2
; CHECK-NEXT:    sel.eqz r0, r2, r3, r27 // Delay Slot 1
entry:
  %v.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs16 %v.coerce, 1
  %cmp.i = icmp eq i32 %idx, 0
  %shuffle.bc.i = bitcast <8 x i8> %v.coerce.fca.1.extract.i to <2 x i32>
  %shuffle.extract.i = extractelement <2 x i32> %shuffle.bc.i, i64 0
  %shuffle1.extract.i = extractelement <2 x i32> %shuffle.bc.i, i64 1
  %retval.0.i = select i1 %cmp.i, i32 %shuffle.extract.i, i32 %shuffle1.extract.i
  ret i32 %retval.0.i
}

define dso_local %struct.v64bfp16ebs8 @_Z11test_insert12v64bfp16ebs8Dv64_a(%struct.v64bfp16ebs8 %v.coerce, <64 x i8> noundef %m) local_unnamed_addr #0 {
; CHECK-LABEL: _Z11test_insert12v64bfp16ebs8Dv64_a:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    mov el0, el2 // Delay Slot 4
; CHECK-NEXT:    mov eh0, eh2 // Delay Slot 3
; CHECK-NEXT:    vmov x0, x4 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %v.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %v.coerce, 1
  %.fca.0.insert.i = insertvalue %struct.v64bfp16ebs8 poison, <64 x i8> %m, 0
  %.fca.1.insert.i = insertvalue %struct.v64bfp16ebs8 %.fca.0.insert.i, <8 x i8> %v.coerce.fca.1.extract.i, 1
  ret %struct.v64bfp16ebs8 %.fca.1.insert.i
}

define dso_local noundef <64 x i8> @_Z20test_extract_v64int812v64bfp16ebs8(%struct.v64bfp16ebs8 %v.coerce) local_unnamed_addr #0 {
; CHECK-LABEL: _Z20test_extract_v64int812v64bfp16ebs8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vmov x0, x2 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %v.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %v.coerce, 0
  ret <64 x i8> %v.coerce.fca.0.extract.i
}

define dso_local noundef <64 x i8> @_Z17test_extract_data12v64bfp16ebs8(%struct.v64bfp16ebs8 %v.coerce) local_unnamed_addr #0 {
; CHECK-LABEL: _Z17test_extract_data12v64bfp16ebs8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vmov x0, x2 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %v.coerce.fca.0.extract.i.i = extractvalue %struct.v64bfp16ebs8 %v.coerce, 0
  ret <64 x i8> %v.coerce.fca.0.extract.i.i
}

define dso_local %struct.v64bfp16ebs8 @_Z11test_insert12v64bfp16ebs8ii(%struct.v64bfp16ebs8 %v.coerce, i32 noundef %idx, i32 noundef %exp) local_unnamed_addr #0 {
; CHECK-LABEL: _Z11test_insert12v64bfp16ebs8ii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    or r27, r0, r0; mov r3, eh2
; CHECK-NEXT:    ret lr; mov r2, el2
; CHECK-NEXT:    sel.eqz r3, r3, r1, r27 // Delay Slot 5
; CHECK-NEXT:    sel.eqz r2, r1, r2, r27; vmov x0, x2 // Delay Slot 4
; CHECK-NEXT:    mov el0, r2 // Delay Slot 3
; CHECK-NEXT:    mov eh0, r3 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %cmp.i = icmp eq i32 %idx, 0
  %v.coerce.fca.1.extract.i13.i = extractvalue %struct.v64bfp16ebs8 %v.coerce, 1
  %shuffle.bc.i14.i = bitcast <8 x i8> %v.coerce.fca.1.extract.i13.i to <2 x i32>
  %shuffle.extract.i15.i = extractelement <2 x i32> %shuffle.bc.i14.i, i64 0
  %shuffle1.extract.i.i = extractelement <2 x i32> %shuffle.bc.i14.i, i64 1
  %exp32.sink.i = select i1 %cmp.i, i32 %shuffle1.extract.i.i, i32 %exp
  %.sink.v.i = select i1 %cmp.i, i32 %exp, i32 %shuffle.extract.i15.i
  %.sink.i = bitcast i32 %.sink.v.i to <4 x i8>
  %1 = bitcast i32 %exp32.sink.i to <4 x i8>
  %shuffle3.i = shufflevector <4 x i8> %.sink.i, <4 x i8> %1, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %.fca.1.insert12.i = insertvalue %struct.v64bfp16ebs8 %v.coerce, <8 x i8> %shuffle3.i, 1
  ret %struct.v64bfp16ebs8 %.fca.1.insert12.i
}

define dso_local noundef i32 @_Z21test_extract_exponent12v64bfp16ebs8i(%struct.v64bfp16ebs8 %v.coerce, i32 noundef %idx) local_unnamed_addr #0 {
; CHECK-LABEL: _Z21test_extract_exponent12v64bfp16ebs8i:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; ret lr; nopm ; nops
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    mov r2, el0 // Delay Slot 4
; CHECK-NEXT:    mov r3, eh0 // Delay Slot 3
; CHECK-NEXT:    or r27, r1, r1 // Delay Slot 2
; CHECK-NEXT:    sel.eqz r0, r2, r3, r27 // Delay Slot 1
entry:
  %v.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %v.coerce, 1
  %cmp.i = icmp eq i32 %idx, 0
  %shuffle.bc.i = bitcast <8 x i8> %v.coerce.fca.1.extract.i to <2 x i32>
  %shuffle.extract.i = extractelement <2 x i32> %shuffle.bc.i, i64 0
  %shuffle1.extract.i = extractelement <2 x i32> %shuffle.bc.i, i64 1
  %retval.0.i = select i1 %cmp.i, i32 %shuffle.extract.i, i32 %shuffle1.extract.i
  ret i32 %retval.0.i
}

define dso_local noundef <32 x i8> @_Z20test_extract_v32int813v64bfp16ebs16i(%struct.v64bfp16ebs16 %v.coerce, i32 noundef %idx) local_unnamed_addr #0 {
; CHECK-LABEL: _Z20test_extract_v32int813v64bfp16ebs16i:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mova r1, #1; nopx
; CHECK-NEXT:    and r0, r0, r1
; CHECK-NEXT:    jz r0, #.LBB10_2
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    vmov x0, x2 // Delay Slot 1
; CHECK-NEXT:  // %bb.1: // %if.else.i.i
; CHECK-NEXT:    vmov wl0, wh0
; CHECK-NEXT:  .LBB10_2: // %_ZL15extract_v32int813v64bfp16ebs16i.exit
; CHECK-NEXT:    nopa ; ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %v.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs16 %v.coerce, 0
  %0 = bitcast <64 x i8> %v.coerce.fca.0.extract.i to <16 x i32>
  %1 = and i32 %idx, 1
  %cmp.i.i = icmp eq i32 %1, 0
  br i1 %cmp.i.i, label %if.then.i.i, label %if.else.i.i

if.then.i.i:                                      ; preds = %entry
  %shuffle.i.i = shufflevector <16 x i32> %0, <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  br label %_ZL15extract_v32int813v64bfp16ebs16i.exit

if.else.i.i:                                      ; preds = %entry
  %shuffle1.i.i = shufflevector <16 x i32> %0, <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  br label %_ZL15extract_v32int813v64bfp16ebs16i.exit

_ZL15extract_v32int813v64bfp16ebs16i.exit:        ; preds = %if.then.i.i, %if.else.i.i
  %retval.0.i.i = phi <8 x i32> [ %shuffle.i.i, %if.then.i.i ], [ %shuffle1.i.i, %if.else.i.i ]
  %2 = bitcast <8 x i32> %retval.0.i.i to <32 x i8>
  ret <32 x i8> %2
}

define dso_local noundef <32 x i8> @_Z20test_extract_v32int812v64bfp16ebs8i(%struct.v64bfp16ebs8 %v.coerce, i32 noundef %idx) local_unnamed_addr #0 {
; CHECK-LABEL: _Z20test_extract_v32int812v64bfp16ebs8i:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mova r1, #1; nopx
; CHECK-NEXT:    and r0, r0, r1
; CHECK-NEXT:    jz r0, #.LBB11_2
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    vmov x0, x2 // Delay Slot 1
; CHECK-NEXT:  // %bb.1: // %if.else.i.i
; CHECK-NEXT:    vmov wl0, wh0
; CHECK-NEXT:  .LBB11_2: // %_ZL15extract_v32int812v64bfp16ebs8i.exit
; CHECK-NEXT:    nopa ; ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %v.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %v.coerce, 0
  %0 = bitcast <64 x i8> %v.coerce.fca.0.extract.i to <16 x i32>
  %1 = and i32 %idx, 1
  %cmp.i.i = icmp eq i32 %1, 0
  br i1 %cmp.i.i, label %if.then.i.i, label %if.else.i.i

if.then.i.i:                                      ; preds = %entry
  %shuffle.i.i = shufflevector <16 x i32> %0, <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  br label %_ZL15extract_v32int812v64bfp16ebs8i.exit

if.else.i.i:                                      ; preds = %entry
  %shuffle1.i.i = shufflevector <16 x i32> %0, <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  br label %_ZL15extract_v32int812v64bfp16ebs8i.exit

_ZL15extract_v32int812v64bfp16ebs8i.exit:         ; preds = %if.then.i.i, %if.else.i.i
  %retval.0.i.i = phi <8 x i32> [ %shuffle.i.i, %if.then.i.i ], [ %shuffle1.i.i, %if.else.i.i ]
  %2 = bitcast <8 x i32> %retval.0.i.i to <32 x i8>
  ret <32 x i8> %2
}

define dso_local noundef <64 x i8> @_Z20test_extract_v64int813v128bfp16ebs8i(%struct.v128bfp16ebs8 %v.coerce, i32 noundef %idx) local_unnamed_addr #0 {
; CHECK-LABEL: _Z20test_extract_v64int813v128bfp16ebs8i:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    eqz r0, r0 // Delay Slot 4
; CHECK-NEXT:    add r16, r0, #-1 // Delay Slot 3
; CHECK-NEXT:    vsel.32 x0, x4, x5, r16 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %cmp.i = icmp eq i32 %idx, 0
  %v.coerce.fca.0.extract.i = extractvalue %struct.v128bfp16ebs8 %v.coerce, 0
  %v.coerce.fca.1.extract.i = extractvalue %struct.v128bfp16ebs8 %v.coerce, 1
  %retval.0.i = select i1 %cmp.i, <64 x i8> %v.coerce.fca.0.extract.i, <64 x i8> %v.coerce.fca.1.extract.i
  ret <64 x i8> %retval.0.i
}

define dso_local %struct.v128bfp16ebs8 @_Z11test_insert13v128bfp16ebs8iDv64_a(%struct.v128bfp16ebs8 %v.coerce, i32 noundef %idx, <64 x i8> noundef %m) local_unnamed_addr #0 {
; CHECK-LABEL: _Z11test_insert13v128bfp16ebs8iDv64_a:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mov el0, el4
; CHECK-NEXT:    ret lr; mov eh0, eh4
; CHECK-NEXT:    eqz r0, r0; mov el1, el5 // Delay Slot 5
; CHECK-NEXT:    add r16, r0, #-1; mov eh1, eh5 // Delay Slot 4
; CHECK-NEXT:    vsel.32 x0, x2, x4, r16 // Delay Slot 3
; CHECK-NEXT:    vsel.32 x1, x5, x2, r16 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %cmp.i = icmp eq i32 %idx, 0
  %v.coerce.fca.1.extract.i = extractvalue %struct.v128bfp16ebs8 %v.coerce, 1
  %v.coerce.fca.0.extract.i = extractvalue %struct.v128bfp16ebs8 %v.coerce, 0
  %retval.sroa.0.0.i = select i1 %cmp.i, <64 x i8> %m, <64 x i8> %v.coerce.fca.0.extract.i
  %retval.sroa.3.0.i = select i1 %cmp.i, <64 x i8> %v.coerce.fca.1.extract.i, <64 x i8> %m
  %v.coerce.fca.3.extract.i = extractvalue %struct.v128bfp16ebs8 %v.coerce, 3
  %v.coerce.fca.2.extract.i = extractvalue %struct.v128bfp16ebs8 %v.coerce, 2
  %.fca.0.insert.i = insertvalue %struct.v128bfp16ebs8 poison, <64 x i8> %retval.sroa.0.0.i, 0
  %.fca.1.insert.i = insertvalue %struct.v128bfp16ebs8 %.fca.0.insert.i, <64 x i8> %retval.sroa.3.0.i, 1
  %.fca.2.insert.i = insertvalue %struct.v128bfp16ebs8 %.fca.1.insert.i, <8 x i8> %v.coerce.fca.2.extract.i, 2
  %.fca.3.insert.i = insertvalue %struct.v128bfp16ebs8 %.fca.2.insert.i, <8 x i8> %v.coerce.fca.3.extract.i, 3
  ret %struct.v128bfp16ebs8 %.fca.3.insert.i
}

define dso_local %struct.v128bfp16ebs8 @_Z11test_concat12v64bfp16ebs8S_(%struct.v64bfp16ebs8 %v1.coerce, %struct.v64bfp16ebs8 %v2.coerce) local_unnamed_addr #0 {
; CHECK-LABEL: _Z11test_concat12v64bfp16ebs8S_:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nops ; mov el0, el2
; CHECK-NEXT:    ret lr; mov eh0, eh2
; CHECK-NEXT:    mov el1, el4 // Delay Slot 5
; CHECK-NEXT:    mov eh1, eh4 // Delay Slot 4
; CHECK-NEXT:    vmov x0, x2 // Delay Slot 3
; CHECK-NEXT:    vmov x1, x4 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %v1.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %v1.coerce, 0
  %v1.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %v1.coerce, 1
  %v2.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %v2.coerce, 0
  %v2.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %v2.coerce, 1
  %.fca.0.insert.i = insertvalue %struct.v128bfp16ebs8 poison, <64 x i8> %v1.coerce.fca.0.extract.i, 0
  %.fca.1.insert.i = insertvalue %struct.v128bfp16ebs8 %.fca.0.insert.i, <64 x i8> %v2.coerce.fca.0.extract.i, 1
  %.fca.2.insert.i = insertvalue %struct.v128bfp16ebs8 %.fca.1.insert.i, <8 x i8> %v1.coerce.fca.1.extract.i, 2
  %.fca.3.insert.i = insertvalue %struct.v128bfp16ebs8 %.fca.2.insert.i, <8 x i8> %v2.coerce.fca.1.extract.i, 3
  ret %struct.v128bfp16ebs8 %.fca.3.insert.i
}

define dso_local %struct.v128bfp16ebs8 @_Z11test_insert13v128bfp16ebs8i12v64bfp16ebs8(%struct.v128bfp16ebs8 %v.coerce, i32 noundef %idx, %struct.v64bfp16ebs8 %vsub.coerce) local_unnamed_addr #0 {
; CHECK-LABEL: _Z11test_insert13v128bfp16ebs8i12v64bfp16ebs8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; jz r0, #.LBB15_2
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    vmov x1, x2 // Delay Slot 3
; CHECK-NEXT:    mov r4, el2 // Delay Slot 2
; CHECK-NEXT:    mov r5, eh2 // Delay Slot 1
; CHECK-NEXT:  // %bb.1: // %if.end.i
; CHECK-NEXT:    j #.LBB15_3
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    vmov x0, x4 // Delay Slot 3
; CHECK-NEXT:    mov r2, el4 // Delay Slot 2
; CHECK-NEXT:    mov r3, eh4 // Delay Slot 1
; CHECK-NEXT:  .LBB15_2:
; CHECK-NEXT:    vmov x0, x1
; CHECK-NEXT:    mov r2, r4
; CHECK-NEXT:    mov r3, r5
; CHECK-NEXT:    mov r6, el5
; CHECK-NEXT:    mov r7, eh5
; CHECK-NEXT:    vmov x1, x5
; CHECK-NEXT:    mov r4, r6
; CHECK-NEXT:    mov r5, r7
; CHECK-NEXT:  .LBB15_3: // %_ZL6insert13v128bfp16ebs8i12v64bfp16ebs8.exit
; CHECK-NEXT:    nopa ; nopb ; ret lr; nopm ; nops
; CHECK-NEXT:    mov el0, r2 // Delay Slot 5
; CHECK-NEXT:    mov eh0, r3 // Delay Slot 4
; CHECK-NEXT:    mov el1, r4 // Delay Slot 3
; CHECK-NEXT:    mov eh1, r5 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %vsub.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %vsub.coerce, 0
  %vsub.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %vsub.coerce, 1
  %cmp.i = icmp eq i32 %idx, 0
  br i1 %cmp.i, label %if.then.i, label %if.end.i

if.then.i:                                        ; preds = %entry
  %v.coerce.fca.3.extract.i = extractvalue %struct.v128bfp16ebs8 %v.coerce, 3
  %v.coerce.fca.1.extract.i = extractvalue %struct.v128bfp16ebs8 %v.coerce, 1
  br label %_ZL6insert13v128bfp16ebs8i12v64bfp16ebs8.exit

if.end.i:                                         ; preds = %entry
  %v.coerce.fca.2.extract.i = extractvalue %struct.v128bfp16ebs8 %v.coerce, 2
  %v.coerce.fca.0.extract.i = extractvalue %struct.v128bfp16ebs8 %v.coerce, 0
  br label %_ZL6insert13v128bfp16ebs8i12v64bfp16ebs8.exit

_ZL6insert13v128bfp16ebs8i12v64bfp16ebs8.exit:    ; preds = %if.then.i, %if.end.i
  %retval.sroa.0.0.i = phi <64 x i8> [ %vsub.coerce.fca.0.extract.i, %if.then.i ], [ %v.coerce.fca.0.extract.i, %if.end.i ]
  %retval.sroa.3.0.i = phi <64 x i8> [ %v.coerce.fca.1.extract.i, %if.then.i ], [ %vsub.coerce.fca.0.extract.i, %if.end.i ]
  %retval.sroa.6.0.i = phi <8 x i8> [ %vsub.coerce.fca.1.extract.i, %if.then.i ], [ %v.coerce.fca.2.extract.i, %if.end.i ]
  %retval.sroa.9.0.i = phi <8 x i8> [ %v.coerce.fca.3.extract.i, %if.then.i ], [ %vsub.coerce.fca.1.extract.i, %if.end.i ]
  %.fca.0.insert.i = insertvalue %struct.v128bfp16ebs8 poison, <64 x i8> %retval.sroa.0.0.i, 0
  %.fca.1.insert.i = insertvalue %struct.v128bfp16ebs8 %.fca.0.insert.i, <64 x i8> %retval.sroa.3.0.i, 1
  %.fca.2.insert.i = insertvalue %struct.v128bfp16ebs8 %.fca.1.insert.i, <8 x i8> %retval.sroa.6.0.i, 2
  %.fca.3.insert.i = insertvalue %struct.v128bfp16ebs8 %.fca.2.insert.i, <8 x i8> %retval.sroa.9.0.i, 3
  ret %struct.v128bfp16ebs8 %.fca.3.insert.i
}

define dso_local %struct.v128bfp16ebs8 @_Z22test_set_v128bfp16ebs8i12v64bfp16ebs8(i32 noundef %idx, %struct.v64bfp16ebs8 %vsub.coerce) local_unnamed_addr #0 {
; CHECK-LABEL: _Z22test_set_v128bfp16ebs8i12v64bfp16ebs8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nops ; mov el0, el2
; CHECK-NEXT:    ret lr; mov eh0, eh2
; CHECK-NEXT:    mov el1, el2 // Delay Slot 5
; CHECK-NEXT:    mov eh1, eh2 // Delay Slot 4
; CHECK-NEXT:    vmov x0, x2 // Delay Slot 3
; CHECK-NEXT:    vmov x1, x2 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %vsub.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %vsub.coerce, 1
  %vsub.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %vsub.coerce, 0
  %.fca.0.insert.i = insertvalue %struct.v128bfp16ebs8 poison, <64 x i8> %vsub.coerce.fca.0.extract.i, 0
  %.fca.1.insert.i = insertvalue %struct.v128bfp16ebs8 %.fca.0.insert.i, <64 x i8> %vsub.coerce.fca.0.extract.i, 1
  %.fca.2.insert.i = insertvalue %struct.v128bfp16ebs8 %.fca.1.insert.i, <8 x i8> %vsub.coerce.fca.1.extract.i, 2
  %.fca.3.insert.i = insertvalue %struct.v128bfp16ebs8 %.fca.2.insert.i, <8 x i8> %vsub.coerce.fca.1.extract.i, 3
  ret %struct.v128bfp16ebs8 %.fca.3.insert.i
}

define dso_local %struct.v128bfp16ebs8 @_Z11test_insert13v128bfp16ebs8ii(%struct.v128bfp16ebs8 %v.coerce, i32 noundef %idx, i32 noundef %exp) local_unnamed_addr #0 {
; CHECK-LABEL: _Z11test_insert13v128bfp16ebs8ii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mova r2, #2; nopb ; nopx
; CHECK-NEXT:    and r7, r0, r2; vmov x0, x4
; CHECK-NEXT:    jnz r7, #.LBB17_2
; CHECK-NEXT:    vmov x1, x5 // Delay Slot 5
; CHECK-NEXT:    mov r3, eh4 // Delay Slot 4
; CHECK-NEXT:    mov r4, el5 // Delay Slot 3
; CHECK-NEXT:    mova r6, #1; mov r5, eh5 // Delay Slot 2
; CHECK-NEXT:    and r27, r0, r6; mov r2, el4 // Delay Slot 1
; CHECK-NEXT:  // %bb.1: // %if.then.i
; CHECK-NEXT:    j #.LBB17_3
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    sel.eqz r3, r3, r1, r27 // Delay Slot 2
; CHECK-NEXT:    sel.eqz r2, r1, r2, r27 // Delay Slot 1
; CHECK-NEXT:  .LBB17_2: // %if.end.i
; CHECK-NEXT:    nopa ; nopb ; sel.eqz r5, r5, r1, r27; nopm
; CHECK-NEXT:    sel.eqz r4, r1, r4, r27
; CHECK-NEXT:  .LBB17_3: // %_ZL6insert13v128bfp16ebs8ii.exit
; CHECK-NEXT:    nopa ; nopb ; ret lr; nopm ; nops
; CHECK-NEXT:    mov el0, r2 // Delay Slot 5
; CHECK-NEXT:    mov eh0, r3 // Delay Slot 4
; CHECK-NEXT:    mov el1, r4 // Delay Slot 3
; CHECK-NEXT:    mov eh1, r5 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %rem.i = and i32 %idx, 2
  %cmp.not.not.i = icmp eq i32 %rem.i, 0
  %rem5.i = and i32 %idx, 1
  %cmp.i.i = icmp eq i32 %rem5.i, 0
  br i1 %cmp.not.not.i, label %if.then.i, label %if.end.i

if.then.i:                                        ; preds = %entry
  %v.coerce.fca.2.extract.i = extractvalue %struct.v128bfp16ebs8 %v.coerce, 2
  %shuffle.bc.i14.i.i = bitcast <8 x i8> %v.coerce.fca.2.extract.i to <2 x i32>
  %shuffle.extract.i15.i.i = extractelement <2 x i32> %shuffle.bc.i14.i.i, i64 0
  %shuffle1.extract.i.i.i = extractelement <2 x i32> %shuffle.bc.i14.i.i, i64 1
  %exp32.sink.i.i = select i1 %cmp.i.i, i32 %shuffle1.extract.i.i.i, i32 %exp
  %.sink.v.i.i = select i1 %cmp.i.i, i32 %exp, i32 %shuffle.extract.i15.i.i
  %.sink.i.i = bitcast i32 %.sink.v.i.i to <4 x i8>
  %0 = bitcast i32 %exp32.sink.i.i to <4 x i8>
  %shuffle3.i.i = shufflevector <4 x i8> %.sink.i.i, <4 x i8> %0, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %v.coerce.fca.3.extract.i.i = extractvalue %struct.v128bfp16ebs8 %v.coerce, 3
  %.fca.2.insert.i.i = insertvalue %struct.v128bfp16ebs8 %v.coerce, <8 x i8> %shuffle3.i.i, 2
  br label %_ZL6insert13v128bfp16ebs8ii.exit

if.end.i:                                         ; preds = %entry
  %v.coerce.fca.3.extract.i = extractvalue %struct.v128bfp16ebs8 %v.coerce, 3
  %shuffle.bc.i14.i45.i = bitcast <8 x i8> %v.coerce.fca.3.extract.i to <2 x i32>
  %shuffle.extract.i15.i46.i = extractelement <2 x i32> %shuffle.bc.i14.i45.i, i64 0
  %shuffle1.extract.i.i48.i = extractelement <2 x i32> %shuffle.bc.i14.i45.i, i64 1
  %exp32.sink.i49.i = select i1 %cmp.i.i, i32 %shuffle1.extract.i.i48.i, i32 %exp
  %.sink.v.i50.i = select i1 %cmp.i.i, i32 %exp, i32 %shuffle.extract.i15.i46.i
  %.sink.i51.i = bitcast i32 %.sink.v.i50.i to <4 x i8>
  %1 = bitcast i32 %exp32.sink.i49.i to <4 x i8>
  %shuffle3.i52.i = shufflevector <4 x i8> %.sink.i51.i, <4 x i8> %1, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  br label %_ZL6insert13v128bfp16ebs8ii.exit

_ZL6insert13v128bfp16ebs8ii.exit:                 ; preds = %if.then.i, %if.end.i
  %.fca.2.insert.i.pn.i = phi %struct.v128bfp16ebs8 [ %.fca.2.insert.i.i, %if.then.i ], [ %v.coerce, %if.end.i ]
  %v.coerce.fca.3.extract.i.pn.i = phi <8 x i8> [ %v.coerce.fca.3.extract.i.i, %if.then.i ], [ %shuffle3.i52.i, %if.end.i ]
  %call6.pn.i = insertvalue %struct.v128bfp16ebs8 %.fca.2.insert.i.pn.i, <8 x i8> %v.coerce.fca.3.extract.i.pn.i, 3
  ret %struct.v128bfp16ebs8 %call6.pn.i
}

define dso_local noundef i32 @_Z21test_extract_exponent13v128bfp16ebs8i(%struct.v128bfp16ebs8 %v.coerce, i32 noundef %idx) local_unnamed_addr #0 {
; CHECK-LABEL: _Z21test_extract_exponent13v128bfp16ebs8i:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; jz r1, #.LBB18_5; nopv
; CHECK-NEXT:    nopa ; nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    mov r4, el0 // Delay Slot 2
; CHECK-NEXT:    mova r27, #0; mov r5, eh0 // Delay Slot 1
; CHECK-NEXT:  // %bb.1: // %entry
; CHECK-NEXT:    mova r0, #2
; CHECK-NEXT:    eq r0, r1, r0
; CHECK-NEXT:    jnz r0, #.LBB18_4
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    mov r2, el1 // Delay Slot 2
; CHECK-NEXT:    mov r3, eh1 // Delay Slot 1
; CHECK-NEXT:  // %bb.2: // %entry
; CHECK-NEXT:    mova r27, #1
; CHECK-NEXT:    ne r0, r1, r27
; CHECK-NEXT:    jnz r0, #.LBB18_4
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
; CHECK-NEXT:  // %bb.3:
; CHECK-NEXT:    mov r2, r4
; CHECK-NEXT:    mov r3, r5
; CHECK-NEXT:  .LBB18_4: // %_ZL16extract_exponent13v128bfp16ebs8i.exit
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    sel.nez r0, r3, r2, r27 // Delay Slot 1
; CHECK-NEXT:  .LBB18_5:
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mov r2, r4 // Delay Slot 3
; CHECK-NEXT:    mov r3, r5 // Delay Slot 2
; CHECK-NEXT:    sel.nez r0, r3, r2, r27 // Delay Slot 1
entry:
  %v.coerce.fca.2.extract.i = extractvalue %struct.v128bfp16ebs8 %v.coerce, 2
  %v.coerce.fca.3.extract.i = extractvalue %struct.v128bfp16ebs8 %v.coerce, 3
  switch i32 %idx, label %if.end8.i [
    i32 0, label %_ZL16extract_exponent13v128bfp16ebs8i.exit
    i32 1, label %if.then2.i
    i32 2, label %if.then6.i
  ]

if.then2.i:                                       ; preds = %entry
  br label %_ZL16extract_exponent13v128bfp16ebs8i.exit

if.then6.i:                                       ; preds = %entry
  br label %_ZL16extract_exponent13v128bfp16ebs8i.exit

if.end8.i:                                        ; preds = %entry
  br label %_ZL16extract_exponent13v128bfp16ebs8i.exit

_ZL16extract_exponent13v128bfp16ebs8i.exit:       ; preds = %entry, %if.then2.i, %if.then6.i, %if.end8.i
  %v.coerce.fca.3.extract.sink.i = phi <8 x i8> [ %v.coerce.fca.3.extract.i, %if.end8.i ], [ %v.coerce.fca.3.extract.i, %if.then6.i ], [ %v.coerce.fca.2.extract.i, %if.then2.i ], [ %v.coerce.fca.2.extract.i, %entry ]
  %.sink.i = phi i64 [ 1, %if.end8.i ], [ 0, %if.then6.i ], [ 1, %if.then2.i ], [ 0, %entry ]
  %shuffle9.bc.i = bitcast <8 x i8> %v.coerce.fca.3.extract.sink.i to <2 x i32>
  %shuffle9.extract.i = extractelement <2 x i32> %shuffle9.bc.i, i64 %.sink.i
  ret i32 %shuffle9.extract.i
}

define dso_local noundef <64 x i8> @_Z20test_extract_v64int814v128bfp16ebs16i(%struct.v128bfp16ebs16 %v.coerce, i32 noundef %idx) local_unnamed_addr #0 {
; CHECK-LABEL: _Z20test_extract_v64int814v128bfp16ebs16i:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    eqz r0, r0 // Delay Slot 4
; CHECK-NEXT:    add r16, r0, #-1 // Delay Slot 3
; CHECK-NEXT:    vsel.32 x0, x4, x5, r16 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %cmp.i = icmp eq i32 %idx, 0
  %v.coerce.fca.0.extract.i = extractvalue %struct.v128bfp16ebs16 %v.coerce, 0
  %v.coerce.fca.1.extract.i = extractvalue %struct.v128bfp16ebs16 %v.coerce, 1
  %retval.0.i = select i1 %cmp.i, <64 x i8> %v.coerce.fca.0.extract.i, <64 x i8> %v.coerce.fca.1.extract.i
  ret <64 x i8> %retval.0.i
}

define dso_local %struct.v128bfp16ebs16 @_Z11test_insert14v128bfp16ebs16iDv64_a(%struct.v128bfp16ebs16 %v.coerce, i32 noundef %idx, <64 x i8> noundef %m) local_unnamed_addr #0 {
; CHECK-LABEL: _Z11test_insert14v128bfp16ebs16iDv64_a:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mov el0, el4
; CHECK-NEXT:    ret lr; mov eh0, eh4
; CHECK-NEXT:    eqz r0, r0; mov el1, el5 // Delay Slot 5
; CHECK-NEXT:    add r16, r0, #-1; mov eh1, eh5 // Delay Slot 4
; CHECK-NEXT:    vsel.32 x0, x2, x4, r16 // Delay Slot 3
; CHECK-NEXT:    vsel.32 x1, x5, x2, r16 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %cmp.i = icmp eq i32 %idx, 0
  %v.coerce.fca.1.extract.i = extractvalue %struct.v128bfp16ebs16 %v.coerce, 1
  %v.coerce.fca.0.extract.i = extractvalue %struct.v128bfp16ebs16 %v.coerce, 0
  %retval.sroa.0.0.i = select i1 %cmp.i, <64 x i8> %m, <64 x i8> %v.coerce.fca.0.extract.i
  %retval.sroa.3.0.i = select i1 %cmp.i, <64 x i8> %v.coerce.fca.1.extract.i, <64 x i8> %m
  %v.coerce.fca.3.extract.i = extractvalue %struct.v128bfp16ebs16 %v.coerce, 3
  %v.coerce.fca.2.extract.i = extractvalue %struct.v128bfp16ebs16 %v.coerce, 2
  %.fca.0.insert.i = insertvalue %struct.v128bfp16ebs16 poison, <64 x i8> %retval.sroa.0.0.i, 0
  %.fca.1.insert.i = insertvalue %struct.v128bfp16ebs16 %.fca.0.insert.i, <64 x i8> %retval.sroa.3.0.i, 1
  %.fca.2.insert.i = insertvalue %struct.v128bfp16ebs16 %.fca.1.insert.i, <8 x i8> %v.coerce.fca.2.extract.i, 2
  %.fca.3.insert.i = insertvalue %struct.v128bfp16ebs16 %.fca.2.insert.i, <8 x i8> %v.coerce.fca.3.extract.i, 3
  ret %struct.v128bfp16ebs16 %.fca.3.insert.i
}

define dso_local %struct.v128bfp16ebs16 @_Z11test_concat13v64bfp16ebs16S_(%struct.v64bfp16ebs16 %v1.coerce, %struct.v64bfp16ebs16 %v2.coerce) local_unnamed_addr #0 {
; CHECK-LABEL: _Z11test_concat13v64bfp16ebs16S_:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nops ; mov el0, el2
; CHECK-NEXT:    ret lr; mov eh0, eh2
; CHECK-NEXT:    mov el1, el4 // Delay Slot 5
; CHECK-NEXT:    mov eh1, eh4 // Delay Slot 4
; CHECK-NEXT:    vmov x0, x2 // Delay Slot 3
; CHECK-NEXT:    vmov x1, x4 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %v1.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs16 %v1.coerce, 0
  %v1.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs16 %v1.coerce, 1
  %v2.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs16 %v2.coerce, 0
  %v2.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs16 %v2.coerce, 1
  %.fca.0.insert.i = insertvalue %struct.v128bfp16ebs16 poison, <64 x i8> %v1.coerce.fca.0.extract.i, 0
  %.fca.1.insert.i = insertvalue %struct.v128bfp16ebs16 %.fca.0.insert.i, <64 x i8> %v2.coerce.fca.0.extract.i, 1
  %.fca.2.insert.i = insertvalue %struct.v128bfp16ebs16 %.fca.1.insert.i, <8 x i8> %v1.coerce.fca.1.extract.i, 2
  %.fca.3.insert.i = insertvalue %struct.v128bfp16ebs16 %.fca.2.insert.i, <8 x i8> %v2.coerce.fca.1.extract.i, 3
  ret %struct.v128bfp16ebs16 %.fca.3.insert.i
}

define dso_local %struct.v128bfp16ebs16 @_Z11test_insert14v128bfp16ebs16i13v64bfp16ebs16(%struct.v128bfp16ebs16 %v.coerce, i32 noundef %idx, %struct.v64bfp16ebs16 %vsub.coerce) local_unnamed_addr #0 {
; CHECK-LABEL: _Z11test_insert14v128bfp16ebs16i13v64bfp16ebs16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; jz r0, #.LBB22_2
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    vmov x1, x2 // Delay Slot 3
; CHECK-NEXT:    mov r4, el2 // Delay Slot 2
; CHECK-NEXT:    mov r5, eh2 // Delay Slot 1
; CHECK-NEXT:  // %bb.1: // %if.end.i
; CHECK-NEXT:    j #.LBB22_3
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    vmov x0, x4 // Delay Slot 3
; CHECK-NEXT:    mov r2, el4 // Delay Slot 2
; CHECK-NEXT:    mov r3, eh4 // Delay Slot 1
; CHECK-NEXT:  .LBB22_2:
; CHECK-NEXT:    vmov x0, x1
; CHECK-NEXT:    mov r2, r4
; CHECK-NEXT:    mov r3, r5
; CHECK-NEXT:    mov r6, el5
; CHECK-NEXT:    mov r7, eh5
; CHECK-NEXT:    vmov x1, x5
; CHECK-NEXT:    mov r4, r6
; CHECK-NEXT:    mov r5, r7
; CHECK-NEXT:  .LBB22_3: // %_ZL6insert14v128bfp16ebs16i13v64bfp16ebs16.exit
; CHECK-NEXT:    nopa ; nopb ; ret lr; nopm ; nops
; CHECK-NEXT:    mov el0, r2 // Delay Slot 5
; CHECK-NEXT:    mov eh0, r3 // Delay Slot 4
; CHECK-NEXT:    mov el1, r4 // Delay Slot 3
; CHECK-NEXT:    mov eh1, r5 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %vsub.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs16 %vsub.coerce, 0
  %vsub.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs16 %vsub.coerce, 1
  %cmp.i = icmp eq i32 %idx, 0
  br i1 %cmp.i, label %if.then.i, label %if.end.i

if.then.i:                                        ; preds = %entry
  %v.coerce.fca.3.extract.i = extractvalue %struct.v128bfp16ebs16 %v.coerce, 3
  %v.coerce.fca.1.extract.i = extractvalue %struct.v128bfp16ebs16 %v.coerce, 1
  br label %_ZL6insert14v128bfp16ebs16i13v64bfp16ebs16.exit

if.end.i:                                         ; preds = %entry
  %v.coerce.fca.2.extract.i = extractvalue %struct.v128bfp16ebs16 %v.coerce, 2
  %v.coerce.fca.0.extract.i = extractvalue %struct.v128bfp16ebs16 %v.coerce, 0
  br label %_ZL6insert14v128bfp16ebs16i13v64bfp16ebs16.exit

_ZL6insert14v128bfp16ebs16i13v64bfp16ebs16.exit:  ; preds = %if.then.i, %if.end.i
  %retval.sroa.0.0.i = phi <64 x i8> [ %vsub.coerce.fca.0.extract.i, %if.then.i ], [ %v.coerce.fca.0.extract.i, %if.end.i ]
  %retval.sroa.3.0.i = phi <64 x i8> [ %v.coerce.fca.1.extract.i, %if.then.i ], [ %vsub.coerce.fca.0.extract.i, %if.end.i ]
  %retval.sroa.6.0.i = phi <8 x i8> [ %vsub.coerce.fca.1.extract.i, %if.then.i ], [ %v.coerce.fca.2.extract.i, %if.end.i ]
  %retval.sroa.9.0.i = phi <8 x i8> [ %v.coerce.fca.3.extract.i, %if.then.i ], [ %vsub.coerce.fca.1.extract.i, %if.end.i ]
  %.fca.0.insert.i = insertvalue %struct.v128bfp16ebs16 poison, <64 x i8> %retval.sroa.0.0.i, 0
  %.fca.1.insert.i = insertvalue %struct.v128bfp16ebs16 %.fca.0.insert.i, <64 x i8> %retval.sroa.3.0.i, 1
  %.fca.2.insert.i = insertvalue %struct.v128bfp16ebs16 %.fca.1.insert.i, <8 x i8> %retval.sroa.6.0.i, 2
  %.fca.3.insert.i = insertvalue %struct.v128bfp16ebs16 %.fca.2.insert.i, <8 x i8> %retval.sroa.9.0.i, 3
  ret %struct.v128bfp16ebs16 %.fca.3.insert.i
}

define dso_local %struct.v128bfp16ebs16 @_Z23test_set_v128bfp16ebs16i13v64bfp16ebs16(i32 noundef %idx, %struct.v64bfp16ebs16 %vsub.coerce) local_unnamed_addr #0 {
; CHECK-LABEL: _Z23test_set_v128bfp16ebs16i13v64bfp16ebs16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nops ; mov el0, el2
; CHECK-NEXT:    ret lr; mov eh0, eh2
; CHECK-NEXT:    mov el1, el2 // Delay Slot 5
; CHECK-NEXT:    mov eh1, eh2 // Delay Slot 4
; CHECK-NEXT:    vmov x0, x2 // Delay Slot 3
; CHECK-NEXT:    vmov x1, x2 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %vsub.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs16 %vsub.coerce, 1
  %vsub.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs16 %vsub.coerce, 0
  %.fca.0.insert.i = insertvalue %struct.v128bfp16ebs16 poison, <64 x i8> %vsub.coerce.fca.0.extract.i, 0
  %.fca.1.insert.i = insertvalue %struct.v128bfp16ebs16 %.fca.0.insert.i, <64 x i8> %vsub.coerce.fca.0.extract.i, 1
  %.fca.2.insert.i = insertvalue %struct.v128bfp16ebs16 %.fca.1.insert.i, <8 x i8> %vsub.coerce.fca.1.extract.i, 2
  %.fca.3.insert.i = insertvalue %struct.v128bfp16ebs16 %.fca.2.insert.i, <8 x i8> %vsub.coerce.fca.1.extract.i, 3
  ret %struct.v128bfp16ebs16 %.fca.3.insert.i
}

define dso_local %struct.v128bfp16ebs16 @_Z11test_insert14v128bfp16ebs16ii(%struct.v128bfp16ebs16 %v.coerce, i32 noundef %idx, i32 noundef %exp) local_unnamed_addr #0 {
; CHECK-LABEL: _Z11test_insert14v128bfp16ebs16ii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mova r2, #2; nopb ; nopx
; CHECK-NEXT:    ge r7, r0, r2; vmov x0, x4
; CHECK-NEXT:    jnz r7, #.LBB24_2
; CHECK-NEXT:    vmov x1, x5 // Delay Slot 5
; CHECK-NEXT:    mov r3, eh4 // Delay Slot 4
; CHECK-NEXT:    mov r4, el5 // Delay Slot 3
; CHECK-NEXT:    mova r6, #1; mov r5, eh5 // Delay Slot 2
; CHECK-NEXT:    and r27, r0, r6; mov r2, el4 // Delay Slot 1
; CHECK-NEXT:  // %bb.1: // %if.then.i
; CHECK-NEXT:    j #.LBB24_3
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    sel.eqz r3, r3, r1, r27 // Delay Slot 2
; CHECK-NEXT:    sel.eqz r2, r1, r2, r27 // Delay Slot 1
; CHECK-NEXT:  .LBB24_2: // %if.end.i
; CHECK-NEXT:    nopa ; nopb ; sel.eqz r5, r5, r1, r27; nopm
; CHECK-NEXT:    sel.eqz r4, r1, r4, r27
; CHECK-NEXT:  .LBB24_3: // %_ZL6insert14v128bfp16ebs16ii.exit
; CHECK-NEXT:    nopa ; nopb ; ret lr; nopm ; nops
; CHECK-NEXT:    mov el0, r2 // Delay Slot 5
; CHECK-NEXT:    mov eh0, r3 // Delay Slot 4
; CHECK-NEXT:    mov el1, r4 // Delay Slot 3
; CHECK-NEXT:    mov eh1, r5 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %cmp.i = icmp slt i32 %idx, 2
  %rem.i = and i32 %idx, 1
  %cmp.i.i = icmp eq i32 %rem.i, 0
  br i1 %cmp.i, label %if.then.i, label %if.end.i

if.then.i:                                        ; preds = %entry
  %v.coerce.fca.2.extract.i = extractvalue %struct.v128bfp16ebs16 %v.coerce, 2
  %shuffle.bc.i14.i.i = bitcast <8 x i8> %v.coerce.fca.2.extract.i to <2 x i32>
  %shuffle.extract.i15.i.i = extractelement <2 x i32> %shuffle.bc.i14.i.i, i64 0
  %shuffle1.extract.i.i.i = extractelement <2 x i32> %shuffle.bc.i14.i.i, i64 1
  %exp32.sink.i.i = select i1 %cmp.i.i, i32 %shuffle1.extract.i.i.i, i32 %exp
  %.sink.v.i.i = select i1 %cmp.i.i, i32 %exp, i32 %shuffle.extract.i15.i.i
  %.sink.i.i = bitcast i32 %.sink.v.i.i to <4 x i8>
  %0 = bitcast i32 %exp32.sink.i.i to <4 x i8>
  %shuffle3.i.i = shufflevector <4 x i8> %.sink.i.i, <4 x i8> %0, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %v.coerce.fca.3.extract.i.i = extractvalue %struct.v128bfp16ebs16 %v.coerce, 3
  %.fca.2.insert.i.i = insertvalue %struct.v128bfp16ebs16 %v.coerce, <8 x i8> %shuffle3.i.i, 2
  br label %_ZL6insert14v128bfp16ebs16ii.exit

if.end.i:                                         ; preds = %entry
  %v.coerce.fca.3.extract.i = extractvalue %struct.v128bfp16ebs16 %v.coerce, 3
  %shuffle.bc.i14.i44.i = bitcast <8 x i8> %v.coerce.fca.3.extract.i to <2 x i32>
  %shuffle.extract.i15.i45.i = extractelement <2 x i32> %shuffle.bc.i14.i44.i, i64 0
  %shuffle1.extract.i.i47.i = extractelement <2 x i32> %shuffle.bc.i14.i44.i, i64 1
  %exp32.sink.i48.i = select i1 %cmp.i.i, i32 %shuffle1.extract.i.i47.i, i32 %exp
  %.sink.v.i49.i = select i1 %cmp.i.i, i32 %exp, i32 %shuffle.extract.i15.i45.i
  %.sink.i50.i = bitcast i32 %.sink.v.i49.i to <4 x i8>
  %1 = bitcast i32 %exp32.sink.i48.i to <4 x i8>
  %shuffle3.i51.i = shufflevector <4 x i8> %.sink.i50.i, <4 x i8> %1, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  br label %_ZL6insert14v128bfp16ebs16ii.exit

_ZL6insert14v128bfp16ebs16ii.exit:                ; preds = %if.then.i, %if.end.i
  %.fca.2.insert.i.pn.i = phi %struct.v128bfp16ebs16 [ %.fca.2.insert.i.i, %if.then.i ], [ %v.coerce, %if.end.i ]
  %v.coerce.fca.3.extract.i.pn.i = phi <8 x i8> [ %v.coerce.fca.3.extract.i.i, %if.then.i ], [ %shuffle3.i51.i, %if.end.i ]
  %call5.pn.i = insertvalue %struct.v128bfp16ebs16 %.fca.2.insert.i.pn.i, <8 x i8> %v.coerce.fca.3.extract.i.pn.i, 3
  ret %struct.v128bfp16ebs16 %call5.pn.i
}


define dso_local noundef i32 @_Z21test_extract_exponent14v128bfp16ebs16i(%struct.v128bfp16ebs16 %v.coerce, i32 noundef %idx) local_unnamed_addr #0 {
; CHECK-LABEL: _Z21test_extract_exponent14v128bfp16ebs16i:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; jz r1, #.LBB25_5; nopv
; CHECK-NEXT:    nopa ; nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    mov r4, el0 // Delay Slot 2
; CHECK-NEXT:    mova r27, #0; mov r5, eh0 // Delay Slot 1
; CHECK-NEXT:  // %bb.1: // %entry
; CHECK-NEXT:    mova r0, #2
; CHECK-NEXT:    eq r0, r1, r0
; CHECK-NEXT:    jnz r0, #.LBB25_4
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    mov r2, el1 // Delay Slot 2
; CHECK-NEXT:    mov r3, eh1 // Delay Slot 1
; CHECK-NEXT:  // %bb.2: // %entry
; CHECK-NEXT:    mova r27, #1
; CHECK-NEXT:    ne r0, r1, r27
; CHECK-NEXT:    jnz r0, #.LBB25_4
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
; CHECK-NEXT:  // %bb.3:
; CHECK-NEXT:    mov r2, r4
; CHECK-NEXT:    mov r3, r5
; CHECK-NEXT:  .LBB25_4: // %_ZL16extract_exponent14v128bfp16ebs16i.exit
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    sel.nez r0, r3, r2, r27 // Delay Slot 1
; CHECK-NEXT:  .LBB25_5:
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mov r2, r4 // Delay Slot 3
; CHECK-NEXT:    mov r3, r5 // Delay Slot 2
; CHECK-NEXT:    sel.nez r0, r3, r2, r27 // Delay Slot 1
entry:
  %v.coerce.fca.2.extract.i = extractvalue %struct.v128bfp16ebs16 %v.coerce, 2
  %v.coerce.fca.3.extract.i = extractvalue %struct.v128bfp16ebs16 %v.coerce, 3
  switch i32 %idx, label %if.end8.i [
    i32 0, label %_ZL16extract_exponent14v128bfp16ebs16i.exit
    i32 1, label %if.then2.i
    i32 2, label %if.then6.i
  ]

if.then2.i:                                       ; preds = %entry
  br label %_ZL16extract_exponent14v128bfp16ebs16i.exit

if.then6.i:                                       ; preds = %entry
  br label %_ZL16extract_exponent14v128bfp16ebs16i.exit

if.end8.i:                                        ; preds = %entry
  br label %_ZL16extract_exponent14v128bfp16ebs16i.exit

_ZL16extract_exponent14v128bfp16ebs16i.exit:      ; preds = %entry, %if.then2.i, %if.then6.i, %if.end8.i
  %v.coerce.fca.3.extract.sink.i = phi <8 x i8> [ %v.coerce.fca.3.extract.i, %if.end8.i ], [ %v.coerce.fca.3.extract.i, %if.then6.i ], [ %v.coerce.fca.2.extract.i, %if.then2.i ], [ %v.coerce.fca.2.extract.i, %entry ]
  %.sink.i = phi i64 [ 1, %if.end8.i ], [ 0, %if.then6.i ], [ 1, %if.then2.i ], [ 0, %entry ]
  %shuffle9.bc.i = bitcast <8 x i8> %v.coerce.fca.3.extract.sink.i to <2 x i32>
  %shuffle9.extract.i = extractelement <2 x i32> %shuffle9.bc.i, i64 %.sink.i
  ret i32 %shuffle9.extract.i
}

attributes #0 = { mustprogress nofree norecurse nosync nounwind willreturn memory(none) "no-builtin-memcpy" "no-builtin-memmove" "no-builtin-memset" "no-trapping-math"="true" "stack-protector-buffer-size"="8" }

!llvm.module.flags = !{!0}
!llvm.ident = !{!1}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{!"clang version 19.0.0git (/scratch/llvm-aie/clang d1a8b6d8ab81576eadc0f94c0bfe11e49842fb01)"}
