; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie2p -verify-machineinstrs -o - < %s | FileCheck %s


%struct.v64bfp16ebs8 = type <{ <64 x i8>, <8 x i8> }>
%struct.v128bfp16ebs8 = type <{ <64 x i8>, <64 x i8>, <8 x i8>, <8 x i8> }>

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z17test_mul_8x8_8x8T12v64bfp16ebs8S_(%struct.v64bfp16ebs8 %a.coerce, %struct.v64bfp16ebs8 %b.coerce) local_unnamed_addr  {
; CHECK-LABEL: _Z17test_mul_8x8_8x8T12v64bfp16ebs8S_:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r0, #780; nopb ; nopxm ; nops
; CHECK-NEXT:    vmul.f dm0, ex0, ex1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 1
  %0 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mul.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <8 x i8> %b.coerce.fca.1.extract.i, i32 780)
  %1 = bitcast <64 x i32> %0 to <64 x float>
  ret <64 x float> %1
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z20test_negmul_8x8_8x8T12v64bfp16ebs8S_(%struct.v64bfp16ebs8 %a.coerce, %struct.v64bfp16ebs8 %b.coerce) local_unnamed_addr  {
; CHECK-LABEL: _Z20test_negmul_8x8_8x8T12v64bfp16ebs8S_:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r0, #780; nopb ; nopxm ; nops
; CHECK-NEXT:    vnegmul.f dm0, ex0, ex1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 1
  %0 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.negmul.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <8 x i8> %b.coerce.fca.1.extract.i, i32 780)
  %1 = bitcast <64 x i32> %0 to <64 x float>
  ret <64 x float> %1
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z17test_mac_8x8_8x8T12v64bfp16ebs8S_Dv64_u10__accfloat(%struct.v64bfp16ebs8 %a.coerce, %struct.v64bfp16ebs8 %b.coerce, <64 x float> inreg noundef %acc) local_unnamed_addr  {
; CHECK-LABEL: _Z17test_mac_8x8_8x8T12v64bfp16ebs8S_Dv64_u10__accfloat:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r0, #780; nopb ; nopxm ; nops
; CHECK-NEXT:    vmac.f dm0, dm1, ex0, ex1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 1
  %0 = bitcast <64 x float> %acc to <64 x i32>
  %1 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mac.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <8 x i8> %b.coerce.fca.1.extract.i, <64 x i32> %0, i32 780)
  %2 = bitcast <64 x i32> %1 to <64 x float>
  ret <64 x float> %2
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z17test_msc_8x8_8x8T12v64bfp16ebs8S_Dv64_u10__accfloat(%struct.v64bfp16ebs8 %a.coerce, %struct.v64bfp16ebs8 %b.coerce, <64 x float> inreg noundef %acc) local_unnamed_addr  {
; CHECK-LABEL: _Z17test_msc_8x8_8x8T12v64bfp16ebs8S_Dv64_u10__accfloat:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r0, #780; nopb ; nopxm ; nops
; CHECK-NEXT:    vmsc.f dm0, dm1, ex0, ex1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 1
  %0 = bitcast <64 x float> %acc to <64 x i32>
  %1 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.msc.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <8 x i8> %b.coerce.fca.1.extract.i, <64 x i32> %0, i32 780)
  %2 = bitcast <64 x i32> %1 to <64 x float>
  ret <64 x float> %2
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z20test_addmac_8x8_8x8T12v64bfp16ebs8S_Dv64_u10__accfloatS0_(%struct.v64bfp16ebs8 %a.coerce, %struct.v64bfp16ebs8 %b.coerce, <64 x float> inreg noundef %acc1, <64 x float> inreg noundef %acc2) local_unnamed_addr  {
; CHECK-LABEL: _Z20test_addmac_8x8_8x8T12v64bfp16ebs8S_Dv64_u10__accfloatS0_:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopx ; vmov.d dm0, dm1
; CHECK-NEXT:    mova r0, #780
; CHECK-NEXT:    vaddmac.f dm0, dm0, dm2, ex0, ex1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 1
  %0 = bitcast <64 x float> %acc1 to <64 x i32>
  %1 = bitcast <64 x float> %acc2 to <64 x i32>
  %2 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.addmac.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <8 x i8> %b.coerce.fca.1.extract.i, <64 x i32> %0, <64 x i32> %1, i32 780)
  %3 = bitcast <64 x i32> %2 to <64 x float>
  ret <64 x float> %3
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z20test_addmsc_8x8_8x8T12v64bfp16ebs8S_Dv64_u10__accfloatS0_(%struct.v64bfp16ebs8 %a.coerce, %struct.v64bfp16ebs8 %b.coerce, <64 x float> inreg noundef %acc1, <64 x float> inreg noundef %acc2) local_unnamed_addr  {
; CHECK-LABEL: _Z20test_addmsc_8x8_8x8T12v64bfp16ebs8S_Dv64_u10__accfloatS0_:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopx ; vmov.d dm0, dm1
; CHECK-NEXT:    mova r0, #780
; CHECK-NEXT:    vaddmsc.f dm0, dm0, dm2, ex0, ex1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 1
  %0 = bitcast <64 x float> %acc1 to <64 x i32>
  %1 = bitcast <64 x float> %acc2 to <64 x i32>
  %2 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.addmsc.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <8 x i8> %b.coerce.fca.1.extract.i, <64 x i32> %0, <64 x i32> %1, i32 780)
  %3 = bitcast <64 x i32> %2 to <64 x float>
  ret <64 x float> %3
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z17test_mul_8x8_8x8T12v64bfp16ebs8iS_i(%struct.v64bfp16ebs8 %a.coerce, i32 noundef %sgn_x, %struct.v64bfp16ebs8 %b.coerce, i32 noundef %sgn_y) local_unnamed_addr  {
; CHECK-LABEL: _Z17test_mul_8x8_8x8T12v64bfp16ebs8iS_i:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r2, #9; nopxm
; CHECK-NEXT:    mova r3, #8; lshl r0, r0, r2
; CHECK-NEXT:    lshl r1, r1, r3
; CHECK-NEXT:    mova r2, #12; or r0, r0, r1
; CHECK-NEXT:    or r0, r0, r2
; CHECK-NEXT:    vmul.f dm0, ex0, ex1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 1
  %shl14.i.i = shl i32 %sgn_x, 9
  %shl15.i.i = shl i32 %sgn_y, 8
  %or5.i.i = or i32 %shl14.i.i, %shl15.i.i
  %or19.i.i = or disjoint i32 %or5.i.i, 12
  %0 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mul.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <8 x i8> %b.coerce.fca.1.extract.i, i32 %or19.i.i)
  %1 = bitcast <64 x i32> %0 to <64 x float>
  ret <64 x float> %1
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z20test_negmul_8x8_8x8T12v64bfp16ebs8iS_i(%struct.v64bfp16ebs8 %a.coerce, i32 noundef %sgn_x, %struct.v64bfp16ebs8 %b.coerce, i32 noundef %sgn_y) local_unnamed_addr  {
; CHECK-LABEL: _Z20test_negmul_8x8_8x8T12v64bfp16ebs8iS_i:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r2, #9; nopxm
; CHECK-NEXT:    mova r3, #8; lshl r0, r0, r2
; CHECK-NEXT:    lshl r1, r1, r3
; CHECK-NEXT:    mova r2, #12; or r0, r0, r1
; CHECK-NEXT:    or r0, r0, r2
; CHECK-NEXT:    vnegmul.f dm0, ex0, ex1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 1
  %shl14.i.i = shl i32 %sgn_x, 9
  %shl15.i.i = shl i32 %sgn_y, 8
  %or5.i.i = or i32 %shl14.i.i, %shl15.i.i
  %or19.i.i = or disjoint i32 %or5.i.i, 12
  %0 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.negmul.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <8 x i8> %b.coerce.fca.1.extract.i, i32 %or19.i.i)
  %1 = bitcast <64 x i32> %0 to <64 x float>
  ret <64 x float> %1
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z17test_mac_8x8_8x8T12v64bfp16ebs8iS_iDv64_u10__accfloat(%struct.v64bfp16ebs8 %a.coerce, i32 noundef %sgn_x, %struct.v64bfp16ebs8 %b.coerce, i32 noundef %sgn_y, <64 x float> inreg noundef %acc) local_unnamed_addr  {
; CHECK-LABEL: _Z17test_mac_8x8_8x8T12v64bfp16ebs8iS_iDv64_u10__accfloat:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r2, #9; nopxm
; CHECK-NEXT:    mova r3, #8; lshl r0, r0, r2
; CHECK-NEXT:    lshl r1, r1, r3
; CHECK-NEXT:    mova r2, #12; or r0, r0, r1
; CHECK-NEXT:    or r0, r0, r2
; CHECK-NEXT:    vmac.f dm0, dm1, ex0, ex1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 1
  %shl14.i.i = shl i32 %sgn_x, 9
  %shl15.i.i = shl i32 %sgn_y, 8
  %or5.i.i = or i32 %shl14.i.i, %shl15.i.i
  %or19.i.i = or disjoint i32 %or5.i.i, 12
  %0 = bitcast <64 x float> %acc to <64 x i32>
  %1 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mac.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <8 x i8> %b.coerce.fca.1.extract.i, <64 x i32> %0, i32 %or19.i.i)
  %2 = bitcast <64 x i32> %1 to <64 x float>
  ret <64 x float> %2
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z17test_msc_8x8_8x8T12v64bfp16ebs8iS_iDv64_u10__accfloat(%struct.v64bfp16ebs8 %a.coerce, i32 noundef %sgn_x, %struct.v64bfp16ebs8 %b.coerce, i32 noundef %sgn_y, <64 x float> inreg noundef %acc) local_unnamed_addr  {
; CHECK-LABEL: _Z17test_msc_8x8_8x8T12v64bfp16ebs8iS_iDv64_u10__accfloat:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r2, #9; nopxm
; CHECK-NEXT:    mova r3, #8; lshl r0, r0, r2
; CHECK-NEXT:    lshl r1, r1, r3
; CHECK-NEXT:    mova r2, #12; or r0, r0, r1
; CHECK-NEXT:    or r0, r0, r2
; CHECK-NEXT:    vmsc.f dm0, dm1, ex0, ex1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 1
  %shl14.i.i = shl i32 %sgn_x, 9
  %shl15.i.i = shl i32 %sgn_y, 8
  %or5.i.i = or i32 %shl14.i.i, %shl15.i.i
  %or19.i.i = or disjoint i32 %or5.i.i, 12
  %0 = bitcast <64 x float> %acc to <64 x i32>
  %1 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.msc.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <8 x i8> %b.coerce.fca.1.extract.i, <64 x i32> %0, i32 %or19.i.i)
  %2 = bitcast <64 x i32> %1 to <64 x float>
  ret <64 x float> %2
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z20test_addmac_8x8_8x8T12v64bfp16ebs8iS_iDv64_u10__accfloatS0_(%struct.v64bfp16ebs8 %a.coerce, i32 noundef %sgn_x, %struct.v64bfp16ebs8 %b.coerce, i32 noundef %sgn_y, <64 x float> inreg noundef %acc1, <64 x float> inreg noundef %acc2) local_unnamed_addr  {
; CHECK-LABEL: _Z20test_addmac_8x8_8x8T12v64bfp16ebs8iS_iDv64_u10__accfloatS0_:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r2, #9; nopx
; CHECK-NEXT:    mova r3, #8; lshl r0, r0, r2
; CHECK-NEXT:    lshl r1, r1, r3
; CHECK-NEXT:    mova r2, #12; or r0, r0, r1; vmov.d dm0, dm1
; CHECK-NEXT:    or r0, r0, r2
; CHECK-NEXT:    vaddmac.f dm0, dm0, dm2, ex0, ex1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 1
  %shl14.i.i = shl i32 %sgn_x, 9
  %shl15.i.i = shl i32 %sgn_y, 8
  %or5.i.i = or i32 %shl14.i.i, %shl15.i.i
  %or19.i.i = or disjoint i32 %or5.i.i, 12
  %0 = bitcast <64 x float> %acc1 to <64 x i32>
  %1 = bitcast <64 x float> %acc2 to <64 x i32>
  %2 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.addmac.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <8 x i8> %b.coerce.fca.1.extract.i, <64 x i32> %0, <64 x i32> %1, i32 %or19.i.i)
  %3 = bitcast <64 x i32> %2 to <64 x float>
  ret <64 x float> %3
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z20test_addmsc_8x8_8x8T12v64bfp16ebs8iS_iDv64_u10__accfloatS0_(%struct.v64bfp16ebs8 %a.coerce, i32 noundef %sgn_x, %struct.v64bfp16ebs8 %b.coerce, i32 noundef %sgn_y, <64 x float> inreg noundef %acc1, <64 x float> inreg noundef %acc2) local_unnamed_addr  {
; CHECK-LABEL: _Z20test_addmsc_8x8_8x8T12v64bfp16ebs8iS_iDv64_u10__accfloatS0_:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r2, #9; nopx
; CHECK-NEXT:    mova r3, #8; lshl r0, r0, r2
; CHECK-NEXT:    lshl r1, r1, r3
; CHECK-NEXT:    mova r2, #12; or r0, r0, r1; vmov.d dm0, dm1
; CHECK-NEXT:    or r0, r0, r2
; CHECK-NEXT:    vaddmsc.f dm0, dm0, dm2, ex0, ex1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 1
  %shl14.i.i = shl i32 %sgn_x, 9
  %shl15.i.i = shl i32 %sgn_y, 8
  %or5.i.i = or i32 %shl14.i.i, %shl15.i.i
  %or19.i.i = or disjoint i32 %or5.i.i, 12
  %0 = bitcast <64 x float> %acc1 to <64 x i32>
  %1 = bitcast <64 x float> %acc2 to <64 x i32>
  %2 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.addmsc.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <8 x i8> %b.coerce.fca.1.extract.i, <64 x i32> %0, <64 x i32> %1, i32 %or19.i.i)
  %3 = bitcast <64 x i32> %2 to <64 x float>
  ret <64 x float> %3
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z22test_mul_8x8_8x8T_conf12v64bfp16ebs8S_i(%struct.v64bfp16ebs8 %a.coerce, %struct.v64bfp16ebs8 %b.coerce, i32 noundef %sub_mul) local_unnamed_addr  {
; CHECK-LABEL: _Z22test_mul_8x8_8x8T_conf12v64bfp16ebs8S_i:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r1, #11
; CHECK-NEXT:    mova r2, #780; lshl r0, r0, r1
; CHECK-NEXT:    or r0, r0, r2
; CHECK-NEXT:    vmul.f dm0, ex0, ex1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 1
  %shl2.i.i = shl i32 %sub_mul, 11
  %or19.i.i = or disjoint i32 %shl2.i.i, 780
  %0 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mul.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <8 x i8> %b.coerce.fca.1.extract.i, i32 %or19.i.i)
  %1 = bitcast <64 x i32> %0 to <64 x float>
  ret <64 x float> %1
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z25test_negmul_8x8_8x8T_conf12v64bfp16ebs8S_i(%struct.v64bfp16ebs8 %a.coerce, %struct.v64bfp16ebs8 %b.coerce, i32 noundef %sub_mul) local_unnamed_addr  {
; CHECK-LABEL: _Z25test_negmul_8x8_8x8T_conf12v64bfp16ebs8S_i:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r1, #11
; CHECK-NEXT:    mova r2, #780; lshl r0, r0, r1
; CHECK-NEXT:    or r0, r0, r2
; CHECK-NEXT:    vnegmul.f dm0, ex0, ex1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 1
  %shl2.i.i = shl i32 %sub_mul, 11
  %or19.i.i = or disjoint i32 %shl2.i.i, 780
  %0 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.negmul.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <8 x i8> %b.coerce.fca.1.extract.i, i32 %or19.i.i)
  %1 = bitcast <64 x i32> %0 to <64 x float>
  ret <64 x float> %1
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z22test_mac_8x8_8x8T_conf12v64bfp16ebs8S_Dv64_u10__accfloatiii(%struct.v64bfp16ebs8 %a.coerce, %struct.v64bfp16ebs8 %b.coerce, <64 x float> inreg noundef %acc, i32 noundef %zero_acc, i32 noundef %sub_mul, i32 noundef %sub_acc1) local_unnamed_addr  {
; CHECK-LABEL: _Z22test_mac_8x8_8x8T_conf12v64bfp16ebs8S_Dv64_u10__accfloatiii:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r3, #11; nopx
; CHECK-NEXT:    mova r4, #12; lshl r1, r1, r3
; CHECK-NEXT:    lshl r2, r2, r4
; CHECK-NEXT:    or r0, r1, r0
; CHECK-NEXT:    mova r1, #780; or r0, r0, r2
; CHECK-NEXT:    or r0, r0, r1
; CHECK-NEXT:    vmac.f dm0, dm1, ex0, ex1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 1
  %shl2.i.i = shl i32 %sub_mul, 11
  %shl4.i.i = shl i32 %sub_acc1, 12
  %or11.i.i = or i32 %shl2.i.i, %zero_acc
  %or16.i.i = or i32 %or11.i.i, %shl4.i.i
  %or19.i.i = or i32 %or16.i.i, 780
  %0 = bitcast <64 x float> %acc to <64 x i32>
  %1 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mac.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <8 x i8> %b.coerce.fca.1.extract.i, <64 x i32> %0, i32 %or19.i.i)
  %2 = bitcast <64 x i32> %1 to <64 x float>
  ret <64 x float> %2
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z22test_msc_8x8_8x8T_conf12v64bfp16ebs8S_Dv64_u10__accfloatiii(%struct.v64bfp16ebs8 %a.coerce, %struct.v64bfp16ebs8 %b.coerce, <64 x float> inreg noundef %acc, i32 noundef %zero_acc, i32 noundef %sub_mul, i32 noundef %sub_acc1) local_unnamed_addr  {
; CHECK-LABEL: _Z22test_msc_8x8_8x8T_conf12v64bfp16ebs8S_Dv64_u10__accfloatiii:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r3, #11; nopx
; CHECK-NEXT:    mova r4, #12; lshl r1, r1, r3
; CHECK-NEXT:    lshl r2, r2, r4
; CHECK-NEXT:    or r0, r1, r0
; CHECK-NEXT:    mova r1, #780; or r0, r0, r2
; CHECK-NEXT:    or r0, r0, r1
; CHECK-NEXT:    vmsc.f dm0, dm1, ex0, ex1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 1
  %shl2.i.i = shl i32 %sub_mul, 11
  %shl4.i.i = shl i32 %sub_acc1, 12
  %or11.i.i = or i32 %shl2.i.i, %zero_acc
  %or16.i.i = or i32 %or11.i.i, %shl4.i.i
  %or19.i.i = or i32 %or16.i.i, 780
  %0 = bitcast <64 x float> %acc to <64 x i32>
  %1 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.msc.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <8 x i8> %b.coerce.fca.1.extract.i, <64 x i32> %0, i32 %or19.i.i)
  %2 = bitcast <64 x i32> %1 to <64 x float>
  ret <64 x float> %2
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z25test_addmac_8x8_8x8T_conf12v64bfp16ebs8S_Dv64_u10__accfloatS0_iiii(%struct.v64bfp16ebs8 %a.coerce, %struct.v64bfp16ebs8 %b.coerce, <64 x float> inreg noundef %acc1, <64 x float> inreg noundef %acc2, i32 noundef %zero_acc1, i32 noundef %sub_mul, i32 noundef %sub_acc1, i32 noundef %sub_acc2) local_unnamed_addr  {
; CHECK-LABEL: _Z25test_addmac_8x8_8x8T_conf12v64bfp16ebs8S_Dv64_u10__accfloatS0_iiii:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r4, #11; nopb ; nopx
; CHECK-NEXT:    mova r5, #12; lshl r1, r1, r4
; CHECK-NEXT:    lshl r2, r2, r5
; CHECK-NEXT:    mova r4, #13; or r0, r1, r0
; CHECK-NEXT:    lshl r3, r3, r4
; CHECK-NEXT:    or r0, r0, r2
; CHECK-NEXT:    mova r1, #780; or r0, r0, r3; vmov.d dm0, dm1
; CHECK-NEXT:    or r0, r0, r1
; CHECK-NEXT:    vaddmac.f dm0, dm0, dm2, ex0, ex1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 1
  %shl2.i.i = shl i32 %sub_mul, 11
  %shl4.i.i = shl i32 %sub_acc1, 12
  %shl6.i.i = shl i32 %sub_acc2, 13
  %or11.i.i = or i32 %shl2.i.i, %zero_acc1
  %or16.i.i = or i32 %or11.i.i, %shl4.i.i
  %or13.i.i = or i32 %or16.i.i, %shl6.i.i
  %or19.i.i = or i32 %or13.i.i, 780
  %0 = bitcast <64 x float> %acc1 to <64 x i32>
  %1 = bitcast <64 x float> %acc2 to <64 x i32>
  %2 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.addmac.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <8 x i8> %b.coerce.fca.1.extract.i, <64 x i32> %0, <64 x i32> %1, i32 %or19.i.i)
  %3 = bitcast <64 x i32> %2 to <64 x float>
  ret <64 x float> %3
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z25test_addmsc_8x8_8x8T_conf12v64bfp16ebs8S_Dv64_u10__accfloatS0_iiii(%struct.v64bfp16ebs8 %a.coerce, %struct.v64bfp16ebs8 %b.coerce, <64 x float> inreg noundef %acc1, <64 x float> inreg noundef %acc2, i32 noundef %zero_acc1, i32 noundef %sub_mul, i32 noundef %sub_acc1, i32 noundef %sub_acc2) local_unnamed_addr  {
; CHECK-LABEL: _Z25test_addmsc_8x8_8x8T_conf12v64bfp16ebs8S_Dv64_u10__accfloatS0_iiii:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r4, #11; nopb ; nopx
; CHECK-NEXT:    mova r5, #12; lshl r1, r1, r4
; CHECK-NEXT:    lshl r2, r2, r5
; CHECK-NEXT:    mova r4, #13; or r0, r1, r0
; CHECK-NEXT:    lshl r3, r3, r4
; CHECK-NEXT:    or r0, r0, r2
; CHECK-NEXT:    mova r1, #780; or r0, r0, r3; vmov.d dm0, dm1
; CHECK-NEXT:    or r0, r0, r1
; CHECK-NEXT:    vaddmsc.f dm0, dm0, dm2, ex0, ex1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 1
  %shl2.i.i = shl i32 %sub_mul, 11
  %shl4.i.i = shl i32 %sub_acc1, 12
  %shl6.i.i = shl i32 %sub_acc2, 13
  %or11.i.i = or i32 %shl2.i.i, %zero_acc1
  %or16.i.i = or i32 %or11.i.i, %shl4.i.i
  %or13.i.i = or i32 %or16.i.i, %shl6.i.i
  %or19.i.i = or i32 %or13.i.i, 780
  %0 = bitcast <64 x float> %acc1 to <64 x i32>
  %1 = bitcast <64 x float> %acc2 to <64 x i32>
  %2 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.addmsc.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <8 x i8> %b.coerce.fca.1.extract.i, <64 x i32> %0, <64 x i32> %1, i32 %or19.i.i)
  %3 = bitcast <64 x i32> %2 to <64 x float>
  ret <64 x float> %3
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z22test_mul_8x8_8x8T_conf12v64bfp16ebs8iS_ii(%struct.v64bfp16ebs8 %a.coerce, i32 noundef %sgn_x, %struct.v64bfp16ebs8 %b.coerce, i32 noundef %sgn_y, i32 noundef %sub_mul) local_unnamed_addr  {
; CHECK-LABEL: _Z22test_mul_8x8_8x8T_conf12v64bfp16ebs8iS_ii:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r3, #11; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    mova r4, #9; lshl r2, r2, r3
; CHECK-NEXT:    mova r3, #8; lshl r0, r0, r4
; CHECK-NEXT:    lshl r1, r1, r3
; CHECK-NEXT:    or r0, r0, r1
; CHECK-NEXT:    mova r1, #12; or r0, r0, r2
; CHECK-NEXT:    or r0, r0, r1
; CHECK-NEXT:    vmul.f dm0, ex0, ex1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 1
  %shl2.i.i = shl i32 %sub_mul, 11
  %shl14.i.i = shl i32 %sgn_x, 9
  %shl15.i.i = shl i32 %sgn_y, 8
  %or5.i.i = or i32 %shl14.i.i, %shl15.i.i
  %or16.i.i = or i32 %or5.i.i, %shl2.i.i
  %or19.i.i = or disjoint i32 %or16.i.i, 12
  %0 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mul.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <8 x i8> %b.coerce.fca.1.extract.i, i32 %or19.i.i)
  %1 = bitcast <64 x i32> %0 to <64 x float>
  ret <64 x float> %1
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z25test_negmul_8x8_8x8T_conf12v64bfp16ebs8iS_ii(%struct.v64bfp16ebs8 %a.coerce, i32 noundef %sgn_x, %struct.v64bfp16ebs8 %b.coerce, i32 noundef %sgn_y, i32 noundef %sub_mul) local_unnamed_addr  {
; CHECK-LABEL: _Z25test_negmul_8x8_8x8T_conf12v64bfp16ebs8iS_ii:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r3, #11; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    mova r4, #9; lshl r2, r2, r3
; CHECK-NEXT:    mova r3, #8; lshl r0, r0, r4
; CHECK-NEXT:    lshl r1, r1, r3
; CHECK-NEXT:    or r0, r0, r1
; CHECK-NEXT:    mova r1, #12; or r0, r0, r2
; CHECK-NEXT:    or r0, r0, r1
; CHECK-NEXT:    vnegmul.f dm0, ex0, ex1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 1
  %shl2.i.i = shl i32 %sub_mul, 11
  %shl14.i.i = shl i32 %sgn_x, 9
  %shl15.i.i = shl i32 %sgn_y, 8
  %or5.i.i = or i32 %shl14.i.i, %shl15.i.i
  %or16.i.i = or i32 %or5.i.i, %shl2.i.i
  %or19.i.i = or disjoint i32 %or16.i.i, 12
  %0 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.negmul.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <8 x i8> %b.coerce.fca.1.extract.i, i32 %or19.i.i)
  %1 = bitcast <64 x i32> %0 to <64 x float>
  ret <64 x float> %1
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z22test_mac_8x8_8x8T_conf12v64bfp16ebs8iS_iDv64_u10__accfloatiii(%struct.v64bfp16ebs8 %a.coerce, i32 noundef %sgn_x, %struct.v64bfp16ebs8 %b.coerce, i32 noundef %sgn_y, <64 x float> inreg noundef %acc, i32 noundef %zero_acc, i32 noundef %sub_mul, i32 noundef %sub_acc1) local_unnamed_addr  {
; CHECK-LABEL: _Z22test_mac_8x8_8x8T_conf12v64bfp16ebs8iS_iDv64_u10__accfloatiii:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r5, #11
; CHECK-NEXT:    mova r6, #12; lshl r3, r3, r5
; CHECK-NEXT:    mova r7, #8; lshl r4, r4, r6
; CHECK-NEXT:    mova r5, #9; lshl r1, r1, r7
; CHECK-NEXT:    lshl r0, r0, r5
; CHECK-NEXT:    or r0, r0, r1
; CHECK-NEXT:    or r0, r0, r2
; CHECK-NEXT:    or r0, r0, r3
; CHECK-NEXT:    or r0, r0, r4
; CHECK-NEXT:    or r0, r0, r6
; CHECK-NEXT:    vmac.f dm0, dm1, ex0, ex1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 1
  %shl2.i.i = shl i32 %sub_mul, 11
  %shl4.i.i = shl i32 %sub_acc1, 12
  %shl14.i.i = shl i32 %sgn_x, 9
  %shl15.i.i = shl i32 %sgn_y, 8
  %or5.i.i = or i32 %shl14.i.i, %shl15.i.i
  %or11.i.i = or i32 %or5.i.i, %zero_acc
  %or16.i.i = or i32 %or11.i.i, %shl2.i.i
  %or13.i.i = or i32 %or16.i.i, %shl4.i.i
  %or19.i.i = or i32 %or13.i.i, 12
  %0 = bitcast <64 x float> %acc to <64 x i32>
  %1 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mac.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <8 x i8> %b.coerce.fca.1.extract.i, <64 x i32> %0, i32 %or19.i.i)
  %2 = bitcast <64 x i32> %1 to <64 x float>
  ret <64 x float> %2
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z22test_msc_8x8_8x8T_conf12v64bfp16ebs8iS_iDv64_u10__accfloatiii(%struct.v64bfp16ebs8 %a.coerce, i32 noundef %sgn_x, %struct.v64bfp16ebs8 %b.coerce, i32 noundef %sgn_y, <64 x float> inreg noundef %acc, i32 noundef %zero_acc, i32 noundef %sub_mul, i32 noundef %sub_acc1) local_unnamed_addr  {
; CHECK-LABEL: _Z22test_msc_8x8_8x8T_conf12v64bfp16ebs8iS_iDv64_u10__accfloatiii:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r5, #11
; CHECK-NEXT:    mova r6, #12; lshl r3, r3, r5
; CHECK-NEXT:    mova r7, #8; lshl r4, r4, r6
; CHECK-NEXT:    mova r5, #9; lshl r1, r1, r7
; CHECK-NEXT:    lshl r0, r0, r5
; CHECK-NEXT:    or r0, r0, r1
; CHECK-NEXT:    or r0, r0, r2
; CHECK-NEXT:    or r0, r0, r3
; CHECK-NEXT:    or r0, r0, r4
; CHECK-NEXT:    or r0, r0, r6
; CHECK-NEXT:    vmsc.f dm0, dm1, ex0, ex1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 1
  %shl2.i.i = shl i32 %sub_mul, 11
  %shl4.i.i = shl i32 %sub_acc1, 12
  %shl14.i.i = shl i32 %sgn_x, 9
  %shl15.i.i = shl i32 %sgn_y, 8
  %or5.i.i = or i32 %shl14.i.i, %shl15.i.i
  %or11.i.i = or i32 %or5.i.i, %zero_acc
  %or16.i.i = or i32 %or11.i.i, %shl2.i.i
  %or13.i.i = or i32 %or16.i.i, %shl4.i.i
  %or19.i.i = or i32 %or13.i.i, 12
  %0 = bitcast <64 x float> %acc to <64 x i32>
  %1 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.msc.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <8 x i8> %b.coerce.fca.1.extract.i, <64 x i32> %0, i32 %or19.i.i)
  %2 = bitcast <64 x i32> %1 to <64 x float>
  ret <64 x float> %2
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z25test_addmac_8x8_8x8T_conf12v64bfp16ebs8iS_iDv64_u10__accfloatS0_iiii(%struct.v64bfp16ebs8 %a.coerce, i32 noundef %sgn_x, %struct.v64bfp16ebs8 %b.coerce, i32 noundef %sgn_y, <64 x float> inreg noundef %acc1, <64 x float> inreg noundef %acc2, i32 noundef %zero_acc1, i32 noundef %sub_mul, i32 noundef %sub_acc1, i32 noundef %sub_acc2) local_unnamed_addr  {
; CHECK-LABEL: _Z25test_addmac_8x8_8x8T_conf12v64bfp16ebs8iS_iDv64_u10__accfloatS0_iiii:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r6, #11; nopx
; CHECK-NEXT:    mova r7, #12; lshl r3, r3, r6
; CHECK-NEXT:    mova r16, #9; lshl r4, r4, r7
; CHECK-NEXT:    mova r6, #13; lshl r0, r0, r16
; CHECK-NEXT:    mova r6, #8; lshl r5, r5, r6
; CHECK-NEXT:    lshl r1, r1, r6
; CHECK-NEXT:    or r0, r0, r1
; CHECK-NEXT:    or r0, r0, r2
; CHECK-NEXT:    or r0, r0, r3
; CHECK-NEXT:    or r0, r0, r4
; CHECK-NEXT:    or r0, r0, r5; vmov.d dm0, dm1
; CHECK-NEXT:    or r0, r0, r7
; CHECK-NEXT:    vaddmac.f dm0, dm0, dm2, ex0, ex1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 1
  %shl2.i.i = shl i32 %sub_mul, 11
  %shl4.i.i = shl i32 %sub_acc1, 12
  %shl6.i.i = shl i32 %sub_acc2, 13
  %shl14.i.i = shl i32 %sgn_x, 9
  %shl15.i.i = shl i32 %sgn_y, 8
  %or5.i.i = or i32 %shl14.i.i, %shl15.i.i
  %or11.i.i = or i32 %or5.i.i, %zero_acc1
  %or16.i.i = or i32 %or11.i.i, %shl2.i.i
  %or13.i.i = or i32 %or16.i.i, %shl4.i.i
  %or17.i.i = or i32 %or13.i.i, %shl6.i.i
  %or19.i.i = or i32 %or17.i.i, 12
  %0 = bitcast <64 x float> %acc1 to <64 x i32>
  %1 = bitcast <64 x float> %acc2 to <64 x i32>
  %2 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.addmac.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <8 x i8> %b.coerce.fca.1.extract.i, <64 x i32> %0, <64 x i32> %1, i32 %or19.i.i)
  %3 = bitcast <64 x i32> %2 to <64 x float>
  ret <64 x float> %3
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z25test_addmsc_8x8_8x8T_conf12v64bfp16ebs8iS_iDv64_u10__accfloatS0_iiii(%struct.v64bfp16ebs8 %a.coerce, i32 noundef %sgn_x, %struct.v64bfp16ebs8 %b.coerce, i32 noundef %sgn_y, <64 x float> inreg noundef %acc1, <64 x float> inreg noundef %acc2, i32 noundef %zero_acc1, i32 noundef %sub_mul, i32 noundef %sub_acc1, i32 noundef %sub_acc2) local_unnamed_addr  {
; CHECK-LABEL: _Z25test_addmsc_8x8_8x8T_conf12v64bfp16ebs8iS_iDv64_u10__accfloatS0_iiii:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r6, #11; nopx
; CHECK-NEXT:    mova r7, #12; lshl r3, r3, r6
; CHECK-NEXT:    mova r16, #9; lshl r4, r4, r7
; CHECK-NEXT:    mova r6, #13; lshl r0, r0, r16
; CHECK-NEXT:    mova r6, #8; lshl r5, r5, r6
; CHECK-NEXT:    lshl r1, r1, r6
; CHECK-NEXT:    or r0, r0, r1
; CHECK-NEXT:    or r0, r0, r2
; CHECK-NEXT:    or r0, r0, r3
; CHECK-NEXT:    or r0, r0, r4
; CHECK-NEXT:    or r0, r0, r5; vmov.d dm0, dm1
; CHECK-NEXT:    or r0, r0, r7
; CHECK-NEXT:    vaddmsc.f dm0, dm0, dm2, ex0, ex1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 1
  %shl2.i.i = shl i32 %sub_mul, 11
  %shl4.i.i = shl i32 %sub_acc1, 12
  %shl6.i.i = shl i32 %sub_acc2, 13
  %shl14.i.i = shl i32 %sgn_x, 9
  %shl15.i.i = shl i32 %sgn_y, 8
  %or5.i.i = or i32 %shl14.i.i, %shl15.i.i
  %or11.i.i = or i32 %or5.i.i, %zero_acc1
  %or16.i.i = or i32 %or11.i.i, %shl2.i.i
  %or13.i.i = or i32 %or16.i.i, %shl4.i.i
  %or17.i.i = or i32 %or13.i.i, %shl6.i.i
  %or19.i.i = or i32 %or17.i.i, 12
  %0 = bitcast <64 x float> %acc1 to <64 x i32>
  %1 = bitcast <64 x float> %acc2 to <64 x i32>
  %2 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.addmsc.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <8 x i8> %b.coerce.fca.1.extract.i, <64 x i32> %0, <64 x i32> %1, i32 %or19.i.i)
  %3 = bitcast <64 x i32> %2 to <64 x float>
  ret <64 x float> %3
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z18test_mul_4x8_8x16T12v64bfp16ebs813v128bfp16ebs8(%struct.v64bfp16ebs8 %a.coerce, %struct.v128bfp16ebs8 %b.coerce) local_unnamed_addr  {
; CHECK-LABEL: _Z18test_mul_4x8_8x16T12v64bfp16ebs813v128bfp16ebs8:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r0, #972; nopb ; nopxm ; nops
; CHECK-NEXT:    vmul.f dm0, ex0, ey1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 1
  %b.coerce.fca.2.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 2
  %b.coerce.fca.3.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 3
  %0 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.mul.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <64 x i8> %b.coerce.fca.1.extract.i, <8 x i8> %b.coerce.fca.2.extract.i, <8 x i8> %b.coerce.fca.3.extract.i, i32 972)
  %1 = bitcast <64 x i32> %0 to <64 x float>
  ret <64 x float> %1
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z21test_negmul_4x8_8x16T12v64bfp16ebs813v128bfp16ebs8(%struct.v64bfp16ebs8 %a.coerce, %struct.v128bfp16ebs8 %b.coerce) local_unnamed_addr  {
; CHECK-LABEL: _Z21test_negmul_4x8_8x16T12v64bfp16ebs813v128bfp16ebs8:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r0, #972; nopb ; nopxm ; nops
; CHECK-NEXT:    vnegmul.f dm0, ex0, ey1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 1
  %b.coerce.fca.2.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 2
  %b.coerce.fca.3.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 3
  %0 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.negmul.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <64 x i8> %b.coerce.fca.1.extract.i, <8 x i8> %b.coerce.fca.2.extract.i, <8 x i8> %b.coerce.fca.3.extract.i, i32 972)
  %1 = bitcast <64 x i32> %0 to <64 x float>
  ret <64 x float> %1
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z18test_mac_4x8_8x16T12v64bfp16ebs813v128bfp16ebs8Dv64_u10__accfloat(%struct.v64bfp16ebs8 %a.coerce, %struct.v128bfp16ebs8 %b.coerce, <64 x float> inreg noundef %acc) local_unnamed_addr  {
; CHECK-LABEL: _Z18test_mac_4x8_8x16T12v64bfp16ebs813v128bfp16ebs8Dv64_u10__accfloat:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r0, #972; nopb ; nopxm ; nops
; CHECK-NEXT:    vmac.f dm0, dm1, ex0, ey1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 1
  %b.coerce.fca.2.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 2
  %b.coerce.fca.3.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 3
  %0 = bitcast <64 x float> %acc to <64 x i32>
  %1 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.mac.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <64 x i8> %b.coerce.fca.1.extract.i, <8 x i8> %b.coerce.fca.2.extract.i, <8 x i8> %b.coerce.fca.3.extract.i, <64 x i32> %0, i32 972)
  %2 = bitcast <64 x i32> %1 to <64 x float>
  ret <64 x float> %2
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z18test_msc_4x8_8x16T12v64bfp16ebs813v128bfp16ebs8Dv64_u10__accfloat(%struct.v64bfp16ebs8 %a.coerce, %struct.v128bfp16ebs8 %b.coerce, <64 x float> inreg noundef %acc) local_unnamed_addr  {
; CHECK-LABEL: _Z18test_msc_4x8_8x16T12v64bfp16ebs813v128bfp16ebs8Dv64_u10__accfloat:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r0, #972; nopb ; nopxm ; nops
; CHECK-NEXT:    vmsc.f dm0, dm1, ex0, ey1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 1
  %b.coerce.fca.2.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 2
  %b.coerce.fca.3.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 3
  %0 = bitcast <64 x float> %acc to <64 x i32>
  %1 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.msc.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <64 x i8> %b.coerce.fca.1.extract.i, <8 x i8> %b.coerce.fca.2.extract.i, <8 x i8> %b.coerce.fca.3.extract.i, <64 x i32> %0, i32 972)
  %2 = bitcast <64 x i32> %1 to <64 x float>
  ret <64 x float> %2
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z21test_addmac_4x8_8x16T12v64bfp16ebs813v128bfp16ebs8Dv64_u10__accfloatS1_(%struct.v64bfp16ebs8 %a.coerce, %struct.v128bfp16ebs8 %b.coerce, <64 x float> inreg noundef %acc1, <64 x float> inreg noundef %acc2) local_unnamed_addr  {
; CHECK-LABEL: _Z21test_addmac_4x8_8x16T12v64bfp16ebs813v128bfp16ebs8Dv64_u10__accfloatS1_:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopx ; vmov.d dm0, dm1
; CHECK-NEXT:    mova r0, #972
; CHECK-NEXT:    vaddmac.f dm0, dm0, dm2, ex0, ey1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 1
  %b.coerce.fca.2.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 2
  %b.coerce.fca.3.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 3
  %0 = bitcast <64 x float> %acc1 to <64 x i32>
  %1 = bitcast <64 x float> %acc2 to <64 x i32>
  %2 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.addmac.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <64 x i8> %b.coerce.fca.1.extract.i, <8 x i8> %b.coerce.fca.2.extract.i, <8 x i8> %b.coerce.fca.3.extract.i, <64 x i32> %0, <64 x i32> %1, i32 972)
  %3 = bitcast <64 x i32> %2 to <64 x float>
  ret <64 x float> %3
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z21test_addmsc_4x8_8x16T12v64bfp16ebs813v128bfp16ebs8Dv64_u10__accfloatS1_(%struct.v64bfp16ebs8 %a.coerce, %struct.v128bfp16ebs8 %b.coerce, <64 x float> inreg noundef %acc1, <64 x float> inreg noundef %acc2) local_unnamed_addr  {
; CHECK-LABEL: _Z21test_addmsc_4x8_8x16T12v64bfp16ebs813v128bfp16ebs8Dv64_u10__accfloatS1_:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopx ; vmov.d dm0, dm1
; CHECK-NEXT:    mova r0, #972
; CHECK-NEXT:    vaddmsc.f dm0, dm0, dm2, ex0, ey1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 1
  %b.coerce.fca.2.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 2
  %b.coerce.fca.3.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 3
  %0 = bitcast <64 x float> %acc1 to <64 x i32>
  %1 = bitcast <64 x float> %acc2 to <64 x i32>
  %2 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.addmsc.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <64 x i8> %b.coerce.fca.1.extract.i, <8 x i8> %b.coerce.fca.2.extract.i, <8 x i8> %b.coerce.fca.3.extract.i, <64 x i32> %0, <64 x i32> %1, i32 972)
  %3 = bitcast <64 x i32> %2 to <64 x float>
  ret <64 x float> %3
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z18test_mul_4x8_8x16T12v64bfp16ebs8i13v128bfp16ebs8i(%struct.v64bfp16ebs8 %a.coerce, i32 noundef %sgn_x, %struct.v128bfp16ebs8 %b.coerce, i32 noundef %sgn_y) local_unnamed_addr  {
; CHECK-LABEL: _Z18test_mul_4x8_8x16T12v64bfp16ebs8i13v128bfp16ebs8i:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r2, #9; nopxm
; CHECK-NEXT:    mova r3, #8; lshl r0, r0, r2
; CHECK-NEXT:    lshl r1, r1, r3
; CHECK-NEXT:    mova r2, #204; or r0, r0, r1
; CHECK-NEXT:    or r0, r0, r2
; CHECK-NEXT:    vmul.f dm0, ex0, ey1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 1
  %b.coerce.fca.2.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 2
  %b.coerce.fca.3.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 3
  %shl14.i.i = shl i32 %sgn_x, 9
  %shl15.i.i = shl i32 %sgn_y, 8
  %or5.i.i = or i32 %shl14.i.i, %shl15.i.i
  %or19.i.i = or disjoint i32 %or5.i.i, 204
  %0 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.mul.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <64 x i8> %b.coerce.fca.1.extract.i, <8 x i8> %b.coerce.fca.2.extract.i, <8 x i8> %b.coerce.fca.3.extract.i, i32 %or19.i.i)
  %1 = bitcast <64 x i32> %0 to <64 x float>
  ret <64 x float> %1
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z21test_negmul_4x8_8x16T12v64bfp16ebs8i13v128bfp16ebs8i(%struct.v64bfp16ebs8 %a.coerce, i32 noundef %sgn_x, %struct.v128bfp16ebs8 %b.coerce, i32 noundef %sgn_y) local_unnamed_addr  {
; CHECK-LABEL: _Z21test_negmul_4x8_8x16T12v64bfp16ebs8i13v128bfp16ebs8i:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r2, #9; nopxm
; CHECK-NEXT:    mova r3, #8; lshl r0, r0, r2
; CHECK-NEXT:    lshl r1, r1, r3
; CHECK-NEXT:    mova r2, #204; or r0, r0, r1
; CHECK-NEXT:    or r0, r0, r2
; CHECK-NEXT:    vnegmul.f dm0, ex0, ey1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 1
  %b.coerce.fca.2.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 2
  %b.coerce.fca.3.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 3
  %shl14.i.i = shl i32 %sgn_x, 9
  %shl15.i.i = shl i32 %sgn_y, 8
  %or5.i.i = or i32 %shl14.i.i, %shl15.i.i
  %or19.i.i = or disjoint i32 %or5.i.i, 204
  %0 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.negmul.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <64 x i8> %b.coerce.fca.1.extract.i, <8 x i8> %b.coerce.fca.2.extract.i, <8 x i8> %b.coerce.fca.3.extract.i, i32 %or19.i.i)
  %1 = bitcast <64 x i32> %0 to <64 x float>
  ret <64 x float> %1
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z18test_mac_4x8_8x16T12v64bfp16ebs8i13v128bfp16ebs8iDv64_u10__accfloat(%struct.v64bfp16ebs8 %a.coerce, i32 noundef %sgn_x, %struct.v128bfp16ebs8 %b.coerce, i32 noundef %sgn_y, <64 x float> inreg noundef %acc) local_unnamed_addr  {
; CHECK-LABEL: _Z18test_mac_4x8_8x16T12v64bfp16ebs8i13v128bfp16ebs8iDv64_u10__accfloat:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r2, #9; nopxm
; CHECK-NEXT:    mova r3, #8; lshl r0, r0, r2
; CHECK-NEXT:    lshl r1, r1, r3
; CHECK-NEXT:    mova r2, #204; or r0, r0, r1
; CHECK-NEXT:    or r0, r0, r2
; CHECK-NEXT:    vmac.f dm0, dm1, ex0, ey1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 1
  %b.coerce.fca.2.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 2
  %b.coerce.fca.3.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 3
  %shl14.i.i = shl i32 %sgn_x, 9
  %shl15.i.i = shl i32 %sgn_y, 8
  %or5.i.i = or i32 %shl14.i.i, %shl15.i.i
  %or19.i.i = or disjoint i32 %or5.i.i, 204
  %0 = bitcast <64 x float> %acc to <64 x i32>
  %1 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.mac.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <64 x i8> %b.coerce.fca.1.extract.i, <8 x i8> %b.coerce.fca.2.extract.i, <8 x i8> %b.coerce.fca.3.extract.i, <64 x i32> %0, i32 %or19.i.i)
  %2 = bitcast <64 x i32> %1 to <64 x float>
  ret <64 x float> %2
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z18test_msc_4x8_8x16T12v64bfp16ebs8i13v128bfp16ebs8iDv64_u10__accfloat(%struct.v64bfp16ebs8 %a.coerce, i32 noundef %sgn_x, %struct.v128bfp16ebs8 %b.coerce, i32 noundef %sgn_y, <64 x float> inreg noundef %acc) local_unnamed_addr  {
; CHECK-LABEL: _Z18test_msc_4x8_8x16T12v64bfp16ebs8i13v128bfp16ebs8iDv64_u10__accfloat:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r2, #9; nopxm
; CHECK-NEXT:    mova r3, #8; lshl r0, r0, r2
; CHECK-NEXT:    lshl r1, r1, r3
; CHECK-NEXT:    mova r2, #204; or r0, r0, r1
; CHECK-NEXT:    or r0, r0, r2
; CHECK-NEXT:    vmsc.f dm0, dm1, ex0, ey1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 1
  %b.coerce.fca.2.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 2
  %b.coerce.fca.3.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 3
  %shl14.i.i = shl i32 %sgn_x, 9
  %shl15.i.i = shl i32 %sgn_y, 8
  %or5.i.i = or i32 %shl14.i.i, %shl15.i.i
  %or19.i.i = or disjoint i32 %or5.i.i, 204
  %0 = bitcast <64 x float> %acc to <64 x i32>
  %1 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.msc.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <64 x i8> %b.coerce.fca.1.extract.i, <8 x i8> %b.coerce.fca.2.extract.i, <8 x i8> %b.coerce.fca.3.extract.i, <64 x i32> %0, i32 %or19.i.i)
  %2 = bitcast <64 x i32> %1 to <64 x float>
  ret <64 x float> %2
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z21test_addmac_4x8_8x16T12v64bfp16ebs8i13v128bfp16ebs8iDv64_u10__accfloatS1_(%struct.v64bfp16ebs8 %a.coerce, i32 noundef %sgn_x, %struct.v128bfp16ebs8 %b.coerce, i32 noundef %sgn_y, <64 x float> inreg noundef %acc1, <64 x float> inreg noundef %acc2) local_unnamed_addr  {
; CHECK-LABEL: _Z21test_addmac_4x8_8x16T12v64bfp16ebs8i13v128bfp16ebs8iDv64_u10__accfloatS1_:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r2, #9; nopx
; CHECK-NEXT:    mova r3, #8; lshl r0, r0, r2
; CHECK-NEXT:    lshl r1, r1, r3
; CHECK-NEXT:    mova r2, #204; or r0, r0, r1; vmov.d dm0, dm1
; CHECK-NEXT:    or r0, r0, r2
; CHECK-NEXT:    vaddmac.f dm0, dm0, dm2, ex0, ey1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 1
  %b.coerce.fca.2.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 2
  %b.coerce.fca.3.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 3
  %shl14.i.i = shl i32 %sgn_x, 9
  %shl15.i.i = shl i32 %sgn_y, 8
  %or5.i.i = or i32 %shl14.i.i, %shl15.i.i
  %or19.i.i = or disjoint i32 %or5.i.i, 204
  %0 = bitcast <64 x float> %acc1 to <64 x i32>
  %1 = bitcast <64 x float> %acc2 to <64 x i32>
  %2 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.addmac.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <64 x i8> %b.coerce.fca.1.extract.i, <8 x i8> %b.coerce.fca.2.extract.i, <8 x i8> %b.coerce.fca.3.extract.i, <64 x i32> %0, <64 x i32> %1, i32 %or19.i.i)
  %3 = bitcast <64 x i32> %2 to <64 x float>
  ret <64 x float> %3
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z21test_addmsc_4x8_8x16T12v64bfp16ebs8i13v128bfp16ebs8iDv64_u10__accfloatS1_(%struct.v64bfp16ebs8 %a.coerce, i32 noundef %sgn_x, %struct.v128bfp16ebs8 %b.coerce, i32 noundef %sgn_y, <64 x float> inreg noundef %acc1, <64 x float> inreg noundef %acc2) local_unnamed_addr  {
; CHECK-LABEL: _Z21test_addmsc_4x8_8x16T12v64bfp16ebs8i13v128bfp16ebs8iDv64_u10__accfloatS1_:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r2, #9; nopx
; CHECK-NEXT:    mova r3, #8; lshl r0, r0, r2
; CHECK-NEXT:    lshl r1, r1, r3
; CHECK-NEXT:    mova r2, #204; or r0, r0, r1; vmov.d dm0, dm1
; CHECK-NEXT:    or r0, r0, r2
; CHECK-NEXT:    vaddmsc.f dm0, dm0, dm2, ex0, ey1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 1
  %b.coerce.fca.2.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 2
  %b.coerce.fca.3.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 3
  %shl14.i.i = shl i32 %sgn_x, 9
  %shl15.i.i = shl i32 %sgn_y, 8
  %or5.i.i = or i32 %shl14.i.i, %shl15.i.i
  %or19.i.i = or disjoint i32 %or5.i.i, 204
  %0 = bitcast <64 x float> %acc1 to <64 x i32>
  %1 = bitcast <64 x float> %acc2 to <64 x i32>
  %2 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.addmsc.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <64 x i8> %b.coerce.fca.1.extract.i, <8 x i8> %b.coerce.fca.2.extract.i, <8 x i8> %b.coerce.fca.3.extract.i, <64 x i32> %0, <64 x i32> %1, i32 %or19.i.i)
  %3 = bitcast <64 x i32> %2 to <64 x float>
  ret <64 x float> %3
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z23test_mul_4x8_8x16T_conf12v64bfp16ebs813v128bfp16ebs8i(%struct.v64bfp16ebs8 %a.coerce, %struct.v128bfp16ebs8 %b.coerce, i32 noundef %sub_mul) local_unnamed_addr  {
; CHECK-LABEL: _Z23test_mul_4x8_8x16T_conf12v64bfp16ebs813v128bfp16ebs8i:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r1, #11
; CHECK-NEXT:    mova r2, #972; lshl r0, r0, r1
; CHECK-NEXT:    or r0, r0, r2
; CHECK-NEXT:    vmul.f dm0, ex0, ey1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 1
  %b.coerce.fca.2.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 2
  %b.coerce.fca.3.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 3
  %shl2.i.i = shl i32 %sub_mul, 11
  %or19.i.i = or disjoint i32 %shl2.i.i, 972
  %0 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.mul.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <64 x i8> %b.coerce.fca.1.extract.i, <8 x i8> %b.coerce.fca.2.extract.i, <8 x i8> %b.coerce.fca.3.extract.i, i32 %or19.i.i)
  %1 = bitcast <64 x i32> %0 to <64 x float>
  ret <64 x float> %1
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z26test_negmul_4x8_8x16T_conf12v64bfp16ebs813v128bfp16ebs8i(%struct.v64bfp16ebs8 %a.coerce, %struct.v128bfp16ebs8 %b.coerce, i32 noundef %sub_mul) local_unnamed_addr  {
; CHECK-LABEL: _Z26test_negmul_4x8_8x16T_conf12v64bfp16ebs813v128bfp16ebs8i:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r1, #11
; CHECK-NEXT:    mova r2, #972; lshl r0, r0, r1
; CHECK-NEXT:    or r0, r0, r2
; CHECK-NEXT:    vnegmul.f dm0, ex0, ey1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 1
  %b.coerce.fca.2.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 2
  %b.coerce.fca.3.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 3
  %shl2.i.i = shl i32 %sub_mul, 11
  %or19.i.i = or disjoint i32 %shl2.i.i, 972
  %0 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.negmul.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <64 x i8> %b.coerce.fca.1.extract.i, <8 x i8> %b.coerce.fca.2.extract.i, <8 x i8> %b.coerce.fca.3.extract.i, i32 %or19.i.i)
  %1 = bitcast <64 x i32> %0 to <64 x float>
  ret <64 x float> %1
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z23test_mac_4x8_8x16T_conf12v64bfp16ebs813v128bfp16ebs8Dv64_u10__accfloatiii(%struct.v64bfp16ebs8 %a.coerce, %struct.v128bfp16ebs8 %b.coerce, <64 x float> inreg noundef %acc, i32 noundef %zero_acc, i32 noundef %sub_mul, i32 noundef %sub_acc1) local_unnamed_addr  {
; CHECK-LABEL: _Z23test_mac_4x8_8x16T_conf12v64bfp16ebs813v128bfp16ebs8Dv64_u10__accfloatiii:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r3, #11; nopx
; CHECK-NEXT:    mova r4, #12; lshl r1, r1, r3
; CHECK-NEXT:    lshl r2, r2, r4
; CHECK-NEXT:    or r0, r1, r0
; CHECK-NEXT:    mova r1, #972; or r0, r0, r2
; CHECK-NEXT:    or r0, r0, r1
; CHECK-NEXT:    vmac.f dm0, dm1, ex0, ey1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 1
  %b.coerce.fca.2.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 2
  %b.coerce.fca.3.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 3
  %shl2.i.i = shl i32 %sub_mul, 11
  %shl4.i.i = shl i32 %sub_acc1, 12
  %or11.i.i = or i32 %shl2.i.i, %zero_acc
  %or16.i.i = or i32 %or11.i.i, %shl4.i.i
  %or19.i.i = or i32 %or16.i.i, 972
  %0 = bitcast <64 x float> %acc to <64 x i32>
  %1 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.mac.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <64 x i8> %b.coerce.fca.1.extract.i, <8 x i8> %b.coerce.fca.2.extract.i, <8 x i8> %b.coerce.fca.3.extract.i, <64 x i32> %0, i32 %or19.i.i)
  %2 = bitcast <64 x i32> %1 to <64 x float>
  ret <64 x float> %2
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z23test_msc_4x8_8x16T_conf12v64bfp16ebs813v128bfp16ebs8Dv64_u10__accfloatiii(%struct.v64bfp16ebs8 %a.coerce, %struct.v128bfp16ebs8 %b.coerce, <64 x float> inreg noundef %acc, i32 noundef %zero_acc, i32 noundef %sub_mul, i32 noundef %sub_acc1) local_unnamed_addr  {
; CHECK-LABEL: _Z23test_msc_4x8_8x16T_conf12v64bfp16ebs813v128bfp16ebs8Dv64_u10__accfloatiii:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r3, #11; nopx
; CHECK-NEXT:    mova r4, #12; lshl r1, r1, r3
; CHECK-NEXT:    lshl r2, r2, r4
; CHECK-NEXT:    or r0, r1, r0
; CHECK-NEXT:    mova r1, #972; or r0, r0, r2
; CHECK-NEXT:    or r0, r0, r1
; CHECK-NEXT:    vmsc.f dm0, dm1, ex0, ey1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 1
  %b.coerce.fca.2.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 2
  %b.coerce.fca.3.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 3
  %shl2.i.i = shl i32 %sub_mul, 11
  %shl4.i.i = shl i32 %sub_acc1, 12
  %or11.i.i = or i32 %shl2.i.i, %zero_acc
  %or16.i.i = or i32 %or11.i.i, %shl4.i.i
  %or19.i.i = or i32 %or16.i.i, 972
  %0 = bitcast <64 x float> %acc to <64 x i32>
  %1 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.msc.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <64 x i8> %b.coerce.fca.1.extract.i, <8 x i8> %b.coerce.fca.2.extract.i, <8 x i8> %b.coerce.fca.3.extract.i, <64 x i32> %0, i32 %or19.i.i)
  %2 = bitcast <64 x i32> %1 to <64 x float>
  ret <64 x float> %2
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z26test_addmac_4x8_8x16T_conf12v64bfp16ebs813v128bfp16ebs8Dv64_u10__accfloatS1_iiii(%struct.v64bfp16ebs8 %a.coerce, %struct.v128bfp16ebs8 %b.coerce, <64 x float> inreg noundef %acc1, <64 x float> inreg noundef %acc2, i32 noundef %zero_acc1, i32 noundef %sub_mul, i32 noundef %sub_acc1, i32 noundef %sub_acc2) local_unnamed_addr  {
; CHECK-LABEL: _Z26test_addmac_4x8_8x16T_conf12v64bfp16ebs813v128bfp16ebs8Dv64_u10__accfloatS1_iiii:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r4, #11; nopb ; nopx
; CHECK-NEXT:    mova r5, #12; lshl r1, r1, r4
; CHECK-NEXT:    lshl r2, r2, r5
; CHECK-NEXT:    mova r4, #13; or r0, r1, r0
; CHECK-NEXT:    lshl r3, r3, r4
; CHECK-NEXT:    or r0, r0, r2
; CHECK-NEXT:    mova r1, #972; or r0, r0, r3; vmov.d dm0, dm1
; CHECK-NEXT:    or r0, r0, r1
; CHECK-NEXT:    vaddmac.f dm0, dm0, dm2, ex0, ey1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 1
  %b.coerce.fca.2.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 2
  %b.coerce.fca.3.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 3
  %shl2.i.i = shl i32 %sub_mul, 11
  %shl4.i.i = shl i32 %sub_acc1, 12
  %shl6.i.i = shl i32 %sub_acc2, 13
  %or11.i.i = or i32 %shl2.i.i, %zero_acc1
  %or16.i.i = or i32 %or11.i.i, %shl4.i.i
  %or13.i.i = or i32 %or16.i.i, %shl6.i.i
  %or19.i.i = or i32 %or13.i.i, 972
  %0 = bitcast <64 x float> %acc1 to <64 x i32>
  %1 = bitcast <64 x float> %acc2 to <64 x i32>
  %2 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.addmac.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <64 x i8> %b.coerce.fca.1.extract.i, <8 x i8> %b.coerce.fca.2.extract.i, <8 x i8> %b.coerce.fca.3.extract.i, <64 x i32> %0, <64 x i32> %1, i32 %or19.i.i)
  %3 = bitcast <64 x i32> %2 to <64 x float>
  ret <64 x float> %3
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z26test_addmsc_4x8_8x16T_conf12v64bfp16ebs813v128bfp16ebs8Dv64_u10__accfloatS1_iiii(%struct.v64bfp16ebs8 %a.coerce, %struct.v128bfp16ebs8 %b.coerce, <64 x float> inreg noundef %acc1, <64 x float> inreg noundef %acc2, i32 noundef %zero_acc1, i32 noundef %sub_mul, i32 noundef %sub_acc1, i32 noundef %sub_acc2) local_unnamed_addr  {
; CHECK-LABEL: _Z26test_addmsc_4x8_8x16T_conf12v64bfp16ebs813v128bfp16ebs8Dv64_u10__accfloatS1_iiii:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r4, #11; nopb ; nopx
; CHECK-NEXT:    mova r5, #12; lshl r1, r1, r4
; CHECK-NEXT:    lshl r2, r2, r5
; CHECK-NEXT:    mova r4, #13; or r0, r1, r0
; CHECK-NEXT:    lshl r3, r3, r4
; CHECK-NEXT:    or r0, r0, r2
; CHECK-NEXT:    mova r1, #972; or r0, r0, r3; vmov.d dm0, dm1
; CHECK-NEXT:    or r0, r0, r1
; CHECK-NEXT:    vaddmsc.f dm0, dm0, dm2, ex0, ey1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 1
  %b.coerce.fca.2.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 2
  %b.coerce.fca.3.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 3
  %shl2.i.i = shl i32 %sub_mul, 11
  %shl4.i.i = shl i32 %sub_acc1, 12
  %shl6.i.i = shl i32 %sub_acc2, 13
  %or11.i.i = or i32 %shl2.i.i, %zero_acc1
  %or16.i.i = or i32 %or11.i.i, %shl4.i.i
  %or13.i.i = or i32 %or16.i.i, %shl6.i.i
  %or19.i.i = or i32 %or13.i.i, 972
  %0 = bitcast <64 x float> %acc1 to <64 x i32>
  %1 = bitcast <64 x float> %acc2 to <64 x i32>
  %2 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.addmsc.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <64 x i8> %b.coerce.fca.1.extract.i, <8 x i8> %b.coerce.fca.2.extract.i, <8 x i8> %b.coerce.fca.3.extract.i, <64 x i32> %0, <64 x i32> %1, i32 %or19.i.i)
  %3 = bitcast <64 x i32> %2 to <64 x float>
  ret <64 x float> %3
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z23test_mul_4x8_8x16T_conf12v64bfp16ebs8i13v128bfp16ebs8ii(%struct.v64bfp16ebs8 %a.coerce, i32 noundef %sgn_x, %struct.v128bfp16ebs8 %b.coerce, i32 noundef %sgn_y, i32 noundef %sub_mul) local_unnamed_addr  {
; CHECK-LABEL: _Z23test_mul_4x8_8x16T_conf12v64bfp16ebs8i13v128bfp16ebs8ii:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r3, #11; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    mova r4, #9; lshl r2, r2, r3
; CHECK-NEXT:    mova r3, #8; lshl r0, r0, r4
; CHECK-NEXT:    lshl r1, r1, r3
; CHECK-NEXT:    or r0, r0, r1
; CHECK-NEXT:    mova r1, #204; or r0, r0, r2
; CHECK-NEXT:    or r0, r0, r1
; CHECK-NEXT:    vmul.f dm0, ex0, ey1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 1
  %b.coerce.fca.2.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 2
  %b.coerce.fca.3.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 3
  %shl2.i.i = shl i32 %sub_mul, 11
  %shl14.i.i = shl i32 %sgn_x, 9
  %shl15.i.i = shl i32 %sgn_y, 8
  %or5.i.i = or i32 %shl14.i.i, %shl15.i.i
  %or7.i.i = or i32 %or5.i.i, %shl2.i.i
  %or19.i.i = or disjoint i32 %or7.i.i, 204
  %0 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.mul.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <64 x i8> %b.coerce.fca.1.extract.i, <8 x i8> %b.coerce.fca.2.extract.i, <8 x i8> %b.coerce.fca.3.extract.i, i32 %or19.i.i)
  %1 = bitcast <64 x i32> %0 to <64 x float>
  ret <64 x float> %1
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z26test_negmul_4x8_8x16T_conf12v64bfp16ebs8i13v128bfp16ebs8ii(%struct.v64bfp16ebs8 %a.coerce, i32 noundef %sgn_x, %struct.v128bfp16ebs8 %b.coerce, i32 noundef %sgn_y, i32 noundef %sub_mul) local_unnamed_addr  {
; CHECK-LABEL: _Z26test_negmul_4x8_8x16T_conf12v64bfp16ebs8i13v128bfp16ebs8ii:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r3, #11; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    mova r4, #9; lshl r2, r2, r3
; CHECK-NEXT:    mova r3, #8; lshl r0, r0, r4
; CHECK-NEXT:    lshl r1, r1, r3
; CHECK-NEXT:    or r0, r0, r1
; CHECK-NEXT:    mova r1, #204; or r0, r0, r2
; CHECK-NEXT:    or r0, r0, r1
; CHECK-NEXT:    vnegmul.f dm0, ex0, ey1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 1
  %b.coerce.fca.2.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 2
  %b.coerce.fca.3.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 3
  %shl2.i.i = shl i32 %sub_mul, 11
  %shl14.i.i = shl i32 %sgn_x, 9
  %shl15.i.i = shl i32 %sgn_y, 8
  %or5.i.i = or i32 %shl14.i.i, %shl15.i.i
  %or7.i.i = or i32 %or5.i.i, %shl2.i.i
  %or19.i.i = or disjoint i32 %or7.i.i, 204
  %0 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.negmul.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <64 x i8> %b.coerce.fca.1.extract.i, <8 x i8> %b.coerce.fca.2.extract.i, <8 x i8> %b.coerce.fca.3.extract.i, i32 %or19.i.i)
  %1 = bitcast <64 x i32> %0 to <64 x float>
  ret <64 x float> %1
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z23test_mac_4x8_8x16T_conf12v64bfp16ebs8i13v128bfp16ebs8iDv64_u10__accfloatiii(%struct.v64bfp16ebs8 %a.coerce, i32 noundef %sgn_x, %struct.v128bfp16ebs8 %b.coerce, i32 noundef %sgn_y, <64 x float> inreg noundef %acc, i32 noundef %zero_acc, i32 noundef %sub_mul, i32 noundef %sub_acc1) local_unnamed_addr  {
; CHECK-LABEL: _Z23test_mac_4x8_8x16T_conf12v64bfp16ebs8i13v128bfp16ebs8iDv64_u10__accfloatiii:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r6, #12; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    mova r5, #11; nopb ; lshl r4, r4, r6
; CHECK-NEXT:    mova r5, #9; lshl r3, r3, r5
; CHECK-NEXT:    mova r6, #8; lshl r0, r0, r5
; CHECK-NEXT:    lshl r1, r1, r6
; CHECK-NEXT:    or r0, r0, r1
; CHECK-NEXT:    or r0, r0, r2
; CHECK-NEXT:    or r0, r0, r3
; CHECK-NEXT:    mova r1, #204; or r0, r0, r4
; CHECK-NEXT:    or r0, r0, r1
; CHECK-NEXT:    vmac.f dm0, dm1, ex0, ey1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 1
  %b.coerce.fca.2.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 2
  %b.coerce.fca.3.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 3
  %shl2.i.i = shl i32 %sub_mul, 11
  %shl4.i.i = shl i32 %sub_acc1, 12
  %shl14.i.i = shl i32 %sgn_x, 9
  %shl15.i.i = shl i32 %sgn_y, 8
  %or5.i.i = or i32 %shl14.i.i, %shl15.i.i
  %or7.i.i = or i32 %or5.i.i, %zero_acc
  %or11.i.i = or i32 %or7.i.i, %shl2.i.i
  %or16.i.i = or i32 %or11.i.i, %shl4.i.i
  %or19.i.i = or i32 %or16.i.i, 204
  %0 = bitcast <64 x float> %acc to <64 x i32>
  %1 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.mac.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <64 x i8> %b.coerce.fca.1.extract.i, <8 x i8> %b.coerce.fca.2.extract.i, <8 x i8> %b.coerce.fca.3.extract.i, <64 x i32> %0, i32 %or19.i.i)
  %2 = bitcast <64 x i32> %1 to <64 x float>
  ret <64 x float> %2
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z23test_msc_4x8_8x16T_conf12v64bfp16ebs8i13v128bfp16ebs8iDv64_u10__accfloatiii(%struct.v64bfp16ebs8 %a.coerce, i32 noundef %sgn_x, %struct.v128bfp16ebs8 %b.coerce, i32 noundef %sgn_y, <64 x float> inreg noundef %acc, i32 noundef %zero_acc, i32 noundef %sub_mul, i32 noundef %sub_acc1) local_unnamed_addr  {
; CHECK-LABEL: _Z23test_msc_4x8_8x16T_conf12v64bfp16ebs8i13v128bfp16ebs8iDv64_u10__accfloatiii:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r6, #12; nopb ; nops ; nopxm ; nopv
; CHECK-NEXT:    mova r5, #11; nopb ; lshl r4, r4, r6
; CHECK-NEXT:    mova r5, #9; lshl r3, r3, r5
; CHECK-NEXT:    mova r6, #8; lshl r0, r0, r5
; CHECK-NEXT:    lshl r1, r1, r6
; CHECK-NEXT:    or r0, r0, r1
; CHECK-NEXT:    or r0, r0, r2
; CHECK-NEXT:    or r0, r0, r3
; CHECK-NEXT:    mova r1, #204; or r0, r0, r4
; CHECK-NEXT:    or r0, r0, r1
; CHECK-NEXT:    vmsc.f dm0, dm1, ex0, ey1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 1
  %b.coerce.fca.2.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 2
  %b.coerce.fca.3.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 3
  %shl2.i.i = shl i32 %sub_mul, 11
  %shl4.i.i = shl i32 %sub_acc1, 12
  %shl14.i.i = shl i32 %sgn_x, 9
  %shl15.i.i = shl i32 %sgn_y, 8
  %or5.i.i = or i32 %shl14.i.i, %shl15.i.i
  %or7.i.i = or i32 %or5.i.i, %zero_acc
  %or11.i.i = or i32 %or7.i.i, %shl2.i.i
  %or16.i.i = or i32 %or11.i.i, %shl4.i.i
  %or19.i.i = or i32 %or16.i.i, 204
  %0 = bitcast <64 x float> %acc to <64 x i32>
  %1 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.msc.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <64 x i8> %b.coerce.fca.1.extract.i, <8 x i8> %b.coerce.fca.2.extract.i, <8 x i8> %b.coerce.fca.3.extract.i, <64 x i32> %0, i32 %or19.i.i)
  %2 = bitcast <64 x i32> %1 to <64 x float>
  ret <64 x float> %2
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z26test_addmac_4x8_8x16T_conf12v64bfp16ebs8i13v128bfp16ebs8iDv64_u10__accfloatS1_iiii(%struct.v64bfp16ebs8 %a.coerce, i32 noundef %sgn_x, %struct.v128bfp16ebs8 %b.coerce, i32 noundef %sgn_y, <64 x float> inreg noundef %acc1, <64 x float> inreg noundef %acc2, i32 noundef %zero_acc1, i32 noundef %sub_mul, i32 noundef %sub_acc1, i32 noundef %sub_acc2) local_unnamed_addr  {
; CHECK-LABEL: _Z26test_addmac_4x8_8x16T_conf12v64bfp16ebs8i13v128bfp16ebs8iDv64_u10__accfloatS1_iiii:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r7, #12
; CHECK-NEXT:    mova r6, #11; lshl r4, r4, r7
; CHECK-NEXT:    mova r6, #13; lshl r3, r3, r6
; CHECK-NEXT:    mova r7, #9; lshl r5, r5, r6
; CHECK-NEXT:    mova r6, #8; lshl r0, r0, r7
; CHECK-NEXT:    lshl r1, r1, r6
; CHECK-NEXT:    or r0, r0, r1
; CHECK-NEXT:    or r0, r0, r2
; CHECK-NEXT:    or r0, r0, r3
; CHECK-NEXT:    or r0, r0, r4
; CHECK-NEXT:    mova r1, #204; or r0, r0, r5; vmov.d dm0, dm1
; CHECK-NEXT:    or r0, r0, r1
; CHECK-NEXT:    vaddmac.f dm0, dm0, dm2, ex0, ey1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 1
  %b.coerce.fca.2.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 2
  %b.coerce.fca.3.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 3
  %shl2.i.i = shl i32 %sub_mul, 11
  %shl4.i.i = shl i32 %sub_acc1, 12
  %shl6.i.i = shl i32 %sub_acc2, 13
  %shl14.i.i = shl i32 %sgn_x, 9
  %shl15.i.i = shl i32 %sgn_y, 8
  %or5.i.i = or i32 %shl14.i.i, %shl15.i.i
  %or7.i.i = or i32 %or5.i.i, %zero_acc1
  %or11.i.i = or i32 %or7.i.i, %shl2.i.i
  %or16.i.i = or i32 %or11.i.i, %shl4.i.i
  %or13.i.i = or i32 %or16.i.i, %shl6.i.i
  %or19.i.i = or i32 %or13.i.i, 204
  %0 = bitcast <64 x float> %acc1 to <64 x i32>
  %1 = bitcast <64 x float> %acc2 to <64 x i32>
  %2 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.addmac.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <64 x i8> %b.coerce.fca.1.extract.i, <8 x i8> %b.coerce.fca.2.extract.i, <8 x i8> %b.coerce.fca.3.extract.i, <64 x i32> %0, <64 x i32> %1, i32 %or19.i.i)
  %3 = bitcast <64 x i32> %2 to <64 x float>
  ret <64 x float> %3
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z26test_addmsc_4x8_8x16T_conf12v64bfp16ebs8i13v128bfp16ebs8iDv64_u10__accfloatS1_iiii(%struct.v64bfp16ebs8 %a.coerce, i32 noundef %sgn_x, %struct.v128bfp16ebs8 %b.coerce, i32 noundef %sgn_y, <64 x float> inreg noundef %acc1, <64 x float> inreg noundef %acc2, i32 noundef %zero_acc1, i32 noundef %sub_mul, i32 noundef %sub_acc1, i32 noundef %sub_acc2) local_unnamed_addr  {
; CHECK-LABEL: _Z26test_addmsc_4x8_8x16T_conf12v64bfp16ebs8i13v128bfp16ebs8iDv64_u10__accfloatS1_iiii:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mova r7, #12
; CHECK-NEXT:    mova r6, #11; lshl r4, r4, r7
; CHECK-NEXT:    mova r6, #13; lshl r3, r3, r6
; CHECK-NEXT:    mova r7, #9; lshl r5, r5, r6
; CHECK-NEXT:    mova r6, #8; lshl r0, r0, r7
; CHECK-NEXT:    lshl r1, r1, r6
; CHECK-NEXT:    or r0, r0, r1
; CHECK-NEXT:    or r0, r0, r2
; CHECK-NEXT:    or r0, r0, r3
; CHECK-NEXT:    or r0, r0, r4
; CHECK-NEXT:    mova r1, #204; or r0, r0, r5; vmov.d dm0, dm1
; CHECK-NEXT:    or r0, r0, r1
; CHECK-NEXT:    vaddmsc.f dm0, dm0, dm2, ex0, ey1, r0
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 1
  %b.coerce.fca.2.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 2
  %b.coerce.fca.3.extract.i = extractvalue %struct.v128bfp16ebs8 %b.coerce, 3
  %shl2.i.i = shl i32 %sub_mul, 11
  %shl4.i.i = shl i32 %sub_acc1, 12
  %shl6.i.i = shl i32 %sub_acc2, 13
  %shl14.i.i = shl i32 %sgn_x, 9
  %shl15.i.i = shl i32 %sgn_y, 8
  %or5.i.i = or i32 %shl14.i.i, %shl15.i.i
  %or7.i.i = or i32 %or5.i.i, %zero_acc1
  %or11.i.i = or i32 %or7.i.i, %shl2.i.i
  %or16.i.i = or i32 %or11.i.i, %shl4.i.i
  %or13.i.i = or i32 %or16.i.i, %shl6.i.i
  %or19.i.i = or i32 %or13.i.i, 204
  %0 = bitcast <64 x float> %acc1 to <64 x i32>
  %1 = bitcast <64 x float> %acc2 to <64 x i32>
  %2 = tail call <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.addmsc.conf(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <64 x i8> %b.coerce.fca.1.extract.i, <8 x i8> %b.coerce.fca.2.extract.i, <8 x i8> %b.coerce.fca.3.extract.i, <64 x i32> %0, <64 x i32> %1, i32 %or19.i.i)
  %3 = bitcast <64 x i32> %2 to <64 x float>
  ret <64 x float> %3
}

; Function Attrs: nofree nosync nounwind memory(none)
declare <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mul.conf(<64 x i8>, <8 x i8>, <64 x i8>, <8 x i8>, i32)

; Function Attrs: nofree nosync nounwind memory(none)
declare <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.negmul.conf(<64 x i8>, <8 x i8>, <64 x i8>, <8 x i8>, i32)

; Function Attrs: nofree nosync nounwind memory(none)
declare <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.mac.conf(<64 x i8>, <8 x i8>, <64 x i8>, <8 x i8>, <64 x i32>, i32)

; Function Attrs: nofree nosync nounwind memory(none)
declare <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.msc.conf(<64 x i8>, <8 x i8>, <64 x i8>, <8 x i8>, <64 x i32>, i32)

; Function Attrs: nofree nosync nounwind memory(none)
declare <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.addmac.conf(<64 x i8>, <8 x i8>, <64 x i8>, <8 x i8>, <64 x i32>, <64 x i32>, i32)

; Function Attrs: nofree nosync nounwind memory(none)
declare <64 x i32> @llvm.aie2p.BFP576.BFP576.ACC2048.addmsc.conf(<64 x i8>, <8 x i8>, <64 x i8>, <8 x i8>, <64 x i32>, <64 x i32>, i32)

; Function Attrs: nofree nosync nounwind memory(none)
declare <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.mul.conf(<64 x i8>, <8 x i8>, <64 x i8>, <64 x i8>, <8 x i8>, <8 x i8>, i32)

; Function Attrs: nofree nosync nounwind memory(none)
declare <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.negmul.conf(<64 x i8>, <8 x i8>, <64 x i8>, <64 x i8>, <8 x i8>, <8 x i8>, i32)

; Function Attrs: nofree nosync nounwind memory(none)
declare <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.mac.conf(<64 x i8>, <8 x i8>, <64 x i8>, <64 x i8>, <8 x i8>, <8 x i8>, <64 x i32>, i32)

; Function Attrs: nofree nosync nounwind memory(none)
declare <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.msc.conf(<64 x i8>, <8 x i8>, <64 x i8>, <64 x i8>, <8 x i8>, <8 x i8>, <64 x i32>, i32)

; Function Attrs: nofree nosync nounwind memory(none)
declare <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.addmac.conf(<64 x i8>, <8 x i8>, <64 x i8>, <64 x i8>, <8 x i8>, <8 x i8>, <64 x i32>, <64 x i32>, i32)

; Function Attrs: nofree nosync nounwind memory(none)
declare <64 x i32> @llvm.aie2p.BFP576.BFP1152.ACC2048.addmsc.conf(<64 x i8>, <8 x i8>, <64 x i8>, <64 x i8>, <8 x i8>, <8 x i8>, <64 x i32>, <64 x i32>, i32)
