; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -O2 -mtriple=aie2p   %s -o - | FileCheck %s

define dso_local inreg noundef <16 x float> @test_broadcast_zero_to_v16accfloatv()  {
; CHECK-LABEL: test_broadcast_zero_to_v16accfloatv:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    mova r0, #0 // Delay Slot 4
; CHECK-NEXT:    vbcst.32 x0, r0 // Delay Slot 3
; CHECK-NEXT:    vmov bmll0, x0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  ret <16 x float> zeroinitializer
}

define dso_local inreg noundef <32 x float> @test_broadcast_zero_to_v32accfloatv()  {
; CHECK-LABEL: test_broadcast_zero_to_v32accfloatv:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; ret lr; nopm ; nops
; CHECK-NEXT:    mova r0, #0 // Delay Slot 5
; CHECK-NEXT:    vbcst.32 x0, r0 // Delay Slot 4
; CHECK-NEXT:    vmov bmll0, x0 // Delay Slot 3
; CHECK-NEXT:    vmov bmlh0, x0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  ret <32 x float> zeroinitializer
}

define dso_local inreg noundef <64 x float> @test_broadcast_zero_to_v64accfloatv()  {
; CHECK-LABEL: test_broadcast_zero_to_v64accfloatv:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; vclr dm0
; CHECK-NEXT:    nopa ; nopb ; nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  ret <64 x float> zeroinitializer
}
