; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2023-2025 Advanced Micro Devices, Inc. or its affiliates

; RUN: llc -O2 -mtriple=aie2p --issue-limit=1 %s -o - | FileCheck --check-prefix=AIE2P %s

define noundef inreg <64 x i32> @test_select_64xi32(i1 noundef zeroext %sel, <64 x i32> inreg noundef %a, <64 x i32> inreg noundef %b) {
; AIE2P-LABEL: test_select_64xi32:
; AIE2P:       // %bb.0: // %entry
; AIE2P-NEXT:    nopa ; add r16, r0, #-1; nopm
; AIE2P-NEXT:    vmov x0, bmlh2
; AIE2P-NEXT:    vmov x2, bmhl2
; AIE2P-NEXT:    vmov x4, bmhh2
; AIE2P-NEXT:    vmov x6, bmll2
; AIE2P-NEXT:    vmov x8, bmlh1
; AIE2P-NEXT:    vmov x10, bmhl1
; AIE2P-NEXT:    vmov x1, bmhh1
; AIE2P-NEXT:    vmov x3, bmll1
; AIE2P-NEXT:    vsel.32 x6, x6, x3, r16
; AIE2P-NEXT:    vsel.32 x0, x0, x8, r16
; AIE2P-NEXT:    vsel.32 x2, x2, x10, r16
; AIE2P-NEXT:    vsel.32 x4, x4, x1, r16
; AIE2P-NEXT:    ret lr
; AIE2P-NEXT:    vmov bmll0, x6 // Delay Slot 5
; AIE2P-NEXT:    vmov bmlh0, x0 // Delay Slot 4
; AIE2P-NEXT:    vmov bmhl0, x2 // Delay Slot 3
; AIE2P-NEXT:    vmov bmhh0, x4 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
entry:
  %cond = select i1 %sel, <64 x i32> %b, <64 x i32> %a
  ret <64 x i32> %cond
}
