; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -O2 -mtriple=aie2p %s -o - | FileCheck %s

define dso_local noundef <16 x i32> @test_bfloat16_to_int(<16 x bfloat> noundef %a, i32 noundef %shft)  {
; CHECK-LABEL: test_bfloat16_to_int:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    mov s0, r0 // Delay Slot 4
; CHECK-NEXT:    vfloor.s32.bf16 x0, wl2, s0 // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call <16 x i32> @llvm.aie2p.v16bf16.to.v16i32(<16 x bfloat> %a, i32 %shft)
  ret <16 x i32> %0
}

%struct.v64bfp16ebs16 = type <{ <64 x i8>, <8 x i8> }>
%struct.v64bfp16ebs8 = type <{ <64 x i8>, <8 x i8> }>

define dso_local %struct.v64bfp16ebs8 @test_v64accfloat_to_v64bfp16ebs8(<64 x float> inreg noundef %a){
; CHECK-LABEL: test_v64accfloat_to_v64bfp16ebs8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    vconv.bfp16ebs8.fp32 ex0, dm0 // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call { <64 x i8>, <8 x i8> } @llvm.aie2p.v64accfloat.to.v64bfp16ebs8(<64 x float> %a)
  %1 = extractvalue { <64 x i8>, <8 x i8> } %0, 0
  %2 = extractvalue { <64 x i8>, <8 x i8> } %0, 1
  %.fca.0.insert.i = insertvalue %struct.v64bfp16ebs8 poison, <64 x i8> %1, 0
  %.fca.1.insert.i = insertvalue %struct.v64bfp16ebs8 %.fca.0.insert.i, <8 x i8> %2, 1
  ret %struct.v64bfp16ebs8 %.fca.1.insert.i
}

define dso_local %struct.v64bfp16ebs16 @test_v64accfloat_to_v64bfp16ebs16(<64 x float> inreg noundef %a){
; CHECK-LABEL: test_v64accfloat_to_v64bfp16ebs16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    vconv.bfp16ebs16.fp32 ex0, dm0 // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call { <64 x i8>, <8 x i8> } @llvm.aie2p.v64accfloat.to.v64bfp16ebs16(<64 x float> %a)
  %1 = extractvalue { <64 x i8>, <8 x i8> } %0, 0
  %2 = extractvalue { <64 x i8>, <8 x i8> } %0, 1
  %.fca.0.insert.i = insertvalue %struct.v64bfp16ebs16 poison, <64 x i8> %1, 0
  %.fca.1.insert.i = insertvalue %struct.v64bfp16ebs16 %.fca.0.insert.i, <8 x i8> %2, 1
  ret %struct.v64bfp16ebs16 %.fca.1.insert.i
}

define dso_local %struct.v64bfp16ebs16 @test_v64bfp16ebs8_to_v64bfp16ebs8(%struct.v64bfp16ebs8 %a.coerce){
; CHECK-LABEL: test_v64bfp16ebs8_to_v64bfp16ebs8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    vconv.bfp16ebs16.ebs8 ex0, ex2 // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %0 = tail call { <64 x i8>, <8 x i8> } @llvm.aie2p.v64bfp16ebs8.to.v64bfp16ebs16(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i)
  %1 = extractvalue { <64 x i8>, <8 x i8> } %0, 0
  %2 = extractvalue { <64 x i8>, <8 x i8> } %0, 1
  %.fca.0.insert.i = insertvalue %struct.v64bfp16ebs16 poison, <64 x i8> %1, 0
  %.fca.1.insert.i = insertvalue %struct.v64bfp16ebs16 %.fca.0.insert.i, <8 x i8> %2, 1
  ret %struct.v64bfp16ebs16 %.fca.1.insert.i
}

declare <16 x i32> @llvm.aie2p.v16bf16.to.v16i32(<16 x bfloat>, i32)

declare { <64 x i8>, <8 x i8> } @llvm.aie2p.v64accfloat.to.v64bfp16ebs8(<64 x float>)
declare { <64 x i8>, <8 x i8> } @llvm.aie2p.v64accfloat.to.v64bfp16ebs16(<64 x float>)
declare { <64 x i8>, <8 x i8> } @llvm.aie2p.v64bfp16ebs8.to.v64bfp16ebs16(<64 x i8>, <8 x i8>)
