; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2024-2025 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie2p -verify-machineinstrs -o - < %s | FileCheck %s

define dso_local inreg noundef <64 x i32> @_Z16test_mul_8x2_2x8Dv16_jDv32_t(<16 x i32> noundef %a0, <32 x i16> noundef %b)  {
; CHECK-LABEL: _Z16test_mul_8x2_2x8Dv16_jDv32_t:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mova r0, #3; nopx
; CHECK-NEXT:    vshuffle x4, x0, x0, r0
; CHECK-NEXT:    mova r0, #2; movx r1, #24
; CHECK-NEXT:    vshuffle x0, x0, x0, r0; vmul dm0, x4, x2,r1
; CHECK-NEXT:    movxm r0, #1048
; CHECK-NEXT:    ret lr; vmac dm0, dm0, x0, x2,r0
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call noundef <16 x i32> @llvm.aie2p.vshuffle(<16 x i32> %a0, <16 x i32> undef, i32 2)
  %1 = tail call noundef <16 x i32> @llvm.aie2p.vshuffle(<16 x i32> %a0, <16 x i32> undef, i32 3)
  %2 = tail call <32 x i64> @llvm.aie2p.I512.I512.ACC2048.mul.conf(<16 x i32> %1, <32 x i16> %b, i32 24)
  %3 = tail call <32 x i64> @llvm.aie2p.I512.I512.ACC2048.mac.conf(<16 x i32> %0, <32 x i16> %b, <32 x i64> %2, i32 1048)
  %4 = bitcast <32 x i64> %3 to <64 x i32>
  ret <64 x i32> %4
}
define dso_local inreg noundef <64 x i32> @_Z19test_negmul_8x2_2x8Dv16_jDv32_t(<16 x i32> noundef %a0, <32 x i16> noundef %b)  {
; CHECK-LABEL: _Z19test_negmul_8x2_2x8Dv16_jDv32_t:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mova r0, #3; nopx
; CHECK-NEXT:    vshuffle x4, x0, x0, r0
; CHECK-NEXT:    mova r0, #2; movx r1, #24
; CHECK-NEXT:    vshuffle x0, x0, x0, r0; vnegmul dm0, x4, x2,r1
; CHECK-NEXT:    movxm r0, #1048
; CHECK-NEXT:    ret lr; vmsc dm0, dm0, x0, x2,r0
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call noundef <16 x i32> @llvm.aie2p.vshuffle(<16 x i32> %a0, <16 x i32> undef, i32 2)
  %1 = tail call noundef <16 x i32> @llvm.aie2p.vshuffle(<16 x i32> %a0, <16 x i32> undef, i32 3)
  %2 = tail call <32 x i64> @llvm.aie2p.I512.I512.ACC2048.negmul.conf(<16 x i32> %1, <32 x i16> %b, i32 24)
  %3 = tail call <32 x i64> @llvm.aie2p.I512.I512.ACC2048.msc.conf(<16 x i32> %0, <32 x i16> %b, <32 x i64> %2, i32 1048)
  %4 = bitcast <32 x i64> %3 to <64 x i32>
  ret <64 x i32> %4
}
define dso_local inreg noundef <64 x i32> @_Z16test_mac_8x2_2x8Dv16_jDv32_tDv64_u7__acc32(<16 x i32> noundef %a0, <32 x i16> noundef %b, <64 x i32> inreg noundef %acc1)  {
; CHECK-LABEL: _Z16test_mac_8x2_2x8Dv16_jDv32_tDv64_u7__acc32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mova r0, #3; nopx
; CHECK-NEXT:    vshuffle x4, x0, x0, r0
; CHECK-NEXT:    mova r0, #2; movx r1, #24
; CHECK-NEXT:    vshuffle x0, x0, x0, r0; vmul dm0, x4, x2,r1
; CHECK-NEXT:    movxm r0, #1048
; CHECK-NEXT:    ret lr; vaddmac dm0, dm0, dm1, x0, x2,r0
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call noundef <16 x i32> @llvm.aie2p.vshuffle(<16 x i32> %a0, <16 x i32> undef, i32 2)
  %1 = tail call noundef <16 x i32> @llvm.aie2p.vshuffle(<16 x i32> %a0, <16 x i32> undef, i32 3)
  %2 = tail call <32 x i64> @llvm.aie2p.I512.I512.ACC2048.mul.conf(<16 x i32> %1, <32 x i16> %b, i32 24)
  %3 = bitcast <64 x i32> %acc1 to <32 x i64>
  %4 = tail call <32 x i64> @llvm.aie2p.I512.I512.ACC2048.addmac.conf(<16 x i32> %0, <32 x i16> %b, <32 x i64> %2, <32 x i64> %3, i32 1048)
  %5 = bitcast <32 x i64> %4 to <64 x i32>
  ret <64 x i32> %5
}
define dso_local inreg noundef <64 x i32> @_Z16test_msc_8x2_2x8Dv16_jDv32_tDv64_u7__acc32(<16 x i32> noundef %a0, <32 x i16> noundef %b, <64 x i32> inreg noundef %acc1)  {
; CHECK-LABEL: _Z16test_msc_8x2_2x8Dv16_jDv32_tDv64_u7__acc32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mova r0, #3; nopx
; CHECK-NEXT:    vshuffle x4, x0, x0, r0
; CHECK-NEXT:    mova r0, #2; movx r1, #24
; CHECK-NEXT:    vshuffle x0, x0, x0, r0; vnegmul dm0, x4, x2,r1
; CHECK-NEXT:    movxm r0, #1048
; CHECK-NEXT:    ret lr; vaddmsc dm0, dm0, dm1, x0, x2,r0
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call noundef <16 x i32> @llvm.aie2p.vshuffle(<16 x i32> %a0, <16 x i32> undef, i32 2)
  %1 = tail call noundef <16 x i32> @llvm.aie2p.vshuffle(<16 x i32> %a0, <16 x i32> undef, i32 3)
  %2 = tail call <32 x i64> @llvm.aie2p.I512.I512.ACC2048.negmul.conf(<16 x i32> %1, <32 x i16> %b, i32 24)
  %3 = bitcast <64 x i32> %acc1 to <32 x i64>
  %4 = tail call <32 x i64> @llvm.aie2p.I512.I512.ACC2048.addmsc.conf(<16 x i32> %0, <32 x i16> %b, <32 x i64> %2, <32 x i64> %3, i32 1048)
  %5 = bitcast <32 x i64> %4 to <64 x i32>
  ret <64 x i32> %5
}
define dso_local inreg noundef <64 x i32> @_Z27test_addmac_4x16_16x16_confDv64_hiDv128_DB8_iDv64_u7__acc32S2_iiiii(<64 x i8> noundef %a, i32 noundef %sgn_x, <128 x i8> noundef %b, i32 noundef %sgn_y, <64 x i32> inreg noundef %acc1, <64 x i32> inreg noundef %acc2, i32 noundef %zero_acc1, i32 noundef %shift16, i32 noundef %sub_mul, i32 noundef %sub_acc1, i32 noundef %sub_acc2)  {
; CHECK-LABEL: _Z27test_addmac_4x16_16x16_confDv64_hiDv128_DB8_iDv64_u7__acc32S2_iiiii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mova r17, #11; nopb ; nops ; nez r16, r1; nopm ; nopv
; CHECK-NEXT:    mova r7, #10; nopb ; lshl r4, r4, r17
; CHECK-NEXT:    mova r7, #12; lshl r3, r3, r7
; CHECK-NEXT:    mova r17, #9; lshl r5, r5, r7
; CHECK-NEXT:    mova r7, #8; lshl r0, r0, r17
; CHECK-NEXT:    vunpack y3, x5, unpacksign0; lshl r1, r1, r7
; CHECK-NEXT:    vunpack y1, x4, unpacksign0; or r0, r1, r0
; CHECK-NEXT:    or r1, r3, r2; mov crunpacksize, #0
; CHECK-NEXT:    or r1, r1, r4; mov unpacksign0, r16
; CHECK-NEXT:    mova r4, #13; or r1, r1, r5; mov r2, #50
; CHECK-NEXT:    lshl r2, r6, r4; vshuffle x0, x0, x0, r2
; CHECK-NEXT:    mova r3, #200; or r1, r1, r0; vmov wl4, wh0
; CHECK-NEXT:    or r1, r1, r3
; CHECK-NEXT:    or r0, r0, r2; vmac dm0, dm1, x4, y3,r1
; CHECK-NEXT:    or r0, r0, r3
; CHECK-NEXT:    ret lr; vaddmac dm0, dm0, dm2, x0, y1,r0
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    mov unpacksign0, #0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <64 x i8> %a to <16 x i32>
  %1 = tail call <16 x i32> @llvm.aie2p.vshuffle(<16 x i32> %0, <16 x i32> undef, i32 50)
  %shuffle.i.i.i = shufflevector <16 x i32> %1, <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %shuffle1.i.i.i = shufflevector <16 x i32> %1, <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %2 = bitcast <128 x i8> %b to <32 x i32>
  %shuffle.i.i19.i = shufflevector <32 x i32> %2, <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %3 = bitcast <16 x i32> %shuffle.i.i19.i to <64 x i8>
  %tobool.i = icmp ne i32 %sgn_y, 0
  %conv.i.i = zext i1 %tobool.i to i32
  %4 = tail call noundef <128 x i8> @llvm.aie2p.unpack.I1024.I8.I4(<64 x i8> %3, i32 %conv.i.i)
  %shuffle1.i.i20.i = shufflevector <32 x i32> %2, <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %5 = bitcast <16 x i32> %shuffle1.i.i20.i to <64 x i8>
  %6 = tail call noundef <128 x i8> @llvm.aie2p.unpack.I1024.I8.I4(<64 x i8> %5, i32 %conv.i.i)
  %shuffle.i.i22.i = shufflevector <8 x i32> %shuffle1.i.i.i, <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %shl1.i.i.i = shl i32 %shift16, 10
  %shl2.i.i.i = shl i32 %sub_mul, 11
  %shl4.i.i.i = shl i32 %sub_acc1, 12
  %shl14.i.i.i = shl i32 %sgn_x, 9
  %shl15.i.i.i = shl i32 %sgn_y, 8
  %or3.i.i.i = or i32 %shl15.i.i.i, %shl14.i.i.i
  %7 = or i32 %shl1.i.i.i, %zero_acc1
  %8 = or i32 %7, %shl2.i.i.i
  %9 = or i32 %8, %shl4.i.i.i
  %or16.i.i.i = or i32 %9, %or3.i.i.i
  %or17.i.i.i = or i32 %or16.i.i.i, 200
  %10 = bitcast <128 x i8> %6 to <64 x i16>
  %11 = bitcast <64 x i32> %acc1 to <32 x i64>
  %12 = tail call <32 x i64> @llvm.aie2p.I512.I1024.ACC2048.mac.conf(<16 x i32> %shuffle.i.i22.i, <64 x i16> %10, <32 x i64> %11, i32 %or17.i.i.i)
  %shuffle.i.i23.i = shufflevector <8 x i32> %shuffle.i.i.i, <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %shl6.i.i.i = shl i32 %sub_acc2, 13
  %or7.i.i27.i = or i32 %or3.i.i.i, %shl6.i.i.i
  %or19.i.i.i = or disjoint i32 %or7.i.i27.i, 200
  %13 = bitcast <128 x i8> %4 to <64 x i16>
  %14 = bitcast <64 x i32> %acc2 to <32 x i64>
  %15 = tail call <32 x i64> @llvm.aie2p.I512.I1024.ACC2048.addmac.conf(<16 x i32> %shuffle.i.i23.i, <64 x i16> %13, <32 x i64> %12, <32 x i64> %14, i32 %or19.i.i.i)
  %16 = bitcast <32 x i64> %15 to <64 x i32>
  ret <64 x i32> %16
}
define dso_local inreg noundef <64 x i32> @_Z27test_addmsc_4x16_16x16_confDv64_hiDv128_DB8_iDv64_u7__acc32S2_iiiii(<64 x i8> noundef %a, i32 noundef %sgn_x, <128 x i8> noundef %b, i32 noundef %sgn_y, <64 x i32> inreg noundef %acc1, <64 x i32> inreg noundef %acc2, i32 noundef %zero_acc1, i32 noundef %shift16, i32 noundef %sub_mul, i32 noundef %sub_acc1, i32 noundef %sub_acc2)  {
; CHECK-LABEL: _Z27test_addmsc_4x16_16x16_confDv64_hiDv128_DB8_iDv64_u7__acc32S2_iiiii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mova r17, #11; nopb ; nops ; nez r16, r1; nopm ; nopv
; CHECK-NEXT:    mova r7, #10; nopb ; lshl r4, r4, r17
; CHECK-NEXT:    mova r7, #12; lshl r3, r3, r7
; CHECK-NEXT:    mova r17, #9; lshl r5, r5, r7
; CHECK-NEXT:    mova r7, #8; lshl r0, r0, r17
; CHECK-NEXT:    vunpack y3, x5, unpacksign0; lshl r1, r1, r7
; CHECK-NEXT:    vunpack y1, x4, unpacksign0; or r0, r1, r0
; CHECK-NEXT:    or r1, r3, r2; mov crunpacksize, #0
; CHECK-NEXT:    or r1, r1, r4; mov unpacksign0, r16
; CHECK-NEXT:    mova r4, #13; or r1, r1, r5; mov r2, #50
; CHECK-NEXT:    lshl r2, r6, r4; vshuffle x0, x0, x0, r2
; CHECK-NEXT:    mova r3, #200; or r1, r1, r0; vmov wl4, wh0
; CHECK-NEXT:    or r1, r1, r3
; CHECK-NEXT:    or r0, r0, r2; vmsc dm0, dm1, x4, y3,r1
; CHECK-NEXT:    or r0, r0, r3
; CHECK-NEXT:    ret lr; vaddmsc dm0, dm0, dm2, x0, y1,r0
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    mov unpacksign0, #0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <64 x i8> %a to <16 x i32>
  %1 = tail call <16 x i32> @llvm.aie2p.vshuffle(<16 x i32> %0, <16 x i32> undef, i32 50)
  %shuffle.i.i.i = shufflevector <16 x i32> %1, <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %shuffle1.i.i.i = shufflevector <16 x i32> %1, <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %2 = bitcast <128 x i8> %b to <32 x i32>
  %shuffle.i.i19.i = shufflevector <32 x i32> %2, <32 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %3 = bitcast <16 x i32> %shuffle.i.i19.i to <64 x i8>
  %tobool.i = icmp ne i32 %sgn_y, 0
  %conv.i.i = zext i1 %tobool.i to i32
  %4 = tail call noundef <128 x i8> @llvm.aie2p.unpack.I1024.I8.I4(<64 x i8> %3, i32 %conv.i.i)
  %shuffle1.i.i20.i = shufflevector <32 x i32> %2, <32 x i32> poison, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %5 = bitcast <16 x i32> %shuffle1.i.i20.i to <64 x i8>
  %6 = tail call noundef <128 x i8> @llvm.aie2p.unpack.I1024.I8.I4(<64 x i8> %5, i32 %conv.i.i)
  %shuffle.i.i22.i = shufflevector <8 x i32> %shuffle1.i.i.i, <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %shl1.i.i.i = shl i32 %shift16, 10
  %shl2.i.i.i = shl i32 %sub_mul, 11
  %shl4.i.i.i = shl i32 %sub_acc1, 12
  %shl14.i.i.i = shl i32 %sgn_x, 9
  %shl15.i.i.i = shl i32 %sgn_y, 8
  %or3.i.i.i = or i32 %shl15.i.i.i, %shl14.i.i.i
  %7 = or i32 %shl1.i.i.i, %zero_acc1
  %8 = or i32 %7, %shl2.i.i.i
  %9 = or i32 %8, %shl4.i.i.i
  %or16.i.i.i = or i32 %9, %or3.i.i.i
  %or17.i.i.i = or i32 %or16.i.i.i, 200
  %10 = bitcast <128 x i8> %6 to <64 x i16>
  %11 = bitcast <64 x i32> %acc1 to <32 x i64>
  %12 = tail call <32 x i64> @llvm.aie2p.I512.I1024.ACC2048.msc.conf(<16 x i32> %shuffle.i.i22.i, <64 x i16> %10, <32 x i64> %11, i32 %or17.i.i.i)
  %shuffle.i.i23.i = shufflevector <8 x i32> %shuffle.i.i.i, <8 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %shl6.i.i.i = shl i32 %sub_acc2, 13
  %or7.i.i27.i = or i32 %or3.i.i.i, %shl6.i.i.i
  %or19.i.i.i = or disjoint i32 %or7.i.i27.i, 200
  %13 = bitcast <128 x i8> %4 to <64 x i16>
  %14 = bitcast <64 x i32> %acc2 to <32 x i64>
  %15 = tail call <32 x i64> @llvm.aie2p.I512.I1024.ACC2048.addmsc.conf(<16 x i32> %shuffle.i.i23.i, <64 x i16> %13, <32 x i64> %12, <32 x i64> %14, i32 %or19.i.i.i)
  %16 = bitcast <32 x i64> %15 to <64 x i32>
  ret <64 x i32> %16
}

declare <16 x i32> @llvm.aie2p.vshuffle(<16 x i32>, <16 x i32>, i32)
declare <32 x i64> @llvm.aie2p.I512.I512.ACC2048.mul.conf(<16 x i32>, <32 x i16>, i32)
declare <32 x i64> @llvm.aie2p.I512.I512.ACC2048.mac.conf(<16 x i32>, <32 x i16>, <32 x i64>, i32)
declare <32 x i64> @llvm.aie2p.I512.I512.ACC2048.negmul.conf(<16 x i32>, <32 x i16>, i32)
declare <32 x i64> @llvm.aie2p.I512.I512.ACC2048.msc.conf(<16 x i32>, <32 x i16>, <32 x i64>, i32)
declare <32 x i64> @llvm.aie2p.I512.I512.ACC2048.addmac.conf(<16 x i32>, <32 x i16>, <32 x i64>, <32 x i64>, i32)
declare <32 x i64> @llvm.aie2p.I512.I512.ACC2048.addmsc.conf(<16 x i32>, <32 x i16>, <32 x i64>, <32 x i64>, i32)
declare <128 x i8> @llvm.aie2p.unpack.I1024.I8.I4(<64 x i8>, i32)
declare <32 x i64> @llvm.aie2p.I512.I1024.ACC2048.mac.conf(<16 x i32>, <64 x i16>, <32 x i64>, i32)
declare <32 x i64> @llvm.aie2p.I512.I1024.ACC2048.addmac.conf(<16 x i32>, <64 x i16>, <32 x i64>, <32 x i64>, i32)
declare <32 x i64> @llvm.aie2p.I512.I1024.ACC2048.msc.conf(<16 x i32>, <64 x i16>, <32 x i64>, i32)
declare <32 x i64> @llvm.aie2p.I512.I1024.ACC2048.addmsc.conf(<16 x i32>, <64 x i16>, <32 x i64>, <32 x i64>, i32)
