; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates
; RUN: llc -mtriple=aie2p -verify-machineinstrs -o - < %s | FileCheck %s

%struct.v64bfp16ebs8 = type <{ <64 x i8>, <8 x i8> }>
%struct.v64bfp16ebs16 = type <{ <64 x i8>, <8 x i8> }>

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <16 x i32> @_Z18test_broadcast_s64Dv2_j(<2 x i32> noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z18test_broadcast_s64Dv2_j:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vbcst.64 x0, r1:r0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %vecinit30.i.i = shufflevector <2 x i32> %b, <2 x i32> poison, <16 x i32> <i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1>
  ret <16 x i32> %vecinit30.i.i
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <16 x i32> @_Z27test_broadcast_to_v16uint32Dv2_j(<2 x i32> noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z27test_broadcast_to_v16uint32Dv2_j:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vbcst.64 x0, r1:r0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %vecinit30.i.i = shufflevector <2 x i32> %b, <2 x i32> poison, <16 x i32> <i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1>
  ret <16 x i32> %vecinit30.i.i
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local inreg noundef <16 x float> @_Z29test_broadcast_to_v16accfloatDv2_f(<2 x float> noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z29test_broadcast_to_v16accfloatDv2_f:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    vbcst.64 x0, r1:r0 // Delay Slot 3
; CHECK-NEXT:    vmov bmll0, x0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = shufflevector <2 x float> %b, <2 x float> poison, <16 x i32> <i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1>
  ret <16 x float> %0
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <16 x float> @_Z26test_broadcast_to_v16floatDv2_f(<2 x float> noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z26test_broadcast_to_v16floatDv2_f:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vbcst.64 x0, r1:r0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = shufflevector <2 x float> %b, <2 x float> poison, <16 x i32> <i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1, i32 0, i32 1>
  ret <16 x float> %0
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <16 x float> @_Z30test_broadcast_one_to_v16floatv() local_unnamed_addr  {
; CHECK-LABEL: _Z30test_broadcast_one_to_v16floatv:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    movxm r0, #1065353216 // Delay Slot 3
; CHECK-NEXT:    vbcst.32 x0, r0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  ret <16 x float> <float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00>
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local noundef <16 x i32> @_Z23test_broadcast_elem_128Dv16_ii(<16 x i32> noundef %a, i32 noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z23test_broadcast_elem_128Dv16_ii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vextbcst.128 x0, x2, r0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call noundef <16 x i32> @llvm.aie2p.vextract.broadcast128.I512(<16 x i32> %a, i32 %b)
  ret <16 x i32> %0
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <64 x i8> @_Z13test_upd_elemDv64_DB8_iS_(<64 x i8> noundef %v, i32 noundef %idx, i8 noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z13test_upd_elemDv64_DB8_iS_:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mov r29, r0 // Delay Slot 3
; CHECK-NEXT:    vinsert.8 x0, x2, r29, r1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %vecins.i.i = insertelement <64 x i8> %v, i8 %b, i32 %idx
  ret <64 x i8> %vecins.i.i
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <64 x i8> @_Z13test_upd_elemDv64_DB8_iDv2_S_(<64 x i8> noundef %v, i32 noundef %idx, <2 x i8> noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z13test_upd_elemDv64_DB8_iDv2_S_:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mov r29, r0 // Delay Slot 3
; CHECK-NEXT:    vinsert.16 x0, x2, r29, r1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <64 x i8> %v to <32 x i16>
  %1 = bitcast <2 x i8> %b to i16
  %vecins.i.i = insertelement <32 x i16> %0, i16 %1, i32 %idx
  %2 = bitcast <32 x i16> %vecins.i.i to <64 x i8>
  ret <64 x i8> %2
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <64 x i8> @_Z13test_upd_elemDv64_DB8_iDv4_S_(<64 x i8> noundef %v, i32 noundef %idx, <4 x i8> noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z13test_upd_elemDv64_DB8_iDv4_S_:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mov r29, r0 // Delay Slot 3
; CHECK-NEXT:    vinsert.32 x0, x2, r29, r1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <64 x i8> %v to <16 x i32>
  %1 = bitcast <4 x i8> %b to i32
  %vecins.i.i = insertelement <16 x i32> %0, i32 %1, i32 %idx
  %2 = bitcast <16 x i32> %vecins.i.i to <64 x i8>
  ret <64 x i8> %2
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <64 x i8> @_Z13test_upd_elemDv64_DB8_iDv8_S_(<64 x i8> noundef %v, i32 noundef %idx, <8 x i8> noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z13test_upd_elemDv64_DB8_iDv8_S_:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; ret lr; nopm
; CHECK-NEXT:    mova r1, #1 // Delay Slot 5
; CHECK-NEXT:    lshl r29, r0, r1 // Delay Slot 4
; CHECK-NEXT:    or r29, r29, r1; vinsert.32 x0, x2, r29, r2 // Delay Slot 3
; CHECK-NEXT:    vinsert.32 x0, x0, r29, r3 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <64 x i8> %v to <16 x i32>
  %1 = bitcast <8 x i8> %b to <2 x i32>
  %mul.i.i = shl nsw i32 %idx, 1
  %vecext.i.i = extractelement <2 x i32> %1, i64 0
  %vecins.i.i = insertelement <16 x i32> %0, i32 %vecext.i.i, i32 %mul.i.i
  %vecext1.i.i = extractelement <2 x i32> %1, i64 1
  %add.i.i = or disjoint i32 %mul.i.i, 1
  %vecins2.i.i = insertelement <16 x i32> %vecins.i.i, i32 %vecext1.i.i, i32 %add.i.i
  %2 = bitcast <16 x i32> %vecins2.i.i to <64 x i8>
  ret <64 x i8> %2
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <64 x i8> @_Z13test_upd_elemDv64_aiDv2_a(<64 x i8> noundef %v, i32 noundef %idx, <2 x i8> noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z13test_upd_elemDv64_aiDv2_a:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mov r29, r0 // Delay Slot 3
; CHECK-NEXT:    vinsert.16 x0, x2, r29, r1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <64 x i8> %v to <32 x i16>
  %1 = bitcast <2 x i8> %b to i16
  %vecins.i.i = insertelement <32 x i16> %0, i16 %1, i32 %idx
  %2 = bitcast <32 x i16> %vecins.i.i to <64 x i8>
  ret <64 x i8> %2
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <64 x i8> @_Z13test_upd_elemDv64_aiDv4_a(<64 x i8> noundef %v, i32 noundef %idx, <4 x i8> noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z13test_upd_elemDv64_aiDv4_a:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mov r29, r0 // Delay Slot 3
; CHECK-NEXT:    vinsert.32 x0, x2, r29, r1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <64 x i8> %v to <16 x i32>
  %1 = bitcast <4 x i8> %b to i32
  %vecins.i.i = insertelement <16 x i32> %0, i32 %1, i32 %idx
  %2 = bitcast <16 x i32> %vecins.i.i to <64 x i8>
  ret <64 x i8> %2
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <64 x i8> @_Z13test_upd_elemDv64_aiDv8_a(<64 x i8> noundef %v, i32 noundef %idx, <8 x i8> noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z13test_upd_elemDv64_aiDv8_a:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; ret lr; nopm
; CHECK-NEXT:    mova r1, #1 // Delay Slot 5
; CHECK-NEXT:    lshl r29, r0, r1 // Delay Slot 4
; CHECK-NEXT:    or r29, r29, r1; vinsert.32 x0, x2, r29, r2 // Delay Slot 3
; CHECK-NEXT:    vinsert.32 x0, x0, r29, r3 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <64 x i8> %v to <16 x i32>
  %1 = bitcast <8 x i8> %b to <2 x i32>
  %mul.i.i = shl nsw i32 %idx, 1
  %vecext.i.i = extractelement <2 x i32> %1, i64 0
  %vecins.i.i = insertelement <16 x i32> %0, i32 %vecext.i.i, i32 %mul.i.i
  %vecext1.i.i = extractelement <2 x i32> %1, i64 1
  %add.i.i = or disjoint i32 %mul.i.i, 1
  %vecins2.i.i = insertelement <16 x i32> %vecins.i.i, i32 %vecext1.i.i, i32 %add.i.i
  %2 = bitcast <16 x i32> %vecins2.i.i to <64 x i8>
  ret <64 x i8> %2
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <32 x i16> @_Z13test_upd_elemDv32_siDv2_s(<32 x i16> noundef %v, i32 noundef %idx, <2 x i16> noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z13test_upd_elemDv32_siDv2_s:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mov r29, r0 // Delay Slot 3
; CHECK-NEXT:    vinsert.32 x0, x2, r29, r1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <32 x i16> %v to <16 x i32>
  %1 = bitcast <2 x i16> %b to i32
  %vecins.i.i = insertelement <16 x i32> %0, i32 %1, i32 %idx
  %2 = bitcast <16 x i32> %vecins.i.i to <32 x i16>
  ret <32 x i16> %2
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <32 x i16> @_Z13test_upd_elemDv32_siDv4_s(<32 x i16> noundef %v, i32 noundef %idx, <4 x i16> noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z13test_upd_elemDv32_siDv4_s:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; ret lr; nopm
; CHECK-NEXT:    mova r1, #1 // Delay Slot 5
; CHECK-NEXT:    lshl r29, r0, r1 // Delay Slot 4
; CHECK-NEXT:    or r29, r29, r1; vinsert.32 x0, x2, r29, r2 // Delay Slot 3
; CHECK-NEXT:    vinsert.32 x0, x0, r29, r3 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <32 x i16> %v to <16 x i32>
  %1 = bitcast <4 x i16> %b to <2 x i32>
  %mul.i.i = shl nsw i32 %idx, 1
  %vecext.i.i = extractelement <2 x i32> %1, i64 0
  %vecins.i.i = insertelement <16 x i32> %0, i32 %vecext.i.i, i32 %mul.i.i
  %vecext1.i.i = extractelement <2 x i32> %1, i64 1
  %add.i.i = or disjoint i32 %mul.i.i, 1
  %vecins2.i.i = insertelement <16 x i32> %vecins.i.i, i32 %vecext1.i.i, i32 %add.i.i
  %2 = bitcast <16 x i32> %vecins2.i.i to <32 x i16>
  ret <32 x i16> %2
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <16 x i32> @_Z13test_upd_elemDv16_iiDv2_i(<16 x i32> noundef %v, i32 noundef %idx, <2 x i32> noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z13test_upd_elemDv16_iiDv2_i:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; ret lr; nopm
; CHECK-NEXT:    mova r1, #1 // Delay Slot 5
; CHECK-NEXT:    lshl r29, r0, r1 // Delay Slot 4
; CHECK-NEXT:    or r29, r29, r1; vinsert.32 x0, x2, r29, r2 // Delay Slot 3
; CHECK-NEXT:    vinsert.32 x0, x0, r29, r3 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %mul.i.i = shl nsw i32 %idx, 1
  %vecext.i.i = extractelement <2 x i32> %b, i64 0
  %vecins.i.i = insertelement <16 x i32> %v, i32 %vecext.i.i, i32 %mul.i.i
  %vecext1.i.i = extractelement <2 x i32> %b, i64 1
  %add.i.i = or disjoint i32 %mul.i.i, 1
  %vecins2.i.i = insertelement <16 x i32> %vecins.i.i, i32 %vecext1.i.i, i32 %add.i.i
  ret <16 x i32> %vecins2.i.i
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <64 x i8> @_Z13test_upd_elemDv64_DU8_iS_(<64 x i8> noundef %v, i32 noundef %idx, i8 noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z13test_upd_elemDv64_DU8_iS_:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mov r29, r0 // Delay Slot 3
; CHECK-NEXT:    vinsert.8 x0, x2, r29, r1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %vecins.i.i = insertelement <64 x i8> %v, i8 %b, i32 %idx
  ret <64 x i8> %vecins.i.i
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <64 x i8> @_Z13test_upd_elemDv64_DU8_iDv2_S_(<64 x i8> noundef %v, i32 noundef %idx, <2 x i8> noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z13test_upd_elemDv64_DU8_iDv2_S_:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mova r2, #-16; nopb ; nopxm ; nops
; CHECK-NEXT:    lshl r2, r1, r2
; CHECK-NEXT:    extend.u8 r1, r1
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    mova r3, #8; extend.u8 r2, r2 // Delay Slot 5
; CHECK-NEXT:    lshl r2, r2, r3 // Delay Slot 4
; CHECK-NEXT:    or r1, r1, r2; mov r29, r0 // Delay Slot 3
; CHECK-NEXT:    vinsert.8 x0, x2, r29, r1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %conv.i.i = extractelement <2 x i8> %b, i64 0
  %vecins.i.i = insertelement <64 x i8> %v, i8 %conv.i.i, i32 %idx
  ret <64 x i8> %vecins.i.i
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <64 x i8> @_Z13test_upd_elemDv64_DU8_iDv4_S_(<64 x i8> noundef %v, i32 noundef %idx, <4 x i8> noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z13test_upd_elemDv64_DU8_iDv4_S_:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mov r29, r0 // Delay Slot 3
; CHECK-NEXT:    vinsert.8 x0, x2, r29, r1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %conv.i.i = extractelement <4 x i8> %b, i64 0
  %vecins.i.i = insertelement <64 x i8> %v, i8 %conv.i.i, i32 %idx
  ret <64 x i8> %vecins.i.i
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <64 x i8> @_Z13test_upd_elemDv64_DU8_iDv8_S_(<64 x i8> noundef %v, i32 noundef %idx, <8 x i8> noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z13test_upd_elemDv64_DU8_iDv8_S_:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; ret lr; nopm
; CHECK-NEXT:    mova r1, #1 // Delay Slot 5
; CHECK-NEXT:    lshl r29, r0, r1 // Delay Slot 4
; CHECK-NEXT:    or r29, r29, r1; vinsert.32 x0, x2, r29, r2 // Delay Slot 3
; CHECK-NEXT:    vinsert.32 x0, x0, r29, r3 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <64 x i8> %v to <16 x i32>
  %1 = bitcast <8 x i8> %b to <2 x i32>
  %mul.i.i = shl nsw i32 %idx, 1
  %vecext.i.i = extractelement <2 x i32> %1, i64 0
  %vecins.i.i = insertelement <16 x i32> %0, i32 %vecext.i.i, i32 %mul.i.i
  %vecext1.i.i = extractelement <2 x i32> %1, i64 1
  %add.i.i = or disjoint i32 %mul.i.i, 1
  %vecins2.i.i = insertelement <16 x i32> %vecins.i.i, i32 %vecext1.i.i, i32 %add.i.i
  %2 = bitcast <16 x i32> %vecins2.i.i to <64 x i8>
  ret <64 x i8> %2
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <64 x i8> @_Z13test_upd_elemDv64_hih(<64 x i8> noundef %v, i32 noundef %idx, i8 noundef zeroext %b) local_unnamed_addr  {
; CHECK-LABEL: _Z13test_upd_elemDv64_hih:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mov r29, r0 // Delay Slot 3
; CHECK-NEXT:    vinsert.8 x0, x2, r29, r1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %vecins.i.i = insertelement <64 x i8> %v, i8 %b, i32 %idx
  ret <64 x i8> %vecins.i.i
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <64 x i8> @_Z13test_upd_elemDv64_hiDv2_h(<64 x i8> noundef %v, i32 noundef %idx, <2 x i8> noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z13test_upd_elemDv64_hiDv2_h:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mov r29, r0 // Delay Slot 3
; CHECK-NEXT:    vinsert.16 x0, x2, r29, r1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <64 x i8> %v to <32 x i16>
  %1 = bitcast <2 x i8> %b to i16
  %vecins.i.i = insertelement <32 x i16> %0, i16 %1, i32 %idx
  %2 = bitcast <32 x i16> %vecins.i.i to <64 x i8>
  ret <64 x i8> %2
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <64 x i8> @_Z13test_upd_elemDv64_hiDv4_h(<64 x i8> noundef %v, i32 noundef %idx, <4 x i8> noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z13test_upd_elemDv64_hiDv4_h:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mov r29, r0 // Delay Slot 3
; CHECK-NEXT:    vinsert.32 x0, x2, r29, r1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <64 x i8> %v to <16 x i32>
  %1 = bitcast <4 x i8> %b to i32
  %vecins.i.i = insertelement <16 x i32> %0, i32 %1, i32 %idx
  %2 = bitcast <16 x i32> %vecins.i.i to <64 x i8>
  ret <64 x i8> %2
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <64 x i8> @_Z13test_upd_elemDv64_hiDv8_h(<64 x i8> noundef %v, i32 noundef %idx, <8 x i8> noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z13test_upd_elemDv64_hiDv8_h:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; ret lr; nopm
; CHECK-NEXT:    mova r1, #1 // Delay Slot 5
; CHECK-NEXT:    lshl r29, r0, r1 // Delay Slot 4
; CHECK-NEXT:    or r29, r29, r1; vinsert.32 x0, x2, r29, r2 // Delay Slot 3
; CHECK-NEXT:    vinsert.32 x0, x0, r29, r3 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <64 x i8> %v to <16 x i32>
  %1 = bitcast <8 x i8> %b to <2 x i32>
  %mul.i.i = shl nsw i32 %idx, 1
  %vecext.i.i = extractelement <2 x i32> %1, i64 0
  %vecins.i.i = insertelement <16 x i32> %0, i32 %vecext.i.i, i32 %mul.i.i
  %vecext1.i.i = extractelement <2 x i32> %1, i64 1
  %add.i.i = or disjoint i32 %mul.i.i, 1
  %vecins2.i.i = insertelement <16 x i32> %vecins.i.i, i32 %vecext1.i.i, i32 %add.i.i
  %2 = bitcast <16 x i32> %vecins2.i.i to <64 x i8>
  ret <64 x i8> %2
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <32 x i16> @_Z13test_upd_elemDv32_tiDv2_t(<32 x i16> noundef %v, i32 noundef %idx, <2 x i16> noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z13test_upd_elemDv32_tiDv2_t:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mov r29, r0 // Delay Slot 3
; CHECK-NEXT:    vinsert.32 x0, x2, r29, r1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <32 x i16> %v to <16 x i32>
  %1 = bitcast <2 x i16> %b to i32
  %vecins.i.i = insertelement <16 x i32> %0, i32 %1, i32 %idx
  %2 = bitcast <16 x i32> %vecins.i.i to <32 x i16>
  ret <32 x i16> %2
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <32 x i16> @_Z13test_upd_elemDv32_tiDv4_t(<32 x i16> noundef %v, i32 noundef %idx, <4 x i16> noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z13test_upd_elemDv32_tiDv4_t:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; ret lr; nopm
; CHECK-NEXT:    mova r1, #1 // Delay Slot 5
; CHECK-NEXT:    lshl r29, r0, r1 // Delay Slot 4
; CHECK-NEXT:    or r29, r29, r1; vinsert.32 x0, x2, r29, r2 // Delay Slot 3
; CHECK-NEXT:    vinsert.32 x0, x0, r29, r3 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <32 x i16> %v to <16 x i32>
  %1 = bitcast <4 x i16> %b to <2 x i32>
  %mul.i.i = shl nsw i32 %idx, 1
  %vecext.i.i = extractelement <2 x i32> %1, i64 0
  %vecins.i.i = insertelement <16 x i32> %0, i32 %vecext.i.i, i32 %mul.i.i
  %vecext1.i.i = extractelement <2 x i32> %1, i64 1
  %add.i.i = or disjoint i32 %mul.i.i, 1
  %vecins2.i.i = insertelement <16 x i32> %vecins.i.i, i32 %vecext1.i.i, i32 %add.i.i
  %2 = bitcast <16 x i32> %vecins2.i.i to <32 x i16>
  ret <32 x i16> %2
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <16 x i32> @_Z13test_upd_elemDv16_jij(<16 x i32> noundef %v, i32 noundef %idx, i32 noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z13test_upd_elemDv16_jij:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mov r29, r0 // Delay Slot 3
; CHECK-NEXT:    vinsert.32 x0, x2, r29, r1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %vecins.i.i = insertelement <16 x i32> %v, i32 %b, i32 %idx
  ret <16 x i32> %vecins.i.i
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <16 x i32> @_Z13test_upd_elemDv16_jiDv2_j(<16 x i32> noundef %v, i32 noundef %idx, <2 x i32> noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z13test_upd_elemDv16_jiDv2_j:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; ret lr; nopm
; CHECK-NEXT:    mova r1, #1 // Delay Slot 5
; CHECK-NEXT:    lshl r29, r0, r1 // Delay Slot 4
; CHECK-NEXT:    or r29, r29, r1; vinsert.32 x0, x2, r29, r2 // Delay Slot 3
; CHECK-NEXT:    vinsert.32 x0, x0, r29, r3 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %mul.i.i = shl nsw i32 %idx, 1
  %vecext.i.i = extractelement <2 x i32> %b, i64 0
  %vecins.i.i = insertelement <16 x i32> %v, i32 %vecext.i.i, i32 %mul.i.i
  %vecext1.i.i = extractelement <2 x i32> %b, i64 1
  %add.i.i = or disjoint i32 %mul.i.i, 1
  %vecins2.i.i = insertelement <16 x i32> %vecins.i.i, i32 %vecext1.i.i, i32 %add.i.i
  ret <16 x i32> %vecins2.i.i
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <16 x float> @_Z13test_upd_elemDv16_fif(<16 x float> noundef %v, i32 noundef %idx, float noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z13test_upd_elemDv16_fif:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; jl #__floatsisf
; CHECK-NEXT:    paddxm [sp], #128 // Delay Slot 5
; CHECK-NEXT:    st r8, [sp, #-60] // 4-byte Folded Spill Delay Slot 4
; CHECK-NEXT:    st lr, [sp, #-64] // 4-byte Folded Spill Delay Slot 3
; CHECK-NEXT:    vst x2, [sp, #-128] // 64-byte Folded Spill Delay Slot 2
; CHECK-NEXT:    mov r8, r0 // Delay Slot 1
; CHECK-NEXT:    lda lr, [sp, #-64]; nopxm // 4-byte Folded Reload
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    vlda x0, [sp, #-128] // 64-byte Folded Reload
; CHECK-NEXT:    nop
; CHECK-NEXT:    lda r8, [sp, #-60] // 4-byte Folded Reload
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    mov r29, r8 // Delay Slot 4
; CHECK-NEXT:    paddxm [sp], #-128 // Delay Slot 3
; CHECK-NEXT:    vinsert.32 x0, x0, r29, r0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast float %b to i32
  %conv.i.i = sitofp i32 %0 to float
  %vecins.i.i = insertelement <16 x float> %v, float %conv.i.i, i32 %idx
  ret <16 x float> %vecins.i.i
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <32 x bfloat> @_Z13test_upd_elemDv32_u6__bf16iu6__bf16(<32 x bfloat> noundef %v, i32 noundef %idx, bfloat noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z13test_upd_elemDv32_u6__bf16iu6__bf16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mov r29, r0 // Delay Slot 3
; CHECK-NEXT:    vinsert.16 x0, x2, r29, r1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %vecins.i.i = insertelement <32 x bfloat> %v, bfloat %b, i32 %idx
  ret <32 x bfloat> %vecins.i.i
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local noundef <32 x bfloat> @_Z13test_upd_elemDv32_u6__bf16iDv2_u6__bf16(<32 x bfloat> noundef %v, i32 noundef %idx, <2 x bfloat> noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z13test_upd_elemDv32_u6__bf16iDv2_u6__bf16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mov r29, r0 // Delay Slot 3
; CHECK-NEXT:    vinsert.32 x0, x2, r29, r1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call noundef <32 x bfloat> @llvm.aie2p.vinsert32.bf512(<32 x bfloat> %v, i32 %idx, <2 x bfloat> %b)
  ret <32 x bfloat> %0
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local noundef <32 x bfloat> @_Z13test_upd_elemDv32_u6__bf16iDv4_u6__bf16(<32 x bfloat> noundef %v, i32 noundef %idx, <4 x bfloat> noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z13test_upd_elemDv32_u6__bf16iDv4_u6__bf16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mov r29, r0 // Delay Slot 3
; CHECK-NEXT:    vinsert.64 x0, x2, r29, r3:r2 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call noundef <32 x bfloat> @llvm.aie2p.vinsert64.bf512(<32 x bfloat> %v, i32 %idx, <4 x bfloat> %b)
  ret <32 x bfloat> %0
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local noundef <32 x bfloat> @_Z13test_upd_elemDv32_u6__bf16iy(<32 x bfloat> noundef %v, i32 noundef %idx, i64 noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z13test_upd_elemDv32_u6__bf16iy:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; ret lr; nopm ; nops
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    mov r4, r1 // Delay Slot 4
; CHECK-NEXT:    or r29, r0, r0; mov r5, r2 // Delay Slot 3
; CHECK-NEXT:    vinsert.64 x0, x2, r29, r5:r4 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast i64 %b to <4 x bfloat>
  %1 = tail call noundef <32 x bfloat> @llvm.aie2p.vinsert64.bf512(<32 x bfloat> %v, i32 %idx, <4 x bfloat> %0)
  ret <32 x bfloat> %1
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <16 x float> @_Z16test_shiftl_elemDv16_u10__accfloatf(<16 x float> inreg noundef %a, float noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z16test_shiftl_elemDv16_u10__accfloatf:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; ret lr; nopm
; CHECK-NEXT:    vbcst.32 x0, r0 // Delay Slot 5
; CHECK-NEXT:    mova r1, #4; vmov x2, bmll1 // Delay Slot 4
; CHECK-NEXT:    vshift x0, x2, x0, r1 // Delay Slot 3
; CHECK-NEXT:    vmov bmll0, x0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = insertelement <16 x float> poison, float %b, i64 0
  %1 = bitcast <16 x float> %a to <16 x i32>
  %2 = bitcast <16 x float> %0 to <16 x i32>
  %3 = shufflevector <16 x i32> %2, <16 x i32> poison, <16 x i32> zeroinitializer
  %4 = tail call <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> %1, <16 x i32> %3, i32 0, i32 4)
  %5 = bitcast <16 x i32> %4 to <16 x float>
  ret <16 x float> %5
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <16 x float> @_Z16test_shiftr_elemDv16_u10__accfloatf(<16 x float> inreg noundef %a, float noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z16test_shiftr_elemDv16_u10__accfloatf:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; ret lr; nopm
; CHECK-NEXT:    vbcst.32 x0, r0 // Delay Slot 5
; CHECK-NEXT:    mova r1, #60; vmov x2, bmll1 // Delay Slot 4
; CHECK-NEXT:    vshift x0, x0, x2, r1 // Delay Slot 3
; CHECK-NEXT:    vmov bmll0, x0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = insertelement <16 x float> poison, float %b, i64 0
  %1 = bitcast <16 x float> %0 to <16 x i32>
  %2 = shufflevector <16 x i32> %1, <16 x i32> poison, <16 x i32> zeroinitializer
  %3 = bitcast <16 x float> %a to <16 x i32>
  %4 = tail call <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32> %2, <16 x i32> %3, i32 0, i32 60)
  %5 = bitcast <16 x i32> %4 to <16 x float>
  ret <16 x float> %5
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef float @_Z13test_ext_elemDv16_fii(<16 x float> noundef %a, i32 noundef %b, i32 noundef %c) local_unnamed_addr  {
; CHECK-LABEL: _Z13test_ext_elemDv16_fii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; jl #__floatsisf; nops
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    paddxm [sp], #64 // Delay Slot 4
; CHECK-NEXT:    st lr, [sp, #-64] // 4-byte Folded Spill Delay Slot 3
; CHECK-NEXT:    vextract.32 r1, x0, r1, vaddsign1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
; CHECK-NEXT:    lda lr, [sp, #-64]; nopb ; nops ; nopxm ; nopv // 4-byte Folded Reload
; CHECK-NEXT:    nopx
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    paddxm [sp], #-64 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <16 x float> %a to <16 x i32>
  %vecext.i.i = extractelement <16 x i32> %0, i32 %b
  %conv.i = sitofp i32 %vecext.i.i to float
  ret float %conv.i
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <2 x float> @_Z16test_ext_v2floatDv16_fii(<16 x float> noundef %a, i32 noundef %b, i32 noundef %c) local_unnamed_addr  {
; CHECK-LABEL: _Z16test_ext_v2floatDv16_fii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; paddxm [sp], #64; nops
; CHECK-NEXT:    jl #__floatsisf
; CHECK-NEXT:    st r8, [sp, #-60] // 4-byte Folded Spill Delay Slot 5
; CHECK-NEXT:    st r10, [sp, #-56] // 4-byte Folded Spill Delay Slot 4
; CHECK-NEXT:    st lr, [sp, #-64]; add r0, r2, #1; vextract.32 r1, x0, r2, vaddsign1 // 4-byte Folded Spill Delay Slot 3
; CHECK-NEXT:    st r11, [sp, #-52]; vextract.32 r8, x0, r0, vaddsign1 // 4-byte Folded Spill Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
; CHECK-NEXT:    nopa ; nopb ; nops ; jl #__floatsisf; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    or r10, r0, r0; mov r1, r8 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
; CHECK-NEXT:    lda lr, [sp, #-64]; nopx // 4-byte Folded Reload
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    lda r10, [sp, #-56] // 4-byte Folded Reload
; CHECK-NEXT:    lda r8, [sp, #-60] // 4-byte Folded Reload
; CHECK-NEXT:    lda r11, [sp, #-52] // 4-byte Folded Reload
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    or r11, r0, r0; mov r0, r10 // Delay Slot 4
; CHECK-NEXT:    mov r1, r11 // Delay Slot 3
; CHECK-NEXT:    paddxm [sp], #-64 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <16 x float> %a to <16 x i32>
  %vecext.i.i = extractelement <16 x i32> %0, i32 %b
  %add.i = add nsw i32 %b, 1
  %vecext.i7.i = extractelement <16 x i32> %0, i32 %add.i
  %conv.i = sitofp i32 %vecext.i.i to float
  %vecinit.i = insertelement <2 x float> poison, float %conv.i, i64 0
  %conv2.i = sitofp i32 %vecext.i7.i to float
  %vecinit3.i = insertelement <2 x float> %vecinit.i, float %conv2.i, i64 1
  ret <2 x float> %vecinit3.i
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef float @_Z17test_extract_elemDv16_fii(<16 x float> noundef %a, i32 noundef %b, i32 noundef %c) local_unnamed_addr  {
; CHECK-LABEL: _Z17test_extract_elemDv16_fii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; jl #__fixsfsi; nops
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    paddxm [sp], #64 // Delay Slot 4
; CHECK-NEXT:    st lr, [sp, #-64] // 4-byte Folded Spill Delay Slot 3
; CHECK-NEXT:    vextract.32 r1, x0, r1, vaddsign1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
; CHECK-NEXT:    lda lr, [sp, #-64]; nopb ; nops ; nopxm ; nopv // 4-byte Folded Reload
; CHECK-NEXT:    nopx
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    paddxm [sp], #-64 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %vecext.i.i = extractelement <16 x float> %a, i32 %b
  %conv.i = fptosi float %vecext.i.i to i32
  %0 = bitcast i32 %conv.i to float
  ret float %0
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <2 x float> @_Z20test_extract_v2floatDv16_fii(<16 x float> noundef %a, i32 noundef %b, i32 noundef %c) local_unnamed_addr  {
; CHECK-LABEL: _Z20test_extract_v2floatDv16_fii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; paddxm [sp], #64; nops
; CHECK-NEXT:    jl #__floatsisf
; CHECK-NEXT:    st r8, [sp, #-60] // 4-byte Folded Spill Delay Slot 5
; CHECK-NEXT:    st r10, [sp, #-56] // 4-byte Folded Spill Delay Slot 4
; CHECK-NEXT:    st lr, [sp, #-64]; add r0, r2, #1; vextract.32 r1, x0, r2, vaddsign1 // 4-byte Folded Spill Delay Slot 3
; CHECK-NEXT:    st r11, [sp, #-52]; vextract.32 r8, x0, r0, vaddsign1 // 4-byte Folded Spill Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
; CHECK-NEXT:    nopa ; nopb ; nops ; jl #__floatsisf; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    or r10, r0, r0; mov r1, r8 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
; CHECK-NEXT:    lda lr, [sp, #-64]; nopx // 4-byte Folded Reload
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    lda r10, [sp, #-56] // 4-byte Folded Reload
; CHECK-NEXT:    lda r8, [sp, #-60] // 4-byte Folded Reload
; CHECK-NEXT:    lda r11, [sp, #-52] // 4-byte Folded Reload
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    or r11, r0, r0; mov r0, r10 // Delay Slot 4
; CHECK-NEXT:    mov r1, r11 // Delay Slot 3
; CHECK-NEXT:    paddxm [sp], #-64 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <16 x float> %a to <16 x i32>
  %vecext.i.i.i = extractelement <16 x i32> %0, i32 %b
  %add.i.i = add nsw i32 %b, 1
  %vecext.i7.i.i = extractelement <16 x i32> %0, i32 %add.i.i
  %conv.i.i = sitofp i32 %vecext.i.i.i to float
  %vecinit.i.i = insertelement <2 x float> poison, float %conv.i.i, i64 0
  %conv2.i.i = sitofp i32 %vecext.i7.i.i to float
  %vecinit3.i.i = insertelement <2 x float> %vecinit.i.i, float %conv2.i.i, i64 1
  ret <2 x float> %vecinit3.i.i
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <2 x float> @_Z20test_extract_v2floatDv16_fi(<16 x float> noundef %a, i32 noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z20test_extract_v2floatDv16_fi:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; paddxm [sp], #64; nops
; CHECK-NEXT:    jl #__floatsisf
; CHECK-NEXT:    st r8, [sp, #-60] // 4-byte Folded Spill Delay Slot 5
; CHECK-NEXT:    st r10, [sp, #-56] // 4-byte Folded Spill Delay Slot 4
; CHECK-NEXT:    st lr, [sp, #-64]; add r0, r2, #1; vextract.32 r1, x0, r2, vaddsign1 // 4-byte Folded Spill Delay Slot 3
; CHECK-NEXT:    st r11, [sp, #-52]; vextract.32 r8, x0, r0, vaddsign1 // 4-byte Folded Spill Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
; CHECK-NEXT:    nopa ; nopb ; nops ; jl #__floatsisf; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    or r10, r0, r0; mov r1, r8 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
; CHECK-NEXT:    lda lr, [sp, #-64]; nopx // 4-byte Folded Reload
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    lda r10, [sp, #-56] // 4-byte Folded Reload
; CHECK-NEXT:    lda r8, [sp, #-60] // 4-byte Folded Reload
; CHECK-NEXT:    lda r11, [sp, #-52] // 4-byte Folded Reload
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    or r11, r0, r0; mov r0, r10 // Delay Slot 4
; CHECK-NEXT:    mov r1, r11 // Delay Slot 3
; CHECK-NEXT:    paddxm [sp], #-64 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <16 x float> %a to <16 x i32>
  %vecext.i.i.i.i = extractelement <16 x i32> %0, i32 %b
  %add.i.i.i = add nsw i32 %b, 1
  %vecext.i7.i.i.i = extractelement <16 x i32> %0, i32 %add.i.i.i
  %conv.i.i.i = sitofp i32 %vecext.i.i.i.i to float
  %vecinit.i.i.i = insertelement <2 x float> poison, float %conv.i.i.i, i64 0
  %conv2.i.i.i = sitofp i32 %vecext.i7.i.i.i to float
  %vecinit3.i.i.i = insertelement <2 x float> %vecinit.i.i.i, float %conv2.i.i.i, i64 1
  ret <2 x float> %vecinit3.i.i.i
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <2 x i32> @_Z15test_ext_mask64Dv64_DU8_ii(<64 x i8> noundef %v, i32 noundef %idx, i32 noundef %sign) local_unnamed_addr  {
; CHECK-LABEL: _Z15test_ext_mask64Dv64_DU8_ii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; ret lr; nopm
; CHECK-NEXT:    mova r1, #1 // Delay Slot 5
; CHECK-NEXT:    lshl r2, r2, r1 // Delay Slot 4
; CHECK-NEXT:    or r1, r2, r1; vextract.32 r0, x0, r2, vaddsign1 // Delay Slot 3
; CHECK-NEXT:    vextract.32 r1, x0, r1, vaddsign1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <64 x i8> %v to <16 x i32>
  %mul.i.i = shl nsw i32 %idx, 1
  %vecext.i.i = extractelement <16 x i32> %0, i32 %mul.i.i
  %vecinit.i.i = insertelement <2 x i32> poison, i32 %vecext.i.i, i64 0
  %add.i.i = or disjoint i32 %mul.i.i, 1
  %vecext1.i.i = extractelement <16 x i32> %0, i32 %add.i.i
  %vecinit2.i.i = insertelement <2 x i32> %vecinit.i.i, i32 %vecext1.i.i, i64 1
  ret <2 x i32> %vecinit2.i.i
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <2 x i32> @_Z15test_ext_mask64Dv64_hii(<64 x i8> noundef %v, i32 noundef %idx, i32 noundef %sign) local_unnamed_addr  {
; CHECK-LABEL: _Z15test_ext_mask64Dv64_hii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; ret lr; nopm
; CHECK-NEXT:    mova r1, #1 // Delay Slot 5
; CHECK-NEXT:    lshl r2, r2, r1 // Delay Slot 4
; CHECK-NEXT:    or r1, r2, r1; vextract.32 r0, x0, r2, vaddsign1 // Delay Slot 3
; CHECK-NEXT:    vextract.32 r1, x0, r1, vaddsign1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <64 x i8> %v to <16 x i32>
  %mul.i.i = shl nsw i32 %idx, 1
  %vecext.i.i = extractelement <16 x i32> %0, i32 %mul.i.i
  %vecinit.i.i = insertelement <2 x i32> poison, i32 %vecext.i.i, i64 0
  %add.i.i = or disjoint i32 %mul.i.i, 1
  %vecext1.i.i = extractelement <16 x i32> %0, i32 %add.i.i
  %vecinit2.i.i = insertelement <2 x i32> %vecinit.i.i, i32 %vecext1.i.i, i64 1
  ret <2 x i32> %vecinit2.i.i
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <2 x i32> @_Z15test_ext_mask64Dv32_sii(<32 x i16> noundef %v, i32 noundef %idx, i32 noundef %sign) local_unnamed_addr  {
; CHECK-LABEL: _Z15test_ext_mask64Dv32_sii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; ret lr; nopm
; CHECK-NEXT:    mova r1, #1 // Delay Slot 5
; CHECK-NEXT:    lshl r2, r2, r1 // Delay Slot 4
; CHECK-NEXT:    or r1, r2, r1; vextract.32 r0, x0, r2, vaddsign1 // Delay Slot 3
; CHECK-NEXT:    vextract.32 r1, x0, r1, vaddsign1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <32 x i16> %v to <16 x i32>
  %mul.i.i = shl nsw i32 %idx, 1
  %vecext.i.i = extractelement <16 x i32> %0, i32 %mul.i.i
  %vecinit.i.i = insertelement <2 x i32> poison, i32 %vecext.i.i, i64 0
  %add.i.i = or disjoint i32 %mul.i.i, 1
  %vecext1.i.i = extractelement <16 x i32> %0, i32 %add.i.i
  %vecinit2.i.i = insertelement <2 x i32> %vecinit.i.i, i32 %vecext1.i.i, i64 1
  ret <2 x i32> %vecinit2.i.i
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <2 x i32> @_Z15test_ext_mask64Dv16_iii(<16 x i32> noundef %v, i32 noundef %idx, i32 noundef %sign) local_unnamed_addr  {
; CHECK-LABEL: _Z15test_ext_mask64Dv16_iii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; ret lr; nopm
; CHECK-NEXT:    mova r1, #1 // Delay Slot 5
; CHECK-NEXT:    lshl r2, r2, r1 // Delay Slot 4
; CHECK-NEXT:    or r1, r2, r1; vextract.32 r0, x0, r2, vaddsign1 // Delay Slot 3
; CHECK-NEXT:    vextract.32 r1, x0, r1, vaddsign1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %mul.i.i = shl nsw i32 %idx, 1
  %vecext.i.i = extractelement <16 x i32> %v, i32 %mul.i.i
  %vecinit.i.i = insertelement <2 x i32> poison, i32 %vecext.i.i, i64 0
  %add.i.i = or disjoint i32 %mul.i.i, 1
  %vecext1.i.i = extractelement <16 x i32> %v, i32 %add.i.i
  %vecinit2.i.i = insertelement <2 x i32> %vecinit.i.i, i32 %vecext1.i.i, i64 1
  ret <2 x i32> %vecinit2.i.i
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <2 x i32> @_Z15test_ext_mask64Dv32_u6__bf16ii(<32 x bfloat> noundef %v, i32 noundef %idx, i32 noundef %sign) local_unnamed_addr  {
; CHECK-LABEL: _Z15test_ext_mask64Dv32_u6__bf16ii:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; ret lr; nopm
; CHECK-NEXT:    mova r1, #1 // Delay Slot 5
; CHECK-NEXT:    lshl r2, r2, r1 // Delay Slot 4
; CHECK-NEXT:    or r1, r2, r1; vextract.32 r0, x0, r2, vaddsign1 // Delay Slot 3
; CHECK-NEXT:    vextract.32 r1, x0, r1, vaddsign1 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <32 x bfloat> %v to <16 x i32>
  %mul.i.i = shl nsw i32 %idx, 1
  %vecext.i.i = extractelement <16 x i32> %0, i32 %mul.i.i
  %vecinit.i.i = insertelement <2 x i32> poison, i32 %vecext.i.i, i64 0
  %add.i.i = or disjoint i32 %mul.i.i, 1
  %vecext1.i.i = extractelement <16 x i32> %0, i32 %add.i.i
  %vecinit2.i.i = insertelement <2 x i32> %vecinit.i.i, i32 %vecext1.i.i, i64 1
  ret <2 x i32> %vecinit2.i.i
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local inreg noundef <16 x i32> @_Z12test_shuffleDv16_u7__acc32S_j(<16 x i32> inreg noundef %a, <16 x i32> inreg noundef %b, i32 noundef %c) local_unnamed_addr  {
; CHECK-LABEL: _Z12test_shuffleDv16_u7__acc32S_j:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    vmov x0, bmll1 // Delay Slot 4
; CHECK-NEXT:    vmov x2, bmll2 // Delay Slot 3
; CHECK-NEXT:    vshuffle bmll0, x0, x2, r0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call noundef <16 x i32> @llvm.aie2p.vshuffle(<16 x i32> %a, <16 x i32> %b, i32 %c)
  ret <16 x i32> %0
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local noundef <16 x i32> @_Z16test_shuffle_s64Dv2_jj(<2 x i32> noundef %b, i32 noundef %m) local_unnamed_addr  {
; CHECK-LABEL: _Z16test_shuffle_s64Dv2_jj:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mov r29, r2 // Delay Slot 3
; CHECK-NEXT:    vbcstshfl.64 x0, r1:r0, r29 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call noundef <16 x i32> @llvm.aie2p.vbcst.shuffle64(<2 x i32> %b, i32 %m)
  ret <16 x i32> %0
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local noundef <16 x i32> @_Z16test_shuffle_u64Dv2_jj(<2 x i32> noundef %b, i32 noundef %m) local_unnamed_addr  {
; CHECK-LABEL: _Z16test_shuffle_u64Dv2_jj:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    mov r29, r2 // Delay Slot 3
; CHECK-NEXT:    vbcstshfl.64 x0, r1:r0, r29 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = tail call noundef <16 x i32> @llvm.aie2p.vbcst.shuffle64(<2 x i32> %b, i32 %m)
  ret <16 x i32> %0
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <16 x i32> @_Z11test_insertDv16_iiDv2_j(<16 x i32> noundef %v, i32 noundef %idx, <2 x i32> noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z11test_insertDv16_iiDv2_j:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; ret lr; nopm
; CHECK-NEXT:    mova r1, #1 // Delay Slot 5
; CHECK-NEXT:    lshl r29, r0, r1 // Delay Slot 4
; CHECK-NEXT:    or r29, r29, r1; vinsert.32 x0, x2, r29, r2 // Delay Slot 3
; CHECK-NEXT:    vinsert.32 x0, x0, r29, r3 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %mul.i.i = shl nsw i32 %idx, 1
  %vecext.i.i = extractelement <2 x i32> %b, i64 0
  %vecins.i.i = insertelement <16 x i32> %v, i32 %vecext.i.i, i32 %mul.i.i
  %vecext1.i.i = extractelement <2 x i32> %b, i64 1
  %add.i.i = or disjoint i32 %mul.i.i, 1
  %vecins2.i.i = insertelement <16 x i32> %vecins.i.i, i32 %vecext1.i.i, i32 %add.i.i
  ret <16 x i32> %vecins2.i.i
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <64 x i8> @_Z11test_insertDv64_DU8_iDv2_j(<64 x i8> noundef %v, i32 noundef %idx, <2 x i32> noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z11test_insertDv64_DU8_iDv2_j:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; ret lr; nopm
; CHECK-NEXT:    mova r1, #1 // Delay Slot 5
; CHECK-NEXT:    lshl r29, r0, r1 // Delay Slot 4
; CHECK-NEXT:    or r29, r29, r1; vinsert.32 x0, x2, r29, r2 // Delay Slot 3
; CHECK-NEXT:    vinsert.32 x0, x0, r29, r3 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <64 x i8> %v to <16 x i32>
  %mul.i.i = shl nsw i32 %idx, 1
  %vecext.i.i = extractelement <2 x i32> %b, i64 0
  %vecins.i.i = insertelement <16 x i32> %0, i32 %vecext.i.i, i32 %mul.i.i
  %vecext1.i.i = extractelement <2 x i32> %b, i64 1
  %add.i.i = or disjoint i32 %mul.i.i, 1
  %vecins2.i.i = insertelement <16 x i32> %vecins.i.i, i32 %vecext1.i.i, i32 %add.i.i
  %1 = bitcast <16 x i32> %vecins2.i.i to <64 x i8>
  ret <64 x i8> %1
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <64 x i8> @_Z11test_insertDv64_hiDv2_j(<64 x i8> noundef %v, i32 noundef %idx, <2 x i32> noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z11test_insertDv64_hiDv2_j:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; ret lr; nopm
; CHECK-NEXT:    mova r1, #1 // Delay Slot 5
; CHECK-NEXT:    lshl r29, r0, r1 // Delay Slot 4
; CHECK-NEXT:    or r29, r29, r1; vinsert.32 x0, x2, r29, r2 // Delay Slot 3
; CHECK-NEXT:    vinsert.32 x0, x0, r29, r3 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <64 x i8> %v to <16 x i32>
  %mul.i.i = shl nsw i32 %idx, 1
  %vecext.i.i = extractelement <2 x i32> %b, i64 0
  %vecins.i.i = insertelement <16 x i32> %0, i32 %vecext.i.i, i32 %mul.i.i
  %vecext1.i.i = extractelement <2 x i32> %b, i64 1
  %add.i.i = or disjoint i32 %mul.i.i, 1
  %vecins2.i.i = insertelement <16 x i32> %vecins.i.i, i32 %vecext1.i.i, i32 %add.i.i
  %1 = bitcast <16 x i32> %vecins2.i.i to <64 x i8>
  ret <64 x i8> %1
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <32 x i16> @_Z11test_insertDv32_tiDv2_j(<32 x i16> noundef %v, i32 noundef %idx, <2 x i32> noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z11test_insertDv32_tiDv2_j:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; ret lr; nopm
; CHECK-NEXT:    mova r1, #1 // Delay Slot 5
; CHECK-NEXT:    lshl r29, r0, r1 // Delay Slot 4
; CHECK-NEXT:    or r29, r29, r1; vinsert.32 x0, x2, r29, r2 // Delay Slot 3
; CHECK-NEXT:    vinsert.32 x0, x0, r29, r3 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %0 = bitcast <32 x i16> %v to <16 x i32>
  %mul.i.i = shl nsw i32 %idx, 1
  %vecext.i.i = extractelement <2 x i32> %b, i64 0
  %vecins.i.i = insertelement <16 x i32> %0, i32 %vecext.i.i, i32 %mul.i.i
  %vecext1.i.i = extractelement <2 x i32> %b, i64 1
  %add.i.i = or disjoint i32 %mul.i.i, 1
  %vecins2.i.i = insertelement <16 x i32> %vecins.i.i, i32 %vecext1.i.i, i32 %add.i.i
  %1 = bitcast <16 x i32> %vecins2.i.i to <32 x i16>
  ret <32 x i16> %1
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef <64 x i8> @_Z25test_broadcast_to_v64int8i(i32 noundef %b) local_unnamed_addr  {
; CHECK-LABEL: _Z25test_broadcast_to_v64int8i:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vbcst.8 x0, r0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %conv.i = trunc i32 %b to i8
  %splat.splatinsert.i.i = insertelement <64 x i8> poison, i8 %conv.i, i64 0
  %splat.splat.i.i = shufflevector <64 x i8> %splat.splatinsert.i.i, <64 x i8> poison, <64 x i32> zeroinitializer
  ret <64 x i8> %splat.splat.i.i
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local inreg noundef <16 x float> @_Z34test_broadcast_zero_to_v16accfloatv() local_unnamed_addr  {
; CHECK-LABEL: _Z34test_broadcast_zero_to_v16accfloatv:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; nopv
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    mova r0, #0 // Delay Slot 4
; CHECK-NEXT:    vbcst.32 x0, r0 // Delay Slot 3
; CHECK-NEXT:    vmov bmll0, x0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  ret <16 x float> zeroinitializer
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local inreg noundef <32 x float> @_Z34test_broadcast_zero_to_v32accfloatv() local_unnamed_addr  {
; CHECK-LABEL: _Z34test_broadcast_zero_to_v32accfloatv:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; ret lr; nopm ; nops
; CHECK-NEXT:    mova r0, #0 // Delay Slot 5
; CHECK-NEXT:    vbcst.32 x0, r0 // Delay Slot 4
; CHECK-NEXT:    vmov bmll0, x0 // Delay Slot 3
; CHECK-NEXT:    vmov bmlh0, x0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  ret <32 x float> zeroinitializer
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local inreg noundef <64 x float> @_Z34test_broadcast_zero_to_v64accfloatv() local_unnamed_addr  {
; CHECK-LABEL: _Z34test_broadcast_zero_to_v64accfloatv:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    nopa ; nopb ; nops ; ret lr; nopm ; vclr dm0
; CHECK-NEXT:    nopa ; nopb ; nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  ret <64 x float> zeroinitializer
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local %struct.v64bfp16ebs8 @_Z12shuffle_test12v64bfp16ebs8S_j(%struct.v64bfp16ebs8 %a.coerce, %struct.v64bfp16ebs8 %b.coerce, i32 noundef %mode) local_unnamed_addr  {
; CHECK-LABEL: _Z12shuffle_test12v64bfp16ebs8S_j:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vshuffle ex0, ex2, ex4, r0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs8 %b.coerce, 1
  %0 = tail call { <64 x i8>, <8 x i8> } @llvm.aie2p.vshuffle.576.bfp16(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <8 x i8> %b.coerce.fca.1.extract.i, i32 %mode)
  %1 = extractvalue { <64 x i8>, <8 x i8> } %0, 0
  %2 = extractvalue { <64 x i8>, <8 x i8> } %0, 1
  %.fca.0.insert.i = insertvalue %struct.v64bfp16ebs8 poison, <64 x i8> %1, 0
  %.fca.1.insert.i = insertvalue %struct.v64bfp16ebs8 %.fca.0.insert.i, <8 x i8> %2, 1
  ret %struct.v64bfp16ebs8 %.fca.1.insert.i
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local %struct.v64bfp16ebs16 @_Z12shuffle_test13v64bfp16ebs16S_j(%struct.v64bfp16ebs16 %a.coerce, %struct.v64bfp16ebs16 %b.coerce, i32 noundef %mode) local_unnamed_addr  {
; CHECK-LABEL: _Z12shuffle_test13v64bfp16ebs16S_j:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vshuffle ex0, ex2, ex4, r0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs16 %a.coerce, 0
  %a.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs16 %a.coerce, 1
  %b.coerce.fca.0.extract.i = extractvalue %struct.v64bfp16ebs16 %b.coerce, 0
  %b.coerce.fca.1.extract.i = extractvalue %struct.v64bfp16ebs16 %b.coerce, 1
  %0 = tail call { <64 x i8>, <8 x i8> } @llvm.aie2p.vshuffle.576.bfp16(<64 x i8> %a.coerce.fca.0.extract.i, <8 x i8> %a.coerce.fca.1.extract.i, <64 x i8> %b.coerce.fca.0.extract.i, <8 x i8> %b.coerce.fca.1.extract.i, i32 %mode)
  %1 = extractvalue { <64 x i8>, <8 x i8> } %0, 0
  %2 = extractvalue { <64 x i8>, <8 x i8> } %0, 1
  %.fca.0.insert.i = insertvalue %struct.v64bfp16ebs16 poison, <64 x i8> %1, 0
  %.fca.1.insert.i = insertvalue %struct.v64bfp16ebs16 %.fca.0.insert.i, <8 x i8> %2, 1
  ret %struct.v64bfp16ebs16 %.fca.1.insert.i
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local %struct.v64bfp16ebs8 @_Z12shuffle_test12v64bfp16ebs8j(%struct.v64bfp16ebs8 %a.coerce, i32 noundef %mode) local_unnamed_addr  {
; CHECK-LABEL: _Z12shuffle_test12v64bfp16ebs8j:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vshuffle ex0, ex2, ex0, r0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 0
  %a.coerce.fca.1.extract.i.i = extractvalue %struct.v64bfp16ebs8 %a.coerce, 1
  %0 = tail call { <64 x i8>, <8 x i8> } @llvm.aie2p.vshuffle.576.bfp16(<64 x i8> %a.coerce.fca.0.extract.i.i, <8 x i8> %a.coerce.fca.1.extract.i.i, <64 x i8> undef, <8 x i8> undef, i32 %mode)
  %1 = extractvalue { <64 x i8>, <8 x i8> } %0, 0
  %2 = extractvalue { <64 x i8>, <8 x i8> } %0, 1
  %.fca.0.insert.i.i = insertvalue %struct.v64bfp16ebs8 poison, <64 x i8> %1, 0
  %.fca.1.insert.i.i = insertvalue %struct.v64bfp16ebs8 %.fca.0.insert.i.i, <8 x i8> %2, 1
  ret %struct.v64bfp16ebs8 %.fca.1.insert.i.i
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
define dso_local %struct.v64bfp16ebs16 @_Z12shuffle_test13v64bfp16ebs16j(%struct.v64bfp16ebs16 %a.coerce, i32 noundef %mode) local_unnamed_addr  {
; CHECK-LABEL: _Z12shuffle_test13v64bfp16ebs16j:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    vshuffle ex0, ex2, ex0, r0 // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
entry:
  %a.coerce.fca.0.extract.i.i = extractvalue %struct.v64bfp16ebs16 %a.coerce, 0
  %a.coerce.fca.1.extract.i.i = extractvalue %struct.v64bfp16ebs16 %a.coerce, 1
  %0 = tail call { <64 x i8>, <8 x i8> } @llvm.aie2p.vshuffle.576.bfp16(<64 x i8> %a.coerce.fca.0.extract.i.i, <8 x i8> %a.coerce.fca.1.extract.i.i, <64 x i8> undef, <8 x i8> undef, i32 %mode)
  %1 = extractvalue { <64 x i8>, <8 x i8> } %0, 0
  %2 = extractvalue { <64 x i8>, <8 x i8> } %0, 1
  %.fca.0.insert.i.i = insertvalue %struct.v64bfp16ebs16 poison, <64 x i8> %1, 0
  %.fca.1.insert.i.i = insertvalue %struct.v64bfp16ebs16 %.fca.0.insert.i.i, <8 x i8> %2, 1
  ret %struct.v64bfp16ebs16 %.fca.1.insert.i.i
}

; Function Attrs: nofree nosync nounwind memory(none)
declare <16 x i32> @llvm.aie2p.vextract.broadcast128.I512(<16 x i32>, i32)

; Function Attrs: nofree nosync nounwind memory(none)
declare <32 x bfloat> @llvm.aie2p.vinsert32.bf512(<32 x bfloat>, i32, <2 x bfloat>)

; Function Attrs: nofree nosync nounwind memory(none)
declare <32 x bfloat> @llvm.aie2p.vinsert64.bf512(<32 x bfloat>, i32, <4 x bfloat>)

; Function Attrs: nofree nosync nounwind memory(none)
declare <16 x i32> @llvm.aie2p.vshift.I512.I512(<16 x i32>, <16 x i32>, i32, i32)

; Function Attrs: nofree nosync nounwind memory(none)
declare <16 x i32> @llvm.aie2p.vshuffle(<16 x i32>, <16 x i32>, i32)

; Function Attrs: nofree nosync nounwind memory(none)
declare <16 x i32> @llvm.aie2p.vbcst.shuffle64(<2 x i32>, i32)

; Function Attrs: nofree nosync nounwind memory(none)
declare { <64 x i8>, <8 x i8> } @llvm.aie2p.vshuffle.576.bfp16(<64 x i8>, <8 x i8>, <64 x i8>, <8 x i8>, i32)
