# NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -verify-machineinstrs --mtriple=aie2ps -O2 \
# RUN:     --start-before=postmisched %s \
# RUN:     --aie-postpipeliner-vreg-mode=1 \
# RUN:     --aie-postpipeliner-phys-mode=0 \
# RUN:     -o - | FileCheck %s

# The loop contains two scarce-register live ranges on the same physical
# register (dj3):
#
#   Range A:  $dj3 = MOV ...    ; def  (NodeNum=N)
#             $r28 = LDA $dj3   ; use  (NodeNum=N+1)
#   Range B:  $dj3 = MOV ...    ; def  (NodeNum=N+2)
#             $r30 = LDA $dj3   ; use  (NodeNum=N+3)
#
# The anti-dependence from Range A's use (NodeNum=N+1) to Range B's def
# (NodeNum=N+2) is intra-iteration because the def topologically follows the
# use.  The anti-dependence from Range B's use (NodeNum=N+3) to Range A's def
# (NodeNum=N) is loop-carried because the def topologically precedes the use;
# the scheduler must subtract II to express the first-iteration constraint.
#
# Before the fix (commit 39280a39dab5) simulateAntiDependences only considered
# ranges that followed the current burst in the permutation order, so the
# loop-carried anti-dep from Range B's use to Range A's def was never enforced.
# This allowed Range A's def to be placed too early, interleaving the two live
# ranges and producing an incorrect schedule that -verify-machineinstrs would
# catch.

--- |
  target triple = "aie2ps"

  define void @test(ptr addrspace(5) noalias %p0, ptr addrspace(6) noalias %p1,
  ; CHECK-LABEL: test:
  ; CHECK:       // %bb.0: // %entry
  ; CHECK-NEXT:    nopa ; add.nc lc, r0, #-3; nopm
  ; CHECK-NEXT:    movxm ls, #.LBB0_1
  ; CHECK-NEXT:    movxm le, #.L_LEnd0
  ; CHECK-NEXT:    lshl r28, r4, r24
  ; CHECK-NEXT:    movs dj3, r28; add r28, r28, r26
  ; CHECK-NEXT:    lda.s16 r28, [p3, dj3]; add r4, r4, #-1; mov dj3, r28
  ; CHECK-NEXT:    lda.s16 r30, [p6, dj3]; lshl r28, r4, r24
  ; CHECK-NEXT:    movs dj3, r28; add r28, r28, r26
  ; CHECK-NEXT:    lda.s16 r28, [p3, dj3]; add r4, r4, #-1; mov dj3, r28
  ; CHECK-NEXT:    lda.s16 r30, [p6, dj3]; lshl r28, r4, r24
  ; CHECK-NEXT:    movs dj3, r28; add r28, r28, r26
  ; CHECK-NEXT:    lda.s16 r28, [p3, dj3]; add r4, r4, #-1; mov dj3, r28
  ; CHECK-NEXT:    lda.s16 r30, [p6, dj3]; lshl r28, r4, r24; vbcst.16 x0, r28
  ; CHECK-NEXT:    .p2align 4
  ; CHECK-NEXT:  .LBB0_1: // %loop
  ; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
  ; CHECK-NEXT:    nopa ; nopb ; movs dj3, r28; add r28, r28, r26; vbcst.16 x2, r30; nopv
  ; CHECK-NEXT:    lda.s16 r28, [p3, dj3]; nopb ; vst x0, [p2], #64; add r4, r4, #-1; mov dj3, r28; nopv
  ; CHECK-NEXT:  .L_LEnd0:
  ; CHECK-NEXT:    lda.s16 r30, [p6, dj3]; nopb ; vst x2, [p1], #64; lshl r28, r4, r24; vbcst.16 x0, r28; nopv
  ; CHECK-NEXT:    .p2align 4
  ; CHECK-NEXT:  // %bb.2: // %exit
  ; CHECK-NEXT:    vbcst.16 x2, r30
  ; CHECK-NEXT:    vst x0, [p2], #64
  ; CHECK-NEXT:    vst x2, [p1], #64; vbcst.16 x0, r28
  ; CHECK-NEXT:    vbcst.16 x2, r30
  ; CHECK-NEXT:    vst x0, [p2], #64; ret lr
  ; CHECK-NEXT:    vst x2, [p1], #64; vbcst.16 x0, r28 // Delay Slot 5
  ; CHECK-NEXT:    vbcst.16 x2, r30 // Delay Slot 4
  ; CHECK-NEXT:    vst x0, [p2], #64 // Delay Slot 3
  ; CHECK-NEXT:    vst x2, [p1], #64 // Delay Slot 2
  ; CHECK-NEXT:    nop // Delay Slot 1
                    i32 %n) {
  entry:
    br label %loop

  loop:
    %pa = phi ptr addrspace(5) [ %p0, %entry ], [ %pa.next, %loop ]
    %pb = phi ptr addrspace(6) [ %p1, %entry ], [ %pb.next, %loop ]
    %da = load <8 x i32>, ptr addrspace(5) %pa, align 64
    %pa.next = getelementptr inbounds i8, ptr addrspace(5) %pa, i32 64
    store <8 x i32> %da, ptr addrspace(6) %pb, align 64
    %pb.next = getelementptr inbounds i8, ptr addrspace(6) %pb, i32 64
    %deca = call i1 @llvm.loop.decrement.i32(i32 1)
    br i1 %deca, label %loop, label %exit, !llvm.loop !0

  exit:
    ret void
  }

  declare void @llvm.set.loop.iterations.i32(i32)
  declare i1 @llvm.loop.decrement.i32(i32)

  !0 = distinct !{!0, !1}
  !1 = !{!"llvm.loop.itercount.range", i64 4}
...
---
name:            test
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry:
    successors: %bb.1
    liveins: $r0, $r4, $r24, $r26, $p1, $p2, $p3, $p6

    $lc = ADD_NC_add_lc_ri $r0, 0
    MOVXM_lng_cg_ls_abs %bb.1, implicit-def $ls
    MOVXM_lng_cg_le_abs <mcsymbol .L_LEnd0>, implicit-def $le

  bb.1.loop (align 16):
    successors: %bb.1, %bb.2
    liveins: $dj0, $dj1, $dj2, $m0, $p0, $p1, $p2, $p3, $p4, $p5, $p6, $p7, $r0, $r2, $r3, $r4, $r5, $r6, $r8, $r16, $r18, $r20, $r22, $r24, $r26, $r27

    renamable $r28 = LSHL renamable $r4, renamable $r24
    renamable $r30 = ADD_alu_r_rr renamable $r28, renamable $r26, implicit-def dead $srcarry
    $dj3 = MOV_scalar_pseudo killed $r28
    renamable $r28 = LDA_s16_idx renamable $p3, killed renamable $dj3 :: (invariant load (s16) from %ir.pa)
    $dj3 = MOV_scalar_pseudo killed $r30
    renamable $r30 = LDA_s16_idx renamable $p6, killed renamable $dj3 :: (invariant load (s16) from %ir.pa)
    renamable $x0 = VBCST_16 killed renamable $r28
    renamable $x2 = VBCST_16 killed renamable $r30
    renamable $p2 = VST_dmx_sts_x_st_pstm_nrm_imm killed renamable $x0, killed renamable $p2, 64 :: (store (<32 x s16>) into %ir.pb, addrspace 6)
    renamable $p1 = VST_dmx_sts_x_st_pstm_nrm_imm killed renamable $x2, killed renamable $p1, 64:: (store (<32 x s16>) into %ir.pb, addrspace 6)
    renamable $r4 = nsw ADD_add_r_ri killed renamable $r4, -1, implicit-def dead $srcarry
    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.1

  bb.2.exit (align 16):
    RET implicit $lr
    DelayedSchedBarrier
...
