; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
;
; RUN: llc -mtriple=aie2p -O2 -aie-enable-outer-loop-pipelining \
; RUN:     -stop-after=irtranslator \
; RUN:     -o - %s 2>&1 | FileCheck %s


; RUN: llc -mtriple=aie2p -O2 -aie-enable-outer-loop-pipelining \
; RUN:     -stop-after=aie-outer-loop-pipeliner -o - %s \
; RUN:   | llc -mtriple=aie2p -x mir -run-pass=none -o /dev/null

; Test for the AIE Outer Loop Pipelining pass with GEP instructions.
;
; This tests that address computation instructions (GEPs) between PHI pointers
; and loads are correctly identified as part of the data-load chain and are
; included in the peel and epilogue clones.
;
; Input structure:
;   %a.ptr = phi ptr [...]
;   %a.gep = getelementptr i32, ptr %a.ptr, i32 %offset   ; GEP between PHI and load
;   %v0 = load i32, ptr %a.gep
;
; Expected after transformation:
;   - Peel: GEP cloned with initial PHI values, load uses cloned GEP
;   - Outer header: pipelined PHIs for both GEPs and loads
;   - Epilogue: GEP cloned with next-iteration pointers, load uses cloned GEP
;
; Note: The -O2 optimization level runs LSR which transforms the inner loop,
; but the key transformation (GEPs being pipelined) is still verified.


; Peel block: GEPs + loads cloned with initial values (using %a, %b)

; Outer header: pipelined PHIs for GEPs and loads

; Outer latch: stores + GEPs + loads for NEXT iteration (uses a.ptr.next, b.ptr.next)

; Cool-down (last iteration) blocks follow the steady loop.
; Last-iteration entry: set.loop.iterations for last iteration

; Last-iteration exit: stores only (no prologue GEPs, no prologue loads)

define void @nested_loop_with_gep(ptr noalias %a, ptr noalias %b, ptr noalias %c,
  ; CHECK-LABEL: name: nested_loop_with_gep
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.10(0x40000000)
  ; CHECK-NEXT:   liveins: $p0, $p1, $p2, $r0, $r1, $r2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(p0) = COPY $p1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(p0) = COPY $p2
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(s32) = COPY $r0
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(s32) = COPY $r2
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(sgt), [[COPY3]](s32), [[C]]
  ; CHECK-NEXT:   G_BRCOND [[ICMP]](s1), %bb.2
  ; CHECK-NEXT:   G_BR %bb.10
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.outer.header.preheader:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.stage0.top:
  ; CHECK-NEXT:   successors: %bb.4(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s20) = G_TRUNC [[COPY5]](s32)
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
  ; CHECK-NEXT:   [[MUL:%[0-9]+]]:_(s20) = G_MUL [[TRUNC]], [[C2]]
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[MUL]](s20)
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(p0) = COPY [[PTR_ADD]](p0)
  ; CHECK-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY1]], [[MUL]](s20)
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(p0) = COPY [[PTR_ADD1]](p0)
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY6]](p0) :: (load (s32) from %ir.a.gep.steady.peel)
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[COPY7]](p0) :: (load (s32) from %ir.b.gep.steady.peel)
  ; CHECK-NEXT:   [[MUL1:%[0-9]+]]:_(s32) = G_MUL [[LOAD]], [[LOAD1]]
  ; CHECK-NEXT:   [[SUB:%[0-9]+]]:_(s32) = G_SUB [[COPY3]], [[C]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4.steady.stage1.top:
  ; CHECK-NEXT:   successors: %bb.5(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:_(s32) = G_PHI %35(s32), %bb.6, [[C1]](s32), %bb.3
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:_(p0) = G_PHI %29(p0), %bb.6, [[COPY]](p0), %bb.3
  ; CHECK-NEXT:   [[PHI2:%[0-9]+]]:_(p0) = G_PHI %30(p0), %bb.6, [[COPY1]](p0), %bb.3
  ; CHECK-NEXT:   [[PHI3:%[0-9]+]]:_(p0) = G_PHI %31(p0), %bb.6, [[COPY2]](p0), %bb.3
  ; CHECK-NEXT:   [[PHI4:%[0-9]+]]:_(p0) = G_PHI [[COPY6]](p0), %bb.3, %41(p0), %bb.6
  ; CHECK-NEXT:   [[PHI5:%[0-9]+]]:_(p0) = G_PHI [[COPY7]](p0), %bb.3, %43(p0), %bb.6
  ; CHECK-NEXT:   [[PHI6:%[0-9]+]]:_(s32) = G_PHI [[LOAD]](s32), %bb.3, %44(s32), %bb.6
  ; CHECK-NEXT:   [[PHI7:%[0-9]+]]:_(s32) = G_PHI [[LOAD1]](s32), %bb.3, %45(s32), %bb.6
  ; CHECK-NEXT:   [[PHI8:%[0-9]+]]:_(s32) = G_PHI [[MUL1]](s32), %bb.3, %46(s32), %bb.6
  ; CHECK-NEXT:   G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.set.loop.iterations), [[COPY4]](s32)
  ; CHECK-NEXT:   [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
  ; CHECK-NEXT:   %29:_(p0) = nuw nusw G_PTR_ADD [[PHI1]], [[C3]](s20)
  ; CHECK-NEXT:   %30:_(p0) = nuw nusw G_PTR_ADD [[PHI2]], [[C3]](s20)
  ; CHECK-NEXT:   %31:_(p0) = nuw nusw G_PTR_ADD [[PHI3]], [[C3]](s20)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5.steady.stage1.inner.inner.header:
  ; CHECK-NEXT:   successors: %bb.5(0x7c000000), %bb.6(0x04000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI9:%[0-9]+]]:_(s32) = G_PHI %34(s32), %bb.5, [[C1]](s32), %bb.4
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(s1) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.loop.decrement), [[C]](s32)
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:_(s32) = G_ADD [[PHI9]], [[PHI8]]
  ; CHECK-NEXT:   G_BRCOND [[INT]](s1), %bb.5
  ; CHECK-NEXT:   G_BR %bb.6
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6.steady.stage1.bottom.and.stage0.top:
  ; CHECK-NEXT:   successors: %bb.4(0x7c000000), %bb.7(0x04000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   G_STORE [[ADD]](s32), [[PHI3]](p0) :: (store (s32) into %ir.c.ptr.steady)
  ; CHECK-NEXT:   [[ADD1:%[0-9]+]]:_(s32) = G_ADD [[PHI]], [[C]]
  ; CHECK-NEXT:   [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(slt), [[ADD1]](s32), [[SUB]]
  ; CHECK-NEXT:   [[TRUNC1:%[0-9]+]]:_(s20) = G_TRUNC [[COPY5]](s32)
  ; CHECK-NEXT:   [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
  ; CHECK-NEXT:   [[MUL2:%[0-9]+]]:_(s20) = G_MUL [[TRUNC1]], [[C4]]
  ; CHECK-NEXT:   [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD %29, [[MUL2]](s20)
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(p0) = COPY [[PTR_ADD2]](p0)
  ; CHECK-NEXT:   [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD %30, [[MUL2]](s20)
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:_(p0) = COPY [[PTR_ADD3]](p0)
  ; CHECK-NEXT:   [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[COPY8]](p0) :: (load (s32) from %ir.a.gep.steady.epi)
  ; CHECK-NEXT:   [[LOAD3:%[0-9]+]]:_(s32) = G_LOAD [[COPY9]](p0) :: (load (s32) from %ir.b.gep.steady.epi)
  ; CHECK-NEXT:   [[MUL3:%[0-9]+]]:_(s32) = G_MUL [[LOAD2]], [[LOAD3]]
  ; CHECK-NEXT:   G_BRCOND [[ICMP1]](s1), %bb.4
  ; CHECK-NEXT:   G_BR %bb.7
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.7.lastiter.stage1.top:
  ; CHECK-NEXT:   successors: %bb.8(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.set.loop.iterations), [[COPY4]](s32)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.8.lastiter.stage1.inner.inner.header:
  ; CHECK-NEXT:   successors: %bb.8(0x7c000000), %bb.9(0x04000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI10:%[0-9]+]]:_(s32) = G_PHI %49(s32), %bb.8, [[C1]](s32), %bb.7
  ; CHECK-NEXT:   [[INT1:%[0-9]+]]:_(s1) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.loop.decrement), [[C]](s32)
  ; CHECK-NEXT:   [[ADD2:%[0-9]+]]:_(s32) = G_ADD [[PHI10]], [[MUL3]]
  ; CHECK-NEXT:   G_BRCOND [[INT1]](s1), %bb.8
  ; CHECK-NEXT:   G_BR %bb.9
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.9.lastiter.stage1.bottom:
  ; CHECK-NEXT:   successors: %bb.10(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   G_STORE [[ADD2]](s32), %31(p0) :: (store (s32) into %ir.c.ptr.next.steady)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.10.exit:
  ; CHECK-NEXT:   PseudoRET implicit $lr
                                   i32 %N, i32 %M, i32 %offset) {
entry:
  %cmp.outer = icmp sgt i32 %N, 1
  br i1 %cmp.outer, label %outer.header, label %exit

outer.header:
  %i = phi i32 [ 0, %entry ], [ %i.next, %outer.latch ]
  %a.ptr = phi ptr [ %a, %entry ], [ %a.ptr.next, %outer.latch ]
  %b.ptr = phi ptr [ %b, %entry ], [ %b.ptr.next, %outer.latch ]
  %c.ptr = phi ptr [ %c, %entry ], [ %c.ptr.next, %outer.latch ]
  %a.gep = getelementptr inbounds i32, ptr %a.ptr, i32 %offset
  %b.gep = getelementptr inbounds i32, ptr %b.ptr, i32 %offset
  %v0 = load i32, ptr %a.gep, align 4
  %v1 = load i32, ptr %b.gep, align 4
  call void @llvm.set.loop.iterations.i32(i32 %M)
  br label %inner.header

inner.header:
  %acc = phi i32 [ 0, %outer.header ], [ %acc.next, %inner.header ]
  %prod = mul i32 %v0, %v1
  %acc.next = add i32 %acc, %prod
  %inner.cond = call i1 @llvm.loop.decrement.i32(i32 1)
  br i1 %inner.cond, label %inner.header, label %outer.latch, !llvm.loop !1

outer.latch:
  store i32 %acc.next, ptr %c.ptr, align 4
  %a.ptr.next = getelementptr inbounds i32, ptr %a.ptr, i32 1
  %b.ptr.next = getelementptr inbounds i32, ptr %b.ptr, i32 1
  %c.ptr.next = getelementptr inbounds i32, ptr %c.ptr, i32 1
  %i.next = add i32 %i, 1
  %outer.cond = icmp slt i32 %i.next, %N
  br i1 %outer.cond, label %outer.header, label %exit, !llvm.loop !0

exit:
  ret void
}

declare void @llvm.set.loop.iterations.i32(i32)
declare i1 @llvm.loop.decrement.i32(i32)

!0 = distinct !{!0, !2, !3}
!1 = distinct !{!1, !2}
!2 = !{!"llvm.loop.mustprogress"}
!3 = !{!"llvm.loop.itercount.range", i32 2}
