; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
;
; RUN: llc -mtriple=aie2p -O2 -aie-enable-outer-loop-pipelining \
; RUN:     -aie-outer-loop-pipelining-split-prologue \
; RUN:     -stop-after=irtranslator \
; RUN:     -o - %s 2>&1 | FileCheck %s

; Test for split-prologue mode of the AIE Outer Loop Pipeliner.
;
; The prologue contains a 2048-bit-producing call (the "anchor") fed by two
; loads. The pass splits the prologue into Part 1 (the loads, which are
; pipelined) and Part 2 (the anchor + its descendants, which stay in
; outer.header and are cloned into lastiter.stage1.top for the last iteration).
;
; Expected structure after transformation:
;
;   [outer.header.peel.pro]  <- peel: Part-1 loads only, no anchor call
;   [outer.header]           <- PHIs for pipelined loads + anchor call remains
;   [outer.latch]            <- Part-1 epilogue loads for next iteration
;   [lastiter.stage1.top]         <- anchor call cloned (uses epilogue loads)
;   [inner.header.lastiter / lastiter.stage1.bottom]  <- cloned inner loop + final store


; Peel: Part-1 loads only -- anchor call and set.loop.iterations absent

; Outer header: pipelined PHIs for the loads, anchor call stays, set.loop.iter stays

; Outer latch: epilogue loads for next iteration, no anchor call

; Cool-down (last iteration) blocks follow the steady loop.
; Last-iteration entry: anchor cloned using epilogue loads + set.loop.iterations

; Cloned inner loop: uses last-iteration accumulator

; Last-iteration exit: store only, no loads

declare <32 x i64> @llvm.aie2p.I512.I512.ACC2048.mul.conf(<16 x i32>, <32 x i16>, i32) #0
declare void @llvm.set.loop.iterations.i32(i32)
declare i1 @llvm.loop.decrement.i32(i32)

define void @split_prologue_basic(ptr noalias %a_ptr_init,
  ; CHECK-LABEL: name: split_prologue_basic
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.10(0x40000000)
  ; CHECK-NEXT:   liveins: $p0, $p1, $p2, $r0, $r1, $r2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(p0) = COPY $p1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(p0) = COPY $p2
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(s32) = COPY $r0
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(s32) = COPY $r1
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(s32) = COPY $r2
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(sgt), [[COPY3]](s32), [[C]]
  ; CHECK-NEXT:   G_BRCOND [[ICMP]](s1), %bb.2
  ; CHECK-NEXT:   G_BR %bb.10
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.outer.header.preheader:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.stage0.top:
  ; CHECK-NEXT:   successors: %bb.4(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[COPY]](p0) :: (load (<16 x s32>) from %ir.a_ptr_init)
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(<32 x s16>) = G_LOAD [[COPY1]](p0) :: (load (<32 x s16>) from %ir.b_ptr_init)
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
  ; CHECK-NEXT:   %11:_(p0) = nuw nusw G_PTR_ADD [[COPY]], [[C2]](s20)
  ; CHECK-NEXT:   %12:_(p0) = nuw nusw G_PTR_ADD [[COPY1]], [[C2]](s20)
  ; CHECK-NEXT:   [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
  ; CHECK-NEXT:   %14:_(p0) = nuw nusw G_PTR_ADD [[COPY2]], [[C3]](s20)
  ; CHECK-NEXT:   [[SUB:%[0-9]+]]:_(s32) = G_SUB [[COPY3]], [[C]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4.steady.stage1.top:
  ; CHECK-NEXT:   successors: %bb.5(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:_(s32) = G_PHI %32(s32), %bb.6, [[C1]](s32), %bb.3
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:_(p0) = G_PHI %22(p0), %bb.6, [[COPY]](p0), %bb.3
  ; CHECK-NEXT:   [[PHI2:%[0-9]+]]:_(p0) = G_PHI %23(p0), %bb.6, [[COPY1]](p0), %bb.3
  ; CHECK-NEXT:   [[PHI3:%[0-9]+]]:_(p0) = G_PHI %24(p0), %bb.6, [[COPY2]](p0), %bb.3
  ; CHECK-NEXT:   [[PHI4:%[0-9]+]]:_(<16 x s32>) = G_PHI [[LOAD]](<16 x s32>), %bb.3, %34(<16 x s32>), %bb.6
  ; CHECK-NEXT:   [[PHI5:%[0-9]+]]:_(<32 x s16>) = G_PHI [[LOAD1]](<32 x s16>), %bb.3, %35(<32 x s16>), %bb.6
  ; CHECK-NEXT:   [[PHI6:%[0-9]+]]:_(p0) = G_PHI %11(p0), %bb.3, %37(p0), %bb.6
  ; CHECK-NEXT:   [[PHI7:%[0-9]+]]:_(p0) = G_PHI %12(p0), %bb.3, %38(p0), %bb.6
  ; CHECK-NEXT:   [[PHI8:%[0-9]+]]:_(p0) = G_PHI %14(p0), %bb.3, %40(p0), %bb.6
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I512.I512.ACC2048.mul.conf), [[PHI4]](<16 x s32>), [[PHI5]](<32 x s16>), [[COPY5]](s32)
  ; CHECK-NEXT:   G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.set.loop.iterations), [[COPY4]](s32)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5.steady.stage1.inner.inner.header:
  ; CHECK-NEXT:   successors: %bb.5(0x7c000000), %bb.6(0x04000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI9:%[0-9]+]]:_(s32) = G_PHI [[C1]](s32), %bb.4, %30(s32), %bb.5
  ; CHECK-NEXT:   [[EVEC:%[0-9]+]]:_(s64) = G_EXTRACT_VECTOR_ELT [[INT]](<32 x s64>), [[C1]](s32)
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s32) = G_TRUNC [[EVEC]](s64)
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:_(s32) = G_ADD [[PHI9]], [[TRUNC]]
  ; CHECK-NEXT:   [[INT1:%[0-9]+]]:_(s1) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.loop.decrement), [[C]](s32)
  ; CHECK-NEXT:   G_BRCOND [[INT1]](s1), %bb.5
  ; CHECK-NEXT:   G_BR %bb.6
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6.steady.stage1.bottom.and.stage0.top:
  ; CHECK-NEXT:   successors: %bb.4(0x7c000000), %bb.7(0x04000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   G_STORE [[ADD]](s32), [[PHI3]](p0) :: (store (s32) into %ir.c_ptr.steady)
  ; CHECK-NEXT:   [[ADD1:%[0-9]+]]:_(s32) = G_ADD [[PHI]], [[C]]
  ; CHECK-NEXT:   [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(slt), [[ADD1]](s32), [[SUB]]
  ; CHECK-NEXT:   [[LOAD2:%[0-9]+]]:_(<16 x s32>) = G_LOAD [[PHI6]](p0) :: (load (<16 x s32>) from %ir.a_ptr.next.steady.phi)
  ; CHECK-NEXT:   [[LOAD3:%[0-9]+]]:_(<32 x s16>) = G_LOAD [[PHI7]](p0) :: (load (<32 x s16>) from %ir.b_ptr.next.steady.phi)
  ; CHECK-NEXT:   [[C4:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
  ; CHECK-NEXT:   %37:_(p0) = nuw nusw G_PTR_ADD [[PHI6]], [[C4]](s20)
  ; CHECK-NEXT:   %38:_(p0) = nuw nusw G_PTR_ADD [[PHI7]], [[C4]](s20)
  ; CHECK-NEXT:   [[C5:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
  ; CHECK-NEXT:   %40:_(p0) = nuw nusw G_PTR_ADD [[PHI8]], [[C5]](s20)
  ; CHECK-NEXT:   G_BRCOND [[ICMP1]](s1), %bb.4
  ; CHECK-NEXT:   G_BR %bb.7
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.7.lastiter.stage1.top:
  ; CHECK-NEXT:   successors: %bb.8(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.set.loop.iterations), [[COPY4]](s32)
  ; CHECK-NEXT:   [[INT2:%[0-9]+]]:_(<32 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2p.I512.I512.ACC2048.mul.conf), [[LOAD2]](<16 x s32>), [[LOAD3]](<32 x s16>), [[COPY5]](s32)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.8.lastiter.stage1.inner.inner.header:
  ; CHECK-NEXT:   successors: %bb.8(0x7c000000), %bb.9(0x04000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI10:%[0-9]+]]:_(s32) = G_PHI [[C1]](s32), %bb.7, %45(s32), %bb.8
  ; CHECK-NEXT:   [[EVEC1:%[0-9]+]]:_(s64) = G_EXTRACT_VECTOR_ELT [[INT2]](<32 x s64>), [[C1]](s32)
  ; CHECK-NEXT:   [[TRUNC1:%[0-9]+]]:_(s32) = G_TRUNC [[EVEC1]](s64)
  ; CHECK-NEXT:   [[ADD2:%[0-9]+]]:_(s32) = G_ADD [[PHI10]], [[TRUNC1]]
  ; CHECK-NEXT:   [[INT3:%[0-9]+]]:_(s1) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.loop.decrement), [[C]](s32)
  ; CHECK-NEXT:   G_BRCOND [[INT3]](s1), %bb.8
  ; CHECK-NEXT:   G_BR %bb.9
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.9.lastiter.stage1.bottom:
  ; CHECK-NEXT:   successors: %bb.10(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   G_STORE [[ADD2]](s32), [[PHI8]](p0) :: (store (s32) into %ir.c_ptr.next.steady.phi)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.10.exit:
  ; CHECK-NEXT:   PseudoRET implicit $lr
                                   ptr noalias %b_ptr_init,
                                   ptr noalias %c_ptr_init,
                                   i32 %N, i32 %M, i32 %conf) {
entry:
  %cmp.outer = icmp sgt i32 %N, 1
  br i1 %cmp.outer, label %outer.header, label %exit

outer.header:
  %i       = phi i32  [ 0,           %entry      ], [ %i.next,     %outer.latch ]
  %a_ptr   = phi ptr  [ %a_ptr_init, %entry      ], [ %a_ptr.next, %outer.latch ]
  %b_ptr   = phi ptr  [ %b_ptr_init, %entry      ], [ %b_ptr.next, %outer.latch ]
  %c_ptr   = phi ptr  [ %c_ptr_init, %entry      ], [ %c_ptr.next, %outer.latch ]
  %a_loaded = load <16 x i32>, ptr %a_ptr, align 64
  %b_loaded = load <32 x i16>, ptr %b_ptr, align 64
  %acc = call <32 x i64> @llvm.aie2p.I512.I512.ACC2048.mul.conf(
             <16 x i32> %a_loaded, <32 x i16> %b_loaded, i32 %conf)
  call void @llvm.set.loop.iterations.i32(i32 %M)
  br label %inner.header

inner.header:
  %result = phi i32 [ 0, %outer.header ], [ %result.next, %inner.header ]
  %lane = extractelement <32 x i64> %acc, i32 0
  %lane.trunc = trunc i64 %lane to i32
  %result.next = add i32 %result, %lane.trunc
  %inner.cond = call i1 @llvm.loop.decrement.i32(i32 1)
  br i1 %inner.cond, label %inner.header, label %outer.latch, !llvm.loop !1

outer.latch:
  store i32 %result.next, ptr %c_ptr, align 4
  %a_ptr.next = getelementptr inbounds <16 x i32>, ptr %a_ptr, i32 1
  %b_ptr.next = getelementptr inbounds <32 x i16>, ptr %b_ptr, i32 1
  %c_ptr.next = getelementptr inbounds i32, ptr %c_ptr, i32 1
  %i.next = add i32 %i, 1
  %outer.cond = icmp slt i32 %i.next, %N
  br i1 %outer.cond, label %outer.header, label %exit, !llvm.loop !0

exit:
  ret void
}

attributes #0 = { nocallback nofree nosync nounwind willreturn memory(none) }

!0 = distinct !{!0, !2, !3}
!1 = distinct !{!1, !2}
!2 = !{!"llvm.loop.mustprogress"}
!3 = !{!"llvm.loop.itercount.range", i32 2}
