# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2026 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=aie-postlegalizer-custom-combiner -verify-machineinstrs -o - %s | FileCheck %s

# AIE2 maxVecBitSize=1024: split 1024-bit concat+stores into two 512-bit stores.

---
name:            split_concat_store_1024
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0, $x0, $x2
    ; CHECK-LABEL: name: split_concat_store_1024
    ; CHECK: liveins: $p0, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<16 x s32>) = COPY $x2
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<8 x s32>), [[UV1:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[COPY2]](<16 x s32>)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; CHECK-NEXT: G_STORE [[UV1]](<8 x s32>), [[PTR_ADD1]](p0) :: (store (<8 x s32>) into unknown-address + 96)
    ; CHECK-NEXT: G_STORE [[UV]](<8 x s32>), [[PTR_ADD]](p0) :: (store (<8 x s32>) into unknown-address + 64, align 64)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(<8 x s32>), [[UV3:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[COPY1]](<16 x s32>)
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; CHECK-NEXT: G_STORE [[UV3]](<8 x s32>), [[PTR_ADD2]](p0) :: (store (<8 x s32>) into unknown-address + 32)
    ; CHECK-NEXT: G_STORE [[UV2]](<8 x s32>), [[COPY]](p0) :: (store (<8 x s32>), align 128)
    %0:_(p0) = COPY $p0
    %1:_(<16 x s32>) = COPY $x0
    %2:_(<16 x s32>) = COPY $x2
    %3:_(<32 x s32>) = G_CONCAT_VECTORS %1(<16 x s32>), %2(<16 x s32>)
    G_STORE %3(<32 x s32>), %0(p0) :: (store (<32 x s32>), align 128)
...
---
name:            split_concat_offset_store_1024
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0, $x0, $x2
    ; CHECK-LABEL: name: split_concat_offset_store_1024
    ; CHECK: liveins: $p0, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<16 x s32>) = COPY $x2
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 128
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<8 x s32>), [[UV1:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[COPY2]](<16 x s32>)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 160
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; CHECK-NEXT: G_STORE [[UV1]](<8 x s32>), [[PTR_ADD2]](p0) :: (store (<8 x s32>) into unknown-address + 96)
    ; CHECK-NEXT: G_STORE [[UV]](<8 x s32>), [[PTR_ADD1]](p0) :: (store (<8 x s32>) into unknown-address + 64, align 64)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(<8 x s32>), [[UV3:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[COPY1]](<16 x s32>)
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; CHECK-NEXT: G_STORE [[UV3]](<8 x s32>), [[PTR_ADD3]](p0) :: (store (<8 x s32>) into unknown-address + 32)
    ; CHECK-NEXT: G_STORE [[UV2]](<8 x s32>), [[PTR_ADD]](p0) :: (store (<8 x s32>), align 128)
    %0:_(p0) = COPY $p0
    %1:_(<16 x s32>) = COPY $x0
    %2:_(<16 x s32>) = COPY $x2
    %3:_(s20) = G_CONSTANT i20 64
    %4:_(<32 x s32>) = G_CONCAT_VECTORS %1(<16 x s32>), %2(<16 x s32>)
    G_AIE_OFFSET_STORE %4(<32 x s32>), %0(p0), %3(s20) :: (store (<32 x s32>), align 128)
...
---
name:            split_concat_postinc_store_1024
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0, $x0, $x2
    ; CHECK-LABEL: name: split_concat_postinc_store_1024
    ; CHECK: liveins: $p0, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<16 x s32>) = COPY $x2
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 128
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s20) = G_CONSTANT i20 64
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s20)
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<8 x s32>), [[UV1:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[COPY2]](<16 x s32>)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s20) = G_CONSTANT i20 96
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C3]](s20)
    ; CHECK-NEXT: G_STORE [[UV1]](<8 x s32>), [[PTR_ADD1]](p0) :: (store (<8 x s32>) into unknown-address + 96)
    ; CHECK-NEXT: G_STORE [[UV]](<8 x s32>), [[PTR_ADD]](p0) :: (store (<8 x s32>) into unknown-address + 64, align 64)
    ; CHECK-NEXT: [[UV2:%[0-9]+]]:_(<8 x s32>), [[UV3:%[0-9]+]]:_(<8 x s32>) = G_UNMERGE_VALUES [[COPY1]](<16 x s32>)
    ; CHECK-NEXT: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C2]](s20)
    ; CHECK-NEXT: G_STORE [[UV3]](<8 x s32>), [[PTR_ADD2]](p0) :: (store (<8 x s32>) into unknown-address + 32)
    ; CHECK-NEXT: G_STORE [[UV2]](<8 x s32>), [[COPY]](p0) :: (store (<8 x s32>), align 128)
    ; CHECK-NEXT: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; CHECK-NEXT: $p1 = COPY [[PTR_ADD3]](p0)
    %0:_(p0) = COPY $p0
    %1:_(<16 x s32>) = COPY $x0
    %2:_(<16 x s32>) = COPY $x2
    %3:_(s20) = G_CONSTANT i20 128
    %4:_(<32 x s32>) = G_CONCAT_VECTORS %1(<16 x s32>), %2(<16 x s32>)
    %5:_(p0) = G_AIE_POSTINC_STORE %4(<32 x s32>), %0(p0), %3(s20) :: (store (<32 x s32>), align 128)
    $p1 = COPY %5(p0)
...
---
# Negative: 512-bit concat store is below AIE2 threshold (1024).
name:            no_split_concat_store_512
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0, $wl0, $wl2
    ; CHECK-LABEL: name: no_split_concat_store_512
    ; CHECK: liveins: $p0, $wl0, $wl2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<8 x s32>) = COPY $wl0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<8 x s32>) = COPY $wl2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(<8 x s32>) = COPY [[COPY1]](<8 x s32>)
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:_(<8 x s32>) = COPY [[COPY2]](<8 x s32>)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s20) = G_CONSTANT i20 32
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s20)
    ; CHECK-NEXT: G_STORE [[COPY4]](<8 x s32>), [[PTR_ADD]](p0) :: (store (<8 x s32>) into unknown-address + 32)
    ; CHECK-NEXT: G_STORE [[COPY3]](<8 x s32>), [[COPY]](p0) :: (store (<8 x s32>), align 64)
    %0:_(p0) = COPY $p0
    %1:_(<8 x s32>) = COPY $wl0
    %2:_(<8 x s32>) = COPY $wl2
    %3:_(<16 x s32>) = G_CONCAT_VECTORS %1(<8 x s32>), %2(<8 x s32>)
    G_STORE %3(<16 x s32>), %0(p0) :: (store (<16 x s32>), align 64)
...
---
# Negative: 1024-bit concat store with multi-use prevents splitting.
name:            no_split_concat_store_1024_multi_use
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $p0, $x0, $x2
    ; CHECK-LABEL: name: no_split_concat_store_1024_multi_use
    ; CHECK: liveins: $p0, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<16 x s32>) = COPY $x2
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<32 x s32>) = G_CONCAT_VECTORS [[COPY1]](<16 x s32>), [[COPY2]](<16 x s32>)
    ; CHECK-NEXT: G_STORE [[CONCAT_VECTORS]](<32 x s32>), [[COPY]](p0) :: (store (<32 x s32>))
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(<32 x s32>) = COPY [[CONCAT_VECTORS]](<32 x s32>)
    ; CHECK-NEXT: G_STORE [[COPY3]](<32 x s32>), [[COPY]](p0) :: (store (<32 x s32>))
    %0:_(p0) = COPY $p0
    %1:_(<16 x s32>) = COPY $x0
    %2:_(<16 x s32>) = COPY $x2
    %3:_(<32 x s32>) = G_CONCAT_VECTORS %1(<16 x s32>), %2(<16 x s32>)
    G_STORE %3(<32 x s32>), %0(p0) :: (store (<32 x s32>), align 128)
    %4:_(<32 x s32>) = COPY %3(<32 x s32>)
    G_STORE %4(<32 x s32>), %0(p0) :: (store (<32 x s32>), align 128)
...
