# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            update_512_256
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $wl4, $x2
    ; CHECK-LABEL: name: update_512_256
    ; CHECK: liveins: $wl4, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec256 = COPY $wl4
    ; CHECK-NEXT: [[INSERT_SUBREG:%[0-9]+]]:vec512 = INSERT_SUBREG [[COPY]], [[COPY1]], %subreg.sub_256_hi
    ; CHECK-NEXT: $x0 = COPY [[INSERT_SUBREG]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<64 x s8>) = COPY $x2
    %2:vregbank(<32 x s8>) = COPY $wl4
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %3:vregbank(<16 x s32>) = G_BITCAST %1:vregbank(<64 x s8>)
    %4:vregbank(<8 x s32>) = G_BITCAST %2:vregbank(<32 x s8>)
    %5:vregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2.upd.I512.I256), %3:vregbank(<16 x s32>), %4:vregbank(<8 x s32>), %6:gprregbank(s32)
    %0:vregbank(<64 x s8>) = G_BITCAST %5:vregbank(<16 x s32>)
    $x0 = COPY %0:vregbank(<64 x s8>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            update_1024_512
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x0, $y3
    ; CHECK-LABEL: name: update_1024_512
    ; CHECK: liveins: $x0, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[INSERT_SUBREG:%[0-9]+]]:vec1024 = INSERT_SUBREG [[COPY]], [[COPY1]], %subreg.sub_512_hi
    ; CHECK-NEXT: $y2 = COPY [[INSERT_SUBREG]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y2
    %1:vregbank(<128 x s8>) = COPY $y3
    %2:vregbank(<64 x s8>) = COPY $x0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %3:vregbank(<32 x s32>) = G_BITCAST %1:vregbank(<128 x s8>)
    %4:vregbank(<16 x s32>) = G_BITCAST %2:vregbank(<64 x s8>)
    %5:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2.upd.I1024.I512), %3:vregbank(<32 x s32>), %4:vregbank(<16 x s32>), %6:gprregbank(s32)
    %0:vregbank(<128 x s8>) = G_BITCAST %5:vregbank(<32 x s32>)
    $y2 = COPY %0:vregbank(<128 x s8>)
    PseudoRET implicit $lr, implicit $y2
...

---
name:            update_1024_256
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $wl0, $y3
    ; CHECK-LABEL: name: update_1024_256
    ; CHECK: liveins: $wl0, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ewh = COPY [[COPY1]]
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec512 = REG_SEQUENCE [[COPY2]], %subreg.sub_256_hi
    ; CHECK-NEXT: [[INSERT_SUBREG:%[0-9]+]]:vec1024 = INSERT_SUBREG [[COPY]], [[REG_SEQUENCE]], %subreg.sub_512_lo
    ; CHECK-NEXT: $y2 = COPY [[INSERT_SUBREG]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y2
    %1:vregbank(<128 x s8>) = COPY $y3
    %2:vregbank(<32 x s8>) = COPY $wl0
    %6:gprregbank(s32) = G_CONSTANT i32 1
    %3:vregbank(<32 x s32>) = G_BITCAST %1:vregbank(<128 x s8>)
    %4:vregbank(<8 x s32>) = G_BITCAST %2:vregbank(<32 x s8>)
    %5:vregbank(<32 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2.upd.I1024.I256), %3:vregbank(<32 x s32>), %4:vregbank(<8 x s32>), %6:gprregbank(s32)
    %0:vregbank(<128 x s8>) = G_BITCAST %5:vregbank(<32 x s32>)
    $y2 = COPY %0:vregbank(<128 x s8>)
    PseudoRET implicit $lr, implicit $y2
...

---
name:            update_512_256_acc32
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $amll2, $bml1
    ; CHECK-LABEL: name: update_512_256_acc32
    ; CHECK: liveins: $amll2, $bml1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bml1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc256 = COPY $amll2
    ; CHECK-NEXT: [[INSERT_SUBREG:%[0-9]+]]:acc512 = INSERT_SUBREG [[COPY]], [[COPY1]], %subreg.sub_256_hi
    ; CHECK-NEXT: $bml0 = COPY [[INSERT_SUBREG]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bml0
    %1:accregbank(<8 x s64>) = COPY $bml1
    %2:accregbank(<4 x s64>) = COPY $amll2
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %0:accregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.upd.512.256.acc), %1:accregbank(<8 x s64>), %2:accregbank(<4 x s64>), %3:gprregbank(s32)
    $bml0 = COPY %0:accregbank(<8 x s64>)
    PseudoRET implicit $lr, implicit $bml0
...

---
name:            update_512_256_acc64
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $amll2, $bml1
    ; CHECK-LABEL: name: update_512_256_acc64
    ; CHECK: liveins: $amll2, $bml1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bml1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc256 = COPY $amll2
    ; CHECK-NEXT: [[INSERT_SUBREG:%[0-9]+]]:acc512 = INSERT_SUBREG [[COPY]], [[COPY1]], %subreg.sub_256_hi
    ; CHECK-NEXT: $bml0 = COPY [[INSERT_SUBREG]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bml0
    %1:accregbank(<8 x s64>) = COPY $bml1
    %2:accregbank(<4 x s64>) = COPY $amll2
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %0:accregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.upd.512.256.acc), %1:accregbank(<8 x s64>), %2:accregbank(<4 x s64>), %3:gprregbank(s32)
    $bml0 = COPY %0:accregbank(<8 x s64>)
    PseudoRET implicit $lr, implicit $bml0
...

---
name:            update_1024_256_acc32
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $amll2, $cm1
    ; CHECK-LABEL: name: update_1024_256_acc32
    ; CHECK: liveins: $amll2, $cm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cm1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mams = COPY $amll2
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc512 = REG_SEQUENCE [[COPY1]], %subreg.sub_256_lo
    ; CHECK-NEXT: [[INSERT_SUBREG:%[0-9]+]]:acc1024 = INSERT_SUBREG [[COPY]], [[REG_SEQUENCE]], %subreg.sub_512_lo
    ; CHECK-NEXT: $cm0 = COPY [[INSERT_SUBREG]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cm0
    %1:accregbank(<16 x s64>) = COPY $cm1
    %2:accregbank(<4 x s64>) = COPY $amll2
    %3:gprregbank(s32) = G_CONSTANT i32 0
    %0:accregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.upd.1024.256.acc), %1:accregbank(<16 x s64>), %2:accregbank(<4 x s64>), %3:gprregbank(s32)
    $cm0 = COPY %0:accregbank(<16 x s64>)
    PseudoRET implicit $lr, implicit $cm0
...

---
name:            update_1024_512_acc32
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bml2, $cm1
    ; CHECK-LABEL: name: update_1024_512_acc32
    ; CHECK: liveins: $bml2, $cm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cm1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc512 = COPY $bml2
    ; CHECK-NEXT: [[INSERT_SUBREG:%[0-9]+]]:acc1024 = INSERT_SUBREG [[COPY]], [[COPY1]], %subreg.sub_512_hi
    ; CHECK-NEXT: $cm0 = COPY [[INSERT_SUBREG]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cm0
    %1:accregbank(<16 x s64>) = COPY $cm1
    %2:accregbank(<8 x s64>) = COPY $bml2
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %0:accregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.upd.1024.512.acc), %1:accregbank(<16 x s64>), %2:accregbank(<8 x s64>), %3:gprregbank(s32)
    $cm0 = COPY %0:accregbank(<16 x s64>)
    PseudoRET implicit $lr, implicit $cm0
...

---
name:            update_1024_256_acc64
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $amll2, $cm1
    ; CHECK-LABEL: name: update_1024_256_acc64
    ; CHECK: liveins: $amll2, $cm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cm1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mams = COPY $amll2
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:acc512 = REG_SEQUENCE [[COPY1]], %subreg.sub_256_hi
    ; CHECK-NEXT: [[INSERT_SUBREG:%[0-9]+]]:acc1024 = INSERT_SUBREG [[COPY]], [[REG_SEQUENCE]], %subreg.sub_512_lo
    ; CHECK-NEXT: $cm0 = COPY [[INSERT_SUBREG]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cm0
    %1:accregbank(<16 x s64>) = COPY $cm1
    %2:accregbank(<4 x s64>) = COPY $amll2
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %0:accregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.upd.1024.256.acc), %1:accregbank(<16 x s64>), %2:accregbank(<4 x s64>), %3:gprregbank(s32)
    $cm0 = COPY %0:accregbank(<16 x s64>)
    PseudoRET implicit $lr, implicit $cm0
...

---
name:            update_1024_512_acc64
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bml2, $cm1
    ; CHECK-LABEL: name: update_1024_512_acc64
    ; CHECK: liveins: $bml2, $cm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cm1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc512 = COPY $bml2
    ; CHECK-NEXT: [[INSERT_SUBREG:%[0-9]+]]:acc1024 = INSERT_SUBREG [[COPY]], [[COPY1]], %subreg.sub_512_hi
    ; CHECK-NEXT: $cm0 = COPY [[INSERT_SUBREG]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cm0
    %1:accregbank(<16 x s64>) = COPY $cm1
    %2:accregbank(<8 x s64>) = COPY $bml2
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %0:accregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.upd.1024.512.acc), %1:accregbank(<16 x s64>), %2:accregbank(<8 x s64>), %3:gprregbank(s32)
    $cm0 = COPY %0:accregbank(<16 x s64>)
    PseudoRET implicit $lr, implicit $cm0
...

---
name:            update_512_256_bf
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $wl4, $x2
    ; CHECK-LABEL: name: update_512_256_bf
    ; CHECK: liveins: $r0, $wl4, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec256 = COPY $wl4
    ; CHECK-NEXT: [[INSERT_SUBREG:%[0-9]+]]:vec512 = INSERT_SUBREG [[COPY]], [[COPY1]], %subreg.sub_256_hi
    ; CHECK-NEXT: $x0 = COPY [[INSERT_SUBREG]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<32 x s16>) = COPY $x2
    %3:vregbank(<16 x s16>) = COPY $wl4
    %4:gprregbank(s32) = G_CONSTANT i32 1
    %0:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2.upd.bf512.bf256), %1:vregbank(<32 x s16>), %3:vregbank(<16 x s16>), %4:gprregbank(s32)
    $x0 = COPY %0:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            update_1024_256_bf
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $wl0, $y3
    ; CHECK-LABEL: name: update_1024_256_bf
    ; CHECK: liveins: $r0, $wl0, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ewl = COPY $wl0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec512 = REG_SEQUENCE [[COPY1]], %subreg.sub_256_lo
    ; CHECK-NEXT: [[INSERT_SUBREG:%[0-9]+]]:vec1024 = INSERT_SUBREG [[COPY]], [[REG_SEQUENCE]], %subreg.sub_512_hi
    ; CHECK-NEXT: $y2 = COPY [[INSERT_SUBREG]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y2
    %1:vregbank(<64 x s16>) = COPY $y3
    %3:vregbank(<16 x s16>) = COPY $wl0
    %4:gprregbank(s32) = G_CONSTANT i32 2
    %0:vregbank(<64 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2.upd.bf1024.bf256), %1:vregbank(<64 x s16>), %3:vregbank(<16 x s16>), %4:gprregbank(s32)
    $y2 = COPY %0:vregbank(<64 x s16>)
    PseudoRET implicit $lr, implicit $y2
...

---
name:            update_1024_512_bf
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x0, $y3
    ; CHECK-LABEL: name: update_1024_512_bf
    ; CHECK: liveins: $r0, $x0, $y3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y3
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[INSERT_SUBREG:%[0-9]+]]:vec1024 = INSERT_SUBREG [[COPY]], [[COPY1]], %subreg.sub_512_hi
    ; CHECK-NEXT: $y2 = COPY [[INSERT_SUBREG]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y2
    %1:vregbank(<64 x s16>) = COPY $y3
    %3:vregbank(<32 x s16>) = COPY $x0
    %4:gprregbank(s32) = G_CONSTANT i32 1
    %0:vregbank(<64 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2.upd.bf1024.bf512), %1:vregbank(<64 x s16>), %3:vregbank(<32 x s16>), %4:gprregbank(s32)
    $y2 = COPY %0:vregbank(<64 x s16>)
    PseudoRET implicit $lr, implicit $y2
...
