# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name: add_s32
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6, $r7
    ; CHECK-LABEL: name: add_s32
    ; CHECK: liveins: $r6, $r7
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r7
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:er = ADD [[COPY]], [[COPY1]], implicit-def dead $srcarry
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[ADD]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = COPY $r7
    %2:gprregbank(s32) = G_ADD %0, %1
    PseudoRET implicit $lr, implicit %2
...

---
name: add_s32_const_smax
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: add_s32_const_smax
    ; CHECK: liveins: $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; CHECK-NEXT: [[ADD_add_r_ri:%[0-9]+]]:er = ADD_add_r_ri [[COPY]], 63, implicit-def dead $srcarry
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[ADD_add_r_ri]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = G_CONSTANT i32 63
    %2:gprregbank(s32) = G_ADD %0, %1
    PseudoRET implicit $lr, implicit %2
...

---
name: add_s32_const_smin
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: add_s32_const_smin
    ; CHECK: liveins: $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; CHECK-NEXT: [[ADD_add_r_ri:%[0-9]+]]:er = ADD_add_r_ri [[COPY]], -64, implicit-def dead $srcarry
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[ADD_add_r_ri]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = G_CONSTANT i32 -64
    %2:gprregbank(s32) = G_ADD %0, %1
    PseudoRET implicit $lr, implicit %2
...

---
name: add_s32_const_smax_plus_1
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: add_s32_const_smax_plus_1
    ; CHECK: liveins: $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; CHECK-NEXT: [[MOV_RLC_imm10_pseudo:%[0-9]+]]:er = MOV_RLC_imm10_pseudo 64
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:er = ADD [[COPY]], [[MOV_RLC_imm10_pseudo]], implicit-def dead $srcarry
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[ADD]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = G_CONSTANT i32 64
    %2:gprregbank(s32) = G_ADD %0, %1
    PseudoRET implicit $lr, implicit %2
...

---
name: add_s32_const_smin_minus_one
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: add_s32_const_smin_minus_one
    ; CHECK: liveins: $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; CHECK-NEXT: [[MOV_RLC_imm10_pseudo:%[0-9]+]]:er = MOV_RLC_imm10_pseudo -65
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:er = ADD [[COPY]], [[MOV_RLC_imm10_pseudo]], implicit-def dead $srcarry
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[ADD]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = G_CONSTANT i32 -65
    %2:gprregbank(s32) = G_ADD %0, %1
    PseudoRET implicit $lr, implicit %2
...
