# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name: implicit_def_s20
legalized: true
regBankSelected: true

body: |
  bb.0:
    ; CHECK-LABEL: name: implicit_def_s20
    ; CHECK: [[DEF:%[0-9]+]]:er = IMPLICIT_DEF
    ; CHECK-NEXT: $m0 = COPY [[DEF]]
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:mdm = IMPLICIT_DEF
    ; CHECK-NEXT: $m1 = COPY [[DEF1]]
    %0:gprregbank(s20) = G_IMPLICIT_DEF
    $m0 = COPY %0
    %1:modregbank(s20) = G_IMPLICIT_DEF
    $m1 = COPY %1
...

---
name: implicit_def_s32
legalized: true
regBankSelected: true

body: |
  bb.0:
    ; CHECK-LABEL: name: implicit_def_s32
    ; CHECK: [[DEF:%[0-9]+]]:er = IMPLICIT_DEF
    ; CHECK-NEXT: $r0 = COPY [[DEF]]
    %0:gprregbank(s32) = G_IMPLICIT_DEF
    $r0 = COPY %0
...

---
name: implicit_def_p0
legalized: true
regBankSelected: true

body: |
  bb.0:
    ; CHECK-LABEL: name: implicit_def_p0
    ; CHECK: [[DEF:%[0-9]+]]:ep = IMPLICIT_DEF
    ; CHECK-NEXT: $p0 = COPY [[DEF]]
    %0:ptrregbank(p0) = G_IMPLICIT_DEF
    $p0 = COPY %0
...
