# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            test_vneg_acc32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cm1, $r0
    ; CHECK-LABEL: name: test_vneg_acc32
    ; CHECK: liveins: $cm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cm1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[VNEG:%[0-9]+]]:acc1024 = VNEG [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $cm0 = COPY [[VNEG]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cm0
    %0:accregbank(<16 x s64>) = COPY $cm1
    %1:gprregbank(s32) = COPY $r0
    %2:accregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.ACC1024.acc32.neg.conf), %0(<16 x s64>), %1(s32)
    $cm0 = COPY %2(<16 x s64>)
    PseudoRET implicit $lr, implicit $cm0
...

---
name:            test_vneg_acc64
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cm1, $r0
    ; CHECK-LABEL: name: test_vneg_acc64
    ; CHECK: liveins: $cm1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cm1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[VNEG:%[0-9]+]]:acc1024 = VNEG [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $cm0 = COPY [[VNEG]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cm0
    %0:accregbank(<16 x s64>) = COPY $cm1
    %1:gprregbank(s32) = COPY $r0
    %2:accregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.ACC1024.acc64.neg.conf), %0(<16 x s64>), %1(s32)
    $cm0 = COPY %2(<16 x s64>)
    PseudoRET implicit $lr, implicit $cm0
...
