# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            llvm_start_loop_iterations_static
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $r0
    ; CHECK-LABEL: name: llvm_start_loop_iterations_static
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[MOV_RLC_imm10_pseudo:%[0-9]+]]:er = MOV_RLC_imm10_pseudo 9
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[MOV_RLC_imm10_pseudo]]
    %0:gprregbank(s32) = G_CONSTANT i32 10
    %1:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.start.loop.iterations), %0(s32)
    PseudoRET implicit $lr, implicit %1
...


---
name:            llvm_start_loop_iterations_dynamic
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $r0
    ; CHECK-LABEL: name: llvm_start_loop_iterations_dynamic
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[ADD_NC_GPR:%[0-9]+]]:er = ADD_NC_GPR [[COPY]], -1
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[ADD_NC_GPR]]
    %0:gprregbank(s32) = COPY $r0
    %1:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.start.loop.iterations), %0(s32)
    PseudoRET implicit $lr, implicit %1
...
