# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            test
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r1

    ; CHECK-LABEL: name: test
    ; CHECK: liveins: $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[MOV_mv_ss2scl:%[0-9]+]]:er = MOV_mv_ss2scl implicit-def $srss0
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er28 = COPY $srss0
    ; CHECK-NEXT: MOV_mv_scl2ms_doTlast_reg [[MOV_mv_ss2scl]], [[COPY]]
    ; CHECK-NEXT: MOV_mv_scl2ms [[MOV_mv_ss2scl]]
    ; CHECK-NEXT: MOV_TLAST_mv_scl2ms [[MOV_mv_ss2scl]]
    ; CHECK-NEXT: $r0 = COPY [[MOV_mv_ss2scl]]
    ; CHECK-NEXT: $r1 = COPY [[MOV_mv_ss2scl]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %4:gprregbank(s32) = G_CONSTANT i32 0
    %5:gprregbank(s32) = G_CONSTANT i32 1
    %2:gprregbank(s32), %3:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.get.ss)
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.put.ms), %2(s32), %3(s32)
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.put.ms), %2(s32), %4(s32)
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.put.ms), %2(s32), %5(s32)
    $r0 = COPY %2(s32)
    $r1 = COPY %2(s32)
    PseudoRET implicit $lr, implicit $r0

...
---
name:            test_nb
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r1

    ; CHECK-LABEL: name: test_nb
    ; CHECK: liveins: $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[MOV_NB_mv_ss2scl:%[0-9]+]]:er = MOV_NB_mv_ss2scl implicit-def $srss0
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er28 = COPY $srss0
    ; CHECK-NEXT: MOV_NB_mv_scl2ms_doTlast_reg [[MOV_NB_mv_ss2scl]], [[COPY]], implicit-def $srms0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $srms0
    ; CHECK-NEXT: MOV_NB_mv_scl2ms [[MOV_NB_mv_ss2scl]], implicit-def $srms0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $srms0
    ; CHECK-NEXT: MOV_NB_TLAST_mv_scl2ms [[MOV_NB_mv_ss2scl]], implicit-def $srms0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $srms0
    ; CHECK-NEXT: $r0 = COPY [[COPY1]]
    ; CHECK-NEXT: $r1 = COPY [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %5:gprregbank(s32) = G_CONSTANT i32 0
    %7:gprregbank(s32) = G_CONSTANT i32 1
    %2:gprregbank(s32), %3:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.get.ss.nb)
    %0:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.put.ms.nb), %2(s32), %3(s32)
    %4:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.put.ms.nb), %2(s32), %5(s32)
    %6:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.put.ms.nb), %2(s32), %7(s32)
    $r0 = COPY %0(s32)
    $r1 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0

...


---
name:            test_packet_header_tlast_reg
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $r1, $r2
    ; CHECK-LABEL: name: test_packet_header_tlast_reg
    ; CHECK: liveins: $p0, $r0, $r1, $r2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er28 = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: MOV_mv_ph2ms_doTlast_reg [[COPY1]], 2, [[COPY]]
    ; CHECK-NEXT: MOV_NB_mv_ph2ms_doTlast_reg [[COPY1]], 2, [[COPY]], implicit-def $srms0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $srms0
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:gprregbank(s32) = COPY $r0
    %1:gprregbank(s32) = COPY $r1
    %5:gprregbank(s32) = COPY $r2
    %9:gprregbank(s32) = G_CONSTANT i32 10
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.put.ms.packet.header), %0:gprregbank(s32), %1:gprregbank(s32), %9:gprregbank(s32)
    %4:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.put.ms.nb.packet.header), %0:gprregbank(s32), %1:gprregbank(s32), %9:gprregbank(s32)
    PseudoRET implicit $lr
...

---
name:            test_ctrl_packet_header_tlast_reg
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $r1, $r2
    ; CHECK-LABEL: name: test_ctrl_packet_header_tlast_reg
    ; CHECK: liveins: $p0, $r0, $r1, $r2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er28 = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: MOV_mv_cph2ms_doTlast_reg [[COPY3]], 2, 1, [[COPY2]], [[COPY]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:em = COPY [[COPY1]]
    ; CHECK-NEXT: MOV_NB_mv_cph2ms_doTlast_reg [[COPY4]], 2, 1, [[COPY2]], [[COPY]], implicit-def $srms0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:er = COPY $srms0
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:gprregbank(s32) = COPY $r0
    %1:gprregbank(s32) = COPY $r1
    %5:gprregbank(s32) = COPY $r2
    %8:gprregbank(s32) = G_CONSTANT i32 3
    %9:gprregbank(s32) = G_CONSTANT i32 1
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.put.ms.ctrl.packet.header), %0:gprregbank(s32), %1:gprregbank(s32), %8:gprregbank(s32), %9:gprregbank(s32), %5:gprregbank(s32)
    %6:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.put.ms.nb.ctrl.packet.header), %0:gprregbank(s32), %1:gprregbank(s32), %8:gprregbank(s32), %9:gprregbank(s32), %5:gprregbank(s32)
    PseudoRET implicit $lr
...

---
name:            test_packet_header
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $r1, $r2
    ; CHECK-LABEL: name: test_packet_header
    ; CHECK: liveins: $p0, $r0, $r1, $r2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: MOV_mv_ph2ms [[COPY]], 1
    ; CHECK-NEXT: MOV_NB_mv_ph2ms [[COPY]], 1, implicit-def $srms0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $srms0
    ; CHECK-NEXT: MOV_TLAST_mv_ph2ms [[COPY]], 1
    ; CHECK-NEXT: MOV_NB_TLAST_mv_ph2ms [[COPY]], 1, implicit-def $srms0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $srms0
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:gprregbank(s32) = G_CONSTANT i32 0
    %10:gprregbank(s32) = G_CONSTANT i32 1
    %1:gprregbank(s32) = COPY $r1
    %5:gprregbank(s32) = COPY $r2
    %9:gprregbank(s32) = G_CONSTANT i32 9
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.put.ms.packet.header), %0:gprregbank(s32), %1:gprregbank(s32), %9:gprregbank(s32)
    %4:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.put.ms.nb.packet.header), %0:gprregbank(s32), %1:gprregbank(s32), %9:gprregbank(s32)
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.put.ms.packet.header), %10:gprregbank(s32), %1:gprregbank(s32), %9:gprregbank(s32)
    %7:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.put.ms.nb.packet.header), %10:gprregbank(s32), %1:gprregbank(s32), %9:gprregbank(s32)
    PseudoRET implicit $lr
...

---
name:            test_ctrl_packet_header
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $r0, $r1, $r2
    ; CHECK-LABEL: name: test_ctrl_packet_header
    ; CHECK: liveins: $p0, $r0, $r1, $r2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:em = COPY [[COPY]]
    ; CHECK-NEXT: MOV_mv_cph2ms [[COPY2]], 2, 2, [[COPY1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:em = COPY [[COPY]]
    ; CHECK-NEXT: MOV_NB_mv_cph2ms [[COPY3]], 2, 2, [[COPY1]], implicit-def $srms0
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $srms0
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:em = COPY [[COPY]]
    ; CHECK-NEXT: MOV_TLAST_mv_cph2ms [[COPY5]], 2, 2, [[COPY1]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:em = COPY [[COPY]]
    ; CHECK-NEXT: MOV_NB_TLAST_mv_cph2ms [[COPY6]], 2, 2, [[COPY1]], implicit-def $srms0
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:er = COPY $srms0
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:gprregbank(s32) = G_CONSTANT i32 0
    %10:gprregbank(s32) = G_CONSTANT i32 1
    %1:gprregbank(s32) = COPY $r1
    %5:gprregbank(s32) = COPY $r2
    %8:gprregbank(s32) = G_CONSTANT i32 3
    %9:gprregbank(s32) = G_CONSTANT i32 2
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.put.ms.ctrl.packet.header), %0:gprregbank(s32), %1:gprregbank(s32), %8:gprregbank(s32), %9:gprregbank(s32), %5:gprregbank(s32)
    %6:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.put.ms.nb.ctrl.packet.header), %0:gprregbank(s32), %1:gprregbank(s32), %8:gprregbank(s32), %9:gprregbank(s32), %5:gprregbank(s32)
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.put.ms.ctrl.packet.header), %10:gprregbank(s32), %1:gprregbank(s32), %8:gprregbank(s32), %9:gprregbank(s32), %5:gprregbank(s32)
    %11:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.put.ms.nb.ctrl.packet.header), %10:gprregbank(s32), %1:gprregbank(s32), %8:gprregbank(s32), %9:gprregbank(s32), %5:gprregbank(s32)
    PseudoRET implicit $lr
...
