# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s
---
name: v8s32
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $wl0
    ; CHECK-LABEL: name: v8s32
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: $wl0 = COPY [[COPY]]
    %0:vregbank(<8 x s32>) = COPY $wl0
    %1:vregbank(<8 x s32>) = G_FREEZE %0
    $wl0 = COPY %1
...

---
name: v16s16
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $wl0
    ; CHECK-LABEL: name: v16s16
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: $wl0 = COPY [[COPY]]
    %0:vregbank(<16 x s16>) = COPY $wl0
    %1:vregbank(<16 x s16>) = G_FREEZE %0
    $wl0 = COPY %1
...

---
name: v32s8
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $wl0
    ; CHECK-LABEL: name: v32s8
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: $wl0 = COPY [[COPY]]
    %0:vregbank(<32 x s8>) = COPY $wl0
    %1:vregbank(<32 x s8>) = G_FREEZE %0
    $wl0 = COPY %1
...

---
name: acc256
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $wl0
    ; CHECK-LABEL: name: acc256
    ; CHECK: liveins: $wl0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc256 = COPY [[COPY]]
    ; CHECK-NEXT: $wl0 = COPY [[COPY1]]
    %0:vregbank(<4 x s64>) = COPY $wl0
    %1:accregbank(<4 x s64>) = G_FREEZE %0
    $wl0 = COPY %1
...

---
name: v16s32
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $x0
    ; CHECK-LABEL: name: v16s32
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: $x0 = COPY [[COPY]]
    %0:vregbank(<16 x s32>) = COPY $x0
    %1:vregbank(<16 x s32>) = G_FREEZE %0
    $x0 = COPY %1
...

---
name: v32s16
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $x0
    ; CHECK-LABEL: name: v32s16
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: $x0 = COPY [[COPY]]
    %0:vregbank(<32 x s16>) = COPY $x0
    %1:vregbank(<32 x s16>) = G_FREEZE %0
    $x0 = COPY %1
...

---
name: v64s8
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $x0
    ; CHECK-LABEL: name: v64s8
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: $x0 = COPY [[COPY]]
    %0:vregbank(<64 x s8>) = COPY $x0
    %1:vregbank(<64 x s8>) = G_FREEZE %0
    $x0 = COPY %1
...

---
name: acc512
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $x0
    ; CHECK-LABEL: name: acc512
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc512 = COPY [[COPY]]
    ; CHECK-NEXT: $x0 = COPY [[COPY1]]
    %0:vregbank(<8 x s64>) = COPY $x0
    %1:accregbank(<8 x s64>) = G_FREEZE %0
    $x0 = COPY %1
...

---
name: v32s32
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $y2
    ; CHECK-LABEL: name: v32s32
    ; CHECK: liveins: $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: $y2 = COPY [[COPY]]
    %0:vregbank(<32 x s32>) = COPY $y2
    %1:vregbank(<32 x s32>) = G_FREEZE %0
    $y2 = COPY %1
...

---
name: v64s16
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $y2
    ; CHECK-LABEL: name: v64s16
    ; CHECK: liveins: $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: $y2 = COPY [[COPY]]
    %0:vregbank(<64 x s16>) = COPY $y2
    %1:vregbank(<64 x s16>) = G_FREEZE %0
    $y2 = COPY %1
...

---
name: v128s8
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $y2
    ; CHECK-LABEL: name: v128s8
    ; CHECK: liveins: $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: $y2 = COPY [[COPY]]
    %0:vregbank(<128 x s8>) = COPY $y2
    %1:vregbank(<128 x s8>) = G_FREEZE %0
    $y2 = COPY %1
...

---
name: acc1024
legalized: true
regBankSelected: true
body: |
  bb.0:
    liveins: $y2
    ; CHECK-LABEL: name: acc1024
    ; CHECK: liveins: $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:acc1024 = COPY [[COPY]]
    ; CHECK-NEXT: $y2 = COPY [[COPY1]]
    %0:vregbank(<16 x s64>) = COPY $y2
    %1:accregbank(<16 x s64>) = G_FREEZE %0
    $y2 = COPY %1
...
