# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name: sext_inreg_s32_8
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: sext_inreg_s32_8
    ; CHECK: liveins: $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; CHECK-NEXT: [[EXTENDs8_:%[0-9]+]]:er = EXTENDs8 [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[EXTENDs8_]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = G_SEXT_INREG %0, 8
    PseudoRET implicit $lr, implicit %1
...

---
name: sext_inreg_s32_16
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: sext_inreg_s32_16
    ; CHECK: liveins: $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; CHECK-NEXT: [[EXTENDs16_:%[0-9]+]]:er = EXTENDs16 [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[EXTENDs16_]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = G_SEXT_INREG %0, 16
    PseudoRET implicit $lr, implicit %1
...
