# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

# Note that G_AIE_PAD_VECTOR_UNDEF is always legal, so it isn't needed to test
# for every possible 256-bit and 512-bit type.

---
name:            test_pad_256_bit_v8int32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_pad_256_bit_v8int32
    ; CHECK: [[COPY:%[0-9]+]]:vec128 = COPY $q0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec256 = COPY [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY1]]
    %1:vregbank(<4 x s32>) = COPY $q0
    %2:vregbank(<8 x s32>) = G_AIE_PAD_VECTOR_UNDEF %1
    PseudoRET implicit $lr, implicit %2
...

---
name:            test_pad_128_bits_into_512_bit_v16int32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_pad_128_bits_into_512_bit_v16int32
    ; CHECK: [[COPY:%[0-9]+]]:vec128 = COPY $q0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec256 = COPY [[COPY]]
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec512 = REG_SEQUENCE [[COPY1]], %subreg.sub_256_lo
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[REG_SEQUENCE]]
    %1:vregbank(<4 x s32>) = COPY $q0
    %2:vregbank(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF %1
    PseudoRET implicit $lr, implicit %2
...

---
name:            test_pad_256_bits_into_512_bit_v16int32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: test_pad_256_bits_into_512_bit_v16int32
    ; CHECK: [[COPY:%[0-9]+]]:vec256 = COPY $wl0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vec512 = REG_SEQUENCE [[COPY]], %subreg.sub_256_lo
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[REG_SEQUENCE]]
    %1:vregbank(<8 x s32>) = COPY $wl0
    %2:vregbank(<16 x s32>) = G_AIE_PAD_VECTOR_UNDEF %1
    PseudoRET implicit $lr, implicit %2
...
