# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            set_satmode
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0
    ; CHECK-LABEL: name: set_satmode
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crsat = COPY [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:gprregbank(s32) = COPY $r0
    %1:gprregbank(s32) = G_CONSTANT i32 9
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.set.ctrl.reg), %1:gprregbank(s32), %0:gprregbank(s32)
    PseudoRET implicit $lr
...

---
name:            set_sat
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: set_sat
    ; CHECK: $crsat = MOV_scalar_imm10_pseudo 1
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:gprregbank(s32) = G_CONSTANT i32 9
    %1:gprregbank(s32) = G_CONSTANT i32 1
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.set.ctrl.reg), %0:gprregbank(s32), %1:gprregbank(s32)
    PseudoRET implicit $lr
...

---
name:            set_symsat
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: set_symsat
    ; CHECK: $crsat = MOV_scalar_imm10_pseudo 3
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:gprregbank(s32) = G_CONSTANT i32 9
    %1:gprregbank(s32) = G_CONSTANT i32 3
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.set.ctrl.reg), %0:gprregbank(s32), %1:gprregbank(s32)
    PseudoRET implicit $lr
...

---
name:            clr_sat
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: clr_sat
    ; CHECK: $crsat = MOV_scalar_imm10_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:gprregbank(s32) = G_CONSTANT i32 9
    %1:gprregbank(s32) = G_CONSTANT i32 0
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.set.ctrl.reg), %0:gprregbank(s32), %1:gprregbank(s32)
    PseudoRET implicit $lr
...

---
name:            set_rnd
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0
    ; CHECK-LABEL: name: set_rnd
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crrnd = COPY [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:gprregbank(s32) = COPY $r0
    %1:gprregbank(s32) = G_CONSTANT i32 6
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.set.ctrl.reg), %1:gprregbank(s32), %0:gprregbank(s32)
    PseudoRET implicit $lr
...

---
name:            set_fpmulmac_mask
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0
    ; CHECK-LABEL: name: set_fpmulmac_mask
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crfpmask = COPY [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:gprregbank(s32) = COPY $r0
    %1:gprregbank(s32) = G_CONSTANT i32 3
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.set.ctrl.reg), %1:gprregbank(s32), %0:gprregbank(s32)
    PseudoRET implicit $lr
...

---
name:            set_fp2int_mask
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0
    ; CHECK-LABEL: name: set_fp2int_mask
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crf2imask = COPY [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:gprregbank(s32) = COPY $r0
    %1:gprregbank(s32) = G_CONSTANT i32 2
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.set.ctrl.reg), %1:gprregbank(s32), %0:gprregbank(s32)
    PseudoRET implicit $lr
...

---
name:            set_fp2bfmask
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0
    ; CHECK-LABEL: name: set_fp2bfmask
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: $crf2fmask = COPY [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:gprregbank(s32) = COPY $r0
    %1:gprregbank(s32) = G_CONSTANT i32 1
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.set.ctrl.reg), %1:gprregbank(s32), %0:gprregbank(s32)
    PseudoRET implicit $lr
...


---
name:            get_satmode
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: get_satmode
    ; CHECK: [[COPY:%[0-9]+]]:er = COPY $crsat
    ; CHECK-NEXT: $r0 = COPY [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:gprregbank(s32) = G_CONSTANT i32 9
    %0:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.get.ctrl.reg), %1:gprregbank(s32)
    $r0 = COPY %0:gprregbank(s32)
    PseudoRET implicit $lr, implicit $r0
...


---
name:            get_sat
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: get_sat
    ; CHECK: [[COPY:%[0-9]+]]:er = COPY $crsat
    ; CHECK-NEXT: $r0 = COPY [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:gprregbank(s32) = G_CONSTANT i32 9
    %0:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.get.ctrl.reg), %1:gprregbank(s32)
    $r0 = COPY %0:gprregbank(s32)
    PseudoRET implicit $lr, implicit $r0
...


---
name:            get_rnd
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: get_rnd
    ; CHECK: [[COPY:%[0-9]+]]:er = COPY $crrnd
    ; CHECK-NEXT: $r0 = COPY [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:gprregbank(s32) = G_CONSTANT i32 6
    %0:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.get.ctrl.reg), %1:gprregbank(s32)
    $r0 = COPY %0:gprregbank(s32)
    PseudoRET implicit $lr, implicit $r0
...


---
name:            get_fpmulmac_mask
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: get_fpmulmac_mask
    ; CHECK: [[COPY:%[0-9]+]]:er = COPY $crfpmask
    ; CHECK-NEXT: $r0 = COPY [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:gprregbank(s32) = G_CONSTANT i32 3
    %0:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.get.ctrl.reg), %1:gprregbank(s32)
    $r0 = COPY %0:gprregbank(s32)
    PseudoRET implicit $lr, implicit $r0
...


---
name:            get_fp2int_mask
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: get_fp2int_mask
    ; CHECK: [[COPY:%[0-9]+]]:er = COPY $crf2imask
    ; CHECK-NEXT: $r0 = COPY [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:gprregbank(s32) = G_CONSTANT i32 2
    %0:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.get.ctrl.reg), %1:gprregbank(s32)
    $r0 = COPY %0:gprregbank(s32)
    PseudoRET implicit $lr, implicit $r0
...


---
name:            get_fp2bfmask
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: get_fp2bfmask
    ; CHECK: [[COPY:%[0-9]+]]:er = COPY $crf2fmask
    ; CHECK-NEXT: $r0 = COPY [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:gprregbank(s32) = G_CONSTANT i32 1
    %0:gprregbank(s32) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.get.ctrl.reg), %1:gprregbank(s32)
    $r0 = COPY %0:gprregbank(s32)
    PseudoRET implicit $lr, implicit $r0
...
