# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            VBNEG_LTZ_S8
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $x2
    ; CHECK-LABEL: name: VBNEG_LTZ_S8
    ; CHECK: liveins: $p0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[VBNEG_LTZ_S8_:%[0-9]+]]:vec512, [[VBNEG_LTZ_S8_1:%[0-9]+]]:el = VBNEG_LTZ_S8 [[COPY]]
    ; CHECK-NEXT: $x0 = COPY [[VBNEG_LTZ_S8_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<64 x s8>) = COPY $x2
    %3:vregbank(<64 x s8>), %4:gprregbank(<2 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2.vbneg.ltz8), %1:vregbank(<64 x s8>)
    $x0 = COPY %3:vregbank(<64 x s8>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VBNEG_LTZ_S16
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $x2
    ; CHECK-LABEL: name: VBNEG_LTZ_S16
    ; CHECK: liveins: $p0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[VBNEG_LTZ_S16_:%[0-9]+]]:vec512, [[VBNEG_LTZ_S16_1:%[0-9]+]]:ers8 = VBNEG_LTZ_S16 [[COPY]]
    ; CHECK-NEXT: $x0 = COPY [[VBNEG_LTZ_S16_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<32 x s16>) = COPY $x2
    %3:vregbank(<32 x s16>), %4:gprregbank(s32) = G_INTRINSIC intrinsic(@llvm.aie2.vbneg.ltz16), %1:vregbank(<32 x s16>)
    $x0 = COPY %3:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...


---
name:            VBNEG_LTZ_S32
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $p0, $x2
    ; CHECK-LABEL: name: VBNEG_LTZ_S32
    ; CHECK: liveins: $p0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[VBNEG_LTZ_S32_:%[0-9]+]]:vec512, [[VBNEG_LTZ_S32_1:%[0-9]+]]:ers8 = VBNEG_LTZ_S32 [[COPY]]
    ; CHECK-NEXT: $x0 = COPY [[VBNEG_LTZ_S32_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<16 x s32>) = COPY $x2
    %3:vregbank(<16 x s32>), %4:gprregbank(s32) = G_INTRINSIC intrinsic(@llvm.aie2.vbneg.ltz32), %1:vregbank(<16 x s32>)
    $x0 = COPY %3:vregbank(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0
...
