# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select -o - -verify-machineinstrs %s | FileCheck --check-prefix=AIE2 %s
# RUN: llc -mtriple aie2p -run-pass=instruction-select -o - -verify-machineinstrs %s | FileCheck --check-prefix=AIE2P %s

---
name: store_s32
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6, $p0
    ; AIE2-LABEL: name: store_s32
    ; AIE2: liveins: $r6, $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r6
    ; AIE2-NEXT: ST_dms_sts_idx_imm [[COPY1]], [[COPY]], 0 :: (store (s32))
    ;
    ; AIE2P-LABEL: name: store_s32
    ; AIE2P: liveins: $r6, $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r6
    ; AIE2P-NEXT: ST_dms_sts_idx_imm [[COPY1]], [[COPY]], 0 :: (store (s32))
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r6
    G_STORE %1, %0 :: (store (s32))
...

---
name: store_s8
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6, $p0
    ; AIE2-LABEL: name: store_s8
    ; AIE2: liveins: $r6, $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r6
    ; AIE2-NEXT: ST_S8_ag_idx_imm [[COPY1]], [[COPY]], 0 :: (store (s8))
    ;
    ; AIE2P-LABEL: name: store_s8
    ; AIE2P: liveins: $r6, $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r6
    ; AIE2P-NEXT: ST_s8_idx_imm [[COPY1]], [[COPY]], 0, implicit-def dead $pe2_ads, implicit $pe2_ads :: (store (s8))
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r6
    G_STORE %1, %0 :: (store (s8))
...

---
name: store_s16
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6, $p0
    ; AIE2-LABEL: name: store_s16
    ; AIE2: liveins: $r6, $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r6
    ; AIE2-NEXT: ST_S16_ag_idx_imm [[COPY1]], [[COPY]], 0 :: (store (s16))
    ;
    ; AIE2P-LABEL: name: store_s16
    ; AIE2P: liveins: $r6, $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r6
    ; AIE2P-NEXT: ST_s16_idx_imm [[COPY1]], [[COPY]], 0, implicit-def dead $pe2_ads, implicit $pe2_ads :: (store (s16))
    %0:ptrregbank(p0) = COPY $p0
    %1:gprregbank(s32) = COPY $r6
    G_STORE %1, %0 :: (store (s16))
...

---
name: store_p0_ptr
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $p0, $p1
    ; AIE2-LABEL: name: store_p0_ptr
    ; AIE2: liveins: $p0, $p1
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:ep_as_32bit = COPY $p1
    ; AIE2-NEXT: ST_dms_sts_idx_imm [[COPY1]], [[COPY]], 0 :: (store (p0), align 4)
    ;
    ; AIE2P-LABEL: name: store_p0_ptr
    ; AIE2P: liveins: $p0, $p1
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:ep_as_32bit = COPY $p1
    ; AIE2P-NEXT: ST_dms_sts_idx_imm [[COPY1]], [[COPY]], 0 :: (store (p0), align 4)
    %0:ptrregbank(p0) = COPY $p0
    %1:ptrregbank(p0) = COPY $p1
    G_STORE %1, %0 :: (store (p0))
...

---
name: store_p0_gpr
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $p0, $p1
    ; AIE2-LABEL: name: store_p0_gpr
    ; AIE2: liveins: $p0, $p1
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p1
    ; AIE2-NEXT: [[COPY2:%[0-9]+]]:er = COPY [[COPY1]]
    ; AIE2-NEXT: ST_dms_sts_idx_imm [[COPY2]], [[COPY]], 0 :: (store (p0), align 4)
    ;
    ; AIE2P-LABEL: name: store_p0_gpr
    ; AIE2P: liveins: $p0, $p1
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p1
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:er = COPY [[COPY1]]
    ; AIE2P-NEXT: ST_dms_sts_idx_imm [[COPY2]], [[COPY]], 0 :: (store (p0), align 4)
    %0:ptrregbank(p0) = COPY $p0
    %1:ptrregbank(p0) = COPY $p1
    %2:gprregbank(p0) = COPY %1
    G_STORE %2, %0 :: (store (p0))
...

---
name: store_s20
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $m0, $m6, $dc1, $dj0, $dn3, $p0
    ; AIE2-LABEL: name: store_s20
    ; AIE2: liveins: $m0, $m6, $dc1, $dj0, $dn3, $p0
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:mdm_as_32bit = COPY $m6
    ; AIE2-NEXT: ST_dms_sts_idx_imm [[COPY1]], [[COPY]], 0 :: (store (s20), align 4)
    ; AIE2-NEXT: [[COPY2:%[0-9]+]]:edc_as_32bit = COPY $dc1
    ; AIE2-NEXT: ST_dms_sts_idx_imm [[COPY2]], [[COPY]], 0 :: (store (s20), align 4)
    ; AIE2-NEXT: [[COPY3:%[0-9]+]]:edj_as_32bit = COPY $dj0
    ; AIE2-NEXT: ST_dms_sts_idx_imm [[COPY3]], [[COPY]], 0 :: (store (s20), align 4)
    ; AIE2-NEXT: [[COPY4:%[0-9]+]]:edn_as_32bit = COPY $dn3
    ; AIE2-NEXT: ST_dms_sts_idx_imm [[COPY4]], [[COPY]], 0 :: (store (s20), align 4)
    ; AIE2-NEXT: [[COPY5:%[0-9]+]]:em_as_32bit = COPY $m6
    ; AIE2-NEXT: ST_dms_sts_idx_imm [[COPY5]], [[COPY]], 0 :: (store (s20), align 4)
    ;
    ; AIE2P-LABEL: name: store_s20
    ; AIE2P: liveins: $m0, $m6, $dc1, $dj0, $dn3, $p0
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:magusrc_and_mdm = COPY $m6
    ; AIE2P-NEXT: ST_dms_sts_idx_imm [[COPY1]], [[COPY]], 0 :: (store (s20), align 4)
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:edc_as_32bit = COPY $dc1
    ; AIE2P-NEXT: ST_dms_sts_idx_imm [[COPY2]], [[COPY]], 0 :: (store (s20), align 4)
    ; AIE2P-NEXT: [[COPY3:%[0-9]+]]:edj_as_32bit = COPY $dj0
    ; AIE2P-NEXT: ST_dms_sts_idx_imm [[COPY3]], [[COPY]], 0 :: (store (s20), align 4)
    ; AIE2P-NEXT: [[COPY4:%[0-9]+]]:edn_as_32bit = COPY $dn3
    ; AIE2P-NEXT: ST_dms_sts_idx_imm [[COPY4]], [[COPY]], 0 :: (store (s20), align 4)
    ; AIE2P-NEXT: [[COPY5:%[0-9]+]]:em_as_32bit = COPY $m6
    ; AIE2P-NEXT: ST_dms_sts_idx_imm [[COPY5]], [[COPY]], 0 :: (store (s20), align 4)
    %0:ptrregbank(p0) = COPY $p0
    %1:modregbank(s20) = COPY $m6
    G_STORE %1, %0 :: (store (s20))
    %2:edc(s20) = COPY $dc1
    G_STORE %2, %0 :: (store (s20))
    %3:edj(s20) = COPY $dj0
    G_STORE %3, %0 :: (store (s20))
    %4:edn(s20) = COPY $dn3
    G_STORE %4, %0 :: (store (s20))
    %5:em(s20) = COPY $m6
    G_STORE %5, %0 :: (store (s20))
...

---
name: store_s20_gpr
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $p0, $p1
    ; AIE2-LABEL: name: store_s20_gpr
    ; AIE2: liveins: $p0, $p1
    ; AIE2-NEXT: {{  $}}
    ; AIE2-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2-NEXT: [[COPY1:%[0-9]+]]:mdm = COPY $m0
    ; AIE2-NEXT: [[COPY2:%[0-9]+]]:er = COPY [[COPY1]]
    ; AIE2-NEXT: ST_dms_sts_idx_imm [[COPY2]], [[COPY]], 0 :: (store (s20), align 4)
    ;
    ; AIE2P-LABEL: name: store_s20_gpr
    ; AIE2P: liveins: $p0, $p1
    ; AIE2P-NEXT: {{  $}}
    ; AIE2P-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; AIE2P-NEXT: [[COPY1:%[0-9]+]]:mdm = COPY $m0
    ; AIE2P-NEXT: [[COPY2:%[0-9]+]]:er = COPY [[COPY1]]
    ; AIE2P-NEXT: ST_dms_sts_idx_imm [[COPY2]], [[COPY]], 0 :: (store (s20), align 4)
    %0:ptrregbank(p0) = COPY $p0
    %1:modregbank(s20) = COPY $m0
    %2:gprregbank(s20) = COPY %1
    G_STORE %2, %0 :: (store (s20))
...
