# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            ext_256_512
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $x2
    ; CHECK-LABEL: name: ext_256_512
    ; CHECK: liveins: $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ewl = COPY [[COPY]].sub_256_lo
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec256 = COPY [[COPY1]]
    ; CHECK-NEXT: $wl0 = COPY [[COPY2]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:vregbank(<64 x s8>) = COPY $x2
    %4:gprregbank(s32) = G_CONSTANT i32 0
    %2:vregbank(<16 x s32>) = G_BITCAST %1:vregbank(<64 x s8>)
    %3:vregbank(<8 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2.ext.I256.I512), %2:vregbank(<16 x s32>), %4:gprregbank(s32)
    %0:vregbank(<32 x s8>) = G_BITCAST %3:vregbank(<8 x s32>)
    $wl0 = COPY %0:vregbank(<32 x s8>)
    PseudoRET implicit $lr, implicit $wl0
...

---
name:            ext_256_1024_0
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $y2
    ; CHECK-LABEL: name: ext_256_1024_0
    ; CHECK: liveins: $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ewle = COPY [[COPY]].sub_256_lo
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec256 = COPY [[COPY1]]
    ; CHECK-NEXT: $wl0 = COPY [[COPY2]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:vregbank(<128 x s8>) = COPY $y2
    %4:gprregbank(s32) = G_CONSTANT i32 0
    %2:vregbank(<32 x s32>) = G_BITCAST %1:vregbank(<128 x s8>)
    %3:vregbank(<8 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2.ext.I256.I1024), %2:vregbank(<32 x s32>), %4:gprregbank(s32)
    %0:vregbank(<32 x s8>) = G_BITCAST %3:vregbank(<8 x s32>)
    $wl0 = COPY %0:vregbank(<32 x s8>)
    PseudoRET implicit $lr, implicit $wl0
...

---
name:            ext_256_1024_1
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $y2
    ; CHECK-LABEL: name: ext_256_1024_1
    ; CHECK: liveins: $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ewhe = COPY [[COPY]].sub_256_hi
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec256 = COPY [[COPY1]]
    ; CHECK-NEXT: $wl0 = COPY [[COPY2]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:vregbank(<128 x s8>) = COPY $y2
    %4:gprregbank(s32) = G_CONSTANT i32 1
    %2:vregbank(<32 x s32>) = G_BITCAST %1:vregbank(<128 x s8>)
    %3:vregbank(<8 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2.ext.I256.I1024), %2:vregbank(<32 x s32>), %4:gprregbank(s32)
    %0:vregbank(<32 x s8>) = G_BITCAST %3:vregbank(<8 x s32>)
    $wl0 = COPY %0:vregbank(<32 x s8>)
    PseudoRET implicit $lr, implicit $wl0
...

---
name:            ext_256_1024_2
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $y2
    ; CHECK-LABEL: name: ext_256_1024_2
    ; CHECK: liveins: $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ewlo = COPY [[COPY]].sub_512_hi_256_lo
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec256 = COPY [[COPY1]]
    ; CHECK-NEXT: $wl0 = COPY [[COPY2]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:vregbank(<128 x s8>) = COPY $y2
    %4:gprregbank(s32) = G_CONSTANT i32 2
    %2:vregbank(<32 x s32>) = G_BITCAST %1:vregbank(<128 x s8>)
    %3:vregbank(<8 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2.ext.I256.I1024), %2:vregbank(<32 x s32>), %4:gprregbank(s32)
    %0:vregbank(<32 x s8>) = G_BITCAST %3:vregbank(<8 x s32>)
    $wl0 = COPY %0:vregbank(<32 x s8>)
    PseudoRET implicit $lr, implicit $wl0
...

---
name:            ext_256_1024_3
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $y2
    ; CHECK-LABEL: name: ext_256_1024_3
    ; CHECK: liveins: $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ewho = COPY [[COPY]].sub_512_hi_256_hi
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec256 = COPY [[COPY1]]
    ; CHECK-NEXT: $wl0 = COPY [[COPY2]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:vregbank(<128 x s8>) = COPY $y2
    %4:gprregbank(s32) = G_CONSTANT i32 3
    %2:vregbank(<32 x s32>) = G_BITCAST %1:vregbank(<128 x s8>)
    %3:vregbank(<8 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2.ext.I256.I1024), %2:vregbank(<32 x s32>), %4:gprregbank(s32)
    %0:vregbank(<32 x s8>) = G_BITCAST %3:vregbank(<8 x s32>)
    $wl0 = COPY %0:vregbank(<32 x s8>)
    PseudoRET implicit $lr, implicit $wl0
...

---
name:            ext_512_1024
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $y2
    ; CHECK-LABEL: name: ext_512_1024
    ; CHECK: liveins: $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:exe = COPY [[COPY]].sub_512_lo
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vec512 = COPY [[COPY1]]
    ; CHECK-NEXT: $x0 = COPY [[COPY2]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<128 x s8>) = COPY $y2
    %4:gprregbank(s32) = G_CONSTANT i32 0
    %2:vregbank(<32 x s32>) = G_BITCAST %1:vregbank(<128 x s8>)
    %3:vregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2.ext.I512.I1024), %2:vregbank(<32 x s32>), %4:gprregbank(s32)
    %0:vregbank(<64 x s8>) = G_BITCAST %3:vregbank(<16 x s32>)
    $x0 = COPY %0:vregbank(<64 x s8>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            ext_256_512_acc32
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bml1
    ; CHECK-LABEL: name: ext_256_512_acc32
    ; CHECK: liveins: $bml1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bml1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mams = COPY [[COPY]].sub_256_hi
    ; CHECK-NEXT: $amll0 = COPY [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $amll0
    %1:accregbank(<8 x s64>) = COPY $bml1
    %2:gprregbank(s32) = G_CONSTANT i32 1
    %0:accregbank(<4 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.ext.256.512.acc), %1:accregbank(<8 x s64>), %2:gprregbank(s32)
    $amll0 = COPY %0:accregbank(<4 x s64>)
    PseudoRET implicit $lr, implicit $amll0
...

---
name:            ext_256_512_acc64
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bml1
    ; CHECK-LABEL: name: ext_256_512_acc64
    ; CHECK: liveins: $bml1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc512 = COPY $bml1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:mams = COPY [[COPY]].sub_256_lo
    ; CHECK-NEXT: $amll0 = COPY [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $amll0
    %1:accregbank(<8 x s64>) = COPY $bml1
    %2:gprregbank(s32) = G_CONSTANT i32 0
    %0:accregbank(<4 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.ext.256.512.acc), %1:accregbank(<8 x s64>), %2:gprregbank(s32)
    $amll0 = COPY %0:accregbank(<4 x s64>)
    PseudoRET implicit $lr, implicit $amll0
...

---
name:            ext_256_1024_acc32_0
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cm1
    ; CHECK-LABEL: name: ext_256_1024_acc32_0
    ; CHECK: liveins: $cm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cm1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eamll = COPY [[COPY]].sub_256_lo
    ; CHECK-NEXT: $amll0 = COPY [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $amll0
    %1:accregbank(<16 x s64>) = COPY $cm1
    %2:gprregbank(s32) = G_CONSTANT i32 0
    %0:accregbank(<4 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.ext.256.1024.acc), %1:accregbank(<16 x s64>), %2:gprregbank(s32)
    $amll0 = COPY %0:accregbank(<4 x s64>)
    PseudoRET implicit $lr, implicit $amll0
...

---
name:            ext_256_1024_acc32_1
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cm1
    ; CHECK-LABEL: name: ext_256_1024_acc32_1
    ; CHECK: liveins: $cm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cm1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eamlh = COPY [[COPY]].sub_256_hi
    ; CHECK-NEXT: $amll0 = COPY [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $amll0
    %1:accregbank(<16 x s64>) = COPY $cm1
    %2:gprregbank(s32) = G_CONSTANT i32 1
    %0:accregbank(<4 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.ext.256.1024.acc), %1:accregbank(<16 x s64>), %2:gprregbank(s32)
    $amll0 = COPY %0:accregbank(<4 x s64>)
    PseudoRET implicit $lr, implicit $amll0
...

---
name:            ext_256_1024_acc32_2
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cm1
    ; CHECK-LABEL: name: ext_256_1024_acc32_2
    ; CHECK: liveins: $cm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cm1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eamhl = COPY [[COPY]].sub_512_hi_256_lo
    ; CHECK-NEXT: $amll0 = COPY [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $amll0
    %1:accregbank(<16 x s64>) = COPY $cm1
    %2:gprregbank(s32) = G_CONSTANT i32 2
    %0:accregbank(<4 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.ext.256.1024.acc), %1:accregbank(<16 x s64>), %2:gprregbank(s32)
    $amll0 = COPY %0:accregbank(<4 x s64>)
    PseudoRET implicit $lr, implicit $amll0
...

---
name:            ext_256_1024_acc32_3
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cm1
    ; CHECK-LABEL: name: ext_256_1024_acc32_3
    ; CHECK: liveins: $cm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cm1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eamhh = COPY [[COPY]].sub_512_hi_256_hi
    ; CHECK-NEXT: $amll0 = COPY [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $amll0
    %1:accregbank(<16 x s64>) = COPY $cm1
    %2:gprregbank(s32) = G_CONSTANT i32 3
    %0:accregbank(<4 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.ext.256.1024.acc), %1:accregbank(<16 x s64>), %2:gprregbank(s32)
    $amll0 = COPY %0:accregbank(<4 x s64>)
    PseudoRET implicit $lr, implicit $amll0
...

---
name:            ext_512_1024_acc32
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cm1
    ; CHECK-LABEL: name: ext_512_1024_acc32
    ; CHECK: liveins: $cm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cm1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ebml = COPY [[COPY]].sub_512_lo
    ; CHECK-NEXT: $bml0 = COPY [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bml0
    %1:accregbank(<16 x s64>) = COPY $cm1
    %2:gprregbank(s32) = G_CONSTANT i32 0
    %0:accregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.ext.512.1024.acc), %1:accregbank(<16 x s64>), %2:gprregbank(s32)
    $bml0 = COPY %0:accregbank(<8 x s64>)
    PseudoRET implicit $lr, implicit $bml0
...

---
name:            ext_256_1024_acc64_1
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cm1
    ; CHECK-LABEL: name: ext_256_1024_acc64_1
    ; CHECK: liveins: $cm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cm1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eamlh = COPY [[COPY]].sub_256_hi
    ; CHECK-NEXT: $amll0 = COPY [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $amll0
    %1:accregbank(<16 x s64>) = COPY $cm1
    %2:gprregbank(s32) = G_CONSTANT i32 1
    %0:accregbank(<4 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.ext.256.1024.acc), %1:accregbank(<16 x s64>), %2:gprregbank(s32)
    $amll0 = COPY %0:accregbank(<4 x s64>)
    PseudoRET implicit $lr, implicit $amll0
...

---
name:            ext_256_1024_acc64_2
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cm1
    ; CHECK-LABEL: name: ext_256_1024_acc64_2
    ; CHECK: liveins: $cm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cm1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:eamhl = COPY [[COPY]].sub_512_hi_256_lo
    ; CHECK-NEXT: $amll0 = COPY [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $amll0
    %1:accregbank(<16 x s64>) = COPY $cm1
    %2:gprregbank(s32) = G_CONSTANT i32 2
    %0:accregbank(<4 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.ext.256.1024.acc), %1:accregbank(<16 x s64>), %2:gprregbank(s32)
    $amll0 = COPY %0:accregbank(<4 x s64>)
    PseudoRET implicit $lr, implicit $amll0
...

---
name:            ext_512_1024_acc64
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cm1
    ; CHECK-LABEL: name: ext_512_1024_acc64
    ; CHECK: liveins: $cm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:acc1024 = COPY $cm1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ebml = COPY [[COPY]].sub_512_lo
    ; CHECK-NEXT: $bml0 = COPY [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bml0
    %1:accregbank(<16 x s64>) = COPY $cm1
    %2:gprregbank(s32) = G_CONSTANT i32 0
    %0:accregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.ext.512.1024.acc), %1:accregbank(<16 x s64>), %2:gprregbank(s32)
    $bml0 = COPY %0:accregbank(<8 x s64>)
    PseudoRET implicit $lr, implicit $bml0
...

---
name:            ext_512_1024_bf
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $y2
    ; CHECK-LABEL: name: ext_512_1024_bf
    ; CHECK: liveins: $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:exo = COPY [[COPY]].sub_512_hi
    ; CHECK-NEXT: $x0 = COPY [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<64 x s16>) = COPY $y2
    %3:gprregbank(s32) = G_CONSTANT i32 1
    %0:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2.ext.bf512.bf1024), %1:vregbank(<64 x s16>), %3:gprregbank(s32)
    $x0 = COPY %0:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            ext_256_1024_bf
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $y2
    ; CHECK-LABEL: name: ext_256_1024_bf
    ; CHECK: liveins: $r0, $y2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec1024 = COPY $y2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ewho = COPY [[COPY]].sub_512_hi_256_hi
    ; CHECK-NEXT: $wl0 = COPY [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %1:vregbank(<64 x s16>) = COPY $y2
    %3:gprregbank(s32) = G_CONSTANT i32 3
    %0:vregbank(<16 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2.ext.bf256.bf1024), %1:vregbank(<64 x s16>), %3:gprregbank(s32)
    $wl0 = COPY %0:vregbank(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0
...
