# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s


---
name:            test_sparsity_t_store
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $p0, $q0

    ; CHECK-LABEL: name: test_sparsity_t_store
    ; CHECK: liveins: $p0, $q0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec128 = COPY $q0
    ; CHECK-NEXT: ST_dmv_sts_q_ag_idx_imm [[COPY1]], [[COPY]], 0 :: (store (s128))
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:ptrregbank(p0) = COPY $p0
    %1:vregbank(s128) = COPY $q0
    G_STORE %1(s128), %0(p0) :: (store (s128))
    PseudoRET implicit $lr
...

---
name:            test_sparsity_t_load
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $p0

    ; CHECK-LABEL: name: test_sparsity_t_load
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[VLDA_128_:%[0-9]+]]:mwa = VLDA_128 [[COPY]] :: (load (s128))
    ; CHECK-NEXT: $q0 = COPY [[VLDA_128_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $q0
    %1:ptrregbank(p0) = COPY $p0
    %0:vregbank(s128) = G_LOAD %1(p0) :: (load (s128))
    $q0 = COPY %0(s128)
    PseudoRET implicit $lr, implicit $q0
...
