# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            512bit_splat_vector_8bit_elt
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $r0
    ; CHECK-LABEL: name: 512bit_splat_vector_8bit_elt
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[VBCST_8_:%[0-9]+]]:vec512 = VBCST_8 [[COPY]]
    ; CHECK-NEXT: $x0 = COPY [[VBCST_8_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:gprregbank(s32) = COPY $r0
    %1:vregbank(<64 x s8>) = G_AIE_BROADCAST_VECTOR %0:gprregbank(s32)
    $x0 = COPY %1:vregbank(<64 x s8>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            512bit_splat_vector_16bit_elt
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $r0
    ; CHECK-LABEL: name: 512bit_splat_vector_16bit_elt
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[VBCST_16_:%[0-9]+]]:vec512 = VBCST_16 [[COPY]]
    ; CHECK-NEXT: $x0 = COPY [[VBCST_16_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:gprregbank(s32) = COPY $r0
    %1:vregbank(<32 x s16>) = G_AIE_BROADCAST_VECTOR %0:gprregbank(s32)
    $x0 = COPY %1:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            512bit_splat_vector_32bit_elt
legalized:       true
regBankSelected: true
selected:        false
body:             |
  bb.1.entry:
    liveins: $r0
    ; CHECK-LABEL: name: 512bit_splat_vector_32bit_elt
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[VBCST_32_:%[0-9]+]]:vec512 = VBCST_32 [[COPY]]
    ; CHECK-NEXT: $x0 = COPY [[VBCST_32_]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:gprregbank(s32) = COPY $r0
    %1:vregbank(<16 x s32>) = G_AIE_BROADCAST_VECTOR %0:gprregbank(s32)
    $x0 = COPY %1:vregbank(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0
...
