# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s
---
name: g_trunc_v2i32_to_i32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $l0

    ; CHECK-LABEL: name: g_trunc_v2i32_to_i32
    ; CHECK: liveins: $l0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:el = COPY $l0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY [[COPY]].sub_l_even
    ; CHECK-NEXT: $r0 = COPY [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:gprregbank(<2 x s32>) = COPY $l0
    %5:gprregbank(s64) = G_BITCAST %1(<2 x s32>)
    %3:gprregbank(s32) = G_TRUNC %5(s64)
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0
...
---
name: g_trunc_i64_to_i32
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $l0

    ; CHECK-LABEL: name: g_trunc_i64_to_i32
    ; CHECK: liveins: $l0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:el = COPY $l0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY [[COPY]].sub_l_even
    ; CHECK-NEXT: $r0 = COPY [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:gprregbank(s64) = COPY $l0
    %2:gprregbank(s32) = G_TRUNC %1(s64)
    $r0 = COPY %2(s32)
    PseudoRET implicit $lr, implicit $r0

...
---
name: g_trunc_i64_to_i20
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $l0

    ; CHECK-LABEL: name: g_trunc_i64_to_i20
    ; CHECK: liveins: $l0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:el = COPY $l0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY [[COPY]].sub_l_even
    ; CHECK-NEXT: $r0 = COPY [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:gprregbank(s64) = COPY $l0
    %2:gprregbank(s20) = G_TRUNC %1(s64)
    %3:gprregbank(s32) = G_ZEXT %2(s20)
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0
...
---
