# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            VSHUFFLE_vregbank
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x2, $x4
    ; CHECK-LABEL: name: VSHUFFLE_vregbank
    ; CHECK: liveins: $r0, $x2, $x4
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x4
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[VSHUFFLE:%[0-9]+]]:vec512 = VSHUFFLE [[COPY]], [[COPY1]], [[COPY2]]
    ; CHECK-NEXT: $x0 = COPY [[VSHUFFLE]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<32 x s16>) = COPY $x2
    %2:vregbank(<32 x s16>) = COPY $x4
    %3:gprregbank(s32) = COPY $r0
    %4:vregbank(<16 x s32>) = G_BITCAST %1:vregbank(<32 x s16>)
    %5:vregbank(<16 x s32>) = G_BITCAST %2:vregbank(<32 x s16>)
    %0:vregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2.vshuffle), %4:vregbank(<16 x s32>), %5:vregbank(<16 x s32>), %3:gprregbank(s32)
    $x0 = COPY %0:vregbank(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            VSHUFFLE_bf
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $x2, $x4
    ; CHECK-LABEL: name: VSHUFFLE_bf
    ; CHECK: liveins: $r0, $x2, $x4
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vec512 = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vec512 = COPY $x4
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[VSHUFFLE:%[0-9]+]]:vec512 = VSHUFFLE [[COPY]], [[COPY1]], [[COPY2]]
    ; CHECK-NEXT: $x0 = COPY [[VSHUFFLE]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %1:vregbank(<32 x s16>) = COPY $x2
    %2:vregbank(<32 x s16>) = COPY $x4
    %3:gprregbank(s32) = COPY $r0
    %0:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2.vshuffle.bf16), %1:vregbank(<32 x s16>), %2:vregbank(<32 x s16>), %3:gprregbank(s32)
    $x0 = COPY %0:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...
