# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            acc256
tracksRegLiveness: true
legalized: true
regBankSelected: true
body:             |
  ; CHECK-LABEL: name: acc256
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x50000000), %bb.2(0x30000000)
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %cond:er = IMPLICIT_DEF
  ; CHECK-NEXT:   %val_1:acc256 = IMPLICIT_DEF
  ; CHECK-NEXT:   PseudoJNZ %cond, %bb.2
  ; CHECK-NEXT:   PseudoJ_jump_imm %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %val_2:acc256 = IMPLICIT_DEF
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   %phi:acc256 = PHI %val_2, %bb.1, %val_1, %bb.0
  ; CHECK-NEXT:   $wl0 = COPY %phi
  bb.0:
    successors: %bb.1(0x50000000), %bb.2(0x30000000)
    liveins: $r0
    %cond:gprregbank(s32) = G_IMPLICIT_DEF
    %val_1:accregbank(<4 x s64>) = G_IMPLICIT_DEF
    G_BRCOND %cond(s32), %bb.2
    G_BR %bb.1
  bb.1:
    %val_2:accregbank(<4 x s64>) = G_IMPLICIT_DEF
  bb.2:
    %phi:accregbank(<4 x s64>) = G_PHI %val_2(<4 x s64>), %bb.1, %val_1(<4 x s64>), %bb.0
    $wl0 = COPY %phi
...
