# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            VST_SRS_D16_S32
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bml0, $p0, $r1
    ; CHECK-LABEL: name: VST_SRS_D16_S32
    ; CHECK: liveins: $bml0, $p0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm10_pseudo:%[0-9]+]]:edj = MOV_PD_imm10_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm10_pseudo1:%[0-9]+]]:edj = MOV_PD_imm10_pseudo 128
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY $bml0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx [[COPY]], [[COPY1]], [[COPY2]], [[COPY4]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>))
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx_imm [[COPY]], 0, [[COPY2]], [[COPY5]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>))
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx [[COPY]], [[MOV_PD_imm10_pseudo]], [[COPY2]], [[COPY6]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>))
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx_imm [[COPY]], -128, [[COPY2]], [[COPY7]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>))
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx_imm [[COPY]], 96, [[COPY2]], [[COPY8]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>))
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx [[COPY]], [[MOV_PD_imm10_pseudo1]], [[COPY2]], [[COPY9]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>))
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -128
    %11:modregbank(s20) = G_CONSTANT i20 96
    %12:modregbank(s20) = G_CONSTANT i20 128
    %100:accregbank(<8 x s64>) = COPY $bml0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %103:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<16 x s16>))
...

---
name:            VST_SRS_D16_S32_dyn
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bml0, $p0, $r1
    ; CHECK-LABEL: name: VST_SRS_D16_S32_dyn
    ; CHECK: liveins: $bml0, $p0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm10_pseudo:%[0-9]+]]:edj = MOV_PD_imm10_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm10_pseudo1:%[0-9]+]]:edj = MOV_PD_imm10_pseudo 128
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY $bml0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx [[COPY]], [[COPY1]], [[COPY2]], [[COPY5]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx_imm [[COPY]], 0, [[COPY2]], [[COPY6]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx [[COPY]], [[MOV_PD_imm10_pseudo]], [[COPY2]], [[COPY7]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx_imm [[COPY]], -128, [[COPY2]], [[COPY8]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx_imm [[COPY]], 96, [[COPY2]], [[COPY9]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx [[COPY]], [[MOV_PD_imm10_pseudo1]], [[COPY2]], [[COPY10]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -128
    %11:modregbank(s20) = G_CONSTANT i20 96
    %12:modregbank(s20) = G_CONSTANT i20 128
    %100:accregbank(<8 x s64>) = COPY $bml0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = COPY $r1
    %103:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<16 x s16>))
...

---
name:            VST_SRS_S16_S32
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bml0, $p0, $r1
    ; CHECK-LABEL: name: VST_SRS_S16_S32
    ; CHECK: liveins: $bml0, $p0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm10_pseudo:%[0-9]+]]:edj = MOV_PD_imm10_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm10_pseudo1:%[0-9]+]]:edj = MOV_PD_imm10_pseudo 128
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY $bml0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S16_S32_ag_idx [[COPY]], [[COPY1]], [[COPY2]], [[COPY4]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<16 x s16>))
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S16_S32_ag_idx_imm [[COPY]], 0, [[COPY2]], [[COPY5]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<16 x s16>))
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S16_S32_ag_idx [[COPY]], [[MOV_PD_imm10_pseudo]], [[COPY2]], [[COPY6]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<16 x s16>))
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S16_S32_ag_idx_imm [[COPY]], -128, [[COPY2]], [[COPY7]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<16 x s16>))
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S16_S32_ag_idx_imm [[COPY]], 96, [[COPY2]], [[COPY8]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<16 x s16>))
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S16_S32_ag_idx [[COPY]], [[MOV_PD_imm10_pseudo1]], [[COPY2]], [[COPY9]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<16 x s16>))
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -128
    %11:modregbank(s20) = G_CONSTANT i20 96
    %12:modregbank(s20) = G_CONSTANT i20 128
    %100:accregbank(<8 x s64>) = COPY $bml0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %103:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc32.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<16 x s16>))
...

---
name:            VST_SRS_D32_S64
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bml0, $p0, $r1
    ; CHECK-LABEL: name: VST_SRS_D32_S64
    ; CHECK: liveins: $bml0, $p0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm10_pseudo:%[0-9]+]]:edj = MOV_PD_imm10_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm10_pseudo1:%[0-9]+]]:edj = MOV_PD_imm10_pseudo 128
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY $bml0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx [[COPY]], [[COPY1]], [[COPY2]], [[COPY4]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>))
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx_imm [[COPY]], 0, [[COPY2]], [[COPY5]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>))
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx [[COPY]], [[MOV_PD_imm10_pseudo]], [[COPY2]], [[COPY6]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>))
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx_imm [[COPY]], -128, [[COPY2]], [[COPY7]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>))
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx_imm [[COPY]], 96, [[COPY2]], [[COPY8]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>))
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx [[COPY]], [[MOV_PD_imm10_pseudo1]], [[COPY2]], [[COPY9]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>))
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -128
    %11:modregbank(s20) = G_CONSTANT i20 96
    %12:modregbank(s20) = G_CONSTANT i20 128
    %100:accregbank(<8 x s64>) = COPY $bml0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %103:vregbank(<8 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<8 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<8 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<8 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<8 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<8 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<8 x s32>))
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<8 x s32>))
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<8 x s32>))
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<8 x s32>))
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<8 x s32>))
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<8 x s32>))
...

---
name:            VST_SRS_D32_S64_dyn
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bml0, $p0, $r1
    ; CHECK-LABEL: name: VST_SRS_D32_S64_dyn
    ; CHECK: liveins: $bml0, $p0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm10_pseudo:%[0-9]+]]:edj = MOV_PD_imm10_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm10_pseudo1:%[0-9]+]]:edj = MOV_PD_imm10_pseudo 128
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY $bml0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx [[COPY]], [[COPY1]], [[COPY2]], [[COPY5]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>))
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx_imm [[COPY]], 0, [[COPY2]], [[COPY6]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>))
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx [[COPY]], [[MOV_PD_imm10_pseudo]], [[COPY2]], [[COPY7]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>))
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx_imm [[COPY]], -128, [[COPY2]], [[COPY8]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>))
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx_imm [[COPY]], 96, [[COPY2]], [[COPY9]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>))
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx [[COPY]], [[MOV_PD_imm10_pseudo1]], [[COPY2]], [[COPY10]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>))
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -128
    %11:modregbank(s20) = G_CONSTANT i20 96
    %12:modregbank(s20) = G_CONSTANT i20 128
    %100:accregbank(<8 x s64>) = COPY $bml0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = COPY $r1
    %103:vregbank(<8 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<8 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<8 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<8 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<8 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<8 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<8 x s32>))
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<8 x s32>))
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<8 x s32>))
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<8 x s32>))
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<8 x s32>))
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<8 x s32>))
...

---
name:            VST_SRS_S32_S64
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $bml0, $p0, $r1
    ; CHECK-LABEL: name: VST_SRS_S32_S64
    ; CHECK: liveins: $bml0, $p0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm10_pseudo:%[0-9]+]]:edj = MOV_PD_imm10_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm10_pseudo1:%[0-9]+]]:edj = MOV_PD_imm10_pseudo 128
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc512 = COPY $bml0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S32_S64_ag_idx [[COPY]], [[COPY1]], [[COPY2]], [[COPY4]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<8 x s32>))
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S32_S64_ag_idx_imm [[COPY]], 0, [[COPY2]], [[COPY5]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<8 x s32>))
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S32_S64_ag_idx [[COPY]], [[MOV_PD_imm10_pseudo]], [[COPY2]], [[COPY6]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<8 x s32>))
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S32_S64_ag_idx_imm [[COPY]], -128, [[COPY2]], [[COPY7]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<8 x s32>))
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S32_S64_ag_idx_imm [[COPY]], 96, [[COPY2]], [[COPY8]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<8 x s32>))
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S32_S64_ag_idx [[COPY]], [[MOV_PD_imm10_pseudo1]], [[COPY2]], [[COPY9]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<8 x s32>))
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -128
    %11:modregbank(s20) = G_CONSTANT i20 96
    %12:modregbank(s20) = G_CONSTANT i20 128
    %100:accregbank(<8 x s64>) = COPY $bml0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %103:vregbank(<8 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<8 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<8 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<8 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<8 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<8 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v8.acc64.srs), %100:accregbank(<8 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<8 x s32>))
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<8 x s32>))
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<8 x s32>))
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<8 x s32>))
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<8 x s32>))
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<8 x s32>))
...

---
name:            VST_SRS_D16_S64
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cm0, $p0, $r1
    ; CHECK-LABEL: name: VST_SRS_D16_S64
    ; CHECK: liveins: $cm0, $p0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm10_pseudo:%[0-9]+]]:edj = MOV_PD_imm10_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm10_pseudo1:%[0-9]+]]:edj = MOV_PD_imm10_pseudo 128
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc1024 = COPY $cm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S64_ag_idx [[COPY]], [[COPY1]], [[COPY2]], [[COPY4]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>))
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S64_ag_idx_imm [[COPY]], 0, [[COPY2]], [[COPY5]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>))
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S64_ag_idx [[COPY]], [[MOV_PD_imm10_pseudo]], [[COPY2]], [[COPY6]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>))
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S64_ag_idx_imm [[COPY]], -128, [[COPY2]], [[COPY7]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>))
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S64_ag_idx_imm [[COPY]], 96, [[COPY2]], [[COPY8]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>))
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S64_ag_idx [[COPY]], [[MOV_PD_imm10_pseudo1]], [[COPY2]], [[COPY9]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>))
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -128
    %11:modregbank(s20) = G_CONSTANT i20 96
    %12:modregbank(s20) = G_CONSTANT i20 128
    %100:accregbank(<16 x s64>) = COPY $cm0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %103:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<16 x s16>))
...

---
name:            VST_SRS_D16_S64_dyn
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cm0, $p0, $r1
    ; CHECK-LABEL: name: VST_SRS_D16_S64_dyn
    ; CHECK: liveins: $cm0, $p0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm10_pseudo:%[0-9]+]]:edj = MOV_PD_imm10_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm10_pseudo1:%[0-9]+]]:edj = MOV_PD_imm10_pseudo 128
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc1024 = COPY $cm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S64_ag_idx [[COPY]], [[COPY1]], [[COPY2]], [[COPY5]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S64_ag_idx_imm [[COPY]], 0, [[COPY2]], [[COPY6]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S64_ag_idx [[COPY]], [[MOV_PD_imm10_pseudo]], [[COPY2]], [[COPY7]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S64_ag_idx_imm [[COPY]], -128, [[COPY2]], [[COPY8]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S64_ag_idx_imm [[COPY]], 96, [[COPY2]], [[COPY9]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S64_ag_idx [[COPY]], [[MOV_PD_imm10_pseudo1]], [[COPY2]], [[COPY10]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>))
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -128
    %11:modregbank(s20) = G_CONSTANT i20 96
    %12:modregbank(s20) = G_CONSTANT i20 128
    %100:accregbank(<16 x s64>) = COPY $cm0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = COPY $r1
    %103:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<16 x s16>))
...

---
name:            VST_SRS_S16_S64
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cm0, $p0, $r1
    ; CHECK-LABEL: name: VST_SRS_S16_S64
    ; CHECK: liveins: $cm0, $p0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm10_pseudo:%[0-9]+]]:edj = MOV_PD_imm10_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm10_pseudo1:%[0-9]+]]:edj = MOV_PD_imm10_pseudo 128
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc1024 = COPY $cm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S16_S64_ag_idx [[COPY]], [[COPY1]], [[COPY2]], [[COPY4]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<16 x s16>))
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S16_S64_ag_idx_imm [[COPY]], 0, [[COPY2]], [[COPY5]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<16 x s16>))
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S16_S64_ag_idx [[COPY]], [[MOV_PD_imm10_pseudo]], [[COPY2]], [[COPY6]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<16 x s16>))
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S16_S64_ag_idx_imm [[COPY]], -128, [[COPY2]], [[COPY7]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<16 x s16>))
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S16_S64_ag_idx_imm [[COPY]], 96, [[COPY2]], [[COPY8]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<16 x s16>))
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S16_S64_ag_idx [[COPY]], [[MOV_PD_imm10_pseudo1]], [[COPY2]], [[COPY9]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<16 x s16>))
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -128
    %11:modregbank(s20) = G_CONSTANT i20 96
    %12:modregbank(s20) = G_CONSTANT i20 128
    %100:accregbank(<16 x s64>) = COPY $cm0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %103:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<16 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<16 x s16>))
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<16 x s16>))
...

---
name:            VST_SRS_D8_S32
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cm0, $p0, $r1
    ; CHECK-LABEL: name: VST_SRS_D8_S32
    ; CHECK: liveins: $cm0, $p0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm10_pseudo:%[0-9]+]]:edj = MOV_PD_imm10_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm10_pseudo1:%[0-9]+]]:edj = MOV_PD_imm10_pseudo 128
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc1024 = COPY $cm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D8_S32_ag_idx [[COPY]], [[COPY1]], [[COPY2]], [[COPY4]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<32 x s8>))
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D8_S32_ag_idx_imm [[COPY]], 0, [[COPY2]], [[COPY5]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<32 x s8>))
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D8_S32_ag_idx [[COPY]], [[MOV_PD_imm10_pseudo]], [[COPY2]], [[COPY6]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<32 x s8>))
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D8_S32_ag_idx_imm [[COPY]], -128, [[COPY2]], [[COPY7]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<32 x s8>))
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D8_S32_ag_idx_imm [[COPY]], 96, [[COPY2]], [[COPY8]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<32 x s8>))
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D8_S32_ag_idx [[COPY]], [[MOV_PD_imm10_pseudo1]], [[COPY2]], [[COPY9]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<32 x s8>))
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -128
    %11:modregbank(s20) = G_CONSTANT i20 96
    %12:modregbank(s20) = G_CONSTANT i20 128
    %100:accregbank(<16 x s64>) = COPY $cm0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %103:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<32 x s8>))
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<32 x s8>))
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<32 x s8>))
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<32 x s8>))
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<32 x s8>))
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<32 x s8>))
...

---
name:            VST_SRS_D8_S32_dyn
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cm0, $p0, $r1
    ; CHECK-LABEL: name: VST_SRS_D8_S32_dyn
    ; CHECK: liveins: $cm0, $p0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm10_pseudo:%[0-9]+]]:edj = MOV_PD_imm10_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm10_pseudo1:%[0-9]+]]:edj = MOV_PD_imm10_pseudo 128
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc1024 = COPY $cm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D8_S32_ag_idx [[COPY]], [[COPY1]], [[COPY2]], [[COPY5]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<32 x s8>))
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D8_S32_ag_idx_imm [[COPY]], 0, [[COPY2]], [[COPY6]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<32 x s8>))
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D8_S32_ag_idx [[COPY]], [[MOV_PD_imm10_pseudo]], [[COPY2]], [[COPY7]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<32 x s8>))
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D8_S32_ag_idx_imm [[COPY]], -128, [[COPY2]], [[COPY8]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<32 x s8>))
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D8_S32_ag_idx_imm [[COPY]], 96, [[COPY2]], [[COPY9]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<32 x s8>))
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D8_S32_ag_idx [[COPY]], [[MOV_PD_imm10_pseudo1]], [[COPY2]], [[COPY10]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<32 x s8>))
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -128
    %11:modregbank(s20) = G_CONSTANT i20 96
    %12:modregbank(s20) = G_CONSTANT i20 128
    %100:accregbank(<16 x s64>) = COPY $cm0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = COPY $r1
    %103:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<32 x s8>))
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<32 x s8>))
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<32 x s8>))
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<32 x s8>))
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<32 x s8>))
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<32 x s8>))
...

---
name:            VST_SRS_S8_S32
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cm0, $p0, $r1
    ; CHECK-LABEL: name: VST_SRS_S8_S32
    ; CHECK: liveins: $cm0, $p0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[MOV_PD_imm10_pseudo:%[0-9]+]]:edj = MOV_PD_imm10_pseudo 16
    ; CHECK-NEXT: [[MOV_PD_imm10_pseudo1:%[0-9]+]]:edj = MOV_PD_imm10_pseudo 128
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc1024 = COPY $cm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S8_S32_ag_idx [[COPY]], [[COPY1]], [[COPY2]], [[COPY4]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<32 x s8>))
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S8_S32_ag_idx_imm [[COPY]], 0, [[COPY2]], [[COPY5]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<32 x s8>))
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S8_S32_ag_idx [[COPY]], [[MOV_PD_imm10_pseudo]], [[COPY2]], [[COPY6]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<32 x s8>))
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S8_S32_ag_idx_imm [[COPY]], -128, [[COPY2]], [[COPY7]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<32 x s8>))
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S8_S32_ag_idx_imm [[COPY]], 96, [[COPY2]], [[COPY8]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<32 x s8>))
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S8_S32_ag_idx [[COPY]], [[MOV_PD_imm10_pseudo1]], [[COPY2]], [[COPY9]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<32 x s8>))
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -128
    %11:modregbank(s20) = G_CONSTANT i20 96
    %12:modregbank(s20) = G_CONSTANT i20 128
    %100:accregbank(<16 x s64>) = COPY $cm0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %103:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<32 x s8>))
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<32 x s8>))
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<32 x s8>))
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<32 x s8>))
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<32 x s8>))
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<32 x s8>))
...

---
name:            VST_SRS_D16_S32_512_bits
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $m0, $r1, $amll0
    ; CHECK-LABEL: name: VST_SRS_D16_S32_512_bits
    ; CHECK: liveins: $p0, $m0, $r1, $amll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:em = COPY $m0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc1024 = COPY $cm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: [[PADD_mod_pseudo:%[0-9]+]]:ep = PADD_mod_pseudo [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx_imm [[PADD_mod_pseudo]], 32, [[COPY5]], [[COPY6]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx_imm [[PADD_mod_pseudo]], 0, [[COPY4]], [[COPY7]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>) into stack - 64, align 64)
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx_imm [[COPY]], 32, [[COPY9]], [[COPY10]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx_imm [[COPY]], 0, [[COPY8]], [[COPY11]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>) into stack - 64, align 64)
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: [[PADD_imm9_pseudo:%[0-9]+]]:ep = PADD_imm9_pseudo [[COPY]], 16
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx_imm [[PADD_imm9_pseudo]], 32, [[COPY13]], [[COPY14]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx_imm [[PADD_imm9_pseudo]], 0, [[COPY12]], [[COPY15]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>) into stack - 64, align 64)
    ; CHECK-NEXT: [[COPY16:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY17:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: [[COPY18:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx_imm [[COPY]], -96, [[COPY17]], [[COPY18]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY19:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx_imm [[COPY]], -128, [[COPY16]], [[COPY19]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>) into stack - 64, align 64)
    ; CHECK-NEXT: [[COPY20:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY21:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: [[COPY22:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx_imm [[COPY]], 96, [[COPY21]], [[COPY22]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY23:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx_imm [[COPY]], 64, [[COPY20]], [[COPY23]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>) into stack - 64, align 64)
    ; CHECK-NEXT: [[COPY24:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY25:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: [[PADD_imm9_pseudo1:%[0-9]+]]:ep = PADD_imm9_pseudo [[COPY]], 96
    ; CHECK-NEXT: [[COPY26:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx_imm [[PADD_imm9_pseudo1]], 32, [[COPY25]], [[COPY26]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY27:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx_imm [[PADD_imm9_pseudo1]], 0, [[COPY24]], [[COPY27]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>) into stack - 64, align 64)
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -128
    %11:modregbank(s20) = G_CONSTANT i20 64
    %12:modregbank(s20) = G_CONSTANT i20 96
    %100:accregbank(<16 x s64>) = COPY $cm0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %103:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<32 x s16>) into stack - 64)
...

---
name:            VST_SRS_D16_S32_512_bits_dyn
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $m0, $r1, $amll0
    ; CHECK-LABEL: name: VST_SRS_D16_S32_512_bits_dyn
    ; CHECK: liveins: $p0, $m0, $r1, $amll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:em = COPY $m0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc1024 = COPY $cm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: [[PADD_mod_pseudo:%[0-9]+]]:ep = PADD_mod_pseudo [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx_imm [[PADD_mod_pseudo]], 32, [[COPY6]], [[COPY7]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx_imm [[PADD_mod_pseudo]], 0, [[COPY5]], [[COPY8]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>) into stack - 64, align 64)
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx_imm [[COPY]], 32, [[COPY10]], [[COPY11]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx_imm [[COPY]], 0, [[COPY9]], [[COPY12]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>) into stack - 64, align 64)
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: [[PADD_imm9_pseudo:%[0-9]+]]:ep = PADD_imm9_pseudo [[COPY]], 16
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx_imm [[PADD_imm9_pseudo]], 32, [[COPY14]], [[COPY15]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY16:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx_imm [[PADD_imm9_pseudo]], 0, [[COPY13]], [[COPY16]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>) into stack - 64, align 64)
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    ; CHECK-NEXT: [[COPY17:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY18:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY19:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx_imm [[COPY]], -96, [[COPY18]], [[COPY19]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY20:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx_imm [[COPY]], -128, [[COPY17]], [[COPY20]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>) into stack - 64, align 64)
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    ; CHECK-NEXT: [[COPY21:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY22:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY23:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx_imm [[COPY]], 96, [[COPY22]], [[COPY23]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY24:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx_imm [[COPY]], 64, [[COPY21]], [[COPY24]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>) into stack - 64, align 64)
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    ; CHECK-NEXT: [[COPY25:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY26:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: [[PADD_imm9_pseudo1:%[0-9]+]]:ep = PADD_imm9_pseudo [[COPY]], 96
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY27:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx_imm [[PADD_imm9_pseudo1]], 32, [[COPY26]], [[COPY27]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY28:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D16_S32_ag_idx_imm [[PADD_imm9_pseudo1]], 0, [[COPY25]], [[COPY28]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<16 x s16>) into stack - 64, align 64)
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -128
    %11:modregbank(s20) = G_CONSTANT i20 64
    %12:modregbank(s20) = G_CONSTANT i20 96
    %100:accregbank(<16 x s64>) = COPY $cm0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = COPY $r1
    %103:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<32 x s16>) into stack - 64)
...

---
name:            VST_SRS_S16_S32_512_bits
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $m0, $r1, $amll0
    ; CHECK-LABEL: name: VST_SRS_S16_S32_512_bits
    ; CHECK: liveins: $p0, $m0, $r1, $amll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:em = COPY $m0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc1024 = COPY $cm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: [[PADD_mod_pseudo:%[0-9]+]]:ep = PADD_mod_pseudo [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S16_S32_ag_idx_imm [[PADD_mod_pseudo]], 32, [[COPY5]], [[COPY6]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<16 x s16>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S16_S32_ag_idx_imm [[PADD_mod_pseudo]], 0, [[COPY4]], [[COPY7]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<16 x s16>) into stack - 64, align 64)
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S16_S32_ag_idx_imm [[COPY]], 32, [[COPY9]], [[COPY10]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<16 x s16>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S16_S32_ag_idx_imm [[COPY]], 0, [[COPY8]], [[COPY11]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<16 x s16>) into stack - 64, align 64)
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: [[PADD_imm9_pseudo:%[0-9]+]]:ep = PADD_imm9_pseudo [[COPY]], 16
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S16_S32_ag_idx_imm [[PADD_imm9_pseudo]], 32, [[COPY13]], [[COPY14]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<16 x s16>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S16_S32_ag_idx_imm [[PADD_imm9_pseudo]], 0, [[COPY12]], [[COPY15]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<16 x s16>) into stack - 64, align 64)
    ; CHECK-NEXT: [[COPY16:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY17:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: [[COPY18:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S16_S32_ag_idx_imm [[COPY]], -96, [[COPY17]], [[COPY18]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<16 x s16>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY19:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S16_S32_ag_idx_imm [[COPY]], -128, [[COPY16]], [[COPY19]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<16 x s16>) into stack - 64, align 64)
    ; CHECK-NEXT: [[COPY20:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY21:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: [[COPY22:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S16_S32_ag_idx_imm [[COPY]], 96, [[COPY21]], [[COPY22]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<16 x s16>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY23:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S16_S32_ag_idx_imm [[COPY]], 64, [[COPY20]], [[COPY23]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<16 x s16>) into stack - 64, align 64)
    ; CHECK-NEXT: [[COPY24:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY25:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: [[PADD_imm9_pseudo1:%[0-9]+]]:ep = PADD_imm9_pseudo [[COPY]], 96
    ; CHECK-NEXT: [[COPY26:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S16_S32_ag_idx_imm [[PADD_imm9_pseudo1]], 32, [[COPY25]], [[COPY26]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<16 x s16>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY27:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S16_S32_ag_idx_imm [[PADD_imm9_pseudo1]], 0, [[COPY24]], [[COPY27]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<16 x s16>) into stack - 64, align 64)
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -128
    %11:modregbank(s20) = G_CONSTANT i20 64
    %12:modregbank(s20) = G_CONSTANT i20 96
    %100:accregbank(<16 x s64>) = COPY $cm0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %103:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<32 x s16>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<32 x s16>) into stack - 64)
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<32 x s16>) into stack - 64)
...

---
name:            VST_SRS_D32_S64_512_bits
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $m0, $r1, $amll0
    ; CHECK-LABEL: name: VST_SRS_D32_S64_512_bits
    ; CHECK: liveins: $p0, $m0, $r1, $amll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:em = COPY $m0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc1024 = COPY $cm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: [[PADD_mod_pseudo:%[0-9]+]]:ep = PADD_mod_pseudo [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx_imm [[PADD_mod_pseudo]], 32, [[COPY5]], [[COPY6]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx_imm [[PADD_mod_pseudo]], 0, [[COPY4]], [[COPY7]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>) into stack - 64, align 64)
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx_imm [[COPY]], 32, [[COPY9]], [[COPY10]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx_imm [[COPY]], 0, [[COPY8]], [[COPY11]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>) into stack - 64, align 64)
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: [[PADD_imm9_pseudo:%[0-9]+]]:ep = PADD_imm9_pseudo [[COPY]], 16
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx_imm [[PADD_imm9_pseudo]], 32, [[COPY13]], [[COPY14]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx_imm [[PADD_imm9_pseudo]], 0, [[COPY12]], [[COPY15]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>) into stack - 64, align 64)
    ; CHECK-NEXT: [[COPY16:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY17:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: [[COPY18:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx_imm [[COPY]], -96, [[COPY17]], [[COPY18]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY19:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx_imm [[COPY]], -128, [[COPY16]], [[COPY19]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>) into stack - 64, align 64)
    ; CHECK-NEXT: [[COPY20:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY21:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: [[COPY22:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx_imm [[COPY]], 96, [[COPY21]], [[COPY22]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY23:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx_imm [[COPY]], 64, [[COPY20]], [[COPY23]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>) into stack - 64, align 64)
    ; CHECK-NEXT: [[COPY24:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY25:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: [[PADD_imm9_pseudo1:%[0-9]+]]:ep = PADD_imm9_pseudo [[COPY]], 96
    ; CHECK-NEXT: [[COPY26:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx_imm [[PADD_imm9_pseudo1]], 32, [[COPY25]], [[COPY26]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY27:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx_imm [[PADD_imm9_pseudo1]], 0, [[COPY24]], [[COPY27]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>) into stack - 64, align 64)
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -128
    %11:modregbank(s20) = G_CONSTANT i20 64
    %12:modregbank(s20) = G_CONSTANT i20 96
    %100:accregbank(<16 x s64>) = COPY $cm0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %103:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<16 x s32>) into stack - 64)
...

---
name:            VST_SRS_D32_S64_512_bits_dyn
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $m0, $r1, $amll0
    ; CHECK-LABEL: name: VST_SRS_D32_S64_512_bits_dyn
    ; CHECK: liveins: $p0, $m0, $r1, $amll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:em = COPY $m0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc1024 = COPY $cm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: [[PADD_mod_pseudo:%[0-9]+]]:ep = PADD_mod_pseudo [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx_imm [[PADD_mod_pseudo]], 32, [[COPY6]], [[COPY7]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx_imm [[PADD_mod_pseudo]], 0, [[COPY5]], [[COPY8]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>) into stack - 64, align 64)
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx_imm [[COPY]], 32, [[COPY10]], [[COPY11]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx_imm [[COPY]], 0, [[COPY9]], [[COPY12]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>) into stack - 64, align 64)
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: [[PADD_imm9_pseudo:%[0-9]+]]:ep = PADD_imm9_pseudo [[COPY]], 16
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx_imm [[PADD_imm9_pseudo]], 32, [[COPY14]], [[COPY15]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY16:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx_imm [[PADD_imm9_pseudo]], 0, [[COPY13]], [[COPY16]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>) into stack - 64, align 64)
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    ; CHECK-NEXT: [[COPY17:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY18:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY19:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx_imm [[COPY]], -96, [[COPY18]], [[COPY19]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY20:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx_imm [[COPY]], -128, [[COPY17]], [[COPY20]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>) into stack - 64, align 64)
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    ; CHECK-NEXT: [[COPY21:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY22:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY23:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx_imm [[COPY]], 96, [[COPY22]], [[COPY23]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY24:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx_imm [[COPY]], 64, [[COPY21]], [[COPY24]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>) into stack - 64, align 64)
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    ; CHECK-NEXT: [[COPY25:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY26:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: [[PADD_imm9_pseudo1:%[0-9]+]]:ep = PADD_imm9_pseudo [[COPY]], 96
    ; CHECK-NEXT: $crsrssign = COPY [[COPY4]]
    ; CHECK-NEXT: [[COPY27:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx_imm [[PADD_imm9_pseudo1]], 32, [[COPY26]], [[COPY27]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY28:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_D32_S64_ag_idx_imm [[PADD_imm9_pseudo1]], 0, [[COPY25]], [[COPY28]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>) into stack - 64, align 64)
    ; CHECK-NEXT: $crsrssign = MOV_scalar_imm10_pseudo 0
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -128
    %11:modregbank(s20) = G_CONSTANT i20 64
    %12:modregbank(s20) = G_CONSTANT i20 96
    %100:accregbank(<16 x s64>) = COPY $cm0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = COPY $r1
    %103:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<16 x s32>) into stack - 64)
...

---
name:            VST_SRS_S32_S64_512_bits
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $m0, $r1, $amll0
    ; CHECK-LABEL: name: VST_SRS_S32_S64_512_bits
    ; CHECK: liveins: $p0, $m0, $r1, $amll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:em = COPY $m0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:acc1024 = COPY $cm0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: [[PADD_mod_pseudo:%[0-9]+]]:ep = PADD_mod_pseudo [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[COPY6:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S32_S64_ag_idx_imm [[PADD_mod_pseudo]], 32, [[COPY5]], [[COPY6]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<8 x s32>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY7:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S32_S64_ag_idx_imm [[PADD_mod_pseudo]], 0, [[COPY4]], [[COPY7]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<8 x s32>) into stack - 64, align 64)
    ; CHECK-NEXT: [[COPY8:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY9:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: [[COPY10:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S32_S64_ag_idx_imm [[COPY]], 32, [[COPY9]], [[COPY10]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<8 x s32>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY11:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S32_S64_ag_idx_imm [[COPY]], 0, [[COPY8]], [[COPY11]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<8 x s32>) into stack - 64, align 64)
    ; CHECK-NEXT: [[COPY12:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY13:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: [[PADD_imm9_pseudo:%[0-9]+]]:ep = PADD_imm9_pseudo [[COPY]], 16
    ; CHECK-NEXT: [[COPY14:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S32_S64_ag_idx_imm [[PADD_imm9_pseudo]], 32, [[COPY13]], [[COPY14]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<8 x s32>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY15:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S32_S64_ag_idx_imm [[PADD_imm9_pseudo]], 0, [[COPY12]], [[COPY15]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<8 x s32>) into stack - 64, align 64)
    ; CHECK-NEXT: [[COPY16:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY17:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: [[COPY18:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S32_S64_ag_idx_imm [[COPY]], -96, [[COPY17]], [[COPY18]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<8 x s32>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY19:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S32_S64_ag_idx_imm [[COPY]], -128, [[COPY16]], [[COPY19]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<8 x s32>) into stack - 64, align 64)
    ; CHECK-NEXT: [[COPY20:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY21:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: [[COPY22:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S32_S64_ag_idx_imm [[COPY]], 96, [[COPY21]], [[COPY22]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<8 x s32>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY23:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S32_S64_ag_idx_imm [[COPY]], 64, [[COPY20]], [[COPY23]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<8 x s32>) into stack - 64, align 64)
    ; CHECK-NEXT: [[COPY24:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_lo
    ; CHECK-NEXT: [[COPY25:%[0-9]+]]:acc512 = COPY [[COPY2]].sub_512_hi
    ; CHECK-NEXT: [[PADD_imm9_pseudo1:%[0-9]+]]:ep = PADD_imm9_pseudo [[COPY]], 96
    ; CHECK-NEXT: [[COPY26:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S32_S64_ag_idx_imm [[PADD_imm9_pseudo1]], 32, [[COPY25]], [[COPY26]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<8 x s32>) into stack - 32, basealign 64)
    ; CHECK-NEXT: [[COPY27:%[0-9]+]]:mss = COPY [[COPY3]]
    ; CHECK-NEXT: VST_SRS_S32_S64_ag_idx_imm [[PADD_imm9_pseudo1]], 0, [[COPY24]], [[COPY27]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd :: (store (<8 x s32>) into stack - 64, align 64)
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %8:modregbank(s20) = G_CONSTANT i20 0
    %9:modregbank(s20) = G_CONSTANT i20 16
    %10:modregbank(s20) = G_CONSTANT i20 -128
    %11:modregbank(s20) = G_CONSTANT i20 64
    %12:modregbank(s20) = G_CONSTANT i20 96
    %100:accregbank(<16 x s64>) = COPY $cm0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 1
    %103:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %104:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %105:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %106:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %107:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %108:vregbank(<16 x s32>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I512.v16.acc64.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    G_AIE_OFFSET_STORE %103, %0, %7 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %104, %0, %8 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %105, %0, %9 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %106, %0, %10 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %107, %0, %11 :: (store (<16 x s32>) into stack - 64)
    G_AIE_OFFSET_STORE %108, %0, %12 :: (store (<16 x s32>) into stack - 64)
...

---
name:            VST_SRS_D8_S32_COPY_BITCAST
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $cm0, $p0, $r1
    ; CHECK-LABEL: name: VST_SRS_D8_S32_COPY_BITCAST
    ; CHECK: liveins: $cm0, $p0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:edj = COPY $m0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:mss = COPY [[COPY2]]
    ; CHECK-NEXT: VST_SRS_D8_S32_ag_idx [[COPY]], [[COPY1]], %5:acc1024, [[COPY3]], implicit-def $srsrs_of, implicit $crsat, implicit $crrnd, implicit $crsrssign :: (store (<8 x s32>))
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %101:gprregbank(s32) = COPY $r1
    %102:gprregbank(s32) = G_CONSTANT i32 0
    %103:vregbank(<32 x s8>) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.I256.v32.acc32.srs), %100:accregbank(<16 x s64>), %101:gprregbank(s32), %102:gprregbank(s32)
    %144:vregbank(<8 x s32>) = G_BITCAST %103(<32 x s8>)
    %201:vregbank(<8 x s32>) = COPY %144(<8 x s32>)
    G_AIE_OFFSET_STORE %201(<8 x s32>), %0, %7 :: (store (<8 x s32>))
...
