# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            v8bf_undef
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: v8bf_undef
    ; CHECK: [[DEF:%[0-9]+]]:vec128 = IMPLICIT_DEF
    ; CHECK-NEXT: $q0 = COPY [[DEF]]
    %0:vregbank(<8 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2.v8bfloat16)
    $q0 = COPY %0
...

---
name:            v16bf_undef
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: v16bf_undef
    ; CHECK: [[DEF:%[0-9]+]]:vec256 = IMPLICIT_DEF
    ; CHECK-NEXT: $wl0 = COPY [[DEF]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $wl0
    %0:vregbank(<16 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2.v16bfloat16)
    $wl0 = COPY %0:vregbank(<16 x s16>)
    PseudoRET implicit $lr, implicit $wl0
...

---
name:            v32bf_undef
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: v32bf_undef
    ; CHECK: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; CHECK-NEXT: $x0 = COPY [[DEF]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2.v32bfloat16)
    $x0 = COPY %0:vregbank(<32 x s16>)
    PseudoRET implicit $lr, implicit $x0
...

---
name:            v64bf_undef
alignment:       16
legalized:       true
regBankSelected: true
body:             |

  bb.1.entry:
    ; CHECK-LABEL: name: v64bf_undef
    ; CHECK: [[DEF:%[0-9]+]]:vec1024 = IMPLICIT_DEF
    ; CHECK-NEXT: $y2 = COPY [[DEF]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $y2
    %0:vregbank(<64 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2.v64bfloat16)
    $y2 = COPY %0:vregbank(<64 x s16>)
    PseudoRET implicit $lr, implicit $y2
...
