# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name: freeze_gpr
legalized:       true
regBankSelected: true
body: |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: freeze_gpr
    ; CHECK: liveins: $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; CHECK-NEXT: $r7 = COPY [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = G_FREEZE %0
    $r7 = COPY %1
    PseudoRET implicit $lr, implicit %1
...

---
name: freeze_ptr
legalized:       true
regBankSelected: true
body: |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: freeze_ptr
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: $p1 = COPY [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY]]
    %0:ptrregbank(p0) = COPY $p0
    %1:ptrregbank(p0) = G_FREEZE %0
    $p1 = COPY %1
    PseudoRET implicit $lr, implicit %1
...
