# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name: icmp_s32_ne
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6, $r7
    ; CHECK-LABEL: name: icmp_s32_ne
    ; CHECK: liveins: $r6, $r7
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r7
    ; CHECK-NEXT: [[NE:%[0-9]+]]:er = NE [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $r0 = COPY [[NE]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = COPY $r7
    %2:gprregbank(s32) = G_ICMP intpred(ne), %0(s32), %1
    $r0 = COPY %2
...

---
name: icmp_s32_nez
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: icmp_s32_nez
    ; CHECK: liveins: $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; CHECK-NEXT: [[NEZ:%[0-9]+]]:er = NEZ [[COPY]]
    ; CHECK-NEXT: [[NEZ1:%[0-9]+]]:er = NEZ [[COPY]]
    ; CHECK-NEXT: $r0 = COPY [[NEZ]]
    ; CHECK-NEXT: $r1 = COPY [[NEZ1]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = G_CONSTANT i32 0
    %2:gprregbank(s32) = G_ICMP intpred(ne), %0(s32), %1
    %3:gprregbank(s32) = G_ICMP intpred(ne), %1(s32), %0
    $r0 = COPY %2
    $r1 = COPY %3
...

---
name: icmp_s32_eq
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6, $r7
    ; CHECK-LABEL: name: icmp_s32_eq
    ; CHECK: liveins: $r6, $r7
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r7
    ; CHECK-NEXT: [[EQ:%[0-9]+]]:er = EQ [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $r0 = COPY [[EQ]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = COPY $r7
    %2:gprregbank(s32) = G_ICMP intpred(eq), %0(s32), %1
    $r0 = COPY %2
...

---
name: icmp_s32_eqz
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6
    ; CHECK-LABEL: name: icmp_s32_eqz
    ; CHECK: liveins: $r6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; CHECK-NEXT: [[EQZ:%[0-9]+]]:er = EQZ [[COPY]]
    ; CHECK-NEXT: [[EQZ1:%[0-9]+]]:er = EQZ [[COPY]]
    ; CHECK-NEXT: $r0 = COPY [[EQZ]]
    ; CHECK-NEXT: $r1 = COPY [[EQZ1]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = G_CONSTANT i32 0
    %2:gprregbank(s32) = G_ICMP intpred(eq), %0(s32), %1
    %3:gprregbank(s32) = G_ICMP intpred(eq), %1(s32), %0
    $r0 = COPY %2
    $r1 = COPY %3
...

---
name: icmp_s32_slt
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6, $r7
    ; CHECK-LABEL: name: icmp_s32_slt
    ; CHECK: liveins: $r6, $r7
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r7
    ; CHECK-NEXT: [[LT:%[0-9]+]]:er = LT [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $r0 = COPY [[LT]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = COPY $r7
    %2:gprregbank(s32) = G_ICMP intpred(slt), %0(s32), %1
    $r0 = COPY %2
...

---
name: icmp_s32_ult
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6, $r7
    ; CHECK-LABEL: name: icmp_s32_ult
    ; CHECK: liveins: $r6, $r7
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r7
    ; CHECK-NEXT: [[LTU:%[0-9]+]]:er = LTU [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $r0 = COPY [[LTU]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = COPY $r7
    %2:gprregbank(s32) = G_ICMP intpred(ult), %0(s32), %1
    $r0 = COPY %2
...

---
name: icmp_s32_sle
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6, $r7
    ; CHECK-LABEL: name: icmp_s32_sle
    ; CHECK: liveins: $r6, $r7
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r7
    ; CHECK-NEXT: [[GE:%[0-9]+]]:er = GE [[COPY1]], [[COPY]]
    ; CHECK-NEXT: $r0 = COPY [[GE]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = COPY $r7
    %2:gprregbank(s32) = G_ICMP intpred(sle), %0(s32), %1
    $r0 = COPY %2
...

---
name: icmp_s32_ule
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6, $r7
    ; CHECK-LABEL: name: icmp_s32_ule
    ; CHECK: liveins: $r6, $r7
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r7
    ; CHECK-NEXT: [[GEU:%[0-9]+]]:er = GEU [[COPY1]], [[COPY]]
    ; CHECK-NEXT: $r0 = COPY [[GEU]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = COPY $r7
    %2:gprregbank(s32) = G_ICMP intpred(ule), %0(s32), %1
    $r0 = COPY %2
...

---
name: icmp_s32_sgt
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6, $r7
    ; CHECK-LABEL: name: icmp_s32_sgt
    ; CHECK: liveins: $r6, $r7
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r7
    ; CHECK-NEXT: [[LT:%[0-9]+]]:er = LT [[COPY1]], [[COPY]]
    ; CHECK-NEXT: $r0 = COPY [[LT]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = COPY $r7
    %2:gprregbank(s32) = G_ICMP intpred(sgt), %0(s32), %1
    $r0 = COPY %2
...

---
name: icmp_s32_ugt
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6, $r7
    ; CHECK-LABEL: name: icmp_s32_ugt
    ; CHECK: liveins: $r6, $r7
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r7
    ; CHECK-NEXT: [[LTU:%[0-9]+]]:er = LTU [[COPY1]], [[COPY]]
    ; CHECK-NEXT: $r0 = COPY [[LTU]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = COPY $r7
    %2:gprregbank(s32) = G_ICMP intpred(ugt), %0(s32), %1
    $r0 = COPY %2
...

---
name: icmp_s32_sge
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6, $r7
    ; CHECK-LABEL: name: icmp_s32_sge
    ; CHECK: liveins: $r6, $r7
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r7
    ; CHECK-NEXT: [[GE:%[0-9]+]]:er = GE [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $r0 = COPY [[GE]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = COPY $r7
    %2:gprregbank(s32) = G_ICMP intpred(sge), %0(s32), %1
    $r0 = COPY %2
...

---
name: icmp_s32_uge
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $r6, $r7
    ; CHECK-LABEL: name: icmp_s32_uge
    ; CHECK: liveins: $r6, $r7
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r6
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r7
    ; CHECK-NEXT: [[GEU:%[0-9]+]]:er = GEU [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $r0 = COPY [[GEU]]
    %0:gprregbank(s32) = COPY $r6
    %1:gprregbank(s32) = COPY $r7
    %2:gprregbank(s32) = G_ICMP intpred(uge), %0(s32), %1
    $r0 = COPY %2
...

---
name: icmp_p0_ne
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $p0, $p1
    ; CHECK-LABEL: name: icmp_p0_ne
    ; CHECK: liveins: $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY [[COPY]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY [[COPY1]]
    ; CHECK-NEXT: [[NE:%[0-9]+]]:er = NE [[COPY2]], [[COPY3]]
    ; CHECK-NEXT: $r0 = COPY [[NE]]
    %0:ptrregbank(p0) = COPY $p0
    %1:ptrregbank(p0) = COPY $p1
    %2:gprregbank(p0) = COPY %0
    %3:gprregbank(p0) = COPY %1
    %4:gprregbank(s32) = G_ICMP intpred(ne), %2(p0), %3
    $r0 = COPY %4
...


---
name: icmp_p0_nez
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: icmp_p0_nez
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $p0
    ; CHECK-NEXT: [[NEZ:%[0-9]+]]:er = NEZ [[COPY]]
    ; CHECK-NEXT: [[NEZ1:%[0-9]+]]:er = NEZ [[COPY]]
    ; CHECK-NEXT: $r0 = COPY [[NEZ]]
    ; CHECK-NEXT: $r1 = COPY [[NEZ1]]
    %0:gprregbank(p0) = COPY $p0
    %1:gprregbank(p0) = G_CONSTANT i20 0
    %2:gprregbank(s32) = G_ICMP intpred(ne), %0, %1
    %3:gprregbank(s32) = G_ICMP intpred(ne), %1, %0
    $r0 = COPY %2
    $r1 = COPY %3
...

---
name: icmp_p0_eq
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $p0, $p1
    ; CHECK-LABEL: name: icmp_p0_eq
    ; CHECK: liveins: $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY [[COPY]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY [[COPY1]]
    ; CHECK-NEXT: [[EQ:%[0-9]+]]:er = EQ [[COPY2]], [[COPY3]]
    ; CHECK-NEXT: $r0 = COPY [[EQ]]
    %0:ptrregbank(p0) = COPY $p0
    %1:ptrregbank(p0) = COPY $p1
    %2:gprregbank(p0) = COPY %0
    %3:gprregbank(p0) = COPY %1
    %4:gprregbank(s32) = G_ICMP intpred(eq), %2(p0), %3
    $r0 = COPY %4
...

---
name: icmp_p0_eqz
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $p0
    ; CHECK-LABEL: name: icmp_p0_eqz
    ; CHECK: liveins: $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $p0
    ; CHECK-NEXT: [[EQZ:%[0-9]+]]:er = EQZ [[COPY]]
    ; CHECK-NEXT: [[EQZ1:%[0-9]+]]:er = EQZ [[COPY]]
    ; CHECK-NEXT: $r0 = COPY [[EQZ]]
    ; CHECK-NEXT: $r1 = COPY [[EQZ1]]
    %0:gprregbank(p0) = COPY $p0
    %1:gprregbank(p0) = G_CONSTANT i20 0
    %2:gprregbank(s32) = G_ICMP intpred(eq), %0, %1
    %3:gprregbank(s32) = G_ICMP intpred(eq), %1, %0
    $r0 = COPY %2
    $r1 = COPY %3
...

---
name: icmp_p0_ult
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $p0, $p1
    ; CHECK-LABEL: name: icmp_p0_ult
    ; CHECK: liveins: $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY [[COPY]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY [[COPY1]]
    ; CHECK-NEXT: [[LTU:%[0-9]+]]:er = LTU [[COPY2]], [[COPY3]]
    ; CHECK-NEXT: $r0 = COPY [[LTU]]
    %0:ptrregbank(p0) = COPY $p0
    %1:ptrregbank(p0) = COPY $p1
    %2:gprregbank(p0) = COPY %0
    %3:gprregbank(p0) = COPY %1
    %4:gprregbank(s32) = G_ICMP intpred(ult), %2(p0), %3
    $r0 = COPY %4
...

---
name: icmp_p0_ule
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $p0, $p1
    ; CHECK-LABEL: name: icmp_p0_ule
    ; CHECK: liveins: $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY [[COPY]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY [[COPY1]]
    ; CHECK-NEXT: [[GEU:%[0-9]+]]:er = GEU [[COPY3]], [[COPY2]]
    ; CHECK-NEXT: $r0 = COPY [[GEU]]
    %0:ptrregbank(p0) = COPY $p0
    %1:ptrregbank(p0) = COPY $p1
    %2:gprregbank(p0) = COPY %0
    %3:gprregbank(p0) = COPY %1
    %4:gprregbank(s32) = G_ICMP intpred(ule), %2(p0), %3
    $r0 = COPY %4
...

---
name: icmp_p0_ugt
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $p0, $p1
    ; CHECK-LABEL: name: icmp_p0_ugt
    ; CHECK: liveins: $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY [[COPY]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY [[COPY1]]
    ; CHECK-NEXT: [[LTU:%[0-9]+]]:er = LTU [[COPY3]], [[COPY2]]
    ; CHECK-NEXT: $r0 = COPY [[LTU]]
    %0:ptrregbank(p0) = COPY $p0
    %1:ptrregbank(p0) = COPY $p1
    %2:gprregbank(p0) = COPY %0
    %3:gprregbank(p0) = COPY %1
    %4:gprregbank(s32) = G_ICMP intpred(ugt), %2(p0), %3
    $r0 = COPY %4
...

---
name: icmp_p0_uge
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $p0, $p1
    ; CHECK-LABEL: name: icmp_p0_uge
    ; CHECK: liveins: $p0, $p1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ep = COPY $p1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY [[COPY]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:er = COPY [[COPY1]]
    ; CHECK-NEXT: [[GEU:%[0-9]+]]:er = GEU [[COPY2]], [[COPY3]]
    ; CHECK-NEXT: $r0 = COPY [[GEU]]
    %0:ptrregbank(p0) = COPY $p0
    %1:ptrregbank(p0) = COPY $p1
    %2:gprregbank(p0) = COPY %0
    %3:gprregbank(p0) = COPY %1
    %4:gprregbank(s32) = G_ICMP intpred(uge), %2(p0), %3
    $r0 = COPY %4
...
