# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s
---
name: v8s32
legalized: true
regBankSelected: true
body: |
  bb.0:
    ; CHECK-LABEL: name: v8s32
    ; CHECK: [[DEF:%[0-9]+]]:vec256 = IMPLICIT_DEF
    ; CHECK-NEXT: $wl0 = COPY [[DEF]]
    %0:vregbank(<8 x s32>) = G_IMPLICIT_DEF
    $wl0 = COPY %0
...

---
name: v16s16
legalized: true
regBankSelected: true
body: |
  bb.0:
    ; CHECK-LABEL: name: v16s16
    ; CHECK: [[DEF:%[0-9]+]]:vec256 = IMPLICIT_DEF
    ; CHECK-NEXT: $wl0 = COPY [[DEF]]
    %0:vregbank(<16 x s16>) = G_IMPLICIT_DEF
    $wl0 = COPY %0
...

---
name: v32s8
legalized: true
regBankSelected: true
body: |
  bb.0:
    ; CHECK-LABEL: name: v32s8
    ; CHECK: [[DEF:%[0-9]+]]:vec256 = IMPLICIT_DEF
    ; CHECK-NEXT: $wl0 = COPY [[DEF]]
    %0:vregbank(<32 x s8>) = G_IMPLICIT_DEF
    $wl0 = COPY %0
...

---
name: acc256
legalized: true
regBankSelected: true
body: |
  bb.0:
    ; CHECK-LABEL: name: acc256
    ; CHECK: [[DEF:%[0-9]+]]:acc256 = IMPLICIT_DEF
    ; CHECK-NEXT: $wl0 = COPY [[DEF]]
    %0:accregbank(<4 x s64>) = G_IMPLICIT_DEF
    $wl0 = COPY %0
...

---
name: v16s32
legalized: true
regBankSelected: true
body: |
  bb.0:
    ; CHECK-LABEL: name: v16s32
    ; CHECK: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; CHECK-NEXT: $x0 = COPY [[DEF]]
    %0:vregbank(<16 x s32>) = G_IMPLICIT_DEF
    $x0 = COPY %0
...

---
name: v32s16
legalized: true
regBankSelected: true
body: |
  bb.0:
    ; CHECK-LABEL: name: v32s16
    ; CHECK: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; CHECK-NEXT: $x0 = COPY [[DEF]]
    %0:vregbank(<32 x s16>) = G_IMPLICIT_DEF
    $x0 = COPY %0
...

---
name: v64s8
legalized: true
regBankSelected: true
body: |
  bb.0:
    ; CHECK-LABEL: name: v64s8
    ; CHECK: [[DEF:%[0-9]+]]:vec512 = IMPLICIT_DEF
    ; CHECK-NEXT: $x0 = COPY [[DEF]]
    %0:vregbank(<64 x s8>) = G_IMPLICIT_DEF
    $x0 = COPY %0
...

---
name: acc512
legalized: true
regBankSelected: true
body: |
  bb.0:
    ; CHECK-LABEL: name: acc512
    ; CHECK: [[DEF:%[0-9]+]]:acc512 = IMPLICIT_DEF
    ; CHECK-NEXT: $x0 = COPY [[DEF]]
    %0:accregbank(<8 x s64>) = G_IMPLICIT_DEF
    $x0 = COPY %0
...

---
name: v32s32
legalized: true
regBankSelected: true
body: |
  bb.0:
    ; CHECK-LABEL: name: v32s32
    ; CHECK: [[DEF:%[0-9]+]]:vec1024 = IMPLICIT_DEF
    ; CHECK-NEXT: $y2 = COPY [[DEF]]
    %0:vregbank(<32 x s32>) = G_IMPLICIT_DEF
    $y2 = COPY %0
...

---
name: v64s16
legalized: true
regBankSelected: true
body: |
  bb.0:
    ; CHECK-LABEL: name: v64s16
    ; CHECK: [[DEF:%[0-9]+]]:vec1024 = IMPLICIT_DEF
    ; CHECK-NEXT: $y2 = COPY [[DEF]]
    %0:vregbank(<64 x s16>) = G_IMPLICIT_DEF
    $y2 = COPY %0
...

---
name: v128s8
legalized: true
regBankSelected: true
body: |
  bb.0:
    ; CHECK-LABEL: name: v128s8
    ; CHECK: [[DEF:%[0-9]+]]:vec1024 = IMPLICIT_DEF
    ; CHECK-NEXT: $y2 = COPY [[DEF]]
    %0:vregbank(<128 x s8>) = G_IMPLICIT_DEF
    $y2 = COPY %0
...

---
name: acc1024
legalized: true
regBankSelected: true
body: |
  bb.0:
    ; CHECK-LABEL: name: acc1024
    ; CHECK: [[DEF:%[0-9]+]]:acc1024 = IMPLICIT_DEF
    ; CHECK-NEXT: $y2 = COPY [[DEF]]
    %0:accregbank(<16 x s64>) = G_IMPLICIT_DEF
    $y2 = COPY %0
...
