# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s


---
name:            ACQ_mLockId_reg
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $r1
    ; CHECK-LABEL: name: ACQ_mLockId_reg
    ; CHECK: liveins: $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: ACQ_mLockId_reg [[COPY]], [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:gprregbank(s32) = COPY $r0
    %1:gprregbank(s32) = COPY $r1
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.acquire), %0:gprregbank(s32), %1:gprregbank(s32)
    PseudoRET implicit $lr
...

---
name:            ACQ_mLockId_imm
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0
    ; CHECK-LABEL: name: ACQ_mLockId_imm
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: ACQ_mLockId_imm 1, [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:gprregbank(s32) = COPY $r0
    %1:gprregbank(s32) = G_CONSTANT i32 1
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.acquire), %1:gprregbank(s32), %0:gprregbank(s32)
    PseudoRET implicit $lr
...


---
name:            ACQ_COND_mLockId_reg
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $r1, $r2
    ; CHECK-LABEL: name: ACQ_COND_mLockId_reg
    ; CHECK: liveins: $r0, $r1, $r2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er26 = COPY $r2
    ; CHECK-NEXT: ACQ_COND_mLockId_reg [[COPY]], [[COPY1]], [[COPY2]]
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:gprregbank(s32) = COPY $r0
    %1:gprregbank(s32) = COPY $r1
    %2:gprregbank(s32) = COPY $r2
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.acquire.cond), %0:gprregbank(s32), %1:gprregbank(s32), %2:gprregbank(s32)
    PseudoRET implicit $lr
...


---
name:            ACQ_COND_mLockId_imm
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $r1
    ; CHECK-LABEL: name: ACQ_COND_mLockId_imm
    ; CHECK: liveins: $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er26 = COPY $r1
    ; CHECK-NEXT: ACQ_COND_mLockId_imm 2, [[COPY]], [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:gprregbank(s32) = COPY $r0
    %1:gprregbank(s32) = COPY $r1
    %2:gprregbank(s32) = G_CONSTANT i32 2
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.acquire.cond), %2:gprregbank(s32), %0:gprregbank(s32), %1:gprregbank(s32)
    PseudoRET implicit $lr
...


---
name:            REL_mLockId_reg
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $r1
    ; CHECK-LABEL: name: REL_mLockId_reg
    ; CHECK: liveins: $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: REL_mLockId_reg [[COPY]], [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:gprregbank(s32) = COPY $r0
    %1:gprregbank(s32) = COPY $r1
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.release), %0:gprregbank(s32), %1:gprregbank(s32)
    PseudoRET implicit $lr
...


---
name:            REL_mLockId_imm
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0
    ; CHECK-LABEL: name: REL_mLockId_imm
    ; CHECK: liveins: $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: REL_mLockId_imm 28, [[COPY]]
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:gprregbank(s32) = COPY $r0
    %1:gprregbank(s32) = G_CONSTANT i32 28
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.release), %1:gprregbank(s32), %0:gprregbank(s32)
    PseudoRET implicit $lr
...


---
name:            REL_COND_mLockId_reg
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $r1, $r2
    ; CHECK-LABEL: name: REL_COND_mLockId_reg
    ; CHECK: liveins: $r0, $r1, $r2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er26 = COPY $r2
    ; CHECK-NEXT: REL_COND_mLockId_reg [[COPY]], [[COPY1]], [[COPY2]]
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:gprregbank(s32) = COPY $r0
    %1:gprregbank(s32) = COPY $r1
    %2:gprregbank(s32) = COPY $r2
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.release.cond), %0:gprregbank(s32), %1:gprregbank(s32), %2:gprregbank(s32)
    PseudoRET implicit $lr
...


---
name:            REL_COND_mLockId_imm
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    liveins: $r0, $r1
    ; CHECK-LABEL: name: REL_COND_mLockId_imm
    ; CHECK: liveins: $r0, $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:er26 = COPY $r1
    ; CHECK-NEXT: REL_COND_mLockId_imm 61, [[COPY]], [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr
    %0:gprregbank(s32) = COPY $r0
    %1:gprregbank(s32) = COPY $r1
    %2:gprregbank(s32) = G_CONSTANT i32 61
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.aie2.release.cond), %2:gprregbank(s32), %0:gprregbank(s32), %1:gprregbank(s32)
    PseudoRET implicit $lr
...
