# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select %s -verify-machineinstrs -o - | FileCheck %s

---
name:            v8accfloat_undef
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: v8accfloat_undef
    ; CHECK: [[DEF:%[0-9]+]]:acc256 = IMPLICIT_DEF
    ; CHECK-NEXT: $amll0 = COPY [[DEF]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $amll0
    %0:accregbank(<4 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.v8accfloat)
    $amll0 = COPY %0:accregbank(<4 x s64>)
    PseudoRET implicit $lr, implicit $amll0
...

---
name:            v16accfloat_undef
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: v16accfloat_undef
    ; CHECK: [[DEF:%[0-9]+]]:acc512 = IMPLICIT_DEF
    ; CHECK-NEXT: $bml0 = COPY [[DEF]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bml0
    %0:accregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.v16accfloat)
    $bml0 = COPY %0:accregbank(<8 x s64>)
    PseudoRET implicit $lr, implicit $bml0
...

---
name:            v32accfloat_undef
alignment:       16
legalized:       true
regBankSelected: true
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: v32accfloat_undef
    ; CHECK: [[DEF:%[0-9]+]]:acc1024 = IMPLICIT_DEF
    ; CHECK-NEXT: $cm0 = COPY [[DEF]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cm0
    %0:accregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.v32accfloat)
    $cm0 = COPY %0:accregbank(<16 x s64>)
    PseudoRET implicit $lr, implicit $cm0
...
