# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s

---
name: test_fabs_s16
body: |
  bb.0:
    liveins: $r1
    ; CHECK-LABEL: name: test_fabs_s16
    ; CHECK: liveins: $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 32767
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY]], [[C]]
    ; CHECK-NEXT: $r0 = COPY [[AND]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %2:_(s32) = COPY $r1
    %1:_(s16) = G_TRUNC %2(s32)
    %0:_(s16) = G_FABS %1
    %3:_(s32) = G_ANYEXT %0(s16)
    $r0 = COPY %3(s32)
    PseudoRET implicit $lr, implicit $r0
...

---
name: test_fabs_s32
body: |
  bb.0:
    liveins: $r1
    ; CHECK-LABEL: name: test_fabs_s32
    ; CHECK: liveins: $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 2147483647
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY]], [[C]]
    ; CHECK-NEXT: $r0 = COPY [[AND]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %1:_(s32) = COPY $r1
    %0:_(s32) = G_FABS %1
    $r0 = COPY %0(s32)
    PseudoRET implicit $lr, implicit $r0
...

---
name: test_fabs_s64
body: |
  bb.0:
    liveins: $r2, $r3

    ; CHECK-LABEL: name: test_fabs_s64
    ; CHECK: liveins: $r2, $r3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r3
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 2147483647
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY1]], [[C]]
    ; CHECK-NEXT: $r0 = COPY [[COPY]](s32)
    ; CHECK-NEXT: $r1 = COPY [[AND]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0, implicit $r1
    %2:_(s32) = COPY $r2
    %3:_(s32) = COPY $r3
    %1:_(s64) = G_MERGE_VALUES %2(s32), %3(s32)
    %0:_(s64) = G_FABS %1
    %4:_(s32), %5:_(s32) = G_UNMERGE_VALUES %0(s64)
    $r0 = COPY %4(s32)
    $r1 = COPY %5(s32)
    PseudoRET implicit $lr, implicit $r0, implicit $r1
...
