# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s
---
name:            bfloat16_float_test
body:             |
  bb.1.entry:
    liveins: $r1

    ; CHECK-LABEL: name: bfloat16_float_test
    ; CHECK: liveins: $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY]], [[C1]]
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s32) = nuw G_SHL [[AND]], [[C]](s32)
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY [[SHL]](s32)
    ; CHECK-NEXT: $r0 = COPY [[COPY1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $r0
    %2:_(s32) = COPY $r1
    %1:_(s16) = G_TRUNC %2(s32)
    %4:_(s32) = G_CONSTANT i32 16
    %3:_(s32) = G_ZEXT %1(s16)
    %5:_(s32) = nuw G_SHL %3, %4(s32)
    %0:_(s32) = COPY %5(s32)
    $r0 = COPY %0(s32)
    PseudoRET implicit $lr, implicit $r0

...
