# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s

---
name: test_fpext_s16_to_s32
body: |
  bb.0:
    liveins: $r1

    ; CHECK-LABEL: name: test_fpext_s16_to_s32
    ; CHECK: liveins: $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[COPY]], [[C]](s32)
    ; CHECK-NEXT: $r0 = COPY [[SHL]](s32)
    %0:_(s32) = COPY $r1
    %1:_(s16) = G_TRUNC %0
    %2:_(s32) = G_FPEXT %1
    $r0 = COPY %2
...

---
name: test_fpext_s32_to_s64
body: |
  bb.0:
    liveins: $r2

    ; CHECK-LABEL: name: test_fpext_s32_to_s64
    ; CHECK: liveins: $r2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r2
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r2 = COPY [[COPY]](s32)
    ; CHECK-NEXT: PseudoJL &__extendsfdf2, csr_aie2, implicit-def $lr, implicit $r2, implicit-def $r0, implicit-def $r1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r0 = COPY [[COPY1]](s32)
    ; CHECK-NEXT: $r1 = COPY [[COPY2]](s32)
    %0:_(s32) = COPY $r2
    %1:_(s64) = G_FPEXT %0(s32)
    %2:_(s32), %3:_(s32) = G_UNMERGE_VALUES %1(s64)
    $r0 = COPY %2(s32)
    $r1 = COPY %3(s32)
...
