# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s

---
name: test_fptoui_s32_to_s32
body: |
  bb.0:
    liveins: $r1

    ; CHECK-LABEL: name: test_fptoui_s32_to_s32
    ; CHECK: liveins: $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r1 = COPY [[COPY]](s32)
    ; CHECK-NEXT: PseudoJL &__fixunssfsi, csr_aie2, implicit-def $lr, implicit $r1, implicit-def $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r0 = COPY [[COPY1]](s32)
    %0:_(s32) = COPY $r1
    %1:_(s32) = G_FPTOUI %0
    $r0 = COPY %1
...

---
name: test_fptoui_s64_to_s32
body: |
  bb.0:
    liveins: $r2, $r3

    ; CHECK-LABEL: name: test_fptoui_s64_to_s32
    ; CHECK: liveins: $r2, $r3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r3
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r1 = COPY [[COPY]](s32)
    ; CHECK-NEXT: $r2 = COPY [[COPY1]](s32)
    ; CHECK-NEXT: PseudoJL &__fixunsdfsi, csr_aie2, implicit-def $lr, implicit $r1, implicit $r2, implicit-def $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r0 = COPY [[COPY2]](s32)
    %0:_(s32) = COPY $r2
    %1:_(s32) = COPY $r3
    %2:_(s64) = G_MERGE_VALUES %0(s32), %1(s32)
    %3:_(s32) = G_FPTOUI %2
    $r0 = COPY %3
...

---
name: test_fptoui_s16_to_s16
body: |
  bb.0:
    liveins: $r1

    ; CHECK-LABEL: name: test_fptoui_s16_to_s16
    ; CHECK: liveins: $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[COPY]], [[C]](s32)
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r1 = COPY [[SHL]](s32)
    ; CHECK-NEXT: PseudoJL &__fixunssfsi, csr_aie2, implicit-def $lr, implicit $r1, implicit-def $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r0 = COPY [[COPY1]](s32)
    %0:_(s32) = COPY $r1
    %1:_(s16) = G_TRUNC %0
    %2:_(s16) = G_FPTOUI %1
    %3:_(s32) = G_ANYEXT %2
    $r0 = COPY %3
...

---
name: test_fptoui_s32_to_s16
body: |
  bb.0:
    liveins: $r1

    ; CHECK-LABEL: name: test_fptoui_s32_to_s16
    ; CHECK: liveins: $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r1 = COPY [[COPY]](s32)
    ; CHECK-NEXT: PseudoJL &__fixunssfsi, csr_aie2, implicit-def $lr, implicit $r1, implicit-def $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r0 = COPY [[COPY1]](s32)
    %0:_(s32) = COPY $r1
    %1:_(s16) = G_FPTOUI %0
    %2:_(s32) = G_ANYEXT %1
    $r0 = COPY %2
...

---
name: test_fptoui_s64_to_s16
body: |
  bb.0:
    liveins: $r2, $r3

    ; CHECK-LABEL: name: test_fptoui_s64_to_s16
    ; CHECK: liveins: $r2, $r3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r3
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r1 = COPY [[COPY]](s32)
    ; CHECK-NEXT: $r2 = COPY [[COPY1]](s32)
    ; CHECK-NEXT: PseudoJL &__fixunsdfsi, csr_aie2, implicit-def $lr, implicit $r1, implicit $r2, implicit-def $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r0 = COPY [[COPY2]](s32)
    %0:_(s32) = COPY $r2
    %1:_(s32) = COPY $r3
    %2:_(s64) = G_MERGE_VALUES %0(s32), %1(s32)
    %3:_(s16) = G_FPTOUI %2
    %4:_(s32) = G_ANYEXT %3
    $r0 = COPY %4
...

---
name: test_fptoui_s64_s64
body: |
  bb.0:
    liveins: $r2, $r3

    ; CHECK-LABEL: name: test_fptoui_s64_s64
    ; CHECK: liveins: $r2, $r3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r3
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r2 = COPY [[COPY]](s32)
    ; CHECK-NEXT: $r3 = COPY [[COPY1]](s32)
    ; CHECK-NEXT: PseudoJL &__fixunsdfdi, csr_aie2, implicit-def $lr, implicit $r2, implicit $r3, implicit-def $r0, implicit-def $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r0 = COPY [[COPY2]](s32)
    ; CHECK-NEXT: $r1 = COPY [[COPY3]](s32)
    %0:_(s32) = COPY $r2
    %1:_(s32) = COPY $r3
    %2:_(s64) = G_MERGE_VALUES %0(s32), %1(s32)
    %3:_(s64) = G_FPTOUI %2
    %4:_(s32), %5:_(s32) = G_UNMERGE_VALUES %3(s64)
    $r0 = COPY %4(s32)
    $r1 = COPY %5(s32)
...

---
name: test_fptoui_s32_to_s64
body: |
  bb.0:
    liveins: $r1

    ; CHECK-LABEL: name: test_fptoui_s32_to_s64
    ; CHECK: liveins: $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r2 = COPY [[COPY]](s32)
    ; CHECK-NEXT: PseudoJL &__fixunssfdi, csr_aie2, implicit-def $lr, implicit $r2, implicit-def $r0, implicit-def $r1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r0 = COPY [[COPY1]](s32)
    ; CHECK-NEXT: $r1 = COPY [[COPY2]](s32)
    %0:_(s32) = COPY $r1
    %1:_(s64) = G_FPTOUI %0
    %2:_(s32), %3:_(s32) = G_UNMERGE_VALUES %1(s64)
    $r0 = COPY %2(s32)
    $r1 = COPY %3(s32)
...

---
name: test_fptoui_s16_to_s64
body: |
  bb.0:
    liveins: $r1

    ; CHECK-LABEL: name: test_fptoui_s16_to_s64
    ; CHECK: liveins: $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[COPY]], [[C]](s32)
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r2 = COPY [[SHL]](s32)
    ; CHECK-NEXT: PseudoJL &__fixunssfdi, csr_aie2, implicit-def $lr, implicit $r2, implicit-def $r0, implicit-def $r1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r0 = COPY [[COPY1]](s32)
    ; CHECK-NEXT: $r1 = COPY [[COPY2]](s32)
    %0:_(s32) = COPY $r1
    %1:_(s16) = G_TRUNC %0
    %2:_(s64) = G_FPTOUI %1
    %3:_(s32), %4:_(s32) = G_UNMERGE_VALUES %2(s64)
    $r0 = COPY %3(s32)
    $r1 = COPY %4(s32)
...

---
name: test_fptoui_s16_to_s1
body: |
  bb.0:
    liveins: $r1
    ; CHECK-LABEL: name: test_fptoui_s16_to_s1
    ; CHECK: liveins: $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[COPY]], [[C]](s32)
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r1 = COPY [[SHL]](s32)
    ; CHECK-NEXT: PseudoJL &__fixunssfsi, csr_aie2, implicit-def $lr, implicit $r1, implicit-def $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s1) = G_TRUNC [[COPY1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[TRUNC]](s1)
    %0:_(s32) = COPY $r1
    %1:_(s16) = G_TRUNC %0
    %2:_(s1)  = G_FPTOUI %1
    PseudoRET implicit $lr, implicit %2
...

---
name: test_fptoui_s16_to_s15
body: |
  bb.0:
    liveins: $r1

    ; CHECK-LABEL: name: test_fptoui_s16_to_s15
    ; CHECK: liveins: $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[COPY]], [[C]](s32)
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r1 = COPY [[SHL]](s32)
    ; CHECK-NEXT: PseudoJL &__fixunssfsi, csr_aie2, implicit-def $lr, implicit $r1, implicit-def $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r0 = COPY [[COPY1]](s32)
    %0:_(s32) = COPY $r1
    %1:_(s16) = G_TRUNC %0
    %2:_(s15) = G_FPTOUI %1
    %3:_(s32) = G_ANYEXT %2
    $r0 = COPY %3
...

---
name: test_fptoui_s16_to_s17
body: |
  bb.0:
    liveins: $r1

    ; CHECK-LABEL: name: test_fptoui_s16_to_s17
    ; CHECK: liveins: $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[COPY]], [[C]](s32)
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r1 = COPY [[SHL]](s32)
    ; CHECK-NEXT: PseudoJL &__fixunssfsi, csr_aie2, implicit-def $lr, implicit $r1, implicit-def $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r0 = COPY [[COPY1]](s32)
    %0:_(s32) = COPY $r1
    %1:_(s16) = G_TRUNC %0
    %2:_(s17) = G_FPTOUI %1
    %3:_(s32) = G_ANYEXT %2
    $r0 = COPY %3
...

---
name: test_fptoui_s32_to_s33
body: |
  bb.0:
    liveins: $r1

    ; CHECK-LABEL: name: test_fptoui_s32_to_s33
    ; CHECK: liveins: $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r2 = COPY [[COPY]](s32)
    ; CHECK-NEXT: PseudoJL &__fixunssfdi, csr_aie2, implicit-def $lr, implicit $r2, implicit-def $r0, implicit-def $r1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r0 = COPY [[COPY1]](s32)
    ; CHECK-NEXT: $r1 = COPY [[COPY2]](s32)
    %0:_(s32) = COPY $r1
    %1:_(s33) = G_FPTOUI %0
    %2:_(s64) = G_ANYEXT %1
    %3:_(s32), %4:_(s32) = G_UNMERGE_VALUES %2(s64)
    $r0 = COPY %3(s32)
    $r1 = COPY %4(s32)
...

---
name: test_fptoui_s16_to_s7
body: |
  bb.0:
    liveins: $r1

    ; CHECK-LABEL: name: test_fptoui_s16_to_s7
    ; CHECK: liveins: $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[COPY]], [[C]](s32)
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r1 = COPY [[SHL]](s32)
    ; CHECK-NEXT: PseudoJL &__fixunssfsi, csr_aie2, implicit-def $lr, implicit $r1, implicit-def $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r0 = COPY [[COPY1]](s32)
    %0:_(s32) = COPY $r1
    %1:_(s16) = G_TRUNC %0
    %2:_(s7) = G_FPTOUI %1
    %3:_(s32) = G_ANYEXT %2
    $r0 = COPY %3
...

---
name: test_fptoui_s16_to_s8
body: |
  bb.0:
    liveins: $r1

    ; CHECK-LABEL: name: test_fptoui_s16_to_s8
    ; CHECK: liveins: $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[COPY]], [[C]](s32)
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r1 = COPY [[SHL]](s32)
    ; CHECK-NEXT: PseudoJL &__fixunssfsi, csr_aie2, implicit-def $lr, implicit $r1, implicit-def $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r0 = COPY [[COPY1]](s32)
    %0:_(s32) = COPY $r1
    %1:_(s16) = G_TRUNC %0
    %2:_(s8) = G_FPTOUI %1
    %3:_(s32) = G_ANYEXT %2
    $r0 = COPY %3
...

---
name: test_fptoui_s16_to_s9
body: |
  bb.0:
    liveins: $r1

    ; CHECK-LABEL: name: test_fptoui_s16_to_s9
    ; CHECK: liveins: $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[COPY]], [[C]](s32)
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r1 = COPY [[SHL]](s32)
    ; CHECK-NEXT: PseudoJL &__fixunssfsi, csr_aie2, implicit-def $lr, implicit $r1, implicit-def $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r0 = COPY [[COPY1]](s32)
    %0:_(s32) = COPY $r1
    %1:_(s16) = G_TRUNC %0
    %2:_(s9) = G_FPTOUI %1
    %3:_(s32) = G_ANYEXT %2
    $r0 = COPY %3
...

---
name: test_fptoui_s32_to_s15
body: |
  bb.0:
    liveins: $r1

    ; CHECK-LABEL: name: test_fptoui_s32_to_s15
    ; CHECK: liveins: $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r1 = COPY [[COPY]](s32)
    ; CHECK-NEXT: PseudoJL &__fixunssfsi, csr_aie2, implicit-def $lr, implicit $r1, implicit-def $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r0 = COPY [[COPY1]](s32)
    %0:_(s32) = COPY $r1
    %1:_(s15) = G_FPTOUI %0
    %2:_(s32) = G_ANYEXT %1
    $r0 = COPY %2
...

---
name: test_fptoui_s32_to_s17
body: |
  bb.0:
    liveins: $r1

    ; CHECK-LABEL: name: test_fptoui_s32_to_s17
    ; CHECK: liveins: $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r1 = COPY [[COPY]](s32)
    ; CHECK-NEXT: PseudoJL &__fixunssfsi, csr_aie2, implicit-def $lr, implicit $r1, implicit-def $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: $r0 = COPY [[COPY1]](s32)
    %0:_(s32) = COPY $r1
    %1:_(s17) = G_FPTOUI %0
    %2:_(s32) = G_ANYEXT %1
    $r0 = COPY %2
...
