# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s

---
name:            or_vec_256
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: or_vec_256
    ; CHECK: [[COPY:%[0-9]+]]:_(<32 x s8>) = COPY $wl0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<32 x s8>) = COPY $wh3
    ; CHECK-NEXT: [[OR:%[0-9]+]]:_(<32 x s8>) = G_OR [[COPY]], [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[OR]](<32 x s8>)
    %0:_(<32 x s8>) = COPY $wl0
    %1:_(<32 x s8>) = COPY $wh3
    %2:_(<32 x s8>) = G_OR %0(<32 x s8>), %1(<32 x s8>)
    PseudoRET implicit $lr, implicit %2
...


---
name:            or_vec_512
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: or_vec_512
    ; CHECK: [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<64 x s8>) = COPY $x1
    ; CHECK-NEXT: [[OR:%[0-9]+]]:_(<64 x s8>) = G_OR [[COPY]], [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[OR]](<64 x s8>)
    %0:_(<64 x s8>) = COPY $x0
    %1:_(<64 x s8>) = COPY $x1
    %2:_(<64 x s8>) = G_OR %0(<64 x s8>), %1(<64 x s8>)
    PseudoRET implicit $lr, implicit %2
...

---
name:            or_vec_1024
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: or_vec_1024
    ; CHECK: [[COPY:%[0-9]+]]:_(<64 x s16>) = COPY $y5
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<64 x s16>) = COPY $y2
    ; CHECK-NEXT: [[OR:%[0-9]+]]:_(<64 x s16>) = G_OR [[COPY]], [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[OR]](<64 x s16>)
    %0:_(<64 x s16>) = COPY $y5
    %1:_(<64 x s16>) = COPY $y2
    %2:_(<64 x s16>) = G_OR %0(<64 x s16>), %1(<64 x s16>)
    PseudoRET implicit $lr, implicit %2
...
