# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=legalizer %s -verify-machineinstrs -o - | FileCheck %s

---
name: test_stack
body: |
  bb.0:
    liveins: $p2

    ; CHECK-LABEL: name: test_stack
    ; CHECK: liveins: $p2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $sp
    ; CHECK-NEXT: $sp = COPY [[COPY]](p0)
    %0:_(p0) = G_STACKSAVE
    G_STACKRESTORE %0(p0)
...

---
name: test_stackalloc
body: |
  bb.0:
    liveins: $r1

    ; CHECK-LABEL: name: test_stackalloc
    ; CHECK: liveins: $r1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $r1
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s20) = G_TRUNC [[COPY]](s32)
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $sp
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(p0) = COPY [[COPY1]](p0)
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY1]], [[TRUNC]](s20)
    ; CHECK-NEXT: $sp = COPY [[PTR_ADD]](p0)
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(p0) = COPY $sp
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:_(p0) = COPY [[COPY3]](p0)
    ; CHECK-NEXT: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY3]], [[TRUNC]](s20)
    ; CHECK-NEXT: $sp = COPY [[PTR_ADD1]](p0)
    %0:_(s32) = COPY $r1
    %1:_(s20) = G_TRUNC %0(s32)
    %2:_(p0) = G_DYN_STACKALLOC %1(s20), 1
    %3:_(p0) = G_DYN_STACKALLOC %1(s20), 32
...
