# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024-2026 Advanced Micro Devices, Inc. or its affiliates
#
# RUN: llc -mtriple aie2 -run-pass=aie2-prelegalizer-combiner -verify-machineinstrs %s -o - | FileCheck %s

# Test that G_SHUFFLE_VECTOR with VSelect patterns are combined to G_AIE_VSEL on AIE2

---
name: shuffle_vector_vsel_16_s32
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $x0, $x2

    ; CHECK-LABEL: name: shuffle_vector_vsel_16_s32
    ; CHECK: liveins: $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<16 x s32>) = COPY $x2
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 65520
    ; CHECK-NEXT: [[AIE_VSEL:%[0-9]+]]:_(<16 x s32>) = G_AIE_VSEL [[COPY]], [[COPY1]], [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_VSEL]](<16 x s32>)
    %0:_(<16 x s32>) = COPY $x0
    %1:_(<16 x s32>) = COPY $x2
    %2:_(<16 x s32>) = G_SHUFFLE_VECTOR %0(<16 x s32>), %1, shufflemask(0, 1, 2, 3, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31)
    PseudoRET implicit $lr, implicit %2
...

---
name: shuffle_vector_vsel_32_s16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $x0, $x2

    ; CHECK-LABEL: name: shuffle_vector_vsel_32_s16
    ; CHECK: liveins: $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<32 x s16>) = COPY $x2
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 -65536
    ; CHECK-NEXT: [[AIE_VSEL:%[0-9]+]]:_(<32 x s16>) = G_AIE_VSEL [[COPY]], [[COPY1]], [[C]](s32)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[AIE_VSEL]](<32 x s16>)
    %0:_(<32 x s16>) = COPY $x0
    %1:_(<32 x s16>) = COPY $x2
    %2:_(<32 x s16>) = G_SHUFFLE_VECTOR %0(<32 x s16>), %1, shufflemask(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63)
    PseudoRET implicit $lr, implicit %2
...
