# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=aie2-prelegalizer-combiner %s -verify-machineinstrs -o - | FileCheck %s

---
name:            vextract_broadcast8
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: vextract_broadcast8
    ; CHECK: [[COPY:%[0-9]+]]:_(<64 x s8>) = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:_(<64 x s8>) = G_INTRINSIC intrinsic(@llvm.aie2.vextract.broadcast8.I512), [[COPY]](<64 x s8>), [[COPY1]](s32)
    ; CHECK-NEXT: $x0 = COPY [[INT]](<64 x s8>)
    %1:_(<64 x s8>) = COPY $x2
    %2:_(s32) = COPY $r0
    %4:_(s32) = G_CONSTANT i32 1
    %3:_(s32) = G_INTRINSIC intrinsic(@llvm.aie2.vextract.elem8.I512), %1(<64 x s8>), %2(s32), %4(s32)
    %0:_(<64 x s8>) = G_INTRINSIC intrinsic(@llvm.aie2.vbroadcast8.I512), %3(s32)
    $x0 = COPY %0(<64 x s8>)
...

---
name:            vextract_broadcast16
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: vextract_broadcast16
    ; CHECK: [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:_(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2.vextract.broadcast16.I512), [[COPY]](<32 x s16>), [[COPY1]](s32)
    ; CHECK-NEXT: $x0 = COPY [[INT]](<32 x s16>)
    %1:_(<32 x s16>) = COPY $x2
    %2:_(s32) = COPY $r0
    %4:_(s32) = G_CONSTANT i32 1
    %3:_(s32) = G_INTRINSIC intrinsic(@llvm.aie2.vextract.elem16.I512), %1(<32 x s16>), %2(s32), %4(s32)
    %0:_(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2.vbroadcast16.I512), %3(s32)
    $x0 = COPY %0(<32 x s16>)
...

---
name:            vextract_broadcast32
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: vextract_broadcast32
    ; CHECK: [[COPY:%[0-9]+]]:_(<16 x s32>) = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:_(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2.vextract.broadcast32.I512), [[COPY]](<16 x s32>), [[COPY1]](s32)
    ; CHECK-NEXT: $x0 = COPY [[INT]](<16 x s32>)
    %1:_(<16 x s32>) = COPY $x2
    %2:_(s32) = COPY $r0
    %4:_(s32) = G_CONSTANT i32 1
    %3:_(s32) = G_INTRINSIC intrinsic(@llvm.aie2.vextract.elem32.I512), %1(<16 x s32>), %2(s32), %4(s32)
    %0:_(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2.vbroadcast32.I512), %3(s32)
    $x0 = COPY %0(<16 x s32>)
...

# Negative test case: Cannot be combined into vextract_broadcast due to type mismatch
---
name:            vextract_broadcast_type_mismatch
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: vextract_broadcast_type_mismatch
    ; CHECK: [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:_(s32) = G_INTRINSIC intrinsic(@llvm.aie2.vextract.elem16.I512), [[COPY]](<32 x s16>), [[COPY1]](s32), [[C]](s32)
    ; CHECK-NEXT: [[INT1:%[0-9]+]]:_(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2.vbroadcast32.I512), [[INT]](s32)
    ; CHECK-NEXT: $x0 = COPY [[INT1]](<16 x s32>)
    %1:_(<32 x s16>) = COPY $x2
    %2:_(s32) = COPY $r0
    %4:_(s32) = G_CONSTANT i32 1
    %3:_(s32) = G_INTRINSIC intrinsic(@llvm.aie2.vextract.elem16.I512), %1(<32 x s16>), %2(s32), %4(s32)
    %0:_(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2.vbroadcast32.I512), %3(s32)
    $x0 = COPY %0(<16 x s32>)
...

# Negative test case: Cannot be combined into vextract_broadcast because extracted element has been used by instruction other than broadcast
---
name:            vextract_broadcast_multiuse
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: vextract_broadcast_multiuse
    ; CHECK: [[COPY:%[0-9]+]]:_(<32 x s16>) = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $r0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[INT:%[0-9]+]]:_(s32) = G_INTRINSIC intrinsic(@llvm.aie2.vextract.elem16.I512), [[COPY]](<32 x s16>), [[COPY1]](s32), [[C]](s32)
    ; CHECK-NEXT: [[INT1:%[0-9]+]]:_(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2.vbroadcast16.I512), [[INT]](s32)
    ; CHECK-NEXT: $x0 = COPY [[INT1]](<32 x s16>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[INT]](s32)
    %1:_(<32 x s16>) = COPY $x2
    %2:_(s32) = COPY $r0
    %4:_(s32) = G_CONSTANT i32 1
    %3:_(s32) = G_INTRINSIC intrinsic(@llvm.aie2.vextract.elem16.I512), %1(<32 x s16>), %2(s32), %4(s32)
    %0:_(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2.vbroadcast16.I512), %3(s32)
    $x0 = COPY %0(<32 x s16>)
    PseudoRET implicit $lr, implicit %3
...
