# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2 -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck %s
...
---
name:            _Z12test_v4acc64v
alignment:       16
legalized:       true
tracksRegLiveness: true
registers:
  - { id: 0, class: _ }
frameInfo:
  maxAlignment:    1
machineFunctionInfo:
  varArgsFrameIndex: 0
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: _Z12test_v4acc64v
    ; CHECK: [[INT:%[0-9]+]]:accregbank(<4 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.v4acc64)
    ; CHECK-NEXT: $amll0 = COPY [[INT]](<4 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $amll0
    %0:_(<4 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.v4acc64)
    $amll0 = COPY %0(<4 x s64>)
    PseudoRET implicit $lr, implicit $amll0

...
---
name:            _Z12test_v8acc64v
alignment:       16
legalized:       true
tracksRegLiveness: true
registers:
  - { id: 0, class: _ }
frameInfo:
  maxAlignment:    1
machineFunctionInfo:
  varArgsFrameIndex: 0
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: _Z12test_v8acc64v
    ; CHECK: [[INT:%[0-9]+]]:accregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.v8acc64)
    ; CHECK-NEXT: $bml0 = COPY [[INT]](<8 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bml0
    %0:_(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.v8acc64)
    $bml0 = COPY %0(<8 x s64>)
    PseudoRET implicit $lr, implicit $bml0

...
---
name:            _Z13test_v16acc64v
alignment:       16
legalized:       true
tracksRegLiveness: true
registers:
  - { id: 0, class: _ }
frameInfo:
  maxAlignment:    1
machineFunctionInfo:
  varArgsFrameIndex: 0
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: _Z13test_v16acc64v
    ; CHECK: [[INT:%[0-9]+]]:accregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.v16acc64)
    ; CHECK-NEXT: $cm0 = COPY [[INT]](<16 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cm0
    %0:_(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.v16acc64)
    $cm0 = COPY %0(<16 x s64>)
    PseudoRET implicit $lr, implicit $cm0

...
---
name:            _Z12test_v8acc32v
alignment:       16
legalized:       true
tracksRegLiveness: true
registers:
  - { id: 0, class: _ }
frameInfo:
  maxAlignment:    1
machineFunctionInfo:
  varArgsFrameIndex: 0
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: _Z12test_v8acc32v
    ; CHECK: [[INT:%[0-9]+]]:accregbank(<4 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.v8acc32)
    ; CHECK-NEXT: $amll0 = COPY [[INT]](<4 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $amll0
    %0:_(<4 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.v8acc32)
    $amll0 = COPY %0(<4 x s64>)
    PseudoRET implicit $lr, implicit $amll0

...
---
name:            _Z13test_v16acc32v
alignment:       16
legalized:       true
tracksRegLiveness: true
registers:
  - { id: 0, class: _ }
frameInfo:
  maxAlignment:    1
machineFunctionInfo:
  varArgsFrameIndex: 0
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: _Z13test_v16acc32v
    ; CHECK: [[INT:%[0-9]+]]:accregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.v16acc32)
    ; CHECK-NEXT: $bml0 = COPY [[INT]](<8 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $bml0
    %0:_(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.v16acc32)
    $bml0 = COPY %0(<8 x s64>)
    PseudoRET implicit $lr, implicit $bml0

...
---
name:            _Z13test_v32acc32v
alignment:       16
legalized:       true
tracksRegLiveness: true
registers:
  - { id: 0, class: _ }
frameInfo:
  maxAlignment:    1
machineFunctionInfo:
  varArgsFrameIndex: 0
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: _Z13test_v32acc32v
    ; CHECK: [[INT:%[0-9]+]]:accregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.v32acc32)
    ; CHECK-NEXT: $cm0 = COPY [[INT]](<16 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cm0
    %0:_(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.v32acc32)
    $cm0 = COPY %0(<16 x s64>)
    PseudoRET implicit $lr, implicit $cm0

...
