# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2 -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck %s

---
name:            copy_256bit_acc
legalized:       true

body: |
  bb.0:
    liveins: $amll0
    ; CHECK-LABEL: name: copy_256bit_acc
    ; CHECK: liveins: $amll0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<4 x s64>) = COPY $amll0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY]](<4 x s64>)
    %0:_(<4 x s64>) = COPY $amll0
    PseudoRET implicit $lr, implicit %0
...

---
name:            copy_512bit_acc
legalized:       true

body: |
  bb.0:
    liveins: $bml0
    ; CHECK-LABEL: name: copy_512bit_acc
    ; CHECK: liveins: $bml0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<8 x s64>) = COPY $bml0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY]](<8 x s64>)
    %0:_(<8 x s64>) = COPY $bml0
    PseudoRET implicit $lr, implicit %0
...

---
name:            copy_1024bit_acc
legalized:       true

body: |
  bb.0:
    liveins: $cm0
    ; CHECK-LABEL: name: copy_1024bit_acc
    ; CHECK: liveins: $cm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:accregbank(<16 x s64>) = COPY $cm0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[COPY]](<16 x s64>)
    %0:_(<16 x s64>) = COPY $cm0
    PseudoRET implicit $lr, implicit %0
...
