# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple aie2 -run-pass=regbankselect %s -verify-machineinstrs -o - | FileCheck %s

---
name: test_fsub_bfloat16
legalized: true
body: |
  bb.0:
    liveins: $x0, $x1

    ; CHECK-LABEL: name: test_fsub_bfloat16
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<16 x s32>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<16 x s32>) = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<16 x s32>) = COPY [[COPY]](<16 x s32>)
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:accregbank(<16 x s32>) = COPY [[COPY1]](<16 x s32>)
    ; CHECK-NEXT: [[FSUB:%[0-9]+]]:accregbank(<16 x s32>) = G_FSUB [[COPY2]], [[COPY3]]
    ; CHECK-NEXT: $x0 = COPY [[FSUB]](<16 x s32>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $x0
    %0:_(<16 x s32>) = COPY $x0
    %1:_(<16 x s32>) = COPY $x1
    %2:_(<16 x s32>) = G_FSUB %0, %1
    $x0 = COPY %2(<16 x s32>)
    PseudoRET implicit $lr, implicit $x0
...
