# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2 -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck %s

---
name:            vec128_V16S8
legalized:       true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: vec128_V16S8
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[AIE_BROADCAST_VECTOR:%[0-9]+]]:vregbank(<64 x s8>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
  ; CHECK-NEXT:   [[AIE_UNPAD_VECTOR:%[0-9]+]]:vregbank(<16 x s8>) = G_AIE_UNPAD_VECTOR [[AIE_BROADCAST_VECTOR]](<64 x s8>)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:vregbank(<16 x s8>) = G_PHI [[AIE_UNPAD_VECTOR]](<16 x s8>), %bb.0, %4(<16 x s8>), %bb.1
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:vregbank(<64 x s8>) = G_INTRINSIC intrinsic(@llvm.aie2.set.I512.I128), [[PHI]](<16 x s8>)
  ; CHECK-NEXT:   [[INT1:%[0-9]+]]:vregbank(<16 x s8>) = G_INTRINSIC intrinsic(@llvm.aie2.extract.I128.I512), [[INT]](<64 x s8>)
  ; CHECK-NEXT:   G_BR %bb.1
  bb.0:
    successors: %bb.1(0x80000000)

    %0:_(s32) = G_CONSTANT i32 0
    %1:_(<64 x s8>) = G_AIE_BROADCAST_VECTOR %0(s32)
    %2:_(<16 x s8>) = G_AIE_UNPAD_VECTOR %1(<64 x s8>)

  bb.1:
    successors: %bb.1(0x80000000)

    %3:_(<16 x s8>) = G_PHI %2(<16 x s8>), %bb.0, %4(<16 x s8>), %bb.1
    %5:_(<64 x s8>) = G_INTRINSIC intrinsic(@llvm.aie2.set.I512.I128), %3(<16 x s8>)
    %4:_(<16 x s8>) = G_INTRINSIC intrinsic(@llvm.aie2.extract.I128.I512), %5(<64 x s8>)
    G_BR %bb.1

...
---
name:            vec128_8S16
legalized:       true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: vec128_8S16
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[AIE_BROADCAST_VECTOR:%[0-9]+]]:vregbank(<32 x s16>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
  ; CHECK-NEXT:   [[AIE_UNPAD_VECTOR:%[0-9]+]]:vregbank(<8 x s16>) = G_AIE_UNPAD_VECTOR [[AIE_BROADCAST_VECTOR]](<32 x s16>)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:vregbank(<8 x s16>) = G_PHI [[AIE_UNPAD_VECTOR]](<8 x s16>), %bb.0, %4(<8 x s16>), %bb.1
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:vregbank(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2.set.I512.I128), [[PHI]](<8 x s16>)
  ; CHECK-NEXT:   [[INT1:%[0-9]+]]:vregbank(<8 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2.extract.I128.I512), [[INT]](<32 x s16>)
  ; CHECK-NEXT:   G_BR %bb.1
  bb.0:
    successors: %bb.1(0x80000000)

    %0:_(s32) = G_CONSTANT i32 0
    %1:_(<32 x s16>) = G_AIE_BROADCAST_VECTOR %0(s32)
    %2:_(<8 x s16>) = G_AIE_UNPAD_VECTOR %1(<32 x s16>)

  bb.1:
    successors: %bb.1(0x80000000)

    %3:_(<8 x s16>) = G_PHI %2(<8 x s16>), %bb.0, %4(<8 x s16>), %bb.1
    %5:_(<32 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2.set.I512.I128), %3(<8 x s16>)
    %4:_(<8 x s16>) = G_INTRINSIC intrinsic(@llvm.aie2.extract.I128.I512), %5(<32 x s16>)
    G_BR %bb.1

...
---
name:            vec128_V4S32
legalized:       true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: vec128_V4S32
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[AIE_BROADCAST_VECTOR:%[0-9]+]]:vregbank(<16 x s32>) = G_AIE_BROADCAST_VECTOR [[C]](s32)
  ; CHECK-NEXT:   [[AIE_UNPAD_VECTOR:%[0-9]+]]:vregbank(<4 x s32>) = G_AIE_UNPAD_VECTOR [[AIE_BROADCAST_VECTOR]](<16 x s32>)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:vregbank(<4 x s32>) = G_PHI [[AIE_UNPAD_VECTOR]](<4 x s32>), %bb.0, %4(<4 x s32>), %bb.1
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:vregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2.set.I512.I128), [[PHI]](<4 x s32>)
  ; CHECK-NEXT:   [[INT1:%[0-9]+]]:vregbank(<4 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2.extract.I128.I512), [[INT]](<16 x s32>)
  ; CHECK-NEXT:   G_BR %bb.1
  bb.0:
    successors: %bb.1(0x80000000)

    %0:_(s32) = G_CONSTANT i32 0
    %1:_(<16 x s32>) = G_AIE_BROADCAST_VECTOR %0(s32)
    %2:_(<4 x s32>) = G_AIE_UNPAD_VECTOR %1(<16 x s32>)

  bb.1:
    successors: %bb.1(0x80000000)

    %3:_(<4 x s32>) = G_PHI %2(<4 x s32>), %bb.0, %4(<4 x s32>), %bb.1
    %5:_(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2.set.I512.I128), %3(<4 x s32>)
    %4:_(<4 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2.extract.I128.I512), %5(<16 x s32>)
    G_BR %bb.1

...
---
name:            vec64_V2S32
legalized:       true
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: vec64_V2S32
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $l0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gprregbank(<2 x s32>) = COPY $l0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gprregbank(<2 x s32>) = G_PHI [[COPY]](<2 x s32>), %bb.0, %2(<2 x s32>), %bb.1
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:vregbank(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2.vbroadcast64.I512), [[PHI]](<2 x s32>)
  ; CHECK-NEXT:   [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 14
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[INT1:%[0-9]+]]:gprregbank(<2 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2.vextract.elem64.I512), [[INT]](<16 x s32>), [[C]](s32), [[C1]](s32)
  ; CHECK-NEXT:   G_BR %bb.1
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $l0

    %0:_(<2 x s32>) = COPY $l0

  bb.1:
    successors: %bb.1(0x80000000)

    %1:_(<2 x s32>) = G_PHI %0(<2 x s32>), %bb.0, %2(<2 x s32>), %bb.1
    %3:_(<16 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2.vbroadcast64.I512), %1(<2 x s32>)
    %4:_(s32) = G_CONSTANT i32 14
    %5:_(s32) = G_CONSTANT i32 1
    %2:_(<2 x s32>) = G_INTRINSIC intrinsic(@llvm.aie2.vextract.elem64.I512), %3(<16 x s32>), %4(s32), %5(s32)
    G_BR %bb.1

...
