# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=regbankselect -regbankselect-fast %s -verify-machineinstrs -o - | FileCheck %s
# RUN: llc -mtriple aie2 -run-pass=regbankselect -regbankselect-greedy %s -verify-machineinstrs -o - | FileCheck %s
---
name:            test_negmsc_4x16_16x8
legalized:       true
body:             |
  bb.1.entry:
    liveins: $cm1, $x0, $x2

    ; CHECK-LABEL: name: test_negmsc_4x16_16x8
    ; CHECK: liveins: $cm1, $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vregbank(<64 x s8>) = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vregbank(<16 x s32>) = COPY $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:accregbank(<16 x s64>) = COPY $cm1
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprregbank(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[INT:%[0-9]+]]:accregbank(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.I512.I512.ACC1024.acc32.negmsc.conf), [[COPY]](<64 x s8>), [[COPY1]](<16 x s32>), [[COPY2]](<16 x s64>), [[C]](s32)
    ; CHECK-NEXT: $cm0 = COPY [[INT]](<16 x s64>)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit $cm0
    %1:_(<64 x s8>) = COPY $x0
    %2:_(<16 x s32>) = COPY $x2
    %3:_(<16 x s64>) = COPY $cm1
    %4:_(s32) = G_CONSTANT i32 0
    %0:_(<16 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.I512.I512.ACC1024.acc32.negmsc.conf), %1(<64 x s8>), %2(<16 x s32>), %3(<16 x s64>), %4(s32)
    $cm0 = COPY %0(<16 x s64>)
    PseudoRET implicit $lr, implicit $cm0

...
