# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple aie2 -run-pass=instruction-select -run-pass=liveintervals -verify-machineinstrs -o - %s 2>&1 | FileCheck %s

# This tests that we don't combine if one of the load's defs is used before the VUPS instruction
---
name:            VLD_UPS_use
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $p0, $m0, $m1, $m2, $r0
    ; CHECK-LABEL: name: VLD_UPS_use
    ; CHECK: liveins: $p0, $m0, $m1, $m2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ep = COPY $p0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:em = COPY $m0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:er = COPY $r0
    ; CHECK-NEXT: [[VLDA_dmw_lda_w_ag_pstm_nrm:%[0-9]+]]:vec256, [[VLDA_dmw_lda_w_ag_pstm_nrm1:%[0-9]+]]:ep = VLDA_dmw_lda_w_ag_pstm_nrm [[COPY]], [[COPY1]] :: (load (<16 x s16>))
    ; CHECK-NEXT: $m1 = COPY [[VLDA_dmw_lda_w_ag_pstm_nrm1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ep = COPY $m1
    ; CHECK-NEXT: $crupssign = COPY [[COPY2]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:mss = COPY [[COPY2]]
    ; CHECK-NEXT: [[VUPS_S64_D16_mv_ups_w2c:%[0-9]+]]:mcms = VUPS_S64_D16_mv_ups_w2c [[VLDA_dmw_lda_w_ag_pstm_nrm]], [[COPY4]], implicit-def $srups_of, implicit $crsat, implicit $crupssign
    ; CHECK-NEXT: $crupssign = MOV_scalar_imm10_pseudo 0
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit [[VUPS_S64_D16_mv_ups_w2c]], implicit [[COPY3]]
    %0:ptrregbank(p0) = COPY $p0
    %7:modregbank(s20) = COPY $m0
    %70:gprregbank(s32) = COPY $r0
    %25:vregbank(<16 x s16>), %19:ptrregbank(p0) = G_AIE_POSTINC_LOAD %0, %7 :: (load (<16 x s16>))
    $m1 = COPY %19:ptrregbank(p0)
    %12:ptrregbank(p0) = COPY $m1
    %103:accregbank(<8 x s64>) = G_INTRINSIC intrinsic(@llvm.aie2.acc64.v16.I256.ups), %25:vregbank(<16 x s16>),  %70:gprregbank(s32),  %70:gprregbank(s32)
    PseudoRET implicit $lr, implicit %103, implicit %12
...
