# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# CHECK lines automatically generated using update_encodings.py
# RUN: llc %llcflags --filetype=obj -o %t
# RUN: llvm-objdump --triple=aie2 -dr --no-print-imm-hex %t | FileCheck %s
# RUN: llc %llcflags --filetype=asm -o %t2
# RUN: llvm-mc -triple aie2 -filetype=obj -o %t %t2
# RUN: llvm-objdump --triple=aie2 -dr --no-print-imm-hex %t | FileCheck %s

---
name:            st_q
alignment:       16
body:             |
  bb.0 (align 16):
    ; ST - Stores - ag_idx_imm
    ST_dmv_sts_q_ag_idx_imm $q0, $p2, 0
    ST_dmv_sts_q_ag_idx_imm $q2, $p2, 32
    ST_dmv_sts_q_ag_idx_imm $q1, $p5, 496
    ST_dmv_sts_q_ag_idx_imm $q3, $p5, -512

    ; ST - Stores - ag_spill
    ST_dmv_sts_q_ag_spill $q0, -32, implicit $sp
    ST_dmv_sts_q_ag_spill $q1, -16, implicit $sp
    ST_dmv_sts_q_ag_spill $q2, -65520, implicit $sp
    ST_dmv_sts_q_ag_spill $q3, -65536, implicit $sp

    ; ST - Stores - ag_idx
    ST_dmv_sts_q_ag_idx $q0, $p2, $dj2
    ST_dmv_sts_q_ag_idx $q1, $p2, $dj1
    ST_dmv_sts_q_ag_idx $q2, $p5, $dj0
    ST_dmv_sts_q_ag_idx $q3, $p5, $dj4

    ; ST - Stores - ag_pstm_nrm
    $p2 = ST_dmv_sts_q_ag_pstm_nrm $q0, $p2, $m4
    $p2 = ST_dmv_sts_q_ag_pstm_nrm $q1, $p2, $m3
    $p5 = ST_dmv_sts_q_ag_pstm_nrm $q2, $p5, $m2
    $p5 = ST_dmv_sts_q_ag_pstm_nrm $q3, $p5, $m0

    ; ST - Stores - ag_pstm_nrm_imm
    $p2 = ST_dmv_sts_q_ag_pstm_nrm_imm $q0, $p2, 0
    $p2 = ST_dmv_sts_q_ag_pstm_nrm_imm $q1, $p2, -1024
    $p5 = ST_dmv_sts_q_ag_pstm_nrm_imm $q2, $p5, 1008
    $p5 = ST_dmv_sts_q_ag_pstm_nrm_imm $q3, $p5, -256

    ; ST - Stores - ag_pstm_2d
    $p2, $dc2 = ST_2D_dmv_sts_q $q0, $p2, $d2
    $p2, $dc1 = ST_2D_dmv_sts_q $q1, $p2, $d1
    $p5, $dc0 = ST_2D_dmv_sts_q $q2, $p5, $d0
    $p5, $dc4 = ST_2D_dmv_sts_q $q3, $p5, $d4

    ; ST - Stores - ag_pstm_3d
    $p0, $dc0, $dc4 = ST_3D_dmv_sts_q $q0, $p0, $d0_3d
    $p2, $dc1, $dc5 = ST_3D_dmv_sts_q $q1, $p2, $d1_3d
    $p4, $dc2, $dc6 = ST_3D_dmv_sts_q $q2, $p4, $d2_3d
    $p5, $dc3, $dc7 = ST_3D_dmv_sts_q $q3, $p5, $d3_3d
...
# CHECK: 0: 99 8a 02 0a st q0, [p2, #0]
# CHECK: 4: 99 aa 0a 0a st q2, [p2, #32]
# CHECK: 8: 99 9a 7e 0d st q1, [p5, #496]
# CHECK: c: 99 ba 82 0d st q3, [p5, #-512]
# CHECK: 10: 99 4a ff 0f st q0, [sp, #-32]
# CHECK: 14: 99 da ff 0f st q1, [sp, #-16]
# CHECK: 18: 99 ea 00 08 st q2, [sp, #-65520]
# CHECK: 1c: 99 7a 00 08 st q3, [sp, #-65536]
# CHECK: 20: 99 8a 50 0a st q0, [p2, dj2]
# CHECK: 24: 99 9a 30 0a st q1, [p2, dj1]
# CHECK: 28: 99 aa 10 0d st q2, [p5, dj0]
# CHECK: 2c: 99 ba 90 0d st q3, [p5, dj4]
# CHECK: 30: 99 8a 88 0a st q0, [p2], m4
# CHECK: 34: 99 9a 68 0a st q1, [p2], m3
# CHECK: 38: 99 aa 48 0d st q2, [p5], m2
# CHECK: 3c: 99 ba 08 0d st q3, [p5], m0
# CHECK: 40: 99 8a 01 0a st q0, [p2], #0
# CHECK: 44: 99 9a 81 0a st q1, [p2], #-1024
# CHECK: 48: 99 aa 7f 0d st q2, [p5], #1008
# CHECK: 4c: 99 ba e1 0d st q3, [p5], #-256
# CHECK: 50: 99 8a 58 0a st.2d q0, [p2], d2
# CHECK: 54: 99 9a 38 0a st.2d q1, [p2], d1
# CHECK: 58: 99 aa 18 0d st.2d q2, [p5], d0
# CHECK: 5c: 99 ba 98 0d st.2d q3, [p5], d4
# CHECK: 60: 99 8a 00 08 st.3d q0, [p0], d0
# CHECK: 64: 99 9a 20 0a st.3d q1, [p2], d1
# CHECK: 68: 99 aa 40 0c st.3d q2, [p4], d2
# CHECK: 6c: 99 ba 60 0d st.3d q3, [p5], d3
