# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2 --verify-machineinstrs -run-pass=greedy -run-pass=virtregrewriter %s -o - | FileCheck %s

# There is only one eDC (MOD) register available, it will then be used for the %0
# virtual register. Here we test that it is properly spilled and then reloaded.

# %0 isn't used by "real" instructions directly, greedy assumes the reg class
# would not benefit from enlarging, and prefers spilling.
---
  name:            spill_to_mem
  alignment:       16
  legalized:       true
  regBankSelected: true
  selected:        true
  tracksRegLiveness: true
  body:             |
    bb.1.entry:
      liveins: $p0, $dc0, $dc1, $dc2, $dc3, $dc4, $dc5, $dc6, $dc7

    ; CHECK-LABEL: name: spill_to_mem
    ; CHECK: liveins: $dc0, $dc1, $dc2, $dc3, $dc4, $dc5, $dc6, $dc7, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: ST_dms_spill $dc0, %stack.0, implicit $sp :: (store (s32) into %stack.0)
    ; CHECK-NEXT: $dc0 = COPY $dc1
    ; CHECK-NEXT: ST_dms_sts_idx_imm $dc0, $p0, 0, implicit $dc1, implicit $dc2, implicit $dc3, implicit $dc4, implicit $dc5, implicit $dc6, implicit $dc7
    ; CHECK-NEXT: renamable $dc0 = LDA_dms_spill %stack.0, implicit $sp :: (load (s32) from %stack.0)
    ; CHECK-NEXT: PseudoRET implicit $lr, implicit killed renamable $dc0
      %0:edc = COPY $dc0 ; -> only $dc0 is available

      ; spill $dc0 before it is re-defined and used
      $dc0 = COPY $dc1
      ST_dms_sts_idx_imm $dc0, $p0, 0, implicit $dc1, implicit $dc2, implicit $dc3, implicit $dc4, implicit $dc5, implicit $dc6, implicit $dc7

      ; reload %0 / $dc0 before PseudoRET
      PseudoRET implicit $lr, implicit %0
...

# %0 is used by "real" instructions, but those impose no strict constraints
# on the current reg class. Greedy prefers spilling, because splitting is
# "similar to spilling", only without the extra COPY instructions.
---
  name:            spill_to_mem2
  alignment:       16
  legalized:       true
  regBankSelected: true
  selected:        true
  tracksRegLiveness: true
  body:             |
    bb.1.entry:
      liveins: $p0, $dc1, $dc2, $dc3, $dc4, $dc5, $dc6, $dc7

    ; CHECK-LABEL: name: spill_to_mem2
    ; CHECK: liveins: $dc1, $dc2, $dc3, $dc4, $dc5, $dc6, $dc7, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $dc0 = LDA_dms_lda_idx_imm $p0, 0
    ; CHECK-NEXT: ST_dms_spill killed renamable $dc0, %stack.0, implicit $sp :: (store (s32) into %stack.0)
    ; CHECK-NEXT: $dc0 = COPY $dc1
    ; CHECK-NEXT: ST_dms_sts_idx_imm $dc0, $p0, 0, implicit $dc1, implicit $dc2, implicit $dc3, implicit $dc4, implicit $dc5, implicit $dc6, implicit $dc7
    ; CHECK-NEXT: renamable $dc0 = LDA_dms_spill %stack.0, implicit $sp :: (load (s32) from %stack.0)
    ; CHECK-NEXT: ST_dms_sts_idx_imm killed renamable $dc0, $p0, 4
      %0:edc_as_32bit = LDA_dms_lda_idx_imm $p0, 0 ; -> only $dc0 is available

      ; spill $dc0 before it is re-defined and used
      $dc0 = COPY $dc1
      ST_dms_sts_idx_imm $dc0, $p0, 0, implicit $dc1, implicit $dc2, implicit $dc3, implicit $dc4, implicit $dc5, implicit $dc6, implicit $dc7

      ; reload %0 / $dc0 before ST
      ST_dms_sts_idx_imm %0, $p0, 4
...

# FIXME: Once we have PADDA_2D_split with an explicit use of %0, the latter
# should be spilled "to GPRs" instead of to memory.
---
  name:            spill_to_reg
  alignment:       16
  legalized:       true
  regBankSelected: true
  selected:        true
  tracksRegLiveness: true
  body:             |
    bb.1.entry:
      liveins: $p0, $dc0, $dc1, $dc2, $dc3, $dc4, $dc5, $dc6, $dc7

    ; CHECK-LABEL: name: spill_to_reg
    ; CHECK: liveins: $dc0, $dc1, $dc2, $dc3, $dc4, $dc5, $dc6, $dc7, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: ST_dms_spill $dc0, %stack.0, implicit $sp :: (store (s32) into %stack.0)
    ; CHECK-NEXT: $dc0 = COPY $dc1
    ; CHECK-NEXT: ST_dms_sts_idx_imm $dc0, $p0, 0, implicit $dc1, implicit $dc2, implicit $dc3, implicit $dc4, implicit $dc5, implicit $dc6, implicit $dc7
    ; CHECK-NEXT: $dc0 = LDA_dms_spill %stack.0, implicit $sp :: (load (s32) from %stack.0)
    ; CHECK-NEXT: $p0, $dc0 = PADDA_2D $p0, $d0
      %0:edc = COPY $dc0 ; -> only $dc0 is available

      ; spill $dc0 before it is re-defined and used
      $dc0 = COPY $dc1
      ST_dms_sts_idx_imm $dc0, $p0, 0, implicit $dc1, implicit $dc2, implicit $dc3, implicit $dc4, implicit $dc5, implicit $dc6, implicit $dc7

      ; reload %0 / $dc0 before PADDA_2D
      $dc0 = COPY %0
      $p0, $dc0 = PADDA_2D $p0, $d0
...
