# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2023-2024 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -mtriple=aie2 --verify-machineinstrs --aie-reserved-gprs=32 -run-pass=greedy -run-pass=virtregrewriter %s -o - | FileCheck %s

# There is only one eDJ (stride dim) register available, it will then be used for the %0
# virtual register. Here we test that it is properly spilled and then reloaded.

# Here it is "spilled" to DN, as there are no GPRs left due to --aie-reserved-gprs.
---
  name:            spill_to_dn_reg
  alignment:       16
  legalized:       true
  regBankSelected: true
  selected:        true
  tracksRegLiveness: true
  body:             |
    bb.1.entry:
      liveins: $p0, $dj0, $dj1, $dj2, $dj3, $dj4, $dj5, $dj6, $dj7

    ; CHECK-LABEL: name: spill_to_dn_reg
    ; CHECK: liveins: $dj0, $dj1, $dj2, $dj3, $dj4, $dj5, $dj6, $dj7, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $dn0 = COPY $dj0
    ; CHECK-NEXT: $dj0 = COPY $dj1
    ; CHECK-NEXT: ST_dms_sts_idx_imm $dj0, $p0, 0, implicit $dj1, implicit $dj2, implicit $dj3, implicit $dj4, implicit $dj5, implicit $dj6, implicit $dj7
    ; CHECK-NEXT: renamable $dj0 = COPY killed renamable $dn0
    ; CHECK-NEXT: ST_dms_sts_idx $r0, $p0, killed renamable $dj0
      %0:edj = COPY $dj0 ; -> only $dj0 is available

      ; spill $dj0 before it is re-defined and used
      $dj0 = COPY $dj1
      ST_dms_sts_idx_imm $dj0, $p0, 0, implicit $dj1, implicit $dj2, implicit $dj3, implicit $dj4, implicit $dj5, implicit $dj6, implicit $dj7

      ; reload %0 / $dj0 before it is used as an offset in ST
      ST_dms_sts_idx $r0, $p0, %0
...

# Here it is spilled to memory, as there are no GPRs left due to --aie-reserved-gprs,
# and no DN registers left either.
---
  name:            spill_to_mem
  alignment:       16
  legalized:       true
  regBankSelected: true
  selected:        true
  tracksRegLiveness: true
  body:             |
    bb.1.entry:
      liveins: $p0, $dj0, $dj1, $dj2, $dj3, $dj4, $dj5, $dj6, $dj7, $dn0 , $dn1 , $dn2 , $dn3 , $dn4 , $dn5 , $dn6 , $dn7

    ; CHECK-LABEL: name: spill_to_mem
    ; CHECK: liveins: $dj0, $dj1, $dj2, $dj3, $dj4, $dj5, $dj6, $dj7, $dn0, $dn1, $dn2, $dn3, $dn4, $dn5, $dn6, $dn7, $p0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: ST_dms_spill $dj0, %stack.0, implicit $sp :: (store (s32) into %stack.0)
    ; CHECK-NEXT: $dj0 = COPY $dj1
    ; CHECK-NEXT: ST_dms_sts_idx_imm $dj0, $p0, 0, implicit $dj1, implicit $dj2, implicit $dj3, implicit $dj4, implicit $dj5, implicit $dj6, implicit $dj7, implicit $dn0, implicit $dn1, implicit $dn2, implicit $dn3, implicit $dn4, implicit $dn5, implicit $dn6, implicit $dn7
    ; CHECK-NEXT: renamable $dj0 = LDA_dms_spill %stack.0, implicit $sp :: (load (s32) from %stack.0)
    ; CHECK-NEXT: ST_dms_sts_idx $r0, $p0, killed renamable $dj0
      %0:edj = COPY $dj0 ; -> only $dj0 is available

      ; spill $dj0 before it is re-defined and used
      $dj0 = COPY $dj1
      ST_dms_sts_idx_imm $dj0, $p0, 0, implicit $dj1, implicit $dj2, implicit $dj3, implicit $dj4, implicit $dj5, implicit $dj6, implicit $dj7, implicit $dn0 , implicit $dn1 , implicit $dn2 , implicit $dn3 , implicit $dn4 , implicit $dn5 , implicit $dn6 , implicit $dn7

      ; reload %0 / $dj0 before it is used as an offset in ST
      ST_dms_sts_idx $r0, $p0, %0
...
