# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2p -run-pass=postmisched %s -o - | FileCheck %s

# The test checks LD_FIFO_WA_PORT resource which is accessed
# by VLDA_FILL_512 at cycle 7 and by VMOV_alu_mv_mv_x at cycle 2.
---
name:            E7_VLDA_FILL_512_E2_VMOV_x
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p0, $lf0, $r24, $x9
    ; CHECK-LABEL: name: E7_VLDA_FILL_512_E2_VMOV_x
    ; CHECK: liveins: $p0, $lf0, $r24, $x9
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $p0, $lf0, $r24 = VLDA_FILL_512 killed $p0, killed $lf0, killed $r24
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: $lfl1 = VMOV_alu_mv_mv_x killed $x9
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $p0, $lf0, $r24 = VLDA_FILL_512 $p0, $lf0, $r24
    $lfl1 = VMOV_alu_mv_mv_x $x9
...
