# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2p -run-pass=postmisched %topdown-multi %s -o - | FileCheck %s

# This test checks that we are scheduling multislot padds in one VLIW bundle.

---
name:            PADD_2D_pseudo
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: PADD_2D_pseudo
    ; CHECK: BUNDLE implicit-def $p3, implicit-def $dc1, implicit-def $p7, implicit-def $dc3, implicit-def $p1, implicit-def $dc4, implicit killed $p3, implicit killed $d1, implicit killed $p7, implicit killed $d3, implicit killed $p1, implicit killed $d4 {
    ; CHECK-NEXT:   $p3, $dc1 = PADDA_2D killed $p3, killed $d1
    ; CHECK-NEXT:   $p7, $dc3 = PADDB_2D killed $p7, killed $d3
    ; CHECK-NEXT:   $p1, $dc4 = PADDS_2D killed $p1, killed $d4
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    $p7, $dc3 = PADD_2D_pseudo $p7, $d3
    $p1, $dc4 = PADD_2D_pseudo $p1, $d4
    $p3, $dc1 = PADD_2D_pseudo $p3, $d1
...

---
name:            PADD_3D_pseudo
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: PADD_3D_pseudo
    ; CHECK: BUNDLE implicit-def $p6, implicit-def $dc3, implicit-def $dc7, implicit-def $p3, implicit-def $dc2, implicit-def $dc6, implicit-def $p2, implicit-def $dc0, implicit-def $dc4, implicit killed $p6, implicit killed $d3_3d, implicit killed $p3, implicit killed $d2_3d, implicit killed $p2, implicit killed $d0_3d {
    ; CHECK-NEXT:   $p6, $dc3, $dc7 = PADDA_3D killed $p6, killed $d3_3d
    ; CHECK-NEXT:   $p3, $dc2, $dc6 = PADDB_3D killed $p3, killed $d2_3d
    ; CHECK-NEXT:   $p2, $dc0, $dc4 = PADDS_3D killed $p2, killed $d0_3d
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    $p3, $dc2, $dc6 = PADD_3D_pseudo $p3, $d2_3d
    $p2, $dc0, $dc4 = PADD_3D_pseudo $p2, $d0_3d
    $p6, $dc3, $dc7 = PADD_3D_pseudo $p6, $d3_3d
...
