# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2p -run-pass=postmisched %s -o - | FileCheck %s

# This test checks that we are scheduling multislot loads from different banks in one VLIW bundle.

---
name:            VLD_w_idx_pseudo_same_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_w_idx_pseudo_same_bank
    ; CHECK: $wh4 = VLDB_dmw_ldb_idx killed $p2, killed $dj2 :: (load (<8 x s32>), addrspace 9)
    ; CHECK-NEXT: $wh2 = VLDB_dmw_ldb_idx killed $p1, killed $dj4 :: (load (<8 x s32>), addrspace 9)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wh4 = VLD_w_idx_pseudo $p2, $dj2 :: (load (<8 x s32>), addrspace 9)
    $wh2 = VLD_w_idx_pseudo $p1, $dj4 :: (load (<8 x s32>), addrspace 9)
...

---
name:            VLD_w_idx_pseudo_diff_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_w_idx_pseudo_diff_bank
    ; CHECK: BUNDLE implicit-def $wh4, implicit-def $wh2, implicit killed $p2, implicit killed $dj2, implicit killed $p1, implicit killed $dj4 {
    ; CHECK-NEXT:   $wh4 = VLDA_dmw_lda_w_idx killed $p2, killed $dj2 :: (load (<8 x s32>), addrspace 14)
    ; CHECK-NEXT:   $wh2 = VLDB_dmw_ldb_idx killed $p1, killed $dj4 :: (load (<8 x s32>), addrspace 9)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wh4 = VLD_w_idx_pseudo $p2, $dj2 :: (load (<8 x s32>), addrspace 14)
    $wh2 = VLD_w_idx_pseudo $p1, $dj4 :: (load (<8 x s32>), addrspace 9)
...

---
name:            VLD_w_idx_imm_pseudo_same_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_w_idx_imm_pseudo_same_bank
    ; CHECK: $wh4 = VLDB_dmw_ldb_idx_imm killed $p2, 0 :: (load (<8 x s32>), addrspace 9)
    ; CHECK-NEXT: $wh2 = VLDB_dmw_ldb_idx_imm killed $p1, 32 :: (load (<8 x s32>), addrspace 9)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wh4 = VLD_w_idx_imm_pseudo $p2, 0 :: (load (<8 x s32>), addrspace 9)
    $wh2 = VLD_w_idx_imm_pseudo $p1, 32 :: (load (<8 x s32>), addrspace 9)
...

---
name:            VLD_w_idx_imm_pseudo_diff_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_w_idx_imm_pseudo_diff_bank
    ; CHECK: BUNDLE implicit-def $wh4, implicit-def $wh2, implicit killed $p2, implicit killed $p1 {
    ; CHECK-NEXT:   $wh4 = VLDA_dmw_lda_w_idx_imm killed $p2, 0 :: (load (<8 x s32>), addrspace 14)
    ; CHECK-NEXT:   $wh2 = VLDB_dmw_ldb_idx_imm killed $p1, 32 :: (load (<8 x s32>), addrspace 9)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wh4 = VLD_w_idx_imm_pseudo $p2, 0 :: (load (<8 x s32>), addrspace 14)
    $wh2 = VLD_w_idx_imm_pseudo $p1, 32 :: (load (<8 x s32>), addrspace 9)
...

---
name:            VLD_w_pstm_nrm_pseudo_same_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_w_pstm_nrm_pseudo_same_bank
    ; CHECK: $wl9, $p4 = VLDB_dmw_ldb_pstm_nrm killed $p4, killed $m4 :: (load (<8 x s32>), addrspace 9)
    ; CHECK-NEXT: $wh2, $p5 = VLDB_dmw_ldb_pstm_nrm killed $p5, killed $m0 :: (load (<8 x s32>), addrspace 9)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl9, $p4 = VLD_w_pstm_nrm_pseudo $p4, $m4 :: (load (<8 x s32>), addrspace 9)
    $wh2, $p5 = VLD_w_pstm_nrm_pseudo $p5, $m0 :: (load (<8 x s32>), addrspace 9)
...

---
name:            VLD_w_pstm_nrm_pseudo_diff_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_w_pstm_nrm_pseudo_diff_bank
    ; CHECK: BUNDLE implicit-def $wl9, implicit-def $p4, implicit-def $wh2, implicit-def $p5, implicit killed $p4, implicit killed $m4, implicit killed $p5, implicit killed $m0 {
    ; CHECK-NEXT:   $wl9, $p4 = VLDA_dmw_lda_w_pstm_nrm killed $p4, killed $m4 :: (load (<8 x s32>), addrspace 14)
    ; CHECK-NEXT:   $wh2, $p5 = VLDB_dmw_ldb_pstm_nrm killed $p5, killed $m0 :: (load (<8 x s32>), addrspace 9)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl9, $p4 = VLD_w_pstm_nrm_pseudo $p4, $m4 :: (load (<8 x s32>), addrspace 14)
    $wh2, $p5 = VLD_w_pstm_nrm_pseudo $p5, $m0 :: (load (<8 x s32>), addrspace 9)
...

---
name:            VLD_w_pstm_nrm_imm_pseudo_same_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_w_pstm_nrm_imm_pseudo_same_bank
    ; CHECK: $wl9, $p4 = VLDB_dmw_ldb_pstm_nrm_imm killed $p4, 0 :: (load (<8 x s32>), addrspace 9)
    ; CHECK-NEXT: $wh2, $p5 = VLDB_dmw_ldb_pstm_nrm_imm killed $p5, 64 :: (load (<8 x s32>), addrspace 9)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl9, $p4 = VLD_w_pstm_nrm_imm_pseudo $p4, 0 :: (load (<8 x s32>), addrspace 9)
    $wh2, $p5 = VLD_w_pstm_nrm_imm_pseudo $p5, 64 :: (load (<8 x s32>), addrspace 9)
...

---
name:            VLD_w_pstm_nrm_imm_pseudo_diff_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_w_pstm_nrm_imm_pseudo_diff_bank
    ; CHECK: BUNDLE implicit-def $wl9, implicit-def $p4, implicit-def $wh2, implicit-def $p5, implicit killed $p4, implicit killed $p5 {
    ; CHECK-NEXT:   $wl9, $p4 = VLDA_dmw_lda_w_pstm_nrm_imm killed $p4, 0 :: (load (<8 x s32>), addrspace 14)
    ; CHECK-NEXT:   $wh2, $p5 = VLDB_dmw_ldb_pstm_nrm_imm killed $p5, 64 :: (load (<8 x s32>), addrspace 9)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl9, $p4 = VLD_w_pstm_nrm_imm_pseudo $p4, 0 :: (load (<8 x s32>), addrspace 14)
    $wh2, $p5 = VLD_w_pstm_nrm_imm_pseudo $p5, 64 :: (load (<8 x s32>), addrspace 9)
...

---
name:            VLD_x_idx_pseudo_same_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_x_idx_pseudo_same_bank
    ; CHECK: $x0 = VLDB_dmx_ldb_x_idx killed $p2, killed $dj2 :: (load (<16 x s32>), addrspace 9)
    ; CHECK-NEXT: $x1 = VLDB_dmx_ldb_x_idx killed $p1, killed $dj4 :: (load (<16 x s32>), addrspace 9)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $x0 = VLD_x_idx_pseudo $p2, $dj2 :: (load (<16 x s32>), addrspace 9)
    $x1 = VLD_x_idx_pseudo $p1, $dj4 :: (load (<16 x s32>), addrspace 9)
...

---
name:            VLD_x_idx_pseudo_diff_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_x_idx_pseudo_diff_bank
    ; CHECK: BUNDLE implicit-def $x0, implicit-def $wl0, implicit-def $wh0, implicit-def $x1, implicit-def $wl1, implicit-def $wh1, implicit killed $p2, implicit killed $dj2, implicit killed $p1, implicit killed $dj4 {
    ; CHECK-NEXT:   $x0 = VLDA_dmx_lda_x_idx killed $p2, killed $dj2 :: (load (<16 x s32>), addrspace 14)
    ; CHECK-NEXT:   $x1 = VLDB_dmx_ldb_x_idx killed $p1, killed $dj4 :: (load (<16 x s32>), addrspace 9)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $x0 = VLD_x_idx_pseudo $p2, $dj2 :: (load (<16 x s32>), addrspace 14)
    $x1 = VLD_x_idx_pseudo $p1, $dj4 :: (load (<16 x s32>), addrspace 9)
...

---
name:            VLD_x_idx_imm_pseudo_same_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_x_idx_imm_pseudo_same_bank
    ; CHECK: $x0 = VLDB_dmx_ldb_x_idx_imm killed $p2, 0 :: (load (<16 x s32>), addrspace 9)
    ; CHECK-NEXT: $x1 = VLDB_dmx_ldb_x_idx_imm killed $p1, 32 :: (load (<16 x s32>), addrspace 9)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $x0 = VLD_x_idx_imm_pseudo $p2, 0 :: (load (<16 x s32>), addrspace 9)
    $x1 = VLD_x_idx_imm_pseudo $p1, 32 :: (load (<16 x s32>), addrspace 9)
...

---
name:            VLD_x_idx_imm_pseudo_diff_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_x_idx_imm_pseudo_diff_bank
    ; CHECK: BUNDLE implicit-def $x0, implicit-def $wl0, implicit-def $wh0, implicit-def $x1, implicit-def $wl1, implicit-def $wh1, implicit killed $p2, implicit killed $p1 {
    ; CHECK-NEXT:   $x0 = VLDA_dmx_lda_x_idx_imm killed $p2, 0 :: (load (<16 x s32>), addrspace 14)
    ; CHECK-NEXT:   $x1 = VLDB_dmx_ldb_x_idx_imm killed $p1, 32 :: (load (<16 x s32>), addrspace 9)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $x0 = VLD_x_idx_imm_pseudo $p2, 0 :: (load (<16 x s32>), addrspace 14)
    $x1 = VLD_x_idx_imm_pseudo $p1, 32 :: (load (<16 x s32>), addrspace 9)
...

---
name:            VLD_x_pstm_nrm_pseudo_same_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_x_pstm_nrm_pseudo_same_bank
    ; CHECK: $x0, $p4 = VLDB_dmx_ldb_x_pstm_nrm killed $p4, killed $m4 :: (load (<16 x s32>), addrspace 9)
    ; CHECK-NEXT: $x1, $p5 = VLDB_dmx_ldb_x_pstm_nrm killed $p5, killed $m0 :: (load (<16 x s32>), addrspace 9)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $x0, $p4 = VLD_x_pstm_nrm_pseudo $p4, $m4 :: (load (<16 x s32>), addrspace 9)
    $x1, $p5 = VLD_x_pstm_nrm_pseudo $p5, $m0 :: (load (<16 x s32>), addrspace 9)
...

---
name:            VLD_x_pstm_nrm_pseudo_diff_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_x_pstm_nrm_pseudo_diff_bank
    ; CHECK: BUNDLE implicit-def $x0, implicit-def $wl0, implicit-def $wh0, implicit-def $p4, implicit-def $x1, implicit-def $wl1, implicit-def $wh1, implicit-def $p5, implicit killed $p4, implicit killed $m4, implicit killed $p5, implicit killed $m0 {
    ; CHECK-NEXT:   $x0, $p4 = VLDA_dmx_lda_x_pstm_nrm killed $p4, killed $m4 :: (load (<16 x s32>), addrspace 14)
    ; CHECK-NEXT:   $x1, $p5 = VLDB_dmx_ldb_x_pstm_nrm killed $p5, killed $m0 :: (load (<16 x s32>), addrspace 9)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $x0, $p4 = VLD_x_pstm_nrm_pseudo $p4, $m4 :: (load (<16 x s32>), addrspace 14)
    $x1, $p5 = VLD_x_pstm_nrm_pseudo $p5, $m0 :: (load (<16 x s32>), addrspace 9)
...

---
name:            VLD_x_pstm_nrm_imm_pseudo_same_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_x_pstm_nrm_imm_pseudo_same_bank
    ; CHECK: $x0, $p4 = VLDB_dmx_ldb_x_pstm_nrm_imm killed $p4, 0 :: (load (<16 x s32>), addrspace 9)
    ; CHECK-NEXT: $x1, $p5 = VLDB_dmx_ldb_x_pstm_nrm_imm killed $p5, 64 :: (load (<16 x s32>), addrspace 9)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $x0, $p4 = VLD_x_pstm_nrm_imm_pseudo $p4, 0 :: (load (<16 x s32>), addrspace 9)
    $x1, $p5 = VLD_x_pstm_nrm_imm_pseudo $p5, 64 :: (load (<16 x s32>), addrspace 9)
...

---
name:            VLD_x_pstm_nrm_imm_pseudo_diff_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_x_pstm_nrm_imm_pseudo_diff_bank
    ; CHECK: BUNDLE implicit-def $x0, implicit-def $wl0, implicit-def $wh0, implicit-def $p4, implicit-def $x1, implicit-def $wl1, implicit-def $wh1, implicit-def $p5, implicit killed $p4, implicit killed $p5 {
    ; CHECK-NEXT:   $x0, $p4 = VLDA_dmx_lda_x_pstm_nrm_imm killed $p4, 0 :: (load (<16 x s32>), addrspace 14)
    ; CHECK-NEXT:   $x1, $p5 = VLDB_dmx_ldb_x_pstm_nrm_imm killed $p5, 64 :: (load (<16 x s32>), addrspace 9)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $x0, $p4 = VLD_x_pstm_nrm_imm_pseudo $p4, 0 :: (load (<16 x s32>), addrspace 14)
    $x1, $p5 = VLD_x_pstm_nrm_imm_pseudo $p5, 64 :: (load (<16 x s32>), addrspace 9)
...

---
name:            VLD_2D_w_pseudo_same_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_2D_w_pseudo_same_bank
    ; CHECK: $wh3, $p7, $dc5 = VLDB_2D_dmw_ldb killed $p7, killed $d5 :: (load (<8 x s32>), addrspace 9)
    ; CHECK-NEXT: $wh4, $p7, $dc7 = VLDB_2D_dmw_ldb killed $p6, killed $d7 :: (load (<8 x s32>), addrspace 9)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wh3, $p7, $dc5 = VLD_2D_w_pseudo $p7, $d5 :: (load (<8 x s32>), addrspace 9)
    $wh4, $p7, $dc7 = VLD_2D_w_pseudo $p6, $d7 :: (load (<8 x s32>), addrspace 9)
...

---
name:            VLD_2D_w_pseudo_diff_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_2D_w_pseudo_diff_bank
    ; CHECK: BUNDLE implicit-def $wh3, implicit-def $p7, implicit-def $dc5, implicit-def $wh4, implicit-def $p6, implicit-def $dc7, implicit killed $p7, implicit killed $d5, implicit killed $p6, implicit killed $d7 {
    ; CHECK-NEXT:   $wh3, $p7, $dc5 = VLDA_2D_dmw_lda_w killed $p7, killed $d5 :: (load (<8 x s32>), addrspace 14)
    ; CHECK-NEXT:   $wh4, $p6, $dc7 = VLDB_2D_dmw_ldb killed $p6, killed $d7 :: (load (<8 x s32>), addrspace 9)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wh3, $p7, $dc5 = VLD_2D_w_pseudo $p7, $d5 :: (load (<8 x s32>), addrspace 14)
    $wh4, $p6, $dc7 = VLD_2D_w_pseudo $p6, $d7 :: (load (<8 x s32>), addrspace 9)
...

---
name:            VLD_2D_x_pseudo_same_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_2D_x_pseudo_same_bank
    ; CHECK: $x0, $p7, $dc5 = VLDB_2D_dmx_ldb_x killed $p7, killed $d5 :: (load (<16 x s32>), addrspace 9)
    ; CHECK-NEXT: $x1, $p7, $dc7 = VLDB_2D_dmx_ldb_x killed $p6, killed $d7 :: (load (<16 x s32>), addrspace 9)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $x0, $p7, $dc5 = VLD_2D_x_pseudo $p7, $d5 :: (load (<16 x s32>), addrspace 9)
    $x1, $p7, $dc7 = VLD_2D_x_pseudo $p6, $d7 :: (load (<16 x s32>), addrspace 9)
...

---
name:            VLD_2D_x_pseudo_diff_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_2D_x_pseudo_diff_bank
    ; CHECK: BUNDLE implicit-def $x0, implicit-def $wl0, implicit-def $wh0, implicit-def $p7, implicit-def $dc5, implicit-def $x1, implicit-def $wl1, implicit-def $wh1, implicit-def $p6, implicit-def $dc7, implicit killed $p7, implicit killed $d5, implicit killed $p6, implicit killed $d7 {
    ; CHECK-NEXT:   $x0, $p7, $dc5 = VLDA_2D_dmx_lda_x killed $p7, killed $d5 :: (load (<16 x s32>), addrspace 14)
    ; CHECK-NEXT:   $x1, $p6, $dc7 = VLDB_2D_dmx_ldb_x killed $p6, killed $d7 :: (load (<16 x s32>), addrspace 9)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $x0, $p7, $dc5 = VLD_2D_x_pseudo $p7, $d5 :: (load (<16 x s32>), addrspace 14)
    $x1, $p6, $dc7 = VLD_2D_x_pseudo $p6, $d7 :: (load (<16 x s32>), addrspace 9)
...

---
name:            VLD_3D_w_pseudo_same_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_3D_w_pseudo_same_bank
    ; CHECK: $wh4, $p5, $dc2, $dc6 = VLDB_3D_dmw_ldb killed $p5, killed $d2_3d :: (load (<8 x s32>), addrspace 9)
    ; CHECK-NEXT: $wh5, $p6, $dc0, $dc4 = VLDB_3D_dmw_ldb killed $p6, killed $d0_3d :: (load (<8 x s32>), addrspace 9)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wh4, $p5, $dc2, $dc6 = VLD_3D_w_pseudo $p5, $d2_3d :: (load (<8 x s32>), addrspace 9)
    $wh5, $p6, $dc0, $dc4 = VLD_3D_w_pseudo $p6, $d0_3d :: (load (<8 x s32>), addrspace 9)
...

---
name:            VLD_3D_w_pseudo_diff_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_3D_w_pseudo_diff_bank
    ; CHECK: BUNDLE implicit-def $wh4, implicit-def $p5, implicit-def $dc2, implicit-def $dc6, implicit-def $wh5, implicit-def $p6, implicit-def $dc0, implicit-def $dc4, implicit killed $p5, implicit killed $d2_3d, implicit killed $p6, implicit killed $d0_3d {
    ; CHECK-NEXT:   $wh4, $p5, $dc2, $dc6 = VLDA_3D_dmw_lda_w killed $p5, killed $d2_3d :: (load (<8 x s32>), addrspace 14)
    ; CHECK-NEXT:   $wh5, $p6, $dc0, $dc4 = VLDB_3D_dmw_ldb killed $p6, killed $d0_3d :: (load (<8 x s32>), addrspace 9)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wh4, $p5, $dc2, $dc6 = VLD_3D_w_pseudo $p5, $d2_3d :: (load (<8 x s32>), addrspace 14)
    $wh5, $p6, $dc0, $dc4 = VLD_3D_w_pseudo $p6, $d0_3d :: (load (<8 x s32>), addrspace 9)
...

---
name:            VLD_3D_x_pseudo_same_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_3D_x_pseudo_same_bank
    ; CHECK: $x0, $p5, $dc2, $dc6 = VLDB_3D_dmx_ldb_x killed $p5, killed $d2_3d :: (load (<16 x s32>), addrspace 9)
    ; CHECK-NEXT: $x1, $p6, $dc0, $dc4 = VLDB_3D_dmx_ldb_x killed $p6, killed $d0_3d :: (load (<16 x s32>), addrspace 9)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $x0, $p5, $dc2, $dc6 = VLD_3D_x_pseudo $p5, $d2_3d :: (load (<16 x s32>), addrspace 9)
    $x1, $p6, $dc0, $dc4 = VLD_3D_x_pseudo $p6, $d0_3d :: (load (<16 x s32>), addrspace 9)
...

---
name:            VLD_3D_x_pseudo_diff_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_3D_x_pseudo_diff_bank
    ; CHECK: BUNDLE implicit-def $x0, implicit-def $wl0, implicit-def $wh0, implicit-def $p5, implicit-def $dc2, implicit-def $dc6, implicit-def $x1, implicit-def $wl1, implicit-def $wh1, implicit-def $p6, implicit-def $dc0, implicit-def $dc4, implicit killed $p5, implicit killed $d2_3d, implicit killed $p6, implicit killed $d0_3d {
    ; CHECK-NEXT:   $x0, $p5, $dc2, $dc6 = VLDA_3D_dmx_lda_x killed $p5, killed $d2_3d :: (load (<16 x s32>), addrspace 14)
    ; CHECK-NEXT:   $x1, $p6, $dc0, $dc4 = VLDB_3D_dmx_ldb_x killed $p6, killed $d0_3d :: (load (<16 x s32>), addrspace 9)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $x0, $p5, $dc2, $dc6 = VLD_3D_x_pseudo $p5, $d2_3d :: (load (<16 x s32>), addrspace 14)
    $x1, $p6, $dc0, $dc4 = VLD_3D_x_pseudo $p6, $d0_3d :: (load (<16 x s32>), addrspace 9)
...

---
name:            VLD_128_idx_pseudo_same_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_128_idx_pseudo_same_bank
    ; CHECK: $wl10 = VLDB_128_idx killed $p0, killed $dj3 :: (load (s128), addrspace 9)
    ; CHECK-NEXT: $wl7 = VLDB_128_idx killed $p6, killed $dj7 :: (load (s128), addrspace 9)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl10 = VLD_128_idx_pseudo $p0, $dj3 :: (load (s128), addrspace 9)
    $wl7 = VLD_128_idx_pseudo $p6, $dj7 :: (load (s128), addrspace 9)
...

---
name:            VLD_128_idx_pseudo_diff_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_128_idx_pseudo_diff_bank
    ; CHECK: BUNDLE implicit-def $wl10, implicit-def $wl7, implicit killed $p0, implicit killed $dj3, implicit killed $p6, implicit killed $dj7 {
    ; CHECK-NEXT:   $wl10 = VLDA_128_dmv_lda_w_idx killed $p0, killed $dj3 :: (load (s128), addrspace 14)
    ; CHECK-NEXT:   $wl7 = VLDB_128_idx killed $p6, killed $dj7 :: (load (s128), addrspace 9)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl10 = VLD_128_idx_pseudo $p0, $dj3 :: (load (s128), addrspace 14)
    $wl7 = VLD_128_idx_pseudo $p6, $dj7 :: (load (s128), addrspace 9)
...

---
name:            VLD_128_idx_imm_pseudo_same_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_128_idx_imm_pseudo_same_bank
    ; CHECK: $wl10 = VLDB_128_idx_imm killed $p0, 0 :: (load (s128), addrspace 9)
    ; CHECK-NEXT: $wl7 = VLDB_128_idx_imm killed $p6, 128 :: (load (s128), addrspace 9)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl10 = VLD_128_idx_imm_pseudo $p0, 0 :: (load (s128), addrspace 9)
    $wl7 = VLD_128_idx_imm_pseudo $p6, 128 :: (load (s128), addrspace 9)
...

---
name:            VLD_128_idx_imm_pseudo_diff_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_128_idx_imm_pseudo_diff_bank
    ; CHECK: BUNDLE implicit-def $wl10, implicit-def $wl7, implicit killed $p0, implicit killed $p6 {
    ; CHECK-NEXT:   $wl10 = VLDA_128_dmv_lda_w_idx_imm killed $p0, 0 :: (load (s128), addrspace 14)
    ; CHECK-NEXT:   $wl7 = VLDB_128_idx_imm killed $p6, 128 :: (load (s128), addrspace 9)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl10 = VLD_128_idx_imm_pseudo $p0, 0 :: (load (s128), addrspace 14)
    $wl7 = VLD_128_idx_imm_pseudo $p6, 128 :: (load (s128), addrspace 9)
...

---
name:            VLD_128_pstm_nrm_pseudo_same_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_128_pstm_nrm_pseudo_same_bank
    ; CHECK: $wh0, $p6 = VLDB_128_pstm_nrm killed $p6, killed $m7 :: (load (s128), addrspace 9)
    ; CHECK-NEXT: $wl6, $p3 = VLDB_128_pstm_nrm killed $p3, killed $m2 :: (load (s128), addrspace 9)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wh0, $p6 = VLD_128_pstm_nrm_pseudo $p6, $m7 :: (load (s128), addrspace 9)
    $wl6, $p3 = VLD_128_pstm_nrm_pseudo $p3, $m2 :: (load (s128), addrspace 9)
...

---
name:            VLD_128_pstm_nrm_pseudo_diff_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_128_pstm_nrm_pseudo_diff_bank
    ; CHECK: BUNDLE implicit-def $wh0, implicit-def $p6, implicit-def $wl6, implicit-def $p3, implicit killed $p6, implicit killed $m7, implicit killed $p3, implicit killed $m2 {
    ; CHECK-NEXT:   $wh0, $p6 = VLDA_128_dmv_lda_w_pstm_nrm killed $p6, killed $m7 :: (load (s128), addrspace 14)
    ; CHECK-NEXT:   $wl6, $p3 = VLDB_128_pstm_nrm killed $p3, killed $m2 :: (load (s128), addrspace 9)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wh0, $p6 = VLD_128_pstm_nrm_pseudo $p6, $m7 :: (load (s128), addrspace 14)
    $wl6, $p3 = VLD_128_pstm_nrm_pseudo $p3, $m2 :: (load (s128), addrspace 9)
...

---
name:            VLD_128_pstm_nrm_imm_pseudo_same_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_128_pstm_nrm_imm_pseudo_same_bank
    ; CHECK: $wh0, $p6 = VLDB_128_pstm_nrm_imm killed $p6, 0 :: (load (s128), addrspace 9)
    ; CHECK-NEXT: $wl6, $p3 = VLDB_128_pstm_nrm_imm killed $p3, 128 :: (load (s128), addrspace 9)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wh0, $p6 = VLD_128_pstm_nrm_imm_pseudo $p6, 0 :: (load (s128), addrspace 9)
    $wl6, $p3 = VLD_128_pstm_nrm_imm_pseudo $p3, 128 :: (load (s128), addrspace 9)
...

---
name:            VLD_128_pstm_nrm_imm_pseudo_diff_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_128_pstm_nrm_imm_pseudo_diff_bank
    ; CHECK: BUNDLE implicit-def $wh0, implicit-def $p6, implicit-def $wl6, implicit-def $p3, implicit killed $p6, implicit killed $p3 {
    ; CHECK-NEXT:   $wh0, $p6 = VLDA_128_dmv_lda_w_pstm_nrm_imm killed $p6, 0 :: (load (s128), addrspace 14)
    ; CHECK-NEXT:   $wl6, $p3 = VLDB_128_pstm_nrm_imm killed $p3, 128 :: (load (s128), addrspace 9)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wh0, $p6 = VLD_128_pstm_nrm_imm_pseudo $p6, 0 :: (load (s128), addrspace 14)
    $wl6, $p3 = VLD_128_pstm_nrm_imm_pseudo $p3, 128 :: (load (s128), addrspace 9)
...

---
name:            VLD_2D_128_pseudo_same_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_2D_128_pseudo_same_bank
    ; CHECK: $wl3, $p2, $dc4 = VLDB_2D_128 killed $p2, killed $d4 :: (load (s128), addrspace 9)
    ; CHECK-NEXT: $wl7, $p3, $dc3 = VLDB_2D_128 killed $p3, killed $d3 :: (load (s128), addrspace 9)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl3, $p2, $dc4 = VLD_2D_128_pseudo $p2, $d4 :: (load (s128), addrspace 9)
    $wl7, $p3, $dc3 = VLD_2D_128_pseudo $p3, $d3 :: (load (s128), addrspace 9)
...

---
name:            VLD_2D_128_pseudo_diff_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_2D_128_pseudo_diff_bank
    ; CHECK: BUNDLE implicit-def $wl3, implicit-def $p2, implicit-def $dc4, implicit-def $wl7, implicit-def $p3, implicit-def $dc3, implicit killed $p2, implicit killed $d4, implicit killed $p3, implicit killed $d3 {
    ; CHECK-NEXT:   $wl3, $p2, $dc4 = VLDA_2D_128 killed $p2, killed $d4 :: (load (s128), addrspace 14)
    ; CHECK-NEXT:   $wl7, $p3, $dc3 = VLDB_2D_128 killed $p3, killed $d3 :: (load (s128), addrspace 9)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl3, $p2, $dc4 = VLD_2D_128_pseudo $p2, $d4 :: (load (s128), addrspace 14)
    $wl7, $p3, $dc3 = VLD_2D_128_pseudo $p3, $d3 :: (load (s128), addrspace 9)
...

---
name:            VLD_3D_128_pseudo_same_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_3D_128_pseudo_same_bank
    ; CHECK: $wl0, $p0, $dc0, $dc4 = VLDB_3D_128 killed $p0, killed $d0_3d :: (load (s128), addrspace 9)
    ; CHECK-NEXT: $wl2, $p2, $dc1, $dc5 = VLDB_3D_128 killed $p2, killed $d1_3d :: (load (s128), addrspace 9)
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl0, $p0, $dc0, $dc4 = VLD_3D_128_pseudo $p0, $d0_3d :: (load (s128), addrspace 9)
    $wl2, $p2, $dc1, $dc5 = VLD_3D_128_pseudo $p2, $d1_3d :: (load (s128), addrspace 9)
...

---
name:            VLD_3D_128_pseudo_diff_bank
alignment:       16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: VLD_3D_128_pseudo_diff_bank
    ; CHECK: BUNDLE implicit-def $wl0, implicit-def $p0, implicit-def $dc0, implicit-def $dc4, implicit-def $wl2, implicit-def $p2, implicit-def $dc1, implicit-def $dc5, implicit killed $p0, implicit killed $d0_3d, implicit killed $p2, implicit killed $d1_3d {
    ; CHECK-NEXT:   $wl0, $p0, $dc0, $dc4 = VLDA_3D_128 killed $p0, killed $d0_3d :: (load (s128), addrspace 14)
    ; CHECK-NEXT:   $wl2, $p2, $dc1, $dc5 = VLDB_3D_128 killed $p2, killed $d1_3d :: (load (s128), addrspace 9)
    ; CHECK-NEXT: }
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    ; CHECK-NEXT: NOP
    $wl0, $p0, $dc0, $dc4 = VLD_3D_128_pseudo $p0, $d0_3d :: (load (s128), addrspace 14)
    $wl2, $p2, $dc1, $dc5 = VLD_3D_128_pseudo $p2, $d1_3d :: (load (s128), addrspace 9)
...
