# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
# RUN: llc -march=aie2p -run-pass=postmisched %s -o - | FileCheck %s

# This test checks that VLDB_POPX_512 and VLDB_FILLX_512 are not using resources
# related to the mov slot, allowing packing them with shuffles and having no port conflicts
# ahead.

---
name:            VLDB_POPX_512_SHUFFLE
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p1, $lfe, $lf1, $r21, $r25, $r30, $x3, $x9
    ; CHECK-LABEL: name: VLDB_POPX_512_SHUFFLE
    ; CHECK: liveins: $p1, $lfe, $lf1, $r21, $r25, $r30, $x3, $x9
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: BUNDLE implicit-def $x3, implicit-def $wl3, implicit-def $wh3, implicit-def $p1, implicit-def $lf1, implicit-def $lfl1, implicit-def $lfh1, implicit-def $r25, implicit-def $lfe, implicit-def $srfifo_uf, implicit-def $x8, implicit-def $wl8, implicit-def $wh8, implicit killed $r30, implicit killed $p1, implicit killed $lf1, implicit killed $r25, implicit killed $lfe, implicit $x9, implicit $r21 {
    ; CHECK-NEXT:   $x3, $p1, $lf1, $r25 = VLDB_POPX_512 killed $r30, $r30, killed $p1, killed $lf1, killed $r25, implicit-def $lfe, implicit-def $srfifo_uf, implicit killed $lfe
    ; CHECK-NEXT:   renamable $x8 = VSHUFFLE_vec_shuffle_x renamable $x9, renamable $x9, renamable $r21
    ; CHECK-NEXT: }
    ; CHECK-NEXT: renamable $x8 = VSHUFFLE_vec_shuffle_x renamable $x9, renamable $x9, renamable $r21
    ; CHECK-NEXT: renamable $x8 = VSHUFFLE_vec_shuffle_x renamable $x9, renamable $x9, renamable $r21
    ; CHECK-NEXT: renamable $x8 = VSHUFFLE_vec_shuffle_x renamable $x9, renamable $x9, renamable $r21
    ; CHECK-NEXT: renamable $x8 = VSHUFFLE_vec_shuffle_x renamable $x9, renamable $x9, renamable $r21
    ; CHECK-NEXT: renamable $x8 = VSHUFFLE_vec_shuffle_x renamable $x9, renamable $x9, renamable $r21
    ; CHECK-NEXT: renamable $x8 = VSHUFFLE_vec_shuffle_x killed renamable $x9, renamable $x9, killed renamable $r21
    ; CHECK-NEXT: NOP
    $x3, $p1, $lf1, $r25 = VLDB_POPX_512 $r30, $r30, $p1, $lf1, $r25, implicit-def $lfe, implicit-def $srfifo_uf, implicit $lfe
    renamable $x8 = VSHUFFLE_vec_shuffle_x renamable $x9, renamable $x9, renamable $r21
    renamable $x8 = VSHUFFLE_vec_shuffle_x renamable $x9, renamable $x9, renamable $r21
    renamable $x8 = VSHUFFLE_vec_shuffle_x renamable $x9, renamable $x9, renamable $r21
    renamable $x8 = VSHUFFLE_vec_shuffle_x renamable $x9, renamable $x9, renamable $r21
    renamable $x8 = VSHUFFLE_vec_shuffle_x renamable $x9, renamable $x9, renamable $r21
    renamable $x8 = VSHUFFLE_vec_shuffle_x renamable $x9, renamable $x9, renamable $r21
    renamable $x8 = VSHUFFLE_vec_shuffle_x killed renamable $x9, renamable $x9, renamable $r21
...

---
name:            VLDB_FILLX_512_SHUFFLE
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $p1, $lfe, $lf1, $r21, $r25, $r30, $x3, $x9
    ; CHECK-LABEL: name: VLDB_FILLX_512_SHUFFLE
    ; CHECK: liveins: $p1, $lfe, $lf1, $r21, $r25, $r30, $x3, $x9
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $x8 = VSHUFFLE_vec_shuffle_x renamable $x9, renamable $x9, renamable $r21
    ; CHECK-NEXT: BUNDLE implicit-def $p1, implicit-def $lf1, implicit-def $lfl1, implicit-def $lfh1, implicit-def $r25, implicit-def $lfe, implicit-def $x8, implicit-def $wl8, implicit-def $wh8, implicit killed $r30, implicit killed $p1, implicit killed $lf1, implicit killed $r25, implicit killed $lfe, implicit $x9, implicit $r21 {
    ; CHECK-NEXT:   $p1, $lf1, $r25 = VLDB_FILLX_512 killed $r30, $r30, killed $p1, killed $lf1, killed $r25, implicit-def $lfe, implicit killed $lfe
    ; CHECK-NEXT:   renamable $x8 = VSHUFFLE_vec_shuffle_x renamable $x9, renamable $x9, renamable $r21
    ; CHECK-NEXT: }
    ; CHECK-NEXT: renamable $x8 = VSHUFFLE_vec_shuffle_x renamable $x9, renamable $x9, renamable $r21
    ; CHECK-NEXT: renamable $x8 = VSHUFFLE_vec_shuffle_x renamable $x9, renamable $x9, renamable $r21
    ; CHECK-NEXT: renamable $x8 = VSHUFFLE_vec_shuffle_x renamable $x9, renamable $x9, renamable $r21
    ; CHECK-NEXT: renamable $x8 = VSHUFFLE_vec_shuffle_x renamable $x9, renamable $x9, renamable $r21
    ; CHECK-NEXT: renamable $x8 = VSHUFFLE_vec_shuffle_x killed renamable $x9, renamable $x9, killed renamable $r21
    ; CHECK-NEXT: NOP
    $p1, $lf1, $r25 = VLDB_FILLX_512 $r30, $r30,  $p1, $lf1, $r25, implicit-def $lfe, implicit $lfe
    renamable $x8 = VSHUFFLE_vec_shuffle_x renamable $x9, renamable $x9, renamable $r21
    renamable $x8 = VSHUFFLE_vec_shuffle_x renamable $x9, renamable $x9, renamable $r21
    renamable $x8 = VSHUFFLE_vec_shuffle_x renamable $x9, renamable $x9, renamable $r21
    renamable $x8 = VSHUFFLE_vec_shuffle_x renamable $x9, renamable $x9, renamable $r21
    renamable $x8 = VSHUFFLE_vec_shuffle_x renamable $x9, renamable $x9, renamable $r21
    renamable $x8 = VSHUFFLE_vec_shuffle_x renamable $x9, renamable $x9, renamable $r21
    renamable $x8 = VSHUFFLE_vec_shuffle_x killed renamable $x9, renamable $x9, renamable $r21
...
