; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2024-2025 Advanced Micro Devices, Inc. or its affiliates

; RUN: llc -O2 -mtriple=aie2 -stop-after=irtranslator --enable-aie-hardware-loops --enable-aie-zero-overhead-loops \
; RUN:    --aie-force-hl-gen=true %s -o - | FileCheck %s --check-prefix=AIE2
; RUN: llc -O2 -mtriple=aie2p -stop-after=irtranslator --enable-aie-hardware-loops --enable-aie-zero-overhead-loops \
; RUN:    --aie-force-hl-gen=true %s -o - | FileCheck %s --check-prefix=AIE2p

; This test feeds a normal counted loop in LLVM IR. We check that it is
; recognised as a hardware loop by the llvm shapers and then correctly
; translated to calls to the set up and loop end intrinsics in G_MIR

define void @simple(ptr nocapture %out, ptr nocapture readonly %in, i32 noundef %size) {
  ; AIE2-LABEL: name: simple
  ; AIE2: bb.1.for.body.lr.ph:
  ; AIE2-NEXT:   successors: %bb.3(0x80000000)
  ; AIE2-NEXT:   liveins: $p0, $p1, $r0
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; AIE2-NEXT:   [[COPY1:%[0-9]+]]:_(p0) = COPY $p1
  ; AIE2-NEXT:   [[COPY2:%[0-9]+]]:_(s32) = COPY $r0
  ; AIE2-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; AIE2-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; AIE2-NEXT:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s32) from %ir.out)
  ; AIE2-NEXT:   G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.set.loop.iterations), [[COPY2]](s32)
  ; AIE2-NEXT:   G_BR %bb.3
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT: bb.2.for.cond.cleanup:
  ; AIE2-NEXT:   PseudoRET implicit $lr
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT: bb.3.for.body:
  ; AIE2-NEXT:   successors: %bb.3(0x7c000000), %bb.2(0x04000000)
  ; AIE2-NEXT: {{  $}}
  ; AIE2-NEXT:   [[PHI:%[0-9]+]]:_(s32) = G_PHI [[LOAD]](s32), %bb.1, %12(s32), %bb.3
  ; AIE2-NEXT:   [[PHI1:%[0-9]+]]:_(s32) = G_PHI [[C1]](s32), %bb.1, %14(s32), %bb.3
  ; AIE2-NEXT:   [[TRUNC:%[0-9]+]]:_(s20) = G_TRUNC [[PHI1]](s32)
  ; AIE2-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
  ; AIE2-NEXT:   [[MUL:%[0-9]+]]:_(s20) = G_MUL [[TRUNC]], [[C2]]
  ; AIE2-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY1]], [[MUL]](s20)
  ; AIE2-NEXT:   [[COPY3:%[0-9]+]]:_(p0) = COPY [[PTR_ADD]](p0)
  ; AIE2-NEXT:   [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[COPY3]](p0) :: (load (s32) from %ir.arrayidx)
  ; AIE2-NEXT:   [[ADD:%[0-9]+]]:_(s32) = nsw G_ADD [[PHI]], [[LOAD1]]
  ; AIE2-NEXT:   G_STORE [[ADD]](s32), [[COPY]](p0) :: (store (s32) into %ir.out)
  ; AIE2-NEXT:   [[ADD1:%[0-9]+]]:_(s32) = nuw nsw G_ADD [[PHI1]], [[C]]
  ; AIE2-NEXT:   [[INT:%[0-9]+]]:_(s1) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.loop.decrement), [[C]](s32)
  ; AIE2-NEXT:   G_BRCOND [[INT]](s1), %bb.3
  ; AIE2-NEXT:   G_BR %bb.2
  ;
  ; AIE2p-LABEL: name: simple
  ; AIE2p: bb.1.for.body.lr.ph:
  ; AIE2p-NEXT:   successors: %bb.3(0x80000000)
  ; AIE2p-NEXT:   liveins: $p0, $p1, $r0
  ; AIE2p-NEXT: {{  $}}
  ; AIE2p-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $p0
  ; AIE2p-NEXT:   [[COPY1:%[0-9]+]]:_(p0) = COPY $p1
  ; AIE2p-NEXT:   [[COPY2:%[0-9]+]]:_(s32) = COPY $r0
  ; AIE2p-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; AIE2p-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; AIE2p-NEXT:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s32) from %ir.out)
  ; AIE2p-NEXT:   G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.set.loop.iterations), [[COPY2]](s32)
  ; AIE2p-NEXT:   G_BR %bb.3
  ; AIE2p-NEXT: {{  $}}
  ; AIE2p-NEXT: bb.2.for.cond.cleanup:
  ; AIE2p-NEXT:   PseudoRET implicit $lr
  ; AIE2p-NEXT: {{  $}}
  ; AIE2p-NEXT: bb.3.for.body:
  ; AIE2p-NEXT:   successors: %bb.3(0x7c000000), %bb.2(0x04000000)
  ; AIE2p-NEXT: {{  $}}
  ; AIE2p-NEXT:   [[PHI:%[0-9]+]]:_(s32) = G_PHI [[LOAD]](s32), %bb.1, %12(s32), %bb.3
  ; AIE2p-NEXT:   [[PHI1:%[0-9]+]]:_(s32) = G_PHI [[C1]](s32), %bb.1, %14(s32), %bb.3
  ; AIE2p-NEXT:   [[TRUNC:%[0-9]+]]:_(s20) = G_TRUNC [[PHI1]](s32)
  ; AIE2p-NEXT:   [[C2:%[0-9]+]]:_(s20) = G_CONSTANT i20 4
  ; AIE2p-NEXT:   [[MUL:%[0-9]+]]:_(s20) = G_MUL [[TRUNC]], [[C2]]
  ; AIE2p-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY1]], [[MUL]](s20)
  ; AIE2p-NEXT:   [[COPY3:%[0-9]+]]:_(p0) = COPY [[PTR_ADD]](p0)
  ; AIE2p-NEXT:   [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[COPY3]](p0) :: (load (s32) from %ir.arrayidx)
  ; AIE2p-NEXT:   [[ADD:%[0-9]+]]:_(s32) = nsw G_ADD [[PHI]], [[LOAD1]]
  ; AIE2p-NEXT:   G_STORE [[ADD]](s32), [[COPY]](p0) :: (store (s32) into %ir.out)
  ; AIE2p-NEXT:   [[ADD1:%[0-9]+]]:_(s32) = nuw nsw G_ADD [[PHI1]], [[C]]
  ; AIE2p-NEXT:   [[INT:%[0-9]+]]:_(s1) = G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.loop.decrement), [[C]](s32)
  ; AIE2p-NEXT:   G_BRCOND [[INT]](s1), %bb.3
  ; AIE2p-NEXT:   G_BR %bb.2
for.body.lr.ph:
  %out.promoted = load i32, ptr %out, align 4
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %for.body.lr.ph, %for.body
  %add7 = phi i32 [ %out.promoted, %for.body.lr.ph ], [ %add, %for.body ]
  %i.06 = phi i32 [ 0, %for.body.lr.ph ], [ %inc, %for.body ]
  %0 = trunc i32 %i.06 to i20
  %arrayidx = getelementptr inbounds i32, ptr %in, i20 %0
  %1 = load i32, ptr %arrayidx, align 4
  %add = add nsw i32 %add7, %1
  store i32 %add, ptr %out, align 4
  %inc = add nuw nsw i32 %i.06, 1
  %exitcond.not = icmp eq i32 %inc, %size
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}
