; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2024-2026 Advanced Micro Devices, Inc. or its affiliates

; RUN: llc -O2 -mtriple=aie2 --enable-aie-hardware-loops \
; RUN:   --enable-aie-zero-overhead-loops %s -o - | FileCheck %s  --check-prefix=AIE2
; RUN: llc -O2 -mtriple=aie2p --enable-aie-hardware-loops \
; RUN:   --enable-aie-zero-overhead-loops %s -o - | FileCheck %s  --check-prefix=AIE2P
%struct.Symbol = type { [50 x i8], i32 }

@test_buf0 = dso_local local_unnamed_addr global [3 x i32] [i32 1, i32 2, i32 3], align 4
@test_buf1 = dso_local local_unnamed_addr global [3 x [3 x i32]] [[3 x i32] [i32 1, i32 2, i32 3], [3 x i32] [i32 4, i32 5, i32 6], [3 x i32] [i32 7, i32 8, i32 9]], align 4
@symbolCount = dso_local local_unnamed_addr global i32 0, align 4
@symbolTable = dso_local global [1000 x %struct.Symbol] zeroinitializer, align 4
@.str = private unnamed_addr constant [5 x i8] c"IntV\00", align 1
@.str.1 = private unnamed_addr constant [7 x i8] c"FloatV\00", align 1

define dso_local void @_Z16addToSymbolTablePKci(ptr nocapture readonly %name, i32 noundef %dataType) {
; AIE2-LABEL: _Z16addToSymbolTablePKci:
; AIE2:       // %bb.0: // %entry
; AIE2-NEXT:    paddb [sp], #32
; AIE2-NEXT:    st p7, [sp, #-16]; movxm p7, #symbolCount // 4-byte Folded Spill
; AIE2-NEXT:    lda r17, [p7, #0]
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    st r17, [sp, #-24]; movx r1, #56 // 4-byte Folded Spill
; AIE2-NEXT:    mul r1, r17, r1; mov p2, p0
; AIE2-NEXT:    jl #strcpy
; AIE2-NEXT:    st p6, [sp, #-20] // 4-byte Folded Spill Delay Slot 5
; AIE2-NEXT:    mov m0, r1 // Delay Slot 4
; AIE2-NEXT:    st lr, [sp, #-32]; movxm p6, #symbolTable // 4-byte Folded Spill Delay Slot 3
; AIE2-NEXT:    paddb [p6], m0; st r16, [sp, #-28] // 4-byte Folded Spill Delay Slot 2
; AIE2-NEXT:    or r16, r0, r0; mov p1, p6 // Delay Slot 1
; AIE2-NEXT:    lda lr, [sp, #-32]; nopx // 4-byte Folded Reload
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    lda p6, [sp, #-20] // 4-byte Folded Reload
; AIE2-NEXT:    lda r17, [sp, #-24] // 4-byte Folded Reload
; AIE2-NEXT:    lda r16, [sp, #-28] // 4-byte Folded Reload
; AIE2-NEXT:    lda p7, [sp, #-16] // 4-byte Folded Reload
; AIE2-NEXT:    ret lr
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    st r16, [p6, #52] // Delay Slot 4
; AIE2-NEXT:    add r0, r17, #1 // Delay Slot 3
; AIE2-NEXT:    paddb [sp], #-32; st r0, [p7, #0] // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: _Z16addToSymbolTablePKci:
; AIE2P:       // %bb.0: // %entry
; AIE2P-NEXT:    paddxm [sp], #64
; AIE2P-NEXT:    st p7, [sp, #-48]; movxm p7, ##symbolCount // 4-byte Folded Spill
; AIE2P-NEXT:    lda r9, [p7, #0]
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    mova r1, #56
; AIE2P-NEXT:    st r9, [sp, #-56]; jl #strcpy // 4-byte Folded Spill
; AIE2P-NEXT:    mul r1, r9, r1 // Delay Slot 5
; AIE2P-NEXT:    st p6, [sp, #-52]; movxm p6, ##symbolTable // 4-byte Folded Spill Delay Slot 4
; AIE2P-NEXT:    st lr, [sp, #-64]; mov m0, r1 // 4-byte Folded Spill Delay Slot 3
; AIE2P-NEXT:    padda [p6], m0; st r8, [sp, #-60] // 4-byte Folded Spill Delay Slot 2
; AIE2P-NEXT:    movs p2, p0; or r8, r0, r0; mov p1, p6 // Delay Slot 1
; AIE2P-NEXT:    lda lr, [sp, #-64]; nopb ; nops ; nopxm ; nopv // 4-byte Folded Reload
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    lda r9, [sp, #-56] // 4-byte Folded Reload
; AIE2P-NEXT:    lda p7, [sp, #-48] // 4-byte Folded Reload
; AIE2P-NEXT:    lda p6, [sp, #-52] // 4-byte Folded Reload
; AIE2P-NEXT:    lda r8, [sp, #-60] // 4-byte Folded Reload
; AIE2P-NEXT:    ret lr
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    add r0, r9, #1 // Delay Slot 4
; AIE2P-NEXT:    mova dj0, #52; st r0, [p7, #0] // Delay Slot 3
; AIE2P-NEXT:    st r8, [p6, dj0]; paddxm [sp], #-64 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
entry:
  %0 = load i32, ptr @symbolCount, align 4
  %1 = trunc i32 %0 to i20
  %arrayidx = getelementptr inbounds [1000 x %struct.Symbol], ptr @symbolTable, i20 0, i20 %1
  %call = tail call ptr @strcpy(ptr noundef nonnull dereferenceable(1) %arrayidx, ptr noundef nonnull dereferenceable(1) %name)
  %dataType3 = getelementptr inbounds [1000 x %struct.Symbol], ptr @symbolTable, i20 0, i20 %1, i32 1
  store i32 %dataType, ptr %dataType3, align 4
  %inc = add nsw i32 %0, 1
  store i32 %inc, ptr @symbolCount, align 4
  ret void
}

declare dso_local ptr @strcpy(ptr noalias returned writeonly, ptr noalias nocapture readonly)

define dso_local void @_Z5test4i(i32 noundef %n) {
; CHECK-LABEL: _Z5test4i:
; CHECK:         .p2align 4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    nopa ; paddb [sp], #32; nopxm
; CHECK-NEXT:    mova r1, #0; st r16, [sp, #-24] // 4-byte Folded Spill
; CHECK-NEXT:    ge r0, r1, r0; mov r16, r0
; CHECK-NEXT:    jnz r0, #.LBB1_3
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    st lr, [sp, #-20] // 4-byte Folded Spill Delay Slot 3
; CHECK-NEXT:    st p6, [sp, #-28] // 4-byte Folded Spill Delay Slot 2
; CHECK-NEXT:    st p7, [sp, #-32] // 4-byte Folded Spill Delay Slot 1
; CHECK-NEXT:  // %bb.1:
; CHECK-NEXT:    nopa ; movxm p6, #.L.str
; CHECK-NEXT:    movxm p7, #.L.str.1
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB1_2: // %for.body
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    nopb ; nopa ; nops ; jl #_Z16addToSymbolTablePKci; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    mova r0, #0; mov p0, p6 // Delay Slot 1
; CHECK-NEXT:    nopb ; nopa ; nops ; jl #_Z16addToSymbolTablePKci; nopv
; CHECK-NEXT:    nopx // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    mova r0, #1; mov p0, p7 // Delay Slot 1
; CHECK-NEXT:    nopb ; nopa ; nops ; add r16, r16, #-1; nopm ; nopv
; CHECK-NEXT:    jnz r16, #.LBB1_2
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    nop // Delay Slot 1
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB1_3: // %for.cond.cleanup
; CHECK-NEXT:    lda lr, [sp, #-20]; nopb ; nopxm ; nops // 4-byte Folded Reload
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    lda p7, [sp, #-32] // 4-byte Folded Reload
; CHECK-NEXT:    lda p6, [sp, #-28] // 4-byte Folded Reload
; CHECK-NEXT:    lda r16, [sp, #-24] // 4-byte Folded Reload
; CHECK-NEXT:    ret lr
; CHECK-NEXT:    nop // Delay Slot 5
; CHECK-NEXT:    nop // Delay Slot 4
; CHECK-NEXT:    nop // Delay Slot 3
; CHECK-NEXT:    nop // Delay Slot 2
; CHECK-NEXT:    paddb [sp], #-32 // Delay Slot 1
; AIE2-LABEL: _Z5test4i:
; AIE2:       // %bb.0: // %entry
; AIE2-NEXT:    paddb [sp], #32; nopa ; nops ; nopxm ; nopv
; AIE2-NEXT:    mova r1, #0; st r16, [sp, #-28] // 4-byte Folded Spill
; AIE2-NEXT:    ge r0, r1, r0; mov r16, r0
; AIE2-NEXT:    jnz r0, #.LBB1_3
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    st lr, [sp, #-32] // 4-byte Folded Spill Delay Slot 3
; AIE2-NEXT:    st p6, [sp, #-24] // 4-byte Folded Spill Delay Slot 2
; AIE2-NEXT:    st p7, [sp, #-20] // 4-byte Folded Spill Delay Slot 1
; AIE2-NEXT:  // %bb.1:
; AIE2-NEXT:    movxm p6, #.L.str
; AIE2-NEXT:    movxm p7, #.L.str.1
; AIE2-NEXT:  .LBB1_2: // %for.body
; AIE2-NEXT:    // =>This Inner Loop Header: Depth=1
; AIE2-NEXT:    nopb ; nopa ; nops ; jl #_Z16addToSymbolTablePKci; nopv
; AIE2-NEXT:    nopx // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    nop // Delay Slot 2
; AIE2-NEXT:    mova r0, #0; mov p0, p6 // Delay Slot 1
; AIE2-NEXT:    nopb ; nopa ; nops ; jl #_Z16addToSymbolTablePKci; nopv
; AIE2-NEXT:    nopx // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    nop // Delay Slot 2
; AIE2-NEXT:    mova r0, #1; mov p0, p7 // Delay Slot 1
; AIE2-NEXT:    nopb ; nopa ; nops ; add r16, r16, #-1; nopm ; nopv
; AIE2-NEXT:    jnz r16, #.LBB1_2
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    nop // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
; AIE2-NEXT:  .LBB1_3: // %for.cond.cleanup
; AIE2-NEXT:    lda lr, [sp, #-32]; nopb ; nopxm ; nops // 4-byte Folded Reload
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    lda p7, [sp, #-20] // 4-byte Folded Reload
; AIE2-NEXT:    lda p6, [sp, #-24] // 4-byte Folded Reload
; AIE2-NEXT:    lda r16, [sp, #-28] // 4-byte Folded Reload
; AIE2-NEXT:    ret lr
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    paddb [sp], #-32 // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: _Z5test4i:
; AIE2P:       // %bb.0: // %entry
; AIE2P-NEXT:    mova r1, #0; nopb ; nops ; paddxm [sp], #64; nopv
; AIE2P-NEXT:    nopa ; nopb ; ge r0, r1, r0; mov r8, r0; st r8, [sp, #-60] // 4-byte Folded Spill
; AIE2P-NEXT:    jnz r0, #.LBB1_2
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    st lr, [sp, #-64] // 4-byte Folded Spill Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
; AIE2P-NEXT:  .LBB1_1: // %for.body
; AIE2P-NEXT:    // =>This Inner Loop Header: Depth=1
; AIE2P-NEXT:    nopa ; nopb ; jl #_Z16addToSymbolTablePKci; nops
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    nop // Delay Slot 2
; AIE2P-NEXT:    mova r0, #0; movxm p0, ##.L.str // Delay Slot 1
; AIE2P-NEXT:    nopa ; nopb ; jl #_Z16addToSymbolTablePKci; nops
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    nop // Delay Slot 2
; AIE2P-NEXT:    mova r0, #1; movxm p0, ##.L.str.1 // Delay Slot 1
; AIE2P-NEXT:    nopa ; nopb ; nops ; add r8, r8, #-1; nopm ; nopv
; AIE2P-NEXT:    jnz r8, #.LBB1_1
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    nop // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
; AIE2P-NEXT:  .LBB1_2: // %for.cond.cleanup
; AIE2P-NEXT:    lda lr, [sp, #-64]; nopb ; nops ; nopxm ; nopv // 4-byte Folded Reload
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    lda r8, [sp, #-60] // 4-byte Folded Reload
; AIE2P-NEXT:    ret lr
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    paddxm [sp], #-64 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
entry:
  %cmp2 = icmp sgt i32 %n, 0
  br i1 %cmp2, label %for.body, label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %for.body, %entry
  ret void

for.body:                                         ; preds = %entry, %for.body
  %i.03 = phi i32 [ %inc, %for.body ], [ 0, %entry ]
  tail call void @_Z16addToSymbolTablePKci(ptr nonnull @.str, i32 noundef 0)
  tail call void @_Z16addToSymbolTablePKci(ptr nonnull @.str.1, i32 noundef 1)
  %inc = add nuw nsw i32 %i.03, 1
  %exitcond.not = icmp eq i32 %inc, %n
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

define dso_local void @memcpy_lowered_to_call(ptr nocapture writeonly %a, ptr nocapture readonly %b, i32 noundef %n) {
; AIE2-LABEL: memcpy_lowered_to_call:
; AIE2:       // %bb.0: // %entry
; AIE2-NEXT:    nopa ; paddb [sp], #32; nopxm
; AIE2-NEXT:    mova r1, #0; st r16, [sp, #-28] // 4-byte Folded Spill
; AIE2-NEXT:    ge r0, r1, r0; mov r16, r0
; AIE2-NEXT:    jnz r0, #.LBB2_3
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    st lr, [sp, #-32] // 4-byte Folded Spill Delay Slot 4
; AIE2-NEXT:    st r17, [sp, #-24] // 4-byte Folded Spill Delay Slot 3
; AIE2-NEXT:    st p6, [sp, #-20] // 4-byte Folded Spill Delay Slot 2
; AIE2-NEXT:    st p7, [sp, #-16] // 4-byte Folded Spill Delay Slot 1
; AIE2-NEXT:  // %bb.1:
; AIE2-NEXT:    mov p6, p0
; AIE2-NEXT:    mov p7, p1
; AIE2-NEXT:    movxm r17, #4096
; AIE2-NEXT:  .LBB2_2: // %for.body
; AIE2-NEXT:    // =>This Inner Loop Header: Depth=1
; AIE2-NEXT:    nopb ; nopa ; nops ; jl #memcpy; nopv
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    mov p1, p6 // Delay Slot 3
; AIE2-NEXT:    mov p2, p7 // Delay Slot 2
; AIE2-NEXT:    mov r0, r17 // Delay Slot 1
; AIE2-NEXT:    nopb ; nopa ; nops ; add r16, r16, #-1; nopm ; nopv
; AIE2-NEXT:    jnz r16, #.LBB2_2
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    nop // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
; AIE2-NEXT:  .LBB2_3: // %for.cond.cleanup
; AIE2-NEXT:    lda lr, [sp, #-32]; nopb ; nopxm // 4-byte Folded Reload
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    lda p7, [sp, #-16] // 4-byte Folded Reload
; AIE2-NEXT:    lda p6, [sp, #-20] // 4-byte Folded Reload
; AIE2-NEXT:    lda r17, [sp, #-24] // 4-byte Folded Reload
; AIE2-NEXT:    lda r16, [sp, #-28] // 4-byte Folded Reload
; AIE2-NEXT:    ret lr
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    paddb [sp], #-32 // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: memcpy_lowered_to_call:
; AIE2P:       // %bb.0: // %entry
; AIE2P-NEXT:    mova r1, #0; nopb ; nops ; paddxm [sp], #64; nopv
; AIE2P-NEXT:    nopa ; nopb ; st r8, [sp, #-60]; ge r0, r1, r0; mov r8, r0; nopv // 4-byte Folded Spill
; AIE2P-NEXT:    jnz r0, #.LBB2_3
; AIE2P-NEXT:    nopx // Delay Slot 5
; AIE2P-NEXT:    st lr, [sp, #-64] // 4-byte Folded Spill Delay Slot 4
; AIE2P-NEXT:    st p6, [sp, #-56] // 4-byte Folded Spill Delay Slot 3
; AIE2P-NEXT:    st p7, [sp, #-52] // 4-byte Folded Spill Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
; AIE2P-NEXT:  // %bb.1:
; AIE2P-NEXT:    movs p6, p0; mov p7, p1
; AIE2P-NEXT:  .LBB2_2: // %for.body
; AIE2P-NEXT:    // =>This Inner Loop Header: Depth=1
; AIE2P-NEXT:    nopa ; nopb ; jl #memcpy
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    movxm r0, #4096 // Delay Slot 2
; AIE2P-NEXT:    movs p1, p6; mov p2, p7 // Delay Slot 1
; AIE2P-NEXT:    nopa ; nopb ; nops ; add r8, r8, #-1; nopm ; nopv
; AIE2P-NEXT:    jnz r8, #.LBB2_2
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    nop // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
; AIE2P-NEXT:  .LBB2_3: // %for.cond.cleanup
; AIE2P-NEXT:    lda lr, [sp, #-64]; nopb ; nopxm // 4-byte Folded Reload
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    lda p7, [sp, #-52] // 4-byte Folded Reload
; AIE2P-NEXT:    lda p6, [sp, #-56] // 4-byte Folded Reload
; AIE2P-NEXT:    lda r8, [sp, #-60] // 4-byte Folded Reload
; AIE2P-NEXT:    ret lr
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    paddxm [sp], #-64 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
entry:
  %cmp2 = icmp sgt i32 %n, 0
  br i1 %cmp2, label %for.body, label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %for.body, %entry
  ret void

for.body:                                         ; preds = %entry, %for.body
  %i.03 = phi i32 [ %inc, %for.body ], [ 0, %entry ]
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 4 dereferenceable(4096) %a, ptr noundef nonnull align 4 dereferenceable(4096) %b, i32 4096, i1 false), !tbaa.struct !2
  %inc = add nuw nsw i32 %i.03, 1
  %exitcond.not = icmp eq i32 %inc, %n
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

declare void @llvm.memcpy.p0.p0.i32(ptr noalias nocapture writeonly, ptr noalias nocapture readonly, i32, i1 immarg)

define void @__addsf3_lowered_to_call(ptr %a) {
; AIE2-LABEL: __addsf3_lowered_to_call:
; AIE2:       // %bb.0: // %entry
; AIE2-NEXT:    paddb [sp], #128; nopa ; nops ; nopxm ; nopv
; AIE2-NEXT:    st r21, [sp, #-40] // 4-byte Folded Spill
; AIE2-NEXT:    st r19, [sp, #-48] // 4-byte Folded Spill
; AIE2-NEXT:    st r20, [sp, #-44] // 4-byte Folded Spill
; AIE2-NEXT:    st r17, [sp, #-56] // 4-byte Folded Spill
; AIE2-NEXT:    st r18, [sp, #-52] // 4-byte Folded Spill
; AIE2-NEXT:    mova r16, #0; st r16, [sp, #-60] // 4-byte Folded Spill
; AIE2-NEXT:    mov r29, r16
; AIE2-NEXT:    st p6, [sp, #-32]; vinsert.32 x0, x0, r29, r16 // 4-byte Folded Spill
; AIE2-NEXT:    st lr, [sp, #-64]; vmov bmh0, x0 // 4-byte Folded Spill
; AIE2-NEXT:    st r22, [sp, #-36]; movxm r18, #16256 // 4-byte Folded Spill
; AIE2-NEXT:    mova r19, #16; vst amhl0, [sp, #-128]; movx r21, #1; mov p6, p0 // 32-byte Folded Spill
; AIE2-NEXT:    mova r17, #0; vst amhh0, [sp, #-96]; movx r20, #28; mov r22, r16 // 32-byte Folded Spill
; AIE2-NEXT:  .LBB3_1: // %for.cond1.preheader
; AIE2-NEXT:    // =>This Inner Loop Header: Depth=1
; AIE2-NEXT:    nopb ; nopa ; nops ; jl #__mulsf3; nopv
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    nop // Delay Slot 2
; AIE2-NEXT:    lshl r1, r18, r19; mov r2, r16 // Delay Slot 1
; AIE2-NEXT:    nopb ; vlda amhl1, [sp, #-128]; nops ; nopxm ; nopv // 32-byte Folded Reload
; AIE2-NEXT:    vlda amhh1, [sp, #-96] // 32-byte Folded Reload
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    mov r29, r22
; AIE2-NEXT:    vinsert.32 x0, x0, r29, r0
; AIE2-NEXT:    vmov bmh0, x0; vadd.f bmh1, bmh0, bmh1, r20
; AIE2-NEXT:    nop
; AIE2-NEXT:    xor r0, r17, r21
; AIE2-NEXT:    st.s16 r18, [p6, #0]; jnz r0, #.LBB3_1
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    vconv.bf16.fp32 wl2, bmh1 // Delay Slot 3
; AIE2-NEXT:    nop // Delay Slot 2
; AIE2-NEXT:    mova r17, #1; vextract.s16 r18, x2, r16 // Delay Slot 1
; AIE2-NEXT:  // %bb.2: // %for.cond.cleanup
; AIE2-NEXT:    nop
; AIE2-NEXT:    lda p6, [sp, #-32] // 4-byte Folded Reload
; AIE2-NEXT:    lda r22, [sp, #-36] // 4-byte Folded Reload
; AIE2-NEXT:    lda lr, [sp, #-64] // 4-byte Folded Reload
; AIE2-NEXT:    lda r21, [sp, #-40] // 4-byte Folded Reload
; AIE2-NEXT:    lda r20, [sp, #-44] // 4-byte Folded Reload
; AIE2-NEXT:    lda r19, [sp, #-48] // 4-byte Folded Reload
; AIE2-NEXT:    lda r18, [sp, #-52] // 4-byte Folded Reload
; AIE2-NEXT:    lda r17, [sp, #-56] // 4-byte Folded Reload
; AIE2-NEXT:    lda r16, [sp, #-60] // 4-byte Folded Reload
; AIE2-NEXT:    ret lr
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    paddb [sp], #-128 // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: __addsf3_lowered_to_call:
; AIE2P:       // %bb.0: // %entry
; AIE2P-NEXT:    nopa ; nopb ; paddxm [sp], #192
; AIE2P-NEXT:    st p6, [sp, #-40] // 4-byte Folded Spill
; AIE2P-NEXT:    st r9, [sp, #-56] // 4-byte Folded Spill
; AIE2P-NEXT:    st r10, [sp, #-52] // 4-byte Folded Spill
; AIE2P-NEXT:    st r11, [sp, #-48]; vmov bmlh0, x1 // 4-byte Folded Spill
; AIE2P-NEXT:    mova r8, #0; st r8, [sp, #-60]; mov p6, p0 // 4-byte Folded Spill
; AIE2P-NEXT:    st r12, [sp, #-44]; vinsert.32 x0, x1, #0, r8 // 4-byte Folded Spill
; AIE2P-NEXT:    st lr, [sp, #-64]; vmov bmll0, x0 // 4-byte Folded Spill
; AIE2P-NEXT:    vst bmlh0, [sp, #-128]; movxm r10, #16256 // 64-byte Folded Spill
; AIE2P-NEXT:    mova r12, #60; vst bmll0, [sp, #-192]; movx r11, #16; mov r9, #1 // 64-byte Folded Spill
; AIE2P-NEXT:  .LBB3_1: // %for.cond1.preheader
; AIE2P-NEXT:    // =>This Inner Loop Header: Depth=1
; AIE2P-NEXT:    nopa ; nopb ; nops ; jl #__mulsf3; nopv
; AIE2P-NEXT:    nopx // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    nop // Delay Slot 2
; AIE2P-NEXT:    mova r2, #0; lshl r1, r10, r11 // Delay Slot 1
; AIE2P-NEXT:    vlda bmll1, [sp, #-192]; nopb ; nopx // 64-byte Folded Reload
; AIE2P-NEXT:    vlda bmlh1, [sp, #-128] // 64-byte Folded Reload
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    vmov bmlh2, x5
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    vinsert.32 x4, x1, #0, r0; vadd.f dm3, dm2, dm1, r12
; AIE2P-NEXT:    vmov bmll2, x4
; AIE2P-NEXT:    xor r0, r8, r9
; AIE2P-NEXT:    st.s16 r10, [p6, #0]; jnz r0, #.LBB3_1
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    vconv.bf16.fp32 wl6, bmll3 // Delay Slot 3
; AIE2P-NEXT:    nop // Delay Slot 2
; AIE2P-NEXT:    mova r8, #1; vextract.16 r10, x6, #0, vaddsign1 // Delay Slot 1
; AIE2P-NEXT:  // %bb.2: // %for.cond.cleanup
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    lda lr, [sp, #-64] // 4-byte Folded Reload
; AIE2P-NEXT:    lda p6, [sp, #-40] // 4-byte Folded Reload
; AIE2P-NEXT:    lda r12, [sp, #-44] // 4-byte Folded Reload
; AIE2P-NEXT:    lda r11, [sp, #-48] // 4-byte Folded Reload
; AIE2P-NEXT:    lda r10, [sp, #-52] // 4-byte Folded Reload
; AIE2P-NEXT:    lda r9, [sp, #-56] // 4-byte Folded Reload
; AIE2P-NEXT:    lda r8, [sp, #-60] // 4-byte Folded Reload
; AIE2P-NEXT:    ret lr
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    paddxm [sp], #-192 // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
entry:
  br label %for.cond1.preheader

for.cond1.preheader:                              ; preds = %for.cond1.preheader, %entry
  %0 = phi bfloat [ 0xR3F80, %entry ], [ %conv14, %for.cond1.preheader ]
  %exitcond39.not = phi i1 [ false, %entry ], [ true, %for.cond1.preheader ]
  %ext = fpext bfloat %0 to float
  %1 = tail call float @llvm.fmuladd.f32(float %ext, float 0.000000e+00, float 0.000000e+00)
  %conv14 = fptrunc float %1 to bfloat
  store bfloat %0, ptr %a, align 2
  br i1 %exitcond39.not, label %for.cond.cleanup, label %for.cond1.preheader

for.cond.cleanup:                                 ; preds = %for.cond1.preheader
  ret void
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare float @llvm.fmuladd.f32(float, float, float)

!2 = !{i64 0, i64 4096, !3}
!3 = !{!4, !4, i64 0}
!4 = !{!"omnipotent char", !5, i64 0}
!5 = !{!"Simple C++ TBAA"}
