; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2023-2026 Advanced Micro Devices, Inc. or its affiliates

; RUN: llc -O2 -mtriple=aie2 --issue-limit=1 --enable-aie-zero-overhead-loops=false \
; RUN:    --aie-force-hl-gen=true %s -o - | FileCheck %s --check-prefix=AIE2
; RUN: llc -O2 -mtriple=aie2p --issue-limit=1 --enable-aie-zero-overhead-loops=false \
; RUN:    --aie-force-hl-gen=true %s -o - | FileCheck %s --check-prefix=AIE2P
; RUN: llc -O2 -mtriple=aie2ps --issue-limit=1 --enable-aie-zero-overhead-loops=false \
; RUN:    --aie-force-hl-gen=true %s -o - | FileCheck %s --check-prefix=AIE2PS

; Check that we recognize the two level nested loops as hardware loop candidates.
; In the LLVM IR input, the loop guards have been removed to allow for a simpler
; branch structure. It is guaranteed that %size and %size2 are greater than 0.
; In both loops, the trip count is decremented by one to obtain the backedge-taken
; count

define void @nested(ptr nocapture %out, ptr nocapture readonly %in, i32 noundef %size, i32 noundef %size2) {
; AIE2-LABEL: nested:
; AIE2:       // %bb.0: // %for.cond3.preheader.lr.ph
; AIE2-NEXT:    nopb ; mova r3, #0; nops ; nopxm ; nopv
; AIE2-NEXT:    mova r4, #2; nopx
; AIE2-NEXT:    movxm p2, #.LBB0_2
; AIE2-NEXT:    lda r2, [p0, #0]
; AIE2-NEXT:  .LBB0_1: // %for.cond3.preheader
; AIE2-NEXT:    // =>This Loop Header: Depth=1
; AIE2-NEXT:    // Child Loop BB0_2 Depth 2
; AIE2-NEXT:    nopa ; lshl r5, r3, r4; nopm
; AIE2-NEXT:    mov dj0, r5
; AIE2-NEXT:    lda p3, [p1, dj0]
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    mova r6, #0
; AIE2-NEXT:    add.nc r5, r1, #-1
; AIE2-NEXT:  .LBB0_2: // %for.body6
; AIE2-NEXT:    // Parent Loop BB0_1 Depth=1
; AIE2-NEXT:    // => This Inner Loop Header: Depth=2
; AIE2-NEXT:    nopa ; lshl r7, r6, r4; nopm
; AIE2-NEXT:    mov dj0, r7
; AIE2-NEXT:    lda r7, [p3, dj0]
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    jnzd r5, r5, p2
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    add r6, r6, #1 // Delay Slot 3
; AIE2-NEXT:    add r2, r2, r7 // Delay Slot 2
; AIE2-NEXT:    st r2, [p0, #0] // Delay Slot 1
; AIE2-NEXT:  // %bb.3: // %for.cond3.for.cond.cleanup5_crit_edge
; AIE2-NEXT:    // in Loop: Header=BB0_1 Depth=1
; AIE2-NEXT:    add r3, r3, #1
; AIE2-NEXT:    eq r5, r0, r3
; AIE2-NEXT:    jz r5, #.LBB0_1
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    nop // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
; AIE2-NEXT:  // %bb.4: // %for.cond.cleanup
; AIE2-NEXT:    ret lr
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    nop // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: nested:
; AIE2P:       // %bb.0: // %for.cond3.preheader.lr.ph
; AIE2P-NEXT:    mova r3, #0; nopb ; nops ; nopxm ; nopv
; AIE2P-NEXT:    mova r4, #2; nopx
; AIE2P-NEXT:    movxm p2, #.LBB0_2
; AIE2P-NEXT:    lda r2, [p0, #0]
; AIE2P-NEXT:  .LBB0_1: // %for.cond3.preheader
; AIE2P-NEXT:    // =>This Loop Header: Depth=1
; AIE2P-NEXT:    // Child Loop BB0_2 Depth 2
; AIE2P-NEXT:    nopa ; lshl r5, r3, r4; nopm
; AIE2P-NEXT:    mov dj0, r5
; AIE2P-NEXT:    lda p3, [p1, dj0]
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    mova r6, #0
; AIE2P-NEXT:    add.nc r5, r1, #-1
; AIE2P-NEXT:  .LBB0_2: // %for.body6
; AIE2P-NEXT:    // Parent Loop BB0_1 Depth=1
; AIE2P-NEXT:    // => This Inner Loop Header: Depth=2
; AIE2P-NEXT:    nopa ; lshl r7, r6, r4; nopm
; AIE2P-NEXT:    mov dj0, r7
; AIE2P-NEXT:    lda r7, [p3, dj0]
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    jnzd r5, r5, p2
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    add r6, r6, #1 // Delay Slot 3
; AIE2P-NEXT:    add r2, r2, r7 // Delay Slot 2
; AIE2P-NEXT:    st r2, [p0, #0] // Delay Slot 1
; AIE2P-NEXT:  // %bb.3: // %for.cond3.for.cond.cleanup5_crit_edge
; AIE2P-NEXT:    // in Loop: Header=BB0_1 Depth=1
; AIE2P-NEXT:    add r3, r3, #1
; AIE2P-NEXT:    eq r5, r0, r3
; AIE2P-NEXT:    jz r5, #.LBB0_1
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    nop // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
; AIE2P-NEXT:  // %bb.4: // %for.cond.cleanup
; AIE2P-NEXT:    ret lr
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    nop // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
;
; AIE2PS-LABEL: nested:
; AIE2PS:       // %bb.0: // %for.cond3.preheader.lr.ph
; AIE2PS-NEXT:    mova r4, #0; nopb ; nops ; nopxm ; nopv
; AIE2PS-NEXT:    mova r6, #2; nopx
; AIE2PS-NEXT:    movxm p2, #.LBB0_2
; AIE2PS-NEXT:    lda r2, [p0, #0]
; AIE2PS-NEXT:  .LBB0_1: // %for.cond3.preheader
; AIE2PS-NEXT:    // =>This Loop Header: Depth=1
; AIE2PS-NEXT:    // Child Loop BB0_2 Depth 2
; AIE2PS-NEXT:    nopa ; lshl r16, r4, r6; nopm
; AIE2PS-NEXT:    mov dj0, r16
; AIE2PS-NEXT:    lda p3, [p1, dj0]
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    addm.nc r3, r1, #-1
; AIE2PS-NEXT:    mova r16, #0
; AIE2PS-NEXT:  .LBB0_2: // %for.body6
; AIE2PS-NEXT:    // Parent Loop BB0_1 Depth=1
; AIE2PS-NEXT:    // => This Inner Loop Header: Depth=2
; AIE2PS-NEXT:    nopa ; lshl r18, r16, r6; nopm
; AIE2PS-NEXT:    mov dj0, r18
; AIE2PS-NEXT:    lda r18, [p3, dj0]
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    jnzd r3, r3, p2
; AIE2PS-NEXT:    nop // Delay Slot 5
; AIE2PS-NEXT:    nop // Delay Slot 4
; AIE2PS-NEXT:    add r16, r16, #1 // Delay Slot 3
; AIE2PS-NEXT:    add r2, r2, r18 // Delay Slot 2
; AIE2PS-NEXT:    st r2, [p0, #0] // Delay Slot 1
; AIE2PS-NEXT:  // %bb.3: // %for.cond3.for.cond.cleanup5_crit_edge
; AIE2PS-NEXT:    // in Loop: Header=BB0_1 Depth=1
; AIE2PS-NEXT:    add r4, r4, #1
; AIE2PS-NEXT:    eq r16, r0, r4
; AIE2PS-NEXT:    jz r16, #.LBB0_1
; AIE2PS-NEXT:    nop // Delay Slot 5
; AIE2PS-NEXT:    nop // Delay Slot 4
; AIE2PS-NEXT:    nop // Delay Slot 3
; AIE2PS-NEXT:    nop // Delay Slot 2
; AIE2PS-NEXT:    nop // Delay Slot 1
; AIE2PS-NEXT:  // %bb.4: // %for.cond.cleanup
; AIE2PS-NEXT:    ret lr
; AIE2PS-NEXT:    nop // Delay Slot 5
; AIE2PS-NEXT:    nop // Delay Slot 4
; AIE2PS-NEXT:    nop // Delay Slot 3
; AIE2PS-NEXT:    nop // Delay Slot 2
; AIE2PS-NEXT:    nop // Delay Slot 1
for.cond3.preheader.lr.ph:
  %out.promoted22 = load i32, ptr %out, align 4
  br label %for.cond3.preheader

for.cond3.preheader:
  %out.promoted23 = phi i32 [ %out.promoted22, %for.cond3.preheader.lr.ph ], [ %add, %for.cond3.for.cond.cleanup5_crit_edge ]
  %i.021 = phi i32 [ 0, %for.cond3.preheader.lr.ph ], [ %inc9, %for.cond3.for.cond.cleanup5_crit_edge ]
  %0 = trunc i32 %i.021 to i20
  %arrayidx = getelementptr inbounds ptr, ptr %in, i20 %0
  %1 = load ptr, ptr %arrayidx, align 4
  br label %for.body6

for.cond.cleanup:
  ret void

for.cond3.for.cond.cleanup5_crit_edge:
  %inc9 = add nuw nsw i32 %i.021, 1
  %exitcond24.not = icmp eq i32 %inc9, %size
  br i1 %exitcond24.not, label %for.cond.cleanup, label %for.cond3.preheader

for.body6:
  %add19 = phi i32 [ %out.promoted23, %for.cond3.preheader ], [ %add, %for.body6 ]
  %j.018 = phi i32 [ 0, %for.cond3.preheader ], [ %inc, %for.body6 ]
  %2 = trunc i32 %j.018 to i20
  %arrayidx7 = getelementptr inbounds i32, ptr %1, i20 %2
  %3 = load i32, ptr %arrayidx7, align 4
  %add = add nsw i32 %add19, %3
  store i32 %add, ptr %out, align 4
  %inc = add nuw nsw i32 %j.018, 1
  %exitcond.not = icmp eq i32 %inc, %size2
  br i1 %exitcond.not, label %for.cond3.for.cond.cleanup5_crit_edge, label %for.body6
}
