; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2023-2025 Advanced Micro Devices, Inc. or its affiliates

; RUN: llc -O2 -mtriple=aie2 --issue-limit=1 --enable-aie-zero-overhead-loops=false \
; RUN:    --aie-force-hl-gen=true %s -o - | FileCheck %s --check-prefix=AIE2
; RUN: llc -O2 -mtriple=aie2p --issue-limit=1 --enable-aie-zero-overhead-loops=false \
; RUN:    --aie-force-hl-gen=true %s -o - | FileCheck %s --check-prefix=AIE2P

define void @sibling(ptr nocapture %out, ptr nocapture readonly %in, i32 noundef %size, i32 noundef %size2) {
; AIE2-LABEL: sibling:
; AIE2:       // %bb.0: // %for.body.lr.ph
; AIE2-NEXT:    nopa ; nopb ; nopx ; add.nc r0, r0, #-1
; AIE2-NEXT:    movxm p2, #.LBB0_1
; AIE2-NEXT:    mova r2, #0; movx r5, #0; mov r4, #2
; AIE2-NEXT:    lda r3, [p0, #0]
; AIE2-NEXT:  .LBB0_1: // %for.body
; AIE2-NEXT:    // =>This Inner Loop Header: Depth=1
; AIE2-NEXT:    nopa ; nopb ; lshl r6, r5, r4; nopm ; nops
; AIE2-NEXT:    mov dj0, r6
; AIE2-NEXT:    lda r6, [p1, dj0]
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    jnzd r0, r0, p2
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    add r5, r5, #1 // Delay Slot 3
; AIE2-NEXT:    add r3, r3, r6 // Delay Slot 2
; AIE2-NEXT:    st r3, [p0, #0] // Delay Slot 1
; AIE2-NEXT:  // %bb.2: // %for.body6.lr.ph
; AIE2-NEXT:    add.nc r1, r1, #-1
; AIE2-NEXT:    mova r3, #2
; AIE2-NEXT:    movxm p2, #.LBB0_3
; AIE2-NEXT:    lda r0, [p0, #0]
; AIE2-NEXT:  .LBB0_3: // %for.body6
; AIE2-NEXT:    // =>This Inner Loop Header: Depth=1
; AIE2-NEXT:    nopb ; nopa ; nops ; lshl r4, r2, r3; nopm ; nopv
; AIE2-NEXT:    nopa ; mov dj0, r4
; AIE2-NEXT:    lda r4, [p1, dj0]
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    jnzd r1, r1, p2
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    add r2, r2, #1 // Delay Slot 3
; AIE2-NEXT:    add r0, r0, r4 // Delay Slot 2
; AIE2-NEXT:    st r0, [p0, #0] // Delay Slot 1
; AIE2-NEXT:  // %bb.4: // %for.cond.cleanup5
; AIE2-NEXT:    ret lr
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    nop // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: sibling:
; AIE2P:       // %bb.0: // %for.body.lr.ph
; AIE2P-NEXT:    nopa ; nopb ; nopx ; add.nc r0, r0, #-1
; AIE2P-NEXT:    movxm p2, #.LBB0_1
; AIE2P-NEXT:    mova r2, #0; movx r5, #0; mov r4, #2
; AIE2P-NEXT:    lda r3, [p0, #0]
; AIE2P-NEXT:  .LBB0_1: // %for.body
; AIE2P-NEXT:    // =>This Inner Loop Header: Depth=1
; AIE2P-NEXT:    nopa ; nopb ; lshl r6, r5, r4; nopm ; nops
; AIE2P-NEXT:    mov dj0, r6
; AIE2P-NEXT:    lda r6, [p1, dj0]
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    jnzd r0, r0, p2
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    add r5, r5, #1 // Delay Slot 3
; AIE2P-NEXT:    add r3, r3, r6 // Delay Slot 2
; AIE2P-NEXT:    st r3, [p0, #0] // Delay Slot 1
; AIE2P-NEXT:  // %bb.2: // %for.body6.lr.ph
; AIE2P-NEXT:    add.nc r1, r1, #-1
; AIE2P-NEXT:    mova r3, #2
; AIE2P-NEXT:    movxm p2, #.LBB0_3
; AIE2P-NEXT:    lda r0, [p0, #0]
; AIE2P-NEXT:  .LBB0_3: // %for.body6
; AIE2P-NEXT:    // =>This Inner Loop Header: Depth=1
; AIE2P-NEXT:    nopa ; nopb ; nops ; lshl r4, r2, r3; nopm ; nopv
; AIE2P-NEXT:    nopx ; mov dj0, r4
; AIE2P-NEXT:    lda r4, [p1, dj0]
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    jnzd r1, r1, p2
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    add r2, r2, #1 // Delay Slot 3
; AIE2P-NEXT:    add r0, r0, r4 // Delay Slot 2
; AIE2P-NEXT:    st r0, [p0, #0] // Delay Slot 1
; AIE2P-NEXT:  // %bb.4: // %for.cond.cleanup5
; AIE2P-NEXT:    ret lr
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    nop // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
for.body.lr.ph:
  %out.promoted = load i32, ptr %out, align 4
  br label %for.body

for.body6.lr.ph:
  %out.promoted25 = load i32, ptr %out, align 4
  br label %for.body6

for.body:
  %add22 = phi i32 [ %out.promoted, %for.body.lr.ph ], [ %add, %for.body ]
  %i.021 = phi i32 [ 0, %for.body.lr.ph ], [ %inc, %for.body ]
  %0 = trunc i32 %i.021 to i20
  %arrayidx = getelementptr inbounds i32, ptr %in, i20 %0
  %1 = load i32, ptr %arrayidx, align 4
  %add = add nsw i32 %add22, %1
  store i32 %add, ptr %out, align 4
  %inc = add nuw nsw i32 %i.021, 1
  %exitcond.not = icmp eq i32 %inc, %size
  br i1 %exitcond.not, label %for.body6.lr.ph, label %for.body

for.cond.cleanup5:
  ret void

for.body6:
  %add826 = phi i32 [ %out.promoted25, %for.body6.lr.ph ], [ %add8, %for.body6 ]
  %j.024 = phi i32 [ 0, %for.body6.lr.ph ], [ %inc10, %for.body6 ]
  %2 = trunc i32 %j.024 to i20
  %arrayidx7 = getelementptr inbounds i32, ptr %in, i20 %2
  %3 = load i32, ptr %arrayidx7, align 4
  %add8 = add nsw i32 %add826, %3
  store i32 %add8, ptr %out, align 4
  %inc10 = add nuw nsw i32 %j.024, 1
  %exitcond27.not = icmp eq i32 %inc10, %size2
  br i1 %exitcond27.not, label %for.cond.cleanup5, label %for.body6
}
