; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; This file is licensed under the Apache License v2.0 with LLVM Exceptions.
; See https://llvm.org/LICENSE.txt for license information.
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
;
; (c) Copyright 2023-2026 Advanced Micro Devices, Inc. or its affiliates

; RUN: llc -O2 -mtriple=aie2 --issue-limit=1 --enable-aie-zero-overhead-loops=false \
; RUN:    --aie-force-hl-gen=true %s -o - | FileCheck %s --check-prefix=AIE2
; RUN: llc -O2 -mtriple=aie2p --issue-limit=1 --enable-aie-zero-overhead-loops=false \
; RUN:    --aie-force-hl-gen=true %s -o - | FileCheck %s --check-prefix=AIE2P
; RUN: llc -O2 -mtriple=aie2ps --issue-limit=1 --enable-aie-zero-overhead-loops=false \
; RUN:    --aie-force-hl-gen=true %s -o - | FileCheck %s --check-prefix=AIE2PS

define void @simple(ptr nocapture %out, ptr nocapture readonly %in, i32 noundef %size) {
; AIE2-LABEL: simple:
; AIE2:       // %bb.0: // %for.body.lr.ph
; AIE2-NEXT:    mova r2, #0; nopb ; nopxm ; nops
; AIE2-NEXT:    add.nc r0, r0, #-1
; AIE2-NEXT:    mova r3, #2
; AIE2-NEXT:    movxm p2, #.LBB0_1
; AIE2-NEXT:    lda r1, [p0, #0]
; AIE2-NEXT:  .LBB0_1: // %for.body
; AIE2-NEXT:    // =>This Inner Loop Header: Depth=1
; AIE2-NEXT:    nopb ; nopa ; nops ; lshl r4, r2, r3; nopm ; nopv
; AIE2-NEXT:    nopa ; mov dj0, r4
; AIE2-NEXT:    lda r4, [p1, dj0]
; AIE2-NEXT:    nop
; AIE2-NEXT:    nop
; AIE2-NEXT:    jnzd r0, r0, p2
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    add r2, r2, #1 // Delay Slot 3
; AIE2-NEXT:    add r1, r1, r4 // Delay Slot 2
; AIE2-NEXT:    st r1, [p0, #0] // Delay Slot 1
; AIE2-NEXT:  // %bb.2: // %for.cond.cleanup
; AIE2-NEXT:    ret lr
; AIE2-NEXT:    nop // Delay Slot 5
; AIE2-NEXT:    nop // Delay Slot 4
; AIE2-NEXT:    nop // Delay Slot 3
; AIE2-NEXT:    nop // Delay Slot 2
; AIE2-NEXT:    nop // Delay Slot 1
;
; AIE2P-LABEL: simple:
; AIE2P:       // %bb.0: // %for.body.lr.ph
; AIE2P-NEXT:    mova r2, #0; nopb ; nopxm ; nops
; AIE2P-NEXT:    add.nc r0, r0, #-1
; AIE2P-NEXT:    mova r3, #2
; AIE2P-NEXT:    movxm p2, #.LBB0_1
; AIE2P-NEXT:    lda r1, [p0, #0]
; AIE2P-NEXT:  .LBB0_1: // %for.body
; AIE2P-NEXT:    // =>This Inner Loop Header: Depth=1
; AIE2P-NEXT:    nopa ; nopb ; nops ; lshl r4, r2, r3; nopm ; nopv
; AIE2P-NEXT:    nopx ; mov dj0, r4
; AIE2P-NEXT:    lda r4, [p1, dj0]
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    nop
; AIE2P-NEXT:    jnzd r0, r0, p2
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    add r2, r2, #1 // Delay Slot 3
; AIE2P-NEXT:    add r1, r1, r4 // Delay Slot 2
; AIE2P-NEXT:    st r1, [p0, #0] // Delay Slot 1
; AIE2P-NEXT:  // %bb.2: // %for.cond.cleanup
; AIE2P-NEXT:    ret lr
; AIE2P-NEXT:    nop // Delay Slot 5
; AIE2P-NEXT:    nop // Delay Slot 4
; AIE2P-NEXT:    nop // Delay Slot 3
; AIE2P-NEXT:    nop // Delay Slot 2
; AIE2P-NEXT:    nop // Delay Slot 1
;
; AIE2PS-LABEL: simple:
; AIE2PS:       // %bb.0: // %for.body.lr.ph
; AIE2PS-NEXT:    nopa ; nopb ; nopx ; addm.nc r1, r0, #-1; nops
; AIE2PS-NEXT:    mova r0, #0
; AIE2PS-NEXT:    mova r4, #2
; AIE2PS-NEXT:    movxm p2, #.LBB0_1
; AIE2PS-NEXT:    lda r2, [p0, #0]
; AIE2PS-NEXT:  .LBB0_1: // %for.body
; AIE2PS-NEXT:    // =>This Inner Loop Header: Depth=1
; AIE2PS-NEXT:    nopa ; nopb ; nops ; lshl r6, r0, r4; nopm ; nopv
; AIE2PS-NEXT:    nopx ; mov dj0, r6
; AIE2PS-NEXT:    lda r6, [p1, dj0]
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    nop
; AIE2PS-NEXT:    jnzd r1, r1, p2
; AIE2PS-NEXT:    nop // Delay Slot 5
; AIE2PS-NEXT:    nop // Delay Slot 4
; AIE2PS-NEXT:    add r0, r0, #1 // Delay Slot 3
; AIE2PS-NEXT:    add r2, r2, r6 // Delay Slot 2
; AIE2PS-NEXT:    st r2, [p0, #0] // Delay Slot 1
; AIE2PS-NEXT:  // %bb.2: // %for.cond.cleanup
; AIE2PS-NEXT:    ret lr
; AIE2PS-NEXT:    nop // Delay Slot 5
; AIE2PS-NEXT:    nop // Delay Slot 4
; AIE2PS-NEXT:    nop // Delay Slot 3
; AIE2PS-NEXT:    nop // Delay Slot 2
; AIE2PS-NEXT:    nop // Delay Slot 1
for.body.lr.ph:
  %out.promoted = load i32, ptr %out, align 4
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %for.body.lr.ph, %for.body
  %add7 = phi i32 [ %out.promoted, %for.body.lr.ph ], [ %add, %for.body ]
  %i.06 = phi i32 [ 0, %for.body.lr.ph ], [ %inc, %for.body ]
  %0 = trunc i32 %i.06 to i20
  %arrayidx = getelementptr inbounds i32, ptr %in, i20 %0
  %1 = load i32, ptr %arrayidx, align 4
  %add = add nsw i32 %add7, %1
  store i32 %add, ptr %out, align 4
  %inc = add nuw nsw i32 %i.06, 1
  %exitcond.not = icmp eq i32 %inc, %size
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}
