# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2024-2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple=aie2p -run-pass=aie-hardware-loops,reserved-reg-licm \
# RUN:   --enable-aie-hardware-loops --enable-aie-zero-overhead-loops \
# RUN:   %s -verify-machineinstrs -o - | FileCheck %s

---
name:            nested_zol_licm_aie2p
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: nested_zol_licm_aie2p
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $r0, $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $p2 = MOVXM %bb.1
  ; CHECK-NEXT:   $ls = MOVXM %bb.2
  ; CHECK-NEXT:   $le = MOVXM <mcsymbol .L_1120>
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $p2, $r0, $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $lc = ADD_NC_mv_add_ri $r1, 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.2(0x7c000000), %bb.3(0x04000000)
  ; CHECK-NEXT:   liveins: $p0, $p2, $r0, $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   PseudoLoopEnd <mcsymbol .L_1120>, %bb.2, implicit $ls, implicit $le
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.1(0x7c000000), %bb.4(0x04000000)
  ; CHECK-NEXT:   liveins: $p0, $p2, $r0, $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $r0 = PseudoJNZD $r0, $p2, implicit-def $srcarry
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   PseudoRET implicit $lr
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $p0, $r0, $r1

    $p2 = MOVXM %bb.1

  bb.1:
    successors: %bb.2(0x80000000)
    liveins: $p0, $p2, $r0, $r1

    LoopStart $r1, 0

  bb.2:
    successors: %bb.2(0x7c000000), %bb.3(0x04000000)
    liveins: $p0, $p2, $r0, $r1

    NOP
    PseudoLoopEnd <mcsymbol .L_1120>, %bb.2, implicit $ls, implicit $le

  bb.3:
    successors: %bb.1(0x7c000000), %bb.4(0x04000000)
    liveins: $p0, $p2, $r0, $r1

    $r0 = LoopDec $r0, implicit-def $srcarry
    LoopJNZ $r0, $p2, implicit-def $srcarry

  bb.4:
    PseudoRET implicit $lr

...
